### PR TITLE
Issue/14315 update about the app

### LINKED ISSUE #14315: Jetpack App (Basics): Update About the App
Parent #14293

App Settings: About the App Section
- [ ] Update WordPress for Android
- [ ] Update Open source licenses

|Wordpress for |open source
|---|---
|light|dark

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #14315

This PR 
- [x] Updates WordPress for Android
- [x] Updates Open source licenses - N/A (Internal ref: `P1617865067066400-slack-C0180B5PRJ4`)

| App Settings | About the app | Licenses |
| ------------- |  ------------- |  --------- |
|  device-2021-04-08-121643 |  device-2021-04-08-121654  |  licenses  |

Note: App version not updated on the About screen, considering it will be covered under `Platform9` tasks.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — CHANGES_REQUESTED** [review]
@ashiagr - Looks like we need to make a new `licenses.html` for Jetpack src. Making the change directly to assets/licenses.html overwrites the values for WordPress.

**Comment by zwarm** [comment]
@osullivanchris - Should we be changing the icon from Wordpress to Jetpack in the **About the App** view? And if so, please add it to your ever growing list of design todos. Thanks.  FYI: @ashiagr - We can create a new issue to change the icon if it is decided to do so.

**Comment by ashiagr** [comment]
Thanks @zwarm!

> @ashiagr - Looks like we need to make a new `licenses.html` for Jetpack src. Making the change directly to assets/licenses.html overwrites the values for WordPress.

Oh yes, added `licenses.html` for jetpack in 79942e0.
Also added a separate task in the parent issue for replacing the app icon. I'll replace it once I get the icon.

**Comment by osullivanchris** [comment]
> @osullivanchris - Should we be changing the icon from Wordpress to Jetpack in the About the App view? And if so, please add it to your ever growing list of design todos.

Yeah I think so @zwarm ! Do you know what assets are needed for that location?

**Review by zwarm — APPROVED** [review]
Thanks for the changes @ashiagr . It works like a charm. 👍

**Comment by zwarm** [comment]
> Do you know what assets are needed for that location?

@osullivanchris  We need an svg vector asset. [This is the WP one ](https://github.com/wordpress-mobile/WordPress-Android/blob/beea01d3f60c768ffe757bb2da239648b3395b45/WordPress/src/main/res/drawable/ic_my_sites_white_24dp.xml#L1)

**Pull request merged**
