### PR TITLE
[Gutenberg] Remove code associated to Story block

### PR DESCRIPTION
**Pull request by fluiddot**
Related PRs:
* https://github.com/WordPress/gutenberg/pull/59547
* https://github.com/Automattic/jetpack/pull/36151
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/6691
* https://github.com/wordpress-mobile/WordPress-iOS/pull/22758

This PR is a follow-up of https://github.com/wordpress-mobile/WordPress-Android/pull/20005 and continues the effort of https://github.com/wordpress-mobile/WordPress-Android/pull/20016 to remove the code associated with Story post/block.

-----

## To Test:

Since the Story block was disabled some time ago, we don't expect that these changes will have an impact on the editor. Nevertheless, we could focus on smoke testing the editor.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing.

3. What automated tests I added (or what prevented me from doing so)

    - None.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by SiobhyB — APPROVED** [review]
LGTM! I smoke tested the editor and confirmed this works well with the changes from the linked PRs checked out. Thanks again @fluiddot! 🙌

**Comment by fluiddot** [comment]
I've added the `Do Not Merge` label to prevent merging the PR until version 24.4 code freeze is finalized.

**Review by jarvislin — APPROVED** [review]
LGTM! Thank you for removing those code related to Stories.

**Pull request merged**
