### PR TITLE
Enable Search for Self-Hosted Sites

### LINKED ISSUE #12058: Add the ability to search the post list for self-hosted site
### Expected behavior

I expected that any kind of site I added to the app would give me the option to search the post or page list.

### Actual behavior

Only WordPress.com/Jetpack sites have the option for this feature. 

### Steps to reproduce the behavior

1. Go to My Site and select a WordPress.com site.
2. Go to Blog Post List
3. You'll see the search icon in the top menu.
4. Go back to My Site and select a self-hosted site. 
5. Go to Blog Post List
6. The icons doesn't display and there is no way to search through posts.

##### Tested on Samsun Tab A, Android 9, WPAndroid 14.9-rc-1

It does look like this was implemented purposefully in #10023, but it was requested by a user with a self-hosted site in 3002439-zen and kind of caught me off guard since I didn't realize this behaviour would be different. I wasn't able to find another report of this anywhere that wasn't related to the old PR.

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #12058 
Prerequisite [WordPress-FluxC-Android #1646](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1646)

Description
-----
This feature enables search for self-hosted sites, something that was previously only available for WordPress.com/Jetpack sites. See issue above for more info.

In general the solution is split into two parts:
1. Make the `search icon` available for when the user navigates to a self-hosted site, just as it is available for non self-hosted sites.
2. Add the user's `search query` to the XML RPC descriptor that is responsible to later make an API request for the self-hosted site. Note that with the `develop` version of this repo the `search query` argument is not available since a new version of **Android FluxC** is required (see `To test` section below).

So, the above work is closely related to the [[Feature] Add Search Filter for XML RPC Requests #1646](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1646) PR, which needs to be merge first.

Blog Posts for Self-Hosted Site (Before)
-----

Blog Posts for Self-Hosted Site (After)
-----

Test:
-----
1. Build the `WordPress` app with a `fluxcVersion` of `e32d20633e68ca1fba1726b75463aa7219ca88f0` (update that within the project's parent `build.gradle` file)
1. Sign in to the app and add a self-hosted site
1. Navigate to `Blog Posts`
1. Verify that the `Search Icon` is available on the top right
1. Click on the `Search Icon` and verify the search functionality works as expected and in general works as it used to work for non self-hosted site
1. The above means that search is enabled for self-hosted sites

While testing note that search in general, for both for self-hosted and non self-hosted sites has a configuration change related bug, see #12561. However, it is out of the scope of this task to fix this bug, but it will be considered as part of another task, later on in the future.

PR submission checklist:
-----
- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
I am not sure about the two items in the `PR Submission Checklist` so please guide me to be able to ✅ them as well:
- I have considered adding accessibility improvements for my changes.
- I have considered if this change warrants user-facing release notes and have added them to RELEASE-NOTES.txt if necessary.

Also, another ✅ that I would have liked to check are adding UI tests where possible, much I am not sure what is the process for adding those.

**Comment by ParaskP7** [comment]
`lint` and `test` are failing on for **CircleCI** due to compilation errors. This is expected, since this PR is based on a future version of `FluxC`. As such, only when a commit with the newest version of `FluxC` will be added to this PR (or the `develop` gets it), will **CircleCI** pass these checks.

PS: Locally, both `lint` and `test` are running fine.

**Comment by ParaskP7** [comment]
> Thanks for the changes @ParaskP7! The apps works as expected, great job!
> 
> I have a couple of questions/suggestions.
> 
> 1. The step 3 is mentioning "Site Pages". I'm wondering if we need to test site pages, since we modified just Post List's VMs. Wdyt?
> 2. I agree that a SiteModel can theoretically have "UNKNOWN" origin - at least the "enum" supports it. However, afaik we don't support that type anywhere else in the app. The app needs to communicate with either WPComRest or XML-RPC. If it doesn't know the type it can't communicate with the site at all. That's the main reason why we never found a need to introduce "isAccessedViaXmlRpc" -> `!isAccessedViaWPComRest == isAccessedViaXmlRpc` (btw there is a typo in the code "View" vs "Via"). I'm wondering if we really want to introduce it now. Wdyt?
Many thanks for reviewing my PR @malinajirka and verifying its functionality! 🌟

1. You are right, this change is only about `Blog Posts`, I wonder why I added a step to verify `Site Pages` as well. I am going to update the description and remove it. It is totally misleading. I am guessing since I was constantly testing both to verify they work the same, I posted the same testing instructions. 😶
2. I wan't aware about the `UNKNOWN` indeed, thanks for clarifying that for me. Also, thanks for noting the `View` typo as well, will update it with a commit. So based on what you say, and if I understand correctly, then overall the `isSearchAvailable` LiveData value is not needed anymore and can be removed from the `PostListMainViewModel`. Then, every site with have search available by default. Is that right?

**Comment by malinajirka** [comment]
> You are right, this change is only about Blog Posts, I wonder why I added a step to verify Site Pages as well. I am going to update the description and remove it. It is totally misleading. I am guessing since I was constantly testing both to verify they work the same, I posted the same testing instructions. 😶

No worries ;)!

> I wan't aware about the UNKNOWN indeed, thanks for clarifying that for me. Also, thanks for noting the View typo as well, will update it with a commit. So based on what you say, and if I understand correctly, then overall the isSearchAvailable LiveData value is not needed anymore and can be removed from the PostListMainViewModel. Then, every site with have search available by default. Is that right?

Yep, sounds good to me ;).

**Comment by ParaskP7** [comment]
@malinajirka all your suggestions have been now added in this PR. Please let me know if everything looks as expected!

**Pull request merged**
