### PR TITLE
Login Rework: visual touches for the epilogue screen

### PR DESCRIPTION
**Pull request by hypest**
**Note: #6341 needs to be merged first.**

This PR is about the visual touches for the epilogue screen.

Highlights:
* The bottom buttons container changes colour depending on the list view "height" above it. The "white" button also adapts and becomes grey in the tall list case.

Screenshots:

| Before |  After |
| --- | --- |
| login-epilogue-before  |  login-epilogue-after |

To test:
* With the app data cleaned, launch the app and hit the "Log in" button
* Log in to a WordPress.com account until the epilogue screen comes up
* Assess the design of the epilogue screen

### CODE REVIEW

**Comment by folletto** [comment]
Tested on Nexus 5:

| short | long (loading) | long |
| - | - | - |
|screenshot_20170719-162601|screenshot_20170719-162719|screenshot_20170719-162743|

Two things:

1. One is that the site avatar should be on transparent background, not red. Not sure if it's an issue of this specific PR or on the component used tho, might be out of scope on this PR.
2. Let's follow #6196 and drop the grey variation `WordPress.Button.Grey` — fwiw in general we should keep the names semantic, not referencing colors. :)

---

Not a code review, but given the other discussion I did a spot check. The PR uses:

* `WordPress.Button`
* `WordPress.Button.Primary`
* `WordPress.Button.Secondary`
* `WordPress.Button.Grey`

What's the difference between `Secondary` and `Grey`? Or well, what's `Secondary` exactly?
In theory (but I might be missing something) we should have only:

* `WordPress.Button`
* `WordPress.Button.Primary`

**Comment by aerych** [comment]
Documenting here what we chatted about. 

Currently, if a user is logged in with a self-hosted site then logs in to wpcom, the epilogue will show all the blogs in the app, including the self-hosted ones.  Ideally the epilogue should only show the blogs relevant to what was just logged into.  So if wpcom, it would only be the wpcom blogs belonging to the account signed into.  If self-hosted it would only show the user's self-hosted blog (or blogs if multi-site).

**Comment by hypest** [comment]
Hey @folletto !

> the site avatar should be on transparent background, not red.

Oh no, red was the color I used for a visual test but unfortunately it survived :(. Fixed with aaef96a.

> Let's follow #6196 and drop the grey variation WordPress.Button.Grey — fwiw in general we should keep the names semantic, not referencing colors. :)

For sure! In this case, since the design spec had a grey-er variant for when on a white background I had to use _a_ name. `Button.Secondary.WhiteBack`, `Button.Secondary2` or similar weren't looking nice so, I resorted to `.Grey` to move on and create the PR

> In theory (but I might be missing something) we should have only:
>
> WordPress.Button
> WordPress.Button.Primary

I understand that that means dropping the grey-er variant of the button so, did that with d9fc1a8.
Here's a before/after of the change:

| With Grey button |  With Secondary button |
| --- | --- |
| login-epilogue-grey-button  |  login-epilogue-white-button |

Let me know what you think! Thanks!

**Comment by hypest** [comment]
Hey @aerych ,

> Ideally the epilogue should only show the blogs relevant to what was just logged into.

Cool, I will work on that. I might break it off into a separate PR if it turns out too big to keep in this one. Thanks!

**Comment by folletto** [comment]
> I understand that that means dropping the grey-er variant

:y: looks good. :)

To confirm: yes, ideally we should have only `WordPress.Button` and `WordPress.Button.Primary`, if there are more variants, let's review them as we might be able to streamline the work :)

**Comment by hypest** [comment]
Hey @aerych , FYI, I've added a site filtering solution here (3619da7) by manually diffing the sites list prior and after logging in. Unfortunately, FluxC doesn't provide a direct way to do that currently so, I think we can leave with the manual solution for now.

**Comment by hypest** [comment]
I've added the `[Status] Not Ready for Review` label since the gravatar/name/usename are not properly loaded when in logging in a selfhosted site.

**Comment by hypest** [comment]
There is currently no support in FluxC for retrieving user's profile data (gravatar, username, name) when logging in a selfhosted site. I opened a ticket about this to track it https://github.com/wordpress-mobile/WordPress-Android/issues/6379. In the meantime, I will completely hide the "Logged in as " section of the view. /cc @aerych , @folletto .

**Comment by hypest** [comment]
I addressed (with 46f645e) an issue @aerych found where quickly dismissing the epilogue screen left the app not fully setup when logging in a wpcom account.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
