### PR TITLE
Added support for Open Sans light bold & light bold italic.

### LINKED ISSUE #2385: TypefaceCache should support semi-bold
Add support for BoldLight and BoldLightItalic to TypefaceCache. This will be needed for the upcoming "masterbar" changes.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #2385 by adding light bold & light bold italic font assets and supporting them in TypefaceCache. Here's a screenshot showing the available styles:

device-2015-03-03-133618

You can test this yourself using the layout below:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is normal"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="normal" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is light"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="normal"
        app:fontVariation="light" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is italic"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="italic"
        app:fontVariation="normal" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is light italic"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="italic"
        app:fontVariation="light" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is bold"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="bold"
        app:fontVariation="normal" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is light bold"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="bold"
        app:fontVariation="light" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is bold italic"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="bold|italic"
        app:fontVariation="normal" />

    <org.wordpress.android.widgets.WPTextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="@dimen/margin_medium"
        android:text="This is light bold italic"
        android:textColor="@color/black"
        android:textSize="@dimen/text_sz_large"
        android:textStyle="bold|italic"
        app:fontVariation="light" />
</LinearLayout>
```

### CODE REVIEW

**Comment by mnt** [comment]
Curious about the "light bold" naming, is that something android specific? Calypso styles use the following weights:

- Light
- Regular
- Semibold

We won't be using bold for anything as we the Calypso design language works its way through the app.

**Comment by nbradbury** [comment]
@mnt Nope, not Android-specific - I simply changed the file names to be more consistent with the "light" variation we use in code.

**Comment by tonyr59h** [comment]
Tested with the provided layout, lookin' good.

:shipit:

**Comment by nbradbury** [comment]
Thanks for the review @tonyr59h! If it looks good you can go ahead and merge it.

**Pull request merged**
