### PR TITLE
Add a fastlane action to create screenshot devices

### PR DESCRIPTION
**Pull request by jkmassel**
**To Test:**
_BEWARE – THIS WILL OVERWRITE YOUR EXISTING SCREENSHOT GENERATION EMULATORS_

In the root of the project, run:

```
bundle install --path vendor/bundle
bundle exec fastlane android rebuild_screenshot_devices
```

There should be no side effects – the script is designed such that:

- Any non-screenshot emulators shouldn't be affected
- Any custom hardware profiles shouldn't be affected

The line count _looks_ high, but it's mostly the emulator and device profile definitions. For a bit more info on how this all works, check out [SCREENSHOT_DEVICE_SETUP.md](https://github.com/wordpress-mobile/WordPress-Android/blob/6d0a825622fda673e328a8a5893b272eb48b47c9/fastlane/SCREENSHOT_DEVICE_SETUP.md)

### CODE REVIEW

**Comment by jkmassel** [comment]
The emulators have been adjusted to work at these sizes:
screenshot_1_1535834625080
screenshot_1_1535835378985
screenshot_1_1535836033789

**Comment by jkmassel** [comment]
I used Python for this because:

1. It's likely to be already present on dev machines
2. It doesn't require any external dependencies to be downloaded
3. It's a lot nicer than merging XML files using bash 🙃

**Comment by loremattei** [comment]
Hey Jeremy! Thank you for the update! 
I tested it and the emulators run with the right size now :-) You rock!
A weird thing I noticed: in the AVD Manager dialog, they still appear to have a standard size, but I really think this is related to Android Studio itself. 

Can I just ask you to add a few comments line in the Fastfile to describe the new action?

**Comment by jkmassel** [comment]
No problem! It's in https://github.com/wordpress-mobile/WordPress-Android/pull/8227/commits/155bcb724192ed756bd5ad48c2f8caa8eefe6afd :)

**Pull request merged**
