### PR TITLE
Login Rework: Enable the new login for all

### PR DESCRIPTION
**Pull request by hypest**
Sets the feature flag for the new login flows to `true` for all build variants.

To test:
* Build `vanilla` and run the app after cleaning all data. The new style login prologue screen should appear.

### CODE REVIEW

**Comment by aforcier** [comment]
@hypest any particular reason not to drop all the `LOGIN_WIZARD_STYLE_ACTIVE` references at this point?

**Comment by aforcier** [comment]
Nevermind, I suppose it's to keep an easy way of toggling the old flow back on for debugging.

**Comment by aforcier** [comment]
Works great @hypest - :shipit:!

**Comment by hypest** [comment]
> Nevermind, I suppose it's to keep an easy way of toggling the old flow back on for debugging.

Yeap, that's exactly the reason. We should remove the feature flag when we remove the old signin classes as well.

**Pull request merged**
