### PR TITLE
Reader search design review

### PR DESCRIPTION
**Pull request by nbradbury**
Reader search passed code review in PR #4096, now it just needs a design review before it can be merged into develop.

Needs review @jancavan

### CODE REVIEW

**Comment by maxme** [comment]
I got the following crash after a search and device rotation:

```
05-26 12:38:03.950 9938-9938/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.wordpress.android.beta, PID: 9938
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android.beta/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.SearchView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/menu_search. Make sure other views do not use the same id.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912)
    at android.app.ActivityThread.access$900(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
 Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.SearchView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/menu_search. Make sure other views do not use the same id.
    at android.view.View.onRestoreInstanceState(View.java:13645)
    at android.widget.TextView.onRestoreInstanceState(TextView.java:3771)
    at android.view.View.dispatchRestoreInstanceState(View.java:13621)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
    at android.view.View.restoreHierarchyState(View.java:13599)
    at android.app.Fragment.restoreViewState(Fragment.java:634)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:914)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
    at android.app.Activity.performCreateCommon(Activity.java:5928)
    at android.app.Activity.performCreate(Activity.java:5935)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912) 
    at android.app.ActivityThread.access$900(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5221) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
```

**Comment by maxme** [comment]
Search box styling is off in landscape:

screenshot-2016-05-26_13 14 42 454

**Comment by maxme** [comment]
Not sure how I was able to do this (I can't repro, low priority):

screenshot-2016-05-26_13 31 06 629

**Comment by nbradbury** [comment]
> Search box styling is off in landscape:

Yuck. Fixed in 57d0602.

> I got the following crash after a search and device rotation

I wasn't able to repro that, but based on the error message it should be resolved by c407f06.

**Comment by maxme** [comment]
> I wasn't able to repro that, but based on the error message it should be resolved by c407f06.

Not resolved, and it looks like a bug in the support lib: https://code.google.com/p/android/issues/detail?id=206296

From a Googler's comment:
> Fix will be release in the final 24.0.0 update.

**Comment by nbradbury** [comment]
> Not resolved, and it looks like a bug in the support lib

supportlib-kirk

**Comment by tonyr59h** [comment]
The suggestions can be "duplicated" by adding whitespace to the end.

So `android`, `android_`, `android__`, and `android___` are all separate entries (where _ is a space). `String.trim()` is your friend 😄

**Comment by nbradbury** [comment]
> The suggestions can be "duplicated" by adding whitespace to the end.

I am in shame for that one. Fixed in 304e6b5.

**Comment by jancavan** [comment]
It's working great, but I've some feedback:

- For search history, might be good to also be able to clear one item instead of just a global clear button:
screenshot-2016-06-02-14 43 30

I think this may just be a verbiage issue, but the "Clear" button is also confusing in this particular scenario. I'm not sure if I'm only clearing "alligator" or all of my search history. 

screenshot 2016-06-02 14 50 22

It does eventually tell you (through a dialog box) that you're clearing all of your history, but it's not initially obvious.

Perhaps it should say "Clear search history"?

- Would be nice for recent searches to show up when tapping the search bar (I think you mentioned this is still a WIP, but just wanted to note it down here)

- It doesn't look like the Search icon is using the right Gridicon. Let me know if you need an SVG/PNG of this. This is the correct one:

screenshot 2016-06-02 14 55 55

- "No results" should probably match the web version's styling:
 - Heading color: `grey_dark` / `#2e4453`
 - Subtext color: `grey` / `#87a6bc`

screenshot-2016-06-02-15 07 26

- Search bar text can be made smaller and lighter and should probably say "Search WordPress.com" instead of "Search _on_ WordPress.com"

screenshot-2016-06-02-15 17 19

- When there is more than a single line of text, the top/bottom padding are inconsistent. A top/bottom padding of around `16px` would be good.

screenshot-2016-06-02-15 31 04

- For the "Clear saved search" dialog box, we can update:
 - the text to say: Clear recent searches (heading), Would you like to clear your recent searches? (subtext)
 - have a division between the heading and subtext
 - no/yes button changed to blue (`blue_wordpress` / `#0087be`) instead of orange

screenshot-2016-06-02-15 41 15

/cc @nbradbury

**Comment by nbradbury** [comment]
Thanks for the design review, @jancavan!

> For search history, might be good to also be able to clear one item 

Added in aa4a6e3

> Perhaps it should say "Clear search history"?

Added in c5d2664

> Search bar text can be made smaller and lighter and should probably say "Search WordPress.com" instead of "Search on WordPress.com"

The text size and color is determined by Android itself. With some effort we can customize it, but I think it's better to stick with the defaults here. Good call on using "Search WordPress.com" - added in 99d5868

> When there is more than a single line of text, the top/bottom padding are inconsistent. A top/bottom padding of around 16px would be good.

Yuck, glad you noticed that! I think it's unlikely that users will enter such a long search query, though. What do you think about simply limiting dropdown items to a single line, like this?

single-line

> For the "Clear saved search" dialog box, we can update: the text to say: Clear recent searches (heading), Would you like to clear your recent searches? (subtext) have a division between the heading and subtext no/yes button changed to blue (blue_wordpress / #0087be) instead of orange

The dialog style is determined by Android itself and is consistent with other dialogs in the app, but I agree the text could use some work. However, the text "Would you like to clear your recent searches?" is a bit long for mobile, and goes against Google's recommendations [here](https://www.google.com/design/spec/style/writing.html#).

screen shot 2016-06-04 at 8 45 20 pm

Looking at Google's [recs for dialogs](https://www.google.com/design/spec/components/dialogs.html), I think we can drop the dialog title entirely and simply use this:

dialog

I added that in de89715. Thoughts?

**Comment by nbradbury** [comment]
> "No results" should probably match the web version's styling:

The colors are used throughout the app for similar messages, so I think they shouldn't change. 

That text copy I'm using matches what we currently have on Calypso search, but I'm happy to change it. However, I don't think it should be changed to use "We couldn't find any..." since Google recommends [avoiding the pronoun "We"](https://www.google.com/design/spec/style/writing.html#writing-language).

I did tweak it slightly and added &lt;em&gt; formatting of the query string in bf08137 - let me know if you'd prefer different copy.

device-2016-06-05-070808

**Comment by jancavan** [comment]
Thanks for working on the updates, it's looking good!

> The text size and color is determined by Android itself. With some effort we can customize it, but I think it's better to stick with the defaults here.

Gotcha. Ok, let's just keep the default styles then.

> What do you think about simply limiting dropdown items to a single line, like this?

Good call, I think this is great. When I checked the branch out, there's a space between the last letter and ellipsis. Or is the ellipses added, I think, after 30 characters including spaces?

> Looking at Google's recs for dialogs, I think we can drop the dialog title entirely and simply use this

Yup, this works. Much better than the original.

> That text copy I'm using for no results matches what we currently have on Calypso search, but I'm happy to change it. However, I don't think it should be changed to use "We couldn't find any..." since Google recommends avoiding the pronoun "We".

Ok, makes sense. I think the latest version is good.

Re https://github.com/wordpress-mobile/WordPress-Android/commit/aa4a6e3bd92b6c17b2a51897d7730fa42ecd517a, sorry I missed this the last time, but I think it's worth adding a dialog box (Would you like to clear the recent search _alligator_?) to avoid inadvertently deleting a recent search item.

Re the Search icon, I also noticed the white Search icon isn't a Gridicon - so both white and gray one:

screenshot 2016-06-07 16 01 53

screenshot 2016-06-07 16 01 58

**Comment by nbradbury** [comment]
> I think it's worth adding a dialog box (Would you like to clear the recent search alligator?) to avoid inadvertently deleting a recent search item

@jancavan I think that may be overkill, since all the user is doing is removing a query string (no other data is affected). I do agree with a confirmation when clearing all items, though.

> Re the Search icon, I also noticed the white Search icon isn't a Gridicon - so both white and gray one

Sorry - I missed that in your previous comment. Can you provide SVGs?

**Comment by jancavan** [comment]
Here's the Search icon SVG. Let me know if there's anything else you need.

https://cloudup.com/c9ffqkTBmCv

**Comment by jancavan** [comment]
Design LGTM 👍

**Comment by nbradbury** [comment]
@maxme This PR is ready to be merged now that it has passed design review, but I wasn't sure if we needed to wait until the support lib bug you mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/4122#issuecomment-222073549) is addressed?

**Comment by maxme** [comment]
> @maxme This PR is ready to be merged now that it has passed design review, but I wasn't sure if we needed to wait until the support lib bug you mentioned here is addressed?

Support library v24.0 should be out soon, we could at least wait 2 weeks (before wpandroid 5.6 freeze) before merging this.

**Comment by nbradbury** [comment]
**Update:** Support library v24.0.0 is [out](https://developer.android.com/topic/libraries/support-library/revisions.html) and apparently [fixes](https://code.google.com/p/android/issues/detail?id=206296#c12) the SearchView crash. I'll give it a test drive.

**Comment by maxme** [comment]
Support library v24.0.0 was merged, so it's time to :shipit:!

**Pull request merged**
