### PR TITLE
Issue/9739 domain contact info and registration

### LINKED ISSUE #9739: Add contact information screen for domain registration
After the user picks a domain name he should be directed to the screen with contact information form and privacy protection option.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #9739

**[Flux-C counterpart](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1245) should be merged before this PR.**

This PR adds the rest of the domain registration functionality: Contact Details + Privacy form and Domain Registration Result screens.

I spend too much time trying to make it all work with `ViewModels`, but without two-way data binding, the complexity was growing out of hand, so I had to abandon this idea for now, and remade everything with more "traditional" approach. There was some certain element of haste, so please do let me know if I missed something important.

Unfortunately, this PR in a whole is necessary for some subsequent tasks that can not wait, so the size of it is a bit out of control 😓 

To test:
1. Install the wasabi build.
2. Switch to a site on a business plan with unclaimed domain credit (let me know if you need help with this).
3. Navigate to Plugins screen, and from there to details of any plugin (like Woocommerce).
4. Tap on Install button.
5. In the dialog tap on "REGISTER DOMAIN".
6. Pick a domain (preferably .blog).
7. Tap on "CHOOSE DOMAIN" and navigate to contact form details.
8. If you had contact information stored at WordPress.com it should be prefilled.
9. All the fields apart from State and Organisation are required, and their emptiness is validated locally.
10. The validity of input fields content is validated on backend one by one (eg. if you have two fields with malformed you will have to make two registration attempts to get errors for both of them).
11. Make sure ToS link is clickable.
12. Every time you change the country States are loaded from remote (some countries, like Germany, do not have states).
13.  Try to register the domain.

PS: Follow domain testing guideline and make sure if you purchase a domain to cancel it.

I had to make a couple of small functional compromises/changes based on the original design, because of the time constraints. 

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by planarvoid** [comment]
Hey 👋 , I'm sorry you're under pressure to finish this fast 👍. I'm focusing mostly on testing the functionality in this PR review and it looks pretty great 💯 . Reviewing the code is hard because the PR is huge and I don't think (and I believe neither do you) this is the way we should write our new code. What do you think about trying to refactor this code to ViewModels right after this is merged? I'd like to help you in any way I can 👍. We could do some pair programming or I can look into it myself. 

Testing results:
* Should the `State` field be still present when we're switching between countries that do and don't have state? I don't see any visual difference between enabled and disabled state. Maybe we should hide it when the country doesn't have states? It might also make sense to have `State (optional)` as the hint since we do the same for `Organisation`. 
* NIT: The `Postal code` is prefilled correctly but when I reenter the value (for me the original value was `180 00`, I entered `18000` manually) without the necessary gap, the registration fails. Would it be possible to maybe auto-correct this? 
* After the domain purchase successfully finishes, I have to click the `Install` on the plugin site again. Is that correct? Shouldn't we maybe trigger it manually?

**Comment by khaykov** [comment]
Thanks for testing this one! You are right about the amount of code, and as we discussed, I'll refactor the contact form using ViewModel and submit a new PR :)

> Should the State field be still present when we're switching between countries that do and don't have state? I don't see any visual difference between enabled and disabled state. Maybe we should hide it when the country doesn't have states? It might also make sense to have State (optional) as the hint since we do the same for Organisation.

There is a difference between enabled and disabled state, but I guess it's too subtle - the line color changes to a bit less grey gray. Hiding the State field is a better idea 👍
 
> NIT: The Postal code is prefilled correctly but when I reenter the value (for me the original value was 180 00, I entered 18000 manually) without the necessary gap, the registration fails. Would it be possible to maybe auto-correct this?

Not sure if there is a way to do it without some 3rd party library that is aware of the postcode formats for countries we support, and can reliably detect issues with user input and suggest corrections. I might be overthinking it, but sounds pretty complicated.

> After the domain purchase successfully finishes, I have to click the Install on the plugin site again. Is that correct? Shouldn't we maybe trigger it manually?

There is another confirmation dialog for the first time plugin installation, and I think it might be confusing for a customer to see it without knowing what triggered it.

**Comment by planarvoid** [comment]
@khaykov thanks for the answers! all of it sounds good.

**Comment by khaykov** [comment]
Looks like Sourctree derped and included changes from `develop` into one of the unrelated commits. I'll sort it out in a bit.

**Comment by khaykov** [comment]
@planarvoid Fixed it!

**Comment by loremattei** [comment]
Hey! I'm moving this to 12.6 since 12.5 has been cut. If you want this to land 12.5, please feel free to target the release branch and ping me to build a new beta.

**Pull request merged**
