### PR TITLE
issue/3871-reader-tag-incorrect

### LINKED ISSUE #3871: Reader tag is not accurate on initial log in
### Expected behavior
When logging in and going to the Reader for the first time, the feed should be the one that it shows on the tag dropdown.

### Actual behavior
The tag shows "Automattic" but is actually "Discover"

### Steps to reproduce the behavior
1. Log in
2. Click on Reader tab
3. Check feed contents and compare to tag

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3871

To test: Logout of the app, then log back in. When you switch to the reader, it should show the Discover tag as the current tag.

Needs review: @kwonye

### CODE REVIEW

**Comment by nbradbury** [comment]
Closing - will resubmit against `release/5.2`

**Comment by nbradbury** [comment]
Re-opening - turns out this bug didn't exist in 5.2 :)

**Comment by kwonye** [comment]
Erm, ran into this while testing. Notice there is no dropdown. Switching tabs did not do anything, but backgrounding/foregrounding the app did. Once I did get back to the Reader, the correct tag did show up though.

screenshot_20160317-190956

**Comment by nbradbury** [comment]
> Erm, ran into this while testing. Notice there is no dropdown.

Oof, that's an ugly one. I haven't had any luck repro'ing this yet, so if you have any more info that would be helpful (such as whether this happened immediately after logging in, or immediately after launching the app).

**Comment by nbradbury** [comment]
Ignore that previous comment. Maxime and Mario confirmed that the problem likely stems from an empty tag, a situation I was luckily able to reproduce one time. Commit fb44cbd should fix that.

**Comment by kwonye** [comment]
> Commit fb44cbd should fix that.

Works great! :shipit:

**Comment by mzorz** [comment]
Thanks for fixing that @nbradbury ! :+1:

**Pull request merged**
