### PR TITLE
Private & Pending review pages

### LINKED ISSUE #8317: Pending review status not saved
`Pending review` status is not saved correctly when the **Back button** is tapped in the editor. It's either saved with the wrong status for new posts or only saved locally for existing posts.

This bug also applies to pages.

### Steps to reproduce:

New post:
1. Go to post list
2. Create a new post and type something
3. Go to post settings and change the status to Pending review
4. Go back to the editor
5. Tap the Back button
6. Wait for the post to upload
7. Notice it's saved as a Draft, not Pending review

Existing post:
1. Go to post list
2. Open an existing published page
3. Go to post settings and change the status to Pending review
4. Go back to the editor
5. Tap the Back button
6. Notice the post status is only saved locally (unlike for `Draft` posts)

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #8317 and #8347.

To test:

#### New post:
1. Go to Site pages
2. Create a new page and type something
3. Go to page settings and change the status to `Private`
4. Go back to the editor
5. Tap the **Back** button
6. Notice the page has `Private` and `Local changes` labels

#### Existing post:
1. Go to Site pages
2. Open an existing `Published` page
3. Go to page settings and change the status to `Private`
4. Go back to the editor
5. Tap the **Back** button
6. Notice the page has `Private` and `Local changes` labels

#### New post:
1. Go to Site pages
2. Create a new page and type something
3. Go to page settings and change the status to `Pending review`
4. Go back to the editor
5. Tap the **Back** button
6. Notice the post is uploaded
7. Notice the page has a `Pending review` label

#### Existing post:
1. Go to Site pages
2. Open an existing `Published` page
3. Go to page settings and change the status to `Pending review`
4. Go back to the editor
5. Tap the **Back** button
6. Notice the post is uploaded
7. Notice the page has a `Pending review` label

#### Existing post with no network:
0. Turn on the flight mode
1. Go to Site pages
2. Open an existing `Published` page
3. Go to page settings and change the status to `Pending review`
4. Go back to the editor
5. Tap the **Back** button
6. Notice the page has `Pending review` and `Local draft` labels

### CODE REVIEW

**Comment by 0nko** [comment]
> The page doesn't have the Local changes label

Oops.. This is now fixed

> When the upload is finished, the Local draft label disappears...

This is expected.

> ...and the page moves to the bottom of the list

This is not unexpected since the pages are ordered by the page ID. When the pages gets uploaded, the new ID is usually the largest in the list so it moves down. But I can see how this might not be ideal UX. I've changed it so that the pages are sorted alphabetically by the title. This way, the page upload won't affect the order.

**Comment by 0nko** [comment]
Btw, I've updated the test scenarios.

**Comment by planarvoid** [comment]
Thanks for the fixes @0nko !
I have one last thing. In the first scenario I see label `Local changes` instead of `Local draft`.

**Comment by 0nko** [comment]
> I have one last thing. In the first scenario I see label Local changes instead of Local draft.

That was a mistake in the testing instructions. It's actually correct like that.

**Pull request merged**
