### PR TITLE
Issue/3592 menus custom hierarchy ui

### LINKED ISSUE #3592: Menus Calypso - Hierarchy customization
Implement editable hierarchy for menus and their items.

- [x] UI: drag & drop
- [x] UI: add item above/below / to children
- [x] Implement UI data loaders (integrate network)
- [x] Implement database save/load

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #3592 (partially)

To test: this code aims at representing the menu items hierarchy - note that this code still has to be integrated with the menu item creation code (that means you can't create new items yet), so for now you can only move items left/right or use drag&drop to change the hierarchy

**EDIT:** Also, you'll find I added a left and right arrow to make it easy to change a menu item level without confusing then gesturedetector on item swipe (reserved for item deletion), which would lead to a messy UX.

Some thoughts on this also I would like long-press to start drag&drop would be more intuitive, wondering how to cue the user on that so they know they can use drag & drop. I think it would be great if dragged state starts like, right away in `onClick` rather than `onLongPressed`. Fuel for thought.

Needs review: @tonyr59h

### CODE REVIEW

**Comment by tonyr59h** [comment]
> wondering how to cue the user on that so they know they can use drag & drop

The way iOS is making that apparent is by adding 'grips' to the right side of each item view (seen [here](https://cldup.com/-dTPBxzwfu.png)). I've seen similar solutions in other apps, I think users would be able to recognize it.

**Comment by tonyr59h** [comment]
> I think it would be great if dragged state starts like, right away in onClick rather than onLongPressed

One thing to note here is that iOS (mobile in general?) we are using `onClick` as the 'edit button' and removing the edit button view altogether. cc @mattmiklic

**Comment by mzorz** [comment]
> The way iOS is making that apparent is by adding 'grips' to the right side of each item view (seen here). I've seen similar solutions in other apps, I think users would be able to recognize it.

Loved that! will steal the idea 👍

**Comment by mzorz** [comment]
Closing this PR as superseeded by #4300

**Pull request closed without merging**
