### PR TITLE
Jetpack Section: Scan - fix crash on snackbar display

### PR DESCRIPTION
**Pull request by ashiagr**
### Description

This PR fixes below crash when snackbar is displayed on Scan and Threat Details screen.

```
java.lang.NullPointerException: scan_state_layout must not be null
        at org.wordpress.android.ui.jetpack.scan.ScanFragment.showSnackbar(ScanFragment.kt:126)
        at org.wordpress.android.ui.jetpack.scan.ScanFragment.access$showSnackbar(ScanFragment.kt:31)
        at org.wordpress.android.ui.jetpack.scan.ScanFragment$setupObservers$2$1.invoke(ScanFragment.kt:89)
```

### Findings

We passed fragment's root constraint layout (using Kotlin synthetics) in the `showSnackbar` method. We started experiencing this crash after replacing `FragmentContainerLayout` with `Fragment` in the corresponding activity layout xml. 

As per this [SO answer](https://stackoverflow.com/a/34543172/193545), we instantiated `viewModels` for these screen inside `onViewCreated` so the layout referenced in the `showSnackbar` method should've been present at the time we had to display the snackbar.

I think it is the way Kotlin synthetic properties are cached and referenced in the different ways we add a fragment (directly in the xml or using `FragmentContainerView`). Or crash might be occurring on random devices as per [this comment](https://stackoverflow.com/questions/34541650/nullpointerexception-when-trying-to-access-views-in-a-kotlin-fragment/34543172#comment98324304_34543172), however I'm not 100% sure.

### Solution

It is sufficient to just pass fragment's view in the `showSnackbar` method, so I've removed reference to the fragment's constraint layout in the method. This fixes the crash and snackbar is displayed properly.

### To Test

Fix or ignore a threat from Threat Details screen (on a Jurassic Ninja site with scan capability and bad calendar plugin installed), see that app does not crash and snackbar is displayed properly.

(Or you can return `Failure.RemoteRequestFailure ` from `FixThreatsUseCase` so that snackbar is shown for the failed response.)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I have reviewed and tested this PR as per the instructions, everything works as expected, good fix! 🌟

**Comment by ParaskP7** [comment]
👋 @ashiagr !

I also triggered a re-run of the CI (from failed) because it was stuck as some `rake` step, not sure. Hopefully it will complete now. Feel free to merge this PR when CI completes.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

CI failed again, maybe ask `Platform9` for support on that.

**Comment by AliSoftware** [comment]
CI fixed!

**Comment by malinajirka** [comment]
@JavonDavis I introduced this crash in beta-2 😢. This PR fixes the issue and is targeting the frozen branch. Could you please include it in the next beta version? Thanks!
P.S. Thank you @ashiagr and @ParaskP7!

**Comment by fluiddot** [comment]
👋 I see this PR doesn't included the last [commit](https://github.com/wordpress-mobile/WordPress-Android/pull/14082/commits/593d24e54f4de96dfb8f61d201adc98e263b9e08) from https://github.com/wordpress-mobile/WordPress-Android/pull/14082, unfortunately this is causing a conflict with a [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14071) I'd like to include in the `release/16.7` branch.

@AliSoftware how should I solve the conflict with or without the last commit? Thanks for the help!

**Comment by AliSoftware** [comment]
The last commit of #14082 should have been included too indeed – it was added late in the investigation of this issue which is why I forgot to cherry-pick it here later, but it is part of the integrity of the whole fix and should indeed be added on top.

Note tho that @jkmassel is currently applying the fix from #14082 to the base of `release/16.7` so that the CI is properly fixed on the release branch for all release PRs. So maybe we should wait for Jeremy to push the fix on release/ branch first 😉

**Comment by fluiddot** [comment]
>Note tho that @jkmassel is currently applying the fix from #14082 to the base of release/16.7 so that the CI is properly fixed on the release branch for all release PRs. So maybe we should wait for Jeremy to push the fix on release/ branch first 😉

Ok, thank you very much @AliSoftware for the info, we'll wait for the fix then.

**Pull request merged**
