### PR TITLE
Issue/9666 post list show real progress

### LINKED ISSUE #9666: Post List: Replace indeterminate progress with real progress
The progress bar on post list items which is shown when the post or media are being uploaded doesn't show any progress. I "accidentally" replaced it with an indeterminate progress bar in [this](https://github.com/wordpress-mobile/WordPress-Android/pull/9431) PR.

Goal of this task is to use a progress bar which shows an actual progress of the upload.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9666

~**Note: Update branch to `feature/master-post-filters` when #9707 is merged.**~

- since this branch will create a bunch of conflicts with #9657 + it'll need to be updated to take into account the Compact list item view I think it should be reviewed and merged after #9657 is merged -> I'm creating just a draft so we don't forget about it.

Shows real progress as the media upload progresses.
uploading-media-progress

I've suppressed the item animation in https://github.com/wordpress-mobile/WordPress-Android/commit/6b521a88d05b2d2f1169369a859eff8c0b1df2b8 to prevent the list item from blinking as the upload progresses. However, the featured image is still blinking since it apparently blinks when the `ImageManager.load` method is re-invoked. I can't think of a good and easy solution right now. Any ideas? cc @mzorz @oguzkocer 

To test:
1. Open Post List
2. Create a post
3. Add title and add some images from the local storage
4. Publish the post before the images are uploaded (you might want to set Edge in emulator's networks settings)
5. Notice the progress bar on the item in the list is updated as the upload progresses

Update release notes:

- I haven't updated the release notes as this issue will be released along with the Post Filters project

### CODE REVIEW

**Comment by oguzkocer** [comment]
> I've suppressed the item animation in 6b521a8 to prevent the list item from blinking as the upload progresses. However, the featured image is still blinking since it apparently blinks when the ImageManager.load method is re-invoked. I can't think of a good and easy solution right now. Any ideas?

@malinajirka I am not sure if I fully understand your intentions with the `getChangePayload`. I don't think you're currently utilizing the information you return from that in `onBindViewHolder` as you'd need to override the following:

```
override fun onBindViewHolder(holder: ViewHolder, position: Int, payloads: List<Any>) {
```

When you override that, you'll need to pass the information about what changed to the view holder. Unless I am missing something, we are not doing any of that right now.

---

I also don't think we should be relying on the progress to update the featured image. Instead, maybe we can just compare the old item's image url to the new one and update the featured image only if there is a change. This can be done either by using the payloads, or caching this information in the view holder itself. Please note that even if we do this, during uploads, there will be at least one flash because the url will change from the device path to the external url. I don't think we should try to prevent this in the view holder layer. (not that it's easy to prevent anyway)

Hope all this helps, let me know if you get stuck or if you have any questions!

**Comment by malinajirka** [comment]
Thanks for the feedback @oguzkocer! 

> I am not sure if I fully understand your intentions with the getChangePayload. I don't think you're currently utilizing the information you return from that in onBindViewHolder

When the getChangePayload returns a non-null value the Android system won't run the default animation. So I don't need to actually handle the payload in `onBindViewHolder` if I just want to suppress the animation.

 >When you override that, you'll need to pass the information about what changed to the view holder. 

This seemed like an overkill for this particular use-case.

>I also don't think we should be relying on the progress to update the featured image.

I'm not sure I follow. I don't think we are relying on the progress. We just re-load the image when the progress changes(which is technically an undesired side-effect), but we also re-load it when the feature images changes.

>This can be done either by using the payloads, or caching this information in the view holder itself. 

I like the idea of caching the url in the viewholder. It seems like an easy win. ;) Thanks!

**Comment by oguzkocer** [comment]
> When the getChangePayload returns a non-null value the Android system won't run the default animation. So I don't need to actually handle the payload in onBindViewHolder if I just want to suppress the animation.

Oh, I did not know about that, so all my assumptions were wrong, you can ignore the whole thing :)

**Comment by malinajirka** [comment]
Actually your comment was quite useful - storing the url/path will work. I'll make sure to add a comment to `getChangePayload`. ;)

**Comment by mzorz** [comment]
> I'll make sure to add a comment to getChangePayload. ;)

That sounds great!  I was on the same place as Oguz, not knowing about it so, it looks like a comment in code will make that clear for future selves and others reading the code :)

**Comment by mzorz** [comment]
> However, the featured image is still blinking since it apparently blinks when the ImageManager.load method is re-invoked. I can't think of a good and easy solution right now. 

> > This can be done either by using the payloads, or caching this information in the view holder itself.

> I like the idea of caching the url in the viewholder

**Comment by malinajirka** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/pull/9776

**Pull request closed without merging**
