### PR TITLE
Initialises DebugCookieManager only when the debug settings are enabled

### LINKED ISSUE #20619: WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
Sentry Issue: [JETPACK-ANDROID-KE0](https://a8c.sentry.io/issues/5045825362/?referrer=github_integration)

```
RuntimeException: Unable to create application org.wordpress.android.WordPressRelease: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7690)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
...
(5 additional frame(s) were not displayed)

AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at org.wordpress.android.ui.debug.cookies.DebugCookieManager.<init>(DebugCookieManager.kt:40)
    android.webkit.CookieManager.getInstance(),
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.debugCookieManager(DaggerWordPressRelease_HiltComponents_SingletonC.java:6463)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.injectAppInitializer(DaggerWordPressRelease_HiltComponents_SingletonC.java:9437)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.access$26600(DaggerWordPressRelease_HiltComponents_SingletonC.java:5264)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get0(DaggerWordPressRelease_HiltComponents_SingletonC.java:11125)
...
(19 additional frame(s) were not displayed)

AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at org.wordpress.android.ui.debug.cookies.DebugCookieManager.<init>(DebugCookieManager.kt:40)
    android.webkit.CookieManager.getInstance(),
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.debugCookieManager(DaggerWordPressRelease_HiltComponents_SingletonC.java:6463)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.injectAppInitializer(DaggerWordPressRelease_HiltComponents_SingletonC.java:9437)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.access$26600(DaggerWordPressRelease_HiltComponents_SingletonC.java:5264)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get0(DaggerWordPressRelease_HiltComponents_SingletonC.java:11125)
...
(20 additional frame(s) were not displayed)

WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at org.wordpress.android.ui.debug.cookies.DebugCookieManager.<init>(DebugCookieManager.kt:40)
    android.webkit.CookieManager.getInstance(),
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.debugCookieManager(DaggerWordPressRelease_HiltComponents_SingletonC.java:6463)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.injectAppInitializer(DaggerWordPressRelease_HiltComponents_SingletonC.java:9437)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl.access$26600(DaggerWordPressRelease_HiltComponents_SingletonC.java:5264)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get0(DaggerWordPressRelease_HiltComponents_SingletonC.java:11125)
...
(21 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #20619

## Description
The linked crash occurs in the initialisation of the `DebugCookieManager` when there is no `WebView` installed.
```
AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at org.wordpress.android.ui.debug.cookies.DebugCookieManager.<init>(DebugCookieManager.kt:40)
    android.webkit.CookieManager.getInstance(),
```
Given that the `DebugCookieManager` [is used only for debugging](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookieManager.kt#L47) when the `ENABLE_DEBUG_SETTINGS` flag is `true` we can prevent the crash in production by conditionally initialising the object only when it is needed ([and not always via injection](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/AppInitializer.kt#L189)).

-----

## To Test:
- *Verify* that the app starts normally
- *Verify* the the cookie manager functionality works as expected (see https://github.com/wordpress-mobile/WordPress-Android/pull/15153)

-----

## Regression Notes

1. Potential unintended areas of impact

    - Debug cookies

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - Refactoring the code for testing escapes the scope of this fix

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jarvislin — APPROVED** [review]
I cannot see the cookies I set in debug settings in both branches of trunk and fix/20619-DebugCookieManager.

According to the changes, I think it makes to me to avoid the crash of initialization. Feel free to merge it.



截圖 2024-04-12 上午10 13 37

**Comment by antonis** [comment]
> I cannot see the cookies I set in debug settings in both branches of trunk and fix/20619-DebugCookieManager.
> According to the changes, I think it makes to me to avoid the crash of initialization. Feel free to merge it.

Thank you for reviewing and testing thoroughly @jarvislin 🙇 
I'll proceed with merging to get the crash fix in `24.7` and investigate separately the debug cookie functionality.

**Comment by antonis** [comment]
> I cannot see the cookies I set in debug settings in both branches of trunk and fix/20619-DebugCookieManager.
> According to the changes, I think it makes to me to avoid the crash of initialization. Feel free to merge it.

I've followed up on this internally pcdRpT-6m5-p2

**Pull request merged**
