### PR TITLE
Fix postcard with empty title in Reader

### LINKED ISSUE #12308: Reader card with empty title
### Expected behavior
When a post in Reader has empty title, it should be replaced with R.string.untitled_in_parentheses.

### Actual behavior
When a post in Reader has empty title, the title is blank and there is horizontal whitespace.

### Steps to reproduce the behavior
1. Publish a post with an empty title
2. Open reader on following tab and filter by the blog you published the post on
3. Notice the card has empty title and horizontal whitespace

https://user-images.githubusercontent.com/1405144/85975973-0c247d00-b9f7-11ea-8805-fadeaeaabf9a.png

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #12308

Updated on 9/2:

Show "(Untitled)" when a post card doesn't have a title -> for example a post with photos in it's content and no title.

To test:
1. Follow "upm59krakatit.wordpress.com"
2. Open reader - following tab
3. Notice the newest post has title "(Untitled)"

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — COMMENTED** [review]
@malinajirka - I could not use `upmkrakatit59.wordpress.com` - it doesn’t exist (I checked using a browser). 
So I created a post on one of my sites without a title. I did not see (Untitled) as expected. It seems that the post excerpt is being used in its place. Take a look at `ReaderPost.fromJosn` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/55d8c0c63763c5bc87edd284cdb6a23129901415/WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java#L140) .

**Comment by malinajirka** [comment]
My bad, sorry @zwarm - I've updated the PR description. The correct url is "upm59krakatit.wordpress.com".

**Comment by zwarm** [comment]
> upm59krakatit.wordpress.com

Much better!! Thanks. :) All works as expected now.

**Review by zwarm — APPROVED** [review]
LGTM.
(Untitled) is shown.
👍

**Pull request merged**
