### PR TITLE
Themes Browser M1 interactions (minus search)

### PR DESCRIPTION
**Pull request by kwonye**
This does all interactions except for search. That includes:

- Activating themes
- Filtering and paging support
- all menu items (details, support, preview, demo, activate)

Needs review: @tonyr59h

### CODE REVIEW

**Comment by kwonye** [comment]
Please do not merge until #3093 is merged.

**Comment by tonyr59h** [comment]
* After activating a theme the Current Theme should update its text
* The web version shows `Customize/Details/Support` with the first letter capitalized, should mobile follow suit?
* Selecting `customize` is a no-op
* Selecting `details` and `support` brings me the same page
* There's no animation for tapping a list item, I feel like it's necessary since our other lists (Reader, Notifs, Posts, etc...) animate selection
* When viewing a theme the `Menu` spinner doesn't show anything
* When viewing a theme selection highlights (tap and hold an image, for example) appear over-top the `WordPress.com` title bar
* There's a weird shadow below the `Buy This Theme` button when scrolling
* Some content is hidden behind `Buy This Theme` when scrolled to the bottom

**Comment by tonyr59h** [comment]
Some more things in case you didn't find them already:

* When additional themes are loaded the filter is not applied; if I have `Free` selected and scroll to the bottom the newly loaded themes are both free and premium
* Rotation resets the filter to `All` but maintains the scroll position
* After activating a blog the spinner shows the previously selected filter but the list contains all themes

**Comment by kwonye** [comment]
```
When additional themes are loaded the filter is not applied; if I have Free selected and scroll to the bottom the newly loaded themes are both free and premium
Rotation resets the filter to All but maintains the scroll position
After activating a blog the spinner shows the previously selected filter but the list contains all themes
```

Thanks for that! I spent forever looking for the culprit and it turned out to be two hard-coded values I had in there. I may have to stop using them as they keep slipping through the cracks!

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
