### PR TITLE
Smart Lock for Passwords integration

### PR DESCRIPTION
**Pull request by maxme**
WIP - needs a design review.

### CODE REVIEW

**Comment by maxme** [comment]
Pain points:

* Self hosted (can't save the url), so only wpcom is supported in this patch
* Delete credentials?
* 2FA

**Comment by kwonye** [comment]
@maxme SignInActivity may be deprecated soon. It may be worth the extra work to separate out the Smart Lock logic.

**Comment by maxme** [comment]
> It may be worth the extra work to separate out the Smart Lock logic.

That's a good idea. Make sure the new activity i

**Comment by maxme** [comment]
Waiting for magic link to land before modifying this PR.

**Comment by kwonye** [comment]
@maxme with the new design of magic-links, I've changed the new login flow to extend `SignInActivity` and `SignInFragment`. This means we can go ahead with the PR.

I'll review it and get @mattmiklic to look at it for the design review". When those two are done, I'll merge this in.

**Comment by kwonye** [comment]
@maxme I'm unable to have Smart Lock sign me in automatically if I have a saved password in Chrome. Netflix does however. Is this expected behavior?

Also, can you add analytics to this please?

**Comment by maxme** [comment]
> @maxme I'm unable to have Smart Lock sign me in automatically if I have a saved password in Chrome. Netflix does however. Is this expected behavior?

For now yes, we need to do an extra dance to share browser and app secrets: https://developers.google.com/identity/smartlock-passwords/android/associate-apps-and-sites#associate_your_app_with_your_website - I'll do that when this PR is merged.

**Comment by maxme** [comment]
We could reuse these, but we need to rename them: https://github.com/wordpress-mobile/WordPress-iOS/blob/53d54580b4a5511f8df2f063ab1564e29e73c4c8/WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m#L849-L854

**Comment by maxme** [comment]
> I couldn't find any way to choose to log in using the Smart Lock. It wasn't until after I force-quit the app and restarted it that I was prompted to sign in with Smart Lock.

Yes, that's on purpose. I thought if the user signed out, it was to sign in with another account, so I don't trigger the auto fill.

What do you recommend? Trigger the auto fill in all cases? add a new button?

Note: we can't mimic browser behavior (list usernames in a dropdown when user tap the username text field).

**Comment by maxme** [comment]
> Yes, that's on purpose. I thought if the user signed out, it was to sign in with another account, so I don't trigger the auto fill.

> What do you recommend? Trigger the auto fill in all cases? add a new button?

I was thinking about this again, if the user switch between 2 set of credentials, it makes sense to show him his credentials list on signout. So I guess we should just trigger the autofill when we show the login screen regardless of a previous signout action.

**Comment by mattmiklic** [comment]
> I was thinking about this again, if the user switch between 2 set of credentials, it makes sense to show him his credentials list on signout. So I guess we should just trigger the autofill when we show the login screen regardless of a previous signout action.

Yeah, I agree. This is the behavior we've adopted for Safari saved passwords on iOS so I think it would be logical to have the password dialog appear in the same circumstances on Android.

If you've dismissed the smart lock dialog, then there's no way currently to make it re-appear, but we didn't worry about that for the first iteration on iOS. I'm going to work on a new icon design to represent saved passwords, and I'll create some mockups of how I suggest we implement a button to force the smart lock dialog to appear when it's ready.

**Comment by maxme** [comment]
@kwonye do you want me to make other changes in this branch?

**Comment by kwonye** [comment]
@maxme sorry I misread @mattmiklic's comment. I was waiting for the mockups, but just noticed he said not to worry about it for V1. Will test again and merge today (assuming I don't find anything)

**Comment by kwonye** [comment]
:shipit:

**Pull request merged**
