### PR TITLE
Adds hint to Web Address dialog in Account Settings

### LINKED ISSUE #3730: Add a hint message to web address dialog in Account Settings
I am going to separate this issue from #3726 since it doesn't affect the functionality and a bit blocked by the #3676. I'll take care of this once the Account Settings changes merged in to `develop`.

https://cloudup.com/iCP_cIADt0L

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #3730. This whole thing feels like a big hack to me, but this was the best solution I could came up with.

To test: Go into Account Settings page and check Web Address field, you should see a dialog like below, which should have a hint:

screen shot 2016-04-04 at 14 16 23

@rickybanister: The fonts for the buttons and the title felt a bit off to me after the change. Could you check that? If it's different, I am not even sure what causes it or how I can fix it? /cc @maxme 

Needs review: @maxme (since this felt like a bit hacky I wanted to ping you Maxime, thanks!)

/cc @astralbodies

### CODE REVIEW

**Comment by maxme** [comment]
Font is good, not sure what you mean, size seems correct and auto capitalization for buttons is normal (follow material specs).


It feels like a hack because overloading Preference component is always hackish (that's why we shouldn't use Preferences if we want custom design) also the normal way to display a message in a Dialog is to use the [setDialogMessage](https://developer.android.com/reference/android/preference/DialogPreference.html#setDialogMessage(int))

IMO, if the position of the hint is not important then we should do something like [this](https://github.com/wordpress-mobile/WordPress-Android/compare/feature/web-address-hint...issue/web-address-hint-maxme?expand=1) but else it's ok to :shipit: (maybe add a comment of `onBindDialogView` to explain why we did that).

**Comment by rickybanister** [comment]
It would be helpful to see a before screenshot just to see the same differences you're seeing maybe. Without that context, the colors and things seem alright to me.

**Comment by oguzkocer** [comment]
@rickybanister: After I took some high res screenshots, I am not so sure if there are any issues, I might have mistaken from the emulator. Here are those screenshots:

before
after

**Comment by oguzkocer** [comment]
@maxme I think the idea was to make it similar to the My Profile dialog which uses the hint below the input. I knew about dialog message, but I thought that's not what we wanted to do. If it's, it's going to be a lot of wasted hours, but also cleaner code...

Anyhow, here is the version with the dialog message instead of the custom text view. @rickybanister should make the call on that.

dialog message

**Comment by maxme** [comment]
> I think the idea was to make it similar to the My Profile dialog which uses the hint below the input. I knew about dialog message, but I thought that's not what we wanted to do. If it's, it's going to be a lot of wasted hours, but also cleaner code...

Understood, I usually prefer to keep things simple when possible, here it feels like a detail to me. Since you already implemented everything, it's ok to :shipit:.

**Comment by rickybanister** [comment]
The dialog message is great, seems like that's easier all around.

**Comment by oguzkocer** [comment]
@maxme Changed the hint to `dialogMessage`. it looks a bit different (like in the screenshot above), but I guess that's fine. Should be ready to merge now if it looks good. Thanks!

**Comment by maxme** [comment]
@oguzkocer looks good, but should we update other dialogs to match the same style?

**Comment by oguzkocer** [comment]
@maxme I was thinking about the same thing actually but forgot to mention here. Here is a screenshot from the my profile dialog using the dialog message instead of the custom text view:

my profile dialog

If we are going to change this one as well, maybe we should style it? I am not sure, but if we can, maybe we should try to style the one in Account Settings as well? What do you think @rickybanister?

On a totally unrelated note @rickybanister is there a reason the My Profile dialogs have orange button instead of blue like the other places in the app? Should we also change that?

**Comment by rickybanister** [comment]
I don't know why that has orange buttons. My design looks like your update to the Web Address field. 

The orange buttons were an older thing when we felt we needed to use a contrasting color I believe, but the medium blue color is the more appropriate button color.

I personally think the help text should have gone below the field like this:

**Comment by oguzkocer** [comment]
I think I am mostly satisfied with the dialogs after the recent changes. I've gone back and forth quite a bit on this feature with the design feedback, but now the dialogs in the Account Settings and My Profile pages mostly match each other and it doesn't feel very hacky anymore (which is good!). Here are the final screenshots for the dialogs (from different pages):

screen shot 2016-04-08 at 15 17 22
screen shot 2016-04-08 at 15 23 48

If the changes look good to you @maxme I think we can finally merge this in. I've chatted with @rickybanister yesterday on Slack and he wanted me to style it this way (in this order & font) if I understood him right :)

Thanks both!

**Comment by rickybanister** [comment]
Happy to see the consistency here!

**Comment by maxme** [comment]
@oguzkocer Dialog message styling looks bad on Android < 6.0:

Android 5.0:
screenshot-2016-04-11_09 05 26 779

Android 4.1.1:
screenshot-2016-04-11_08 59 58 174

**Comment by oguzkocer** [comment]
@maxme I attempted to fix that in [b3f624c](https://github.com/wordpress-mobile/WordPress-Android/pull/3921/commits/b3f624c2ac6fc5b56e243ac775ee753ef550e776). I am not sure if we are ok with these kind of checks and different solutions for different API levels. I think this is the best we're going to get considering 3 different api versions handle the positioning of the message 3 different ways. Below you can find screenshots from 4.4.4 & 5.0.0. Can you also check for something like 4.1.1? 

I am sorry for missing this before I replied to the PR. Thanks for catching it! Btw, the issue was not related to any changes made in the PR, but from the OS differences, we just didn't know about it because we weren't using the dialog message before. All in all I think the original PR might have been the better way to go, since this didn't really turned out to be easier, but oh well...

screen shot 2016-04-11 at 14 51 34
screen shot 2016-04-11 at 14 48 58

**Comment by maxme** [comment]
> I am not sure if we are ok with these kind of checks and different solutions for different API levels. I think this is the best we're going to get considering 3 different api versions handle the positioning of the message 3 different ways. 

I'm not really happy with this solution, but there is no way to cleanly customize different layouts (each API version has its version of the EditText dialog layout). That's another good reason not to use Preference components if we need to customize them.

> All in all I think the original PR might have been the better way to go, since this didn't really turned out to be easier, but oh well...

Yes, it's the same kind of dirty hack ;)

**Comment by oguzkocer** [comment]
@maxme So, what would you like to do with this PR? I am kind of lost now after trying/changing a bunch of things.

**Comment by maxme** [comment]
> what would you like to do with this PR? I am kind of lost now after trying/changing a bunch of things.

The only ways to fix it properly would be 1. drop Preferences or 2. drop custom design, and we're not going to choose one of these solutions, so let's :shipit: and revisit later if we need other customizations.

**Comment by oguzkocer** [comment]
Cool - thanks a lot for the review and your insight @maxme!

**Pull request merged**
