### PR TITLE
Discard empty new posts

### LINKED ISSUE #6079: Empty draft should be deleted automatically
### Expected behavior
Entering the Editor for a new Post and immediately exiting shouldn't add a new draft to the Posts list

### Actual behavior
Entering the Editor for a new Post and immediately exiting creates a new empty draft post in the Posts list.

### Steps to reproduce the behavior
1. Tap on the floating "write" button
2. When the editor is shown, tap "back"
3. Observe there's a new empty "(Untitled)" draft pos in the posts list.

### PR DESCRIPTION
**Pull request by mzorz**
Only check for changes if there was a original post to compare against

Fixes #6079 

To test:
1. start new draft
2. exit the editor
3. you should not see any new posts in the posts list

cc @aforcier

### CODE REVIEW

**Comment by mzorz** [comment]
Side note on this: I thought of just removing [the check here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java#L164-L166) as it's used _with the same check added in this PR_ [in this other place only](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1020). We might want to go with that option instead, and make `hasEdits` not check between `oldPost` and `newPost` being null and non null respectively.

**Comment by aforcier** [comment]
This breaks draft auto-saving for non-empty new posts. IIUC, `hasChanges` is _supposed to_ be always `true` for new posts. I think the problem is that, at some point, we stopped checking correctly whether a new post was different from an empty, freshly initialized post (in which case it's empty).

**Comment by oguzkocer** [comment]
I don't think this is the right change to make. If I am not mistaken, we need to clone the post to `mOriginalPost` after this line `mPost = mPostStore.instantiatePostModel(mSite, mIsPage, categories, postFormat);` and all should be good.

P.S: There is a snackbar when we don't save the new post (since it's empty) which says the post is deleted, which is not true, we should probably change that.

**Comment by mzorz** [comment]
Thanks for your comments @oguzkocer @aforcier ! Looking into it more deeply now. 🙇

**Comment by oguzkocer** [comment]
The suggested change might need a bit more explanation, so here it is. I don't think `mOriginalPost` should ever be `null` and we shouldn't even need to check for it. In order to be able to check if a post object has any change on it, we need to clone the post after it's instantiated. During initialization we'll update some of the properties of the post, but we still want that version of the post to be considered empty, because the user has not made any changes to the object yet. If the user closes the editor, hence delete this new post and create another one, it'll be exactly the same object, that means nothing has been lost.

@mzorz Hope that makes sense!

**Comment by mzorz** [comment]
it does @oguzkocer ! I'm trying your suggested approach now :)

**Comment by mzorz** [comment]
> This breaks draft auto-saving for non-empty new posts.

This commit here f01d000 addresses this: now making sure we save a draft if it has changes and is not new, or it is new and is publishable, or has unpublished local draft changes.

@oguzkocer I explored the suggested approach: making a clone in that part and even if the user doesn't do anything will still make the original (`mPost`) and the clone (`mOriginal`) differ, because the settings fragment still handles the object in the background (particularly, `EditPostSettingsFragment` which lives in the viewPager adapter makes a call to `fetchSiteSettingsAndUpdateDefaultPostFormat`, which potentially updates the `mPostFormat`with the sites’ default).
This ends up with that fragment in the background setting the `mPostFormat`  to `standard` (or whatever the Site Setting value is) in the living object, while the `mOriginal` clone remains with `mPostFormat` uninitialised (that is, an empty "" String).

I also considered still going with the cloning approach and set a default value for `mPostFormat` right away, but it turns out I can’t use any default in particular as this would still be a problem when the remote site settings are fetched and differ, so that's why the only option left was to go with the flag approach I started with in the original PR.

Regarding this: 
> There is a snackbar when we don't save the new post (since it's empty) which says the post is deleted, which is not true, we should probably change that.

It didn't happen for me, where did you see that? Could you let me know if that still happens with these latest changes?

Ready for another round @oguzkocer @aforcier 🙇

**Comment by aforcier** [comment]
@mzorz There's one minor buggy behavior I'm seeing:

1. Start a new post
2. Open the post settings, and set something that doesn't open a new fragment (publication date, format, slug, etc - excerpt is excluded since it makes the post qualify under `isPublishable`)
3. Exit the editor
4. The post is not saved as a draft

Overall I think this is minor, but it's pretty brittle. The reason it works for some of the post settings actions, like setting a category or a featured image, is that those open a new fragment, which triggers `EditPostActivity.onSaveInstanceState()`, which ends up calling `savePostToDb()` and assigning `mOriginalPost` a value.

In general I'm not a fan of adding more obscure boolean checks to the save post handling code, but as has been discussed elsewhere we're going to need to take a methodical approach and write some tests before we do more deep changes there. And I agree with your notes about how initing more fields in the `PostModel` won't really solve the problem.

So, I'm okay with this approach for now, as it fixes the far worse problem of saving empty new posts.

(Though we should file an issue for the above case so it's tracked.)

I'll let @oguzkocer give his thoughts as well.

**Comment by oguzkocer** [comment]
@mzorz I had an idea I forgot to share yesterday. Could we try it before merging this in?

When we are checking for edits, if the `oldPost` is `null`, that means this is a new post and we need to check it differently. So, if that's the case, I suggest we instantiate a new post and check the changes against that ignoring the post format. I _think_ this will cover every case. It'll look something like this:

```
if (oldPost == null) {
    oldPost = {instantiate new post}
    return {do the compare and ignore the post format during comparison}        
}

return {do the regular compare}
```

**Comment by mzorz** [comment]
Thanks again for your comments @oguzkocer and @aforcier. I've been exploring on this a fair bit more and **tl;dr** I think it should be left as per this PR and not dedicate further time to it until we get to revisit EditPostActivity's architecture in an integral way.

As I was saying, I put together some thoughts on this and been pondering for quite a while.

@oguzkocer I was going to try your approach but I rapidly realized it would mean we needed to instantiate a new Post, which needs `categories` and `post format` to be also cached in some class variable so it can be reached by the time we need it, and things started looking even unprettier. :(

However, let me stop a bit on this:

> if the oldPost is null, that means this is a new post and we need to check it differently.

So from my POV the fact this new suggested approach checks for a special condition (i.e. `is the original post null?`), when what we actually want to ask is  `is this a new post?` I actually prefer asking directly for what we  want to ask, which is `is this a new post?`, therefore I think the added check I made is more clear and straight-forward, specifically checking for this condition `(isPublishable && isNewPost())`.

let me dissect the OR clauses I had here:
- `(mOriginalPost != null && hasChanges)` -> did there exist an Original Post and we have changes to it?, OR
- `hasUnpublishedLocalDraftChanges ` -> does the Post have unpublished local draft changes?, OR
- `(isPublishable && isNewPost())` —> is this Post good to be published, and new?

—> then let’s save it online.

IMO these are straight-forward and easy enough to understand. 

@aforcier thanks for testing every corner - I wonder how many people would go without adding any content (no title, no content, no excerpt), but still have settings to define in mind as a priority when starting a draft 🤔 - I honestly think this might be as is by design. i.e. I wonder, is this really the expected behavior? nevertheless, tracking the issue for further discussion / treatment as suggested, here https://github.com/wordpress-mobile/WordPress-Android/issues/6413

Thank you both again for your considerations and time spent testing this!

**Comment by aforcier** [comment]
Thanks for filing an issue @mzorz - I agree it's really minor and in some cases probably what the user would expect to happen. But some of the other, more important settings (like you might be annoyed if we lost your post with a featured image set) are only working because of a fluke, and I wanted the issue recorded in case we refactor this in the future and the fluke no longer saves us.

Given that @oguzkocer gave his 👍 for us to go ahead with this elsewhere, I'm going to merge this.

:shipit:

**Pull request merged**
