### PR TITLE
Issue/15983 make comment text selectable

### LINKED ISSUE #15983: Add Ability to Highlight Text of Comments Without Editing the Comment
### Expected behavior
Like the iOS app, users should be able to highlight text within comments without having to enter the edit screen for that comment.

### Actual behavior
You can't highlight text in a comment without entering the edit screen for that comment.

### Steps to reproduce the behavior
1. Navigate to My Site > Comments.
2. Select a comment from the list.
3. Attempt to highlight text in the comment.

##### Tested on Pixel 3, Android 12, WPAndroid 19.2-rc-3

Ticket: 4740245-zd-woothemes

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #15983

This PR makes comment text selectable in Site Comment Details and in Reader Comment List.

Text in those place was set to non-selectable long time ago, because of [this]( https://code.google.com/p/android/issues/detail?id=30961) issue, which scrolled the long TextView after it gained focus. That issue was since fixed, and does not happen in android versions supported by us.

During my tests I discovered another issue when text is set to selectable - with a very long comment, selecting a word at the top of it, and scrolling the screen down causes a crash. The issue is present on devices with api <=27. I did not particularly like any workarounds, so I decided to disable selectable text on affected devices. Majority of our users will still benefit from this update.

To test:
- Using a device with api <=27 navigate to Site Comments and open a comment.
- Confirm that the text of the comment is not selectable.
- Using a device with api <=27 navigate to Reader Post Comments.
- Confirm that the text of the comment is not selectable.

--

- Using a device with api >=28 navigate to Site Comments and open a comment.
- Confirm that the text of the comment is selectable.
- Using a device with api >=28 navigate to Reader Post Comments.
- Confirm that the text of the comment is selectable.
- In Reader comment, find a very long comment, that spans below the visible area.
- Select a word at the top of the comment and scroll the screen down (so the selected word will move up out of view).
- Confirm that nothing is crashing.

## Regression Notes
1. Potential unintended areas of impact
- Crash described in "To test" happens on devices with API 28+

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual testing.

3. What automated tests I added (or what prevented me from doing so)
- Not testable.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
Good job with this one sir 🙇 ! Also great catch with the issue with long comments scroll 👍 ! I was able to:
- reproduce both the original issue and the long comment scroll issue on Pixel 4 EMU API 26 (forcing allowing selection to check for reproducibility). 
- Also verified that the patch do not allow selection before API28 and allows it otherwise. 
- With API >= 28 both selection and scroll on long comment issues are also not present AFAIU 👍 ! 

This said I found another issue in threaded comments that's worth investigating before we merge this. In my setup if I go to posts with lot of comments (so to force pagination) it seems I cannot select the comment body anymore after going down the list on comments after pagination. Steps:
- open in the reader a post with more than 20 root comments (so to force pagination)
- verify you can select on comments at the beginning of the ilst
- scroll down to the end of comments list (notice pagination is triggered with loading state)
- try again to select comment body from comments at the end of the list of comments
- notice you cannot select it

I was using a pixel 4 EMU with API 28 for this.

Moving milestone to 19.5 so we can better double-check 🙇

**Comment by khaykov** [comment]
Thanks for testing, @develric! After trying all kind of things, I discovered that the issue you described is an is an old [android bug](https://code.google.com/p/android/issues/detail?id=208169). I think I fixed it (at least I can't replicate it again).

**Comment by khaykov** [comment]
Just a heads up - found a minor issue where taping on a very long comment in a recycled view moves the scroll of the RecyclerView. Can be annoying, so will try to fix it.

**Comment by khaykov** [comment]
I'm currently a bit swarmed with other issues, so will close this PR.

**Pull request closed without merging**
