### PR TITLE
fix #2160: removed unnecessary configChanges

### LINKED ISSUE #2160: Remove "android:configChanges" config in AndroidManifest.xml if not really needed
Especially on `WPDrawerActivity` subclasses where the menu drawer is initialized in `onCreate`.

### PR DESCRIPTION
**Pull request by maxme**
I kept in SignIn/NewAccount acitivities cause we're moving buttons on
rotation (we could remove it and use a different layout) and EditPost
activity to keep the keyboard opened after rotation.

### CODE REVIEW

**Comment by nbradbury** [comment]
If I rotate the device while blog preferences is showing, it returns to the main preferences activity.

**Comment by maxme** [comment]
> If I rotate the device while blog preferences is showing, it returns to the main preferences activity.

Hm, right, I haven't noticed this: https://github.com/wordpress-mobile/WordPress-Android/blob/943057c2d7a56924c4673869805ad6834bc586bf/WordPress/src/main/java/org/wordpress/android/ui/prefs/BlogPreferencesActivity.java#L153

**Comment by maxme** [comment]
Not sure why `onPause` is used here, it look like we want to save and finish in the `onStop` method

**Comment by nbradbury** [comment]
Looks good :shipit:

**Pull request merged**
