### PR TITLE
Unified Login & Sign-Up: Login library screen layouts update

### LINKED ISSUE #11785: Update the UI of the login flow
The task is to update the UI of all the steps of the login/signup flow. This flow uses shared components so the screen changes will be overlapping
- The toolbar is changing, instead of a logo it now contains a title with the flow you're in ("Get Started" changes either into "Log In" or into "Sign Up"), the help is now an icon
- The action buttons are moving to the bottom of the screen
- The colors and styling are changing
- Go step by step and compare the screens to the desings to see all the changes
- If possible, the changes should be behind a feature flag

Continue with WordPress com

### PR DESCRIPTION
**Pull request by renanferrari**
Fixes #11785

Depends on #12047

This PR updates the following screens layouts on the Login Library:
- Login Email Screen
- Login Email Password Screen
- Login Magic Link Request Screen
- Login Magic Link Sent Screen
- Login 2FA Screen
- Login Site Address Screen
- Login Username Password Screen
- Signup Email Screen
- Signup Magic Link Screen

With the exception of the Login Email screen, which has a flag to switch from the old layout to the one, most changes on the other screens are pretty similar: we basically hide the secondary button, override a method to setup the toolbar title and replace its old elements with new ones, if any. 

Other than that, some screens needed a shared header component, which consisted of the user's avatar and email. That component was extracted to a common layout file and a simple helper class was created to share the logic for loading the avatar.

## To test

Navigate through each of the screens listed above and make sure its appearance is in line with the design spec (internal ref: pbArwn-mA-p2). You may also want to test the flow with the feature flag turned off.

## Notes
- We still have to add the Signup Confirmation Screen, which should be done in a PR to follow.
- Both the Jetpack flow and the Share Intent flow make use of a button inside the Login Email Screen that is not being shown on the new layout. This still needs some input from the design team and will also be addressed in a future PR.

---

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by planarvoid** [comment]
hey, thanks for the changes! It all looks amazing 👍 

I've noticed a few details different from the designs:
- The app says `Verification code` but the designs say `Authentication code` 
- I think the `Or type your password` is bolder in the designs
- On signup with a non-existing email there is a missing screen (the magic link request screen) that says "We'll email you a link to create your account" and shows you the button with "Send link by email"
- Clicking on "Continue" when you enter a non-existing email doesn't hide the keyboard (even though there is no field on the next screen)
Stuff probably unrelated to your PR:
- The google account picker and the email picker don't have a dark theme

**Comment by renanferrari** [comment]
@planarvoid Thanks a lot for the review!

>The app says Verification code but the designs say Authentication code
Good catch! 

>I think the Or type your password is bolder in the designs
Some designs were using a medium weight on those buttons, while others were using a regular weight. After talking with @mattmiklic we decided to keep them all on regular for now.

>On signup with a non-existing email there is a missing screen (the magic link request screen) that says "We'll email you a link to create your account" and shows you the button with "Send link by email"
Yes, that's the Signup Confirmation Screen I mentioned on the PR notes. It will be added on a follow-up PR.

>Clicking on "Continue" when you enter a non-existing email doesn't hide the keyboard (even though there is no field on the next screen)
I hadn't noticed that, but I should be able to address it on the next PR, since it's directly related to that new screen.

>The google account picker and the email picker don't have a dark theme
I considered giving this a try, but I think @AmandaRiu is currently working on updating the Google Sign-In library, which I'm assuming would address that issue. If not, we can look into this again later on.

**Comment by planarvoid** [comment]
thanks for the reply @renanferrari

> Some designs were using a medium weight on those buttons, while others were using a regular weight. After talking with @mattmiklic we decided to keep them all on regular for now.

Makes sense 👍 

> Yes, that's the Signup Confirmation Screen I mentioned on the PR notes. It will be added on a follow-up PR.

I don't know how I missed that 🤦 

> I hadn't noticed that, but I should be able to address it on the next PR, since it's directly related to that new screen.

Sounds good 👍 . It's not a big deal anyway and I think it was there before.

> I considered giving this a try, but I think @AmandaRiu is currently working on updating the Google Sign-In library, which I'm assuming would address that issue. If not, we can look into this again later on.

👍

**Comment by AmandaRiu** [comment]
> I considered giving this a try, but I think @AmandaRiu is currently working on updating the Google Sign-In library, which I'm assuming would address that issue. If not, we can look into this again later on.

@renanferrari I'm not working on anything having to do with login currently.

**Comment by renanferrari** [comment]
>@renanferrari I'm not working on anything having to do with login currently.

Thanks for letting me know. My assumption was wrong either way, since updating the library [won't fix the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/11650) @planarvoid brought up.

**Comment by renanferrari** [comment]
Hey @mattmiklic 👋 Thanks a lot for taking the time to review this.

>Disabled buttons don't have the new style shown in the design spec (outlined with no fill, with light gray text). 

I'm not sure we will be able to easily change the style of the button _only_ when it's disabled, since we're using the Material Components library and it treats Outlined Buttons and Filled Buttons as two separate styles (not something we could mix and change based on state, AFAIK). I have created a new issue for it anyway: #12242

>And on most screens, the primary button is enabled even before any of the form fields have been filled. Some screens like the site address screen do have disabled buttons.

Good catch! I have created a new issue for this here: #12243 

 >After creating a new account, when I add an avatar, the header is blue with black text (screenshot attached).

I was able to reproduce this with the current version of the app, so I don't think it's related to the changes made here. I'd encourage you to create a new issue for it, if there isn't one yet.

**Pull request merged**
