### PR TITLE
My Site Dashboard - Phase 2 - Stale Message

### PR DESCRIPTION
**Pull request by ashiagr**
Parent #15625

This PR `displays a stale message below the site switcher` whenever (and only when) there's a dashboard update error. Unlike the dashboard error snack bar, it keeps displaying until the update is successful. 

UI 

Light Mode | Dark Mode
------------| -----------
stale_msg_light_mode | stale_msg_dark_mode

To test:

Prerequisites

- Go to `My Site` -> `Me` -> `App Settings` -> `Test Feature Configuration`.
- Turn the `MySiteDashboardPhase2FeatureConfig` feature flag ON.
- Relaunch the app.

1. Login with an account having `wpcom` sites and go to the `My Site` tab.
2. Notice that initially the stale message is not displayed below the site switcher.
3. Update the `CardsSource.getData(...)` and `CardsSource.fetchCardsAndPostErrorIfAvailable(...)` logic to get the `showStaleMessage` to true.
4. Re-install the app.
5. Notice that the stale message is displayed below the site switcher.

## Regression Notes
1. Potential unintended areas of impact
The stale message should not be displayed on login from `self-hosted` site or inside the `Jetpack` app.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See above.

3. What automated tests I added (or what prevented me from doing so)
Added unit tests for the stale message display and order. 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
👋 @osullivanchris! Pinging you so that you can check the stale message UI. I've included screenshots in the PR description.
Feel free to ping the editorial for any copy changes. 🙇‍♀️

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I have reviewed and tested this PR as per the instructions, everything works as expected, excellent work! 🌟 🌟 🌟 🎄 

PS: Feel free to merge when CI completes! 🟢

**Comment by osullivanchris** [comment]
@ashiagr looks good. 2 minor tweaks

- can we reduce the space below the stale message. It looks like its 16dp right now. I think 8dp will be better.
- Now that the message is at the top, I think left-aligned is better. Centre aligned looks a bit out of place now that its at the top.

**Comment by osullivanchris** [comment]
Added Needs Copy Review Label

FAO editorial: this is part of our new dynamic dashboard. Previously the My Site tab was a static list. Now it can show dynamic cards.

- if the user tries to refresh the dashboard we first show a snackbar "Couldn't update dashboard"
- As the snackbar will disappear, we show a small caption at the top of the dashboard so the user knows the data is out of date. it says "Couldn't update dashboard. Check your connection and pull to refresh".
- The intention is to let the user know what they're looking at might be out of date, and tell them what to do to resolve

Any improvements for the Snackbar or the Caption would be welcome.

**Comment by carolynannewells** [comment]
Hello!

This looks good. :)

I would suggest changing the caption to: "The dashboard is not updated. Please check your connection and then pull to refresh"

**Comment by ParaskP7** [comment]
👋 @ashiagr @osullivanchris !

FYI: I have created this #15785 issue to deal with updating the style & copy.

**Pull request merged**
