### PR TITLE
PlayStore Data Safety Report

### PR DESCRIPTION
**Pull request by AliSoftware**
This commits the result of the scan of our source code by [the `privado` open-source tool](https://github.com/Privado-Inc/privado) — presented in [this recent Android Worldwide talk](https://www.youtube.com/watch?v=eEbUwQzfMBo).

## Context

This tools is used to help us [fill the Data Safety report form for Google in the PlayStore](https://support.google.com/googleplay/android-developer/answer/10787469) (see pdnsEh-iy-p2); deadline for submitting that report is July 20, and this `privado` tool can greatly help identifying what we need to report.

 - The `.privado/privacy.json` file in that PR is the result of running `privado scan` on commit 4f5cc64c92bb990ea549875c3886e42af33c29f7 of this repository
   - That scan took more than 30mn to run 😓  — I think one of the reason it took that long is that `privado` apparently also scanned for all the files in `vendor/*` — i.e. the ruby gems and tools we use only for our tooling purposes and have nothing to do with the app's own code.
 - I have already marked a couple of Data Types and Third Parties detected by the tool as "False Positive" for any entry whose occurrences were ONLY on `*.rb` files — as those are used by our ruby tooling, which has nothing to do with what data the mobile app itself might collect.

## How to use the report

From there, to continue with the wizard and generate the report to submit to PlayStore, one can:
 - Ensure they have [Docker](https://docs.docker.com/engine/install/) and [privado installed](https://github.com/Privado-Inc/privado#installation) and set up (see `privado auth` and `privado bootstrap`)
 - Run `privado load .` on this repo to open the privado wizard/web UI in your browser with the existing result of the scan I ran earlier (`.privado/privacy.json`), without having to re-scan the code

## Should we commit this?

This is just an intermediate file for the tool that might help us generate the Privacy Report for PlayStore.
So, after all, once we've generated that report and submitted it to the PlayStore by July 20, we could just ditch that file and close that PR (which is why I've kept that PR as Draft, as I'm not sure if we do want to merge this after all).

But still I think it's nice to have the existence of this preliminary scan available and visible — at least for until we complete the report, and for us and others to see how to `privado` tool works and can be used — hence why I still opened it as a PR.

It could also be useful as a starting point if we need to update the Privacy Report in the PlayStore in the future.

## Screenshots

To give you a taste, here's what the report looks like when opened (in <tt>localhost:3000</tt> after running <tt>privado load</tt>):

<table>
<tr><td colspan="2">dashboard</td>
</tr><tr>
  <td>Data Elements Analysis
  <td>Third Party libs Analysis</td>
</tr><tr>
  <td>DataSafetyReport-1</td>
  <td>DataSafetyReport-2</td>
</tr><tr>
  <td>DataSafetyReport-3a</td>
  <td>DataSafetyReport-3b</td>
</tr><tr>
  <td>DataSafetyReport-3c</td>
  <td>DataSafetyReport-3d</td>
</tr></table>

### CODE REVIEW

**Comment by guarani** [comment]
> Should we commit this?

I think it might be useful to have it committed. At some point, it might make sense to add it to the release process so that developers who manually update the privacy file will see their changes reflected in the apps' Play Store listings.

That said, we would need two separate files, one for the WP app and another for the JP app. There are differences in how each app handles user data. For example, the JP app includes WP.com domain purchases, while the WP app does not.

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

Just FYI that this is now done and the `Data Safety Report` has been completed and published to the PlayStore for both, WordPress and Jetpack apps. I wonder whether this draft PR should be now closed. 🤔

**Comment by guarani** [comment]
Just my 2c: I think it might be valuable to commit the CSV that we submitted to the Play Store, not the report from `privado`. This could be coupled with a PR submissing checklist item that asks whether you've considered if the PR changes the app's privacy practices. 

That would mean that we treat what's committed in the repo as the source of truth, and we'd need to somehow ensure that folks don't just update it from within the Play Store. Without a mechanism for this in place, it might not be worth it. 

I personally see `privado` as a tool we might use for occasional scanning of our repos (including dependency repos), but it doesn't seem worth committing its output to the repo.

**Comment by AliSoftware** [comment]
I agree that since we didn't use `privado`'s output as the source of truth to generate the final report (but more as a starter helper), it doesn't really make sense to commit this after all.

I'd be ok to commit in the repo the actual CSV we submitted to the PlayStore… but I am afraid that the risk would be high that we completely forget to commit any update to that CSV again the next time we make changes to the form in the PlayStore. So I'm not sure it's worth it after all, as it might be more detrimental to us (having two sources of truth — Google Play itself and the commited CSV — that will likely easily diverge over time, making it unclear which is the one to trust) than helpful.

As such, I'm closing this draft PR after all. Thanks all for your inputs!

**Pull request closed without merging**
