### PR TITLE
Create comments block

### LINKED ISSUE #8529: Create a Comments block in Stats
The FluxC endpoint needs to be created first - https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/968

Create a block in the Insights screen that contains two tabs - one contains a list of top commentators of the user's posts/pages and the other contains a list of top commented posts/pages.

The page links to a more detailed view of the data.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #8529 

Add a Comments block to the Stats screen with two tabs - a list of top commenting authors and a list of top commented posts. The view more button links to a more detailed screen (with the original designs).  

To test:
* Open stats
* You see a Comments block
* Switch tabs
* There is a "No data yet" message when the comments are empty
* View more button links to the detail screen

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @planarvoid. The code looks good, however I don't see the comments block on the UI.
screenshot_20181112-170835

**Comment by malinajirka** [comment]
I've just noticed there are errors in the log
```
11-12 17:16:12.899 22088-22088/org.wordpress.android E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/30121039/stats/comments/?max=6&locale=en_US
    com.android.volley.ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 880 path $.authors[1].follow_data
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:89)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 880 path $.authors[1].follow_data
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:83)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125) 
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 880 path $.authors[1].follow_data
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:83) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125) 
11-12 17:16:12.901 22088-22088/org.wordpress.android D/WordPress-API: Receiving OnUnexpectedError event, message: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 880 path $.authors[1].follow_data
```

**Comment by planarvoid** [comment]
@malinajirka I've updated the FluxC version and now it should work. There was something wrong with the `FollowData` field coming from the API

**Comment by malinajirka** [comment]
@planarvoid Thanks for the fix, however I'm still having some troubles on some sites (which don't have any comments).

1. 
```
com.android.volley.ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 162 path $.most_commented_post
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:89)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 162 path $.most_commented_post
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:83)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125) 
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BOOLEAN at line 1 column 162 path $.most_commented_post
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:83) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125) 
```


2. The detail screen is displayed after rotating the device
- open stats
- click on the "View More" button in the Comments section
- press back button
- rotate your device -> the Detail section is displayed + I need to press back button twice in order to get back to stats

**Comment by malinajirka** [comment]
3. Toolbar title issue
- open stats
- click on the "View more" button in the Comments section
- rotate your device
- notice the title in the toolbar is "Stats" instead of "Comments"

**Comment by planarvoid** [comment]
@malinajirka thanks for the comments 👍 
1) This should be fixed with my FluxC update
2) I've introduced an `Event` and `observeEvent` method on `LiveData` that makes sure we only consume the `NavigationTarget` only once so this should be fixed now`
3) I haven't touched that screen so I assume this was there before. I don't think we should fix that as part of this issue. We'll be rewriting these screens in part 2 of Stats Refresh

**Comment by malinajirka** [comment]
LGTM, thanks @planarvoid !

**Pull request merged**
