### PR TITLE
Stats traffic fix graph issues

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes # 
https://github.com/wordpress-mobile/WordPress-Android/issues/20312
https://github.com/wordpress-mobile/WordPress-Android/issues/20311

| Week | Year | Detail |
|--------|--------|--------|
| Screenshot_20240229_184934| Screenshot_20240229_184956|Screenshot_20240229_184915 | 

-----

## To Test:

- Enable Stats Traffic Feature flag
- Open Stats
- Open Traffic tab

#### Bar graph
- Select By week/year
- Verify the bars now start at base, and no gap as in Week, Year images above

#### Detail Views Graph

- Select Posts & Pages card
- Go to detail view
- Ensure the graph is show as in the third image above

-----

## Regression Notes

1. Potential unintended areas of impact

    - No unintended impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - tested all bar charts

3. What automated tests I added (or what prevented me from doing so)

    - existing unit tests

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>TrafficBarChartItem</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/278">24.4</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
@staskus, I can't reproduce the issue of "Weekly and yearly bar chart bars start above 0" on `trunk`. Can you retest it on `trunk` and confirm if it has been resolved in this PR?

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻

**Comment by irfano** [comment]
I'm merging this PR, but I'm unsure if this PR has fixed https://github.com/wordpress-mobile/WordPress-Android/issues/20311. If we reproduce it again, we can reopen the issue.

**Comment by staskus** [comment]
@irfano, thanks for reminding! Just tested it, not reproducible anymore.

**Pull request merged**
