### PR TITLE
Use new newSendAuthEmailAction's method signature

### PR DESCRIPTION
**Pull request by hypest**
FluxC's `newSendAuthEmailAction` has been updated to pass the email via a structure along with more parameters. This PR updates the call which is currently broken.

Needs https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/605 to be merged first.

To test:
* Compile and run wpandroid. It should work.

### CODE REVIEW

**Comment by hypest** [comment]
This PR will be updated with a commit to point to the FluxC hash that includes the change, when it lands.

**Comment by oguzkocer** [comment]
@hypest Since you're afk and the changes in this PR is a blocker for me, I took the liberty to merge `develop` into this branch (to fix app versioning issue for test) and updating the FluxC to the latest. I hope that's OK with you.

**Comment by nbradbury** [comment]
:shipit:

**Comment by hypest** [comment]
Thanks for picking this up and seeing it through while I was AFK!! 🚀

**Pull request merged**
