### PR TITLE
Removes ImageSettingsDialogFragment which is not used anymore

### PR DESCRIPTION
**Pull request by antonis**
## Description
This PR removes `ImageSettingsDialogFragment` which is not used anymore as identified in https://github.com/wordpress-mobile/WordPress-Android/pull/19568#pullrequestreview-1744379496

-----

## To Test:

* Verify that the app builds and the CI checks pass
* Verify that the editor opens and behaves as expected

-----

## Regression Notes

1. Potential unintended areas of impact

 Editor

2. What I did to test those areas of impact (or what existing automated tests I relied on)

 Manual testing

3. What automated tests I added (or what prevented me from doing so)

 N/A since this PR involves code cleanup

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by antonis** [comment]
Converting to draft to figure out the CI failures

**Comment by antonis** [comment]
> Converting to draft to figure out the CI failures

Removed some extra unused resources with e7938b71625c2735ec2957f7a0b539a74cae0d0b :)

**Review by justtwago — APPROVED** [review]
Nice code removal! Tested the editor and it seems to work as usual 👌

**Comment by antonis** [comment]
Thank you for reviewing Artyom 🙇

**Pull request merged**
