### PR TITLE
Remove explore plans from Quick start 

### LINKED ISSUE #16477: Quick Start showing Plans item despite app not showing plan information
### Expected behavior

The "Grow your audience" Quick Start screen should not show an "Explore plans" item. (The plans screen was removed in https://github.com/wordpress-mobile/WordPress-Android/issues/16471, but removing the corresponding Quick Start item was overlooked.)

### Actual behavior

The "Grow your audience" Quick Start screen shows an "Explore plans" item.

#### New site
1. Log in to the app
2. Create a new site
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

#### Existing site
1. Log in to the app
2. Locate an existing site that has not completed its Quick Start steps
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

### Additional information

As @zwarm ([internal reference](p1651671871579959/1651587009.445519-slack-C011BKNU1V5)) mentions:

> it's a bit involved to remove the quickstart task; especially taking into account users who have started on the quick start flow.

so that must be kept in mind when addressing this issue. 

Also, as @thehenrybyrd points out ([internal reference](p1651671795976489/1651587009.445519-slack-C011BKNU1V5)), **_if_** the removal of the Plans screen is temporary, it might be best to prioritize updating the plans and showing the screen again, instead of addressing this issue.

##### Tested on Samsung Galaxy S10, Android 12, WPAndroid 19.7

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #16477 

This PR removes the Explore Plans task from the quick start list and card. 

Internal Reference: p1651666551282059/1651587009.445519-slack-C011BKNU1V5
Corresponding FluxC PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2409

|Before|After|  
|---|---|
|Screenshot_20220517_183221|Screenshot_20220517_182531| 
---

#### Test 1
Explore Plans is Not Shown on Quickstart list 

1.  Login to the app with a quick start in progress
2. Click on My Site -> Next Steps Card
3. Notice that Explore Plans quick start task is not displayed

#### Test 2 - Migration 
Scenario - Test the case where all Quickstart tasks other than Explore Plan is completed, In this task completed notification should be shown to the user in Notifications tab 

Pre- requisites 
For this test, install an app having the `Explore Plans` listed, 

1.  Login to the app with a quick start in progress
2. Complete all tasks other than Explore Plans 
3. Checkout to this branch or Install the build from this PR
4. Notice that Explore Plans is not displayed and Quick start is completed 

---
### Merge Instructions
1. Make sure the dependent FluxC PR is merged 
2. Update FluxC hash
3. Remove Not Ready for Merge 

## Regression Notes
1. Potential unintended areas of impact
- Quickstart progress not shown properly 
- Explore plans tasks being shown 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)
N/A

---
PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — COMMENTED** [review]
Thanks for this PR, @AjeshRPai! 

Overall I find the changes fine, except that in the migration test - step 4 since all `Quick Start` tasks are complete on installing the app from this PR branch, I would have expected following actions:
1. Show `Quick Start` completion notification.
2. Hide `Quick Start` card.

Currently, I see that `Quick Start` card is shown with all items stuck off.  It's not hidden even on pull-to-refresh.

https://user-images.githubusercontent.com/1405144/169239208-5379d07c-a46f-43cb-8162-749f8df1ad70.mp4

It looks like 

1. When we install an app having the `Explore Plans` listed, and only the `Plans` task is left incomplete, `Quick Start` is not marked complete in the DB which should have happened [here](https://github.com/wordpress-mobile/WordPress-Android/blob/e6f8de6e17a3c29a05b62c0dd86f21be776e13d4/WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt#L211).

2. Then when we launch the app from this PR branch, we [show a completion notification](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L907-L919) if every task is marked complete for the site and the completion notification is not yet received. On refreshing the screen, since `Quick Start` is still in progress, [the card keeps displaying](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartCardSource.kt#L45-L50).

I think we can resolve this issue if we [mark `Quick Start` complete explicitly (if not already complete) when we check that all tasks are complete on app launch](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L907-L919) before sending the completion notification. Let me know if it makes sense. 😅

**Comment by AjeshRPai** [comment]
Hey @ashiagr , Thanks for reviewing the PR. 

I was expecting that scenario to work properly as I had tested the scenario you had described in my local and I got
- [x] Show Quick Start completion notification.
- [x] Hide Quick Start card.

I am not sure what went wrong here, I will look into this on priority 

>I think we can resolve this issue if we mark Quick Start complete explicitly (if not already complete) when we check that all tasks are complete on app launch before sending the completion notification. Let me know if it makes sense. 😅

I think this will work. Working on a fix 👍🏼

**Comment by AjeshRPai** [comment]
@ashiagr Thanks for the Input and all the help. The issue you have mentioned in the PR have been fixed by the commit [b7dfd15](https://github.com/wordpress-mobile/WordPress-Android/pull/16582/commits/b7dfd15720c05c8c941695f2872916e8e18e5230). I have implemented the solution you had described. Thanks for the help. 

Now, if only the plans item is remaining before this PR, then after installing the app from this PR the user will 
- [x] Will see a Quick Start completion notification.
- [x] Will not see the  Quick Start card.

**Review by ashiagr — APPROVED** [review]
Thanks for the fix! All looks good to me now.

**Pull request merged**
