### PR TITLE
Feature/reader search toolbar

### PR DESCRIPTION
**Pull request by nbradbury**
This is the first of several PRs which will implement WordPress.com search in the Android reader. This PR doesn't perform any search yet - it simply adds a basic search UI to the reader, which includes:

* Modifying `FilteredRecyclerView` to allow for a menu to be inflated in the toolbar
* Adding a search icon in the reader toolbar which expands to show a standard Android `SearchView`
* Remembering previous searches and using them as suggestions when typing a new search query

Note that the wording used in this PR isn't final - it's simply a placeholder until a later design review.

### CODE REVIEW

**Comment by daniloercoli** [comment]
@aerych - Is it ok if I do a first review of this PR, and call you later for a 2nd opinion?

**Comment by aerych** [comment]
@daniloercoli its all you sir. :)

**Comment by daniloercoli** [comment]
I found a small UI issue if you tap the Search icon while a tag is loading from remote. Steps to repro below:
- Open the reader, and select a tag from the reader toolbar.
- While the Reader is retrieving the content from remote, tap the Search icon.
- The UI shows you the new search input field on the top, and a placeholder view ("Search all public WordPress.com blogs").
- Wait until the content of the selected tag is loaded, and then the main view is switched with the content just retrieved from the server.

**Comment by daniloercoli** [comment]
Seems that the back button is highlighted in the result screen. See the GIF below:

reader-search

**Comment by daniloercoli** [comment]
I see the DB field `query_string` declared as nocase `query_string   TEXT NOT NULL COLLATE NOCASE PRIMARY KEY`, but the suggestions UI seems to remember the case.

screen shot 2016-05-12 at 12 18 48


Should we call a `toLowercase()` on the string before inserting it in the DB?

**Comment by nbradbury** [comment]
> Seems that the back button is highlighted in the result screen.

I see this quite often in the emulator, not just with this PR but with others. I don't see this on a real device, though - are you also only seeing it in the emulator?

**Comment by nbradbury** [comment]
> Should we call a toLowercase() on the string before inserting it in the DB?

I'm not sure if you wanted me to ignore this, but just in case you didn't: I don't think we need to lowercase the string. I think the user would expect to see it remembered using the same casing they used when they entered the query.

**Comment by nbradbury** [comment]
> I found a small UI issue if you tap the Search icon while a tag is loading from remote

Good catch! Fixed in 62317a9.

**Comment by daniloercoli** [comment]
Noticed that with the "Search interface" on the screen the back button closes the app, instead of returning you to the main Reader interface.

**Comment by daniloercoli** [comment]
>> Seems that the back button is highlighted in the result screen.

> I see this quite often in the emulator, not just with this PR but with others. I don't see this on a real device, though - are you also only seeing it in the emulator?

Seeing it on emulators only. Sorry for the false alarm, usually emulators don't have this kind of issue.

**Comment by daniloercoli** [comment]
>> I found a small UI issue if you tap the Search icon while a tag is loading from remote

> Good catch! Fixed in 62317a9.

I see a similar behavior if you start tapping something in the "search field" and then rotate the device.
The string just typed is remembered, but the main UI shows the previous topic items.

**Comment by nbradbury** [comment]
> the "Search interface" on the screen the back button closes the app

Glad you found that one - fixed in 6279f18.

**Comment by nbradbury** [comment]
> I see a similar behavior if you start tapping something in the "search field" and then rotate the device.
> The string just typed is remembered, but the main UI shows the previous topic items.

That turned out to be a nasty one to fix, but it's taken care of now. So, ready for another round. Thanks!

**Comment by daniloercoli** [comment]
> That turned out to be a nasty one to fix, but it's taken care of now. So, ready for another round. Thanks!

Sorry @nbradbury, it seems to partially fix the issue.  he main text is not visible when I turn the device to landscape. See the pictures below.

screen shot 2016-05-12 at 23 01 24

And this happens when I rotate the *emulator*

screen shot 2016-05-12 at 23 01 35

**Comment by daniloercoli** [comment]
@aerych - I've done with the review. If you want to take a look at this PR you're welcome. 
Otherwise, this is ready to be merged.

**Comment by aerych** [comment]
> Otherwise, this is ready to be merged.

Merge away :)  No need to wait for me

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
