### PR TITLE
Post Settings: Small fixes & improvements

### PR DESCRIPTION
**Pull request by oguzkocer**
This is a set of small fixes to Post Settings screen(s) which were documented in various places and didn't fit in other recent PRs. The changes are listed in commit messages.

### CODE REVIEW

**Comment by maxme** [comment]
I'm not sure why you removed the top padding on the category list, from the specs I read:

> Single-line list specs
> 
> Font: Roboto Regular 16sp
> Height: 48dp
> Left and right padding from screen edge: 16dp
> Top padding: 8dp


https://material.io/guidelines/components/lists.html#lists-specs

**Comment by oguzkocer** [comment]
> I'm not sure why you removed the top padding on the category list, from the specs I read:

@maxme It was reported by @tonyr59h [here](https://github.com/wordpress-mobile/WordPress-Android/pull/6058#pullrequestreview-44191952). If it's not a correct change, I can remove that commit.

**Comment by maxme** [comment]
Reported issue was:

> For some reason it really stood out to me that the Tags dialog doesn't have a scrollbar while all the other dialogs with lists do 😆 On that topic, the Select categories dialog scrollbar doesn't go all the way to the top (looks like there's padding)

Padding is normal and should be on every list, not sure about the scrollbar itself behavior, but I don't noticed it until I really paid attention to it.

I'd rebase and drop that commit.

**Comment by oguzkocer** [comment]
@maxme Dropped that commit!

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
