### PR TITLE
[Home Page Picker] Adds sample URL to the Choose a Domain Screen

### PR DESCRIPTION
**Pull request by antonis**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3019

## Description
This PR enhances the Domain Search screen with a sample URL view. 

## To test:

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
1. Press **Skip** or select a domain and press **Choose**
1. Verify that the sample URL view is shown

## Screenshots

|Phone Portrait|Phone Landscape|
|---|---|
|mp|ml|

|Tablet Portrait|Tablet Landscape|
|---|---|
|tp|tl|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hey @kyleaparker 👋 ,
I implemented the domain search sample url enhancement. Let me know if there are any adjustments that should be made.
You can find some screenshots in the description.

**Review by mkevins — APPROVED** [review]
This looks good! I tested on Pixel 3a (physical device) and Pixel C (emulator) and it works as described. Nice work Antonis :+1:

**Comment by kyleaparker** [comment]
This looks good to me! There is just a small problem with the illustration, we shouldn't see the border at the bottom. Is it possible to move the illustration down -1? Otherwise I can try edit the illustration to remove the border, let me know if that would be better :)

**Comment by antonis** [comment]
Hey @kyleaparker 👋 

Thank you for reviewing this 🙇 

> There is just a small problem with the illustration, we shouldn't see the border at the bottom. Is it possible to move the illustration down -1?

Nice catch 👍 
It was actually not a problem with the illustration since I needed to recreate this in code. I fixed it with https://github.com/wordpress-mobile/WordPress-Android/pull/13999/commits/307b3e49ffe769d072b19fa30d0d0585589c262b and updated the screenshots in the description.

**Comment by kyleaparker** [comment]
Looks great!

**Pull request merged**
