### PR TITLE
UI Modernization Post: Add GB icons for Post context menu

### PR DESCRIPTION
**Pull request by zwarm**
Parent #19343 

### This PR is the first in a series which will update the Post list context menu. 

The focus of the PR is to add the gutenberg icon set and apply them to the "matching" context menu item.
- The SVG's were taken directly from the GB javascript files found in this GH [repo](https://github.com/WordPress/gutenberg/tree/trunk/packages/icons/src/library) . The svg part was converted to a Vector Asset using the Android Studio tool. 
- The following file naming pattern was applied to each icon: "gb_ic_iconname" . "iconname" matches the name in the GB repo. 
- At the time of this PR there may have been other GB icons already in the code base; however there was no way to properly identify them. A few icons used the word "new" in the filename; however those files were used in conjunction with an "old/new" feature, so they weren't changed.

**Note**: This PR does **NOT** contain the new context menu groupings or copy changes.

FYI @osullivanchris - Take a look at the context icons; I took the liberty of using GB equivalent icons outside of what you have specified (redo/undo and seen actions). All will change, but I wanted a good starting point within the app so you can review. In this PR the icons are applied to their existing text. Take note of the "contributor draft viewing as contributor" there is a "submit" that uses an older icon. Also, notice that there would also be a view and publish - should we be using "globe" for both of those icons? Anyway, this is a good PR for a quick review. Next PR will apply the updated copy, icons and grouping according to figma (which will take more time) - I wanted to get the icons in so Ajesh can use for Pages work. thanks.

Published | Scheduled | Trashed
-- | -- | --
Alt desc | Alt desc | trashed

Contributor Pending Review viewing as contributor | Contributor Pending Review viewing as editor/owner
-- | --
Alt desc | Alt desc

Contributor Draft viewing as contributor | Contributor Draft viewing as editor/owner
-- | --
Alt desc | Alt desc

Drafts | Published With Blaze capabilities
-- | --
Alt desc | Alt desc

**To test:**
- Install the JP app
- Launch and sign in
- Navigate to My Site > Posts
- Tap on the "more" icon on a post row in the Published tab
- ✅ Verify the new icon set is shown
- Repeat the last two steps for each tab 

## Regression Notes
1. Potential unintended areas of impact
The icons look off

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual/visual testing

3. What automated tests I added (or what prevented me from doing so) N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
The code changes looks good to me. I am approving but not merging so that @osullivanchris  can have a look before merging. 

Also I like the naming pattern you have used here for the icons 👏🏼 

Please feel free to merge this PR

**Comment by osullivanchris** [comment]
@zwarm great start. These look pretty good straight off the bat. 

- this eye icon for view is good to me
- I don't like the submit icon. That's actually our reader icon. Do we have something that means send like a paper airplane, or even an arrow?
- You mentioned redo, undo and seen actions. I don't see any actions like that in our context menus though?

**Comment by zwarm** [comment]
> * this eye icon for view is good to me
+1

> * I don't like the submit icon. That's actually our reader icon. Do we have something that means send like a paper airplane, or even an arrow?
Me either, that's what we use today :( 

The closest I found is "login" - take a look [here](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) - you can see the icons 

> * You mentioned redo, undo and seen actions. I don't see any actions like that in our context menus though?

I don't see anything like that now either; however if we are taking icons from the GB set, these are the icons they use for those actions. Same link as above. 

@osullivanchris  - Forgot to say thanks!

**Comment by osullivanchris** [comment]
@zwarm what about postAuthor for 'submit for review' - kinda gives the idea of another person and writing, makes sense to me.

Ok I got it, so you're reusing the redo/undo and seen for other purposes? I see where you're using seen but I still don't see where you are using undo/redo or what you're getting at there, sorry 😄

**Comment by zwarm** [comment]
> Ok I got it, so you're reusing the redo/undo and seen for other purposes? 

@osullivanchris 
Nope, I am not currently reusing them for anything outside of this project. My bad, I don't think I am explaining myself properly. 🤦 

I imported the GB icon set equivalents to the existing context menu: edit/trash/duplicate/redo/undo/move-to/etc., and plopped them into the as-is post list context menu for you to preview in-app. I did not include an example of where the redo/undo are used, but they are part of the error actions and I couldn't trigger the event (I will retry to get some).

For example: the figma spec uses the pencil for the "move-to" draft menu item, the GB equivalent for "move-to" is the arrow I show in this PR. Our project does NOT need to line up with the GB icon. I will absolutely use the "pencil" for "move to drafts", but I really just wanted you to have a live view of what the current mapping to GB would be without applying the figma icons first. 

Hope that helps.

**Comment by osullivanchris** [comment]
aha got it @zwarm. I'd actually rather use the GB icons wherever possible so there is no need to revert to what I have in Figma. I am happy to go ahead with what I see here and I'll let you know otherwise.

One thing that just came up on slack - the 'eye' icon is a bit creepy for 'View'. We could use 'external' which communicates the idea of seeing what the post looks like in a browser.

**Comment by zwarm** [comment]
@osullivanchris 

> One thing that just came up on slack - the 'eye' icon is a bit creepy for 'View'. 

Yes it is; glad I wasn't the only one who thought this. It feels like half a person. lol

> We could use 'external' which communicates the idea of seeing what the post looks like in a browser.

Excellent choice. I shall adjust and then merge this. A forthcoming PR will have the icon/copy updates. Over on Android we are still exploring ways to add the divider line in the context menu, we don't get it out of the box :( . Never easy with Android.

Thanks so much for seeing this one through. 
:)

**Pull request merged**
