### PR TITLE
Issue/list row padding

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update item row layout for ***Sites*** and ***Me*** to show full-width background when pressed.  Consequently, this also updates the width of the card view for ***Me*** to be evenly spaced.  See the screenshots below for illustration.

row_padding

### Test
1. Go to ***Sites*** tab.
2. Long-press any row item.
3. Notice background is full-width.
4. To go ***Me*** tab.
5. Long-press any row item.
6. Notice background is full-width.
7. Notice card view is evenly spaced.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Awesome!

**Comment by khaykov** [comment]
@theck13 this branch developed some conflicts :)

**Comment by mzorz** [comment]
> I'll check the code after fixing conflicts and resolving history but functionality looks good

Same here - let's resolve commit history 👍

**Comment by theck13** [comment]
I don't know what happened to this branch's history previously so I just killed it and rewrote the code.  The changes are ready to be reviewed again.

**Comment by mzorz** [comment]
There's conflicts now 🤔 - feel free to merge after resolved

**Comment by theck13** [comment]
The conflicts have been resolved.  The changes are ready to be reviewed again.

**Pull request merged**
