### PR TITLE
Support for numeric-only tags in posts

### LINKED ISSUE #8008: Unable to Add Tags That Only Consist of Numbers
### Expected behavior

I expected to be able to add tags that only consist of numbers, for example "2018".

### Actual behavior

Tags that only consist of numbers are automatically stripped out when added via the app.

### Steps to reproduce the behavior

1. Navigate to My Site > Blog Posts and edit a post.
2. Tap the three dots to the upper right of the post editor to get to "Post Settings".
3. Add multiple tags to the post, including some that only consist of numbers ("2018", for example).
4. Update your changes then view the post's tags.

##### Tested on Pixel, Android 8.1.0, WordPress for Android alpha 116

This was reported to us in 1265772-z

### PR DESCRIPTION
**Pull request by hypest**
Fixes #8008 

The solution to issue resides [on the FluxC side](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/847) so, no changes introduced in this PR other than pointing to the FluxC version with the fix.

I will update this PR after the FluxC side PR is merged.

To test:

1. Navigate to My Site > Blog Posts and edit a post.
2. Tap the three dots to the upper right of the post editor to get to "Post Settings".
3. Add multiple tags to the post, including some that only consist of numbers ("2018", for example).
4. Update your changes then view the post's tags.
5. The new tags should be there, both on the mobile and on the web

### CODE REVIEW

**Comment by oguzkocer** [comment]
@hypest I am happy to review this when it's time, but I think it might be better for the FluxC reviewer to also merge the WPAndroid PR especially since it's just a hash update. They'll have more context about the change and it will be less of a focus shift for them. What do you think?

P.S: I might end up reviewing the FluxC PR as well, in which case this comment will be meaningless. 👀

**Comment by oguzkocer** [comment]
> Happy to have it reviewed/merged by you! Feel free to pick it up if you feel you have the spare time

@hypest I can't do it this week, so hopefully someone grabs it soon, but if not I can definitely review them for you.

**Comment by oguzkocer** [comment]
@hypest The FluxC PR is merged, so we can update the hash in this one :)

**Comment by loremattei** [comment]
Hey! I'm moving the milestone to 10.7 because 10.6 has been cut. Please, feel free to move it back to 10.6 if it has to land there: update it to target the release branch and ping me to update the build!

**Comment by oguzkocer** [comment]
@hypest Do you mind updating the FluxC hash so we can merge this in? Thanks!

**Pull request merged**
