### PR TITLE
Issue/3799 appcompat wp widgets

### LINKED ISSUE #3799: Switch to "AppCompat" versions of WPxxx widgets
For example, `WPTextView` should extend `AppCompatTextView` rather than `TextView`. The AppCompat versions:

* Support textAllCaps style attribute which works back to Eclair MR1
* Allow dynamic tint via the background tint methods in ViewCompat
* Allow setting of the background tint using backgroundTint and backgroundTintMode attributes

Note: this should wait until the [Open Sans PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3796) is merged, since that renames some our widgets.

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #3799 

* Updated WPButton, WPCheckBox, WPRadioButton and WPTextView to extend AppCompat variations
* Removed `fixWidowWords` from WPTextView and switched to `android:breakStrategy="balanced"` in layouts/styles

cc: @maxme

### CODE REVIEW

**Comment by maxme** [comment]
Apparently `android:breakStrategy="balanced"` doesn't produce the expected result on widow words, example on a 1440x2560 - 560dpi screen (Nexus 6):
screenshot-2016-03-03_11 54 43 622

On `develop` (same screen):

screenshot-2016-03-03_11 59 40 518

**Comment by nbradbury** [comment]
> Apparently android:breakStrategy="balanced" doesn't produce the expected result on widow words

I was just wondering whether we should stick with `fixWidowWords` since android:breakStrategy` is only supported on API 23+. How about I kill this PR, then submit one which just switches to the AppCompat views?

**Comment by maxme** [comment]
> I was just wondering whether we should stick with fixWidowWords since android:breakStrategy` is only supported on API 23+.

Should that work with `AppCompatTextView`? This is why we want to use app compat views, or I missed something?

**Comment by nbradbury** [comment]
> Should that work with AppCompatTextView? This is why we want to use app compat views, or I missed something?

Nope, as noted in [the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/3799) the AppCompat versions:

* Support textAllCaps style attribute which works back to Eclair MR1
* Allow dynamic tint via the background tint methods in ViewCompat
* Allow setting of the background tint using backgroundTint and backgroundTintMode attributes

So, AppCompatTextView doesn't support `breakStrategy` (unless you're using API 23+). I was wondering why you added using `breakStrategy` to that issue :)

**Comment by maxme** [comment]
> So, AppCompatTextView doesn't support breakStrategy (unless you're using API 23+). I was wondering why you added using breakStrategy to that issue :)

**Pull request closed without merging**
