### PR TITLE
Show a notification with a Share Link button when a Post has been uploaded

### LINKED ISSUE #3172: When a post is uploaded, show a "Post uploaded" notification with a "share link" button
Example: Google Drive

### PR DESCRIPTION
**Pull request by maxme**
fix #3172: Show a notification with a Share Link button when a Post has been uploaded

### CODE REVIEW

**Comment by nbradbury** [comment]
A few issues here:

* Tapping the push notification doesn't do anything.
* The notification doesn't disappear after you tap the share button. Should it?
* The share button appears even if the post is a draft, or is private, or is pending review, or is scheduled.
* Instead of "Share link" I think simply "Share" is sufficient.
* If I publish multiple posts in a row, the share button only appears for the last one (see screenshot below)

device-2015-09-11-141351

**Comment by maxme** [comment]
> Tapping the push notification doesn't do anything.

Right, it should open the post.

> The notification doesn't disappear after you tap the share button. Should it?

I don't think it should disappear (swipe to dismiss), share to facebook then twitter, or mistaped the app? Just tested with Google Drive, it doesn't disappear after sharing.

> The share button appears even if the post is a draft, or is private, or is pending review, or is scheduled.

Good catch.

> If I publish multiple posts in a row, the share button only appears for the last one (see screenshot below)

That's how Android handle notifications. Hide the first notification, you'll see the button on the next one.

**Comment by nbradbury** [comment]
> That's how Android handle notifications. Dismiss the first notification, you'll see the button on the next one.

TIL.

**Comment by roundhill** [comment]
> TIL.

You can also swipe down with two fingers to expand the notification!

**Comment by roundhill** [comment]
Hey @drw158, any thoughts on the working/design here?

**Comment by maxme** [comment]
> > Tapping the push notification doesn't do anything.

> Right, it should open the post.

I tried to open the Post Preview but that broke the app flow if you've another tab opened (notifications for instance). So I'm now opening Post List when tapping the notification. ref 	9e18074

**Comment by maxme** [comment]
> This is an edge case, but if the user switches blogs while the post is uploading, tapping that notification will open the post list for the newly selected blog rather than the one the post is in.

We're using `WordPress.getCurrentBlog()` in `PostsListFragment`, `EditPostActivity`, `EditPostSettingsFragment`, and other places that could be run from the Post List, so we can't open the corresponding post list without creating other issues. We can eventually show a toast "Post/Page was published in another Blog" on the Post List, or deactivate the action on click.

**Comment by drw158** [comment]
Looks good! I definitively like "Share" better than "Share link".

What's the reasoning with the up arrow icon? Is that a default system icon? What icons do we have to choose from?

**Comment by maxme** [comment]
> What's the reasoning with the up arrow icon? Is that a default system icon? What icons do we have to choose from?

Yes this is the default "upload" Android icon (but we can change it). It's animated in the notification bar when the post uploads. Animation stops when the upload stops.

Example with a post containing a picture:
https://cloudup.com/cOVpX9FCAZt

**Comment by drw158** [comment]
@maxme Great, that makes sense. :+1:

**Comment by nbradbury** [comment]
Looks good :shipit:

**Pull request merged**
