### PR TITLE
Reader related posts design review

### PR DESCRIPTION
**Pull request by nbradbury**
This PR is for a design review of the already-merged [related posts](https://github.com/wordpress-mobile/WordPress-Android/pull/4269) feature.

Needs review: @jancavan

### CODE REVIEW

**Comment by jancavan** [comment]
- There needs to be a divider in between posts that's the same color as the border around it:

screenshot 2016-07-01 16 19 18

- When you're a few levels deep into related posts, there isn't a way to go back to the previous page. Related Posts is like a "dismissible slide in panel" where you x out of it and can only go back to the first full-post view:

**Current flow:**
related-posts-flow

**Suggested flow:**
related-posts-flow-2

- There's a bit too much top/bottom padding for the first/third items in the list:

padding

Padding around each related post should be equal similar to:
equal-padding

- A `border-radius` of `2px` for the images would be nice.

- Author and site name currently link to the article itself. They should link to that site's stream.
screenshot 2016-07-05 12 42 45

**Comment by nbradbury** [comment]
> There needs to be a divider in between posts that's the same color as the border around it

Corrected in 2a0bcee.

> When you're a few levels deep into related posts, there isn't a way to go back to the previous page.

There actually is, but it's a little unusual. The "X" in the toolbar always returns you to the original post, but the Android back button enables navigating backwards one related post at-a-time. There was [some discussion](https://github.com/wordpress-mobile/WordPress-Android/pull/4269#issuecomment-228175986) about this on the original PR, and it's a pattern that Twitter uses.

> There's a bit too much top/bottom padding for the first/third items...Padding around each related post should be equal

Fixed in 3f7955e

> Author and site name currently link to the article itself. They should link to that site's stream.

The entire box for each related post links to the article. Having the author & site name link elsewhere would be a bit of a crapshoot - that's a fairly tiny tap target and could easily be tapped when the user just meant to tap to view the article. I'd prefer to leave this the way it is.

> A border-radius of 2px for the images would be nice.

Added in 5998f40.

**Comment by nbradbury** [comment]
@jancavan Thanks for your input - ready for another round! As always, if supplying screenshots would be easier than requiring you to build the app, let me know.

**Comment by jancavan** [comment]
Thanks @nbradbury. I was  afk so just got a chance to review this.

Not sure if this is just appearing on my emulator, but there seems to be a tiny border around the images which shouldn't be there:

screenshot 2016-07-18 13 57 03

Sorry I didn't notice this earlier, but on Calypso:

- We have omitted "by" from the byline
- To avoid repetition, if both Author and Site names are the same, we just display the Site name:

**Android:**
screenshot 2016-07-18 14 04 31

**Calypso:**
screenshot 2016-07-18 14 04 54


- If there isn't a Site name, the URL is displayed

**Comment by nbradbury** [comment]
> We have omitted "by" from the byline

Fixed in 1f963dd

> if both Author and Site names are the same, we just display the Site name

Fixed in 49b0c07

> If there isn't a Site name, the URL is displayed

Fixed in b9d17ed and dcf6ba1

> there seems to be a tiny border around the images which shouldn't be there

Fixed in 5e0209d

**Comment by nbradbury** [comment]
@jancavan I've addressed the issues you raised, so ready for another round again :)

**Comment by jancavan** [comment]
Looks great 👍  🚢

**Comment by kwonye** [comment]
I am having issues compiling as it seems my `WPImageUtils.getRoundedEdgeBitmap(Bitmap bitmap, int radius, int color)` isn't showing up, but because Travis is fine and I was able to compile commenting that out, :shipit:

**Pull request merged**
