### PR TITLE
[do-not-merge] #13892 date range picker

### PR DESCRIPTION
**Pull request by cray85**
Fixes #
13892

To test:

First pull associated FluxC PR branch from https://github.com/cray85/WordPress-FluxC-Android-Enhancements/tree/issue/WPMobile13892-mediastore-date-range-support - then modify local project properties accordingly
 

Go to Media from home screen and select date range picker (currently an icon in the action bar), then select your preferred date range. After range is updated, press X on date range indicator above gallery to reset.
## Regression Notes
1. Potential unintended areas of impact

Coming soon

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Coming soon

3. What automated tests I added (or what prevented me from doing so)

Coming soon

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
Hi @cray85 :wave: :smiley: . Thank you for working on this! Since this is still in draft, I have not thoroughly tested various scenarios, so I'll just comment on what I've observed so far in my testing.

#### Online mode
I was able to use the feature nicely. I tried filtering by date, and it works as expected. I also tried updating the filter, and as well as clearing the filter, and these flows also work as expected.

I also tested the media type tabs, and the date filter is also working nicely with those. :tada: 

#### Offline mode
The current state of the code has a limitation regarding offline error handling. As already discussed, there is an issue with error handling when the local db tries to sync with the server, so updating the filter while offline is not working yet. Do you think this is something that we'll be able to address in this PR? If not, do you have any fall-back mechanisms in mind? E.g., would it be possible to detect that the network is unavailable and hide the feature if we cannot support it in that scenario?

Generally, I think it would be good to also somehow mitigate the following scenario:

1. Navigate to the media library
2. Apply a filter (online, and working correctly)
3. Lose service (or put on airplane mode)
4. Try to clear the filter (so we can see the already downloaded media) :x: :point_left: we hit a dead end here.

Wdyt? Any approaches to consider for solving that?

#### Design
Before landing this, it'd be great to get some design feedback about the filter bar. I don't have any feedback (except that I agree with your changes to avoid the large icon obscuring the screen's title). I wonder if there is anywhere else to put the button without having the filter row present when the feature is not active :thinking: . We can circle back to this when the PR is ready for review (and has an APK generated), but if any ideas come to mind, feel free to mention them. :+1:

**Comment by cray85** [comment]
> Generally, I think it would be good to also somehow mitigate the following scenario:

Hey @mkevins. Thanks for the detailed comments. Currently the fetch logic is to delete any uploaded media items from the database that are not included in the response. We can send the date range parameters in `FetchMediaListResponsePayload` to make sure that only the records between those dates are cleaned up before `MediaGridFragment` attempts to read the database again.

The corollary to this is that the filtering method in `MediaGridFragment#getFilteredMedia()` and the methods it invokes in FluxC must also be updated to accept the date range parameters as the database would end up including records not meant to be displayed when the filter is enabled. But as a consequence the app would be able to support offline/error-state date filtering. Upon date range change/clear, the logic will be changed to first load from database with the given parameters.

**Comment by cray85** [comment]
> Wdyt? Any approaches to consider for solving that?

I have implemented the above proposed solution and updated the PR.

**Comment by mkevins** [comment]
Hi @cray85 , I've tested the PR after the latest changes, and I've run into a few more issues.

The first thing I noticed is that an image that I recently added was not shown in the "All" tab when filtered by date. In the video below, I expect the top most image in the grid before the filter is applied to remain after the filter is applied.

https://user-images.githubusercontent.com/8507675/180921245-fc87c398-4590-4573-b8d7-f493ad5817da.mp4

Is there perhaps some fence-post issue with the date range?

The next issue I encountered is that the video tab seems to sometimes have the filter applied, and sometimes not. In the following video, I follow the same steps twice, with different results the second time. Steps:

1. Apply the filter on the "All" tab
2. Navigate to the "Images" tab
3. Navigate to the "Videos" tab (videos are not filtered)
4. Navigate to the "All" tab
5. Clear the filter
6. Repeat steps 1-3: (this time videos _are_ filtered)

https://user-images.githubusercontent.com/8507675/180921491-137c31fa-cf6f-4ba1-8338-03d04865c17c.mp4

While offline, the filtering on the "All" tab seems to be working (aside from the missing image mentioned earlier):

https://user-images.githubusercontent.com/8507675/180922070-fb65f319-ac80-4a1f-a5d4-32e98d8565d6.mp4

Another strange issue I observed while _online_ is that videos seem to disappear at times, when switching to the all tab and back again:

https://user-images.githubusercontent.com/8507675/180922213-b535f2e9-9cfd-4fd3-930e-83df0174243e.mp4

**Comment by cray85** [comment]
Hi @mkevins - I'll have a look. Did you add the image in the app itself or elsewhere?

**Comment by cray85** [comment]
Hi @mkevins - I'll have a look. Did you add the video in the app itself or elsewhere?

Edit: PR updated with fixes.

**Pull request closed without merging**
