### PR TITLE
Issue/update color scheme

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the color scheme to Classic Bright to match the color changes described in https://en.blog.wordpress.com/2019/01/08/customize-your-wordpress-com-dashboard.  These changes include updating color values, refactoring color names, renaming file names based on the new color values/names, and removing unused colors.  There are no functional changes.

### Test
An alpha build can be downloaded from [here](https://drive.google.com/open?id=1fpHKCGQXeJrfe8y3FjkxeAw5bVSYi-pe).  It will be installed alongside the production build (i.e. two WordPress apps will be on the device; one production and one debug) so changes can be compared on the same device.

### Review
The code review should not worry about the color names or specific changes to the color of the interface, but it should check that there are no breaking changes.  The design and interface have been reviewed multiple times by @mattmiklic, but it should still be reviewed again to ensure nothing was missed.

### Release
The `RELEASE-NOTES.txt` document was updated in 443b2de with the following:
> Updated color scheme to Classic Bright

### CODE REVIEW

**Comment by theck13** [comment]
Thanks for the review and catching those bugs, @0nko!

I added resources to override the login library colors in a9ba165.  See the screenshots below for illustration.

color_login_button_input

color_login_progress

You'll notice the button color was updated to `accent` (`#d52c82`) also.  That's a pleasant side effect since we were going to update the buttons to that color in a subsequent pull request anyway.  @mattmiklic, can you confirm that's desired behavior?

I removed the custom selectable background drawable in af1657a.  See the screenshots below for illustration.

color_pages_menu

I think the toolbar touch feedback color is correct since the app theme's parent style is `Theme.AppCompat.Light.DarkActionBar`.  I checked other apps with a dark toolbar and light text/actions.  They had the same touch feedback.  See the screenshots below for illustration.

color_toolbar_feedback

I'm not sure why the page modification icon color shows up as dark yellow, which I think is warning_700` (`#bd9219`), rather than white on your device.  It is shown as white when I tested it.  See the screenshot below for illustration.

color_activity_modified

Can you share how you got to that screen in case there are certain steps to reproduce it?

**Comment by mattmiklic** [comment]
Thanks for catching those spots I missed, @0nko!

> @mattmiklic, can you confirm that's desired behavior?

Yes, that's perfect, the pink buttons look great there.

I noticed in your before/after login screenshot that I think the "log in with google" and "log in by entering your site address" links are maybe still using the old blue -- if so we should change those to `primary` blue.

**Comment by theck13** [comment]
> I noticed in your before/after login screenshot that I think the "log in with google" and "log in by entering your site address" links are maybe still using the old blue -- if so we should change those to `primary` blue.

I added color resources for the login button text color in 6e4bc09.  See the screenshots below for illustration.

color_login_button_text

I updated the background color for shortcuts too in order to follow the guidelines [here](https://commondatastorage.googleapis.com/androiddevelopers/shareables/design/app-shortcuts-design-guidelines.pdf).  See the screenshots below for illustration.

color_shortcuts

**Comment by mattmiklic** [comment]
Good catch on the shortcuts. Those links now look good. 👍

**Comment by 0nko** [comment]
Thanks for the changes, @theck13. It looks great 👍.

**Pull request merged**
