### PR TITLE
Update dashboard card domain to v2

### LINKED ISSUE #18280: Domains Dashboard Card: Card UI v2
**Specification:** pc8eDl-LC-p2

Create Domains Dashboard Card

## Requirements

1. The card should resemble the design requirements
2. The card should support light and dark mode
3. The card should support accessibility and voice-over features
4. The card should show "domain. Blog" static text (Use [Domains Dashboard Card UI v2.1 SVG.zip](https://github.com/wordpress-mobile/WordPress-Android/files/11269440/Domains.Dashboard.Card.UI.v2.1.SVG.zip))

## Design

(Card) Domain Upsell – iOS Light
(Card) Domain Upsell – iOS Dark

### PR DESCRIPTION
**Pull request by ravishanker**
Updating dashboard card domain ui to match latest v2

Fixes #18280 

| Light | Dark | Bold text
|--------|--------|--------|
| Screenshot_20230426_103917 | Screenshot_20230426_103937 | Screenshot_20230426_104020 |

To test:

- Launch Jetpack/WordPress app
- Verify **domain card** appears as shown above on dashboard
- Switch to dark/night mode
- Verify **domain card** matches the dark version

Additionally use the UI changes checklist

- **Tap** on **domain card**
- **Verify** that it launches domains search
- Tap on overflow (three dots) menu
- **Verify** it pops up menu with **Hide this** option
- Tap on Hide this
- **Verify**, the card gets hidden 

Also, do some relevant test from the UI Changes Checklist below

>** Note **
> The browser image needs to be updated, waiting for a final version.  Will update before merging

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by staskus** [comment]
@ravishanker 

[Designer updated the assets with a static text](https://github.com/wordpress-mobile/WordPress-Android/issues/18280#issuecomment-1514201417)

**Comment by staskus** [comment]
**Note:** 

The previous version of the card supported all the accessibility features except the bold text. Maybe a good chance to introduce it.

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻 The only issue is on the title in RTL layout. It's still aligned to the left. I'm approving, we're good to merge after fixing it.

**Comment by irfano** [comment]
> The previous version of the card supported all the accessibility features except the bold text. Maybe a good chance to introduce it.

I noticed the issue in bold text. It would be nice if we could fix it now, but the [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/18274) was already opened to be fixed later.

**Comment by ravishanker** [comment]
> The previous version of the card supported all the accessibility features except the bold text. Maybe a good chance to introduce it.

Fixed for this card in 904bfd30234d5f7128d45984c5c7dcaa4aec67cc

**Comment by ravishanker** [comment]
> The only issue is on the title in RTL layout. It's still aligned to the left.
> 
It seems to work find in LTR layout.  What locale were you using?  (Translations are not in place just yet)

**Comment by irfano** [comment]
> It seems to work find in LTR layout. What locale were you using? (Translations are not in place just yet)

👍🏻 I suppose it didn't work because I used the "Force RTL" option in the developer settings, and the translation was missing. Next time, I should test it by changing the language instead of using "Force RTL".

**Pull request merged**
