### PR TITLE
Issue/13326 scan screen UI iteration 1

### PR DESCRIPTION
**Pull request by ashiagr**
Parent #13326

This PR makes small UI improvements to the Scan screen for scan state items:
- Separates primary and secondary buttons
- Add icon margin, size dynamically (for different margins, sizes on scan and threat details screen)
- Adds vertical and horizontal margins to the scan screen items

To test:

That scan states UI is rendered properly:

|scan ok|scanning|threats found|fixing|
|---|---|---|---|
|scan_okay|scanning|threats_found|fixing

Notes:

1. Review by commits might be easier
2. Yet to add CTA for "here to help" - added to backlog

Merge Instructions

- Make sure PR #13872 is merged to develop
- Remove the "Not Ready for Merge label"
- Merge this PR

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by malinajirka — COMMENTED** [review]
Thanks @ashiagr, the changes look good overall. I noticed one minor issue - the icon on the "scanning" doesn't match the designs.


SideNote: I'm still not sure about the JetpackIconViewHolder - I'm wondering if re-using this part is worth it. We might want to consider having a Header for scan screen and a different header for detail screen. Wdyt?

**Comment by ashiagr** [comment]
Thanks for the review @malinajirka!

> SideNote: I'm still not sure about the JetpackIconViewHolder - I'm wondering if re-using this part is worth it. We might want to consider having a Header for scan screen and a different header for detail screen. Wdyt?

This view holder is reused on other screens too: backup, restore etc. I can discuss with @zwarm and decide upon it. 

> the icon on the "scanning" doesn't match the designs.

I'll look into it, seem like dynamic tinting is causing some issues.

**Comment by ashiagr** [comment]
> the icon on the "scanning" doesn't match the designs.

@malinajirka I couldn't find a solution to this problem yet. I've replaced the icon with the one without stroke and added this issue to the backlog.

Screenshot 2021-01-25 at 6 50 14 PM

Ready for another round!

**Review by malinajirka — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
