### PR TITLE
[Jetpack Content Migration Flow] Implement Error Screen support

### LINKED ISSUE #17489: Android - Error Screen
This task is to implement the error screens UI in the WordPress to Jetpack migration flow.

### Designs:
**Note** _Designs are  iOS specific, slight differences may apply on Android_

| Networking Error | Generic Error |
| - | - |
|  |  |

Functionality:
- The screen appears after `Continue` is tapped on the Welcome Screen, if errors prevent a successful migration.
- `Try Again` should retry data migration
- `Need Help` should open the Help/Support screen specific to the migration flow.

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #17489

This PR adds support for showing the error screens (Networking & General) in the WordPress to Jetpack migration flow.

There's only one final type for the errors in `UiState.Error`, while not ideal this limitation was enforced by the need to show a processing state on these screens, and using distinct types for each error resulted in too much complications by having to cast each error type in order to change the `isProcessing` flag. Providing the specifics for each error type is done by instantiating the `Error` data class with the right values via 2 different methods. Ideally we would have 2 different error types but as explained this would result in over-complication of the code.

Adaptation of the header icon for dark mode is not handled, to be done together with adapting the the icons for all other migration flow screens in:
- https://github.com/wordpress-mobile/WordPress-Android/issues/17491

> 🏁 **All these changes are behind a temporary feature flag.**

To test:

 <details>
   <summary><b>Prerequisite</b> - local changes to show error screen</summary>

   <br>

   Replace `tryMigration()` in `JetpackMigrationViewModel.kt:73` to test errors:
   https://github.com/wordpress-mobile/WordPress-Android/blob/f77ec1e4c81773731f0be7d371c5d3b207c69e87/WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt#L70-L75
   - Replace with `postGenericErrorState()` to test the **Generic Error**
   - Replace with `postNetworkingErrorState()` to test the **Networking Error**
---
</details>

0. Checkout the branch of this PR locally
1. Modify the locally checked out code to show one of the errors when `Continue` is tapped on the Welcome Screen — see **Prerequisite** collapsible panel above.
2. Open the Jetpack app & login
3. Toggle the temporary feature flag (this is only needed once)
   a. Go to `Me` → `App Settings` → `Debug Settings`
   b. Enable the `JetpackMigrationFlowFeatureConfig` & restart the app.
4. Tap the `Continue` button on the "Welcome to Jetpack!" screen
5. **Expect** to see one of the error screens (depending which one was added via local changes)
6. **Verify** that the error screen matches the design
7. Tap `Need help?`
8. **Expect** To see the Support Screen customized for the migration flow (see PR [#17449](https://github.com/wordpress-mobile/WordPress-Android/pull/17449))
9. Go back
10. Tap `Try Again` on the error screen
11. **Expect** to see a processing state simulating the migration progress
12. **Expect** to land on the "Notifications now come from Jetpack" screen

📣 Please test both errors (Generic & Networking), with each variation via local changes:
- `postGenericErrorState()`
- `postNetworkingErrorState()`

### Previews

| Generic Error | Networking Error |
| - | - |
|  |  |

## Regression Notes
1. Potential unintended areas of impact
   N/a - Changes are behind feature flag.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
   N/a

4. What automated tests I added (or what prevented me from doing so)
   N/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mkevins — APPROVED** [review]
Great work Ovi! The code looks good and this works as expected. I tested per the instructions on a Pixel 3a (physical device). :+1:

**Comment by ovitrif** [comment]
> Great work Ovi! The code looks good and this works as expected. I tested per the instructions on a Pixel 3a (physical device). 👍

Thank you @mkevins 🙇 !

I was thinking of adding this change to the error `UiState` in order to have 2 different error types:

```kt
data class Error(
    val primaryActionButton: ErrorPrimaryButton,
    val secondaryActionButton: ErrorSecondaryButton,
    val type: ErrorType,
    val isProcessing: Boolean = false,
) : UiState() {
    @DrawableRes val screenIconRes = R.drawable.ic_jetpack_migration_error

    sealed class ErrorType(
        val title: UiString,
        val subtitle: UiString,
        val message: UiString,
    )

    object Generic : ErrorType(
            title = UiStringRes(R.string.jp_migration_generic_error_title),
            subtitle = UiStringRes(R.string.jp_migration_generic_error_subtitle),
            message = UiStringRes(R.string.jp_migration_generic_error_message),
    )

    object Networking : ErrorType(
            title = UiStringRes(R.string.jp_migration_network_error_title),
            subtitle = UiStringRes(R.string.jp_migration_network_error_subtitle),
            message = UiStringRes(R.string.jp_migration_network_error_message),
    )
}
```

With it, instantiating a specific error would look like this:
```kt
_uiState.value = UiState.Error(
        primaryActionButton = ErrorPrimaryButton(::onTryAgainClicked),
        secondaryActionButton = ErrorSecondaryButton(::onHelpClicked),
        type = Generic,
)
```

Wdyt, is it worth it? This way we can still have 2 different types for errors and avoid having to specify the title, subtitle & message since they are predefined, aligned with how we actually already know them.

If it makes sense I'll add this change, otherwise feel free to merge 🙇 

P.S. Maybe it's not the most common pattern, to put implementations of a sealed class outside of it, but it felt to me there's too much nesting if I'd be to add the objects inheriting `ErrorType` inside the sealed class 😅 .

**Comment by mkevins** [comment]
> Wdyt, is it worth it? This way we can still have 2 different types for errors and avoid having to specify the title, subtitle & message since they are predefined, aligned with how we actually already know them.

Thanks for considering different approaches :+1:  I don't have a preference in this case, so I'd say do what makes the most sense to you to reason about it. Fwiw, the data layer has _many_ possible error types, but those are more useful for diagnostics, tracking, graceful fallback, etc. and will probably almost all be mapped to a "generic" error in the UI. I'm not :100: sure that a network error will be common, considering that most users will have just downloaded the app from the store - but maybe that assumption is invalid :man_shrugging: .

**Comment by ovitrif** [comment]
> Thanks for considering different approaches 👍 I don't have a preference in this case, so I'd say do what makes the most sense to you to reason about it.

Thank you for your feedback Matthew 🙇 , the current approach isn't that suboptimal imho, though the [update](https://github.com/wordpress-mobile/WordPress-Android/pull/17492#issuecomment-1321854617) would add a bit more structuring.

I'll push an update to include it 😄

**Comment by ovitrif** [comment]
> I'll push an update to include it 😄

@mkevins Done, if everything looks ok this is ready to merge 🙇

**Comment by mkevins** [comment]
Looks great! Thanks for the effort on this Ovi!

**Pull request merged**
