### PR TITLE
fix #3807: c2d message permissions conflict

### LINKED ISSUE #3807: Make sure C2D_MESSAGE permission is correctly set for all flavors
And make sure PNs work with wasabi

### PR DESCRIPTION
**Pull request by maxme**
fix #3807: c2d message permissions conflict

<s>Note: PNs are currently not working with this version: a server side patch is coming soon, I'll remove the "Not Ready for Review" lable when it's merged.</s>

### CODE REVIEW

**Comment by maxme** [comment]
Ready for review

**Comment by tonyr59h** [comment]
Changes look good and PN's are being received on both flavors, makes sense to use `applicationId` since the package name is inconsistent.

One thing I don't think I'm fully understanding is how the permissions conflict presents. Is it that a PN will only be received by one of the flavors if both are installed?

**Comment by maxme** [comment]
> One thing I don't think I'm fully understanding is how the permissions conflict presents. Is it that a PN will only be received by one of the flavors if both are installed?

No, Android doesn't let you install a second application with the same defined permission and a different signature. So before the patch: if you install Vanilla Release on a device, you can't install Wasabi Debug, they had different applicationIds but the same C2D_MESSAGE permission name.

With this patch, they now have different applicationIds and differrent C2D_MESSAGE permission names.

**Comment by tonyr59h** [comment]
Gotcha, thanks for the explanation :smile:

:shipit:

**Pull request merged**
