### PR TITLE
Consolidate granular stats tabs

### LINKED ISSUE #20660: Stats Traffic & Subscribers: Reintroduce Traffic tab with an old chart and a new date picker
Parent: https://github.com/Automattic/wordpress-mobile/issues/47

### Traffic tab updates

- Consolidate Days/Weeks/Month/Years tabs while keeping the same bar chart and the same behavior
- Add a new date picker that allows to switch between Days/Weeks/Months/Years

### PR DESCRIPTION
**Pull request by irfano**
Fixes #20660

This removes codes from the old Traffic tab and consolidates granular tabs to the new TRAFFIC tab.

Additionally, reverts removing of Today card (https://github.com/wordpress-mobile/WordPress-Android/commit/8c2c169093cc5cec65aa57e26c90817fb3a440f2). We removed the Today card because we were showing a similar card in the previous project. Now it's not necessary to remove it.

-----

#### Disabled `stats_traffic_subscribers_tab` flag
1. Disable `stats_traffic_subscribers_tab` config from "Me → Debug settings"
2. Open "My Site → Stats".
3. Verify that there are INSIGHTS/DAYS/WEEKS/MONTHS/YEARS tabs and they work as before.

#### Enabled `stats_traffic_subscribers_tab` flag
1. Enable `stats_traffic_subscribers_tab` config from "Me → Debug settings"
2. Open "My Site → Stats".
3. Verify that there are TRAFFIC/INSIGHTS tabs and they work as expected.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Disabled and enabled states of `stats_traffic_subscribers_tab`

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Tested manually.

3. What automated tests I added (or what prevented me from doing so)

    - Updated current tests.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
I have noticed that Views & Visitors detail screen is not working on this PR. I need to make significant changes to address this issue because the Views & Visitors detail screen was relying on cached data from the WEEKS tab. I will address this in a separate PR.

**Review by aditi-bhatia — APPROVED** [review]
Looks good to me 👍

**Comment by aditi-bhatia** [comment]
> I have noticed that Views & Visitors detail screen is not working on this PR. I need to make significant changes to address this issue because the Views & Visitors detail screen was relying on cached data from the WEEKS tab. I will address this in a separate PR.

Sounds good, since this issue only occurs with the feature flag on, I've gone ahead and approved/merged this PR

**Pull request merged**
