### PR TITLE
[Modal Layout Picker] Enable the new Layout Picker for release

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2447

## Description
[Enables](https://github.com/wordpress-mobile/WordPress-Android/pull/12482/files#r462066562) the new Layout Picker for release

## To test:
Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

### Modal Layout Picker loads without toggling it on
1. Create a new page for a Gutenberg site. 
     - **Expect** to see the Modal Layout Picker. 

### Create a Blank Page
1. Create a new page for a Gutenberg site. 
1. Select "Create a Blank Page"
     - **Expect** to see the Editor Load and not present the old Starter Page Template Picker Bar

### Create a Page from a layout
1. Create a new page for a Gutenberg site. 
1. Select a layout
1. Select "Create Page"
     - **Expect** to see the Editor Load with the contents of the layout

### Preview a layout
1. Create a new page for a Gutenberg site. 
1. Select a layout
1. Select "Preview"
     - **Expect** to see a Read-Only Editor load with the contents of the layout
1. Select "Create Page"
     - **Expect** to see the Editor load with the contents of the layout

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by chipsnyder — COMMENTED** [review]
Nice work on this feature as a whole @antonis! Congrats on wrapping it up! 

I ran through the sanity test cases against vanilla release and everything works great.

I also tested this against vanilla debug and that didn't have MLP turned on. Can we switch that up to turn the feature on for vanilla debug too?

**Comment by antonis** [comment]
Hello @chipsnyder 👋 
Thank you for reviewing this 🙇 

> I also tested this against vanilla debug and that didn't have MLP turned on. Can we switch that up to turn the feature on for vanilla debug too?

I wasn't able to reproduce this. I've kept the setting only in the `defaultConfig` that should be applied to all flavours and release types. Tested with `vanillaDebug` and I can see the MLP screen and the configuration in the generated file.

Please let me know if you are still able to reproduce this to investigate further

**Comment by chipsnyder** [comment]
> Please let me know if you are still able to reproduce this to investigate further

You were right it looks like I had a Gradle cache issue that didn't clean up when I reran the refresh earlier. Refreshing Gradle and testing again this morning worked well though. 👍

**Review by chipsnyder — APPROVED** [review]
Working well now after my Gradle refresh 👍

**Pull request merged**
