### PR TITLE
[Global Styles] Adds Global Styles API Call and passes the value to the editor via a new prop

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3163

`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/30544
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3459
`WordPress-FluxC-Android` PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1940

## Description

This PR adds a feature flag for consuming the new the new Global styles API endpoint (https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1940)

## To Test

Use the app from this PR, turn on the `GlobalStyleSupportFeatureConfig` (_Me > App Settings > Test feature configuration_) and follow the test instructions on:
* https://github.com/WordPress/gutenberg/pull/30810

Optionally:
* https://github.com/WordPress/gutenberg/pull/30997

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hey @geriux 👋 
I temporarily [disabled the site version check](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1940/commits/79035779763e0ca3aa7349cb139c057ec27188a5) to [align with iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/16411/files#diff-50a5f41ef5e22b41033024416ab4d717208ca711675f9ac84dceebe15eccbb1aR16) and added a [feature flag](https://github.com/wordpress-mobile/WordPress-Android/pull/14597/commits/d082b4c6e3de53211ee47bebfc1cc108788ac259) under *App Settings > Test Feature configuration*.
Let me know if the [new APK](https://107434-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14597-build-107434.apk) works for you 🙇

**Comment by geriux** [comment]
> Hey @geriux 👋
> I temporarily [disabled the site version check](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1940/commits/79035779763e0ca3aa7349cb139c057ec27188a5) to [align with iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/16411/files#diff-50a5f41ef5e22b41033024416ab4d717208ca711675f9ac84dceebe15eccbb1aR16) and added a [feature flag](https://github.com/wordpress-mobile/WordPress-Android/pull/14597/commits/d082b4c6e3de53211ee47bebfc1cc108788ac259) under _App Settings > Test Feature configuration_.
> Let me know if the [new APK](https://107434-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14597-build-107434.apk) works for you 🙇

Thank you so much @antonis I'll give it a try! 🚀

**Comment by antonis** [comment]
>I have considered if this change warrants user-facing release notes and have added them to RELEASE-NOTES.txt if necessary.

Since the new functionality is behind a feature flag that is off by default I'm not sure if we want to add release notes at this point. Wdyt @geriux?

**Comment by geriux** [comment]
> Since the new functionality is behind a feature flag that is off by default I'm not sure if we want to add release notes at this point. Wdyt @geriux?

Yeah, I think we should wait until it's released to avoid confusion. 👍

**Review by chipsnyder — APPROVED** [review]
Changes look good Nice work @antonis 👍 

I only had time to give it a smoke test but I'll do a more thorough test before we fully turn the feature on.

**Pull request merged**
