### PR TITLE
Prepublishing Nudges : Add bottom sheet to Post List

### LINKED ISSUE #11886: Prepublishing Nudges : Show publish bottomsheet on Post List
The prepublishing nudges bottom sheet should be shown when the user initiates `Publish Now` from the `Post List`

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #11886

## Solution
1. I Utilized the `EditPostActivityHook` on the `PostsListActivity` so that I could create the `EditPostRepository` setup that the core functionality in the bottom sheet requires. This component doesn't seem like it was designed to be used outside the `EditPostActivity` but thankful due to its great design it was integrated really well with the `PostsListActivity`. 

2. In terms of page upload, I modified the `PostActionHandler` 's `publishPost` to take a whole post so that it can be uploaded. This was necessary because the user will be making changes to the `PostModel` that the `EditPostRepository` references so we use it as the source of truth since it wasn't persisted to the `PostStore`. 

One caveat of this approach is that, if the user dismisses the bottom sheet and opens the post, the tags, visibility, and publish date won't be persisted. I honestly think this functionality is fine since the `Posts List` isn't an editor and the changes being done in the bottom sheet are constrained there. Nonetheless, the opposite of this thought is the user making changes in the Editor and expecting them to be persisted. Any thoughts on this?

1. Should I figure out a way to save changes to the post even if the user dismisses the bottom sheet? 
2. How far should we go if this is done? Meaning, if they change the date and dismiss then it should switch to the `Scheduled` section of the `Post List` right? 

### Publishing 

1. Go to Post List. 
2. Go to Drafts. 
3. Click Publish. 
4. Once the bottom sheet is visible, click Publish Now. 
5. Ensure the post is published and it's shown in the Published tab. 

<kbd></kbd>

### Tags Added
1. Go to Post List. 
2. Go to Drafts. 
3. Click Publish. 
4. Once the bottom sheet is visible, change the tags. 
5. Click Publish Now. 
6. Ensure the post is published and the tags are shown when you open it in the Post Settings of the editor. 

<kbd></kbd>

### Post Scheduled

1. Go to Post List. 
2. Go to Drafts. 
3. Click Publish. 
4. Once the bottom sheet is visible, click Publish Date. 
5. Change the date to one in the future. 
6. Click Schedule Now.
5. Ensure the post is scheduled and it's shown in the Scheduled tab. 

<kbd></kbd>

### Change Visibility To Private
1. Go to Post List. 
2. Go to Drafts. 
3. Click Publish. 
4. Once the bottom sheet is visible, click Visibility. 
5. Change the visibility to Private. 
6. Click Publish Now.
5. Ensure the post is published and it's shown in the Published tab with Private label.

<kbd></kbd>

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by jd-alexander** [comment]
I didn't test configuration changes thoroughly as yet and I am still reviewing the changes to see how I can unit test them.

**Comment by ashiagr** [comment]
Great work @jd-alexander ! I tested the scenarios and the app worked well.

>  if the user dismisses the bottom sheet and opens the post, the tags, visibility, and publish date won't be persisted. I honestly think this functionality is fine since the Posts List isn't an editor 

if the user dismisses the bottom sheet and reopens it again, even then the tags, visibility, and publish date won't be persisted, right? This looks fine to me.

Also noticed one bug: published date was initially set to current date and when I chose to change it, it was set to last scheduled date even though I made no changes:

publish_date

**Comment by jd-alexander** [comment]
Thanks for the review @ashiagr Responding to all the comments tomorrow!

**Comment by jd-alexander** [comment]
Thanks again @ashiagr for spotting that bug. Ready for another round 😄

**Comment by ashiagr** [comment]
Thanks for fixing "Publish Date" caching issue @jd-alexander ! 🎉

I'll hold off further reviewing till we hear about the question you asked and you've tested configuration changes.

**Comment by leandroalonso** [comment]
> Yes, that's the expected behavior. But just to double-check let me loop in @leandroalonso @malinajirka more context in the PR description. Thanks.

I'm afraid that in iOS we save all the information to the post at the moment the user changes it (just like Post Settings). That wasn't intentional, but since we reused Post Settings stuff it works the same way it works there.

@jd-alexander the same applies when the user dismiss the bottom sheet under the editor?

**Comment by jd-alexander** [comment]
Thanks for chiming in @leandroalonso 😄 

> I'm afraid that in iOS we save all the information to the post at the moment the user changes it (just like Post Settings). That wasn't intentional, but since we reused Post Settings stuff it works the same way it works there.

> @jd-alexander the same applies when the user dismiss the bottom sheet under the editor?

Yes, so the same thing happens in Android when it's within the Editor. The difference in the Post List is that it wasn't created as a space where we would be persisting modifications being made to a post. We assumed that all modifications have already taken place and if any more changes need to be made then we will open the editor for that. So in this implementation when we make changes to the `PostModel` it's an in memory representation and when it's being passed to the `UploadService` it gets persisted in the database. So yes, when the user presses the `Publish` button within the Post List that's when a fresh post from the `PostStore` is fetched and if changes were made to the in memory representation that would be cleared out.

**Comment by jd-alexander** [comment]
> Thanks for fixing "Publish Date" caching issue @jd-alexander ! 🎉

> I'll hold off further reviewing till we hear about the question you asked and you've tested configuration changes.

Thanks @ashiagr  you rock 😎

**Comment by jd-alexander** [comment]
So I discovered that we are persisting the post before we trigger the `UploadService` here 
https://github.com/wordpress-mobile/WordPress-Android/blob/6d6309ec876d0afd822c54efd13fa12bfeb26ed3/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java#L401

So once the user presses publish in the bottom sheet with the changes made on the Post List it's saved in the database. Wdyt @malinajirka ?

**Comment by jd-alexander** [comment]
Hi @ashiagr this PR is ready for another review. There is a crash taking place here at times that's expected.

```
 java.lang.IllegalStateException: The SAVE action shouldn't be available in this bottom sheet.
        at org.wordpress.android.ui.posts.prepublishing.home.usecases.GetButtonUiStateUseCase.getUiState(GetButtonUiStateUseCase.kt:37)
        at org.wordpress.android.ui.posts.PrepublishingHomeViewModel.setupHomeUiState(PrepublishingHomeViewModel.kt:82)
        at org.wordpress.android.ui.posts.PrepublishingHomeViewModel.start(PrepublishingHomeViewModel.kt:46)
        at org.wordpress.android.ui.posts.PrepublishingHomeFragment.initViewModel(PrepublishingHomeFragment.kt:78)
        at org.wordpress.android.ui.posts.PrepublishingHomeFragment.onViewCreated(PrepublishingHomeFragment.kt:55)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
```

I will be addressing this in another PR so that we don't have to keep this one lingering on. So this is safe for merge once you have tested it and all is well.

**Comment by jd-alexander** [comment]
Thanks @ashiagr I did a run but I didn't spot this one. Let me know what you think about the solution I created.

**Comment by jd-alexander** [comment]
> hey 👋

Hey 😄 

> I tested the changes and all looks good to me. Thanks for your coordination efforts for reaching solutions 👍. Great job!

Awesome. Again thanks for always being a thorough tester and reviewer. It's greatly appreciated 💯

**Pull request merged**
