### PR TITLE
Fix animation on lowering Card height in stats list

### LINKED ISSUE #9171: Stats Expandable View Does Not Show Collapse Animation
### Expected
The chevron icon in an expandable list row animates when the view is expandable and collapsed.

### Observed
The chevron icon in an expandable list row animates when the view is expandable, but not collapsed.  See the animation below for illustration.

stats_animation_collapse

### Reproduced
0. Select site with at least one post.
1. Go to ***Sites*** tab.
2. Tap ***Stats*** item.
3. Tap ***Years*** tab.
4. Tap author in ***Authors*** section.
5. Notice chevron animates when view is expanded.
6. Tap author in ***Authors*** section from Step 4.
6. Notice chevron does not animate when view is collapsed.

##### Tested
Google Pixel 3 on Android 9.0 with alpha-150

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9171 
This fixes the issue when a RecyclerView height is set to `wrap_content` and we decrease its height. In a normal RV the height is decreased immediately but the items removal is animated. This causes the weird behaviour where the items first disappear completely only to slide back in once their animation is finished. This PR fixes the issue and it is based on [this solution](https://stackoverflow.com/questions/40242011/custom-recyclerviews-layoutmanager-automeasuring-after-animation-finished-on-i).
It basically reverts the order of item animation/outer dimension change so it first finishes the animation that removes the items and changes the RV height later. 

To test:
* Go to Stats/DWMY
* Go to any Card with expandable items (Referrers, Clicks, Authors...)
* Try expanding and collapsing items
* The animation works both ways
* Nothing looks yanky

fixed_animation_2

### CODE REVIEW

**Review by theck13 — COMMENTED** [review]
Interesting solution!  The code looks good and fixes the chevron animation issue as described in https://github.com/wordpress-mobile/WordPress-Android/issues/9171.  I noticed one side effect though.  Previously, the view below the expandable list row would slowly slide up when the view above is collapsed.  Now, the view below the expandable list row quickly snaps up when the view above is collapsed.  See the animations below for illustration.

Before|After
-|-
stats_before|stats_after

It seems this solution fixes one issue, but causes another.  Is [sequencing the animations as mentioned in the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/9171#issuecomment-460722328) not possible for these views?  It might avoid both issues and we may not need a custom class.

**Comment by planarvoid** [comment]
@theck13 I haven't noticed that! thanks 👍 
I think I've found a solution. I was using one layout manager for all the view holders. It needs to be initialized in each `bind` call.  

I've checked your suggestion and the issue I'm facing here is caused by RecyclerView and its lack of support of `wrap_content`. It doesn't really work well. I could just animate the chevron but adding more items to the inner list would still cause this issue.

Let me know what you think! 
collapse_animation_fixed

**Review by theck13 — COMMENTED** [review]
The animation looks much better and the code looks good too!  Do you know why the rows being hidden disappear immediately rather than fading out when collapsing the view?  See the slowed down animation below for illustration.

stats_update

Other expandable/collapsible views in the app fade the view in/out (e.g. site plugin detail, quick start list).

**Comment by planarvoid** [comment]
hey @theck13 , I've realized that the solution actually uses the original (unmodified) RV behaviour which doesn't work if there are more items under the collapsed items. I've gone back to the first fix where the block collapses instantly. I think it's the best we can do now. Let me know if it's good enough or I should just keep the previous behaviour

**Review by theck13 — COMMENTED** [review]
I just noticed if there are many authors and I tap the ***View More*** button at the bottom of the ***Authors*** view, the complete list of authors seems to expand/collapse correctly.  Is that a different architecture?  See the animation below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/56841628-c80e7900-6843-11e9-9d9b-857ebe522445.gif"></a>

Also, something odd is happening in when there are many authors on the main ***Stats*** view.  When expanding a list item with a few child items, the entire expandable list group slides down.  This happens when expanding the ***Tyler*** or ***oguzkocer*** items.  When expanding a list item with many child items, some items in the group disappear and are added to the end of the group after the expanding list item is finished expanding.  This happens when expanding the ***Vojta Smrcek*** item with the ***lorenzomattei*** and ***View More*** items disappearing momentarily.  I'm not sure if that helps understand why these expandable list views are acting differently than others in the app or not.  See the animation below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/56841864-1e2fec00-6845-11e9-96fa-b7090ae7603c.gif"></a>

**Comment by planarvoid** [comment]
Hey!

> I just noticed if there are many authors and I tap the View More button at the bottom of the Authors view, the complete list of authors seems to expand/collapse correctly. Is that a different architecture? See the animation below for illustration.

The `View more` screen has the recycler view with height set to `match_parent`. This works correctly in both adding and removing items to the list. This issue only happens when we have nested recycler views. The inner RV has height set to `wrap_content`

I'll look into the other issue!

**Comment by planarvoid** [comment]
I've finally found the issue and fixed it @theck13 - we were using the different order of animation whenever the app called `onItemRangeRemoved` but this could've been called even when a part of the list was removed but more items were added (so in total the list grew). I've changed the call so we only use different animation when we actually remove some items. Sorry it took so long!

**Comment by theck13** [comment]
It appears we're back to the state mentioned in [my original review](https://github.com/wordpress-mobile/WordPress-Android/pull/9662#pullrequestreview-228519468).  The view below the expandable list row quickly snaps up when the view above is collapsed.  Is there no animation for removing the items like that [mentioned in the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/9171#issuecomment-460722328)?

**Comment by planarvoid** [comment]
@theck13 yep, we're in the original state. The whole animation is processed by recycler view (which is buggy) so there isn't much I can do about it (possibly we can animate the whole thing ourselves but I don't think it's worth it). I don't think I want to spend much more time on this issue. Either we keep it as it is for now (and I'll close this PR) or we merge this and create a new issue to further improve the behaviour.

**Comment by theck13** [comment]
Since these changes address the issue, which was the chevron animation when collapsing the expandable row, we can merge this pull request.  Since these changes produce a different issue, which is the view below the expandable row is not animated when collapsing, I created https://github.com/wordpress-mobile/WordPress-Android/issues/9888.

**Review by theck13 — APPROVED** [review]

**Pull request merged**
