### PR TITLE
Onboarding Improvements Existing Users: Tracking

### LINKED ISSUE #15010: Onboarding Improvements: Tracking
Parent #14989

The goal of this task is to verify that tracking is integrated for the project and events are validated in Tracks.

- Add two new events to the Login Epilogue view
On tap of `Site` row ->  `LOGIN_EPILOGUE_CHOOSE_SITE_TAPPED`
On tap of `Create a new site` button -> `LOGIN_EPILOGUE_CREATE_NEW_SITE_TAPPED`
- Update  `UnifiedLoginTracker.Click` to include CHOOSE_SITE 
- Track both the screen event and the unified login event as follows: 
```
analyticsTracker.track(LOGIN_EPILOGUE_CREATE_NEW_SITE_TAPPED)
unifiedLoginTracker.trackClick(Click.CREATE_NEW_SITE)

analyticsTracker.track(LOGIN_EPILOGUE_CHOOSE_SITE_TAPPED)
unifiedLoginTracker.trackClick(Click.CHOOSE_SITE)
```

The following tracks: CONNECT_SITE (connect another site) and CONTINUE (done) will not be collected when the new epilogue is shown.  FYI, both of the existing tracks happen in LoginEpilogueFragment `bindFooterViewHolder` and `setupBottomButton`

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #15010 

This PR adds tracking for the OnBoarding Existing Users project

Two new events were added:
LOGIN_EPILOGUE_CHOOSE_SITE_TAPPED 
LOGIN_EPILOGUE_CREATE_NEW_SITE_TAPPED

Also added `CHOOSE_SITE` to UnifiedLoginTracker.Click  

To test:
- Launch the app 
- Enable `My Site` -> `App Settings` -> 'Privacy Settings' ->  "Collecting Information"   
- Go to `My Site` -> `App Settings` -> `Test feature configuration`.
- Enable the `OnboardingImprovementsFeatureConfig` and click on the `RESTART THE APP` button 
- Log out of the app
- Log in to the app
- On the Login Epilogue tap the `Create a new site` button
- Check log for:
- `🔵 Tracked: login_epilogue_create_new_site_tapped`
- `🔵  Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_password","step":"success","click":"create_new_site"}`
- Log out of the app

- Log in to the app
- On the Login Epilogue, Tap on a site to select it
- - Check log for:
- `🔵 Tracked: login_epilogue_choose_site_tapped`
- `🔵  Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_password","step":"success","click":"choose_site"}`

## Regression Notes
1. Potential unintended areas of impact 
The new events aren't tracked

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested and viewed log files

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — APPROVED** [review]
All events fired as described:

```
I: 🔵 Tracked: login_epilogue_choose_site_tapped
I: 🔵 Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_password","step":"success","click":"choose_site"}
I: 🔵 Tracked: login_epilogue_create_new_site_tapped
I: 🔵 Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_password","step":"success","click":"create_new_site"}
```

Thanks for tracking these new events ✨.

Note: The only comment I have is that `login_epilogue_choose_site_tapped` gets fired in the Jetpack app when onboarding improvements feature flag is enabled. There's already a sub-task for Jetpack app handling in the Epilogue screen task. Hopefully, it should be tackled there. Just leaving a note here.

Feel free to merge if no action is needed for the note above.

**Comment by zwarm** [comment]
> Note: The only comment I have is that login_epilogue_choose_site_tapped gets fired in the Jetpack app when onboarding improvements feature flag is enabled. There's already a sub-task for Jetpack app handling in the Epilogue screen task. Hopefully, it should be tackled there. Just leaving a note here.

@ashiagr - FYI there are separate tasks to always show old for UI for Jetpack, but I am going to cc @ParaskP7 just so he is aware of the tracking. I don't believe we need to do anything for this, as Jetpack should never make it here.

**Comment by ParaskP7** [comment]
👋 @zwarm !

Thanks for the ping! 🙏 

> @ashiagr - FYI there are separate tasks to always show old for UI for Jetpack, but I am going to cc @ParaskP7 just so he is aware of the tracking. I don't believe we need to do anything for this, as Jetpack should never make it here.

Thanks for making me aware. Yes, you are right about the Jetpack app. And as discussed, I am going to take care all of that and some other fixes as part of my last PR, the one with the `Alternative Flow`.

**Comment by leandroalonso** [comment]
@zwarm @ParaskP7 @ashiagr friendly reminder to validate the events on Tracks if they're being fired correctly, thanks!

**Pull request merged**
