### PR TITLE
Enable Connected Tests on Gutenberg Mobile releases

### LINKED ISSUE #65: Make WPAndroid automatically run optional tests on Gutenberg release branches
WPiOS [runs optional tests automatically on Gutenberg Release branches](https://github.com/wordpress-mobile/WordPress-iOS/blame/develop/.circleci/config.yml#L331-L339.). WPAndroid [doesn't](https://github.com/wordpress-mobile/WordPress-Android/blob/5aa4cbbb83f686c02fa00838efc5cebe8fec4b27/.circleci/config.yml#L363-L377) though, so we should update WPAndroid's CI configuration to do this.

If this change is made, tweak the release checklist to remove the checklist item that calls for these tests to be manually triggered.

### PR DESCRIPTION
**Pull request by guarani**
This enables automatic execution of our optional Connected Tests suite on PRs used for Gutenberg Mobile releases. Releases will now benefit from optional tests being ran by default, without release wranglers needing to manually run them.

The regex used here matches the branch name used by the release automation script [here](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/6595c075e00aff342164b469dcfbaf84e4bda561/release_automation.sh#L262).

| Before | After |
| - | - |
| Screen Shot 2021-10-12 at 09 09 09 | Screen Shot 2021-10-13 at 08 47 12 |

This is a follow up to https://github.com/wordpress-mobile/WordPress-iOS/pull/16233 which made the same changes for WPiOS.

Fixes https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/issues/65

### To test
1. Notice that the branch of this PR follows the Gutenberg release branch naming convention i.e. `gutenberg/integrate_release_X.XX.X`, so we can expect GitHub to now automatically run UI tests on this branch
2. Verify that UI tests are automatically run

## Regression Notes
Not applicable since this isn't a user-facing change.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
👋 @AliSoftware, I was wondering if you could help here or know who I could ask for help.
I'm trying to automatically run optional tests on Gutenberg Mobile release PRs and have two questions: a) after making the change seen in this PR's diff, I no longer see the optional tests on hold, but also can't see evidence of them being executed in the list of checks above. b) This PR only handles CircleCI, would it make sense to also make a change for Buildkite?

**Comment by AliSoftware** [comment]
@guarani Thanks for the ping. You're almost there!

### a) Making Connected Tests run unconditionally

What you changed in that diff is only the `Optional Tests` workflow, which consists of running 2 jobs: `Hold` and `Connected Tests`, with the latter [requiring](https://github.com/wordpress-mobile/WordPress-Android/pull/15449/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L378-R380) the former. That's why that workflow is called `Optional Tests`, because it only runs the `Connected Tests` if you approved the `Hold` job before it.

With your change, the `Hold` job doesn't run anymore for gutenberg-named branches… and since the `Connected Tests` from line 379 still _requires_ `Hold` but `Hold` isn't run for those branches, that specific `Connected Tests` – from `Optional Tests` workflow – will _not_ run at all either. That's what this syntax means and why it behaves like you observed.

You could see it another way by considering that making the `Hold` job _ignored_ kinda defaults it always to `false`/`rejected` rather than `true`/`approved` for those branches, hence why the follow-up `Connected Tests` don't run. 


This is a good start (indeed we don't want the `Optional Tests` workflow with the `Hold` mechanism for those branches anymore), but you will _also_ need to tell CircleCI to run the `Connected Tests` job **unconditionally** (i.e. without a `require: [Hold]`) for those G branches. This is done [here in the other `wordpress_android` workflow a couple of lines above](https://github.com/wordpress-mobile/WordPress-Android/pull/15449/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L355-L362), which runs the `Connected Tests` job unconditionally (i.e. without a Hold) but only for `develop` and `release/*` branches. Just add your branch here too, and it should be enough for it to run unconditionally for those branches. 🎉 

_PS: Bonus points if you use [a YAML anchor](https://mobile.blog/2021/09/09/clean-config-files-with-yaml-anchors/) to avoid repeating your branch name/regex in the 2 places 😛_

### b) Reflect change in BuildKite

The WPAndroid repo currently only have a minimal set of jobs running on BuildKite, mostly lint jobs and a couple of unit test jobs, but it doesn't yet run the Connected Tests (the ones using Firebase Test Lab). So no changes needed there.

Once we'll get back to finishing the migration of WPAndroid from CircleCI to Buildkite, and translate those Connected Tests jobs and Optional Tests workflows from CircleCI into Buildkite, we will take care of translating this change too for you 🙂

**Review by AliSoftware — APPROVED** [review]
Works as expected:

| Before | After |
|---|---|
| before | image |

👏  :shipit:

**Comment by guarani** [comment]
Thanks for the detailed explanation above about why it wasn't working previously 👍 
I've made the changes and as you mention above it's looking good now!

---

### YAML anchors

I tried YAML anchors but ran into an issue. The array of branch names is used in two places:

https://github.com/wordpress-mobile/WordPress-Android/blob/bd3e97d6d911be149e6ceeadf34fa728a2dc5425/.circleci/config.yml#L360-L362

and 

https://github.com/wordpress-mobile/WordPress-Android/blob/bd3e97d6d911be149e6ceeadf34fa728a2dc5425/.circleci/config.yml#L374-L377

However, the latter has `/pull\/[0-9]+/` that the former does not. Using YAML anchors, I first declared them up the top of the file like this:

```
# Nodes with values to reuse in the config.
common_params:
  # The names of branches where connected tests will run by default.
  - &branches_requiring_connected_tests [
      develop,
      /^release.*/,
      /^gutenberg\/integrate_release_.*/,
    ]
```
Then I could successfully use it in the first place mentioned above like so:

```
              only: *branches_requiring_connected_tests
```

In the second place, I needed to combine the sequence with `/pull\/[0-9]+/`, so I tried:
```
              ignore:
                [ *branches_requiring_connected_tests, /pull\/[0-9]+/ ]
```
but I believe this would result in a nested array, so isn't the right approach. I then looked at the merge operator `<< :`, but it looks to be specific to mappings, not arrays. After a bit of Googling, [it looks like this is not possible with just YAML](https://stackoverflow.com/a/9322417/1305067). **Are you aware of a way to do this?**

The alternative I'm aware of doesn't help reduce the line count, but helps make sure actual branch names are defined only once:
```
# Nodes with values to reuse in the config.
common_params:
  # The names of branches where connected tests will run by default.
  - &develop_branch
    develop
  - &release_branch
    /^release.*/
  - &gutenberg_mobile_release_branch
    /^gutenberg\/integrate_release_.*/
  - &numbered_branch
    /pull\/[0-9]+/
```

This I would use like this:
```
              only:
                - &develop_branch
                - &release_branch
                - &gutenberg_mobile_release_branch
```
and
```
              ignore:
                - &develop_branch
                - &release_branch
                - &gutenberg_mobile_release_branch
                - &numbered_branch
```

---

I'm going to merge this change as-is, but I would love to hear if you know of possible improvements. If so, I'm keen to apply the changes in a follow up PR here (as well as in WPiOS).

**Comment by guarani** [comment]
Actually, in this repo, would merging be done by the reviewer (on WPiOS it's done by the PR author, but I remember it being different here in the Android repo)? If so, would you like to merge this @AliSoftware?

**Comment by AliSoftware** [comment]
Sure, no worries 👍 

For the record, indeed [the official policy is different between WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md#pr-merge-policy) and WPiOS repos… but in practice that policy is pretty loosely held :P It's just saying that in WPAndroid if the reviewer approves, it's ok for them to also merge without waiting for the author to merge it themselves. But if the reviews didn't merge after approval (e.g. because the CI hasn't finished yet by then, or because they forgot), it's ok for the author to merge it too 🙂

**Comment by AliSoftware** [comment]
As for YAML anchors, you totally nailed it:
 - indeed you won't be able to put an anchor in the whole array because they are not the same (one have one more item)
 - and indeed you won't be able to use the `<<:` merge operator either, because that one only works on dictionaries, not arrays.
 - So the only solution would be to add an anchor to the individual elements themselves, like you suggested in your last point.
 - Though, my idea was to only add an anchor for the `&gutenberg_release_branch /^gutenberg\/integrate_release_.*/` one – because it's a bit longer than the others and requires that pesky escape sequence for `\/` and is a less common branch name than `develop` or `release`, which I feel a bit less useful to have an anchor for

That being said, this was just a bonus (because I love YAML anchors 😇 ) and totally optional, and it works just as well the way you did it, so I'm ok to merge it as is 🙂  (especially given CircleCI config will disappear in the near future once we finish the migration to Buildkite anyway 😉 )

**Comment by guarani** [comment]
Thanks for clarifying the merge policy and providing the link to the official repo policy, @AliSoftware! And for merging this ❤️

**Comment by guarani** [comment]
Your comment about YAML anchors here makes sense, a reasonable compromise would be to just use anchors on the long-and-unwieldy Gutenberg Mobile release branch regex 😄 
I might make that change at one point (unless someone else gets to it first or it's replaced by buildkite before). It's low on my priority list of course, but I like YAML anchors too ❤️ so it might be a fun exercise for both repos.

**Pull request merged**
