### PR TITLE
Login Rework: Use the new login flow via Site Picker

### PR DESCRIPTION
**Pull request by hypest**
**Note: #6137 needs to be merged first.**

This PR enables the new login flow to add a selfhosted site from the Site Picker. Only the selfhosted flow is offered via the site picker.

The final visual touches, the messages and final texts will be done in a future PR.

To test:
* With a wpcom or selfhosted site already logged in the app, tap on the "Switch Site" option in MySite
* Tap on the "+" action to add a new site
* Input the site URL of the selfhosted site and hit "NEXT"
* Input the site username and password and hit "NEXT"
* ~The epilogue screen should come up, listing the new site among the previous ones. Only the "CONTINUE" button should be available. Tap on it.~
* The MySite screen should now be visible, displaying the site originally selected

### CODE REVIEW

**Comment by nbradbury** [comment]
Just gave this a quick spin and everything appeared to work fine, but after I clicked Continue on the epilogue, the My Site page showed the previously selected site rather than the JP site I just added.

**Comment by nbradbury** [comment]
Similar to [my comment](https://github.com/wordpress-mobile/WordPress-Android/pull/6119#issuecomment-312136706) on an earlier PR, after I added a JP site I found it confusing to be taken to the epilogue with a list of sites. I started on one list of sites, added a site, and ended up on a different list of sites. 

Wouldn't it make more sense to skip the epilogue and take the user directly to My Site with the added site selected?

**Comment by hypest** [comment]
>  after I clicked Continue on the epilogue, the My Site page showed the previously selected site rather than the JP site I just added.

That's the intended behaviour, replicating what the production app does anyway. It's also mentioned in the last step in the test scenario (`The MySite screen should now be visible, displaying the site originally selected`), sorry if it wasn't clear.

> Similar to my comment on an earlier PR, after I added a JP site I found it confusing to be taken to the epilogue with a list of sites. I started on one list of sites, added a site, and ended up on a different list of sites.
>
> Wouldn't it make more sense to skip the epilogue and take the user directly to My Site with the added site selected?

I had another look at this and removed the epilogue (with f353108). Here's what's different from the [other case](https://github.com/wordpress-mobile/WordPress-Android/pull/6119#issuecomment-312136706) you've mentioned: Logging to WordPress.com to enable the Jetpack stats has the "side effect" of connecting all the sites associated with the wpcom account, and having the epilogue is a reminder and a confirmation of that. On the other hand, connecting a selfhosted site like in this case, has no secondary effects nor needs the extra network calls the epilogue fragment performs (fetching account settings, all sites info).

I will update the test steps to remove the epilogue screen step.

Ready for another pass @nbradbury , thanks!

**Comment by nbradbury** [comment]
> That's the intended behaviour, replicating what the production app does anyway. It's also mentioned in the last step in the test scenario (The MySite screen should now be visible, displaying the site originally selected), sorry if it wasn't clear.

Oh, I completely misread that. I think if you add a site it should become the active one, but if the app already doesn't do that, then this is a subject for a different PR/issue.

> connecting a selfhosted site like in this case, has no secondary effects nor needs the extra network calls the epilogue fragment performs (fetching account settings, all sites info).

Perfect. I'll give this a test drive and then we can :shipit: after I merge #6137.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
