### PR TITLE
Issue/11254 material revisions

### LINKED ISSUE #11254: Implement Material theme on Post Revisions
We should switch widgets used at Post Revisions their material counterparts, remove color references where possible, and switch to using material textAppearance attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #11254

This PR moves Post Revisions to the material theme and adds a Dark Mode support.

VIsual Preview is not part of this PR, since I will have to update Aztec color scheme first.

comparison_revisions

To test:
- Navigate to the post with multiple revisions, and make sure they all look good in both light and dark themes.

You can change the app theme from App Settings.

Only one engineer/designer is required to review this PR, but anyone can do it.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by khaykov** [comment]
@theck13 Thanks for the review! All the things you mentioned are totally legit and I hope I addressed them.
I changed the size of the footer text from Body1 of appcompat to Body1 of Material theme and forgot that they are different (14 vs 16). Fixed it :)

The bottom bar should not be that bright, so I fixed it and changed the disabled chevron opacity. We have to ramp up the opacity of enabled chevron for them to be easily distinguishable.

I also added the background to revisions.

cc @mattmiklic 
[Image from Gyazo](https://gyazo.com/b1f948fc22fb84aaf5b025790f0570ae)

**Comment by khaykov** [comment]
@theck13 I looked for any material colors we can use in both light and dark modes, but nothing really worked. Since it's a one-off thing, I added a dedicated color for it, that points to `neutral_0` for light mode and `grey_90` for dark. I think it looks pretty good:

Screen Shot 2020-02-23 at 8 59 33 PM

**Comment by oguzkocer** [comment]
We're freezing `14.3` today, so this PR is being bumped to `14.4`. If you'd like it to ship with `14.3`, please merge it into `release/14.3` and ping me – I'll be happy to cut a new beta release.

**Comment by mattmiklic** [comment]
Agreed that Gray 100 might look a bit better with the neutral material background colors. Otherwise, looking good to me. 👍

**Comment by khaykov** [comment]
Updated color to Gray 100 👍

**Pull request merged**
