### PR TITLE
Add indicator line to selected value in overview block

### LINKED ISSUE #9061: [Stats Refresh] Add indicator line on DWMY overview tabs
As part of stats improvements: add indicator line on DWMY overview tabs. This helps to fix navigational issues.

indicator line

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9061 
This PR adds a line to the selected type in the Overview blocks. Constraint layout didn't work in this case so I moved the columns to a separate linear layout. I moved the padding back to the columns so be careful with different languages.

To test:
* Go to Stats/DWMY tab
* Notice the selected type in overview block is underlined
* Click on a different type
* The indicator is now on the newly selected type

To test 2: 
* Go to Stats/Insights
* The Latest post summary block doesn't show indicators

To test 3:
* Switch the language to Spanish
* Go to Stats/DWMY tab
* The paddings in the Overview block columns are not broken

**Default font size and display size:** 

screenshot_1548948283

**Largest font size and display size**

screenshot_1548948258

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good!

The line seems to be 1dp though instead of 2dp (as in the main page tabs)

**Review by 0nko — CHANGES_REQUESTED** [review]
It looks fine for the default screen settings, but when you change it to large (Settings -> Display -> Advanced -> Display size) and a different language, the paddings push things off the edge:

image

image

**Comment by planarvoid** [comment]
@SylvesterWilmott what do you think we should do in these use cases? ellipsize the text? or have different layout on smaller screens?

**Comment by 0nko** [comment]
This is what it still looks like:

image

Issue #8986 was raised specifically because the largest font/display size settings didn't work.

Maybe we could display the 4 values in a 2x2 grid for cases like this?

**Comment by planarvoid** [comment]
@0nko we've decided with @SylvesterWilmott that we'll align the items to the left and add horizontal scrolling in case the items overflow the screen. Thanks a lot for the feedback and the review!

**Comment by planarvoid** [comment]
@SylvesterWilmott I've updated the screenshots in the PR description. All the text size changes should be included in this PR

**Comment by SylvesterWilmott** [comment]
I think this change is having a negative effect on the most used display settings/screen sizes. By using a scrolling element everything becomes left aligned and unbalanced and I fear might add to the "muddled" feeling some users are reporting.

I think a safe trade off could be:

- Reduce the size of the tab labels to 10sp
- Use uppercase for tab labels
- Use even spacing for tabs ie 25% width on each one
- 8dp left and right padding inside each tab
- Truncate any overflow from the tab labels (we show the full label next to the new large number at the top when one is selected so we don't have 
- Use auto sizing for tab numbers so we can always show an un-truncated number

screenshot 2019-02-04 at 13 14 14

**Review by 0nko — APPROVED** [review]
This looks awesome! 👍

**Pull request merged**
