### PR TITLE
Issue/10648 material web preview

### LINKED ISSUE #10648: Implement Material theme on various web Preview screens
We should switch widgets used at web Preview screens to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10648

This PR moves Web Preview screens to the material theme and adds dark mode support.

comparison_webpreview

To test:
- Check Site, Post and Theme previews and make sure they look ok in both light and dark themes.

The theme can be changed from app settings.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
Great catch, @mattmiklic ! I also noticed that the bottom bar is too bright. I fixed elevation on both 👍 

comparions_wp

**Comment by mattmiklic** [comment]
Looking good now! 🚢

**Comment by oguzkocer** [comment]
@khaykov I don't think I can work on this PR this week since I am on groundskeeping. Hopefully someone will have time for it, but if nobody else takes it, I should be able to review it on Monday 🤞

**Comment by khaykov** [comment]
@malinajirka The UP button color was wrong. It's the only place we are using the white toolbar, so there was some mix up with styling. I updated it to be consistent with other screens (we are using `onSurface` color for Toolbar icons/text).

[Image from Gyazo](https://gyazo.com/c02c91ceade734888a7340a6e7dfcf1a)

I'll leave the question about "Desktop" label to @mattmiklic :)

**Comment by khaykov** [comment]
@malinajirka @mattmiklic mentioned that we can leave the label as is :)

**Comment by malinajirka** [comment]
Sorry, I missed the last update ;). LGTM, thanks!

**Pull request merged**
