### PR TITLE
[Gutenberg] Seamless media completion

### PR DESCRIPTION
**Pull request by mkevins**
Fixes (Android part of): https://github.com/wordpress-mobile/gutenberg-mobile/issues/2325

#### Related PR

gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2381

### Description

This PR adds a mechanism to defer actions until after the editor has mounted. This is useful to ensure that the local media id and url can be replaced by a remote id and url after upload has completed.

To test:
Follow the steps in these issues: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2041, https://github.com/wordpress-mobile/gutenberg-mobile/issues/1928
Expect that the url is correct after the upload completes and the editor finishes opening.
(i.e. url should begin with `https://` not `file://`)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @mkevins  
I was going through and testing some initial tests by testing the steps from https://github.com/wordpress-mobile/gutenberg-mobile/issues/2041. In my initial few runs, I ran into a crash while opening the post:

In the video, I'm testing the artifact [here](https://56114-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-12183-build-56114.apk) and running on a Pixel 3a running Android 10

screencapture-2381

Is there anything you see that here that might give a hint?

**Comment by mkevins** [comment]
Thanks for testing Chip!

> Is there anything you see that here that might give a hint?

:thinking: Hm.. I didn't encounter that, but I'll try to match the timing shown in yours and see whether I can reproduce it.

**Comment by mkevins** [comment]
Hi @chipsnyder :wave: :smile: 

I was able to reproduce it by resuming the editor _before_ the upload completed, while progress events were still occuring. In my testing, I had gotten so good at reopening the editor at exactly the moment between the last progress event and the final completion event that I missed / forgot to [drop non-critical messages](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2381/commits/b4b7055f7a1a8a93e30b60af45c373a48313871a#diff-d912a097d869167502d67f61a7bc649aL85) :man_facepalming: . This is ready for another pass.

**Comment by chipsnyder** [comment]
> In my testing, I had gotten so good at reopening the editor...

No problem :) I should be able to look at this again tomorrow. Got a bit busy today but I'll jump on it ASAP

**Pull request merged**
