### PR TITLE
Notifications Settings - adding "All Your Sites" button to show short list + all sites

### LINKED ISSUE #4866: Notification Settings: make the site list show the first 3 sites to give room for other settings
When you have a lot of sites, the notification settings screen in the WordPress Android app gets very, very long as the sites are listed before the “Other” and “Sights and Sounds” sections.

It might be better for folks with lots of sites if the more general settings were first, and the site-specific afterwards to make getting to the general settings easier.

**EDIT**: following iOS implementation here as per @rachelmcr 's comment here https://github.com/wordpress-mobile/WordPress-Android/issues/4866#issuecomment-264825366

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4866 

With a long "Your sites" list, it's difficult for users to find the general section, so this PR moves that section to the top of the screen, followed by "Your Sites" and "Other".

To test:
1. go to My Profile tab (3rd tab)
2. tap on Notification Settings
3. you should see "Sights & Sounds" section first, as in the screenshot

screenshot_20161203-171630

cc @daniloercoli

### CODE REVIEW

**Comment by daniloercoli** [comment]
👏

**Comment by mzorz** [comment]
As per @rachelmcr 's comment here https://github.com/wordpress-mobile/WordPress-Android/issues/4866#issuecomment-264825366  I went ahead and implemented a similar UX to that of iOS:

screenshot_20161209-130254
screenshot_20161209-130258


**What it does now:**
- now we show top 3 sites and a new item with title “All Your Sites”
- if you tap on “All Your Sites”, the full list is displayed in another screen
- if you start searching (tap on the search view) then all sites are displayed on the same screen to provide filtering
- while at the search view, if you tap back, the short list is displayed again.

**Notes:**
- One thing bugs me a bit though, it’s that the preference item called “All Your Sites” doesn’t stand out. Been trying to change its appearance so it looks a bit differently but couldn’t make it.
- the iOS app shows 3 sites and then the  “View all…” option. Wondering if we should show more? 5 maybe? Depends on how many users have more than 3 sites maybe, as the screens nowadays seem to support a 4 or 5 item list very well.

cc @rachelmcr @daniloercoli

**Comment by daniloercoli** [comment]
Just a minor thing, and then we can :shipit: with 3 sites and the "View all" link/button.
Calypso, web interface, uses "All My Sites" in the sites switcher. Maybe we want to reuse the same form for our "View all" button/link?

> Depends on how many users have more than 3 sites maybe, as the screens nowadays seem to support a 4 or 5 item list very well.

I think 3 sites is fine. On my Nexus 5X  I see the "Sights and Sound" label (not the whole section) at the bottom of the screen without scrolling.

**Comment by mzorz** [comment]
Thank you @daniloercoli ! Just changed wording in 7a4d6db 👍 
Leaving visible items in 3 too

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
