### PR TITLE
Only stop the sign in process when we don't get sites updated

### PR DESCRIPTION
**Pull request by maxme**
Only stop the sign in process when we don't get sites updated

### CODE REVIEW

**Comment by aforcier** [comment]
[Here](https://github.com/wordpress-mobile/WordPress-Android/pull/5426/files#diff-d1955c04c369a8c269a4d81a5fdbe99fR1271) we don't finish the activity if `event.isError()`, so we'll still stay stuck at the sign in screen even if `rowsAffected > 0`.

**Comment by maxme** [comment]
Not easy to read, but fixed in 96e0dd7

**Comment by aforcier** [comment]
We still need to drop `&& !event.isError()` [here](https://github.com/wordpress-mobile/WordPress-Android/pull/5426/files#diff-d1955c04c369a8c269a4d81a5fdbe99fR1273) for this to work.

**Comment by maxme** [comment]
@aforcier should be ready now

**Comment by aforcier** [comment]
Tested normal sign-in, and sign-in with one duplicate WP.com site (by modifying the response of `/me/sites` so that two different sites have the same `meta.links.xmlrpc` location). 👍

:shipit:

**Pull request merged**
