### PR TITLE
[Reader Improvements] Post card minor tweaks

### LINKED ISSUE #19337: [Reader Improvements] Post card minor adjustments
Do some font size adjustments:
- lets try changing the excerpt, comments/likes numbers, and actions text all up from m3 body small (12) to m3 body medium (14)
- The heading, I actually went back and forth between a very prominent and a more subtle heading in the designs. I landed on a larger one, you might have grabbed the subtler version I had before. In the designs its m3 title large (22). That large title seems to have font-weight regular by default, but I have made it medium.

For the avatar: 
- let's try showing the author avatar if the site has none (or we were not able to get one, like in the Discover tab).

For the card actions:
- change the spacing between the horizontal card actions from 24 to 16? I made it 24 in the designs

Refs: 
- p1696500503457939/1696435972.339529-slack-C05N140C8H5
- https://github.com/wordpress-mobile/WordPress-Android/pull/19328#issuecomment-1755797831

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #19337

Increase font size for all post card texts.

Note: I did not add the fallback to use the Author avatar in the cards since that can create an inconsistency with the Post Details / Site header, that are set to show the avatar only when there's a Blog avatar available.

To test:
1. Install and log into Jetpack
2. Go to Reader
3. Enable `ReaderImprovementsFeatureConfig`
4. **Verify** the post cards have bigger text in all feeds

## Regression Notes
1. Potential unintended areas of impact
N/A

5. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

6. What automated tests I added (or what prevented me from doing so)
N/A 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by RenanLukas — APPROVED** [review]
Thanks for the PR, @thomashorta.
The post cards have bigger text in all feeds and code LGTM :shipit:

**Review by osullivanchris — APPROVED** [review]
Looks much better! Only one tweak from me. The post card titles should be medium weight. I think the m3 title we've used by default takes regular weight. But can we manually make it medium here? Thanks.

**Comment by RenanLukas** [comment]
> Only one tweak from me. The post card titles should be medium weight. I think the m3 title we've used by default takes regular weight. But can we manually make it medium here? Thanks.

👋 @osullivanchris 

Since @thomashorta is AFK today, I took care of this tweak. Please let me know if it's working as expected.

### Before
Screenshot 2023-10-11 at 3 06 53 PM


### After
Screenshot 2023-10-11 at 3 34 29 PM

**Comment by thomashorta** [comment]
Thanks @RenanLukas for taking care of that! 

I cannot officially approve the PR since I'm the author, but the code changes look good to me! 🙇🏼‍♂️  Thanks.

**Comment by osullivanchris** [comment]
Screenshots look right to me! Thanks!

**Pull request merged**
