### PR TITLE
Create clicks block

### LINKED ISSUE #8678: Create Clicks block in Stats
The FluxC endpoint has to be implemented first - wordpress-mobile/WordPress-FluxC-Android#999

- Create a block in Stats that shows the Clicks by days/weeks/months/years on the DWMY page.
- Show the block on each tab with the correct data.
- Show the View more button when there is 6+ items
- show only <= 6 items in the block
- the items are expandable

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #8678
FluxC endpoint needs to be reviewed and merged with this PR - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1022

This PR is adding the Clicks block to the Stats screen. The block contains a list of click items. Some of them are expandable. The list should be different on each Day/Week/Month/Year tab. There should be at most 6 top-tier items in the list. If there are more than 6 items, the `View more` button appears which redirects you to the `View all` activity. We're still reusing the old activity for viewing more clicks.

To test:
* Open Stats
* Go to Days/Weeks/Months/Year tab
* You see a Clicks block at the bottom of the screen
* The block contains different data on different tabs
* Some items are expandable (you have to use a high traffic site to see them)
* If there are 6+ items, the `View more` button appears
* Clicking the `View more` button redirects you to the `View all Clicks` activity

### CODE REVIEW

**Review by khaykov — COMMENTED** [review]
Apart from the conflicts, everything looks and works as expected 👍 
I noticed that links are not clickable (neither top level or expanded ones). Is it by design?

Couple of things, that are not related to the clicks block implementation:
There is no chevron animation when colapsing expandable views.
Whole block blinks when expanding list. Maybe something with the way changes to dataset are notified to adapter?

**Comment by planarvoid** [comment]
@khaykov thanks for the review! the clicks should be clickable, that's a bug. 
With the chevron - this is pretty tricky. We're using nested RV and there are animations happening in both. I've described the solution in `BlockListAdapter` -

```
We're using a nested recycler view here. When we try to update a block with new data, there are 2 animations happening at the same time. The outer recycler view is animating the block height change and the inner recycler view is animating items being added or removed. The problem is that only the inner animation is actually animating, the block size happens immediately. This looks OK for adding new items to the list or when the size of the list doesn't change. In that case the block height increases immediately and the inner list changes are animated. However, when we want to remove items, the block height decreases immediately so the bottom items disappear and then the animation happens and they slowly slide back into view. This doesn't look good. We couldn't find a solution that handles this case well so we're falling back to notifying the whole list instead of animating changes when we decrease the number of items. When we do that, the outer animation happens and the items are replaced immediately.
```

**Comment by planarvoid** [comment]
@khaykov I've added the click listener and fixed the conflicts

**Review by khaykov — APPROVED** [review]
Thanks for the fix @planarvoid ! Everything looks good now.

Animations in nested RV is an interesting issue, would love to see us tackle it at some point :)

**Comment by khaykov** [comment]
I just wanted to make sure that this branch should be merged into `feature/create_referrers_block`. If it's ok feel free to merge anytime :)

**Comment by planarvoid** [comment]
@khaykov good catch! I've changed the base and I'm merging it now. Thanks a lot!

**Pull request merged**
