### PR TITLE
Feature/aztec integration media upload

### PR DESCRIPTION
**Pull request by hypest**
Wires up the media menu and media upload functionality with Aztec.

This PR depends on the https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/226 being merged.

To test:

1. Insert an image from the device's gallery
2. The image will get uploaded to the current blog and added to the post. While uploading a progress bar at the image top will denote the upload progress.

### CODE REVIEW

**Comment by 0nko** [comment]
I've noticed a couple of things when testing the app:

- Each image has extra padding above it (this is caused by the `lineSpacingExtra` and `lineSpacingMultiplier` attribute)
- When you open Elisa's intro post and quickly click on the 1st image, you'll get the following exception:
```
Process: org.wordpress.android, PID: 21055
    java.lang.NumberFormatException: For input string: "wp-image"
    at java.lang.Integer.parseInt(Integer.java:521)
    at java.lang.Integer.parseInt(Integer.java:556)
    at org.wordpress.android.editor.AztecEditorFragment.getMetadata(AztecEditorFragment.java:728)
    at org.wordpress.android.editor.AztecEditorFragment.mediaTapped(AztecEditorFragment.java:794)
    at org.wordpress.aztec.spans.AztecMediaSpan.onClick(AztecMediaSpan.kt:178)
    at org.wordpress.aztec.spans.AztecMediaClickableSpan.onClick(AztecMediaClickableSpan.kt:8)
    at org.wordpress.aztec.EnhancedMovementMethod.onTouchEvent(EnhancedMovementMethod.kt:38)
    at android.widget.TextView.onTouchEvent(TextView.java:8485)
    at android.view.View.dispatchTouchEvent(View.java:10023)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
    at android.view.View.dispatchPointerEvent(View.java:10243)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
```
- When you click on an an image in a different post (the hedgehog image in Cate's notes, for instance), the app doesn't crash and the image dialog is opened but you can't close it using the X button
- If there is a text wrapping an image, the baseline is pushed up (this is also caused by the `lineSpacingExtra` and `lineSpacingMultiplier` attribute):
image
- Maybe we could remove/disable the media menu items that don't do anything right now

**Comment by hypest** [comment]
Thanks for picking this up @0nko !

> Each image has extra padding above it (this is caused by the lineSpacingExtra and lineSpacingMultiplier attribute)

I think this is not directly related with the changed in this PR so, let's handle it separately. Thanks!

> When you open Elisa's intro post and quickly click on the 1st image, you'll get the following exception:

Aha, will look into it, thanks for the stacktrace!

> When you click on an an image in a different post (the hedgehog image in Cate's notes, for instance), the app doesn't crash and the image dialog is opened but you can't close it using the X button

Confirmed! Will work on it as well!

> Maybe we could remove/disable the media menu items that don't do anything right now

Not a bad idea. In our case, I'd recommend to just put out a Toast message that the feature is not yet implemented.

> The state of the image (failed/upload finished) is not updated until text is changed

Hmm, this is quite an issue and it seems to be cause by a combination of software/hardware rendering and perhaps a missing `refreshText()` somewhere. As we discussed on the chat, we might want to tackle that with a separate PR. Thanks!

In the meantime, I fixed the "initial" marking of failed images with 27129c5.

**Comment by hypest** [comment]
Ready for another pass @0nko ! I addressed all the comments except for the image-tap crash that I cannot reproduce.

**Comment by 0nko** [comment]
:shipit:

**Comment by 0nko** [comment]
:shipit: for real now

**Pull request merged**
