### PR TITLE
HackWeek: Migrate MediaPlayer to ExoPlayer

### PR DESCRIPTION
**Pull request by ashiagr**
This PR contains minimum viable changes to replace `MediaPlayer` to `ExoPlayer` in the `MediaPreviewFragment`.

##### Remote Media (for a site)

1. Launch app and go to My Site ->  Media for a site with already uploaded media assets
2. Click an image/ audio/ video to go to media settings screen
3. Click on the image/ play icon on the media settings screen 
4. Verify that selected media is shown/ played properly 
5. Swipe left/ right - notice that correct image/ video / audio is shown/ played 

Try to test for different supported audio/ video formats. 
[Media in different formats can be found [here](https://rb.gy/oizmh1)]

##### Local Media (on device)

1. Launch app and go to My Site -> Post
2. Add a Video/ Image block
3. Select “Choose from device” and long press a thumbnail on the following screen
4. Notice that media stored locally on the device is opened/ played properly

#### Freshly created video plays on a private site

1. Open a private site
2. Upload a new video freshly created with the phone’s camera
3. Go to the media section and tap on the new video to see the media settings screen
4. Tap on the play icon, notice that video can play

Earlier these could not be played: [comment#4](https://rb.gy/xpky0p)

Before | After
-------|------
cant play| private_site_video

#### On device with API <= 23 and API > 23 

It'd be great if anyone can test playing videos on devices with API <= 23. I tested on emulators and get this error:

```
Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(22050, 12, 22048)
        at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1893)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:835)
```

Same error is noticed in the [ExoPlayer demo app ](https://rb.gy/6iqckp)so looks like it has something to do with [old emulators](https://stackoverflow.com/a/63444407/193545).      

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@ashiagr 
Ran into an error
1. Public site - uploaded videos 
2. Sometimes a video would not show or load, but a PTR seems to have fixed that
3. Switched the site to private 
4. Logged out of app, cleared cache and data
5. Logged back into the app
6. Headed over to media
7. No previews of any media is showing
8. Uploaded a brand new video freshly taken with the device camera
9. There is no preview for the video, but I can tap on it to get to the play view, but the video won't play (logs below)
10. Create a new post & add the video you just took from the media section
11. Post creates and play video
12. Navigate back to media & the new video is shown in the preview grid, plus I can tap on it and play it without a problem.

**Logs show**
10-07 10:01:20.199 E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:193)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by mzorz** [comment]
This is great @ashiagr ! will look into this as soon as possible 👍

**Comment by ashiagr** [comment]
hey @zwarm 

I tested the flow on live app (ver 16.1-rc-1) and have some findings to share.

When I upload a video (captured from camera or chosen from device) from mobile on a wordpress.com site with business plan [it was an atomic (WoA) site] and upload finishes, server sends a media response with a url containing a dash instead of dot before the video format e.g. (`-mp4` instead of `.mp4`). 

media_response_wrong_url

This url is passed to the media preview fragment where it fails to [qualify as a video url](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java#L74-L82):

wrong_url_video

I tested it on a public site, so site privacy doesn't seem to be an issue. When I leave and return to the media preview screen, correct response is received (with url ending with .mp4) and video can be played fine this time.

See video (captured on Android 10, app ver 16.1-rc-1)
https://cldup.com/CBxy880m-N.mp4

I also tested it on a simple site with free plan and could not reproduce it.

I'll create a separate issue to track it as it doesn't seem to be related to changes in this PR.

**Comment by malinajirka** [comment]
@ashiagr This PR looks stale - are you planning on working on it or should we close it?

**Comment by ashiagr** [comment]
This can be closed. I'll create another one when I'll work on it again.

**Pull request closed without merging**
