### PR TITLE
Api26/stats service loading spinner

### PR DESCRIPTION
**Pull request by mzorz**
Coming from https://github.com/wordpress-mobile/WordPress-Android/pull/7617#issuecomment-379583077 and  https://github.com/wordpress-mobile/WordPress-Android/pull/7506#issuecomment-379915796

This is an improvement over the current intermittent PTR spinner, and makes the loading spinning wheel stay for as long as there are scheduled Jobs expected to be finished.

Note: I have seen some glitches while going back and forth from the Stats screen or changing the filter repeatedly, but it should work fine enough for people using the screen normally.

cc @nbradbury

### CODE REVIEW

**Comment by nbradbury** [comment]
Although this isn't an ideal solution, it does appear to work well on API 26+. However, I tested this on an API 19 emulator and the PTR progress never disappeared - I left the emulator running for several minutes and the progress remained visible the entire time.

**Comment by mzorz** [comment]
> tested this on an API 19 emulator and the PTR progress never disappeared

Thanks for checking this - will come back shortly 👍

**Comment by mzorz** [comment]
I totally overlooked testing on platforms < API 26 @nbradbury 🤦‍♂️ - I apologize for that.

Handling for these platforms should be addressed now in f6d6060.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
