### PR TITLE
Update support library to 28

### PR DESCRIPTION
**Pull request by malinajirka**
First step in preparation for #9209 (Migration to AndroidX).

- I've updated compileSdkVersion and support library version to api 28

- Some modules required me to explicitly add new dependencies to override versions of transitive dependencies. For example `exifinterface:27.1.1` was added as transitive dependency and AS was complaining that having dependencies from both 27.1.1 and 28.0.0 isn't recommended. (I recommend using AS diff tool to compare what has changed, since GitHub doesn't do a very good job)

- I've fixed places in the code which were targeting old apis. The biggest change is in [#1bf1872](https://github.com/wordpress-mobile/WordPress-Android/commit/1bf18720cee0c1cb679c7a0ef20e67239948279c). Reflection isn't required anymore in order to suppress shift animation on the bottom navigation bar.

- Some resources we use from the support library have been marked as private -> fixed in [da2dc8e](https://github.com/wordpress-mobile/WordPress-Android/pull/9215/commits/da2dc8e3f37276a3a2dab40afe00b93219605fdc)

To test:
- run the app
- switch tabs in the bottom navigation bar and make sure the animation hasn't changed

Update release notes:

- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

Question: Should we push the changes to the subtrees?
Note: One reviewer should be enough.

### CODE REVIEW

**Comment by malinajirka** [comment]
@jtreanor It seems we might need to accept an updated license on the CI server. Can you please take a look into it. Thanks!

```
Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
```

**Comment by jtreanor** [comment]
@malinajirka you should be able to update the image used in ‘.circleci/config.yml`. Just change 27 to 28!

**Comment by kwonye** [comment]
Thanks for doing this, @malinajirka!

Everything compiles and after doing intensive smoke testing things are running smoothly! That said, there are issues with the tests:

`androidTest` is failing to compile and in `test`, `QuickStartViewModelTest.testSetDoneTask()` is failing.

**Comment by malinajirka** [comment]
Thanks @kwonye !!

>in `test`, `QuickStartViewModelTest.testSetDoneTask()` is failing.
Hmm, it's weird. I've run it locally and I assume CI runs it as well and it works as expected for me.

>`androidTest` is failing to compile
I'll need to look into this. It seems some of the classes we use were deprecated a while ago and they removed them in v28.

**Comment by malinajirka** [comment]
@kwonye I've fixed the issue with androidTests. It's ready for another round;). Thanks!

`WPScreenshotTest.wPScreenshotTest` keeps failing with the following message "Unable to capture screenshot.". However, it's failing even on `develop` so I assume the issue wasn't introduced in this PR.

**Pull request merged**
