### PR TITLE
[Jetpack Focus] Revamp Landing Screen

### LINKED ISSUE #17072: [Revamp Landing Screen] WPAndroid - Remove carousel & redesign landing screen
Redesign the landing screen of the WordPress app, by replacing the carousel with a static wp-admin themed splash screen:

WPSplash

---
- Development should be behind [the recently introduced feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17071).

### LINKED ISSUE #17073: [Revamp Landing Screen] JPAndroid - Update landing screen to match new design (no text animation)
Redesign the landing screen of the Jetpack Android app to match the new design.
- Animation for the large text is in scope of another issue.

JPSplash

---
- Development should be behind [the recently introduced feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17071).

### LINKED ISSUE #17074: [Revamp Landing Screen] JPAndroid - Add default animation to large text (no sensors feedback)
Add a "default"* text animation to the large text on the Jetpack iOS app landing screen.

The large text should have been introduced with the PR that closes [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17073).

📜 Animation to be provided by project design lead.

---
/* By "default" we mean the animation will run infinitely, and it won't be influenced by the gyro sensor.

### PR DESCRIPTION
**Pull request by ovitrif**
Resolved #17072, resolved #17073, resolved #17074

This PR combines the work that was done to individually resolve the issues listed above and merges it into `trunk` as a shippable update behind a feature flag.

Remarks: 
1. Since toggling the feature flag requires to login, and navigating to this screen requires being logged out, it can be cumbersome to go back and forth between implementations. To make this easier, the _Prerequisite_ section from the testing steps includes a hard-coded approach.
2. On the Jetpack Landing Screen, the blur effect behind the buttons is only applied for devices running `Android12+`. On older Android versions, a semi-transparent visual effect is applied.
3. The Login screen orientation was locked to `landscape` to match with the iOS apps.

To test:
<details>
<summary><b>Prerequisite</b> - Enable the <code>LandingScreenRevamp</code> feature flag</summary>

- Either `login` → `Me` → `App Settings` → `Debug Settings` → enable `LandingScreenRevamp` → `RESTART THE APP` → `logout` or
- Apply this hard-coded solution:

<details>
<summary>Patch to enable the <code>LANDING_SCREEN_REVAMP</code> build flag</summary>

```diff
diff --git a/WordPress/build.gradle b/WordPress/build.gradle
index 63260a4ca8..fe999fa92f 100644
--- a/WordPress/build.gradle
+++ b/WordPress/build.gradle
@@ -112,7 +112,7 @@ android {
         buildConfigField "boolean", "READER_COMMENTS_MODERATION", "false"
         buildConfigField "boolean", "SITE_INTENT_QUESTION", "true"
         buildConfigField "boolean", "SITE_NAME", "false"
-        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "false"
+        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "true"
         buildConfigField "boolean", "LAND_ON_THE_EDITOR", "false"
         buildConfigField "boolean", "BLOGGING_PROMPTS", "false"
         buildConfigField "boolean", "QUICK_START_EXISTING_USERS_V2", "false"
```  
</details>

---

</details>

##### 1️⃣ Test Case 1: WordPress Landing Screen — Happy Flow

0. Open the WP app and make sure you're logged out
1. The new login screen should be visible
4. Put the device in dark mode
5. The dark mode design should be readable
6. Change to an RTL locale
7. **Expect** the screen to match design specs:

<details>
<summary>WordPress Landing Screen Revamp — Design</summary>

wp_redesign
</details>

##### 2️⃣ Test Case 2: WordPress Landing Screen — Login Flow

0. Open the WP app and make sure you're logged out
1. From the login screen, tap the `Log in or sign up with WordPress.com` button
2. **Expect** to be presented with the login flow
3. Go back
4. Tap the `Enter your existing site address` button
5. **Expect** to be presented with the site address login flow

##### 3️⃣ Test Case 3: Jetpack Landing Screen — Happy Flow

0. Open the JP app and make sure you're logged out
1. The new login screen should be visible
2. Put the device in dark mode
3. The dark mode design should be readable
4. **Expect** the large text to animate infinitely
5. **Expect** the screen to match design specs:

<details>
<summary>Jetpack Landing Screen Revamp — Design</summary>

jp_redesign
</details>

##### 4️⃣ Test Case 4: Jetpack Landing Screen — Login Flow

0. Open the JP app and make sure you're logged out
1. From the login screen, tap the `Continue with WordPress.com` button
2. **Expect** to be presented with the login flow
3. Go back
4. Tap the `Enter your existing site address` button
6. **Expect** to be presented with the site address login flow

##### 5️⃣ Test Case 5: WordPress/Jetpack Landing Screen — Accessibility font size

0. Open the WP/JP app and make sure you're logged out
1. Set larger/smaller font sizes via Accessibility settings
2. **Expect** Readable texts and clickable buttons without UI artifacts.

##### 6️⃣ Test Case 6: WordPress/Jetpack Landing Screen — Regression

0. Disable the <code>LandingScreenRevamp</code> feature flag (revert change from **Prerequisite**)
1. Open the WP/JP app and make sure you're logged out
2. **Expect** To be presented with the previous design
3. Tap any of the 2 buttons
4. **Expect** the Login flows to start as expected

## Previews

<details>
<summary>WordPress App</summary>

| Light | Dark |
| - | - |
|  |  |
</details>

<details>
<summary>Jetpack App</summary>

| Light | Dark |
| - | - |
|  |  |
</details>

## Regression Notes
5. Potential unintended areas of impact
  Previous WordPress and Jetpack login screen.

7. What I did to test those areas of impact (or what existing automated tests I relied on)
  Manual testing + added testing steps for regression.

8. What automated tests I added (or what prevented me from doing so)
  This PR only adds UI changes (under a feature flag).

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @ovitrif 👍 
I retested the flows with both apps on my Pixel 5 (Android 13) and everything worked as expected. The code changes also LGTM and the internal release note looks good 🎉 

Notes:
1. I encountered again [the issue reported here with the bars on top and bottom](https://github.com/wordpress-mobile/WordPress-Android/pull/17117#issuecomment-1253789439). I remember that I've [tested the fix and it worked](https://github.com/wordpress-mobile/WordPress-Android/pull/17117#issuecomment-1253873568) and confirmed that the commit is included on this branch 🤔. Since I validated that this does not affect the app when the feature is off I suggest to proceed with merging this PR and revisit the issue independently. Wdyt?
2. This is more of a compose newbie question. In a few cases ([example 1](https://github.com/wordpress-mobile/WordPress-Android/pull/17203/files#diff-11826c10771cb5a0a4c6eef40becd151e343e12690e6bfd5b57b1f7063a0612aR23), [example 2](https://github.com/wordpress-mobile/WordPress-Android/pull/17203/files#diff-0ddbcac04d7f8e41dd4ecdc185e45a7b357addd9d9822210e14ab73c2267bccdR77)) we are using hardcoded dimensions in the code (e.g. `60.dp`). Can those be extracted as resources?

**Comment by ovitrif** [comment]
> 1. I encountered again [the issue reported here with the bars on top and bottom](https://github.com/wordpress-mobile/WordPress-Android/pull/17117#issuecomment-1253789439). I remember that I've [tested the fix and it worked](https://github.com/wordpress-mobile/WordPress-Android/pull/17117#issuecomment-1253873568) and confirmed that the commit is included on this branch 🤔. Since I validated that this does not affect the app when the feature is off I suggest to proceed with merging this PR and revisit the issue independently. Wdyt?

Very strange indeed, though I agree with your plan 👍 
Thanks a lot for testing all sides (especially whether this affects the app without the feature flag off) 🙇 


> 2. This is more of a compose newbie question. In a few cases ([example 1](https://github.com/wordpress-mobile/WordPress-Android/pull/17203/files#diff-11826c10771cb5a0a4c6eef40becd151e343e12690e6bfd5b57b1f7063a0612aR23), [example 2](https://github.com/wordpress-mobile/WordPress-Android/pull/17203/files#diff-0ddbcac04d7f8e41dd4ecdc185e45a7b357addd9d9822210e14ab73c2267bccdR77)) we are using hardcoded dimensions in the code (e.g. `60.dp`). Can those be extracted as resources?

Had a long discussion on this topic with @mkevins, our conclusion was to freely use hardcoded values in Compose UI code since this would allow for seamless future tweaks & layout updates if needed, and proceed with extracting / reusing dimensions in Kotlin code rather than making use of resources.

We'd still be using resources when there's an advantage to this (e.g. strings because of the localization system, dimensions/ colors when we're making use of values dependent on configuration).

The discussion is definitely not "closed" and your feedback is more than welcome! 

Does this sounds good for a plan with Compose? 😸

**Comment by antonis** [comment]
> Does this sounds good for a plan with Compose? 😸

Sounds good to me. Thank you for the extra context @ovitrif 🙇

**Comment by ovitrif** [comment]
Merging this as discussed 🚀

**Pull request merged**
