### PR TITLE
[Gutenberg] Hide audio block on free sites

### PR DESCRIPTION
**Pull request by ceyhun**
gb-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3129

Hide audio block on free sites.

### Testing

1. Switch to a free/simple site
1. Open editor
1. Tap block inserter
1. Audio Block should not be in the list  
 
#
  
1. Switch to a paid/self-hosted site
1. Open editor
1. Tap block inserter
1. Audio Block should be in the list

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jd-alexander** [comment]
@ceyhun I will have to branch from this PR by @mzorz https://github.com/wordpress-mobile/WordPress-Android/pull/14034 because this `gutenberg-mobile` submodule hash only contains the changes for the release and it doesn't contain the story related changes that haven't been reverted as yet so the Android build is failing. So yes, I will change the base of this. I am just making a note of this here for review purposes 😄

**Comment by jd-alexander** [comment]
I'm now seeing where the revert will not be done and the changes will be included so I'm going to double check on the gutenberg-mobile side of things for verification to resolve this error.

**Comment by jd-alexander** [comment]
@ceyhun based on this comment 

> Will change base to release/1.46.1 branch when it's ready.

on the `gutenberg-mobile` PR I went ahead and added the Android changes here and I  was able to test locally by removing code that was causing the build to fail due to the Story changes not being present. I am also testing the self-hosted flow to verify all is well there. 

Once the changes have been either reverted or added and `release/1.46.1` has been finalized this PR can be retested.

**Comment by jd-alexander** [comment]
@ceyhun do you want to give this a test as well? All is working from my side with the following flows: 

1. WPCom simple site with a free plan. - Audio block is not shown in the inserter.
2. WPCom simple site using a paid plan - Audio block is shown in the inserter.
3. Self-hosted site - Audio block is shown in the inserter.

**Comment by ceyhun** [comment]
@jd-alexander working fine from my side as well 👍

**Review by jd-alexander — APPROVED** [review]
Approved! Awaiting confirmation that the `gutenberg-mobile` and `gutenberg` are in sync and good to go!

**Pull request merged**
