### PR TITLE
Fixes broken links on some notifications due to ranges with invalid urls

### LINKED ISSUE #13113: Some announcement badges contain text that looks like they are links but that aren't active
### Expected behavior

I expect that any text that looks like a link in the announcement badges will work like a link.

### Actual behavior

Some text, usually numbers, look like they are links but nothing happens when you tap on them.

### Steps to reproduce the behavior

Trigger any announcement badge that contains links and try to tap on them. ([56s](https://cloudup.com/c2GMVrCiSA2))

Some example announcement badges I tested were: 

20 Likes|Boom!
---|---
Screen Shot 2020-10-12 at Oct 12 4 05 22 PM|Screen Shot 2020-10-12 at Oct 12 4 06 20 PM

### PR DESCRIPTION
**Pull request by antonis**
Fixes #13113

## Description
This PR skips notification text ranges with UNKNOWN type and no URL since they are not actionable and seem to interfere with valid link ranges. An example response that reproduced the issue is the following.
<details>
  <summary>Response</summary>

```
{
  "body": [
    {
      "text": "Go through your site set-up checklist.Watch a getting started video or join our free live webinars.Check out our help library.",
      "ranges": [
        {
          "type": "ol",
          "indices": [
            0,
            126
          ],
          "id": "5",
          "parent": null,
          "class": "wpnc__ol--outside"
        },
        {
          "type": "li",
          "indices": [
            0,
            38
          ],
          "id": "6",
          "parent": "5"
        },
        {
          "url": "https:\/\/wordpress.com\/help\/",
          "indices": [
            113,
            125
          ],
          "id": "21",
          "parent": "19",
          "type": "a"
        },
        {
          "url": "https:\/\/wordpress.com\/home",
          "indices": [
            16,
            37
          ],
          "id": "8",
          "parent": "6",
          "type": "a"
        },
        {
          "type": "li",
          "indices": [
            38,
            99
          ],
          "id": "11",
          "parent": "5"
        },
        {
          "url": "https:\/\/wordpress.com\/support\/video-tutorials\/",
          "indices": [
            46,
            67
          ],
          "id": "13",
          "parent": "11",
          "type": "a"
        },
        {
          "url": "https:\/\/wordpress.com\/webinars\/",
          "indices": [
            90,
            98
          ],
          "id": "16",
          "parent": "11",
          "type": "a"
        },
        {
          "type": "li",
          "indices": [
            99,
            126
          ],
          "id": "19",
          "parent": "5"
        }
      ]
    }
  ]
}
```

</details>

-----

## To Test:

Follow the steps in https://github.com/wordpress-mobile/WordPress-Android/issues/13113#issuecomment-1980084307

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/a4abc3f8-cdc0-48d9-8fe3-d9a4778485c0

-----

## Regression Notes

1. Potential unintended areas of impact

    - Notifications Details page

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - Added a test case for the added logic

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by antonis** [comment]
> [C Maintainability Rating on New Code](https://sonarcloud.io/dashboard?id=wordpress-mobile_WordPress-Android&pullRequest=20417) (required ≥ A)

A couldn't find a way to make the code more maintainable and pass the optional test without fully refactoring the method/class. Any suggestions are welcome.

**Review by mkevins — APPROVED** [review]
Nice work! This fixes the links, and code changes look good. Thank you for adding tests!

I've added [a small suggestion branch](https://github.com/wordpress-mobile/WordPress-Android/compare/fix/13113-notif-links...fix/13113-notif-links--suggestion-nullness-annotations). It has some nullness annotations which I added after analyzing the code, along with an IDE suggestion: using a lambda). Feel free to merge as is, or include those changes as well if you'd like. 😄

**Comment by antonis** [comment]
Thank you for reviewing and your suggestion @mkevins 🙇 

> I've added [a small suggestion branch](https://github.com/wordpress-mobile/WordPress-Android/compare/fix/13113-notif-links...fix/13113-notif-links--suggestion-nullness-annotations). It has some nullness annotations which I added after analyzing the code, along with an IDE suggestion: using a lambda). Feel free to merge as is, or include those changes as well if you'd like. 😄

Your suggestion makes sense and also fixed the sonarcloud error https://github.com/wordpress-mobile/WordPress-Android/pull/20417#issuecomment-1981367330 I was struggling with :)

**Pull request merged**
