### PR TITLE
Remove fixed issues from lint-baseline.xml

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes the following warning [from the lint task](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/24304/workflows/7b139331-794d-46fb-8352-7a0c1f3c2e85/jobs/108659):

> 184 errors/warnings were listed in the baseline file (/home/circleci/project/WordPress/lint-baseline.xml) but not found in the project; perhaps they have been fixed?

I've tried my best to remove everything in place, so the diff would only have removals, but unfortunately it still shows some minor movements. I don't think it matters though, since the baseline file only matters for ignoring lint issues and since I started from a commit with a successful lint task, there is very little that can go wrong with it.

I tried to regenerate the file, [as suggested by docs](https://developer.android.com/studio/write/lint#baseline-warning), but that caused a lot of movement and even a failure. It's probably not something we want to do right now and I'd really like to see us fixing these lint errors. We have a lot of them and looks like we keep adding new warnings :(

**To test:**
N/A

_P.S: This was not fun at all! 😭_

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AliSoftware — COMMENTED** [review]
First of all, I really appreciate the time you took to make the diff as minimal as possible by editing it manually as much as you could!! ❤️ 🧸  That must have been quite a lot of work.

---

The diff and changes make sense to me, and running `./gradlew lintWordPressVanillaRelease` indeed get rid of most warnings that were listed in baseline but fixed since. I still got this after the run though:

```
1 errors/warnings were listed in the baseline file (/Users/olivier/Documents/Dev/apps/WordPress-Android/WordPress/lint-baseline.xml) but not found in the project; perhaps they have been fixed?
```

I've looked at the docs and I have no idea how to see what this single fixed issue is to allow us to manually remove just this one from the baseline?
The only suggestion I can read in the docs is to remove the `lint-baseline.xml` and re-run lint to regenerate it… but as you mention in the PR description that generates too big a change (even with `git diff --color-moved --minimal`…) to understand which issue would be removed from the baseline when doing this.

---

Also, unfortunately, the PR apparently now has conflicts with `develop` 😒 It seems the conflict comes from the login subtree removal from https://github.com/wordpress-mobile/WordPress-Android/issues/14742 earlier today. Since you're also the author of that PR I'll let you resolve the conflict as you'll probably be more aware of what you did there and what to keep.

**Comment by ParaskP7** [comment]
👋 @oguzkocer and @AliSoftware !

I am glad that I noticed this PR. 😅 

I actually started doing the same work today, as part of my hack week. I was supposed to do that during the previous hack week but had to help with another task instead. Plus, I want to afterwards fix/remove as many issues as I can from the baseline so that we can ultimately get rid of that.

I have a pretty decent idea on how to do that step-by-step and then after having the correct unused baseline issues removed from this outdated baseline, to replace the old `<issues format="4" by="lint 3.1.3">` baseline format with the newest `<issues format="5" by="lint 4.0.2">` one.

Let me know how I can help you with this task so that we can maybe avoid duplicate work as well. 🙏

**Comment by AliSoftware** [comment]
@ParaskP7 I'll let Oguz give you his final go since he's the one who opened that PR, but my suggestion is that it will probably be okay for you to take over this, i.e. don't hesitate to push a commit to this PR to get rid of the remaining issue listed in baseline but already fixed, and help fix the conflict, so this can be merged ASAP; then once this is merged we'll be happy to let you open other PRs on top of this one to go forward with your HACK week, including updating the lint file format from 4 to 5

**Comment by ParaskP7** [comment]
Thanks for your input @AliSoftware ! 🙏 

Sure, sounds like a plan, I'll also wait for @oguzkocer input as well before progressing in any direction. At the moment I have pulled this branch and I am playing with it. I'll post my findings to help us progress in the meanwhile.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

I went through the changes and can verify that you did almost everything that I would have done with some slight exceptions. I will mention those below. I might have also removed the already fixed issues step-by-step, like commit-by-commit, per group, just for me to manage all that better without ending up 😭 and pulling my hair off my head.

✅ Firstly, I agree with you removing the below issues from the baseline, even if those are not fixed, per se. I agree with that approach since all of them are already present as warnings anyway, so removing those from the baseline will just at to the number of the already existing issues on our list. PS: `VectorPath` can be removed as well. Those are:
- `InflateParams` (2)
- `SetJavaScriptEnabled` (2)
- `VectorPath` (1) 🔍 - Here I also suggest removing another one of those from the baseline, the last one left, so in total it would be (2) instead.
- `Overdraw` (10)
- `IconDensities` (2)
- `AlwaysShowAction` (1)

⚠️ However, I suggest to add back the below issues to the baseline, since those are not present as warning at the moment, and we might not want to add them to the list. Ideally, I suggest having the same diff, plus the numbers above. Those are:
- `LocaleFolder` (2)
- `TrustAllX509TrustManager` (4)
- `IconMissingDensityFolder` (1)

💡 Finally, I suggest removing the `ResourceType` issue from the baseline and suppressing this one directly on the `WPSwipeToRefreshHelper.buildSwipeToRefreshHelper(...)` method itself with `@SuppressLint("ResourceType")`. The reason for me suggesting that is because with the new format I anyway got that warning misbehaving and I seemed it doesn't work as much with this older format too. Anyway, this would have been one of those warning that I would personally prefer closer to the issue itself instead of having it persistent in the baseline, and thus ultimately adding to its growth, instead of it shrinking. PS: Maybe this is the one issue we are hunting here.

**UPDATE**: Actually this aforementioned `ResourceType` issue is the one that you and @AliSoftware are hunting for, this last one persisting as `listed but not found`. Making the change I suggested above seems to be solving it.

**Comment by oguzkocer** [comment]
> I've looked at the docs and I have no idea how to see what this single fixed issue is to allow us to manually remove just this one from the baseline?

@AliSoftware I forgot to mention this in the PR description. There are no warnings in the `lint-baseline.xml` anymore, so somehow one of the errors is reported as a warning and I didn't want to spend too much time on it as part of this PR.

> I might have also removed the already fixed issues step-by-step, like commit-by-commit, per group, just for me to manage all that better without ending up 😭 and pulling my hair off my head.

@ParaskP7 I did that too, but they weren't clean commits, so I combined them all in another branch.

> ⚠️ However, I suggest to add back the below issues to the baseline, since those are not present as warning at the moment, and we might not want to add them to the list. Ideally, I suggest having the same diff, plus the numbers above. Those are:

@ParaskP7 I removed _all_ warnings from `lint-baseline.xml` because we have 300+ warnings already and having a few specific ones in the baseline didn't make sense to me. I don't mind re-adding them if there is a good reason for it, but I am not sure what that would be.

> 💡 Finally, I suggest removing the ResourceType issue from the baseline and suppressing this one directly on the WPSwipeToRefreshHelper.buildSwipeToRefreshHelper(...) method itself with @SuppressLint("ResourceType")

Sure, I'll take care of it.

---

@ParaskP7 I'd much prefer to separate the updating the baseline work from the lint improvement work you're suggesting. Even if you want to add some of them back to `lint-baseline.xml`, it'd be better to do that in a separate PR so we can track down the reason if we need to. Let me know if that works for you and we'll get this merged in, so you can take over the lint work. _I really appreciate you working on that btw._

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @ParaskP7 I did that too, but they weren't clean commits, so I combined them all in another branch.

👍 

> @ParaskP7 I removed all warnings from lint-baseline.xml because we have 300+ warnings already and having a few specific ones in the baseline didn't make sense to me. I don't mind re-adding them if there is a good reason for it, but I am not sure what that would be.

This is true, given that fact, I think it might be beneficial if we remove those from the baseline and add them in the list. Your reasoning makes sense. Let's do that.

PS: I was purely thinking of it as a no diff task, but we can definitely add this one exception if it is anyway for the best, which is removing the need for the baseline in the first place.

> Sure, I'll take care of it.

👍 

-----

> @ParaskP7 I'd much prefer to separate the updating the baseline work from the lint improvement work you're suggesting. Even if you want to add some of them back to lint-baseline.xml, it'd be better to do that in a separate PR so we can track down the reason if we need to.

Same here, I think it is best if all that is done in separate PRs. Me saying that `I want to afterwards fix/remove as many issues as I can from the baseline so that we can ultimately get rid of that`, I meant doing it,  later on, as a separate task/PR.

> Let me know if that works for you and we'll get this merged in, so you can take over the lint work.

Yes, 💯 , when you are ready we can merge this and I can take over the lint work.

PS: I am going to log-off now, but I'll catch up with the rest tomorrow.

> I really appreciate you working on that btw.

Back to YOU! 🙏

**Comment by oguzkocer** [comment]
@AliSoftware I've fixed the merge conflict and, following @ParaskP7's advice, moved `ResourceType` lint error suppression to the source code in 79be1e92b40cad95a6bc75ae533ec04bf86950b8 which got rid of the extra warning. I think this is ready to be merged as long as the CI is green. 🤞

**Review by AliSoftware — APPROVED** [review]
Re-tried linting and no more mention about baseline warnings to be removed 👍

**Comment by ParaskP7** [comment]
👋 @oguzkocer and @AliSoftware !

Merged, awesome! 🎉 

As discussed, I'll take this over now and continue with the below 2 next tasks:
- Upgrade the baseline from the current old to the newest format.
- Fix/Remove individual baseline issues, with the end goal of getting rid of the baseline for good.

When those 2 PRs are ready, would you mind if I assign you as reviewers on both? 🙏

**Comment by oguzkocer** [comment]
@ParaskP7 Sounds good - thank you!

**Pull request merged**
