### PR TITLE
[Tags IA] Integrate subfilters and post list in Tags Feed

### LINKED ISSUE #20669: [Reader] Implement "More from <tag>" row
UI already implemented on https://github.com/wordpress-mobile/WordPress-Android/pull/20686

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #20669 

- Refactor `SubFilterViewModel` to move relevant observers to `ReaderFragment` and be able to reuse it properly in Tags Feed
- Fix subfilter in the top bar for Tags Feed
- Implement the tag pills and "view more" feed button actions
- Implement functionality to show the post list for selected/filtered tag

-----

## To Test:

1. Make sure the `reader-tags-feed` feature flag is on
2. Go to Reader
3. Go to the Tags Feed
4. **Verify** the top bar shows the "X Tags" pill
5. Tap the filter chip in the top bar
6. **Verify** it opens the filter bottom sheet
7. Select a tag
8. **Verify** it opens the Post List for that tag
9. Clear the filter
10. **Verify** it returns to the Tags Feed
11. Tap the "header" pill for a tag in the feed
12. **Verify** it opens the Post List for that tag
13. **Verify** it updates de top bar subfilter pill
14. Clear the filter
15. **Verify** it returns to the Tags Feed
16. Scroll horizontally to the end of a tag post row
17. Tap "More from <tag>"
18. **Verify** steps 12-15 happen 

-----

## Regression Notes

1. Potential unintended areas of impact

    - Breakage of top bar filters in other filterable screens (subscriptions/P2/automattic)

19. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

20. What automated tests I added (or what prevented me from doing so)

    - WIP

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ActionEvent</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by daniloercoli — COMMENTED** [review]
👍 The code is well-structured with clear separation of concerns. 

I noticed that PTR doesn't work anymore in the Tags Feed.

Aside from this, the feature seems to work as expected. I've also noticed a couple of things about the new UI; I'm 99% sure they are not related to this PR, but I want to collect my feedback here since we're now working with a UI that uses real data:

* Having to deal with horizontal lists of non-homogeneous items sometimes made me think there was a problem with the UI, even though it's not a problem of the UI itself; it's because the posts don't have pictures in them.

* Scrolling horizontally through a row can be stuttering, and it's definitely not smooth on my device, a Pixel 5. It's not a new device, but it's not that old either.

* I see the same problem with vertical scrolling in the feed. Follow a few tags, and try to scroll vertically. (The same happens when you follow new tags and go back to the list; you see the placeholders, and vertical scrolling is a bit stuttering.)

**Comment by thomashorta** [comment]
> I noticed that PTR doesn't work anymore in the Tags Feed.

We didn't implement it yet, so it never worked in the Tags Feed. There's an issue opened for implementing that: https://github.com/wordpress-mobile/WordPress-Android/issues/20707

Regarding the stuttering, right now the tag loading is far from optimal, since we're requesting everything at once and I'm not even sure what's running on the UI thread and what's actually being sent to a background thread. We still have other tasks to improve that, like this: https://github.com/wordpress-mobile/WordPress-Android/issues/20708 Thanks for bringing it up!

**Comment by thomashorta** [comment]
I just added the `unit-tests-exemption` since dangermattic is complaining about the `ActionEvent` class in the `ReaderTagsFeedViewModel` but @RenanLukas is actually working on more actions in https://github.com/wordpress-mobile/WordPress-Android/issues/20670 which will likely change how things work regarding actions, therefore I will leave the tests for that `OpenTagPostsFeed` untested for now.

**Comment by daniloercoli** [comment]
> > I noticed that PTR doesn't work anymore in the Tags Feed.
> 
> We didn't implement it yet, so it never worked in the Tags Feed. There's an issue opened for implementing that: #20707
> 
> Regarding the stuttering, right now the tag loading is far from optimal, since we're requesting everything at once and I'm not even sure what's running on the UI thread and what's actually being sent to a background thread. We still have other tasks to improve that, like this: #20708 Thanks for bringing it up!

Okay, thanks for the clarification; I didn't notice the ticket about PTR. Approving this PR!

**Review by daniloercoli — APPROVED** [review]

**Pull request merged**
