### PR TITLE
[Modules Restructuring] Restructure Mocks Module

### LINKED ISSUE #16566: Modules Restructuring - Mocks Module
Parent #16562
Related Repo [WordPressMocks](https://github.com/wordpress-mobile/WordPressMocks)

This issue is about investigating the `mocks` lib project module and converting it to pure module.

- [x] Investigate module @ParaskP7
  - [ ] ⛔️ [DEPRECATED] prefix added to the `About` section of the [related repo](https://github.com/wordpress-mobile/WordPressMocks).
  - [x] Archive [related repo](https://github.com/wordpress-mobile/WordPressMocks) and make it read-only ❓ 🤔 (just like it is done for the [networking](https://github.com/wordpress-mobile/WordPress-Networking-Android) repo)
- [x] Convert to pure module @ParaskP7 #16784

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #16562
Fixes #16566

This PR restructures the `mocks` module by disassociating the [WordPressMocks](https://github.com/wordpress-mobile/WordPressMocks) repo and removing the extra `WordPressMocks` level from it. This effectively makes `mocks` a pure module, without any extra inner levels or unnecessary build files lying around (like `settings.gradle`, `.gitignore`, etc).

PS: @ashiagr I added you as the main reviewer, that is, in addition to the @wordpress-mobile/owl-team team itself, since I am seeing you being the last WPAndroid engineer working with Mocks recently, which will come handy for testing purposes. As such, I think you might be the best person to sign-off on that change for WPAndroid. 🥇

-----

Question (❓): As per my licensing question on this other related PR of mine [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16744) and since I saw that the `LICENCE` file for this module is `GPLv2`, unlike the `analytics` mode, which is pointing to `MIT`, I deleted the licence for this module to start depending solely on the root level `LICENCE` that WPAndroid is using, which is `GPLv2` as well, wdyt? 🤔

-----

To test:

- Build the app and install it on your device or emulator.
- Find the `LoginTests.loginWithEmailPassword()` e2e test and trigger it.
- Verify that the test succeeds as expected.
- Find the `rest_v11_me_sites.json` mapping file from within the `mocks` module and delete it.
- Re-trigger the `LoginTests.loginWithEmailPassword()` e2e test and verify that it now fails (see expected test failure below).
- Add back the `rest_v11_me_sites.json` mapping file and re-trigger the `LoginTests.loginWithEmailPassword()` e2e test.
- Verify that the test succeeds as expected. This means that the needed mapping file is loaded and as such makes sure that the `mocks` module, along with all its mapping, files works as expected.

`Expected test failure`:
before

The above is just one example of how this change can tested so that we could quickly verify the overall correctness of this PR. However, feel free to smoke test other e2e tests as well.

-----

## Regression Notes
1. Potential unintended areas of impact

N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: The [Optional Test -> Connected Test-2](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/32071/workflows/e7752447-7732-4f42-b69a-fb33ab60f017) job also succeed, which further verifies that everything `mocks` related is working as expected. ✅

**Review by ashiagr — APPROVED** [review]
Found everything working, 👍 thank you for the changes!

**Comment by ParaskP7** [comment]
👋 @ashiagr !

Thank you so much for reviewing, testing and giving us a 👍 , you rock! 🙇

**Review by oguzkocer — APPROVED** [review]
Gradle changes look good to me.

P.S: I am trying to catch up, so I didn't test this PR, sorry about that!

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Thank you reviewing this PR and for the 👍 ! 🙇 

> P.S: I am trying to catch up, so I didn't test this PR, sorry about that!

Of course, and THANK YOU again, you rock! 💯

PS: There is no need for you to test this PR, Ashita already did that for us! 🥇

**Pull request merged**
