### PR TITLE
Issue/13268 filters 1

### PR DESCRIPTION
**Pull request by malinajirka**
Parent #13268

This PR
- adds a divider to the filter bar
- adds a shadow when the recycler view scroll position != 0
- adds border to the chips
- updates margins/paddings

Note:
- filter labels and cancel actions are coming in the next PR
- I'll ask for a design review on the next PR when the filter bar is finalized

To test:
1. Enable ActivityLogFilters feature flag
2. Open Activity Log
3. Check the filter bar and its styles
4. Scroll down and notice a shadow appears
--------------
1. Disable ActivityLogFilters feature flag
2. Open Activity Log
3. Verify the divider and the filter bar are hidden

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@malinajirka - Am I looking at this correctly? I see the shadow, but should the filter bar background change color too when in dark mode? I'm on a pixel 3xla emulator.

DARK|LIGHT
---|---
|

**Comment by malinajirka** [comment]
Thanks @zwarm! Chris did [a design review](https://github.com/wordpress-mobile/WordPress-Android/pull/13615#issuecomment-747566528) in the following PR and he approved the bar color. So I'd say yes - moreover, I believe it's consistent with the other bars we have in the app (eg reader). If we change our mind we can update it later.

**Comment by zwarm** [comment]
> I believe it's consistent with the other bars we have in the app (eg reader). 

I never noticed it before ... I usually use light mode. Thanks for pointing it out.

**Review by zwarm — APPROVED** [review]
👍  Looks good.

**Pull request merged**
