### PR TITLE
[Reader Performance] Remove unnecessary requests to following/mine endpoint on "Following" tab

### PR DESCRIPTION
**Pull request by RenanLukas**
To test:
Reader "Following" tab should continue to work as expected, including:
- Opening Reader with empty DB (clear app data);
- Opening Reader again after DB is created;
- Swipe-to-refresh;
- Followed/unfollowed sites should be reflected in the list (including from other platforms such as web). This is not covered properly by the app right now and in some cases the "Following" tab list is also not updated in `trunk` after a new site is followed, but please let me know if you find any issues;
- Switching between SH and WP.com sites;

## Regression Notes
1. Potential unintended areas of impact
"Following" tab 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and updated unit tests.

3. What automated tests I added (or what prevented me from doing so
Updated `SubFilterViewModelTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by thomashorta — COMMENTED** [review]
Thanks for the changes. Overall looks good to me but I found an issue while testing that did not happen when testing the current prod version, so might have been introduced in this change.

### Infinite Loading on Following Tab

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/3f0de9b8-1ba1-47f2-b06e-05aee96ff1a7

Steps:
1. Go to Reader -> Following
2. Pull to refresh
3. Go to another bottom nav tab (Notification for instance)
4. Go back to Reader
5. ⚠️ The pull-to-refresh progress indicator is now stuck and posts are not loaded

**Comment by RenanLukas** [comment]
Thanks for catching that, @thomashorta 
I'll investigate what happened

**Comment by RenanLukas** [comment]
@thomashorta unfortunately I wasn't able to reproduce it. For me it took quite a few seconds for the loading to disappear after moving back to `"Following"` tab both in this branch and on `trunk`, but at some point it disappeared in both branches.
Maybe I'm missing something? Here's what I did:
1 - Install and sign in to JP
2 - Open Reader
3 - Tap on "Following"
4 - Pull-to-refresh
5 - Move to "Notifications" and stay there for a bit (~3 seconds)
6 - Move back to "Following" tab: after a few seconds the loading disappeared.

**Comment by thomashorta** [comment]
> For me it took quite a few seconds for the loading to disappear after moving back to `"Following"` tab both in this branch and on `trunk`, but at some point it disappeared in both branches.
> Maybe I'm missing something?

Not sure, I tested on an emulator, but it reproduced a lot with this branch while it didn't seem to get stuck for other branches, though it could very well be some race condition not related to this change. I think the only different thing I had seeing your steps is that it wasn't my first time signing it, so I already have content loaded locally in the Reader tabs. Not sure if that would make any difference though.

**Comment by RenanLukas** [comment]
> I think the only different thing I had seeing your steps is that it wasn't my first time signing it, so I already have content loaded locally in the Reader tabs. Not sure if that would make any difference though.

Thanks @thomashorta 
I'll try again with some content already loaded locally and will let you know

**Comment by RenanLukas** [comment]
@thomashorta I've tried reproducing it a few more times and instead of right after signing in I've navigated through the Reader for some time, but every time the loading disappeared after a few seconds 🤔 I'm also using an emulator. Maybe it's a race condition like you said.

**Review by thomashorta — APPROVED** [review]
Since the issue I reported doesn't seem to be something consistent or easily reproducible (most likely some race condition not related to this change) I will go ahead and approve it, as everything else looks fine!

Thanks for the changes! :shipit:

**Pull request merged**
