### PR TITLE
Prevents the app from crashing when the ReaderCommentService fails to start

### LINKED ISSUE #18666: IllegalStateException: Not allowed to start service Intent via Reader
Sentry Issue: [JETPACK-ANDROID-7P7](https://a8c.sentry.io/issues/4254096043/?referrer=github_integration)

```
IllegalStateException: Not allowed to start service Intent { cmp=com.jetpack.android/org.wordpress.android.ui.reader.services.comment.ReaderCommentService (has extras) }: app is in background uid UidRecord{9864311 u0a509 TRNB bg:+2m38s12ms idle change:idle procs:1 seq(0,0,0)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1725)
    at android.app.ContextImpl.startService(ContextImpl.java:1680)
    at android.content.ContextWrapper.startService(ContextWrapper.java:731)
    at org.wordpress.android.ui.reader.services.comment.ReaderCommentService.startServiceForCommentSnippet(ReaderCommentService.java:83)
    at org.wordpress.android.ui.reader.services.comment.wrapper.ReaderCommentServiceStarterWrapper.startServiceForCommentSnippet(ReaderCommentServiceStarterWrapper.kt:11)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #18666

## Description
This PR prevents the app from crashing when the ReaderCommentService for comment snippet fails to start with a [`BackgroundServiceStartNotAllowedException`](https://developer.android.com/reference/android/app/BackgroundServiceStartNotAllowedException)/`IllegalStateException` and logs the caught exception.

```
Exception android.app.BackgroundServiceStartNotAllowedException:
    at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1981)
    at android.app.ContextImpl.startService (ContextImpl.java:1927)
    at android.content.ContextWrapper.startService (ContextWrapper.java:834)
    at org.wordpress.android.ui.reader.services.comment.ReaderCommentService.startServiceForCommentSnippet (ReaderCommentService.java:83)
    at org.wordpress.android.ui.reader.services.comment.wrapper.ReaderCommentServiceStarterWrapper.startServiceForCommentSnippet (ReaderCommentServiceStarterWrapper.kt:11)
```

Note that a wider refactoring is needed to tackle the root of this issue (see https://github.com/wordpress-mobile/WordPress-Android/issues/18666#issuecomment-1690415225) but given that it is the 3rd crash in number of events/users for the last (`24.5`) version of the app, handling the crash sounds reasonable.

Screenshot 2024-04-15 at 1 24 26 PM

-----

## To Test:
I was not able to reproduce this crash thus I'd recommend a sanity of the functionality:
1. On the Reader tab
2. Tap on a post
3. **Verify** that the post details with the comments loads

-----

## Regression Notes

1. Potential unintended areas of impact

    - Reader post comment

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - The specific code is hard to test without major refactoring

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/281">24.7 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by antonis** [comment]
I've changed the target to `24.7` since this came up in the release rotation (ref pcdRpT-6oc-p2#comment-9821) and the code changes should not have side effects.

**Review by jarvislin — APPROVED** [review]
Test result is as expected, LGTM

**Pull request merged**
