### PR TITLE
Fixed Reader Settings: Following icon color

### PR DESCRIPTION
**Pull request by gorvk**
PR for #14796 

Changed and fixed the default color of **ic_reader_following_white_24dp** from **reader_listitem_blog.xml** which was different and not matching with the one in **reader_listitem_tag.xml**.

Here are the screenshot of changes - 

**Before** 

Before

**After**

After

### CODE REVIEW

**Comment by malinajirka** [comment]
Thank you so much for contribution @Gstar1525, it is very much appreciated! 

Great job tracking down the correct layouts and finding the difference in their colors! 👏 

I noticed the changed file is called secondary_**gray_20**_selector.xml, but the used color is not "gray_20" anymore. That might cause some confusion in the future, wdyt? 

What if we used the same button type and style to make sure this bug is "never" introduced again in the future. If we make sure both places are using the same resource we reduce the risk that someone updates one place but forgets to update the second one. How does that sound?

I'll share what I have in mind and please let me know what you think about it ;).

We could replace [this item](https://github.com/wordpress-mobile/WordPress-Android/blob/af93d9364018acee094744aa4f5703253d43c8b9/WordPress/src/main/res/layout/reader_listitem_tag.xml#L30)  with 
```
<org.wordpress.android.ui.reader.views.ReaderFollowButton
        android:id="@+id/btn_remove"
        style="@style/Reader.Follow.Button.Icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/margin_medium"
        android:layout_marginEnd="@dimen/margin_medium"/>
```
and update type of the button in [the ViewHolder here](https://github.com/wordpress-mobile/WordPress-Android/blob/e2ca65fca59a08ba23ab186fd26a81540ae82653/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderTagAdapter.java#L145) to `ReaderFollowButton`.
However, if you run this code you might notice the icon is in the "not following" state instead of the "following" state. We can fix this by adding `mBtnRemove.setIsFollowed(true);` into the ViewHolder.

Let me know what are your thoughts about all this! Looking forward to your comments ;)

**Comment by gorvk** [comment]
Hi @malinajirka, I have following thoughts about your suggestions,

- About difference in color and xml file name, we can simply rename it because **secondary_gray_20_selector.xml** is only used once in **reader_style.xml**. We can rename file to **black_transp_selector.xml** because the color value which I used to fix this icon color issues is **?attr/wpColorOnSurfaceMedium** having color value of **#99000000** which can be described as **black_transp** or we can create different file with name **black_transp_selector.xml** and use it in place of it.

-  And About Changing the **ImageButton** to **ReaderFollowButton**, I think it would not be appropriate because **ReaderFollowButton** is used to switch icon from **ic_reader_follow_white_24dp** to **ic_reader_following_white_24dp** for following and unfollowing the blogs and when we click on **ImageButton** it actually removes the followed item from list which are two different behaviors so I think they should not be changed.

So I guess the only additional change we should do is change the file name to match with color name.

**Comment by malinajirka** [comment]
> And About Changing the ImageButton to ReaderFollowButton, I think it would not be appropriate because ReaderFollowButton is used to switch icon from ic_reader_follow_white_24dp to ic_reader_following_white_24dp for following and unfollowing the blogs and when we click on ImageButton it actually removes the followed item from list which are two different behaviors so I think they should not be changed.

Yep, I agree the original usage of ReaderFollowButton is to change states which we don't need for this screen. The button would work even for our scenario without any behavioural changes, but it's a tough question whether it's a good idea to reuse it or not. Let's keep the current setup ;).

> About difference in color and xml file name, we can simply rename it because secondary_gray_20_selector.xml is only used once in reader_style.xml. We can rename file to black_transp_selector.xml because the color value which I used to fix this icon color issues is ?attr/wpColorOnSurfaceMedium having color value of #99000000 which can be described as black_transp.

Thanks for checking that it's not used anywhere else. The only minor thing is that we might want to consider following the naming convention for consistency - "[default_color]_[selected_color]_selector.xml" -> "secondary_on_surface_medium_selector.xml". Wdyt?

**Comment by gorvk** [comment]
> Thanks for checking that it's not used anywhere else. The only minor thing is that we might want to consider following the naming convention for consistency - "[default_color]_[selected_color]_selector.xml" -> "secondary_on_surface_medium_selector.xml". Wdyt?

Yup @malinajirka , let's rename to secondary_on_surface_medium_selector.xml.
Got one question, so shall I keep the color value as **?attr/wpColorOnSurfaceMedium** or change it to **#99000000** ?
I think we should go with **?attr/wpColorOnSurfaceMedium** because everywhere in the project for that color it is used.

**Comment by malinajirka** [comment]
Good question! Yes, I think using `?attr/wpColorOnSurfaceMedium` is the best solution here. If we ever decide to re-design the app, it'll be much easier if `attribute colors` are used everywhere ;). Thank you so much! 🙇

**Comment by gorvk** [comment]
bd51910 -> As suggested by @malinajirka renamed the `secondary_gray_20_selector.xml` file to `secondary_on_surface_medium_selector.xml`.

**Comment by malinajirka** [comment]
Thanks for fixing the issue and also for the interesting discussion! ;) 

I've updated the target branch as not all CI jobs are supported on PRs from a fork. I'll create a new PR and merge it as soon as the CI is done verifying the changes.

Again, thank you so much for your contribution!

**Pull request merged**
