### PR TITLE
Block upload and switch to HTML mode until insert image or video has finished

### PR DESCRIPTION
**Pull request by maxme**
Fixes #wordpress-mobile/WordPress-Editor-Android#294

I'm using time with `mActionStartedAt` instead of a simple boolean because I fear the app/activity/fragment or webview lifecycle could interfere and we could miss the `action-finished` callback.

cc @aforcier

### CODE REVIEW

**Comment by maxme** [comment]
Note: this is a pure editor subtree patch, but it's only testable in wpandroid.

**Comment by maxme** [comment]
> Note: this is a pure editor subtree patch, but it's only testable in wpandroid.

Actually it's not ;) (`WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java` changed)

**Comment by maxme** [comment]
Note: commits should be cherry-picked in `release/5.4`

**Comment by aforcier** [comment]
Looks good @maxme. I'm unable to reproduce the original bug anywhere naturally, though I was able to force it by wrapping `insertImage` in a `setTimeout`. Fix works well in that case, though there's one situation where it breaks down:

1. Insert media item from WP library
2. Before the media has finished being inserted, add another media item
3. When returning to the editor, the first media item will get inserted
4. Press HTML or Publish before the second item is inserted
5. HTML/Publish works, and the item doesn't get inserted

I'm only able to make this happen using the `setTimeout`, without it the media item is added in the time it takes to press the image button and make a selection from the menu. Perhaps we should also block use of the media button while waiting for `isActionInProgress()`?

**Comment by aforcier** [comment]
Working well with the added media button block. :shipit:

**Pull request merged**
