### PR TITLE
Test PR (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by ParaskP7**
Relates #13996

This PR is for 'Static Analysis' testing purposes only and it will be used to identify how the 'Violation Comments' plugin works on a PR.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @loremattei !

I am not seeing the `Violation Comments` plugin working in this PR as expected. Or, I don't understand how this is supposed to work. Can you please confirm?

**Comment by loremattei** [comment]
Yup! It's not working. It's supposed to comment on the PR, like Hound does on iOS.

**Comment by ParaskP7** [comment]
👋 @loremattei !

> Yup! It's not working. It's supposed to comment on the PR, like Hound does on iOS.

Thanks for confirming it! 🙏 

Ok, then maybe I'll exclude the `violation comments` configuration from the `Detekt` [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13996) and merge that as is without it. Then, when we get to the bottom of fixing the `violation comments` configuration we can add and test `Detekt` on it. Wdyt?

PS: I can create an issue for the `violation comments`.

**Comment by ParaskP7** [comment]
> PS: I can create an issue for the violation comments.

This is now done here: #14051

**Comment by loremattei** [comment]
Yeah! Sounds good to me 👍

**Pull request closed without merging**
