### PR TITLE
Updates to site store

### PR DESCRIPTION
**Pull request by planarvoid**
This PR is here to test changes to the FluxC site store. 

To test:
- Try the "Create a site" flow
- Try logging in with a self-hosted non-Jetpack site, going to the site list and to the profile
- Try logging in with a WP.com site, going to the site list and to the profile

## Regression Notes
1. Potential unintended areas of impact
-  Anything related to fetching and creating sites

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- There is a lot of tests in FluxC

3. What automated tests I added (or what prevented me from doing so)
- I've added unit tests in fluxC

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by develric — COMMENTED** [review]
Hi @planarvoid 👋 ! Checked the code and looks good 👍 . Also testing was ok (did some smocktesting, jetpack install, posting/reblogging etc... + the test steps in the description), only thing I found is the following while creating a new site (let me know if you can replicate):

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.wordpress.android.prealpha, PID: 7127
    java.lang.NullPointerException: payload.error must not be null
        at org.wordpress.android.fluxc.store.SiteStore.handleCreateNewSiteCompleted(SiteStore.kt:1423)
        at org.wordpress.android.fluxc.store.SiteStore.createNewSite(SiteStore.kt:1417)
        at org.wordpress.android.fluxc.store.SiteStore$createNewSite$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-06-10 15:29:54.118 10614-10803/org.wordpress.android.prealpha E/WordPress-API: handleDesignatedMobileEditorForAllSites - The backend returned info for the following siteID 194223837 but there is no site with that remote ID in SiteStore.
```

**Comment by planarvoid** [comment]
Good catch! I've fixed it in the FluxC PR + I changed all the errors to be nullable to be extra cautious @develric

**Review by develric — COMMENTED** [review]
Thanks for the follow up and fix @planarvoid . I can confirm the fluxc fix works as expected and can complete the create new site flow without issues 👍 ! I will keep it opened so that tomorrow we can consolidate into 1 PR all the fluxc reviewed PRs, relink here and final test 🙇 .

**Comment by planarvoid** [comment]
I've updated the FluxC version to a tag so we should be ready to merge @develric

**Review by develric — APPROVED** [review]
Hey @planarvoid 👋 ! I tested this again and all was smooth for me 👍 ! :shipit:

**Pull request merged**
