### PR TITLE
[Reader IA] Add dropdown menu analytics events

### LINKED ISSUE #19906: [Reader IA] Implement analytics events for drop-down menu
**When Reader drop-down menu is opened**
Key: `"reader_dropdown_menu_opened"`
No parameters.

**When Reader drop-down menu item is tapped**
Key: `"reader_dropdown_menu_item_tapped"`

```
Parameters:
// list should be sent when any custom list item is tapped
{ 
    "id": "discover|following|saved|liked|a8c|list"
}
```

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19906 

-----

## To Test:
- Install JP and sign-in;
- Open `"Reader"`;
- Tap on the drop-down menu: you should see the following analytics event in the Logcat:
```
🔵 Tracked: reader_dropdown_menu_opened
```
- Tap each item in the drop-down menu (including a custom list item). You should see the following analytics events being tracked:
```
// When "Discover" is tapped
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"discover"}
// When "Subscriptions" is tapped
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"following"}
// When "Saved" is tapped
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"saved"}
// When "Liked" is tapped
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"liked"}
// When "Automattic" is tapped
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"a8c"}
// When any item in a custom list is tapped (Menu -> Lists -> Tap any item)
🔵 Tracked: reader_dropdown_menu_item_tapped, Properties: {"id":"list"}
```
-----

## Regression Notes

1. Potential unintended areas of impact
None 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and unit tests.

3. What automated tests I added (or what prevented me from doing so)
Updated `ReaderTrackerTest.kt`.

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by daniloercoli — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
