### PR TITLE
Add an arrow icon for handling the UI of RTL

### LINKED ISSUE #18807: Navigation buttons point to the same side when viewing a post in the web for RTL languages.
### Expected behavior
When viewing a post in the web, navigate back button should point to the right and navigate forward should point to the left.

### Actual behavior
Both buttons point to the right.

image

### Steps to reproduce the behavior
1. Configure the device language as an RTL language.
2. Go to Reader 
3. Select a post and view it in the web browser.

### PR DESCRIPTION
**Pull request by jarvislin**
Fixes #18807

-----

We have two arrow icons, → and ←. We only handle RTL for the ← icon, which causes the two arrows are in the same direction when the device is using the RTL language.

This PR contains a new arrow under the `ldrtl` directory for handling RTL.

## To Test:

1. Install JP and sign in.
2. Click `Reader` at the bottom tab.
3. Find a post and click it.
4. Click the three dot icon at the top-right corner.
5. Click `Visit site`
6. Change the locale on your device to a RTL language, e.g. `Arabic`.
7. Back to the app.
8. The arrow icons should be displayed correctly.

| Before the fix | After the fix |
|--|--|
| 255023331-de8735ba-798c-44f7-96bd-99f00324caa3 | Screenshot_٢٠٢٤٠١١٧-١٤٣٢٠٠ |

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

9. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual

10. What automated tests I added (or what prevented me from doing so)

    - None

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by antonis — APPROVED** [review]
Thank you for fixing this @jarvislin 🙇 
The added resource looks good and the app behaved as expected when testing it on a Pixel 5 (Android 14) 🎉 

|LTR|RTL|
|---|---|
|Screenshot_20240118_105951|Screenshot_20240118_110038|

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/275">24.1</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jarvislin** [comment]
@antonis Thanks for the review 👍

**Pull request merged**
