### PR TITLE
Issue/updating material reader bottom sheet

### PR DESCRIPTION
**Pull request by khaykov**
Catching up with changes in develop branch.

cc @develric @osullivanchris 

This PR updates the look of the Subfilter bottom sheet and adds a default style for all bottom sheets in our app.

Not much changed visually, apart from this swell corner animation when the bottom sheet is at the top:
[Image from Gyazo](https://gyazo.com/c0bce797bf392187fc176eea2f5aec18)

How cool is that!

Rest of the stuff looks about the same:
reader

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by osullivanchris** [comment]
Hey looks good and I just approved but after downloading the build I found a small bug.

When I tap the Floating Action Button on My site, that sheet appears with a corner radius (as expected) but immediately animates to flat when opened. I'm thinking its to do with how you define the animation. Perhaps you are doing it when the sheet reaches its maximum height, but this one only has one height as there isn't additional content.

Let me know if you need suggestions to resolve! But think its just technical.

**Comment by khaykov** [comment]
@osullivanchris That's intended behavior. Non-rounded corners indicate that the bottom sheet reached the maximum expanded state :)

**Comment by khaykov** [comment]
PS: By intended behavior, I mean I'm not doing anything special there - it's out of the box, material bottom sheet behavior.

**Comment by oguzkocer** [comment]
We're freezing `14.3` today, so this PR is being bumped to `14.4`. If you'd like it to ship with `14.3`, please merge it into `release/14.3` and ping me – I'll be happy to cut a new beta release.

**Comment by osullivanchris** [comment]
> @osullivanchris That's intended behavior. Non-rounded corners indicate that the bottom sheet reached the maximum expanded state :)

So I think we should do this with expandable sheets. Our idea with the reader one was it started at 50% height. And then when its expanded and reaches full height, this effect is really nice and its great that we get it for free.

However, in this 'Add new post/page' sheet. I don't think it really 'expands' in my mental model - because all of the content is displayed within the initial presentation of the sheet. There's no overflow of content or need to scroll. So I just thought this one would be rounded in this state. Is it possible to only use this expanding behaviour (moving from rounded to flat) for sheets that have an overflow/can be expanded to fill the screen?

Its a bit tricky to come up with a logical definition for that so maybe its hard to define in code? But hopefully you get what I mean!

**Comment by khaykov** [comment]
@osullivanchris I totally get what you mean, but in my understanding, the issue is that this approach goes against OS design paradigm:
 - Rounded corners - can pull the bottom sheet up.
 - Square corners - can't pull the bottom sheet up.

Applying this on cases by case basis makes implied behavior of the bottom sheet confusing.

Regardless, it's a pretty easy fix, so If you are positive that we should go this way I'll go ahead and change the style of not fully expandable bottom sheets to always rounded corners :)

**Comment by osullivanchris** [comment]
I've thought about it and it sounds like we're best to steer close to the default behaviour.

I can't think of a good way to define what I was going for, and it might cause bugginess. So let's go with what we're getting from the system. Thanks for making this work!

**Comment by khaykov** [comment]
Thank you, @osullivanchris ! 

@develric I think this PR is ready for code review :)

**Comment by khaykov** [comment]
Thank you @develric ! I think Google started adding the bottom sheet before it was a part of the material library :) That's why we see all those different things around the place.

**Pull request merged**
