### PR TITLE
[Site Name] Adapt the Site name screen layout for landscape orientation

### LINKED ISSUE #16294: [Site Name] Adapt the Site name screen for landscape orientation
## Description
The screen should be adapted on landscape to show only a title `Site Name` (instead of `Site topic`) similar to what we do in the other site creation screens.
https://user-images.githubusercontent.com/304044/162751627-712c70b6-2c59-4cc9-b72a-2e3bcffb9073.mp4

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #16294

The Site Name screen layout for landscape orientation is adapted:
- Title text updated to 'Site name' (instead of `Site topic`)
- The title and subtitle in header is hidden, similar to what we do in the other site creation screens.
- Continue button is only shown in portrait orientation when the input is not empty.

I went with 'Site name' instead of the suggested 'Site **Name**' title because during testing it seemed unpolished to see 'Site intent', 'Site Name' and then 'Choose a design' in the site creation flow.

Ideally we'd capitalize the title also for the 'Site intent' screen if we prefer Capitalized Words notation.

## To test:
Prerequisites
<details>
<summary>Toggle the Site Intent Question feature</summary>

1. From My Site Go to Me → App Settings → Debug settings
2. Scroll to Features in development section and tap on SiteIntentQuestionFeatureConfig
3. Tap RESTART THE APP button
4. Since this feature is A/B tested the Site Intent Question will appear only to half of the users. Retry with a different account if it doesn't work

**Alternatively hardcode the feature on by returning `true` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/521e6b3a296339bec026f8ee2648eab326d31129/WordPress/src/main/java/org/wordpress/android/util/config/SiteIntentQuestionFeatureConfig.kt#L19)** 
</details>
<details>
<summary>Toggle the Site Name feature</summary>

1. From My Site Go to Me → App Settings → Debug settings
2. Scroll to Features in development section and tap on SiteNameFeatureConfig
3. Tap RESTART THE APP button
4. Since this feature is A/B tested go to **Abacus**, find the `wpandroid_site_name_v1` experiment and assign to your test a8c-user the treatment variation

**Alternatively hardcode the feature on by returning `true` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/521e6b3a296339bec026f8ee2648eab326d31129/WordPress/src/main/java/org/wordpress/android/util/config/SiteNameFeatureConfig.kt#L19)** 
</details>

1. Toggle the Site Name feature ON
2. Toggle the Site Intent Question feature ON
3. Start the Site Creation flow
4. Choose an intent for your site
5. `Verify` that the Site Name screen is shown
6. Rotate the device or simulator
7. `Verify` that the tile is 'Site name' and the input is the only thing visible besides the top bar.
8. Type something in the input
9. `Verify` that the continue button is not shown

Further testing — Opening the screen in **landscape** device orientation

10. Navigate back
11. Choose an intent for your site
12. `Verify` by repeating steps 7, 8, 9.

## Preview
| Before | After |
| --- | --- |
|  |  |

## Other Changes
- I reused the layout for the header (title & subtitle) that we have on the Site Intent screen, and renamed it to `site_creation_header_v2`.

## Regression Notes
1. Potential unintended areas of impact
   Site Intent screen because I refactored the layout of the title & subtitle to be reusable — though unlikely given that the changes are trivial.

13. What I did to test those areas of impact (or what existing automated tests I relied on)
   Tested manually with different exploratory scenarios.

14. What automated tests I added (or what prevented me from doing so)
   The PR only does UI fixes and UI refactoring → no tests were added or changed.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mkevins — APPROVED** [review]
Nice work Ovi! I tested this, and it is working as expected. Also, the code looks good - thanks for refactoring to share common parts of the UI, I had something similar in mind :+1: .

One thing to mention is that I intended to revisit [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/16259#discussion_r843418680) when addressing the landscape orientation (and deferred until determining whether we'd include the intent as part of the title). This PR "uncomplicates" that (since we are omit it in landscape in favor of the shorter title). Maybe we could extract the `isPhoneLandscape()` into the utils? I'd consider this non-blocking to, so feel free to merge as is, and we can address the extraction in another PR.

**Comment by mkevins** [comment]
Also, I agree with your rationale about the title case, and the change to make it consistent. I'd be in favor of either keeping it as is, or changing the case on the other screens for consistency. :+1:

**Comment by ovitrif** [comment]
> Maybe we could extract the `isPhoneLandscape()` into the utils? I'd consider this non-blocking to, so feel free to merge as is, and we can address the extraction in another PR.

Thank you for the reminder @mkevins! Definitely a good idea now that we're using it in 3 different `Fragment`s! 🙇 

I'd love to do the extraction to utils in this PR 👍

**Comment by ovitrif** [comment]
@mkevins Applied the improvement we thought of to extract the `isPhoneLandscape()` logic to `DisplayUtils` 🎉 

I tested the changes by rotating the device a few times on each screen and it worked as we'd expect, no regression on this side (would have given up Kotlin if that was the case 😅 ).

Please have a look at the latest push 🙇 , if not @antonis might as well, no need to prioritize this in any way 😉.

**Review by antonis — APPROVED** [review]
Great work Ovi 👍 
I've tested the implementation with latest changes on a Pixel 5 (Android 12) and it is working as expected. The code also looks good 🎉

**Pull request merged**
