### PR TITLE
Share title & url from Reader

### LINKED ISSUE #5512: Replace "Shared from WordPress" title when sharing from the Reader
Replace  "Shared from WordPress" with the post title, like we do [when we share a freshly published post](https://github.com/wordpress-mobile/WordPress-Android/blob/edc5bf6fca78ba90347fa3c32cfe41721896bd4f/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java#L130-L131).

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5512

To test:
* Share a post from reader and make sure the title and url shared are correct

### CODE REVIEW

**Comment by nbradbury** [comment]
This looks good and I'll :shipit: I do want to point out, though, that when sharing to apps that ignore the subject line (like Messenger), only the URL will be shared.

screenshot_1490705364

**Comment by catehstn** [comment]
This is great - can we make this same change for sharing from the post list too, please?

**Comment by oguzkocer** [comment]
@catehstn I think you mean the post preview as I don't think there is a way to share a post from the list, so I opened an issue for that: #5536

**Comment by catehstn** [comment]
@oguzkocer yes - and from the post published notification. Thanks!

**Comment by oguzkocer** [comment]
@catehstn The post published notification one was working already (verified it, just in case), the post preview/view one is fixed in #5546. So, all 3 of them should be pretty consistent now 👍

**Comment by catehstn** [comment]
Great!

**Pull request merged**
