### PR TITLE
Stats Revamp v2:  Feature Announcement

### LINKED ISSUE #16686: [android] Stats:  Feature Announcement

### PR DESCRIPTION
**Pull request by ravishanker**
This PR adds feature announcement for Stats Revamp v2.

Fixes #16686 

NOTE:
- At the moment it is set up to show up at app launch if  local debug feature flag is enabled

TODO:
- [x] Replace the image with properly exported one
- [ ] Confirm what and when should invoke this on release

|Detail screen with date selector|
|---|
||

To test:

Setup:
1. Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
2. Select Debug Settings
3. Find StatsRevampV2FeatureConfig under Features in development enable it and restart app
4. Launch / Re-Launch app

Test:
- Notice  the new Feature announcement dialog pops up.
- Tap on [Try it now] and ensure it opens Stats 
- Relaunch or Return Feature announcement
- Tap on [Remind me later] and it should dismiss the dialog
- Relaunch or Return Feature announcement
- Tap on X on top right hand corner and it should dismiss the dialog

To test:

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the paths

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by irfano — COMMENTED** [review]
- I think the design should be prompt popups, like blogging reminders popups.
- We can use Hilt for `StatsNewFeaturesIntroDialogFragment` and `StatsNewFeatureIntroViewModel`. I can update it in this PR if you like, let me know.
- I couldn't see a bulb at the top and there is divider line above buttons. Did you use a different version design file?
image

**Comment by ravishanker** [comment]
> * I think the design should be prompt popups, like blogging reminders popups.

That was in i1 of the design.  Latest i5 iteration is based on feature intro feature from [blogging prompts](https://github.com/wordpress-mobile/WordPress-iOS/issues/18176)

>     * We can use Hilt for `StatsNewFeaturesIntroDialogFragment` and `StatsNewFeatureIntroViewModel`. I can update it in this PR if you like, let me know.

I did try that, given WPMainActivity is still in Java.  If you can make it work, would be great!  thanks

>     * I couldn't see a bulb at the top and there is divider line above buttons. Did you use a different version design file?
It is not in the design, but in [the feature intro design](https://github.com/wordpress-mobile/WordPress-iOS/pull/18738#issuecomment-1145226138)
>

**Comment by spencertransier** [comment]
Hello! Just letting you know I am moving this to the 20.2 milestone while running the code freeze for 20.1 today.

**Review by irfano — APPROVED** [review]
> I did try that, given WPMainActivity is still in Java.

@ravishanker I added `AndroidEntryPoint` to `WPMainActivity`, then migrate `StatsNewFeaturesIntroDialogFragment` to the Hilt. 427319b61ddfbee6b9b96e46ab01f400734720e4

It's up to you to implement the final decision on the logic in this PR or a separate one. I'm approving the current changes. 👍🏻 

I think we're good to merge after resolving the conflict. But also let's follow this thread for analytics change. Internal Slack ref: p1655236755558709/1654082772.152509-slack-C02QANACA

**Pull request merged**
