### PR TITLE
Fix #3141 re enable the connection bar

### LINKED ISSUE #3141: Add the connection bar back
It was removed in #3136

### PR DESCRIPTION
**Pull request by maxme**
Fix #3141 add connection bar and move some onCreate method to a deferred init.

`CONNECTION_CHANGE` receiver is enabled when the app comes from background and disabled when it goes to background, thus the `ConnectionChangeEvent` could be used in all Activities (not only WPMainActivity)

cc @nbradbury

### CODE REVIEW

**Comment by nbradbury** [comment]
If the connection receiver is disabled when there's a connection and then re-enabled when there isn't a connection (or vice-versa), it doesn't send the connection change event. Right now this isn't really an issue since the main activity's `onResume` will check the connection, but it could cause problems down the road if we use this receiver elsewhere.

A simple fix would be to modify the receiver as below, then call `ConnectionChangeReceiver.setIsEnabled()` when enabling or disabling the receiver.


```
private static boolean mIsEnabled = true;

@Override
public void onReceive(Context context, Intent intent) {
    boolean isConnected = NetworkUtils.isNetworkAvailable(context);
    if (mIsFirstReceive || isConnected != mWasConnected) {
        sendConnectionChangeEvent(isConnected);
    }
}

private static void sendConnectionChangeEvent(boolean isConnected) {
    AppLog.i(T.UTILS, "Connection status changed, isConnected=" + isConnected);
    mWasConnected = isConnected;
    mIsFirstReceive = false;
    EventBus.getDefault().post(new ConnectionChangeEvent(isConnected));
}

public static void setIsEnabled(Context context, boolean enabled) {
    if (mIsEnabled != enabled) {
        mIsEnabled = enabled;
        if (mIsEnabled) {
            sendConnectionChangeEvent(NetworkUtils.isNetworkAvailable(context));
        }
    }
}
    
```

**Comment by maxme** [comment]
> If the connection receiver is disabled when there's a connection and then re-enabled when there isn't a connection (or vice-versa), it doesn't send the connection change event.

Good catch - I'm going to implement your suggestions, about the `SuggestionTable`, I guess it's actually useless to reset it here, we should simply clean it upon update, I'll fill a new ticked.

**Comment by maxme** [comment]
Ready for another review.

Note about [this](https://github.com/wordpress-mobile/WordPress-Android/blob/1996d852d7524551798a71ac1ad8ca6c5b1a6840/WordPress/src/main/java/org/wordpress/android/networking/ConnectionChangeReceiver.java#L22-22): there is a way to get the state from the [PakageManage](https://developer.android.com/reference/android/content/pm/PackageManager.html#getApplicationEnabledSetting(java.lang.String)) but it needs a `Context`. We could get that state during the first `setEnabled()` call, but that seems an overkill to me.

**Comment by nbradbury** [comment]
> We could get that state during the first setEnabled() call, but that seems an overkill to me.

Agreed.

**Comment by nbradbury** [comment]
Looks good :shipit:

**Pull request merged**
