### PR TITLE
Choose any file in media library

### LINKED ISSUE #4842: Media Library: Allow uploading any file
Currently we only support uploading image & video files in the app. A user is asking to upload mp3 files for example (#144231-h). We should probably support every file type we currently support in wp-admin.

Summary with a list of remaining work can be found pOhUr-47V-p2 + comments.

### LINKED ISSUE #8052: Media: allow uploading audio files
This is a subset of #4842, which asks for uploading of any file type. This issue is specifically about adding the ability to upload audio files.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #4842
Related FluxC changes #https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1634

This PR adds a "Choose from device" option to the media library. This option hides the previous "Choose photo from devices" and "Choose video from device" options and allows the user to upload any image/video/document/audio file (that is supported). 

I've replaced the String mime type with an enum value I've created in FluxC. 

Upload doesn't work on a site with a free plan. The upload currently just fails, internally with following error: "Error uploading media: Sorry, this file type is not permitted for security reasons.". We'll improve the error handling and the message in another PR.

To test:
- Go to Media library
- Click on the hamburger menu in toolbar
- Select "Choose from device"
- Try uploading various files (all supported file types are mentioned in this list - https://wordpress.com/support/accepted-filetypes/ )
- Test both with business and on a self-hosted site

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by planarvoid** [comment]
thanks for the check @osullivanchris , 
> On a free plan, I chose an MP3. It tells me I can't upload it. But it doesn't say why. If its due to plan.- we should probably say this
I've looked into it and Audio upload indeed doesn't work on free sites. I've uploaded the PR description 
> On dark mode the text describing the document changes to white. The background color of the box should also change to a darker grey, as otherwise it is hard to read.
It makes sense, I'll look into it and let you know 👍

**Comment by planarvoid** [comment]
hey @osullivanchris , I've fixed the background colors for the file/audio tiles + I've made some improvements to the tile sizes. They should now be consistent (previously the file size was slightly bigger than the images).

**Comment by planarvoid** [comment]
thanks for the review @develric !

> It seems we have no filters and allow every file to be selected (also those not accepted like apk as below; we manage correctly an error in that case, but maybe we could check if we can filter out those files from being listed, wdyt?)

I've changed the behaviour to only allow selection of mimetypes that are allowed by the API :-). I hope this fixes this problem.

> When no audio files are present in the library we remove the Audio tab, while this is not the case for the others like Videos tab that is always there with a CTA; is it wanted?

This is the current intentional behaviour. It might make sense to change this but I wouldn't do it in this PR.

> Maybe related to my setup, but I’m getting few strange things with a business plan site (this is an a8c user in case makes a difference for this; let me know if you can replicate or not)

I can reproduce it (both in the app and on Calypso). It seems to not work on Jetpack (or Atomic) sites. Since it behaves the same way in the app and in Calypso, I'd keep it as it is for now.

> I can upload an mp4 video and it succeeds but if I leave the media library and come back, I get a white preview tile of that video (while preview was correct right after upload)

I couldn't reproduce this with a sample mp4 file.

> This is not related to this PR I think, but when hitting the file dimension limit uploading a 5MB mp3 on a self-hosted with JP site I got a message referring to image being too big (wondering if this can be true for other cases as well)

Let's improve this in another PR.

**Comment by develric** [comment]
Hey @planarvoid , thanks for the changes 🙇‍♂️!

> I've changed the behaviour to only allow selection of mimetypes that are allowed by the API :-). I hope this fixes this problem.

That's working great thanks 😊

> I couldn't reproduce this with a sample mp4 file.
it seems I can reproduce with 15.0 also; wonder if it's related to my specific account 🤔. In case you want to give it another try before we open a ticket for this, I was on a pixel 3 emu API 29 using my business a8c account.

I think this PR is working great 👍! IIRC we are still missing confirmation from woo folks about eventual binary compatibility issues with the fluxc modifications (is it right?). If we can get their ok I think we can merge the fluxc and this PR; good job 😊!

PS: for the others point I agree we can tackle in dedicated tasks/prs 👍

**Pull request merged**
