### PR TITLE
Lowercase block editor and classic editor 

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Updated the editor naming convention to follow core spelling which lowercases both block editor and classic editor unless referring to a title or the Classic Editor plugin.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by garrett-eclipse** [comment]
Reference - https://make.wordpress.org/core/handbook/best-practices/spelling/

**Comment by Tug** [comment]
Thank you for the fix, this looks good to me 👍
I don't have much experience in this codebase though, maybe @marecar3 can have a look as well and confirm we're not forgetting files?

**Comment by marecar3** [comment]
Hey, @Tug @garrett-eclipse thanks for the ping. It seems that there is a conflict which needs to be resolved.

But besides that, I think that those changes are ok. The only concern would be about localization. Will localization start automatically or we need to manually do it?

**Comment by garrett-eclipse** [comment]
Thanks @marecar3 I've resolved the conflict there. Can you take a look. All the best.
As to localization I'm unsure but assume it would be picked up when publishing a new version.

**Comment by marecar3** [comment]
Hey, @garrett-eclipse it seems that it's now. 
However, I can see that some tests are failing now.

**Comment by garrett-eclipse** [comment]
Hi @marecar3 not sure how to address this failing test;
Screen Shot 2019-06-30 at 12 03 46 PM

Any thoughts appreciated

**Comment by marecar3** [comment]
Hey, @loremattei please can you help with this PR as I am not 100% sure what's wrong with the failing build. Also if you can double check the changes so that we are sure we want them? Thanks!

**Comment by marecar3** [comment]
Hey, @garrett-eclipse you can merge this one if you want! :)

**Comment by garrett-eclipse** [comment]
Thanks @marecar3 but sadly I don't have the capability to merge this, will need to be handled by a project maintainer. Cheers

**Comment by marecar3** [comment]
Ok, @garrett-eclipse merged! :)

**Comment by garrett-eclipse** [comment]
Thanks @marecar3

**Pull request merged**
