### PR TITLE
Async media: Notifications for async publish

### PR DESCRIPTION
**Pull request by aforcier**
Adds some notification support for async post publishing (#5880). #5880 should be merged first, and then the base branch of this PR updated.

This is intended to be temporary, to give us some visual feedback on what's happening (post waiting for media to finish --> post itself publishing), and also to show an error notification when a post upload is cancelled because it had failed media. It's temporary because the upload UI is getting a major overhaul as part of the async media project, and that will supersede these changes.

To test:
Run the same cases as in #5880. You should get an immediate notification when pressing 'Publish', and you should get an error notification if a media item fails while the post is queued to upload.

cc @mzorz @daniloercoli

### CODE REVIEW

**Comment by mzorz** [comment]
Good job @aforcier! Generally speaking the code looks good, I only found these things that might be improved:

- if you write a post and get out of the editor while leaving some media upload in progress, you get a notification. Let it finish and you can see the notification updates until the final state notification `"Post updated"`.
If you then open _that same post_ again for editing, then add a new media item and start uploading, then leave the editor, you end up having that `"Post updated"` notification which should be cancelled in favor of the most recent event notification happening (that is, the new notification that tells you some media is being uploaded and then the post is being updated). Otherwise you end up seeing a `"Post updated"` along with a `"Media uploading/Post uploading"` notification for the same post.
(Note that notifications for different Posts should remain on the system dashboard if the user chooses not to dismiss them).

- If you write a new draft, add an image, leave the editor. Wait for everything to finish. Then open the draft again, now tap on the settings wheel and change the status from `Draft` to `Publish`. Come back from the settings screen to the editor (tapping the back arrow) and add another media item. Now leave the editor tapping back.
--> The Toast "Post saved on device / SYNC" is shown, and then no progress notifications are shown, even if the media is being uploaded (checked this by debugging). Also, in this case only, the post doesn't seem to be uploaded in the end (I guess this is correct as I didn't hit UPDATE or PUBLISH but only changed the Post settings and then hit the back arrow). Also, it lets me get in the editor while some media is uploading, potentially causing some problem there too.

**Comment by aforcier** [comment]
> if you write a post and get out of the editor while leaving some media upload in progress, you get a notification. Let it finish and you can see the notification updates until the final state notification "Post updated".
If you then open that same post again for editing, then add a new media item and start uploading, then leave the editor, you end up having that "Post updated" notification which should be cancelled in favor of the most recent event notification happening (that is, the new notification that tells you some media is being uploaded and then the post is being updated). Otherwise you end up seeing a "Post updated" along with a "Media uploading/Post uploading" notification for the same post.
(Note that notifications for different Posts should remain on the system dashboard if the user chooses not to dismiss them).

As discussed we should deal with this in a separate PR (and after we know the rest of the design requirements for notifications).

For context, this isn't completely straightforward since the in-progress notification and the 'post uploaded' notification are very different. The in-progress notification is an [ongoing notification pinning the service to the foreground](https://github.com/wordpress-mobile/WordPress-Android/blob/9580e5af323708a7503a17bbe970365ac82cd34c/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java#L68) to prevent the system from killing the service. Once the upload completes we don't need to pin the service to the foreground anymore (and it should be stopped if there's nothing left to upload), so that one is just a [normal notification](https://github.com/wordpress-mobile/WordPress-Android/blob/9580e5af323708a7503a17bbe970365ac82cd34c/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java#L220).

We should rework this so the 'uploaded' notification is dismissed if we're uploading the same post again (but, as mentioned, at a later point).

**Comment by aforcier** [comment]
> If you write a new draft, add an image, leave the editor. Wait for everything to finish. Then open the draft again, now tap on the settings wheel and change the status from Draft to Publish. Come back from the settings screen to the editor (tapping the back arrow) and add another media item. Now leave the editor tapping back.
--> The Toast "Post saved on device / SYNC" is shown, and then no progress notifications are shown, even if the media is being uploaded (checked this by debugging). Also, in this case only, the post doesn't seem to be uploaded in the end (I guess this is correct as I didn't hit UPDATE or PUBLISH but only changed the Post settings and then hit the back arrow). Also, it lets me get in the editor while some media is uploading, potentially causing some problem there too.

So there are a few things going on here, I'll separate them out.

> the post doesn't seem to be uploaded in the end (I guess this is correct as I didn't hit UPDATE or PUBLISH but only changed the Post settings and then hit the back arrow)

Changing the status from Draft to Publish makes this a 'published' post, and as you say since we didn't actually hit UPDATE, uploading the post automatically when exiting the editor would publish a draft, which is probably not what the user intended (or if it is we probably should not assume it). So it's correct not to queue up a post upload, and instead just save locally and update the post model in the db (from the `MediaUploadService`) when its media uploads complete.

> Also, it lets me get in the editor while some media is uploading, potentially causing some problem there too.

I may have missed your meaning here - isn't this expected behavior? At least for Aztec, where we have reattachment. For the visual editor, we'll take care of this when we disable opening any post that has uploading media in general.

> no progress notifications are shown

We're currently only showing progress notifications if the post is supposed to be uploading - if we're just updating the post locally, and the media uploads are proceeding (and you can re-open the post right away and see them still uploading), I'm not sure any messaging is needed in this case. We'll bring this up in the i2 design discussion with @bysl though.

**Comment by aforcier** [comment]
PR updated with changes to the base branch (had to make some changes to accommodate notification error messaging for [media cancellation](https://github.com/wordpress-mobile/WordPress-Android/pull/5880/commits/3d25a37f1d37d155d4b56508f8367a5bffdeb306)).

**Comment by mzorz** [comment]
> I may have missed your meaning here - isn't this expected behavior? At least for Aztec, where we have reattachment. For the visual editor, we'll take care of this when we disable opening any post that has uploading media in general.

Agh you're right! my bad - sorry

**Comment by mzorz** [comment]
Thanks for the important notes and clarifications here @aforcier ! Will re-test and get back with comments if I should make any 👍

**Comment by mzorz** [comment]
🔥 :shipit:

**Pull request merged**
