### PR TITLE
build: replace `kapt` with `ksp`

### PR DESCRIPTION
**Pull request by wzieba**
This PR migrates from using kapt to ksp, for running annotation processors of 3rd party libraries.

It targets a feature branch.

-----

## To Test:

Please run and smoke test the app.

-----

## Regression Notes

1. Potential unintended areas of impact

    - The whole app

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - I smoke tested the app, we rely on automated tests on CI
 
3. What automated tests I added (or what prevented me from doing so)

    - None

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
@jarvislin and @aditi-bhatia are unavailable presently AFAIK, hence the next requests for selecting a reviewer.

**Review by justtwago — APPROVED** [review]
🙇 Sorry for the delay.
Smoke tested the app and it works as usual with no major defects.
Thank you!

**Comment by wzieba** [comment]
No worries, thank you!

**Pull request merged**
