### PR TITLE
Add period change to DWMY view in Stats

### LINKED ISSUE #9137: [Stats Refresh] Add period change values to DWMY overview
This is a task to add the period change values to the DWMY overview card

difference_values

- Show actual number, shortened above 9,999
- Show percentage difference
- Values are representing the change from the previous period
- If previous period had a value of 0 then show `∞` as the percentage

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9137 

This PR adds a value change to the big value item in the overview block. The value compares the selected time period to the previous value (previous day/week/month/year). If the change is positive or neutral, the value is green in this format `+15 (50%)`, if it's negative, it looks like `-15 (50%)`. If the previous value was 0, instead of percentage we show the infinity - `+15 (∞%)`. If the current value is 0 and the previous one was > 0, we show `-15 (-∞%)`.

This block is only visible on the DWMY screen.

To test:
* Go to the Stats/Day-Week-Month-Year view
* The Overview block shows the change value next to the big value 
* If previous value < selected value -> the change is green and has `+` in front of the text
* If previous value > selected value -> the change is red and has `-` in front of the text
* If previous value = selected value -> the change is green and has 0 as the value
* If previous value = 0 -> the change is green and has `∞` as the percentage
* If selected value = 0 -> the change is red and has `-∞` as the percentage

screenshot_1549459502

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks fantastic @planarvoid !

Could we just align the baseline of the text with the big number + label?

screenshot 2019-02-06 at 09 45 13

**Comment by SylvesterWilmott** [comment]
Can we also stress test that big number, say with 100,000, 1 million, 10, million, 100 million etc

**Comment by planarvoid** [comment]
@SylvesterWilmott I've fixed the alignment and updated the screenshot, thanks for checking it!

**Comment by SylvesterWilmott** [comment]
Looks good!

After some conversation with @planarvoid we have initially decided on the following number caps:

Big number - 99,999 with auto text sizing (26sp minimum)
Value change - 9,999
Percentage change - 9,999

Let's test this on a smaller device and see how we get on.

**Review by 0nko — APPROVED** [review]
Great PR! 🥇

**Pull request merged**
