### PR TITLE
[Home Page Picker] Updates the design of the “Choose a Domain” screen

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2722

## Description
Updates the design of the “Choose a Domain” screen
*Internal reference: `pb3aDo-xN`*

## To test:

<details>
<summary><strong>To disable or enable the development version of Home Page Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker is enabled only in development builds.
    - From the site page:
        1. Click on your Gravatar.
        1. Click on App Settings.
        1. Click on Test feature configuration.
        1. Toggle "HomePagePickerFeatureConfig" to enable or disable the picker
        1. Restart the App
</details>

<details>
<summary><strong>To start the Home Page Picker screen</strong></summary>

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
</details>

*Note: This PR introduces no change in the functional part of the choose domain screen. The tests below just validate that no functionality is broken*

### Search a domain
1. Start the site creation flow
1. Select a design and press *Choose* or press *SKIP*
1. Enter your search query in the input field
1. Validate that you get results

### Choose a domain
1. Follow the steps above
1. Choose a domain
1. Verify that the toolbar appears
1. Press *Choose*
1. Verify that the site is created

## Screenshots

|Initial Screen Before|Initial Screen After|
|---|---|
|before1|after1|

|Search State Before|Search State After|
|---|---|
|before2|after2|

|Select State Before|Select State After|
|---|---|
|before4|device-2020-11-18-221630|

|Landscape Before|Landscape After|
|---|---|
|before3|after3|

|Dark mode Initial Screen|Dark mode Select State|
|---|---|
|device-2020-11-18-220300|device-2020-11-18-221646|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hello @kyleaparker @iamthomasbishop @SylvesterWilmott 👋 ,

This PR customises the Choose Domain screen.
You can find some screenshots in the description and the latest APK [above](https://github.com/wordpress-mobile/WordPress-Android/pull/13424#issuecomment-729919486) and instructions on how to enable the picker in the description.

Any feedback on this is welcome :)

**Comment by antonis** [comment]
Hello @mkevins , @chipsnyder 👋 
I keep this in draft since I still need to fix some broken tests but If you have the time have a look.

**Comment by chipsnyder** [comment]
Hey @antonis, nicely done on this! 

While testing I ran into an oddly specific use case that I'm curious if you'll be able to reproduce or not. I'm testing on a Pixel 3a  API 29

1. Start the site creation flow (e.g. Choose site > Add button)
1. Select the Create WordPress.com site option 
1. Select a Design
1. Preview
1. Choose

The search box appears selected with a cursor but the keyboard didn't pop. To recreate the issue again you need to go all the way back to the My Site screen. Seems like a small case but if a user goes through the happy preview path they might run into it.

**Comment by antonis** [comment]
Hey @chipsnyder  👋 
Thank you for taking the time to review this 🙇 

> The search box appears selected with a cursor but the keyboard didn't pop. To recreate the issue again you need to go all the way back to the My Site screen. Seems like a small case but if a user goes through the happy preview path they might run into it.

Nice catch 👍  I managed to reproduce this and applied a workaround with 2a45fdf891bfa0272d5cd3921e5443ecb181fe48
My hunch is that the dismissal of the modal preview fragment interferes with the keyboard appearance (another similar case is [this](https://github.com/wordpress-mobile/WordPress-Android/blob/acf750fe80c032530cccd7897194117537ee9e72/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java#L832))

**Review by chipsnyder — APPROVED** [review]
That fix seemed to take care of it 👍

**Comment by kyleaparker** [comment]
Hi @antonis, sorry I am a bit late here! Thank you for the ping 🙏 This is looking really great! This is my feedback after testing: 

- On the domains screen, remove the ellipsis from the title "Choose a domain ..." (see screenshot below)
- The spacing of the back icon, title, and sub-text is inconsistent between screens. The _Choose a design_ screen spacing looks better to me, but whichever we choose it should be the same on both of these screens as well as any other screens using this layout (the page template picker is another example that uses this). 
Android_spacing

The following I mentioned in the[ iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/15303), but they apply here too so I am copying them over: 
- On a slow connection the homepage images load in one by one. Do we have a skeleton loading state we can use to fade the images in once they're available? I think this would help the loading state feel a bit smoother.
- I'd mentioned this in a previous PR but I think it would be useful to add the Skip option to the domains screen
- I think we should change the wording of the sub-text on the _Choose a Design_ screen from "Pick your favorite homepage layout. You can customize or change it later." to "Pick your favorite homepage layout. You can edit and customize it later." At least until we know which approach we are going to take on switching homepage layouts. cc @iamthomasbishop I'd like to hear your thoughts on changing the wording here.

**Comment by antonis** [comment]
Thank you for the detailed response @kyleaparker 👍 
Please check [my reply on the feature release PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13409#issuecomment-732290724).

**Pull request merged**
