### PR TITLE
Stats Posting activity block

### LINKED ISSUE #9289: Posting activity card in Stats
As part of this ticket implement a posting activity card in Insights according to the designs. 
[FluxC endpoint](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1130) needs to be finished first before working on this ticket

screenshot 2019-02-20 at 11 06 42

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9289 - Related FluxC changes - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1135
This PR adds a posting activity block in the Insights. The `View more` screen will be implemented in another PR since it requires the other `View more` screens to be merged first. 
The block contains at most 3 months, stretched horizontally. If the months cannot fit the screen, we'll hide them (we always show at least one month worth of data). The data is not clickable. 
There are 5 color levels visible in the blocks. The light grey is when there shows when the number of posts for the day is 0. The other colors are divided by 25%.
The data might be slightly different than what you see in Calypso because I'm using local Calendar to decide whether an event happened on a certain day. If (for example) there was an event happening in the evening in the US, it would be already happening after midnight of my local time and that makes the posting activity graphs slightly different. We might decide 

To test:
* Go to Stats/Insights
* Scroll to the `Posting activity` block
* Check that you see three months when they fit the screen.
* Check on a smaller device that fewer blocks are shown

screenshot 2019-02-26 at 10 39 47
screenshot 2019-02-26 at 11 00 44

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Review by 0nko — APPROVED** [review]
Looks beautiful @planarvoid! 👏

One thing I noticed is that the first day of a week is always Sunday even after changing the language to Czech (at least that's how I think a locale can be changed, I'm not sure).

**Comment by planarvoid** [comment]
@0nko thanks for the review 👍 I've double checked that and you have to restart the app to see the locale changes. These are the same months for me in CZ and EN:

screenshot 2019-02-28 at 10 26 04
screenshot 2019-02-28 at 10 26 38

**Comment by 0nko** [comment]
Cool, thanks! :shipit:

**Comment by designsimply** [comment]
LGTM! Tested with WPAndroid alpha-156 (12.0 alpha) on Pixel 3 Android 9 and wanted add some screenshots for reference:

Screenshot_20190319-172525   Screenshot_20190319-172504

**Pull request merged**
