### PR TITLE
Feature/android shortcuts

### LINKED ISSUE #4681: Add App Shortucts to launcher (Android 7.1+)
With Android 7.1 came application shortcuts - by long-pressing on launcher icon you can display the popup list with shortcuts to different app activities. They can be both dynamic and static.

We could implement this feature and add shortcuts to often used parts of the app or the ones we would like to showcase. Couple of suggested options: Quick Photo, Quick Post, Stats, Reply to someone.

Reference:
https://developer.android.com/preview/shortcuts.html

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #4681

Adds Android Shortcuts for Stats, Notifcations and New Post screens.

To test:
1. Long press the launcher icon
2. Try to open the app using each of the shortcuts
3. Check whether the app is open on the correct screen

shortcuts_1
shortcuts_2

Note:
@iamthomasbishop Are names of these three events ok?
`"shortcut_stats_clicked", "shortcut_notifications_clicked", "shortcut_new_post_clicked"`

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Nice work @malinajirka! One *super* minor thing:

Can we move `new post` to the top of the list? Reasoning: IIRC, the data suggests the order of use is as follows: 1. Stats, 2. Notifs, 3. New Post. Can we were to invert this list to optimize for reachability? In other words, the most-used action (stats) would be closest to the trigger action and the lesser-used (new post) would be further away.

Other than that, 🚢 it!

**Comment by malinajirka** [comment]
Thanks for the review Thomas! I've moved `new post` to the top.

**Comment by nbradbury** [comment]
This all looks good - nice work @malinajirka! A couple of thoughts:
* Do we need to call [reportShortcutUsed](https://developer.android.com/reference/android/content/pm/ShortcutManager#reportShortcutUsed(java.lang.String)) anywhere?
* Is it necessary to have all the PNGs in the `mipmap` folder? I understand the reason for using mipmaps for launcher icons, but wouldn't devices that support pinned shortcuts also support SVGs?

**Comment by nbradbury** [comment]
@malinajirka The changes look good. If you're done, I'll merge it.

**Comment by malinajirka** [comment]
Thank you for reviewing this PR @nbradbury!

>Do we need to call reportShortcutUsed anywhere?

Great catch! I have added 'shortcut used' reporting.

>Is it necessary to have all the PNGs in the mipmap folder? I understand the reason for using mipmaps for launcher icons, but wouldn't devices that support pinned shortcuts also support SVGs?

Good point! I used Android Studio Icon Generator and I didn't realize I don't need pngs at all. 


I think it's ready for the second round. Thanks!

**Comment by nbradbury** [comment]
Looks great! :shipit:

**Pull request merged**
