### PR TITLE
[Home Page Picker] Adds template to the existing site creation analytics if a template was used

### PR DESCRIPTION
**Pull request by antonis**
Add's the template to the site creation analytics calls.

This is an alternative approach to https://github.com/wordpress-mobile/WordPress-Android/pull/13479
adding the template information to the `site_created` and the existing `enhanced_site_creation_success_*` event.

### Skip on site creation
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  Select `Skip` on `Choose a Design`
1. Complete the flow
1. **Expect** to see the events
```
enhanced_site_creation_accessed
enhanced_site_creation_site_design_viewed
enhanced_site_creation_site_design_skipped
enhanced_site_creation_domains_accessed
enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"antonistest81.wordpress.com","search_term":"antonistest81"}
enhanced_site_creation_success_loading
site_created
enhanced_site_creation_success_preview_viewed
enhanced_site_creation_success_preview_loaded
enhanced_site_creation_preview_ok_button_tapped
```

### Select site design
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  Select `Skip` on `Choose a Design`
1. Complete the flow
1. **Expect** to see the events
```
enhanced_site_creation_accessed
enhanced_site_creation_site_design_viewed
enhanced_site_creation_site_design_selected, Properties: {"template":"alves"}
enhanced_site_creation_domains_accessed
enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"antonistest82.wordpress.com","search_term":"antonistest82"}
enhanced_site_creation_success_loading, Properties: {"template":"alves"}
site_created, Properties: {"template":"alves"}
enhanced_site_creation_success_preview_viewed, Properties: {"template":"alves"}
enhanced_site_creation_success_preview_loaded, Properties: {"template":"alves"}
enhanced_site_creation_preview_ok_button_tapped
```

## Additional Context: 

This is a continuation of the work done in the [Home Page Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker). 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
This is working as described. Nice work Antonis :+1: 

Here are the events I observed for each flow:

### Create a site with a blog design

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134891.wordpress.com","search_term":"snaptest134891"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading, Properties: {"template":"blog"}
🔵 Tracked: site_created
🔵 Tracked: enhanced_site_creation_success_preview_viewed, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_success_preview_loaded, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

### Create a site with a non-blog design

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"barnsbury"}
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134892.wordpress.com","search_term":"snaptest134892"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading, Properties: {"template":"barnsbury"}
🔵 Tracked: site_created
🔵 Tracked: enhanced_site_creation_success_preview_viewed, Properties: {"template":"barnsbury"}
🔵 Tracked: enhanced_site_creation_success_preview_loaded, Properties: {"template":"barnsbury"}
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

### Create a site after skipping the design step

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_skipped
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134893.wordpress.com","search_term":"snaptest134893"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading
🔵 Tracked: site_created
🔵 Tracked: enhanced_site_creation_success_preview_viewed
🔵 Tracked: enhanced_site_creation_success_preview_loaded
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

**Review by mkevins — COMMENTED** [review]
The code looks good if we do intend to go this route.

**Comment by antonis** [comment]
As discussed I extended this PR by also adding the template information to the `site_created` event with e52f84b9fee6798b50058cfc62c3ae560cade0d8
cc @chipsnyder

**Review by mkevins — APPROVED** [review]
I've tested this again with the latest changes, and confirmed that the `site_created` event now emits with the `template` property:

### Create a site with a blog design

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134895.art.blog","search_term":"snaptest134895"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading, Properties: {"template":"blog"}
🔵 Tracked: site_created, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_success_preview_viewed, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_success_preview_loaded, Properties: {"template":"blog"}
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

### Create a site with a non-blog design

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134894.wordpress.com","search_term":"snaptest134894"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading, Properties: {"template":"alves"}
🔵 Tracked: site_created, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_success_preview_viewed, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_success_preview_loaded, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

### Create a site after skipping the design step

```
🔵 Tracked: enhanced_site_creation_accessed
🔵 Tracked: enhanced_site_creation_site_design_viewed
🔵 Tracked: enhanced_site_creation_site_design_skipped
🔵 Tracked: enhanced_site_creation_domains_accessed
🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"snaptest134896.wordpress.com","search_term":"snaptest134896"}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"IDLE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"CREATE_SITE","is_foreground":false}
🔵 Tracked: enhanced_site_creation_background_service_updated, Properties: {"phase":"SUCCESS","is_foreground":false}
🔵 Tracked: enhanced_site_creation_success_loading
🔵 Tracked: site_created
🔵 Tracked: enhanced_site_creation_success_preview_viewed
🔵 Tracked: enhanced_site_creation_success_preview_loaded
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped
```

LGTM! :+1:

**Pull request merged**
