### PR TITLE
Add custom selector for password button

### PR DESCRIPTION
**Pull request by marecar3**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/9905

**Summary:**
As we have struggled with google-material-library `1.1.0` and above, we have picked @oguzkocer suggestion https://github.com/wordpress-mobile/WordPress-Android/issues/9905#issuecomment-577979372 to use custom drawable and not to increment google-material-library. 

If this solution doesn't make an impact, we will try some other approach.

To test: 
1. Open the app
2. Make sure you are logged out
3. Go to the login screen with the password input field
4. Play around with the password (eye) icon.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
Hey @oguzkocer @malinajirka @designsimply I have targeted milestone `14.2` as maybe it would be too risky to add it to `14.1` (which deadline is today)

**Comment by oguzkocer** [comment]
@marecar3 I think we should definitely try to get this merged to `14.1`. Even if the freeze happens, since it addresses a crash, I think we can still target the release branch.

@malinajirka If you have time, do you think you can review this today? I had a quick look but I am about to sleep and can't test it. It'd be great to merge it before the cut off. Thanks!

**Comment by marecar3** [comment]
> @marecar3 I think we should definitely try to get this merged to `14.1`. Even if the freeze happens, since it addresses a crash, I think we can still target the release branch.
> 
> @malinajirka If you have time, do you think you can review this today? I had a quick look but I am about to sleep and can't test it. It'd be great to merge it before the cut off. Thanks!

Let's then try to target the `14.1` release.

**Comment by marecar3** [comment]
> Looks good :shipit:
> 
> I've compared the password field in 2 different emulators for `develop` and this branch and didn't find any differences. I uploaded the screenshots to an album here for reference: https://cloudup.com/cCXNDUYJflc
> 
> _small emulator is Nexus S - API 24 large emulator is Pixel 2 - API 26 No particular reason for picking these emulators, I just had them already setup and wanted to test in both._

Thanks @oguzkocer @malinajirka !!!

**Pull request merged**
