### PR TITLE
Experiment - Gutenberg Android X migration

### PR DESCRIPTION
**Pull request by marecar3**
Updates the Gutenberg mobile ref to point to the latest work, including the effort to migrate to AndroidX.

Gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1112

To test:
* Build and run WPAndroid and check that the block editor is working as normal.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Tested this PR and LGTM! I was able to build both from local src, and remote artifacts. 

Let me know @marecar3 if other tests are needed, I just see we're using RN 0.6.0-RC1, but i guess it's safe to use it for the moment, otherwise we can't move forward our prjs.

**Comment by marecar3** [comment]
Thanks @daniloercoli !

**Comment by marecar3** [comment]
I was also able to build both from local src, and remote artifacts.
It seems that we are ready :)

**Comment by hypest** [comment]
With v0.60 being a RC still, let's just test it out even more, ideally on the iOS side too, and look out for points of interest from [the changelog](https://github.com/react-native-community/releases/blob/953e7d7769183393a4bc14f18f2efdd84ac22495/CHANGELOG.md#060) that we might need to test.

It feels like the 0.60 release [is not far](https://github.com/react-native-community/releases/issues/116#issuecomment-503024903) although it will probably miss our code-freeze Monday so, yeah, let's test it out and we will probably merge before the 0.60 gets promoted to full release.

**Comment by marecar3** [comment]
Hey @daniloercoli @hypest 
You can do another iteration of testing as we are pointing to new RN release, RN-60-RC2
In my test cases, I didn't find any major issues.
Thanks!

**Comment by daniloercoli** [comment]
I've updated to latest GB `master` and tested this branch again on RC2. It looks good to me, didn't find any new problem.

**Comment by marecar3** [comment]
WIll mark this one as BLOCKED because React Native version 0.60 - RC2 has exposed some problems to  WPiOS app https://github.com/facebook/react-native/issues/25349. When we resolve those issues we can merge https://github.com/wordpress-mobile/gutenberg-mobile/pull/1112 into develop.

**Comment by hypest** [comment]
Will retarget this PR to the `gb/release-1.9.0` branch, to include it in the gutenberg-mobile release.

**Comment by daniloercoli** [comment]
Just noticed on a clean installation of the app - building the app with GB-src-code-mode set to OFF - WPAndroid hash c63e1e73eb, gutenberg-mobile hash 4107bf6e - that it doesn't show the Video block. 
Nor in the inserter, nor in the editor if you load a post with a video block (the default unsupported block placeholder is then shown).

**Comment by hypest** [comment]
> Just noticed on a clean installation of the app - building the app with GB-src-code-mode set to OFF - WPAndroid hash c63e1e7, gutenberg-mobile hash 4107bf6e - that it doesn't show the Video block.

Indeed, as @marecar3 has found out, we disabled the block in the v1.8 editor release so it stayed disabled in here too because we've updated from develop. Decided to just revert the release-notes.txt changes in this PR and enable the block in the v1.9 release PRs.

**Pull request merged**
