### PR TITLE
Issue/4438 pn read signal clear all

### LINKED ISSUE #4438: Send "read signal" PNs to automatically dismiss notifications on Android when Notifications Tab is seen on the web
Related issue: #1603 

When the notifications TAB is opened ~~on any of the 3 client apps~~  on the web, send a CLEAR ALL (badge-reset) notification to the remaining devices.
This is what we are doing already for iOS and the web (if you open the notifications tab on the web, a `badge-reset` PN is triggered for iOS).
Same should be done on Android: a `badge-reset` type PN should be sent to this users's registered Android devices and the client app should be able to handle that type of PN and thus clear any outstanding / read-pending notification from the native notifications dashboard.

This specific behavior is first commented / described here https://github.com/wordpress-mobile/WordPress-Android/issues/1603#issuecomment-54329077

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4438

To test:
This needs the backend counterpart to test, but basically:

1) log in with your account on an iOS and an Android device, as well as the web client on a browser.
2) have some other account like/comment/etc one of your posts
3) you'd receive push notifications about this action on both your iOS and Android devices - don't open them or do anything there yet, just observe this.
4) open the Notifications TAB on the web client
5) the notifications on both iOS and Android devices should be cleared.

Needs review: @kwonye

### CODE REVIEW

**Comment by kwonye** [comment]
> 5) the notifications on both iOS and Android devices should be cleared

Just want to clarify... Is this possible on iOS? From what I understand iOS doesn't support updating current notifications until iOS 10.

**Comment by mzorz** [comment]
> > 5) the notifications on both iOS and Android devices should be cleared
> Just want to clarify... Is this possible on iOS? From what I understand iOS doesn't support updating current notifications until iOS 10.

That's right - what iOS is doing is clearing the badge (thus the original name for that PN in the backend, which type is called `badge-reset`). Thanks for bringing this up @kwonye

**Comment by kwonye** [comment]
Works great! :shipit:

**Comment by mzorz** [comment]
Yay!

**Pull request merged**
