### PR TITLE
Refactors NoteBlock to Kotlin

### PR DESCRIPTION
**Pull request by antonis**
## Description
As an initial step towards the Milestone screen revamp this PR refactors some of the related code to Kotlin.

-----

## To Test:
1. Open the Notifications tab
2. Browse to different types of notifications
3. **Verify** no change in the functionality

-----

## Regression Notes

1. Potential unintended areas of impact

    - Notifications

4. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual Testing

5. What automated tests I added (or what prevented me from doing so)

    - I plan to add tests with a follow up PR

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>BlockType</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jarvislin — APPROVED** [review]
Thanks for making these refactors, it makes the foundation of codebase better. I've tested in different kinds of notifications, everything works as expected. LGTM

It seems that our CI/CD is unstable, I gonna re-run the task, please feel free to merge it after the build is done.

**Comment by antonis** [comment]
Thank you for reviewing @jarvislin 🙇 

> It seems that our CI/CD is unstable, I gonna re-run the task, please feel free to merge it after the build is done.

I'll run the tests again and if they fail I'll check if any change was introduced with the code. It's weird that https://github.com/wordpress-mobile/WordPress-Android/pull/20713 passed the CI checks with the 1st attempt 🤔

**Comment by antonis** [comment]
>I'll run the tests again and if they fail I'll check if any change was introduced with the code.

This should be fixed with 9fd9d9ad0cd5501c94653ac694e049817a71df1d

thank you for the tip @jarvislin 🙇

**Pull request merged**
