### PR TITLE
Merge hotfix 18.2.1 changes into release/18.3

### PR DESCRIPTION
**Pull request by AliSoftware**
### What

Hotfix 18.2.1 was submitted to Google, so merging the changes back to the current code-frozen release/18.3 to synchronize the changes.

The hotfix contains the following Gutenberg fix: https://github.com/wordpress-mobile/WordPress-Android/pull/15375

Note: the empty diff of this PR is expected (see below).

### Conflicts Resolutions & Empty Diff

<details><summary><tt>build.gradle</tt> was resolved by keeping Gutenberg's <tt>v1.62.0</tt> from this <tt>release/18.3</tt> branch.</summary>

```
<<<<<<< merge/release-18.2.1-into-18.3
    ext.gutenbergMobileVersion = 'v1.61.2'
=======
    ext.gutenbergMobileVersion = 'v1.62.0'
>>>>>>> release/18.3
```
</details>

A Gutenberg release `v1.62.1` [will soon be integrated in this branch](https://github.com/wordpress-mobile/WordPress-Android/pull/15379#issuecomment-929297770) to include the same fix that what was shipped in the hotfix.

<details><summary><tt>version.properties</tt> was resolved by keeping the versions from this <tt>release/18.3</tt> branch. </summary>

```
<<<<<<< merge/release-18.2.1-into-18.3
versionName=18.2.1
versionCode=1113
=======
versionName=18.3-rc-1
versionCode=1111
>>>>>>> release/18.3
```
</details>

As usual with hotfixes, this will likely create an invalid `versionCode` bump during the next beta; I plan to fix that manually when the time of the next beta comes.

---

ℹ️  Because both conflicts were resolved by keeping what's in `release/18.3`, this explains why the diff of this PR is empty. The PR is still useful in order to keep the git graph consistent and have the branch in sync in the git history.

### CODE REVIEW

**Comment by AliSoftware** [comment]
I'm planning to resolve the Gutenberg version conflict in `build.gradle` by keeping `1.62.0` in the `release/18.3` version, since it contains new features that were not in `1.61.1` and thus are not in `1.61.2` that was cut from `1.61.1` and got integrated in the WP `18.2.1` hotfix.

@geriux can you confirm I should expect a new `1.62.1` release of Gutenberg some time soon, to include that G fix in the latest Gutenberg used by the current release branch? Or maybe that issue was already fixed in `1.62.0`?

**Comment by geriux** [comment]
> @geriux can you confirm I should expect a new 1.62.1 release of Gutenberg some time soon, to include that G fix in the latest Gutenberg used by the upcoming branch?

That's correct, the `1.62.1` is in progress and it includes that fix. Here's the integration [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15371) for that one.

Thanks for working on this hotfix! 🚀

**Comment by loremattei** [comment]
> As usual with hotfixes, this will likely create an invalid versionCode bump during the next beta; I plan to fix that manually when the time of the next beta comes.

I wonder if the best place to fix this issue is actually this PRs. PRs which merge hotfixes always get a higher attention during the review anyway, so it would be easier to spot issues. And have everything ready for the next beta to be handled by the our tools as usual.

**Comment by AliSoftware** [comment]
> I wonder if the best place to fix this issue is actually this PRs. PRs which merge hotfixes always get a higher attention during the review anyway, so it would be easier to spot issues. And have everything ready for the next beta to be handled by the our tools as usual.

Yep, I sometimes do that too – that's actually what I did during the last hotfix, but… it happens that I still had to fix the version bump again anyway 😅  (maybe because I forgot to bump the alpha code too, iirc?). So I figured this time I'd try to do it the other way around 🤷‍♂️

**Review by mokagio — APPROVED** [review]
Easy review 😄 

image

I don't have a strong opinion on whether to [fix the version bump in this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15379/#issuecomment-929357034) or at the time of the next beta. I'm approving to allow this to move forward regardless. Auto-merge is not enabled, so the call is yours 😄

**Comment by AliSoftware** [comment]
We started discussing this in our Owl private Slack channel, and I'll try to remember to create an RFC or async-mtg discussion about this after my support rotation, to discuss how to handle such cases of version bumps for hotfix/beta in the future.

In the meantime, I'll merge this and update https://github.com/wordpress-mobile/WordPress-Android/pull/15381 accordingly. (given the correct bump was already done in the `release/18.3` branch after this 15379 PR when I issued the beta anyway, amending this PR now would cause more trouble than anything by now anyway)

**Pull request merged**
