### PR TITLE
New FAB icon

### PR DESCRIPTION
**Pull request by nbradbury**
Replaces the existing FAB icon with the "create" gridicon.

cc: @jasmussen 

newfab

### CODE REVIEW

**Comment by kwonye** [comment]
@nbradbury Just curious, there is no use of the `dark` image. Is this for future use?

**Comment by nbradbury** [comment]
> there is no use of the dark image. Is this for future use?

Possibly, yes. Since "create" is such a common action, I figured we should have both light & dark icons because there's a good chance we'll need a dark version for a menu somewhere.

**Comment by kwonye** [comment]
> I figured we should have both light & dark icons because there's a good chance we'll need a dark version for a menu somewhere.

Good enough for me! I'm normally opposed to having things in 'for future use', but assets are fine.

:shipit:

**Comment by jasmussen** [comment]
Looks good!

**Comment by folletto** [comment]
:+1:

**Pull request merged**
