### PR TITLE
Merge release branch after 20.8-rc-2 beta

### PR DESCRIPTION
**Pull request by AliSoftware**
Merging the release branch after doing a new beta.

The new beta includes:
 * https://github.com/wordpress-mobile/WordPress-Android/pull/17185
 * https://github.com/wordpress-mobile/WordPress-Android/pull/17189 to include https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2527
 * Latest `strings.xml` from GlotPress — had to manually fix `values-cs` in 6f4327df60d3c529870f5ece7d0989e8a80f7f5a due to placeholder inconsistencies in the translation (asked a GTE to reject it in GlotPress since)
 * Version bump in `version.properties`

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
LGTM! 💯

I am approving this PR, as always, but I have disabled `auto-merge` because I have one question we might like to discuss before merging.

Question (❓): I am seeing the manually amend `values-cs.xml` to fix the lint errors, thank you for that! 🥇 However, I am seeing two different resolutions and I was wondering why:
- For `feature_announcement_dialog_label` you kept the translation, just amended it with `%s` in favor of `WordPressu`. Looking at `values/strings.xml` I also feel that this is the correct way of dealing with it. Then this was rejected in GlotPress so that it get re-done. 👍
- For `calendar_scheduled_post_description` you completely removed the translation instead of amending it by possibly adding the extra ` \n %4$s`, which will end up in a new line, and I wonder why (again I picked on `values/strings.xml` to see the original translation). Wouldn't keeping this translation and amending it like you did above be a better alternative here too? 🤔 PS: Apologies for digging into that, I have no strong feeling about the end result, this is merely a question so I understand the process you follow in this situation a bit better.

**Comment by AliSoftware** [comment]
> Question (❓): I am seeing the manually amend `values-cs.xml` to fix the lint errors, thank you for that! 🥇 However, I am seeing two different resolutions and I was wondering why:

Answer is simple:
 - The first one was an easy fix for which I knew that the introduction of `%1$s` in the original was just to replace the term `WordPress`, so that was a safe bet to fix myself like I did. I considered removing it entirely, but figured replacing `Wordpressu` with `%1$s` was a good bet.
 - The second one was more complicated, especially I wasn't convinced that the order of the parameters didn't change (i.e. previous copy had `%3$s` as the text to put after the new line, and new copy had `%4$s` in that place instead, because `Wordpressu` was already a placeholder in 3rd position. Maybe replacing `Wordpressu` with `%3$s` and then replacing the old `%3$s` with `%4$s` would have been enough of a fix, but I felt less confident on this one, so preferred to just delete it and let polyglots fix it properly in GlotPress anyway.

**Comment by AliSoftware** [comment]
And as always, thanks for your extra attention to detail on those reviews @ParaskP7 🙇 

Merging this now that the question was clarified 🙂  (and next beta—or final release—will have the Czech entry removed or replaced anyway since those have been fixed in GlotPress since)

**Comment by ParaskP7** [comment]
Thank you for all this clarification @AliSoftware , much appreciated, it makes sense! 👍

**Pull request merged**
