### PR TITLE
Remove social subscribers

### LINKED ISSUE #20714: Stats Insights: Remove social (publicize) subscribers
Total Subscribers number on Insights is calculated by adding: wpcom + email + publicize (Jetpack social) subscribers. However, it's been removed from the web.

1. Update Total Subscribers card on Insights not to add publicize numbers
2. Update Total Subscribers -> Details to remove "Social" from Subscribers table

image

### PR DESCRIPTION
**Pull request by irfano**
Fixes #20714 

This removes social subribers from the detail screen of the Total Followers card and additionally, changes the endpoint for the "Total Followers" card from `/sites/$site/stats/summary/` → `stats/subscribers`. 

Additionally, this PR removes `FollowerTotalsUseCase`, which was already unused. This card was being used only on the WordPress app but then we removed stats from WP, now it's fine to remove the usecase as well. I haven't removed `InsightType.FOLLOWER_TOTALS` from FLuxC for now because it may cause crashes on a case when upgraded from a very old version since selected insight cards are stored in the db.

|after|
|-|
||

-----

## To Test:

1. Log in
2. Enable stats_traffic_subscribers_tab flag from "Me → Debug settings"
3. Navigate back.
4. Open the INSIGHTS tab from "My Site → Stats".
5. Tap the "VIEW MORE" button on the Total Followers card.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - Updated `FollowerTypesUseCaseTest` and `FollowerTotalsUseCaseTest`

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by aditi-bhatia — APPROVED** [review]
Lgtm, works as expected 👍  I went ahead and merged in trunk since there was a conflict. Just curious, when would be considered a good time to remove `InsightType.FOLLOWER_TOTALS` from FluxC?

**Comment by irfano** [comment]
Thanks for resolving the conflict. 

> when would be considered a good time to remove InsightType.FOLLOWER_TOTALS from FluxC?

I've made a note of it for myself. I will remove it after the project by checking if it affects old versions.

**Comment by aditi-bhatia** [comment]
> I've made a note of it for myself. I will remove it after the project by checking if it affects old versions.

Sounds good, thanks!

**Pull request merged**
