### PR TITLE
Posts list: upload status text and icon changes

### PR DESCRIPTION
**Pull request by mzorz**
This PR implements the changes for `Uploading` and `Queued` states (text + icon) for a given Post to be represented as such within the Posts list, as per the following:

27458075-4023c648-5775-11e7-847c-a247c5967867

cc @nbradbury

### CODE REVIEW

**Comment by mzorz** [comment]
@nbradbury known issue: for this one I'm having lots of trouble trying to make the cloud upload icon base align with the text. Any suggestions for this welcome :) 🙇

**Comment by nbradbury** [comment]
> I'm having lots of trouble trying to make the cloud upload icon base align with the text. Any suggestions for this welcome

Would it help to have a separate ImageView for the icon, so it's not a `drawableLeft` on the TextView? I *think* you may need to do that anyway due to issues using vectors in `drawableLeft`.

**Comment by mzorz** [comment]
Thank you @nbradbury - I've been considering either going the way you suggested (having a separate ImageView) or moving everything to their PNG versions.

So these are the current icons we have, that represent different statuses in the Posts List:

screen shot 2017-07-14 at 9 21 33 am


Digging a bit more I also realized the `ic_pages_alert_red_16dp`  is not being used actually, because that's supposed to represent trashed items, and we simply do not show trashed items in the Posts list AFAICT.
So that leaves just 1 icon `noticon_scheduled_alert_yellow_16dp` used to represent `Draft`, `locally changed`, `private`, `pending`, and `scheduled`.

I was thinking of going with the ImageView approach as you suggested, and also normalize every icon to use the vector version, so in looking for a replacement for the replace the `noticon_scheduled_alert_yellow_16dp` icon I thought of replacing it like this, given I didn't find a direct replacement in the gridicons repo:

- `noticon_scheduled_alert_yellow_16dp` ([link to current png](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/drawable-hdpi/noticon_scheduled_alert_yellow_16dp.png)) -> https://github.com/Automattic/gridicons/blob/master/sources/svg/gridicons-pages.svg
screen shot 2017-07-14 at 9 28 49 am

- and also use this one for the `scheduled` Post status
https://github.com/Automattic/gridicons/blob/master/sources/svg/gridicons-scheduled.svg
screen shot 2017-07-14 at 9 28 32 am

(both would have the right tint - yellow, as shown in the code)

what do you think @nbradbury? cc @folletto

**Comment by folletto** [comment]
Heya! I'm not sure I understand the problem entirely. 
Can you show the use of the two in context? So I've a reference to see where the icons would appear — also under which condition, and what are the other icons in the set for each status?

**Comment by nbradbury** [comment]
If you're looking to replace the scheduled icon, I think it should use [this gridicon](https://github.com/Automattic/gridicons/blob/master/sources/svg/gridicons-calendar.svg) to match Calypso.

scheduled

**Comment by mzorz** [comment]
> Can you show the use of the two in context?

**Comment by mzorz** [comment]
> Can you show the use of the two in context? 

Sure! First let's look at these 2 mockups
screen shot 2017-07-14 at 11 37 43 am
screen shot 2017-07-14 at 11 37 28 am

As you can see the cloud upload icon is used in this PR now for either `queued` or  `uploading` posts as seen in the first image, as requested by the design. Now, for all of these other states:
- `local draft`
- `local changes`
- `draft`
- `pending review`
- `scheduled` (*)
currently [`noticon_scheduled_alert_yellow_16dp` (which name I can see now might be misleading, right?)](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/drawable-hdpi/noticon_scheduled_alert_yellow_16dp.png) is used, that is, this one here:
screen shot 2017-07-14 at 11 52 01 am

As I'm moving these icons to vector images, **my question is: 1) is there a direct replacement for that icon ^^^^ screen shot 2017-07-14 at 12 09 55 pm  in gridicons?** if there is, and you can point me to it, that'd be awesome - otherwise I was proposing to use the following one for all those cases: https://github.com/Automattic/gridicons/blob/master/sources/svg/gridicons-pages.svg

By using that icon all these following cases 
- `local draft`
- `local changes`
- `draft`
- `pending review`
- `scheduled` (*)
would look like this:

screen shot 2017-07-14 at 11 57 32 am copy

(note in the image I only made it up with my very poor skills, these would have the right colors and such, which is `#f0b849` for both the icon and the text in all these cases).

Finally, **(second question)** I find that the `scheduled` state (as I marked with * up there in the lists within this comment) could benefit of using another icon, just like [@nbradbury suggested](https://github.com/wordpress-mobile/WordPress-Android/pull/6294#issuecomment-315358493). I 

I hope that clarified a bit! What do you think @folletto ?

**Comment by mzorz** [comment]
Went ahead with the [`ImageView`  option as suggested](https://github.com/wordpress-mobile/WordPress-Android/pull/6294#issuecomment-315208420) so we could use vector drawables gently, and added [the proper scheduled icon to match Calypso](https://github.com/wordpress-mobile/WordPress-Android/pull/6294#issuecomment-315358493)
Also, I separated the different statuses into more granular messaging while the upload is happening, namely these: 

- Uploading post
- Uploading media
- Queued

This is how it looks like now:

screenshot_20170714-184906
screenshot_20170714-184923


Note the cloud icon still has a slight padding issue for my untrained eye; in any case I think that should be addressed in another PR through the replacement of the icon itself (code shouldn't treat that icon any different than we treat the rest of icons).

Ready for another round @nbradbury

**Comment by nbradbury** [comment]
I'm getting this crash when I visit the post list:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference
                                                                                at android.support.v4.graphics.drawable.DrawableCompatLollipop.setTint(DrawableCompatLollipop.java:53)
                                                                                at android.support.v4.graphics.drawable.DrawableCompat$LollipopDrawableImpl.setTint(DrawableCompat.java:220)
                                                                                at android.support.v4.graphics.drawable.DrawableCompat.setTint(DrawableCompat.java:386)
                                                                                at org.wordpress.android.ui.posts.adapters.PostsListAdapter.updateStatusTextAndImage(PostsListAdapter.java:451)
                                                                                at org.wordpress.android.ui.posts.adapters.PostsListAdapter.onBindViewHolder(PostsListAdapter.java:256)
                                                                            
```

**Comment by mzorz** [comment]
Gotcha looking into it 👍

**Comment by mzorz** [comment]
Addressed in 5441ba4

**Comment by nbradbury** [comment]
It looks like there should be more space between the status icon and the status text. I think `android:layout_marginRight="@dimen/margin_small"` on the icon should do it. Also, should the scheduled icon color match Calypso (`blue_medium`, I think)? Here's what those two changes would look like:

device-2017-07-14-191002

**Comment by nbradbury** [comment]
Sorry, just noticed that the date text doesn't align with the status text now that the status icon has that margin. How about adding `drawablePadding="@dimen/margin_small"` to the date icon? That would look like this:

device-2017-07-14-192108

**Comment by mzorz** [comment]
awesome!, escape my eyes as well, addressed in d9cc99d

**Comment by nbradbury** [comment]
Looks great! Obviously we'll want designer input on my suggestions (I'm not a designer, I just play one in my head), but since this is a feature branch I'm good to :shipit:

**Pull request merged**
