### PR TITLE
Merge recent WordPress-Login-Flow-Android changes

### PR DESCRIPTION
**Pull request by shiki**
This applies the recent WordPress-Login-Flow-Android changes as described in https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/24. The changes are mainly from these 2 PRs:

- https://github.com/wordpress-mobile/WordPress-Android/pull/10255
- https://github.com/wordpress-mobile/WordPress-Android/pull/10142

## Release Notes

- [x] If there are user-facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
Tested login on API 28 + 22 and both worked as expected.

**Comment by shiki** [comment]
Thank you, @AmandaRiu! I marked this as _Ready for Review_ since https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/24 was merged. Can I merge this? 🙂

**Comment by jkmassel** [comment]
I'm bumping this to `13.1` as part of the `13.0` code freeze.

If you'd like it to be released as part of `13.0`, please merge it against `release/13.0` then DM me, and I'll be happy to issue a new beta release! :)

**Comment by shiki** [comment]
No worries, @AmandaRiu. You're right. It's just to bring in the merge commit into WPAndroid for completion.

**Pull request merged**
