### PR TITLE
Feature/hide bottom nav onscroll

### PR DESCRIPTION
**Pull request by nbradbury**
Updates bottom navigation so that it hides when you scroll down and re-appears when you scroll up.

I had hoped I could rely on a `CoordinatorLayout` to do the work for us, but that didn't pan out so I opted for the more involved approach of using a listener in each of the four main fragments to alert the main activity when they're scrolled.

### CODE REVIEW

**Comment by folletto** [comment]
I'm not too keen on implementing this solution. I'm aware that Material outlines this as a possibility, but it comes at a usability cost: the toolbar is meant to be visible, reliably so, on the screen. If it disappears, it means that it's not quick anymore: one has to check first if it's visible, and then wiggle to show it, and then tap.

While there are some apps where the need to hide it can supersede the need to have it always visible, I don't think it's the case for our app. 

Sorry if I came in late when the PR is already out instead of sparing the work :|

**Comment by nbradbury** [comment]
> While there are some apps where the need to hide it can supersede the need to have it always visible, I don't think it's the case for our app.

While I'm not wedded to the idea of hiding bottom nav, I should mention that the idea was to provide extra space for landscape users. Bottom nav takes up more space than the previous tab navigation did because bottom nav added a toolbar. 

screenshot_1527007066

**Comment by iamthomasbishop** [comment]
After thinking about this a bit, even though I personally enjoy this show/hide nav pattern in other apps, I think I am in agreement w/ @folletto - hiding the bottom nav could potentially cause some confusion and I'm not sure there is a big win vs. persistent/static visibility. I can understand where it'd be nice on the landscape variation, but we should probably be consistent whichever pattern we stick with.

I was thinking it might be useful in the context of Reader, but that's mainly because we have three levels of navigation (app bar, filter bar, bottom nav) on the list pages, and that is another issue altogether 😄

**Comment by nbradbury** [comment]
OK, I'll close this then. It would be nice to do something about the extra space the toolbar takes up (esp. in landscape) but that's a separate discussion :)

**Pull request closed without merging**
