### PR TITLE
Upgrade Mixpanel library

### LINKED ISSUE #3067: Upgrade Mixpanel library to the latest version
Title has it.

### PR DESCRIPTION
**Pull request by daniloercoli**
Upgrade the Mixpanel library to the latest version available out there. 
Fix #3067

### CODE REVIEW

**Comment by astralbodies** [comment]
I just did the same on iOS, so good idea :+1:

**Comment by tonyr59h** [comment]
Adding `-dontwarn com.mixpanel.**`to `proguard.cfg` allows it to compile fine. We'll have to make sure it still works as expected with that change though.

**Comment by daniloercoli** [comment]
Adding `-dontwarn com.mixpanel.**` to `proguard.cfg` fixes the problem. Just tested and everything we use in Mixpanel is working as expected.

Note: `-dontwarn` will cause Tweak and A/B test not working properly. It's not an issue at the moment, since we're not using them. More info here: https://github.com/mixpanel/mixpanel-android/issues/245

**Comment by maxme** [comment]
Upgraded Mixpanel version and proguard issues fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/2795

**Pull request closed without merging**
