### PR TITLE
Keep CommentsActivity on rotation, resize Fixes #1142

### LINKED ISSUE #1142: Rotate the device dismiss the keyboard while replying to a comment
Tested on Nexus 7 and Nexus 5

1. Go to the comment list
1. Tap a comment and start to write a reply
1. Rotate portrait to landscape or landscape to portrait
1. Keyboard is dismissed

### PR DESCRIPTION
**Pull request by hypest**
Otherwise the virtual keyboard doesn't automatically come up (even though the input focus is retained).

### CODE REVIEW

**Comment by nbradbury** [comment]
Note that `CommentDetailFragment` is also used by notifications (you can tap a comment notification to view the comment detail), and in that situation it isn't hosted in `CommentsActivity`. This where a lot of users will reply from, so relying on `ConfigChanges` in `CommentsActivity` won't work here.

**Comment by khaykov** [comment]
I think keyboard disappears because of the way android handles EditText/keyboard combo when there are not enough screen space. I also can't reproduce this issue on Nexus 9 which has enough screen size, and that also hints to this issue.

You can tell that landscape mode on smarthone
screenshot-2016-01-28_12 53 52 669

Looks different then on a tablet (I cut out the comment body)
screenshot-2016-01-28_12 59 28 31


That's because on smartphone, in landscape you actually see ExtractEditText with soft keyboard. And the keyboard disappears during orientation change because of all the magic between ExtractEditText, keyboard and actual fragment.

Easy fix is to add  android:imeOptions="flagNoExtractUi" to our EditText. This prevent ExtractEditText from being shown.
This makes landscape on smartphones look like this, with original EditText style.
screenshot-2016-01-28_13 07 19 272

And the keyboard stays open on configuration change. EditText looks a little bit weird in landscape, so I'm not 100% sure this could be used as solution.

**Comment by hypest** [comment]
@nbradbury indeed, thanks for the headsup! Will get to it. Gonna try some other attach vector since I wouldn't like to `configChanges` yet another activity!

@khaykov thanks for analysis! I'm afraid the `android:imeOptions="flagNoExtractUi"` doesn't help here. I kinda doubt it would anyway since the documented purpose of that flag is to *disable* the full-screen keyboard. But that full screen keyboard is exactly what would "help" in the small screens case. Also, this option doesn't easily explain why retaining the fragment does keep the keyboard open on rotation.

**Comment by hypest** [comment]
I've added a different approach for keeping the keyboard open. This time, I made `SuggestionAutoCompleteText` associate its focus state with the keyboard being open or not. In essence, if the editbox has focus, the keyboard will be open for input. Then, SuggestionAutoCompleteText keeps its focus state as an instance variable.

Pros: no need for the debatable `configChanges` manifest attribute.
Cons: SuggestionAutoCompleteText is "smarter" than someone would expect and bypassing the typical (Android) behaviour of focus on an editbox.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
