### PR TITLE
Convert post list fragment and adapter to Kotlin

### PR DESCRIPTION
**Pull request by oguzkocer**
As part of the list store integration for post list, we'll use Kotlin coroutines, which means our code needs to be in Kotlin or we need helpers with Java interfaces. Since we want our code to be in Kotlin anyway, I thought it's a good opportunity to update these two components to Kotlin.

This PR tries to replace said components without refactoring or making any Kotlin specific improvements to them. (most of the conversion is done by AS) There are still some minor changes to make the code more Kotlin-y, but I didn't want to spend too much time on it as I'll be making a lot of changes to it in the next PRs.

@malinajirka Let's try to avoid any major changes to this code in this PR as I have a lot of changes in both of these classes in another branch and I don't want to spend too much time on merging them. If a change will prove difficult to merge, we can do that in or after the next PR. Also, our goal is not a major refactor/rewrite of these classes. I realize a lot of it is far from ideal, but I don't have any time to actually fix those.

Please also note that this branch is targeting a new master branch instead of `develop`. My primary goal with this PR is to make it easier to review the next ones. This will give us some more time to make improvements to Kotlin conversion after `ListStore` integration is done but before it's merged into `develop`.

To test:
* There shouldn't be any functionality changes. It'd be great if you can test the post list in general.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @oguzkocer !

I agree converting those files to Kotlin is a good idea:), however converting them in a separate branch without freezing these files my bite us (merge conflicts will be basically unresolvable). I think we should first inform everyone on the team what we are planning. Ask everyone to merge any changes to the files and freeze the files until we merge this change into develop. Wdyt?

I've scanned the files and run the app and I've haven't found anything suspicious.

**Comment by oguzkocer** [comment]
> Ask everyone to merge any changes to the files and freeze the files until we merge this change into develop. Wdyt?

I don't think that'll be necessary. These two files are not updated that often, especially recently and any change that's made in the Java versions will show up as a merge conflict, so we can fix that in our branch. We are also aiming to finish this project asap, so it should all be merged pretty soon.

Having said all that, if you're still uncomfortable with this, we can fix any important issues in this PR and then merge it against `develop`.

**Comment by malinajirka** [comment]
I still think it's a bit risky (PostListFragment has been updated twice in the last two weeks), but let's do it. However, I think we should at least ping everyone next time we do a similar conversion.

**Comment by malinajirka** [comment]
I still think it's a bit risky (PostListFragment has been updated twice in the last two weeks), but let's do it. However, I think we should at least ping everyone next time we do a similar conversion.

**Comment by malinajirka** [comment]
I still think it's a bit risky (PostListFragment has been updated twice in the last two weeks), but let's do it. However, I think we should at least ping everyone next time we do a similar conversion.

**Comment by malinajirka** [comment]
I still think it's a bit risky (PostListFragment has been updated twice in the last two weeks), but let's do it. However, I think we should at least ping everyone next time we do a similar conversion.

**Comment by malinajirka** [comment]
I still think it's a bit risky (PostListFragment has been updated twice in the last two weeks), but let's do it. However, I think we should at least ping everyone next time we do a similar conversion.

**Pull request merged**
