### PR TITLE
Gutenberg content detected dialog [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by mzorz**
This PR implements showing a dialog to warn the user that Gutenberg content is about to be edited, when Gutenberg blocks are detected within the content of Posts or Pages.

Notes: 
- the implementation of the dialog is based on the `BasicFragmentDialog` class, derived from `AppCompatDialogFragment` which contains all the latest improvements to handle Fragment/Activity saved states, rotation and other common Android lifecycle problems.
- the `BasicDialogPositiveClickInterface` and `BasicDialogNegativeClickInterface` interfaces have been enhanced to carry an `extras` param, which we're using here to communicate the Post's id in callbacks
- given the PromoDialog was being used with an interface with the same signature, I added the same param there as well, even if unused for now it'll be good for future use, and also otherwise keeping the interface implied tweaking even more code that I didn't want to risk breaking here.
- we need to verify/edit the copy (I made up the one being shown right now). cc @koke @hypest for help there
- Tracking: we are tracking the 3 moments:

```
        GUTENBERG_WARNING_CONFIRM_DIALOG_SHOWN,
        GUTENBERG_WARNING_CONFIRM_DIALOG_SHOWN_YES_TAPPED,
        GUTENBERG_WARNING_CONFIRM_DIALOG_SHOWN_CANCEL_TAPPED

```
the corresponding strings being used are:
- `gutenberg_warning_confirm_dialog_shown`
- `gutenberg_warning_confirm_dialog_shown_yes_tapped`
- `gutenberg_warning_confirm_dialog_shown_cancel_tapped`

Those will appear on Tracks with the `wpandroid_` prefix.

### **To test:**
**CASE A: Gutenberg Post**
1. open the posts list
2. tap on a Gutenberg Post
3. the dialog should be shown:
screen shot 2018-10-29 at 23 41 55
4. if you choose `EDIT POST`, the Post should open in the editor.
5. if you choose `GO BACK`, you should just stay on the posts list and the dialog is dismissed.

**CASE B: Non-Gutenberg Post**
1. open the posts list
2. tap on a non-Gutenberg Post
3. the dialog should NOT be shown.

**CASE C and D: Pages**
Try the same as above with Pages, and observe the title of the dialog changes from "Gutenberg Post"  to "Gutenberg Page". The positive button should also say "Edit Page" instead of "Edit Post" as well.
screen shot 2018-10-30 at 01 31 48

**CASE E: Tracks**
As you test all of the above, also please verify the corresponding Tracks events appear on the backend.

**Questions / discussion**:
- This dialog will appear each single time a Post/Page with Gutenberg blocks is found. Should we have an internal counter saved to prefs and only show the dialog every n times the user opens a Gutenberg post? Or maybe, should we add a checkbox to "don't tell me this again"?

cc @hypest @koke

### CODE REVIEW

**Comment by benhuberman** [comment]
@mzorz feel free to ping me here once @koke / @hypest had a chance to chime in and if you might still need an editor's review on any suggested edits. (For example, in the current copy both the length and the references to Gutenberg itself might warrant tweaking, but I'm happy to stay put until others had a chance to offer their feedback.)

**Comment by mzorz** [comment]
Thank you @benhuberman! For sure, will let @koke and @hypest and others chime in and take it from there. Thanks for the early ping!

**Comment by mzorz** [comment]
As per discussions with @koke @hypest and @elibud elsewhere, here are further changes:
- [ ] keep the copy as per Koke’s suggestion:
`
We are working hard to bring the new WordPress editor to the apps. You can still use the app editor to edit this post, but we recommend you preview the results before publishing and let us know if something doesn’t look right.
`
- [ ] add a `never show this again` option
- [ ] leave a placeholder for a `learn more` link

**Comment by mzorz** [comment]
Can you check the copy looks good @benhuberman please? 🙇 ☝️

**Comment by benhuberman** [comment]
Thanks @mzorz  -- this reads better to me, though I wonder if we could add a more concrete reason why the user should preview their edits, otherwise there's a bit of a disconnect between "we're working on the new editor" and "please preview before publishing." There's also a hyphen missing in "brand new." Here's a suggested edit:

> **Before you continue**:
> We're working on a brand-new WordPress editor. To make sure no formatting quirks make their way into your post, we recommend previewing it before publishing.

What neither version addresses, of course, is what a user _should_ do if they see a formatting issue -- I'm not sure there's a way to address it in the pop-up dialog, but it's something to perhaps think about, since just previewing would make them aware of a problem, but not of the solution to it.

**Comment by mzorz** [comment]
> What neither version addresses, of course, is what a user should do if they see a formatting issue -- I'm not sure there's a way to address it in the pop-up dialog, but it's something to perhaps think about, since just previewing would make them aware of a problem, but not of the solution to it.

Totally agreed, I think there are plans to have the `learn more` button give them more instructions on what the editors are, how to reach out to us if they have problems, and more. Not sure it's the best solution but at least that will have that path covered. cc @iamthomasbishop 

- Added Learn more, tapping on it opens a web view at `https://apps.wordpress.com/gutenberg`.
- added `don't show anymore` checkbox, tapping on it remembers the decision.
- both actions also are now tracked (checkbox has 2 actions being tracked, for checking and unchecking).
`gutenberg_warning_confirm_dialog_shown_dont_show_again_checked`
`gutenberg_warning_confirm_dialog_shown_dont_show_again_unchecked`
`gutenberg_warning_confirm_dialog_shown_learn_more_tapped`

cc @diegoreymendez for the Tracks strings parts ☝️ 

gutenberg_dialog

This one should be ready for review (we may even change the copy later as well) @hypest . Sorry for the length of the change, was supposed to me something 'minor' and ended up touching several parts.

**Comment by mzorz** [comment]
Closing in favor of #8524

**Pull request closed without merging**
