### PR TITLE
Reinstate missing "none" string Fixes #3621

### LINKED ISSUE #3621: Missing default translation for string name="none"
The default string literal for the "none" string is missing.

### PR DESCRIPTION
**Pull request by hypest**
The string got missing in a recent refactoring so, this PR just gets it back.

### CODE REVIEW

**Comment by nbradbury** [comment]
A very minor nit: how about moving this string under the `<!-- general strings -->` section?

**Comment by hypest** [comment]
@nbradbury reasonable enough. I'll move it to general, with the caveat that it is so general that translations can be way off (due to wrong context).

**Comment by nbradbury** [comment]
:shipit:

**Comment by maxme** [comment]
That one should be cherry picked in `release/5.0`

**Comment by hypest** [comment]
Will cherry pick it, +1

**Pull request merged**
