### PR TITLE
Show toast when user attempts to delete post with in-progress uploads

### LINKED ISSUE #6280: Posts list: show a Toast when trying to delete a Post that is being uploaded
(known issue as per [this ToDo comment](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/one-true-uploadservice/WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java#L554)) you can’t tap Delete on the Posts list for a post that has media being uploaded. It doesn’t do anything, we should at least show a Toast if we’re keeping it that way on purpose (although cancelling all related uploads would be always a better option).

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #6280.

To test:
* Create a post with some media that will take some time to upload
* Attempt to delete the post from the posts list

### CODE REVIEW

**Comment by tonyr59h** [comment]
I'm wondering if it would make more sense to have a confirmation dialog here. Something that will cancel the downloads and delete the post for them rather than having them do it manually.

**Comment by mzorz** [comment]
> I'm wondering if it would make more sense to have a confirmation dialog here. Something that will cancel the downloads and delete the post for them rather than having them do it manually.

Totally! This would probably be the best option. Would you like to do it on this PR? Or we can merge this one and create a new issue for that

**Comment by mzorz** [comment]
As chatted, we'll create a new issue to go with the Dialog option.
This one is GTG

**Comment by mzorz** [comment]
:shipit:

**Comment by tonyr59h** [comment]
Note: Created #6306 to improve this.

**Pull request merged**
