### PR TITLE
Update follow and following icons and color

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update icons and color for Follow and Following buttons as described in https://github.com/wordpress-mobile/WordPress-Android/issues/4354.

### Test
<ol><b>Follow</b>
<li>Go to Reader tab.</li>
<li>Tap Search action.</li>
<li>Enter random word.</li>
<li>Tap unfollowed site.</li>
<li>Notice Follow icon and color.</li>
</ol>

<ol><b>Following</b>
<li>Go to Reader tab.</li>
<li>Choose Followed Sites from the dropdown list.</li>
<li>Tap first post in list.</li>
<li>Notice Following icon and color.</li>
</ol>

### Review
@nbradbury

### CODE REVIEW

**Comment by nbradbury** [comment]
:shipit:

**Comment by jancavan** [comment]
This appears to be the current behavior, but the text color for Follow/Following are initially blue-ish then changes to dark gray/green in less than a sec:

screenshot 2016-07-18 15 11 09

screenshot 2016-07-18 15 11 05

Also, minor nitpick: any way to horizontally align the icon and text by moving the icon a couple pixels down?

screenshot-2016-07-18-15 00 46

**Comment by theck13** [comment]
Where are you seeing the light blue font for Follow/Following within the app?

The icons are vertically centered with the font.  See the screenshots below for a clarification.

follow

following

There is no internal padding added programmatically.  The icons were imported from the SVG files attached to https://github.com/wordpress-mobile/WordPress-Android/issues/4354.  Do you have SVG files without padding?

**Comment by jancavan** [comment]
> Where are you seeing the light blue font for Follow/Following within the app?

Using an emulator, on `master` branch. Video: https://cloudup.com/ccjLsyWHTMR

The text changing color also happens in version 4.2 of the app, but with the old icon.

**Pull request merged**
