### PR TITLE
[Site Creation] Site Preview Landscape Layout

### LINKED ISSUE #8687: Site Creation: Site Preview Landscape
We have a slightly different design for the landscape version of the new site preview screen. Since the original PR is merged without it, I am opening an issue for this just to make sure we don't forget about it.

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #8687. This PR adds an alternate layout for the landscape orientation of the site preview page.

Here are screenshots for the portrait and landscape orientations:

screenshot_1548726074
screenshot_1548726053

I've recorded gifs to showcase the animations. I've slowed the animation down to make the review easier. [Portrait](https://cloudup.com/cwLb86u4lUv), [Landscape](https://cloudup.com/cILlzs78ADZ)

* In these gifs a site is not actually created, I am loading one of my test sites in it. (for faster testing)
* The last few frames in the portrait animation seems to be cut off, or playing too fast. Please ignore that, the site loads just fine.
* The landscape one was rotated after its recorded. That's why it's lower quality.

**To test:**
* Enable the `NEW_SITE_CREATION_ENABLED` in `WordPress/build.gradle`.
* Go through the site creation flow in both portrait and landscape modes and verify that everything looks good and matches the screenshots above.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by oguzkocer** [comment]
```
/home/travis/build/wordpress-mobile/WordPress-Android/WordPress/src/main/res/layout/new_site_creation_preview_screen.xml:45: Error: The id "sitePreviewOkButtonContainer" in layout "new_site_creation_preview_screen" is missing from the following layout configurations: layout-land (present in layout) [InconsistentLayout]
              android:id="@+id/sitePreviewOkButtonContainer"
```

@malinajirka I am getting `InconsistentLayout` lint error for the `sitePreviewOkButtonContainer` which I guess is a fair error. What do you think would be the best path to fix this? Should we add the container to the landscape version just to wrap the button for consistency?

I tried a couple things and failed, I'll need to take a look on Wednesday. Feel free to review the rest of the PR till then. Thanks!

**Comment by malinajirka** [comment]
Thanks @oguzkocer! I've tested it and it looks awesome! The code looks good as well.

>@malinajirka I am getting InconsistentLayout lint error for the sitePreviewOkButtonContainer which I guess is a fair error. What do you think would be the best path to fix this? Should we add the container to the landscape version just to wrap the button for consistency?

I don't think we should modify the layout just to get rid of a warning. I think, since this is something we do intentionally, it's complete fine to suppress this warning with `tools:ignore="InconsistentLayout"` on the `CardView`. Wdyt?

If you decide to suppress the warning feel free to merge this PR by yourself.

**Comment by SylvesterWilmott** [comment]
Looking good @oguzkocer !

Transition looks awesome. One thing, were there problems extending the preview container to the very bottom of the view?

Couple of other things I noticed:

- The address bar has rounded corners on all sides, rather they would only be applied to the top corners.
- Theres a little white area at the bottom of the preview container in landscape, Im not sure what's causing that but presumably it doesn't exist in the portrait version because the preview is below the button bar?

**Comment by malinajirka** [comment]
>There was a 8dp bottom margin on the web view, I can't remember why it's there. I've moved the margin to the OK button container instead. (as top margin of course)

I believe it's there because of [this](https://github.com/wordpress-mobile/WordPress-Android/pull/8654#issuecomment-441224648) comment. Specifically `Nitpick: I'd suggest adding a bottom padding to the CardView and draw it "behind" the sitePreviewOkButtonContainer so the rounded corner is not visible. Wdyt?`


>@malinajirka Any ideas about this one if we want to keep the regular layout for the landscape version for tablets?

I haven't tried it, but my guess is that copying the regular layout to `layout-sw600dp-land` should be enough. The OS will use the layout from the most specific folder for which all the attributes (such as sw600, land etc) matches.

**Comment by oguzkocer** [comment]
> Sorry for the mix up, just to clarify, I was talking about the white area, not the grey part.

I did misunderstand this one, it's fixed in e11f4afc29155ce8a6d72545bbd2db08e6ea56ad

> I should only see this layout on a phone in landscape. Specifically I should see this layout when the viewport height is 360dp or less.

I think `360dp` is too small. According to [this doc](https://developer.android.com/training/multiscreen/screensizes), `480dp` is the landscape height of the larger phones and `360dp` is the one for the typical phones. I assume we want to use the alternate layout for phones like Pixel, so I opted to use `480dp` instead. Let me know if you want me to change that @SylvesterWilmott!

Here are screenshots after the latest changes: https://cloudup.com/cOJGmaV3hCB

@malinajirka I've made this ^ change in f08cc3725c0dac7c147f1d97b4978b6cab465bbe & a90980107e927ccfe0d36240c2927c5f561f0aca. If I understand the docs correctly, there is no resource for `up to a height`, so I had to add the alternate version as the default landscape and added another resource for layouts with landscape height larger than `480dp`. In order to be able to reuse the regular layout, I moved it to a different resource and included it in both the portrait mode and this newly added resource for landscape larger than `480dp`. That resulted in some `InconsistentLayout` issues that I had to ignore. It feels really bad to have to do this, but I can't find an alternative. Finally, I changed the logic for when to use the slide in animation and when to fade in, since I can't rely on the orientation anymore. It'd be great if you can test all this out in different devices. I tested the animation and the layout, but I might have missed something :(

**Comment by malinajirka** [comment]
Thanks @oguzkocer ! I've tested it on a couple of devices and it looks awesome!

**Pull request merged**
