### PR TITLE
Material Design launcher icon!

### PR DESCRIPTION
**Pull request by jasmussen**
New WordPress icon that better matches the Material makeover the rest of the app is getting. It follows Google guidelines (http://www.google.com/design/spec/style/icons.html), it uses "WordPress Medium Blue" brand color, and it matches the new Material Simplenote icon in card style.

### CODE REVIEW

**Comment by maxme** [comment]
Note: the new xxxhdpi size is correct (192px), old one was too big.

**Comment by nbradbury** [comment]
The new icon looks great @jasmussen! At first I thought the square seemed too small, but I compared it to Google's material icons and it fits right in. :shipit: 

material-icons

**Comment by jasmussen** [comment]
:)

I tried following guidelines fairly strictly.

**Comment by roundhill** [comment]
@jasmussen Did you try out a circular version, or did it not jive?

**Comment by jasmussen** [comment]
> @jasmussen Did you try out a circular version, or did it not jive?

I did try out a circular version. It got weird since it's a circle in a circle, and the innermost circle is the logo.  The innermost circle would have to be scaled up, like it is on the old icon, so that the logo is actually the blue part not the white part. Which is possible, but just didn't feel material.

On the other hand, with the "round rect" material card standard Lollipop has introduced, we have an opportunity to standardize icons between iOS and Android, which jived with the other designers. 

I can give it another shot if you like?

**Comment by roundhill** [comment]
It's all good, just curious. I like the square version. Looks nice with the Simplenote icon as well :)

**Comment by folletto** [comment]
:+1:

**Comment by hugobaeta** [comment]
I still find the W a tad too small, compared to the old icon it goes unnoticed in the middle of the other apps. But I agree that it definitely feels much more modern and in sync with what the OS is doing. What I think makes the Material design icons stand out is those block shadows, did you try something similar?

**Comment by jasmussen** [comment]
> What I think makes the Material design icons stand out is those block shadows, did you try something similar?

I did try a longshadow, but that made it feel extremely Googley, farther than we even need to go to fulfill the guidelines for icons. Besides, I'd feel better with the longshadow also on the iOS icon for consistency, and it would feel off there.

**Pull request merged**
