### PR TITLE
Jetpack focus: Display feature specific overlays for phase 2 and 3

### LINKED ISSUE #17548: Jetpack Focus: Display feature specific overlays for Phase 2 and 3
Display feature-specific overlays across the app

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

Tasks
- [x] Phase Two
- [x] Phase Three

### PR DESCRIPTION
**Pull request by AjeshRPai**
Closes #17548

## Changes 
This PR adds logic for showing the Feature specific overlay on Jetpack removal phases 2 and 3. 

The changes in PR 
- Adds the UI components for Phase 2 and Phase 3
- Adds the logic of showing Phase 2 and Phase 3 overlays depending on the Current phase 
- Adds the logic of tracking the click-on migration info text 
- Fixes the Secondary button text colour on dark mode to be white instead of jetpack green 

###  To note

⚠️ The logic to determine the frequency at which the overlay is shown is commented out with this [commit](https://github.com/wordpress-mobile/WordPress-Android/pull/17580/commits/d2494e8627e86d9ea653517c1f38c1885060d51e) for testing purposes, also the frequency logic is already tested, and there are no changes in this PR to the frequency logic. So no need to re-test the frequency logic as well 

⚠️ The remote field flags needed for Jetpack feature removal were added in this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17667), the logic of fetching the remote field flags are tested using Unit tests in the above-mentioned PR. 

The changes between Phase 2 and Phase 3 Overlays in design other than content, as per Project specs, is 

| Component | Phase 2 overlay | Phase 3 overlay| 
|---|---|---|
| Close button | visible  |  Hidden |  
| Text "Switching is free and only takes a minute" | Hidden | Visible |  

### 📷 Screenshots 

|Page| Phase 2 - Light Mode  | Phase 2 - Dark Mode | Phase 3- Light Mode | Phase 3- Dark Mode |
|---|---|---|---|---|
|Notifications|day_phase2_notifications|night_phase2_notifications|day_phase3_notifications|night_phase3_notifications| 
|Reader| day_phase2_reader  | night_phase2_reader| day_phase3_reader|night_phase3_reader|
| Stats  | day_phase2_stats  | night_phase2_stats  | day_phase3_stats  | night_phase3_stats  |

### Phase Two overlay is shown as expected 

- Open the app
- Make sure that only the "jp_removal_two" flag is enabled from the debug settings
- Navigate to stats
- Make sure the overlay is displayed with the correct content and matches the design
- Verify that the deadline 
- Click on learn more about migration text  
- Verify that the user is redirected to `jetpack.com`(current value from the BE for the phase two URL)
- Verify that the log contains the tracking information 
- 🔵 Tracked: remove_feature_overlay_link_tapped, Properties: {"phase":"two","source":"stats"}
- On clicking back, verify that the overlay is still shown 
- Turn on dark mode
- Make sure the overlay matches the dark mode design
- Repeat the above steps for Reader and Notifications

### Phase Three overlay 
- Open the app
- Make sure that only the "jp_removal_three" flag is enabled from the debug settings
- Navigate to stats
- Make sure the overlay is displayed with the correct content and matches the design
- Click on learn more about migration text
- Verify that the user is redirected to `jetpack.com`(current value from the BE for the phase two URL)
- Verify that the log contains the tracking information 
- 🔵 Tracked: remove_feature_overlay_link_tapped, Properties: {"phase":"three","source":"stats"}
- On clicking back, verify that the overlay is still shown 
- Turn on dark mode
- Make sure the overlay matches the dark mode design
- Repeat the above steps for Reader and Notifications

### Migration info text is not shown when there is no value for the Blog post link - Needs Code changes in BE/Local env to test 
- Change the value of the `phase-three-blog-post` or `phase-two-blog-post` to empty("") in BE or Change the parameter in `JetpackFeatureOverlayContentBuilder` -> `build` to get the default value of the flag in local which is empty, for eg 
- Screenshot 2022-12-19 at 6 01 14 PM
- Open the app
- Make sure that the "jp_removal_three/jp_removal_two" flag is enabled from the debug settings
- Navigate to stats/reader/notifications
- Make sure the overlay is displayed without the learn more about migration text 

### Caption is shown without deadline  - Needs Code changes in BE/Local env to test 
- Change the value of the `jp_deadline` to empty("") in BE Change the parameter in `JetpackFeatureOverlayContentBuilder` -> `build` to get the default value of the flag in local which is empty
- Open the app
- Make sure that the "jp_removal_three/jp_removal_two" flag is enabled from the debug settings
- Navigate to stats/reader/notifications
- Make sure the overlay is displayed without a deadline date

 ## Merge Instructions 
- [x] Make sure that https://github.com/wordpress-mobile/WordPress-Android/pull/17667 is merged to trunk 
- [x] Revert the commented-out logic to determine the frequency at which the overlay is shown [commit](https://github.com/wordpress-mobile/WordPress-Android/pull/17580/commits/d2494e8627e86d9ea653517c1f38c1885060d51e)
- [x] Wait for CI to pass successfully 
- [x] Merge as normal 

## Regression Notes
1. Potential unintended areas of impact
- Jetpack feature removal overlay is not shown as intended for Phase 1 and Deeplink 
- Jetpack feature removal overlay is not shown as intended for Phase 2 and Phase 3

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual testing 
- Unit tests

3. What automated tests I added (or what prevented me from doing so)
Unit tests 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@AjeshRPai - I started testing with the Phase Two flag enabled, but I the content did not match in the first test. Even in Phase 3 the content I see is not matching what you are showing. I don't see a "date", but "removed from the WordPress app soon". Maybe I am missing something? I won't move forward until I hear back from you - maybe it's a remote config thing and we need those PRs merged first?

**Comment by AjeshRPai** [comment]
Hey @zwarm 

The Phase 2 and 3 overlays were using the remote fields - "jp-deadline", "phase-two-blog-post", and "phase-three-blog-post". Since the remote config values were changed to use the "_" instead of the "-", while you were testing, these values were unavailable in the UI. Hence the behaviour of the UI changes according to the conversations - [show WordPress app soon message if jp_deadline is not available](p1669776652344139-slack-C04564QS0V7), [hide learn more jetpack migration link](p1669870437469189-slack-C04564QS0V7) if "phase_two_blog_post" or "phase_three_blog_post" is not available. 

I have updated this branch with the branch in the [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17667). The phase 2 and phase 3 overlays should work as expected. But it would also be good to test the scenario in which the "jp_deadline", "phase_two_blog_post", and "phase_three_blog_post" is unavailable or empty. I have added those test scenarios in the PR description. Please have a look at it.

**Comment by zwarm** [comment]
@AjeshRPai  - I have retested with this PR with your updates; however I am still not seeing the "date" and "blog url" values propagating in the overlay. Let's sync and see if we can sort out why.

**Comment by AjeshRPai** [comment]
@zwarm 👋🏼 

I could not find any issue with the logic of displaying the overlay. However, I have updated the content builder logic and added some unit tests to ensure everything works as expected. So please have a look at the PR again.

**Review by zwarm — CHANGES_REQUESTED** [review]
@AjeshRPai  - Thanks for the changes. I now see the URL and the deadline date in the overlays. 👍

I tested the following:
Phase two: light/dark, LTR/RTL, close button, url tap, tracks
Phase three: light/dark, LTR/RTL, no close button, url tap, tracks

I found two issues (Pixel 5 Android 13) that need to be addressed.

Issue 1:
- Follow the test instructions to launch the overlay
- Tap the “learn more at jetpack.com url”
- Internal browser launches
- Tap the “home back arrow” 
- The URL refreshes and the user can not return to the app.
❓ Can we use an external browser here or is the requirement for an internal browser?

Issue 2:

- Follow the test instructions to launch the overlay
- Tap “Switch to the new Jetpack App”
- Google play launches
- Tap the “back arrow” - which will take you back one place in the google play store
- Swipe between apps to bring back WP. See video 

https://user-images.githubusercontent.com/506707/210382848-c7d2aab6-f204-432e-b52a-36379b0f7923.mp4


- Notice that WP returns from background and pushes the user back to the play store. The only way to clear this is to swipe close the app. 

I am not going to approve the PR; however if you want to address these as separate issues then re-request my review and link the new GH issues here and I'll approve. (Plus I think you may need to uncomment some code before committing, so I will leave the merge for you) Thanks.

**Review by zwarm — APPROVED** [review]
@AjeshRPai - Woot woot, all is working now. Thank you for addressing the issues so quickly. 🚢

**Pull request merged**
