### PR TITLE
Issue/media browser state

### LINKED ISSUE #4603: Media library status text is hard to read
When uploading something via the Media section in the Android app, the “uploading”, “queued”, and “retry” text (on failed uploads) is a bit hard to read.

The tap target for “retry” seems very small (and it’s not obvious that it is tappable since it looks the same as the other states).

per @mjangda 

wp-1474696695627

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4603 - as referenced in #5337, simplifies and improves how upload state is displayed in the media browser, including using a translucent background so the upload state TextView is readable regardless of the colors in the image behind it.

This is how failed images used to appear:
failed-before

This is how they appear in this PR:
failed-after

### CODE REVIEW

**Comment by nbradbury** [comment]
Note: A simple way to test this is to set the `state` variable before [this line](https://github.com/wordpress-mobile/WordPress-Android/pull/5391/files#diff-3906473d772ee9020fb6f298bbf5f5a4R173). For example, `state = MediaUploadState.UPLOADING.name();`

**Comment by daniloercoli** [comment]
Hey @nbradbury - It seems that the picture is not visible during upload: https://cloudup.com/cgiQkRQfQVx

Also, the "re-ordering" of pictures when the upload ends is kind of annoying. Any change we can get rid of it with a quick patch?

**Comment by daniloercoli** [comment]
^^^ Experienced in Android 7.1.1. Android 5.0.1 is fine.

**Comment by daniloercoli** [comment]
@nbradbury I'm still seeing the gray background on uploading for some picture on Android 7.1.1. 
Could it be a memory issue when decoding the bitmap and adding it to the screen? Just guessing, since I moved the same pictures on another device and the issue is not there.

Anyway, I found other problems when testing this PR, not sure they're related to this PR, probably not, so feel free to open a new issue for `release/7.0`. See the video :) https://cloudup.com/chmMbyYDjKR 
In the video you can see the missing picture issue, and the new one, where the preview of the uploading picture changes without a valid reason while scrolling. The gasoline pump was a picture I uploaded yesterday.

**Comment by nbradbury** [comment]
@daniloercoli I looked into this a bit, and the problem with the wrong image and gray image appears to be due to an issue with `loadLocalImage()`, which fails to receive any callback that the image can be shown. That bug has been around for a while, so I'd like to tackle it in a separate PR.

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
