### PR TITLE
Fix #5171: Disable plans and themes for Jetpack sites

### LINKED ISSUE #5171: FluxC: Disable Plans and Themes for Jetpack sites
We can fix them (Jetpack plans API needs some love) and re-enable after we finished the first step integration.

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5171, temporarily disabling the 'Plan' and 'Themes' options from the 'My Site' list for Jetpack sites.

Update: The `plans` endpoint now returns WordPress.com plans for Automated Transfer sites, so AT sites are still able to use the `Plan` option.

~Automated Transfer sites still return Jetpack plans from the API (rather than WP.com plans), so we still need to disable plans for them. However, having the 'Plan' item just disappear after AT seemed a bit jarring, so I opted to keep it (along with the 'Business' label), but make it unclickable:~

at-with-plan-row

~If this it too weird I can revert that change.~

Issues for reinstating Plans and Themes for Jetpack sites: https://github.com/wordpress-mobile/WordPress-Android/issues/5121 & https://github.com/wordpress-mobile/WordPress-Android/issues/5122.

### CODE REVIEW

**Comment by rachelmcr** [comment]
>I opted to keep it (along with the 'Business' label), but make it unclickable

That feels reasonable. Not sure if users will be confused by the change in behavior, but we can keep an eye on user feedback after launch.

Another option could be to make it an external link to the site's Plans page on the web.

**Comment by aforcier** [comment]
> That feels reasonable. Not sure if users will be confused by the change in behavior, but we can keep an eye on user feedback after launch.

Hopefully the endpoint will be updated soon-ish and we'll be able to fix this for AT sites before FluxC is in beta. 🤞

> Another option could be to make it an external link to the site's Plans page on the web.

I'm not sure about this, but I think there was an issue with doing that due to app store policies.

**Comment by nbradbury** [comment]
This seems strange to me. Having plans visible but un-clickable seems more confusing/jarring to me than hiding it. I'd be surprised if many users noticed the missing "Plans" item, but if it's there they may click on it and wonder why it's not doing anything.

**Comment by aforcier** [comment]
> This seems strange to me. Having plans visible but un-clickable seems more confusing/jarring to me than hiding it. I'd be surprised if many users noticed the missing "Plans" item, but if it's there they may click on it and wonder why it's not doing anything.

I can see that point of view too - I can revert it.

**Comment by nbradbury** [comment]
> I can see that point of view too - I can revert it.

That would be my choice, but feel free to get other opinions.

**Comment by aforcier** [comment]
> That would be my choice, but feel free to get other opinions.

It actually looks like the plans endpoint for AT sites might get fixed soon - if it's okay with you let's wait a day or two and see what comes of that, this might be completely moot.

**Comment by aforcier** [comment]
The server-side patch has landed - the `plans` endpoint now returns WordPress.com plans for AT sites. I've made the Plans item clickable for AT sites as of 4b23d60.

Ready for another pass @nbradbury!

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
