### PR TITLE
Better handling of rotation

### LINKED ISSUE #4062: Gravatar: App crashes if device is rotated while new Gravatar is loading on me screen
### Expected behavior

After adding a new Gravatar, the user should be able to rotate the device between portrait and landscape.

### Actual behavior

After adding a new Gravatar, if the new Gravatar image is still loading on the Me screen, the app crashes.

This is especially noticeable if you were using the app in landscape prior to adding a new Gravatar. The Edit Photo screen forces a portrait view, so the next possible opportunity to rotate back to landscape (to continue using the app that way) is when the new Gravatar is loading on the Me screen.

### Steps to reproduce the behavior

1. Tap on Gravatar on Me screen
2. Select and edit photo
3. On Edit Photo screen, select OK
4. While new Gravatar is loading, rotate device from portrait to landscape

Result: App crashes if the new Gravatar hasn't finished loading on the Me screen.

### Screenshot

This is the point (while the new Gravatar is loading) where the app will crash if you rotate it:

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-8.

### PR DESCRIPTION
**Pull request by hypest**
Fixes #4062 

By the time the two async operations complete (Gravatar upload, reloading the image) the Fragment can be a new instance if rotation has happened in the meantime. So, have the callbacks send messages (EventBus) so the new Fragments can catch them.

While at it, keep the progress bar state on rotation.

To test:
1. Tap on Gravatar on Me screen
2. Select and edit photo
3. On Edit Photo screen, select OK
4. While new Gravatar is loading, rotate device from portrait to landscape
5 Progress bar should continue to show, until the operation finishes and the new image is displayed

Needs review: Hey @nbradbury , wanna take this on? We can reassign if too busy. Cheers!

### CODE REVIEW

**Comment by nbradbury** [comment]
> Hey @nbradbury , wanna take this on?

Sure thing, I'll start the review shortly.

**Comment by nbradbury** [comment]
Unrelated to this PR, I noticed that the gravatar is being loaded twice when the fragment is created (or recreated). This is because `refreshAccountDetails()` is called in both `onCreateView` and `onResume`. We should be able to drop it from `onCreateView`.

**Comment by nbradbury** [comment]
Looks good and works well :shipit:

**Comment by maxme** [comment]
This wasn't merged in the release/5.4 branch so the bug happens in 5.4, I'll cherry pick it in hotfix/5.4.1

**Pull request merged**
