### PR TITLE
[Compile Warnings As Errors] WordPress Module - Resolve Coroutines Warnings

### LINKED ISSUE #17181: Compiler Warnings as Errors - WordPress Module
Parent #17173

This issue is about resolving/suppressing the compile warnings for the `WordPress` app module.

Number of Warnings: `621`
    - Main Source: `481`
    - Debug Source: `2`
    - WordPress Source: `5`
    - Jetpack Source: `4`
    - Test Source: `128`
    - UI Test Source: `1`

- [x] Resolve/Suppress all warnings.
    - [x] Main Source (`481`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`6`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`3`)
            2. 'XYZ' is deprecated. Implement CoroutineScope interface and cancel all child coroutines in xyz (`2`)
            3. @Synchronized annotation is not applicable to suspend functions and lambdas (`1`) (with [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/10878#issuecomment-1258130096), cc @malinajirka)
        - [x] Resolve/Suppress `Deprecated` related warnings (`365`). @ParaskP7
            - [x] Specific
                1. `PreferenceManager` related warnings. @ParaskP7 #17215
                2. `LifecycleEvent` related warnings. @ParaskP7 #17223
            - [x] Generic 
                1. 'XYX' is deprecated. Deprecated in Java (`247` minus `Specific` above) @ParaskP7 #17246
                3. 'Xyz' is deprecated. Overrides deprecated member in 'xyz'. Deprecated in Java (`5`) @ParaskP7 #17287
                4. 'xyz' is deprecated. Use xyz instead. (`24`) @ParaskP7 #17287
                5. 'Xyz' is deprecated. This should be removed once we start receiving Xyz the source block from the backend (`2`) @ParaskP7 #17287
                6. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`87`) @ParaskP7 #17287
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`75`). @ParaskP7 #17291
            - Type (`44`)
                1. Unsafe use of a nullable receiver of type Xyz? (`4`)
                2. Type mismatch: inferred type is Xyz? but Xyz was expected (`13`)
                3. Elvis operator (?:) always returns the left operand of non-nullable type Xyz (`4`)
                4. The corresponding parameter in the supertype 'Xyz' is named 'xyz'. This may cause problems when calling this function with named arguments. (`4`)
                5. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`1`)
                7. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`18`)
            - Cast (`5`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`1`)
            - When (`26`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`26`)
        - [x] Resolve/Suppress `Other` related warnings (`35`). @ParaskP7 #17293
            1. This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API. (`1`)
            2. Parameter 'xyz' is never used (`17`)
            3. Parameter 'xyz' is never used, could be renamed to _ (`9`)
            4. Name shadowed: xyz (`2`)
            5. Parcelize annotations from package 'kotlinx.android.parcel' are deprecated. Change package to 'kotlinx.parcelize' (`1`)
            6. Variable 'xyz' initializer is redundant (`1`)
            8. There is more than one label with such a name in this scope (`1`)
            9. Condition 'xyz' is always 'xyz' (`2`)
            10. Unreachable code (`1`)
    - [x] Debug/WordPress/Jetpack Source (`11`) @ParaskP7
        - [x] Resolve/Suppress `Deprecated` related warnings (`11`). @ParaskP7 #17287
            1. 'Xyz' is deprecated. Deprecated in Java (`11`)
    - [x] Test/UI Test Source (`129`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`11`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`8`)
            2. 'Xyz' is deprecated. Deprecated in the favour of 'xyz'. Please note that the provided replacement does not rethrow channel's close cause as 'poll' did, for the precise replacement please refer to the 'poll' documentation (`3`)
        - [x] Resolve/Suppress `Deprecated` related warnings (`80`). @ParaskP7 #17300
            1. 'XYX' is deprecated. Deprecated in Java (`58`)
            2. 'xyz' is deprecated. Use xyz instead. (`2`)
            3. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`20`)
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`15`). @ParaskP7 #17300
            - Type (`8`)
                1. Type mismatch: inferred type is Xyz? but Xyz was expected (`3`)
                2. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`4`)
                3. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`1`)
            - Cast (`6`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`2`)
            - When (`1`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`1`)
        - [x] Resolve/Suppress `Other/Test/UI Test` related warnings (`23`). @ParaskP7 #17300
            - Other (`5`)
                1. Parameter 'xyz' is never used (`5`)
            - Test (`17`)
                1. Check for instance is always 'xyz' (`2`)
                2. Name contains characters which can cause problems on Windows: " (`15`)
            - UI Test (`1`)
                1. Name shadowed: fileName (`1`)
- [x] Enable all warnings as errors flag. @ParaskP7 #17318

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent: #17173
Partially Closes: #17181

This PR resolves all `Coroutines` related warnings for the `WordPress` module:

- Main Source:
    - 3 warnings x `This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'`
    - 2 warnings x `'XYZ' is deprecated. Implement CoroutineScope interface and cancel all child coroutines in xyz`
    - 1 warning x `@Synchronized annotation is not applicable to suspend functions and lambdas` + Question [❓]: [see comment](https://github.com/wordpress-mobile/WordPress-Android/pull/10878#issuecomment-1258130096) @malinajirka
- Test Source:
    - 8 warnings x `This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'`
    - 3 warnings x `'Xyz' is deprecated. Deprecated in the favour of 'xyz'. Please note that the provided replacement does not rethrow channel's close cause as 'poll' did, for the precise replacement please refer to the 'poll' documentation`

-----

Warnings Resolution List:

1. [Resolve opt-in experimental coroutines api warnings.](https://github.com/wordpress-mobile/WordPress-Android/commit/0ab8933e765fdc567f82912f8fd55f63eeab2b93)
2. [Resolve deprecated coroutines thread module scope warnings.](https://github.com/wordpress-mobile/WordPress-Android/commit/ea825920691bfdd973deb192375d421055280766)
3. [Resolve opt-in experimental coroutines api warnings for tests.](https://github.com/wordpress-mobile/WordPress-Android/commit/e6471d4cf17c5763aa15f606f71270589705c031)
4. [Resolve deprecated coroutines channel poll warnings for tests.](https://github.com/wordpress-mobile/WordPress-Android/commit/fc6e457377bd4bb79a8b8fe429563accd421c944)

Warnings Suppression List:

1. [Suppress synchronized on suspend coroutines warning.](https://github.com/wordpress-mobile/WordPress-Android/commit/175f0e364cf4b923a64c7cf036ae75a244924c9e)

Refactor List:

1. [Move ui dispatcher down to group scope and dispatcher funs.](https://github.com/wordpress-mobile/WordPress-Android/commit/d1f74fdd436d65e41fab3a77bebc298c3503536d)
2. [Rename provide background to bg dispatcher.](https://github.com/wordpress-mobile/WordPress-Android/commit/e03d208247c7487a7497f873d91f6b0e52a3622e)
3. [Reorder and add experimental coroutines api on top of test suites.](https://github.com/wordpress-mobile/WordPress-Android/commit/d2f4ca2e317c6b033383aa1aa82d297f93127451)
4. [Remove unnecessary experimental coroutines api annotation.](https://github.com/wordpress-mobile/WordPress-Android/commit/2fd0fc8fc1c1a71c01b0256d0618d187dcbd8916)

Documentation List:

1. [Add scope, dispatcher and other group sections to thread module.](https://github.com/wordpress-mobile/WordPress-Android/commit/e3242a543ba60786a01ec9bd1ac885b4e9cfc72c)

-----

PS: @AjeshRPai I added you as the main reviewer, that is, in addition to @wordpress-mobile/apps-infrastructure team itself, but randomly, since I want someone from the `WordPress Android` team to primarily sign-off on that change. 🥇

FYI: I am going to randomly add more of you in those PRs that will follow, just so you become more aware of this change and how close we are on enabling `allWarningsAsErrors` by default everywhere. 🎉

-----

To test:

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough.
- However, if you want to be thorough about reviewing this change, you could quickly smoke test both, the `WordPress` and `Jetpack` apps, and see if they are both working as expected.

PS: Also note the additional testing instructions as specified in this comment [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17210#issuecomment-1259265799).

-----

## Regression Notes

1. Potential unintended areas of impact

N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

FYI: After talking to Jirka about this comment I left for him [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10878#issuecomment-1258130096), I decided to go ahead and resolve this `@Synchronized annotation` related warning after all, that is, instead of suppressing it like I did (see [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17210/commits/175f0e364cf4b923a64c7cf036ae75a244924c9e)).

As such, I added an additional label to this PR, the `[Status] Not Ready For Merge` label. However, feel free to proceed with the code review as you would have anyway, don't let this stop you from reviewing the overall solution here.

Then, and when I'll have my finally solution to this problem ready (probably tomorrow), I'll push it here and inform you about the change so you can take a final look at it (plus test it). 🧑‍🏭

**Comment by ParaskP7** [comment]
👋 @AjeshRPai @malinajirka !

FYI: This is now done, I have resolved the `@Synchronized annotation` related warning by reverting the previous (d5b994850d80de50edbcf3c8237aa9daf3ffedd0) commit via this new commit here (43949f11e88fe29b3710a7812f6c1e03fc18f2fc). I have also tested this, both, the before and after the change, by following the instructions in this PR [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10877/), everything worked as expected. For your convenience, I am copy-pasting the testing instructions here as well:

```
To test:
I don't have a Samsung phone running Android 5. But we should at least
verify it still works as expected on other phones.

1. Turn off the internet connection
2. Create a post
3. Publish it
4. Turn on internet connection + pull to refresh
5. Make sure the post gets uploaded
```

PS: You will find more info about the reasoning behind this change, along with a couple associated links, within the commit message itself.

**Review by AjeshRPai — APPROVED** [review]
Thanks for providing me with all the details for the review in commit messages as well as in the description. As always, it’s a pleasure to review your PR since I will get the context of the change/links of the references in your PR description and commit messages themselves. 🙌

I have 
- tested the PR by going through the changes in every commit and reading the reference links mentioned in the commit messages and everything LGTM 👍🏼 
- done a smoke testing of the WordPress and jetpack app and everything looks fine 👍🏼 
- tested the synchronized to mutex changes. Published a post on offline mode with the following steps. It works as expected 🟢 👍🏼 
```
1. Turn off the internet connection
2. Create a post
3. Publish it
4. Turn on internet connection + pull to refresh
5. Make sure the post gets uploaded
```


Am going to approve but not merge the PR so that anyone from @wordpress-mobile/apps-infrastructure or @jirka can have a look. Please feel free to merge the PR at your convenience. Nice work 🙌🏼

**Comment by ParaskP7** [comment]
Thank you so much for reviewing and testing this @AjeshRPai , you are awesome! 🙇 

> Am going to approve but not merge the PR so that anyone from https://github.com/orgs/wordpress-mobile/teams/apps-infrastructure or @Jirka can have a look. Please feel free to merge the PR at your convenience. Nice work 🙌🏼

This sounds like a good plan! 🙏

PS: As always, I am humbled by your kind words, thank you! 😊

**Comment by ParaskP7** [comment]
👋 @malinajirka !

> Am going to approve but not merge the PR so that anyone from https://github.com/orgs/wordpress-mobile/teams/apps-infrastructure or @Jirka can have a look. Please feel free to merge the PR at your convenience. Nice work 🙌🏼

Any last thoughts on it before I go merging this to `trunk`. PS: Thanks a lot for your help? 🙏

**Comment by malinajirka** [comment]
I haven't tested it but the changes LGTM! ⭐

**Comment by ParaskP7** [comment]
Coolio, thank you for the confirmation @malinajirka , that's all I needed! 🙇

**Pull request merged**
