### PR TITLE
Update/ci tools release branch

### PR DESCRIPTION
**Pull request by JavonDavis**
See https://github.com/wordpress-mobile/WordPress-Android/pull/14494

Replaying changes onto the release branch

### CODE REVIEW

**Comment by jkmassel** [comment]
I presume the test for this is that you can cut a new beta? :)

**Review by AliSoftware — APPROVED** [review]
Looking good 👍 :shipit: 

Let's merge this and test it right away with the beta you planned to do.

**Comment by JavonDavis** [comment]
> I presume the test for this is that you can cut a new beta? :) 

Yep @jkmassel 🙂

**Comment by AliSoftware** [comment]
> I presume the test for this is that you can cut a new beta? :)

@jkmassel Yep. I tested that the same changes that were done in #14494 worked – by triggering a Release Build in that PR's branch – and (apart from a glitch due to my temporary change in order to limit side effects during the testing of the PR) it seemed to work as expected.

So the next step was to report the changes from #14494 on the release branch – this PR – then actually do a new beta – coincidentally, we needed a new beta anyway – and if all works as expected in the real test here, finally merge #14494.

**Pull request merged**
