### PR TITLE
Updates: the tab bar icons and styling

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #

### Updates the icons in bottom bar nav in JP/WP app

| Dark  | Light Mode | 
|---|---|
| Screenshot 2024-01-03 at 3 51 14 PM  | Screenshot 2024-01-03 at 3 51 00 PM  |   

### Sets the me icon to B&W or with color depending on the selected state 
[me_icon_tint.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/a24b6e0e-7a8f-47dc-976f-8b44a08aa647)

### Adds a pop animation to the bottom nav icon on selecting 

Note: please ignore the badge position on notification icon. It has been moved to left of the icon as before

[Screen_recording_20240103_232835.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/3a022c9d-485e-4f35-a277-c473b846fb30)

## To Test:
- Login to the JP/WP app 
- Go to the dashboard 
- Verify that the icons on the bottom bar as in the design P4DK0f5zK8F3Y1eifGqS39-fi-3:12381
- Verify new tab icons adapt to environment (light vs dark)
- Verify the icons animate when switching tabs
- Verify the me icon gets blacked out when not selected
- Verify notification icon shows the correct badge color when there are unread notifications (blue for WP, green for JP)

## Regression Notes

1. Potential unintended areas of impact
Bottom bar icons are not correct

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)
N/A
  
PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by AjeshRPai** [comment]
cc: @zwarm Pinging you so that you are aware of this change

**Comment by AjeshRPai** [comment]
Hey @zwarm 

I am adding you as a reviewer since Chris is not available for the review. The IOS PR for these changes is https://github.com/wordpress-mobile/WordPress-iOS/pull/22325

The haptics for the nav bar items were already in a past PR.

**Review by zwarm — CHANGES_REQUESTED** [review]
@AjeshRPai - I've tested the following
✅ Verify that the icons on the bottom bar as in the design 
✅ Verify new tab icons adapt to environment (light vs dark)
🟡 Verify the icons animate when switching tabs
✅ Verify the me icon gets blacked out when not selected
✅ Verify notification icon shows the correct badge color when there are unread notifications (blue for WP, green for JP) - I had to turn notifications on to see the badge.

🟡 Verify the icons animate when switching tabs 
- Technically it works; however it doesn't feel clean - sometimes the animation takes too long and the icon completely disappears. And sometimes in dark mode you don't see the animation at all. See my attached video. Pixel 5 Android 14

I am going to leave this PR in request changes status to give you a chance to respond. If this is the expected behavior, then I will go ahead and approve the PR. lmk. Thanks

https://github.com/wordpress-mobile/WordPress-Android/assets/506707/8b96b471-9b77-4feb-8b6c-f676efe23e03

**Review by zwarm — APPROVED** [review]
After syncing with @AjeshRPai , this PR will be merged and we'll take up any minor issues during beta week.

**Pull request merged**
