### PR TITLE
[Tooling] Draft: Upload app metrics

### PR DESCRIPTION
**Pull request by AliSoftware**
🚧  This is WIP to test the new App Size Metrics API and fastlane action implemented in https://github.com/wordpress-mobile/release-toolkit/pull/364

Internal Reference: paaHJt-3od-p2

### CODE REVIEW

**Comment by AliSoftware** [comment]
Rats: WPAndroid is still using CircleCi and its `.circleci/config.yml` for the Installable Builds, and there [Installable Builds are built directly using `gradlew assembleWordpress<Flavor><Type> -PinstallableBuildVersionName=…`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/.circleci/config.yml#L59-L64)… — as opposed to using [`fastlane build_and_upload_release`](https://github.com/wordpress-mobile/WordPress-Android/blob/tooling/app-size-metrics/fastlane/lanes/build.rb#L17-L46), [`fastlane build_alpha`](https://github.com/wordpress-mobile/WordPress-Android/blob/tooling/app-size-metrics/fastlane/lanes/build.rb#L89-L113), [`fastlane build_beta`](https://github.com/wordpress-mobile/WordPress-Android/blob/tooling/app-size-metrics/fastlane/lanes/build.rb#L129-L153) and [`fastlane build_internal`](https://github.com/wordpress-mobile/WordPress-Android/blob/tooling/app-size-metrics/fastlane/lanes/build.rb#L169-L193) like I thought it would 😔

In practice CircleCI only calls those `fastlane build_*` lanes [during the "Release Build" workflow](https://github.com/wordpress-mobile/WordPress-Android/blob/tooling/app-size-metrics/.circleci/config.yml#L114-L138)…

So in its current state my demo here won't work on Installable Builds, only on Alpha, Beta and Final Releases.

**Comment by AliSoftware** [comment]
> So in its current state my demo here won't work on Installable Builds, only on Alpha, Beta and Final Releases.

This has now been fixed:
 - https://github.com/wordpress-mobile/release-toolkit/pull/365 added support for the `android_send_app_size_metrics` to use a "Universal APK" as the input file as well (instead of an `.aab`)
 - This PR is now pointing to that new branch of the releae-toolkit and uses that new option to pass to the action the "Universal APK" produced by `./gradlew assembleWordPressJalapenoDebug` during "Installable Build" jobs on PRs.

With that new change, you can see that [the payload for both WordPress and Jetpack app metrics have been properly generated and saved as artifacts for the CI](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/31475/workflows/e7f74f3f-4dcc-4cad-b217-ccead5ea8d94/jobs/124137/artifacts) (until we get a proper runnin Metrics server to send them to).

**Comment by AliSoftware** [comment]
Note: this PR Draft was initially created to test that the new `android_send_app_size_metrics` from https://github.com/wordpress-mobile/release-toolkit/pull/364 + https://github.com/wordpress-mobile/release-toolkit/pull/365 worked as expected in client repos with actual APKs and AABs.

But I'm not yet sure we'd really want to send app size metrics for every Installable Build like what this Demo PR does here — and thus size data for "Universal APKs" — in practice once the Metrics server goes live (as opposed to limit it to only send data for betas and final builds, and thus size data for `.aab` files, but not "Universal APKs"). Cc @jkmassel thoughts?

 - On one end that would make a lot of data, probably too much given how many PRs we have and that each PR can generate an Installable Build multiple times (on each new commit being pushed)
 - On the other end, better have more data and filter it out, rather than less data and regretting not having it later…

**Comment by mokagio** [comment]
My two cents on whether to send app size data for every Installable Build is that we should not do it just yet. Alongside @AliSoftware  legitimate questions about having too much data, there's also the fact that we are just starting out with this project. It seems wise to start small and add the extra information later on.

And while it's true that it's better to have more data and filter it out than to not have it and regret it, I think that applies more for analytics that can allow to understand user behavior (where more details give better insight) or in an even sourcing service (where you might want to replay the whole collection of events through a more advanced ML model in the future). In our case, we're talking about how the app size varies between commits on a feature branch. I think we can live with less granularity in this instance.

**Pull request closed without merging**
