### PR TITLE
Drop Open Sans (Part 1)

### PR DESCRIPTION
**Pull request by nbradbury**
This is the first of two PRs to drop Open Sans (see #3792). After this is merged, [the editor](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/281) needs to be updated to stop using Open Sans, and then I'll submit another PR which:

* Removes the openSans fontFamily from attrs.xml
* Removes the "light" fontVariation from attrs.xml
* Removes the actual font assets

Note that we can drop the "light" fontVariation since it's not supported for Merriweather, and this PR changes the previous uses of the light variation to "sans-serif-light" ([reference](http://developer.android.com/about/versions/android-4.1.html#Fonts))

### CODE REVIEW

**Comment by maxme** [comment]
> Note that we can drop the "light" fontVariation since it's not supported for Merriweather,

"As of now there are 4 styles: Regular, Light, Bold, and Black. " - https://www.google.com/fonts/specimen/Merriweather - but since we're not using it, I think we shouldn't add the light version of it.

Note that I also noticed on this page: "Updated in January 2016: A deep refresh of the design that makes all upright or roman styles darker" - We should probably update with the newest ttf files.

IMO, we should keep the light variation for the default font, in case we need it in a future version. We might want to add a warning log (`Merriweather light not supported`) if Merriweather + Light are selected.

> Removes the openSans fontFamily from attrs.xml
> Removes the actual font assets

Can you do this in this PR? The editor was only using css to setup OpenSans and it also packages OpenSans in its `assets/` folder.

**Comment by mattmiklic** [comment]
> IMO, we should keep the light variation for the default font, in case we need it in a future version. We might want to add a warning log (Merriweather light not supported) if Merriweather + Light are selected.

No changes needed for Merriweather -- the updated version is the one we've opted not to use in Calypso and the apps. We don't use the light weight by design (see: https://wordpress.com/design-handbook/typography/).

**Comment by maxme** [comment]
> No changes needed for Merriweather -- the updated version is the one we've opted not to use in Calypso and the apps.

:ok_hand: 

> We don't use the light weight by design (see: https://wordpress.com/design-handbook/typography/).

Ok, so the light weight could be used with Roboto but not with Merriweather, better to keep the light variation in `WPEditText` then.

**Comment by maxme** [comment]
Editor PR: https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/304

**Comment by nbradbury** [comment]
> so the light weight could be used with Roboto but not with Merriweather, better to keep the light variation in WPEditText then

This is now done via `android:fontFamily="sans-serif-light"` ([explanation here](http://developer.android.com/about/versions/android-4.1.html#Fonts)). So, since the "light" variation is unused for Merriweather, and isn't necessary for Roboto since it has built-in support, we can drop our custom attribute.

**Comment by maxme** [comment]
> This is now done via android:fontFamily="sans-serif-light" (explanation here). So, since the "light" variation is unused for Merriweather, and isn't necessary for Roboto since it has built-in support, we can drop our custom attribute.

:ok_hand:

**Comment by nbradbury** [comment]
> We now have 2 WPEditText, one in org.wordpress.android.widgets and one in org.wordpress.android.utli.widgets - the old one was used in the Legacy Editor.
> 
> We should probably rename the old one, and move the new one to Utils

I'm not sure about moving the new one to Utils since `org.wordpress.android.widgets` is where similar custom views reside. Would it work if I just left this new one where it is, and renamed the Utils one to `WPLegacyEditText` (with a comment header stating that it's solely for use in the legacy editor)?

**Comment by maxme** [comment]
`WPEditText` could be used by another library. I can't think of any library that needs merriweather currently (The editor for sure but it uses a Webview so it doesn't need any `WPEditText`).

I'm OK moving it to `org.wordpress.android.widgets`, if a future library needs it, it's pretty easy to move it to wputils.

**Comment by nbradbury** [comment]
> I'm OK moving it to org.wordpress.android.widgets, if a future library needs it, it's pretty easy to move it to wputils.

@maxime I'm confused by that reply. The existing (renamed) WPEditText is already in `org.wordpress.android.widgets`. The other one, which is used solely by the legacy editor, is in `org.wordpress.android.util.widgets`. Are you suggesting we move the legacy WPEditText to `org.wordpress.android.widgets` (and rename it)?

**Comment by maxme** [comment]
> Update: I suspect we're over-thinking this :) Perhaps the simplest solution is to mark the legacy WPEditText as @Deprecated, add a comment header explaining why it's deprecated, and be done with it.

:+1: - we won't use the Legacy WPEditText

**Comment by nbradbury** [comment]
Done in 3058f23.

**Comment by maxme** [comment]
:shipit:

**Comment by maxme** [comment]
Note: I pulled the editor subtree in `develop`, includes the changes from https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/304

**Pull request merged**
