### PR TITLE
fixed database cursor leaks

### PR DESCRIPTION
**Pull request by andrew659**
Dear developers,

I propose some fixes to issue #4591 

@rachelmcr Please let me know if there are any problems. Thanks.

### CODE REVIEW

**Comment by nbradbury** [comment]
Hey Andrew, thanks for contributing these fixes! Your changes look good, but if I can make a suggestion, you could simplify things by using <a href="https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/src/main/java/org/wordpress/android/util/SqlUtils.java#L36">SqlUtils.closeCursor()</a>.

**Comment by maxme** [comment]
Hi @andrew659 - any news on this?

**Comment by andrew659** [comment]
@nbradbury Nick's suggestion sounds good. 

@maxme Would you like me to submit another pull request? I am happy to help :)

**Comment by maxme** [comment]
@andrew659 you can update this one by pushing to your `andrew659:develop` branch, you don't have to submit another PR.

**Comment by andrew659** [comment]
@maxme thanks for the suggestion. I updated the PR. Let me know if it's ok.

**Comment by nbradbury** [comment]
Looks good, @andrew659 - thanks for contributing to WordPress for Android!

**Pull request merged**
