### PR TITLE
Add line chart to ValueWithChartViewHolder

### LINKED ISSUE #16494: [android] Stats: Line Graph for Likes and Comments
This graph is required on **Total Likes Card** and **Total Comments card**.  Re-use on all three once it is done

### PR DESCRIPTION
**Pull request by irfano**
Fixes #16494 

This PR adds a line chart for the current week (last 7 days + today) to Total Likes and Total Comments cards.

|Light|Dark|
|-|-|
|||

To test: 
1. Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings).
2. Select Debug Settings.
3. Find StatsRevampV2FeatureConfig under Features in development enable it and restart app.
4. Go to stats either using quick links or menu.
5. Ensure that it opens in Insights tab otherwise switch to Insights tab.
6. If the Total Likes and/or Total comments cards are not present, go to the stats management (either through ⚙️ menu at the top right hand corner or Add new stats card at the bottom) and add cards and save, then return to Insights.
7. Verify that there is a line chart in the Total Likes and Total Comments cards.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ravishanker** [comment]
The line chart is looking great @irfano 

> This PR adds a line chart for the last 15 days to Total Likes and Total Comments cards.

The chart needs to be only this week (last 7 days + today)  not for two weeks (or last 15 days)
Also, shouldn't the color needs to change to blue (whatever was decided) when it is down?

**Comment by irfano** [comment]
> The chart needs to be only this week (last 7 days + today) not for two weeks (or last 15 days)
 
 Oh, yes! We've already discussed that on Slack. I'm fixing it.

**Comment by ravishanker** [comment]
Is that line chart supposed to be in different color when it is negative?  Please check and see if it can updated here or in a separate PR.
Please feel free to merge if you like to handle it in a separate PR or update here and merge

**Review by ravishanker — APPROVED** [review]
LGTM 👍

**Comment by irfano** [comment]
> Is that line chart supposed to be in different color when it is negative? Please check and see if it can updated here or in a separate PR. Please feel free to merge if you like to handle it in a separate PR or update here and merge

Done in 984ac1b2bb65d21f992069ee69555470375af8ba

Green for positive change, blue for negative change.

**Pull request merged**
