### PR TITLE
Feature/logged out reader

### PR DESCRIPTION
**Pull request by nbradbury**
The PR provides a "logged out" Reader experience for when the user has a self-hosted account but hasn't logged into WordPress.com. Instead of being able to follow tags, the user is provided a default set of recommended tags which can't be changed. Follow buttons have been removed, like buttons are disabled, and submitting comments isn't available.

The experience is similar to that on iOS, and down the road we hope to improve upon this so that these features are all available and prompt the user to sign in when accessed.

### CODE REVIEW

**Comment by daniloercoli** [comment]
The footer is empty but still visible in the details screen. Is that on purpose?
screen shot 2015-05-11 at 12 49 46

**Comment by nbradbury** [comment]
Great catch on the footer - it shouldn't be there. I'll fix that shortly.

**Comment by daniloercoli** [comment]
I'm ok with this PR and I'm going to merge it. 

Side note:
I've found a very small issue with the reader toolbar, where it's shown for a fraction of second and then it disappears. It's really hard to replicate the issue though. See the end of the animated GIF attached below (it's a 60 fps screen recored GIF)
reader-toolbar-ui-issue

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
