### PR TITLE
Clarity SDK integration

### PR DESCRIPTION
**Pull request by antonis**
## Description
This PR integrates the [Clarity SDK](https://clarity.microsoft.com/) in the Jetpack app

Internal ref: pcdRpT-52O-p2

-----

## To Test:

-----

## Regression Notes

1. Potential unintended areas of impact

    - TODO

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - TODO

3. What automated tests I added (or what prevented me from doing so)

    - TODO

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by antonis** [comment]
The `buildkite/wordpress-android/jetpack-instrumented-tests` `verifyOnAppComesFromBackgroundCalled` fails with the following stack trace:
```
java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/~~F18fFJLyMCkGGDsplShg0Q==/com.jetpack.android.test-f5eZCo0CHG4S-q3q5_x1LQ==/base.apk)
at com.microsoft.clarity.protomodels.mutationpayload.MutationPayload$DisplayFrame.<clinit>(Unknown Source:9)
at com.microsoft.clarity.protomodels.mutationpayload.MutationPayload$DisplayFrame.newBuilder(Unknown Source:0)
at com.microsoft.clarity.models.display.DisplayFrame.toProtobufInstance(Unknown Source:0)
at com.microsoft.clarity.f.q.b(Unknown Source:5)
at com.microsoft.clarity.f.q$d.invoke(SourceFile:4)
at com.microsoft.clarity.f.q$a.invoke(SourceFile:3)
at com.microsoft.clarity.n.f.a(Unknown Source:5)
at com.microsoft.clarity.n.f.a(Unknown Source:12)
at com.microsoft.clarity.f.q.h(Unknown Source:18)
at com.microsoft.clarity.f.q$$ExternalSyntheticLambda0.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:923)
```

The error occurs [both with Clarity 1.3.3 and the latest 2.0.0](https://central.sonatype.com/artifact/com.microsoft.clarity/clarity/versions).

Note that the test runs:
✅  successfully on my local machine at a Pixel 5  physical device with Android 14
❌  fails on CI at a Pixel 2 (API Level 30)
❌  fails on my local machine at a Pixel 2 emulator (API Level 30)

**Comment by antonis** [comment]
Testing the latest [SDK version 2.1.1](https://central.sonatype.com/artifact/com.microsoft.clarity/clarity/2.1.1)

**Comment by antonis** [comment]
After revisiting the testing issue reported above https://github.com/wordpress-mobile/WordPress-Android/pull/19763#issuecomment-1854189594 I implemented a more proper solution by excluding the conflicting dependency from tests https://github.com/wordpress-mobile/WordPress-Android/pull/19763/commits/82e9ceaf4891e30fa0e7dfc46846b86a26fd1ef1 and removed the emulator check https://github.com/wordpress-mobile/WordPress-Android/pull/19763/commits/1a7afebca066769d61fa14b7f86515eee1513bbf.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by antonis** [comment]
Closing this PR for now as the project is put on-hold

**Pull request closed without merging**
