### PR TITLE
Feature/15426 add domains ctas to next steps on my site

### LINKED ISSUE #15426: [Android] Domains v2: Enhance Call-To-Action on My Site
In order to make the Domains feature more discoverable, we will add a new Call To Action for users that don't have a custom domain yet.

The new Call To Action will be added to the "Next Steps" section (see designs below)

Without Quick Start | With Quick Start
-- | --
 | 

The existing Call to Action that appears when a paid user does not have a domain yet, will be replaced by this new one.
The Domains Action in the Configure Section will remain as it is.

**NOTE: design have slightly changed compared to these screens, and the Domains Call to Action needs to be the first one when Quick Start is shown**

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes #15426 

To test:

- Create a new site
- Enable quick start steps
- Logout and login if required
- Next steps should now show Get your domain or Claim your free domain task

## Regression Notes
1. Potential unintended areas of impact
Next steps

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ravishanker** [comment]
depends on this FluxC [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2154)

**Comment by ravishanker** [comment]
@renanferrari This feature probably still needs to figure out the following, perhaps something for next PR.  I wanted to get your review and pointers on how and where it could be improved.  Thank you.

- Shout it go under feature flag
- Should CTA open domains dashboard or search
- How to handle CTA task complete or not ( or it is not relevant for this, just show claim or get domain based on domain credit)

I've also posted the questions on i5 as well

**Comment by renanferrari** [comment]
I haven't reviewed this, but I left [a comment on the FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2154#pullrequestreview-781066670) explaining why I think we should put this on hold for now, but to reiterate the main problem with this approach is that it adds the domain actions as part of Quick Start, even though we might want to show them when Quick Start isn't active.

That said, here's how I would personally approach the questions you raised:

>Shout it go under feature flag

Yes.

>Should CTA open domains dashboard or search

Probably search, unless we believe the dashboard could add some value to the flow, but I don't think it does in this case.

>How to handle CTA task complete or not ( or it is not relevant for this, just show claim or get domain based on domain credit)

Good question! I also don't have a definitive answer to this, but when credits are available the behavior seems easier to infer: we would hide the card after the credits are redeemed. But what about after that, when no credits are available? I'd think that the card wouldn't be persistent, meaning it would go away at some point. Maybe automatically after a certain time, or maybe after the user enters the Domain Dashboard for the first time, or maybe the user could dismiss it manually... None of this is clear to me yet.

**Comment by ravishanker** [comment]
Closing this one as the designs have changed to evolving existing card.

**Pull request closed without merging**
