### PR TITLE
[DO NOT MERGE] Allow user to keep the homepage when selecting a new theme

### LINKED ISSUE #15014: Allow user to keep the homepage when selecting a new theme
### Description
When someone decides to change their theme, they may have already customized the homepage. Instead of automatically overwriting it, we need to give them an option to keep their existing one.

To achieve this we will add one more step after the user chooses to activate a new theme. This will prompt the user to select between two options:
* Use the [New Theme]'s homepage layout
* Keep current homepage layout (**default** preselected option)

The user may press the **Preview** button to view the new theme in action.
Hitting the **Activate** button will apply the new theme respecting the user's choice.

*Note that this functionality already exists on the web.*

### Design
The new step will be presented as a bottom sheet sliding from the bottom. The design below depicts the theme change flow with the addition of the new step. 

changingtheme

*Note that the design above is targeting iOS but the same changes apply on Android too. Our design team can provide clarifications or extra designs if needed.*

There is a matching iOS issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/16954).

### PR DESCRIPTION
**Pull request by antonis**
Fixes #15014

## Description
TODO

### Sub PRs
* https://github.com/wordpress-mobile/WordPress-Android/pull/15029
* https://github.com/wordpress-mobile/WordPress-Android/pull/15043
* https://github.com/wordpress-mobile/WordPress-Android/pull/15088

To test:
TODO

## Regression Notes
1. Potential unintended areas of impact
TODO

2. What I did to test those areas of impact (or what existing automated tests I relied on)
TODO

3. What automated tests I added (or what prevented me from doing so)
TODO

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by kashandanish** [comment]
@antonis I see that this check is failing
```
buildkite/wordpress-android/lint — Failed (exit status 1)
```
But running `./gradlew ktlint` is not reporting any issues. I also don't have access to this check's [details](https://buildkite.com/wordpress-mobile/wordpress-android/builds/705#74a91c87-3c80-40ab-a6f0-d72faebac5d3). I need your help in checking what lint issue is being reported here.

**Comment by antonis** [comment]
> @antonis I see that this check if failing
> 
> ```
> buildkite/wordpress-android/lint — Failed (exit status 1)
> ```
> 
> But running `./gradlew ktlint` is not reporting any issues. I also don't have access to this check's [details](https://buildkite.com/wordpress-mobile/wordpress-android/builds/705#74a91c87-3c80-40ab-a6f0-d72faebac5d3). I need your help in checking what lint issue is being reported here.

Hey @kashandanish 👋 
I checked the report and the issue is the following.

```
[2021-07-23T16:24:30Z]   /workdir/WordPress/src/main/res/values/dimens.xml:686: Error: The resource R.dimen.theme_bottom_sheet_button_corner_radius appears to be unused [UnusedResources]
--
  | [2021-07-23T16:24:30Z]       <dimen name="theme_bottom_sheet_button_corner_radius">8dp</dimen>
```

**Comment by kashandanish** [comment]
> Hey @kashandanish 👋
> I checked the report and the issue is the following.

Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/15088/commits/a77e409f4bd249e5b9cdf003814b39591aa88fdf as a part of https://github.com/wordpress-mobile/WordPress-Android/pull/15088.
Thank you for letting me know.

**Comment by antonis** [comment]
Hey @kyleaparker 👋 
As this feature approaches completion ([pending issues](https://github.com/wordpress-mobile/WordPress-Android/issues/15014#issuecomment-888232814)) we would like your feedback 🙏 
You can find an APK [above](https://github.com/wordpress-mobile/WordPress-Android/pull/15055#issuecomment-884765285).
We would also like your view on how to handle the two other activation flows. Specifically:
1. Choose a theme > tap on (...) > **View > Activate** : I think we can eliminate this flow if you agree
2. Choose a theme > tap on (...) > **Activate > Preview > Activate**: I was thinking of trying to respect the user's choice but as @kashandanish pointed out the preview screen is the same same irrespective of the selection. Wdyt?

**Comment by kyleaparker** [comment]
Thanks for the ping @antonis !

It looks good to me 😄 

>Choose a theme > tap on (...) > View > Activate : I think we can eliminate this flow if you agree

What are your thoughts on showing the action sheet after clicking the activate button from the preview?

>Choose a theme > tap on (...) > Activate > Preview > Activate: I was thinking of trying to respect the user's choice but as @kashandanish pointed out the preview screen is the same same irrespective of the selection. Wdyt?

I think in this case we can remove the preview button and just have the Activate button

**Comment by antonis** [comment]
Thank you for the prompt feedback @kyleaparker 🙇 

> > Choose a theme > tap on (...) > View > Activate
> What are your thoughts on showing the action sheet after clicking the activate button from the preview?

That sounds like a good option 👍
In that case, is it ok to dismiss the preview screen and present the dialog on top of the themes screen as is now?  

> > Choose a theme > tap on (...) > Activate > Preview > Activate
> I think in this case we can remove the preview button and just have the Activate button

Ok 👍

**Comment by kyleaparker** [comment]
> In that case, is it ok to dismiss the preview screen and present the dialog on top of the themes screen as is now?

Yes this should be fine 👍

**Pull request closed without merging**
