### PR TITLE
Stats new colors and icons

### LINKED ISSUE #3300: Stats: Icons need to be updated from Noticons to Gridicons
Icons have been updated on the Web version so we need these updated on the Android app.

Update:

As an example,

**iOS icons (using Noticons):**
screenshot 2015-10-08 15 01 02

**Web icons (using Gridicons):**
screenshot 2015-10-08 15 02 20

/cc @daniloercoli

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #3300 and #3320 

Designer and developer review needed.

@jancavan Can you check that everything is OK with icons and colors?

### CODE REVIEW

**Comment by maxme** [comment]
`drawable-xhdpi/stats_chevron_down.png` size is incorrect: w=12dp instead of w=16dp for other resolutions.

**Comment by daniloercoli** [comment]
cc @jancavan ^

**Comment by maxme** [comment]
:shipit:  when `drawable-xhdpi/stats_chevron_down.png` is fixed (should be 32x22px)

**Comment by jancavan** [comment]
@daniloercoli Sorry for the bit of delay, I'm on support rotation. But here's the updated `drawable-xhdpi/stats_chevron_down.png` (32x32 px):
https://cloudup.com/c44Dcef3umv

We need to remove the placeholder favicon. I noticed they've been removed everywhere else except for Search Engines:
screenshot 2015-10-30 12 25 19

No favicon should just show the "Open external link" icon:
screenshot 2015-10-30 12 26 36

If a list has sites with and without favicons, it should show up like this, so it's fine if they all get mixed together:
screenshot 2015-10-30 12 28 55

All the other icon and color updates look great :+1:

**Comment by daniloercoli** [comment]
@maxme Fixed the image and removed placeholder icons in Referrers.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
