### PR TITLE
Refactor Account Settings Screen - Creates AccountSettings UseCases

### PR DESCRIPTION
**Pull request by SowmiaS**
Part of #12372

### **Description**

First PR for the task of refactoring the [`AccountSettingsFragment`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java) to MVVM following the reactive approach using Flow.

This PR extracts calls to `AccountStore` and `SiteStore` from AccountSettingsFragment to the Repository layer.
- gets all sites from SiteStore.
- gets account from AccountStore.
- fetch new account settings from the server.
- updates account settings to the server.
- Right now, the fluxC gives back the response to the `onAccountChanged` event method using the event bus. I have created suspend functions with `suspendablecoroutine` for fetching new account settings and for updating the account settings.

Note: 

- Call to `fetch new account settings` and `update account settings` to AccountStore, retrieves or update to the server and it caches the new / updated account information in the `account` property in AccountStore. And then posts `onAccountChanged` event, which tells us if the server request is a success or failure.
- get sites functions retrieves sites from DB.

There will be follow-up Pull Requests for ViewModel and Fragment.

### **Testing**
- No testing is required.

### Regression Notes
 - There will be no impact on the screens, as AccountSettingsRepository is not yet used by AccountSettingsFragment.

### **Screenshots**
N/A

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — COMMENTED** [review]
Hey @SowmiaS, thank you so much for working on it! 🙇‍♀️ 

I like how a repository layer is created to interact with the data layer and to convert event bus to coroutines and suspend functions. This is such a nice first step 🙌 

I feel like we can split responsibilities a bit more. As you noted down, currently the repository performs the following responsibilities:

1. get sites from `SiteStore`.
2. get account from `AccountStore`.
3. fetch new account settings from the server.
4. updates account settings to the server.

It manages two `continuations` for fetching and updating account settings. Can we split these different responsibilities to use cases like:
`FetchAccountSettingsUseCase`
`PushAccountSettingsUseCase`?

Several of the `update functions` can move to `PushAccountSettingsUseCase` and `FetchAccountSettingsUseCase` can only be responsible for fetching account settings.

**Optional:**  We can also put a network availability check in `Fetch...UseCase()` similar to [FetchFollowedTagsUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/tags/FetchFollowedTagsUseCase.kt) , [FetchScanStateUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchScanStateUseCase.kt) to keep fetch logic in one use case. But I wouldn't advise you to do it in this PR as it can complicate things for linked PRs. We can take it up in separate PR later.

Let me know if it makes sense or we can further discuss 🙂

**Comment by SowmiaS** [comment]
Hi @ashiagr 👋 

First of all, thank you so much for taking your valuable time reviewing my PR and providing feedback. 🙇 

> Can we split these different responsibilities to use cases like:
> FetchAccountSettingsUseCase
> PushAccountSettingsUseCase?

This is a good point. I totally agree with your feedback on splitting responsibilities into different use cases. I will make the necessary code changes and let you know.

> Optional: We can also put a network availability check in Fetch...UseCase() similar to [FetchFollowedTagsUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/tags/FetchFollowedTagsUseCase.kt) , [FetchScanStateUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchScanStateUseCase.kt) to keep fetch logic in one use case. But I wouldn't advise you to do it in this PR as it can complicate things for linked PRs. We can take it up in separate PR later.

As you suggested, we can take this up in separate PR.

Thanks 🙂

**Comment by SowmiaS** [comment]
@ashiagr 
I have split the functionalities into use cases and it is ready for another round of review. Kindly have a look.
Thanks 🙂

**Comment by ashiagr** [comment]
Woohoo! Thank you, @SowmiaS
Sorry I could not review it today but it's on my list and I'll get back to it by Mon/Tues.

**Review by ashiagr — COMMENTED** [review]
Hey @SowmiaS 

I reviewed new changes and overall they look great! 🙌 

I really liked how you created `ContinuationWrapper` and `ConcurrentContinuationWrapper`. Also, separate use cases with their own responsibilities look awesome! 👏 
Before I approve the changes, a couple of more observations that I would like to discuss:

1. Since the `repository` is now not doing anything, how about we remove it, and then we can directly use `usecases` in the view model in the next PR?
2. If we use the `usecase` in the view model, we can directly invoke `usecase` functions from it (and thus eliminate use case interfaces). There's nothing wrong with the approach but thinking in terms of consistency with other use cases where we do not use `Interface` and `Impl` convention. Wdyt?
3. I ran CI on the branch and notice a few check style issues. Can you take a look? You can check [details](https://buildkite.com/automattic/wordpress-android/builds/4667#abf3c82e-c61e-4aad-bdf7-f4e252faf919) for logs. 

We're almost ready to finalize this PR. Thank you so much for your hard work on this. 🙇‍♀️

**Comment by SowmiaS** [comment]
> Since the repository is now not doing anything, how about we remove it, and then we can directly use usecases in the view model in the next PR?

I have deleted the `AccountSettingsRepository` class. Done in 356e11f90e3f1191d47d449159a55f39704def2e

> 1. If we use the usecase in the view model, we can directly invoke usecase functions from it (and thus eliminate use case interfaces). There's nothing wrong with the approach but thinking in terms of consistency with other use cases where we do not use Interface and Impl convention. Wdyt?

This makes sense. I have made changes in 9f77de65bc8436c951b9a1712830d386e4f015f7

> 1. I ran CI on the branch and notice a few check style issues. Can you take a look? You can check [details](https://buildkite.com/automattic/wordpress-android/builds/4667#abf3c82e-c61e-4aad-bdf7-f4e252faf919) for logs.

Sorry about missing this. I have fixed in bb492fc8c121df2b05ad18590d245b945bc287d1

Thank you so much reviewing PR and providing your feedbacks.🙇

**Review by ashiagr — APPROVED** [review]
Thank you for the changes @SowmiaS! And don't feel sorry about anything. You're doing great! 🎊

I'm approving this PR. Let me know once you've replaced the `repository` with `usecases` in the next PR that introduces  `ViewModel` and I'll start reviewing it.

**Pull request merged**
