### PR TITLE
Add delay to wait Gutenberg to load in connected tests

### PR DESCRIPTION
**Pull request by oguzkocer**
**To test:**

* CI should pass without a restart

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
I ran the CI 3 times and in the 3rd run it failed even with a delay of 15 seconds. Not really sure what we should do, but I think temporarily disabling these 2 tests might be our best bet. I can then try to fix it during this sprint by time-boxing it to maybe half a day.

What do you think @rachelmcr @jkmassel?

**Comment by jkmassel** [comment]
>I ran the CI 3 times and in the 3rd run it failed even with a delay of 15 seconds. Not really sure what we should do, but I think temporarily disabling these 2 tests might be our best bet. I can then try to fix it during this sprint by time-boxing it to maybe half a day.


Yep works for me – if it's failing in the same place, it could be a crash on Gutenberg startup? 🤔

**Comment by rachelmcr** [comment]
Let's disable these tests and work on a fix. I finally had a chance to take a closer look at these tests and failures: the problem seems to be that the tests expect Aztec (not Gutenberg) but for some reason sometimes Gutenberg is getting enabled.

Longer term we need to make sure we have tests that cover the Gutenberg integration as well, but for now let's just get the existing tests working correctly. We probably need to adjust the mocks to ensure the correct editor is always used — @oguzkocer let me know if you still want to work on that or if you'd like me to investigate it (or we can look together).

**Comment by oguzkocer** [comment]
@rachelmcr Sounds good to me. I am going to close this PR and open a new one disabling the tests for now.

**Pull request closed without merging**
