### PR TITLE
Issue/13268 implement clear and apply actions

### PR DESCRIPTION
**Pull request by malinajirka**
Partially fixes #13268

This PR adds the clear and apply action to the Activity Log Type Filter screen. 

Note: Review by commits might be easier.
Note2: Checked items are not persisted when you go back to activity log and re-open the activity type filter. That's coming in the next PR.

Merge instructions:
1. Make sure https://github.com/wordpress-mobile/WordPress-Android/pull/13470 is reviewed
2. Remove "Not ready for merge" label
3. Merge this PR

To test:
1. My site -> Activity Log
2. Click on "Activity type" chip
3. Try to select multiple items
4. Click on the Clear action and notice all items get de-selected
5. Click on the Apply action and notice the screen gets dismissed

The rest of the functionality will be tested when the filter actually work - next week.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@malinajirka - The clear functionality is not working for me, can you take a look - maybe I am doing something wrong?
ezgif com-gif-maker (1)

**Comment by malinajirka** [comment]
@zwarm Could you please double check that you are on the correct apk/branch. I just retested it on 2 emulators and it worked as expected. If it still doesn't work for you, what device/android are you testing it on? Thanks!

**Comment by zwarm** [comment]
I'm running: pr-13483-build-84851 on emulator Pixel 3a XL API 29. I re-downloaded the APK attached to this PR and tried again, no luck. @malinajirka 

It works on emulator Nexus 5X API 24. 
Doesn't work on emulator Pixel 4 XL API 30 either.

**Review by zwarm — APPROVED** [review]
Created issue for the clear not working when tapping on checkboxes proper.
https://github.com/wordpress-mobile/WordPress-Android/issues/13509

Feel free to merge after conflict is fixed.
👍

**Comment by malinajirka** [comment]
Thanks for the review ;)!

**Pull request merged**
