### PR TITLE
Prevent Homepage from being deleted or moved to a draft

### LINKED ISSUE #13908: User can delete Homepage and break their site
### Description
It is possible to delete your Homepage while it's set as your static Homepage. This is a feature that is disabled on dotCom. If a user does delete their Homepage then their site will render with an error when you navigate there. 

### Steps to reproduce the behavior
**_Setup:_** Set your site's Homepage settings to use a Static Homepage

1. Navigate to pages
2. Tap the `...` 
3. Tap `Move to Trash`

##### Tested on Pixel 3a, Android 29, WPAndroid 16.6

iOS Ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/15729

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes:** https://github.com/wordpress-mobile/WordPress-Android/issues/13908

## To test:
📓 Make sure your site is set to have a Static Homepage

### Attempt to delete Homepage
1. Navigate to the Page List 
2. Select the `...` on the Homepage
3. **Expect** to _NOT_ see the `Move to Trash` option
📓 If the Homepage has been moved out of the Published filter then the `Move to Trash` option will still be there. The site is already broken so no reason to restrict it.

<details>
<summary>Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107820017-1c038e00-6d48-11eb-81e3-a44f4827390a.png"></a></kbd>
</details>

### Attempt to move Homepage to Draft - Page List
📓 This doesn't apply if you've trashed your Homepage.

1. Navigate to the Page List 
2. Select the `...` on the Homepage
3. **Expect** to NOT see the  `Move to Draft` 

<details>
<summary> Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107820017-1c038e00-6d48-11eb-81e3-a44f4827390a.png"></a></kbd>
</details>

### Attempt to move Homepage to Draft - Page Settings
1. Navigate to the Page List 
2. Select Homepage to open the Editor
3. Select the `...` in the top right-hand corner
4. Select `Page Settings`
5. Select `Status`
6. **Expect** to only have the Publish option and Private Option.
📓 On iOS Private is handled by a different menu.

<details>
<summary> Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107820143-4ce3c300-6d48-11eb-8ff6-1aec504107e5.png"></a></kbd>
</details>

### Attempt to delete Page
1. Navigate to the Page List 
2. Select the `...` on a page that is not the Homepage
3. **Expect** to see the `Move to Trash` option
4. Select `Move to Trash` 
5. **Expect** for the page to be deleted

### Attempt to move Page to Draft - Page List
1. Navigate to the Page List 
2. Select the `...` on a page that is not the Homepage
3. Select `Move to Draft` 
4. **Expect** to see the page be moved to a draft.

### Attempt to move Page to Draft - Page Settings
1. Navigate to the Page List 
2. Select a page (not Homepage) to open the Editor
3. Select the `...` in the top right-hand corner
4. Select `Page Settings`
5. Select `Status`
6. Change the status
7. **Expect** to see the screen to dismiss and the page will modify to the new status.

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Nice work @chipsnyder 👍 
Tested the App on an Pixel 2 XL with Android 11 and behaves as expected.
The code changes are consistent and LGTM 🎉 

Regarding the failing checks:

1. The `CreatePageListItemActionsUseCaseTest` tests should be ok by removing the `MOVE_TO_DRAFT, MOVE_TO_TRASH` values from the expected actions. It would be nice if we added a couple more tests to verify [the new if branch](https://github.com/wordpress-mobile/WordPress-Android/pull/14061/files#diff-1c507531c224af9d005b9a1591c6fca5ad76d3104b496ecb6195abc600e8b3a4R61) in the `CreatePageListItemActionsUseCase`.

2. The lint check failure has to do with the introduction of Detekt and a fix is already available in `develop`

**Comment by chipsnyder** [comment]
> Regarding the failing checks:
> 
> 1. The CreatePageListItemActionsUseCaseTest tests should be ok by removing the MOVE_TO_DRAFT, MOVE_TO_TRASH values from the expected actions. It would be nice if we added a couple more tests to verify the new if branch in the CreatePageListItemActionsUseCase.
> 
> 2. The lint check failure has to do with the introduction of Detekt and a fix is already available in develop

Thanks for the help @antonis! I totally forgot to come back and validate these checks before I logged off for the day. I updated the tests that check the available settings for Homepages and it looks like a [test](https://github.com/wordpress-mobile/WordPress-Android/pull/14061/files#diff-007b4b76437aca83cb27579ead55167a72a846ae9c3b423ab1cbd9ae4953f2feR189) already existed for pages that aren't homepages.

**Comment by chipsnyder** [comment]
The installable build is still failing but that should be resolved by https://github.com/wordpress-mobile/WordPress-Android/pull/14082 once that's available

**Review by antonis — APPROVED** [review]
> Thanks for the help @antonis! I totally forgot to come back and validate these checks before I logged off for the day. I updated the tests that check the available settings for Homepages and it looks like a test already existed for pages that aren't homepages.

Thank you for the changes @chipsnyder 👍 
LGTM 🎉

**Pull request merged**
