### PR TITLE
My Site Dashboard: Tabs - Refactor MySiteFragment to support tabs

### LINKED ISSUE #16003: My Site Dashboard: Tabs - Refactor MySiteFragment
Parent #15989 

The goal of this task is to refactor MySiteFragment to support the `Dashboard` and `Site Menu` tabs

- [x] Reuse parent view models for each tab
- [x] Implement default tab strategy
- [x] Tab management - filter content based on tab type
- [x] Write Unit Tests

### LINKED ISSUE #16048: My Site Dashboard: Tabs - Extract tab fragment from my site fragment
Parent #16001

- [x] Create MySiteTab fragment to host tabbed views for Dashboard and Site Menu

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #16048
Fixes #16003 

This PR adds "tab" functionality to the My Site Fragment

Menu | Dashboard
-- | --
Menu | Dashboard

1. Adds MySiteTabFragment
2. Reuses MySiteViewModel for each tab
3. Maintains PTR in each tab
4. Builds distinct views for each tab 
5. Maintains a single view containing all cards/site items (for when tab feature flag is disabled)

Known issues/not included in this PR
1. Dynamic card left/right swiping may swipe entire tab 
2. Moving site header above tabs
3. Tab labels 
4. PTR as a single unit across both tabs
5. While on Dashboard tab, notification dot not shown on menu tab. See comment [below](https://github.com/wordpress-mobile/WordPress-Android/pull/16099#pullrequestreview-910034172).

@tiagomar - Would love your eyes on this one - most important items are tests A, B, and C, with Quick Start as the highest priority. Thanks.

**To test:**

The first set of tests focus on regression testing functionality while tabs are disabled
Prerequisite
1. Launch the app.
6. Go to `My Site` -> `Me` -> `App Settings` -> `Debug settings`.
7. Turn off the `MySiteDashboardTabsFeatureConfig` flag under the `Features in development` section.
8. Restart the app
9. Logout/login and select "Show me around" when the quick start prompt is shown.

**Test A: Regression test Quick Start in single view (tabs disabled)**
1. Run tests in [wpandroid-quick-start-testing-instructions.txt](https://github.com/wordpress-mobile/WordPress-Android/files/8246096/wpandroid-quick-start-testing-instructions.txt)

**Test B: Regression test general navigation (tabs disabled)**
1. Navigate around the My Site View and validate that navigation works as expected (FAB, site items, Quick links)

**Test C: Regression test - PTR (tabs disabled)**
1. Swipe down on the My Site view to request a refresh of the view
----------------------------

The remainder of the tests focus on testing functionality while tabs are enabled
Prerequisite
1. Launch the app.
3. Go to `My Site` -> `Me` -> `App Settings` -> `Debug settings`.
4. Turn on the `MySiteDashboardTabsFeatureConfig` flag under the `Features in development` section.
6. Restart the app

**Test D: Quick Start 
1. Logout/login and select "Show me around" when the quick start prompt is shown.
2. Note the "Quick Start" shows in the "Menu" tab only 
3. Run tests in [wpandroid-quick-start-testing-instructions.txt](https://github.com/wordpress-mobile/WordPress-Android/files/8246096/wpandroid-quick-start-testing-instructions.txt)

**Test E: General navigation**
1. Navigate around the My Site View and validate that navigation works as expected (FAB, site items, Quick links)

**Test F: Content validation**
1. Validate the following tab content:
Menu tab includes: Site Info header, quick links, quick start (if selected), domain registration card (if available), and site menu items.
Dashboard tab includes: Site info header, quick links, domain registration card (if available), and dashboard cards (stats, posts).

## Regression Notes
1. Potential unintended areas of impact
Quick start actions/tasks don't work as expected

4. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and automated tested

10. What automated tests I added (or what prevented me from doing so)
Unit tests were updated to reflect refactoring efforts

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — APPROVED** [review]
👋 @zwarm, 

Thank you for putting together all the testing steps. 🙌 
I tested as per the instructions, and found no issues for the following test cases:

`Test A: Regression test Quick Start in single view (tabs disabled)` ✅  (I ran all quick start steps)
`Test B: Regression test general navigation (tabs disabled)`  ✅ 
`Test C: Regression test - PTR (tabs disabled)`  ✅ 
`Test E: General navigation`  ✅ 
`Test F: Content validation` ✅ 

For `Test D: Quick Start` test case (tabs enabled), I noticed that if we're on the `Dashboard` tab and a quick start next task snackbar is displayed for a site item which is on the `Site Menu` tab , notification dot is not set. But we're not enabling the tabs right now and we have a separate task for quick start functionality, so all 🟢  from my side.

**Comment by zwarm** [comment]
> For `Test D: Quick Start` test case (tabs enabled), I noticed that if we're on the `Dashboard` tab and a quick start next task snackbar is displayed for a site item which is on the `Site Menu` tab , notification dot is not set. But we're not enabling the tabs right now and we have a separate task for quick start functionality, so all 🟢 from my side.

Excellent find @ashiagr -- I noted this above and dropped it in the QS [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/16006)

**Comment by tiagomar** [comment]
Hey @zwarm! 👋  Sorry for the delay.

I went through Test A to Test F without seeing any major issues.  =D

Let me share some findings, some of them may already be covered by the known issues list. I don't see any as blocker for this PR.

<details>
  <summary>Hint being displayed when long pressing the tabs.</summary>
  image
</details>

<details>
  <summary>This is probably the 'Moving site header above tabs' known issue. It only happens in portrait mode</summary>

  https://user-images.githubusercontent.com/42008628/158467264-22c1d38f-8028-40e8-882c-9b73ec04d6b0.mp4
</details>

Other issues not introduced by this card:
<details>
  <summary>QS: Completed tasks are not brought into screen when expanding Complete.</summary>

https://user-images.githubusercontent.com/42008628/158469476-3e982862-cffd-4925-ab9b-f69a397410db.mp4
</details>

<details>
  <summary>Blogging reminders modal being displayed after discarding a story post.</summary>

  https://user-images.githubusercontent.com/42008628/158470459-faec4110-8307-4f4f-ba8b-f754d46111ef.mp4
</details>

**Comment by ashiagr** [comment]
Thank you so much for reviewing it, @tiagomar, please don't be apologetic about anything. 🙏 

Since Annmarie is still few hours away, I've responded to the comments:

---------------

> Hint being displayed when long-pressing the tabs. 

Nice observation, 😅 I never tried that. But the behavior seems consistent with other tabs like the ones on the `Reader` tab so I think we're fine with it.



---------------

> This is probably the 'Moving site header above tabs' known issue. It only happens in portrait mode. 

Correct, there's a separate task where we're moving the site's dropdown above the tabs. Not quite sure what you meant by "happens in portrait mode". Actually, we can see site's dropdown below the tabs in both portrait and landscape mode. 

---------------

The other two issues are not related to this PR. But I checked this one:

> QS: Completed tasks are not brought into screen when expanding Complete.

https://user-images.githubusercontent.com/1405144/158567028-00f94db5-3791-45f1-acfc-35eacd374c75.mp4

I was able to scroll and see completed tasks, let us know if you expected something different. 

Considering there are no blockers, I'll merge this PR now. Appreciate all your efforts on this! 🙇‍♀️

**Comment by tiagomar** [comment]
Thanks for checking, @ashiagr! =)

> Nice observation, 😅 I never tried that. But the behavior seems consistent with other tabs like the ones on the Reader tab so I think we're fine with it.

Interesting! I hadn't tried the other tabs. Unlike `My Site` and `Notifications`, `Reader` tab hints are not capitalized though. Obviously unrelated. =)

> Correct, there's a separate task where we're moving the site's dropdown above the tabs. Not quite sure what you meant by "happens in portrait mode". Actually, we can see site's dropdown below the tabs in both portrait and landscape mode.

Yeah, you're right, I haven't properly pointed out what I was seeing. The site's dropdown below the tabs happens in both portrait and landscape mode. What I only noticed in portrait mode was the `My Site` label not shrinking when:
1. Scroll down until `My Site` label is small
2. Scroll up just until `My Site` label is full size
3. Scroll down again
**Expected**: `My Site` label is resized
**Observed**: Notice that `My Site` label will stay full size

> I was able to scroll and see completed tasks, let us know if you expected something different.

I expected that the completed tasks would be automatically brought into view when I tap `Complete (2)` as just rotating the accordion (current state) might not be enough feedback for the user's action. As this is not related I will probably just file an issue and hear people's thoughts on this.

**Pull request merged**
