### PR TITLE
Editor - Backspacing uploading media doesn't clear them properly

### PR DESCRIPTION
**Pull request by aforcier**
Fixes https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/297 and https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/313.

Adds a new JavaScript callback, `callback-media-removed`, which is tripped when an uploading or failed image is deleted manually by the user. This cancels the uploading and updates the uploading/failed media list native-side, unblocking the user from uploading the post.

On `API>18` there was an [additional issue](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/313), where backspacing uploading/failed media would delete the placeholder image but not the progress element or container. Those would be kept as empty elements and uploaded with the post. The cursor would also disappear when backspacing (unless you backspaced three times, to delete the progress element and container as well). This PR fixes that as well; deleting the image will delete its entire container, and move the cursor appropriately.

<h4>Implementation details (mostly here for future reference)</h4>

This introduces a `MutationObserver` to listen for element deletions. The iOS editor also uses one, but our implementations are a bit different.

On iOS, the MO is set globally on the parent (`contenteditable`) `div` to listen for `childList` changes, which will catch any changes to the list of child nodes (additions/removals, but not modifications within the child nodes). Due to the [#313](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/313) issue, on Android the image inside the container is deleted, rather than the container itself, and this doesn't trip the MO set on the `contenteditable`.

I initially used the `subtree` param for configuring the global MO, which listens to the entire subtree of the parent node. This worked, but it gets called anytime any element is modified in the entire document, and we could expect some performance hits from that.

Instead, each time a container node is created I assign the MO to listen to that, and in that case only the `childList` level config is needed.

On stock `API<19`, the MO is not supported. Instead we fall back to the deprecated `DOMNodeRemoved` events, which are also attached per-container rather than globally.

<h4>Testing</h4>

- Backspace uploading media: should be able to switch to HTML mode or Publish immediately
- Backspace failed media: should be able to HTML/Publish immediately
- Close a post while uploading, re-open it: should be unable to HTML/Publish (uploading media are now marked as failed). Backspace failed media: should be able to HTML/publish
- With failed media, switch to HTML mode and back; should be unable to publish until removing manually
- The above should be checked on a `API 19+` device and on a `API<19` device

### CODE REVIEW

**Comment by aforcier** [comment]
cc @tonyr59h

**Comment by tonyr59h** [comment]
Testing went great on API 19+, no problems found.

On API 16 I tested
> With failed media, switch to HTML mode and back

and found that the failed media was automatically removed when I switched to HTML. This also seems to be the case with:
> Close a post while uploading, re-open it

Maybe it's just the emulator? I don't have a real device with a low enough API to test with. Have you seen this behavior/is it expected?

**Comment by aforcier** [comment]
It's very possible it's the emulator - does this happen if you wait ~10 seconds after loading the post or the image fails before switching to HTML mode?

The emulators (especially older ones) are really slow with WebViews, and sometimes the request for the HTML from JS takes longer than the [timeout](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/bf525c8a5043a9b7f2f3b7b0d87ab98d81133e39/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L722). If auto-save hasn't already captured the recent change, that can cause the change to be ignored when switching to HTML mode, and then removed when switching back.

This can happen outside of the emulator as well, and we have an open issue to improve this: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/47

If it's still happening even after waiting (I can't reproduce it if I wait), this might be worth opening a separate issue to investigate. But, it's hard to be sure without a physical `API 16` device.

**Comment by tonyr59h** [comment]
> does this happen if you wait ~10 seconds after loading the post or the image fails before switching to HTML mode?

Nope, everything behaves as you'd expect after waiting a bit. Looks good to :shipit: then since there's already an issue to improve that behavior.

**Pull request merged**
