### PR TITLE
FluxC: TaxonomyStore integration

### PR DESCRIPTION
**Pull request by aforcier**
Integrates the FluxC [TaxonomyStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/221) into WPAndroid.

## Notes

* Only categories are using `TaxonomyStore` at this time - tags are still fetched and pushed as a list of strings attached to the `PostModel` (provisions are present in `TaxonomyStore` for tags when we decide to switch to id-based tag management in the future)
* Site settings isn't using FluxC for Default Category - this is still using the existing network layer. For XML-RPC the site settings module is currently unused; for REST API the module needs to be refactored to use FluxC everywhere, and we'll revisit that after v1 ships.

#### Categories:
* [x] Load existing post with categories, they should display correctly in post settings
* [x] Add a category (from the list) to post in Editor -> Settings, and upload
* [x] Remove a category from a post, and upload
* [x] Create a new category in Editor -> Settings -> `+` -> `+`, add to post, and upload
* [x] Publish a post with no category - it should have the site's default category once uploaded
* [x] Remove all categories from a published post, and upload

#### Tags:
* [x] Load existing post with tags, they should display correctly in post settings
* [x] Add a new tag (new to the site or one that already exists) to post in Editor -> Settings, and upload
* [x] Remove a tag from a post, and upload
* [x] Publish a post with no tags
* [x] Remove all tags from a published post, and upload - the post should remain tag-less

#### Categories:
* [x] Load existing post with categories, they should display correctly in post settings
* [x] Add a category (from the list) to post in Editor -> Settings, and upload
* [x] Remove a category from a post, and upload
* [x] Create a new category in Editor -> Settings -> `+` -> `+`, add to post, and upload
* [x] Change the default category in My Site -> Settings -> Default Category, confirm new posts have this category automatically added
* [x] Publish a post with no category - it should have the site's default category once uploaded
* [x] Remove all categories from a published post, and upload - it should have the site's default category once uploaded

#### Tags:
* [x] Load existing post with tags, they should display correctly in post settings
* [x] Add a new tag (new to the site or one that already exists) to post in Editor -> Settings, and upload
* [x] Confirm that tag suggestions are working (WP.com/Jetpack only)
* [x] Remove a tag from a post, and upload
* [x] Publish a post with no tags
* [x] Remove all tags from a published post, and upload - the post should remain tag-less

### CODE REVIEW

**Comment by aforcier** [comment]
I considered modifying `onTaxonomyChanged` [here](https://github.com/wordpress-mobile/WordPress-Android/pull/5000/files#diff-2a05761a1946e0ddb314645e44ab3eb6R1112) to fetch any missing categories by individual `FETCH_TERM` calls (these would be categories that were outside the limit of the `FETCH_TERMS` server call).

Unfortunately this can't currently be done for the WP.com REST API, as individual terms can only be fetched by slug, and we don't have a way to get that at the moment (XML-RPC and WP-API can fetch by ID).

We could:
1. Store slugs as well as IDs when parsing posts initially (this will be less messy when we extend WellSql to serialize arbitrary objects, but currently I think would just be bloating PostModel)
2. Add an endpoint for fetching by ID

I think for now we can leave this as is. XML-RPC returns all categories on the site, and we can update FluxC to request the maximum numbers of terms from the WP.com REST API (`1000` - we're currently fetching the default, which is `100`).

**Comment by aforcier** [comment]
This PR also fixes https://github.com/wordpress-mobile/WordPress-Android/issues/3152 and https://github.com/wordpress-mobile/WordPress-Android/issues/3788 (in the FluxC branch).

**Comment by aforcier** [comment]
Ready for review!

cc @maxme

**Comment by maxme** [comment]
I was testing https://github.com/wordpress-mobile/WordPress-Android/issues/3152 and I found something weird: [demo video](https://cloudup.com/i4ED5QmUXER) (look at the quoted `"c"`)

**Comment by maxme** [comment]
I confirm this fixes #3152 for self hosted sites (and almost for wpcom sites except for the case described above).

**Comment by maxme** [comment]
We should drop the test file `malformed_category_parent_id.sql` (it was only used in the test you deleted).

**Comment by maxme** [comment]
Got this crash when testing:
```
FATAL EXCEPTION: main
Process: org.wordpress.android, PID: 3186
java.lang.IndexOutOfBoundsException: Invalid index 5, size is 3
   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
   at java.util.ArrayList.get(ArrayList.java:308)
   at org.wordpress.android.ui.posts.SelectCategoriesActivity.updateSelectedCategoryList(SelectCategoriesActivity.java:236)
   at org.wordpress.android.ui.posts.SelectCategoriesActivity.refreshCategories(SelectCategoriesActivity.java:223)
   at org.wordpress.android.ui.posts.SelectCategoriesActivity.access$100(SelectCategoriesActivity.java:44)
   at org.wordpress.android.ui.posts.SelectCategoriesActivity$1.onRefreshStarted(SelectCategoriesActivity.java:119)
   at org.wordpress.android.util.helpers.SwipeToRefreshHelper.onRefresh(SwipeToRefreshHelper.java:59)
   at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:188)
   at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:105)
   at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:5616)
```

I added the category `"c"` (no parent), then added `c` (no parent), then refreshed the view.

**Comment by maxme** [comment]
There is something wrong with the backend, here is the request to create a `"d"` category:
```json
{
	"name": "\"d\"",
	"parent": "0",
	"description": ""
}
```

And the response:

```json
{
	"ID": 7734,
	"name": "d",
	"slug": "d",
	"description": "",
	"post_count": 0,
	"parent": 0,
	"meta": ...
}
```

**Comment by aforcier** [comment]
> Got this crash when testing:
> FATAL EXCEPTION: main
> I added the category "c" (no parent), then added c (no parent), then refreshed the view.

It looks like adding categories in general seems to be behaving a bit oddly and not preserving checked categories - looking into that.

**Comment by aforcier** [comment]
> It looks like adding categories in general seems to be behaving a bit oddly and not preserving checked categories - looking into that.

Fixed in 50ae846 and 87168b7. 50ae846 should also fix the crash you reported @maxme, but I added a check in 50c16fd for safety.

**Comment by aforcier** [comment]
> We should drop the test file malformed_category_parent_id.sql (it was only used in the test you deleted).

Done in 0e1a53b.

Ready for round 2 @maxme.

**Comment by maxme** [comment]
Tested all the described cases and a bunch of operations in the Category screen, looks good :shipit:

**Pull request merged**
