### PR TITLE
Update save button text for users that lack publish permissions

### LINKED ISSUE #5163: Editor: Contributors should not see the option to publish posts
### Expected behavior

If my role on a site is Contributor, I shouldn't see an option to Publish in the editor. Instead of Publish, the primary action I see should be "Submit for Review."

### Actual behavior

When I use the app as a Contributor, and write a post, I see a big Publish button. If I click on it, the editor closes like normal. But if I navigate to my Posts list, I see that it's only been saved locally; it's not actually uploaded to my site at all. After a minute, I'll get a bad error message.

### Steps to reproduce the behavior

- Add a contributor to a site
- Login to the app as that user
- Open the editor
- Write a post and click Publish.

Current flow:
androidflow

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #5163 

To test:
* Add a contributor to a site
* Login to the app as that user
* Open the editor
* Verify the save button text
* Repeat for user with publish permissions (editor, admin)

### CODE REVIEW

**Comment by nbradbury** [comment]
"Submit for Review" takes up too much space on smaller displays, resulting in the redo button being cut off. Perhaps just "Submit" would work?

screenshot_1490007744

Also, if we're going to change the text in the post editor, we should also change it in the post list (right now it still says "Publish").

screenshot_1490007756

**Comment by tonyr59h** [comment]
> we should also change it in the post list 

Agreed, good catch. For now it's going to use the same icon as the `Publish` button. I don't think it will cause confusion, but cc @mattmiklic just in case 😄

**Comment by mattmiklic** [comment]
> For now it's going to use the same icon as the Publish button. I don't think it will cause confusion, but cc @mattmiklic just in case 😄

That matches Calypso, so :shipit:

**Comment by nbradbury** [comment]
Clicking the "Submit" button doesn't do anything. We need to add `PostListButton.BUTTON_SUBMIT` to [this switch statement](https://github.com/wordpress-mobile/WordPress-Android/blob/bda808a5d19707ffdd6f9ebf61cf0d0088f2a5a6/WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java#L422).

**Comment by tonyr59h** [comment]
All set 👍

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
