### PR TITLE
Jetpack focus: Show full screen overlay for Jetpack Features

### LINKED ISSUE #17330: Jetpack Focus: Create a generic fullscreen overlay
Description

This dynamic overlay will be used for feature-specific overlays across the app.

Project Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #17330 and #17333 

This PR adds a feature-specific overlay for the Feature Removal Phase one. Screenshot of the feature-specific overlays is shown below in dark as well light mode. 

| Stats  | Notifications | Reader  | 
|---|---|---|
|Screenshot_20221108-041659|Screenshot_20221108-041907 (1)| Screenshot_20221108-041913|
|Screenshot_20221108-041638| Screenshot_20221108-041810| Screenshot_20221108-130130| |
| | |

### Known issues and Improvements
- The UI in landscape mode will be taken up in a separate PR 
- Analytics and tracking will be taken up in a separate PR 
- The logic for showing overlay in Site creation will be taken up in a separate PR 

### 1. Make sure that the Overlay is not shown 
1.  If Phase one is not started yet 
- Launch the WordPress app with a WP site and navigate to Stats/Reader/Notifications 
- Verify that the feature overlay is not shown 

2. If the site is a Self-hosted site

3. No shown on the Jetpack app 

### 2. Jetpack overlay is shown when Phase one is started 

The logic for testing whether the overlay is shown according to feature-specific overlay frequency or global-specific overlay frequency is implemented in `JetpackFeatureRemovalOverlayUtilTest`. 

- Launch WordPress app and go to My Site -> App Settings -> Debug settings ->  enable `jp_removal_one` 
- Close app and Launch the app again 

### Stats

1.  Navigate to Stats either through dashboard/widget/notifications 
2. Verify that the feature-specific overlay is shown 
3. Turn on dark mode 
4. Verify that the overlay is shown in Dark mode
5. Click on **Try the new jetpack app** button 
6. Verify that the user is redirected to the Jetpack app on the play store 

1.  Navigate to Stats either through dashboard/widget/notifications 
2. Verify that the feature-specific overlay is shown 
3. Click on **Continue to Stats** button
4. Notice that the overlay is dismissed and Stats are visible  

### Notifications feature
1.  Navigate to the Notifications tab either through the dashboard/system notifications 
2. Verify that the feature-specific overlay is shown 
3. Turn on dark mode 
4. Verify that the overlay is shown in Dark mode
5. Click on **Try the new jetpack app** button 
6. Verify that the user is redirected to the Jetpack app on the play store 

1.  Navigate to the Notifications tab either through the dashboard/notifications 
2. Verify that the feature-specific overlay is shown 
3. Click on **Continue to Notifications** button 
4. Notice that the overlay is dismissed and Notifications are visible  

### Reader 
1.  Navigate to Reader either through the dashboard/notifications 
2. Verify that the feature-specific overlay is shown 
3. Turn on dark mode 
4. Verify that the overlay is shown in Dark mode
5. Click on **Try the new jetpack app** button 
6. Verify that the user is redirected to the Jetpack app on the play store 

1.  Navigate to Reader either through the dashboard/notifications 
2. Verify that the feature-specific overlay is shown 
3. Click on **Continue to Reader** button 
4. Notice that the overlay is dismissed and Notifications are visible  

### 3. Make sure that the Unit tests logic is correct 
- Unit tests in [JetpackFeatureRemovalOverlayUtilTest](WordPress/src/test/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtilTest.kt),  
- Unit tests in [ReaderViewModelTest.kt](https://github.com/wordpress-mobile/WordPress-Android/pull/17432/files#diff-77197b524e2a22f8c727c207a2c5875699dfffc718c2e57dd01124270e827ced)
- Unit tests in [StatsViewModelTest](WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt)

## Regression Notes
1. Potential unintended areas of impact
Overlay is not shown properly

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and Automated tests 

3. What automated tests I added (or what prevented me from doing so)
Added unit tests in JetpackFeatureRemovalOverlayUtilTest, ReaderViewModelTest and StatsViewModelTest

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — COMMENTED** [review]
👋  @AjeshRPai  - I took a first pass at the code and have a few small comments. I need to dig in deeper into the "shown" logic and dates. I'll give that a go during my next review, but wanted to give you enough to keep moving. 

I'm impressed with the work so far. 👏 ❤️ 

See below for preliminary comments
- Should `.idea/checkstyle-idea.xml` be checked in or should this be removed from the PR?
- Nit: Run a reformat code on the  android:id="@+id/caption" TextView in `jetpack_feature_removal_overlay`
- In `JetpackFeatureFullScreenOverlayFragment` how do you feel about replacing 
`private val binding get() = _binding!!`. 
with
`private val binding get() = _binding ?: throw NullPointerException("_binding cannot be null")`
to eliminate the double bang (!!)
- Also in `JetpackFeatureFullScreenOverlayFragment`, wdyt about making the `rtlLayout` fun name a little bit clearer. The fun is not only checking the rtl is true/false, but also is setting the layoutDirection of the view. BTW: There is a `RtlUtils` that has a static method called `isRtl`. Hard to test without a wrapper and may not be worth it to change, but just thought I'd mention it.
- In `JetpackBrandingUtils` - I don't think you added any changes other than the "," at the end of the `private val analyticsTrackerWrapper: AnalyticsTrackerWrapper,`. Did you intend to add something here? If not, want to revert this file.

**Comment by AjeshRPai** [comment]
@zwarm Thanks for taking a look at the PR and giving me the suggestions 

> - Should `.idea/checkstyle-idea.xml` be checked in or should this be removed from the PR?

Removed the changes. Some issues with the local environment. Sorry 

>- Nit: Run a reformat code on the  android:id="@+id/caption" TextView in `jetpack_feature_removal_overlay`

Done 👍🏼 . I have reformatted the code and rearranged the views on top to bottom order in 6f14f2aa

> - In `JetpackFeatureFullScreenOverlayFragment` how do you feel about replacing 
`private val binding get() = _binding!!`. 
with
`private val binding get() = _binding ?: throw NullPointerException("_binding cannot be null")`
to eliminate the double bang (!!)

Yep makes sense. Have done the changes in https://github.com/wordpress-mobile/WordPress-Android/pull/17432/commits/750ced0ad7ece1f52069656a8416ba3a9b906835

>- Also in `JetpackFeatureFullScreenOverlayFragment`, wdyt about making the `rtlLayout` fun name a little bit clearer. The fun is not only checking the rtl is true/false, but also is setting the layoutDirection of the view. BTW: There is a `RtlUtils` that has a static method called `isRtl`. Hard to test without a wrapper and may not be worth it to change, but just thought I'd mention it.

Yep, thanks. I have removed the function and added `RtlUtils.isRtl` for checking whether its RTL. I have done a manual testing of the screens in RTL to ensure that this works as Intended.  Done in https://github.com/wordpress-mobile/WordPress-Android/pull/17432/commits/750ced0ad7ece1f52069656a8416ba3a9b906835


>- In `JetpackBrandingUtils` - I don't think you added any changes other than the "," at the end of the `private val analyticsTrackerWrapper: AnalyticsTrackerWrapper,`. Did you intend to add something here? If not, want to revert this file.

Yep, reverted the change in commit https://github.com/wordpress-mobile/WordPress-Android/pull/17432/commits/750ced0ad7ece1f52069656a8416ba3a9b906835

**Comment by shaunandrews** [comment]
Nice work!

I'm able to see the overlay every time I tap on Stats, but I only saw it once when tapping on Reader and Notifications. Is this intentional? (To be clear, it _shouldn't_ show every time in "real life," but I wasn't sure about in this testing PR.)

When I tap on Stats, I see the overlay. If I dismiss it (tap "Continue..." or swipe down) I see my Stats. I then try tapping on the "Jetpack powered" banner, expecting to see the overlay again — but nothing happens. Perhaps this is out of scope for this PR?

**Comment by AjeshRPai** [comment]
>Nice work!

Thanks shaun 👍🏼 

>I'm able to see the overlay every time I tap on Stats, but I only saw it once when tapping on Reader and Notifications. Is this intentional? (To be clear, it shouldn't show every time in "real life," but I wasn't sure about in this testing PR.)

Yeah shaun, for testing purposes I enabled the overlay to be shown everytime the feature pages are loaded. Since Notifications and Reader pages are loaded on launch, the overlay for notifications and reader might be visible only once per app launch.  The intended behaviour of the jetpack overlay is tested on the Unit tests and also can be tested by re-enabling one or two lines of code. Once I have 👍🏼  from @JB184351 I can reenable it and the intended behaviour as mentioned on the Project thread can be tested. 

>When I tap on Stats, I see the overlay. If I dismiss it (tap "Continue..." or swipe down) I see my Stats. I then try tapping on the "Jetpack powered" banner, expecting to see the overlay again — but nothing happens. Perhaps this is out of scope for this PR?

Yes shaun. Showing Overlay on clicking the Banner is out of scope of this PR and is part of Jetpack powered Overlay project.

**Comment by JB184351** [comment]
I get an `unknown client_id` error when trying to sign in on my Android device, what are the usual causes for this?

**Comment by JB184351** [comment]
While testing I noticed that if I rotate the device while viewing the Stats page the overlay will keep popping back up, even after dismissal, here's a screen recording below to demonstrate this.

https://user-images.githubusercontent.com/36495451/200893074-0a07e45f-8f44-4a08-918f-e4b137f53816.mp4

**Comment by hassaanelgarem** [comment]
> the overlay for notifications and reader might be visible only once per app launch

@AjeshRPai, Will this always be the case? If yes, then I think we should check whether we should display the overlay or not when the view appears instead of when it loads. What do you think?

**Comment by AjeshRPai** [comment]
>While testing I noticed that if I rotate the device while viewing the Stats page the overlay will keep popping back up, even after dismissal, here's a screen recording below to demonstrate this.

Hey @JB184351 I made some changes to the overlay display logic because of which it's being displayed every time the view gets loaded. As said in slack, I will create a separate draft PR for testing. 


>If yes, then I think we should check whether we should display the overlay or not when the view appears instead of when it loads. What do you think?

@hassaanelgarem You are correct. Silly mistake. Thanks for pointing it out. I will update the logic for showing overlay when the view appears than when it loads. 

I am also updating the UI of this PR according to this [conversation](p1668183226582009-slack-C04564QS0V7) in slack. 

Changes yet to be done 
- Remove the swipe to dismiss logic
- Add the dismiss button 

I am marking this PR as not ready for review until the above changes are pushed.

**Comment by AjeshRPai** [comment]
@JB184351 @shaunandrews @zwarm  👋🏼 

👀  This PR is ready for a re-review now. I have 
- Removed the swipe to dismiss logic
- Added the dismiss button 
- Removed the testing logic 

@JB184351
In order to test the overlay frequency logic you can use the Draft PR -  https://github.com/wordpress-mobile/WordPress-Android/pull/17475

In addition to the PR, the tests for the frequency logic exist in the class `JetpackFeatureRemovalOverlayUtilTest`

cc:@zwarm

**Comment by shaunandrews** [comment]
With the "X" close button added, I noticed that it doesn't line up with the rest of the screen:

CleanShot 2022-11-18 at 14 13 20@2x

---

I also looked a little closer at the colors for the button, and it seems they're using a lighter green which produces a contrast issue:

CleanShot 2022-11-18 at 14 12 05@2x

In the designs we're using `jetpack-green-50` (#008710) for the greens.

**Comment by enejb** [comment]
@AjeshRPai `jetpack-green-50` has a hex value of `#008710`

**Comment by AjeshRPai** [comment]
@shaunandrews Thanks for reviewing the PR. 

@enejb Thanks for providing the `jetpack-green-50` values. 

I have updated the UI with 

- **Aligning the close button with the rest of the screen** 

Screenshot_20221121-145122

- **Updated the colour of the Primary button and the text in the secondary button `jetpack-green-50`**

|Secondary button text colour | Primary button colour background|
|---|---|
|Screenshot_20221121-150338|Screenshot_20221121-150345|


Commit - 1ce8fe55

In case anyone is wondering how I checked the alignment and colour of the elements in the UI - I am using this [app](https://play.google.com/store/apps/details?id=com.scheffsblend.designertools&hl=en_IN&gl=US&pli=1) on my physical device to check the alignment and colour of the elements as shown on the screenshot.

**Review by zwarm — APPROVED** [review]
@AjeshRPai - with the exception of landscape mode, all is working as expected. 
I ran all the unit tests + manual testing on a device (WP & JP)

Thanks for all the great work 👍

**Comment by osullivanchris** [comment]
Alignment and color looks good in the updated screenshots, thanks @AjeshRPai  👍

**Review by JB184351 — APPROVED** [review]

**Pull request merged**
