### PR TITLE
Add adaptive icon

### LINKED ISSUE #5529: New adaptative launcher icon for Android O
See https://developer.android.com/preview/features/adaptive-icons.html

### PR DESCRIPTION
**Pull request by jasmussen**
This attempts to address #5529. It adds app icon back and foregrounds, and an adaptive asset.

The ongoing conversation right now is whether this looks good in the shapes other than the round version. This particular version of the icon uses a 3dp padding around the WordPress logo. Should we try a 4dp version?

Fixes #5529 

To test:

- Build this branch on a Oreo device
- Test that the icon looks good
- Try and "jiggle" the icon to see the shape inside parallax
- If you have the Google Pixel launcher, you can long press the homescreen to test other icon shapes, like square and squircle

Screenshots:

screenshot_20171115-102552

screenshot_20171115-102535

screenshot_20171115-102525
screenshot_20171115-102501

screenshot_20171115-102512

### CODE REVIEW

**Comment by folletto** [comment]
I agree that kind of closeness to the border suits better the round shape, but I recall we tried other solution and while they might have worked with the other shapes, they would make the round one odd.

I'd say we can start releasing this one. ;)

**Comment by jasmussen** [comment]
The version shown in this branch has 3dp padding between the safe area and the logoshape.

Here's a version that has 4dp padding between the safe area and the logoshape:

screenshot_20171115-125857
screenshot_20171115-125909
screenshot_20171115-125923

Here's a version that has 5dp padding between the safe area and the logoshape:

screenshot_20171115-130312
screenshot_20171115-130326
screenshot_20171115-130337

**Comment by folletto** [comment]
Interesting. I didn't expect this but while the circle one feels still ok as before, the others are way better. 👍

**Comment by jasmussen** [comment]
Nice. You're referring to the 4dp version right?

**Comment by folletto** [comment]
4dp, yes :)

**Comment by jasmussen** [comment]
Check. I've just left the office where I have Android studio set up, so I'll update tomorrow, but meanwhile perhaps the code can be reviewed. I noticed a few checks failing.

**Comment by mattmiklic** [comment]
Agreed, the 4dp version feels great. Using 4px feels more in line with the Material grid, too.

**Comment by jasmussen** [comment]
Sorry, came down with a sickness. I'll be back in action monday, and yes I can get you an SVG (and I'll make sure it's the size of the version that has 4dp padding),  though I would appreciate help implementing it as I haven't yet worked with vector drawables in Android yet. Something something XML conversion?

**Comment by theck13** [comment]
You can actually use Android Studio 3.0 to translate SVG into XML by going to File > New > Image Asset.  There you can browse to the SVG for the foreground and background layers as well as create legacy icons.

In this case, the SVG's are pretty simple so you can create the XML files manually.  The background is a solid color (i.e. [blue_medium](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/colors.xml#L38)) and the viewport is a square (i.e. 108.0 x 108.0) so the background XML would be this

``` xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="108dp"
    android:width="108dp"
    android:viewportHeight="108.0"
    android:viewportWidth="108.0" >

    <path
        android:fillColor="@color/blue_medium"
        android:pathData="M0,0h108v108H0V0z" >
    </path>

</vector>
```

The foreground XML would be nearly identical except for the `android:fillColor` and `android:pathData` values.  Take the path from the SVG, insert it into the `android:pathData` field below, and you're done.

``` xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="108dp"
    android:width="108dp"
    android:viewportHeight="108.0"
    android:viewportWidth="108.0" >

    <path
        android:fillColor="@color/white"
        android:pathData="INSERT_SVG_PATH_HERE" >
    </path>

</vector>
```

**Comment by jasmussen** [comment]
Thanks @theck13, appreciate it. 

I have to jump on some other things so I didn't have time to try and make the resource. But here's an SVG I believe you can use if you'd like: 

[app_icon_foreground@1x.svg.zip](https://github.com/wordpress-mobile/WordPress-Android/files/1487224/app_icon_foreground.1x.svg.zip)

- Canvas is 108dp size
- Logo shape is 64dp size (the safe / visible area is 72dp, so a 64dp is what's left after we subtract 4dp padding on all sides)

**Comment by theck13** [comment]
I updated the adaptive icon from raster to vector in 83dc909492d727e02c736b87a3f368d536380027.  See the animations below for behavior.  Click on an animation to see it in full-resolution.

**Comment by jasmussen** [comment]
Thanks a bunch for the help @theck13. I think this looks stellar, and completely ship ready. [This image](https://user-images.githubusercontent.com/3827611/33045780-40e8fd48-ce0b-11e7-8d56-2b1e820060cb.gif) is especially convincing, I feel like the logo looks great in circle and pretty good in the rest of them too (definitely much better than "good enough"). 

I'll defer to @mattmiklic and @folletto of course on the final word. Excited to see this happen!

**Comment by mattmiklic** [comment]
I think this looks great. Thanks for the attention to detail, @jasmussen and @theck13! :shipit:

**Comment by jasmussen** [comment]
Do I merge this myself or would one of you do the honors? 🎉

**Pull request merged**
