### PR TITLE
Issue/update pages item ui

### LINKED ISSUE #11133: Update labels on page list items
Goal of this task is to introduce/update labels shown on page list items as per p8g8V2-eE-p2.

- [ ] Add an "Uploading ..." label

### PR DESCRIPTION
**Pull request by malinajirka**
Partially fixes #11133 

Merge instructions:
1. https://github.com/wordpress-mobile/WordPress-Android/pull/11191 needs to be merged first.
2. Update target branch to `master_page_offline_support`
3. Merge

Updates the layout of the PageList list items to match the layout of PostList items. I've copy pasted the post list compact item layout so there shouldn't be any issues.

Before|After
-|-
Screenshot_1581080900|Screenshot_1581080819
Screenshot_1581080892|Screenshot_1581080812

To test:
We'll continue working on the PageList. So I don't think we need to do detailed tests.
- Open Page List and make sure the items look ok
- Try to upload a post and make sure the progress bar looks ok
- Make a change to the post and leave the editor without saving the chagnes ->make sure the "Local changes" label looks ok

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

cc @mbshakti Could you please just quickly check the design. I think it should exactly match the design on PostList, but just to be sure I didn't overlook something (one difference is, that the "Local changes" label isn't yellow - we plan to add this in a different PR).  Thanks!

### CODE REVIEW

**Comment by jd-alexander** [comment]
I reviewed this and it works as expected! I’m going to review again today. The design review has to be completed before this is merged right ?

**Comment by malinajirka** [comment]
>The design review has to be completed before this is merged right ?

I think that'd be ideal since I didn't confirm this change with a designer. It just felt weird the two list were looking differently + I needed more space for the labels.

**Comment by malinajirka** [comment]
@jd-alexander I've talked to Shakti and I'd suggest merging this PR since other PRs are based on this branch. We are merging it into a working branch so it won't get released to our users before the design review is done. Thanks!

**Comment by mbshakti** [comment]
The rows match post lists - lgtm!

**Pull request merged**
