### PR TITLE
Issue/udpate author location

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the author filter from the right/end to the left/start of the tab layout on the ***Blog Posts*** screen as described in https://github.com/wordpress-mobile/WordPress-Android/issues/9689.  The author filter image does not fall into the 16dp left/start keyline intentionally.  It was requested to vertically align the center of the author filter image with the center of the back arrow icon above it.  Also, the touch target for the author filter was expanded to fill the width of the view and match the height of the tabs.  See the screenshots and animation below for illustration.

post_list_author

post_list_author_60

### Test
0. Set app language to English.
1. Go to ***Sites*** tab.
2. Tap ***Blog Posts*** under ***Publish*** section.
3. Notice location of author filter in tab layout.
4. Long-press author filter.
5. Notice touch background.
6. Scroll ***Published***, ***Drafts***, ***Scheduled***, and ***Trashed*** tabs left/right.
7. Notice tabs scroll behind author filter with gradient between views.
8. Tap back arrow.
9. Go to ***Me*** tab.
10. Tap ***App Settings*** item.
11. Tap ***Interface Language*** item.
12. Tap ***Hebrew*** option.
13. Tap ***OK*** button.
14. Tap back arrow.
15. Repeat steps 1 through 7.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @theck13! LGTM - good job;)

Note: We've merged the `feature/master-post-filters` into `develop`. Could you please merge `develop` into the current branch and update the target branch to `develop`. Thanks!

**Comment by SylvesterWilmott** [comment]
It looks pretty good @theck13 

I noticed that the avatar isn't horizontally centred inside of its container, ie. there's slightly more padding on the right than the left. Is this to keep it aligned to the 16dp gutter? Would you mind adding a screenshot where the avatar is exactly centered?

**Comment by theck13** [comment]
I merged `develop` and changed the target branch, @malinajirka.

> I noticed that the avatar isn't horizontally centred inside of its container, ie. there's slightly more padding on the right than the left. Is this to keep it aligned to the 16dp gutter? Would you mind adding a screenshot where the avatar is exactly centered?

Yep, there is 4dp padding on the right/end of the author filter container to vertically align the center of the author filter image with the center of the back arrow icon above it.  If the author filter image is centered in the container, it will neither left-align with the 16dp keyline nor center-align with the back arrow.  Also, that will overlap the gradient view between the author filter image and the tabs.  This is easier to see if the tab background is set to white for the current implementation.  See the screenshots below for illustration.

post_list_author_white

**Comment by theck13** [comment]
An alternative to the off-centered author filter container issue would be to remove the 4dp right padding and add 4dp left margin.  See the screenshots below for illustration.

post_list_author_56

There are a few side effects with that; one positive, one negative, one maybe positive and maybe negative.  The author filter image would left-align with the 16dp keyline.  The 4dp left margin looks a little weird when the author filter container is tapped (i.e. why doesn't the touch background go all the way to the edge?).  The width of the gradient view between the author filter image and the tabs would decrease from 16dp to 12dp.

**Comment by malinajirka** [comment]
>I merged develop and changed the target branch, @malinajirka.

Thanks;), I'll review it and merge as soon as @SylvesterWilmott finishes the design review.

**Comment by SylvesterWilmott** [comment]
@theck13 Okay yeah, it doesn't look great with the 4dp left margin.

Let's use the padding that you suggested initially.

A few more things:

- I only just noticed that the avatar is a little smaller than in the designs, could we bump the size up to 28dp
- Let's increase the white border on the avatar to 2dp, at 1dp there's some weird anti-aliasing
- Can we increase the right padding on the author selection menu? It should be 24dp

**Comment by theck13** [comment]
> * I only just noticed that the avatar is a little smaller than in the designs, could we bump the size up to 28dp

The author filter image in the screenshots above is [30dp](https://github.com/wordpress-mobile/WordPress-Android/pull/9697/files#diff-a38f8955f26ed07cc283ff53e02b57dbR370) with a [1dp](https://github.com/wordpress-mobile/WordPress-Android/pull/9697/files#diff-a38f8955f26ed07cc283ff53e02b57dbR371) stroke making the avatar 28dp.

> * Let's increase the white border on the avatar to 2dp, at 1dp there's some weird anti-aliasing

I updated the author filter image stroke to 2dp in cc49d76368.  Consequently, I updated the author filter image to 32dp in b0c39cdb81 to account for the new stroke/padding.  See the screenshots below for illustration.

Before|After
-|-
post_list_author_image_before|post_list_author_image_after

> * Can we increase the right padding on the author selection menu? It should be 24dp

I updated the right/end padding on the author filter menu to 24dp in 884f4ecaba.  See the screenshots below for illustration.

post_list_author_image

**Comment by SylvesterWilmott** [comment]
Looks great @theck13 !

**Pull request merged**
