### PR TITLE
Merge 23.3 code freeze string to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**
In https://github.com/wordpress-mobile/WordPress-Android/pull/19213, I think I created the merge branch from the wrong commit, so there are 2 commits from the code freeze that didn't make it to `trunk`. This PR merges those commits as well as the changes from #19214.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
LGTM! 💯 

> #19213, I think I created the merge branch from the wrong commit, so there are 2 commits from the code freeze that didn't make it to trunk.

Ah, apologies @oguzkocer , I wonder how I would have seen that [this](https://github.com/wordpress-mobile/WordPress-Android/pull/19219/commits/656850e194266854e7838d4e9bdd1c6c3696d459) and [this](https://github.com/wordpress-mobile/WordPress-Android/pull/19219/commits/88bb67a5d659e07ccb952266c2670b9f031e83a7) were missing and request changes instead of approving it (for next time)? 🤔

FYI: When I work on such release PRs, I personally have a template with a list of all the commits that such PR might be having, then work it out myself from them, removing anything from that template that is not valid for a specific release PR, and this way I am also hoping to help a reviewer review the change ([example](https://github.com/woocommerce/woocommerce-android/pull/9667)).

> This PR merges those commits as well as the changes from #19214.

👍

**Comment by oguzkocer** [comment]
> Ah, apologies @oguzkocer , I wonder how I would have seen that [this](https://github.com/wordpress-mobile/WordPress-Android/pull/19219/commits/656850e194266854e7838d4e9bdd1c6c3696d459) and [this](https://github.com/wordpress-mobile/WordPress-Android/pull/19219/commits/88bb67a5d659e07ccb952266c2670b9f031e83a7) were missing and request changes instead of approving it (for next time)? 🤔

Not at all @ParaskP7. This was totally on me. It's worth noting that it's completely fine to merge a partial PR, we just need to make sure that we follow that up and merge the remaining quickly especially if it contains string changes.

We don't really get code freeze merge conflicts very often, since it happens in just an hour or two, but this time I was unlucky and didn't pay enough attention. Sorry about that!

---

This is one of the minor issues with the release management in CI. Since the remote moves outside of relese manager's control, we need to pay special attention to update our local environments before creating a new branch from the `release/x.y` branch.

I think the solution to this - and merge conflicts in general - is to create a merge branch before opening the `Merge release/x.y branch to trunk` PRs. That way the release manager will resolve the conflict from the same PR, instead of creating a new branch and opening a new PR from it.

The only downside to that would be `release/x.y` won't be automatically deleted at the end of the cycle, but that seems like a good tradeoff to me - and we have a step for that in the release scenario anyway. I'll probably work on that next time we are working on release management in CI improvements - which hopefully is not too far away.

**Comment by ParaskP7** [comment]
👋 @oguzkocer and thanks for the reply! 🙇 

> This is one of the minor issues with the release management in CI. Since the remote moves outside of relese manager's control, we need to pay special attention to update our local environments before creating a new branch from the release/x.y branch.

👍 

> I think the solution to this - and merge conflicts in general - is to create a merge branch before opening the Merge release/x.y branch to trunk PRs. That way the release manager will resolve the conflict from the same PR, instead of creating a new branch and opening a new PR from it.

Indeed, that sounds like a solution to this! 💯 

> The only downside to that would be release/x.y won't be automatically deleted at the end of the cycle, but that seems like a good tradeoff to me - and we have a step for that in the release scenario anyway.

A minor downside, but as you said, I too wouldn't worry about it too much. 👍

**Comment by AliSoftware** [comment]
FWIW, in Tumblr fastfiles, we:
 - Call `ensure_git_branch` to check that we're running the lanes from the expected branch
 - Call `git pull` at the start of many if not all PRs, to make sure we're up-to-date before starting
 - Systematically create an intermediate branch when we make the Fastfile create GitHub PRs, so that we can use it in case there ends up being conflicts.

**Pull request merged**
