### PR TITLE
Gutenberg mobile release v1.7.0

### PR DESCRIPTION
**Pull request by hypest**
This PR updates the gutenberg-mobile reference to point to the latest release, v1.7.0.

The reference is currently pointing to the release/1.7.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1116.

To test:
The block editor should work as normal.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mkevins** [comment]
I've tested this out on Android emulator (Pixel 2, Android 8.1.0) by adding and interacting with all the available block types. Everything seems to be working as expected for the most part.

I tested pressing [Enter] in the title, and that works as expect. I tested pasting in the title, and that does not crash :tada: .

A few issues I did notice:

On lists, after merging two list items, then subsequently splitting them, the second list item is missing the bullet. I believe I've seen this before, and it may be a known issue, but I'm noting it so it in case it's not.

On video blocks, I have not been able to see the video after uploading one. Instead, I only see a black rectangle. In preview mode, I see:


 Also, I get some logcat entries like this:
```
2019-06-11 21:49:14.243 6226-7177/org.wordpress.android E/WordPress-MEDIA: The passed video path is invalid: https://storeadmintestsite123.blog/vid_20190529_162012-1-mp4/
2019-06-11 21:49:14.244 6226-7177/org.wordpress.android W/WordPress-MEDIA: Failed to retrieve frame from the passed video path: https://storeadmintestsite123.blog/vid_20190529_162012-1-mp4/
2019-06-11 21:49:14.346 6226-6226/org.wordpress.android V/WordPress-MEDIA: Fetched media list for site with size: 3
```

Lastly, I confirmed that the caret position is not correct after pasting into an empty paragraph block, as reported here: https://github.com/wordpress-mobile/WordPress-iOS/pull/11885#pullrequestreview-248123236.

**Comment by daniloercoli** [comment]
I've tested this PR on my S9 and didn't find new problems with the GB block editor.

I see issues with Videos files, but those problems are also present in the Media library of the app, where the device fails to load them. So it's not a problem related to the Editor component.

**Comment by mkevins** [comment]
I've done some more smoke testing on this release, and so far, things are looking very nice. :tada: 

Some additional (minor) issues I've encountered:

**Image caption alignment:**
It seems that the image caption center alignment gets lost when the post is updated. The caption becomes left aligned after any of the following:

* Leave the post and open it again
* Click update
* View preview and then switch back to visual mode

**Small images are left aligned:**
This may not be an issue, but since the caption is center aligned, I'd expect that images would be center aligned as well.

**Headings look like paragraph font in preview:**
When previewing, I noticed that all three heading types (H2, H3, H4) appear with the same font styles as plain text paragraph content (i.e. no larger or stronger typeface).

**Comment by hypest** [comment]
> Image caption alignment:

I think it's the same issue reported with https://github.com/wordpress-mobile/gutenberg-mobile/issues/1070

> Small images are left aligned

Reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/830

> Headings look like paragraph font in preview
Known WPAndroid issue, not related to the block editor https://github.com/wordpress-mobile/WordPress-Android/issues/9916

**Pull request merged**
