### PR TITLE
Issue/5310 premium themes link

### LINKED ISSUE #5310: Add link to premium themes selector in Themes section in app
Currently the apps only offer free themes. We want to let our users know there are premium themes they can obtain in the web.

I'd add it right below the search bar after you tap on it (the "Current theme" section is hidden and the search tab gains a prominent space occupying the whole header space), so this way we are sure the user is attempting to search for a theme as their intent is clear.

This is the action that makes the search bar go to the top, hiding the "Current theme" section: 

themes

This is the place we'd use for the CTA:

screen shot 2017-03-01 at 12 46 32 pm

Something like  **“Hey, want more? We have premium themes! go here <link>”.**

Link is `https://wordpress.com/design/premium/<site domain url>`

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #5310 by adding a premium themes link at the bottom of the screen (consistently with the Plans section)

screenshot_20170306-160334

To test:

1. open the Themes section in the main tab
2. tap on the search bar
3. the blue bottom button is shown, and you can explore premium themes by tapping on it (an external browser is opened)

### CODE REVIEW

**Comment by nbradbury** [comment]
If there are no search results, the "premium themes" label is hidden until the soft keyboard is closed.

screenshot_1488977399

**Comment by nbradbury** [comment]
Instead of using a solid label with a chevron, what do you think about showing a hyperlink?

screenshot_1488977684

**Comment by nbradbury** [comment]
The experience when you're not logged in on the browser is pretty bad. You're sent to a mostly blank page with a login/signup link at the top.

screenshot_1488977434

**Comment by nbradbury** [comment]
Related to the above, if you login from that page, you're taken to the reader instead of the themes page you expected. I realize this isn't an issue with the app, but do we really want to direct users to a confusing experience?

screenshot_1488978131

**Comment by mzorz** [comment]
Right - it would be great to make this PR wait to be merged until this other issue gets solved #5077
- ok on showing a hyperlink instead of the chevron
- will check in with the blank page / soft keyboard hiding it

**Comment by nbradbury** [comment]
> Right - it would be great to make this PR wait to be merged until this other issue gets solved #5077

Ah, sorry - I hadn't noticed that #5077 would resolve this.

**Comment by maxme** [comment]
Should we still wait for  #5077 to be fixed?

**Comment by mzorz** [comment]
Closing this - premium themes being handled elsewhere now - thanks @nbradbury for the heads up

**Pull request closed without merging**
