### PR TITLE
[Modal Layout Picker] Add support for Self-Hosted sites

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2455

**Related PRs:**
- **Depends on**: https://github.com/wordpress-mobile/WordPress-Android/pull/12943
- **API call**: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1702

## Description

This PR populates the MLP UI for self-hosted sites with data fetched from `/wpcom/v2/common-block-layouts`.

## To test:

Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

### Regular Flow
1. With a good network connection
1. Open the app and select a Self-Hosted site (e.g. https://rainy-koala.jurassic.ninja)
1. Open the Modal Layout Picker
1. **Expect** to see a brief ghost of while the data is fetched
1. **Expect** to see the screen updated with the fetched layouts
    - Layouts in the filter bar should be in alphabetical order
    - The sections in the table view should match the order of the categories in the filter bar
1. You should be able to select a layout from a category. 

### Slow Network
1. With a slow network connection (e.g. by changing the cellular configuration in an emulator).
1. Open the app and select a Self-Hosted site
1. Open the Modal Layout Picker.
1. **Expect** to see a ghost of empty cells while the data is fetched.
    - You should not be able to select a cell or category while the data is being fetched.
1. **Expect** to see the screen updated with the fetched layouts
    - Layouts in the filter bar should be in alphabetical order
    - The sections in the table view should match the order of the categories in the filter bar
1. You should be able to select a layout from a category. 

### No Network
1. Disable your device's connection ( e.g. airplane mode)
1. Return to the app and select a Self-Hosted site
1. Open the Modal Layout Picker.
1. **Expect** to see a ghost of empty cells while the data is fetched.
    - You should not be able to select a cell or category while the data is being fetched.
1. You should be able to still create a blank page
    - 📝We will be using cached data for this flow in the future.

## Screenshots:

<image width="360" src="https://user-images.githubusercontent.com/304044/94276029-5a8edc80-ff50-11ea-9575-21b5bfd287f5.gif">

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Changes looks good @antonis 👍.

Just mentioning two issues (might not require any action)

1. Some of the categories are translated in the top bar (for a non-English language) but layout titles are still shown in English. 

translation

2. On selecting a layout (e.g. Team) page and press back, app sometimes becomes unresponsive and crashes

crash

Seems like it is a known issue on debug builds:
```
java.lang.RuntimeException: Debug build crash: Post had changes that needed to be saved when exiting the editor, and there was NOT an autosave pending. This means that the editor's autosave mechanism failed. This only crashes on debug builds.
        at org.wordpress.android.ui.posts.EditPostActivity.lambda$updateAndSavePostAsyncOnEditorExit$16$EditPostActivity(EditPostActivity.java:1662)
```

Thought to mention since it happened consistently for the "Team" layout.

**Comment by antonis** [comment]
Hello @ashiagr 👋 ,

> 1. Some of the categories are translated in the top bar (for a non-English language) but layout titles are still shown in English.

Since all content is returned with the same API call I guess this is a data issue. I will check with @enejb and @chipsnyder on this. 

> 2. On selecting a layout (e.g. Team) page and press back, app sometimes becomes unresponsive and crashes

I'll investigate further if I can handle this on my side. It seems to be related with the [updateAndSavePostAsyncOnEditorExit function](https://github.com/wordpress-mobile/WordPress-Android/blob/2ea185764149d988ba2ed752716199480a6aed6f/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1644)

Thanks again for your feedback 🙇

**Comment by malinajirka** [comment]
> I'll investigate further if I can handle this on my side. It seems to be related with the updateAndSavePostAsyncOnEditorExit function

@antonis This is expected behavior and the app crashes only in debug mode.

**Comment by malinajirka** [comment]
I'm sorry for the confusion, but I mystified you.

When the message says `Post had changes that needed to be saved when exiting the editor, but there was an autosave pending.` than it’s a known issue and we should just ignore it.

When the message says `Post had changes that needed to be saved when exiting the editor, and there was NOT an autosave pending. This means that the editor’s autosave mechanism failed.`  It’s an unknown issue and we should investigate what’s wrong.

So in our current case it’s not ok and we should investigate why gutenberg didn’t let us (EditPostActivity) know that the content of the post has changed.

**Comment by antonis** [comment]
Hello @malinajirka , @ashiagr 👋 
I opened a GB-Mobile issue on this at https://github.com/wordpress-mobile/gutenberg-mobile/issues/2701

**Review by chipsnyder — APPROVED** [review]
Tested this out with the included build and everything is working well 👍

**Pull request merged**
