### PR TITLE
Improvements: Dashboard UI 

### LINKED ISSUE #19772: Dashboard cards implemented with Jetpack compose have a background
### Expected behavior
The cards on the dashboard shouldn't have a background outside the rounded corners

### Actual behavior
Screenshot 2023-12-07 at 7 02 07 PM

Notice that there is a background outside the rounded corners. This behaviour exists in the following cards 
- Blaze Campaigns Card 
- Personalize card
- Bloganuray Card
- Domain Dashboard Card

### Steps to reproduce the behavior
Login to the app with an admin account + jetpack site

### PR DESCRIPTION
**Pull request by AjeshRPai**
## Fixes
#19772

## Description
This PR makes the following changes 
1.  Removes the site info header from my site fragment - A `SiteInfoHeaderCardViewHolder` is added to render the site header instead of my site fragment. This will improve the rendering time and will also help us when converting the views to compose 
2. Fixes the background color in the compose cards 

| Before  | After   |
|---|---|
| Screenshot 2023-12-07 at 6 59 17 PM | Screenshot 2023-12-12 at 4 25 32 PM |  

 - Blaze Campaign
 - Bloganuary Nudge Card
 - Personalize card 
 - Domain dashboard card 

3. Adds a haptic feedback to the bottom nav 

## To Test:
1. Login to the Jetpack app 
2. Go to the dashboard 
3. Verify that the dashboard is rendered as before
5. Verify that there are no background in compose cards 
6. Verify that on switching between the bottom nav items(my site, reader, notifications, me) , there is a haptic feedback 

## Regression Notes

1. Potential unintended areas of impact
N  

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by zwarm — COMMENTED** [review]
@AjeshRPai - so far, so good. The site header functions as normal (clicks on title, icon, launching the site selector). To my eye, I do not see the background color on cards, but in layout inspector I see the corners. Not sure if this should be the case or I am not testing it correctly. 

Alt desc

**Comment by AjeshRPai** [comment]
Hey @zwarm 

>To my eye, I do not see the background color on cards, but in layout inspector I see the corners. Not sure if this should be the case or I am not testing it correctly.

I think thats ok, can u also check if the cards built using XML also has corners. As much as I checked all cards has corners in layout inspector. So that's ok.

**Comment by zwarm** [comment]
@AjeshRPai 

> I think thats ok, can u also check if the cards built using XML also has corners. 

I checked XML and see the same corner , so 👍

**Review by zwarm — APPROVED** [review]
@AjeshRPai - Adding my approval. Will wait for @osullivanchris to give the thumbs up before merging.

**Review by osullivanchris — APPROVED** [review]

**Pull request merged**
