### PR TITLE
CONTRIBUTING.md: Add information about our PR merge policy

### PR DESCRIPTION
**Pull request by AliSoftware**
Similar addition to our contributing guidelines as https://github.com/wordpress-mobile/WordPress-iOS/pull/15170, but adapted to the Android workflow

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AliSoftware** [comment]
_Side note: Using this PR to test the new `@wordpress-mobile/release-managers` team we just created. Note that this new team should usually be used only for Release PRs while we'd still continue to use the `@wordpress-mobile/platform-9` for Tooling PRs like this one to affect three random P9 members, instead of every single MIE in P9 like `release-managers` does)_

**Review by mokagio — APPROVED** [review]
Thank you for working on this @AliSoftware, and for creating the "release managers" team ❤️ 

I like how clear and explicit this is. On the other hand, other than the last part regarding how a reviewer how approved the PR should merge it, everything else is automated, can be automated (a Peril check to make sure PRs have an assignee?), or configured in the repo settings (disable "squash and merge" and "rebase and merge").

I don't mind the verbosity of it, but I feel like we could keep the document lighter if we only left what we cannot (yet?) enforce.

What do you think? I'm fine either way, so I'm leaving a ✅ to unblock this (_although I realize I'm not following the convention by not merging it immediately_ 😳😅)

**Comment by AliSoftware** [comment]
Yeah good point.

I actually thought about not mentioning the "1 reviewer approval needed" and "merge commit" given that they are (or can be) enforced by repo settings, but I feel like it's still nice to have this written down rather than any contributor wondering about our policy and not having admin access to our settings to check. I mean they don't need to if it's enforced, but that's still something that is interesting to share and document imho just for clarity and user documentation instead of the user wondering about it until they actually open the PR and investigate to see what's allowed to do?

As for labels and milestones, they are already enforced by Peril but I still thing it's worth mentioning them, because it's always nicer to know what you're supposed to do in advance before being yelled at by Peril that you forgot to do it. Peril is there to ensure you didn't forget to do it, but doesn't mean we shouldn't document what we expect so that contributors do the right thing right from the start. #CommunicationIsOxygen 😛

**Comment by mokagio** [comment]
> Peril is there to ensure you didn't forget to do it, but doesn't mean we shouldn't document what we expect so that contributors do the right thing right from the start. #CommunicationIsOxygen

Fair point 👍

**Pull request merged**
