### PR TITLE
Issue/4768 move edit button

### LINKED ISSUE #4768: Notification edit button moved to below comment
To make way for the up/down arrows in the nav bar, we'll be moving the edit button as shown in this mockup:

iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/6140

d4be49ca-a697-11e6-8b39-476219022ffd-2

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4768 

To test:

Click edit on a comment that can be edited

### CODE REVIEW

**Comment by mzorz** [comment]
@kwonye looks good and Edit works OK - but I noticed a problem with how the `LIKE` behaves, I think it's not painting the star asset correctly. Check video https://cloudup.com/cL4nhqFHNXA

**Comment by mzorz** [comment]
Also check the liked/unliked states, not sure they are represented correctly on the text itself (sometimes like appears in orange when it shouldn't, and viceversa).
In the video, first time we go into the item,  "Like" is shown all grey. There we just hit "approve", and that action makes the app return to the notifications list screen.
Then tap on that item again, and now the "Like" action is shown text orange and star grey. It should be at least the same way as before, right?

**Comment by kwonye** [comment]
Thanks for finding those bugs, @mzorz. I'll get on them today.

After reviewing #4796, my opinion is that this change doesn't conflict with that, meaning both can go in. What do you think?

**Comment by mzorz** [comment]
> After reviewing #4796, my opinion is that this change doesn't conflict with that, meaning both can go in. What do you think?

Let's go ahead then @kwonye ! ping me to re-check this PR when you see fit 👌

**Comment by kwonye** [comment]
@mzorz bugs addressed 👍

**Comment by mzorz** [comment]
Colours are ok, but still the Like action has a strange behavior. Will further investigate and ultimately address on another issue/pr

**Comment by mzorz** [comment]
🔥 :shipit:

**Pull request merged**
