### PR TITLE
Issue/3779 store plan name with blog

### PR DESCRIPTION
**Pull request by nbradbury**
This addresses the first part of #3779 by saving the short plan name with the blog object and displaying it on the My Site fragment.

cc @daniloercoli

### CODE REVIEW

**Comment by daniloercoli** [comment]
I think you should include the parameter `locale` to the REST call to `/me/sites`. Otherwise you could see something like the following:

screen shot 2016-02-23 at 23 58 15

The Plan name in the screenshot above is not localized to IT.

**Comment by nbradbury** [comment]
> I think you should include the parameter locale to the REST call to /me/sites

I think you're right that we need to add the `locale` param, but I suspect we need to add that to a number of other calls as well. Do you think this should be addressed in this PR or as a separate issue?

**Comment by daniloercoli** [comment]
> I suspect we need to add that to a number of other calls as well. Do you think this should be addressed in this PR or as a separate issue?

You're right. I think, however, that's better to fix the issue in the `/me/sites` call in this PR, and open a new ticket for all other calls in the app. 

Background: There are, unfortunately, different parts of the app that use string matching over the error string returned from the server to display a proper error to the user. This is due to some errors, returned from the server,  that have the same error_code, but different error_description.
Ticket is here: https://github.com/wordpress-mobile/WordPress-Android/issues/2789

**Comment by nbradbury** [comment]
@daniloercoli I added the locale param to `me/sites` in e9c59a8. Ready for another round!

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
