### PR TITLE
Issue/7892 save locally dialog

### LINKED ISSUE #7892: Save for later - show warning dialog informing posts are saved just locally
### Expected behavior
When the user saves a post for the first time a dialog is shown.

Title: Save Posts for Later

Body: “You can now save posts for later! For this version, saved posts are only saved to this device, but we are working on adding cross-device syncing!”

Actions: "OK"

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #7892 

Show a warning dialog informing the user that posts are saved just locally when they save a post for the first time.

screenshot_1528880124

To test:
1. Login
2. Go to reader
3. Click on the "save post" button
4. Dialog should be shown
5. Click on the "save post" button of another post
6. Dialog should not be shown
---
1. Clear app data
2. Go to reader
3. Open a post detail
4. Click on the "save post" button
5. Dialog should be shown

Note:
Dialog in the Reader list is not retained after configuration changes - ReaderFragment extends native android fragment instead of support fragment, so we can't use the BasicDialogFragment. 
Retaining basic alert dialog is also tricky, since we recreate the fragment from scratch after configuration change (without using savedInstanceState). 

cc @iamthomasbishop

### CODE REVIEW

**Comment by michelleweber** [comment]
Some tweaks:

Save Posts for Later
Save this post, and come back to read it whenever you'd like. It will only be available here -- saved posts don't sync to your other devices. (Yet! We're working on it.)

**Comment by malinajirka** [comment]
Thanks! 

Updated screenshot
screenshot_1528891198

**Comment by iamthomasbishop** [comment]
LGTM! Thanks for the review @michelleweber !

**Comment by malinajirka** [comment]
>We need to add BasicFragmentDialog.BasicDialogPositiveClickInterface to other activities that might use ReaderPostDetailFragment, like NotificationsDetailActivity or the app will crash.

Thank you for catching this!! I totally forgot to check other activities. It should be fixed now.

>Another really minor thing - we are using AlertDialog in reader list (disappears on configuration change), and fragment dialog in post details (persistent). Maybe we can standardize this behavior somehow? WDYT?

Hmm, unfortunately we can't use the fragment dialog in both places, because ReaderFragment extends native android fragment instead of support fragment. Using Alert dialog in support fragment seems like a bad practice to me. One solution would be to create second BasicFragmentDialog which would extend the native DialogFragment, but I think it's an overkill. 
I want to migrate all native fragments to support fragments during the next hack week - I'll keep a note to migrate all alert dialogs to fragments dialogs as well. Wdyt?

**Comment by iamthomasbishop** [comment]
After discussing the wording/dialog internally, I'm wondering if we can word the last part of this slightly differently. I've bolded the part in question below.

Currently:

"Save this post, and come back to read it whenever you’d like. **It will only be available here — saved posts don’t sync to your other devices. (Yet! We’re working on it.)**"

Proposal:

"Save this post, and come back to read it whenever you’d like. **It will only be available on this device — saved posts don’t sync to other devices (Yet! We’re working on it.)**"

"on this device" vs. "here" seems clearer. Thoughts, @michelleweber @malinajirka ?

// cc @frosty

**Comment by michelleweber** [comment]
+1! Clearer -- good suggestion.

**Comment by mzorz** [comment]
Modified the string as suggested by @iamthomasbishop  with permission from @malinajirka  in commit b4115e9b2f.

**Comment by mzorz** [comment]
Merging this one to make it to `10.2` beta-2, as the remaining work exceeds the purpose of the PR and has only been suggested / proposed as a minor (in the sense of non-blocking) observation  by @khaykov 🙇

**Comment by designsimply** [comment]
😍😍😍

**Pull request merged**
