### PR TITLE
Fix #6483: enable comments in the Reader for Jetpack sites

### LINKED ISSUE #6483: Jatpack: Add support for comments on reader
Comments for Jeatpack sites ares coming soon to reader, we want to fully support them in the apps.

iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/7660

### PR DESCRIPTION
**Pull request by maxme**
Fix #6483: enable comments in the Reader for Jetpack sites

### CODE REVIEW

**Comment by nbradbury** [comment]
@maxme This looks good and can be merged, but before I merge I wanted to make sure we want to enable JP comments in the app before they're available in the Calypso reader.

**Comment by maxme** [comment]
@nbradbury Yes, I tested a few sites and it worked well, but better to wait for that Calypso PR to be merged.

**Comment by maxme** [comment]
Note: enabled Reader comments for Jetpack sites - only for the `alpha` variant.

**Comment by nbradbury** [comment]
@maxme Shouldn't this flag be enabled for wasabi builds as well?

**Comment by maxme** [comment]
> Shouldn't this flag be enabled for wasabi builds as well?

Good idea, added in c2f3d56

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
