### PR TITLE
Refactor login prologue screen

### LINKED ISSUE #19841: Refactor Login Prologue screen
The entire login-related  codebase has to be refactored:
* Replace LoginPrologueFragment with LoginPrologueRevampedFragment and remove the feature flag.
* Move the entire LoginPrologueRevampedFragment logic to LoginPrologueRevampedViewModel.
* Get rid of an Android Context dependency from the LoginPrologueRevampedViewModel.
* Add tests to LoginPrologueRevampedViewModel.

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes #19841 

-----

## To Test:

- Install Jetpack app
- `Logout` if you're already logged in or Fresh install
- `Verify` Prologue screen is displayed at the start as in image above
- `Tap` on **Continue with WordPress.com** button
- `Verify`, able to login as before
- `Logout` if you're already logged in or Fresh install
- `Tap` on **Enter your existing site address**
- `Verify`, able to login as before
- `Test` WordPress app besides Jetpack app to ensure login is working

-----

## Regression Notes

1. Potential unintended areas of impact

    - No intended side effects

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Tested various login flows

3. What automated tests I added (or what prevented me from doing so)

    - TBD

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by tiagomar** [comment]
The changes related to the UI Tests look good. 👍

**Review by justtwago — APPROVED** [review]
I'm sorry for the delay.
Thank you for the fantastic code removal, Ravi! 🏅 I've tested both login methods and they worked as usual 👍 

I just found one interesting bug that is out of scope and couldn't find out if it's already been reported. When I log out from a self-hosted site, it does not log me out completely and breaks the app:

https://github.com/wordpress-mobile/WordPress-Android/assets/16563318/96616f75-7046-4805-98bc-4ac705399d7b

If it's not reported yet, I can create an issue.

**Comment by ravishanker** [comment]
> I'm sorry for the delay. Thank you for the fantastic code removal, Ravi! 🏅 I've tested both login methods and they worked as usual 👍

No worries!  It wasn't urgent.  Thanks for creating the issue in first place, and help in reviewing it 🙇 
> I just found one interesting bug that is out of scope and couldn't find out if it's already been reported. When I log out from a self-hosted site, it does not log me out completely and breaks the app:
> 
>  Screen_recording_20240319_103408.mp4 
> If it's not reported yet, I can create an issue.

There's an issue #19098 , not sure if it is related!  Either update it or create a new one (if it is not related)

**Pull request merged**
