### PR TITLE
Issue/5885 media download

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5585 - uses the Android DownloadManager to add the ability to save from the WP media browser to the local device.

To test: Open the WP media browser, tap an image to go to the full-screen preview, then tap the new Save icon to save it to the device.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Just a note, this PR fixes #5743.

**Comment by tonyr59h** [comment]
Nicely done! The only issue I found was trying to download an image without a network connection. The download icon is shown briefly in the notification bar then it disappears without indicating that the download failed. I think toasting an error would be a good idea here.

**Comment by nbradbury** [comment]
@tonyr59h Good catch - addressed in ae1cc86.

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
