### PR TITLE
Feature/move notification settings to notifications list

### PR DESCRIPTION
**Pull request by khaykov**
This PR moves Notifications Settings from Me screen to Notifications List.

I don't think there was a design for this one, so visuals are based on my assumption about how it should look like :)

[Image from Gyazo](https://gyazo.com/4c5870dec2741802375eb131e9ce545d)

To test:
- On the fresh app installation, login with a self-hosted site without Jetpack.
- Navigate to Notifications List.
- Notice Notifications Settings button is no there.
- Navigate to Me tab and login wot WordPress.com account.
- Navigate back to Notifications List.
- Notice that the Notifications Settings button is there and works!

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by loremattei** [comment]
I'm moving this to 13.2 since 13.1 has been cut. As usual, if you want this to make it to 13.1, feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by osullivanchris** [comment]
On iOS we're adding a small line of text to inform the user the feature has moved in case they cannot find it in the old position. Here's a mock for how that would look on Android. Is this ok to add, or would you like to create a separate task for that? CC @frosty 

notification settings moved notice

**Comment by khaykov** [comment]
@osullivanchris Thanks for taking a look! I added the note to the bottom of the list. Any ideas on copy?

Screenshot_1565758907

**Comment by osullivanchris** [comment]
@khaykov It looks like the copy for this is "Looking for notification settings? They’re in the Notifications tab — tap the cog." Per the comment on p2JRYi-48h

**Comment by frosty** [comment]
Thanks for updating this!

**Pull request merged**
