### PR TITLE
[Voice to Content] Implement frag/view model skeleton

### PR DESCRIPTION
**Pull request by zwarm**
Closes https://github.com/Automattic/wordpress-mobile/issues/75
Closes https://github.com/Automattic/wordpress-mobile/issues/74

This PR creates the skeleton classes for the Voice to Content feature. The intent is to have an entry point into the flow and be able to test FluxC calls.

Includes
- Add "Post to Audio" option to the My Site FAB (guarded by FF)
- Add the feature utils class to determine if the feature should be added to the FAB 
- Add a few resources
- Add a temporary audio file into the assets directory (this should be removed before release)
- Add the skeletons for VoiceToContentDialogFragment, VoiceToContentViewModel, and VoiceToContentUseCase

Note: No attempt was made to create production ready composables

-----
FAB Option | Entry view | Result view
-- | -- | --
Alt desc | Alt desc  | Alt desc

## To Test:
**Prerequisites**
- Install and launch the app
- Login into a site in which you have access to create posts

**Test Post from audio not shown**
- Navigate to My Site
- Tap the FAB
- ✅ Verify the options do not include Post from Audio

**Test Post from audio is shown**
- Navigate to Me > Debug Settings
- Enable `voice_to_content` and restart the app
- Navigate to My Site
- Tap the FAB
- ✅ Verify the options do include Post from Audio

**Test Post will show the transcribed text**
- Run Test Post from audio is shown
- Tap the microphone
- ✅ Verify the microphone disappears and the text "Testing Jetpack AI. Testing" is shown in the bottom sheet
-----

## Regression Notes
1. Potential unintended areas of impact
The feature shows when the flag is off

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Unit and manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

-----

## PR Submission Checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pantstamp** [comment]
@zwarm I tried to build the branch but I am getting some "Unresolved reference" errors in VoiceToContentUseCase. 

Do I need to link another FluxC version?

**Comment by zwarm** [comment]
> Do I need to link another FluxC version?

Trunk should be good ... let me take another look

**Comment by zwarm** [comment]
@pantstamp - Looks like my FluxC PR missed the latest release label. I updated this PR with the FluxC hash to point to the trunk version after my PR was merged yesterday. Let me know if you still run into issues. Thanks for bringing it to my attention.

**Review by pantstamp — APPROVED** [review]
Tested and it works like a charm! Thanks @zwarm for fixing the FluC dependency!

**Pull request merged**
