### PR TITLE
Create CODE-OF-CONDUCT.md

### PR DESCRIPTION
**Pull request by hoverduck**
Initial commit, has placeholder for contact form

### CODE REVIEW

**Comment by lancewillett** [comment]
Let's hold off merging until we get a few more eyes on it next week, maybe starting with @catehstn @codebykat for a review.

I've reached out to WordPress.org community team to ask about the best place for the contact emails to go — or if we can use the existing https://make.wordpress.org/community/contact/ form for this.

**Comment by hoverduck** [comment]
Also, a suggestion from @sendhil - 

> make it consistent with the Automattic diversity and inclusion page and include political affiliation

https://automattic.com/diversity-and-inclusion/

**Comment by codebykat** [comment]
Hi, thanks for tagging me in! It's great to see this happening! :grinning:

Since we're using the Contributor Covenant, I would strongly recommend that we avoid adjusting the language here, and instead take discussion about additions/changes to that upstream repository. This is also the one that we're using in Calypso, and I believe the WP community has a similar one as well. We should at the very least strive to be consistent within WP.

It is not intended as, nor in fact is it possible for it to be, an exhaustive list of the forms discrimination can take. But it does give us a framework to act inclusively in those situations. For example, derogatory comments about someone's political beliefs would likely fall under "personal attacks".

The context for A8c's D&I page is a bit different (since it's focused on our hiring policies), so I think it makes sense for it to be a somewhat wider frame. Political affiliation is also not generally considered a protected class.

Anyhow, there is an existing issue we could weigh in on here: https://github.com/ContributorCovenant/contributor_covenant/issues/17

I think it's more important to standardize on one thing and get it out there, and then if we have a situation come up in the future we can always iterate on it.

**Comment by catehstn** [comment]
Thanks @codebykat, I also think we should keep in line with the Contributor Covenant. Customising Code of Conducts usually goes about as well as customising an OSS license - you screw up, and end up with a bunch of people angry at you. A number of people who have a lot of expertise in this area put together the Contributor Covenant, and it's got a lot of feedback from the community. If anyone wants to weigh in on the original repo, we can pull down changes. (@hoverduck - maybe you can check in a subsequent PR if there are any changes we should pull down?)

When it comes to political views specifically, one thing that makes that challenging is what a political view even *is*. "Governments should run a deficit no greater than XXX of GDP" is, I guess, a political view? Or is it an economic one? Both? It's also something that is challenging internationally. Gun control is - as I understand it - a left political view in the US? But is a fact of life in Australia and most EU countries. Then we get to things like "women shouldn't vote", which I guess people can frame as a "political view" but sounds more like a manifestation of sexism (if this seems extreme, you might be interested to know that women did not get to vote in Switzerland until [1971](https://en.wikipedia.org/wiki/Women's_suffrage_in_Switzerland)).

Companies can arbitrate these kind of questions through an HR process, this is much harder to do in an OSS community. Part of the purpose of a Code of Conduct is to demonstrate a commitment to making an inclusive community. Deviations from an accepted standard (like the Contributor Covenant) are often taken as red flags by people who have historically been less welcome, especially when those deviations are things that are hard to arbitrate.

**Pull request merged**
