### PR TITLE
Add Gutenberg mobile strings for translation

### PR DESCRIPTION
**Pull request by Tug**
This PR manually adds the strings that needs to be translated in `gutenberg-mobile` to `res/values/strings.xml` which will thus be added to the WordPress Android glotpress project.

### CODE REVIEW

**Comment by koke** [comment]
This looks good to me, but I don't have enough Android experience, I'd like to see a 👍 from @wordpress-mobile/platform-9

**Comment by loremattei** [comment]
Yep! Strings look good to me. 
The CI is failing because of the linter. Maybe the regex in `lint.xml` doesn't match?

**Comment by koke** [comment]
> Maybe the regex in `lint.xml` doesn't match?

It looks to me like the `ignore` option deals with filenames, not string IDs

**Comment by koke** [comment]
I've pushed 257500a which seems to solve the lint issues locally, let's see what Circle has to say

**Comment by loremattei** [comment]
Oh, I'm sorry I didn't make it clear enough (I thought I did, but re-reading my comment I see it's not): It works with file content as well, but the input string is the whole line. So the regex didn't match because of the `^`.  This is the reason I hadn't put it in the solution I posted on slack. 

Anyway, your solution works as well and to be honest I think it's better because it keeps all the changes in the same file. Since we plan to change the way we handle the translations for these strings in the future, this way we don't risk to leave unused rules in `lint.xml` when we'll switch. 

I'd say :shipit: 👍

**Pull request merged**
