### PR TITLE
Issue/8993 fixing my site rtl layout

### LINKED ISSUE #8993: My Site - broken RtL layout
Section headers should be aligned to right in RtL layout (adding `textAlignment="viewStart"` should be probably enough).
screenshot_1547716897

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #8993 

To test:
- Toggle "Force RTL layout direction" in developer settings.
- Open app on My Site screen with Quick Start active.
- Make sure that My Site category titles are properly aligned.
- Make sure that content of Quick Srtart card is properly aligned.

Everything should look like this:
screenshot_1550530764

### CODE REVIEW

**Comment by theck13** [comment]
Does this bug occur on devices or just emulators?  Does it occur with true right-to-left languages or just the "Force RTL layout direction" setting on a non-right-to-left language?  We discussed that this might be a bug with the "Force RTL layout direction" setting [here](https://github.com/wordpress-mobile/WordPress-Android/pull/8355#pullrequestreview-158102812).  I just want to make sure we're fixing a bug with our layout rather than using a workaround for a _*Developer Options*_ setting issue.

**Comment by khaykov** [comment]
@theck13 Thanks for taking a look at the PR! They are legit concerns. What you described in the issue is not really a bug of force-rtl functionality, but rather the effect of "force" part. The content of the TextView without explicit width bounds will be aligned automatically to the correct side depending on the language, so if you switch to the actual RTL language, like Hebrew, everything should look ok. But, there is a reason to specify `textAlignment` - some of our locales are not 100% translated, and without `textAlignment` attribute the layout will look weird and not uniform. Maybe @malinajirka can add some more to this :)

**Comment by malinajirka** [comment]
Not much to add here:). It's not an issue in most applications as they are usually either 100% translated or 0% translated. However, since our translations are done by community, it's pretty common some languages are just partially translated. Therefore we need to explicitly specify textAlignment to better support RtL languages.

Thanks for the changes @khaykov ! ;)

**Comment by malinajirka** [comment]
There is one more thing I'd like to mention. If the TextViews had layout_width=wrap_content, we wouldn't need to specify the textAlignment as the OS would take care of mirroring the layout (more info [here](https://github.com/wordpress-mobile/WordPress-Android/wiki/Right-to-Left-layouts-guidelines#text-alignment)).

**Pull request merged**
