### PR TITLE
Migrate MediaPlayer to ExoPlayer - Contd...

### PR DESCRIPTION
**Pull request by ashiagr**
This PR is a continuation of https://github.com/wordpress-mobile/WordPress-Android/pull/12976 to migrate `MediaPlayer` to `ExoPlayer`.  (Newer commits: ea7d1c4 onwards)

It fixes video not playing issue on Atomic sites (Internal Reference: p4a5px-2Ma-p2).

**Note 1** `Gutenberg` editor currently uses `ExoPlayer` `2.9.3` ([1](https://github.com/WordPress/gutenberg/blob/ca67d603637950bc08291ed9208a3f2d2e3e67c2/packages/react-native-editor/package.json#L73), [2](https://github.com/wordpress-mobile/react-native-video/blob/5.0.2-wp-1/android-exoplayer/build.gradle#L46)) via `react-native-video`. The previous PR used a newer `ExoPlayer` `2.13.0` causing a [crash when opening a post on a `Gutenberg` editor](https://github.com/wordpress-mobile/WordPress-Android/files/7113755/exoplayer_crash.txt). To avoid this crash, this PR downgrades the `ExoPlayer` version to `2.9.3` in 5325aa4 and updates the player initialization logic in 05b9f9b.

I also considered upgrading `react-native-video` version in the `Gutenberg` editor but [the latest `react-native-video` version still uses a considerable old  Exoplayer 2.11.4](https://github.com/react-native-video/react-native-video/blob/5.1.1/android-exoplayer/build.gradle#L31) so didn't go that route.

##### Test.1 Remote Media (for a site)

1. Launch app and go to My Site ->  Media for a site with already uploaded media assets
2. Click an image/ audio/ video to go to media settings screen
3. Click on the image/ play icon on the media settings screen 
4. Verify that selected media is shown/ played properly 
5. Swipe left/ right - notice that correct image/ video / audio is shown/ played 

Try to test for different supported audio/ video formats. Media in different formats can be found in the [ExoPlayer Demo App](https://shorturl.at/buxM2). Also, I've uploaded supported media from the above link on one of [my sites](https://wordpress.com/view/testmedia662929000.wordpress.com). I can invite you to it (if not already invited) and you can access them all from the media section. Ping me to provide your email address.

##### Test.2 Local Media (on device)

1. Launch app and go to My Site -> Post
2. Add a Video/ Image block
3. Select “Choose from device” and long press a thumbnail on the following screen
4. Notice that media stored locally on the device is opened/ played properly

##### Test.3 Known Issue: Freshly created video on Atomic/ Jetpack sites (https://github.com/wordpress-mobile/WordPress-Android/issues/13314)

1. Select an Atomic site using the site chooser
2. Go to the media section on My Site tab
3. Upload a new video freshly created with the phone’s camera
4. Tap on the new video to see the media settings screen
5. Tap on the play icon, notice that the video can't load (See **Note 2**,  URL fallbacks to `GUID`)
6. Wait for few seconds, return to the media grid screen and pull-to-refresh (`.mp4` URL is returned)
7. Re-select the video and play it
8. Notice that it plays fine this time. Earlier these valid `.mp4` urls could not be played from the media section even **_after reload_** (See **Note 3**)`.

##### Test.4 Load Post on Gutenberg Editor

1. Click Blog Posts from the My SIte > Publish section
2. Click a post with video on the Blog Posts
3. Notice that the post loads fine 

**Note 2** 
On investigating the API code for video upload on an Atomic/ Jetpack site, it was noticed that when a video is first created, the video URL may fallback to the GUID (_Test.3 - Step 5_) (See [here](https://opengrok.a8c.com/source/xref/trunk/public.api/rest/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php?r=214892#110) -> [here](https://opengrok.a8c.com/source/xref/trunk/public.api/rest/class.json-api-endpoints.php?r=230845#1417) -> [here](https://opengrok.a8c.com/source/xref/trunk/wp-includes/post.php?r=228879#6440-6445)). Example temporary URL created this way: https://test287home.wpcomstaging.com/pxl_20210903_054813345-mp4. 
This URL does not end with `.mp4` extension, it is kind of a temporary URL created while the [video is still processing ](https://github.com/wordpress-mobile/WordPress-Android/files/7119131/response.txt) (`"videopress_processing_done:" false`) using the `GUID` and redirect to the [actual one]([url](https://videos.files.wordpress.com/uKA0tOER/pxl_20210903_054813345_mp4_hd.mp4)) when loaded in a browser. 
 
However, the Android app checks for a valid video file extension [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java#L139) and the video cannot be loaded. This needs to be handled separately.

unable_to_load

**Note 3**
`MediaPlayer` used earlier could not play certain videos (_Test.3 - Step 8_) and failed to load with the below error:

cannot_play

Logs:

Screenshot 2021-09-03 at 1 46 49 PM

These [cryptic codes `-1007` did not convey any useful information ](https://stackoverflow.com/questions/31370431/android-media-player-implementation-randomly-stops-playing-error-1-1007), so it was hard to fix it while using the `MediaPlayer`. Migration to `ExoPlayer` resolves this issue.

**Merge Instructions**

Requires at least 2 approvals.

- Wait for entry to "Release Notes"
- Remove Not "Ready for Merge"
- Merge the PR

## Regression Notes
1. Potential unintended areas of impact
Loading Posts in the `Gutenberg` Editor

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See tests above

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ravishanker — APPROVED** [review]
Working great and seems to solve the play issue.  Thanks for reopening it with necessary tweaks. 🙌

LGTM 👍

**Review by zwarm — COMMENTED** [review]
@ashiagr 

The code looks great, but I am having trouble with Test.2 Local Media (on device). The thumbnails do not load on my device and long pressing the video doesn't play it, just opens a view of what appears to be the first frame. See the attached video.

Maybe I am doing something wrong or I have a setting that is off?
Pixel 5 Android 11 Version: pr-15285-build-115016

https://user-images.githubusercontent.com/506707/132365985-61764cf7-158a-40c9-9501-e4c0dde13133.mp4

**Comment by ashiagr** [comment]
👋 @zwarm 

Thanks for reporting it! 🙇‍♀️ 

`Test.2 Local Media (on device)` was copied from the previous PR, it used to pass at that time. I've made no changes to this part. I checked this issue exists even on `develop` `18.2` but not in `16.3`. I think something got changed in between. I'll check different versions and see when it started happening, and maybe create a separate issue as it doesn't seem to be introduced by this PR.

**Review by zwarm — APPROVED** [review]
Based on the following comment from, I am going to add my approval to this PR. @ashiagr 

>  create a separate issue as it doesn't seem to be introduced by this PR.

**Review by mzorz — APPROVED** [review]
Thanks for these changes @ashiagr ! Checked the code and I have nothing to add. It's nice to see these improvements!
LGTM 👍 will let you merge

**Comment by ashiagr** [comment]
Created new issue #15306 for local videos issue noticed in https://github.com/wordpress-mobile/WordPress-Android/pull/15285#pullrequestreview-748080406 and [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/15285#issuecomment-914930637).

**Pull request merged**
