### PR TITLE
Issue/reader post layout

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the post list card layout in the ***Reader*** tab by making the ***Visit*** button touch feedback consistent with the other action buttons (i.e. Comment and Like) and fixing a potential button text overlap due to localization.  See the screenshots below for illustration.

reader_list

### Test
1. Go to ***Reader*** tab.
2. Long-press on ***Visit*** button.
3. Notice icon background and color.
4. Long-press on ***Comment*** button.
5. Notice icon background and color.
6. Long-press on ***Like*** button.
7. Notice icon background and color.

### CODE REVIEW

**Comment by folletto** [comment]
Thanks! Looks like a nice... touch! :D

**Comment by nbradbury** [comment]
@theck13 Looks like this is crashing on API 16:

```
05-15 15:25:39.978 2344-2344/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #206: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at org.wordpress.android.ui.reader.adapters.ReaderPostAdapter.onCreateViewHolder(ReaderPostAdapter.java:307)
```

**Comment by theck13** [comment]
Thanks, @nbradbury!  I fixed the crash in 579d879.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
