### PR TITLE
[Tooling] Remove duplicate locales in translations download

### PR DESCRIPTION
**Pull request by AliSoftware**
The list of `ALL_LOCALES` — that we use to derive the list of locales to download `strings.xml` files and Play Store metadata `*.txt` files from GlotPress — contained duplicates, and the list was also in some random/arbitrary order.

ℹ️  Note: this PR targets `release/20.0` because the next time we'll use this will be during next beta or final release.

I figured that, given that this change reduces the number of network requests to GlotPress (by removing useless duplicate calls), and the fact that we've been having the occasional `429 Too Many Requests` by GlotPress lately, better profit from the risk reduction brought by this PR sooner rather than later — especially if it reduces the risk for @ParaskP7 to get missing translations when he'll cover for me on submission day next Friday.

## What

In this PR:

 - fa13640: Removes locales that were duplicated in the list.
    - The duplicates led to those locales being downloaded twice from GlotPress when exporting translations, which was not great especially given we lately get some rate limiting once in a while from GlotPress already.
 - 106ff60: Reorders the list of locales so that it's kept alphabetical.
    - The list still keeps the locales used for "both in-app `strings.xml` and release notes / Play Store metadata" first, and the list of additional locales used "only for in-app `strings.xml` but not release notes" next, to make it easier to grasp which locales are used only for metadata (filtered into `RELEASE_NOTES_LOCALES` [a couple of lines below](https://github.com/wordpress-mobile/WordPress-Android/blob/919b78405c2f430d7b0a5a5b14e15a9035d554ea/fastlane/lanes/localization.rb#L65-L67)).
    - But within each of those 2 subsets, locales have been ordered alphabetically for consistency.
 - 0d4b74c: Updated the comment to explain a bit more about that definition of this `ALL_LOCALES` array constant.

## To Test

 - Creating a test branch from this one
 - Run the `download_metadata_strings` lane, and check that it still downloads all the same list of locales for release notes as before
 - Run `download_translations`, and check that it still downloads all the same list of locales for in-app strings as before

That being said, I think that just carefully inspecting the diff would be enough testing, since it's only removal of duplicates and reordering of the list.

### Diff tip: use `--color-moved`

You can checkout this branch then run `git diff --color-moved=plain release/20.0` to get a colored diff that shows more clearly which lines were just moved from one location (pink) to another (cyan), as opposed to the ones completely deleted (red) or added (green):
image

You can then check that the only locales that were deleted (red) were ones already present higher in the file and list.

### CODE REVIEW

**Review by ParaskP7 — COMMENTED** [review]
👋 @AliSoftware !

1. I reviewed this PR, checking the diff and everything, all LGTM! ✅ 
2. However, while following the test instructions you posted:
  - For `download_metadata_strings`, I got this error: `lanes/localization.rb:213:in `block (2 levels) in parsing_binding': \e[31m[!] undefined method `split' for nil:NilClass\e[0m (NoMethodError)` ❌ 
  - For `download_translations`, everything worked as expected. ✅ 

I wonder if I am doing something wrong on my side when triggering `download_metadata_strings`? 🤔 I would have approved otherwise but I am not all too confident, maybe someone else can help or help me figure out why I am getting this error on my side, maybe I need to update something...

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

Because I tested on this branch, I ended up committing this a2c1362398ff010dbb828ab689f888d0a93fef84 to your PR, apologies I should have tested on a different test branch as you instructed... Please feel free to drop this remote commit or let me know and I can remove it myself. I should start remembering which lane is pushing to remote and which isn't... 😅

**Comment by AliSoftware** [comment]
@ParaskP7 
1. I see that you tested the actions directly on this branch instead of first cutting a test branch from it… which means that the translations that your test run downloaded got commited and pushed 🙃  Can you revert that commit please, so it doesn't pollute the PR?
    - [EDIT] ah I missed your message above while writing my answer. Yes please revert it 😄 
3. As for the `download_metadata_strings`, the error is because you're supposed to provide `version:20.0` as a parameter to that lane: `bundle exec fastlane download_metadata_strings version:20.0`.
    - Sorry, that's my bad for forgetting that in the testing instructions.
    - Sadly the error handling on that is inexistent… it would have been nice for us to catch the case where `options[:version]` is missing / `nil` and provide a more friendly error message… maybe for a future PR.

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

1. Thank you, I am on it!
2. Thank you, will do, yea I totally missed `version:20.0`, following the test instructions totally blindly, this makes sense... 😅

**Review by ParaskP7 — APPROVED** [review]
👋 @AliSoftware !

After testing with your instructions [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16701#issuecomment-1146085451) everything worked as expected with `download_metadata_strings` too. ✅

PS: I also removed the commit I accidentally added. 👍

**Pull request merged**
