### PR TITLE
Switch gutenberg-mobile's dependency group to org.wordpress

### PR DESCRIPTION
**Pull request by oguzkocer**
This is a follow up to https://github.com/wordpress-mobile/WordPress-Android/pull/19989 and makes the group id switch for `gutenberg-mobile` dependencies from `org.wordpress-mobile` to `org.wordpress`.

In order for this PR to build, [gutenbergMobileVersion](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/build.gradle#L26) will need to be updated to a version that's published to the new group id. @fluiddot could you please take care of that? You can directly push to this branch and merge the PR once the CI is green.

### CODE REVIEW

**Comment by fluiddot** [comment]
> In order for this PR to build, [gutenbergMobileVersion](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/build.gradle#L26) will need to be updated to a version that's published to the new group id. @fluiddot could you please take care of that? You can directly push to this branch and merge the PR once the CI is green.

@oguzkocer I pushed part of these changes in https://github.com/wordpress-mobile/WordPress-Android/pull/20005, it also updates the Gutenberg Mobile reference to an alpha version published to the new group ID. Once it's merged, I'll update this PR and we can proceed with merging.

**Comment by fluiddot** [comment]
> @oguzkocer I pushed part of these changes in #20005, it also updates the Gutenberg Mobile reference to an alpha version published to the new group ID. Once it's merged, I'll update this PR and we can proceed with merging.

Done in https://github.com/wordpress-mobile/WordPress-Android/pull/20042/commits/a6272983542d46317d8723b6102c7bf566f93d79.

**Review by fluiddot — COMMENTED** [review]
I'm thinking we should probably remove the following part:

https://github.com/wordpress-mobile/WordPress-Android/blob/a6272983542d46317d8723b6102c7bf566f93d79/.github/dependabot.yml#L39-L41

WDYT?

**Comment by oguzkocer** [comment]
@fluiddot Sure - feel free to make that change and then merge 👍

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Pull request merged**
