### PR TITLE
Reset migration state when interrupted

### LINKED ISSUE #17625: Android - The migration flow does not resume if interrupted
## Description
When the migration flow is interrupted or the user closes the app (or navigates back)the flow is not resumed leading in inconsistent states.

To test ( 
1. Install WP and Jetpack app (if the Jetpack app is already installed, clear all app’s data from device settings).
2. Open the WP app and log in.
3. Navigate to the Notifications screen
4. Tap on the ⚙️ button located at the top-right corner and observe that the Notifications are On.
5. Tap on any of the Jetpack-powered banners and Try the new Jetpack app button. Alternatively, you can open the Jetpack app directly.
6. Observe that the first screen of the migration shows up (i.e. Welcome to Jetpack! screen).
7. Navigate back (this will make the app close) and open the Jetpack app again.
8. Observe that the migration screens don’t show up and not being able to initiate it again.
9. Open the WP app and repeat steps 3 and 4.
10. Observe that Notifications are still On in the WP app, meaning that the migration didn’t disable it.

Ref `pcdRpT-1i3-p2#comment-2123`

### PR DESCRIPTION
**Pull request by antonis**
Fixes #17625 

## Description
This PR resets the migration state so that the user may retry the migration flow

### Exit the flow with back navigation
1. Prerequisite: WordPress app should be installed and logged in
2. Uninstall Jetpack App if installed or clear the app data
3. Run the Jetpack app from this branch
4. On the migration welcome screen press back
5. Close the App
7. Restart the app
8. **Verify** that the migration flow starts from the beginning
### Exit the flow and login
1. Prerequisite: WordPress app should be installed and logged in
2. Uninstall Jetpack App if installed or clear the app data
3. Run the Jetpack app from this branch
4. On the migration welcome screen press back
5. Login
6. **Verify** that your data are not migrated (if you used the same account)
### Interrupt the flow
1. Prerequisite: WordPress app should be installed and logged in
2. Uninstall Jetpack App if installed or clear the app data
3. Run the Jetpack app from this branch
4. Interrupt the app (e.g. by answering a phone call or putting it in the background)
5. Open the app
8. **Verify** that the migration flow continues
### Interrupt the flow with force close
1. Prerequisite: WordPress app should be installed and logged in
2. Uninstall Jetpack App if installed or clear the app data
3. Run the Jetpack app from this branch
4. Force close the Jetpack app
5. Re-open the Jetpack app
8. **Verify** that the migration flow starts from the beginning

## Regression Notes
1. Potential unintended areas of impact
Migration flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Relied on existing tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
This is mostly working as expected (e.g. the described scenarios worked as expected in my testing). But I encountered a subtle issue when testing the first flow (Exit the flow with back navigation): the dark mode setting persisted from a previous attempt to migrate.

Steps:

Same as above with a prerequisite that the WordPress app has dark-mode manually enabled (or a light-mode if your system mode is dark-mode).

Observe that after pressing back, killing the app, and restarted the app, Jetpack will have the dark-mode set already.

This is not a major issue on its own, but it is probably worth investigating to find out:

1. If other app settings are not being reset to default on logout (perhaps leading to a worse bug?)
2. If this is a more general issue, outside the context of migration (i.e. should all app settings survive logouts?)

Since I authored part of this branch, it would be good to get feedback from another reviewer. @ovitrif , I wonder what your thoughts are on the above issue, and also if you could find any other issues with this approach.

**Comment by mkevins** [comment]
Thinking on this a bit more, I wonder whether we should tackle this at a higher level :thinking: 

For example I was thinking about an approach to solve:

> the case when the migration is interrupted by killing the app is not covered with this PR

and a simplified view of the flow looks like:

```mermaid

stateDiagram-v2
AppNotRunning --> LoginScreen: Ineligible
LoginScreen --> LoggedIn: User logged in
LoginScreen --> AppNotRunning: Back pressed
AppNotRunning --> MigrationRunning: Eligible
MigrationRunning --> AppNotRunning: App killed
MigrationRunning --> LoginScreen: Back pressed
MigrationRunning --> LoggedIn: Migration completed
AppNotRunning --> LoggedIn: Token persisted

```

The issue is that the token is persisted during a partial completion of the migration steps, and when the app is restarted, the user is logged in with the rest of the migration omitted.

We currently rely on the token in the control flow (e.g. logged in users are not migrated), but we may want to improve the commitment scheme by persisting more than a simple boolean flag whether migration is completed. Ideally, we should be able to distinguish that migration has been started, but not completed differently from migration having never been attempted (regardless of the logged in state).

For this, there are really three states we are concerned with: `CleanSlate`, `PartiallyMigrated`, `FullyMigrated`. We have been using the migration completion boolean to guarantee that we are in the `FullyMigrated` state so far (caveat being that `trySyncBloggingReminders` happens outside of the flow :sweat_smile: ). We've been using the logged in state as a kind of proxy to mitigate that this boolean cannot represent three states.

One way to approach it would be to add another boolean; something like: `migrationInProgress`. The combination of the two booleans gives us four states, but the three that we care about are represented:

|migrationComplete == | false | true |
|-|-|-|
| migrationInProgress == false | `CleanSlate` | `FullyMigrated` |
| migrationInProgress == true | `PartiallyMigrated` | `FullyMigrated` |

I think this should allow us to handle the case where the app is killed in the middle of the migration process since if we know we are in a partially migrated state, we can reset to a clean state and start over when the app launches. This is not possible using the logged in state as a proxy since the logged in state when migration complete is false is a valid state (and we do _not_ want to reset to a clean state for users in that state).

**Comment by mkevins** [comment]
Investigating the dark-mode preference, I discovered that [the code which resets the preferences on logout](https://github.com/wordpress-mobile/WordPress-Android/blob/88572b2869952a6dee5bb17f2c7e575d6851327d/WordPress/src/main/java/org/wordpress/android/AppInitializer.kt#L596) actually [only resets `DeleteablePrefKey`s](https://github.com/wordpress-mobile/WordPress-Android/blob/88572b2869952a6dee5bb17f2c7e575d6851327d/WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java#L403). This means that [several other settings](https://github.com/wordpress-mobile/WordPress-Android/blob/88572b2869952a6dee5bb17f2c7e575d6851327d/WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt#L68-L80) will persist after being partially migrated from WordPress, when the process is interrupted by a back press.

One solution is to just reset these as well (to default), but it isn't clear if this goes against the intended design, since I believe these settings also survive logouts (so resetting to default may clobber some settings). :thinking:

**Comment by ovitrif** [comment]
> Since I authored part of this branch, it would be good to get feedback from another reviewer. [@ovitrif](https://github.com/ovitrif) , I wonder what your thoughts are on the above issue, and also if you could find any other issues with this approach.

Hi @mkevins 👋
Thank you for the ping 🙇‍♂️

I could reproduce the `dark-mode` issue you've described, and I also noticed a similar issue when the interface language is changed in the WordPress app before installing the Jetpack app:

#### App Language from WordPress app on Jetpack app login screen

1. Install WordPress app and login
2. Go to `Me` → `App settings` → `Interface language` and change the app language.
3. Run the Jetpack app from this branch
4. On the migration welcome screen press back
5. **Notice** the language of the Landing screen is different than in migration flow (it's equal to what was set at step 2).

This may be related to the [known issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17685) that the language setting is not applied on the migration screens, but I wonder if these two issues are not an indication that we may have to review the fact that part of the user flags remain migrated when interrupting the flow.

One idea might be to cleanup all the migrated user prefs only when interrupting/resuming the flow, instead of a more general approach to resetting all prefs on logout. This could go well with the proposed higher level approach [described here](https://github.com/wordpress-mobile/WordPress-Android/pull/17701#issuecomment-1370559063).

---

I couldn't find other issues related to the partially migrated user flags, but I found another issue on the `Help` screen of the migration flow:

#### Logout from migration Help screen always goes back to Welcome screen

https://user-images.githubusercontent.com/4588074/210632911-46129880-6e7e-45a4-9f14-bb939fe0dfff.mp4

##### Repro Steps
1. Install WordPress app and login
2. Run the Jetpack app from this branch
3. On the migration welcome screen tap `Need help?`
4. On the migration help screen tap `Log out`
5. **Notice** The app lands back on the welcome screen of the migration flow

This issue can be reproduced repeatedly, as the logout functionality no longer works on the migration Help screen.

**Review by ovitrif — COMMENTED** [review]
Great work, following the testing steps this works as expected.

I encountered a regression issue on the help screen, [described here](https://github.com/wordpress-mobile/WordPress-Android/pull/17701#issuecomment-1371329659):
 - **Logout from migration Help screen always goes back to Welcome screen**

As well as an issue when the WordPress app language is different, but upon checking on `21.4` beta from Play Store I could reproduce it also, so it's not a new issue.

**Comment by mkevins** [comment]
Thanks for taking a look at this and testing it Ovi.

> I could reproduce the `dark-mode` issue you've described, and I also noticed a similar issue when the interface language is changed in the WordPress app before installing the Jetpack app:
> 
> #### App Language from WordPress app on Jetpack app login screen

Good catch :+1: . I had a feeling there were other similar issues possible since the reset is not comprehensive.

> One idea might be to cleanup all the migrated user prefs only when interrupting/resuming the flow, instead of a more general approach to resetting all prefs on logout. This could go well with the proposed higher level approach https://github.com/wordpress-mobile/WordPress-Android/pull/17701#issuecomment-1370559063.

I've given this some thought, and to address the kind of interruption where the app is killed, we would need to reset at the start of the flow (since we can't rely on things like `onDestroy` nor `onDetach` for that scenario).

To clarify a bit the concern described here:

> but it isn't clear if this goes against the intended design, since I believe these settings also survive logouts (so resetting to default may clobber some settings). :thinking:

Before the migration was introduced, a Jetpack user could log out and log back in, possibly to a different account, and I believe the non-user related preferences would persist between these sessions (haven't tested this, but expect it based on the implementation). It would be good to get a better understanding of _why_ the reset was designed this way:

```mermaid
flowchart
  subgraph LoggedOut [Logged out]
    A(Non-user-pref == false)
    B(Non-user-pref == true)
  end
  A --login--> C(User-pref == false<br>Non-user-pref == false)
  C --changePrefs--> D(User-pref == true<br>Non-user-pref == true)
  D --logout--> B
  B --login--> E[User-pref == false<br>Non-user-pref == true]
```

A proposed approach for resetting the migration to a "clean slate" involves resetting all preferences that are to be migrated at the start of the flow, including some preferences are not "user related" (i.e. preferences that would have otherwise survived session cycling). This may be somewhat of an edge case (i.e. users that frequently logout and login to Jetpack), so maybe it is ok to just reset at the start of eligible migration. :man_shrugging:

**Comment by mkevins** [comment]
Ovi :wave: :smile: 

I have pushed some changes to try a different approach based on the above discussion. tl;dr: the latest changes introduce a new preference which is used to track the intermediate (incomplete) migration state. Also, the reset is moved to the start of the flow to handle the case where the process dies before we can reset anything.

The latest changes do _not_ yet address the possible need to reset other preferences that would otherwise persist between user sessions.

Also, regarding the logout loop you encountered, I was unable to reproduce that for some reason :thinking: . I tried the steps you described, and also tried a few other things (such as first pressing back and then clearing the app from the recent apps switcher to get back to the welcome screen). None of the things I tried resulted in getting a loop as shown in your video. I'm not sure what could be different about our steps or environment that could result in this difference. I'm curious if you encounter this as well with the latest changes as well. Maybe that will help narrow it down?

**Comment by ovitrif** [comment]
Thank you for the thorough analysis Matthew and exploring a different approach!

> I've given this some thought, and to address the kind of interruption where the app is killed, we would need to reset at the start of the flow (since we can't rely on things like `onDestroy` nor `onDetach` for that scenario).
> [...]
> A proposed approach for resetting the migration to a "clean slate" involves resetting all preferences that are to be migrated at the start of the flow, including some preferences are not "user related" (i.e. preferences that would have otherwise survived session cycling). This may be somewhat of an edge case (i.e. users that frequently logout and login to Jetpack), so maybe it is ok to just reset at the start of eligible migration. 🤷‍♂️

Sounds good to me, I had the same thing in mind 👍 

> I have pushed some changes to try a different approach based on the above discussion. tl;dr: the latest changes introduce a new preference which is used to track the intermediate (incomplete) migration state. Also, the reset is moved to the start of the flow to handle the case where the process dies before we can reset anything.

I've had a look at the changes and tested them and it looks in principle it's an approach worth pursuing.
I did encounter two issues with it though:

1. **If we tap the back button in the migration flow it always goes back to the welcome screen**
   We may be able to change this by adding specific logic for the back navigation to make sure the migration is not retried. Although based on this internal discussion (pcdRpT-1i3-p2#comment-2162) looks like this is not an issue and it might be the way to go since we give users the option to restart the migration, and if the `Log out` on the help screen works that's the escape hatch if migration is not desired. Still feels somehow like a bug when using the app 🤷 .
3. **If we force close the app during the migration flow, upon restart it ends up on `My Site` with data migrated**
   One cause for this seems to be the [change of the migration entry-point](https://github.com/wordpress-mobile/WordPress-Android/commit/b6211caf58379f1889fddb963bbb5e91d3905e2d). That is because [once signed in the new entry-point is skipped](https://github.com/wordpress-mobile/WordPress-Android/blob/8146bffc1d8ad0caca0403ebb48193deafc4ba3d/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L331).

> Also, regarding the logout loop you encountered, I was unable to reproduce that for some reason 🤔 . I tried the steps you described, and also tried a few other things (such as first pressing back and then clearing the app from the recent apps switcher to get back to the welcome screen). None of the things I tried resulted in getting a loop as shown in your video. I'm not sure what could be different about our steps or environment that could result in this difference. I'm curious if you encounter this as well with the latest changes as well. Maybe that will help narrow it down?

Not sure what could be different, I tested both on emulator and physical device with the previous changes and the new ones and the issue keeps reproducing with the latest changes as well 🤔 .

For repro reasons, I'm logged in the WordPress app with a WP.com account.

**Comment by ovitrif** [comment]
Moved up to the next milestone since this is still in investigation.

**Comment by mkevins** [comment]
Thank you for testing this again Ovi, and also for your insightful comments about the issues you encountered, which were very helpful in debugging and finding a solution.

I've pushed a few more commits with a modified approach. In this approach, we differentiate the WPMainLogin branching when the migration has failed by providing a migration bypass argument.

Also, I was encountering a lot of weird race conditions on many earlier attempts, making this difficult to debug, and ultimately found the most stability by moving the reset code to be closer to the migration start. Crucially, the logout and flags reset was more deterministic after ensuring that the code was within the same coroutine context / dispatch cycle.

This is ready for further testing to make sure the approach doesn't introduce other regressions. :sweat_smile: :crossed_fingers:

**Review by ovitrif — COMMENTED** [review]
Great work @mkevins! This is starting to look really good, thanks a lot for pursuing a more robust solution! :bow: 🥇 

I've tested the migration flow and via the following **exit points**:

- Back button → ✅ Login screen is shown
  - Login -→ ✅ no migration, user is logged in
    - Force close & restart the app → ✅ no migration, app opens logged in
- Back button → force close & restart → ✅ migration resumed
- Force close & restart → ✅ migration resumed
- Background & foreground the app → ✅ migration continues
- Change light to dark mode → ✅ migration continues
- Help → Log out → ✅ Login screen is shown
- Help → Log out → force close & restart → ✅ migration resumed
- Go through and complete flow → ✅ migration completes
  - Force close & restart the app → ✅ no migration, app opens logged in

---

The only small regression I've encountered was:
### Tapping `Got It` on the `Delete WP app screen`  logs out.
In code, this functionality simply redirects to the `MainActivity`.

**Steps**:

1. Launch WordPress App and login
2. Uninstall Jetpack App if installed or clear the app data
3. Run the Jetpack app from this branch
4. Go through the migration flow and complete it
5. Tap on the `Please delete the WordPress app` card
6. Tap on `Got it`
7. **Notice** the app logs out.

I will investigate this further to figure out what's causing it and see if I can come up with a solution. While at it I'll also look if similar code paths (starting main activity in a new stack) are not affected as well.

P.S. I pushed two small changes to fix the build.

**Comment by ovitrif** [comment]
> ### Tapping `Got It` on the `Delete WP app screen` logs out.
> I will investigate this further to figure out what's causing it and see if I can come up with a solution. While at it I'll also look if similar code paths (starting main activity in a new stack) are not affected as well.

I had a look at the issue and found out it was caused by the fact that the migration logic (including the reset) was running again when the `Delete WP app` screen is displayed, and as part of it the migration was flagged again as being `in progress`.

I pushed a rather trivial fix for it in https://github.com/wordpress-mobile/WordPress-Android/pull/17701/commits/cb3e8082ff8dcf77c0abf55137f3ded5c70bce9c. This also makes it pretty clear that other code paths that open the `main activity` in a new stack weren't affected. I tested anyways opening the Jetpack app from a web link after finishing the migration and that worked without regressions 👍 .

**Review by ovitrif — APPROVED** [review]
This PR looks now ready on my side:
- All possible scenarios to interrupt the flow allow to resume it from the beginning
  - I added a new testing scenario: [Interrupt the flow with force close](https://github.com/wordpress-mobile/WordPress-Android/pull/17701#issue-1511847452) since it is also covered with the latest changes.
- There is no regression found after [the last one was addressed](https://github.com/wordpress-mobile/WordPress-Android/pull/17701#issuecomment-1377194706)

Thanks a lot @mkevins and @antonis for your work on this 🙇 

Since I also pushed a few small changes I'll leave the merge open but feel free to merge it after checking those.

**Review by ovitrif — APPROVED** [review]

**Comment by ovitrif** [comment]
Merging this PR since there were no other blocking issues found 🚀

**Pull request merged**
