### PR TITLE
Feature/toggle between preview modes

### PR DESCRIPTION
**Pull request by khaykov**
This PR is part of the feature branch. Additional functionality comes soon.

This PR adds the ability to toggle between desktop and native to devise view modes for responsive websites.

I stumbled upon a combination of WebView settings (pretty obvious in hindsight) that allowed me to avoid using JS injection to manipulate viewport.

Different website implements mobile/desktop versions in different ways, so we can only do our best to show them.
[Image from Gyazo](https://gyazo.com/cf635611b5b63eeb167b4a1c76135756)
Screenshot_1562888618

To test:
- Navigate to site preview.
- Toggle desktop/default preview and make sure it works and persists on configuration change.
- You can toggle the preview mode before the page is loaded.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

I'm waiting for parent PR to get merged before this one is ready for code review. The design review can be performed right now.

### CODE REVIEW

**Comment by khaykov** [comment]
Looking at the original design looks like I forgot a checkbox in selector popup 😓

**Comment by khaykov** [comment]
Fixed visuals 👍

**Comment by SylvesterWilmott** [comment]
Looking really good @khaykov it's taking shape!

Is there a white space at the top because we are hiding `wpadminbar`? There's some additional spacing that is added to the `body` and `html` that are both using the `!important` exception which we might also need to include to ovveride it.

`#wpadminbar{ display: none; }`
`body{ padding-top: 0 !important; }`
`html{ margin-top: 0 !important; }`

Can we also show a small label when a view mode other than "Default" is selected?

Screenshot 2019-07-16 at 10 33 02

**Comment by khaykov** [comment]
@SylvesterWilmott Empty bar thing is localized to en.blog, and should not affect anyone else.

Yes, we can show the label! Sorry, I missed it in the original design. I assume you want it to be fixed-width since the width of the preview mode button will fluctuate a lot depending on screen size and other buttons being hidden in some use cases.

**Comment by khaykov** [comment]
@SylvesterWilmott Added label with slide up/down animation 👍 

[Image from Gyazo](https://gyazo.com/d6808415664c810810d4f96996484b76)

**Comment by SylvesterWilmott** [comment]
Looks great @khaykov

**Pull request merged**
