### PR TITLE
Updates .configure to latest hash

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR updates the pinned hash to the latest commit. It looks like we haven't updated the pinned hash for a very long time. @loremattei Is that something intentional, or did we just not need to do it yet?

To test:
* Installable build CI task should pass

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@loremattei Unfortunately this is still failing. I am sure you already know what we need to do, so I am just going to stop wasting time on it.

**Comment by loremattei** [comment]
Hey @oguzkocer!

> Is that something intentional, or did we just not need to do it yet?
Usually the developers update it when the feature they are working on requires an update. Since the repository is shared by a lot of apps, it's not unusual for an app to stay on an old commit until (probably the newer ones are related to other apps).

> Unfortunately this is still failing.
Did you update the file manually? It looks like there are some inconsistencies. You can use the `configure_update` fastlane command to properly update the hash.

**Comment by oguzkocer** [comment]
> Did you update the file manually? It looks like there are some inconsistencies. You can use the configure_update fastlane command to properly update the hash.

I did 🤦‍♂ I'll try that today.

**Comment by oguzkocer** [comment]
@loremattei When I run the `configure_update` lane, I got some erros, but it looks like it still worked. I need to spend some time learning about our Fastlane setup :(

```
NoMethodError: [!] undefined method `trigger_action_by_name' for nil:NilClass
```

**Pull request merged**
