### PR TITLE
Updated constraintlayout version to fix #21429

### LINKED ISSUE #21429: Blaze "Learn more" crash
If you tap the ☰ icon on the Blaze card (My Site), the app crashes with this:

```
java.lang.NoSuchMethodError: No static method Fixed(I)L
androidx/constraintlayout/core/state/Dimension; 
in class Landroidx/constraintlayout/core/state/Dimension; or its super classes
```

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #21429

This PR fixes a crash that was introduced by a recent `ConstraintLayout` update. The fix was simply to update that library again. Note that I had to fix a "private resource" lint error caused by `DomainItem` for the app to build.

To test:

* Using `trunk` go to "My Site," tap the ☰ icon on the Blaze card, and select "Learn more"
* Notice the app crashes
* Using this branch, do the same and note the crash is resolved

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nbradbury** [comment]
Reverting to a Draft due to lint issues with the library update.

**Comment by nbradbury** [comment]
**Note:** To get this to pass lint, I had to change `lint.xml` to treat `ObsoleteLintCustomCheck` as a warning rather than an error. See [this Slack thread](p1730984010427129-slack-C04PWEZSYFL) for details.

**Review by wzieba — APPROVED** [review]

**Comment by wzieba** [comment]
hi @nbradbury ! The code looks good to me - I couldn't test it as I don't see Blaze card on my end (Jetpack app) but code itself look good and safe to merge IMO! 👍

**Pull request merged**
