### PR TITLE
Stats - Use flat flag icons in Geoviews

### LINKED ISSUE #2204: Use flat icon in Countries
The API now has an option to get flat country icons, we should use them https://cloudup.com/cvAVI2PLyyq

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2204

### CODE REVIEW

**Comment by nbradbury** [comment]
This works just fine, but some of the flags look odd now that there's no border. For example, look at "Republic of Korea" in this before/after screenshot:

device-2015-01-20-123353

Similar problem for Pakistan, Cyprus, Japan, Indonesia, Finland, Qatar, Malta and Switzerland.

**Comment by daniloercoli** [comment]
Yes, I noticed that issue, and we've the problem on the web.

**Comment by daniloercoli** [comment]
screen shot 2015-01-20 at 18 45 52

**Comment by nbradbury** [comment]
Sounds like a bug in both apps, then :) @isaackeyet are you okay with this being merged despite the border-less flag icons? It looks weird to me, but it's not a big deal.

**Comment by isaackeyet** [comment]
I see your point and these could probably use some sort of border -- but they're from an icon pack, the same icon pack we used before only the non-3d versions, so I don't think we should change the icons directly. I'll let Jan provide some guidance on how to solve this.

**Comment by daniloercoli** [comment]
We've decided to use flat icons on all of our clients for now. Web, iOS, and Android. We can merge this PR then.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
