### PR TITLE
Update domain empty view UI

### LINKED ISSUE #17898: Update domain empty view UI
The empty view of the domain screen in site creation flow will be updated.
The view is displayed after the `Choose a theme` screen, when the search input is empty.

#### Subtasks

- [ ] Update title and subtitle text and left align it
- [ ] Update search input
- [ ] Change illustration view

### Design

| Before | After |
| - | - |
|  |  |

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)

### PR DESCRIPTION
**Pull request by mkevins**
Fixes #17898

This PR updates the text and domain example on the domain search screen. The updated design is behind the domain purchasing feature flag.

#### Tasks

- [x] Update title and subtitle text and left align it
- [x] Update search input
- [x] Change illustration view

#### With Keyboard Visible

Original | Updated
-|-
original-empty-domain-screen-with-keyboard | updated-empty-domain-screen-with-keyboard

#### With Keyboard Hidden

Original | Updated
-|-
original-empty-domain-screen-without-keyboard | updated-empty-domain-screen-without-keyboard

#### With feature flag enabled

<details><summary>◐ Toggle the <code>SiteCreationDomainPurchasingFeatureConfig</code> flag</summary>

1. Go to `Me` → `App Settings` → `Debug settings`
2. Scroll to the `Features in development` section
3. Tap on the item corresponding to the flag
4. Tap `RESTART THE APP` button

</details>

1. Start the create a new site flow from the my sites menu.
2. Pick any topic and theme (or skip) and get to the "Choose a domain" screen.
3. Check that the screen is displayed with the changes noted in above.

#### With the feature flag disabled

1. Perform the same steps with the flag disabled.
2. Expect that the original designs are displayed for the empty UI domain search screen.

## Regression Notes
1. Potential unintended areas of impact
The domain search screen without the feature flag.

4. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

5. What automated tests I added (or what prevented me from doing so)
Establishing a foundation for writing UI tests for this would be out of scope for the task.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by mkevins** [comment]
Note that some of the new content in the updated domain example view is not visible until the keyboard is hidden. The keyboard is displayed immediately on this screen, since the search field is auto-focused. I think this is a general screen real estate issue, and maybe this is an acceptable trade-off for now :man_shrugging:  wdyt?

**Comment by antonis** [comment]
> The keyboard is displayed immediately on this screen, since the search field is auto-focused. I think this is a general screen real estate issue, and maybe this is an acceptable trade-off for now 🤷‍♂️ wdyt?

I would consider it an expected behaviour (and not a trade-off) to start with the keyboard visible since there is only one input field 👍

**Review by antonis — APPROVED** [review]
Great work @mkevins 👍 
the code changes LGTM and the app behaves as expected. 

|Dark mode / Portrait|Dark mode landscape|
|---|---|
|Screenshot_20230421_121215|Screenshot_20230421_121207|

|Light mode / Portrait|Ligth mode landscape|
|---|---|
|Screenshot_20230421_121303|Screenshot_20230421_121313|

|Control flow portrait|Control flow landscape|
|---|---|
|Screenshot_20230421_121551|Screenshot_20230421_121630|

ps. I have a design nitpick that I don't consider blocking but I'd like design input on this. I think we the title-subtitle-search icon should be vertically aligned. Wdyt @paulforgione?

Screenshot_20230421_121010

**Comment by antonis** [comment]
Tested out a few more UI configurations. All LGTM. Probably we only need to check if the subtitle text is aligned correctly when the text is RTL.

|Bold Large fonts|Bold fonts|High contrast|Large display|RTL|Small fonts|
|---|---|---|---|---|---|
|bold-large|bold|highcontrast|largedisplay|rtl|small|

**Comment by ovitrif** [comment]
Good point in the alignment @antonis!
I'd love to see everything aligned to the same line:
1. Title
2. Subtitle
3. Search Icon

**Review by ovitrif — APPROVED** [review]
LGTM ❤️ 

Thank you Matthew for owning this work 🎉

**Comment by mkevins** [comment]
> Probably we only need to check if the subtitle text is aligned correctly when the text is RTL.

Nice catch! I had intended to support RTL, but used the wrong values for `textAlignment`. Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/18302/commits/76bd2687ec39f5f04f13028424e72aa824f1d371

I had trouble testing this initially, since it seems that pseudoLocales are not working (they used to work, though :thinking: ). Anyway, I tested with actual arabic, keeping my language settings in the nearby in the back-stack so I don't get lost :smile: , and this should be resolved now.

Re: the overall alignment, I agree as well that it should all be aligned - but I'm not sure whether the icon or the text / hint text of the search input should be aligned with the text above :thinking:  I'll defer to a designer :sweat_smile:

**Pull request merged**
