### PR TITLE
[Stats] Bring Geochart legend back working

### LINKED ISSUE #4131: Gradient is black on the Country view in Stats
4372b28a2c5069cb69395d9f39f076591080a971

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #4131 by loading the old version of Google Charts API (v42 - corresponding to the April 30 2015 release).
The latest 2 stable versions of it have a problem with the legend that under some circumstances started being black when rendered in our webview. Tried to fix the issue in some other ways, but even the examples provided with the API may present black legend when rendered in our webview in a fragment. The issue ins't there if we only load 1 value in the geochart. Thanks @aerych for showing me up this.
Releases note https://developers.google.com/chart/interactive/docs/release_notes#release-candidate-details

To test:  Load Stats and switch to a period timeframe. Check that the legend is correctly rendered on the screen.

### CODE REVIEW

**Comment by daniloercoli** [comment]
I think we could merge this branch with in 5.4.X, if we don't want to wait another month for the bug to being fixed for all users.

**Comment by maxme** [comment]
> I think we could merge this branch with in 5.4.X

5.4.1 has been released, but we might consider a 5.4.2 hotfix.

**Comment by maxme** [comment]
cherry picked in `release/5.5` - I'll cherry pick in `hotifx/5.4.2` if we need one.

**Comment by maxme** [comment]
Cherry picked in `hotifx/5.4.2`

**Pull request closed without merging**
