### PR TITLE
Domains dashboard card feature config

### LINKED ISSUE #18179: Domains Dashboard Card: Presentation Criteria & Functionality
**Specification:** pc8eDl-LC-p2
**Project board:** [GitHub](https://github.com/orgs/wordpress-mobile/projects/154/views/19)

Implement domains dashboard card presentation criteria and functionality

## Requirements

1. Implement `dashboard_card_domain` remote feature flag
2. The dashboard card is shown only if it satisfies these conditions:
- The site [is hosted at WP.com](https://href.li/?https://github.com/wordpress-mobile/WordPress-iOS/blob/157aee0f9d2e9429e50a863ca6d7ecefbafe5be9/WordPress/Classes/Models/Blog.m#L582) OR the site [is atomic](https://href.li/?https://github.com/wordpress-mobile/WordPress-iOS/issues/15476) (blog.isHostedAtWPcom || blog.isAtomic on iOS)
- The user is an admin
- The site doesn’t have other domains
- The site doesn’t have domain credits
- The dashboard card for this site wasn’t hidden by the user
- Feature flag is enabled

2. The dashboard card can be hidden by opening the card option menu and selecting “Hide” CTA
3. The dashboard card opens the existing domains view (My Site -> Domains)

### PR DESCRIPTION
**Pull request by ravishanker**
Adds Feature flag for showing Domains Dashboard Card 

Fixes #18179 

To test:

1. Launch Jetpack/WordPress app
2. Go to **App Settings** (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
3. Tap **Debug Settings**
4. Find **dashboard_card_domain** under Remote features as shown in the image above

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ravishanker** [comment]
👋 @AjeshRPai - Adding you to make sure this is correct since there have been some changes recently, and you're the best person. 🙇

**Review by AjeshRPai — APPROVED** [review]
Hey @ravishanker 

Everything looks great to me. 👍🏼 . The code for the feature flag, default value for the flag, and I have also tested by running it locally. I can see the feature flag in debug settings. So 👍🏼 

One suggestion I have is to rename the remote field from `domains_dashboard_card` to `dashboard_card_domain` to keep the naming consistent with the other feature flags we have added for the dashboard cards - pages and activity log [here](https://github.com/wordpress-mobile/WordPress-Android/pull/18221/files).  But not a blocker. 

❓ Also, from the parent issue, I can see that @staskus  has added a todo 
>  Implement `direct_domain_purchase_dashboard_card` remote feature flag

Wasn't `direct_domain_purchase_dashboard_card`  the key of the remote feature flag  to be added here?. 🤔 

Am approving but not merging so that you can look at the above concerns, please feel free to address it or ignore and merge.

**Comment by ravishanker** [comment]
> One suggestion I have is to rename the remote field from `domains_dashboard_card` to `dashboard_card_domain` to keep the naming consistent with the other feature flags we have added for the dashboard cards - pages and activity log [here](https://github.com/wordpress-mobile/WordPress-Android/pull/18221/files). But not a blocker.

Appreciate the suggestion, makes sense.

@staskus - What do you think about updating remote field to "dashboard_card_domain" for consistency?

**Comment by staskus** [comment]
> > One suggestion I have is to rename the remote field from `domains_dashboard_card` to `dashboard_card_domain` to keep the naming consistent with the other feature flags we have added for the dashboard cards - pages and activity log [here](https://github.com/wordpress-mobile/WordPress-Android/pull/18221/files). But not a blocker.
> 
> Appreciate the suggestion, makes sense.
> 
> @staskus - What do you think about updating remote field to "dashboard_card_domain" for consistency?

@ravishanker okay, we can rename it, no problem. I'll update the specs and iOS!

**Pull request merged**
