### PR TITLE
fixes #9942 full screen comments

### LINKED ISSUE #9942: Full-screen comments
When the user writes a comment on a post, they only see up to 4 lines of text. We want to implement a chevron in the comment edit text that would open a full screen edittext view when clicked. This way it would be possible to see the full comment if necessary. 

enhanced_commenting_android-1

### PR DESCRIPTION
**Pull request by fdoyle**
Fixes #9942 
Currently, when the user attempts to enter a long comment, they're unable to see more than 4 lines at a time. This change enables users to press a button which will expand the comment entry field to the full height of the screen. Additionally, the new UI adds visual feedback to the submit button to show whether the comment is submittable (pink when there's content, grey when there's not)

UI 
Expected:
image

Actual:
Initial empty state:

Focused State:

(note that the button stays visible when there is text entered, even if the field is not focused)

Expanded empty state:

Collapsed with entered text (max 4 lines)

Expanded with content:

Animation:

To test:
Test that submitting a comment from the comments list continues to work in the collapsed state
Test that pressing up chevron expands comment field
Test that pressing down chevron in expanded comment state collapses comment field
Test that submitting a comment from expanded state properly posts comment
Test that the submit comment button is disabled and grey when the field is empty, and enabled and pink when the field is not empty

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

(note: I don't have permissions to update the labels/milestone on the right)

### CODE REVIEW

**Comment by planarvoid** [comment]
Thanks for the PR! I've checked the functionality and it mostly works. The chevron seems to be too big (it's smaller in the designs). There is also this weird functionality what happens that happens when there is a longer text. When expanding the view, the top of the text disappears and collapsing it again, we lose the scroll position in the view. Any idea what could be causing that? 
expande_collapse

**Comment by fdoyle** [comment]
It looks like this is a result of two issues with the edittext:
First, it doesn't like the transition from gravity being center vertical to top, resulting in a jump when changing between the two. 
Second, it doesn't attempt to scroll content into view (That it now has space for, since it expanded) until the user attempts to scroll it themselves. 

I'll see if TransitionManager has any built-in options to mitigate these, and if it doesn't, I'll explore other options

**Comment by fdoyle** [comment]
To follow up on that bug: It did end up being an issue with EditText not handling resizing very well. The solution was to wrap it in a ScrollView, which handles the resizing quite nicely, replacing the EditText's own scrolling mechanism. This change, along with a couple other tweaks, also mitigates the jump that occurs when you change the text gravity. The "animation" image demonstrates the result.

**Comment by planarvoid** [comment]
I'm closing this PR because it was fixed in this PR - https://github.com/wordpress-mobile/WordPress-Android/pull/10140

**Pull request closed without merging**
