### PR TITLE
[Reader Improvements] Update following status button design

### LINKED ISSUE #19260: [Reader Improvements] Update "Following" status button design
Update "Following" status button design and [remove unused XML attribute](https://github.com/wordpress-mobile/WordPress-Android/pull/19246#discussion_r1337591505).

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19260 

### Do not merge
Should only be merged after https://github.com/wordpress-mobile/WordPress-Android/pull/19281

Fix the design of "Following" button status.

Design specs: zQnohyMpLzBzQ5jzMMKni3-fi

To test:
1 - Run JP and sign in;
2 - Open debug settings and enable `ReaderImprovementsFeatureConfig` FF;
3 - Open reader;
4 - Verify the follow/unfollow button design using dark/light themes in "Sites to follow",  "You might like" tags, post header, site header and tag header: the design should be correct. Make sure that the follow/unfollow action still works as expected;
5 - Repeat step 2 but this time disable the FF;
6 - Repeat steps 3-4 and verify the layout: the follow icon should appear like it currently does in prod;

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Changes were only made to views

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
Mostly working for me 👍 

Two minor issues to look at:
- On the 'sites to follow' unit in particular the button is a bit slow sometimes to respond. Particularly when I have followed, and I tap again to unfollow. Maybe it needs to wait for some response or similar? Maybe we could change the button immediately assuming it is going to go through, if thats possible. It also happens when I go to those site headers, but not quite as slow.
- The ripple effect is quite prominent. Is there any parameters we can control on that? Or any other options? I would prefer if it was a little bit more subtle. But not a must fix or anything.

**Comment by RenanLukas** [comment]
Thanks for the review, @osullivanchris 

> The ripple effect is quite prominent. Is there any parameters we can control on that? Or any other options? I would prefer if it was a little bit more subtle. But not a must fix or anything.

Usually we apply a default ripple effect, but in this particular case I had to apply it manually so I have some control over it. I've pushed a change trying to make it less prominent. In case it's not working well, please let me know and I can change it.

> On the 'sites to follow' unit in particular the button is a bit slow sometimes to respond. Particularly when I have followed, and I tap again to unfollow. Maybe it needs to wait for some response or similar? Maybe we could change the button immediately assuming it is going to go through, if thats possible. It also happens when I go to those site headers, but not quite as slow.

I've investigated a bit and there seems to be a lot of duplicated code. We should be able to change it, I'm just not sure it's possible to be part of this release considering the ETA. What should happen when the back-end request fails? We change the button back to "Follow" state and show some error message? Like a toast or something? Also, should we disable the button or show some progress indicator?

**Comment by osullivanchris** [comment]
> Usually we apply a default ripple effect, but in this particular case I had to apply it manually so I have some control over it. I've pushed a change trying to make it less prominent. In case it's not working well, please let me know and I can change it.

I think its a bit better now! I am probably looking at it too closely.

> I've investigated a bit and there seems to be a lot of duplicated code. We should be able to change it, I'm just not sure it's possible to be part of this release considering the ETA. What should happen when the back-end request fails? We change the button back to "Follow" state and show some error message? Like a toast or something? Also, should we disable the button or show some progress indicator?

Think we can do without if we're tight on time for this release. Yeah I would design for the default case where follow/following is assumed to work. If the user is offline, ideally I'd capture that button press somewhere and connect it up when they come online. But that might not be possible, and there are other errors we'd have to account for. So I would show a toast that says 'couldn't follow SiteName (tappable to go to site)' and revert the button state, if it didnt go through. But as I write it out I can see that's a bit complex.

**Review by thomashorta — APPROVED** [review]
The code changes look good to me! Thanks for renaming some of the resource names to something that makes more sense, it is very helpful! 🙇🏼 

Regarding the discussion about changing the responsiveness logic, I see you created a GH issue (https://github.com/wordpress-mobile/WordPress-Android/issues/19307) for it so I believe this PR should be ready to be merged.

**Pull request merged**
