### PR TITLE
Migration: Android 12 Removes unsafe intent launches

### LINKED ISSUE #16093: Android 12: Security and performance - Unsafe intent launches
Parent #16062

[Unsafe intent launches](https://developer.android.com/about/versions/12/behavior-changes-12#unsafe-intent-launches)

The goal of this task is to detect and fix unsafe launches from the app.

Found atleast two unsafe launches from the app: 

**From Login Lib** 
```
D/StrictMode: StrictMode policy violation: android.os.strictmode.UnsafeIntentLaunchViolation: Launch of unsafe intent: Intent { (has extras) }
        at android.os.StrictMode.onUnsafeIntentLaunch(StrictMode.java:2330)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11450)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11368)
        at android.app.Activity.startIntentSenderForResultInner(Activity.java:5654)
        at android.app.Activity.autofillClientAuthenticate(Activity.java:8546)
        at android.view.autofill.AutofillManager.authenticate(AutofillManager.java:2224)
        at android.view.autofill.AutofillManager.access$2500(AutofillManager.java:176)
        at android.view.autofill.AutofillManager$AutofillManagerClient.lambda$authenticate$3(AutofillManager.java:3506)
        at android.view.autofill.AutofillManager$AutofillManagerClient$$ExternalSyntheticLambda1.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**EditPostActivity**

```
D/StrictMode: StrictMode policy violation: android.os.strictmode.UnsafeIntentLaunchViolation: Launch of unsafe intent: Intent { cmp=org.wordpress.android.prealpha/org.wordpress.android.ui.posts.EditPostActivity (has extras) }
        at android.os.StrictMode.onUnsafeIntentLaunch(StrictMode.java:2330)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11450)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11368)
        at android.app.Activity.finish(Activity.java:6463)
        at android.app.Activity.finish(Activity.java:6499)
        at org.wordpress.android.ui.posts.EditPostActivity.lambda$startObserving$8$EditPostActivity(EditPostActivity.java:898)
        at org.wordpress.android.ui.posts.-$$Lambda$EditPostActivity$0mYQlvvtdaW0SjEuv-bQkUzqaXY.invoke(Unknown Source:4)
        at org.wordpress.android.viewmodel.Event.applyIfNotHandled(Event.kt:26)
        at org.wordpress.android.ui.posts.EditPostActivity.lambda$startObserving$9$EditPostActivity(EditPostActivity.java:884)
        at org.wordpress.android.ui.posts.-$$Lambda$EditPostActivity$SR4BjYkthqVIkINAm1tyLY480sk.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### PR DESCRIPTION
**Pull request by AjeshRPai**
Parent #16093

This PR makes the necessary changes for Unsafe Intent Launches as part of the Android 12 migration. I started by running test 1 and then test 2. Expanding on why the activities set as `exported=true` is not changed. 

1. NotificationSettingsActivity
This class is launched from the system through App Info -> Notifications -> In-App Notifications Settings. For this purpose, the following Intent filter is added for launching from the system. We cannot set export to false since it will fail with the message "A launchable activity must be exported as of Android 12, which also makes it available to other apps.". 
```
 <intent-filter>
<action android:name="android.intent.action.MAIN" />
 <category android:name="android.intent.category.NOTIFICATION_PREFERENCES" />              
</intent-filter>
```
I have tested the following workaround for this Activity
1. Set the export as false -> Build fails 
2. Check if the MAIN intent filter is necessary -> Without this Intent filter, the system cannot launch the in-app notification settings. 

Changes 
1. Removes `InstanceIDService.java`, which extends `FirebaseMessagingService`- This service was set as `exported=" true"` in Android Manifest. Further investigation found that this Class was added to handle the logic after the refresh of the Firebase token. Earlier there were two base classes for firebase, [`FirebaseMessagingService`](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService) and [`FirebaseInstanceIDService`](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService)(Deprecated).  On Updating the firebase dependency, the base class of  `InstanceIDService.java` was changed from `FirebaseInstanceIDService` to  `FirebaseMessagingService`. As there is already a class(`GCMMessageService.java`) which extends `FirebaseMessagingService`, it would be better to use the same class for handling the token refresh logic. 

2.  Removes `PostsActivity` from Android Manifest - `PostsActivity` was renamed to `PostsListActivity` and the PostsActivity was added to Manifest to launch WPLaunchActivity in this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/2824). Since the version of this change was `4.1`(7 years back) and the current version is 20.1, we can safely remove this logic. 

To test:
#### Test 1 - Check for activities which has Unsafe intent launches
1. Add the following code to `init()` function in `AppInitializer.kt.` 
```
StrictMode.setVmPolicy(
                VmPolicy.Builder()
                // Other StrictMode checks that you've previously added.
                // ...
                .detectUnsafeIntentLaunch()
                .penaltyLog()
                .penaltyDeath()
                // Consider also adding penaltyDeath()
                .build())
```
4. Run the app and check for any crashes 

#### Test 2 - Check if `exported=true` is mandatory 
1. Look for activities which are set as `exported = "true"` in Android Manifest
2. Check if Intent filters are present; if present, then check if they are relevant 
5. If Intent filters are not present or relevant, Set `exported = "false"` and launch the activity with all the scenarios possible in Android 12 and Android 11 device  
6. See if the activity is working as intended. 

## Regression Notes
1. Potential unintended areas of impact
    
2. What I did to test those areas of impact (or what existing automated tests I relied on)

5. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
> NotificationSettingsActivity
> We cannot set export to false since it will fail with the message "A launchable activity must be exported as of Android 12, which also makes it available to other apps.".

I was able to launch `NotificationSettingsActivity` from the system through `App Info -> Notifications -> In-App Notifications Settings` after setting `exported=false` and suppressing the warning. Is there any other use of the intent filter?

> Removes InstanceIDService
> Removes PostsActivity

I too think we can remove them. 👍 

I'd suggest merging this PR before code freeze, if possible, and carrying on with the investigation after that.

**Comment by AjeshRPai** [comment]
Hey @ashiagr ,

> I’d suggest merging this PR before code freeze, if possible, and carrying on with the investigation after that.

I Agree 👍🏼 . We can merge and take up the rest of the changes in a separate PR. 


>I was able to launch NotificationSettingsActivity from the system through App Info -> Notifications -> In-App Notifications Settings after setting exported=false and suppressing the warning. Is there any other use of the intent filter?

Nope, there is no other use other than to launch it from the system settings. But I would have to double-check whether the setting the exported false in the release build works as expected. 

I will take up these Activities, and post the findings on setting it as exported as false in a Separate PR. And make the changes if necessary. Let me know if that works for you. 🤔  
```
LoginMagicLinkInterceptActivity
NotificationsSettingsActivity
JetpackConnectionResultActivity
DeepLinkingIntentReceiverActivity
WPComPostReaderActivity
```

**Comment by Ashita** [comment]
Hey @AjeshRPai,

I think there's a little mistake when choosing my nickname, probably you mean @ashiagr :)

Have a good day !

**Comment by ashiagr** [comment]
Works for me. Make sure that CI passes and there are no merge conflicts before merging this one.

**Review by ashiagr — APPROVED** [review]

**Pull request merged**
