### PR TITLE
Feature/reader stream refresh cards video

### PR DESCRIPTION
**Pull request by nbradbury**
This PR adds a video card type to the reader stream refresh (see #4776). Posts which have a supported featured video show the video thumbnail in the stream overlaid with a "play video" icon. Tapping this icon opens the video in a fullscreen landscape player.

A simple way to test this is to follow the "YouTube" or "Vimeo" tag. Many of the posts will have featured videos.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Quick questions:
* Is there a way to auto-start the video? Once I tap on the play button on the reader, I'd expect to video to start, but I have to tap play again once video loads. This is for Youtube btw.
* On emulator with API 25, the video was black. I am pretty sure this is an emulator thing, but if you have a 7.1 device, it'd be great to check. It works as expected on my S6 with 6.x.

**Comment by oguzkocer** [comment]
Code looks good @nbradbury! Aside from the above questions, I am ready to merge this.

**Comment by nbradbury** [comment]
@oguzkocer I don't have a 7.1 device, but on my 7.1 emulator the video plays just fine.

I also wonder about being able to autoplay the video. Mind if I open a separate issue for that, so we can get this merged?

**Comment by roundhill** [comment]
Just stopped by to say this looks like an amazing improvement! 👍

**Comment by oguzkocer** [comment]
Sounds good @nbradbury :shipit:

**Pull request merged**
