### PR TITLE
My Site Dashboard: Phase 1 - Quick Start finetune UI

### PR DESCRIPTION
**Pull request by zwarm**
Parent #15189

This PR adjusts the UI based upon the latest design iteration. Included are margin/padding changes, progress circle background color. size ratios, card frame, and font sizes for titles and text.

Dark | Light
-- | --
Quick Start Dark | Quick Start Light

**To test:**
- Launch the app 
- Navigate to My Site -> App Settings -> Test feature configuration
- Enable the `MySiteImprovementsFeatureConfig` and tap the button to restart the app (I also like to swipe the app closed after that and then reopen - sometimes weird behavior happens)
- Log out of the app
- Log in to the app
- When the Quick Start Prompt is shown, tap the "Show me around" option

## Regression Notes
1. Potential unintended areas of impact N/A
2. What I did to test those areas of impact (or what existing automated tests I relied on) N/A
3. What automated tests I added (or what prevented me from doing so) N/A

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — APPROVED** [review]
Looking great @zwarm! 🤩 
All good codewise. 

I'll let Chris to give a final approval.

**Review by osullivanchris — COMMENTED** [review]
@zwarm this looks fantastic. Really sharp and almost exactly matches the mocks. 

I have two pernickety details. Which means its very solid already if I'm being this pedantic. Neither are errors on your part.

**Top Padding**

- The space between the 'Next Steps' title and the top of the card is 4dp more than I expected compared to what we have in 'Stats'. See green line compared with orange line in below image. 
Screenshot 2021-08-25 at 09 58 27

- I am thinking this is because of the 'more'/elipsis icon. You probably have the same padding, as stats but the elipsis is moving the heading down.
- I would say just to move the heading and icon up 4dp. But there might also be cases where we don't have the elipsis. So here are two options. Let me know what works best in code. Could be another way too.

Screenshot 2021-08-25 at 10 01 54


**Next Steps row spacing**

- There is more space above the text than below. 
- Previously the spacing on this component was probably based on the big circle icon on the left which we've now removed.
- Is it possible to make it more vertically centred?
- Another possibility is that the 4dp spacing I defined is not appearing at the top of the list, but rather at the top of each list item? Mentioning just in case

Screenshot 2021-08-25 at 10 02 27

**Comment by zwarm** [comment]
@osullivanchris 
As discussed 
- Decreased space about card toolbar title from 16dp to 12dp
- Adjusted space around the Customize your site/Grow your audience to 16dp top/bottom
- Dropped the additional 4dp

In a subsequent PR, the card toolbar more menu will be set to Invisible. 

Updated 
-- 
Quick Start Dark

**Review by osullivanchris — APPROVED** [review]
Nice one @zwarm thanks for the chat to help map my design wishes to the right type of technical solutions!

Those changes all sound correct to me and it looks good too.

**Pull request merged**
