### PR TITLE
Issue/6507 third party authentication

### PR DESCRIPTION
**Pull request by theck13**
#### Note
This should be merged ***after*** https://github.com/wordpress-mobile/WordPress-Android/pull/6522.

### Fix
Add third-party authentication screen as described in https://github.com/wordpress-mobile/WordPress-Android/issues/6507.  See the screenshots below for details.

auth_screenshot_03_third_party

### Test
0. Clear app data.
1. Tap ***Log In*** button.
2. Tap ***Log in with Google*** button.
3. Notice third-party authentication view.
4. Rotate device into landscape orientation.
5. Notice third-party authentication view.
6. Tap ***Help*** action.
7. Notice help screen is displayed.

### CODE REVIEW

**Comment by folletto** [comment]
Design looks good: 👍

**Comment by nbradbury** [comment]
Everything looks good, but that image seems small on a Pixel C. Should it be larger on tablets?

screenshot_1502998197

**Comment by theck13** [comment]
Ha, that is tiny.  What do you think, @folletto?  Should be have a different layout or larger image for tablets?

**Comment by folletto** [comment]
In general I think it's fine: this screen in theory will never be seen by anyone.

Regardless: do we already have a screen like that elsewhere? If yes, it should behave the same. :)

**Comment by theck13** [comment]
The screen shown after sending a magic link has a similar layout and size.  Should the third-party layout be center aligned as it is currently or top aligned like the magic link screen shown below?

tablet_magic

**Comment by folletto** [comment]
> The screen shown after sending a magic link has a similar layout and size. Should the third-party layout be center aligned as it is currently or top aligned like the magic link screen shown below?

Yes ok, that actually look worse. :D 

So I'd suggest to simply align center and if we want to tweak it later to fill more space we'll tweak all similar screens in one go.

I don't think we discussed yet on how to use images larger, so I don't want to make a call now for something that feels ok to me – whitespaces are good. :) 

This PR is good.

**Comment by theck13** [comment]
The design has changed and this screen is no longer needed.  See the [master issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6505) for details.

**Pull request closed without merging**
