### PR TITLE
Migrate Dagger's ContributesAndroidInjector annotations to Hilt

### PR DESCRIPTION
**Pull request by irfano**
This PR removes ContributesAndroidInjector annotations and migrates related views to the Hilt.

To test:
Launch the app and navigate through the screens. Ensure it doesn't crash.

**CommentFullScreenDialogFragment**
1. Open the WP app and log in.
2. Navigate to `Reader → Following`.
3. Tap the comment icon at the bottom of a post item.
4. Tap the arrow at the bottom of the screen to open full-screen edit text.
5. Ensure it doesn't crash.

**StatsListFragment**
1. Open the WP app and log in.
2. Navigate to Stats.
3. Ensure it doesn't crash.

**SettingsUsernameChangerFragment**
1. Launch the app and log in.
2. Navigate "My Site → Me → Account Settings → Username"
3. Ensure it doesn't crash.

**UsernameChangerFullScreenDialogFragment**
1. Launch the app and sign up.
2. At the last step of the signup flow, you'll see a screen where you can update your username.
3. Tap the Username.
4. Ensure it doesn't crash.

**DebugSettingsFragment**
1. Launch the app and log in.
2. Navigate to "My Site → Me → App Settings → Debug settings".
3. Ensure it doesn't crash.

**CountryPickerDialogFragment, StatePickerDialogFragment**
1. Launch the app and log in.
2. Ensure you have credits on your account.
3. Navigate "My Site → MENU".
4. The "Register Domain" card should be on the screen. There must be some other cases for the card. I selected a hidden site with "*.wordpress.com" domain.
5. Tap the card.
6. Select a domain and tap the "Select domain" button.
7. Tap the "Country" field. Select a country with a state.
8. Tap the 'State" field. Select a state.
10. Ensure it doesn't crash on any step.

**BasicDialog**
1. Launch the app and sign up.
2. Enable Quick start tasks on the signup flow.
3. Navigate "My Site → Home".
4. Tap the three dots button on the Next Steps card.
5. Tap "Remove this"
6. Ensure a dialog appears.

**ReaderPostWebViewCachingFragment**
1. Launch the app and log in.
2. Navigate to Reader.
3. Bookmark a post.
4. Ensure it doesn't crash.

**SubfilterPageFragment**
1. Launch the app and log in.
2. Navigate to Reader.
3. Tap the Filter button.
4. 4. Ensure it doesn't crash.

**StatsViewAllFragment**
1. Open the WP app and log in.
2. Navigate to Stats -> YEARS or any other tabs except INSIGHTS.
3. Tap the "View More" button on Post and Pages card
4. Ensure Post and Pages screens open, and it doesn't crash.

**StatsDetailFragment**
1. Open the WP app and log in.
2. Navigate to Stats -> YEARS or any other tabs except INSIGHTS.
3. Tap a post item on Post and Pages card
4. Ensure the detail screen opens and doesn't crash.

**InsightsManagementFragment**
1. Open the WP app and log in.
2. Navigate to Stats.
3. Tap the cog button at the top end of the screen.
4. Ensure the insights management screen opens and doesn't crash.

**StatsWidgetColorSelectionDialogFragment, StatsWidgetConfigureFragment, StatsWidgetDataTypeSelectionDialogFragment, StatsMinifiedWidgetConfigureFragment, StatsWidgetSiteSelectionDialogFragment**
1. Add All Time to the home screen.
2. Tap the color and site buttons on the widget settings screen.
4. Add "At a glance widget" and tap Type on the config screen.
5. Ensure it doesn't crash at any step.

## Regression Notes
1. Potential unintended areas of impact
Opening current screens may cause a crash.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested all of the updated screens manually.

3. What automated tests I added (or what prevented me from doing so)
None. Because this PR doesn't introduce a new feature.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — CHANGES_REQUESTED** [review]
👋 @irfano and thanks for moving that forward! 🙇 ❤️ 

I have reviewed but tested only one specific part of this PR, the app is actually breaking, at least on `InsightsManagementFragment`, which is also where I stopped my testing, can you please take a look! 🐛 

-----

FYI: It seems that `@AndroidEntryPoint` is missing from the fragment's parent activity (or any other dependant class). On the above `InsightsManagementFragment` breaking example, me adding `@AndroidEntryPoint` on its `InsightsManagementActivity` parent activity solved the issue. 🤔 

<details>
    <summary>Stack Trace</summary>

```
13:38:12.423  E  FATAL EXCEPTION: main
                 Process: org.wordpress.android.beta, PID: 31427
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android.beta/org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.InsightsManagementActivity}: android.view.InflateException: Binary XML file line #22 in org.wordpress.android.beta:layout/insights_management_activity: Binary XML file line #22 in org.wordpress.android.beta:layout/insights_management_activity: Error inflating class fragment
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7898)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                 Caused by: android.view.InflateException: Binary XML file line #22 in org.wordpress.android.beta:layout/insights_management_activity: Binary XML file line #22 in org.wordpress.android.beta:layout/insights_management_activity: Error inflating class fragment
                 Caused by: android.view.InflateException: Binary XML file line #22 in org.wordpress.android.beta:layout/insights_management_activity: Error inflating class fragment
                 Caused by: java.lang.IllegalStateException: Hilt Fragments must be attached to an @AndroidEntryPoint Activity. Found: class org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.InsightsManagementActivity
                 	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
                 	at dagger.hilt.android.internal.managers.FragmentComponentManager.createComponent(FragmentComponentManager.java:75)
                 	at dagger.hilt.android.internal.managers.FragmentComponentManager.generatedComponent(FragmentComponentManager.java:64)
                 	at org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.Hilt_InsightsManagementFragment.generatedComponent(Hilt_InsightsManagementFragment.java:90)
                 	at org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.Hilt_InsightsManagementFragment.inject(Hilt_InsightsManagementFragment.java:112)
                 	at org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.Hilt_InsightsManagementFragment.onAttach(Hilt_InsightsManagementFragment.java:62)
                 	at androidx.fragment.app.Fragment.onAttach(Fragment.java:1881)
                 	at org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.Hilt_InsightsManagementFragment.onAttach(Hilt_InsightsManagementFragment.java:49)
                 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:3063)
                 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
                 	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
                 	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
                 	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
                 	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
                 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
13:38:12.424  E  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                 	at org.wordpress.android.databinding.InsightsManagementActivityBinding.inflate(InsightsManagementActivityBinding.java:55)
                 	at org.wordpress.android.databinding.InsightsManagementActivityBinding.inflate(InsightsManagementActivityBinding.java:49)
                 	at org.wordpress.android.ui.stats.refresh.lists.sections.insights.management.InsightsManagementActivity.onCreate(InsightsManagementActivity.kt:12)
                 	at android.app.Activity.performCreate(Activity.java:8290)
                 	at android.app.Activity.performCreate(Activity.java:8269)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7898)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

</details>

Can you please check and test each affected fragment/dialog, then update each dependent class accordingly? I can then do another round of testing. 🙏 

PS: It would help me if you provide specific test instructions per affected fragment/dialog so that it becomes easier for me to test it afterwards and verify correctness, just in case we'll miss something obvious, or even, not so obvious. 🙏 

-----

`EXTRAS`

Suggestion (💡): Now that we are at it, let's remove the `glassfishJavaxAnnotationVersion` version and its corresponding dependency and be done with that (see [comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17570#issuecomment-1479092386)).

**Comment by irfano** [comment]
> I have reviewed but tested only one specific part of this PR, the app is actually breaking, at least on InsightsManagementFragment, which is also where I stopped my testing, can you please take a look! 🐛

Good job on finding it out, @ParaskP7. I only tested a few screens and assumed the others would be okay. 🤦🏻‍♂️ Hilt activities can contain non-Hilt fragments, but Hilt fragments must be in Hilt activities. I forgot about this rule.
This time, I checked the activities of every updated fragment and manually tested all affected screens to ensure they wouldn't crash. 

> Suggestion (💡): Now that we are at it, let's remove the glassfishJavaxAnnotationVersion version and its corresponding dependency and be done with that (see https://github.com/wordpress-mobile/WordPress-Android/issues/17570#issuecomment-1479092386).

Done: 433d3364d24790100ea3aa9603917566d1662187

**Comment by ParaskP7** [comment]
👋 @irfano and thanks so much for the update! ❤️ 

> Good job on finding it out, @ParaskP7. I only tested a few screens and assumed the others would be okay. 🤦🏻‍♂️ Hilt activities can contain non-Hilt fragments, but Hilt fragments must be in Hilt activities. I forgot about this rule.
This time, I checked the activities of every updated fragment and manually tested all affected screens to ensure they wouldn't crash.

I have reviewed the change but didn't have time today to test every affected screen, just to verify that we are not missing something. I'll proceed with the testing tomorrow (if that's okay). 🙏 

In the meanwhile, would it be easy for you to provide excplict testing instructions, or at least the list of screens that I should go through while I'll be doing my testing tomorrow. It will help me save time to compile that list myself by traversing through the code manually. 🙏 

> Done: https://github.com/wordpress-mobile/WordPress-Android/commit/433d3364d24790100ea3aa9603917566d1662187

Awesome, thanks! 🥇

**Comment by irfano** [comment]
> In the meanwhile, would it be easy for you to provide excplict testing instructions, or at least the list of screens that I should go through while I'll be doing my testing tomorrow. It will help me save time to compile that list myself by traversing through the code manually. 🙏

👋🏻 @ParaskP7 , I've updated **To test:** section.

**Review by ParaskP7 — APPROVED** [review]
👋 @irfano !

Thank you so much for adding the extra testing instructions, this is great, it give me much more confidence that we are not missing-out on something obvious! 🥇 

I have tested almost all cases (the ones I could) and everything is looking good from where I stand, I'll approve this PR now but let you merge it yourself after me adding the below notes as an FYI to you:

1. ❗ `StatsWidgetSiteSelectionDialogFragment`: This was missing within the testing instructions, but I think I tested this as well via the `StatsWidgetColorSelectionDialogFragment, StatsWidgetConfigureFragment, StatsWidgetDataTypeSelectionDialogFragment, StatsMinifiedWidgetConfigureFragment` section and by selecting the `Site` from the specific widget options screen. 👍 
2. ❓ `UsernameChangerFullScreenDialogFragment`: I couldn't test this as the screen was shown for a second and then disappeared while I was signing-up. I could only go and test that updating the username works via `Account Settings` and that its screen is shown (`SettingsUsernameChangerFragment`).
3. 🤔 `CountryPickerDialogFragment, StatePickerDialogFragment`: I could't test this as I can't find the entry point to it (and to be honest, didn't want to spend much time figuring this out). I tried to add and select a domain via the `Domain` menu item, but on selection I was navigated to a web-view instead (thus couldn't tap on the `Country` or `State` fields).

**Comment by irfano** [comment]
> StatsWidgetSiteSelectionDialogFragment: This was missing within the testing instructions, but I think I tested this as well via the StatsWidgetColorSelectionDialogFragment, StatsWidgetConfigureFragment, StatsWidgetDataTypeSelectionDialogFragment, StatsMinifiedWidgetConfigureFragment section and by selecting the Site from the specific widget options screen.

Correct! It's already tested in that section. I've updated the instructions.

> UsernameChangerFullScreenDialogFragment: I couldn't test this as the screen was shown for a second and then disappeared while I was signing-up. I could only go and test that updating the username works via Account Settings and that its screen is shown (SettingsUsernameChangerFragment).

❗ **Can you reproduce it?** (I can't) If it's also reproducible on `trunk` we can open a new issue, or if it's happening only in this PR, we can fix it here.

> CountryPickerDialogFragment, StatePickerDialogFragment: I could't test this as I can't find the entry point to it (and to be honest, didn't want to spend much time figuring this out). I tried to add and select a domain via the Domain menu item, but on selection I was navigated to a web-view instead (thus couldn't tap on the Country or State fields).

In-app domain purchase is available when you have credits on your account, otherwise, it opens the web-view.  I think it's fine that you won't test this. It wouldn't be worth the effort and I've already tested it.

**Comment by ParaskP7** [comment]
👋 @irfano !

> Correct! It's already tested in that section. I've updated the instructions.

Thank you! 👍 

> ❗ Can you reproduce it? (I can't) If it's also reproducible on trunk we can open a new issue, or if it's happening only in this PR, we can fix it here.

Yea, maybe opening a new issue is enough for now, wdyt? 🤔 

> In-app domain purchase is available when you have credits on your account, otherwise, it opens the web-view. I think it's fine that you won't test this. It wouldn't be worth the effort and I've already tested it.

I agree, I do have credits (as far as I know) but as you said, you have tested it so it is okay by me too if we merge this PR now, and again, thank YOU! 🚀

**Comment by irfano** [comment]
> Yea, maybe opening a new issue is enough for now, wdyt? 🤔

If this PR is the cause of the issue, I'd like to fix it now in this PR. However, I don't anticipate this PR to be the reason for that issue.
Can you try to reproduce it on both `trunk` and this PR?

**Comment by ParaskP7** [comment]
Yes, same here, I don't think this PR is what caused this issue. I also remember seeing this on some previous testing I did on dependency updates. IMHO, I think it is okay to merge this now and create an issue to deal with that later on.

**Comment by irfano** [comment]
> I think it is okay to merge this now and create an issue to deal with that later on.

👍🏻 I tried various cases but couldn't reproduce the issue. Can you please open the issue, @ParaskP7?

I'm merging now, thanks for the review.

**Comment by ParaskP7** [comment]
👋 @irfano !

> 👍🏻 I tried various cases but couldn't reproduce the issue.

👍 

> Can you please open the issue, @ParaskP7?

Done: #18204 ✅

> I'm merging now, thanks for the review.

Awesome! 🎉 🚀

**Pull request merged**
