### PR TITLE
Quick start tasks

### PR DESCRIPTION
**Pull request by khaykov**
Part of #7707

This PR adds actual Quick Start tasks and allows you to complete them as long as you are followinf the instructions.

I opted to use EvenBus to reduce the coupling and extra boilerplate code required to pass tasks to fragments.

To test:

1. Navigate to Quick Start activity from My Site fragment.
2. Click on each tutorial, make sure the directions and visual clues of tasks are correct, and that following them results in a completion of a task (task will be marked as completed in Quick Start list).

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
I'm fine with hiding quick start if the user downgrades their own privileges to Contributor. It's edge-y enough that we don't need to create an experience around it.

>Are tasks meant to be checked off if they are completed without selecting them from the Quick Start list?

Yes @khaykov this should be the case. The user doesn't need to use the list to check things off.

**Comment by khaykov** [comment]
Thanks for the review, @theck13 !

I implemented the feedback, and here are the changes:

- Removed Quick Start row from My Site tab for non-admins.
- You can complete Quick Start tasks passively (you don't need to select them from Quick Start screen first).
- You can now repeat completed Quick Start tasks by selecting them from Quick Start list.
- Customize Theme button is now highlighted with focus point as a part of the Customize Site task.

**Comment by theck13** [comment]
> Customize Theme button is now highlighted with focus point as a part of the Customize Site task.

I can't find how to trigger the focus point for this one.  I tried the following steps, but no focus point is shown on the ***Themes*** screen.
1. Go to ***My Site*** tab.
2. Tap ***Quick Start*** item.
3. Tap ***Customize your site*** item.
4. Tap ***Themes*** item under ***Look and Feel*** section.
5. Notice no focus point.

I _am_ able to complete the ***Customize your site*** task (i.e. item is marked done in ***Quick Start*** list) by following the steps below.
1. Go to ***My Site*** tab.
2. Tap ***Themes*** item under ***Look and Feel*** section.
3. Tap ***Customize*** button in ***Current Theme*** view.

The following steps _do not_ mark the ***Customize your site*** task complete though.  Should they?
1. Go to ***My Site*** tab.
2. Tap ***Themes*** item under ***Look and Feel*** section.
3. Tap overflow menu icon in currently selected theme.
4. Tap ***Customize*** item in list.

**Comment by SylvesterWilmott** [comment]
>The following steps do not mark the Customize your site task complete though. Should they?
>Go to My Site tab.
>Tap Themes item under Look and Feel section.
>Tap overflow menu icon in currently selected theme.
>Tap Customize item in list.

Good catch @theck13 this should also check the item off

**Comment by khaykov** [comment]
@theck13 thanks for catching those issues! I screwed up some things when I allowed tasks to be completed passively. Should be fixed now!

**Pull request merged**
