### PR TITLE
Update login / signup buttons copy

### LINKED ISSUE #13879: Login: "Continue with WordPress.com" might not be clear to some users.
### Description
During a recent site-creation discovery session (internal reference `pbArwn-1AT`) a point was made that the login option "Continue with WordPress.com" might not be clear to all users that this will present you with options to create an account. As a result of that session, it was mentioned that it might be worth exploring ideas to add clarity in that area. 

<kbd><a href="https://user-images.githubusercontent.com/3384451/105766761-217b6e80-5f28-11eb-80d5-5588dd9f94d1.png"></a></kbd>

iOS Ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/15703

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #13879
Related [WordPressAuthenticator-iOS#572](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/572)

This PR updates the copy on the login/signup button from `Continue to WordPress.com` to `Log in or sign up with WordPress.com`.

To test:
- Be signed out.
- See copy as described.

Warning (⚠️): On iOS, since the title is more lengthy now, @yaelirub updated the title label font of both buttons from `title3` to `body` (per design). However, on Android we already are using `textAppearanceSubtitle2`, which is a small font. An alternative would be to use `textAppearanceBody2` or `textAppearanceCaption`, but that doesn't help much, just making the font look less bold.

textAppearanceSubtitle2 | textAppearanceBody2 | textAppearanceCaption
-------|------|------
before | after | after

What are your thoughts on that @mattmiklic ? 🙏 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mattmiklic — APPROVED** [review]
Hi @ParaskP7 -- I think the existing text style works fine in the screenshot you shared. This button text was already smaller on Android than it was on iOS, so the reduction in font size isn't as necessary.

[One thing I noticed on iOS](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/572#issuecomment-772756962), that it would be good to look at on Android, is how the text appears in other languages, or when font scaling is turned on, and the text has to wrap to two lines. I noticed on iOS that the button would benefit from some top and bottom padding when the text wraps to two lines. This may not be an issue on Android, but it'd be good to check it to see if we should make an improvement here as well.

**Comment by malinajirka** [comment]
Thanks @ParaskP7! I've tested the changes with Large Accessibility text and also with a long translation and it all LGTM.

| [ ] | rr |
|-----|----|
| Screenshot_1612423535 | Screenshot_1612422507 |

**Review by malinajirka — APPROVED** [review]

**Comment by ParaskP7** [comment]
> Thanks @ParaskP7! I've tested the changes with Large Accessibility text and also with a long translation and it all LGTM.

👋 @malinajirka ! Thank you so much for the review and for actually testing it with `Large Accessibility` text and `Long Translation`. 🙏

**Comment by ParaskP7** [comment]
> Hi @ParaskP7 -- I think the existing text style works fine in the screenshot you shared. This button text was already smaller on Android than it was on iOS, so the reduction in font size isn't as necessary.

👋 @mattmiklic ! Thanks for the explanation. 🙏 

> One thing I noticed on iOS, that it would be good to look at on Android, is how the text appears in other languages, or when font scaling is turned on, and the text has to wrap to two lines. I noticed on iOS that the button would benefit from some top and bottom padding when the text wraps to two lines. This may not be an issue on Android, but it'd be good to check it to see if we should make an improvement here as well.

@malinajirka shared one screenshot that has text wrapped to two lines. Would you mind checking that and let us know if that is okay? Do the top and bottom paddings look okay to you? Please let me know and I'll create a separate issue for that. I'll merge this PR with `develop` now in order to progress with at least that main change. 🙏

**Comment by ParaskP7** [comment]
👋 @anitaa1990 !

I wasn't sure who would be the best person to ping from `Woo`, thus apologies for the direct ping in this PR. Since `WordPress` and `Woo` share the same login, this change might be related and should be applies to `Woo` as well. Wdyt?

**Comment by anitaa1990** [comment]
Hey @ParaskP7 👋 

> I wasn't sure who would be the best person to ping from Woo, thus apologies for the direct ping in this PR. Since WordPress and Woo share the same login, this change might be related and should be applies to Woo as well. Wdyt?

Thanks for flagging this! I think in Woo, we override certain strings to use our own text during the login process. So we have the `continue_with_wpcom` defined in [WooCommerce -> strings.xml file](https://github.com/woocommerce/woocommerce-android/blob/46928aff10181e26ed79b3050de16976d5a62d99/WooCommerce/src/main/res/values/strings.xml#L1462-L1461) so the changes made in this PR should not affect Woo.

**Comment by ParaskP7** [comment]
👋 @anitaa1990 !

Thanks for the response!

> Thanks for flagging this! I think in Woo, we override certain strings to use our own text during the login process. So we have the continue_with_wpcom defined in WooCommerce -> strings.xml file so the changes made in this PR should not affect Woo.

Great, we do the same as well for `WordPress`, we override this string. It is good to hear that this will not affect `Woo`.

PS: I kind of also pinged you in case you actually wanted to change that as well or start a discussion around this.

**Comment by ParaskP7** [comment]
Warning (⚠️): I have merged this to `develop` in order not to block this feature ending up in `16.7`. However, this PR is still not 100% done since the below subtree steps are not yet completed due to a problem with creating [this PR](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/compare/merge/WordPress-Android/13951?expand=1) within the [WordPress-Login-Flow-Android](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android) repo.

Steps followed below:

image

The issue was already raised with the `Platform9` team.

**Comment by mattmiklic** [comment]
> @malinajirka shared one screenshot that has text wrapped to two lines. Would you mind checking that and let us know if that is okay? Do the top and bottom paddings look okay to you?

Yes this looks great; thanks to you and @malinajirka for checking on it.

**Comment by ParaskP7** [comment]
> Warning (⚠️): I have merged this to develop in order not to block this feature ending up in 16.7. However, this PR is still not 100% done since the below subtree steps are not yet completed due to a problem with creating this PR within the WordPress-Login-Flow-Android repo.

After receiving a suggestion from @oguzkocer I [manual PR](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/50) was created (cherry-peeking the commit from this PR) within the [WordPress-Login-Flow-Android ](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android) repo to make sure that this change is replicated within that repo as well.

**Pull request merged**
