### PR TITLE
Likers in reader enhancements

### PR DESCRIPTION
**Pull request by develric**
This is a follow up to #14375 with enhancements based on review feedbacks there.

The following should be addressed:

- [ ] Adding an `isMatchingPost` method to `RenderedLikesData` data class ([link to comment](https://github.com/wordpress-mobile/WordPress-Android/pull/14375#discussion_r610207418))
- [ ] String resources renaming to make it more clear (linked comments [1](https://github.com/wordpress-mobile/WordPress-Android/pull/14375#discussion_r610203041), [2](https://github.com/wordpress-mobile/WordPress-Android/pull/14375#discussion_r610203536)): not sure why but I see we are not using the `plurals` way currently in the app and we created a `getQuantityString` function ourself in `ResourceProvider`. Given as you said this seems a simple case I preferred to play simple and renamed the resources as per your suggestions. Let me know wdyt 🙇 
- [ ] Adding RTL support ([link to comment](https://github.com/wordpress-mobile/WordPress-Android/pull/14375#discussion_r610199059))
- [ ] Adding nullability check with exception for ListScenario ([link to comment](https://github.com/wordpress-mobile/WordPress-Android/pull/14375#discussion_r610100314))

Re the faces alignment in landscape, I think it's not trivial to see also given the 2dp white border around avatars, but the faces are aligned to the back arrow even in portrait (where the padding start is 20dp as per spec in `pbArwn-1CQ-p2#comment-2379`). 
I kept is as it is for now but worth to cross-check with @mattmiklic ; hi sir 👋 , any thought about it or things to further check? Thanks 🙇!

| image | image |
|---|---|

## To test
Checking the listed fixes above and smoke testing the reader and notifications likers sections should be enough here. As of now would be good to still smoke test the feature flag off scenarios as well 🙇 

## Regression Notes
1. Potential unintended areas of impact
Feature is still behind FF

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Feature is still behind FF

3. What automated tests I added (or what prevented me from doing so)
Feature is still behind FF

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mattmiklic** [comment]
Hey @develric  -- this doesn't look bad, but is it possible to align the avatars with the post text, so they line up with the text right above, in both portrait and landscape? It feels a little odd when it shifts over to the left on landscape.

**Comment by develric** [comment]
Hey @mattmiklic 👋 . Changed alignment as per below screenshots. Let me know if it's better now and I will push the changes 🙇 

| image | image |
|---|---|

**Review by mattmiklic — APPROVED** [review]
Looks great now. Thanks for those adjustments!

**Review by khaykov — APPROVED** [review]
Thanks for the improvements, @develric ! Looks good to me 👍

**Pull request merged**
