### PR TITLE
Fix rtl layouts in notification and me sections

### PR DESCRIPTION
**Pull request by malinajirka**
Partially fixes #2278 - Fixes RTL layouts on me and notification screens.

Some Views are not properly positioned in the RTL language mode.

To test:
1. Check layouts of the 
       Notifications screen + sub-screens
       Me + sub-screens
2. Change your locale to a RTL language (eg. Hebrew) or force RTL layouts in the developer options.
3. Check the layouts, see step 1

Doesn't fix the ViewPager swipe direction in the RTL mode.

### CODE REVIEW

**Comment by malinajirka** [comment]
Notifications settings -> pick any site -> "Home/Up" arrow in the toolbar is pointing in the wrong direction. I tried to fix the issue, however I didn't have any luck. It's a preferences screen and I wasn't able to customize it. Any ideas?

**Comment by khaykov** [comment]
Thanks for the fixes! I found only one issues so far, the App Settings -> Interface Language list behaves weirdly - when you scroll it, some of the values appear to be changing their alignment.
[https://gyazo.com/76f524ed45a8dd8baf0268af20fd9173](https://gyazo.com/76f524ed45a8dd8baf0268af20fd9173)

> Notifications settings -> pick any site -> "Home/Up" arrow in the toolbar is pointing in the wrong direction. I tried to fix the issue, however I didn't have any luck. It's a preferences screen and I wasn't able to customize it. Any ideas?

Preference screens are the bane of our existence and there is a lot of hacks around them. In this particular scenario looks like we are setting the icon manually [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L65). I think we can just use different icon based on locale.

**Comment by malinajirka** [comment]
Thanks for the feedback @khaykov ;).

> App Settings -> Interface Language list behaves weirdly - when you scroll it, some of the values appear to be changing their alignment.

It doesn't happen to me. Any specific steps to reproduce the issue?

>Preference screens are the bane of our existence and there is a lot of hacks around them. In this particular scenario looks like we are setting the icon manually here. I think we can just use different icon based on locale.

Wow, thanks! I was pulling my hair out over this issue:D. It's fixed in e52121e.

**Comment by khaykov** [comment]
> It doesn't happen to me. Any specific steps to reproduce the issue?
Hm. Yeah, it only happens on Genymotion. Stock emulator and real device work ok. I assume it's a  Genymotion problem.

**Comment by khaykov** [comment]
:shipit:

**Pull request merged**
