### PR TITLE
Merge release branch after 20.8-rc-3 beta

### PR DESCRIPTION
**Pull request by ParaskP7**
Merging the release branch after doing a new beta.

The new beta includes:
- Latest `strings.xml` from GlotPress
- Version bump in `version.properties`

### 1. `values-es/strings.xml` (1 conflict)

```
<<<<<<< merge/release-20.8
    <string name="backup_download_progress_footnote">No hace falta que esperes. Te avisaremos cuando la copia de seguridad esté lista</string>
=======
>>>>>>> trunk
```

### 2. `values-ja/strings.xml` (4 conflicts)

```
<<<<<<< merge/release-20.8
=======
    <string name="restore_another_process_running">実行中の復元が他にあります。</string>
    <string name="restore_complete_visit_site_button_content_description">サイトを表示ボタン</string>
    <string name="restore_complete_visit_site_action_button">サイトを表示</string>
    <string name="restore_complete_description_with_two_parameters">選択したすべてのアイテムは %1$s %2$s に復元されました。</string>
    <string name="restore_complete_header">サイトを復元しました</string>
    <string name="restore_complete_icon_content_description">復元アイコン</string>
>>>>>>> trunk
```

```
<<<<<<< merge/release-20.8
    <string name="restore_complete_icon_content_description">復元アイコン</string>
    <string name="restore_complete_visit_site_action_button">サイトを表示</string>
    <string name="restore_complete_description_with_two_parameters">選択したすべてのアイテムは %1$s %2$s に復元されました。</string>
    <string name="restore_complete_header">サイトを復元しました</string>
=======
>>>>>>> trunk
```

```
<<<<<<< merge/release-20.8
=======
    <string name="backup_download_progress_footnote">お待ちいただく必要はありません。 バックアップが完了したら通知します。</string>
>>>>>>> trunk
```

```
<<<<<<< merge/release-20.8
    <string name="stats_insights_popular">最も人気の時間</string>
=======
>>>>>>> trunk
```

### 3. `values-ko/strings.xml` (0 conflicts)

```
🤔
```

### 4. `values-zh-rTW/strings.xml` (1 conflict)

```
<<<<<<< merge/release-20.8
=======
    <string name="backup_download_progress_footnote">無需在附近等待。 我們會在備份準備就緒時通知你。</string>
>>>>>>> trunk
```

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @ovitrif @thehenrybyrd !

Apologies for the shameless ping and also adding you as reviewers to this PR, but can someone from the WPAndroid team help me resolve these `strings.xml` conflicts we have here (see PR description). 🙇

PS: I didn't want to ping the whole WPAndroid team, so if you know anyone better than you to help with resolving these conflicts please feel free do ping them here too. 💯

**Comment by ovitrif** [comment]
Not sure about the merge conflicts, though I'll dive deeper into git blame maybe that can help if not enough to find the solution at least to figure out who could help us on this 🤞

**Comment by ParaskP7** [comment]
> Not sure about the merge conflicts, though I'll dive deeper into git blame maybe that can help if not enough to find the solution at least to figure out who could help us on this 🤞

Thank you so much for your support @ovitrif ! 🤞 🙇 🥇

**Comment by ovitrif** [comment]
I've been looking a bit into the git history and attempting a manual merge locally for the changes. Here's my finding:

### 1. values-es/strings.xml
```
<string name="backup_download_progress_footnote">No hace falta que esperes. Te avisaremos cuando la copia de seguridad esté lista</string>
```
Seems the position of this string changed on the `merge/release-29.8` branch. Unfortunately the line number it got moved to coincides with the line where `backup_download_progress_label` string was removed on both branches.
The removed `backup_download_progress_label` string is neither on `trunk` nor on `merge/release-29.8`.

✅ **Solution** It should be safe to simply accept "yours" → the changes from the release branch.

I'll keep investigating the other points tomorrow ;)

**Comment by ParaskP7** [comment]
Thanks for the investigation @ovitrif ! 🙇 

Yea, it is weird that this happens, but yes, I too believe that accepting "yours", the changes from the release branch should be the best we could do at this point. And that, not only for this 1st conflict, but for the rest 3 of them too. 🤔

PS: I just wanted someone from the WPAndroid team to confirm that before I proceed with that resolution, just in case I am missing something vital.

**Comment by ovitrif** [comment]
> Thanks for the investigation @ovitrif ! 🙇

You're always welcome @ParaskP7 🎉 

> Yea, it is weird that this happens, but yes, I too believe that accepting "yours", the changes from the release branch should be the best we could do at this point. And that, not only for this 1st conflict, but for the rest 3 of them too. 🤔

I'm getting the same feeling, so far I've also checked every line from the first part of the 2nd conflict and was getting the same idea 👍 

> PS: I just wanted someone from the WPAndroid team to confirm that before I proceed with that resolution, just in case I am missing something vital.

Sounds good! I plan to check with @AliSoftware about this / and how he's approaching such issues, it looks to me (though not 💯 sure) that there's some kind of alphabetical ordering applied to the translated strings based on their keys when we're getting them back from GlotPress.

If that's the case then I would imagine this kind of conflicts are pretty "regular" and perhaps Olivier has a manual process to go by 🤷 , for solving the merge conflicts in the translation files more seamless.

**Comment by ParaskP7** [comment]
👋 @ovitrif !

> I'm getting the same feeling, so far I've also checked every line from the first part of the 2nd conflict and was getting the same idea 👍

👍 

> Sounds good! I plan to check with @AliSoftware about this / and how he's approaching such issues, it looks to me (though not 💯 sure) that there's some kind of alphabetical ordering applied to the translated strings based on their keys when we're getting them back from GlotPress.

Yea, I have the same feeling about the `alphabetical ordering` thingy mechanism you are mentioning here. 🤔

> If that's the case then I would imagine this kind of conflicts are pretty "regular" and perhaps Olivier has a manual process to go by 🤷 , for solving the merge conflicts in the translation files more seamless.

True, but me covering for Olivier on `release management` duties once in a while, this is the first I am seeing this kind of conflicts. Thus, this made me wonder if something is wrong and how to deal with that... 🤔

-----

You don't need to further investigate that @ovitrif , I think you did enough, again thank you for your time. 💯 

FYI: I am currently in the process of creating the `20.8` final build (it's Friday, end of sprint today 🎉), afterwards, I'll be creating another release PR from `release/20.8` to `trunk`. I'll keep this draft PR opened for now, just to get @AliSoftware's opinion on the conflicts, but I think the next release PR will overshadow this anyway, making this draft PR obsolete. Thus, I think we will continue this discussion with @AliSoftware on Monday on this other newer PR that I'll be opening by the end of today. I'll reference this draft PR in there as well. 👍

**Comment by ovitrif** [comment]
> You don't need to further investigate that @ovitrif , I think you did enough, again thank you for your time. 💯

You're welcome 🙇 !

> FYI: I am currently in the process of creating the `20.8` final build (it's Friday, end of sprint today 🎉), afterwards, I'll be creating another release PR from `release/20.8` to `trunk`. I'll keep this draft PR opened for now, just to get @AliSoftware's opinion on the conflicts, but I think the next release PR will overshadow this anyway, making this draft PR obsolete. Thus, I think we will continue this discussion with @AliSoftware on Monday on this other newer PR that I'll be opening by the end of today. I'll reference this draft PR in there as well. 👍

Thank you for describing the next steps @ParaskP7 🙇 , it was nice to collaborate on this 🎉 .

Looking forward to discuss with @/AliSoftware and learn more about possible merge conflicts when merging release branches into `trunk` 👍

**Comment by ParaskP7** [comment]
FYI: See #17237 for resolution. Cc @ovitrif @AliSoftware

PS: This newly created PR has the same set of conflicts, except for `values-ko/strings.xml`, which had 0 conflicts anyway, and shouldn't have been in the list of conflicts in the first place, GitHub... 🤷

**Comment by AliSoftware** [comment]
FYI @ovitrif @ParaskP7:
 - It's pretty rare that we got those kind of conflicts (so no, it's not something very common for which I have an official process to deal with every sprint).
 - But it can happen in rare cases where XML nodes got re-ordered during GlotPress exports indeed. I am unsure in which order GlotPress exports the various keys in the exported `values-*/strings.xml` but my guess is it's either alphabetically, or by date of last time a polyglot changed the translation in GlotPress, or something like that… it's a bit unclear (and undocumented in GlotPress). So I'm not that surprised that it could happen from time to time.
 - But given those files are the `values-*/strings.xml` translations, i.e. the content downloaded from GlotPress, what's in `release/*` for those files should be the new source of truth. Which is how I resolved the conflict in https://github.com/wordpress-mobile/WordPress-Android/pull/17237/#issuecomment-1265133618 after all

**Comment by ParaskP7** [comment]
Thank you @AliSoftware , it all makes sense, I will now close this draft PR as it is no longer needed!

**Pull request closed without merging**
