### PR TITLE
Site Creation Domain Selection Layout Fix

### LINKED ISSUE #11008: Site Creation - domain suggestions are being cut off
### Expected behavior
The domain suggestions aren't cut off.

### Actual behavior
The domain suggestions are being cut off.
Screenshot_1577087981

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. + sign button
4. Create WordPress.com site
5. Choose a type
6. Skip
7. Skip
8. Type a long domain name into the search box

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Android 9
cc @jd-alexander I think we've introduced this with the "domain unavailable" PR.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #11008

## Findings
The layout was broken due to constraints that weren't optimized for really long text. 

## Solution
I optimized the constraints of the views within the layout. 

Before | After 
--------|-------
        |       

## Testing
1. My Site
2. Switch Site
3. Plus sign button
4. Create WordPress.com site
5. Choose a type
6. Skip
7. Skip
8. Type a long domain name into the search box

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @jd-alexander for the prompt fix! However, I've noticed the layout is broken for the single line view now.

Notice the view isn't centered in the row + the selector is being cut off.
domains

**Comment by jd-alexander** [comment]
Made the changes to the layout. This is how it looks now. 

Before | After 
--------|-------
        |

**Comment by malinajirka** [comment]
Thanks @jd-alexander 

I'm wondering if we can achieve the same behaviour without nesting a linear layout into the constraint layout - it feels like this solution beats the purpose of the constraint layout as we don't have a flat hierarchy anymore. It seems the solution before the commit 228ee98 was almost working, it was just missing some of the constraints. I believe each view in a constraint layout needs to have all the constraints "start/end/top/bottom" specified. Our views are missing some of them.

For this specific layout, I think the following might work
```
        ...
        android:id="@+id/domain_suggestion_radio_button"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toStartOf="@+id/domain_suggestion"
        ...
        android:id="@+id/domain_suggestion"
        app:layout_constraintStart_toEndOf="@+id/domain_suggestion_radio_button"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toTopOf="@+id/domain_unavailability"
        ...
       android:id="@+id/domain_unavailability"
        app:layout_constraintStart_toStartOf="@+id/domain_suggestion"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/domain_suggestion"
        app:layout_constraintBottom_toBottomOf="parent"
        ...
```

I haven't fully tested it, so I might be missing something. Let me know what you think ;)

**Comment by jd-alexander** [comment]
Thanks @malinajirka I didn't realize I missed the "end" constraints in the first implementation! Your suggestion worked perfectly 🤝 

Short Query | Long Query 
--------|-------
        |

**Pull request merged**
