### PR TITLE
Fix #5417: Images added from WP media cache are empty

### LINKED ISSUE #5417: Images added to editor from the WordPress media cache are empty
As of `7.0-rc-1`, images added from our app's media cache folder (`WordPress/images/`) are turned into empty files and fail to be added (and the local file becomes empty too). Either we’re just not resolving media from our own cache directory correctly, or we’re corrupting them when we try to load them.

### Steps to reproduce the behavior
1. In `7.0-rc-1`, upload an image using any editor
2. Find the file in the local cache directory (`WordPress/images`) - `adb pull` it and make sure it's non-empty
3. Open the media picker again, and select the same image from our cache directory (it might show up at the top of 'Recent', otherwise navigate to the cache directory and find it there)
4. The upload should fail, and you should get an 'File is empty' error in the log
5. `adb pull` the same image from cache - it should be an empty file

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5417 by renaming media files saved to the cache directory if a file with that name already exists (`myphoto.png` will become `myphoto-1.png`).

This will prevent files from becoming empty as we read from and write to them at the same time; but a smarter fix would be to avoid saving a duplicate at all if we know it's the same file (or, at least, if we know the file is already in the cache directory). I'd like to open a separate issue for that, as figuring out the origin via `ContentProvider` is different depending on API level and probably won't be a trivial fix (and we'll still need this one anyway for external files with the same name as files in the cache directory).

One more thing that needs to be done is to delete already-affected images. Especially for devices with 'external' storage directories, the cache folder isn't actually cleared on cache/data clear, or on app uninstall, so those empty images will keep showing up in the picker until they're manually deleted.

To test:
1. Make sure you're able to reproduce the steps in #5417.
2. Choose a different file that is in the app's cache directory but isn't empty
3. Attempt to upload it
4. The upload should succeed, and you should have a new file named `{original-filename}-1.png` in the cache directory
5. Test with a few oddly-named files (`image-1.png`, `image`, `image-`, for example, should all correctly handled if they're uploaded a second time)

cc @maxme

### CODE REVIEW

**Comment by maxme** [comment]
> but a smarter fix would be to avoid saving a duplicate at all if we know it's the same file (or, at least, if we know the file is already in the cache directory).

I think we shouldn't even have to save the file. We should write a FluxC action that takes an `InputStream` and `POST` is directly

**Comment by aforcier** [comment]
> I think we shouldn't even have to save the file. We should write a FluxC action that takes an InputStream and POST it directly.

That would be good. I know @nbradbury was working on/wants to add a new table in FluxC that'll keep track of files already uploaded, so we never upload duplicates - that'll play well with having no local cache at all.

**Comment by aforcier** [comment]
I added a fake DB migration step to clear existing empty cache files in 05395e6.

**Comment by maxme** [comment]
Looks good, but the removed file still appears in my "Recent" view, when I try to select and upload it I get a Toast "Error downloading image" and in my logs an exception "java.io.FileNotFoundException: No such file or directory".

I don't think we can do anything about it and it should only happen for some beta testers anyway.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
