### PR TITLE
Update FluxC to enable authenticated rest api requests to self-hosted sites

### PR DESCRIPTION
**Pull request by mchowning**
Update FluxC to allow authenticated requests. Also moves much of the logic around rest API requests out of WPAndroid to be handled within FluxC. As a result, we no longer need to rewrite the context parameter for media queries to be "view" instead of "edit" in order to avoid needing authentication. 

Further details and testing instructions are in the [related FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1525).

### TODO
 - [x] Once the FluxC PR is merged, the `fluxCVersion` here needs to be updated before this is merged.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Hi there! I will be freezing 14.6 in a little bit, to this PR is being bumped to 14.7. If you need this to be shipped in 14.6, please update the base branch to `release/14.6` and give me a heads up when the PR is merged so I can release a new beta.

**Comment by maxme** [comment]
❤️ +9 −234  - everything looks good on wpandroid with this patch, waiting for the new FluxC version before we can merge that one.

Screenshot 2020-04-08 at 15 57 19

**Comment by mchowning** [comment]
Meged the FluxC PR, tagged a beta release for FluxC, and updated the `fluxCVersion` here. I believe this PR is ready now.

**Comment by mchowning** [comment]
The "Installable build" step failure is a known issue unrelated to this PR, which is [being fixed separately](https://github.com/wordpress-mobile/WordPress-Android/pull/11624), so going ahead and merging this.

**Comment by mchowning** [comment]
The "Installable build" step failure is a known issue unrelated to this PR, which is being fixed separately. Going ahead and merging this.

**Pull request merged**
