### PR TITLE
Material 3: Voice to content

### PR DESCRIPTION
**Pull request by nbradbury**
This PR converts the "Voice to content" feature to Material3. To test:

* Enable `voice_to_content` in Debug Settings > Remote Features
* Tap the FAB on My Site
* Select "Post from audio"
* Verify it looks as expected

https://github.com/user-attachments/assets/5d374395-8de7-491b-a178-24bdc389457a

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by dcalhoun — APPROVED** [review]
Changes look sound, testing succeeded. 

I noted the UI is unexpectedly obscured from content overflow scrolling. Also, a11y needs improvement, as there are little-to-no labels for the interactive elements—e.g., buttons, live regions. That said, these issues are also present on the `trunk` branch. 

| Start | In-Progress |
| - | - |
|  Screenshot_20241106_150007_Jetpack Pre-Alpha | Screenshot_20241106_150023_Jetpack Pre-Alpha |

**Comment by nbradbury** [comment]
> I noted the UI is unexpectedly obscured from content overflow scrolling.

Oh, interesting. It looks like that happens on smaller screens. Which device are you testing with?

**Comment by dcalhoun** [comment]
> > I noted the UI is unexpectedly obscured from content overflow scrolling.
> 
> Oh, interesting. It looks like that happens on smaller screens. Which device are you testing with?

A Samsung Galaxy S20 5G FE. I consider it a fairly large device screen.

**Comment by nbradbury** [comment]
> A Samsung Galaxy S20 5G FE. I consider it a fairly large device screen.

Yes, that is a large screen. I'm not sure why the overlap is happening, then, but since it happens in `trunk` I'll file a separate issue for it. Thanks!

**Pull request merged**
