### PR TITLE
Jetpack App (Basics): Prologue screen

### PR DESCRIPTION
**Pull request by ashiagr**
SubTask: #14302

PS: Don't be alarmed with the PR size, its because of `bg_stars_background_large.xml ` ( 2,436 lines)

This PR updates the prologue screen for the Jetpack app. 

device-2021-05-04-135123

To test:

Jetpack app
- Install and launch Jetpack app. 
- Notice that the prologue screen for the Jetpack app is displayed.
(Check for both light and dark mode.)

WordPress app 
- Install WordPress app. 
- Notice that the prologue screen for WordPress app is displayed.

Merge Instructions

1. Wait for design review
2. Remove Not Ready for Merge label
3. Merge the PR

## Regression Notes
1. Potential unintended areas of impact
WordPress app

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested prologue screen for WordPress app manually.

3. What automated tests I added (or what prevented me from doing so)
Added tests for prologue screen for Jetpack app.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — CHANGES_REQUESTED** [review]
Looking good so far! 
all these working well:
- Logo size
- background colours
- gradient

Some nitpicks:

- I think the stars background looks great on phone landscape. But the individual stars are a *tiny* bit large on portrait. Could we make that background a tiny bit smaller.
- How is the text and logo positioned? My thinking was to position it centre between the top of the device, and the top of the buttons, or slightly higher. At the moment, its a little bit low down. But I don't want to specify exactly the amount to change, as it depends how it is built.
- Could we make the padding left and right of the text a bit more? I'd like the text to wrap a little bit earlier than it is. Maybe add another 8dp left and right.
- On tablet its displaying funky for me altogether. but maybe an issue with the build I'm using or maybe you haven't looked at it yet.

Also let me know if there's any issues you ran into building it that might change how we are thinking about structuring it.

Screenshot 2021-05-05 at 11 43 01

**Comment by zwarm** [comment]
> * Could we make the padding left and right of the text a bit more? I'd like the text to wrap a little bit earlier than it is. Maybe add another 8dp left and right.

**Comment by zwarm** [comment]
> * I think the stars background looks great on phone landscape. But the individual stars are a _tiny_ bit large on portrait. Could we make that background a tiny bit smaller.

Going to leave this with a "centerCrop" and if we decide to do differently, @osullivanchris will provide a new asset.

> * Could we make the padding left and right of the text a bit more? I'd like the text to wrap a little bit earlier than it is. Maybe add another 8dp left and right.

I increased the start/end padding from `32dp` to `40dp`

I'm working on the other changes

**Comment by zwarm** [comment]
> On tablet its displaying funky for me altogether. but maybe an issue with the build I'm using or maybe you haven't looked at it yet.

@osullivanchris - I think I managed to address this one too. Do a pull on this branch and give it a whirl.

**Comment by zwarm** [comment]
> How is the text and logo positioned? My thinking was to position it centre between the top of the device, and the top of the buttons, or slightly higher. At the moment, its a little bit low down. But I don't want to specify exactly the amount to change, as it depends how it is built.

🤔  @osullivanchris  It does appear that the Logo is spaced properly between the top of the view and the start of the button bar. Let me know what you want me to do here? I can add a negative margin of 20dp to the logo element? wdyt?

**Comment by osullivanchris** [comment]
Aha! Now I see the miscommunication. Yeah, the logo is indeed centred. What I was actually trying to achieve is having the logo *and* text, as a group, centred.

Hard to explain. But below:
- The yellow box is the group I want to centre
- the pink lines are equal. So its roughly equidistant between the top of the screen and the buttons
- But actually, as you mention nudging up slightly in the original scenario. In this case, I still want to do it. Marked in blue, I have pushed it up a further 16dp...as there's a weird optical rule where things that are actually centred don't optically look centred, they need to be slightly above centre. I'm willing to be called pedantic. [I found this cool image to explain the optical illusion](http://www.vanseodesign.com/blog/wp-content/uploads/2010/12/optical-center.png). Actually I'm not sure how well it explains it but it looks technical 😄 

jetpack prologue layout

**Comment by zwarm** [comment]
@osullivanchris - Thanks for the clarification. I moved it up 16dp. Let me know what you think. Thanks.

Original | Moved up 16dp
-----|-----
light | dark

**Review by osullivanchris — APPROVED** [review]
> @osullivanchris - Thanks for the clarification. I moved it up 16dp. Let me know what you think. Thanks.

It looks perfect now @zwarm. 

In the screenshot provided it is appearing exactly as intended in the spec I provided. 

Did you also do the thing to centre [text and logo] as a group, rather than just centring the 
 from the logo? It looks like you did 🤔 Which would be good! Just thinking if you only nudged 16dp, it might not be correct on all devices/orientations. We can huddle on it real quick if I am confusing the hell out of you!

**Comment by zwarm** [comment]
> In the screenshot provided it is appearing exactly as intended in the spec I provided.

YaY!

> Did you also do the thing to centre [text and logo] as a group, rather than just centring the
> from the logo? 

Yes, yes I did.

**Comment by osullivanchris** [comment]
> Yes, yes I did.

Ah great! Should be good now so!

**Review by zwarm — APPROVED** [review]
@ashiagr - All looks good. I worked with Chris to fine tune the design; just a few small changes. Nice work. 👍

**Pull request merged**
