### PR TITLE
[Editor] Enable inserter block search

### PR DESCRIPTION
**Pull request by jhnstn**
Enables inserter block search in the editor 
See https://github.com/wordpress-mobile/gutenberg-mobile/pull/3867

To test:
See https://github.com/wordpress-mobile/gutenberg-mobile/pull/3867

## Regression Notes
1. Potential unintended areas of impact 
Editor: Block Inserter Menu

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See https://github.com/wordpress-mobile/gutenberg-mobile/pull/3867

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@jhnstn This is looking really close! I'm not seeing the block search UI on the [sibling WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16889) but I took this Android build for a spin and have a few bits of feedback, one of which I'd consider a blocker.

- [Blocker] I'm seeing some weird transitions when switching between the short and tall sheets ([video](https://cloudup.com/c-t1Q3iSS67)). It looks like the sheet height is jumping to full before transitioning back down to the desired height, and vice versa, although it is less jarring when going back to the compact sheet. Note: I would consider this a blocker, assuming it's reproducible.
- The scroll container is cutting off the content on scroll on the tall sheet ([example](https://cloudup.com/cM7sSeiMfkT))
- The search input looks a bit small on Android. For reference, it should be 48px tall, but looks about ~40-42px ([comparison](https://cloudup.com/c2Rm8Jv0Lhn))

**Comment by jhnstn** [comment]
> [Blocker] I'm seeing some weird transitions when switching between the short and tall sheets (video). It looks like the sheet height is jumping to full before transitioning back down to the desired height, and vice versa, although it is less

@iamthomasbishop  I believe this is the same issue mentioned [here](https://github.com/WordPress/gutenberg/pull/33237#issuecomment-879680369). Carlos has worked on this quite a bit and doesn't look like there is a clear fix coming anytime soon.

**Comment by jhnstn** [comment]
> - [Blocker] I'm seeing some weird transitions when switching between the short and tall sheets (video). It looks like the sheet height is jumping to full before transitioning back down to the desired height, and vice versa, although it is less jarring when going back to the compact sheet. Note: I would consider this a blocker, assuming it's reproducible.

We've resolved this by making the inserter fullscreen by default.

> - The scroll container is cutting off the content on scroll on the tall sheet (example)

I am unable to reproduce this with the recent fullscreen changes.

**Comment by jhnstn** [comment]
Gutenberg changes merged.

**Pull request closed without merging**
