### PR TITLE
Merge 21.8 code freeze into trunk

### PR DESCRIPTION
**Pull request by jkmassel**
Includes:
- Version number bumps
- Dependency updates
- Release notes chores

### CODE REVIEW

**Review by ParaskP7 — COMMENTED** [review]
LGTM! 💯 

Question (❓) Shouldn't we remove the JP items from WP release notes too? Just like you did [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17992/commits/738b4aadf33e5e27ca30a4c0571c74ded6fba588) for the JP release notes. 🤔 

I am asking that because I am seeing this `[Jetpack-only]` entry on the [WordPress/metadata/release_notes.txt](https://github.com/wordpress-mobile/WordPress-Android/pull/17992/commits/0e23e21e8fdfd9f90b3fc84895e29ea9b9efbe63#diff-82636e6ad25e1187592f3ae87c9126c3e71c8a9fdff1a3f23b075456e320915d). PS: The same applies on the [21.8-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/21.8-rc-1) pre-release.

**Comment by jkmassel** [comment]
> Question (❓) Shouldn't we remove the JP items from WP release notes too? Just like you did [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17992/commits/738b4aadf33e5e27ca30a4c0571c74ded6fba588) for the JP release notes. 🤔

We haven't in the past, but I'll look into whether we should moving forward!

**Comment by AliSoftware** [comment]
> > Question (❓) Shouldn't we remove the JP items from WP release notes too? Just like you did [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17992/commits/738b4aadf33e5e27ca30a4c0571c74ded6fba588) for the JP release notes. 🤔
> 
> We haven't in the past, but I'll look into whether we should moving forward!

I remember that I have when I was WPAndroid's RM 😛

**Comment by mokagio** [comment]
FWIW, I've been removing `[Jetpack-only]` and the occasional `[WordPress-only]` in the iOS counterpart after it was suggested to me.

I'm of two minds about it. On one hand, it feels correct because the files are Jetpack- or WordPress- specific. On the other hand, it should be clear enough to readers that "Jetpack-only" applies only to Jetpack, regardless of whether the note is in the Jetpack- or WordPress- file. 🤷‍♂️ 

_We should automate it away_ 🧐

**Review by ParaskP7 — APPROVED** [review]
I am now approving this PR so that to unblock it, but I disabled the auto-merge in case we want to make a change to the WP release notes. 👍

**Comment by jkmassel** [comment]
I merged it for now; next time they'll be separated!

**Pull request merged**
