### PR TITLE
Non-static locale

### PR DESCRIPTION
**Pull request by nbradbury**
This PR addresses [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/21542#discussion_r1893760658) regarding `LocaleManager` by removing `LocaleManager.getLanguage()` and replacing it with `PerAppLocaleManager.getCurrentLocaleLanguageCode()`.

@ParaskP7 I've asked for your review of this since you're familiar with the context, but there's no rush to get this merged. Also, I see that this is failing SonarCloud Code Analysis due to duplication, but I'm thinking we can ignore that 🤞

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ParaskP7 — APPROVED** [review]
👋 @nbradbury !

I have reviewed this PR as per the instructions (also tested it), everything works as expected, thanks for making this refactor! 🥇 

> Also, I see that this is failing SonarCloud Code Analysis due to duplication, but I'm thinking we can ignore that 🤞

Definitely can ignore that. 👍

**Comment by nbradbury** [comment]
@ParaskP7 You surprised me by reviewing this so quickly - thank you!

**Comment by ParaskP7** [comment]
😅 It would have been now or 2 weeks from now! 😅

**Pull request merged**
