### PR TITLE
Check the html editor for change as well

### LINKED ISSUE #7819: Just opening a post in Aztec could result in local changes
There is an issue with Aztec that can slightly change the content of the current post even if the user has not made any changes to it.

To test this:
- Open a post in the editor
- Don't edit anything
- Switch to HTML
- Tap BACK
- You will see the post marked with local changes

This happens because there is an internal conversion from HTML to Span(s) that doesn't preserve (and probably can't) the exact HTML code passed in input. The conversion back to HTML is done internally by Aztec, when we request the content again on exit, and the produced HTML can be slightly different (attributes order, inline tag not closed) from what we passed in input.

We've already tried different approaches to fix this issue (see #7767), but those were not working as expected. This should be fix Aztec side, and integrate the changes here.

### PR DESCRIPTION
**Pull request by hypest**
Fixes #7819 

This PR uses the `hasChanges()` method [added to the html editor](https://github.com/wordpress-mobile/AztecEditor-Android/pull/704) to avoid marking the post as modified, unless the user has indeed introduced changes to the content while in the html editor.

The Aztec side PR needs to get merged first, after which this PR will get updated to point to the proper commit hash.

To test:
1. Run the app and make sure you're using the Beta editor (Aztec)
2. Open a published post that has an image in the content but don't make any changes
3. Switch to html mode
4. Tap "Back" to return to the post list and notice that the post has no "Local changes" label

### CODE REVIEW

**Comment by hypest** [comment]
Note: wpandroid will still try to push (upload) a post to the backend, even though the editor reports "no changes". That happens because the since the user tapped on "Update" in the editor screen, the app will try its best to update the post online. This includes pushing a post that already has local changes from previous editor sessions.

**Comment by hypest** [comment]
Updated to the latest hash from the Aztec PR and fixed wpandroid (with 2388954) to initialize the source editor too.

**Comment by daniloercoli** [comment]
I think I noticed something weird with this PR where my changes are not preserved upon switching from visual to html (and vice-versa).

It seems to happen when you add a single character to the content. See the GIF below:
content-loss

I was with "Don't keep activities set to ON".

**Comment by hypest** [comment]
I think I manage to reproduce that issue @daniloercoli . I opened https://github.com/wordpress-mobile/AztecEditor-Android/issues/711 to track it.

I think we should hold off this PR until the issue on the Aztec side gets fixed. WDYT?

**Comment by daniloercoli** [comment]
Sure, let's wait the fix on the Aztec side.

**Comment by hypest** [comment]
Hey @daniloercoli , updated the PR to point to latest Aztec `develop` (includes the fix for https://github.com/wordpress-mobile/AztecEditor-Android/issues/711 ).

I also removed the `Not Ready for Review` label.

Ready for another pass, thanks!

**Comment by daniloercoli** [comment]
LGTM! :shipit:

**Pull request merged**
