### PR TITLE
Make the IME Submit button work fullscreen reply dialog in landscape orientation

### LINKED ISSUE #11449: Comments : Expanded comment layout doesn't send commit in landscape mode
### Expected behavior
The `SEND` button of the keyboard will work in Landscape mode. 

### Actual behavior
`SEND` button doesn't work when the comment mode is expanded and the device is in landscape i.e when the soft keyboard takes over the comment's `EditText` control. 

### Steps to reproduce the behavior
1. Go to Notifications.
2. Open comments tab. 
3. Turn the device to landscape mode. 
4. Open a comment.
5. Expand the comment reply.
6. Click Comment control.
7. The soft keyboard should be shown now; enter a comment. 
8. Press `SEND` and realize that it does nothing.

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #11449 

This PR fixes the non-working send button in expanded comment reply/edit dialog in landscape mode.
[Image from Gyazo](https://gyazo.com/6a5c54037e50f7276361fce5738883e8)

To test:
- Turn the device to landscape mode.
- Open a comment.
- Expand the comment reply.
- Click Comment field.
- The soft keyboard should be shown now; enter a comment.
- Press SEND confirm that reply is published.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@develric Thanks for pointing out the issue with Send button not working after orientation change. Looks like we were not reattaching the listeners to the fragment after orientation change, so I fixed that. Also gave the reply fragment unique ID's based on site and remote comment ID, so we can point it to the correct comment details fragment in ViewPager.

**Review by develric — COMMENTED** [review]
>Also gave the reply fragment unique ID's based on site and remote comment ID, so we can point it to the correct comment details fragment in ViewPager

Nice catch and addition 👍 

While testing I found another edge case I'm describing below (this one is related to full screen dialog); it's possibly not related to the changes tbh, maybe have been already present before.

- in portrait go full screen with comment dialog
- go landscape (from now you can stay landscape or go portrait again)
- try to write a comment and send after having been in full screen
- comment is not sending for me

Let me know if you can reproduce and confirm it; I guess we can also merge this PR and address the below in another PR (or at least document in an issue); let me know 🙇

**Comment by khaykov** [comment]
@develric As we discussed, this happens in Reader, and it's probably the same issue of listeners not being reattached on configuration change. I created a separate issue for this #14537 :)

**Review by develric — APPROVED** [review]
Hi @khaykov, yep confirm issue was in the reader and makes sense the issue could be in the hosting fragment that is different in reader 👍 ! Thanks for creating the GH issue 🙇 , approving this one!

**Pull request merged**
