### PR TITLE
Sharing - manage connections

### LINKED ISSUE #4070: Manage Sharing section
In the Sharing feature, there is a manage section that opens the following sections:
1. Sharing buttons (Can edit which is visible and the order in which they are visible)
2. More (opens to show more social options)
3. Label (The text that the sharing label uses)
4. Button style (Four options)
   1. Official Buttons
   2. Icon Only
   3. Icon and Text (default)
   4. Text Only
5. Reblog/Like enabled radio buttons
6. Comment like radio button
7. Twitter username

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4070 

To test:
Toggle all settings in manage connection and verify that it reflects on the web or iOS

Needs review: @nbradbury

### CODE REVIEW

**Comment by nbradbury** [comment]
Right now this is failing Travis due to:

* The use of "slideInFromRight" [here](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/4070-manage-sharing/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L129), which no longer exists in `develop`. That line can be replaced with `context.startActivity(intent);`
* The use of "slideOutToRight" [here](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/4070-manage-sharing/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java#L180). That whole `finish` method can be deleted - it's no longer necessary

**Comment by nbradbury** [comment]
I have to be honest: I work for Automattic and I still don't know what most of the "Manage Connections" settings do.

My understanding is the goal here was for the Android app to copy the design of the iOS app, but unless I was an end user who already understood the same settings on the web app, I would have no idea what these settings are all about. 

I would have a tough time merging this PR without knowing there was a plan for making the settings more user friendly.

cc: @hugobaeta 

sharing-settings

**Comment by nbradbury** [comment]
I just spent some time looking at this same feature on iOS, and there I find it less confusing. The helpful text below things like "Edit More Button" and "Twitter Username" makes it far more clear what these settings are for. Is there a reason these weren't added on Android?

**Comment by kwonye** [comment]
> Right now this is failing Travis

Addressed in 42dd07c, thanks!

**Comment by kwonye** [comment]
@nbradbury sorry for the confusion, that's totally my fault. I fell into the trap of having the iOS context in my mind (as I was constantly using it as reference) when working on Android, so I must've subliminally filled in the blanks of what each button does.

It's a bit tricky how we show additional info. There is a long-tap "hold" that the user can do (which I actually forgot to implement because only about 100 people do that action a day). 

One option is for us to set the `android:summary` of each setting, but it could possibly get tricky as it's also used for showing the current value, e.g. Label and Button Style. It _is_ a different color though, so that may be good enough for a differentiator. Here's an example of how it would look:

screenshot_20160722-174902

**Comment by kwonye** [comment]
I believe this design is useable, we just need to continue to iterate on it until it makes sense 😊

**Comment by nbradbury** [comment]
> I believe this design is useable, we just need to continue to iterate on it until it makes sense

Agreed, the use of the summary line would help a lot.

**Comment by kwonye** [comment]
@nbradbury ready for another pass! Don't know if the wording is quite there yet so please feel free to edit as you'd like :)

**Comment by nbradbury** [comment]
This is much better, but could use some more work.

* On the main sharing screen, the button at the bottom says "Manage Connections" but the resulting screen doesn't appear to be related to managing the connections. On iOS this button (which is just "Manage") is under a "Sharing Buttons" label, which is more accurate.
* The "Edit Sharing Buttons" setting is less attractive on Android than on iOS. The iOS app has icons for each of the services, and it's clear from the main setting screen which buttons have been enabled
* On iOS there's a description on the dialog that pops up when you edit the sharing label. This is missing on Android.
* The word MORE is quoted on iOS when referring to a "more" button, which works better, imo
* The "Visual" grouping doesn't really make sense, since so many of these settings are visual
* The "Twitter Username" setting would benefit from a description
* Disabling "Comment Likes" doesn't seem to work - the next time I return to the sharing settings, they're re-enabled

**Comment by kwonye** [comment]
> On the main sharing screen, the button at the bottom says "Manage Connections" but the resulting screen doesn't appear to be related to managing the connections. On iOS this button (which is just "Manage") is under a "Sharing Buttons" label, which is more accurate.

> The word MORE is quoted on iOS when referring to a "more" button, which works better, imo

Done 👍 

>  The "Twitter Username" setting would benefit from a description

Description is unavailable as that space is reserved for the actual username. I did however add a message in the dialog when the user clicks the preference though.

> The "Edit Sharing Buttons" setting is less attractive on Android than on iOS. The iOS app has icons for each of the services, and it's clear from the main setting screen which buttons have been enabled
On iOS there's a description on the dialog that pops up when you edit the sharing label. This is missing on Android.

Yes, that's correct. It was decided to do the least-effort solution on customizing `MultiSelectListPreference` for V1. What we want eventually is a ReorderableListView but that work is being done in a Menus PR. Once that is merged in, we can inherit that class and use it (along with adding icons, etc).

> The "Visual" grouping doesn't really make sense, since so many of these settings are visual

I consolidated it with "Buttons" as that seemed the best fit. Willing to try something else if that doesn't seem optimal.

> Disabling "Comment Likes" doesn't seem to work - the next time I return to the sharing settings, they're re-enabled

Thanks for catching that, I was using very similar constants and got them mixed up. Fixed!

@nbradbury ready for another pass!

**Comment by nbradbury** [comment]
Almost there! A few issues:
* Instead of using "Edit Sharing Buttons" as the label, how about just "Sharing Buttons?" The word "Edit" implies an action and is confusing because the action is performed by the "Manage" button
* The word MORE still isn't quoted ("more" button) as it is on iOS
* There's a typo in the Twitter username dialog

typo

**Comment by kwonye** [comment]
@nbradbury thanks for catching those! All fixed for realzies this time.

**Comment by nbradbury** [comment]
@kwonye All the fixes look good. I was just about to merge this when I realized I hadn't tested in landscape, so I rotated the device - and discovered the "Manage" button was unreachable. It's offscreen and there's no way to scroll to it.

**Comment by kwonye** [comment]
@nbradbury guilty of that as well, thanks for catching that! Addressed by adding a `ScrollView`

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
