### PR TITLE
Testing: Add optional connected tests on PRs

### PR DESCRIPTION
**Pull request by rachelmcr**
This change sets up a CircleCI workflow to optionally run connected tests on PRs.

Here's how the setup works:
* The `Optional Tests/Hold` job puts the workflow on hold, so the tests will only run when they are manually triggered on CircleCI.
* Peril is now set up to force the `Optional Tests/Hold` check to have a `success` status on the PR, so it won't block merging if you choose not to run the tests.
* Peril comments on the PR with a link to the Optional Tests workflow on CircleCI. To run the tests, you can approve the Hold job on CircleCI and the Connected Tests results will be posted on the PR.
* Any new commits to the PR will trigger the Peril comment to be updated with the current link to run the connected tests.

Related changes to Peril settings:

* https://github.com/Automattic/peril-settings/pull/39
* https://github.com/Automattic/peril-settings/pull/40

To test:

* Confirm you see a `ci/circleci: Optional Tests/Hold` check on this PR with a `success` status.
* Confirm you see a Peril comment on this PR that says, "You can trigger optional UI/connected tests for these changes by visiting CircleCI here."
* Confirm the text "here" is a link to the `Optional Tests` workflow on CircleCI. On CircleCI, confirm you can manually approve it to start the connected tests.
* Confirm that when the connected tests finish, the test results are posted as an additional check on the PR.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
I just realized that this PR doesn't change the `slack/status` step in the connected tests job, so a Slack message will be posted for any connected test failures (including optional test runs on PRs). Do you think that's ok or should we try to restrict the Slack message to only develop and release branches?

It looks like the [Slack orb](https://circleci.com/orbs/registry/orb/circleci/slack) supports a parameter `only_for_branches` to specify which branches to run on, but I'm not clear on whether that supports regex (to specify our release branches).

**Comment by rachelmcr** [comment]
> I think it might be best to restrict this to just develop and release. 

Cool, that was my instinct, too. I went ahead and created a CircleCI job for the optional connected tests that doesn't include the Slack notification, so the notification is restricted to develop and release branches. A better way to do this in the future would be to create our own Slack orb or use another that supports limiting to branches based on pattern matching or regex (currently it only works for string literals, which won't work for our release branches), but for the sake of getting this done now I went with this approach.

> Having said that, maybe we can add a little note about pinging us if they feel the it is a false negative, so developers know how to deal with a failure that's not caused by their changes. What do you think?

Sure, we could add something like this. What do you think of adding this to the Slack notification:

> Please reach out in #platform9 if you think this failure is not caused by your changes, so we can investigate.

And maybe this for the Peril comment on PRs:

> If you see any test failures not caused by your changes, please reach out to the `wordpress-mobile/platform-9` team so we can investigate.

**Comment by oguzkocer** [comment]
@rachelmcr All of that sounds great to me. The changes also makes sense to me, but again, I'll let someone with more experience merge it just in case :)

**Comment by loremattei** [comment]
This looks good to me! A small improvement to avoid duplicating the same configuration just because of the slack message could be to make that step parametric and suppress it for Optional tests. 

Something like this (syntax may be slightly off):
```
Connected Tests:
    executor:
        name: android/default
        api-version: "28"
    parameters:
        steps:
            type: steps
            default:
                - slack/status:
                    fail_only: true
                    include_job_number_field: false
                    include_project_field: false
                    failure_message: '<...>'
    step:
<...>
        - android/save-gradle-cache
        - steps: << parameters.steps >>
<...>
Optional Tests:
    #Optionally run connected tests on PRs
    jobs:
      - Hold:
          type: approval
          filters:
            branches:
              ignore:
                - develop
                - /^release.*/
                - /pull\/[0-9]+/
      - Optional Tests:
          requires: [Hold]
          steps: [ ] # Overwrite Slack with nothing
```

**Comment by rachelmcr** [comment]
I just figured out that approach with the parameter and then saw your comment. :) I'll merge this and follow up with that improvement. Thanks!

**Pull request merged**
