### PR TITLE
New per app language preferences implementation

### PR DESCRIPTION
**Pull request by ravishanker**
This PR adds [Per-app language preferences](https://developer.android.com/about/versions/13/features#app-languages)  introduced in Android 13 (API 33) level.

- Updates compileSDKVersion to 33
- Updates androidxAppCompatVersion to 1.6.0-rc01
- Updates for API changes after upgrading compileSdkVersion to 33
- Let AndroidX handle the locale storage so that the user's preference persists
- Provides migration for handing over storage to system

> **Note**
> This PR is going to be parked until such time `androidxAppCompatVersion` is upgraded to ~ 1.6.0 and `compileSdkVersion` to 33 in separate PRs

TODO:
- [ ] Set allWarningsAsErrors to true before merge (Set it to false to avoid updating a large number files in this PR)
- [ ] Auto generate locales_config.xml using release-toolkit when we download the list of locales from GlotPress.
- [ ] Probably need to upgrade Android Gradle Plugin from 7.2.1 to 7.3.1 or later in settings.gradle

Settings > System > Languages and Input > App languages > [App] > App language

https://user-images.githubusercontent.com/990349/190540086-ec27306b-7149-4621-92af-9923061c6a39.mp4

Settings > Apps > [App] > Language > App language

https://user-images.githubusercontent.com/990349/190540143-37ae77a9-a96c-4552-944f-2b02b8626981.mp4

To test:

Test 1:
- Build and run
- Launch WordPress or Jetpack app on a device running Android 13
- Now go to device **Settings > System > Languages & Input > App Languages** > Select (WordPress app or Jetpack app)
- Ensure WordPress or Jetpack app shows in App Lanaguages
- Tap on the app.  It should navigate to App Lanaguage selection screen

Test 2:
- Build and run
- Launch WordPress or Jetpack app on a device running Android 13
- **Settings > Apps > Select (WordPress app or Jetpack app) > Language** (scroll if required)
- Tap on the Language option.  It should navigate to App Lanaguage selection screen

Test 3
- WordPress app / Jetpack app already have in app Language picker ( Me > App Setttings > Interface Language)
- Select another language
- Ensure, the language change take effect
- Navigate to **Settings > Apps > Select (WordPress app or Jetpack app) > Language** (scroll if required)
- Tap on the Language option.  It should navigate to App Lanaguage selection screen
- Ensure, the language selected in in-app language picker also takes effect in System settings

Test 4
- Build and run
- Launch WordPress or Jetpack app on a device/emulator running **Android 12**
- Navigate to in app Language picker ( Me > App Setttings > Interface Language)
- Select another language
- Ensure, the language change takes effect

Test 5
- Build and run
- Launch WordPress or Jetpack app on a device/emulator running **Android 12**
- Upgrade to **Android 13**
- Navigate to in app Language picker ( Me > App Setttings > Interface Language), Note language
- Navigate to **Settings > Apps > Select (WordPress app or Jetpack app) > Language** (scroll if required)
- Tap on the Language option.  It should navigate to App Lanaguage selection screen, Note language
- Ensure, the language selected in in-app language picker, and in Systems settings are same

> **Note**
> Need to evaluate when we can potentially remove in-app language picker altogether.  Potentially when **targetSdkVersion** or **minSdkVersion** is upgraded to Android 13 (API 33).

To test:

## Regression Notes
1. Potential unintended areas of impact
Language and Locale in some places

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested various features and in both ways from in-app picker to system settings and vice versa

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @ravishanker and thank you a lot for working on this! 🥇 

Initially, I recommend to not rash with this PR. Instead we should do the below first and unblock all WPAndroid engineers from the `compileSDKVersion = 33` need. Also, I recommend us to avoid doing such an `compileSDKVersion` updates as part of a feature PRs. Instead, we should consider split them into multiple PRs and do the required tech debt changes first. Wdyt? 🤔

> Updates compileSDKVersion to 33
> +
>  Set allWarningsAsErrors to true before merge (Set it to false to avoid updating a large number files in this PR)

As you noticed, and as I already warned on this `paqN3M-Ku-p2` P2 post (see `What Now? 🤔` sections, `3.` point), to update `compileSdkVersion = 33` is not as simple as it used to. This needs to become an organized effort so that first all new warnings are resolved, with the bulk of them being the deprecated related warnings, and only then to update the `compileSdkVersion` to `33` and merge to `trunk`.

Now, in order to do that, I would either recommend:
- An `build/update-compile-sdk-version-to-33` feature branch, where on top of that, someone would work on fixing those various warnings by splitting them into multiple PRs.
- Or, to first fix the various warnings targeting `trunk` directly, that is, without the intermediate `sdk/compile-sdk-version-33` feature branch.

PS: It all depends on how quick this `build/update-compile-sdk-version-to-33` feature branch will end up being merged to `trunk`. If one would envision this effort to take more than a couple of weeks, due to limited resources or otherwise, then I would recommend to avoid the `build/update-compile-sdk-version-to-33` feature branch and merge the warnings fix to `trunk` directly. Else, you will end up having to maintain the `build/update-compile-sdk-version-to-33` feature branch, that is, the need to keep it up-to-date with `trunk` every day/week, which might cause you some pain with resolving merge conflicts as a process.

Cc @AjeshRPai as I know you are also started looking into Android 13 (`API 33`).

**Comment by ParaskP7** [comment]
FYI @ravishanker: Same applies to the `androidxAppcompatVersion = '1.6.0-rc01'` update. It should be done in isolation to everything else, but in coordination with the rest and as a prerequisite to unblock this feature work. The good news are that I am already working on this #17561 batch dependency updates issues and I am be dealing with the `androidxAppcompatVersion` as part of that.

**Comment by AliSoftware** [comment]
Thanks for working on this! ❤️ 

>  Auto generate `locales_config.xml` using release-toolkit when we download the list of locales from GlotPress.

For your information, the `release-toolkit` already generates a `WordPress/src/{main,jetpack}/res/values/available_languages.xml` file (as part of [this action](https://github.com/wordpress-mobile/release-toolkit/blob/4e5fdfe467480bc2a80b07f72f0b608920734bef/lib/fastlane/plugin/wpmreleasetoolkit/actions/android/android_download_translations_action.rb#L12-L15)). This file is currently used by [the existing In-App `LocalePickerViewModel`](https://github.com/wordpress-mobile/WordPress-Android/blob/fe648a15a4a8c4cd16a11707266de4bed90f2e36/WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerViewModel.kt#L147). That file is NOT following [the expected `locales_config.xml` config file format](https://developer.android.com/guide/topics/resources/app-languages#use-localeconfig)—and instead is a Strings resource—so we can't use it directly; but that implementation could be a good starting point to adapt things easily to generate the necessary `locales_config.xml` file I guess.

That raises another question though: was this list of locales the appropriate list in the first place? Because the whole list of locales that we have from GlotPress might be diffrent from the list of locales that we _download_ from GlotPress (e.g. if we don't download some locales that have a translation % coverage that seems too low), and might also be different from the list of localized resources that we end up including in the final `.aab`/`.apk`, depending on [the `resourceConfiguration` setup we have in our `build.gradle`](https://github.com/wordpress-mobile/WordPress-Android/blob/fe648a15a4a8c4cd16a11707266de4bed90f2e36/WordPress/build.gradle#L196-L198) too… so might require more careful inspection of what needs to be listed there… and what list of locales we end up wanting to include (See pdnsEh-ev-p2)

**Comment by AjeshRPai** [comment]
Hey @ravishanker 

I have the same opinion as @ParaskP7 here. 

> I recommend us to avoid doing such an compileSDKVersion updates as part of a feature PRs. Instead, we should consider split them into multiple PRs and do the required tech debt changes first. Wdyt?

Well put. 💯 . 

I feel like we are rushing to compile SDK version update and the dependant in App language feature. I also feel that we need not rush the update of the `androidxAppCompatVersion to 1.6.0-rc01`. 

I agree that the per-app language preference is a great feature, and I appreciate your effort. But I think we can take up  the changes needed for it after 
1. Compile SDK version is changed to 33 in a PR, and its merged 
2. Once this dependency updates issue is closed  - https://github.com/wordpress-mobile/WordPress-Android/issues/17561

FYI: Once the hack week is over and I have identified the necessary tasks for Android 13 changes. I will create a Project thread as well as a project board for the Android 13 changes. As part of the Android 13 changes, I think the first task I had in mind was to update the compile SDK version to 33. So if you want me to take up that task. I can. Let me know.

**Comment by ravishanker** [comment]
👋 @ParaskP7, @AliSoftware, @AjeshRPai 

Thanks for taking a look at this PR promptly.  I agree with the suggestions, and I had similar thoughts while working on this.

> the androidxAppcompatVersion = '1.6.0-rc01' update. The good news is that I am already working on this https://github.com/wordpress-mobile/WordPress-Android/issues/17561 

_@ParaskP7 - Awesome, better wait for this update to come through then.  Probably need to upgrade Android Gradle Plugin from 7.2.1 to 7.3.1 or later in settings.gradle as well._

> Update the `compileSdKVersion` to 33 as part of the Android 13 changes

_@AjeshRPai  - Totally, I'm happy for you to tackle it, I can also lend a hand once you've list of changes ready for 13._

> Was this list of locales the appropriate list in the first place?

_@AliSoftware - Good idea, `locales_config.xml` is one-to-one match with the existing `available_languages.xml`.  We need to adapt the script that generates `available_languages.xml` to generate `locales_config.xml` and also use it for Locale Picker perhaps._


My challenge in this PR was mainly to achieve sync between In-app picker and System settings selection.  So, once androidxAppCompatVersion and compileSdkVersion are upgraded, I can then cherry pick relevant commits and open a new PR then.  I'm going to watch out for the changes.

**Comment by ParaskP7** [comment]
> @ParaskP7 - Awesome, better wait for this update to come through then. Probably need to upgrade Android Gradle Plugin from 7.2.1 to 7.3.1 or later in settings.gradle as well.

Deal @ravishanker and thank you, I'll add a comment here when that is done so you're aware of it! 💯 

PS: Please expect that happening somewhere around next month. ⏳

**Comment by ravishanker** [comment]
I'm closing this for now since it is agreed to do this, after upgrading the following dependencies first in separate PRs
- androidxAppCompatVersion to 1.6.0
- compileSdkVersion to 33

**Pull request closed without merging**
