### PR TITLE
Implement domains list search logic

### LINKED ISSUE #19173: 🤖 Domains List Search Logic
* The search operation will be performed locally.
* The search logic should return domains where the `domain.domain` or `domain.site_slug` matches or contains the search query.

### PR DESCRIPTION
**Pull request by mkevins**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/19173

### Description

This PR adds search (filtering) logic to the my domains screen.

To test:

Prerequisite: Please test this with an account which has several domains.

1. Navigate to the "My Domains" screen (Me -> Domains)
2. Wait for your domains to load
3. Type a search query into the input

Expect that the domains shown in the list are filtered based on the query. Only matching domains should be shown. A domain matches if the query string is present within either the `domain` or the `siteSlug` for the domain.

## Regression Notes
1. Potential unintended areas of impact
N/A

5. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

6. What automated tests I added (or what prevented me from doing so)
Unit tests were added for this logic.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Awesome work @mkevins 👍 
I've tested the implementation on a Pixel 5 (Android 14) and the main functionality worked as expected for me in different configurations. The code also looks good 😄 

I've noticed two minor UI issues:
1. It would be nice to have a clear ✖️ button at the right of the field so that the user can easily reset the search (ref rvVgXupiyONUcJMgPSoMFj-fi-2565_27287)
2. I would expect the field to allow only one line of input and the enter button to close the keyboard

|Missing X button|Double line|
|---|---|
|Screenshot_20231026_201841|Screenshot_20231026_201903|

**Comment by mkevins** [comment]
Thank you for reviewing and testing this!

> I've noticed two minor UI issues:
> 
> 1. It would be nice to have a clear ✖️ button at the right of the field so that the user can easily reset the search (ref rvVgXupiyONUcJMgPSoMFj-fi-2565_27287)
> 2. I would expect the field to allow only one line of input and the enter button to close the keyboard
> 

Good catches! Wdyt about addressing these in a follow-up PR? The reason I mention that is that Artyom has a fix in an upcoming PR to set the input field as a single line, so we will get that for free, and avoid conflict if we address the clearable input afterwards.

**Review by antonis — APPROVED** [review]
> Good catches! Wdyt about addressing these in a follow-up PR? The reason I mention that is that Artyom has a fix in an upcoming PR to set the input field as a single line, so we will get that for free, and avoid conflict if we address the clearable input afterwards.

Sounds good @mkevins 👍 
I'll proceed with merging the PR.

**Comment by antonis** [comment]
> 2. I would expect the field to allow only one line of input and the enter button to close the keyboard

Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/19466

**Pull request merged**
