### PR TITLE
Deprecate Ui and Default scopes from thread module

### PR DESCRIPTION
**Pull request by malinajirka**
This PR 
1. deprecates injected UI/DEFAULT CoroutineScopes. These scopes are not tied to anything and therefore their children coroutines are never cancelled -> they behave like GlobalScope. 
2. refactors places where injected CoroutineScopes were used.

I decided not to refactor `BackupDownloadStatusService, RewindStatusService, ScanStatusService, BackupDownloadProgressChecker , RewindProgressChecker` since they are being worked on and I didn't want to cause too many unnecessary conflicts. I'll get back to those next week when the work there is finished.

To test:
#### Reader - https://github.com/wordpress-mobile/WordPress-Android/commit/5a2776f6a6088788b49efc4cd9aa9f2f16c80252
1. Open Reader
2. Click on more button on one of the posts
3. Click on "Block"
4. Notice a snackbar is shown
5. Click on "UNDO" in the snackbar and verify it works
6. Switch to Discover tab
7. Click on more button on one of the posts
8. Click on "Follow" button
9. Notice s snackbar is shown
10. Click on "Enable" action in the snackbar - it currently doesn't work https://github.com/wordpress-mobile/WordPress-Android/issues/13812, however, verifying that the exception is shown in the Logcat should be enough for this PR, wdyt?

#### WordPress.java - https://github.com/wordpress-mobile/WordPress-Android/commit/53c684d8b2c77fdbee46851087cf5a26a8269fa8 and https://github.com/wordpress-mobile/WordPress-Android/pull/13813/commits/d619152e7e0005fc6444502d2846d882a939ac45
1. Put a breakpoint [here](https://github.com/wordpress-mobile/WordPress-Android/blob/0ec6666468507a56d8ecabc16799189b465b3331/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorFileUtils.kt#L11)
2. Launch the app with an attached debugger
3. Verify the app reaches the breakpoint

#### PlansViewModel - https://github.com/wordpress-mobile/WordPress-Android/commit/72f3fa35c1c3ecaa6e4d9f48529aee3046673166
1. Open plans page
2. Verify plans are fetched and shown

#### SearchListViewModel - https://github.com/wordpress-mobile/WordPress-Android/commit/5185001ba09e9c083725098f731abf9049d5b983
1. Open Site Pages
2. Click on Search icon
3. Verify the search works

#### Page Parent - https://github.com/wordpress-mobile/WordPress-Android/commit/d19b824fd8fd02ecee88edc2629ee2ce3898bbf0 and https://github.com/wordpress-mobile/WordPress-Android/commit/89877018b12f0d213c6905b0aebc72d6f4460bf0 and https://github.com/wordpress-mobile/WordPress-Android/commit/e19c1970916eb92550f36c16879d74b1304ce8b6
1. Open Site Pages
2. Click on the more action on one of the pages
3. Click on "Set page parent"
4. Select a page
5. Verify the radio button gets selected
6. Click on Search icon
7. Verify the search works and that you can select a page from the search results

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by planarvoid** [comment]
Just for the record: 

> Click on "Enable" action in the snackbar - it currently doesn't work #13812, however, verifying that the exception is shown in the Logcat should be enough for this PR, wdyt?

This is happening to me when I do Follow/unfollow, is that expected?

**Review by planarvoid — APPROVED** [review]
I've tested all the scenarios and it all seems to work well 👍  good job! 

The only thing is this https://github.com/wordpress-mobile/WordPress-Android/pull/13813#issuecomment-766714965
Feel free to merge this PR if the behaviour is expected

**Comment by malinajirka** [comment]
> This is happening to me when I do Follow/unfollow, is that expected? 
That's not expected, great catch! ;)

Thanks for the review @planarvoid! I've fixed the issue and merged develop -> both follow and turn on site notifications buttons should work as expected now (https://github.com/wordpress-mobile/WordPress-Android/issues/13812 is fixed)

**Review by planarvoid — APPROVED** [review]
Thanks for the changes! The follow now works well 👍

**Pull request merged**
