### PR TITLE
Add fingerprint scanning as option on PIN lock

### PR DESCRIPTION
**Pull request by tonyr59h**
The passcodelock v1.1.0 library is hosted in the staging repository [here](https://oss.sonatype.org/content/repositories/staging/org/wordpress/passcodelock/1.1.0/).

Add `maven { url 'https://oss.sonatype.org/content/repositories/staging' }` to your repositories block in WordPress `build.gradle` to test before releasing the library.

cc @daniloercoli (since you got a fancy new 5X :wink:)

### CODE REVIEW

**Comment by tonyr59h** [comment]
Just updated the staged library. It includes a fix for the issue we discussed with multiple lock screens appearing when attempting to unlock the app. Before merging this we should release the library and test again without the staging repository.

**Comment by daniloercoli** [comment]
- Invalidated and restarted AS
- Cleaned and rebuilt the project
- Same issue : multiple lock screens appearing when attempting to unlock the app.

**Comment by daniloercoli** [comment]
Wait, I linked the PasscodeLock prj (issue/multiple-lock-screen branch), and it seems to fix the issue. Most probably AS still reference the previous 1.1.0 version of PasscodeLock. Despite my attempts with cleaning caches.

@kwonye Can you please confirm/double check that the new fix works as expected?

**Comment by daniloercoli** [comment]
@tonyr59h - I used the app over the weekend without noticing any issues with the fingerprint unlock. 
I think it's safe to publish the library and merge this PR.

**Pull request merged**
