### PR TITLE
NPE when rendering post with video in WebView 

### LINKED ISSUE #11791: NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
**Sentry Url**: https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/
**User Count**: 3
**Count**: 18
**First Release**: org.wordpress.android-14.6.1
**First Seen**: 2020-04-25T02:22:32Z
**Last Seen**: 2020-04-28T23:40:07Z
**24 Hours**: 0
**30 Days**: 18

```
NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
     at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1164)
     at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
     at android.os.Handler.handleCallback(Handler.java:815)
     at android.os.Handler.dispatchMessage(Handler.java:104)
     at android.os.Looper.loop(Looper.java:207)
     at android.app.ActivityThread.main(ActivityThread.java:5765)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Update: See https://github.com/wordpress-mobile/WordPress-Android/issues/13070 for repro steps

### PR DESCRIPTION
**Pull request by develric**
Fixes #11791
The solution in this PR is based on this comment [findings](https://github.com/wordpress-mobile/WordPress-Android/issues/11791#issuecomment-706188426).

I think the issue can potentially affect everywhere we use a `WebChromeClient`, that is:

1. WPWebChromeClient: used by WPWebViewActivity. This is when asking for VIEW/PREVIEW of a post containing a video from the posts list or the editor.
2. ReaderVideoViewerActivity: this is when tapping on play button on a video from a post card in the main reader streams (like Following or Discover).
3. ReaderWebChromeClient: used by ReaderWebView. This is when opening a post details with a video from the reader.

Special cases:

4. PublicizeWebChromeClient: used by PublicizeWebViewFragment (I think currently not affected by the problem based on the content rendered in the webview; but I covered it nonetheless)
5. GutenbergWebViewActivity 

This PR introduces a `WebChromeClientWithVideoPoster` abstract base class that provides the `getDefaultVideoPoster` method with a default drawable poster. First 4 scenarios above are covered; the GutenbergWebViewActivity scenario related to not supported blocks fallback (see `gutenbergDidRequestUnsupportedBlockFallback`)  still uses `WebChromeClient`. I would ping someone from GB teams to further dig into that one (let me know wdyt).

**NOTE:** I think this PR is a containment action but AFAIU we have another issue. If I'm not wrong, the webview always uses the default poster (provided by us in this PR for API < 29, and the one returned by `super.getDefaultVideoPoster()` in API >= 29; but essentially does not present a `preview` poster from the video). If you can confirm that this is true I can file a dedicated GH issue, let me know 🙇 ).

| Default video poster on API 29 as provided by the WebChromeClient | Default video poster on API 28 as provided by the WebChromeClientWithVideoPoster |
|---|---|
| image | Screenshot_1606953389 |

### Cases 1, 2, 3
Replicate using develop

- Go to each of the 3 scenarios places in the app
- Try to visualize a post with a video
- Check the app crashes

Confirm the fix in this PR

- Go to each of the 3 scenarios places in the app
- Try to visualize a post with a video
- Check the app does not crash and uses the default video placeholder

### Smoke testing

- Smoke test cases from 1 to 4.

### Check Bitmap memory is released
As per Jirka suggestion on our quick discussion in slack I checked in the profiler that the Bitmap is released when deallocating the client. As usual forcing of 2-3 GC cycles is needed. Would be good if you could confirm it as well, thanks 🙇 .

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by malinajirka — COMMENTED** [review]
Thanks for working on this @develric!

The changes look good to me ;). However, I'm not able to replicate the issue on `develop`. I tested it on Emulator API 24 and API 30 and the app didn't crash. Were you able to simulate the crash on your device/emulator?

**Comment by develric** [comment]
Hey @malinajirka, thanks for the review 🙇 . 

>Were you able to simulate the crash on your device/emulator?

Yep I'm able to reproduce the crash on a Pixel 2 Emu API 23 using develop and this [post](https://demo2020042702.wordpress.com/2020/12/01/test-std-video/) 

Let's dig this further on Monday, have a nice we 👋

**Comment by malinajirka** [comment]
Thanks @develric!

I was able to reproduce the crash on Pixel 2 API 23 emulator. I tested the steps and I can confirm the fix works as described. 🎉 

> I think this PR is a containment action but AFAIU we have another issue. If I'm not wrong, the webview always uses the default poster (provided by us in this PR for API < 29, and the one returned by super.getDefaultVideoPoster() in API >= 29; but essentially does not present a preview poster from the video). If you can confirm that this is true I can file a dedicated GH issue, let me know 🙇 ).

I'm able to see valid previews on discover when I follow "Video" topic. So there are cases when it's available.

I noticed that when the video preview is not available and we show the default poster, the video preview doesn't appear on the post list (it appears only in post detail). 

Either way, I think it might be good to create an issue. It's quite suspicious that the "missing default poster" crash started appearing 7 months ago and not sooner - perhaps we broke the video preview for some videos around that time. Wdyt?

**Review by malinajirka — APPROVED** [review]

**Comment by develric** [comment]
Hey @malinajirka, thanks for the review 🙇 . I'm moving this PR to the new flow with modularised Utils lib, so I was wondering if you could have a look into this in case I'm missing any step, thanks 😄 .

This is the companion Utils repo PR: wordpress-mobile/WordPress-Utils-Android#55 . I referenced the current sha from that PR. I will take care to update it with the `1.30.1-beta.2` once we have the binary lib into bintray (that AFAIU we will have once that PR is merged into develop).

>Either way, I think it might be good to create an issue. It's quite suspicious that the "missing default poster" crash started appearing 7 months ago and not sooner - perhaps we broke the video preview for some videos around that time. Wdyt?

Agree. Opened #13589

Re this one:
>the GutenbergWebViewActivity scenario related to not supported blocks fallback (see gutenbergDidRequestUnsupportedBlockFallback) still uses WebChromeClient. I would ping someone from GB teams to further dig into that one.

pinging @hypest if anyone from GB teams can have a look to evaluate if anything related to this must be done there.

**Review by malinajirka — APPROVED** [review]
I've tested the app and it works as expected even after the extraction to WPUtils repo. Thanks @develric!

**Comment by hypest** [comment]
> This PR introduces a WebChromeClientWithVideoPoster abstract base class that provides the getDefaultVideoPoster method with a default drawable poster. First 4 scenarios above are covered; the GutenbergWebViewActivity scenario related to not supported blocks fallback (see gutenbergDidRequestUnsupportedBlockFallback) still uses WebChromeClient. I would ping someone from GB teams to further dig into that one (let me know wdyt).

Not urgent but, it would be cool if you could give a quick look at this PR @marecar3 to check if there's something we need to do and I will find someone to work on it, thanks!

**Pull request merged**
