### PR TITLE
[Dependency Updates] Update `googleMaterialVersion` to 1.9.0

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #17798

This PR updates `googleMaterialVersion` to [1.9.0](https://github.com/material-components/material-components-android/releases/tag/1.9.0).

PS: Since this library was anyway pointing to `1.6.0-alpha01` (it seems for some time now), the below commits was for documentation purposes only and weren't causing any actual changes whatsoever:

- [Update google material to 1.3.0](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/c33137db12fa1a0c63ed3569cf77d15a495dabc2)
- [Update google material to 1.4.0](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/9c0bbcb3432c48bf819d259a4040bc6674822f40)
- [Update google material to 1.5.0](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/ea1f9eed83666708ebe3b22d2c4dbfa0b6075fa5)

-----

PS: @AjeshRPai I added you as the main reviewer, randomly so, since I just wanted someone from the WordPress team to be aware of and sign-off on that change for WPAndroid. I also added the @wordpress-mobile/apps-infrastructure team, but this in done only for monitoring purposes, as such, I am not expecting any active review from that team. Thus, feel free to merge this PR if you deem so.

-----

App UI Fix List:

1. [Replace material check box with with checkbox on every layout](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/2d26d31fd37a9bcb6b5da968a55681a073012160) (due to `1.7.0`)

Compile Errors Fix List:

1. [Replace not found m3 sys res on jetpack powered bottom sheet](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/032c245e08642a4b5f2c9472a555b14a851504f0) (due to `1.6.1`)
    - FYI: @ravishanker since you introduced this `@dimen/m3_sys_typescale_headline_large_text_size` dimension and assigned it to `android:textSize` via this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17039) [[commit](https://github.com/wordpress-mobile/WordPress-Android/commit/c140292526d7adedb475f85e7acfcbbd717fc9b3)], let me know if this fix makes sense to you too.
3. [Replace not found m3 sys res on jetpack feature removal overlay](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/72ff376eaea6e2323e0071c00eaa49ebf0a04ec1) (due to `1.6.1`)
    - FYI: @AjeshRPai since you introduced this `@dimen/m3_sys_typescale_headline_medium_text_size` dimension and assigned it to `app:autoSizeMinTextSize` via this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17510) [[commit](https://github.com/wordpress-mobile/WordPress-Android/commit/b0ff534e06e6f14a7e887ec42dc250a9b0a97e8b)], let me know if this fix makes sense to you too. Or, if you would prefer this dimension to remain `28sp` and be either hardcoded or extracted to a newly `dimen` resource. 🤔 

Compile Warnings Resolution List:

1. [Resolve chip group checked change listener deprecation warning](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/dd0d27f5cb2bb19ceaa60fb0f235c6eee5d14da5) (due to `1.6.1`)

List Warnings Suppression List:

1. [Suppress restricted api lint error on wp dialog snackbar](https://github.com/wordpress-mobile/WordPress-Android/pull/18433/commits/936a486a391fc324be431434fac8173653507e50) (due to `1.6.1`)

-----

## To test:

1. See the dependency tree diff result and verify correctness.
2. Thoroughly smoke test both, the WordPress and Jetpack apps, and see if everything is working as expected.
3. In addition to the above smoke test, you can expand the below and follow the inner and more explicitly test steps within, which is mainly related to the fixes (see above) and transitive updates on external and internal libraries (see [diff](https://github.com/wordpress-mobile/WordPress-Android/pull/18433#issuecomment-1548105947)):

#### `1.6.1` Update:

<details>
    <summary>1. Jetpack Feature Full Screen Overlay [JetpackFeatureFullScreenOverlayFragment.kt + jetpack_feature_removal_overlay.xml]</summary>

ℹ️ This test applies to the `WordPress` app.

- Go to `My Site` tab -> `Site Picker` (down-arrow).
- Click the `plus` (+) button to add a new site.
- Choose `Create WordPress.com site` when the dialog appears.
- Verify that the `Jetpack Feature Full` screen overlay is shown and functioning as expected.

</details>

<details>
    <summary>2. Jetpack Powered Bottom Sheet [JetpackPoweredBottomSheetFragment.kt + jetpack_powered_bottom_sheet.xml]</summary>

ℹ️ This test applies to the `WordPress` app.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section in the middle and click on its `Activity Log` option.
- You will notice the `Moving to the Jetpack app in a few days.` bottom sheet, click on it.
- Verify that the `Jetpack Powered` bottom sheet is shown and functioning as expected.

</details>

<details>
    <summary>3. Jetpack Static Poster Screen [ChipsViewHolder.kt]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Traffic` section in the middle and click on its `Stats` option.
- Verify that the `Views & Visitors` card is shown and functioning as expected.
- More specifically, click on the `Visitors` chip (at the bottom of the card) and verify that the UI is updated to show visitors, then switch back by clicking on the `Views` chip and verify that the UI is updated to show views.
- Finally, click on the `VIEW MORE` button (top right) and verify that the `Views & Visitors` screen is shown and functioning as expected. Click again the on `Visitors` and `Views` chips to verify that everything is working as expected.

</details>

<details>
    <summary>4. Dialog Snackbar Component [WPDialogSnackbar.java]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.

- Verify that the dialog snackbar is still shown were needed and working as expected.

</details>

#### `1.7.0` Update:

<details>
    <summary>1. Activity Type Filter Screen [ActivityLogTypeFilterViewHolder.kt + activity_log_type_filter_item.xml]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section in the middle and click on its `Activity Log` option.
- Find the `Activity Type` filter on top and click on it to navigate to the `Activity Type Filter` screen.
- Filter by various activity types and verify that the checkbox UI is updated accordingly on both, the light and dark theme.

</details>

<details>
    <summary>2. Restore/Download Backup Screen [JetpackCheckboxViewHolder.kt + jetpack_list_checkbox_item.xml]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section in the middle and click on its `Activity Log` option.
- Find an event and click on it.
- Click on the `RESTORE` and `DOWNLOAD BACKUP` button to navigate to the `Restore` and `Download Backup` screen respectively.
- Filter by various restore items and verify that the checkbox UI is updated accordingly on both, the light and dark theme.

</details>

<details>
    <summary>3. Related Posts Settings Dialog [RelatedPostsDialog.java + related_posts_dialog.xml]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section at the bottom and click on its `Site Settings` option.
- Find the `Writing` section in the middle and click on its `Related Posts` option.
- A `Related Posts` dialog will appear, enable the `Show Related Posts` option. This will enable
the `Show Header` and `Show Images` checkboxes.
- Enabled/Disable the `Show Header` and `Show Images` checkboxes and verify that the UI is updated
accordingly on both, the light and dark theme.

</details>

#### `Internal` Libraries:

<details>
    <summary>1. Post Editing Flow [libs:editor]</summary>

️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ This test makes sure that the `Post Editing` flow, which comes from the [libs:editor](https://github.com/wordpress-mobile/WordPress-Android/tree/trunk/libs/editor)
module is also working as expected and that any transitive dependency changes aren't affecting
any `Material` related components.

- Add a new `blog` post.
- Add as many blocks as possible, along with any combination of those (like the `paragraph`, `heading`,
`image`, `video`, `separator`, `quote`, `gallery`, `columns`, `rows` blocks).
- Verify that the `Post Editing` screen, along with all the blocks you added, are shown and
that everything is functioning as expected.
- Publish the post and verify that it is displayed as expected both, on the mobile and web.

</details>

<details>
    <summary>2. Image Editing Flow [libs:image-editor]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ This test makes sure that the `Image Editing` flow, which comes from the [libs:image-editor](https://github.com/wordpress-mobile/WordPress-Android/tree/trunk/libs/image-editor)
module is also working as expected and that any transitive dependency changes aren't affecting
any `Material` related components.

- Add a new `blog` post.
- Add a new `image` block.
- Choose an image and wait for it to be uploaded within the `image` block.
- Click on the `media options` of this image (top right) and then click `edit`.
- Verify that the `Edit Image` screen is shown and functioning as expected.
- Crop the image and click the `done` menu option (top right).
- Make sure the image is updated accordingly.

</details>

#### `External` Libraries:

<details>
    <summary>1. Login Flow [org.wordpress:login]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ This test makes sure that the `Login` flow, which comes from the [com.wordpress:login](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android)
library is also working as expected and that any transitive dependency changes aren't affecting
any `Material` related components.

- Log out of the app (if already logged-in).
- Verify that the `Login` screen is shown and functioning as expected.

</details>

<details>
    <summary>2. Story Flow [com.automattic:stories]</summary>

ℹ️ This test applies to the `Jetpack` app.
❗️ This test makes sure that the `Story` flow, which comes from the [com.automattic:stories](https://github.com/Automattic/stories-android)
library is also working as expected and that any transitive dependency changes aren't affecting
any `Material` related components.

- Create a new `story` post.
- Add a couple of `images` to that story.
- Add a some `text` on top of any image you uploaded.
- Verify that everything is functioning as expected and that you can publish the story.
- Publish the story and make sure that the story has been published as expected.

</details>

<details>
    <summary>3. About App Screen [com.automattic:about]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ This test makes sure that the `About App` screen, which comes from the [com.automattic:about](https://github.com/Automattic/about-automattic-android)
library is also working as expected and that any transitive dependency changes aren't affecting
this `Material` related components.

- Go to `My Site` tab and navigate to the `Me` screen (click on avatar at top-right).
- Tap the `About App` item on the `Me` screen you are currently at.
- Verify that the `About App` screen is shown and functioning as expected.

</details>

<details>
    <summary>4. Contact Support Screen [com.zendesk:support]</summary>

ℹ️ This test applies to the `Jetpack` app.
❗️ This test makes sure that the `Contact Support` screen, which comes from the [com.zendesk:support](https://github.com/zendesk)
library is also working as expected and that any transitive dependency changes aren't affecting
this `Material` related components.

- Go to `My Site` tab and navigate to the `Me` screen (click on avatar at top-right).
- Tap the `Help` item on the `Me` screen you are currently at, and then the `Contact Support` item within.
- Verify that the `Contact Support` Zendesk related screen is shown and functioning as expected.

</details>

#### `Other`:

<details>
    <summary>1. Snackbar + Snack Accessibility [org.wordpress:utils]</summary>

ℹ️ This test applies to the `Jetpack` app.
❗️ This test makes sure that any and all `Snackbar` related functionality, especially the
`getSnackbarDuration` accessibility related one, which is used mainly via snackbar related classes
and `SitePickerActivity`, which comes from the [org.wordpress:utils](https://github.com/wordpress-mobile/WordPress-Utils-Android) library is also working as
expected and that any transitive dependency changes aren't affecting this `Material` related components.

- Go to `My Site` tab -> `HOME` sub-tab.
- Find the `Get to know the app` card and click on it.
- The `Get to know the app` screen should be shown. Start the flow by clicking on the
`Check your site stats` button.
- Verify that the `snackbar` is shown and functioning as expected.
- Try again with accessibility enabled and verify that the snackbar duration is increased.

</details>

<details>
    <summary>2. WPTextInputLayout [org.wordpress:utils] 🤔</summary>

❓ From the looks of it, this layout is unused both, not only in the `WordPress` and `Jetpack` apps, but also in the [WordPress-Login-Flow-Android](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android) library, which is were it was supposed to be used in anyway (see [here](https://github.com/wordpress-mobile/WordPress-Android/pull/6776)). Also, see [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/9905) on a related crash, which is an interesting thread to read, but I still can't figure out what happen to this layout and whether it was removed somehow/somewhere after all. Maybe it is time for us to remove it from the [WordPress-Utils-Android](https://github.com/wordpress-mobile/WordPress-Utils-Android) library, not sure...

</details>

-----

## Merge instructions

- [x] Wait for [this other](https://github.com/wordpress-mobile/WordPress-Android/pull/18395) PR to be reviewed, tested and approved.
- [x] Update this PR with latest `trunk` and make sure everything is still working as expected.
- [x] Wait for this [Compose/Kotlin](https://github.com/wordpress-mobile/WordPress-Android/pull/18364) PR to be tested and approved.
    - FYI: This is because, as seen by the [diff](https://github.com/wordpress-mobile/WordPress-Android/pull/18433#issuecomment-1548105947) (at this point), Kotlin is being transitively updated to [1.7.10](https://github.com/JetBrains/kotlin/releases/tag/v1.7.10), something to avoid and depend on updating Kotlin explicitly.
- [x] Update this PR with latest `trunk` and make sure everything is still working as expected.
- [x] Remove `[PR] Not Ready For Merge]` label.
- [ ] Merge PR to `trunk`.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Potential breakage or misbehaviour of screens and UI components as `Material Components` is a library that is being used across many, if not all screens, since amongst others it is also driving the `styles.xml` and the main `Base.Wordpress` style/theme.
    - Some of the transitive dependencies added might be causing some kind of misbehaviour.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - See `To test` section.

4. What automated tests I added (or what prevented me from doing so)

    - N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [ ] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by ParaskP7** [comment]
> UI Changes testing checklist:

FYI: As part of this dependency update, and since `Material` is totally related with UI, I went ahead and tested both apps, Jetpack and WordPress, against as many items on this checklist as I thought fits the purpose of this PR. I have good and bad news:

PS: I didn't test the below UI changes testing checklist items:

- [x] ...
- [ ] Talkback.
- [x] ...
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

-----

#### Good news! 🎉

I identified nothing related to this `Material` dependency update, everything seemed to be working as expected. ✅

-----

#### Bad news! 🤷

I identified a number of generic issues (of various weight), some known, while others not so much (maybe), still, none is related to this `Material` dependency update itself, but still, good if we dealt with them, at some point, and as part another task, or set of tasks:

1. `Jetpack`: Issue with `Hebrew` and `Indonesian` languages. FYI: @RenanLukas is already working on that (see `C0180B5PRJ4/p1684312232589679`).
2. `Jetpack`: Issue with `Reader` tabs not changing language when the app language is changed (by persisting the login language).
3. `WordPress`: Crash when trying to close the `Create a new WordPress site with the Jetpack app` screen overlay after rotating it.
4. `Jetpack`: RTL is not working as expected while creating `Stories`.
5. `Jetpack`: On the `Add New Card` settings screen within `Stats`, the `All-time` and `Today's Stats` items within the `General` section, and `Followers` item within the `Activity` section are not persisted on save, that is, if you exit and enter `Stats` again (or by simple rotating the screen, changing the language, or any configuration change for that matter).
6. `Jetpack`: Some `Jetpack Compose` related screen are not rotating to landscape (like the `Learn more`, `Blaze`, etc).
7. `Jetpack`: When entering the `Blaze a Post now` screen, if you switch the theme, change the language, or any configuration change for that matter (it seems), the `Blaze a Post now` screen will exit, navigating the user back to the previous `Blaze` screen.
8. `Jetpack`: When larger fonts in combination with languages with large words make the `Blaze a Post now` button text on the `Blaze` screen to be positioned outside of the button's display.

**Review by ravishanker — COMMENTED** [review]
LGTM 👍

**Comment by AjeshRPai** [comment]
Hey @ParaskP7 👋🏼 
Thanks for the ping and the detailed commit message. 

>FYI: @AjeshRPai since you introduced this @dimen/m3_sys_typescale_headline_medium_text_size dimension and assigned it to app:autoSizeMinTextSize via this https://github.com/wordpress-mobile/WordPress-Android/pull/17510 [[commit](https://github.com/wordpress-mobile/WordPress-Android/commit/b0ff534e06e6f14a7e887ec42dc250a9b0a97e8b)], let me know if this fix makes sense to you too. Or, if you would prefer this dimension to remain 28sp and be either hardcoded or extracted to a newly dimen resource. 🤔

AFAIK I had introduced this value with design input from @osullivanchris. I would let @osullivanchris take this call. To let understand @osullivanchris better. @ParaskP7 is updating the material library and the reference to the material text style size is no longer avaiable, closest value is 24sp. So do we need to keep the min text size of the Jetpack powered title in jetpack feature overlay as 28sp or will 24sp do?. Below is a screenshot from the original PR with min text size as 28sp

Screenshot 2023-05-19 at 3 42 37 PM

**Comment by osullivanchris** [comment]
@AjeshRPai that's ok to me 👍

**Comment by ParaskP7** [comment]
Awesome, thanks you both for the confirmation on that, @AjeshRPai and @osullivanchris ! 🙇 ❤️ 🚀

**Review by AjeshRPai — APPROVED** [review]
Hey @ParaskP7 , 
Sorry for the delay in the review. The smoke testing took more time than expected. Everything works as expected. I have tested all the scenarios explained below. 

## Tested the following

1. See the dependency tree diff result and verify correctness - ✅
2. Thoroughly smoke test both, the WordPress and Jetpack apps, and see if everything is working as expected - ✅
3. In addition to the above smoke test, I have tested the scenarios you have described in each section. 

### `1.6.1` Update:

- [x]  Jetpack Feature Full Screen Overlay [JetpackFeatureFullScreenOverlayFragment.kt + jetpack_feature_removal_overlay.xml] - ✅
- [x]  Jetpack Powered Bottom Sheet [JetpackPoweredBottomSheetFragment.kt + jetpack_powered_bottom_sheet.xml] - ✅
- [x]  Jetpack Static Poster Screen [ChipsViewHolder.kt] ✅
- [x]  Dialog Snackbar Component [WPDialogSnackbar.java] ✅

### `1.7.0` Update:

- [x]  Activity Type Filter Screen [ActivityLogTypeFilterViewHolder.kt + activity_log_type_filter_item.xml] - ✅
- [x]  Restore/Download Backup Screen [JetpackCheckboxViewHolder.kt + jetpack_list_checkbox_item.xml] - ✅
- [x]  Related Posts Settings Dialog [RelatedPostsDialog.java + related_posts_dialog.xml] - ✅

### `Internal` Libraries:

- [x]  Post Editing Flow [libs:editor] ✅
- [x]  Image Editing Flow [libs:image-editor] ✅

### `External` Libraries:

- [x]  Login Flow [org.wordpress:login] - ✅
- [x]  Story Flow [com.automattic:stories] - ✅
- [x]  About App Screen [com.automattic:about] - ✅
- [x]  Contact Support Screen [com.zendesk:support] - ✅

### `Other`:

- [x]  Snackbar + Snack Accessibility [org.wordpress:utils] - ✅
- [x]  WPTextInputLayout [org.wordpress:utils]

>❓ From the looks of it, this layout is unused both, not only in the `WordPress` and `Jetpack` apps, but also in the [[WordPress-Login-Flow-Android](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android)](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android) library, which is were it was supposed to be used in anyway (see [[here](https://github.com/wordpress-mobile/WordPress-Android/pull/6776)](https://github.com/wordpress-mobile/WordPress-Android/pull/6776)). Also, see [[this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/9905)](https://github.com/wordpress-mobile/WordPress-Android/issues/9905) on a related crash, which is an interesting thread to read, but I still can't figure out what happen to this layout and whether it was removed somehow/somewhere after all. Maybe it is time for us to remove it from the [[WordPress-Utils-Android](https://github.com/wordpress-mobile/WordPress-Utils-Android)](https://github.com/wordpress-mobile/WordPress-Utils-Android) library, not sure...

Yup, am not sure either. I think we can safely remove the `WPTextInputLayout`. I couldn't find any usages. It looks like `WPLoginInputRow` is the view that's being used in login screen.

**Comment by ParaskP7** [comment]
This is awesome @AjeshRPai , thank you SO MUCH for reviewing, testing and merging this, you are a rockstar! 🪨 + 🌟 x 🙇 ❤️ 🚀

**Pull request merged**
