### PR TITLE
Media upload error codes wpcom jp in media lib

### PR DESCRIPTION
**Pull request by develric**
This PR is part of a series related to #12325 

The changes here should address the Media Library with WP.com/JP scenario. The equivalent scenarios for GB Editor will be covered in subsequent PRs.

This has a companion FluxC PR [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1657) 

Here below the error messages you should get from endpoint API for `rest_upload_limited_space`, `rest_upload_file_too_big` and `rest_upload_user_quota_exceeded`

```
rest_upload_limited_space|Not enough space to upload. 3,145 KB needed. Back

rest_upload_file_too_big|This file is too big. Files must be less than 1500000 KB in size. Back

rest_upload_user_quota_exceeded|You have used your space quota. Please delete files before uploading. Back
```

Note that we changed the FluxC to get the user message part of the string (that after the `|` sign) to be localized from the API (adding the `locale` query param that was not provided before).

One thing we should consider is maybe to filter out the ` Back` ending part, it does not seem to be a message to the user and not sure how it is used.

### To test:
The following apply both to WP.com and JP sites.

- Open the Media Library screen and try to upload a file
- Force trigger the 3 errors as described above (I can provide access to my sandbox or you can use Charles proxy rewrite feature or AS debugger for this)
- Check you get the API user message in the snackbar
- Check you get the message localized if you change app language

UPDATE: while further checking this I see the the message is cut in the snackbar since too long, maybe something we can discuss and address in another PR.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
Hey @planarvoid just noting here that I removed the [matching pattern](https://github.com/wordpress-mobile/WordPress-Android/pull/12620/commits/402ef6efd125ced789db5dbed9ce3c7a965f9e5e) we were doing in the MediaError message in case of restricted files upload. Now we are mapping the 400 BAD_REQUEST error code so that message is no more routed to GENERIC_ERROR logic. Also we are actually relying on API translated messages.

**Review by planarvoid — APPROVED** [review]
Looks good 👍 , feel free to merge this once the FluxC changes are approved and merged

**Comment by develric** [comment]
Moving the milestone to 15.7 since makes sense to take care of [this](https://github.com/wordpress-mobile/WordPress-Android/pull/12672#issuecomment-674990529) design improvements before to ship these chained PRs.

**Review by planarvoid — APPROVED** [review]
LGTM 👍  feel free to merge it after the FluxC is merged

**Pull request merged**
