### PR TITLE
Issue/8643 full screen dialog

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add a full-screen dialog interface for the ***Customize Your Site*** and ***Grow Your Audience*** tasks as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8643.  See the screenshots below for illustration.

v2_list

#### Note
The completed tasks are shown at the bottom of the list without the expandable section as shown in the design mockups.  That will be addressed in a separate pull request as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8645.  There are three `// TODO: Quick Start -` items included in these changes that are related to analytics and new tasks.  They will be addressed in a separate pull requests as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8647 and https://github.com/wordpress-mobile/WordPress-Android/issues/8649.  The old seven tasks excluding ***Create your site*** will start the task tutorial, but the new four tasks will not.  The old seven task are listed below:
- Create your site
- View your site
- Browse themes
- Customize your site
- Add social media account
- Publish a post
- Follow other sites

### Test
0. Select site with Quick Start in progress.
1. Go to ***Sites*** tab.
2. Notice ***Next Steps*** view is shown.
3. Tap ***Customize Your Site*** type.
4. Notice ***Customize Your Site*** tasks are shown.
5. Tap old task in list.
6. Notice task tutorial is shown.
7. Tap ***Customize Your Site*** type.
8. Tap new task in list.
9. Notice task tutorial is not shown.
10. Tap ***Grow Your Audience*** type.
11. Notice ***Grow Your Audience*** tasks are shown.
12. Tap old task in list.
13. Notice task tutorial is shown.
14. Tap ***Grow Your Audience*** type.
15. Tap new task in list.
16. Notice task tutorial is not shown.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good!

One thing:
Is there a shadow or a dark stroke beneath the whole list?

**Comment by theck13** [comment]
> Is there a shadow or a dark stroke beneath the whole list?

Yep, there is a shadow at the bottom since the list has a card view background.  I used that in anticipation of the tablet view seen [here](https://user-images.githubusercontent.com/3827611/49227002-ac469a00-f3ad-11e8-99f8-0f818f39de0e.png), which will be addressed in a subsequent pull request as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8700.

**Comment by theck13** [comment]
I updated the divider color in 0e3199e.  Now it matches the mockups and the ***Sites*** view from https://github.com/wordpress-mobile/WordPress-Android/pull/8707.

**Comment by theck13** [comment]
> Can we only show the shadow when the card view reaches it's maximum width?

We can have a different layout for various screen widths (e.g. 600dp, 720dp, etc.).  Is that what you mean?  If so, would you want a flat white background for the default layout and the card view layout for the wider screens?  What should that maximum width be in dp?

**Comment by SylvesterWilmott** [comment]
>We can have a different layout for various screen widths

Yes, for tablet sizes we should apply a maximum width of 512dp and add a shadow, otherwise it's full width and without a shadow.

**Comment by theck13** [comment]
I updated the list background in 2fa5d9c.  We can address the card view and tablet layouts in https://github.com/wordpress-mobile/WordPress-Android/issues/8700.

**Comment by SylvesterWilmott** [comment]
Looks awesome, thanks!

**Pull request merged**
