### PR TITLE
Gutenberg: update to v1.26.0

### PR DESCRIPTION
**Pull request by pinarol**
gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2153
WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/13878

To test:

**Bug fix**

- [x] Fix: remove extra padding for post title and first `Paragraph` block  https://github.com/wordpress-mobile/gutenberg-mobile/pull/2095
- [x] Layout Template Modal & Button block - Orientation fixes https://github.com/wordpress-mobile/gutenberg-mobile/pull/2086
- [x] Fix: prevent ripple effect on slider cell in BottomSheet and disable it completely on iOS https://github.com/wordpress-mobile/gutenberg-mobile/pull/2023
- [x] Correct slider step value https://github.com/wordpress-mobile/gutenberg-mobile/pull/2119
- [x] Fix typography breakage in master https://github.com/wordpress-mobile/gutenberg-mobile/pull/2149
- [x] Align plus icon for the iOS Stepper control https://github.com/wordpress-mobile/gutenberg-mobile/pull/2116
ℹ️iOS only but checked all was working on Android

**New feature & Improvement**

- [x] New: Column block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/1661
- [x] New: Blogger template - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2114
- [x] Layout Picker - Keyboard visibility improvements https://github.com/wordpress-mobile/gutenberg-mobile/pull/2123

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pinarol** [comment]
Writing flow sanity check:

- [ ] Undo-redo [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/undo-redo.md)
- [ ] Copy-paste [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md)
- [ ] Splitting blocks [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md)
- [ ] Multiline components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md)
- [ ] Formatting on rich-text based components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md)
- [ ] Block insertion [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/block-insertion.md)

**Comment by geriux** [comment]
All tests done! ✅

**Comment by geriux** [comment]
FYI the `gutenberg-mobile` ref is behind one commit (Podfile lock update)

**Comment by geriux** [comment]
Tested the new build with:

- [x] [Correct colors usage in Button](https://github.com/WordPress/gutenberg/pull/21603) ✅

**Pull request merged**
