### PR TITLE
Material3 account settings

### PR DESCRIPTION
**Pull request by nbradbury**
As part of #21065 , this updates our account settings to use the new Material3 theme. 

To test, view account settings in both JPAndroid and WPAndroid and verify the correct theme colors are used for its screens and dialogs (green tint for JP, blue for WP).

### Jetpack

https://github.com/user-attachments/assets/fc62f01d-570c-4f4e-ac1c-b281c45e397e

### WordPress

https://github.com/user-attachments/assets/2182e1f3-7d13-4e4d-8ac3-f0ab5a260bee

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by geriux — APPROVED** [review]
I've tested on both Jetpack and WordPress and it looks good! 🚀 One thing I noticed though, I'm not sure if we'd want to tweak the "Close Account" button style when it's pressed. Here's how it looks before and after:

## Before

https://github.com/user-attachments/assets/e6209914-445e-46e1-b97f-b27913bf2e22

## After

https://github.com/user-attachments/assets/cc9a05ef-1714-4793-8ec6-74496262f63f

I'm not a fan of the red color changing in the before video but now it appears it adds a border radius when it's pressed. What do you think?

**Comment by nbradbury** [comment]
> now it appears it adds a border radius when it's pressed. What do you think?

@geriux Thanks for the review! I hadn't noticed the pressed border radius, but I agree that it looks off. I corrected this in [7749c2d](https://github.com/wordpress-mobile/WordPress-Android/pull/21096/commits/7749c2d3d4a1ed76ec4f0820f20306ab0d6a7ab0).


https://github.com/user-attachments/assets/0ecb1b66-88f6-4ba9-b580-06347596e219

**Comment by geriux** [comment]
> @geriux Thanks for the review! I hadn't noticed the pressed border radius, but I agree that it looks off. I corrected this in [7749c2d](https://github.com/wordpress-mobile/WordPress-Android/pull/21096/commits/7749c2d3d4a1ed76ec4f0820f20306ab0d6a7ab0).

Awesome! Thank you for updating it 🚀

**Pull request merged**
