### PR TITLE
Stats revamp v2 guide cards

### LINKED ISSUE #16610: [android] Stats:  Guide Cards

### PR DESCRIPTION
**Pull request by ravishanker**
This PR adds guide cards to Comments, Likes and Followers cards based on certain criteria

Fixes #16610 

To test:

Setup:

- Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
- Select Debug Settings
- Find StatsRevampV2FeatureConfig under Features in development enable it and restart app
- Launch / Re-Launch app
- Go to Stats either using quick links or menu 
- Switch to Insights tab if necessary
- Make sure **Total Likes**, **Total Comments**, **Total Followers** and **Latest Post Summary** cards are visible on Insights tab. If those cards are not present then add them through stats management using either [+ add new stats card ] at the bottom or clicking ⚙️ icon at the top right hand corner.

Test 1: 

- A **guide card** as shown above with latest post and number of likes for that post in bold appears on **Total Likes** card 
- Click on the latest post, it should take to that post
- NOTE: The guide only appears if total likes are one or more

Test 2:
- A **guide card** as shown above appears on **Total Comments** card 
- NOTE: The guide only appears if total followers are one or more

Test 3:
- A **guide card** as shown above appears on **Total Followers** card 
- NOTE: The guide only appears if total followers are 0.  Initially it was supposed to appear when followers %change was negative.  However, it was found out that endpoint only returns total count.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and unit texts

3. What automated tests I added (or what prevented me from doing so)
Updated existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by irfano** [comment]
> NOTE: The guide only appears if total comments are 0. Initially it was supposed to appear when comments %change was negative. However, it was found out that endpoint only returns total count.

Is this note in test 3 correct?

**Comment by irfano** [comment]
> The guide only appears if total likes are one or more

In the screenshot, the total like is 0 but still showing the guide.

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻 
Please just check my comments and ensure if the showing rules are correct. Then we can merge.

**Comment by ravishanker** [comment]
> > The guide only appears if total likes are one or more
> 
> In the screenshot, the total like is 0 but still showing the guide.

It is the card total.  The 0 you're referring to is for the latest post

**Comment by ravishanker** [comment]
> > NOTE: The guide only appears if total comments are 0. Initially it was supposed to appear when comments %change was negative. However, it was found out that endpoint only returns total count.
> 
> Is this note in test 3 correct?

You're right, it was meant to be followers, not comments

**Pull request merged**
