### PR TITLE
Update login lib hash that allows wpcom site address login for JetPack app

### PR DESCRIPTION
**Pull request by ashiagr**
References: https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/80

Now that `Jetpack` site filtering is removed as part of `Jetpack App - Enable Features` (https://github.com/wordpress-mobile/WordPress-Android/pull/15946), this PR updates login lib hash for a fix that matches `wpcom site address login` in the `Jetpack` app with the `WordPress` app.

CC @thehenrybyrd 

To test:

1. Install `Jetpack` app.
2. Click "Enter your exiting site address" on the `Landing` screen.
3. Enter a `wpcom` `simple` site address (note that the `Jetpack` app already allowed `atomic` site address login earlier as it has `Jetpack` installed, so make sure you specifically test a `wpcom` `simple` site).
4. Notice that the app directs to the email login screen.
5. Follow the log in steps. 
6. Notice that the login is successful.

## Merge Instructions
This issue was noticed during beta testing 19.3-rc-1 (p5T066-31e-p2#comment-11484), and so targets `release/19.3` branch.

- Make sure that linked login lib is merged to `trunk`. I can take care of the merging tomorrow.
- Update login lib version inside `build.gradle`.
- Remove `Not Ready for Merge` label and merge the PR.

## Regression Notes
1. Potential unintended areas of impact
Minimal changes are included in the linked login lib PR that filters out `wpcom` sites from the connect site info handling for the `Jetpack` app. These sites are handled by the fallback method that redirects them to `WordPress.com` email login similar to the `WordPress` app. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually.

3. What automated tests I added (or what prevented me from doing so)
 Login lib does not support unit testing for this flow. 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
👋 @AliSoftware, pinging you as this issue was noticed during `19.3` beta testing yesterday and the fix targets `release/19.3` branch. I'll also inform in the Slack channel for more visibility.

**Review by zwarm — APPROVED** [review]
@ashiagr - I reviewed and merged the Login Library changes. As per instructions, I'll leave this merge for you. 👍

**Comment by ashiagr** [comment]
👋 @AliSoftware

I updated login lib version to [trunk commit](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/commit/6c8cd2f3c3873f3beca9309cae18c196df24eb84). I just realized I should have created a tag and updated that instead. Can you please confirm?

**Comment by AliSoftware** [comment]
Yes for code frozen branch we should indeed use a tag 🙇‍♂️
In this case bumping the patch version (3rd digit) is usually the way to go for a betafix that happened after the freeze.

**Pull request merged**
