### PR TITLE
[Home Page Picker] - Fixes title and action bar overlap

### LINKED ISSUE #13558: [Home Page Picker] - title and action bar default action overlap in German
### Expected behavior
The labels should not overlap

### Actual behavior
The "skip" translation for German is "überspringen" and it occupies much more space, overlapping with the title when it's collapsed as you scroll down

overlap

### Steps to reproduce the behavior
1. set your device language to German (Deutsch)
2. open the WPAndroid app, and go to the site picker
3. tap on + 
4. select "WordPress.com-site erstellen"
5. the Design selection screen appears.
6. Scroll down to observe the behavior described above.

### PR DESCRIPTION
**Pull request by antonis**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/13558

## Description
Ellipsize centered title to prevent overlapping in some languages

## To test:

<details>
<summary><strong>To start the Home Page Picker screen</strong></summary>

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
</details>

<details>
<summary><strong>To switch language</strong></summary>

1. From the My Site screen select the user avatar
1. Select App Settings (third option)
1. Tap on the language selection (first option)
</details>

1. Switch the app to language with large words (e.g. Russian or German)
1. Open the Home Page Picker screen
1. Verify that the *Skip* button is visible

## Screenshots

|English|Russian|German|
|---|---|---|
|device-2020-12-08-173013|device-2020-12-08-173121|device-2020-12-08-172906|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hello @iamthomasbishop @kyleaparker @SylvesterWilmott 👋 
I approached solving https://github.com/wordpress-mobile/WordPress-Android/issues/13558 by keeping the title centered and elipsizing it. An alternative might be to align title to the left. Wdyt?

**Comment by chipsnyder** [comment]
Hey @antonis 
I noticed a few landscape inconsistencies that I think may have been introduced with some of the layout changes. I tested on my Pixel 3a and noticed that the header title in landscape mode is gone, then also noticed I now have two layout columns instead of three. I'm wondering if this related to wrapping the view in the `LinearLayout` WDYT?

develop | PR
--- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/101539330-5f1e3b00-396c-11eb-8c99-71109606da93.jpg"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/101539404-79f0af80-396c-11eb-8ede-c777ace33590.jpg"></a></kbd>

**Comment by kyleaparker** [comment]
>I approached solving #13558 by keeping the title centered and elipsizing it. An alternative might be to align title to the left. Wdyt?

I think we should avoid truncating the text if possible. Can we try left aligning the title and wrapping the text onto a second line?

**Comment by antonis** [comment]
Thank you for the prompt feedback @kyleaparker 🙇 

> I think we should avoid truncating the text if possible. Can we try left aligning the title and wrapping the text onto a second line?

I've changed the layout to use the space on the left and if that doesn't work either to use a second line.

|Russian|German|
|---|---|
|device-2020-12-09-155026|device-2020-12-09-154931|

**Comment by antonis** [comment]
Hey @chipsnyder 👋 

thank you for taking the time to review this 🙇 

> I noticed a few landscape inconsistencies that I think may have been introduced with some of the layout changes. I tested on my Pixel 3a and noticed that the header title in landscape mode is gone, then also noticed I now have two layout columns instead of three. I'm wondering if this related to wrapping the view in the `LinearLayout` WDYT?

This seems to be an existing issue. I've managed to reproduce it a few times and applied a workaround with 3eb21580f749cfedd4442ed454308cd5fff0ddeb.
It seems that this came from [DisplayUtils.isLandscape](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/2aade322494df0df01633f1d17880e0bf0f9b969/WordPressUtils/src/main/java/org/wordpress/android/util/DisplayUtils.java#L18) returning the wrong orientation in some cases. I noticed also that when this starts to happen if I restart the app it works correctly again 🤷

**Comment by chipsnyder** [comment]
>  I noticed also that when this starts to happen if I restart the app it works correctly again 🤷

Oh, that's really interesting! Good to know. Thanks for confirming 🙇

**Review by chipsnyder — APPROVED** [review]
LGTM! I am still running into that landscape issue still but restarting does fix it. I agree I don't think it's related to the changes here, I would like to know why it gets confused but we can investigate that later. 

One other thing I noticed but just tangential to the change here. Should we also wrap the main title? 

<kbd><a href="https://user-images.githubusercontent.com/3384451/101672110-753b0280-3a23-11eb-8ab8-73554b0a6574.jpg"></a></kbd>

**Comment by chipsnyder** [comment]
> I think we should avoid truncating the text if possible. Can we try left aligning the title and wrapping the text onto a second line?

On iOS we truncate this title as well. I can spin up an investigation to see how well the system handles wrapping the text.

**Comment by antonis** [comment]
Thanks for checking this again @chipsnyder 🙇 

> I am still running into that landscape issue still but restarting does fix it.

I thought I fixed this. I'll try to revisit this asap.

> On iOS we truncate this title as well. I can spin up an investigation to see how well the system handles wrapping the text.

I checked Android and there at least a few more screens that truncate the title text in some locales (e.g. [1](https://user-images.githubusercontent.com/304044/101673241-9588b280-3a5f-11eb-8f86-e57bf21bdc9b.png), [2](https://user-images.githubusercontent.com/304044/101673256-991c3980-3a5f-11eb-988a-3d4d1136940a.png)).
In my opinion the only way to really handle this type of problems is curating that the translations to fit in the provided space.

**Comment by chipsnyder** [comment]
I added the changes to iOS and the navbar doesn't let the title grow vertically enough to wrap. One option is to shrink the font to fit the space but we could end up with a problem where the font is unreadably small. I think if we wrap the main title (expanded view) so that is readable then ~truncating~ shrink the font of the smaller title (after scrolling) then that would be ideal, but @kyleaparker I would want your opinion after look at our options on iOS:

Current Behavior | Wrapping the Text | Shrinking (1)
--- | --- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/101674494-94875f00-3a26-11eb-8605-731323a13702.jpeg"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/101674629-ba146880-3a26-11eb-8baa-fe519c445dcf.jpeg"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/101674799-f5169c00-3a26-11eb-96a6-7acba80f2dc1.jpeg"></a></kbd>


(1) I don't know if this screenshot provides the best example. That would depend on how long the longest translated text is. That said this is the longest string we have so far out of the translated versions of this text

----
_EDITED_ updated my suggestion to go with shrinking the font size

**Comment by iamthomasbishop** [comment]
@antonis @chipsnyder thanks for the pings, apologies for the delay on my end. I agree w/ @kyleaparker, let's try to avoid truncating if possible. For the Nav/App bar, I was going to suggest what Chip mentioned on iOS (shrinking the font-size dynamically, which I've seen relatively often on iOS) — would be nice if we can make something similar happen on Android. 🤞 

For the large inline title, I would maintain the font-size and just allow that text to wrap to the next line. @kyleaparker do you agree?

**Comment by antonis** [comment]
Hey @chipsnyder 👋 

> I am still running into that landscape issue still but restarting does fix it.

Regarding the landscape issue. Without the fix 3eb21580f749cfedd4442ed454308cd5fff0ddeb applied in this PR (e.g. on `develop`) I'm able to consistently reproduce it with the following steps:
1. Open the App
1. Go to HPP screen
1. Validate that the issue is not reproduced
1. **Change the app language**
1. Go to HPP screen
1. Validate that the **issue is reproduced** (always in my device)
1. If you restart the app everything is back to normal

My guess is that the configuration change applied when you switch language affects the [DisplayUtils.isLandscape](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/2aade322494df0df01633f1d17880e0bf0f9b969/WordPressUtils/src/main/java/org/wordpress/android/util/DisplayUtils.java#L18) configuration orientation retrieval.

With the applied fix in this PR I haven't been able to reproduce it yet. If you have identified a pattern to reproduce this issue please let me know 🙇

**Comment by antonis** [comment]
@iamthomasbishop, @kyleaparker Thank you both for the prompt feedback. I really appreciate this 🙇 

I changed the implementation to match the iOS and allow the text to shrink in the title. If you agree I suggest to proceed with this implementation. Some screenshots bellow.
 
|English|German|Russian|
|---|---|---|
|device-2020-12-10-132428|device-2020-12-10-132105|device-2020-12-10-132203|

|Wrap header text on small device|
|---|
|Screenshot_1607599491|

**Comment by chipsnyder** [comment]
Hey @antonis I did a fresh install with this [APK](https://86959-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-13563-build-86959.apk). On the last build I tested I was getting the error seemingly sporadically but I didn't pay close enough attention to the repo steps. On this build I still see the rotation issue with the steps you posted here: 

> 1. Open the App
> 1. Go to HPP screen
> 1. Validate that the issue is not reproduced
> 1. **Change the app language**
> 1. Go to HPP screen
> 1. Validate that the **issue is reproduced** (always in my device)
> 1. If you restart the app everything is back to normal

However, once I kill the app and come back the issue hasn't appeared again. I'm testing on a Pixel 3a running API 29

______

For the change to auto shrink the heading and wrap the title looks good and is working well 👍

**Comment by kyleaparker** [comment]
>For the large inline title, I would maintain the font-size and just allow that text to wrap to the next line. @kyleaparker do you agree?

Agreed!

>I changed the implementation to match the iOS and allow the text to shrink in the title. If you agree I suggest to proceed with this implementation. Some screenshots bellow.

This is looking good to me @antonis  👍

**Pull request merged**
