### PR TITLE
Issue/3979 reader referrer

### LINKED ISSUE #3979: Reader: Add referrer to links opened from the reader detail and comments
Same as [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/5150) on iOS.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3979 - Adds referrer information to links opened via the reader:
* For links opened in the internal browser we add the referrer via a header.
* For links opened in the external browser, we add a `utm_source` query param to the URL
In both cases the referrer is set as `https://wordpress.com`.

### CODE REVIEW

**Comment by daniloercoli** [comment]
screen shot 2016-05-04 at 16 35 02

Opening an article in the external browser, from the internal in-app webview, doesn't add the referrer parameter to the URL. See the picture above. (The in-app web view is correctly loaded with the `referer` parameter set, but then it's not passed to the external browser).

Instead, opening an article in the external browser, from the reader detail view, does add the referrer parameter to the original URL.

**Comment by nbradbury** [comment]
> Opening an article in the external browser, from the internal in-app webview, doesn't add the referrer parameter to the URL

Oof, I should've thought of that situation. I'll fix that and ping you when it's ready. Thanks!

**Comment by nbradbury** [comment]
@daniloercoli Ready for another round.

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
