### PR TITLE
Merge final release/20.9

### PR DESCRIPTION
**Pull request by AliSoftware**
- [x] `changelog/*.txt` files updated with latest translations
- [x] `values*/strings.xml` updated with latest translations
- [x] Version bumped in `version.properties`
- [x] WPAndroid submitted to Google for review
- [x] JPAndroid submitted to Google for review

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

If I am not mistaken, the new `fastlane/metadata/android/en-US/changelogs/1281.txt` file is missing, can you confirm that? 🤔

**Comment by AliSoftware** [comment]
> 👋 @AliSoftware !
> 
> If I am not mistaken, the new `fastlane/metadata/android/en-US/changelogs/1281.txt` file is missing, can you confirm that? 🤔

What an eagle eye! Thanks so much for noticing that, you're a life-saver!

I also checked at what I submitted to Play Store, and indeed the `<en-US>…</en-US>` entry of the release notes were empty as a result, so indeed we almost submitted a release with no English release notes (and with the default ones falling back to the Arabic ones instead, apparently)!
<table><tr>
  <td>image</td>
  <td>image</td>
</tr></table>


The root cause of this bug is likely due to the same issue that what happened in a 20.6 too (see pdnsEh-jJ-p2#comment-1233), where the `en-GB` translation were missing for the release notes, and since we currently do something very ugly with [mapping the source copy of the `en-GB` locale to retrieve the `en-US`'s `changelogs/*.txt`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/localization.rb#L229-L230), and if there is no `en-GB` entry in GlotPress for a release… then the entire entry is absent from the GlotPress download, hence why we fail to extract the associated source file from it.

We should definitively remove that `en-GB => en-US` hacky mapping at some point, and instead copy the files from the `WordPress/metadata/*.txt` source of truth [like we do for the case of Jetpack](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/localization.rb#L265-L272). I'll try to address that in a dedicated PR on `trunk`.

> **Note**: Ideally in the future we could even consider having `fastlane/*metadata/en-US`  (or even `fastlane/*metadata/default`) be the source of truth, instead of it being `WordPress/*metadata` and then having to copy that over to `fastlane/*metadata/en-US` during final release, that would simplify things greatly. The case for `release_notes.txt` is a bit special though, as at some point during the release that file contains transient content (the release notes extracted from the top section of `RELEASE-NOTES.txt`, before they get editorialized), so that wouldn't solve us keeping to have a separate, transient source of truth for that one I guess?

**Comment by AliSoftware** [comment]
> 👋 @AliSoftware !
> 
> If I am not mistaken, the new `fastlane/metadata/android/en-US/changelogs/1281.txt` file is missing, can you confirm that? 🤔

Fixed in c2bf8ce, and manually updated the Release Notes in Play Store Console accordingly as well, which now defaults back to `en-US` 🎉 

image

**Comment by ParaskP7** [comment]
> What an eagle eye! Thanks so much for noticing that, you're a life-saver!

🦅 👀 

> I also checked at what I submitted to Play Store, and indeed the `<en-US>…</en-US>` entry of the release notes were empty as a result, so indeed we almost submitted a release with no English release notes!

Good thinking, nice catch! 🥇 

> (and with the default ones falling back to the Arabic ones instead, apparently)

😵‍💫 

> The root cause of this bug is likely due to the same issue that what happened in a 20.6 too (see pdnsEh-jJ-p2#comment-1233), where the en-GB translation were missing for the release notes, and since we currently do something very ugly with [mapping the source copy of the en-GB locale to retrieve the en-US's changelogs/*.txt](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/localization.rb#L229-L230), and if there is no en-GB entry in GlotPress for a release… then the entire entry is absent from the GlotPress download, hence why we fail to extract the associated source file from it.

👀 

> We should definitively remove that en-GB => en-US hacky mapping at some point, and instead copy the files from the WordPress/metadata/*.txt source of truth [like we do for the case of Jetpack](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/localization.rb#L265-L272). I'll try to address that in a dedicated PR on trunk.

👍 💯 

> Note: Ideally in the future we could even consider having fastlane/*metadata/en-US (or even fastlane/*metadata/default) be the source of truth, instead of it being WordPress/*metadata and then having to copy that over to fastlane/*metadata/en-US during final release, that would simplify things greatly. The case for release_notes.txt is a bit special though, as at some point during the release that file contains transient content (the release notes extracted from the top section of RELEASE-NOTES.txt, before they get editorialized), so that wouldn't solve us keeping to have a separate, transient source of truth for that one I guess?

Thanks for this note! 🙇

**Review by ParaskP7 — APPROVED** [review]
LGTM! 💯 

> Fixed in https://github.com/wordpress-mobile/WordPress-Android/commit/c2bf8ce8be1f67b757334f0361d331639f323ae4, and manually updated the Release Notes in Play Store Console accordingly as well, which now defaults back to en-US 🎉

Awesome, thanks for the double fix @AliSoftware ! 🥇 ❤️ 🚀

**Comment by AliSoftware** [comment]
> We should definitively remove that en-GB => en-US hacky mapping at some point, and instead copy the files from the WordPress/metadata/*.txt source of truth [like we do for the case of Jetpack](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/localization.rb#L265-L272). I'll try to address that in a dedicated PR on trunk.

Follow-up on this: https://github.com/wordpress-mobile/WordPress-Android/pull/17341

**Pull request merged**
