### PR TITLE
Issue/7996 actionable empty states (Part 5)

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add actionable empty state to the photo picker.  This was not specifically included in https://github.com/wordpress-mobile/WordPress-Android/issues/7996, but it contained an empty state similar to the media browser.  `ActionableEmptyView` was updated to use the `<merge>` tag for layout optimization and top padding to avoid view clipping.  Also, some instances of the deprecated method `MenuItemCompat.setOnActionExpandListener()` were updated.

#### Photo Picker
0. Use device with no media.
1. Tap ***Create*** button in bottom navigation bar.
2. Tap ***Show Media Options*** button in toolbar.
3. Tap ***Allow*** button if permission has not been granted.
4. Tap ***Allow*** button to grant permission to access media.
5. Notice actionable empty state shown below.

aes_editor_media

#### Top Padding
0. Rotate device into landscape orientation.
1. Go to ***My Site*** tab.
2. Tap ***Media*** item under ***Publish*** section.
3. Tap ***New Media*** action in toolbar.
4. Tap ***Choose from Free Photo Library*** option in menu.
5. Notice actionable empty state shown below.

aes_search_media_stock_padding

### Review
Only one develop and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by theck13** [comment]
I just thought about updating the media permissions view of the photo picker to use `ActionableEmptyView` also.  I added the `[Status] Not Ready for Review` label while I work on that.

**Comment by theck13** [comment]
Replacing the current custom view in the photo picker when allowing/editing media access permissions would look like this.  What do you think, @SylvesterWilmott?

aes_editor_media_permission_allow

aes_editor_media_permission_edit

**Comment by SylvesterWilmott** [comment]
Amazing @theck13 

Thanks for including this!

>Updating the current custom view with ActionableEmptyView in the photo picker when allowing/editing media access permissions would look like this.

I'd just be interested to see some German or Russian translations for the denied access ones since those strings are pretty long. Otherwise looks great.

**Comment by theck13** [comment]
> I'd just be interested to see some German or Russian translations for the denied access ones since those strings are pretty long. Otherwise looks great.

Here's what it looks like in Russian.  The `ActionableEmptyView` is scrollable too.  The current custom empty view for the photo picker is not.

aes_editor_media_russian

**Comment by SylvesterWilmott** [comment]
>Here's what it looks like in Russian. The ActionableEmptyView is scrollable too. The current custom view for the photo picker is not.

Thanks! 5 lines is a lot here but actually it's not going to be too bad if we scale the image down to max 120dp in height if not to avoid scrolling then just for consistency across other empty states.

Again, thanks for adding this to the project!

**Comment by theck13** [comment]
> it's not going to be too bad if we scale the image down to max 120dp in height

I added the actionable empty view with the `120dp` height image in bf7fed5.

This pull request is now ready for code review.

**Comment by theck13** [comment]
Yep, the `ActionableEmptyView` was indeed off-center in landscape orientation due to the bottom bar.  I added the `layout_above` attribute to that view in e26bb9d.

**Pull request merged**
