### PR TITLE
Updates Utils & FluxC to a version with sources jar

### PR DESCRIPTION
**Pull request by oguzkocer**
**This PR is used for testing purposes only.**

I am working on publishing the `-sources.jar` files for our projects that are published to S3 and I'd like to use this PR to verify that it works as expected. I've published both FluxC and WordPress-Utils-Android artifacts with their `-sources.jar` files to S3 and now I can navigate to the source files without any issues. @malinajirka @wzieba Can I bother you to test this PR to verify that it works as you were expecting it to?

_Please don't forget to disable composite builds for FluxC & WordPress-Utils-Android projects._

For each of the following lines, I used Android Studio's go to declaration feature (either Command+B or Command+click with a default setup) to test the changes:
* `PostStore` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt#L64) to verify `org.wordpress:fluxc` module
* `VersionUtils` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java#L333) to verify a Kotlin source file for `org.wordpress:utils` module
* `UrlUtils` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java#L187) to verify a Java source file for `org.wordpress:utils` module

**Here are screenshots from current `develop`. Notice the `Decompiled .class` banner:**

Screen Shot 2021-10-21 at 7 41 43 PM
Screen Shot 2021-10-21 at 7 41 28 PM
Screen Shot 2021-10-21 at 7 41 15 PM

**Here are screenshots from this PR:**

Screen Shot 2021-10-21 at 7 40 22 PM
Screen Shot 2021-10-21 at 7 39 53 PM
Screen Shot 2021-10-21 at 7 37 53 PM

### CODE REVIEW

**Comment by oguzkocer** [comment]
@malinajirka @wzieba I forgot to include links to the `-sources.jar` files for these dependencies, in case you want to explore them: (I didn't)

* [utils-95-1b9fd4ddf4a74ecf1e82effd589d5385faddfc76-sources.jar](https://a8c-libs.s3.amazonaws.com/android/org/wordpress/utils/95-1b9fd4ddf4a74ecf1e82effd589d5385faddfc76/utils-95-1b9fd4ddf4a74ecf1e82effd589d5385faddfc76-sources.jar)
* [fluxc-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar](https://a8c-libs.s3.amazonaws.com/android/org/wordpress/fluxc/2160-7ed5d2247456bda1db5ba665b027c92001a495ac/fluxc-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar)
* [fluxc-annotations-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar](https://a8c-libs.s3.amazonaws.com/android/org/wordpress/fluxc/fluxc-annotations/2160-7ed5d2247456bda1db5ba665b027c92001a495ac/fluxc-annotations-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar)
* [fluxc-processor-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar](https://a8c-libs.s3.amazonaws.com/android/org/wordpress/fluxc/fluxc-processor/2160-7ed5d2247456bda1db5ba665b027c92001a495ac/fluxc-processor-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar)
* [woocommerce-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar](https://a8c-libs.s3.amazonaws.com/android/org/wordpress/fluxc/plugins/woocommerce/2160-7ed5d2247456bda1db5ba665b027c92001a495ac/woocommerce-2160-7ed5d2247456bda1db5ba665b027c92001a495ac-sources.jar)

**Review by malinajirka — COMMENTED** [review]
Great job @oguzkocer! I've tested it and works as expected :). Thank you so much for working on this!

**Review by wzieba — COMMENTED** [review]
Works for me too, awesome improvement thank you!

**Comment by oguzkocer** [comment]
> This PR is used for testing purposes only.

This PR has served its purpose, closing now.

**Pull request closed without merging**
