### PR TITLE
Feature/stock photos design review

### PR DESCRIPTION
**Pull request by nbradbury**
All PRs related to stock media have been submitted and merged, so it's ready for a design review. Once this passes design review, it can be merged into the feature branch and then the feature branch can be merged into `develop` 🎉 

[Here's a video](https://cloudup.com/cfmedBgxciE) which demonstrates this feature in full. If this isn't sufficient for a design review, let me know and I'll provide an APK.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Great work, as always! It's damn near perfect, but I'm going to be _that guy_ and nitpick a tiny bit :)

* "Powered by Pexels" should say "Photos provided by Pexels" to match Calypso
* Can we include the [illustration](https://cloudup.com/cHtqk0x0DpT) from the original designs in the empty state? We had discussed there not being a lot of room, but if we were to use the illustration at 100pt height, I think it would work. I will find the illustration for you - I know @mattmiklic also used these in recent empty state designs.
* Should search hide the `search` icon while the search is active? For example, this is how it currently works on Themes, Media Library search pages:

**Comment by nbradbury** [comment]
>  "Powered by Pexels" should say "Photos provided by Pexels" to match Calypso

Corrected in 57a91b8

> Can we include the illustration from the original designs in the empty state?

Oh, I meant to mention this. Yes, we should include that - if you can provide the SVG I'll add it to that screen.

> Should search hide the search icon while the search is active?

Good point. In this case the search is **always** active, so in b4377a4 I removed it entirely (see screenshot below).

screenshot_1522192188

**Comment by iamthomasbishop** [comment]
Awesome, thanks for the updates! One more thing - can we center the empty state (section w/ illustration + copy) vertically between the toolbar and keyboard?

**Comment by nbradbury** [comment]
@iamthomasbishop Good call on centering the empty view - not sure how I didn't see that! I've added that change, and I've also added code that hides the image on smaller screens.

screenshot_1522335911

**Comment by iamthomasbishop** [comment]
Just took this for a spin and functionally it looks perfect to me! My only remaining wish - the tiniest thing - I think the positioning of the empty state could still be slightly lower, maybe 6sp lower.

screen shot 2018-03-29 at 2 28 54 pm

Outside of that, 🚢  it!

**Comment by iamthomasbishop** [comment]
Everything looks good on my end in terms of design review 👍 . 🚢 it!

**Pull request merged**
