### PR TITLE
Add domains button to the me screen

### LINKED ISSUE #19066: 🤖 Add Domains Button to the Me Screen
Add `Domains` button to the "Me" Screen.

## Acceptance Criteria
- A new field titled "Domains" should be visible on the Me Screen.
- Tapping on it should open the Domains List Screen.

### PR DESCRIPTION
**Pull request by mkevins**
Fixes #19066

### Description

This PR adds a "Domains" button to the "Me" screen, hidden by default. This can be enabled via [the testing steps in the corresponding feature flag PR](https://github.com/wordpress-mobile/WordPress-Android/pull/19203#issue-1900384857).

To test:

Enable the feature flag, and navigate to the "Me" screen. Expect to see the "Domains" button.

Note: since the domain management screens are still in development, this is not wired up yet to launch the domain management activity.

## Regression Notes
1. Potential unintended areas of impact
Me screen

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A (declarative UI element hidden by default - a unit test would merely be testing the `visibility` flag).

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by justtwago** [comment]
Same problem with managing the FF as described here: https://github.com/wordpress-mobile/WordPress-Android/pull/19203#issuecomment-1737830286

In addition, according to pc8HXX-1gR-p2, along with `Me > Domains` path, there should be an alternative `My Site > Menu > Domains > Manage all Domains`. I don't see a separate task for it, so just wanted to double-check wthether it should be included in this PR too.

**Comment by mkevins** [comment]
> I don't see a separate task for it, so just wanted to double-check wthether it should be included in this PR too.

Thanks for double checking that. That can be tackled in another task, since the site-related flow will be different in other ways as well.

**Review by justtwago — APPROVED** [review]
Tested it and it looks good for me! Thank you! Since the alternative (My Site > Menu > Domains > Manage all Domains) path is out of scope, I'm hitting the `Approve` :)

**Comment by mkevins** [comment]
Thanks for reviewing!

**Pull request merged**
