### PR TITLE
Woo/aztec design changes

### LINKED ISSUE #1750: Aztec editor: Design changes
It looks like there is no option to customise the styles/colors for the Axztec Toolbar at the moment. This is needed by the Woo app when trying to update product description. Once Aztec is updated, we would need to incorporate changes to the Aztec editor to fix the design changes required.

- Change toolbar border color to `#E6E6E6` 
- Change toolbar background to white
- Change toolbar icon colors to `#595959`

LEFT - What is needed
RIGHT - Current implementation
 .

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes woocommerce/woocommerce-android#1750. This PR adds changes to the Aztec Editor to support customisation of the Aztec Toolbar. 

### Changes
- Added multiple attributes to `AztecToolbar`:
  - `toolbarBackgroundColor` - to change the background color of the Aztec Toolbar.
  - `toolbarBorderColor` - to change the color of the divider above the Aztec toolbar.
  - `toolbarIconNormalColor`, `toolbarIconHighlightColor`, `toolbarIconDisabledColor` - to change the color of the Aztec toolbar button icons.
- Since this PR adds support to change the color of the vector drawable icons used in the Aztec toolbar, I have removed all the drawables under `WordPress-Editor` module.

~**Note that this PR is in draft till this [Aztec PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/900) can be reviewed and merged and then we would need to update the hash to this branch before it can be merged.****~

**I understand the PR file size looks big but most of the changes are the drawable files that have been deleted from the WordPress-Editor module so I felt it shouldn't be a problem.** 

### To test
- Since this PR only makes changes to the styles, smoke testing the Aztec editor by selecting all the toolbar options should suffice. 
 - Testing in API 21, 23, 28 and 29 would be great since the change affects all supported API versions. Without making any modifications to the app activity, the Aztec toolbar should look and function exactly as before. 

#### API 21
. . . 

#### API 23
. . . 

#### API 29
. . . 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
PR is ready for review 👍

**Review by 0nko — COMMENTED** [review]
Nice code dump! I love it when a huge chunk of unused code gets removed :). 

Things are looking solid, but I did find an issue where the **List** and **Header** buttons are highlighted (correctly) in dark mode, but not in light mode (on API 28):

| Light mode | Dark mode |
| --- | --- |
| image | image |

**Comment by anitaa1990** [comment]
Thanks for the review @0nko! 

> Things are looking solid, but I did find an issue where the List and Header buttons are highlighted (correctly) in dark mode, but not in light mode (on API 28):

I noticed the same thing when pulling changes from `develop` so not sure if this has something to do with dark mode rather than changes with this PR.

**Review by 0nko — APPROVED** [review]
Oh ok. Then this PR is a 👍 and I'll create an issue for the other problem.

**Review by cameronvoell — CHANGES_REQUESTED** [review]
@ondrej @anitaa1990 I have this PR open for updating Aztec in gutenberg-mobile => https://github.com/wordpress-mobile/gutenberg-mobile/pull/2170. Once that gets merged we should update the `libs/gutenberg-mobile` submodule reference in this PR to the merged [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) `develop` branch commit so that the Aztec version stays the same in the WordPress-Android and gutenberg-mobile.

**Review by cameronvoell — APPROVED** [review]

**Comment by cameronvoell** [comment]
@anitaa1990 gutenberg-mobile has it's Aztec version in sync with this PR now, so feel free to update the gutenberg-mobile submodule to [9abd4aca67e0a828034edf42871daee285d7b7bd](https://github.com/wordpress-mobile/gutenberg-mobile/commit/9abd4aca67e0a828034edf42871daee285d7b7bd), and everything should be good for merging 👍

**Comment by anitaa1990** [comment]
Thanks for the heads up @cameronvoell! I have updated the gutenberg-mobile hash to the PR and pulled in the latest changes from `develop`. PR ready for merge 👍

**Comment by hypest** [comment]
Looks like many of the CI jobs have failed due to the gutenberg-mobile build on JitPack failing. I've deleted the JitPack build to let it rebuild and restarted the CI jobs.

**Comment by hypest** [comment]
Headsup: this PR is blocked by failing CI jobs because the gutenberg-mobile JitPack-built artifact/dependency fails to build. https://github.com/wordpress-mobile/WordPress-Android/pull/11747 is trying to remedy and it has to target this PR anyway. So, let's merge https://github.com/wordpress-mobile/WordPress-Android/pull/11747 first and then this one.

**Comment by cameronvoell** [comment]
> So, let's merge #11747 first and then this one.

https://github.com/wordpress-mobile/WordPress-Android/pull/11747 is Merged. So know we have shallow submodule enabled(which helped us pass CI), and Aztec versions in synch between WPAndroid and gutenberg-mobile. I did one last build of WPAndroid locally and everything looks good. Nice teamwork @hypest @anitaa1990 !

**Pull request merged**
