### PR TITLE
Editor - Integrate visual editor 0.4

### PR DESCRIPTION
**Pull request by aforcier**
Integrates version 0.4 of the new visual editor into WPAndroid.

wpandroid-editor-0 4-screen

wpandroid-editor-0 4-screen-2-image-settings

<h3>Major changes</h3>

- Image support
  - Adding images from media library
  - Uploading local images (they're uploaded individually as you add them to a post)
  - Cancelling image uploads
  - Retrying failed image uploads
  - Changing image settings (with a visual overhaul of the image settings dialog)
- Added post settings button to ActionBar

Also some minor bug fixes. Full list of changes:

https://github.com/wordpress-mobile/WordPress-Editor-Android/issues?q=milestone%3A0.4

<h3>Notes</h3>
- [Video](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/238)/[galleries](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/239)/[featured images](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/16) aren't supported yet (links to open issues)
- The editor won't display remote images in private blogs ([issue](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/255))
- Sharing media to WordPress isn't supported by the new editor yet ([issue](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/233))

### CODE REVIEW

**Comment by aforcier** [comment]
cc @maxme, @bummytime

**Comment by maxme** [comment]
From my first pass on that PR.

Issues:
* New post, add a picture, tap the back button before it's uploaded, now edit that post, picture is still greyed and won't upload
* I'm not seeing the progress bar. Took me some time to track that down, but my device is set to French locale, and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/visual-editor-sync/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L720-720) that call is localized, so the float "0.1" is formatted to "0,1" using the French locale. That line should be: `String.format(Locale.US, "%.1f", progress);` (or `String progressString = String.valueOf(progress)`).

Minor issue:
* "Post Uploaded" notification now lacks the thumbnail after uploading a Post. (I'm not sure how to solve that: maybe store a thumbnail of the first uploaded image with the Post - and delete it in case it's removed from the Post)

Code:
* This is not introduced in that PR, and that's the first time I see the `WordPressDB.updateMediaUploadState` method, it looks like an old one. We should clean that one a bit (at least use an enum for getting/updating the `uploadState`).
* This [method](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/visual-editor-sync/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1211-1211) is getting big, can we split it in 2? `addMediaNewEditor` / `addMediaLegacyEditor`?

**Comment by maxme** [comment]
Not related to that PR, but while testing on a 4.1.1 emulator, I pasted a string to the content field. Then tried to delete it (by taping the delete key on my keyboard), but I wasn't able to delete that pasted string.

Then I used my up and down arrow keys (on my hardware keyboard) to navigate the contents, the editor was adding "&amp;#x200b;" into the field while spitting this log:

```
10-06 13:48:49.332 7910-7910/org.wordpress.android D/WordPress-EDITOR: Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1 -- From line 2051 of file:///android_asset/ZSSRichTextEditor.js
10-06 13:48:49.496 7910-7910/org.wordpress.android D/WordPress-EDITOR: Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1 -- From line 2051 of file:///android_asset/ZSSRichTextEditor.js
10-06 13:48:49.652 7910-7910/org.wordpress.android D/WordPress-EDITOR: Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1 -- From line 2051 of file:///android_asset/ZSSRichTextEditor.js
10-06 13:48:49.808 7910-7910/org.wordpress.android D/WordPress-EDITOR: Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1 -- From line 2051 of file:///android_asset/ZSSRichTextEditor.js
10-06 13:48:50.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:48:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=INDEX_SIZE_ERR: DOM Exception 1 -- From line 2051 of file:///android_asset/ZSSRichTextEditor.js
10-06 13:48:50.244 7910-7914/org.wordpress.android D/dalvikvm: GC_CONCURRENT freed 1510K, 17% free 20703K/24711K, paused 12ms+2ms, total 35ms
10-06 13:48:50.908 7910-7976/org.wordpress.android W/DebugConnManager: getNetworkInfo() on networkType 1
10-06 13:49:00.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:49:10.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:49:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:49:30.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:49:40.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:49:50.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:49:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:49:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:00.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:10.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:30.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:40.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:50:50.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:50:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:50:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:00.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:00.208 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:00.208 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:10.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:10.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:20.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:20.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:30.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:40.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:51:50.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:51:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:51:50.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
10-06 13:52:00.200 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
10-06 13:52:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=arst
10-06 13:52:00.204 7910-8370/org.wordpress.android D/WordPress-EDITOR: &amp;#x200b;
```

Caught it in a video: https://cloudup.com/ckE6TfHZmz3

Ignore me if that only happens on an emulator. (Would be great to test that on a device with a bluetooth keyboard connected).

**Comment by aforcier** [comment]
> New post, add a picture, tap the back button before it's uploaded, now edit that post, picture is still greyed and won't upload

Related to this bug, publishing a post while an image is uploading is also problematic: the image doesn't upload, and when opening the uploaded post the image is grayed and won't upload.

**Comment by aforcier** [comment]
Change checklist:

- [ ] Fix progress bar string localization issue
- [ ] Fix closing/uploading a post while an image is in the middle of uploading
- [ ] Clean up `WordPressDB.updateMediaUploadState` method
- [ ] Split up `addMedia` method
- [ ] Open new issue for 'Post Uploaded' notification
- [ ] Open new issue for 4.1.1 HW keyboard paste issue

**Comment by aforcier** [comment]
Ready for another pass @maxme, @bummytime! Here are the changes:

* Fixed the string localization issue that affected the progress bar
* Some code cleanup (`WordPressDB.updateMediaUploadState` and `EditPostActivity.addMedia`)
* While images are uploading:
  * Closing the editor and re-opening a post that had in-progress image uploads now marks the images as failed so they can be retried. The upload tasks are also cancelled when the editor is closed
  * Attempting to publish/update or edit the settings of a post fails, showing a toast, and the action doesn't complete:

editor-media-uploading-toast

* While there are failed images in the post:
  * Attempting to publish/update or edit the settings of a post fails, showing a toast, and the action doesn't complete. In this case I think it would be better to instead show a dialog, which would let the user clear all failed media uploads and proceed with the upload, as iOS does it:

ios-editor-html-mode-failed-media

Implementing that will require a lot of changes to the native and JS parts of the editor, so since it's not a blocking issue I think it's best to handle it separately. I'll be opening an issue for this.

**Comment by aforcier** [comment]
Also I added a note to the original post that sharing media from another app to the editor isn't supported yet, with a link to the issue tracking that.

**Comment by maxme** [comment]
Building the tests fails: 

```
$ ./gradlew :libs:editor:WordPressEditor:cAT --offline
/Users/max/work/automattic/WordPress-Android/libs/editor/WordPressEditor/src/androidTest/java/org.wordpress.android.editor/MockEditorActivity.java:11: error: MockEditorActivity is not abstract and does not override abstract method onMediaUploadCancelClicked(String,boolean) in EditorFragmentListener
public class MockEditorActivity extends AppCompatActivity implements EditorFragmentAbstract.EditorFragmentListener {
       ^
/Users/max/work/automattic/WordPress-Android/libs/editor/WordPressEditor/src/androidTest/java/org.wordpress.android.editor/MockEditorActivity.java:54: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
```

**Comment by aforcier** [comment]
@maxme should be working now

**Comment by maxme** [comment]
:shipit: - looks good for v0.4 - if @bummytime is OK, I will merge it.

**Comment by bummytime** [comment]
@maxme I checked it out...it looks good to me as well :shipit: !

**Pull request merged**
