### PR TITLE
Add background for screens while paging through notifs in the Notifications tab

### LINKED ISSUE #12040: No Background When Paging Between Notifications
### Expected
The background is opaque when paging through notifications in ***Notifications*** like paging through revisions in ***History***.

### Observed
The background is transparent when paging through notifications in ***Notifications*** unlike paging through revisions in ***History***.  See the screenshots below for illustration.

paging_background

### Reproduced
1. Go to ***Notifications***
2. Tap any notification in list.
3. Swipe left/right to page through notifications.
4. Notice entering notification has no background.

##### Tested
Google Pixel 2 on Android 10.0 with WordPress Android 14.9-rc-2

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #12040

This PR adds background to the screens shown during paging through notifs in the Notifications tab.

To test:

1. Go to Notifications.
2. Tap any notification in list.
3. Swipe left/right to page through notifications.
4. Notice entering notification has background.

Review Instructions:
Only 1 reviewer is required. Anyone can review.

## Regression Notes
1. Potential unintended areas of impact  🟢

2. What I did to test those areas of impact (or what existing automated tests I relied on)  🟢

3. What automated tests I added (or what prevented me from doing so)  🟢

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @ashiagr 👍 
I tested this on a Pixel 2 XL with Android 11 and the app works as expected and solves the reported problem. The code changes also LGTM 🎉 

ps. I wonder if we can further improve this (in a different PR) with designer feedback. It looks a bit weird to me that the limit between the foreground and the background screens are not distinguishable. I would expect a slightly different background color or a light shadow between the screens. Tbh I've noticed this in the reader some time ago (and this screen is aligned with the reader behavior). Probably it's just me :P Wdyt?

<details>
 <summary>Screenshots</summary>

|Dark theme|Normal|Reader
|---|---|---|
|device-2021-06-23-170307|device-2021-06-23-170222|device-2021-06-23-171246|

</details>

**Comment by ashiagr** [comment]
Thanks for the feedback @antonis! 🙏
I thought about adding an elevation to the screens involved and tried it as well, this is how it looked:

device-2021-06-24-102355

Notice there's a common app bar at the top, and didn't look great. I can create a new task to further explore our options.

**Comment by antonis** [comment]
Hey @ashiagr 👋 

> Notice there's a common app bar at the top, and didn't look great.

Thank you for exploring this option. I agree that it looks better as is and aligned with the reader implementation.

> I can create a new task to further explore our options.

That would be great.

**Comment by ashiagr** [comment]
New Task: #14919
Cc @antonis

**Pull request merged**
