### PR TITLE
 Reader Detail Updates (App bar & Featured Image)

### PR DESCRIPTION
**Pull request by ashiagr**
Task: #12900

This PR includes below changes on the Reader Details screen:
   - App bar
      - Show white icons (until scroll) 01c43fc
      - On scroll: white background with black icons 01c43fc
      - Remove top app bar from the activity and define it in the details fragment - 141f15a
(Top app bar now includes collapsing toolbar that wraps a featured image wherever available. Since it changes across fragments based on featured image availability, it is moved from the activity to the individual ViewPager fragments.)
   - Featured Image
      - Show featured image edge-edge, parallax effect on scroll 0447ecf, 7de3f6c, da7a34d
      - Add black to transparent linear gradient at the top of the image d4f677d

[The PR is still in draft because of the known issues listed at the bottom. Looking for feedback for the rest of changes.]

featured_image_in_app_bar

Screenshots

Light Mode

Portrait | Landscape
--------|-----------
device-2020-09-15-105327|device-2020-09-15-105300

Dark Mode

Portrait | Landscape
--------|-----------
device-2020-09-15-105703|device-2020-09-15-105715

Known Issues

1. ~Status bar color - status bar is not reverted to original state (clicking search after returning from details screen shows status bar in white background instead of blue in light mode)~ - Fixed in 863d143

2. ~Featured image [height](https://github.com/wordpress-mobile/WordPress-Android/blob/863d14308cc5ec397526caeaaa9f43c5ab8dca1d/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt#L1439) - should we change it to 16:9 aspect ratio? Since details screen is shown in full width in the landscape mode, we might want to retain fixed height so that it doesn't cover entire screen. Tentatively kept it equal to 40% of screen height similar to media settings screen.~ - retaining fixed height as per comment https://github.com/wordpress-mobile/WordPress-Android/pull/12931#issuecomment-703475513

3. Try to remove [isToolbarShowing](https://github.com/wordpress-mobile/WordPress-Android/blob/043bff53202eacd66a5d9c2fee33b20f853e6ae2/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt#L176) - it is not dependent on the new toolbar but is still used to show/hide footer - will handle with new comments entry point changes

4. ~Yet to remove toolbar title~ - Fixed in 9d00059

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — COMMENTED** [review]
@ashiagr - I really love the way this came together. Moving to toolbar to the fragment was key - the smooth transition feels like a unit. Nice work!

Only a couple of things to report
1. If I create a post with a featured image AND include a media text or image block, the featured image does not show. See `FeaturedImageUtils.showFeaturedImage` [line 31].
`postText.contains(featuredImagePath) && featuredImagePath != featuredImageFile -> false` 
I know you didn't add this check, but wanted to call it out because I'm not 100% sure what it needs to be checking for and this one probably needs to be addressed.

2. There is a brief moment when the toolbar title says "Wordpress reader". This is when you are swiping from right to left. It only happens the first time you swipe back to the post. Not sure you need to do anything here, but wanted to bring it up. See the attached gif.


Light

Other than that all is working as expected. Looks good on light/dark backgrounds. 

As for
> Since details screen is shown in full width in the landscape mode, we might want to retain fixed height so that it doesn't cover entire screen.

I am a +1 on retaining a fixed height, so that we don't disrupt the experience. I would double check on this one with Jirka.

**Comment by malinajirka** [comment]
> Since details screen is shown in full width in the landscape mode, we might want to retain fixed height so that it doesn't cover entire screen.

> > I am a +1 on retaining a fixed height, so that we don't disrupt the experience. I would double check on this one with Jirka.

Sounds good to me ;). 

Great job!!!

**Comment by ashiagr** [comment]
Thank you  for the review! Ready for another look @zwarm , @malinajirka 

> 1. If I create a post with a featured image AND include a media text or image block, the featured image does not show. See FeaturedImageUtils.showFeaturedImage [line 31].
postText.contains(featuredImagePath) && featuredImagePath != featuredImageFile -> false
I know you didn't add this check, but wanted to call it out because I'm not 100% sure what it needs to be checking for and this one probably needs to be addressed.

I'll check with Shakti on this, AFAIU we just need to move the existing featured image (with existing conditions) from the content section to the app bar. 

> 2. There is a brief moment when the toolbar title says "Wordpress reader". This is when you are swiping from right to left. It only happens the first time you swipe back to the post. Not sure you need to do anything here, but wanted to bring it up.

I've removed toolbar title as per design in 9d00059 which fixes this issue:

no-toolbar-title

Additionally, fixed another issue when toolbars were messed up on fragments accessed from notifications and comments activity in c4541a2.

**Review by zwarm — COMMENTED** [review]
@ashiagr 
> I've removed toolbar title as per design 

Looks good and works as expected. When there is no featured image the missing title looks sparse, but that's just me experiencing the change. 

> I'll check with Shakti on this, AFAIU we just need to move the existing featured image (with existing conditions) from the content section to the app bar.

Just a bit more information on this one ... it has something to do with the path having `/wp` - if the path for the featured image includes `/wp`, and you add an image/media block and that image file has `/wp` in it's path, then it assumes it's the same file and `FeaturedImageUtils.showFeaturedImage` returns false. I don't know why it works off that. I don't even see the featured image in the content. Again, not something you did in this PR.

Everything else is looking good. 👍

**Comment by ashiagr** [comment]
Thanks @zwarm !

> When there is no featured image the missing title looks sparse, but that's just me experiencing the change.

Hmm, Shakti is reviewing it in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13058). I'll check with her.

> Just a bit more information on this one ... it has something to do with the path having `/wp` - if the path for the featured image includes `/wp`, and you add an image/media block and that image file has `/wp` in it's path, then it assumes it's the same file and `FeaturedImageUtils.showFeaturedImage` returns false. I don't know why it works off that. I don't even see the featured image in the content. Again, not something you did in this PR.

I've added it to backlog [here](https://github.com/wordpress-mobile/WordPress-Android/issues/12900). I'll verify it later.

I think we can merge this PR to target branch as this condition wasn't updated in this PR. Lmkwyt.

**Review by zwarm — APPROVED** [review]
All good to merge. 👍  Again, nice work.

**Pull request merged**
