### PR TITLE
Onboarding Improvements: Update quick start prompt (part 2)

### PR DESCRIPTION
**Pull request by ashiagr**
Parent Issue #14991

This PR styles the new quick start prompt dialog for both portrait and landscape mode. 

Portrait 
Light Mode | Dark Mode | Layout Bounds
------------|------------|---------
lt_port| dk_port | lt_port_boundary

Landscape 

lt_land
dk_land 
lt_land_boundary

To Test:

**Original Dialog**

1. Launch the app with `OnboardingImprovementsFeatureConfig` unset.
2. Create a new site using the menu option in the "My Site" tab -> Site Picker. 
3. Notice that the quick start prompt is shown in the original design.
4. Rotate the device and see the dialog is still visible.
5. Dismiss the dialog.

**Updated Dialog**

1. Go to My Site -> Me profile -> App Settings -> Test feature configuration.
2. Enable `OnboardingImprovementsFeatureConfig`. 
3. Create a new site using the menu option in the "My Site" -> Site Picker. 
4. Notice that the quick start prompt is shown using the new design.
5. Rotate the device and see that the landscape layout is shown using the new design.
6. Dismiss the dialog.

Design Notes (cc @osullivanchris):
1. In Zeplin secondary button has a regular font, however, I haven't applied the change yet to keep it consistent with the buttons arranged similarly on the login prologue screen. Let's discuss if we should change it.
2. I've added a `24dp` margin below the description and above the buttons. The buttons have a `4dp` padding on top and bottom, so ideally this margin should be `20dp`. There's no existing `20dp` standard margin available [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/dimens.xml#L116-L117). Unless you think it is a negligible difference, I can add a custom margin. I'll wait for a confirmation before I make this change.

**Merge Instructions**

1. Wait for design review from @osullivanchris.
2. Remove the [Status] Needs Design Review.
3. Merge this PR.

## Regression Notes
1. Potential unintended areas of impact
Existing quick start prompt (shown without feature flag enabled)

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See "To test" above

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@ashiagr - What is expected behavior for dismissing the quick start prompt using the back button? Obviously the dialog dismisses :) The behavior is the same as if I clicked the"No thanks" button . Is this what is expected? Thanks.

**Review by zwarm — APPROVED** [review]
All tests ran as expected - landscape and portrait 👍  . Just waiting on design approval before merging.

**Comment by ashiagr** [comment]
👋 @zwarm, thanks for reviewing it! 

Regarding

> What is expected behavior for dismissing the quick start prompt using the back button? Obviously the dialog dismisses :) The behavior is the same as if I clicked the"No thanks" button . Is this what is expected? Thanks.

I still need to look into the button actions as per the parent task. I guess the back button should dismiss the dialog but I'll revisit the logic when I update the actions. 

> Just waiting on design approval before merging.

Sounds good 🙌

**Review by osullivanchris — APPROVED** [review]
👋  Hey @ashiagr this looks great! I only have one tiny thing. The line-height in the heading "Want a little help..." is a bit tight. In the design I had it at 24dp, or 1.33, depending how you define it.

> In Zeplin secondary button has a regular font, however, I haven't applied the change yet to keep it consistent with the buttons arranged similarly on the login prologue screen. Let's discuss if we should change it.

I just intended to use our standard button style so any difference in my mocks was unintentional. Re-using is exactly as desired.

> I've added a 24dp margin below the description and above the buttons. The buttons have a 4dp padding on top and bottom, so ideally this margin should be 20dp. There's no existing 20dp standard margin available here. Unless you think it is a negligible difference, I can add a custom margin. I'll wait for a confirmation before I make this change.

Yeah that's fine. It looks good to me.

**Comment by ashiagr** [comment]
Thanks for the review @osullivanchris 🙏

> I only have one tiny thing. The line-height in the heading "Want a little help..." is a bit tight. In the design I had it at 24dp, or 1.33, depending how you define it.

Curently [lineSpacingMultiplier](https://stackoverflow.com/a/19255737/193545) for this heading is set to `1.3` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/da17f85ab0968645b8a30bf5994dd18958c02ace/WordPress/src/main/res/values/styles.xml#L862). 

I tried changing it to `1.33` and `1.4`, this is how it looks: 

line_height

I can increase it to `1.33` but I see this attribute set to only upto 1 decimal space in the app e.g. [here](https://github.com/wordpress-mobile/WordPress-Android/blob/da17f85ab0968645b8a30bf5994dd18958c02ace/WordPress/src/main/res/values/styles.xml#L1533) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/da17f85ab0968645b8a30bf5994dd18958c02ace/WordPress/src/main/res/values/reader_styles.xml#L83).

Should I maybe increase it to `1.4` or more? 


EDIT: I just noticed, the value [does not apply to the last line of the text](https://developer.android.com/reference/android/widget/TextView#attr_android:lineSpacingMultiplier). How about we increase the margin between the heading and the description then?

**Comment by osullivanchris** [comment]
@ashiagr thanks for the investigation and the details. I actually wrote one thing wrong. I should have said I wanted to make it tighter 🤦  

In the original screenshot, the space between the two lines looked a little large to me. 

However, if we only use 1 decimal space, lets just leave it. 1.2 will be too small. 1.4 will be crazy big.

> How about we increase the margin between the heading and the description then?

I think this is a good idea. If the space between the heading and description increases, it will resolve this a bit as currently the line space is almost as large as the space before the description. Could you just add an extra 4dp there? Small difference but I think it looks more balanced.

Before (left) and after (right)

Screenshot 2021-07-20 at 13 57 34

**Comment by ashiagr** [comment]
> Could you just add an extra 4dp there? Small difference but I think it looks more balanced.

Yep, it definitely looks more balanced 👍. Spacing increased by 4dp in 705ff91

new_screenshot

**Comment by osullivanchris** [comment]
Thanks @ashiagr looks good now! 👍 🙏

**Pull request merged**
