### PR TITLE
Remove unnecessary pageActionsEnabled for upload as we use an overlay

### LINKED ISSUE #11620: IllegalStateException: Already resumed, but proposed with update kotlin.Unit
**Sentry Url**: https://sentry.io/share/issue/a1811baed63f46bc80b27ec6e7760fca/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android-14.6-rc-1
**First Seen**: 2020-04-08T11:16:30Z
**Last Release**: org.wordpress.android-14.6-rc-1
**Last Seen**: 2020-04-08T11:16:30Z
**24 Hours**: 1
**30 Days**: 1

**Stacktrace**:
```
IllegalStateException: Already resumed, but proposed with update kotlin.Unit
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:332)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:327)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:247)
    at org.wordpress.android.viewmodel.pages.PagesViewModel.handlePageUpdated(PagesViewModel.kt:774)
    at org.wordpress.android.viewmodel.pages.PagesViewModel$start$1.invoke(PagesViewModel.kt:212)
    at org.wordpress.android.viewmodel.pages.PagesViewModel$start$1.invoke(PagesViewModel.kt:84)
    at org.wordpress.android.viewmodel.pages.PageListEventListener$onPostChanged$1.invokeSuspend(PageListEventListener.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #11620 

Info [here](https://github.com/wordpress-mobile/WordPress-Android/issues/11620#issuecomment-611432757)

To test:
- Publish a post from the page list
- Publish a post from the editor
- Publish multiple posts from the page list (might be worth limiting the bandwidth on the emulator)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Do you think we should merge this PR into the RC? The number of changes is quite high for a "hot-fix". On the other hand, we are just removing code. (cc @jd-alexander @oguzkocer )

### CODE REVIEW

**Comment by oguzkocer** [comment]
Let's keep this against `develop`. We have a single instance of the crash, that's why I assigned `14.7` as the milestone for the issue :)

**Comment by malinajirka** [comment]
>We have a single instance of the crash, that's why I assigned 14.7 as the milestone for the issue :)

Ohh, I missed that. I felt like a single instance in the beta might be hundreds of instances in the production. But looking at the changes, I think it's safer to wait for 14.7. 👍

**Comment by malinajirka** [comment]
Thanks for the review @jd-alexander ! ;)

>I tested this solution and it works as expected 😄 What I noticed is that we still have actionsEnabled in the PageItem. We also have _arePageActionsEnabled and the references to still exists in the models, adapters etc. Should we be removing these?

I think it's still being used for some of the other actions. For example "Move to draft" doesn't support multiple concurrent actions. So I'm a bit worried we can't remove it yet. :(

**Comment by jd-alexander** [comment]
Okay thanks 🙏🏾 Otherwise this is good to go. Thanks Jirka 🚀🚀🚀 LGTM!

**Pull request merged**
