### PR TITLE
Do not mark post as changed when loading revision without changes

### LINKED ISSUE #8773: Editor revisions: loading latest revision makes post get uploaded even if no changes
### Expected behavior
When loading the same history revision as the current one, the Post should not get updated.

### Actual behavior
The post gets updated when the last history revision version gets loaded on the Editor.

### Steps to reproduce the behavior
1. start a new Post (Aztec)
2. type a title
3. start a paragraph, enter "first version" as text.
4. tap back
5. observe the post gets uploaded as a draft
6. open it again and edit  paragraph "first version" enter something else, for example I entered "second version"
7. tap back to make the first entry in history
8. open it again
9. now add a new paragraph with text "hello"
10. tap back, open it again and tap on History to see you have 2 entries there.
11. load one of the older entries
12. wait for the snackbar to hide
13. tap on undo
14. tap back - the post is uploaded (IIUC, it shouldn't).

NOTE: If you set airplane mode ON before step 14, the post is then marked with `Local changes` as described in the [original report](https://github.com/wordpress-mobile/WordPress-Android/pull/8768#issuecomment-446239923).

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #8773 

This PR adds a check when loading a revision that prevents post from being marked as "changed" if the content of post and its title are identical to revision.

I decided to still leave a "Revision loaded" toast and undo button that does nothing (otherwise it might be confusing, and give an impression that something is not working).

To test (from original issue):
* start a new Post in Aztec
* type a title
* start a paragraph, enter "first version" as text.
* tap back
* observe the post gets uploaded as a draft
* open it again and edit paragraph "first version" enter something else, for example "second version"
* tap back to make the first entry in history
* open it again
* now change the content to "third version"
* tap back to make the second entry in history
* navigate back to post and load the revision with "third version" (same as the content of editor)
* naviagate back and notice that post was not uploaded

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by khaykov** [comment]
Good catch, @theck13 ! This happens because we call `setIsLocallyChanged(true)` when revision had changes, but ignored this method when there was no changes, so the `true` flag from previous call was still in the post object. I update the code to set it every time revision is loaded.

I also looked for the usage of  'setDateLocallyChanged' and it looks like we don't need to update it when post was not actually changed.

**Comment by khaykov** [comment]
You are right, I missed that part 🤦‍♂️ Having an original post content to compare against sounds like a good approach - I'll give it a try.

**Comment by khaykov** [comment]
So turns out this is a bit trickier than expected. We already have `mOriginalPost` variable but it's not exactly original - we don't retain post during any configuration change events because, if I remember correctly, they are too big to be safely passed around (we had to deal with `TransactionTooLargeException`). We save them to the DB and retrieve them later, which means our "original" post always have latest changes after a configuration change. At the same time, we retain the Revision object through configuration changes without much issues (maybe we should not do this and use revision id instead?). I do wonder how safe it would be to store initial post content and title and retain them through config changes.

**Comment by theck13** [comment]
What about storing the post when entering the editor in the database with a unique identification and not retaining an object in the class at all?  Then we could retrieve the post by that unique identification to compare it when exiting.

Also, it sounds like we should rename the `mOriginalPost` variable if it's not actually the original post.

**Comment by khaykov** [comment]
@theck13 That's a great idea. Ideally, we would have a dedicated functionality for this, maybe a simple table, that will only be permitted to have one entry at a time (so we don't have to manage addition/removal) and some utility methods for comparison. 
I would consider this issue a low priority, and the amount of work involved makes this issue a good candidate for Hack Week project, so I'm going to close this PR for now.

**Pull request closed without merging**
