### PR TITLE
Dashboard Cards: Activity Card rearrange content in card 

### LINKED ISSUE #18210: Dashboard Cards: Add Activity Log card in the correct position
- [x] Create UI Skeleton/Boilerplate #18270 
- [x] Show card in the correct position within the feed #18285 
- [x] Create params builder for ActivityCard or update the cards builder params #18285 
- [x] Build out the view holder logic #18285 
- [x] Build out MySiteCardAndItem.ActivityCard #18285 
- [x] Update Unit Tests (MySiteViewModel, MySiteCardAndItem, etc.) #18285 
- [ ] Refactor UI: Swap title and content, remove constraint layout, adjust margins/padding #18292

### PR DESCRIPTION
**Pull request by zwarm**
Closes #18210 

This PR focuses on:
(1) Swapping the label/sub-label of activity items within the card
(2) Renaming the label fields in the layout and associated files
(2) Minor refactoring of the XML layout file - removing inner constraint layout and deprecated attributes, consolidating padding/margin settings

Light | Dark
-- | --
Alt desc | Alt desc

**NOTE: The navigation clicks are not enabled in this build.** 

**To test:**
Make sure the activity card item list shows the "content" as the label and "summary" as sublabel
1. Install the Jetpack app
2. Login with a wp account
3. Select a site in which you can access the activity log (manage content/admin)
4. Navigate to App Setting > Debug Settings 
5. Enable `dashboard_card_activity_log` and restart the app
6. Navigate to Home
7. ✅ Verify that the activity card is shown
9. ✅ Verify the card matches the design in this PR and figma design docs

See UI Changes testing checklist below. Note: I have already been through the list before submitting this PR

cc: @startuptester 

cc: @osullivanchris - Can you take a look and see if I have missed anything with regards to design/layout, etc?. Thanks.

## Regression Notes
1. Potential unintended areas of impact
The items in the activity card are not displayed properly

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [X] Portrait and landscape orientations.
- [X] Light and dark modes.
- [X] Fonts: Larger, smaller and bold text.
- [X] High contrast.
- [X] Talkback.
- [X] Languages with large words or with letters/accents not frequently used in English.
- [X] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [X] Large and small screen sizes. (Tablet and smaller phones)
- [X] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by enejb — APPROVED** [review]
I am approving this PR since the change only update some sementic code.

**Comment by enejb** [comment]
Over all this worked really well. 
I was able to see the activities. 

Some things that I noticed that are a bit strange to me. 
1. In RTL mode, I would expect the icon (circle) to be on the right side of the app. 
2. When I visit the activity log. it shows me 1 less activity. I am not sure why that is. For sites that have 2 activities. I see 2 in the dashboard but only one in the activity log. 
3. I am not able to navigate to the activity. I am also not able to navigate to all activities from the dashboard.

**Comment by zwarm** [comment]
Thanks @enej for testing!!!

> Some things that I noticed that are a bit strange to me.

> 1. In RTL mode, I would expect the icon (circle) to be on the right side of the app.

They are, it just takes a little time for the app to catch up when the language is changed on the fly. Close the app and relaunch it, you should see the icons on the right. Like this:

Alt desc

> 2. When I visit the activity log. it shows me 1 less activity. I am not sure why that is. For sites that have 2 activities. I see 2 in the dashboard but only one in the activity log.

That is odd and something I haven't been experiencing in my testing. Both views are endpoint driven, but from different endpoints. I wonder if there is a difference in what type of site you are using. I've used AT, free, and business so far.

> 3. I am not able to navigate to the activity. I am also not able to navigate to all activities from the dashboard.

The navigation actions are not hooked up in this PR. I'll add a note in the description above. :)

**Comment by osullivanchris** [comment]
👋  Hey @zwarm mostly looking as expected, nice stuff. Two small details:

- could we reduce the size of the icons to the same size as the Activity Log view. I sometimes struggle to define the right size with different screen sizes and resolution, but if you could use the value on Activity Log that should be good.
- Could you reduce the space between items slightly. I think 4dp less would do the trick.

**Comment by zwarm** [comment]
> * could we reduce the size of the icons to the same size as the Activity Log view. I sometimes struggle to define the right size with different screen sizes and resolution, but if you could use the value on Activity Log that should be good.
> * Could you reduce the space between items slightly. I think 4dp less would do the trick.

Can do @osullivanchris . I created a new [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/18307) to track it. 🙇

**Pull request merged**
