### PR TITLE
Coil image loader singleton

### LINKED ISSUE #21285: Coil ImageLoader singleton
According to [Coil's documentation](https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection):

> Coil performs best when you have a single ImageLoader that's shared throughout your app. This is because each ImageLoader has its own set of resources.

We should update the app to follow that advice.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #21285 

This PR updates our use of the Coil `ImageLoader` to rely on a singleton, as recommended in the [docs](https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection). Currently we only use an `ImageLoader` in the `MediaUriPager`, which was added for the feedback form.

To test:

* Me > Send feedback
* Verify attaching an image works
* Verify attaching a video works

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jkmassel — APPROVED** [review]
Because we only use it here, this is probably fine, but I'd think we could use Hilt to inject it if it's ever needed elsewhere? WDYT?

**Comment by nbradbury** [comment]
> I'd think we could use Hilt to inject it if it's ever needed elsewhere? WDYT?

I'm curious why this would be an improvement, since if (and actually when) we need the `ImageLoader` elsewhere, as long as we use `context.imageLoader` my understanding is it will use the same instance as `newImageLoader` in the application class?

**Comment by jkmassel** [comment]
This is an area where I quickly get out of my depth on Android stuff 😅 

@oguzkocer or @wzieba could give a better answer (and set me straight, probably!)

**Review by oguzkocer — APPROVED** [review]
As far as I can tell, this implementation is correct and using our own dependency injection is not necessary.

The singleton logic is handled by `coil`'s `Context.imageLoader` extension [here](https://github.com/coil-kt/coil/blob/2.7.0/coil-singleton/src/main/java/coil/Extensions.kt#L23C12-L24) which [returns a singleton](https://github.com/coil-kt/coil/blob/2.7.0/coil-singleton/src/main/java/coil/Coil.kt#L26-L28):

```
/**
 * Get the singleton [ImageLoader].
 */
inline val Context.imageLoader: ImageLoader
    get() = Coil.imageLoader(this)
```

```
/**
 * Get the singleton [ImageLoader].
 */
@JvmStatic
fun imageLoader(context: Context): ImageLoader {
    return imageLoader ?: newImageLoader(context)
}
```

```
/** Create and set the new singleton [ImageLoader]. */
@Synchronized
private fun newImageLoader(context: Context): ImageLoader {
    // Check again in case imageLoader was just set.
    imageLoader?.let { return it }

    // Create a new ImageLoader.
    val newImageLoader = imageLoaderFactory?.newImageLoader()
        ?: (context.applicationContext as? ImageLoaderFactory)?.newImageLoader()
        ?: ImageLoader(context)
    imageLoaderFactory = null
    imageLoader = newImageLoader
    return newImageLoader
}
```

**Comment by nbradbury** [comment]
Thanks @oguzkocer !

**Pull request merged**
