### PR TITLE
Move fastlane env file

### PR DESCRIPTION
**Pull request by loremattei**
While working on another PR, I noticed that the Fastlane `env` file hasn't been moved to the new location yet on this project. 
This PR just fixes it. 

When this is merged, I'll update the internal docs to reflect the changes. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jkmassel — APPROVED** [review]

**Comment by jkmassel** [comment]
@loremattei – leaving it to you to merge this one to align with the docs change :)

**Comment by AliSoftware** [comment]
What do you think about taking the occasion to add the similar check than what is [in WPiOS here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/fastlane/Fastfile#L48-L54) so that users have a nice documenting message if the file is missing?

**Comment by loremattei** [comment]
Yes, that would be very nice! Do you want to take care of this @AliSoftware ?

**Comment by AliSoftware** [comment]
> Yes, that would be very nice! Do you want to take care of this @AliSoftware ?

https://github.com/wordpress-mobile/WordPress-Android/pull/14365

**Pull request merged**
