### PR TITLE
Issue/6720 media browser redesign

### LINKED ISSUE #6720: Media Browser redesign
In #6718 we changed the behavior of the media picker, we should likewise change the behavior of the media browser when used as a picker.

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #6720 - This PR makes updates the media browser to match #6720 when used as a picker to add an image to a post. It also makes the following changes when the media browser is used standalone:

* Does away with multi-select (and the ability to multi-delete)
* Failed items show two icons (Retry and Delete)

screenshot_1508011853

screenshot_1508010007

### CODE REVIEW

**Comment by daniloercoli** [comment]
> Failed items show two icons (Retry and Delete)

Not sure if it is related to this Pr, but I've felt in a state where I can't retry a media. `Delete` is the only option available on the item. Below are the steps to repro the issue:
- Turn Airplane mode ON
- Go to photos app and share to WP Media Library
- The item is added to the library, but has the `enqueued` state label over it, and the `delete` icon as well
- Turn Airplane mode OFF, and now the device is able to connect to the Internet
- Go back to WP Media Library, do a PTR just to check that everything is working OK
- You will notice the item still had the `enqueued` state label over it, and the `delete` icon. There is no way to re-try the upload.

The only way to get the "retry" icon on the item is to close the app for real, and restart it.

**Comment by daniloercoli** [comment]
I'm able to reproduce the following issue (as before I'm not sure it's related to this PR):
- Start uploading a video to the media library
- Start uploading a picture to the media library
- Tap on the picture and access the preview screen
- Stay on the preview screen till the video finishes the uploading
- Go back to media library
- The video item has the spinning indicator over it. Doesn't matter how long you wait, you have to go back to site menu and than again to media library to get the correct state/overlay over the video.

**Comment by nbradbury** [comment]
@daniloercoli I'm pretty sure neither of those are related to this PR - could you file separate issues for those? Thanks!

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
