### PR TITLE
Issue/5015 reader detail title

### LINKED ISSUE #5015: Change title of Reader Stream Detail from "Reader Blog" to the title of the site
Right now when clicking into a post, the Action Bar shows "Reader Blog" for every site. Change it to be the title of the site.

Same as https://github.com/wordpress-mobile/WordPress-iOS/issues/6333

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5015 - changes the reader detail screen so that it shows the site name as the title.

Related iOS issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/6333)

cc: @kwonye

### CODE REVIEW

**Comment by nbradbury** [comment]
Note: [This new routine](https://github.com/wordpress-mobile/WordPress-Android/pull/5021/files#diff-e46f5035ae37fb0d85f4f2729f5afe50R446) to delete a post is unused here, but it's something I needed while testing this feature and it will come in handy down the road.

**Comment by kwonye** [comment]
@nbradbury I'm sorry I wrote such a vague issue. We want to set the title when looking at a site overall like this (along with the title when looking at an individual post): 
simulator screen shot jan 12 2017 12 10 13 pm

simulator screen shot jan 12 2017 12 11 58 pm

Can you modify this to work in that manner please? Again, my fault, sorry.

**Comment by nbradbury** [comment]
@kwonye I updated this PR to set the title for blog & tag preview, so ready for another round.

**Comment by kwonye** [comment]
@nbradbury The actionbar title isn't set to the blog post title when clicking into an actual post as shown here:

simulator screen shot jan 12 2017 12 11 58 pm

**Comment by nbradbury** [comment]
> The actionbar title isn't set to the blog post title when clicking into an actual post as shown here:

Changed in c7e0681, so ready for another (final?) round.

**Comment by kwonye** [comment]
Works great! Thanks for picking this issue up. :shipit:

**Pull request merged**
