### PR TITLE
Remove maximum number of posts that can be loaded in ReaderPostAdapter

### LINKED ISSUE #19811: [Reader] Pagination for unfollowed tags doesn't work properly
### Expected behavior
When opening an unfollowed tag/topic feed (by tapping a tag in a post / discover suggested tags card) and reaching the end of the list, it should load the results from newer to older, fetching more posts and adding to the end of the list. It should also fetch all posts eventually if the user keeps scrolling.

### Actual behavior
When opening an unfollowed tag/topic feed (by tapping a tag in a post / discover suggested tags card)and reaching the end of the list, it fetches some posts and put them in the middle of list, sometimes also at the end, and it sometimes stops loading more posts entirely.

### Steps to reproduce the behavior
1. Open the Reader on Jetpack App
2. Open a tag you do not follow yet (from some post or the discover tag suggestions card) - prefer very generic and widely used tags like `love`, `science`, `education`.
3. Scroll to the end of the list so it loads more posts
4. Keep doing it for a while
5. Notice that sometimes posts are loaded above the last post (shifting content around) and eventually posts stop loading.

### Some initial investigation
It looks like the code that loads more posts from the endpoint uses different date/score fields for the `before` field. [This function](https://github.com/wordpress-mobile/WordPress-Android/blob/74c1591cb1ac97bb4f28dec5a9bdc91316ebcab0/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L774-L786) retrieves the local database field that will be used to set the before param in the read/tags endpoint.

For followed tags, since the `ReaderTag.mEndpoint` field is set, the code uses `date_tagged`, but if it’s not followed, it uses the `date_published` (because of the `tag.isTagTopic` [logic](https://github.com/wordpress-mobile/WordPress-Android/blob/28fe95a349766b818ac617a213eba21cca9f4435/WordPress/src/main/java/org/wordpress/android/models/ReaderTag.java#L191-L194)).

When posts are no longer loading it is likely because we used some reference date for `before` which is too recent and doesn't match the actual date (used by the endpoint) of the last item on the shown list, so we only receive items that are already in the list.

Ideally, we should take a look at the `/rest/v1.2/read/tags/<tag-slug>/posts` endpoint code as well because we are sending different reference dates in the before for different [cases](https://github.com/wordpress-mobile/WordPress-Android/blob/74c1591cb1ac97bb4f28dec5a9bdc91316ebcab0/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L774-L786) which will likely never work properly since `before` is probably always using a specific column, leading to the pagination issues we see.

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19811 

> sometimes posts are loaded above the last post (shifting content around) 

I wasn't able to reproduce this part. I suspect it was fixed by [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/19881).

> eventually posts stop loading.

By removing the `mCanRequestMorePostsTemp` logic (originally implemented in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/2159)) the unfollowed tag post list loaded a few more items, but eventually it stops. I thought it was something in the client, but this also happens in web which makes me think it's something in the back-end that eventually stops sending us more items.

-----

## To Test:

[See the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/19811)

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - UI changes only

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by thomashorta** [comment]
I believe most of the issues from the original GH issue were previously fixed thanks to your work on using dates instead of strings as well as some other minor changes we did throughout past Reader projects, so removing this limit should make sure we have an infinite list of posts as long as the user keeps scrolling and there are posts available in that feed. 🙇🏼 

That said, I still think there's some issue going on on mobile, check the rest of this comment below:

> I thought it was something in the client, but this also happens in web which makes me think it's something in the back-end that eventually stops sending us more items.

Not sure which tag you used, but could you have reached the last post from the tag you were testing?

I tested with a `calm` tag and on Mobile (with your changes) and I can't get past the post in the screenshot below. I opened the App Inspector and noticed in the DB that the `date_published` field looks pretty weird (`2024-05-12T11:00:07-125:56`). Look at the timezone segment. App inspector screenshot also below.

As mentioned in the original issue (#19811) for tag/topic feed, the field used for the `before` query parameter is `date_published` because of the [logic here](https://github.com/wordpress-mobile/WordPress-Android/blob/74c1591cb1ac97bb4f28dec5a9bdc91316ebcab0/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L774-L786). **So this could be causing the issue, though I'm not sure what the proper fix is.**

App Last Post for `calm` tag/topic feed:


App Inspector (last post highlighted):
Screenshot 2024-06-10 at 14 16 17

On the Web I was able to get past it. Note that it looked stuck for a bit when I reached that same post, but after I scrolled up and down again, the posts loaded below it as expected. Also notice that the web says "Invalid Date" for the post date.
Screenshot 2024-06-10 at 14 20 00

**Review by thomashorta — COMMENTED** [review]
Look at my previous comment, I ended up sending it without the Code Review, but it has all the information about what I investigated with your changes.

I think the changes as-is have value, removing this unnecessary soft-limit that exists on the Android Client, but there is still some issue going on related to fetching by `date`, though it does look like an issue in the data retrieved by the backend, so I'm not sure what we can do from a client-side. Maybe we can try to figure out what the web does, since in the web they seem to have some workaround that "invalid date" issue (see https://github.com/wordpress-mobile/WordPress-Android/pull/20958#issuecomment-2158927310).

**Comment by RenanLukas** [comment]
Thanks for the review and investigation, @thomashorta !

I agree this PR provides some value by removing the maximum number of posts to be loaded but it doesn't fully address the problem. Since it seems like the web is doing a workaround for invalid data returned by the back-end and we'll need to understand what they're doing, I propose we merge this PR and create a new issue/update the existing issue including your investigation. WDYT?

**Review by thomashorta — APPROVED** [review]

**Review by nbradbury — APPROVED** [review]
This was previously approved and tested fine after updating with `trunk` :shipit:

**Pull request merged**
