### PR TITLE
Issue/9666 post list show real progress

### LINKED ISSUE #9666: Post List: Replace indeterminate progress with real progress
The progress bar on post list items which is shown when the post or media are being uploaded doesn't show any progress. I "accidentally" replaced it with an indeterminate progress bar in [this](https://github.com/wordpress-mobile/WordPress-Android/pull/9431) PR.

Goal of this task is to use a progress bar which shows an actual progress of the upload.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9666 

This PR is follow up for draft PR https://github.com/wordpress-mobile/WordPress-Android/pull/9708 which I've closed to make things clearer.

**Note: This PR is based on https://github.com/wordpress-mobile/WordPress-Android/pull/9770.**
Merge instructions

0. Review this PR
1. Wait until https://github.com/wordpress-mobile/WordPress-Android/pull/9770 is merged
2. Update target branch to `feature/post-filters-compat-view-toggle`
3. (Review) and Merge this PR

Adds a determinate progress bar indicator to post list items when media files are being uploaded.

To test:

1. Open Post List
2. Create a post
3. Add title and add some images from the local storage
4. Publish the post before the images are uploaded (you might want to modify network settings on your emulator to make the internet connection slower)
5. Notice the progress bar on the item in the list is updated as the upload progresses

Update release notes:

- I haven't updated the release notes as this issue will be released along with the Post Filters project
real-progress

### CODE REVIEW

**Comment by mzorz** [comment]
hi @malinajirka ! Been testing this, it seems to be functional however I noticed some clunkiness when trying to scroll the list up and down while a card for Post with in-progress uploads is visible or near-visible as can be seen in this video here https://cloudup.com/cRztdQEqBpW
Do you know why is that, and how can that be improved?
Code looks good to me 👍

**Comment by mzorz** [comment]
>  I noticed some clunkiness when trying to scroll the list up and down while a card for Post with in-progress uploads is visible or near-visible as can be seen in this video here https://cloudup.com/cRztdQEqBpW

I correct myself: just noticed the video doesn't really reflect my description, but the actual feel of the responsiveness to scrolling is that it is not as smooth - if you place your finger and try to scroll up and down, also fling (quick movement up or down), you'll see the movement is not continuous. I hope that makes sense! Also let me know if I can provide some other feedback on this regard?

**Comment by malinajirka** [comment]
As @mzorz mentioned, the issue is not a blocker for this PR. I'm merging it, so we can merge the whole feature into `develop` and I'll fix the issue as part of another PR.

**Comment by malinajirka** [comment]
@mzorz I haven't submitted a new issue as it's related to this https://github.com/wordpress-mobile/WordPress-Android/issues/9528. I've tried to comment out the bitmap loading and it seemed smooth.

**Pull request merged**
