### PR TITLE
Adding dual pane layout functionality to MySite tab.

### LINKED ISSUE #3662: "Blog Posts" row in MySite fragment is not blinking when post is saved as draft
According to code, when post, created through MySite fragment's FAB, is saved as draft, the "Blog Posts" row should blink twice.
selectors

Looks like it's not working because of the bug in RelativeLayout.
From [official documentation](http://developer.android.com/reference/android/widget/RelativeLayout.html):

*Note: In platform version 17 and lower, RelativeLayout was affected by a measurement bug that could cause child views to be measured with incorrect MeasureSpec values. (See MeasureSpec.makeMeasureSpec for more details.) This was triggered when a RelativeLayout container was placed in a scrolling container, such as a ScrollView or HorizontalScrollView. If a custom view not equipped to properly measure with the MeasureSpec mode UNSPECIFIED was placed in a RelativeLayout, this would silently work anyway as RelativeLayout would pass a very large AT_MOST MeasureSpec instead.*

### PR DESCRIPTION
**Pull request by khaykov**
Current dual-pane beta (framework+individual screens with improvised design) is located [here](https://github.com/khaykov/WordPress-Android/tree/feature/tablet-ui-beta). 

## Preface.

This PR provides a core dual pane functionality.

When it comes to dual pane, the most interesting part of it is to how to make it work on devices that use both single and dual pane layout, like most of the 7 inch tablets.

When coming up with specs, the interaction design part (aka. "When you rotate device this should happen!") was defined only superficially, so I filled the gaps based on my own idea of how everything should work, so feel free to comment if you think something could be done differently or should behave in different way.

Minimum screen width for dual pane layout is ~~720dp~~ 960dp (layout-w960dp) with sidebar width set at 300dp.

## About the code.

_This PR is quite big - unfortunately, there is no good way to split it, because in case of this feature, all the parts only make sense when they are together._

The main idea behind dual pane functionality is simple - show content fragment alongside the sidebar in dual pane mode, and same fragment inside activity in single pane mode.

Implementation was a little bit more complicated, so I'll try to provide as much info as possible. I left plenty of comments, and there is a Log output so you could check main lifecycle events. 

Some notable classes:

**DualPaneHostFragment** - abstract fragment that provides basic dual pane functionality and exposes it with **DualPaneHost** interface.

**DualPaneContentActivity** - abstract activity that allows us to switch between single/double panes.

**MySiteDualPaneFragment** - is our concrete implementation of dual pane layout. Provides a little bit of custom logic by overriding some of DualPaneHostFragment methods.

*Footnote: at my first try with this problem, I made a version that does not relies on Activity to show fragment in single pane mode. Instead it used the container view of main activity to show fragment's and made it look like they are activities. It used the child fragment manager in dual pane, main activity fragment manager in single pane, and juggled fragment between them on configuration change.Pretty neat! For curious - you can check the code [here] (https://git.io/vz1fi)
Unfortunately, I had to abandon this idea on early stage, as @maxme pointed some potential overdraw problems in previous PR, and on further inspection I discovered even more performance issues (mostly with animation). That's also the reason I have reverted some changes from previous PR.*

## About content fragments.

For now you can only display Blog Posts and Pages (they are same fragment) in dual pane mode. More will come later.

## About default content.

Default content is a fragment visible in dual pane mode when nothing is selected (app just started, or you just changed blog). Like with website, we should probably use Stats as a default fragment, but making it work in dual pane layout will take some time (see #3643), so to prove the concept, I'm using a PostsListFragment for now. Unless you explicitly select it, the default content will not be displayed in single pane activity on orientation change.

## About Selectors.
MySite fragment now features selectors. When we select "Pages" or "Blog Posts", or any other fragment with dual pane support, the matching row will be selected. Selectors will only be visible in dual pane mode. If the default fragment has selector - it will be used.

## What's next.
Make most of the MySite content work in dual pane mode. Almost all of that content heavily tied to activity and activity lifecycles, so we will have to decouple it, and move to fragments.
Apart from technical side, there's also a design problem. Like how to show errors and action prompts to users in dual pane mode (stuff that works nicely in activity will not work in fragment). Or what to do with giant orange FAB that visible in both sidebar and content pane. (Update: based on feedback, I removed MySite FAB from dual pane mode)

This PR is part of the #3551
Also fixes #3662

### CODE REVIEW

**Comment by khaykov** [comment]
I totally missed the fact that ViewPager fragments implement `OnScrollToTopListener` and should scroll to top when you reselect a tab. So, I added `OnScrollToTopListener` to `MySiteDualPaneFragment` and made it pass `onScrollToTop` events to both sidebar and content fragments.

**Comment by khaykov** [comment]
Sneaked couple of minor fixes when no one was looking.

**Comment by maxme** [comment]
First, I'm impressed it works so well, all my orientation tests switches felt natural. I only noticed one minor issue: 1. landscape orientation 2. tap Blog posts 3. tap Stats 4. switch to portrait orientation 5. tap back, see a full screen Post list, I was expecting the My Site menu.

IMO, having a mixture of full screen and dual pane views when navigating the My Site menu is a weird experience (if @jasmussen is ok to merge it as it, I'm good with that). Not you're fault, "dual paning" everything is a huge task. If I'm not mistaken, what's needed for a good/full dual pane mode on the My Site Tab: fragment/activity refactors (Stats, Media, Themes, Settings, Comments), some component rewrites (spinner, transform action bar actions into something else), and more maintenance and testing when we change something in these views.

This exhibits the problem of implementing and doing the maintenance of a dual pane mode, it takes time and I'm not sure we should invest that time in this at the moment.

So even if we roll that out piece by piece, I think we're not going to implement other pieces in a near future - which make the whole rollout plan stuck at the first step ;) - and that's my conclusion: If we're not planning to work on other pieces, we should not merge this in develop.

**Comment by khaykov** [comment]
Thank's for the feedback! The issue you described is actually intended behaviour :) Idea is, when you tap Blog posts in landscape you are interacting with the Blog posts content, so when you come back from Stats in portrait the Blog posts would be visible because it was the content you were interacting before. In contrary, If you swiped to reader tab while having the Blog posts opened in landscape, then go portrait while in reader tab and swiped back, you would see MySite menu, because swiping to other tab indicates that you are not "interacting" with Blog posts anymore (it will still be there waiting for you in landscape mode). Makes more sense when all the screens in MySite support dual pane :)

I understand your concerns about dual-pane, and they are totally on point. This feature could always be revisited later, when priorities will change. So feel free to close this PR for now :)

**Comment by maxme** [comment]
> when you tap Blog posts in landscape you are interacting with the Blog posts content, so when you come back from Stats in portrait the Blog posts would be visible because it was the content you were interacting befor

IMO, it's not natural, because I was interacting with Stats before the rotation (step 3), I wasn't interacting with the Post List anymore. It's actually hard to say if I switched context (don't want to use the post list anymore) or if I want to push a new temporary task (analyze my stats). Now I'm confused, I'm not even sure what would be the best solution ;).

BTW, If the Stats screen was dual-paned, that wouldn't be a problem.

> I understand your concerns about dual-pane, and they are totally on point. This feature could always be revisited later, when priorities will change. 

Yes. I think this makes more sense. What did you learn from your implementation? Could we write our future fragments (related to My Site) in a certain way it would be easy to dual-pane them? Should we avoid using action bar actions?

**Comment by khaykov** [comment]
> What did you learn from your implementation? Could we write our future fragments (related to My Site) in a certain way it would be easy to dual-pane them? Should we avoid using action bar actions?

Actually, quite a lot :)
There are couple of things that should we should be careful about when making fragments that will work in dual pane mode. Action bar actions were the least of my worries, of course it would be better not to use them, but we can always supplement them with similar UI element in portrait orientation. 

Contextual Action Bar is something that can get weird, considering dual-pane host fragment is a child of ViewPager - we need to hide it when changing tabs, and deselect whatever we were selecting.

Soft Keyboard also does not work very well in ViewPager, and requires some special attention. Theme fragment has search toolbar, and dealing with it's focus on orientation/tab change was quite tricky. This will probably apply to all EditText elements.

Another thing is error handling. For example, Stas activity calls quit() every time something goes wrong. If we want to do something similar in dual pane mode, we need to make sure the fragment will show error toast, then call MySite (sidebar) and ask it to remove the called and show default fragment.

The biggest issue IMO, is the fragment back stack. For example, at Comments activity, when we tap on a comment we just replace the list with comment details, and add transaction to a back stack. We have two ways to get back, UP button at Toolbar and back button. Now, you probably see where it goes when the comment list is shown in dual pane ;) You go to comment details, and now we don't have UP button in toolbar (having it would be weird, I think) and what would happen when you press back button? Would you expect app to close? We are at root activity, so this makes sense. But how do we get to previous fragment? Let's say back button pops back stack, so you will need to clear all back stack before the app will close (did I mentioned that we are maintain different backstack with child FragmentManager and we need to make sure we are popping right one?). This becomes even more interesting when we have some transactions in back stack, and then we change ViewPager tab. Now what happens when we press the back button? Do we close app, or pop up backstack from MySite tab? All those issues are solvable, but solutions are often borderline hacky. The best one would probably be to just not do complicated fragment transactions in dual pane, and only allow new activities to be opened from it. 

Ase you see, there quite a lot of issues that need to be considered.

**Comment by maxme** [comment]
Thanks for these infos. I think we don't want to see a Toolbar at all, when in dual pane mode. I mean the 
"traditional" android Toolbar (with the UP button), could be something similar to the Calypso bar:

screen shot 2016-02-17 at 16 17 20

But I'm not sure we should display this while on a phone screen (meaning we'll end up with 2 code paths).

**Comment by khaykov** [comment]
Yes, we actually discussed this idea a little bit [here](https://github.com/wordpress-mobile/WordPress-Android/pull/3691#issuecomment-181150049).

**Comment by khaykov** [comment]
Actually the Theme screen is a good example of how it could be done.
Regular:
themes_1

In search mode I actually left the UP button:
themes_2

**Comment by jasmussen** [comment]
> IMO, having a mixture of full screen and dual pane views when navigating the My Site menu is a weird experience (if @jasmussen is ok to merge it as it, I'm good with that)

First off, I think this is very impressive work. Whether it's ready to merge or not, I insist that is a code-maintenance decision. But UI wise, I think it's right on point, and if not perfect, than at least an excellent prototype.

One of the things this dual pane adventure has made clear, is that we still have some big navigational hierarchy issues with Calypso on the web. These issues are most evident when switching from portrait to landscape and back again on Android. The web equivalent is resizing the browser window from wide to thin. Since the latter is presumably done less often than the former, fixing this on the web is not the biggest priority right now. But it is *a* priority, and work will be done at some point to improve this, even if we don't have a completely clear picture how a solution to these issues will look.

So that was a roundabout way of saying that changes to "dual-pane-mode" on the web will happen, which would be likely to require changes to Android dual-pane as well, if this gets merged in. 

That could be an argument for not merging this in as is, but instead approaching it piece-meal if that's possible. But even then, the lessons learned from this project I would consider very valuable.

**Comment by maxme** [comment]
@khaykov it's up to you to close this one.

**Comment by khaykov** [comment]
I'll close it for now, but hope we will be able to revisit it later.

**Pull request closed without merging**
