### PR TITLE
No email client causes crash when trying to sign in with magic links

### LINKED ISSUE #4185: Crash report 5.4.1: MagicLinkSignInFragment.openEmailClient
No default email app on the device
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.APP_EMAIL] }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
       at android.app.Activity.startActivityForResult(Activity.java:3778)
       at android.app.Activity.startActivityForResult(Activity.java:3739)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
       at android.app.Activity.startActivity(Activity.java:4049)
       at android.app.Activity.startActivity(Activity.java:4017)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.openEmailClient(MagicLinkSentFragment.java:80)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.access$100(MagicLinkSentFragment.java:17)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment$2.onClick(MagicLinkSentFragment.java:55)
       at android.view.View.performClick(View.java:4756)
       at android.view.View$PerformClick.run(View.java:19761)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4185 

To test:

1. Get to `MagicLinkSentFragment` when you have no default email client and there will be no "Open email" button
2. Get to `MagicLinkSentFragment` when you have a default email client and there will be an "Open email" button

### CODE REVIEW

**Comment by maxme** [comment]
PR works, "Open Email App" Button is hidden but the user lands on a screen with just the message "Check your emails" it's not obvious what they have to do

1. We could add another message to explain they should check their mailbox (on their mobile browser for instance) and tap the link.
2. We could disable magic link login for them (always display username + password fields)

I think solution 2 is better since these users are rare.

**Comment by kwonye** [comment]
> We could disable magic link login for them (always display username + password fields)

Great idea. If they don't have a default email client on their phone magic links would be a worse experience for them. I'll add it.

**Comment by kwonye** [comment]
@maxme ready for another go!

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
