### PR TITLE
Add Tenor support

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
This pull request proposes a solution that brings a complete integration for the Tenor API within the pre-existent GIF selection code inside the WordPress application, solving the [issue 11456](https://github.com/wordpress-mobile/WordPress-Android/issues/11456).

This is an aggregation branch for four different branches:

| Pull Request  | Link |
| ------------- | ------------- |
| Tenor API integrated with GIF Picker  | https://github.com/ThomazFB/WordPress-Android/pull/1  |
| GIF selection fully restored with Tenor API improvements  | https://github.com/ThomazFB/WordPress-Android/pull/2  |
| Replace UI and internal Giphy references  | https://github.com/ThomazFB/WordPress-Android/pull/3  |
| Add Tenor feature flag through selected build type  | https://github.com/ThomazFB/WordPress-Android/pull/4  |

Changelog
------------

### Tenor integration changes ###

* A `GifProvider` interface is now the only coupling between all code for the GIF picker and the Tenor implementation, avoiding any reference to the Tenor library and making it easy to replace the Provider as we're doing now.
* The `TenorProvider` implements the `GifProvider` interface and is injected within the `DataSource` via Dagger, this way only the `AppplicationModule` knows about the `TenorProvider`. Also, the `TenorProvider` is covered by unit tests in the `TenorProviderTest` class.
* The already implemented pagination feature and list actions are all kept and integrated to work smoothly with the `GifProvider`, this integration happens through the available `PositionalDataSource`, The Tenor implementation makes sure that positioning tracking is respected.
* The original integration with the `MediaBrowserActivity` was restored, making GIF selection available again.
* The original integration with the `EditPostActivity` was restored, making GIF selection available again when writing or editing posts.
* Analytics tracking restored.

### UI changes ###

* The Giphy attribution icon was removed and replaced by the Tenor attribution icon.
* Every UI string with `Giphy` information was replaced with `Tenor`. 

### Refactoring and improvements changes ###

* Test suite class added to `GiphyPickerDataSource` in order to better enforce the business logic when consuming any `GifProvider` implementation.
* The `giphy` packages inside `ui` and `viewmodel` were both renamed to only `gif`.
* All classes with the `Giphy` naming convention were renamed to only `Gif` to better fit the agnostic gif provider implementation strategy.
* All comments and documentation with references to `Giphy` or the Giphy SDK were readapted to better fit the `GifProvider` structure.

### Build configuration changes ###

* The `BuildConfig` now receive the declaration of the boolean `TENOR_AVAILABLE` field directly from the `build.gradle`.
* The button availability to select the Tenor GIF picker follows the `TENOR_AVAILABLE` value, if the value is false, the button doesn't get configured and should never appear on the screen.
* The `TENOR_AVAILABLE` is set as `true` for the Wasabi and Zalpha builds and `false` for the Vanilla build.
* Removed the Giphy SDK  reference at maven repository in `build.gradle`.

Testing
==========
Before doing any tests, make sure that to create a Tenor API key and paste it associated with the `wp.tenor.api_key` as the value inside your `gradle.properties`

GIF picking from Media Browser
------------

screencapture-1585095917110 2020-03-24 23_04_23

### How to test ###

1. Go to the Media Browser
2. Click on the Add button at the top right. Select the `Choose from Tenor` option
3. Type in the search bar to query GIFs
4. Once inside the Gif Picker, make sure that `selection`, `preview` and `add` are all working as expected

GIF picking from the Editor
------------

screencapture-1585276984938 2020-03-26 23_46_37

### How to test ###

1. Click to create a new post
2. Click on the overflow button at the top right end of the screen
3. select the `Switch to classic editor` 
4. Click on the plus (+) button at the bottom left end of the screen
5. Select the `Choose from Tenor` option
6. Type in the search bar to query GIFs
7. Once inside the Gif Picker, make sure that `selection`, `preview` and `add` are all working as expected

Tenor GIF picker feature flag - Post Editor
------------
| Wasabi and Zalpha  | Vanilla |
| ------------- | ------------- |
| screenshot-1585788446924  | screenshot-1585788432154  |

### How to test with Wasabi and Zalpha build ###
1. Click to create a new post
2. Click on the overflow button at the top right end of the screen
3. select the `Switch to classic editor` 
4. Click on the plus (+) button at the bottom left end of the screen
5. Verify that the `Choose from Tenor` option is available
6. Type in the search bar to query GIFs
7. Once inside the Gif Picker, make sure that `selection`, `preview` and `add` are all working as expected

### How to test with Vanilla build ###
1. Click to create a new post
2. Click on the overflow button at the top right end of the screen
3. select the `Switch to classic editor` 
4. Click on the plus (+) button at the bottom left end of the screen
5. Verify that the `Choose from Tenor` option isn't there

Tenor GIF picker feature flag - Media Browser
------------

| Wasabi and Zalpha  | Vanilla |
| ------------- | ------------- |
| screenshot-1585788487864  | screenshot-1585788395658 |

### How to test with Wasabi and Zalpha build ###
1. Go to the Media Browser
2. Click on the Add button at the top right
3. Verify that the `Choose from Tenor` option is available
4. Type in the search bar to query GIFs
5. Once inside the Gif Picker, make sure that `selection`, `preview` and `add` are all working as expected

### How to test with Vanilla build ###
1. Go to the Media Browser
2. Click on the Add button at the top right.
3. Verify that the `Choose from Tenor` option isn't there

PR submission checklist
==========
- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hello @planarvoid! Just for your information, I've added three additional commits directly to this branch.

The c604372736bfb3366aab5ee46cdee3222bd73ebb to adjust the `licenses.html` file as we talked at the slack.

The 74082b99a8612d026dcea26a65ea1520a17e67a7 and 009684b9e1e1e034aa4fd3af37a1c4933cefab6e to fix the checkstyle and lint reports.

What do you think?

**Comment by planarvoid** [comment]
Hey @ThomazFB, thanks for the PR! I was wondering about why you moved the error string from the `strings.xml` into a constant? This way it can't be translated. I actually quite liked the previous approach.

**Comment by ThomazFB** [comment]
> Hey @ThomazFB, thanks for the PR! I was wondering about why you moved the error string from the `strings.xml` into a constant? This way it can't be translated. I actually quite liked the previous approach. Is it the Unused resource lint warning? We usually suppress these when the strings are used just in the code.

Hello @planarvoid! It was exactly because of the lint warning! The report was pointing out about the unused strings. And so I thought that the project was restricted about using strings for Exception messages, should we suppress those errors then?

**Comment by ThomazFB** [comment]
Hey @planarvoid! Thank you for your feedback! Just letting you know that I committed a fix with your proposed string suppression for unused warnings and reverted the translatable string usage. Here's the commit: 0c09c88d77d77acd9a152dad0546e9093563578b. What do you think?

**Comment by planarvoid** [comment]
thanks for the changes @ThomazFB, we usually do `git merge develop` instead of rebases here but rebase works just as well :-). 
I'd recommend doing something like this to ignore the exception:
```
<string name="stats_site_not_loaded_yet" tools:ignore="UnusedResources">Site not loaded yet</string>
```

**Comment by ThomazFB** [comment]
Thank you for the suggestions @planarvoid! I'll prioritize merges instead of rebases then! Also, I've just modified the suppression declaration right here: 13e88ec3e3e7b2ab3ac19a4419cf65067715602e. Let me know what you think.

**Pull request merged**
