### PR TITLE
Cleanup a few lint warnings about contentDescription

### PR DESCRIPTION
**Pull request by hypest**
This PR addresses a handful of the `Image without contentDescription` issues brought up when running the linter on the WordPress module.

What I would ideally like to take out of this PR, besides merging it, is to start forming a checklist a wpandroid contributor can consult to figure out whether the `contentDescription` or `importantForAccessibility` attribute need to be set on an ImageView.

Also ideally, we probably want to set a "template" on what such a PR should include.

Thanks!

Images addressed:
* The Drake illustration on the "My Site" screen when no sites are available. Added a `contentDescription` in this case.
* The icons on the left of the "My Site" screen items. Added `importantForAccessibility=no` on those.

### CODE REVIEW

**Comment by maxme** [comment]
Some information there: https://material.io/guidelines/usability/accessibility.html#accessibility-implementation

> Screen-reader users need to know which UI elements are tappable on-screen. To enable screen readers to read the names of components out loud, add the contentDescription attribute to components such as buttons, icons, and tabs containing icons that have no visible text. 

I'd probably use `importantForAccessibility="no"` everywhere on non tappable image unless it's an important hint for screen navigation/understanding (like an empty list view with only an image).

**Comment by catehstn** [comment]
This PR has been open since September - @hypest, do you need anything to get it merged?

**Comment by hypest** [comment]
I brought the PR up to date and removed the `Needs Design Review` as the changes are only related to a11y. The PR is ready for review now. /cc @catehstn

**Comment by maxme** [comment]
Looks good :shipit:

**Pull request merged**
