### PR TITLE
Jetpack Section: Update Activity Log Details UI and Add Backup Download Button/Flow

### LINKED ISSUE #14095: Jetpack Section: Update Activity Log Details UI and Add Backup Download Button/Flow
As per the requirements in this post (`pcdRpT-cM`, see `Activity Log: Event Details`), this issue is about:
- UI updates on this screen to match design, and
- Adding the `Backup Download` button and connecting the button with the new flow.

Before | After
-------|------
before | after

On Android, the screen looks a bit different today, comparing the before (or current) of Android with the after (or current) of iOS:

Before or Current (Android) | After or Current (iOS)
-------|------
before android | after ios

@osullivanchris can you please suggest what UI changes need to happen to the UI so that Android get the appropriate after look, and still be comparable with iOS's after look?

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #14095

This PR does the below:
- It updates the `Activity Log Details` screen UI based on design (see [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/14095#issuecomment-780685652) for more details).
- It add the `Download Backup` button and connects the `Activity Log Details` screen with the backup download flow.
- It replaces the `Rewind Status Service` with a more simplified solution for making sure that the restore and download backup buttons are shown/hidden depending on the rewindable and in progress status of the activity log items.

More importantly, this PR makes sure that when a user presses the `DOWNLOAD BACKUP` button within the `Activity Log Detail` screen, then they get redirected to the `Backup Download` screen. Also, when a backup download gets triggered from within this flow, this PR makes sure that the user get redirected back to the `Activity Log` screen, skipping the `Activity Log Detail` screen and starts seeing the backup download progress row within that screen.

Light Theme | Dark Theme | Layout Bounds
-------|------|------
before | after | after

To test:
* Open app and go to `My Site` tab.
* Launch `Activity Log` or `Backup` screen.
* Find a rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, make sure that both, the `RESTORE` and `DOWNLOAD BACKUP` buttons are visible.
* Make sure the UI matches the designs (see [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/14095#issuecomment-780685652) for more details).
* Go back to the previous list screen.
* Find a non-rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, make sure that both, the `RESTORE` and `DOWNLOAD BACKUP` buttons are not visible.
* Go back to the previous list screen.
* Trigger the `Restore` or `Backup Download` flow from a rewindable item from the list. Wait for the progress item to appear and the menu item on all the list items to disappear.
* While the `Restore` or `Backup Download` process is in progress, find a rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, make sure that both, the `RESTORE` and `DOWNLOAD BACKUP` buttons are *NOT* visible.
* Go back to the previous list screen.
* While the `Restore` or `Backup Download` process is in progress, find a non-rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, make sure that both, the `RESTORE` and `DOWNLOAD BACKUP` buttons are not visible.
* Wait for the `Restore` or `Backup Download` process to finish.
* Find a rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, click the `RESTORE` button to launch the `Restore` screen,
* Click the `Restore site` button. On the confirmation screen, click on the `Confirm restore site` button.
* Navigate back manually (by clicking the `X` toolbar button or pressing/swiping back).
* You should automatically be navigated back to the `Activity Log` screen, skipping the `Activity Log Detail` screen and a restore status will be triggered,
* The restore progress item should immediately appears. Make sure the restore timestamp is available on this progress item.
* Try doing the same steps again, but this time when within the `Restore` screen and flows, **DO NOT** trigger the restore, go back.
* Make sure that going back will navigate to the `Activity Log Detail` screen.
* Again, find a rewindable item from the list and click on it. You will now enter the `Activity Log Detail` screen.
* On that screen, click the `DOWNLOAD BACKUP` button to launch the `Backup Download` screen,
* Click the `Create downloadable file` button.
* Navigate back manually (by clicking the `X` toolbar button or pressing/swiping back).
* You should automatically be navigated back to the `Activity Log` screen, skipping the `Activity Log Detail` screen and a backup download status will be triggered,
* The backup download progress item should immediately appears. Make sure the backup download timestamp is available on this progress item.
* Try doing the same steps again, but this time when within the `Backup Download` screen and flows, **DO NOT** trigger the backup download, go back.
* Make sure that going back will navigate to the `Activity Log Detail` screen.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — APPROVED** [review]
@ParaskP7 🥳  Everything works as expected. 🙇‍♀️  for getting rid of the services, so happy to see those gone!

**Comment by ParaskP7** [comment]
👋 @zwarm !

Thank you so much for the rapid review and for merging that to `develop`, you rock! 🙏 

PS: About those services, YEA, so happy to have them gone as well! 🎉 

👋 @osullivanchris !

Apologies for merging with `develop` without your approval first, I forgot to add the **MERGE INSTRUCTION** on the PR description and explicitly specific to **NOT** merge until that is done.

Please feel free to suggest any change and I'll create another PR afterwards. 🙏

**Comment by osullivanchris** [comment]
@ParaskP7 Hey I just went through it. It looks great. Nice quick fix and good attention to detail on the UI, it looks spot on. Thank you!

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

Many thanks for the review, and your kind words, as always! ❤️

**Pull request merged**
