### PR TITLE
Fix rounding issues on stats

### PR DESCRIPTION
**Pull request by irfano**
This fixes rounding issues on stats cards. The problem is introduced in #16947. 

It was showing `16.6%` as `16%`. This PR will show it as `17%`.
These are the cards having the issues:
- Most Popular Time card
- Views & Visitors card
- Total Likes card
- Total Comments card
- The bar chart on DAYS, WEEKS, MONTHS, YEARS tabs
- The bar chart on Posts and Pages detail screen

To test:
1. Launch the Jetpack app.
2. Open Stats from "My Site → HOME → Stats" or "My Site → MENU → Stats".
3. If **Most Popular Time** card is not added to the screen, add it by using ⚙️ button at the top end of the screen.
4. Verify percentage numbers are the same with the iOS version and web. (You can navigate the same screen on the iOS app by using the same steps here)
5. If **Views & Visitors** card is not added to the screen, add it by using ⚙️ button at the top end of the screen.
6. Verify percentage number on the Views & Visitors card is correct.
7. Tap **Views & Visitors** and navigate to the **detail** screen.
8. Verify percentage number on the Views & Visitors card is correct.
9. Navigate back.
10. If **Total Likes** and **Total Comments** cards are not added to the screen, add them by using ⚙️ button at the top end of the screen.
11. Verify percentage numbers on the Total Likes, and Total Comments cards are correct.
12. Navigate to DAYS, WEEKS, MONTHS, or YEARS tab.
13. Verify percentage number on the **bar chart** card is correct. 
14. Change the tab on the bar chart card and repeat 13.
15. Tap an item on the **Posts and Pages** card.
16. Verify percentage number on the bar chart card is correct. 
17. Repeat 2-16 for a different site.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
Updated current unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
> This PR will show it as `%17`.

Did you mean `17%`?

**Comment by RenanLukas** [comment]
Hey @irfano , thank you for the PR 👍 

I couldn't find any card showing percentage (e.g. `MOST POPULAR TIME`) in the `Insights` tab while testing iOS, but it's shown on Android for the same site. Does anyone know if this is expected? 🤔 

Also, in all the charts that I've tested where we're showing the infinity symbol (∞) on Android, iOS shows 0%. I suppose this is not related to the changes on this PR.

image

Besides the fact that I couldn't find any percentage on the `Insights` tab cards while testing iOS, everything else that I've found in both platforms matched 👍 
I've also checked web for the fields that Android also displays.

**Comment by irfano** [comment]
> Did you mean `17%`?

Yes, I meant `17%`, fixed that. Thanks!

**Comment by irfano** [comment]
> I couldn't find any card showing percentage (e.g. `MOST POPULAR TIME`) in the `Insights` tab while testing iOS, but it's shown on Android for the same site. Does anyone know if this is expected? 🤔

Yes, the Stats Revamp project has been released on Android but not yet on iOS. It's expected.

> Also, in all the charts that I've tested where we're showing the infinity symbol (∞) on Android, iOS shows 0%. I suppose this is not related to the changes on this PR.

Thanks for finding this, @RenanLukas! Actually, `0%` is removed on iOS for infinite cases https://github.com/wordpress-mobile/WordPress-iOS/pull/19400. `(∞)` doesn't look good to me. IINM, web doesn't show `(∞)` too. We should remove it from Android too, we shouldn't show `(∞)` when the percentage is infinite. I opened the issue https://github.com/wordpress-mobile/WordPress-Android/issues/17314

**Review by RenanLukas — APPROVED** [review]
Thanks for creating the issue to handle `(∞)`
LGTM :shipit:

**Pull request merged**
