### PR TITLE
Merge release/19.2 (19.2-rc-1 code freeze)

### PR DESCRIPTION
**Pull request by ParaskP7**
Code freeze and release of [19.2-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/19.2-rc-1).

- [x] New empty entry created in `RELEASE-NOTES.txt` for next iteration.
- [x] `{jetpack_}metadata/release_notes.txt` extracted for WordPress and Jetpack.
- [x] `WordPress/jetpack_metadata/release_notes.txt` audited to remove any item not applicable for Jetpack.
- [x] Internal dependencies (FluxC, Login. Stories. About…) bumped to a new stable version in `build.gradle` if necessary.
- [x] `WordPress/src/main/res/values/strings.xml` updated with strings from binary dependencies.
- [x] New strings frozen/copied into `fastlane/resources/values/strings.xml`.
- [x] Version bumped in `version.properties`

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Can you please confirm that the `Jetpack` release notes are as expected? 🙏

**Comment by ParaskP7** [comment]
👋 @hypest !

Can you please double check that anything related to `Gutenberg` applies to Android (and not iOS only). 🙏

**Review by mokagio — COMMENTED** [review]
- [x] New version header in `RELEASE-NOTE.txt` 
- [x] Version updates in `version.properties`
- [x] `release_notes.txt` updated with notes from `RELEASE-NOTE.txt` for current version 
- [x] `strings.xml` updates via automation merging values from libraries

I don't see any changes to the internal libraries versions. [`trunk` doesn't show any RC being in use](https://github.com/wordpress-mobile/WordPress-Android/blob/fa84370aad432a067cd54a715d574737be48b5fc/build.gradle) so maybe there hasn't been any change to any library during this sprint.

If that's expected, then feel free to merge.

**Comment by hypest** [comment]
> Can you please double check that anything related to Gutenberg applies to Android (and not iOS only). 🙏

Good to go @ParaskP7 👍

**Comment by AliSoftware** [comment]
> I don't see any changes to the internal libraries versions. [trunk doesn't show any RC being in use](https://github.com/wordpress-mobile/WordPress-Android/blob/fa84370aad432a067cd54a715d574737be48b5fc/build.gradle) so maybe there hasn't been any change to any library during this sprint.

Indeed, we didn't have any library to release, everything was already on a tag / stable version.

We pondered about doing a new version of FluxC (i.e. `trunk` was pointing to `1.34.0` which means that at the time we cut the release branch, that's the version that WPAndroid was expected to build with, even if in practice FluxC has new commits since `1.34.0` which could have warranted us to create a new version `1.35.0` at the time of the code freeze to pull all the new changes.

In practice all the changes that were pushed in FluxC after `1.34.0` are WooCommerce-related and not relevant to WordPress (and if any of those changes were needed by a feature then `trunk` would have been pointing to a `trunk-<sha1>` or more recent tag anyway, otherwise the new feature would not be building anyway, which proves that none of those new commits were needed by WP at the time of code freeze)

Personally, I usually use the occasion of the code freeze to still do a new version of FluxC (to include all the latest commits) even if not strictly necessary (i.e. even if any new commits were likely done by WC and not relevant to WP), just so that we are using the latest version and commits (and in case WC folks shipped a bug fix that could benefit to WP while we're at it).

But doing that also has the risk of pulling a FluxC commit done by WC's team but that would accidentally break WP… so it's also kind of a bargain to create a new FluxC and bring latest commits while they're not strictly necessary and were not tested against during `trunk`… so @ParaskP7 preferred to err on the side of caution here and keep the stable version that was in `trunk` rather than risking pulling untested changes from latest commit potential breaking WP, which was a very sensible rationale as well, and why we ended up not doing a new version of FluxC

**Review by AliSoftware — APPROVED** [review]
> If that's expected, then feel free to merge.

It was expected indeed (no new lib release was needed, see comment above), so approving and auto-merging.

**Comment by AliSoftware** [comment]
Eh forgot to wait for Leandro to confirm the Jetpack release notes 😅  Eh, if it ends up there are some amends to make to it, we can always do a subsequent PR to fix that 🙂

**Pull request merged**
