### PR TITLE
Issue/2873 app compat activity

### LINKED ISSUE #2873: Convert ActionBarActivity to AppCompatActivity
Now that we're using v22.1 of the Android Support Library, we should convert ActionBarActivity to AppCompatActivity. See the **AppCompat** section of [this blog post](http://android-developers.blogspot.in/2015/04/android-support-library-221.html) for details.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #2873 - updates all instances of ActionBarActivity to AppCompatActivity, as recommended in [this blog post](http://android-developers.blogspot.in/2015/04/android-support-library-221.html).

@maxme I figured we'd make this change now before it was required in the future, but it's obviously your call as to whether it's necessary at this point.

### CODE REVIEW

**Comment by aforcier** [comment]
Note that this currently breaks the editor(s) due to a `ClassCastException` when attempting to edit a post. The references to `ActionBarActivity` in `libs/editor` (`EditorFragment`, `LegacyEditorFragment` and `EditLinkActivity`) should be updated as well.

**Comment by aforcier** [comment]
Update: will be updating the `EditorFragment` to drop references to `ActionBarActivity` (https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/166)

(this still leaves the `LegacyEditorFragment` and `EditLinkActivity` to be dealt with, either by dropping the reference to the containing activity or just renaming)

**Comment by maxme** [comment]
`EditLinkActivity` doesn't need an action bar, probably should inherit `android.app.Activity`, `LegacyEditorFragment` should include the same changes you applied to `EditorFragment`.

**Comment by aforcier** [comment]
Made the changes to `EditorFragment`, `LegacyEditorFragment` and `EditLinkActivity`, they're in this PR in the editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/167

Will `subtree pull` the changes into WPAndroid and open a PR once the editor PR is merged.

**Comment by maxme** [comment]
Waiting for wordpress-mobile/WordPress-Editor-Android#167 to be merged and the editor subtree pulled before merging this

**Comment by bummytime** [comment]
@aforcier wordpress-mobile/WordPress-Editor-Android#167  is merged.

**Comment by aforcier** [comment]
Pulled editor subtree changes into PR #2880.

**Pull request merged**
