### PR TITLE
Domains: enable domains only for jetpack mobile app

### LINKED ISSUE #16381: Domains: Enable domains purchase on Jetpack app only
It has been decided to enable domains purchase on Jetpack only.  Please see below for context

pbArwn-3Sl-p2

pc8eDl-hH-p2

### PR DESCRIPTION
**Pull request by ravishanker**
Enable domains purchase on Jetpack Mobile app only

Fixes #16381 

| Feature Config | Domains | 
|---|---|
| Screenshot_20220422_131651|Screenshot_20220422_125553|

To test:

Setup
- Make sure you're using Jetpack app
- Go to App Settings -> Debug settings -> Enable SiteDomainsFeatureConfig and restart app 

Test 1

- Launch Jetpack app
- Find Domains menu under Configuration (under My Site or the new SITE MENU tab)
- Tap on Domains, it should take to Domains dashboard

Test 2

- Launch WordPress app
- Go to App Settings -> Debug settings -> Enable SiteDomainsFeatureConfig and restart app 
- Make sure Domains menu doesn't show up under Configuration (under My Site or the new SITE MENU tab)

Test 3 - Main Scenario

1. Open the Jetpack app.
1. On the Main screen, tap the "Domains" item under the "Configuration" section.
1. On the Domains Dashboard screen, tap the "Add a domain" or "Search for a domain" button.
1. Complete the domain registration flow.
1. On the Success screen, tap "Done".
1. On the Dashboard screen, notice the domain list is updated with the newly registered domain

Other scenarios to try out, that have been tested as part of feature development on WordPress app
1. Free plan with custom domains
3. Free plan with no custom domains
4. Paid plan with custom domains and credits
5. Paid plan with custom domains and no credits
6. Paid plan with no custom domains and credits
7. Paid plan with no custom domains and no credits

NOTE:  There are a few flows based on credits and other site settings.  Mainly make sure the purchase flow happens with the credits or payment

## Regression Notes
1. Potential unintended areas of impact
None, it is behind a feature config

8. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested both WordPress and Jetpack apps

9. What automated tests I added (or what prevented me from doing so)
Existing unit tests

Before merging

- [x] Confirm merge for launch
- [x] Update Feature Config for Remote field
- [x] Update release notes

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — APPROVED** [review]
LGTM 👍

**Comment by guarani** [comment]
Thanks for getting the build ready, @ravishanker!

- [x] Setup
- [x] Test 1
- [x] Test 2
- [ ] Test 3 - Main Scenario
  - ⚠️  I failed to buy a Free `.code.blog` subdomain while on a Free plan: the app says "You have no items in your cart" / "If you were trying to add something to your cart, there may have been a problem. Try adding it again."
  - ✅ I successfully bought a Paid `.blog` domain while on a Free plan using 9.9 USD of free credit and the new domain successfully redirects to the original `.wordpress.com` subdomain as expected.
  -  ✅ I successfully bought a "Free for the first year" `.social` domain while on a Pro plan using free credit. Given I was now on a Pro plan, this new URL no longer re-directed to the `.wordpress.com` subdomain, but instead to the `.blog` domain I purchased above (which I think is expected).

@ravishanker, do you know why the Free domain couldn't be purchased?

---

> Other scenarios to try out, that have been tested as part of feature development on WordPress app
> 
>     1. Free plan with custom domains
>     2. Free plan with no custom domains
>     3. Paid plan with custom domains and credits
>     4. Paid plan with custom domains and no credits
>     5. Paid plan with no custom domains and credits
>     6. Paid plan with no custom domains and no credits
> 
> NOTE: There are a few flows based on credits and other site settings. Mainly make sure the purchase flow happens with the credits or payment

@ravishanker, where can I find more information about these additional test cases? Specifically, I'd like to know:
- What's the difference between "with custom domains" and "without custom domains" in your above list? Do you have a link to details of when these tests were done on WPAndroid?
- In the "and no credits" scenarios in your above list, how is this tested? Is an actual credit card needed?

Please hold off merging this for now 🙇

**Comment by ravishanker** [comment]
> @ravishanker, do you know why the Free domain couldn't be purchased?
You can’t register a subdomain (of a normal domain). You have to own the domain, and then do some DNS setup to create the subdomain itself. So, subdomains will not be supported in mobile flows at this point, with the exception of .wordpress.com and .blog subdomains (but these are used as site addresses and therefore probably only available in the site creation flow)

I seem to have same issue.  I see in the logs "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3.
Is this by any chance a jurassic.ninja created site?  Usually, jurassic ninja created sites are deemed as self-hosted sites!
Does it work on iOS?
I've checked on the web, it is showing only custom domains when you search, not showing any free ones.  We may need to filter out free domains
> 
> @ravishanker, where can I find more information about these additional test cases? Specifically, I'd like to know:

[This PR lists all the above scenarios](https://github.com/wordpress-mobile/WordPress-Android/pull/15521).  It is how dashboard presents itself depending on conditions.  More [discussions here](p1633549036242800-slack-C0280085R7W)

>     * What's the difference between "with custom domains" and "without custom domains" in your above list? Do you have a link to details of when these tests were done on WPAndroid?
custom domains means any non .wordpress.com ending domains.  Please also see the above PR

>     * In the "and no credits" scenarios in your above list, how is this tested? Is an actual credit card needed?
There's a way to test this without  using actual credit card [with a sandbox setup](pbArwn-2GN-p2),  and [some more instructions on this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15153)

> Please hold off merging this for now 🙇

Sure, it is also behind a feature flag.

**Comment by guarani** [comment]
Thanks for the above responses, @ravishanker.

> I've checked on the web, it is showing only custom domains when you search, not showing any free ones. We may need to filter out free domains

Please check with @frosty to align the platforms. It does look like the free domains might not need to be shown.

|   | Screen Shot 2022-05-11 at 21 13 45 | 
| - | - |

We're going to ship this in 19.9 (internal reference), and its beta is cut next Monday. In anticipation for this, would it make sense to move forward with the updating this PR to resolve conflicts and get the latest from `trunk`, enabling the feature flag, adding release notes, etc? I'm hoping we can merge this this May 13 (within 48hs), unless any blockers come up.

**Comment by ravishanker** [comment]
> We're going to ship this in 19.9 (internal reference), and its beta is cut next Monday. In anticipation for this, would it make sense to move forward with the updating this PR to resolve conflicts and get the latest from `trunk`, enabling the feature flag, adding release notes, etc? I'm hoping we can merge this this May 13 (within 48hs), unless any blockers come up.

@guarani - I've updated the PR to be ready for release.  Please go ahead and merge it if you're OK 🙇🏻‍♂️

**Comment by guarani** [comment]
> @guarani - I've updated the PR to be ready for release. Please go ahead and merge it if you're OK 🙇🏻‍♂️

Thank you @ravishanker! I'll give it a quick test and merge it if everything looks OK 🙇

**Comment by guarani** [comment]
I did a quick smoke test where I enabled the store sandbox, bought a domain using dummy credit card information, and confirmed the new domain appears in the Site Dashboard. I also double-checked that the Domains Dashboard isn't visible on the WordPress build.
I did not actually buy a domain here, I only tested within the sandbox. 

I'm merging this now, since it looks ready and has a code review.

**Pull request merged**
