### PR TITLE
Consolidate styles in Insights in refreshed Stats

### PR DESCRIPTION
**Pull request by planarvoid**
In this PR I've implemented design cleanup and fixed stuff that was missing. It's also a point for a design review (@SylvesterWilmott ) for the `Insights` tab because all the blocks should be implemented now. 
@theck13 It's likely we haven't implemented the Styles correctly so please let me know if there is anything you'd change 🙇 

What was implemented:
- Use standard dimensions instead of values directly + extracted some other common fields
- Replace the `progress bar` with a new animation when items are being loaded
- Fix field underscore length when an icon is missing
- Only update Tab item when a user selects a Tab
- Add scrolling to Toolbar and change the text to `Stats`
- Fix paddings in the list

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Fantastic job! Really, hats off to @planarvoid and @0nko 

Looking at the UI, a few things I noticed:

- We should stay consistent with the table row margins: Between cards, the distance between the left and right labels appear to be different. To clarify, these should be 8dp.

screenshot 2018-12-11 at 13 12 55

- The table headers appear to be 42dp instead of 40dp

screenshot 2018-12-11 at 13 15 05

- As discussed already with @planarvoid , the line on the tabs should be #E9EFF3

- Let's change the string `Tags & Categories` to `Tags and Categories`

- The left on the cards need a review. Some are correct and others are off:

**Latest Post Summary**

latestpostsummary

1. Title bar content should align to 16dp
2. Paragraph should align to 16dp
3. Button (View More) row content should align to 16dp

**Most Popular Day and Hour**

mostpopulardayandhour

1. Title bar content should align to 16dp

**Today's Stats, All Time Stats, Tags and Categories, Publicize**

alltimestats

tagsandcategories

publicize

1. Title bar content should align to 16dp
2. Icons should align to 16dp
3. Row text should align to 72dp from the card edge (not screen edge)
3. Button (View More) row content should align to 16dp

**Comments, Followers**

comments

followers

1. Title bar content should align to 16dp
2. Image/icon should align to 16dp
3. Button (View More) row content should align to 16dp

**Comment by planarvoid** [comment]
Thanks a lot 💯  for testing it so deeply! I've tried to fix everything you suggested.

> * We should stay consistent with the table row margins: Between cards, the distance between the left and right labels appear to be different. To clarify, these should be 8dp.

Fixed ✅ 
 
> * The table headers appear to be 42dp instead of 40dp

Fixed ✅ 

> * As discussed already with @planarvoid , the line on the tabs should be #E9EFF3

Fixed ✅ 

> * Let's change the string `Tags & Categories` to `Tags and Categories`

Fixed ✅ 

I've aligned everything to 16dp from the left side - I used a wrong constant when extracting styles 🤦‍♂️ 

> 3. Row text should align to 72dp from the card edge (not screen edge)

This should be fixed but it's a little tricky. I'm using a constraint layout where there is an icon (24dp wide, 2dp padding, 16dp left margin) and the text next to it has 32dp left margin with the icon and 16 dp without the icon. Let me know if it looks good. It's hard for me to see.

**Comment by SylvesterWilmott** [comment]
Looks so good! Thanks for all the changes.

I've noticed a couple more nitpicks:

- On the latest post summary, we will also need to align the button in the same way as the other rows.

screenshot 2018-12-12 at 16 30 57

- Are we using bold text to highlight the post title in latest post summary? It should be medium. If it's already medium let's use regular. The weight seems a little harsh.

- In latest post summary, if the latest post is untitled we don't show any post name. We should use `(Untitled)` as a fallback if a post has no title

screenshot 2018-12-12 at 16 33 54

- In All Time Stats, the Best Views Ever row shows a date. Can we use `grey_darken_20` for the text colour.

- For the tabbed cards, would it be an easy change to hide tabs when no data exists in either tab?

screenshot 2018-12-12 at 16 43 05

**Comment by SylvesterWilmott** [comment]
I found a couple of buggy bits, not sure how much we have control over but here you go anyway:

- If I trash my latest post, it still appears in my latest post summary. This means I can get an option to share a post that doesn't exist anymore.

- The latest post summary appears for "the journey begins" post, is there something unique about this post or a post number that we can just ignore it in latest post summary? Then we can show this state instead:

screenshot 2018-12-12 at 21 40 03

- On a card with tabs, if one tab is empty and one is filled with data, there is no animated transition when tabbing from the filled one to the empty one. This is common on followers when "email" is empty in case you wanted to check.

**Comment by planarvoid** [comment]
> * grey_darken_20

**Comment by planarvoid** [comment]
Thanks again for looking at this

> * On the latest post summary, we will also need to align the button in the same way as the other rows.
Done

> * Are we using bold text to highlight the post title in latest post summary? It should be medium. If it's already medium let's use regular. The weight seems a little harsh.
The thing is I'm setting this programatically and I can set a just a typeface. The options are DEFAULT, DEFAULT_BOLD,  SANS_SERIF, SERIF, MONOSPACE for the font and public static final int NORMAL, BOLD, ITALIC, BOLD_ITALIC for the style. I've used DEFAULT + BOLD before, now it's DEFAULT_BOLD + NORMAL, which doesn't seem bold at all 😨 

> * In latest post summary, if the latest post is untitled we don't show any post name. We should use `(Untitled)` as a fallback if a post has no title

Done

> * In All Time Stats, the Best Views Ever row shows a date. Can we use `grey_darken_20` for the text colour.

Done

> * For the tabbed cards, would it be an easy change to hide tabs when no data exists in either tab?

Done

> * When columns are empty in the graph can we show a greyish bar that fades like in Zeplin? If we don't do this it might feel like the data hasn't loaded yet which would especially be an issue when we have an empty chart.

In the `Last post summary` block we never show the graph when there are no views. However, I've implemented this anyway because it might make sense in the Day/Week/Month/Year view. 

> * Do we need to update the margins of the separators too? It's not aligning with the text in some of the cards.

Done

**Comment by SylvesterWilmott** [comment]
Looks so good @planarvoid 

Couple more things:

- Can we change the string `Most popular day and hour` to `Most Popular Day and Hour`
- In the `Most Popular Day and Hour` block, can we just show the percentage on the right of the rows, so instead of `N% of views` just show `N%`

**Comment by planarvoid** [comment]
@SylvesterWilmott thanks! I've fixed the remaining Most popular issues

**Comment by theck13** [comment]
Are these changes ready for code review?  There looks like a lot more than just design and style updates in this pull request.  If it's intended for me to review _all_ the code changes, let's update the original comment to avoid confusion.  If not, we should request another developer to make sure everything is reviewed.

**Comment by planarvoid** [comment]
@theck13 I'm pulling in @0nko  for the code changes and you can start with the Styles consolidation (if that's ok), thanks 💯

**Review by theck13 — APPROVED** [review]
All the style updates look good to me.

Eventually, I would like to consolidate all styles and files, but that is out of the scope of these changes.

**Review by 0nko — APPROVED** [review]
Looks good to me 👍

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
