### PR TITLE
Site Creation: Domains ViewModel unit tests

### LINKED ISSUE #8508: [Site Creation] Step: Domain Selection - Unit Tests
Write unit tests for Step: Domain Selection VM. Parent ticket #8507

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #8508. This PR adds unit tests for `NewSiteCreationDomainsViewModel` and `FetchDomainsUseCase`. It follows an approach very similar to `NewSiteCreationVerticalsViewModelTest` and `FetchVerticalsUseCaseTest`. It also updates the `org.wordpress.android.ui.sitecreation.domain` package to `org.wordpress.android.ui.sitecreation.domains` for consistency.

I've added comments to each test for what it tests in `NewSiteCreationDomainsViewModel` and kept the logic fairly simple. Each test is testing a single thing (one state) even in cases where the setup is exactly the same as another test.

Note that there are some very minor refactors in the actual code to make the it more testable.

**To test:**
* Run newly added unit tests

_P.S: Single reviewer should be enough for this PR_

### CODE REVIEW

**Comment by oguzkocer** [comment]
@malinajirka Welcome back! Could you review this one when you get a chance since you're very familiar with it? :)

**Comment by malinajirka** [comment]
Thank you @oguzkocer! It looks good overall. Only thing I'd consider is adding tests for error states. Wdyt?

**Comment by oguzkocer** [comment]
> Only thing I'd consider is adding tests for error states. Wdyt?

🤦‍♂️ Well.. I don't think I can prioritize that right now. Let's either edit #8508 or open a new issue for this and consider it a low priority. Let's focus on the user facing changes first and then we can pick up the few remaining tests when we are done. Does that work for you?

**Comment by malinajirka** [comment]
Sure, sounds good;). Thanks!

**Pull request merged**
