### PR TITLE
[Gutenberg] Update `compileSdkVersion` to 34

### PR DESCRIPTION
**Pull request by fluiddot**
**Related PRs:**
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/6196
* https://github.com/WordPress/gutenberg/pull/54437

Part of https://github.com/wordpress-mobile/WordPress-Android/issues/19106.

**To test:**
* Check that all CI jobs pass.
* Smoke test the editor.

## Regression Notes
1. Potential unintended areas of impact
The PR bumps the Aztec version used in the Gutenberg editor, so might have an impact to the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing the Gutenberg editor.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by thomashorta — COMMENTED** [review]
I wonder if we should keep this PR as "not ready for merge" until we have a released gutenberg mobile using `compileSdkVersion` 34. Other than that, it looks good to me!

**Comment by fluiddot** [comment]
> I wonder if we should keep this PR as "not ready for merge" until we have a released gutenberg mobile using `compileSdkVersion` 34. Other than that, it looks good to me!

Yep, we need to wait for the GBM PR to be merged and create an alpha version before merging this one. We don't usually mark the PRs as "not ready for merge" because we are aware that the GBM reference should always point to a Git tag. However, I'm open to using it if that makes more sense. Thanks!

**Review by geriux — APPROVED** [review]
Approved via https://github.com/wordpress-mobile/gutenberg-mobile/pull/6196 🚀

**Comment by fluiddot** [comment]
⚠️  Now that the PR is approved, I'll proceed to generate an alpha version of GBM. Note that we can't merge this PR until the GBM reference points to the alpha version.

**Comment by thomashorta** [comment]
Thanks for dealing with this! 🙇🏼

**Pull request merged**
