### PR TITLE
Feature/update threaded comment design

### LINKED ISSUE #15593: Implement visual changes to the Threaded Comments

### LINKED ISSUE #15594: Allow sharing of the links to individual comments

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #15593
Fixes #15594

This PR implements the first part of UI change to threaded comments. Comment moderation for Administrators will come later.

Share functionality for now only shares the shortened URL to the comment.

[[Image from Gyazo](https://gyazo.com/90af003f1a2c1193863ac1e2e74e91f9)](https://i.gyazo.com/65484547567cbf4f82450fd57f696773.png)

[Image from Gyazo](https://gyazo.com/1ac4b881ca9609d3a5ec00a311832886)

To test:
- Open comments for a Post from the reader.
- Make sure they look similar to the screenshots provided.
- Confirm that the sharing button works as expected.

## Regression Notes
1. Potential unintended areas of impact
- Visual issue.
- Sharing now working.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual testing.

3. What automated tests I added (or what prevented me from doing so)
Changes are visual, so no testing is required.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mattmiklic — APPROVED** [review]
I'm at a meetup today so I'm not able to install the build, but going from the screenshots included the design looks great to me. 

One request -- right now when a comment is liked, the word "Like" turns into the # of likes it's received. I'd like to append the word "Likes" there, so it looks like `⭐️ 5 Likes`.

I'll take a look at the apk next week when I'm back in my office and will ping if I see anything else that should be adjusted.

**Comment by khaykov** [comment]
@mattmiklic Thanks for checking! Update the like counter:

[Image from Gyazo](https://gyazo.com/13e0592aa47d9f0dff53816f637c3d41)

**Comment by mattmiklic** [comment]
Thanks, that looks good!

I just noticed one other thing -- can you check the line spacing on the comment text? I'm not sure how it's specified in code, but for 16sp body text, the line height should be 24sp, or 1.5x the font size. It looks a bit compressed in the screenshot.

**Comment by khaykov** [comment]
@mattmiklic Fixed the line height 👍 It was the default height for Body1 style.

[Image from Gyazo](https://gyazo.com/e2d12cd8964c94afb672ba8366a5a445)

**Comment by mattmiklic** [comment]
Looks great, thank you!

**Review by develric — COMMENTED** [review]
Hey @khaykov 👋 , code looks good and UI is really nice ❤️  ! Behaviours worked mostly as expected for me, I have a few notes for your review below, let me know sir 🙇 

- In ReaderCommentTable  I'm getting a null pointer exception in `stmt.bindString(17, comment.getShortUrl())`  when replying directly to a post (maybe we should protect set/get ShortUrl with a `StringUtils.notNullStr`)
- When opening a comment from a deep link, the header area is tappable (as it should be); when tapping on it to open the relevant post, the touch ripple seems like it should arrive to the below horizontal separator

<p align=center>
Screenshot 2021-11-23 at 15 45 39</p>

- Somewhat related to the previous one; when replying to a root comment (so the horizontal separator is just above the comment) the highlighted area goes above the separator; maybe it's ok, I was just expecting the highlight to cover below the separator.

<p align=center>
Screenshot 2021-11-23 at 15 44 33</p>

- When replying we show a loading state; it seems a bit too out of screen to me, wondering if we should place it below the sharing? wdyt? cc @mattmiklic  

<p align=center>
Screenshot 2021-11-23 at 15 44 33</p>

Couple of additional notes that is not for this PR I think:

- I think it was already there before; once you try to reply to a comment when you actually wanted to reply to the post, there seems not to be a straightforward path to come back to reply to the post. What worked for me was to dismiss the keyboard, wonder if we should consider coming back to reply to post if selecting again to reply on an already highlighted post
- We should report the changes from ReaderCommentListActivity to the kotlin ThreadedCommentsFragment (I placed a task reminder in the GH project)

**Comment by khaykov** [comment]
Thanks for the review, @develric !

> In ReaderCommentTable I'm getting a null pointer exception in stmt.bindString(17, comment.getShortUrl()) when replying directly to a post (maybe we should protect set/get ShortUrl with a StringUtils.notNullStr)

Fixed 👍 

> When opening a comment from a deep link, the header area is tappable (as it should be); when tapping on it to open the relevant post, the touch ripple seems like it should arrive to the below horizontal separator



Since the container is very wide, the ripple is also very big. I think the way it now is better :)

> Somewhat related to the previous one; when replying to a root comment (so the horizontal separator is just above the comment) the highlighted area goes above the separator; maybe it's ok, I was just expecting the highlight to cover below the separator.

The separator is a bit tricky in the legacy adapter, so I changed the highlighted area to exclude the separator. 



> I think it was already there before; once you try to reply to a comment when you actually wanted to reply to the post, there seems not to be a straightforward path to come back to reply to the post. What worked for me was to dismiss the keyboard, wonder if we should consider coming back to reply to post if selecting again to reply on an already highlighted post

This is a very good point. If you dismiss the keyboard when in a full-screen reply window, and collapse the window you are stuck with the reply to comment.

> We should report the changes from ReaderCommentListActivity to the kotlin ThreadedCommentsFragment (I placed a task reminder in the GH project)

Done 👍

**Comment by khaykov** [comment]
@develric I totally forgot about new look of highlighted comments, so I just added it :) Also reorganized some padding and margins to make highlighted comments look better, and added bottom padding to the header view to expand area for the ripple.

[Image from Gyazo](https://gyazo.com/b05e8f568add5d77e4c7d8bbd1ac3878)

**Review by develric — COMMENTED** [review]
Thanks for the changes (and managing the highlight style :) ) @khaykov 🙇 

>This is a very good point. If you dismiss the keyboard when in a full-screen reply window, and collapse the window you are stuck with the reply to comment.

Nice catch 👍 , this is another scenario that we should review and that I also found in current releases (worth creating a GH issue for this and the other case I spotted that possibly have a similar cause)

A part the above, everything worked well for me 👍 ! Not sure if this is the last PR we are going to merge by tomorrow, if so, we should include an update to the release notes. Let me know if you'd like to update the release notes now, otherwise I can just approve as it is 🙇 

Update: I think we should add a track event for the share comment action, so maybe we have another PR on the way to add the release notes :)

**Review by develric — APPROVED** [review]
Checked the tracking and the release notes, and LGTM 👍 ! Also created [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/15621) to track what we were discussing in the review comments already. 

This is ready to 🚢 !

**Comment by khaykov** [comment]
Thank you!

**Pull request merged**
