### PR TITLE
[Gutenberg] Disable editor Jetpack-powered features based on Jetpack Features Removal phases

### PR DESCRIPTION
**Pull request by fluiddot**
- Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/5293

## To test

The following features in the editor will be disabled when reaching the phase of disabling Jetpack-powered features:
- Disable Jetpack blocks
  - Remove Jetpack blocks from the block picker
  - Display Jetpack blocks as unsupported
- Disable @-mentions and X-posts features
- Remove Editor’s help support
- Remove Reusable blocks
- Disable Unsupported Block Editor (UBE)

#### Preparation
1. Navigate to App Settings in the WordPress app and open Debug settings.
2. Turn `jp_removal_four` and `jp_removal_new_users` flags off.

#### Check Jetpack blocks
1. Create a post.
2. Tap on _➕ Add Blocks_ button.
3. Scroll down the block list.
4. Observe that the Jetpack blocks are present within the _Jetpack powered section_ section and can be added to the post.
5. Add all Jetpack blocks (`Contact Info`, `Story`, `Layout Grid` blocks).
6. Observe that all Jetpack blocks are displayed and can be edited.
7. Save the post with some Jetpack blocks (this post will be used in other test cases).

#### Check @-mentions and X-posts features
1. Add a Paragraph block.
2. Type the `+` character and observe that the `x-post` sheet is displayed.
**NOTE:** `x-post` feature only works in sites with the [O2 plugin](https://github.com/Automattic/o2) enabled like P2-based sites. **In order to test this, please use a P2-based site.**
3. Type the `@` character and observe that the `@-mentions` sheet is displayed.
4. Observe that in the toolbar the `@` format button is displayed.

#### Check the help's support section
1. Open a post.
2. Tap on the three dots button to open the contextual menu.
3. Observe that there's the option _Help & Support_ that references `Support`, tap on it.
4. Observe that the section _Get support_ is present.

#### Check Reusable blocks
1. Create a reusable block in the web version of the editor (instructions [here](https://wordpress.com/support/wordpress-editor/blocks/reusable-block/#create-a-reusable-block)).
2. Create a post in the app.
3. Tap on _➕ Add Blocks_ button.
4. Observe that in the bottom sheet the "Reusable" tab is shown.
5. Tap on the "Reusable" tab and insert a Reusable block.
6. Observe that the block is displayed.
7. Save the post with at least one Reusable block (this post will be used in other test cases).

#### Check Unsupported Block Editor (UBE)
1. Create a post in the web version of the editor.
2. Add a block that is not supported in the native version like the Table block.
3. Save the post (this post will be used in other test cases).
4. Open the same post in the app.
5. Observe that the block is displayed as unsupported.
6. Tap on the block and try to edit it with UBE.
7. Observe that it can be edited with UBE.

#### Preparation
1. Navigate to App Settings in the WordPress app and open Debug settings.
2. Turn `jp_removal_four` flag on.

**NOTE:** It's recommended that the following test cases are also checked by turning the `jp_removal_new_users` flag on and  `jp_removal_four` flag off in Debug settings.

#### Check Jetpack blocks
1. Open the previous post saved with Jetpack blocks.
2. Observe that the Jetpack blocks are displayed as unsupported.
3. Tap on a Jetpack block and observe that a bottom sheet is displayed indicating that the block is not supported.
4. Tap on _➕ Add Blocks_ button.
5. Scroll down the block list.
6. Observe that the Jetpack blocks are NOT present.

#### Check @-mentions and X-posts features
1. Add a Paragraph block.
2. Type the `+` character and observe that the `x-post` sheet is NOT displayed.
**NOTE:** `x-post` feature only works in sites with the [O2 plugin](https://github.com/Automattic/o2) enabled like P2-based sites. **In order to test this, please use a P2-based site.**
4. Type the `@` character and observe that the `@-mentions` sheet is NOT displayed.
5. Observe that in the toolbar the `@` format button is NOT displayed.

#### Check the help's support section
1. Open a post.
2. Tap on the three dots button to open the contextual menu.
3. Observe that there's the option _Help_ but doesn't reference `Support`, tap on it.
4. Observe that the section _Get support_ is NOT present.

#### Check Reusable blocks
1. Open the previous post saved with Reusable blocks.
2. Observe that the Reusable block is displayed as unsupported.
3. Tap on the block and observe that a bottom sheet is displayed indicating that the block is not supported.
4. Tap on _➕ Add Blocks_ button.
6. Observe that in the bottom sheet the "Reusable" tab is NOT shown.

#### Check Unsupported Block Editor (UBE)
1. Open the previous post saved with unsupported blocks.
2. Observe that the block is displayed as unsupported.
3. Tap on the block and observe that it can't be edited with UBE.

### 3- Editor Jetpack-powered features **ENABLED** in **Jetpack app**

1. Navigate to App Settings in the Jetpack app and open Debug settings.
2. Turn `jp_removal_four` flag on. _This flag should be omitted by the Jetpack app._
3. Repeat the same test cases described in "1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**":
    - Check Jetpack blocks
    - Check @-mentions and X-posts features
    - Check the help's support section
    - Check Reusable blocks
    - Check Unsupported Block Editor (UBE)

## Regression Notes
1. Potential unintended areas of impact
Only the editor should be affected.

14. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

16. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by derekblank** [comment]
Thanks for putting this together @fluiddot! I am capturing my testing experiences below. It seems like a few of the steps are not working correctly for me, mostly around when the Jetpack blocks are present -- I'm curious if this matches your testing experiences. For reference, I checked the web version of each of the sites I was testing on and verified that Jetpack was/was not connected and could see Jetpack blocks in the web version when they were expected based on the testing scenarios. I've color-coded which steps succeeded and which steps failed for me. Let me know if I can provide more info:

1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**:
1. Create a post. 🟢 
2. Tap on _➕ Add Blocks_ button. 🟢 
3. Scroll down the block list. 🟢 
3. Observe that the Jetpack blocks are present within the _Jetpack powered section_ section and can be added to the post. 🔴 
4. Add some Jetpack blocks. 🔴 
5. Add a Paragraph block. 🟢 
6. Type the `+` character and observe that the `x-post` sheet is displayed. 🔴 
7. Type the `@` character and observe that the `@-mentions` sheet is displayed. 🟢 
8. Observe that in the toolbar the `@` format button is displayed. 🟢 
9. Tap on the three dots button to open the contextual menu. 🟢 
10. Observe that there's the option _Help & Support_ that references `Support`, tap on it. 🟢 
11. Observe that the section _Get support_ is present. 🟢 
12. Save the post with some Jetpack blocks and close the editor. 🟡  (no Jetpack blocks present in Block list)

2 - Editor Jetpack-powered features **DISABLED** in **WordPress app**:
1. Navigate to App Settings and open debug settings. 🟢 
2. Turn `jp_removal_four` flag on. 🟢 
3. Open the previous post saved with Jetpack blocks. ⚪  (see dependent steps on the above test scenario)
4. Observe that the Jetpack blocks are displayed as unsupported. ⚪ 
5. Tap on _➕ Add Blocks_ button. 🟢 
6. Scroll down the block list. 🟢 
7. Observe that the Jetpack blocks are NOT present. 🟢 
6. Add a Paragraph block. 🟢 
7. Type the `+` character and observe that the `x-post` sheet is NOT displayed. 🟢 
8. Type the `@` character and observe that the `@-mentions` sheet is NOT displayed. 🟢 
9. Observe that in the toolbar the `@` format button is NOT displayed. 🟢 
10. Tap on the three dots button to open the contextual menu. 🟢 
11. Observe that there's the option _Help_ but doesn't reference `Support`, tap on it. 🟢 
12. Observe that the section _Get support_ is NOT present. 🟢 

3- Editor Jetpack-powered features **ENABLED** in **Jetpack app**:
1. Navigate to App Settings and open debug settings. 🟢 
2. Turn `jp_removal_four` flag on. _This flag should be omitted by the Jetpack app._ 🟢 
3. Create a post. 🟢 
4. Tap on _➕ Add Blocks_ button. 🟢 
5. Scroll down the block list. 🟢 
6. Observe that the Jetpack blocks are present within the _Jetpack powered section_ section and can be added to the post. 🔴 
7. Add a Paragraph block. 🟢 
8. Type the `+` character and observe that the `x-post` sheet is displayed. 🟢 
9. Type the `@` character and observe that the `@-mentions` sheet is displayed. 🟢 
10. Observe that in the toolbar the `@` format button is displayed. 🟢 
11. Tap on the three dots button to open the contextual menu. 🟢 
12. Observe that there's the option _Help & Support_ that references `Support`, tap on it. 🟢 
13. Observe that the section _Get support_ is present. 🟢

**Comment by fluiddot** [comment]
Thank you @derekblank for testing the changes 🙇 ! I went through the testing instructions again to check the steps that failed for you:

> 1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**:
>> 4. Observe that the Jetpack blocks are present within the Jetpack powered section section and can be added to the post. 🔴
>> 5. Add some Jetpack blocks. 🔴

Interesting, I can see the Jetpack blocks in the block inserter menu. Let me know if you could check the following points to identify what's different between our test sessions:
- Was the `jp_removal_four` flag disabled? (I'm going to update the test instructions to make clear that this flag has to be disabled, which should be by default).
- Did you encounter this issue when testing on a WPCOM site or a self-hosted site? If the latter, was it connected to Jetpack?
- Could you elaborate on what failed? Was that you couldn't see the Jetpack powered section or that some Jetpack blocks weren't present?

> 1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**:
>> 7. Type the + character and observe that the x-post sheet is displayed. 🔴

I should have highlighted that x-post feature is only available on sites with the [O2 plugin](https://github.com/Automattic/o2) enabled like P2-based sites. Could you check this step again on a P2-based site?

> 1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**:
>> 13. Save the post with some Jetpack blocks and close the editor. 🟡 (no Jetpack blocks present in Block list)

It's not clear to me what happened in this step, was it that you couldn't save Jetpack blocks because there weren't available?

> 3- Editor Jetpack-powered features ENABLED in Jetpack app:
>> 6. Observe that the Jetpack blocks are present within the Jetpack powered section section and can be added to the post. 🔴

I understand this could be caused by a similar cause like the one you pointed in `1 - Editor Jetpack-powered features **ENABLED** in **WordPress app*`, is it accurate?

It's definitely not expected that in the Jetpack app you can't see the Jetpack blocks. Could you share more info about the type of site you used for testing? Thanks!

**Comment by zwarm** [comment]
@fluiddot I ran across an exception while trying to test. I could not reproduce it, but you might find the following helpful. After the exception, the app locked up and I had to swipe it closed. I could not recreate. 

Pixel 5 Android 13

- Create a post.
- Tap on ➕ Add Blocks button.
- Scroll down the block list.
- Observe that the Jetpack blocks are present within the Jetpack powered section section and can be added to the post.
- Added the "contact" info Jetpack block


Exception | Log
-- | --
 |

**Comment by fluiddot** [comment]
> @fluiddot I ran across an exception while trying to test. I could not reproduce it, but you might find the following helpful. After the exception, the app locked up and I had to swipe it closed. I could not recreate.

Thanks for reporting this @zwarm 🙇. I'll take a look and try to reproduce it locally.

**Comment by fluiddot** [comment]
@zwarm I tried to reproduce the `NullPointerException` crash but it's quite hard to get it constantly. The only way I found where it crashes more often is by having several Contact Info blocks in a post and closing and opening the editor multiple times until it crashes.

However, as far as I investigated, this crash is not new as I found reports in previous versions. Besides, I found a related issue (`https://github.com/facebook/react-native/issues/17530`) reported in the React Native repository with the same error:

```java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference```

The issue seems solved but per recent comments, I understand that is still happening. Plus, I couldn't find information about how to reproduce it or a way to really solve it. Seems that it might have to do with setting transparency in the `EditText` component but I couldn't relate this to the editor so far.

Being this said, **I think we can omit this error for the PR review**, I'll open another GitHub issue with this information as a follow-up. Thanks!

**Comment by Mina012015** [comment]
Ok

في الأربعاء، ١٤ ديسمبر، ٢٠٢٢ ٢:٤٦ م Carlos Garcia ***@***.***>
كتب:

**Comment by derekblank** [comment]
> Interesting, I can see the Jetpack blocks in the block inserter menu. Let me know if you could check the following points to identify what's different between our test sessions:
> 
> * Was the `jp_removal_four` flag disabled? (I'm going to update the test instructions to make clear that this flag has to be disabled, which should be by default).
> * Did you encounter this issue when testing on a WPCOM site or a self-hosted site? If the latter, was it connected to Jetpack?
> * Could you elaborate on what failed? Was that you couldn't see the Jetpack powered section or that some Jetpack blocks weren't present?

After re-reading this feedback and exploring the Debug menu more, I realized that after disabling the `jp_removal_four` feature flag, I did not know to scroll and select "Restart the App". To answer the other questions, I did encounter this on both a WPCOM and a self-hosted site with Jetpack connected. In both cases, I believe the issue was I did not restart the app after disabling the feature flag. When re-testing after doing this, I was able to `Observe that the Jetpack blocks are present within the Jetpack powered section section and can be added to the post. 🟢 ` and `Add some Jetpack blocks. 🟢 `

> `Save the post with some Jetpack blocks and close the editor. 🟡 (no Jetpack blocks present in Block list)`
> It's not clear to me what happened in this step, was it that you couldn't save Jetpack blocks because there weren't available?

Correct, initially I was simply unable to complete this step as in my first testing setup, there were no Jetpack blocks present to test, so I marked it 🟡 . After retesting (from the feedback above), this step is now also green. 🟢 

> `Observe that the Jetpack blocks are present within the Jetpack powered section section and can be added to the post. 🔴`
> I understand this could be caused by a similar cause like the one you pointed in 1 - Editor Jetpack-powered features **ENABLED** in **WordPress app*, is it accurate?

Correct, same issue as above. This step is now green after retesting. 🟢 

> `Type the + character and observe that the x-post sheet is displayed. 🔴`
> I should have highlighted that x-post feature is only available on sites with the [O2 plugin](https://github.com/Automattic/o2#installation) enabled like P2-based sites. Could you check this step again on a P2-based site?

After retesting, this is the only remaining 🔴 / 🟡  for me. I am having trouble installing the O2 plugin based on the [documentation](https://github.com/Automattic/o2#installation) on my WPCOM and self-hosted sites. Based on internal references, it appears the p2-breathe theme is deprecated, which is the blocker. However, when using a draft post on P2-based site where I know O2 is already installed, I am able to succeed on this step, which I think should be sufficient to mark all of these steps as green. 🟢 WDYT?

**Comment by fluiddot** [comment]
Thanks @derekblank for re-testing this PR, I really appreciate it 🙇.

I'd like to note that following [this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/19691#discussion_r1047907000), **I'd need to update this PR to include the flag `newUsers` to the condition for determining if the Jetpack-powered features should be disabled**. Once I execute this change I'll let you know in case you could perform a last review. Thanks!

> After re-reading this feedback and exploring the Debug menu more, I realized that after disabling the jp_removal_four feature flag, I did not know to scroll and select "Restart the App"

Oh, that's interesting. In my case, I didn't need to restart the app after enabling/disabling the flags 🤔. In any case, I'm glad that doing that and after re-testing, most of the steps succeeded. In relation to this, would you mind updating [your comment](https://github.com/wordpress-mobile/WordPress-Android/pull/17587#issuecomment-1347880875) or posting another one to reflect the latest status of your testing? Thanks!

> After retesting, this is the only remaining 🔴 / 🟡 for me. I am having trouble installing the O2 plugin based on the [documentation](https://github.com/Automattic/o2#installation) on my WPCOM and self-hosted sites. Based on internal references, it appears the p2-breathe theme is deprecated, which is the blocker. However, when using a draft post on P2-based site where I know O2 is already installed, I am able to succeed on this step, which I think should be sufficient to mark all of these steps as green. 🟢 WDYT?

To be honest, I simply tested this by creating a post on a P2-based site, any of them should work. Therefore, if you managed to make this work on that type of site, I agree it's enough to mark this step as succeeded 🟢 .

**Comment by derekblank** [comment]
After retesting the latest build, the following steps are all green:

1 - Editor Jetpack-powered features **ENABLED** in **WordPress app**:
1. Create a post. 🟢 
2. Tap on _➕ Add Blocks_ button. 🟢 
3. Scroll down the block list. 🟢 
3. Observe that the Jetpack blocks are present within the _Jetpack powered section_ section and can be added to the post. 🟢 
4. Add some Jetpack blocks. 🟢 
5. Add a Paragraph block. 🟢 
6. Type the `+` character and observe that the `x-post` sheet is displayed. 🟢 
7. Type the `@` character and observe that the `@-mentions` sheet is displayed. 🟢 
8. Observe that in the toolbar the `@` format button is displayed. 🟢 
9. Tap on the three dots button to open the contextual menu. 🟢 
10. Observe that there's the option _Help & Support_ that references `Support`, tap on it. 🟢 
11. Observe that the section _Get support_ is present. 🟢 
12. Save the post with some Jetpack blocks and close the editor. 🟢

2 - Editor Jetpack-powered features **DISABLED** in **WordPress app**:
1. Navigate to App Settings and open debug settings. 🟢 
2. Turn `jp_removal_four` flag on. 🟢 
3. Open the previous post saved with Jetpack blocks. 🟢 
4. Observe that the Jetpack blocks are displayed as unsupported. 🟢 
5. Tap on _➕ Add Blocks_ button. 🟢 
6. Scroll down the block list. 🟢 
7. Observe that the Jetpack blocks are NOT present. 🟢 
6. Add a Paragraph block. 🟢 
7. Type the `+` character and observe that the `x-post` sheet is NOT displayed. 🟢 
8. Type the `@` character and observe that the `@-mentions` sheet is NOT displayed. 🟢 
9. Observe that in the toolbar the `@` format button is NOT displayed. 🟢 
10. Tap on the three dots button to open the contextual menu. 🟢 
11. Observe that there's the option _Help_ but doesn't reference `Support`, tap on it. 🟢 
12. Observe that the section _Get support_ is NOT present. 🟢 

3- Editor Jetpack-powered features **ENABLED** in **Jetpack app**:
1. Navigate to App Settings and open debug settings. 🟢 
2. Turn `jp_removal_four` flag on. _This flag should be omitted by the Jetpack app._ 🟢 
3. Create a post. 🟢 
4. Tap on _➕ Add Blocks_ button. 🟢 
5. Scroll down the block list. 🟢 
6. Observe that the Jetpack blocks are present within the _Jetpack powered section_ section and can be added to the post. 🟢 
7. Add a Paragraph block. 🟢 
8. Type the `+` character and observe that the `x-post` sheet is displayed. 🟢 
9. Type the `@` character and observe that the `@-mentions` sheet is displayed. 🟢 
10. Observe that in the toolbar the `@` format button is displayed. 🟢 
11. Tap on the three dots button to open the contextual menu. 🟢 
12. Observe that there's the option _Help & Support_ that references `Support`, tap on it. 🟢 
13. Observe that the section _Get support_ is present. 🟢

**Comment by derekblank** [comment]
> I'd like to note that following [this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/19691#discussion_r1047907000), **I'd need to update this PR to include the flag `newUsers` to the condition for determining if the Jetpack-powered features should be disabled**. Once I execute this change I'll let you know in case you could perform a last review. Thanks!

Makes sense, I will keep an eye out and retest when ready.

> In relation to this, would you mind updating https://github.com/wordpress-mobile/WordPress-Android/pull/17587#issuecomment-1347880875 or posting another one to reflect the latest status of your testing? Thanks!

I've posted a [new comment](https://github.com/wordpress-mobile/WordPress-Android/pull/17587#issuecomment-1354273342) clarifying that all steps are green from my latest testing. I think preserving the status of the original testing comment could possibly help in the future (instead of editing it). 👍

> To be honest, I simply tested this by creating a post on a P2-based site, any of them should work. Therefore, if you managed to make this work on that type of site, I agree it's enough to mark this step as succeeded 🟢 .

Yep, I agree, and was able to retest this successfully. I am happy to review this PR as Approved, unless you'd like to await for the `newUser` changes [mentioned above](https://github.com/wordpress-mobile/WordPress-iOS/pull/19691#discussion_r1047907000) to be retested -- let me know what you think. 🙇

**Comment by fluiddot** [comment]
> I am happy to review this PR as Approved, unless you'd like to await for the newUser changes https://github.com/wordpress-mobile/WordPress-iOS/pull/19691#discussion_r1047907000 to be retested -- let me know what you think. 🙇

@derekblank I'd rather wait for all changes to be executed before heading to the approval, thanks!

**Comment by fluiddot** [comment]
> > I am happy to review this PR as Approved, unless you'd like to await for the newUser changes [wordpress-mobile/WordPress-iOS#19691 (comment)](https://github.com/wordpress-mobile/WordPress-iOS/pull/19691#discussion_r1047907000) to be retested -- let me know what you think. 🙇
> 
> @derekblank I'd rather wait for all changes to be executed before heading to the approval, thanks!

All changes applied. The PR is ready for another review, thanks 🙇 !

**Review by derekblank — APPROVED** [review]
LGTM! 🚀

**Comment by geriux** [comment]
Hey there @fluiddot 👋 Quick question, is the Add new `Story post` button going to disabled in another PR? It is being shown using the WordPress app with the `jp_removal_four` and `jp_removal_new_users` flags enabled.

**Review by geriux — APPROVED** [review]
Test cases worked correctly ✅ I only left one question in https://github.com/wordpress-mobile/WordPress-Android/pull/17587#issuecomment-1367156478

**Comment by fluiddot** [comment]
> Hey there @fluiddot 👋 Quick question, is the Add new `Story post` button going to disabled in another PR? It is being shown using the WordPress app with the `jp_removal_four` and `jp_removal_new_users` flags enabled.

@geriux Yes, the Story post button is going to also be disabled but that will be done in another PR. In this one, I only wanted to disable the editor features.

**Pull request merged**
