### PR TITLE
My Site Dashboard - Phase 1 - Refactor use of Repository in favor of Prefs for Selected Site

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #15191

This PR mainly refactors all usages of `AppPrefs.get/setSelectedSite(...)` to go through the `SelectedSiteRepository` and through that change to make this repository the source of truth for when a selected site is being accessed.

Also, as part of this PR, the below occurred:
- Documentation was added to `AppPrefs.get/setSelectedSite(...)` method calls so that access to a selected site becomes explicitly prohibited and only available through the `SelectedSiteRepository`.
- All `id` naming conventions, mainly the local id ones, for when a selected site is accessed, were renamed to `siteLocalId`.
- Two new FAQ questions was added based on both those main changes:
  - Should I use `AppPrefs` or `SelectedSiteRepository` as the source of truth on a selected site?
  - Should I use `id`, `siteId`, `siteLocalId`, `siteRemoteId` or any other naming convention?

-----

To test:
- Smoke test the `Login` screen. Focus on site selection, site creation and the quick start functionality.
- Smoke test the `My Site` screen. Focus on site selection, site creation and the quick start functionality.
- Smoke test the `Stats` screen. Just verify that everything works as expected and there are no surprises.
- Smoke the the `Reader` screen. Just verify that everything works as expected and there are no surprises.
- Smoke test the `Media Upload` functionality. Just verify that everything works as expected and there are no surprises.

-----

Merge Instructions for @ashiagr :
- ~~Wait for `18.1` code freeze, cut and for the `release/18.1` branch to happen.~~ ✅ 
- ~~Remove the `[Status] Not Ready for Merge` label.~~ ✅ 
- ~~Remove the `(DO NOT MERGE)` suffix from the title.~~ ✅ 
- ~~Merge this PR.~~ ✅ 

-----

## Regression Notes
1. Potential unintended areas of impact

The `Login`, `My Site`, `Stats`, `Reader` and/or `Media Upload` logic might be somehow affected by all the changes in this PR since there has been some updates to all that.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @ashiagr @zwarm !

I have added you both on this PR so that it gets more code review exposure than usual. This is done because this PR has the potential of breaking changes. 🤞 

As such, could you please review this PR, commit-by-commit, but more importantly smoke tests the screens and functionality that I listed under the `To test` section? 🙏 

If we manage to merge this PR into `develop` it will really help us alleviate the pain of having to choose between `AppPrefs` and the `SelectedSiteRepository` when working with a `Selected Site`. I think this will be of great help to us while we progress with the `My Site Dashboard`. Many thanks for your continuous support! 🙇

**Review by ashiagr — APPROVED** [review]
Great job Petros! 

I smoke tested the screens and also reviewed code commit by commit. Everything seems to be in order and the code looks so much better with the use of the repository for the selected site wherever possible 🙌.

I also tested Quick Start (in progress status) by upgrading the app from `17.9.1` to this branch and it got displayed properly both in `MySiteFragment` and `ImprovedMySiteFragment`.

Kudos for all the renaming stuff and for adding the 2 new faqs in c8ca728!

Regarding your note for commit 2e60777

> two possible bugs where fixed due
to the fact that the 'WPMainActivity.onSiteChanged(...)' and the
'WPMainActivity.refreshCurrentSelectedSiteAfterEditorChanges(...)'
methods were not updating the 'AppPrefs.setSelectedSite(...)' when that
was happening on the repository level, through
'SelectedSiteRepository.updateSite(...)'.

they appear as bugs to me as well. Ideally, we would like to have `AppPrefs` and the repository in sync for the selected site. I'd vote for keeping your changes.

As a precautionary measure, since the changes affect several screens, need just one confirmation regarding the merge: do you want them to be merged
1.  in this sprint (`18.1`) with the changes going to beta on the coming Monday and the testing is done while being on beta
2.  the next one (`18.2`) with changes in `develop` after Monday and testing is first done on `develop` as a result of different ongoing features?

**Comment by ParaskP7** [comment]
👋 @ashiagr !

Thanks so much for this code review! 🙏 

> I smoke tested the screens and also reviewed code commit by commit. Everything seems to be in order and the code looks so much better with the use of the repository for the selected site wherever possible 🙌.

It is great to hear that everything worked as expected, thanks for going through all that trouble! 🙏  🙌 

> I also tested Quick Start (in progress status) by upgrading the app from 17.9.1 to this branch and it got displayed properly both in MySiteFragment and ImprovedMySiteFragment.

Brilliant, thanks for doing that! 🙏 🥇 

> Kudos for all the renaming stuff and for adding the 2 new faqs in c8ca728!

🙏 😊

> Regarding your note for commit 2e60777 they appear as bugs to me as well. Ideally, we would like to have AppPrefs and the repository in sync for the selected site. I'd vote for keeping your changes.

Exactly, I am pretty confident that those are bugs are well, but you never know... 🤷  Thanks so much for double checking on it and for actually reading through the description! 🙏 🥇 

> As a precautionary measure, since the changes affect several screens, need just one confirmation regarding the merge: do you want them to be merged
> - in this sprint (18.1) with the changes going to beta on the coming Monday and the testing is done while being on beta
> - the next one (18.2) with changes in develop after Monday and testing is first done on develop as a result of different ongoing features?

Such a great point Ashita, I actually think that it would be wiser to merge this PR after this release (`18.1`) and include all these changes for the next release (`18.2`), along with removing the `MySiteFragment` and all the clean-up that will be happening afterwards. I actually already updated the milestone for this PR to `18.2` and will mark it as `DO NOT MERGE` for now.

PS: The only drawback would be that:
- This PR will need to be kept up-to-date with `develop` till that point and this might end up taking some time since the change in this PR affect the whole codebase.
- I will not be here to update and the merge this PR when the time comes next Monday, since I will be on vacation. Can you take this over Ashita?

**Comment by ashiagr** [comment]
Thanks for updating the milestone! 

> I will not be here to update and the merge this PR when the time comes next Monday, since I will be on vacation. Can you take this over Ashita?

I'll be happy to help! Maybe we can merge `develop` with this PR once tomorrow before you go for vacation and then I can take care of any conflicts due to changes on Friday and Monday so that there are not too many conflicts by then.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> I'll be happy to help! Maybe we can merge develop with this PR once tomorrow before you go for vacation and then I can take care of any conflicts due to changes on Friday and Monday so that there are not too many conflicts by then.

Thank you! Yes, that's an excellent idea, I'll make sure to update this PR tomorrow by the end of my day, just before I log off, thanks for pairing with me on that. 🤝 🙇

**Review by zwarm — APPROVED** [review]
Thanks for the all hard work @ParaskP7 

I smoked tested as requested - with and without the `MySiteImprovementsFeatureConfig` flag enabled. I didn't encounter any issues with the QSP or QS steps. I spent a fair amount of time going from site-to-site and navigating throughout the app. 

Nice use of commits! Very easy to follow all the changes, including the renaming. 👍 

Since we already discussed implementation this morning, I won't add any extra comments about it - other than - Post next freeze. 

Excellent work. 🚀 

You already know how I feel about the FAQ's ❤️

**Comment by ParaskP7** [comment]
👋 @zwarm !

Thanks so much for taking the time to code review this PR, I really appreciate that! 🙇 

> I smoked tested as requested - with and without the MySiteImprovementsFeatureConfig flag enabled. I didn't encounter any issues with the QSP or QS steps. I spent a fair amount of time going from site-to-site and navigating throughout the app.

This is so good to hear, thanks for all your testing! 🤞 

> Nice use of commits! Very easy to follow all the changes, including the renaming. 👍

❤️ 

> Since we already discussed implementation this morning, I won't add any extra comments about it - other than - Post next freeze.

💪 

> You already know how I feel about the FAQ's ❤️

All the ❤️s go to you for suggesting it in the first place, thank YOU! 🙇

**Comment by ashiagr** [comment]
>  include all these changes for the next release (18.2),

As discussed, since `18.1` code-freeze is complete, merging this PR with `develop` now.

**Pull request merged**
