### PR TITLE
Moderate comment to SPAM via REST Fixes #1341

### LINKED ISSUE #1341: unable to remove spam from comments listing
using Wordpress for Android v2.8 on a Galaxy S4.
Self-hosted Wordpress

In my listing of comments on my site, there are some 20 spam comments, listed as "Pending". However, trying to remove them fails, and I will explain why.

I had them listed in the app, but then went to the blog with my browser and removed them in Wordpress instead. Ever since, I cannot remove them from the app. When I try to either mark them spam or trash them, I get "an error occurred while moderating" and the comment is not removed from the listing. The log shows that there is an error 404 on the request.

### PR DESCRIPTION
**Pull request by hypest**
The XMLRPC API causes a 500 fault code when the comment under moderation (SPAM) is already marked as SPAM from wp-admin. The REST API doesn't seen to have the same problem and is actually already used in the iOS app.

Could use some feedback on this one. Care to have a look @roundhill ? Cheers!

### CODE REVIEW

**Comment by nbradbury** [comment]
A couple of issues here:

1. The REST call won't work with non-Jetpack self-hosted blogs, so we'll either need to stick with XMLRPC here or detect when the blog uses Jetpack or wp.com and only then use the REST call.
2. When you do use the REST call, there's no need to wrap it in a `thread` since `moderateCommentRestApi` relies on Volley (which does the network call in the background).

**Comment by hypest** [comment]
Hey @nbradbury , feel free to review this take. Cheers!

**Comment by nbradbury** [comment]
@hypest The logic here looks good and worked during my tests. Just a couple NPE-avoidance tweaks and I'm good to merge. Nice work!

**Comment by hypest** [comment]
Hey @nbradbury, I've added a couple of commits (a NPE check and a couple of ApiHelper tests). Notice that I didn't add a NPE check for `contentHash.get("status")` since `CommentStatus.fromString()` properly handles the `null` anyway. Feel free to review. Cheers!

**Comment by nbradbury** [comment]
> Notice that I didn't add a NPE check for contentHash.get("status") since CommentStatus.fromString() properly handles the null anyway.

The problem here is with `contentHash.get("status").toString()`. Since `contentHash.get("status")` can return null, calling `.toString()` on it could result in an NPE.

**Comment by hypest** [comment]
> The problem here is with contentHash.get("status").toString()
Oh, right!

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
