### PR TITLE
Fixed issue #4327 : Apostrophe displayed incorrectly when replying fr…

### LINKED ISSUE #4327: Apostrophe displayed incorrectly when replying from a notification
### Expected behavior

When replying to a comment notification, if you leave the same comment twice, a message pops up that should say "_Duplicate comment detected; It looks as through you've already said that!_"

### Actual behavior
The message doesn't render the apostrophe correctly, and actually reads as "_Duplicate comment detected; It looks as through you#8217;ve already said that!_

This only happens when replying from the notification. Replying from the Reader displays a more basic "_Couldn't post your comment_" popup.

screenshot_20160630-081817

### Steps to reproduce the behavior

1. Open the app and tap the notifications icon
2. Scroll down to a comment notification, and open it
3. Use the 'Reply to [Commenter Name] field to submit a comment
4. Once the comment is submitted, try saying the same thing again to trigger the popup

### PR DESCRIPTION
**Pull request by nawabhussain**
Fixes #4327

### CODE REVIEW

**Comment by hypest** [comment]
Confirmed the issue fixed with this PR @nawabhussain , thanks!

I'm about to merge this but I'd like to raise a minor issue as well: even though the fix commit is a "one-liner", the changeset has quite a few of codestyle changes. Allow me to suggest to keep these types of change in separate commits in the spirit of easing the review passes. Let me know if I need to elaborate on this. Thanks!

**Comment by hypest** [comment]
Let's get this merged and keep 'em coming :)

**Comment by nawabhussain** [comment]
@hypest Please do. It will me help me understand better .

**Comment by hypest** [comment]
OK, so, in this case, I'd say that the single commit has at least 3 kind of changes that are different in nature:

1. Code style changes (empty lines removed or added, spacing added after parenthesis, excess spaces removed, indentation changes, constants moved to the top, setter moved below the getter)
2. Removal of unused imports
3. [Functional changes](https://github.com/wordpress-mobile/WordPress-Android/pull/4547/files#diff-204e59c94fe33997c26fd2c5350090f3R831) (string message processed through `StringEscapeUtils.unescapeHtml` in order to display in the Toast) 

From those, only the third point is related to the original issue fix and this PR would be perfectly acceptable even if it was introducing that one-liner alone.

Points 1 and 2 are valid changes as well (albeit not related to the issue at hand) and in so were good to merge! Those could be in a _dedicated commit_ though with their own commit message (perhaps something like "Code style fixes and imports cleanup"). Grouped in a separate commit can help the reviewer(s) walk through the changes in a commit-by-commit fashion, if they wish to, focusing on the important ones as they go along.

We're not very strict with this "splitting" though and that's why it was not a blocker for merging your PR. My remark has to do only with setting it up for easier review :wink: 

Here's a article with more info on the reasoning behind keeping the commits as _atomic_ as possible: https://seesparkbox.com/foundry/atomic_commits_with_git

Hope it's more clear now and again, thanks for contributing! :+1:

**Comment by nawabhussain** [comment]
@hypest Thanks for clearing that out . I will try and follow it. Cheers

**Pull request merged**
