### PR TITLE
Update gutenberg-mobile ref to enable edit button over image-block

### LINKED ISSUE #11147: Enable "Edit Image" button in Gutenberg-mobile for Android
Enable "Edit Image" button in Gutenberg-mobile for Android and connect it to the edit media Activity.

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #11147

This PR updates `gutenberg-mobile` ref to enable edit button over image-block.

Corresponding `gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2062.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Thanks a lot for reviewing @etoledom !

@oguzkocer is it ok to merge this PR to develop? CircleCI tests are failing but don't think it is because of this PR. Can you please confirm?

**Comment by oguzkocer** [comment]
> @oguzkocer is it ok to merge this PR to develop? CircleCI tests are failing but don't think it is because of this PR.

@ashiagr I restarted the build and everything seems to be fine. When this happens next time in a PR and you think it's false failure, consider following the steps below:

1. Check CircleCI error and verify that it seems to be a hiccup rather than an actual issue
2. Restart CircleCI once or twice to see if it resolves the issue. Consider giving CircleCI some time in between runs, especially if it looks like CircleCI is choking and not finding something that should be there etc.
3. Run the tests locally and verify that it works as expected
4. If all else fails, ping me or anyone else from platform 9 for a second look. You can also ask the reviewer(s) for help.

When I get pinged I'll be following the same steps.

---

> Btw I can't merge because required statuses must pass before merging.

Yeap and you definitely shouldn't. Please ping us on Slack if you need any urgent help to merge a PR. We made the connected tests optional and the other tasks very rarely fail, so this shouldn't cause any friction.

---

Separate from this PR, while trying to figure out what might be wrong with this PR I checked the linked Gutenberg PRs. The process might be different in Gutenberg and if it is, please feel free to follow the process there, but otherwise I suggest not merging a PR after making changes to it. (except for some edge cases*) In general, we should give the reviewers a chance to re-check the PR after a new commit and that includes especially merges from another PR.

\* An example edge case would be a change to a `txt` file that can't affect the build. Or updating the FluxC version from a hash to a tag where the tag points to the exact same commit etc.

Hope it helps!

**Comment by ashiagr** [comment]
Thanks for a detailed explanation @oguzkocer , it definitely helps 🙏. I'll try to follow your advice.

Just one question:
> Restart CircleCI once or twice to see if it resolves the issue.

Earlier I could rerun CircleCI workflow, I used to try it when tests failed but recently I noticed I am not authorised to do so. 

circleci

What's the recommended way to trigger CircleCI restart?

**Comment by oguzkocer** [comment]
@ashiagr Are you sure you're logged in? I am not sure how the accounts are setup on CircleCI, but I think just logging in with your Github account is enough to restart builds. 
/cc @jkmassel

**Comment by ashiagr** [comment]
You're right @oguzkocer , didn't realise when I got logged out of CircleCI. Everything sorted now. Thank you!

@etoledom , can we finally merge this PR?

**Comment by ashiagr** [comment]
Thanks for confirming to merge on slack @etoledom !

**Pull request merged**
