### PR TITLE
GitHub templates

### PR DESCRIPTION
**Pull request by kwonye**
Adds simple templates for PRs and issues

Mirrors wordpress-mobile/WordPress-iOS#4867 so any changes here should be made there for consistency

### CODE REVIEW

**Comment by tonyr59h** [comment]
I think we should add a note to the PR template that mentions our code style [guidelines](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CODESTYLE.md).

Maybe something like
```
** Delete before submission **
If you haven't already, please verify that your contribution adheres to our code style [guidelines](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CODESTYLE.md).
```

**Comment by tonyr59h** [comment]
cc @maxme @aforcier @sendhil

**Comment by tonyr59h** [comment]
For the issue template, at least for Android (but possibly iOS), we should ask for the device and OS version.

```
##### Tested on [device], Android [version]
```

**Comment by maxme** [comment]
Is this some kind of GitHub integration?

**Comment by maxme** [comment]
> Is this some kind of GitHub integration?

Looks like it is: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by tonyr59h** [comment]
[Yup](https://github.com/blog/2111-issue-and-pull-request-templates) :)

**Comment by maxme** [comment]
> I think we should add a note to the PR template that mentions our code style guidelines.

We're opening 99% of the PRs, I think we shouldn't add that.

**Comment by maxme** [comment]
And it's a GitHub feature :)

screen shot 2016-02-25 at 13 32 14

**Comment by tonyr59h** [comment]
> We're opening 99% of the PRs, I think we shouldn't add that.

:+1:

**Comment by kwonye** [comment]
> For the issue template, at least for Android (but possibly iOS), we should ask for the device and OS version.

Added for both Android and iOS

**Pull request merged**
