### PR TITLE
Integrate gutenberg-mobile release 1.72.1

### PR DESCRIPTION
**Pull request by fluiddot**
## Description
This PR incorporates the 1.72.1 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4714

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
@mchowning  I'm afraid this PR was originally generated pointing to `trunk` instead of `release/19.5` branch, my bad. The release script didn't ask me to set the target branch (probably it detected any input command while it was running and skipped it instantly), so it took `trunk` as default 🤦.

I've rebased the branch on the release branch and forced pushed the changes, now it should be ready to review.

**Review by geriux — APPROVED** [review]
LGTM, we just need to update to the release tag and it's ready to merge 👍

**Comment by fluiddot** [comment]
> LGTM, we just need to update to the release tag and it's ready to merge 👍

The Gutenberg Mobile ref now points to the release tag ([reference](https://github.com/wordpress-mobile/WordPress-Android/pull/16211/commits/36a8ca5029532dded7795d03049e330e37c857a5)).

**Comment by AliSoftware** [comment]
Shipped as part of WPAndroid 19.5-rc-4 beta 🎉

**Pull request merged**
