### PR TITLE
Dashboard Personalization: Recent Activity Log Card

### PR DESCRIPTION
**Pull request by zwarm**
Parent #18948 

This is the first step in a series of changes aimed at adding a "more menu" to the recent Activity Log dashboard card. 

Menu Closed | Menu Open
--|--
Alt desc | Alt desc

**Included in this PR are the following:**
- Added "more menu" to the recent activity log dashboard card
- Handle More Menu item clicks
- Removed the "footer link" portion of the card
- Removed tracking related to footer link
- Removed navigation events related to footer link
- Updated unit and instrumentation tests 

**Not included is this PR**: 
- Tracking events for the menu item taps 
- Logic to hide the card when "hide this" is tapped

**Note**: No dashboard cards retain open menus upon rotation 

**To test:**
- Install and login to the app
- Select a site in which you have access to Activity Log
- Tap My Site
- Scroll to the Recent Activity card
- ✅ Verify the card does not contain a footer 
- ✅ Verify the card has a vertical more menu
- Tap on the More Menu 
- ✅ Verify the more menu is expanded
- Tap on the All activity menu item
- ✅ Verify you are navigated to the Activity Log view

## Regression Notes
1. Potential unintended areas of impact
The activity log card does not work properly

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Updated automated and unit tests

3. What automated tests I added (or what prevented me from doing so)
MySiteViewModelTest, CardsBuilderTest, CardsShownTrackerTest, ActivityCardBuilderTest

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [X] Portrait and landscape orientations.
- [X] Light and dark modes.
- [X] Fonts: Larger, smaller and bold text.
- [X] High contrast.
- [X] Talkback.
- [X] Languages with large words or with letters/accents not frequently used in English.
- [X] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [X] Large and small screen sizes. (Tablet and smaller phones)
- [X] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
Hey @zwarm 

I have tested the PR according to the instructions. Everything looks good to me.

Do you think it would be good to have a click on the card as well ?

**Comment by zwarm** [comment]
> Do you think it would be good to have a click on the card as well ?

@AjeshRPai 
Not sure, is there sufficient tap space for that? If I am not mistaken, I believe iOS supports taps on the header with navigation to the full feature

**Comment by AjeshRPai** [comment]
When I checked, I felt that there is enough space for us to support the click on the card.I think we can check the no of click events on the card on IOS + ask @osullivanchris about his opinion on providing a click on the card. 🤔

**Comment by osullivanchris** [comment]
With cards that have only one link, I wouldn't be worried about the whole card being tappable. In these examples, it would be beneficial.
Screenshot 2023-08-21 at 10 38 37

But in cards that have nested objects with different tap targets, could having the whole card tapabble end up with some accidental clicks? Where the user wants to access a particular nested object, but inadvertently taps the 'all' link? It would depend a lot how the spacings/paddings are defined. E.g. are the right and left margins of the rows part of the row or the card? same for the bottom padding?

image

For that reason, having the header area tappable seems safer. But could be the whole top area of the header, not just the text. 
Screenshot 2023-08-21 at 10 42 55

**Pull request merged**
