### PR TITLE
Jetpack App (Basics): Merge Jetpack App Branch (Into Develop)

### LINKED ISSUE #14309: Jetpack App (Basics): Configure CI
Parent: #14293

TODO

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes #14309 

To test: N/A (was tested through the individual children PRs) 🟢 

## Regression Notes
1. Potential unintended areas of impact 🟢 
2. What I did to test those areas of impact (or what existing automated tests I relied on) 🟢
3. What automated tests I added (or what prevented me from doing so) 🟢

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @jkmassel !

I took the liberty and updated the `.circleci/config.yml` to fix the APK paths in order for the `Connected Tests` to pass on CI (same for Fastlane and the `fastlane/ScreenshotFastfile`). Let me know what you think. See change here: 0853d0e

🙏

**Comment by jkmassel** [comment]
> 👋 @jkmassel !
> 
> I took the liberty and updated the `.circleci/config.yml` to fix the APK paths in order for the `Connected Tests` to pass on CI (same for Fastlane and the `fastlane/ScreenshotFastfile`). Let me know what you think. See change here: [0853d0e](https://github.com/wordpress-mobile/WordPress-Android/commit/0853d0ebabc2054eeacde42490b24f447d39d305)
> 
> 🙏

Thanks @ParaskP7! I took a look at this yesterday, but [Docker Hub was down](https://status.docker.com/pages/history/533c6539221ae15e3f000031) so I wasn't able to run it. Thanks for taking this over the finish line!! 🙌

**Comment by ParaskP7** [comment]
👋 @jkmassel !

> Thanks @ParaskP7! I took a look at this yesterday, but Docker Hub was down so I wasn't able to run it. Thanks for taking this over the finish line!! 🙌

Great, thanks for the confirmation! 🎉 

PS: Do you think we are now ready to merge this `develop`? It would be good if we end up going for a merge just right after the release cut. Wdyt?

**Comment by jkmassel** [comment]
@ParaskP7 – I think that is ready to hit develop – if we run into further issues I think we can patch them as needed!

**Review by ParaskP7 — APPROVED** [review]
This feature branch is now ready to be merged to `develop`! 🎉

**Pull request merged**
