### PR TITLE
  Fixes #4140: drop webview on view site and view admin

### LINKED ISSUE #4140: Launch "View Site" and "View Admin" in device browser instead of in-app browser
Currently, the app's "View Admin" and "View Site" links open in an in-app browser.

#### The problem:

This leads to confusion when users try to use features that don't work well or at all in the in-app browser. Some things (like uploading media) are broken and/or don't work as well as features we have already implemented in the app itself.

#### Possible solution:

By changing "View Site" and "View Admin" to launch in the device browser, we can cut down on that confusion (and other effects like negative app reviews).

We could also add contextual cues in the app to items that launch outside the app, similar to the icon Calypso uses to identify external links:
 screen shot 2016-05-31 at 2 08 52 pm

#### Potential downsides:

- If the user isn't already logged in to the site in their browser, the visit to their site will be counted in their stats
- Users may be frustrated/confused about where they landed, having to log in again, getting back to the app.

### PR DESCRIPTION
**Pull request by maxme**
Fixes #4140: drop webview on view site and view admin - open site and admin using device Web Browser.

Added an "external" icon to the list item to warn the user. I also moved these sections to their own "External" (rewording welcome) section since they're specific to the Apps.

The FAB hides the external icons, not sure if we should 1. move the icons 2. add extra space on the bottom 3. do nothing.

screenshot-2016-06-21_15 40 44 763

screenshot-2016-06-21_15 40 40 768

### CODE REVIEW

**Comment by nbradbury** [comment]
> The FAB hides the external icons, not sure if we should 1. move the icons 2. add extra space on the bottom 3. do nothing.

FWIW, I think the first option makes the most sense (put the icons to the immediate right of the text).

**Comment by maxme** [comment]
screenshot-2016-06-21_16 51 17 738

**Comment by nbradbury** [comment]
Maybe if the arrow icons were smaller and offset a bit, like this?

7156ad36-37d0-11e6-9de4-8cd1b81193d3

**Comment by maxme** [comment]
Looking at Calypso use case for this icon, you're right we should probably make it smaller, not sure about the offset.

screen shot 2016-06-21 at 17 16 56

**Comment by maxme** [comment]
screenshot-2016-06-21_18 01 58 64

**Comment by nbradbury** [comment]
Looks good - and I'm happy we're finally dropping those from the app! :shipit:

**Pull request merged**
