### PR TITLE
Blaze Promote: web view refactoring

### PR DESCRIPTION
**Pull request by zwarm**
This PR implements refactor a good portion of the Blaze Promote webview/fragment to use UI states. This PR is very similar to #18844 

Changes include
-The view moves from `Preparing` to `Loading` to `Loaded` states. The loading indicator is shown while in the preparing and loading states. It gets removed on call from the webview that the page has loaded.

-Show a loading indicator, the view will now show an error view if account details are not present, there is no network connectivity, or the webview throws an error. I included a "retry" button, not sure if it should be there for non network connectivity errors. wdyt? FYI @osullivanchris 

Loading Before | Loading After
-- | --
<video src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/d67752f6-de71-4ed6-b045-32cc6b25d711"> | <video src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/a6521682-fd88-4b34-a901-7f0c71e0762b">

No Network Dark | No Network Light
-- | --
 | 

Error Dark | Error Light
-- | --
 | 

### Merge Instructions
- Ensure #18844 has been merged
- Remove Not Ready for merge label
- Merge as normal

### To test:
**Setup**
- Install and launch the app
- Navigate to Me -> App Settings -> Privacy Setting
- Enable collection information
- Navigate to Me -> App Settings -> Debug Setting
- Enable Blaze
- Restart the app

**Viewing Promote Blaze Flow**
- Navigate to a site that has blaze campaigns (use the test creds or create a blaze campaign first)
- Navigate to My Site tab
- Tap on the Create Campaign link within the Blaze Card to launch the Promote with Blaze Flow
- ✅ Verify the Loading indicator is shown while the page is loading
- ✅ Verify the Loading indicator goes away when the page is loaded

**Error view shows when there is no internet**
- Navigate to a site that has blaze campaigns (use the test creds or create a blaze campaign first)
- Navigate to My Site tab > Menu tab
- Tap on the Blaze menu item
- Verify the campaign list view has launched
- **STOP** - Turn on airplane mode
- Tap on the FAB button 
- ✅ Verify the Blaze view is launched, the header is visible, and the No Internet Error view is shown

**Error view shows when there is no account creds/or the webview is throws an error**
- Download the branch
- In fun `validateAndPostErrorIfNeeded` comment out the if statement and the return false
- Build, install, and run
- Navigate to My SIte tab 
- Tap on the Create Campaign link within the Blaze Card to launch the Promote with Blaze Flow
✅ Verify the generic error view is shown  

**Test Dashboard Entry Point**
- Navigate to My SIte tab
- Tap on the Promote With Blaze card
- If the blaze overlay is shown, then tap on the Blaze a Post Now button within the overlay. The blaze overlay will only show 1X
- ✅ Verify you are launched into the Blaze flow post lists
- ✅ Verify logs contain:  🔵 Tracked: blaze_flow_started, Properties: {"source":"dashboard_card"}
- Tap the cancel button in the header
- ✅ Verify you are taken out of the flow 
- ✅ Verify logs contain: 🔵 Tracked: blaze_flow_canceled, Properties: {"source":"dashboard_card","current_step":"posts_list"}
- Enter the blaze flow again
- Select a post from the list and tap Promote
- Tap the cancel button in the header
- ✅ Verify you are taken out of the flow 
---------------------------
- Enter the flow again
- Select a post from the list and tap Promote
- Fill out the fields (Change the title and snippet to DO NOT APPROVE - TESTING)
- Fill out the Payment information and submit
- Note that the cancel button is un-clickable
- Wait for the process to complete
-  ✅ Verify the header action button changed to "done"
- Tap the Header "Done" button

**Test Post Entry**
- Navigate to My SIte tab
- Tap on the Posts menu item or ribbon action
- Tap on More > Promote with Blaze
- ✅ Verify you are launched into the Blaze flow for the post you selected
- Tap the cancel button in the header
- ✅ Verify you are taken out of the flow 

## Regression Notes
1. Potential unintended areas of impact
The blaze flow does not work as expected

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

**PR submission checklist:**
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

**UI Changes testing checklist:**
- [X] Portrait and landscape orientations.
- [X] Light and dark modes.
- [X] Fonts: Larger, smaller and bold text. 
- [X] High contrast.
- [X] Talkback.
- [X] Languages with large words or with letters/accents not frequently used in English.
- [X] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [X] Large and small screen sizes. (Tablet and smaller phones)
- [X] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
Hey @zwarm

I have tested this PR according to the instructions. Everything looks good to me 👍🏼 . I can see the loading state/error state and the blaze flow is working as before 👍🏼

Approving but not merging so that you can merge once the dependant PR is merged

**Comment by zwarm** [comment]
> Approving but not merging so that you can merge once the dependant PR is merged

Thanks @AjeshRPai . I went ahead and made the same uiState change for Error.

**Comment by osullivanchris** [comment]
I don't love the phrase "There was a problem handling the request". Is that a standard one that we use? EDIT: I see on #18844 that you're reusing an error message from elsewhere. So we can leave as is and I can look across all another time.

> The view moves from Preparing to Loading to Loaded states. The loading indicator is shown while in the preparing and loading states. It gets removed on call from the webview that the page has loaded.

Ideally it would be great to go straight to the loading state (the skeleton view) but I can see that we're going from native -> web view, so we probably need that native step with a spinner? Just one small thing. After the spinner stops, there's a grey screen for a split second, before the webview skeleton loading state appears. Wonder if this is avoidable. Makes it less smooth because you see spinner>grey screen > skeleton loading screen > content. 


> Show a loading indicator, the view will now show an error view if account details are not present, there is no network connectivity, or the webview throws an error. I included a "retry" button, not sure if it should be there for non network connectivity errors. wdyt? FYI @osullivanchris

Depends. Is there a chance it succeeds second time? And is there some indication in the UI that its attempting again, e.g. going back to the spinner? If yes and yes, then could be good.

**Comment by zwarm** [comment]
Thanks @osullivanchris 

You are correct, that error message is from somewhere else, but I'm happy to change it to something more user friendly. lmk and I will update the copy.

>  Ideally it would be great to go straight to the loading state (the skeleton view) but I can see that we're going from native -> web view, so we probably need that native step with a spinner? Just one small thing. After the spinner stops, there's a grey screen for a split second, before the webview skeleton loading state appears. Wonder if this is avoidable. Makes it less smooth because you see spinner>grey screen > skeleton loading screen > content.

Before: pause/empty view > [web page gray screen > skeleton > web page] 
After: native spinner >  [web page gray screen > skeleton > web page] 

The obstacle we face is we don't control anything within the "[ brackets ]" above, we can only control the native pieces. The native spinner is removed once we get the signal that the web page has finished loading. I can remove the native spinner all together too. Personally I dislike seeing the blank view, but I will go with whatever you feel is the better ux.

> Is there a chance it succeeds second time? And is there some indication in the UI that its attempting again, e.g. going back to the spinner? If yes and yes, then could be good.

In the case of no network connectivity, yes retry is good. Other times, like in the case of missing account info, no, they can't recover, but if that get this far without that info, they will fail in other places in the app. If the webview throws an error, we don't have enough info to tell what caused it OR if it's recoverable, so sometimes a retry may work and other times it may not. I'm on the fence with this one. Will a user get frustrated tapping retry and getting the same error? Maybe? Perhaps we can switch the text to "Close" or "Go Back". Thoughts?  

P.S. Any changes will be made in a new PR :)

**Comment by osullivanchris** [comment]
> The obstacle we face is we don't control anything within the "[ brackets ]" above, we can only control the native pieces. The native spinner is removed once we get the signal that the web page has finished loading. I can remove the native spinner all together too. Personally I dislike seeing the blank view, but I will go with whatever you feel is the better ux.

Sounds good. I think the spinner is ok for now, if we have to wait. Better to show spinner than grey screen. Maybe its feedback for whoever owns the UI we're linking to? Surely if they have this skeleton loading style they want to display that immediately and not a grey screen first. Granted in any case the grey screen only flickers for a split second.

> In the case of no network connectivity, yes retry is good. Other times, like in the case of missing account info, no, they can't recover, but if that get this far without that info, they will fail in other places in the app. If the webview throws an error, we don't have enough info to tell what caused it OR if it's recoverable, so sometimes a retry may work and other times it may not. I'm on the fence with this one. Will a user get frustrated tapping retry and getting the same error? Maybe? Perhaps we can switch the text to "Close" or "Go Back". Thoughts?

Let's keep it for now. It sounds like those errors will be infrequent. And it is possible the retry will help. I'm sure if retry doesn't work after a couple times they will go back on their own accord.

**Comment by zwarm** [comment]
Thanks for the response, appreciate the input. Keeping it all "is-as", but open to future alterations as needed. 🙇

**Pull request merged**
