### PR TITLE
Feature/modularize editor

### PR DESCRIPTION
**Pull request by maxme**
This is a huge PR, because I had to extract `WordPressAnalytics` and `WorPressEditor` in their own repo / subtree. The idea behind this modularization is to have a `Fragment` with a title + content editor. It also includes a format bar and a settings button because we don't want to have nested Fragments.

I also made some changes in `WordPressUtils` (moved some code from the main project + renaming). That was a bad idea to include it in that PR, but it was also too late to change it back.

Everything media related (upload, gallery creation, etc.) now lives in the `EditPostActivity` and could be reused for both the legacy and visual editor.

The legacy editor supports wysiwyg edition for local drafts and html edition only for published posts/pages, so we have a dirty interface: [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b2d5377642ae027c1a458dfde6c43054812e4205/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java#L20-L21) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b2d5377642ae027c1a458dfde6c43054812e4205/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java#L68-L70) for instance, we will remove that when the legacy editor can be removed completly (or if we want to improve it and make some sort of `html2spanned` converter that would allow the wysiwyg edition of published posts).

The visual editor is not usable yet, but everything is ready to make it work (lives in [EditorFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/b2d5377642ae027c1a458dfde6c43054812e4205/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java)).

There is also a sample project that can be run without the main project. It should help to work on the hybrid editor and write new tests.

Warning: once this PR is merged, we must push `WordPressUtils` in its subtree (same for `WordPressAnalytics` and `WordPressEditor`, but this is not as important).

Tested with:

* QuickPress: OK
* QuickPhoto: OK
* New gallery from the media picker: OK
* New gallery / post from the media library: OK
* New post with a single picture from the media picker: OK
* New post with several pictures from the media picker: OK
* Share with WordPress with a single picture: OK
* Share with WordPress with several pictures: OK

### CODE REVIEW

**Comment by tonyr59h** [comment]
The gallery icon is not visible in the editor. It works as expected, just impossible to tell that it's been added to the post (unless you highlight it). [See here.](https://cloudup.com/cdEpy3YXFxe)

**Comment by tonyr59h** [comment]
Tested all the scenarios you mentioned, on both a tablet and phone, and they're all working :+1:

Gonna dig through the projects a bit now.

**Comment by maxme** [comment]
> The gallery icon is not visible in the editor. It works as expected, just impossible to tell that it's been added to the post (unless you highlight it). See here.
> 
> Edit: This is the current one. Should we import it to the editor module?

Yep, moved the icon to the editor module and updated the constructor call in a5e6c39

**Comment by maxme** [comment]
Example project should look like this:
https://cloudup.com/cNWo0fVB2r8

**Comment by tonyr59h** [comment]
Tested all the features both online and offline in the app as well as the example project and things seem to be working smoothly.

:+1: for the interfaces and setting up the WebView.

Reading through [this](http://developer.android.com/guide/webapps/webview.html#HandlingNavigation) I saw we can also override navigations. Maybe we could redirect WordPress.com sites to the app.

I'm onboard with the merge. Do we want to wait on @bummytime to chime in before we push the button.

**Comment by bummytime** [comment]
@tonyr59h @maxme: I have been working with @aforcier for the past few days on a private copy of this branch and we have not encountered any issues. Since our focus was mainly porting [portions](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/3fb089aec656f99e35447ca21ace89eea254181a/Assets/ZSSRichTextEditor.js) of the iOS-Editor code over to Android, we did not test everything as well as @tonyr59h. However in our use case this PR provides a great starting point for the updated editor.

So from our perspective, it's a :shipit:

**Pull request merged**
