### PR TITLE
Merge release 15.7-rc-4 into develop

### PR DESCRIPTION
**Pull request by loremattei**
This PR merges 15.7-rc-4 into develop. 
There were many conflicts in the merge. I tried to address them, but can you please review them @zwarm and make sure I didn't revert any of your fixes?
Also, feel free to close this PR and redo the process from scratch if it's easier for you to analyze the changes. 

@ceyhun there was also a conflict with Gutenberg which is hard to solve because we don't use tagged references. I opted for keeping the version in develop: is that ok?

Thank you!

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ceyhun** [comment]
> @ceyhun there was also a conflict with Gutenberg which is hard to solve because we don't use tagged references. I opted for keeping the version in develop: is that ok?

I think it's ok, thanks for checking 👍

**Review by ceyhun — COMMENTED** [review]
> @ceyhun there was also a conflict with Gutenberg which is hard to solve because we don't use tagged references. I opted for keeping the version in develop: is that ok?

I think it's ok, thanks for checking 👍

**Comment by zwarm** [comment]
@loremattei - Thanks for pinging me. There is some code in 15.7 that no longer exists in develop. `ReaderPostAdapter` is the culprit. I see the following options (1) Cherry pick the code to merge back into develop for ReaderPostAdapter (2) Merge this PR & immediately followup with a PR to develop BEFORE 15.8 is frozen to address that file. I am open to either option. I'm a bit nervous to redo this PR by myself for fear of screwing up anything in Gutenberg, but I am open to a redo together (teach to fish) wdyt?

**Review by zwarm — APPROVED** [review]
@loremattei - LGTM! I don't think I should be the one to merge, so I'll just do the approve part. Thanks for all your help.

**Comment by loremattei** [comment]
Thank you very much for _your_ help @zwarm!

**Pull request merged**
