### PR TITLE
Fix for failed uploads that loop and drains battery

### LINKED ISSUE #7017: Unable to dismiss failed upload notification, drains battery
### Expected behavior
To be able to dismiss a notification

### Actual behavior
It keeps coming back from the dead

### Steps to reproduce the behavior
1) Connect a Jetpack site and make sure you can access it from the app
2) Shut down the site (but don't disconnect it from wpcom)
3) Start writing a post on the site and let it try to auto-save your draft to the web

Now I have a "Upload failed" notification that returns immediately after I dismiss it.  Clicking the Retry button likewise dismisses the notification before it immediately returns.

https://cloudup.com/cPcKqkv7PDK

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #7017 by making sure to not automatically re-enqueue posts that failed.

Details and steps to repro in the original ticket.

cc @mzorz 

Side note:
I see a lot of parts in `PostUploadHandler` where we're checking for equality between 2 posts by only using postID.  EX: `queuedPost.getId() == post.getId()` and `sCurrentUploadingPost.getId() == post.getId();`. Full code snippet below:
```
    static boolean isPostQueued(PostModel post) {
        if (post == null) {
            return false;
        }

        // Check the list of posts waiting to be uploaded
        if (sQueuedPostsList.size() > 0) {
            synchronized (sQueuedPostsList) {
                for (PostModel queuedPost : sQueuedPostsList) {
                    if (queuedPost.getId() == post.getId()) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    static boolean isPostUploading(PostModel post) {
        return post != null && sCurrentUploadingPost != null && sCurrentUploadingPost.getId() == post.getId();
    }
```

Is it correct? Should not we also check the `siteId`?

### CODE REVIEW

**Comment by mzorz** [comment]
> Is it correct? Should not we also check the siteId?

**Comment by mzorz** [comment]
> Is it correct? Should not we also check the siteId?

Yes, strictly speaking you're right this should be checked. I wonder what probability of collision we have (that 2 posts of 2 different sites are being queued/uploaded at the same time).

**Comment by mzorz** [comment]
Agreed on the algorithm previously - tested, works alright :shipit: 
Thanks for jumping on this @daniloercoli ! 🙇

**Comment by daniloercoli** [comment]
I agree with you, it's very unlikely that 2 posts with the same local_id, on 2 different sites, fail at the same time. But like is hard :) and i'm sure this will happen sooner or later. We should try to fix it in a future iteration.

**Pull request merged**
