### PR TITLE
Fix #2834 - Checking for null Tags view

### LINKED ISSUE #2834: 4.1 crash - NPE inflating options menu
[Looks like](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L357) mTags isn't inflated yet.
```
java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.onCreateOptionsMenu(EditPostActivity.java:357)
       at android.app.Activity.onCreatePanelMenu(Activity.java:2546)
       at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
       at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
       at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
       at android.support.v7.app.ActionBarActivityDelegateBase.preparePanel(ActionBarActivityDelegateBase.java:979)
       at android.support.v7.app.ActionBarActivityDelegateBase.doInvalidatePanelMenu(ActionBarActivityDelegateBase.java:1182)
       at android.support.v7.app.ActionBarActivityDelegateBase.access$100(ActionBarActivityDelegateBase.java:79)
       at android.support.v7.app.ActionBarActivityDelegateBase$1.run(ActionBarActivityDelegateBase.java:118)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5097)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
#2834

### CODE REVIEW

**Comment by nbradbury** [comment]
Hmmm, there are problems with the way this was originally implemented. The activity itself doesn't contain `mTags` - it's in the [post settings fragment](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/edit_post_settings_fragment.xml#L81). I don't know why this is being done in `onCreateOptionsMenu` when it should be configured in the fragment instead.

At any rate, I guess that should be a separate issue :)

This PR should correct the NPE, but I think if `mTags` is null then we don't want to bother creating the adapter. So:

```
mTags = (SuggestionAutoCompleteText) findViewById(R.id.tags);
if (mTags != null) {
    mTags.setTokenizer(new SuggestionAutoCompleteText.CommaTokenizer());

    remoteBlogId = WordPress.getCurrentRemoteBlogId();
    mSuggestionServiceConnectionManager = new SuggestionServiceConnectionManager(this, remoteBlogId);
    mTagSuggestionAdapter = SuggestionUtils.setupTagSuggestions(remoteBlogId, this, mSuggestionServiceConnectionManager);
    if (mTagSuggestionAdapter != null) {
        mTags.setAdapter(mTagSuggestionAdapter);
    }
}
```

**Comment by tonyr59h** [comment]
> if mTags is null then we don't want to bother creating the adapter

Good point, moving it into the conditional block.

**Comment by tonyr59h** [comment]
Reminder to merge this into release/4.2 after review.

**Comment by nbradbury** [comment]
:shipit:

**Comment by maxme** [comment]
Cherry picked in 4.1.1

**Pull request merged**
