### PR TITLE
Activate the plugin after installation

### PR DESCRIPTION
**Pull request by oguzkocer**
#7292 needs to be reviewed and merged before this is reviewed!

This is a single commit PR that activates and enables the autoupdates for a plugin after it's installed.

To test:
* Install a plugin and check that it's active after a few seconds (we need to dispatch a network event to actually change the plugin's state even though we show it as enabled from the start)

/cc @theck13 (for the review) @nbradbury (to keep you in the loop for plugin changes)

### CODE REVIEW

**Comment by oguzkocer** [comment]
@theck13 Please change the base branch to `issue/plugin-data-reload` after #7280 is merged. I used `issue/reflect-fluxc-plugin-optimizations-1`, so it doesn't look like this PR is a massive one. 🐼

**Comment by oguzkocer** [comment]
We need to move this logic to FluxC to make that happen which is not something I'd like to do because it'll add unnecessary complication. I think we are OK to ignore this case, but a second opinion would be good, what do you think @nbradbury ?

We could also try to get this to be implemented on the server side, so the same "hack" is not implemented in 3 clients.

**Comment by theck13** [comment]
Even though I'm not usually a fan of blocking interface, we could have a progress dialog similar to removing a plugin as a workaround until the FluxC optimization is implemented.  We could just mimic the "Disabling <plugin>..." and "Removing <plugin>..." message with "Installing <plugin>..." and "Activating <plugin>..." or something similar.

**Comment by oguzkocer** [comment]
I think I am just going to do the FluxC change, this feels bad however we do it. Expect a small new PR in FluxC and a commit in this PR to reflect the changes here soon.

**Comment by oguzkocer** [comment]
@theck13 FluxC changes have been included in b8b3993acad4d5d53e4dd016b877f63d741d2399 and now it's ready to review!

**Pull request merged**
