### PR TITLE
Delete site warning dialog

### LINKED ISSUE #5145: Add warning about the site's address when deleting a site
When a user deletes their site in the app (My Sites > Settings > Delete Site), we warn them that their site will be gone forever, but we don't clearly state that the site address will also be unavailable:

This leads users to delete their sites when they want to start over, and then they are blocked when they can't recreate a site at the same address.

We should clarify, before the user deletes the site, that the site address will be unavailable. Related warnings in Calypso:

screen shot 2017-02-09 at 4 59 56 pm

screen shot 2017-02-09 at 5 00 19 pm

Reference: p77Llu-3Uf-p2

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-34

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5145. This PR adds an extra warning dialog when you try to delete the site, before actually confirming it. It contains the same message we have in Calypso and addresses the issues raised in #5145. I think this is the best approach to the issue, as otherwise we'd have a really big dialog and it won't probably even fit in some screens. In general, I don't like multiple dialogs, but since this is deleting a site, I think it's better to have it. It's also similar to how Calypso works in that regard.

You can find screenshots of the dialogs below. Please let me know if you want me to change the copy, especially for title and positive button (currently `yes`).

To test:
* Try to delete a site without any premium purchases

/cc @rachelmcr @mattmiklic @kwonye 

screenshot_1491400047
screenshot_1491400620

### CODE REVIEW

**Comment by nbradbury** [comment]
On the web there's some whitespace between the two sentences - I think that would be helpful here, too.

screen shot 2017-04-13 at 8 58 13 am

**Comment by oguzkocer** [comment]
> On the web there's some whitespace between the two sentences - I think that would be helpful here, too.

@nbradbury I think spacing is the same, there is only one new-line there in web and same in the dialog. However, I did try to add one more new-line there to increase the spacing, but it doesn't seem to work.

**Comment by nbradbury** [comment]
> However, I did try to add one more new-line there to increase the spacing, but it doesn't seem to work.

You can create the extra line using the BR tag. The simplest way to do this would be to break the message into two strings, like this:
```
<string name="delete_site_warning">All your posts, images, and data will be deleted. And this site’s address (%s) will be lost.</string>
<string name="delete_site_warning_subtitle">Be careful! Once a site is deleted, it cannot be recovered. Please be sure before you proceed.</string>
```
Then format them like this:
```
String text = getString(R.string.delete_site_warning, "<b>" + UrlUtils.getHost(mSite.getUrl()) + "</b>")
                + "<br><br>"
                + "<i>" + getString(R.string.delete_site_warning_subtitle) + "</i>";
```

screenshot_1492101137

**Comment by oguzkocer** [comment]
@nbradbury I changed the code to your suggestion in 7d2dcd6db1e3f2b03476358bf3cdb194c610f35a, however I still don't get the same spacing in my emulator. It also felt a little easier to understand,  so I thought it's better either way.

P.S: I had to merge `develop` in the issue because there was a change in the supporting library (I think) that prevented from me building the branch.

screenshot_1492176675

**Comment by nbradbury** [comment]
> however I still don't get the same spacing in my emulator.

That's due to using `<br></br>` - it should be `<br><br>` (no closing tag).

**Comment by oguzkocer** [comment]
> That's due to using `<br></br>` - it should be `<br><br>` (no closing tag).

🤕 

Fixed in 14e0a3b3b2973b13d057d4d36ec6a49ffd76f89d

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
