### PR TITLE
Update WordPress icon to use a circle base shape.

### PR DESCRIPTION
**Pull request by jasmussen**
This is based on a discussion on the optical weight the icon carries in stock homescreens. Moving from a square to a circle allows us to stay within Google material guidelines, while still making for an icon that looks bigger next to other icons that don't necessarily follow material guidelines. It's like having the cake, and eating it too.

### CODE REVIEW

**Comment by jasmussen** [comment]
By the way here's a 512x512 version that can be used in the Play Store:

app_icon-web

**Comment by roundhill** [comment]
Yay, I kinda missed the old round icon anyways!

**Comment by jasmussen** [comment]
> Yay, I kinda missed the old round icon anyways!

Classic Coke is back!

**Comment by maxme** [comment]
According to [this](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7QklSbXpmcjRSTlU/style_logos_product_grid_shapes_circle.png), new icon size looks good.

:shipit:

**Pull request merged**
