### PR TITLE
Gutenberg: update to v1.27.0

### PR DESCRIPTION
**Pull request by mkevins**
## Related PRs

gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2186
WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14002

To test:

**Bug fix**

- [x] Issue/1966 Disable whitespace collapse in Aztec https://github.com/wordpress-mobile/gutenberg-mobile/pull/2127
- [x] Revert "Add prop to force fullscreen preview for videos. (#20436)" https://github.com/wordpress-mobile/gutenberg-mobile/pull/2173
- [x] Block list - Autoscroll to text components within InnerBlocks https://github.com/wordpress-mobile/gutenberg-mobile/pull/2171
- [x] Issue/1851 insert captions https://github.com/wordpress-mobile/gutenberg-mobile/pull/2156
- [x] [FIX] Cover block background when there's a video is totally black https://github.com/wordpress-mobile/gutenberg-mobile/pull/2146
- [x]  Correct colors usage in Button https://github.com/wordpress-mobile/gutenberg-mobile/issues/2155
- [x] Correct slider step value https://github.com/wordpress-mobile/gutenberg-mobile/issues/2119
- [x] Refactor: Fixed position of `FloatingToolbar` on the bottom of the screen https://github.com/wordpress-mobile/gutenberg-mobile/issues/2118

**New feature & Improvement**

- [x] Update Aztec-Android for alignment handling https://github.com/wordpress-mobile/gutenberg-mobile/pull/2006
- [x] ~Video block - don't force full screen on iOS https://github.com/wordpress-mobile/gutenberg-mobile/pull/1952~ This was reverted
- [x] Adjust RangeControl to add the stepper control and allow type selection https://github.com/wordpress-mobile/gutenberg-mobile/pull/2125
- [x] Cover block - enable upload options in production https://github.com/wordpress-mobile/gutenberg-mobile/issues/2174
- [x] Cover block uploads failure UI https://github.com/wordpress-mobile/gutenberg-mobile/issues/2150
- [x] Add Buttons block https://github.com/wordpress-mobile/gutenberg-mobile/issues/1933

**Note:** including this to ensure we don't see the block in production yet:
- [x] Contact Info jetpack native blocks behind DEV flag https://github.com/wordpress-mobile/gutenberg-mobile/issues/1934

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by geriux** [comment]
### Writing flow sanity check

- [ ] Undo-redo [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/undo-redo.md)
- [ ] Copy-paste [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md)
- [ ] Splitting blocks [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md)
- [ ] Multiline components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md)
- [ ] Formatting on rich-text based components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md)
- [ ] Block insertion [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/block-insertion.md)

**Comment by mkevins** [comment]
### MediaText-1

- [ ] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [ ] Media Text block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText-2

- [ ] Media Text block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [ ] Media Text block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

### MediaText-3

- [ ] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [ ] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

### MediaText-4

- [ ] Media Text block - Media & Text alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [ ] Media Text block - Vertical alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

### MultipleUpload-1

- [ ] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

### Shortcode-1

- [ ] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

### Cover-2

- [ ] Cover - Add Video Background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [ ] Cover - Replace media - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [ ] Cover - Gradient background is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
- [ ] Cover - Gradient overlay is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

### Columns - 2

- [ ] Columns - Check if Column placeholders is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [ ] Columns - Appearance in vertical device position (vertical layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [ ] Columns - Appearance in horizontal device position (horizontal layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [ ] Columns - Mover direction - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [ ] Columns - Check if Column placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [ ] Columns - Unselected Column placeholder is streched to content in nested structure- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### Columns - 3

- [ ] Columns - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc018)

**Comment by pinarol** [comment]
> Done button in paragraph block (landscape mode text editing) leads to loop

@mkevins This is not a new behavior but I think this is worth revisiting that UX, could you open an issue? Not a blocker for the release imo.

**Comment by mkevins** [comment]
Thanks for testing!

**Pull request merged**
