### PR TITLE
Issue/6075 add toolbar toggle

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add ellipsis icons for expand/collapse buttons and `aztec:advanced` attribute to `AztecToolbar` view as described in https://github.com/wordpress-mobile/WordPress-Android/issues/6075.

### Test
0. Enable ***Beta*** editor.
1. Go to ***Sites*** tab.
2. Tap ***Create*** floating button.
3. Tap content text field.
4. Notice toolbar contains the following format buttons:
- Media
- Headings
- Lists
- Quote
- Bold
- Italic
5. Tap horizontal ellipsis button.
6. Notice toolbar expands to contain the following format buttons:
- Media
- Headings
- Lists
- Quote
- Bold
- Italic
- Link
- Underline
- Strikethrough
- Horizontal Rule
- More
- HTML
7. Tap vertical ellipsis button.
8. Notice toolbar collapses to contain the original format buttons.

#### Note
The ***branch will not build*** and the expand/collapse buttons will not be shown until https://github.com/wordpress-mobile/AztecEditor-Android/pull/388 is merged and the version containing those changes is included in the [WordPressEditor dependencies](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/build.gradle#L54).

### CODE REVIEW

**Comment by 0nko** [comment]
The build is failing because WordPress `develop` is still referencing the old Aztec release, not the latest `develop`.

**Comment by theck13** [comment]
Correct.  We don't want to target `develop` either.  We should change the [WordPress dependency](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/build.gradle#L54) once the next version of Aztec is released since the feature has been merged into the library.

**Comment by 0nko** [comment]
Once #6108 is merged, this PR's build can be restarted.

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
