### PR TITLE
Fix #2110: Add the option to set the parent of a Page

### LINKED ISSUE #2110: Page Options: Add the option to set the parent of a Page
Currently in neither the iOS or Android app are you able to set the parent attribute of a Page.
This is a feature request to have that added in a future version.

### PR DESCRIPTION
**Pull request by aforcier**
Fixes [#2110](https://github.com/wordpress-mobile/WordPress-Android/issues/2110).

I added a new field to the Page settings screen:

01-page-settings

Selecting that new field will open a new activity, that's modelled after the current categories page:

02-select-page-parent

You can select a new page as the parent, or no parent as shown in this video: https://cloudup.com/cLdFSp74Zoe

If the user tries to refresh the page parent list while there are local changes for any of the pages, they're prompted about being unable to refresh:

03-local-changes

Some details:
* Uses the `wp.getPosts` XML-RPC call to get a list of all pages with their title and parent id only
* Adds a new table, `page_list`, which stores the bare-bones list of pages and is kept up to date if the `posts` table changes, and if the new parent page list is refreshed
* Modelled after `SelectCategoriesActivity`. I refactored some code so that both activities use more general 'hierarchy' classes where possible. These can be used for custom hierarchical taxonomies and custom post types in the future.
* I used a workaround for issue [#2220](https://github.com/wordpress-mobile/WordPress-Android/issues/2220), so that the `SwipeRefreshLayout` is properly displayed when first starting the activity. This is only really needed for blogs with a large number of pages where the refresh takes a while (more than 50 or so, also dependant on connection quality), so that the user is aware that the list is being updated. We could instead add a dialog with a progress report for the time being, until there's a proper fix for the `SwipeRefreshLayout`.
* For cases where there are hundreds of pages it sometimes takes a long time to scroll to the page you're looking for - a future improvement could be to add a `SearchView` to the action bar to filter through the list of pages (similar to the media browser):

04-media-search

### CODE REVIEW

**Comment by maxme** [comment]
* +1 for reusing CategoryNode and CategoryArrayAdapter/HierarchyListAdapter
* +1 for PageHierarchyPage POJO
* You couldn't know this: we should stop adding stuff to WordPressDB, but use specialized class for new tables / models.
* I'm not sure we should compare parent title in `Post.java: hasChanges(Post otherPost)`
* We should (a) hide the modified page from the page hierarchy (and it's children) (b) or change it's style (greyed?), (c) or display a toast message when user tries to select it as root.
* I'm wondering if we should display the hierarchy in the main page list, like in wp-admin
* I'm not a big fan of the scrolling animation in `updateCheckedPosition`
* About the "Workaround for swipe to refresh bug", great to have it, but we should have a consistent way to apply it on all "refreshable" view (maybe simply have a Utility function for it).

**Comment by aforcier** [comment]
Thanks for the feedback @maxme!

> I'm not sure we should compare parent title in `Post.java: hasChanges(Post otherPost)`

You're right, the parent title check is unnecessary, parent id is all that's needed there

> We should (a) hide the modified page from the page hierarchy (and it's children) (b) or change it's style (greyed?), (c) or display a toast message when user tries to select it as root.

I had considered doing (a), since that would be consistent with wp-admin, but thought it might benefit the user to be able to see the full hierarchy of their pages in the app. If we ended up adding a way to display the hierarchy in the main page list, (a) would be my choice. Right now the user isn't able to select the modified page or its children, but some indication of why might be good - I think (c) would accomplish that, but doing (b) and (c) together would make it more obvious.

> I'm wondering if we should display the hierarchy in the main page list, like in wp-admin

I thought about that too, it can be done but there are some UX problems to address:
* If the user has pages than haven't yet been fully downloaded and saved to the `posts` table, we would have to pull the list of pages from the `page_list` table. If they wanted to edit a page that isn't in the `posts` table yet we'd have to download it on the spot. I think that would be OK, though some indication to the user of which pages have been fully downloaded might be helpful.
* We'd probably want to add a toggle, so the user can switch between a new hierarchical order and the chronological order we currently use (like wp-admin does for 'All Pages': the default vs sorting by date). I suggest this because it seems like users are more likely to want to edit recent pages, and making them scroll through a (potentially very long) list to find a newly created page when it used to be near the top would be irritating.

> I'm not a big fan of the scrolling animation in `updateCheckedPosition`

We could drop the scrolling animation entirely. I thought it looked a little sudden if the page list auto-refreshes and jumps down the list to the current parent (but the auto-refresh only happens at most once per blog)

> About the "Workaround for swipe to refresh bug", great to have it, but we should have a consistent way to apply it on all "refreshable" view (maybe simply have a Utility function for it).

I agree that there should be a consistent way to apply this fix. I added it mostly for demonstrative purposes, since it looked strange not showing any indication of loading if there are hundreds of pages being downloaded. It's specific to this activity but can certainly be extended to the rest of them with some testing.

**Comment by maxme** [comment]
I think we're going to close this, we may reopen/rework it when the REST client is implemented. Is that ok for you @aforcier?

**Comment by aforcier** [comment]
@maxme Sounds good, let me know if I can help with that when it happens!

**Pull request closed without merging**
