### PR TITLE
Stats - Fix class cast exception in Comments module

### LINKED ISSUE #2251: Crash Report 3.6: cast exception on Comments Fragment
java.lang.ClassCastException: com.android.volley.NoConnectionError cannot be cast to org.wordpress.android.ui.stats.models.CommentsModel
       at org.wordpress.android.ui.stats.StatsCommentsFragment.hasPosts(StatsCommentsFragment.java:128)
       at org.wordpress.android.ui.stats.StatsCommentsFragment.updateUI(StatsCommentsFragment.java:102)
       at org.wordpress.android.ui.stats.StatsAbstractListFragment$2.onClick(StatsAbstractListFragment.java:378)
       at android.view.View.performClick(View.java:4275)
       at android.view.View$PerformClick.run(View.java:17437)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:177)
       at android.app.ActivityThread.main(ActivityThread.java:4947)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2251 by checking the correct datamodel index for errors.

### CODE REVIEW

**Comment by nbradbury** [comment]
@danilo I think we've seen three different "class cast exception" issues in 3.6 related to casting VolleyErrors as stats CommentModels. That to me says a rethink is necessary.

**Comment by daniloercoli** [comment]
Yes, there was another issue of this type in this module. This is because this module is a little bit different from others and some checks were missing. I think will add some additional checks in the future to ensure that is not going to happen again. Maybe in 3.7.

**Comment by daniloercoli** [comment]
Just to be clear, now we should not see other Cast exceptions here.

**Comment by Danilo** [comment]
At least for me a rethink is in general always good. Good luck with that! :)

**Comment by nbradbury** [comment]
Sorry about that, I at-linked the wrong Danilo :)

**Comment by nbradbury** [comment]
This looks fine, but I still think this whole approach is simply too fragile. For example, we could run into the same problem [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2251-stats-class-cast-comments/WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java#L129) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2251-stats-class-cast-comments/WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java#L143) if things change. I'm going to go ahead and merge this fix, but a redesign really is necessary if similar issues occur.

**Pull request merged**
