### PR TITLE
[Gutenberg] - Filter media types when sharing files to the app

### LINKED ISSUE #6443: JavascriptException: Error: Block type 'core/other' is not registered.
**Describe the bug**
The editor crashes on Android when trying to share different types of media into the editor, for example selecting an image and a PDF file.

**To Reproduce**
- Go to your Files folder on your device
- Multiselect an image and a PDF file
- Tap on Share
- Select the Jetpack app
- Tap on Create a new post
- The editor crashes

**Expected behavior**
The supported media files (image/video) should be uploaded successfully and the rest should not be included

**Screenshots**
<video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/4885740/0569ea03-812b-4b13-a2e8-f787dea27b8e" width="230" />

**Smartphone (please complete the following information):**
 - Device: Samsung A23 5G
 - OS: Android 13

### PR DESCRIPTION
**Pull request by geriux**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/6443

**Related PRs:**
- https://github.com/WordPress/gutenberg/pull/56791

This PR fixes an issue when appending unsupported media types when using the Sharing functionality on Android devices.

The only way to be able to "Share" unsupported media types is when multi-selecting files that the app does support like images or videos.

For more information please check Gutenberg's PR description.

-----

## To Test:

- **Precondition**: Have different kinds of files on your device: `PDF`, `jpg`,  and `mp4`.
- **NOTE:** Since this is not a release build, the editor takes a bit of time to load when adding media.
- Install the app from this PR
- Open your Files app
- Multiselect an image and a PDF file 
- Tap on the Share button
- Select the Jetpack app
- **Expect** the editor to be loaded with just the supported media types (images, and videos)

Test Case 1|Test Case 2
-|-
<video src="https://github.com/WordPress/gutenberg/assets/4885740/dd8dd610-5371-4da0-acf2-a36d1914c97e" />|<video src="https://github.com/wordpress-mobile/WordPress-Android/assets/4885740/19574a54-0db9-41bf-ab45-e30e8cb80278" />

-----

## Regression Notes

1. Potential unintended areas of impact

It should only affect the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual tests.

3. What automated tests I added (or what prevented me from doing so)

    - TODO

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by justtwago — APPROVED** [review]
Thank you for fixing this @geriux! Awesome work! The code looks simple and good for me 👍 I tested the change on Google Pixel 7 Pro (Android 14) and it behaved as described - no crash when selecting unsupported files to share as a new post.

I'm not sure if we can merge not stable Gutenberg version though:
```
    gutenbergMobileVersion = '6444-7b344ab956224ba96726111c150dc44a39be8b9e'
```
Reference: https://github.com/wordpress-mobile/WordPress-Android/pull/19683#discussion_r1410113714

**Comment by derekblank** [comment]
> I'm not sure if we can merge not stable Gutenberg version though:

Thank you for testing, @justtwago and good call out on noting the Gutenberg ref. Typically for Gutenberg PRs on WPAndroid we update the Gutenberg reference to a specific Gutenberg Mobile branch and commit to generate the CI builds. Once we merge the Gutenberg and Gutenberg Mobile PRs, we'll update the WPAndroid Gutenberg reference back to the latest Gutenberg Mobile tag before merging this PR. [Here's an example](https://github.com/wordpress-mobile/WordPress-Android/pull/18705/commits).

**Review by derekblank — APPROVED** [review]
Adding another +1 that I was able to successfully test the changes via https://github.com/WordPress/gutenberg/pull/56791#pullrequestreview-1771587004 🚀

**Comment by justtwago** [comment]
> Thank you for testing, @justtwago and good call out on noting the Gutenberg ref. Typically for Gutenberg PRs on WPAndroid we update the Gutenberg reference to a specific Gutenberg Mobile branch and commit to generate the CI builds. Once we merge the Gutenberg and Gutenberg Mobile PRs, we'll update the WPAndroid Gutenberg reference back to the latest Gutenberg Mobile tag before merging this PR. https://github.com/wordpress-mobile/WordPress-Android/pull/18705/commits.

Cool, thank you a lot for clarifying this, @derekblank! 💯 Totally makes sense.

**Comment by geriux** [comment]
Thank you both for reviewing and testing! 

For this case, since these changes don't rely on the Gutenberg ones, I will revert updating the Gutenberg reference since it was just for testing the latest changes and we can update it later on either with the next release or alpha version.

**Pull request merged**
