### PR TITLE
Keep Aztec editing in landscape

### PR DESCRIPTION
**Pull request by hypest**
Continue using "Aztec" mode instead of letting Android use the extracted UI editing mode.

The actionbar gets hidden in landscape to allow for a bit more breathing space.

To test:
1. Use the app in landscape
2. Tap inside the editor
3. The actionbar get hidden while the editor is still available with all the formatting shown and available.

@theck13 you might want to pick this up as well since you reviewed the corresponding one in Aztec. Thanks!

### CODE REVIEW

**Comment by theck13** [comment]
There is some odd behavior between the title and body views.  Follow the steps below for example.

1. Create a new post.
2. Rotate the device into landscape orientation.
3. Tap the body text area.
4. Enter the following text.
```
One
Two
Three
```
5. Notice only the body text area is scrollable.
6. Tap the ***HTML*** format button.
7. Notice the title and body text area is scrollable.
8. Tap the ***HTML*** format button.
9. Notice the title and body text area is scrollable.

Also, what about hiding the title as well?  That would fix the issue above and provide more room in landscape orientation.  We might want to get some designer feedback on that one.

**Comment by maxme** [comment]
@hypest is this still relevant, should we fix it and ship it?

**Comment by hypest** [comment]
Hey @maxme , the issue this PR is trying to solve is still relevant. That is, prevent the extracted UI editing mode to kick in when in landscape. We should either fix this PR or create a new one. Thanks!

**Comment by lapolinar** [comment]
i'm a newbee how can i adopt github to my wordpresd, thanks...

**Comment by maxme** [comment]
Closing that one, superseded by https://github.com/wordpress-mobile/WordPress-Android/pull/6730

**Pull request closed without merging**
