### PR TITLE
[Gutenberg] Add metadata on media upload success event

### LINKED ISSUE #5471: Upload - Pass VideoPress GUID in media upload events [WP-Android]
## Description

As part of the upload process, we need to pass the `videopress_guid` to render the content once the upload finishes. This parameter can be fetched from [the media metadata](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/media/%24media_ID/). This [parameter is already fetched in WordPress-Android](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5bce27afc6c377d404c088f683451609263b71f3/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaResponseUtils.kt#L55), however, it's not being passed down to the editor.

### PR DESCRIPTION
**Pull request by fluiddot**
**Related PRs:**
- [WordPress-Utils-Android](https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/121)
- [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/20144)
- [Gutenberg Mobile](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5479)
- [Gutenberg](https://github.com/WordPress/gutenberg/pull/48103)

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/5471.

Add metadata parameter to the media upload success event that is passed to the Gutenberg editor. This parameter is open to any information around the media that can be useful to have when the upload finishes successfully.

This PR also includes the VideoPress GUID to the metadata parameter as it's needed to render the VideoPress block.

## To test

**NOTE:** This change can only be tested on development using a patch file in Gutenberg.

1. Apply the following patch in Gutenberg codebase:
```
diff --git forkSrcPrefix/packages/block-library/src/video/edit.native.js forkDstPrefix/packages/block-library/src/video/edit.native.js
index 99225ba5d5c569d19a158f5b1a203c68aa353c33..da4e3418c46305386a68ceaec618f818dc0ffb4a 100644
--- forkSrcPrefix/packages/block-library/src/video/edit.native.js
+++ forkDstPrefix/packages/block-library/src/video/edit.native.js
@@ -138,6 +138,9 @@ class VideoEdit extends Component {
 
 	finishMediaUploadWithSuccess( payload ) {
 		const { setAttributes } = this.props;
+
+		console.log( 'finishMediaUploadWithSuccess', payload );
+
 		setAttributes( { src: payload.mediaUrl, id: payload.mediaServerId } );
 		this.setState( { isUploadInProgress: false } );
 	}

```
1. Build the app and connect it with your Metro local server.
1. Open a post/page in a simple site.
1. Insert a Video block.
1. Upload a video from the device.
1. Once the upload finishes, check the console logs and observe an entry that displays the metadata and VideoPress GUID, e.g.: `
finishMediaUploadWithSuccess {"mediaId": <MEDIA_ID>, "mediaServerId": <MEDIA_SERVER_ID>, "mediaUrl": "https://<SITE>.files.wordpress.com/2023/02/file_example_mp4_480_1_5mg-21.mp4", "metadata": {"videopressGUID": "<VIDEOPRESS_GUID"}, "progress": 1, "state": 2}
`

## Regression Notes
1. Potential unintended areas of impact
This change shouldn't produce any side effects but if any, it would affect the media uploads in the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested uploads on the different media blocks:
    - Image block ✅ 
    - Video block ✅ 
    - Cover block ✅ 
    - File block ✅ 
    - Audio block ✅ 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jhnstn — APPROVED** [review]
Test plan worked as expected and changes look good :shipit:

**Comment by dcalhoun** [comment]
👋🏻 @fluiddot. I encountered the following error while attempting to build WPAndroid against my local Gutenberg repository. 

```
/WordPress-Android/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java:218: error: method mediaFileUploadSucceeded in class WPAndroidGlueCode cannot be applied to given types;
        mWPAndroidGlueCode.mediaFileUploadSucceeded(mediaId, mediaUrl, serverMediaId);
                          ^
  required: int,String,int,WritableNativeMap
  found: int,String,int
  reason: actual and formal argument lists differ in length
```

My understanding is that this error occurs because this PR has not yet merged integrating the now merged https://github.com/WordPress/gutenberg/pull/48103. I can easily work around the issue by reverting https://github.com/WordPress/gutenberg/commit/cfb54a75f726d5f65d03bcc2fca9afc58b9af2c4 locally, but wanted to call attention to the error incase this PR was overlooked. 

Do we intend to merge this PR in the near future? Doing so may help others avoid this unexpected error. Thanks! 🙇🏻

**Comment by fluiddot** [comment]
> My understanding is that this error occurs because this PR has not yet merged integrating the now merged [WordPress/gutenberg#48103](https://github.com/WordPress/gutenberg/pull/48103). I can easily work around the issue by reverting [WordPress/gutenberg@cfb54a7](https://github.com/WordPress/gutenberg/commit/cfb54a75f726d5f65d03bcc2fca9afc58b9af2c4) locally, but wanted to call attention to the error incase this PR was overlooked.
> 
> Do we intend to merge this PR in the near future? Doing so may help others avoid this unexpected error. Thanks! 🙇🏻

Yeah, sorry for that. I started the merge domino but had to pause it due to the Buildkite issues. Now that the issue is solved I'll resume it and merge the PRs 💨 .

**Comment by fluiddot** [comment]
> > My understanding is that this error occurs because this PR has not yet merged integrating the now merged [WordPress/gutenberg#48103](https://github.com/WordPress/gutenberg/pull/48103). I can easily work around the issue by reverting [WordPress/gutenberg@cfb54a7](https://github.com/WordPress/gutenberg/commit/cfb54a75f726d5f65d03bcc2fca9afc58b9af2c4) locally, but wanted to call attention to the error incase this PR was overlooked.
> > Do we intend to merge this PR in the near future? Doing so may help others avoid this unexpected error. Thanks! 🙇🏻
> 
> Yeah, sorry for that. I started the merge domino but had to pause it due to the Buildkite issues. Now that the issue is solved I'll resume it and merge the PRs 💨 .

@dcalhoun The PR is ready to be merged so I enabled auto-merge. Once the CI jobs succeed, it will be merged into `trunk` 🎊 .

**Pull request merged**
