### PR TITLE
Fix failing connected tests

### PR DESCRIPTION
**Pull request by renanferrari**
Fixes connected tests that were failing for `loginWithMagicLink` due to non-null parameter being null.

I believe this was introduced by [this change](https://github.com/wordpress-mobile/WordPress-Android/commit/c9854692e53e302b4ae3bc42a4ff5af35e519065#diff-1cf6428dcfe0d429dfdcf7398ef4c056R812) from [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/12728).

This PR simply updates `onResume(site: SiteModel)` to `onResume(site: SiteModel?)` as it seems to have fixed the issue, but I wonder if we shouldn't do the same for the other functions in that class that also receive a `SiteModel`? (cc @aforcier as I don't have much context on this right now)

To test:

Run the connected tests from the `LoginTests` suite and make sure they all pass.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by aforcier** [comment]
Looks good @renanferrari 👍 

> This PR simply updates onResume(site: SiteModel) to onResume(site: SiteModel?) as it seems to have fixed the issue, but I wonder if we shouldn't do the same for the other functions in that class that also receive a SiteModel? (cc @aforcier as I don't have much context on this right now)

Yeah let's update them all to be consistent.

Also I just realized this is quite a serious issue - it's going to cause a crash on startup for siteless WordPress.com users. The issue is in 15.6, which just went to the beta channel - I believe we need to change this PR to target `release/15.6` and release a 15.6-rc-2, is that correct @oguzkocer ?

**Comment by oguzkocer** [comment]
Thanks for taking care of it @renanferrari and reviewing it @aforcier!

@aforcier Yes, if it's a serious issue, it'd be better to target `release/15.6`. I can release a new version on Thursday with other possible fixes.

**Comment by oguzkocer** [comment]
This may actually be worth a fix on its own, I'll see if anything else is being worked on and potentially release the new beta early.

**Comment by mzorz** [comment]
Thanks for bringing up a fix for this @renanferrari ! 🙇 Just checked this PR as the issue has been reported once more elsewhere 👍 

> but I wonder if we shouldn't do the same for the other functions in that class that also receive a SiteModel

Just wanted to add to this, [`hasFullAccessToContent()` in SiteUtils](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java#L317) (calls for which were what that commit mostly did) accepts the `site` parameter being null so with this suggested change  / question of yours on other functions I believe the behavior which was changed unintentionally would be restored then 👍

**Comment by renanferrari** [comment]
I have merged the changes from #12794 and updated the base branch to `release/15.6`. Ready for review.

**Review by mzorz — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
