### PR TITLE
Update lint baseline file

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR updates Android Lint baseline file. As the code changed, it's worth updating the file to match the current state of the code. 

The huge diff comes from the fact, that we didn't update the baseline file after adding `UnknownNullness` rule, which now will be added to the baseline.

I do this as a preparation before another update of baseline file, which I plan to do in #21082

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>LineChartMarkerView</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ParaskP7** [comment]
👋 @wzieba !

> The huge diff comes from the fact, that we didn't update the baseline file after adding UnknownNullness rule, which now will be added to the baseline.

This was actually done by design, the [MissingNullAnnotationDetector.kt](https://github.com/wordpress-mobile/WordPress-Lint-Android/blob/b374448366b36fb597d61f84126d65f0b5e3ce9f/WordPressLint/src/main/java/org/wordpress/android/lint/MissingNullAnnotationDetector) that holds all these 4 x checks has an [INFO](https://github.com/wordpress-mobile/WordPress-Lint-Android/blob/b374448366b36fb597d61f84126d65f0b5e3ce9f/WordPressLint/src/main/java/org/wordpress/android/lint/MissingNullAnnotationDetector.kt#L152) severity for that specific reason, to keep getting those shown in the report (highlighted on IDE) so that they could be progressively fixed as devs keep touching those files. I didn't want to have them buried into the baseline where no-one would ever clean those up, unless of course explicitly working on reducing the baseline.

Also, personally, my goal was to resolve/suppress all that baseline warnings at some point, thus I wanted to keep this baseline small. Now, adding 7K more issues into it, it will be impossible to get rid of the baseline anytime soon.

What is more, now the baseline has a mix of both WARN + INFO issues in it, and I am not sure if that's what we want. I would personally keep the baseline with WARN only issues.

Let me know your thoughts so we can progress with this accordingly, I am just clarifying here and open to suggestions.

**Comment by ParaskP7** [comment]
To accompany [this](https://github.com/wordpress-mobile/WordPress-Android/pull/21083#issuecomment-2255571086) comment of mine, I added the following `disable` related configuration to this [lint { ... }](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/build.gradle#L285-L292) block:

```gradle
    lint {
        ...
        disable += [
                'UsingMaterialAndMaterial3Libraries',
                'UnknownNullness',
                'MissingNullAnnotationOnField',
                'MissingNullAnnotationOnConstructorParameter',
                'MissingNullAnnotationOnMethodParameter',
                'MissingNullAnnotationOnMethodReturnType',
        ]
    }
```

With that, you get an updated Lint baseline which is "almost" what we want, lost of issues got automatically removed, while some new got added. And for those new added, I would move them close to source of fix them (ie. 1 x `ObsoleteLintCustomCheck`, 1 x `IntentFilterUniqueDataAttributes`, 13 x `KtxExtensionAvailable`). This way, IMHO you will get a much better version of the Lint baseline, with only about 300 baseline issues remaining to get addressed.

FYI: I run Lint for Jetpack only to get the above number. We need to run Lint for both, Jetpack + WordPress, and merge the 2 x baselines into one, that is, if we see a diff.

PS: I added this [UsingMaterialAndMaterial3Libraries](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/config/lint/lint.xml#L73-L74) as well, because that Lint warning was most recently got ignored via the config. Additionally, the `UnknownNullness` is equivalent to the other 4 x `MissingNullAnnotationOnXyz` and got disabled for the very same reasons, it is only informational.

I hope that all helps you! 🙏

**Comment by ParaskP7** [comment]
👋 @wzieba and quick question, shouldn't we now close this PR? 🤔

**Comment by wzieba** [comment]
Sure @ParaskP7 ! Thanks for all the explanation here, the suggestions discussed and applied in #21082

**Pull request closed without merging**
