### PR TITLE
Converts Starter Page previews to use the web view implementations from Home Page Picker

### LINKED ISSUE #2980: Convert Starter Page previews to use the web view implementations from Home Page Picker
**Is your feature request related to a problem? Please describe.**
When implementing the new [Starter Page Picker](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aclosed+%5BModal+Layout+Picker%5D) we decided to replicate the preview functionality that was currently in place in the Gutenberg Editor (ie a read-only view of the editor). During that project, we updated the previews to provide a web view that loads an autosave of the page. 

**Describe the solution you'd like**
Update starter page picker's preview screen to provide:
- WebView that loads a URL representing the chosen page
    - Similar to the Editor's Preview and Site Creation
- A toggle to support Mobile vs Desktop
    - Default to mobile (or to the setting on the [previous screen](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2979) if available)
- **Bonus** if the preview applied the current theme.

Current | Site-Creation comparison | Editor Comparison
--- | --- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/103943417-0f17cd00-5100-11eb-8791-081199ec450e.PNG"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/103943520-3b334e00-5100-11eb-8d6a-bc1e043a6195.PNG"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/103943561-4be3c400-5100-11eb-979e-1a479dfb2c84.PNG"></a></kbd>

**Additional context**
- This will need some API changes in addition to app changes and likely some exploration into the bonus goals of applying the site's theme. 

cc @iamthomasbishop @kyleaparker

### PR DESCRIPTION
**Pull request by antonis**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2980

### Description
Converts Starter Page previews to use the web view implementations from Home Page Picker

### Notes
* [Removing preview mode from `gutenberg` will be implemented as a separate issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3217)
* The `editor_session_template_preview` event (as introduced [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2454)) has been replaced with the following new events that match the Home Page Picker implementation: `layout_picker_preview_mode_changed`, `layout_picker_thumbnail_mode_button_tapped`, `layout_picker_preview_mode_button_tapped`, `layout_picker_preview_loading`, `layout_picker_preview_loaded`, `layout_picker_preview_viewed`, `layout_picker_error_shown`
* The rest of the layout picker analytics tracking will be implemented in a separate [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3130)

## To test:

<details>
<summary><strong>To start the Modal Layout Picker screen</strong></summary>

* Press the fab ➕  icon in the **My Site** screen and select **Site Page**
or
* Press the fab ➕  icon in the **Pages** screen
</details>

### Preview options availability
1. Start the Modal Layout Picker screen
1. Select a layout
1. Press the **Preview** button
1. **Verify** that a preview is displayed
1. Verify that that the following analytics events are emitted (where `blog-9` the selected template):
- `🔵 Tracked: layout_picker_preview_viewed, Properties: {"template":"blog-9","preview_mode":"mobile"}`
- `🔵 Tracked: layout_picker_preview_loading, Properties: {"template":"blog-9","preview_mode":"mobile"}`
- `🔵 Tracked: layout_picker_preview_loaded, Properties: {"template":"blog-9","preview_mode":"mobile"}`
1. **Verify** that there is a preview mode button at the top right of the screen
1. Press the **preview mode button**
1. Verify that an analytics event is emitted `🔵 Tracked: layout_picker_preview_mode_button_tapped, Properties: {"preview_mode":"mobile"}` where `mobile` is the current preview mode
1. Verify that three options are displayed: Mobile, Tablet, Desktop

### Mobile preview
1. Start the Modal Layout Picker
1. Select a layout
1. Press the **Preview** button
1. Press the **preview mode button**
1. Verify that an analytics event is emitted `🔵 Tracked: layout_picker_preview_mode_button_tapped, Properties: {"preview_mode":"mobile"}` where `mobile` is the current preview mode
1. Select **Mobile**
1. **Verify** that a mobile preview is displayed

### Tablet preview
1. Start the Modal Layout Picker screen
1. Select a layout
1. Press the **Preview** button
1. Press the **preview mode button**
1. Verify that an analytics event is emitted `🔵 Tracked: layout_picker_preview_mode_button_tapped, Properties: {"preview_mode":"mobile"}` where `mobile` is the current preview mode
1. Select **Tablet**
1. Verify that an analytics event is emitted `🔵 Tracked: layout_picker_preview_mode_changed, Properties: {"preview_mode":"tablet"}`
1. **Verify** that a tablet preview is displayed
1. Verify that that the following analytics events are emitted (where `blog-9` the selected template):
- `🔵 Tracked: layout_picker_preview_loading, Properties: {"template":"blog-9","preview_mode":"tablet"}`
- `🔵 Tracked: layout_picker_preview_loaded, Properties: {"template":"blog-9","preview_mode":"tablet"}`

### Desktop preview
1. Start the Modal Layout Picker screen
1. Select a layout
1. Press the **Preview** button
1. Press the **preview mode button**
1. Select **Desktop**
1. **Verify** that a desktop preview is displayed
1. Verify that that the following analytics events are emitted (where `blog-9` the selected template):
- `🔵 Tracked: layout_picker_preview_loading, Properties: {"template":"blog-9","preview_mode":"desktop"}`
- `🔵 Tracked: layout_picker_preview_loaded, Properties: {"template":"blog-9","preview_mode":"desktop"}`

### Change mode on the preview screen
1. Start the Modal Layout Picker screen
1. Select a layout
1. Press the **Preview** button
1. Press the preview mode button
1. Select **Desktop**
1. **Verify** that desktop mode is displayed
1. Close the preview screen (back or swipe down)
1. **Verify** that desktop thumbnails are displayed

### Change mode from the layouts screen
1. Start the Modal Layout Picker screen
1. Press the preview mode button
1. Select **Desktop**
1. Select a design
1. Press the **Preview** button
1. **Verify** that a desktop preview is displayed

#### Create a Blank Page
1. Create a new page for a Gutenberg site.
1. Select "Create a Blank Page"
     - **Expect** to see the Editor Load and not present the old Starter Page Template Picker Bar

#### Create a Page from a layout
1. Create a new page for a Gutenberg site.
1. Select a layout
1. Select "Create Page"
     - **Expect** to see the Editor Load with the contents of the layout

#### Preview a layout
1. Create a new page for a Gutenberg site.
1. Select a layout
1. Select "Preview"
     - **Expect** to see the new preview screen
1. Select "Create Page"
     - **Expect** to see the Editor load with the contents of the layout

#### Create a Site - Selecting a Design
1. Select a design
1.  **Expect**
    - To see the footer slide in from the bottom
    - To see a border and checkmark animate in place on the selected design.
1. Select Choose
1.  **Expect**
    - To see the analytics event `enhanced_site_creation_site_design_selected` with the property `template` populated with the selected layout's slug
1. Search for and select a domain
1. Select Create Site
1.  **Expect**
    - To see a temporary screen as the site is being created
    - To see the site confirmation screen.

#### Preview then Create a Site
1. Select a design
1. Select Preview
1.  **Expect** the preview to show for the selected design
1. Select Choose
1. **Expect** to see the preview modal dismiss and for the Choose a Domain screen to be "pushed" on to the navigation flow.
1. Search for and select a domain
1. Select Create Site
1.  **Expect**
    - To see a temporary screen as the site is being created
    - To see the site confirmation screen.

## Screenshots

|Before|After|
|---|---|
|device-2021-03-04-215242|device-2021-03-04-215322|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hey @chipsnyder, @mkevins 👋 

> For consistency with existing analytics data the editor_session_template_preview event (as introduced [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2454)) is used.

Do you think we should replace this analytics event with a new one? The name is a bit misleading since we no longer use the editor. We can also [track additional events](https://github.com/wordpress-mobile/WordPress-Android/pull/14184/files#diff-c3b5ae18ffb29dec6511f23398992eb0aebf18af2071a25a578155687f81f5a3R178) as we do with the Home Page Picker.

**Comment by chipsnyder** [comment]
> Do you think we should replace this analytics event with a new one?

I think it makes sense to align the analytics between the two screens.

**Comment by antonis** [comment]
Thank you for the feedback @chipsnyder 👍 

> I think it makes sense to align the analytics between the two screens.

I agree. I added analytics tracking aligning with the Home Page Picker preview with 3551cae4717c03d46f917f040f2aa1f1f2cee028

**Review by chipsnyder — APPROVED** [review]
This looks good to me tested it out on my Pixel 3a thanks for knocking this out so quickly!

**Pull request merged**
