### PR TITLE
Zendesk WIP: Removing HelpshiftHelper and some organization

### PR DESCRIPTION
**Pull request by oguzkocer**
This is a follow up PR to #7739 and that PR needs to be merged in before this can be reviewed. It's main goal is to remove the `HelpshiftHelper` and cleanup the current implementation. Aside from adding a `connecting_jetpack` tag, not much has been done about the Zendesk integration.

_To test:_

There is not really anything particular to test in this PR. Same tests in #7739 can be run here as well.

P.S: As mentioned in #7739, I am hoping for some more cleanup for the ZendeskHelper and HelpActivity. However, before I start that work, I would like to merge `develop` into my WIP branch to pull changes in #7755 & #7745.

Also, refer to #7737 for what's planned to be worked on for Zendesk integration.

### CODE REVIEW

**Comment by oguzkocer** [comment]
I had to change the base branch a couple times as Github was not showing the correct diff. This PR should be ready to review now. 🤞

**Comment by oguzkocer** [comment]
> I don't think ZendeskHelper should be a utility file(?). It doesn't really behave like one.

Do you mind explaining a bit more about what you mean by this? It's a collection of stateless helper functions that aims to minimize the code duplication. That sounds to me like a utility class, but maybe we have a different understanding of it?

>  You probably know this (I've seen your comment on your previous PR) but I just want to mention I think this is important. Using utility/static methods makes any class that calls current implementation untestable.

Yeap, I am aware. What we expose from the `ZendeskHelper` is starting of activities, which means they are not going to be part of business logic, hence won't be tested. I am still not sure this is the best way to go, but using a class feels even worse to me, because that'll mean we will start adding state to it.

The problems mostly come from the singleton usage of the Zendesk SDK. To get around that, I initially had this idea of passing the Zendesk instance around. I thought that'd fix some of the testability issues in the `ZendeskHelper` itself as well as giving a way to the callers of `ZendeskHelper` to test their code. I am not 100% sure whether it'll work out as I haven't full tried it yet. I was going to do that if I get to work on the Zendesk tests 🤷‍♂️ 

Due to the way Zendesk SDK works, I found myself in this side of the trade off for now and gone ahead with the helper pattern. However, I am always open to suggestions, so if you have any ideas that'll help with testing without hurting the actual implementation, feel free to drop them here or in the master thread. Note that I am using a similar pattern in an upcoming PR [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/zendesk-identity-with-email-input/WordPress/src/main/java/org/wordpress/android/support/SupportHelper.kt) so you can check out that and gave your feedback combined together. Thanks!

**Comment by planarvoid** [comment]
> Do you mind explaining a bit more about what you mean by this
I agree with you on the definition but I would personally use utility classes (and by this I mean in Java classes with static methods, in Kotlin files with static methods) only in extremely simple usecases, the kind of methods you extract because of code duplication but you wouldn't generally mind if they were inlined - one I could think of would be `checkNotNull` in guava or anything you'd put into public extension functions in Kotlin.

> The problems mostly come from the singleton usage of the Zendesk SDK
I think it would be fine if you just wrapped the static methods by an injected class. By this approach you hide the Zendesk code and the static approach, you make the classes that call it testable and you can still keep your old code. The new classes would use the injected `Helper` and the old classes could still call the static metods. 
```
class InjectedHelper @Inject constructor(accountStore: AccountStore) {
   fun dynamicZendeskMethod(message: String) {
      staticZendeskMethoda(accountStore, message)
   }
}
fun staticZendeskMethod(accountStore: AccountStore, message: String) {
   ...whatever
}
```

**Comment by oguzkocer** [comment]
> I think it would be fine if you just wrapped the static methods by an injected class.

**Pull request merged**
