### PR TITLE
Configure Codecov

### PR DESCRIPTION
**Pull request by wzieba**
## Description

This PR integrates Codecov. By this, we'll have:
- comments on each PR reporting code coverage diff (e.g. https://github.com/woocommerce/woocommerce-android/pull/10523#issuecomment-1879634587)
- a trend metrics available at the dashboard: https://app.codecov.io/github/wordpress-mobile/WordPress-Android/

Screenshot 2024-01-12 at 16 39 56

## To Test:

1. Open https://app.codecov.io/github/wordpress-mobile/WordPress-Android/
2. See that for this PR, there's a reprt and it contains some code coverage data for some class from each module:
    - `WordPress`
    - `:libs:image-editor`
    - `:libs:processors`

It's double-check. From what I've browsed, all seems fine. Also, each job on Buildkite reports successful report upload to Codecov.

### Why specify the report file directly?

Codecov couldn't find reports if they were named differently than `report.xml`. So initially, it worked only for a JVM module (`:lib:processors`) but didn't work for e.g. `WordPress`, because the report file is named `reportWordpressVanillaRelease.xml`.

### Why use `CODECOV_TOKEN` if WordPress-Android is a public repository?

It's possible to use Codecov uploader without specifing a token if repository is open source. This approach is flaky though and results with often upload failures. Details are available in this comment and thread: https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by tiagomar — APPROVED** [review]
Thanks for working on this, @wzieba! 🙇 

I could visit the dashboard and confirm there was coverage reported for `WordPress`, `:libs:image-editor` and `:libs:processors`.

> comments on each PR reporting code coverage diff(...)

I assume this would only be visible after being merged to `trunk`.

> Why use CODECOV_TOKEN if WordPress-Android is a public repository?

Thanks for being one step ahead and for sharing the context! 🙇 

Everything looks good to me. :shipit:

**Pull request merged**
