### PR TITLE
Newest comments are shown first in ReaderCommentListActivity

### LINKED ISSUE #4387: Improve Reader experience for posts with lots of comments
A user recently pointed out that it can be difficult to read the latest comments on a post that has a lot of comments on it. For example, if a post has 100+ comments, you have to scroll through all the comments (and wait for them to load) to get to the newest comments at the bottom.

It would be nice if the Reader had a way to easily get back to the latest/unread comments on a post. A couple ideas:
- A way to jump to the latest comments
- Collapse comments the user has already seen (either collapse threaded comments that aren't at the top level of comments, or collapse all read comments)

### PR DESCRIPTION
**Pull request by karambir252**
Fixes #4387 

To test:
1. Go to Followed Sites in Reader Tab on MainActivity
2. Tap on number of comments in any post
3. comments are ordered from newest to oldest by default
4. you can also change the ordering from option menu item checkbox

Needs review:
newest_comment_first menu in ReaderCommentListActivity
ReaderCommentService can load comments from newest to oldest

screenshot_2016-07-20-15-06-52_org wordpress android

### CODE REVIEW

**Comment by karambir252** [comment]
@rachelmcr 
Now newest comments are shown first in ReaderCommentListActivity.

**Comment by nbradbury** [comment]
Hey @karambir252, thanks for tackling this issue!

I'm happy to do a code review, but I've noticed you continuing to make commits to this PR, then closing it, then re-opening it.

If this is ready for review now just let me know - and thanks again for this contribution to our Android app!

**Comment by karambir252** [comment]
@nbradbury 
I noticed some bugs after submitting the pull request. That's why i closed it.
But now it is ready. You can review it and notify me about further issues you found in code.

**Comment by nbradbury** [comment]
Your code is solid - it all works very well and obviously took some time - but I'm not sold on the experience of sorting the comments in reverse. It's very hard to get a feel for the conversation in reverse (with replies always sorted chronologically).

I think a better solution would be to continue to sort comments chronologically, but do as #4387 suggests and find a way to scroll to the last comment (easy with small comment threads, but obviously tricky with longer ones that haven't been cached yet).

**Comment by karambir252** [comment]
@nbradbury 

### That's why when I load a comment in NEWEST_FIRST_ORDER. I am loading all its parent recursively and show the whole conversation in place of new comment. As shown in these pics.

  

  



# Other Solution : 
we can show two tabs to user
1. All comments
2. Unread comments

and bring the whole conversation in unread comments when a new comment is done on a already seen conversation.

## Problem:
We don't know about the new comments on a conversation until we load all comments from server. This will increase data usage and user have to wait until all comments are loaded.
The problem arises because a child comment have a parent_id but a parent comment doesn't have any information about its child comments.

## Solution:
we need a REST API CALL to which we send list of ids of cached parent comments and a timestamp Than in response we get any change in that parent comments and changes in its child comments and its new child comments recursively after that timestamp.
### Its' Advantages : 
1. low data usage => low data cost => Low battery usage because cellular radio consume lots of battery.
2. fast loading time => user have to wait less time.
3. as we are only loading changes in comments(not all 200 comments again) It works well on slow data connection.

**Pull request closed without merging**
