### PR TITLE
[Reader] Improve content navigation and filtering

### PR DESCRIPTION
**Pull request by RenanLukas**
> [!CAUTION]
> **Do not merge** this feature branch until all the task PRs are merged.

Feature branch for the Reader Navigation and Filtering Improvements Project 
Internal ref: pcdRpT-506-p2

This feature branch contains code from PRs that were reviewed and tested individually, and `trunk` sync commits, so everything here is already Code Reviewed. 

Here is the list of PRs included in this branch:
- #19679
- #19816
- #19805
- #19842
- #19862
- #19844
- #19881
- #19856
- #19860
- #19863
- #19929
- #19927
- #19928
- #19882
- #19911
- #19949
- #19960
- #19993
- #19996
- #20059
- #20081
- #20090
- #20057
- #20103
- #20104
- #20114
- #20115
- #20119

-----

## To Test:

Since this feature branch includes several tested PRs (see section above) there are several changes to cover with testing, so it is easier to follow the Test Plan for the whole Reader Navigation and Filtering Improvements Project, which can be found at: p1706977111734119-slack-C05N140C8H5

-----

## Regression Notes

1. Potential unintended areas of impact

    - Any Reader integration/interaction around the app

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Unit tests where applicable
    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - Unit tests where applicable
    - We were not able to add automated tests for some of the new code, but we plan to add it in future PRs (here's an issue to track that: https://github.com/wordpress-mobile/WordPress-Android/issues/20120)

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [ ] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          5 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>TopBarUiState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>FilterUiState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ReaderFilterType</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ReaderFilterSelectedItem</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          7 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>TopBarUiState</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>FilterUiState</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ReaderFilterType</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ReaderFilterSelectedItem</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by thomashorta — APPROVED** [review]
This PR only contains code that was already reviewed and tested in other separated PRs, so I am leaving my approval here.

**Review by develric — APPROVED** [review]
Gave a quick run to the testplan and was ok for me (found only non-blocking issues we tracked already in GH issues 👍 )

**Pull request merged**
