### PR TITLE
Add OkBuck gradle plugin

### PR DESCRIPTION
**Pull request by maxme**
[OkBuck](https://github.com/uber/okbuck) is a gradle plugin that automatically creates buck wrappers and buck configuration files from the gradle files. 

It allows us to build the app without touching a BUCK file, just do:

```shell
$ ./buckw install --run WordPressWasabiDebug
```

It will run gradle the first time and eventually update BUCK config files, then it will run buck to build the project.

Main targets are:
```shell
$ ./buckw install
WordPressZalphaDebug 
WordPressWasabiDebug 
WordPressZalphaRelease 
WordPressVanillaDebug 
WordPressVanillaRelease 
WordPressWasabiRelease
```

Note: Buck is not much faster than Gradle nowadays, but its cache is really great so it makes sense to use it if you swing from branch to branch like a small arboreal monkey.

### CODE REVIEW

**Comment by mzorz** [comment]
> if you swing from branch to branch like a small arboreal monkey.
LOL

**Comment by tonyr59h** [comment]
Hopefully it's safe to ignore changes from d4f014c2346a9ddf7ed1db86e3158773c1956f64 and 6aa329d2c9b81a4cd46c349495ea95be269e65d7 😆

**Comment by tonyr59h** [comment]
Commands are working well. I'll hold off on merging for now, I want to make sure I'm not missing anything important.

**Comment by maxme** [comment]
I actually have to double check `d4f014c`, instead of having symlinks, we want a plain directory and reuse the same files (id -> in, he -> iw, etc.)

**Comment by tonyr59h** [comment]
> I actually have to double check d4f014c

If no more changes are needed this has a thumbs up from me for the merge.

**Comment by maxme** [comment]
I'll close this one and revisit it later, after AS3 and gradle 3.5.

**Pull request closed without merging**
