### PR TITLE
Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ PublishSettingsFragment & PrepublishingHomeViewModel

### PR DESCRIPTION
**Pull request by Hoossayn**
Parent: https://github.com/wordpress-mobile/WordPress-Android/issues/17010

This PR resolves/suppresses all complexity related LongMethod warnings for the PublishSettingsFragment class & PrepublishingHomeViewModel class (see docs [here](https://detekt.dev/docs/rules/complexity#longmethod)):

`2` x LongMethod  (Resolve: 16d4942312a6139c2e65c28175abce7171865907 + ba7f9ccd7e80b96635e93ae17f940550af8fe8b0 + 2725d708cdc366138e97fd63814b30ef63a6e5e6 + eadde85bac5ecd6de5663a04f9f831ca672e1009 + 9bbdd6df26f6e8ca5d04cd803ca824f968e92370 + 66ae4827baf881414b5dccc576a6e710615d4ca9 + b2e6ba103c066bc25eec3fcb46c4c355ffa03d61 + 6fa6603a9fae6d212f04292baadaa879e807075a + 383417fbc6a087f22592a29e963533581dabe479 + 4a661f70fa91795e7b6438f78974b00317bfd531 + 3aac955e7e97a013fed8d5f6d713af4380dd67d8 + 7771a9e469dbbd19b55057e9507ff4c2218c4ce7 )

-----

To test:

- There is nothing much to test here.

- Verifying that all the CI checks are successful should be enough (especially the detekt check).
- However, if you really want to be thorough, you could smoke test the WordPress and/or Jetpack apps to verify that everything works as expected on every screen that relates to these changes. Specifically, you could follow the below steps:

   - Click the FAB(round button at the bottom right corner) to create new post
   - Select site page and choose a layout
   - Click on create page 
   - Click on publish and select publish date 
   - pick a date or publish immediately 

## Regression Notes
1. Potential unintended areas of impact
     can't think of any 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
   See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)
     N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Hoossayn** [comment]
👋🏾 @ParaskP7

**Review by ParaskP7 — APPROVED** [review]
👋 @Hoossayn !

Thank you so much for yet another contribution to WPAndroid with this PR! 🥇 

I have reviewed and tested this PR as per the instructions, along with triggering CI on it via this [draft](https://github.com/wordpress-mobile/WordPress-Android/pull/17443) PR, everything works as expected, good job! 🌟 

Praise (❤️): Let me say this, what an awesome job composing this PR, everything was spot on and kudos for doing such an awesome job, it did make reviewing this PR very pleasant. 💯 

-----

I have only 1 very minor suggestion (💡) for you (see below), that is, just in case you would like to apply it, else we can merge this to `trunk` just as is. Let me know and I'll progress accordingly.

1. Suggestion (💡): How would you feel if the `PublishSettingsFragment.onCreateView(...)` was to be grouped like that below:

```
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val rootView = inflater.inflate(getContentLayout(), container, false) as ViewGroup
        val dateAndTime = rootView.findViewById<TextView>(R.id.publish_time_and_date)
        val dateAndTimeContainer = rootView.findViewById<LinearLayout>(R.id.publish_time_and_date_container)
        val publishNotification = rootView.findViewById<TextView>(R.id.publish_notification)
        val publishNotificationTitle = rootView.findViewById<TextView>(R.id.publish_notification_title)

        AccessibilityUtils.disableHintAnnouncement(dateAndTime)
        AccessibilityUtils.disableHintAnnouncement(publishNotification)
        dateAndTimeContainer.setOnClickListener { showPostDateSelectionDialog() }
        setupContent(rootView, viewModel)

        observeOnDatePicked()
        observeOnPublishedDateChanged()
        observeOnNotificationTime()
        observeOnUiModel(dateAndTime, publishNotificationTitle, publishNotification, rootView)
        observeOnShowNotificationDialog()
        observeOnToast()
        observerOnNotificationAdded()
        observeOnAddToCalendar()

        viewModel.start(getPostRepository())
        return rootView
    }
```

**Comment by Hoossayn** [comment]
> 👋 @Hoossayn !
> 
> Thank you so much for yet another contribution to WPAndroid with this PR! 🥇
> 
> I have reviewed and tested this PR as per the instructions, along with triggering CI on it via this [draft](https://github.com/wordpress-mobile/WordPress-Android/pull/17443) PR, everything works as expected, good job! 🌟
> 
> Praise (❤️): Let me say this, what an awesome job composing this PR, everything was spot on and kudos for doing such an awesome job, it did make reviewing this PR very pleasant. 💯
> 
> I have only 1 very minor suggestion (💡) for you (see below), that is, just in case you would like to apply it, else we can merge this to `trunk` just as is. Let me know and I'll progress accordingly.
> 
> 1. Suggestion (💡): How would you feel if the `PublishSettingsFragment.onCreateView(...)` was to be grouped like that below:
> 
> ```
>     override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
>         val rootView = inflater.inflate(getContentLayout(), container, false) as ViewGroup
>         val dateAndTime = rootView.findViewById<TextView>(R.id.publish_time_and_date)
>         val dateAndTimeContainer = rootView.findViewById<LinearLayout>(R.id.publish_time_and_date_container)
>         val publishNotification = rootView.findViewById<TextView>(R.id.publish_notification)
>         val publishNotificationTitle = rootView.findViewById<TextView>(R.id.publish_notification_title)
> 
>         AccessibilityUtils.disableHintAnnouncement(dateAndTime)
>         AccessibilityUtils.disableHintAnnouncement(publishNotification)
>         dateAndTimeContainer.setOnClickListener { showPostDateSelectionDialog() }
>         setupContent(rootView, viewModel)
> 
>         observeOnDatePicked()
>         observeOnPublishedDateChanged()
>         observeOnNotificationTime()
>         observeOnUiModel(dateAndTime, publishNotificationTitle, publishNotification, rootView)
>         observeOnShowNotificationDialog()
>         observeOnToast()
>         observerOnNotificationAdded()
>         observeOnAddToCalendar()
> 
>         viewModel.start(getPostRepository())
>         return rootView
>     }
> ```

@ParaskP7  thank you for the praise, sure does feel good, i felt the spaces between the function look cool on the eye, however i have implemented your suggestion. thank you once again

**Comment by ParaskP7** [comment]
👋 @Hoossayn !

> @ParaskP7 thank you for the praise, sure does feel good

❤️ 🥇 💯 

> i felt the spaces between the function look cool on the eye, however i have implemented your suggestion. thank you once again

No, thank you, once again! 🙇 

FYI: As soon as CI complete and gets 🟢 I'll merge this PR to `trunk`! 🎉 

PS: Next time, feel free to skip such minor comments, especially if you already thought about them and decided to go another way. We could have merged this PR as it was, even before you applying my suggestion.

**Pull request merged**
