### PR TITLE
Bump :gravatar to 2.0.1

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
This PR bumps the Gravatar SDK to the latest 2.0.0 version. 

On the outside, we made some updates to our public API but under the hood, the avatar upload endpoint was also updated to a v3 version.

Note: I have an issue with one screen during sign-up flow `SignupEpilogueFragment`. When I run `wasabi` flavor this screen automatically finishes and moves to the next one. Testing the `jalapeno` build seems to work fine. I've also asked @hamorillo to test this and it worked okay for him on both variants. Any idea what's happening? I can see the the `wasabi` build is getting some `AccountAction.PUSH_SETTINGS` updates. 

## To Test:

Avatar change flow from the `MeFragment` and `SignupEpilogueFragment`.

1. In the sign-up flow on the `SignupEpilogueFragment` screen.
2. Tap on the add avatar button, pick one and upload. 
3. Once logged in, go to the Me tab.
4. Tap on the avatar.
5. Follow the flow to update the avatar.
6. Go to Gravatar.com and make sure that the avatar was indeed set.

-----

## Regression Notes

1. Potential unintended areas of impact

    - no

-----

## PR Submission Checklist:

~- [ ] I have completed the Regression Notes.~
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

~- [ ] WordPress.com sites and self-hosted Jetpack sites.~
~- [ ] Portrait and landscape orientations.~
~- [ ] Light and dark modes.~
~- [ ] Fonts: Larger, smaller and bold text.~
~- [ ] High contrast.~
~- [ ] Talkback.~
~- [ ] Languages with large words or with letters/accents not frequently used in English.~
~- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
~- [ ] Large and small screen sizes. (Tablet and smaller phones)~
~- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

The update shouldn't affect the UI so the above scenarios are not valid.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nbradbury** [comment]
@AdamGrzybkowski I tested the flow with the Me fragment and it all worked as expected, but I can't seem to get `SignupEpilogueFragment` to appear regardless of the build variant. What do I need to do to get that to show?

**Comment by AdamGrzybkowski** [comment]
>@AdamGrzybkowski I tested the flow with the Me fragment and it all worked as expected, but I can't seem to get SignupEpilogueFragment to appear regardless of the build variant. What do I need to do to get that to show?


@nbradbury I was actually hoping you would help me with this screen as I also struggle with it. 

I mentioned it in the description: 

>Note: I have an issue with one screen during sign-up flow SignupEpilogueFragment. When I run wasabi flavor this screen automatically finishes and moves to the next one. Testing the jalapeno build seems to work fine.

Here's how it looks for me:


https://github.com/user-attachments/assets/63294887-a883-4e5c-b160-f6005d4ce2ce


There's this Dialog with `Updating account` copy that's triggered by something and then the screen is closed.

**Review by nbradbury — APPROVED** [review]
@AdamGrzybkowski Apologies, I've only recently returned to working on the WordPress app after several years away, so I don't have a great understanding of how it all works. In my case I can only get that epilogue screen to show when using a "magic link," and like you I see the screen disappear right away.

But this isn't new behavior related to this PR, so I'm fine approving it. Feel free to merge once the conflicts are resolved.

**Comment by AdamGrzybkowski** [comment]
@hamorillo Given that the Signup screen works for you, would you mind testing this as well?

**Comment by hamorillo** [comment]
🤔 I wonder why the behavior is different for me: 

https://github.com/user-attachments/assets/d9aed627-ae72-4ef1-808a-a351e956c26e

**Pull request merged**
