### PR TITLE
Update Helpshift from 3.12 to 4.1.1-support

### PR DESCRIPTION
**Pull request by maxme**

### CODE REVIEW

**Comment by maxme** [comment]
Just noticed there is a bug with the new Helpshift version, can't attach pictures to support message.

**Comment by maxme** [comment]
Note: Helpshift support contacted

**Comment by kwonye** [comment]
Does the latest `com.helpshift:android-aar:4.2.0-support` fix this? https://developers.helpshift.com/android/release-notes/

**Comment by maxme** [comment]
> Does the latest com.helpshift:android-aar:4.2.0-support fix this?
No

**Comment by maxme** [comment]
HelpShift crashes are now #2 in our top 10, just after the Samsung bug. So, I think we should update to 4.2.0 even with that upload issue.

**Comment by kwonye** [comment]
@maxme the crashes seem to only be photos that are not in local storage. I was able to upload a screenshot fine. I think this is good enough for us.

**Comment by maxme** [comment]
> If you agree, feel free to  anytime you like.

:+1: Let's merge it.

**Comment by kwonye** [comment]
Thanks for keeping our dependencies updated!

**Pull request merged**
