### PR TITLE
Fix #3257: move the help icon out of the LinearLayoutSizeBound

### LINKED ISSUE #3257: Sign In: Top right Help icon is not right aligned in landscape orientation
Nexus 7, OS 5.1.1

To reproduce:
From a fresh install launch the app. 
Dismiss the keyboard and rotate to landscape orientation. 

The top right Help (?) icon stays aligned with the right edge of the text fields rather than the right edge of the screen.  By comparison, if you tap to launch the Help screen, you'll notice the close (X) button is left aligned to the screen edge.

### PR DESCRIPTION
**Pull request by maxme**
Fix #3257 - https://cloudup.com/cCu8tBDRuEr

### CODE REVIEW

**Comment by nbradbury** [comment]
@maxme This looks good, but it's currently failing Travis.

**Comment by maxme** [comment]
@nbradbury I fixed the lint issue in 911182d and I also added button pressed feedback in 869707a
 for secondary buttons and the help button.

**Comment by maxme** [comment]
> This selector can be simplified to:

RIght, updated in 51037a4

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
