### PR TITLE
Feature/plugin browser master

### PR DESCRIPTION
**Pull request by nbradbury**
This PR implements the plugin browser (#7156) and plugin search (#7163). This is a master branch containing code that has already been reviewed, but @oguzkocer will still be reviewing to make sure we've identified any missed issues.

35358906-36c88632-0126-11e8-9d1c-ad1e63c34391

[Here's a demo video](https://cloudup.com/cIjdVOjAM4B) which should help with the design review. Note that the plugin detail is left out of the video since it passed design review already

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Looking great @nbradbury! Should the transition to child pages (Popular, Installed, New, etc) be a lateral push transition? It's hard to tell from the video, but it looks like a really quick cross-fade. // cc @mattmiklic

**Comment by mattmiklic** [comment]
This is looking pretty good! A few design issues I noticed:

screen shot 2018-02-07 at 4 02 01 pm

The Plugin name should all be top-aligned, rather than bottom-aligned, so if the title is only one line, there's extra space under the plugin author name, not above the plugin name. [Compare to this mockup](https://user-images.githubusercontent.com/1396552/35941584-c5478bf6-0c20-11e8-9d8f-3b58c51f0926.png). 

screen shot 2018-02-07 at 4 09 46 pm

List views don't quite line up as expected with the 16dp and 72dp keylines. Screenshot on top, mockup on bottom in the example above. I expected the page title/search field and the plugin names/authors to align to the 72dp keyline.

- The search cancel icon should sit 16dp from the right edge of the screen, right-aligned with the ratings stars that also sit 16dp from the right edge.
- Plugin icons in list view should be 40dp. With 16dp of padding on both sides this will put the related text on the 72dp keyline.
- Ratings stars should use `gridicons-star` at 12dp.

screen shot 2018-02-07 at 4 15 24 pm

- Another couple of small issues here, padding on left/right edges of screen should be 16dp, page title should sit on the 72dp keyline
- The Needs update status should use the `gridicons-sync` icon instead of `gridicons-sync-circled`.
- The wrapping is a little rough on on "Jetpack by Wor / dPress.com." Can we make sure this doesn't insert a line break inside of a word? I realize the long URL string "WordPress.com" is probably the culprit here.

screen shot 2018-02-07 at 4 02 59 pm

When horizontally scrolling, the content being scrolled should disappear off the left edge of the screen; there is currently a ~8dp gap between the edge of the screen and where the scrolling is being clipped.

Other:

Most of the text and colors look good to me, but a few (the section headers on the horizontally-scrolling plugins page are the main ones I noticed) might not be the right size. I'm including a few annotated mockups below so that you have the numbers to double-check. While the font sizes on the mockups are shown in px, they all correspond to one of the sizes [listed here](https://material.io/guidelines/style/typography.html#typography-styles).

screen shot 2018-02-07 at 4 21 14 pm
screen shot 2018-02-07 at 4 23 37 pm

**Comment by suroyo** [comment]
thanks. good

2018-02-08 4:34 GMT+07:00 Matt Miklic <notifications@github.com>:

**Comment by nbradbury** [comment]
@mattmiklic I believe I've corrected everything (see screenshots below) except for two things:

1. I couldn't figure out how to change the position/padding of the search cancel icon, but none of the search cancel icons in the app are right-aligned to 16dp. I'll open a separate issue related to this.

2. In order to get the Android `RatingBar` to use `gridicons-star` we'll need to use PNGs, which requires separate HDPI, XHDPI, and XXHDPI versions of both the filled and unfilled stars, along with three other new files. Nine new files seems like a lot of overhead for a very minor visual change - are you okay with sticking with the stock Android stars?

browser

list

**Comment by oguzkocer** [comment]
@mattmiklic @nbradbury A minor question: The search icon is shown on all screens under plugin directory (site plugins, new plugins, popular plugins and the main screen) however the search feature will always look for the plugins in the directory and not in the section the user is in. I thought this might be confusing especially when the user is in the site plugins page.

Also, when the user taps on the back button while searching for something, we always go back to the main screen for plugin directory, so let's say if they were in the popular plugins and tapped on the search icon, once they try to go back from the search page, they'll lose their position.

I was wondering if it'd made more sense to have the search icon/feature only in the main screen but not while under other screens to avoid both of these issues.

**Comment by nbradbury** [comment]
@oguzkocer I'm okay with dropping the search icon from the list unless the list is displaying search results (in which case we want them to be able to search again without returning to the main screen).

**Comment by mattmiklic** [comment]
@nbradbury Thanks for the fixes! I didn't realize the ratings bar was a standard component, let's definitely use the standard icons rather than creating a mess of PNGs. Good call on that.

@oguzkocer Definitely agree, my intention for the design was to only show the search icon on the main Plugins page.

**Comment by mattmiklic** [comment]
@nbradbury Is it possible to adjust the size of the standard ratings bar? It'd be good to get the stars down to 12px if possible just so they'd be a better size match for the Active/Inactive/etc.

**Comment by nbradbury** [comment]
@mattmiklic There are ways to change the size, but they're hacks with side effects I'd like to avoid. What if I increased the font size for the status to more closely match the ratings bar? Example below.

screenshot_1518546651

**Comment by mattmiklic** [comment]
@nbradbury Yeah, I think that will be OK, just take a look at the "Needs Update" label to make sure it still fits within the 88px-wide space that's available on the main plugins screen. Making a mental note that we'll need to see how this performs with translations that run long.

**Pull request merged**
