### PR TITLE
Fix database migration issue

### LINKED ISSUE #15022: Blogging Reminders: Settings do not remain intact across app version updates.
### Expected behavior
Updating the app will not effect my Blogging Reminders schedule. In other words, if I set up Blogging Reminders, and then update the app to the latest version, I should still receive reminders and see them in My Site > Settings.

### Actual behavior
After updating the app to 17.8-rc-1, I no longer see Blogging Reminders set in My Site > Settings.
However, though Blogging Reminders are not set, publishing a post doesn't trigger the "Set Blogging Reminders" interface.

### Steps to reproduce the behavior
1. Make sure you have 17.7 currently
2. Set up Blogging Reminders
3. Update to 17.8.
4. Check My Site > Settings, and see that Blogging Reminders are not set.
5. Publish a post to try to trigger Blogging Reminders interface.

##### Samsung Galaxy S21, Android 11, WPAndroid 17.7-rc-2 and 17.8-rc-1
Also experienced by @loremattei and @dcalhoun

### PR DESCRIPTION
**Pull request by renanferrari**
Fixes #15022

Please check the corresponding FluxC PR for additional details: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2056

To test:

- Install the version `17.7` of the app.
- Set up some Blogging Reminders.
- Update the app with this build.
- Verify that your Blogging Reminders are still set.

## Regression Notes
1. Potential unintended areas of impact
Plan Offers feature.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
Thanks @renanferrari! I've checked and approved the fluxc companion PR, I'll wait that to be merged/tagged and the fluxc tag to be updated here before to approve this one 🙇 . Just ping me if anything needed on my side sir 👍

**Review by AliSoftware — APPROVED** [review]
Took me some time to test, because Installable Builds from PRs are alpha builds so not the same package as the 17.7 that I initially downloaded from the GitHub Release (to install the old version first and test the upgrade scenario). I then tried to build a vanillaRelease of this PR from my Mac directly (to get a vanilla not a zalpha) but then encountered the case of different code signing (apk from GH Releases are signed with PlayStore cert, local builds are not)… I probably could have re-signed the apks but I'm not yet fluent in that part of Android tooling, so I ended up instead rebuilding a `vanillaRelease` from the `17.7` tag on my Mac, install it, then switch to that branch and rebuild from my Mac again and install over the 17.7. Phew!

Finally, TL;DR was able to check that it fixes it and that my blogging reminders were kept between 17.7 and the 17.8 from that PR 🎉

**Comment by renanferrari** [comment]
@AliSoftware I actually generated a couple of apks to make testing this a bit easier, but I completely forgot to attach them to the PR in the end 🤦‍♂️ Sorry about that, and thanks for taking the time to test it out despite that!

**Comment by AliSoftware** [comment]
FYI this fix just made it to the new 17.8-rc-2 beta send to beta testers! 🎉

**Pull request merged**
