### PR TITLE
Adds analytics for the site intent question screen

### LINKED ISSUE #16047: [Site Intent Question] Analytics tracking
### Description
The following events should be tracked for the [Site Intent Question screen](https://github.com/wordpress-mobile/WordPress-Android/issues/15998):
1. **Cancel/Back** pressed (`enhanced_site_creation_intent_question_canceled`): No properties
2. **Skip** pressed (`enhanced_site_creation_intent_question_skipped`): No properties
3. Vertical **selected** (`enhanced_site_creation_intent_question_vertical_selected`): 2 properties `vertical_id`, `vertical_slug`
4. **Continue** Pressed (`enhanced_site_creation_intent_question_continue_pressed`):  1 property `search_term`
5. **Search** focused (`enhanced_site_creation_intent_question_search_focused`): No properties
6. Screen **viewed** (`enhanced_site_creation_intent_question_viewed`): No properties

Screenshot 2022-03-03 at 5 51 16 PM

### PR DESCRIPTION
**Pull request by antonis**
Fixes #16047

Adds the following new analytics tracking events to the site creation flow:
1. **Cancel/Back** pressed (`enhanced_site_creation_intent_question_canceled`): No properties
2. **Skip** pressed (`enhanced_site_creation_intent_question_skipped`): No properties
3. Vertical **selected** (`enhanced_site_creation_intent_question_vertical_selected`): 2 properties `vertical_id`, `vertical_slug`
4. **Continue** Pressed (`enhanced_site_creation_intent_question_continue_pressed`):  1 property `search_term`
5. **Search** focused (`enhanced_site_creation_intent_question_search_focused`): No properties
6. Screen **viewed** (`enhanced_site_creation_intent_question_viewed`): No properties

Screenshot 2022-03-03 at 5 51 16 PM

## To test:
_For all the tests the [`SITE_INTENT_QUESTION` development feature flag should be enabled](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)_ 

### Screen presented
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. **Verify** that the `enhanced_site_creation_intent_question_viewed` event is emitted

### Back pressed
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Press the **Back** button
4. **Verify** that the `enhanced_site_creation_intent_question_canceled` event is emitted

### Skip pressed
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Press the **Skip** button
4. **Verify** that the `enhanced_site_creation_intent_question_skipped` event is emitted

### Default vertical selected
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Tap on [a default vertical](https://github.com/wordpress-mobile/WordPress-Android/issues/16052)
4. **Verify** that the `enhanced_site_creation_intent_question_vertical_selected` event is emitted with the correct `vertical_id` and `vertical_slug`

### Search focused
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Tap [on the search field](https://github.com/wordpress-mobile/WordPress-Android/issues/16053)
4. **Verify** that the `enhanced_site_creation_intent_question_search_focused` event is emitted

### Search result selected
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Tap [on the search field](https://github.com/wordpress-mobile/WordPress-Android/issues/16053)
4. Type a search term
5. Select one of the results
6. **Verify** that the `enhanced_site_creation_intent_question_vertical_selected` event is emitted with the correct `vertical_id` and `vertical_slug`

### Continue pressed
1. Start the site creation flow
2. Verify the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
3. Tap [on the search field](https://github.com/wordpress-mobile/WordPress-Android/issues/16053)
4. Type a search term
5. Tap on the **Continue** button
6. **Verify** that the `enhanced_site_creation_intent_question_continue_pressed` event is emitted with the correct `search_term`

## Regression Notes
1. Potential unintended areas of impact
N/A

7. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

8. What automated tests I added (or what prevented me from doing so)
Added tests for the emitted events in `SiteCreationIntentsViewModelTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Keeping this PR in draft state till it can be tested properly with the new screen.

**Comment by ovitrif** [comment]
> Keeping this PR in draft state till it can be tested properly with the new screen.

Hey @antonis 👋 
Now that the new Site Intent Question empty screen implementation has been merged, should we progress with this PR as it is and address the events we can't track yet (because there's no UI for triggering their parent actions) with the remaining PRs of the open [Screen UI issues](https://github.com/wordpress-mobile/WordPress-Android/issues/15998)?

The issues also have tracking acceptance criteria 👍

**Comment by antonis** [comment]
Hey @ovitrif 👋 

> Now that the new Site Intent Question empty screen implementation has been merged, should we progress with this PR as it is and address the events we can't track yet (because there's no UI for triggering their parent actions) with the remaining PRs of the open [Screen UI issues](https://github.com/wordpress-mobile/WordPress-Android/issues/15998)?

I updated the PR with e3d4bd547a61eaf3c3ca0929c470f68b5bc10bd0 and confirmed that the three events that can be tracked with the empty screen are tracked properly:

```
🔵 Tracked: enhanced_site_creation_intent_question_viewed
🔵 Tracked: enhanced_site_creation_intent_question_canceled
🔵 Tracked: enhanced_site_creation_intent_question_skipped
```

**Comment by antonis** [comment]
Hey @ovitrif 👋 

> should we progress with this PR as it is and address the events we can't track yet (because there's no UI for triggering their parent actions) with the remaining PRs of the open https://github.com/wordpress-mobile/WordPress-Android/issues/15998?

following your suggestion I added detailed testing steps in the description. We can proceed with testing the first three test cases in this PR and leave the rest for https://github.com/wordpress-mobile/WordPress-Android/issues/16052 and https://github.com/wordpress-mobile/WordPress-Android/issues/16053 (added links to their descriptions).

**Review by ovitrif — APPROVED** [review]
Great work @antonis 👍 

The code LGTM & manual testing the 3 events that are tracked in the current implementation went as expected for me! 🎉 

- Screen presented
- Back pressed
- Skip pressed

I also tested with the feature flag disabled and no events are tracked for the Site Intent Question.

With all this in mind, I think the PR is ready to be merged 🎉

One thing we could still add though, but I don't see it mandatory, is unit test the events tracking via the `SiteCreationIntentsViewModel` methods.

**Comment by antonis** [comment]
Thank you for the prompt review @ovitrif 🙇 

> One thing we could still add though, but I don't see it mandatory, is unit test the events tracking via the `SiteCreationIntentsViewModel` methods.

That's indeed a good idea. I added some tests with f996021987c22340f5216e0e9fb7d9c4c15ba5be. Let me know wdyt 🙏

**Review by ovitrif — APPROVED** [review]
Nice work, thank you for adding the unit tests @antonis 🙇 

Looks ready to merge from my side 🎉 🚀

**Pull request merged**
