### PR TITLE
Use site timezone in the Overview card

### PR DESCRIPTION
**Pull request by planarvoid**
The FluxC changes need to be merged first - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1323

This PR adds a "Site timezone" text to the date selector whenever the site timezone is different that the current timezone. The text is always in `UTC + 5:30` format. You can set the site timezone in wordpress.com settings. 

I've extracted the common UI code for the date selector into a separate file.

This PR also contains the FluxC changes for loading data in the overview card.

Screenshot 2019-07-30 at 10 46 55
Screenshot 2019-07-30 at 10 46 36

To test:
* Change timezone of your site 
* Go to the app
* Check that the Date selector now shows the `Site timezone (UTC + X)` subtitle
* Change the timezone back to your current timezone
* The Date selector doesn't show the Site timezone

To test 2: 
* Change timezone of your site to UTC + 14/-14 (it could be different, but it's the timezone that moves your current date)
* Go to the app
* Reload the stats (if necessary)
* Check that the max date in the Overview card on the Days tab is different than your current date in the app

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Review by khaykov — COMMENTED** [review]
Thanks for the PR, @planarvoid! Timezones are scary :)

I have a couple of comments on functionality:

On a fresh installation, without messing with Site's time zone I see the timezone with only UTC:
[Image from Gyazo](https://gyazo.com/3f82066041c1000f1a7a16cf618d91a7)
I assume I should not see the timezone label at all.

On fresh installation using Site with timezone manually set to my local one, it works as expected.

Changing timezone from the app (from Site Settings) is not reflected in Stats until you restart the app.

After the restart, timezone is correctly reflected, by the max date is not correct (it's Aug 12 in UTC+9 at the time):
[Image from Gyazo](https://gyazo.com/9fc62aea4119ab15e92edfdc33841d09)

Not sure how, but somehow max date eventually changed for me, and I tried to move timezone back to my original one, but the max date was still showing tomorrow.

**Comment by planarvoid** [comment]
thanks for the review @khaykov !

> On a fresh installation, without messing with Site's time zone I see the timezone with only UTC:
> I assume I should not see the timezone label at all.

We show the timezone any time the site timezone != the device timezone. In this case I guess the default site timezone was set to UTC but you're not in UTC timezone. That's why we show the "UTC" as a site timezone. 

> Changing timezone from the app (from Site Settings) is not reflected in Stats until you restart the app.

This might be related to the site not being properly updated when we change the settings. I guess there might be a race condition on the server? There isn't much I can do about this.

> After the restart, timezone is correctly reflected, by the max date is not correct (it's Aug 12 in UTC+9 at the time):
> Not sure how, but somehow max date eventually changed for me, and I tried to move timezone back to my original one, but the max date was still showing tomorrow.

There might be a caching problem, I'll look into it.

**Comment by khaykov** [comment]
> We show the timezone any time the site timezone != the device timezone. In this case I guess the default site timezone was set to UTC but you're not in UTC timezone. That's why we show the "UTC" as a site timezone.

Yep, you are right. I confirmed that default timezone for wpcom sites is UTC+0
+0 part was not there, so I assumed this was some sort of malfunction :)

> This might be related to the site not being properly updated when we change the settings. I guess there might be a race condition on the server? There isn't much I can do about this.

I looked into it a bit more and looks like while we do save site settings remotely, we don't actually get the remote version of the site. But, If you changed the site name, [we will update the local site model and push it to DB](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java#L824). I doubt we can do same with the timezone since we will need a way to translate 
string `America\Los_Angeles` into 7 (as in UTC-7). Alternatively, we can fetch a remote site and hope it will get here before the user navigates to Stats. What do you think?

> I was using the date without the timezone as the key in the in the stats database. I've changed it to use the cached date instead so the overview data should be always up to date.

Works well 👍

**Comment by planarvoid** [comment]
@khaykov thanks for the review!

> default timezone for wpcom sites is UTC+0

I don't know if this is a standard but the `+0` feels wrong :-). I used just UTC because Android uses the same for GMT. I think it's better.

> Alternatively, we can fetch a remote site and hope it will get here before the user navigates to Stats. What do you think?

I've looked into this hard (the settings fragment is difficult) and what I did in the end is fetch a site when you modify the settings. I think it works well. While testing this, please also look into modifying the site title because that part caused me some headaches and I had to change it to a (I think) correct solution. Local mutable SiteModel object is something I think we should avoid :-)

**Review by khaykov — APPROVED** [review]
I tested timezone and site title change and everything works well! Good job figuring it out 👍

**Pull request merged**
