### PR TITLE
Adds descriptive introductory paragraph to Domain Suggestions screen

### LINKED ISSUE #9815: Use Domain Credit
All WordPress.com plans include a custom domain name. This is given to the users as a domain credit, which they can redeem against any valid domain.

This issue is to implement a way for users to redeem their domain credit in the Android app. The flow is included below.

Most of this flow is already implemented via this issue (#9739). The goal here is to expose it on the **My Site** screen. This flow will be hidden behind the DOMAIN_REGISTRATION_ENABLED feature flag.

**Tasks**

- [ ] Create a *Call to Action* on **My Site** screen (#9839)
- [ ] Add reminder message to verify email address when domain registration is completed (#9866)
- [ ] Add descriptive introductory paragraph to **Domain Suggestions** screen (#9865)
- [ ] Add analytics - Would be great to track if people are using this flow and if they are dropping off at any point

DomainCreditFlow

### PR DESCRIPTION
**Pull request by tylermarien**
Fixes #9815 Subtask: Add descriptive introductory paragraph to Domain Suggestions screen

This PR adds an introduction paragraph to the Domain Suggestions screen. The paragraph will disappear when the user starts typing into the search box. It will not reappear if they clear the search box, since it really only needs to be read once. If this behaviour is not correct, please let me know.

To test:
1. Install the wasabi build.
2. Switch to a site on a business plan with unclaimed domain credit (let me know if you need help with this).
3. Navigate to Plugins screen, and from there to details of any plugin (like Woocommerce).
4. Tap on Install button.
5. In the dialog tap on "REGISTER DOMAIN".
6. View the introduction paragraph on the Domain Suggestions screen
7. Start typing in the search box, the introduction paragraph should disappear

Screenshot3

### CODE REVIEW

**Comment by tylermarien** [comment]
Hi @SylvesterWilmott, I just wanted to get your opinion on the animation on this task. I made it so the intro paragraph disappears when you start typing in the search box. It does not re-appear if you clear the search box. My thought was that it was a one time introduction and didn't really need to re-appear in that case. Is this how you wanted it to work? Thanks.

DomainSuggestionsIntro

**Comment by SylvesterWilmott** [comment]
Looking good @tylermarien thanks!

I think we should reverse the animation when the field is cleared to stay consistent with the domain chooser in the site creation flow.

There are also a couple of minor inconsistencies

**Spacing:**

The space above and below the title/subtitle block should be the same
Screenshot 2019-05-21 at 10 43 25

**Colour**

I understand this isn't part of this PR but could we change the colour of the stroke under the field to `#f6f6f6`

**Comment by tylermarien** [comment]
Thanks @SylvesterWilmott. I have updated the animation, padding and colour as requested.

I noticed that the animation is slightly different than the domain chooser on the site creation flow. The one in this flow uses the built in animation. The one on the site creation flow actually slides the intro up underneath the title bar. Should I update this one to be consistent with the site creation flow. I think it might require changing the layout (from RelativeLayout to ConstraintLayout) so I wanted to make sure before I went ahead and did that work.

output2

**Comment by SylvesterWilmott** [comment]
>I noticed that the animation is slightly different than the domain chooser on the site creation flow. The one in this flow uses the built in animation. The one on the site creation flow actually slides the intro up underneath the title bar.

I didn't notice so I doubt our users will. I think what you have here looks great!

I think the search icon and disabled radio buttons may be a different colour than what we have in site creation also. Do you mind confirming this?

**Comment by tylermarien** [comment]
Yep. You are definitely right about the colours @SylvesterWilmott. I updated those colours to be consistent in the site creation. I also noticed that the text size on the list items and the vertical spacing in the search box was different, so I updated those to be more consistent. The were easy changes, so if you don't like them I can switch them back quickly.

It would be nice if we refactored these 2 screens to use the same code since they are basically the same thing with a few copy changes. That is definitely out of the scope of this task though. It might be something that we could create a task for later though. @khaykov

**Comment by SylvesterWilmott** [comment]
LGTM, thanks @tylermarien

**Comment by nbradbury** [comment]
Just a friendly reminder to please make sure to manually merge `develop` into this branch before you merge this PR, as `develop` now contains the AndroidX migration. The automatic merge can succeed but still break the build. Better to find out now before it breaks `develop`. Thanks!

**Comment by khaykov** [comment]
Closing this PR. We updated to AndroidX so I'm going to bring commits in this PR to the current repo so I can make necessary changes, and continue with the feature.

**Pull request closed without merging**
