### PR TITLE
Display list of domains for a site on domains dashboard

### LINKED ISSUE #15358: [Android] Add list of existing domains on the domains dashboard

### PR DESCRIPTION
**Pull request by ravishanker**
Fetch and display list of domains for a site on domains dashboard

Fixes #15358 
Depends on this [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2130)

To test:

- Enable AppSettings -> Debug settings -> SiteDomainsFeatureConfig ✅
- Return to My Site, Notice there's a new item under Configuration -> 🌐 Domains
- Click on Domains, takes your Site Domains Screen
- Notice that it display a list of domains under Your Site Domains
- Test with a site that has more than one domain on the site to see the above screen

NOTE:  Look and feel is not final, will be updated later.

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by renanferrari — COMMENTED** [review]
Thanks for the changes! As I've mentioned in the FluxC PR, this is working as expected 👍

Feel free to ping me once you update the FluxC PR so I can take another look at this. 

Also, I'm adding the `[Status] Not Ready For Merge` label here, since I'm assuming we'd still need to update the FluxC version before merging this to `develop`. Let me know if that's not the case.

**Comment by ravishanker** [comment]
> Thanks for the changes! As I've mentioned in the FluxC PR, this is working as expected 👍
> 
> Feel free to ping me once you update the FluxC PR so I can take another look at this.
> 
> Also, I'm adding the `[Status] Not Ready For Merge` label here, since I'm assuming we'd still need to update the FluxC version before merging this to `develop`. Let me know if that's not the case.

Thanks @renanferrari for adding the label.  This has the latest commit hash for testing.  It needs to be updated with develop-# after merging FluxC PR  to merge this one.

**Comment by thehenrybyrd** [comment]
@ravishanker I was able to test the build today, and ran into a few issues.
I tested only the Domains Dashboard, and had no trouble navigating to it in any case, and no trouble loading the screen. The issues I found seem to mostly be around what information is pulled in and how it is displayed (not the design, but text).

* The domain listed under `Your free WordPress.com address is` cannot be a custom domain. We need to list the actual underlying site address here. The primary domain should probably be labeled separately.
* Domains owned by other users are not shown, while they are shown in Calypso.
* `Get your domain` is sometimes shown even when the domain credit has already been used. This occurs when the domain credit has been used, but the custom domain is not currently primary. We cannot offer a free domain once the domain credit has been used.
* When a plan exists and domain credit has not been used, `Get your domain` still says `domains purchased...will redirect to…`, however if there’s a plan, it won’t be a redirect. We should instead use the text `Claim your free domain` - `You have a free one-year domain registration included with your plan` for this case, as described in design i3.

I also ran into an issue where a few of my sites did not show the extra domains, despite having them. This happened with and without a plan, with and without a custom domain set as primary, and with and without connected (mapped domains). I need to dig into this one further to try to understand the logic of which sites did not show the list of domains.

**Tested on Samsung Galaxy S21, Android 11, WPAndroid pr-15377-build-115913**

**Comment by ravishanker** [comment]
> @ravishanker I was able to test the build today, and ran into a few issues. I tested only the Domains Dashboard, and had no trouble navigating to it in any case, and no trouble loading the screen. The issues I found seem to mostly be around what information is pulled in and how it is displayed (not the design, but text).
> 
>     * The domain listed under `Your free WordPress.com address is` cannot be a custom domain. We need to list the actual underlying site address here. The primary domain should probably be labeled separately.
> 
>     * Domains owned by other users are not shown, while they are shown in Calypso.
> 
>     * `Get your domain` is sometimes shown even when the domain credit has already been used. This occurs when the domain credit has been used, but the custom domain is not currently primary. We cannot offer a free domain once the domain credit has been used.
> 
>     * When a plan exists and domain credit has not been used, `Get your domain` still says `domains purchased...will redirect to…`, however if there’s a plan, it won’t be a redirect. We should instead use the text `Claim your free domain` - `You have a free one-year domain registration included with your plan` for this case, as described in design i3.
> 
> 
> I also ran into an issue where a few of my sites did not show the extra domains, despite having them. This happened with and without a plan, with and without a custom domain set as primary, and with and without connected (mapped domains). I need to dig into this one further to try to understand the logic of which sites did not show the list of domains.
> 
> **Tested on Samsung Galaxy S21, Android 11, WPAndroid pr-15377-build-115913**

@thehenrybyrd Thanks for testting quickly.  Sorry, this PR is not doing all that you have come to expect.  It is only fetching and displaying list of domains for a site part.  
Some of the other stuff is in develop branch or yet to be done.  You could probably test this better when we merge this PR and another one for webview in to develop then you can test off develop branch better and complete the purchase too.

**Review by renanferrari — APPROVED** [review]
Thanks for the changes! Feel free to merge this after bumping the FluxC version.

**Comment by thehenrybyrd** [comment]
@ravishanker looping back around here, I did a bit more testing around sites that _weren't_ showing the list of domains, as I assume the fetching/displaying should be working properly in this PR. 
I wasn't able to reproduce all the situations I initially found, but I did consistently reproduce one case where the list of domains was not shown:

If the underlying site address (the ".wordpress.com" address) is set as primary, any other domains **are not shown**. The _list of domains_ interface is not shown in this case, instead showing "Get your domain".

**Pull request merged**
