### PR TITLE
Feature/material theme and Dark Theme support

### PR DESCRIPTION
**Pull request by khaykov**
This PR moves app to the material theme and adds Dark Theme support.

This is a feature branch and most of the commits were reviewed.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
Hey @khaykov,

I have merged all GB PR's and I have updated GB mobile hash on this PR.
The plan from my side is to test once more and we can merge this branch.

**Comment by marecar3** [comment]
Hey @khaykov,

I have found a bug while testing dark mode which didn't show up when I tested the app over the last week.

OS: Android 8.1
Device: Nexus 5x

1. Open Aztec or Gutenberg Editor
2. Play around with battery saver on/off
3. Screen with "Choose your site will pop up" as unexpected behavior.


ezgif com-video-to-gif (19)

**Comment by marecar3** [comment]
Let's bump this to `14.6` milestone as we want to buy more time for testing this feature.

**Comment by khaykov** [comment]
Thanks for wrangling the merge from develop, @marecar3 ! Looks good to me :)

**Pull request merged**
