### PR TITLE
Remove language from Jetpack migration

### PR DESCRIPTION
**Pull request by nbradbury**
This PR removes language handling from the Jetpack migration flow, since it's now handled by per-app language preferences. This isn't an easy flow to test, but simply eyeballing the code and ensuring the altered tests pass should suffice.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ParaskP7 — APPROVED** [review]
👋 @nbradbury !

I have reviewed this PR as per the instructions (also tested it), everything works as expected, good job! 🌟 

-----

`EXTRAS`

Question (❓): As per [my previous such question](https://github.com/wordpress-mobile/WordPress-Android/pull/21521#discussion_r1883786490) back when I reviewed #21521, what do you think we should do with this `AppInitializer.updateContextLocale(...)` function, which is only used within `WordPress.updateContextLocale(...)`, which only points to `WPLocaleTestRule.changeLocale(...)` and this rule being utilized by `WPScreenshotTest` and `JPScreenshotTest` only. Do you think this rule is still relevant, and if not, let's maybe consider deleting it too as part of this overall feature. 🤔

**Comment by nbradbury** [comment]
> Do you think this rule is still relevant, and if not, let's maybe consider deleting it too as part of this overall feature. 🤔

I think we can definitely remove this - I'll do that in a separate PR.

**Comment by ParaskP7** [comment]
> I think we can definitely remove this - I'll do that in a separate PR.

Awesome, good to know Nick, thanks! 👍

**Pull request merged**
