### PR TITLE
Issue/2844 material tabs

### LINKED ISSUE #2844: Switch to material tabs
Now that #2841 adds the design support library, drop the hackish [SlidingTabLayout](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/SlidingTabLayout.java) (borrowed from IOsched) and use the "official" material [TabLayout](http://developer.android.com/reference/android/support/design/widget/TabLayout.html) instead.

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #2844 - replaces the increasingly hacky [SlidingTabLayout](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/SlidingTabLayout.java) used in WPMainActivity, MediaPickerActivity and ThemeBrowserActivity with the [TabLayout](http://developer.android.com/reference/android/support/design/widget/TabLayout.html) from the design support library.

Also updates ReaderSubsActivity to use TabLayout.

### CODE REVIEW

**Comment by tonyr59h** [comment]
The tabs on landscape phones and portrait/landscape tablets are centered instead of [left aligned](https://github.com/wordpress-mobile/WordPress-Android/pull/2745).

**Comment by nbradbury** [comment]
> The tabs on landscape phones and portrait/landscape tablets are centered instead of left aligned.

That surprised me as well, but that's the default behavior of the new TabLayout so I'm assuming it's the right approach.

**Comment by tonyr59h** [comment]
Centered looks fine on the phone in landscape, but on a tablet I think we need to pad the tab icons along the x-axis. [Here](https://cldup.com/N70A4S2Yq3.png) is what it looks like currently on the tablet. The icons are the same size in landscape orientation. [Googles docs](http://www.google.com/design/spec/components/tabs.html#tabs-usage) seem to take the padding approach as well for icons.

**Comment by nbradbury** [comment]
> on a tablet I think we need to pad the tab icons

Good call - added for both tablet and landscape in cd02955.

**Comment by tonyr59h** [comment]
Looks a lot nicer :+1:

Waiting for Travis now then I'll merge.

**Pull request merged**
