### PR TITLE
Updates for the ticket #6071 add more context to action buttons.

### LINKED ISSUE #6071: Reader: Add more context to action buttons on posts
### Expected behavior

When I navigate the Reader in the Android app with a screen reader, I expect to find more context on buttons.

### Actual behavior

* I found the "Visit" icon button was unlabeled. The word "Visit" lacked context for a screen reader user. I want to know what I'm visiting. This can be combined into one button, labeled with "Visit Post Title Name" "Post Title Name" can be hidden visually.
* The Likes button should be labeled with Like "Post Title Name" Has 77 Likes. Or Like "Post Title Name" No Likes yet. You could also communicate state here. So if a post is in a liked state, it could say: Like "Post Title Name" Pressed Has 77 Likes (or  No Likes yet).
*  Similarly with the Comments button, it needs a more specific label. Comment on "Post Title Name"
* The More button is labeled, but could use more context. "Follow Site Menu" maybe?

### Steps to reproduce the behavior

* Start Talk Back
* Open WordPress app
* Open Reader.
* Begin navigating a list of post by swiping right to navigate forward, reaching the action button area.

##### Tested on [device], Android [version]

* Tested on Nexus 6P, Version Alpha-60.

### PR DESCRIPTION
**Pull request by iegorka**
Fixes #6071 add more context to action buttons.

To test:

### CODE REVIEW

**Comment by nbradbury** [comment]
Welcome back! This all looks good, but I'm not sure about "Following site menu" as the content description for the "..." more icon. How about simply "More..."?

**Comment by iegorka** [comment]
@davidakennedy asked to change this label in the ticket #6071. I can keep the previous version "More".

**Comment by iegorka** [comment]
@nbradbury I'm beginner in GitHub workflow. 
Could you say me how I can added changes for this Pull request? 

I must create another new Pull request for this branch and you will merge or it's possible to do this in easier way?
Or it's better to create Pull request based on the "develop" branch and close this Pull request?
For instance I don't have the permission to push in this branch:
```
WordPress-Android git:(issue/6071-add-more-context-to-action-buttons) git push --set-upstream upstream issue/6071-add-more-context-to-action-buttons
remote: Permission to wordpress-mobile/WordPress-Android.git denied to iegorka.
fatal: unable to access 'https://github.com/wordpress-mobile/WordPress-Android/': The requested URL returned error: 403
```

**Comment by nbradbury** [comment]
You should be able to simply keep making changes in this same branch, then commit those changes. 

If you're like me and find the  git command line unfriendly, I recommend using a git GUI. I use [SourceTree](https://www.sourcetreeapp.com/) but there are several others available.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
