### PR TITLE
Jetpack App (Basics): Update Notifications Colors

### LINKED ISSUE #14307: Jetpack App (Basics): Update Notifications Colors
Parent: #14293

Color Updates:
- Background color: No updates ✅ 
- Notification badge icon color: Update from blue (`primary`) to 🟢 (`colorPrimary`) ✅ 
- Notifications tab badge/dot icon color: Update from pink (`accent`) to 🟢 (`colorPrimary`) ✅ 

The notifications tab badge/dot for the Jetpack app can go 🟢 (from the WordPress app pink dot).
- WordPress: accent (`ping_50` for both the light and dark modes)
- Jetpack: colorPrimary (`jetpack_green_50` for the light mode and `jetpack_green_40` for the dark mode)

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #14307

This PR updates the `Jetpack` related notifications colors based on the latest design feedback.

App/Component | Light Theme | Dark Theme
-----|-----|-----
WordPress/Nav Badge</br>(`#c9356e` for light/dark) | wordpress_nav_badge_light | wordpress_nav_badge_dark
Jetpack/Nav Badge</br>(`#008710` for light)</br>(`#069e08` for dark) | jetpack_nav_badge_light | jetpack_nav_badge_dark
WordPress/Avatar Badge</br>(`#0675c4` for light/dark) | wordpress_avatar_badge_light | wordpress_avatar_badge_dark
Jetpack/Avatar Badge</br>(`#008710` for light)</br>(`#069e08` for dark) | jetpack_avatar_badge_light | jetpack_avatar_badge_dark

**To Test**
- Build, launch and smoke test the accent `pink` nav badge and primary `blue` avatar badge notifications colors for the WordPress app (e.g. wordpressWasabiDebug).
- Build, launch and smoke test the color primary `greens` nav badge and `greens` avatar badge notifications colors for the Jetpack app (e.g. wordpressWasabiDebug).

**Merge Instructions**
- A quick design review by @osullivanchris on the notifications color changes for the Jetpack app.
- Remove `Needs Design Review` label.
- Merge as normal.

## Regression Notes
1. Potential unintended areas of impact ⚪ N/A
2. What I did to test those areas of impact (or what existing automated tests I relied on) 🟢 Manual Testing
3. What automated tests I added (or what prevented me from doing so) ⚪ N/A

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
Looks good, thanks @ParaskP7 

One other suggestion for improvement, as discussed on slack. Its pre-existing with WordPress, so feel free to fix separately.

On dark mode, the border colour for the notification badge should match the tab background, to give the same 'cutout' appearance as light mode. The border colour should remain as white in light mode.

Screenshot 2021-04-22 at 14 45 07

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> Looks good, thanks @ParaskP7

🙏 

> One other suggestion for improvement, as discussed on slack. Its pre-existing with WordPress, so feel free to fix separately.

As discussed on Slack, your 👁️ for detail is 🥇 !

> On dark mode, the border colour for the notification badge should match the tab background, to give the same 'cutout' appearance as light mode. The border colour should remain as white in light mode.

I agree, and will do that change promptly! 🌟

**Review by zwarm — APPROVED** [review]
Looking good @ParaskP7 👍

**Comment by ParaskP7** [comment]
👋 @zwarm !

This PR wasn't fully completed, it was still pending a commit from my side to fix @osullivanchris [tiny little request](https://github.com/wordpress-mobile/WordPress-Android/pull/14514#pullrequestreview-642222310). 😅 

Anyway, we can maybe create a separate issue and deal with that in isolation, would you mind opening this issue @zwarm ? Is that okay @osullivanchris ? 🙏

**Comment by osullivanchris** [comment]
> Anyway, we can maybe create a separate issue and deal with that in isolation, would you mind opening this issue @zwarm ? Is that okay @osullivanchris ? 🙏

That's totally fine for me! It makes sense to be a separate issue anyway as in this case its a fix for both WordPress and Jetpack.

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> That's totally fine for me! It makes sense to be a separate issue anyway as in this case its a fix for both WordPress and Jetpack.

Just an FYI for you, I just created this #14629 issue, included that on the parent #14293 master issue, where we can further track this task there.

**Comment by osullivanchris** [comment]
@ParaskP7 makes sense! Thanks

**Pull request merged**
