### PR TITLE
[Tooling] Limit Jetpack supported locales to only Mag16

### PR DESCRIPTION
**Pull request by AliSoftware**
Internal ref: pxLjZ-7b9-p2

## Why?

While the WordPress app is community-driven and [translated by the community in many locales in GlotPress](https://translate.wordpress.org/projects/apps/android/dev/), the Jetpack app, while based on the same codebase, is an Automattic product whose strings are translated internally by our paid translation vendor, and only in the Mag16 (= the 16 locales we found to be most used)..

We can't really ask the community to translate features that are Jetpack-only like they do for the WordPress app features. But since the Jetpack app shares a lot of screens/features/code with the WordPress app, if we allowed Jetpack to use the translations for all the same locales as WordPress, we could end up with an half-translated Jetpack UI for locales that are not part of the Mag16 (e.g. for someone who has their phone set to `vi`, screens common with WordPress would be translated and in Vietnamese, while Jetpack-only screens would appear in English).

This is why we decided to enforce the Jetpack app binary to only include resource configurations/alternatives for the Mag16 locales — instead of the whole set of locales provided by WordPress' codebase in `src/main/res/values-*`.

Additionally, this helps reduce the app size, by removing unsupported locales in the Jetpack app from the final binary.

## How

This uses `resourceConfigurations` (previously [resConfig](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/BaseFlavor#resConfigs(kotlin.collections.Collection))) to [remove non-Mag16 resource alternatives](https://developer.android.com/studio/build/shrink-code.html#unused-alt-resources) for the Jetpack flavor.

This approach also allowed us to [delete the fallback folders we previously created](https://github.com/wordpress-mobile/WordPress-Android/pull/16902) (by having `src/jetpack/res/values-{locale}/` for non-Mag16 be a copy of `src/jetpack/res/values`), and remove the workaround code (creating those fallbacks) from `fastlane/lanes/localization.rb`.

#### Test WordPress still includes all resources

 - Run `bundle exec fastlane build_bundle app:wordpress version:res-mag16 flavor:Vanilla buildType:Release skip_lint:true` to build the WordPress aab
 - Run `bundletool dump resources --bundle=build/wpandroid-res-mag16.aab --resource=$res` for the various values of `$res` listed in the ➡️ table below, and ensure you get the expected configurations in return <sup>(†)</sup>

#### Test Jetpack only includes resources for Mag16 locales (but still includes `night`, `landscape`, etc)

 - Run `bundle exec fastlane build_bundle app:jetpack version:res-mag16 flavor:Vanilla buildType:Release skip_lint:true` to build the WordPress aab
 - Run `bundletool dump resources --bundle=build/jpandroid-res-mag16.aab --resource=$res` for the various values of `$res` listed in the ➡️ table below, and ensure you get the expected configurations in return <sup>(†)</sup>

<details><summary><sup>(†)</sup> You can use the following shell script to help you with these tests</summary>

```sh
#!/bin/sh

aab=${1:-build/jpandroid-res-mag16.aab}

# Resource => What to expect
# string/app_title => (default), mag16
# dimen/prologue_promo_title_size => (default), smallest_screen_width_dp: 600, orientation: LAND
# string/reader_author_with_blog_name => (default), layout_direction: RTL
# color/placeholder => (default), ui_night_mode: NIGHT

for res in string/app_title dimen/prologue_promo_title_size string/reader_author_with_blog_name color/placeholder; do
  bundletool dump resources --bundle=$aab --resource=$res
done
```
</details>

<details><summary>➡️ Resources to test for <tt>bundletool dump resources</tt> for each app</summary>

And the corresponding expected results (in addition to `(default)`) for each app flavor:

| `$res` | WordPress | Jetpack |
|---|---|---|
| `string/app_title` | 53 locales, including non-Mag16 ones like `vi` | Only Mag16 |
| `dimen/prologue_promo_title_size` | `smallest_screen_width_dp: 600`, `orientation: ORIENTATION_LAND` | _same as WP_
| `string/reader_author_with_blog_name` | `layout_direction: LAYOUT_DIRECTION_RTL` | _same as WP_ |
| `color/placeholder` | `ui_night_mode: UI_MODE_NIGHT_NIGHT` | _same as WP_ |
</details>

#### Test that the new constency check in fastlane works as expected

 - Run `./gradlew printResourceConfigurations`
 - Validate that the last lines prints an array of the Mag16 locales for `jetpack`, and an empty array for `wordpress`
 - Cut a test branch from this PR's branch
 - Run `bundle exec fastlane download_translations`
 - Check that in the logs printed while running that lane, `printResourceConfigurations` is called twice:
    - Once for WordPress (before downloading the WP translations), ending with a message ``No `resourceConfigurations` field set on the `wordpress` flavor to limit the locales. Nothing to check.``
    - Once for Jetpack (before downloading the JP translations), ending with a message like ``The `resourceConfigurations` field set in `build.gradle` for the `jetpack` flavor matches what is set in our Fastfile. All is good!``
 - Modify either the `resourceConfigurations` from `build.gradle`, or the `JP_APP_LOCALES` array to add/remove locales, run the test again, and ensure that this time the lane stops with an error to complain about the configuration inconsistency for Jetpack.
 - Delete your test branch, **both** from your local git **and the remote** — since that test ends up doing a `git push`

#### Test on device

 - Install the Jetpack `aab` on your test device
 - Set your test device to a non-Mag16 locale like Vietnamese
 - Ensure the Jetpack app still shows its UI in English, not Vietnamese
 - Go to Me screen > App Settings > Interface Language and check that the list only lists Mag16 (+ English) and does not contain e.g. Vietnamese.

### CODE REVIEW

**Comment by AliSoftware** [comment]
> Warnings
> ⚠️	PR has more than 300 lines of code changing. Consider splitting into smaller PRs if possible.
> Generated by 🚫 [dangerJS](https://danger.systems/js)

I know Danger, but those >300 lines of change is mostly deletion of all the non-Mag16 `strings.xml` files from `src/jetpack/res/values-{locale}/`, so that's a good thing! 🎉 

image

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> Run bundletool dump resources --bundle=build/wpandroid-res-mag16.aab --resource=$res for the various values of $res listed in the table below, and ensure you get the expected configurations in return (†)

I am currently testing this PR as per the description, quick question on the above step; you are mentioning `$res listed in the table below`, which table are you referring to? 🤔

PS: Kudos on this PR and the testing steps, very thorough, love it! ❤️

**Comment by ParaskP7** [comment]
> I am currently testing this PR as per the description, quick question on the above step; you are mentioning $res listed in the table below, which table are you referring to? 🤔

Ah, got it, I replaced `--resource=$res` with `--resource=string/app_title`, taking it from the comments within the (†).

> Resource => What to expect
> string/app_title => (default), mag16
> dimen/prologue_promo_title_size => (default), smallest_screen_width_dp: 600, orientation: LAND
> string/reader_author_with_blog_name => (default), layout_direction: RTL
> color/placeholder => (default), ui_night_mode: NIGHT

And, now my eye are open as I was looking for the table within the (†) expanding list, but it was within the ➡️ expanding list instead, daaa... 😅

> ➡️ Resources to test for bundletool dump resources for each app

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> Modify either the resourceConfigurations from build.gradle, or the JP_APP_LOCALES array to add/remove locales, run the test again, and ensure that this time the lane stops with an error to complain about the configuration inconsistency for Jetpack.

I tested that and it works! 🎉 

But I am not sure if that is expected or not as you are saying that `the lane should stop with an error` to complain about the configuration inconsistency, but what I am seeing is that `the lane finishes with an error`. Maybe we should actually `stop` the lane with an error (like a 💥 or something, as you also stated) instead of having it `finished` with an error as the release manager might miss the error or ignore it. Wdyt? 🤔

PS: No matter, double kudos on actually adding this e0e26e5b567983646ed80e268dcae2411cd2e58e solution to make sure we remain consistent, well done! ❤️

**Comment by AliSoftware** [comment]
> 👋 @AliSoftware !
> 
> > Modify either the resourceConfigurations from build.gradle, or the JP_APP_LOCALES array to add/remove locales, run the test again, and ensure that this time the lane stops with an error to complain about the configuration inconsistency for Jetpack.
> 
> I tested that and it works! 🎉
> 
> But I am not sure if that is expected or not as you are saying that `the lane should stop with an error` to complain about the configuration inconsistency, but what I am seeing is that `the lane finishes with an error`. Maybe we should actually `stop` the lane with an error (like a 💥 or something, as you also stated) instead of having it `finished` with an error as the release manager might miss the error or ignore it. Wdyt? 🤔
> 
> PS: No matter, double kudos on actually adding this [e0e26e5](https://github.com/wordpress-mobile/WordPress-Android/commit/e0e26e5b567983646ed80e268dcae2411cd2e58e) solution to make sure we remain consistent, well done! ❤️

@ParaskP7 Thanks for taking the time to go through all the test steps!

I'm not sure what you mean by the above though. When an inconsistency is found, the lane triggers a `UI.user_error!`, which is the dedicated method to stop a lane lane with a red message an error state (exit code != 0 and all), not with a finished/success green state… Isn't it what happened during your testing of this case?

image

**Review by ParaskP7 — APPROVED** [review]
👋 @AliSoftware !

I have reviewed and tested this PR as per the instructions, everything works as expected, great work here, love it! 🥇 ❤️ 🚀 

It is a 👍 from my side! ✅ 

-----

As I was reviewing and testing this PR I gathered some comments for you to think, discuss and/or act on:

1. While I was following the `Test on device` instructions, I noticed that I cannot actually test that as you would expect, at least with my WordPress app, as I had no way of setting the `Interface Language` to `System Default`. It was explicitly set to `English (United States)` and now, even if I change the whole device to ie. `Vietnamese` it would not affect it. However, because I didn't do that for Jetpack, when changing the whole device to ie. `Polish`, the `Interface Language` was indeed pointing to `Polski (Polska)` but the app was unaffected by this change, defaulting to `English (United State)` as it doesn't support `Polish` (as expected). This made me wonder if this is an opportunity for us, in a separate PR, to make it explicit that the user can select an extra option from the `Interface Language` that allow them to select `System Default`, something which is not available at the moment. For example/reference, this option is available on the `Appearance` setting. Wdyt? 🤔
2. When I was reviewing the change and comparing the `res` for the various languages on both, WordPress and Jetpack, and then comparing the `Interface Languages` on both, WordPress and Jetpack, I noticed the following that I wanted to share with you just as an FYI (maybe for later as it isn't related to this work):
    - WordPress
        - Interface Languages: 50 + Default [English (United States)] 🤔
        - Res Languages: 53 + Default (values) 🤔
        - Extra Res Folders: 3 🤔
            - `values-he` -> `Hebrew` -> This is similar to 'values-iw', as such a complete duplicate, why, do we need both? 🤔
            - `values-id` -> `Indonesian` -> This is similar to 'values-in', as such a complete duplicate, why, do we need both? 🤔
            - `values-zh` -> `Chinese` -> Maybe it should be 'values-zh-rSG' instead, as it is not shown on the `Interface Languages` anyway, we get there 3/4 shown.
    - Jetpack
        - Interface Language: 16 + Default [English (United States)] ✅ 
        - Res Languages: 16 + Default (values) ✅ 
        - Extra Res Folders: 0 ✅

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> I'm not sure what you mean by the above though. When an inconsistency is found, the lane triggers a UI.user_error!, which is the dedicated method to stop a lane lane with a red message an error state (exit code != 0 and all), not with a finished/success green state… Isn't it what happened during your testing of this case?

Yes, it is happening, but the fastlane completes with 🟢 messages like the below which might not make it obvious that there was an error (see image below), one would need to scroll-up to notice the error, maybe we can somehow make this more obvious, that was my main point. 🤔 Please ignore me if you think this is now an easy and everyone should scroll-up anyway and look at all possible errors or at least 🔴 letters.

image

**Comment by AliSoftware** [comment]
> This made me wonder if this is an opportunity for us, in a separate PR, to make it explicit that the user can select an extra option from the Interface Language that allow them to select System Default, something which is not available at the moment.

Great observation. I'd suggest to open a GitHub issue to track this for the dev team.

In general this in-app Language Switcher will definitively need a revamp at some point as a couple of other issues have been found with it in the past (e.g. the interface orientation not being updated in the app when switching to a RTL language with it, while it would work when switching the language at the System level…). Once we start supporting Android 13, we could even consider remove it entirely, and replace it to a link to the [System's per-app Language Settings](https://developer.android.com/guide/topics/resources/app-languages#app-language-settings)… but we're not there yet.

Past internal ref discussing this: paqN3M-wE-p2 — which references a couple of those other issues, like https://github.com/wordpress-mobile/WordPress-Android/issues/15742 and https://github.com/wordpress-mobile/WordPress-Android/issues/16233, found with that in-app language switcher

> Extra Res Folders: 3 🤔
> - `values-he` -> Hebrew -> This is similar to 'values-iw', as such a complete duplicate, why, do we need both? 🤔
> - `values-id` -> Indonesian -> This is similar to 'values-in', as such a complete duplicate, why, do we need both? 🤔
> - `values-zh` -> Chinese -> Maybe it should be 'values-zh-rSG' instead, as it is not shown on the Interface Languages anyway, we get there 3/4 shown.

Those three folders are actually symlinks (`values-in` -> `values-id`, `values-iw` -> `values-he` and `values-zh` -> `values-zh-rCN` — see `ls -lF` output.

 - The reason for the two first symlinks is because of multiple Android versions used different locale codes for those two locales. See https://github.com/wordpress-mobile/WordPress-Android/pull/10538 for details.
    - I'd have to do some research to find out when (which API level) that change of locale code happened. Maybe if it was a long time ago, and depending on our adoption stats as well, we could reconsider dropping those nowadays… 🤔 
 - The reason for the last one `zh` is because we have `zh-rTW` and `zh-rCN` in GlotPress and in our Mag16, but we don't have a GlotPress entry for the more general `zh` locale.
     - So when downloading translations from GlotPress, those go in `zh-rTW` and `zh-rCN` to be consistent with the fact that we want/need to differentiate the two region-specific variants of Chinese (as there _are_ some significant differences in the two indeed, hence why we don't have just a single `zh` in GlotPress). (See also internal ref pxLjZ-6SD-p2, even if not directly related)
     - But in order for users using yet another regionale variant of Chinese (e.g. `zh-rHK`) for their device to still fallback at runtime to one of the Chinese variants rather than falling back to English, we made this `values-zh` symlink to support that fallback.
     - Now, given that, [since Android 7 (API 24), Android resource resolution strategy was improved significantly](https://developer.android.com/guide/topics/resources/multilingual-support) and would likely automatically still fallback to one of the `zh-r*` childen variant for someone having their device in a `zh-r*` variant we don't include even if we didn't have `values-zh`… maybe it's time to drop the symlink for `values-zh`?

**Comment by AliSoftware** [comment]
> maybe we can somehow make this more obvious, that was my main point. 🤔

Oh I see.

I'd suggest you to declare `export FASTLANE_HIDE_CHANGELOG=1` in your `~/.zshrc` to hide that verbose "fastlane CHANGELOG" output at the end of all your invocations of fastlane when a new version of fastlane was found. Would make things way nicer for every time you run `fastlane` in the future, and make the errors that might have happened higher in the logs easier to spot.

You could also use `export FASTLANE_SKIP_UPDATE_CHECK=1` instead (which is what I personally did in my `~/.zshrc`), to skip the update check entirely. Which would not only avoid the verbose CHANGELOG at the end… but avoid to check for new versions of fastlane altogether.

(All those are documented [here](https://docs.fastlane.tools/advanced/fastlane/))

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> I'd suggest you to declare export FASTLANE_HIDE_CHANGELOG=1 in your ~/.zshrc to hide that verbose "fastlane CHANGELOG" output at the end of all your invocations of fastlane when a new version of fastlane was found. Would make things way nicer for every time you run fastlane in the future, and make the errors that might have happened higher in the logs easier to spot.

Didn't know that, thanks for the tip!

PS: Just tried it and it works like a charm, this makes the errors at the end so much more visible indeed. 💯 

> You could also use export FASTLANE_SKIP_UPDATE_CHECK=1 instead (which is what I personally did in my ~/.zshrc), to skip the update check entirely. Which would not only avoid the verbose CHANGELOG at the end… but avoid to check for new versions of fastlane altogether.

Another great tip, thank you!

> (All those are documented [here](https://docs.fastlane.tools/advanced/fastlane/))

🙇

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> Great observation. I'd suggest to open a GitHub issue to track this for the dev team.

Will do! 👍 

> In general this in-app Language Switcher will definitively need a revamp at some point as a couple of other issues have been found with it in the past (e.g. the interface orientation not being updated in the app when switching to a RTL language with it, while it would work when switching the language at the System level…). Once we start supporting Android 13, we could even consider removed entirely, and replace it to a link to the [System's per-app Language Settings](https://developer.android.com/guide/topics/resources/app-languages#app-language-settings)… but we're not there yet.
> 
> Past internal ref discussing this: paqN3M-wE-p2 (which references a couple of those other issues found with that in-app language switcher)

True... and thanks for referencing past discussions on that here! 🥇 

> Those three folders are actually symlinks (values-in -> values-id, values-iw -> values-he and values-zh -> values-zh-rCN — see ls -lF output.

Oh, I didn't know about them being symlinks, this is good to know! 👍 

> The reason for the two first symlinks is because of multiple Android versions used different locale codes for those two locales. See https://github.com/wordpress-mobile/WordPress-Android/pull/10538 for details.
I'd have to do some research to find out when (which API level) that change of locale code happened. Maybe if it was a long time ago, and depending on our adoption stats as well, we could reconsider dropping those nowadays… 🤔

Oh, thanks for sharing the closed issue, this is very interesting! 💰 

> The reason for the last one zh is because we have zh-rTW and zh-rCN in GlotPress and in our Mag16, but we don't have a GlotPress entry for the more general zh locale.
> - So when downloading translations from GlotPress, those go in zh-rTW and zh-rCN to be consistent with the fact that we want/need to differentiate the two region-specific variants of Chinese (as there are some significant differences in the two indeed, hence why we don't have just a single zh in GlotPress). (See also internal ref pxLjZ-6SD-p2, even if not directly related)
> - But in order for users using yet another regionale variant of Chinese (e.g. zh-rHK) for their device to still fallback at runtime to one of the Chinese variants rather than falling back to English, we made this values-zh symlink to support that fallback.
> - Now, given that, [since Android 7 (API 24), Android resource resolution strategy was improved significantly](https://developer.android.com/guide/topics/resources/multilingual-support) and would likely automatically still fallback to one of the zh-r* childen variant for someone having their device in a zh-r* variant we don't include even if we didn't have values-zh… maybe it's time to drop the symlink for values-zh?

Thank you so much for sharing all this context on all that, so much appreciated, everything makes sense to me now! 🙇 

PS: Yes, maybe, when we get some extra time, we should figure out if we could improve on all aspects of what is shared here so that to avoid having to explain all that again in some other such PR to some other such curious engineer like myself. 😅

**Pull request merged**
