### PR TITLE
Issue/8649 add analytics tracking

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add analytics tracking for new ***Quick Start*** tasks and actions as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8649.  The following were added and removed:
#### Added
Code|Event|Key|Value
-|-|-|-
`QUICK_START_MIGRATION_DIALOG_VIEWED`|`quick_start_migration_dialog_viewed`|-|-
`QUICK_START_MIGRATION_DIALOG_POSITIVE_TAPPED`|`quick_start_migration_dialog_positive_tapped`|`type`|`positive`
`QUICK_START_REMOVE_DIALOG_NEGATIVE_TAPPED`|`quick_start_remove_dialog_button_tapped`|`type`|`negative`
`QUICK_START_REMOVE_DIALOG_POSITIVE_TAPPED`|`quick_start_remove_dialog_button_tapped`|`type`|`positive`
`QUICK_START_TYPE_CUSTOMIZE_VIEWED`|`quick_start_list_viewed`|`type`|`customize`
`QUICK_START_TYPE_GROW_VIEWED`|`quick_start_list_viewed`|`type`|`grow`
`QUICK_START_TYPE_CUSTOMIZE_DISMISSED`|`quick_start_type_dismissed`|`type`|`customize`
`QUICK_START_TYPE_GROW_DISMISSED`|`quick_start_type_dismissed`|`type`|`grow`
`QUICK_START_LIST_CUSTOMIZE_COLLAPSED`|`quick_start_list_collapsed`|`type`|`customize`
`QUICK_START_LIST_GROW_COLLAPSED`|`quick_start_list_collapsed`|`type`|`grow`
`QUICK_START_LIST_CUSTOMIZE_EXPANDED`|`quick_start_list_expanded`|`type`|`customize`
`QUICK_START_LIST_GROW_EXPANDED`|`quick_start_list_expanded`|`type`|`grow`
`QUICK_START_LIST_UPLOAD_ICON_TAPPED`|`quick_start_list_item_tapped`|`task_name`|`upload_icon`
`QUICK_START_LIST_CREATE_PAGE_TAPPED`|`quick_start_list_item_tapped`|`task_name`|`create_page`
`QUICK_START_LIST_CHECK_STATS_TAPPED`|`quick_start_list_item_tapped`|`task_name`|`check_stats`
`QUICK_START_LIST_EXPLORE_PLANS_TAPPED`|`quick_start_list_item_tapped`|`task_name`|`explore_plans`
`QUICK_START_LIST_CREATE_SITE_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`create_site`
`QUICK_START_LIST_VIEW_SITE_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`view_site`
`QUICK_START_LIST_BROWSE_THEMES_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`browse_themes`
`QUICK_START_LIST_CUSTOMIZE_SITE_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`customize_site`
`QUICK_START_LIST_ADD_SOCIAL_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`share_site`
`QUICK_START_LIST_PUBLISH_POST_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`publish_post`
`QUICK_START_LIST_FOLLOW_SITE_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`follow_site`
`QUICK_START_LIST_UPLOAD_ICON_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`upload_icon`
`QUICK_START_LIST_CREATE_PAGE_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`create_page`
`QUICK_START_LIST_CHECK_STATS_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`check_stats`
`QUICK_START_LIST_EXPLORE_PLANS_SKIPPED`|`quick_start_list_item_skipped`|`task_name`|`explore_plans`
`QUICK_START_UPLOAD_ICON_COMPLETED`|`quick_start_task_completed`|`task_name`|`upload_icon`
`QUICK_START_CREATE_PAGE_COMPLETED`|`quick_start_task_completed`|`task_name`|`create_page`
`QUICK_START_CHECK_STATS_COMPLETED`|`quick_start_task_completed`|`task_name`|`check_stats`
`QUICK_START_EXPLORE_PLANS_COMPLETED`|`quick_start_task_completed`|`task_name`|`explore_plans`
`QUICK_START_NOTIFICATION_DISMISSED`|`quick_start_tnotification_dismissed`|-|-
`QUICK_START_NOTIFICATION_SENT`|`quick_start_tnotification_sent`|-|-
`QUICK_START_NOTIFICATION_TAPPED`|`quick_start_tnotification_tapped`|-|-

#### Removed
Code|Event|Key|Value
-|-|-|-
`QUICK_START_LIST_COMPLETED_VIEWED`|`quick_start_list_completed_viewed`|-|-
`QUICK_START_LIST_SKIP_ALL_TAPPED`|`quick_start_list_skip_all_tapped`|-|-
`QUICK_START_LIST_COMPLETED_VIEWED`|`quick_start_list_completed_viewed`|-|-

`QUICK_START_LIST_VIEWED` was replaced by `QUICK_START_TYPE_CUSTOMIZE_VIEWED`and `QUICK_START_TYPE_GROW_VIEWED`, which use the same `quick_start_list_viewed` event with the `customize` and `grow` values respectively for the `type` key.  `QUICK_START_LIST_SKIP_ALL_TAPPED` is no longer applicable since we can only skip tasks individually and not all at once.  `QUICK_START_LIST_COMPLETED_VIEWED` is no longer applicable since the view on the ***Sites*** tab isn't removed after viewing the completed list.

### Test
The best way to test this with a debug build is to set breakpoints on the `AnalyticsTracker.track(AnalyticsTracker.Stat)` lines, perform the actions, and see if the code breaks at that point.  The steps for each action are below.

#### Migration Dialog Viewed
0. Run app with 5c034b4ac314a8bfe89e6a1a953993ab40fb4d7f.
1. Go to ***Sites*** tab.
2. Tap ***Switch Site*** button.
3. Tap ***Add new site*** action.
4. Tap ***Create WordPress.com site*** option.
5. Follow site creation steps.
6. Tap ***Configure*** button.
7. Notice ***Want a little help getting started?*** dialog is shown.
8. Tap ***Accept*** action.
9. Go to ***Reader***, ***Me***, or ***Notifications*** tab.
10. Run app with `issue/8649-add-analytics-tracking`.
11. Go to ***Sites*** tab.
12. Notice ***We've made some changes to your checklist*** dialog is shown.
13. Notice [`QUICK_START_MIGRATION_DIALOG_VIEWED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L1326) is tracked.

#### Migration Dialog Positive Tapped
14. Tap ***OK*** button.
15. Notice [`QUICK_START_MIGRATION_DIALOG_POSITIVE_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L1055) is tracked.

#### Remove Dialog Negative Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ellipsis menu button in ***Next Steps*** view.
2. Notice ***Remove Next Steps*** dialog is shown.
3. Tap ***Cancel*** button.
4. Notice [`QUICK_START_REMOVE_DIALOG_NEGATIVE_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L1100) is tracked.

#### Remove Dialog Positive Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ellipsis menu button in ***Next Steps*** view.
2. Notice ***Remove Next Steps*** dialog is shown.
3. Tap ***Remove*** button.
4. Notice [`QUICK_START_REMOVE_DIALOG_POSITIVE_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L1058) is tracked.

#### Type Customize Viewed
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Notice [`QUICK_START_TYPE_CUSTOMIZE_VIEWED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L86) is tracked.

#### Type Grow Viewed
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Notice [`QUICK_START_TYPE_GROW_VIEWED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L92) is tracked.

#### Type Customize Dismissed
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap ***X*** action in top app bar.
3. Notice [`QUICK_START_TYPE_CUSTOMIZE_DISMISSED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L137) is tracked.

#### Type Grow Dismissed
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap ***X*** action in top app bar.
3. Notice [`QUICK_START_TYPE_GROW_DISMISSED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L140) is tracked.

#### List Customize Collapsed
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap chevron to expand completed task view.
3. Tap chevron to collapse completed task view.
4. Notice [`QUICK_START_LIST_CUSTOMIZE_COLLAPSED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L192) is tracked.

#### List Grow Collapsed
0. Run app with Quick Start v2 in progress and at least one task completed.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap chevron to expand completed task view.
3. Tap chevron to collapse completed task view.
4. Notice [`QUICK_START_LIST_GROW_COLLAPSED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L196) is tracked.

#### List Customize Expanded
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap chevron to expand completed task view.
3. Notice [`QUICK_START_LIST_CUSTOMIZE_EXPANDED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L191) is tracked.

#### List Grow Expanded
0. Run app with Quick Start v2 in progress and at least one task completed.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap chevron to expand completed task view.
3. Notice [`QUICK_START_LIST_GROW_EXPANDED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java#L195) is tracked.

#### List Upload Icon Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap ***Upload a site icon*** task.
3. Notice [`QUICK_START_LIST_UPLOAD_ICON_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L252) is tracked.

#### List Create Page Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap ***Create a new page*** task.
3. Notice [`QUICK_START_LIST_CREATE_PAGE_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L253) is tracked.

#### List Check Stats Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap ***Check your site stats*** task.
3. Notice [`QUICK_START_LIST_CHECK_STATS_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L254) is tracked.

#### List Explore Plans Tapped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap ***Explore plans*** task.
3. Notice [`QUICK_START_LIST_EXPLORE_PLANS_TAPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L255) is tracked.

#### List Create Site Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ***Create your site*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_CREATE_SITE_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L263) is tracked.

#### List Upload Icon Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ***Upload a site icon*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_UPLOAD_ICON_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L270) is tracked.

#### List Browse Themes Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ***Browse themes*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_BROWSE_THEMES_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L265) is tracked.

#### List Customize Site Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ***Customize your site*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_CUSTOMIZE_SITE_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L266) is tracked.

#### List Create Page Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ****** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_CREATE_PAGE_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L271) is tracked.

#### List View Site Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Long-press ***View your site*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_VIEW_SITE_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L264) is tracked.

#### List Add Social Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Long-press ***Enable post sharing*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_ADD_SOCIAL_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L267) is tracked.

#### List Publish Post Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Long-press ***Publish a post*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_PUBLISH_POST_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L268) is tracked.

#### List Follow Site Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Long-press ***Follow other sites*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_FOLLOW_SITE_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L269) is tracked.

#### List Check Stats Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Long-press ***Check your site stats*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_CHECK_STATS_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L272) is tracked.

#### List Explore Plans Skipped
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Long-press ***Explore plans*** task.
3. Tap ***Skip task*** action.
4. Notice [`QUICK_START_LIST_EXPLORE_PLANS_SKIPPED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L273) is tracked.

#### Upload Icon Completed
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap ***Upload a site icon*** task.
3. Follow task prompts to complete task.
4. Notice [`QUICK_START_UPLOAD_ICON_COMPLETED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L287) is tracked.

#### Create Page Completed
0. Run app with Quick Start v2 in progress.
1. Tap ***Customize Your Site*** item in ***Next Steps*** view.
2. Tap ***Create a new page*** task.
3. Follow task prompts to complete task.
4. Notice [`QUICK_START_CREATE_PAGE_COMPLETED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L288) is tracked.

#### Check Stats Completed
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap ***Check you site stats*** task.
3. Follow task prompts to complete task.
4. Notice [`QUICK_START_CHECK_STATS_COMPLETED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L289) is tracked.

#### Explore Plans Completed
0. Run app with Quick Start v2 in progress.
1. Tap ***Grow Your Audience*** item in ***Next Steps*** view.
2. Tap ***Explore plans*** task.
3. Follow task prompts to complete task.
4. Notice [`QUICK_START_EXPLORE_PLANS_COMPLETED`](https://github.com/wordpress-mobile/WordPress-Android/blob/3ec2264ab62f2b74eb55dc6a14a69b0c675e52e8/WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt#L290) is tracked.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by theck13** [comment]
Yeah, good point.  Do you think I should remove it or leave it for completeness?

**Comment by khaykov** [comment]
I would personally leave it and add a comment. If it's not there someone at some point will notice it, and if it's there but does nothing someone will notice it too :)

**Comment by theck13** [comment]
Sounds good.  I added a comment in b29bad5.

**Comment by SylvesterWilmott** [comment]
LGTM, thanks!! :shipit:

**Pull request merged**
