### PR TITLE
Issue/10642 material plans and domains

### LINKED ISSUE #10642: Implement Material theme on Plans and Domain Registration Screens
We should switch widgets used at Plans and Domain Registration screens to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10642 

This PR moves Plans and Domain Registration screens to Material Theme and adds Dark Theme support.

Plans is a really small part of the app, so I bundled it with Domain Registration flow.

While refactoring is not in the scope of this PR, since I touched those files, I cleaned up/optimized some of the redundant code as suggested by AS, so do not be alarmed by the size of the PR. I suggest turning on the "Hide whitespace changes" option during the review.

There is a huge amount of PRs in this feature that covers all the screens within the app, so I'm requesting reviews from a wide variety of people.

comparison_plans
comparison_domains

To test:
- Navigate to Plans screen and confirm it's visual and functional integrity in both Light and Dark themes. 
- Using a site with unclaimed domain credit, Navigate to Domain Registration screen and confirm it's visual and functional integrity in both Light and Dark themes. There are no functional changes to domain registration flow, so you might choose not to register an actual domain name, instead, you can add following line `mainViewModel.completeDomainRegistration(DomainRegistrationCompletedEvent("super-test-domain.com", "super-test-email@wordpress.org"))` 
to the end of the method like `onViewCreated`  in `DomainRegistrationDetailsFragment` to skip to the final screen.
The theme can be changed from App Settings.

PR submission checklist:
- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@mattmiklic Good catch! The wrong color snuck back in accidentally 😅 
I changed the margins around start/end of a button from 12 to 16 dp.

comparison_comments_2

**Comment by mattmiklic** [comment]
Thanks! This looks great now.

**Comment by jkmassel** [comment]
I'm moving this PR to 14.1 since we're code freezing today.

**Comment by khaykov** [comment]
Thanks for the review, @malinajirka ! 

> The color of the selector seems off

Good catch! That button was still using `AppCompat` version :)

> The selector is displayed under the text

There is nothing special about that radio button, so I assume that's how it's actually implemented. Also the color of the radio button is correct 👍 

The login flow is still not converted to the material theme, so that weird thing at the top will be gone.

Regarding pull to refresh style, I checked the styling options for it, and decided to implement it as a separate issue, since it involves submodule (#11085)

**Pull request merged**
