### PR TITLE
Fix upload notification not shown on retry

### LINKED ISSUE #9951: Uploading post system notification not displayed on retry
### Expected behavior
When a retry upload action is triggered the system notification is displayed.

### Actual behavior
When a retry upload action is triggered the system notification is not displayed.

### Steps to reproduce the behavior
1. Turn on airplane mode
2. My Site -> Blog Posts -> Drafts tab
3. Create a local draft
4. Turn off airplane mode - `LocalDraftUploadStarter` will automatically trigger retry
5. Notice there is no system notification, but the "local draft" label disappears when the post gets uploaded

##### Tested on [device], Android [version], WPAndroid [version]
Reproduced on `77168a33e87507a470a823f7744b9ceca3fa5af9`.
Emulator API 26

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9951 

This PR takes care of promoting the UploadService to the foreground (shows an upload in progress notification) when retrying upload.

I've removed this line
`mPostUploadNotifier.removePostInfoFromForegroundNotificationData(post, mediaToRetry);`
but tbh I'm not sure what was the initial purpose of the line. I haven't find any reason why we need to invoke it on this place. If I keep it there, the upload notification will always show "1 post remaining" even when I invoke retry on three posts.
Imagine we have 3 posts
1. First post increases `sNotificationData.mTotalPostItems` to 1
2. Second post invokes `mPostUploadNotifier.removePostInfoFromForegroundNotificationData(post, mediaToRetry);` -> decreases `sNotificationData.mTotalPostItems` to 0 -> and increases it back to 1
3. Third post also decreases it to 0 and back to 1
4. The notification shows "1 post remaining" even when there are actually 3 posts being uploaded

To test:
retry-notification-2
1. Turn on airplane mode
2. Create a local draft
3. Turn off airplane mode and notice the upload notification is being shown
--------------
1. Turn on airplane mode
2. Create 3 local drafts
3. Turn off airplane mode and notice the upload notification (3 posts remaining) is being shown
--------------
retry-notification

1. Open editor
2. Enter title
3. Press back and turn on airplane mode asap
4. Wait until the upload fails
5. Turn off airplane mode and notice the upload notification is shown
----------------
1. Open editor and enter title
2. Press back and turn on airplane mode asap
3. Open editor and enter title
4. Turn off airplane mode, press back and turn on airplane mode (you might want to set network type to GPRS in emulator settings so the draft from step 2 doesn't get uploaded)
5. Wait until the upload fails
6. Turn off airplane mode and notice the upload notification (2 posts remaining) is shown

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by malinajirka** [comment]
Woow, thank you so much for the thorough review and for the great suggestions!

>Problem A

I've applied your patch. Thanks!!

>Problem B:

This was recently fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9962.

>Problem C:

I've created a new issue - https://github.com/wordpress-mobile/WordPress-Android/issues/9966.


Thanks @mzorz! I have just applied your patch and tested the app and it LGTM! It's ready for another round/merge. 🙇

**Comment by loremattei** [comment]
Hey! I'm moving this to 12.7 since 12.6 has been cut. If you want it to land 12.6, please feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by nbradbury** [comment]
Just a friendly reminder to please make sure to manually merge `develop` into this branch before you merge this PR, as `develop` now contains the AndroidX migration. The automatic merge can succeed but still break the build. Better to find out now before it breaks `develop`. Thanks!

**Comment by malinajirka** [comment]
Thanks @mzorz !;) I've merged develop into the branch + I verified everything is migrated to AndroidX (no changes were required). I've also updated release notes - moved the note about this fix into 12.7.

**Comment by malinajirka** [comment]
I'm merging this as the PR has been approved. 🚢

**Pull request merged**
