### PR TITLE
Feature/deep link main activity

### LINKED ISSUE #6313: Handle upcoming stats, notification, and editor app banner deep links
https://github.com/Automattic/wp-calypso/issues/15228 will add app banner deep links. We already handle the reader one. We have to add stats, notifications, and editor deep links.

Details of scheme here: https://github.com/Automattic/wp-calypso/pull/16124#issuecomment-315650955

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #6313

To test:

Go to the following sections of WordPress.com with the app installed and logged in

Reader and verify when clicking the app banner it goes to the Reader
Stats and verify when clicking the app banner it goes to stats
Editor and verify when clicking the app banner it goes to the editor
Notifications and verify when clicking the app banner it goes to notifications

Solution that we'll ship for 11.2. We still plan on moving all the logic to `DeepLinkingIntentReceiverActivity`.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @kwonye! I hope this feature will bring new users to our apps ;-).

>Stats and verify when clicking the app banner it goes to stats

The `mSelectedSite` is sometimes not initialised yet and an error occurs. Maybe adding `initSelectedSite()` into the `handleAppBannerDeepLink()` would do the trick. Wdyt?

>Notifications and verify when clicking the app banner it goes to notifications

I don't see any banner in the Notifications section in the browser. Any ideas why?


I've talked to Lorenzo and he'll let me know before they cut 11.2 so we can make sure this feature is merged by then. If you are not online by that time, I'll commit the fixes myself, but I want to do that only as a last resort.

Note: Travis keeps failing on `line too long` in `ReaderPostpagerActivity:262.

**Comment by malinajirka** [comment]
@kwonye I'm sorry for committing a code into your branch, but I wanted to merge this branch before version 11.2 was cut. 

Changes:
- I fixed 'line too long' error
- I added `initSelectedSite()` into `handleAppBannerDeepLink()` to make sure the mSelectedSite is initialized -> an error was occurring when the Stats section was opened from a deeplink

**Comment by kwonye** [comment]
Perfect, thanks!

**Comment by kwonye** [comment]
> I don't see any banner in the Notifications section in the browser. Any ideas why?

I don't either, the web may have changed something. That said, our app handles it for when it does come back. I'll investigate. Here's the link for reference:

```intent://notifications/#Intent;scheme=wordpress;package=org.wordpress.android;end```

**Pull request merged**
