### PR TITLE
Issue/publicize broken connections

### PR DESCRIPTION
**Pull request by kwonye**
This is similar to @aerych's change https://github.com/wordpress-mobile/WordPress-iOS/pull/10965

What this does is when a user has a broken connection (triggered by changing line 111 in `PublicizeConnectionAdapter` to `ConnectStatus status = ConnectStatus.BROKEN;`), it triggers a reconnect path.

What happens in reconnect is we disconnect the current connection and start up a new connection.

Full disclosure: Publicize is very broken and I don't even know if this change is worth it. It may be worth looking into a comprehensive fix to also address #8652. @aerych let me know what you think.

### CODE REVIEW

**Comment by kwonye** [comment]
@aerych heads up, I intentionally did not assign a milestone to this because of my concerns stated above.

**Comment by aerych** [comment]
> Publicize is very broken and I don't even know if this change is worth it

I'd say still worth it as a bandaid to make sure users with affected connections have a path forward in the app. 
That said, as far as I can tell we don't show any kind of status indicator to flag a non `ok` status connection so it would be nice to follow up with a more comprehensive patch, plus whatever else you saw wasn't working right.

**Comment by aerych** [comment]
I pushed two commits with @kwonye's blessing.  The changes will treat any unexpected status as broken and default the user into the reconnect flow.  

To test this branch I first hard coded the status I wanted to test and then checked to see what the details screen would show for the connect button. OK and MUST DISCONNECT statuses should end up in the disconnection flow.  BROKEN and any other status should end up in the reconnect flow.  

For a final test I used my own test account that has a good Tumblr connection and a linkedin connection with the new 'must_reauth' status.  I saw the disconnect button for Tumblr, and the reconnect button for linkedin, as expected. 

Changes look good @kwonye! (Please double check my additions yourself!)  We need to target 11.8 so we can cherry pick the commits in to a new branch and then it'll be good to go!

**Comment by kwonye** [comment]
Thanks! Appreciate you merging your changes in. Because this change needs to be in 11.8 I'll be deleting this PR and opening a new one.

**Pull request closed without merging**
