### PR TITLE
Fix a minor visual issue in the reader post cards

### PR DESCRIPTION
**Pull request by maxme**
To test: Open the reader, make sure the "visit" icon is vertically aligned with the other elements.

LTR1
RTL1

Update release notes: this is a very minor fix, should I update the release notes?

### CODE REVIEW

**Comment by theck13** [comment]
> Update release notes: this is a very minor fix, should I update the release notes?

Also, I don't think this change needs an entry in the release notes.

**Comment by SylvesterWilmott** [comment]
Looks good @maxme !

While we're here, do you think we could also align the site name + date to the 72dp keyline?

**Comment by maxme** [comment]
> Thanks for spotting and fixing this!
> 
> We only need to add `android:paddingStart="@dimen/margin_medium"` to the `visit` `LinearLayout` view. The rest of the changes can be reverted. We want to keep the asymmetrical `marginEnd` and `marginStart` on the `image_visit_icon` `ImageView`. The start padding and asymmetrical margins will allow the icon to line up vertically with the starting edge of the text above it while giving a little space between the icon and the "Visit" text. See the screenshots below for illustration.

Ok got it, updated in  c645635

**Comment by maxme** [comment]
> While we're here, do you think we could also align the site name + date to the 72dp keyline?


Updated the site name / date alignment - also updated site header ("Discover") alignment:

site-name-72dp

**Comment by mattmiklic** [comment]
Thank you for this one! Looks so much cleaner now.

**Comment by SylvesterWilmott** [comment]
Thanks @maxme , looks great!

**Pull request merged**
