### PR TITLE
Set explicit locale when constructing rest path.

### LINKED ISSUE #4342: Error 404 when replying to comments with device language set to Arabic or Farsi (Persian)
### Expected behavior

Users should be able to reply to comments (e.g. from the notifications comment detail view) no matter what device language they use.
### Actual behavior

Comment replies fail when the device language is set to Arabic or Farsi (Persian).

Replies work as expected with other languages (tested in Spanish and Hebrew) or with the device language set to English and keyboard language set to Arabic.

I get this error when I try to reply to a comment with my device language set to Farsi:

```
07-04 13:07:06.996 11904-11947/? E/WordPress: [11795] BasicNetwork.performRequest: Unexpected response code 404 for https://public-api.wordpress.com/rest/v1/sites/۷۶۰۲۶۹۶۲/comments/۳۷/replies/new?locale=fa_IR
07-04 13:07:07.010 11904-11904/? E/WordPress-COMMENTS: com.android.volley.ServerError
                                                           at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
                                                           at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
```

It looks like the issue is that these languages use different numerals, so the site ID and comment ID in the API request are being sent in the wrong numeral system.
### Steps to reproduce the behavior
1. On a WordPress.com or Jetpack blog, leave a comment (to trigger a notification)
2. In the app, open the comment notification and approve the comment if needed
3. Reply to the comment. Result: Comment is successfully published.
4. In the device settings, switch the language to Arabic or Farsi (Persian)
5. Return to the app and reply to the comment. Result: Comment fails.
##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-16

Reported by a user in 114004-h using WPAndroid 5.5 (h/t Sandy for the report)

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #4342 

To test:

1. On a WordPress.com or Jetpack blog, leave a comment (to trigger a notification)
2. In the app, open the comment notification and approve the comment if needed
3. Reply to the comment. Result: Comment is successfully published.
4. In the device settings, switch the language to Arabic or Farsi (Persian)
5. Return to the app and reply to the comment. Result:Comment is successfully published

Because we didn't explicitly set a locale while making a rest path for notification comment reply, the resulting url might have contained non latin numbers.

### CODE REVIEW

**Comment by maxme** [comment]
I'll turn the `DefaultLocale` lint check to an error in FluxC, it's not the first time we have this kind of bug.

**Comment by maxme** [comment]
I think I've found other places where this can be a problem: 

```shell
$ ag "String.format\(\"" | grep "%d" | grep -v AppLog
```

```
libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java:122:        String path = String.format("sites/%d/comments/%d/replies/new", siteId, commentId);
libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java:208:        String path = String.format("sites/%d/comments/%d/", siteId, commentId);
libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java:234:        String path = String.format("sites/%s/themes?tier=" + tier + "&number=%d&offset=%d&search=%s", siteId, limit, offset, searchTerm);
libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java:251:        String path = String.format("sites/%s/themes/?tier=" + tier + "&number=%d&offset=%d", siteId, limit, offset);
libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/MediaFile.java:333:            content = String.format("[caption id=\"\" align=\"%s\" width=\"%d\"]%s%s[/caption]",
WordPress/src/main/java/org/wordpress/android/models/Note.java:531:            restPath = String.format("sites/%d/comments/%d", getSiteId(), getCommentId());
WordPress/src/main/java/org/wordpress/android/models/Note.java:533:            restPath = String.format("sites/%d/posts/%d", getSiteId(), getPostId());
WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java:153:             + String.format("?w=%d", width);
WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java:193:        String path = String.format("sites/%s/users/%d", blogId, personID);
WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java:224:        String path = String.format("sites/%s/users/%d/delete", blogId, personID);
WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java:257:            path = String.format("sites/%s/email-followers/%d/delete", blogId, personID);
WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java:259:            path = String.format("sites/%s/followers/%d/delete", blogId, personID);
WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java:291:        String path = String.format("sites/%s/viewers/%d/delete", blogId, personID);
```

**Comment by khaykov** [comment]
Thanks, Maxime! I added locale to more places where it is/might be a problem.

**Comment by maxme** [comment]
:shipit: - Cherry picked in `release/6.1` and merged into `develop`.

**Pull request closed without merging**
