### PR TITLE
Merge release/17.9.1 into release/18.0

### PR DESCRIPTION
**Pull request by AliSoftware**
Merge `17.9.1` hotfix into current code-frozen `release/18.0` so that hotfix is applied to 18.0 too (and ultimately lands into `develop` after the next 18.0 beta that will follow this PR)

There were expected conflicts on `build.gradle` and `version.properties` which I resolved using the following:
 - The conflict on `build.gradle` was about `ext.gutenbergMobileVersion`, I picked the version from `release/18.0`, i.e. `v1.59.1` (while 17.9.1 branch was `1.58.3`) since we want the latest Gutenberg to still be used in 18.0
 - For `version.properties`, I kept the `versionName` from `release/18.0` – aka `18.0-rc-1`, the name of the last beta) but picked the `versionCode` from `release/17.9.1`, so that when we'll build a new beta right after this merge to bump the `versionCode` again, it will still generate a valid versionCode by incrementing it by one.

\cc @fluiddot @geriux to validate my rationale for conflict resolution about `gutenbergMobileVersion` version is correct

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
I always get confused in the Android hotfix merges with `versionName` not changing while `versionCode` does.

`versionName` stays the same because we are not shipping a new version from here. `versionCode` changes so that the next time we generate a beta, it will bump that value and avoid rejection because of a reused code.

🚀

**Comment by fluiddot** [comment]
> The conflict on build.gradle was about ext.gutenbergMobileVersion, I picked the version from release/18.0, i.e. v1.59.1 (while 17.9.1 branch was 1.58.3) since we want the latest Gutenberg to still be used in 18.0

That's correct, the changes introduced in the hotfix `17.9.1` (GB-mobile `1.58.3`) are already included in `18.0` (GB-mobile `1.59.1`) so we should pick `v1.59.1`.

**Comment by AliSoftware** [comment]
> I always get confused in the Android hotfix merges with `versionName` not changing while `versionCode` does.
> 
> `versionName` stays the same because we are not shipping a new version from here. `versionCode` changes so that the next time we generate a beta, it will bump that value and avoid rejection because of a reused code.

Yeah this is always a bit confusing. An alternative option could have been to pick both the `versionName` and `versionCode` from `release/18.0` unchanged in that merge PR, and then fix the incorrect increment manually when the time comes to do the new beta. But that alterantive means interrupting the `new_beta_release` lane mid-work to fix the versionCode it incremented, which is not great, which is why I opted for this mixed pick.

**Comment by mokagio** [comment]
>  But that alterantive means interrupting the new_beta_release lane mid-work to fix the versionCode it incremented, which is not great, which is why I opted for this mixed pick.

Agreed.

My comment was more of a note to self, by the way. Just to ~~say~~ write out loud what I was thinking. 😄 I didn't mean to imply your change had been done in a confusing way.

**Comment by AliSoftware** [comment]
The "funny" thing is that the `new_beta_release` failed anyway with duplicate `versionCode` after all because I didn't increment the alpha version here so the beta took the next version number after alpha value and failed… so I [had to fix it manually](https://github.com/wordpress-mobile/WordPress-Android/pull/15194/commits/b9635f6bb59678e16098f76747739ecc780b2a80) anyway … 🤦‍♂️

**Comment by mokagio** [comment]
🙃

**Pull request merged**
