### PR TITLE
[Tags Feed] Implement no connection state

### LINKED ISSUE #20815: [Reader] Empty screen shown in tags feed when there's no internet connection
When tags feed is first loaded and the user has no internet connection, we're showing an empty screen. We should probably show an error like we do in the other feeds (in case we don't have the tags). We should compare it with iOS.

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #20815 

- Implement `NoConnection` state for showing an error message when the Feed is opened without an internet connection
- Initialize the UI State to `Loading` when there is an internet connection
- Avoid refreshing the tags when there's no internet connection (pull-to-refresh and coming back from tag details)
- Fix snackbar positioning
- Extract Error Message UI logic for reuse in `NoConnection` and `PostList.Error` states

-----

## To Test:

1. Open Jetpack
2. Make sure `reader_tags_feed` FeatureConfig is ON (`Debug Settings` -> `Remote Features`
3. Turn ON airplane mode
4. Go to Reader
5. Go to `Your Tags` feed
6. **Verify** a connection error is shown
7. Tap "Retry"
8. **Verify** the screen starts loading and goes back to the connection error
9. Turn OFF airplane mode and wait for internet connection to come back
10. Tap "Retry"
11. **Verify** the tags feed is loaded
12. Pull to refresh
13. **Verify** the tags feed is refreshed
14. Turn ON airplane mode
15. Pull to refresh
16. **Verify** the feed is not refreshed and a Snackback with a connection error message is shown

-----

## Regression Notes

1. Potential unintended areas of impact

    - Refreshing/fetching issues

18. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing and unit testing

19. What automated tests I added (or what prevented me from doing so)

    - Added tests covering no internet connection scenarios

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by daniloercoli** [comment]
Hey Thomas! 👋 
Code looks good (as always), and the testing steps are okay. However, I have a couple of questions:

- I noticed that on the Discovery feed, the snackbar message is still the old version. Is it supposed to be the new one?
- I also noticed that the Discovery screen doesn't show the "No Connection" screen when the feed is opened without an internet connection. It briefly shows it and then switches to the content. (See the attached picture).
- 
photo1716200188

**Comment by thomashorta** [comment]
hey @daniloercoli, thanks for the Review! This PR only touches the `Your Tags` feed. Unfortunately, the current code treats the connection state for each feed independently and it isn't straightforward to implement a solution that works across all feeds (especially the Discover feed, which uses a completely different Fragment).

So currently this only targets the Tags Feed.

**Review by daniloercoli — APPROVED** [review]
As discussed https://github.com/wordpress-mobile/WordPress-Android/pull/20842#issuecomment-2120238080, this PR only addresses the Tags Feed, so LGTM!

**Pull request merged**
