### PR TITLE
[Gutenberg] Gallery refactor - Update upload completion processor

### PR DESCRIPTION
**Pull request by mkevins**
### Description
This updates the Gallery block upload completion processor to be compatible with the refactored format. It works by detecting the refactored version by the presence of the `imageCount` property in the block's json attributes, and defers to the existing image block processor for the inner block contents.

To test:
Run the upload completion processor unit tests.

Manual testing:
* Create a post on the web (or a version of the mobile editor without the refactored gallery block)
* Add a gallery with at least one image
* Open this post with [app version from this PR](https://109799-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14760-build-109799.apk)
  * Expect the gallery to display as the way as the non-refactored version
* Add a new gallery with at least one image
  * Expect the new gallery to display as the refactored version
* Peform the steps from [the upload tests described here](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/gallery-upload.md) on each gallery version

## Regression Notes
1. Potential unintended areas of impact
Upload completion processing.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Existing tests are relied upon, as well as new unit tests described below.

3. What automated tests I added

Unit tests were added for individual gallery blocks and for posts, to ensure that the processors can handle mixed content, since it will be possible to encounter (and edit) both formats in the same post.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @mkevins 🎉 
I've tested this with the APK from the PR on a Pixel 2 XL with Android 11 and everything seems to work as expected. The code changes are consistent and LGTM 🎉 

ps. I've run into a crash when trying to tap on a failed upload on an old gallery but I think this was my fault since I originally tried to test this with metro running the `gutenberg` [pr](https://github.com/WordPress/gutenberg/pull/31306). I'll investigate this further and report back.

<details>
 <summary>Screenshot</summary>

device-2021-06-16-190030
</details>

**Comment by mkevins** [comment]
Thanks for reviewing and testing Antonis!

> ps. I've run into a crash when trying to tap on a failed upload on an old gallery but I think this was my fault since I originally tried to test this with metro running the `gutenberg` [pr](https://github.com/WordPress/gutenberg/pull/31306). I'll investigate this further and report back.
> 

Thanks for reporting. I'll look into that as well. Unrelated with this PR, but it looks like a bridge incompatibility - I've since updated the gutenberg PR, but I wonder whether perhaps you were running metro from an older commit on that PR?

**Comment by antonis** [comment]
> I wonder whether perhaps you were running metro from an older commit on that PR?

I was running from the latest commit but did not clean/install before running. Probably that explains it.

**Comment by antonis** [comment]
> I wonder whether perhaps you were running metro from an older commit on that PR?

I think this is related to [this](https://github.com/wordpress-mobile/WordPress-Android/issues/14852) and [this](https://github.com/wordpress-mobile/WordPress-Android/issues/14851) issue. A PR tackling it is on the way.

**Comment by mkevins** [comment]
> > I wonder whether perhaps you were running metro from an older commit on that PR?
> 
> I think this is related to [this](https://github.com/wordpress-mobile/WordPress-Android/issues/14852) and [this](https://github.com/wordpress-mobile/WordPress-Android/issues/14851) issue. A PR tackling it is on the way.

Thanks for circling back!

**Pull request merged**
