### PR TITLE
Improvements in Feature Config

### PR DESCRIPTION
**Pull request by AjeshRPai**
## changes
The changes in this PR is described in this [internal p2](pcdrpt-2z2) 

## To test:
1. Verify that the debug settings can be accessed from the places described in the P2
2. Verify that the debug settings can't be accesed in a release build 
3. verify that the functionality in debug settings page is as expected

## Regression Notes
1. Potential unintended areas of impact
debug settings are not working as expected

2. What I did to test those areas of impact (or what existing automated tests I relied on)
manual testing 

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by ovitrif — COMMENTED** [review]
So far so good, both in terms of functionality and code changes 🚀

**Review by zwarm — COMMENTED** [review]
Looking good. 👏  Thanks for all the improvements, especially exposing outside of app settings

Still experiencing those two issues
- Tapping on “restart” menu item freezes UI (almost like a thread lock). 
- title overlapping with checkboxes
Alt desc



I don't think they are blockers, but wanted to jot them down for future iterations.

**Comment by AjeshRPai** [comment]
Hey @zwarm 👋🏼 

Thanks for reviewing this pR. 

>tapping on “restart” menu item freezes ui (almost like a thread lock).

I tried to fix this issue multiple times by 
 - trying to restart the app in a seperate thread 
 - change the logic of restart 
but I can still see the freeze, am not sure whats happening here as I am pretty sure that I haven't modified any existing logic. I will take up this in a seperate PR in future. 

>title overlapping with checkboxes

This was an easy fix, fixed it with the commit [cac5ec0](https://github.com/wordpress-mobile/WordPress-Android/pull/18603/commits/cac5ec0207c079f599911b227bf248b449cdca1b)



Also note, the preview is not working as of now, @ovitrif is working on a fix if am not wrong. @ovitrif please let me know if you need me to work on it.

**Review by zwarm — APPROVED** [review]
Thanks for the changes @AjeshRPai . I'm giving it a 👍 , but I will leave the merging for you. I'm not sure if Ovi's fix will be in this PR or handled separately. Can't wait to use this!!!

**Comment by Gilbert1874** [comment]
Really thank you so much my Paypal account was +639367175043 GILBERT
NATIVIDAD MEJORADA

GILBERT MEJORADA

Noong Huw, Hun 22, 2023, 3:20 AM, isinulat ni Annmarie <
***@***.***> ang:

**Pull request merged**
