### PR TITLE
My Site Dashboard - Gray line missing under the tabs #16403

### LINKED ISSUE #16403: My Site Dashboard - Gray line missing under the tabs
### Expected behavior
There should be a gray line in the tab under the menu (For example, [like this](https://cln.sh/kNSNfP))

### Actual behavior
Gray line is not present in the tab under the menu.

### Steps to reproduce the behavior

1. Login to app.
2. Go to My Site tab.
3. Notice that the app does not display gray line in the tab under the menu. 

Internal ref: p5T066-3a9-p2#comment-12130

##### Tested on Device: Pixel 5, Android version: 12, WP version: 19.7-rc-2(1202)

### LINKED ISSUE #16499: My Site Tabs: Spacing between tab bottom and tab indicator
There's a space between the blue line indicating the active tab, and the bottom of the tab bar. On reader, and in general with the material component, the active line should be right at the bottom.

| Acutal | Expected|
|---|---|
|161093794-492ae418-b743-44e9-bb7b-db542d9033e2| expected|

### PR DESCRIPTION
**Pull request by gitstart**
This PR fixes the gray line missing under my site tabs.

Fixes [#16403](https://github.com/wordpress-mobile/WordPress-Android/issues/16403)
Fixes [#16499](https://github.com/wordpress-mobile/WordPress-Android/issues/16499)

Solution:
Added a drawable resource file for tabsBackground in styles.xml

**To test:**
1.Login to app.
2.Go to My Site tab.
3.Switch between the tabs.

Screenshots 
**Before**
before
**After**
after

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Before:
https://www.loom.com/share/10672e26dd6242698fdba5d51d2a2532
After:
https://www.loom.com/share/10381c3e4dd7497ea9b56147ebdd2938

### CODE REVIEW

**Comment by AjeshRPai** [comment]
@gitstart Thanks for working on this Issue. I tested the changes and found an issue - when the toolbar is collapsed, there is a small gap between the tab selector indicator and the actual tab bottom position.

 
Screenshot_20220831-065528_Jetpack Pre-Alpha

**Review by AjeshRPai — CHANGES_REQUESTED** [review]
@gitstart I have left a comment with a screenshot which might be worth looking into. Once again, thanks for working on this issue

**Comment by gitstart** [comment]
Thank you @AjeshRPai for reviewing the PR. 
Will do the requested fixes and push it soon. 
Thank you again. 🙏

**Comment by gitstart** [comment]
@AjeshRPai 
Requested changes added. Please review it again.
Thank you!

**Review by AjeshRPai — CHANGES_REQUESTED** [review]
@gitstart It works as expected in Portrait Mode. I believe the same height change has to be done in landscape mode. Can you please make the necessary changes so that it looks as expected in landscape mode as well?

Screenshot_20220907-125012_WordPress Pre-Alpha

Once again thanks for working on this issue

**Comment by gitstart** [comment]
> @gitstart It works as expected in Portrait Mode. I believe the same height change has to be done in landscape mode. Can you please make the necessary changes so that it looks as expected in landscape mode as well?
> 
> Screenshot_20220907-125012_WordPress Pre-Alpha
> 
> Once again thanks for working on this issue

Thank you @AjeshRPai for reviewing the PR.
Will do the changes asap and push the requested changes,

**Comment by gitstart** [comment]
Hello @AjeshRPai,
Requested changes added. Please review it again.
Thank you!

**Review by AjeshRPai — APPROVED** [review]
@gitstart Everything looks good to me. I have triggered the CI for this PR. Once the CI passes successfully, I will merge this PR. Once again, thank you for fixing this issue 🙌🏼 🙇🏼

**Comment by AjeshRPai** [comment]
@gitstart Looks like the lint check with checkstyle is failing. May I suggest looking at this link https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/docs/coding-style.md to check and drill down into issues? Since you have raised multiple PR's in the https://github.com/wordpress-mobile/WordPress-Android repo, our coding style guidelines would be helpful for you to find the issues in this PR and other PRs if need be,

**Comment by gitstart** [comment]
> @gitstart Looks like the lint check with checkstyle is failing. May I suggest looking at this link https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/docs/coding-style.md to check and drill down into issues? Since you have raised multiple PR's in the https://github.com/wordpress-mobile/WordPress-Android repo, our coding style guidelines would be helpful for you to find the issues in this PR and other PRs if need be,

Thank you for reviewing PR @AjeshRPai..
Will do the required changes and push it soon. 🙌

**Comment by gitstart** [comment]
Hello @AjeshRPai,
Please check that whether CI pass the tests.
Thank you!

**Comment by AjeshRPai** [comment]
@gitstart Everything looks good to me. Thanks for working on this issue 👍🏼 .

**Pull request merged**
