### PR TITLE
Changes related to deep linking email marketing

### LINKED ISSUE #9864: Site Creation: Fix deep linking in first-post congratulations email.
## Description:

After creating a WP.com site, and right after publishing the first post, the user is getting a mail in their inbox titled: "Congratulations on your first post!".

This email has a blue button to start a new post.

We need to ensure both this link is opened by the App.

## Images:

IMG_06FCCD794808-1

## Corresponding iOS issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/11693

### PR DESCRIPTION
**Pull request by maxme**
Fixes #9864

To test:
- Should not open the app: `https://wordpress.com/post/`
- Should not open the app: `https://public-api.wordpress.com/nope/`
- Should not open the app: `https://public-api.wordpress.com/bar/?redirect_to=https%3A%2F%2FCHANGEME.wordpress.com%2Fpost`
- Should open the app's editor on previously selected site: `https://wordpress.com/post/wrong-hostname`
- Should open the app's editor with selected site CHANGEME: `https://wordpress.com/post/CHANGEME.wordpress.com`
- Should open the app's editor with selected site CHANGEME: `https://public-api.wordpress.com/mbar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2FCHANGEME.wordpress.com`
- Should "open" the app, but then redirect to the browser: `https://public-api.wordpress.com/mbar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fnope`

<s>Note: this is a draft PR because backend isn't updated yet and the deep linking urls might changes (`mobile-api`)</s>

This can be tested with ADB:

```shell
$ adb shell am start -a android.intent.action.VIEW \
 -c android.intent.category.BROWSABLE \
 -d "https://public-api.wordpress.com/mbar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2FCHANGEME.wordpress.com"
```

Real test:
- Create a new site.
- Publish a post.
- Switch to another site (to make sure the editor is opened for the right site later).
- Wait for the "Congrats for your first post" marketing email.
- Tap the "Create new post" button, you should be able to choose between your browser or the WordPress app, select the WordPress app, the editor should open on this site.

[Demo video](https://bia.is/s/lhOY/mbar-email-demo.webm) of this ^

cc @diegoreymendez

### CODE REVIEW

**Comment by nbradbury** [comment]
Just a friendly reminder to please make sure to manually merge `develop` into this branch before you merge this PR, as `develop` now contains the AndroidX migration. The automatic merge can succeed but still break the build. Better to find out now before it breaks `develop`. Thanks!

**Comment by maxme** [comment]
This one is now ready for review: server side code has been deployed and marketing emails have been updated.

**Comment by hypest** [comment]
FWIW, looks like the changes in the manifest (https://github.com/wordpress-mobile/WordPress-Android/pull/9957/files#diff-5f7bbc0f00e829f6e38e74e2e89f5c43R375-R388) are breaking the `wordpress://viewpost` deeplink, causing `Error: Activity not started, unable to resolve Intent`. Not sure if that was intentional or not.

**Comment by maxme** [comment]
@hypest I'm able to reproduce the problem with:
```
adb shell am start \
 -W -a android.intent.action.VIEW \
 -c android.intent.category.BROWSABLE \
 -d "wordpress://viewpost?blogId=1\&postId=1"
```

I read the documentation again and I don't understand why this is not working, even though there is a side effect that I didn't anticipated (see the part about merging schemes and hosts in the doc: https://developer.android.com/training/app-links/deep-linking).

**Comment by hypest** [comment]
Should have mentioned earlier, props to @renanferrari for noticing that the `wordpress://viewport` format wasn't working for him while trying to verify that deeplinking works, and reached out to me for collaboration.

**Pull request merged**
