### PR TITLE
Blocks reader user locally

### LINKED ISSUE #17603: Add block user option in the Reader post menu
### Description
We want to add a new `Block user` action at the end of the menu appearing in reader post. This action will filter out content from a specific user based on the user id. The list of blocked users will be kept client side (internal ref: `p1669978053731249/1669929094.952189-slack-C02FMH4G8`).

| Followed Site Post | Unfollowed Site Post |
| - | - |
| 205069298-3eab803b-7d9a-4879-8789-61a399b0368b|205069305-887341ea-8058-4402-ad3f-beb390aacdc6|

Internal ref `pcdRpT-1ms-p2`

### PR DESCRIPTION
**Pull request by antonis**
Fixes #17603

## Details
Adds functionality to allow blocking a user locally on the device

Implementation notes:
* For the architecture I essentially copied the logic of `BlockBlogUseCase` removing the remote parts
* [For persisting the blocked authors I added a new reader db table and filtered out the post before getting into the local db](https://github.com/wordpress-mobile/WordPress-Android/pull/17604/commits/a0dc44c6bee6a28c4a2e5c270ac09f1c3bfb5c0a)

### Block user
1. Open the reader
2. Tap on the `⋮` overflow menu on one of the posts
3. Select `Block user`
4. **Verify** that the post disappears from the list
5. **Verify** that an **Undo** snack bar appears
6. Refresh the list
7. **Verify** that the post does not appear back
8. **Verify** that no other posts from the same author are listed

### Unblock user
1. Open the reader
2. Tap on the `⋮` overflow menu on one of the posts
3. Select `Block user`
4. **Verify** that the post disappears from the list
5. **Verify** that an **Undo** snack bar appears
6. Tap on the **Undo** button
7. **Verify** that the post appears back along with the other posts from the author

### Sanity test
* Test upgrading from an older app version

|Following **before**|Following **after**|
|---|---|
|Screenshot_20221202_181736|Screenshot_20221202_181842|

|Discover **before**|Discover menu **after**|
|---|---|
|Screenshot_20221202_181750|Screenshot_20221202_181856|

## Regression Notes
1. Potential unintended areas of impact
N/A

10. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

11. What automated tests I added (or what prevented me from doing so)
Extended existing test cases

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@antonis - Probably not related to this PR, but we may want to take a look at `ReaderDiscoverLogic` to ensure that posts in the local blocked users list don't get into the database when discover data is retrieved from the BE.

**Review by ovitrif — APPROVED** [review]
Awesome work on wrangling this so quickly and great @antonis 🙇 🥇 

I've tested the new functionality using the various options to open the overflow menu in Reader and it worked as described in my tests 🚀 

The code changes also LGTM 🎉 

EDIT: P.S. I also tested upgrading from an older app version and it worked good in my test ✅

I'm approving this PR though I feel it would be great to have this PR also reviewed by someone more experienced with the Reader code, strongly suggested IMHO to be safe 🙇

**Comment by antonis** [comment]
Thank you for the prompt review @ovitrif 🏅 
> I'm approving this PR though I feel it would be great to have this PR also reviewed by someone more experienced with the Reader code, strongly suggested IMHO to be safe 🙇
@zwarm , @develric Let me know if you have any feedback or suggestion for improvements 🙇

**Review by zwarm — APPROVED** [review]
@antonis - Nicely done 👏  

All tests pass!

I'm going to approve this PR because it works as stated; however I will leave a couple of questions:

(1) If the app user clears all data for the app, the blocked users list gets reset as expected. But upon logout/login, it looks like user posts makes it back into the reader list.

I tried the following scenario
- Follow a site that has multiple authors (tvline.com)
- Choose one post and block the user. Note the post from that user is gone
- Logout and login back in again
- Navigate to Reader > Following tab. The Blocked users post shows again in the list.

(2) Do we intend to add a feature to show the list of blocked authors? The undo is only shown for a very short amount of time. And yes, I know this wouldn't be needed for the Dec 7th deadline, but I'm curious.

Thanks

**Comment by antonis** [comment]
Thank you for reviewing and your feedback @zwarm 🙇 

> (1) If the app user clears all data for the app, the blocked users list gets reset as expected. But upon logout/login, it looks like user posts makes it back into the reader list.

I investigated this a bit and it seems that this happens because [the reader database is reset](https://github.com/wordpress-mobile/WordPress-Android/blob/c7c9d591cb7daf38f5b21863884a4489b2b81972/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L311) when the user logs out. I played around with removing the specific table from the reset list and this results and special handling when the table is created too. Given that we plan to iterate on this and support the functionality from the backend (ref: `pcdRpT-1ms-p2#comment-2177`) I would restrain from supporting this on the client for now.

> (2) Do we intend to add a feature to show the list of blocked authors? The undo is only shown for a very short amount of time. And yes, I know this wouldn't be needed for the Dec 7th deadline, but I'm curious.

That's a good point 👍 Let's consider this on the long term plan for this feature (ref `pcdRpT-1ms-p2#comment-2188`)

**Comment by zwarm** [comment]
> I investigated this a bit and it seems that this happens because [the reader database is reset](https://github.com/wordpress-mobile/WordPress-Android/blob/c7c9d591cb7daf38f5b21863884a4489b2b81972/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L311) when the user logs out

This is what I assumed happens and seems reasonable for a local solution. There are plenty of others things that get reset on logout. Like you said, this is our stop-gap solution and once we move to a robust BE solution this will do. Thanks.

**Pull request merged**
