### PR TITLE
🤖 [Dynamic Cards] Card Actions

### LINKED ISSUE #19746: 🤖 [Dynamic Cards] Card Actions
Ref: pc8HXX-1nA-p2#card-actions
```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19738
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #19746

## Description
This PR adds card actions based on the provided url.
* If the url is a deep link the proper screen is opened inside the app
* If the url is not a deep link a webview opend

-----

### With a response patch
- Apply the [cardactions.patch](https://github.com/wordpress-mobile/WordPress-Android/files/13712576/cardactions.patch) and run the app.
- Tap on the first card action button
- **Verify** that a webview opens with the provided url
- Tap on the second action card
- **Verify** that the reader opens with the linked post

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/02ecc2a4-eb48-42a5-a04b-9f6aa73ffec4

### With a sandbox (url testing only)
- Sandbox your emulator with D132479-code (instructions paqN3M-5m-p2)
- Tap on the *Check it out* button
- **Verify** that a webview opens (Note you can use the follow up PR to test deep link handling https://github.com/wordpress-mobile/WordPress-Android/pull/19821)

-----

## Regression Notes

1. Potential unintended areas of impact

    My Site Dashboard screen and a dynamic dashboard card

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    Manual testing

3. What automated tests I added (or what prevented me from doing so)

    Added test cases in the `DynamicCardsViewModelSliceTest`

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by justtwago** [comment]
I can't test it yet because I'm getting a dashboard fetch error when enabling the `dynamic_card` feature flag:
```
org.wordpress.android.fluxc.store.dashboard.CardsStore$CardsError@4262af6: Invalid parameter(s): cards
```

**Comment by antonis** [comment]
> I can't test it yet because I'm getting a dashboard fetch error when enabling the dynamic_card feature flag:

Thank you for looking into this and sorry for missing this @justtwago in the test instructions.
The issue occurred because [the FluxC client was sending an unknown card type parameter](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/dashboard/CardsRestClient.kt#L54) in the dashboard request payload. (internal discussion ref p1702972968507529-slack-C067H36F011)
I updated the [patch file](https://github.com/wordpress-mobile/WordPress-Android/files/13712576/cardactions.patch) in the description [commenting out the addition of the `dynamic` card type in the dashboard request payload](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsSource.kt#L108). I also merged `trunk` along https://github.com/wordpress-mobile/WordPress-Android/pull/19801 and used an enabled (`domain_management`) remote flag in the patch file to simulate a desired network response.

**Comment by antonis** [comment]
Added a `With a sandbox (url testing only)` section for testing with the actual implementation (ref p1702973133453389/1702973027.394549-slack-C067H36F011)

**Review by justtwago — APPROVED** [review]
Thank you for the amazing work Antonis! 😮 I tested both cases using a patch and sandbox and had no issues.
The only defect I found is a handling deeplinks to the reader. Would be nice to not redirect users to the reader tab and just open a post. It's out of the scope but worth addressing in the future.

https://github.com/wordpress-mobile/WordPress-Android/assets/16563318/c5d2a0b8-653e-4b33-b1c7-9e4ffb322a2e

**Comment by antonis** [comment]
Thank you for reviewing and your feedback @justtwago 🙇 

> The only defect I found is a handling deeplinks to the reader. Would be nice to not redirect users to the reader tab and just open a post. It's out of the scope but worth addressing in the future.

Good catch 👍 
I've opened an issue to track this down https://github.com/wordpress-mobile/WordPress-Android/issues/19825

**Pull request merged**
