### PR TITLE
Issue/10650 material me screen

### LINKED ISSUE #10650: Implement Material theme on Me and related screens
We should switch widgets used at Me and related setting screens to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10650 

This PR is based on #11071 , which needs to be merged first.

This PR moves Me and all nested screens to Material Theme and adds Dark Theme support. There are some code changes for cosmetic reasons. The photo picker and ZenDesk styling is not a part of this PR.

Design changes are reviewed before the code review is requested.

While refactoring is not in the scope of this PR, since I touched those files, I cleaned up/optimized some of the redundant code as suggested by AS, so do not be alarmed by the size of the PR. I suggest turning on the "Hide whitespace changes" option during the review.

There is a huge amount of PRs in this feature that covers all the screens within the app, so I'm requesting reviews from a wide variety of people.

@mattmiklic I wasn't sure what to do with About screen, so I improvised a bit :)
comparison_me

To test:
- Navigate to Me screen and check that it and all the nested screens are visually and functionally good in both Dark and Light themes. Make sure to check the username changer screen too.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by khaykov** [comment]
Thanks for taking a look at this one, @jd-alexander ! Good catch with the About screen! I was testing Light Mode on API 28, and missed the weird icon color in navbar.

image


Icon tint is the known issue (tint on Privacy settings screen is the correct one). I was planning to fix after other PR's are merged, but I think this is might be a good time to start :)

**Comment by jd-alexander** [comment]
> Thanks for taking a look at this one, @jd-alexander ! Good catch with the About screen! I was testing Light Mode on API 28, and missed the weird icon color in navbar.

Awesome! Just checked and it has been resolved now 🎉 

> Icon tint is the known issue (tint on Privacy settings screen is the correct one). I was planning to fix after other PR's are merged, but I think this is might be a good time to start :)

Okay understood! Let me know if you change your mind and I would approve this since I have done my review.

**Comment by khaykov** [comment]
@jd-alexander The icons are supposed to be grey (medium emphasis). I thought you are pointing out the difference in the shade (the icons on preference screen are a little bit lighter, which is correct color), and I fixed this :)

**Comment by jd-alexander** [comment]
> @jd-alexander The icons are supposed to be grey (medium emphasis). I thought you are pointing out the difference in the shade (the icons on preference screen are a little bit lighter, which is correct color), and I fixed this :)

Ohhh! Yes, that's what I was looking at. I got a bit confused looking at the earlier screenshots without remembering the medium emphasis comment! All is well now!

**Pull request merged**
