### PR TITLE
Rotating the device loses the theme search fix

### PR DESCRIPTION
**Pull request by rishabh7m**
fix for #3446

### CODE REVIEW

**Comment by rishabh7m** [comment]
Hi @kwonye , is this PR under review?

**Comment by kwonye** [comment]
Hi @rishabh7m, yes it is on my list. No ETA yet, but I will get to it. Thanks for contributing!

**Comment by rishabh7m** [comment]
okay :)

**Comment by hypest** [comment]
Oops, hadn't notice that this issue was been worked on and pushed a different PR for it (https://github.com/wordpress-mobile/WordPress-Android/pull/3616).

**Comment by daniloercoli** [comment]
The original issue has been fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/3616.
This PR should contain a fix a new issue i'm going to fill in. Will reference this PR from there.

**Pull request closed without merging**
