### PR TITLE
Feature/site media collapsing toolbar

### PR DESCRIPTION
**Pull request by nbradbury**
Replaces the current media settings scroll transition with the more standard "collapsing toolbar" pattern.

new

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
This looks mostly solid to me, but one small concern. The semi-transparent status bar color seems to change from blue to black. Can we force it to start and stay as the dark gray/black color? I understand the color will shift visually bc the black will be semi-transparent over a new color (blue) but starting on blue and shifting is odd.

**Comment by nbradbury** [comment]
@iamthomasbishop Is this better?

**Comment by iamthomasbishop** [comment]
Perfect 👍

**Comment by daniloercoli** [comment]
Don't think it's an issue, but worth to mention.  I can scroll (& stop) the screen and make the translucent toolbar disappear and no title in the blu toolbar.
screenshot_2017-09-29-13-38-28
screenshot_2017-09-29-13-38-39

**Comment by nbradbury** [comment]
> I can scroll (& stop) the screen and make the translucent toolbar disappear and no title in the blu toolbar.

I noticed that, too, and tried to resolve it by keeping the title for the first bit of the scroll. That didn't look right, though, because the `CollapsingToolbarLayout` animates the title as you scroll, so it ends up looking like this:

**Comment by daniloercoli** [comment]
Ok, let's ship this since it is not a problem. :shipit:

**Pull request merged**
