### PR TITLE
Ui Modernization Posts: Apply Context Menu Groupings

### LINKED ISSUE #19343: UI Modernization Posts: Update context menus
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Apply new grouping and ordering for the context menu on each tab
- [x] Adjust copy and icons
- [x] Apply existing visibility rules
- [x] Move offline actions to the context menu
- [x] Add GB icons to the project
```

### PR DESCRIPTION
**Pull request by zwarm**
Closes #19343 

This PR applies the updated icons, copy, text coloring, and groupings for the Post "context menus". Use the figma file as the base, but note that further modifications were decided in slack.

Note: This PR does not include the "Comments" menu item, that will be taken up in a separate PR.

FYI @osullivanchris - let me know if see anything out of whack. Thanks.

Contributor Pending Review Draft (viewing as Contributor) | Contributor Draft (viewing as Contributor)
-- | --
Alt desc | Alt desc

Contributor Pending Review Post (viewing as admin) | Contributor Draft Post (viewing as admin)
-- | --
Alt desc | Alt desc

Publish (Viewing as editor) | Published (Viewing as admin)
-- | --
Alt desc | Alt desc

Drafts | Scheduled | Trashed
-- | -- | --
Alt desc | Alt desc | Alt desc

**To test:**
**Prereqs**
- Have a few accounts with editor, contributor, and admin capabilities
- Create a fews posts as a contributor - drafts, scheduled, and non-scheduled (submit these)
- Create a few posts as editor/admin

- Install the JP app
- Launch and sign in
- Navigate to My Site > Posts
- Tap on the "more" icon on a post row in the Published tab
- ✅ Verify the new icon groupings are shown, the icons and copy are correct
- Repeat the last two steps for each tab 
- Repeat for WP app 

## Regression Notes
1. Potential unintended areas of impact
The context menus are not correct

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and updated 'PostListItemUiStateHelperTest`

3. What automated tests I added (or what prevented me from doing so) N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [X] Portrait and landscape orientations.
- [X] Light and dark modes.
- [X] Fonts: Larger, smaller and bold text.
- [X] High contrast.
- [X] Talkback.
- [X] Languages with large words or with letters/accents not frequently used in English.
- [X] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [X] Large and small screen sizes. (Tablet and smaller phones)
- [X] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
Works as described 👍🏼 . Nicely done 

I am approving but not merging so that @osullivanchris can have a look

**Comment by osullivanchris** [comment]
Looking good! 3 small UI details. I have an idea about groupings but will discuss in Slack:

- Can we have some right padding on the menu so it isn't pinned exactly to the edge of the device?
- The icon and text don't look exactly centred in their row when there is only one item in the group. I guess this is because of some extra spacing at the start of a group? Making it look a bit 'off' when only one item in the group?
- Probably related but the 'Trash' action looks too close to the bottom of the menu.

for 2 and 3, I was working off what I think is the native component but for me the rows are all 48dp. Then there is 8dp padding at top and bottom of the entire menu, and at the start and end of a group.

image

**Review by osullivanchris — COMMENTED** [review]
forgot to tap the 'review changes' button before commenting above

**Comment by zwarm** [comment]
@osullivanchris 
The following groupings have been merged {Cancel Upload and/or [Publish | Retry | Sync | Submit]} with {Move to drafts, Duplicate}

> Can we have some right padding on the menu so it isn't pinned exactly to the edge of the device?

I don't have fine grained control of the widget, but what I did do is update the gravity to the end of the anchor view. It looks good. wdyt?

> The icon and text don't look exactly centered in their row

I agree that the spacing looks off. I believe this is because the popup menu doesn't support showing icons out of the box. And to top if off we are trying to adjust the icons by setting bounds and then merging it with the text field. Unfortunately we don't have the capability to adjust layout parameters within a popup menu. :(  However, I swapped out the existing popupMenu implementation with the appCompat one. This appears to work 100% better in terms of spacing (we still don't have access to adjust the layout parameters/spacing, etc). 

~~I still have to drop in the 24x24 blaze icon, so for now there is an empty icon to hold the space~~. In the interim you can check out the updated feel/look. If this doesn't meet our needs, then I'll have to write a completely custom solution (a few days of work). I am keeping my fingers crossed. :) 

Update: Dropped in the new blaze icon. 🥳 

Merged Groupings | Context Menu Spacing
-- | --
Alt desc | Alt desc

Thanks for all the comments!

**Comment by osullivanchris** [comment]
> I don't have fine grained control of the widget, but what I did do is update the gravity to the end of the anchor view. It looks good. wdyt?

That position looks good now!

> I agree that the spacing looks off. I believe this is because the popup menu doesn't support showing icons out of the box. And to top if off we are trying to adjust the icons by setting bounds and then merging it with the text field. Unfortunately we don't have the capability to adjust layout parameters within a popup menu. :( However, I swapped out the existing popupMenu implementation with the appCompat one. This appears to work 100% better in terms of spacing (we still don't have access to adjust the layout parameters/spacing, etc).

Don't understand how it all works exactly but it looks better now!!


Sorry this caused lots of hassle but it looks cool. Wonder if and of what you did could be re-used elsewhere in the app. Not in every case, but in some, the dividers and icons add a bit of gravitas to the component.

**Comment by zwarm** [comment]
> Don't understand how it all works exactly but it looks better now!!

lol, I swapped one native widget for another native widget that lets me set an icon directly without jumping through hoops. And seriously, that new blaze icon helped significantly. 🙇

**Comment by zwarm** [comment]
@osullivanchris - I am going to go ahead and merge this PR. 🔆

**Pull request merged**
