### PR TITLE
Reader Stream Refresh Design Review

### LINKED ISSUE #4776: Reader stream refresh
This is the master issue for the reader stream (card/list view) refresh, which will update the reader stream to match the Calypso web reader. The refresh will be split into several PRs:

1. Post card refresh (#4777)
2. Photo card (#4808)
3. Gallery card (#4811)
4. XPost card refresh (#4804)
5. Video card (#4820)
6. ~~Add sharing to post card~~ (will come later)

Below are the rules used for the Calypso reader cards:

- If the post has 0 images: Text card.
- If the post has 1 or more images and less than 100 characters: Photo card (using featured image or first image).
- If the post has 1-3 images and over 100 characters: Default card (using featured image or first image).
-  If the post has 4 or more images and over 100 characters: Gallery card (using first 4 images).
-  If the post has a video as featured image or a video as first usable media: Video card.

For the text excerpts, we use the excerpt attached to the post. If no excerpt, we use the first X words (whatever we’re doing now). Links, paragraph tags, and break tags should be removed from the excerpt. Bold and italics can stay, so long as the tag gets closed and it doesn’t include all of the text in the excerpt.

### Default Card

The Default card is the most common. It shows some text and one image. The image is the featured image (if the user set one, and it’s not busted). If the user has not set a featured image, it’s the first usable (over 350px) image in the post. The text should be about three lines. This is also the card format used if the post has three or fewer images. If it has four, it uses the Gallery format below.

### Text Card

The Text card is used when the post contains no usable images. It should also be limited to about three lines. Because there’s no image, the total amount of text is greater.

### Photo Card

The Photo card is used when the post contains one or more images (if more than one, use the first image) and under 100 characters of text. Note that the photo card displays the post title on a single line on top of the image (in SF UI Text Medium 14px – sans serif is easier to read on a busy background). The post title should never wrap! The image also has a fade applied to the lower quarter so the title can be read easily. (Note: a fade on the lower quarter – not the whole image darkened.)

## Gallery Card

The Gallery card is used when the post contains text and 4 or more images (excluding the featured image – the featured image is ignored for the Gallery card to avoid duplications if the author used the image in the post as well). The card gets a row of four images above the headline. These images should be the first four usable (over 350px) images in the post. Each image gets 25% of the width. 1px of whitespace in between each image.

## Mobile Web Screenshot
sm-post

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4776 - this is the master branch of the reader "stream refresh." All code related to this feature has already been reviewed and merged into this branch. This PR is to seek a design review of this feature before it's merged into develop.

We now show five different card types:

1. Default
2. Text
3. Photo
4. Gallery
5. Video

Screenshots of each of theses cards are below.

all-cards

Note that "sharing" will come later - it's not part of this PR.

*Update:* I've added the new tag image header to this PR. Screenshot below:

android-tag-header

CC: @fraying @jancavan

### CODE REVIEW

**Comment by daniloercoli** [comment]
cc @drw158

**Comment by fraying** [comment]
Thanks for being on top of this, @nbradbury, and sorry for the delay in getting you feedback.

Overall, this is a fantastic implementation of the refresh language on native mobile. Well done! Just a few things I wanted to call out.

**1. Consistency in margins.**

From the looks of what you've posted here, there's an inconsistency in when the image in the card goes full bleed (touching the edges of the screen) and when it's indented to match the text.

Default, Photo, and Video: full bleed.
Text and Gallery: Indented.

We should make them consistent, just so the experience feels more cohesive. My recommendation: Indent them all. Why: The image connecting to the outer edge creates a visual break with what's above and below it, which makes it hard to tell where each card stops and starts. Indenting them makes it clearer what's in each card.


**2. Post divider lines.**

Speaking of consistency in margins, on web mobile, we maintain the same margins for the line that divides posts. So, they end 10-20px before the edge of the screen, same as the text and images. But! On the web we have way more space around each card. So, I'm cool with connecting the lines to the edges of the screen. Just wanted to flag it as a difference, but it's a difference that makes sense on native.

I also notice that the divider line looks like it's 2px tall, and the web version is 1px. If you think the wider line is more important on mobile, it's cool, but I wouldn't mind trying it at 1px. May be enough. 


**3. Action items and labels.**

In the web version, at the smallest width, we keep the "Visit" text with the visit icon, but drop the labels on Share, Comment, and Like. (Why keep "Visit"? Because it's the thing our site creators want people to do, and we want to show them we're thinking about them.) I think it would make sense to replicate that here. Note that, even with the labels dropped, we still append numbers to Like and Comment to show activity. Like so:

screen shot 2016-12-02 at 11 07 53 am

Also on the action links: They're a bit too far away from the text, vertically. Try to mirror the same amount of vertical whitespace as the distance from photo to title, and title to excerpt – about half of what's there currently. And be sure that the left edge of the visit icon aligns with the left edge of the card. Like so:

screen shot 2016-12-02 at 11 23 55 am

This attention to alignment/spacing is what keeps every card feeling like it's in a box, even though it's not.

Last thing: We made the icons a bit smaller on the web. We could stand to do that here, too. Okay, I can hear the argument about tap targets in my head already. So I'll just say this: The action links are functionality, yes, but also meta information. It's okay for them to get a teensy bit smaller because the thing we most want people to do is tap the card itself. Letting the action links fade back a bit lets the content come forward. Give it a try?


**4. Image borders.** 
 
In the web view, we became concerned with cases where image backgrounds were white, so the card looked too "floaty." To fix this, we added a 1px border to all images (same grey as divider line). It's pretty unnoticeable for color images, and really helps images with white backgrounds. Consider adding it here, too? Note that, when the card is a Gallery, the 1px border goes around each image, with 1px of white in between each border, so they don't blend together to become one thing visually.

(In the future, I'd LOVE to apply this border only to white backgrounded images.)


**5. Follow button baseline.**

On the web, we've been very consistent with keeping the "Follow" link on the same visual baseline as the name. This helps make it clear what you're following. We'd like to retain this consistency on native. Note that the active tap area could still extend below the "Follow" text.

So this:
screen shot 2016-12-02 at 11 17 46 am

Should be this:
screen shot 2016-12-02 at 11 18 12 am

Note also that the follow icon and the "Follow" text also share the same baseline. This helps them feel connected to each other.


**6. Video icon.**

(Now we're getting into the tiny stuff.) The triangle in the center of the video play icon should be black, not transparent. This is important if that part of the thumb happens to be over white.

So this:
screen shot 2016-12-02 at 11 35 43 am

Should be this:
screen shot 2016-12-02 at 11 36 49 am


That's all I've got!

Anything I missed, @jancavan?

**Comment by nbradbury** [comment]
@fraying Thanks for taking a look at this! I've addressed all of the issues you raise.

> Consistency in margins.

Added in e7a5033

> Post divider lines

Changed to 1px in 56bd0ac

> Action items and labels

Removed text from like & comment icons, corrected vertical spacing, and reduced size of action icons in 3ad8ea7, 500e327 and baa5004

> Image borders

Added around featured image in ba8042e and gallery images in 01269da

> Follow button baseline

Added in d482d27

> Video icon

Triangle in the center changed to black in 1329838, also added a 1px black outline in 3a9fef3

Here's a screenshot which I think illustrates all of the above fixes.

video

**Comment by fraying** [comment]
Nice work, @nbradbury!

_Almost_ there.

1. The Follow link is still off baseline (needs to move up).

So this:
screen shot 2016-12-03 at 10 40 58 am

Should be this:
screen shot 2016-12-03 at 10 41 10 am

2. The Comment icon's flat part should align with the baseline (needs to move down).

So this:
screen shot 2016-12-03 at 10 41 29 am

Should be this:
screen shot 2016-12-03 at 10 41 51 am

3. The row of action links still have a bit too much space above them (need to move up).

So this:
screen shot 2016-12-03 at 10 42 16 am

Should be this:
screen shot 2016-12-03 at 10 42 52 am

4. The Visit link is still a couple pixels from the left edge (needs to move left).

So this:
screen shot 2016-12-03 at 10 48 04 am

Should be this:
screen shot 2016-12-03 at 10 48 13 am

**Comment by nbradbury** [comment]
@fraying I need to purchase some designer eyeballs, because mine never noticed those differences! I've made all of those fixes - screenshot below.

screenshot_1480861863 2

**Comment by fraying** [comment]
Nice work! Don't worry, you can borrow my eyeballs anytime.

**Pull request merged**
