### PR TITLE
Add Duplicate (Copy) Page functionality

### LINKED ISSUE #13599: Android: Add Duplicate (Copy) Page functionality
### Description

The user should be able to duplicate a page. This functionality is already available on the web.
The [design](https://user-images.githubusercontent.com/50576199/61964868-dc8b1a80-afc6-11e9-939e-0a0862a76601.png) should be similar with the [duplicate post functionality](https://github.com/wordpress-mobile/WordPress-Android/pull/13521).

The new "Duplicate" option should be available for **Published** and **Draft** pages both in the initial listing and in search results.

<details>
  <summary>Web Copy page action</summary>
  
Screenshot 2020-12-14 at 5 12 26 PM

</details>

cc @osullivanchris

### PR DESCRIPTION
**Pull request by antonis**
Fixes #13599

## Description
This PR implements the "Duplicate page" functionality (already exists on Calypso) and is similar with the [Duplicate Post functionality](https://github.com/wordpress-mobile/WordPress-Android/pull/13521)

### Duplicate published page
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. Create a new page or open a page by tapping on it
1. Take a note of the title and content
1. Press the *dots* at the right of the page listing
1. **Verify** that the *Duplicate* button is visible
1. Press the *Duplicate* button
1. **Expect** to see an analytics event like the following `🔵 Tracked: site_pages_options_pressed, Properties: {"option_name":"copy","blog_id":174576032,"is_jetpack":false,"site_type":"blog"}`
1. **Verify** that the editor opens with the title and content from step 3
1. Make a minor change
1. Publish or exit to save the page as draft
1. **Verify** that both the original and the duplicate pages are listed

### Duplicate draft page
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. Select the *Drafts* (second) tab
1. Create a new page or open a page by tapping on it
1. Take a note of the title and content
1. Press the *dots* at the right of the page listing
1. **Verify** that the *Duplicate* button is visible
1. Press the *Duplicate* button
1. **Expect** to see an analytics event like the following `🔵 Tracked: site_pages_options_pressed, Properties: {"option_name":"copy","blog_id":174576032,"is_jetpack":false,"site_type":"blog"}`
1. **Verify** that the editor opens with the title and content from step 4
1. Make a minor change
1. Publish or exit to save the page as draft
1. **Verify** that both the original and the duplicate pages are listed

### Duplicate page with conflict
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. Create a new page or open a page by tapping on it
1. Take a note of the title and content
1. Press the *dots* at the right of the page listing
1. **Verify** that the *Duplicate* button is visible
1. Press the *Duplicate* button
1. **Expect** to see an analytics event like the following `🔵 Tracked: site_pages_options_pressed, Properties: {"option_name":"copy","blog_id":174576032,"is_jetpack":false,"site_type":"blog"}`
1. **Verify** that the *Conflict dialog*(check screenshot below) appears

### Edit page with conflict
1. Follow the steps from **Duplicate page with conflict** above
1. Select *Edit the post first*
1. **Verify** that the conflict resolution dialogs appear and the post opens for editing

### Duplicate local page
1. Follow the steps from **Duplicate page with conflict** above
1. Select *Copy the version from this app*
1. **Verify** that the editor opens
1. Make a minor change
1. Publish or exit to save the page as draft
1. **Verify** that both the original and the duplicate page are listed

## Screenshots

|Published pages actions|Draft pages actions|Conflict dialog|
|---|---|---|
|device-2020-12-15-175732|device-2020-12-15-175748|device-2020-12-15-175818|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hey @osullivanchris 👋 
I was requested to extend the *Duplicate Post* functionality for pages. I implemented the UI to be the same with *Duplicate Post* based on your [design](https://user-images.githubusercontent.com/50576199/61965121-676c1500-afc7-11e9-8d9f-b9c0546844c3.png).
The *Duplicate* action (as with posts) is present in *Published* and *Draft* pages. @mkevins [suggested that we may allow the user to also duplicate posts (or pages) in other states](https://github.com/wordpress-mobile/WordPress-iOS/pull/15460/files#r540715969) (e.g. scheduled, pending). I think that implementation wise this should be simple. Wdyt?
Thank you in advance for your feedback🙇

**Comment by antonis** [comment]
To create Pages with version conflicts for testing purposes you can use the following steps:
1. Create a new page and publish it
1. Reopen the page
1. Press the back button to exit the editor and save a local copy
1. Delete the app from the device
1. Install the app and login
1. Notice the conflict warning on the page listing 🎉 

This scenario is extreme but seems to consistently produce conflicts. cc @mkevins

**Review by mkevins — APPROVED** [review]
Reviewed and tested on Pixel 3a (physical device). It is working as expected for all the described flows. Nice work Antonis! LGTM :+1:

**Comment by osullivanchris** [comment]
> The Duplicate action (as with posts) is present in Published and Draft pages. @mkevins suggested that we may allow the user to also duplicate posts (or pages) in other states (e.g. scheduled, pending). I think that implementation wise this should be simple. Wdyt?

Hey @antonis, I must have missed this before the holidays. I think duplicating a scheduled or pending post is fine. I think the new duplicated post should behave like others - just being a plain draft with no schedule or pending status. Perhaps we need to tell the user in some way, is the only issue I can see.

I just captured draft and published as two examples in the mock, but covering all statuses is even better.

**Comment by antonis** [comment]
> Hey @antonis, I must have missed this before the holidays. I think duplicating a scheduled or pending post is fine. I think the new duplicated post should behave like others - just being a plain draft with no schedule or pending status. Perhaps we need to tell the user in some way, is the only issue I can see.

Hello @osullivanchris 👋 
Thank you for the feedback. I'll try to cover this with a separate PR.

**Pull request merged**
