### PR TITLE
Lint: Fix Jetpack Lint Errors

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR:
1. Fixes all the `jetpack` only, dimension related errors, so that when running `./gradlew lintJetpackVanillaRelease`, Lint successfully builds.
2. Suppress the `jetpack` only, dimension related warnings, so that both, the `wordpress` and `jetpack` Lint reports output the same results, in terms of total and individual number of warnings. Those number are currently `339` for `wordpress` and `336` for `jetpack`, `3` diff. The current discrepancy is due to 2 `editor` lib and 1 `story` submodule overdraw related Lint warnings, which weren't fixed, at this specific time, and on purpose.

To test:
1. Pull the branch locally.
2. Run ` ./gradlew lintWordpressVanillaRelease` and verify everything works as expected. The task should complete successfully.
3. Go to `WordPress/build/outputs` folder and open the `lint-results-wordpressVanillaRelease.html` report. Note the number.
4. Run ` ./gradlew lintJetpackVanillaRelease` and verify everything works as expected. The task should complete successfully.
5. Go to `WordPress/build/outputs` folder and open the `lint-results-jetpackVanillaRelease.html` report. Note the number.
6. Check CI and verify everything works as expected.
7. Note that CI only trigger Lint for `wordpress`. This is expected. As such, you can only compare CI with your local `wordpress` report.

## Regression Notes
1. Potential unintended areas of impact

N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I run `Lint` in both, `debug` and `release` build types, as well as both, `wordPress` and `jetpack` dimensions to make sure that this change is not affecting the lint report and the actual reported issues, both `errors` and `warnings`.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @oguzkocer and @AliSoftware !

As part of this ongoing process of cleaning-up all the Lint warning I wanted to create a process around that. However, I first want to run it by you, that is before proceeding with it. I actually created an example issue for that matter (#14818).

So, the process will be as follows:
- For each of the warnings that are listed within the Lint report, starting with those that are non trivial to fix, or too many, or require extra collaboration with other team members (ie. designers).
- I will first create a PR to suppress them inline and closer to the source code (ie. see `VectorRaster` or `VectorPath` or `Overdraw`).
- This PR will also make sure that the specific `warning` is to be treated as `error` afterwards (ie. I will add the `<issue id="VectorRaster" severity="error" />` line within the `lint.xml` file). This will make sure that whenever a new team member introduces a new such warning again, the build will fail forcing them to resolve that instead (fix or suppress it). In any case, the total or individual numbers on the Lint report, based on this specific warning, should never not go up again.
- Then, I will create an ongoing monitoring and fix mega issue that will make sure that those suppressed warnings are fixed progressively and as time passes by, while at the same time making sure that those will get reported back to this mega issue (ie. an example here #14818). In case all of them get fixed at some point then this mega issue can be temporarily closed, at least up until the needs to tackle this problem arise again in the future.

What do you think about tackling the Lint clean-up process like that? I would love if you could share your thoughts on this process. I can later on create a P2 post about it and gather some additional feedback from other engineers as well.

PS: Please read through the example #14818 `VectorRaster` issue for more details on the process and the end goal, which is to start using the `warningsAsErrors` afterwards.

And once more, MANY thanks all your support! 🙏

**Comment by oguzkocer** [comment]
@ParaskP7 This approach sounds good to me. I think the main worry with removing any warning is that it'll go unnoticed and will never be fixed. This is doubly true for suppressing a warning in place, especially for drawables, because it's very unlikely for us to even open that file. The thing is, even though these warnings are printed out in every CI task and every local build, it's still ignored - because let's face it, we always have bigger fish to fry.

Although some warnings should be taken seriously and fixed immediately, a lot of it would be fine if we never fixed it. The tricky fixes are probably at the bottom of our todo list and that's fine if it's currently working OK. So, if you take a look at a lint error and either suppress it in place or fix it, that's more than good enough for me. These issues you're creating are the cherry on-top (and I suggest not spending more time on documenting them than you'd take to fix the issue 😂 ) so all good from me 👍

**Review by oguzkocer — COMMENTED** [review]
@ParaskP7 I am sorry, but I can't quite follow your PR description. My suggestion is not to worry too much about numbers right now, especially comparing CI to local or wordpress to jetpack, I don't think that's very helpful, not as part of this PR anyway. If there is a discrepancy that you think would be helpful to address, please feel free to open a PR just for that, so it'll be easier to follow and test.

From the changeset, it looks like you're suppressing 2 `VectorRaster` and 1 `Overdraw` lint issues in place which looks good to me. However, I don't know why these 3 issues were specifically picked as there are other lint errors for these types. I also don't have any context about the file movement, so not sure what to look for there. I guess that's what's fixing the Jetpack lint issues?

Overall I am a little confused by this PR - sorry about that! I think maybe it's doing a few things at once, considering that extra comment as well, so I am just not able to connect the dots.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @ParaskP7 This approach sounds good to me.

👍 

> I think the main worry with removing any warning is that it'll go unnoticed and will never be fixed. This is doubly true for suppressing a warning in place, especially for drawables, because it's very unlikely for us to even open that file. 

This is very unless there is a process in place to help with that. However, to be honest, that's what I like to achieve going forward. Also, by doing that my initial goal would be to stop adding new warning like that, which might be a good win. Wdyt? 🤔 

> The thing is, even though these warnings are printed out in every CI task and every local build, it's still ignored - because let's face it, we always have bigger fish to fry.

This is very true and thus I wanted to create a new process for us to start tackling this. ☝️ 

> Although some warnings should be taken seriously and fixed immediately, a lot of it would be fine if we never fixed it.

Totally agree with that statement. 💯 

> The tricky fixes are probably at the bottom of our todo list and that's fine if it's currently working OK. So, if you take a look at a lint error and either suppress it in place or fix it, that's more than good enough for me.

> I can't agree more and thanks for being on the same page with me on that. 🙏 

> These issues you're creating are the cherry on-top (and I suggest not spending more time on documenting them than you'd take to fix the issue 😂 ) so all good from me 👍

True, you are right, but what I want to achieve with this example issue that I created is exactly that, to have a template issue that I (and anyone else) can just duplicate and reuse for any issue. That's why I think that only the first such issue will take time to get it right and the next such issue will just follow by example, without requiring much time from others to create them. Wdyt? 🤔

**Comment by oguzkocer** [comment]
> This is very unless there is a process in place to help with that. However, to be honest, that's what I like to achieve going forward. Also, by doing that my initial goal would be to stop adding new warning like that, which might be a good win. Wdyt? 🤔

I understand that and I appreciate the effort. However the issues go stale all the time, that's why we have a stalebot 🙈 so even though what you're making it better, it's not a silver bullet either. As I have also followed up in that comment, I don't think that's an issue. I just thought it was worth noting the issue first and then share my thoughts about why I don't feel it's a blocker for what you're trying to do. So all good 👍 

> True, you are right, but what I want to achieve with this example issue that I created is exactly that, to have a template issue that I (and anyone else) can just duplicate and reuse for any issue. That's why I think that only the first such issue will take time to get it right and the next such issue will just follow by example, without requiring much time from others to create them. Wdyt? 🤔

Depends on who is writing the issue, it takes me a while to write any post/issue/pr description even if there is a template, because I re-read it at least 10 times. That issue you wrote is not very small either 😂 Anyway, that's just something every developer will have to consider themselves. Worst case, a developer will write an issue and realize it took them so much time that they'd have preferred to fix the issue and next time, that's what they'll do. :)

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Thanks for an initial review.

> @ParaskP7 I am sorry, but I can't quite follow your PR description.

Apologies for making this PR harder that is might have been. My reasoning for doing that further below. 😊 

> My suggestion is not to worry too much about numbers right now, especially comparing CI to local or wordpress to jetpack, I don't think that's very helpful, not as part of this PR anyway.

I didn't worry about CI vs local numbers, actually those numbers are the same. My worry was `wordpress` vs `jetpack` numbers and that's what I wanted to tackle in this PR. As such, I started with `errors`, which were actually failing the Lint task for the `jetpack` flavor, and then fixed a few warning as well to even the numbers out.

I did that because those errors/warnings were ignored for `jetpack` since the beginning of this project and I though this is a good opportunity to fix them. PS: Those should have been fixed individually, per PR, at the point of creation, but due to CI not running Lint on the `jetpack` flavor, those were ignored.

> If there is a discrepancy that you think would be helpful to address, please feel free to open a PR just for that, so it'll be easier to follow and test.

I think with those few Lint suppressions that I did we are now even.

> From the changeset, it looks like you're suppressing 2 VectorRaster and 1 Overdraw lint issues in place which looks good to me. However, I don't know why these 3 issues were specifically picked as there are other lint errors for these types.

Those issues were specifically picked because there were introduced on the `jetpack` flavor and that is the diff I was trying to even in this PR.

> I also don't have any context about the file movement, so not sure what to look for there. I guess that's what's fixing the Jetpack lint issues?

The file movement are actually fixing the 3 Lint errors that was failing the Lint task for the `jetpack` flavor.

> Overall I am a little confused by this PR - sorry about that! I think maybe it's doing a few things at once, considering that extra comment as well, so I am just not able to connect the dots.

Oh, I am sorry for making it more confusing that it need to be, here is a quick summary, it might be of help:
1. This 29dd4f8dd8871eacb0f86d4500e07ba9c23994d5 fixes all additional 3 Lint errors for the `jetpack` flavor.
2. This 29dd4f8dd8871eacb0f86d4500e07ba9c23994d5 and this 6cb2f609c9dd5b62c75c0e823a517e23ca0e9c6d fixes all 3 additional 3 Lint warning for the `jetpack` flavor.

Does this make sense a bit more now?

**Comment by oguzkocer** [comment]
> Does this make sense a bit more now?

Yes - well, kind of. It turns out you had detailed explanations in the commit messages, I just didn't see them because I didn't check each commit. And as I suspected the file movement was to fix the Jetpack lint issues, but there wasn't an indication of that in the PR description, so I wanted to double check before reviewing the PR.

Finally, from the commit message of 29dd4f8dd8871eacb0f86d4500e07ba9c23994d5, it looks like you did try to match the numbers a bit and it was a source of confusion for me as explained previously. Mainly because it was only suppressing certain issues, but leaving out others even though they were very similar. Hope that makes sense for where I was coming from with that comment.

I'll approve the PR now.

**Review by oguzkocer — APPROVED** [review]

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Many thanks for re-checking this PR! 🙏 

> I understand that and I appreciate the effort. However the issues go stale all the time, that's why we have a stalebot 🙈 so even though what you're making it better, it's not a silver bullet either. As I have also followed up in that comment, I don't think that's an issue. I just thought it was worth noting the issue first and then share my thoughts about why I don't feel it's a blocker for what you're trying to do. So all good 👍

Definitely, to be honest this silver bullet is non-existing when dealing with thinks like that, all you can try do is creating some kind of process around that! 😅 Thanks for sharing all your thoughts with me Oguz, I agree with you! 👍 

> Depends on who is writing the issue, it takes me a while to write any post/issue/pr description even if there is a template, because I re-read it at least 10 times. That issue you wrote is not very small either 😂 Anyway, that's just something every developer will have to consider themselves. Worst case, a developer will write an issue and realize it took them so much time that they'd have preferred to fix the issue and next time, that's what they'll do. :)

This is very true, everyone is different, I should keep that in mind going forward and should not take that for granted. 👍 I personally would prefer to have an issue every time, even if that take more time than writing the fix, just so that there is a history left behind. I do the same with commits. But, again, I understand your point, being able to fix it quicker than creating an accompanying issue first and then fix it. 😅

> Yes - well, kind of. It turns out you had detailed explanations in the commit messages, I just didn't see them because I didn't check each commit. And as I suspected the file movement was to fix the Jetpack lint issues, but there wasn't an indication of that in the PR description, so I wanted to double check before reviewing the PR.

True, I should have added my commits on my 1. and 2. bullet points in my description.

> Finally, from the commit message of 29dd4f8, it looks like you did try to match the numbers a bit and it was a source of confusion for me as explained previously. Mainly because it was only suppressing certain issues, but leaving out others even though they were very similar. Hope that makes sense for where I was coming from with that comment.

Yes, definitely, once more thank you for your time! 👍 

> I'll approve the PR now.

🙏

**Pull request merged**
