### PR TITLE
[Compile Warnings As Errors] WordPress Module - Resolve `PreferenceManager` Deprecated Warnings

### LINKED ISSUE #17181: Compiler Warnings as Errors - WordPress Module
Parent #17173

This issue is about resolving/suppressing the compile warnings for the `WordPress` app module.

Number of Warnings: `621`
    - Main Source: `481`
    - Debug Source: `2`
    - WordPress Source: `5`
    - Jetpack Source: `4`
    - Test Source: `128`
    - UI Test Source: `1`

- [x] Resolve/Suppress all warnings.
    - [x] Main Source (`481`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`6`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`3`)
            2. 'XYZ' is deprecated. Implement CoroutineScope interface and cancel all child coroutines in xyz (`2`)
            3. @Synchronized annotation is not applicable to suspend functions and lambdas (`1`) (with [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/10878#issuecomment-1258130096), cc @malinajirka)
        - [x] Resolve/Suppress `Deprecated` related warnings (`365`). @ParaskP7
            - [x] Specific
                1. `PreferenceManager` related warnings. @ParaskP7 #17215
                2. `LifecycleEvent` related warnings. @ParaskP7 #17223
            - [x] Generic 
                1. 'XYX' is deprecated. Deprecated in Java (`247` minus `Specific` above) @ParaskP7 #17246
                3. 'Xyz' is deprecated. Overrides deprecated member in 'xyz'. Deprecated in Java (`5`) @ParaskP7 #17287
                4. 'xyz' is deprecated. Use xyz instead. (`24`) @ParaskP7 #17287
                5. 'Xyz' is deprecated. This should be removed once we start receiving Xyz the source block from the backend (`2`) @ParaskP7 #17287
                6. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`87`) @ParaskP7 #17287
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`75`). @ParaskP7 #17291
            - Type (`44`)
                1. Unsafe use of a nullable receiver of type Xyz? (`4`)
                2. Type mismatch: inferred type is Xyz? but Xyz was expected (`13`)
                3. Elvis operator (?:) always returns the left operand of non-nullable type Xyz (`4`)
                4. The corresponding parameter in the supertype 'Xyz' is named 'xyz'. This may cause problems when calling this function with named arguments. (`4`)
                5. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`1`)
                7. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`18`)
            - Cast (`5`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`1`)
            - When (`26`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`26`)
        - [x] Resolve/Suppress `Other` related warnings (`35`). @ParaskP7 #17293
            1. This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API. (`1`)
            2. Parameter 'xyz' is never used (`17`)
            3. Parameter 'xyz' is never used, could be renamed to _ (`9`)
            4. Name shadowed: xyz (`2`)
            5. Parcelize annotations from package 'kotlinx.android.parcel' are deprecated. Change package to 'kotlinx.parcelize' (`1`)
            6. Variable 'xyz' initializer is redundant (`1`)
            8. There is more than one label with such a name in this scope (`1`)
            9. Condition 'xyz' is always 'xyz' (`2`)
            10. Unreachable code (`1`)
    - [x] Debug/WordPress/Jetpack Source (`11`) @ParaskP7
        - [x] Resolve/Suppress `Deprecated` related warnings (`11`). @ParaskP7 #17287
            1. 'Xyz' is deprecated. Deprecated in Java (`11`)
    - [x] Test/UI Test Source (`129`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`11`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`8`)
            2. 'Xyz' is deprecated. Deprecated in the favour of 'xyz'. Please note that the provided replacement does not rethrow channel's close cause as 'poll' did, for the precise replacement please refer to the 'poll' documentation (`3`)
        - [x] Resolve/Suppress `Deprecated` related warnings (`80`). @ParaskP7 #17300
            1. 'XYX' is deprecated. Deprecated in Java (`58`)
            2. 'xyz' is deprecated. Use xyz instead. (`2`)
            3. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`20`)
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`15`). @ParaskP7 #17300
            - Type (`8`)
                1. Type mismatch: inferred type is Xyz? but Xyz was expected (`3`)
                2. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`4`)
                3. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`1`)
            - Cast (`6`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`2`)
            - When (`1`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`1`)
        - [x] Resolve/Suppress `Other/Test/UI Test` related warnings (`23`). @ParaskP7 #17300
            - Other (`5`)
                1. Parameter 'xyz' is never used (`5`)
            - Test (`17`)
                1. Check for instance is always 'xyz' (`2`)
                2. Name contains characters which can cause problems on Windows: " (`15`)
            - UI Test (`1`)
                1. Name shadowed: fileName (`1`)
- [x] Enable all warnings as errors flag. @ParaskP7 #17318

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent: #17173
Partially Closes: #17181

This PR resolves all `PreferenceManager` related `Deprecated` warnings for the `WordPress` module and beyond (`Analytics` and `Editor` modules):

Modules:
- Analytics: [Resolve preference manager deprecated warnings for analytics.](https://github.com/wordpress-mobile/WordPress-Android/commit/2fae16df781a65c2a8017a2ddfb5d4c77c3fd963)
- Editor: [Resolve preference manager deprecated warnings for editor.](https://github.com/wordpress-mobile/WordPress-Android/commit/b5d47b56070d11f50ca796787737b9dd9dabf3ee)
- WordPress: [Resolve preference manager deprecated warnings for wordpress.](https://github.com/wordpress-mobile/WordPress-Android/commit/5f354a202dbe4bf1fd37ea8ad9e0b33e0d421469)

-----

PS: ~~@RenanLukas~~ @AjeshRPai I added you as the main reviewer, that is, in addition to @wordpress-mobile/apps-infrastructure team itself, but randomly, since I want someone from the `WordPress Android` team to primarily sign-off on that change. 🥇

FYI: I am going to randomly add more of you in those PRs that will follow, just so you become more aware of this change and how close we are on enabling `allWarningsAsErrors` by default everywhere. 🎉

-----

To test:

- Smoke test both, the `WordPress` and `Jetpack` apps, and see if their settings and preference related functionalities are working as expected. For example, and per module, you could test the following:
  - Analytics: Switch on and off the `Collect Information` privacy setting and verify that the `Logcat` is showing/hiding the `🔵 Tracked: xyz` related information. To find this setting go to: `My Site` tab -> `Me` options -> `App Settings` -> `Privacy settings`
  - Editor: Switch on and off the `Use Block Editor` site setting and verify that the `Dialog` that appears when using the legacy editor is showing/hiding. The dialog's title should be `Try the new Block Editor`. To find this setting go to: `My Site` tab -> `Site Settings` configuration
  - WordPress: Update the interface language and verify that the app's language changes accordingly. To find this setting got to: `My Site` tab -> `Me` options -> `App Settings` -> `Interface Language`

PS: The above testing should be enough to verify that all other setting related affecting changes are also working as expected.

-----

## Regression Notes
1. Potential unintended areas of impact

The settings and preference related functionalities are not working as expected.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @RenanLukas !

Apologies for the direct ping, but I wonder if you have the capacity for reviewing and testing this PR. Let me know, and if not, I can assign it to another engineer. I would like to avoid keeping this PR open for much longer, risking it becoming stale.

**Comment by ParaskP7** [comment]
👋 @RenanLukas !

As I am seeing you being busy with other priorities I am assigning this PR review to @AjeshRPai for now. Ajesh, let me know if that's okay with you too. I have updated the PR description accordingly. Thank you all for helping out in reviewing, testings and ultimately merging this to `trunk`. 🙇

**Comment by AjeshRPai** [comment]
@ParaskP7 Thanks for the ping 👍🏼 . I will review the PR tomorrow. I hope the PR is not urgent. Let me know if a review is needed before that.

**Comment by ParaskP7** [comment]
> @ParaskP7 Thanks for the ping 👍🏼 . I will review the PR tomorrow. I hope the PR is not urgent. Let me know if a review is needed before that.

Thank you so much @AjeshRPai ! 🙇

PS: No, this PR is not that urgent, so please feel free to review it when you get some extra time this week. It is just that this needs to be done sooner than later in order to avoid having it become stale.

**Review by AjeshRPai — APPROVED** [review]
Thanks for providing me with all the details for the review in the commit messages as well as in the description. 🙌🏼 

I have 
- tested the PR by going through the changes in every commit and reading the reference links mentioned in the commit messages and everything LGTM
- done a smoke testing of the WordPress and everything looks fine here 
   - Logcat is showing/hiding the 🔵 Tracked: XYZ related information 🟢 
   - New block editor dialogue is shown 🟢 
   - Changed Interface language 🟢 

Am going to approve but not merge the PR so that anyone from @wordpress-mobile/apps-infrastructure can have a look. Please feel free to merge the PR at your convenience.

**Comment by ParaskP7** [comment]
Awesome, thank you so much for reviewing and testing this PR @AjeshRPai, you rock! 🙇 ❤️ 🚀

**Pull request merged**
