### PR TITLE
Link Day One attribution to dayoneapp.com when tapped

### PR DESCRIPTION
**Pull request by roundhill**
This is the Android version of https://github.com/wordpress-mobile/WordPress-iOS/pull/23586

In this PR we are opening dayoneapp.com when a user taps on the "Day One" attribution in the blogging prompt. There's an "external link" icon added as well.

Screenshot 2024-09-16 at 1 14 40 PM

-----

## To Test:

* Sign into Jetpack
* On the `My Site` tab, if you have a Day One prompt, you should see the external link icon next to it.
* Tap it!
* You should be at dayoneapp.com
* Bonus, change the `BloggingPromptAttribution` class to use these values for `DAY_ONE`:

```
DAY_ONE(
        "dayone",
        R.string.my_site_blogging_prompt_card_attribution_day_one,
        R.drawable.ic_dayone_24dp,
        false
    ),
```

In this case you should _not_ see the external icon and tapping on it should do nothing. This simulates the behavior for bloganuary prompts that we don't want to show the icon for or make tappable. (I never saw any of these in my testing)

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by notandyvee** [comment]
Good work! It all works as expected.

Wondering what you think about shrinking the clickability of the "from Day One" view? On my device it's centered. But if I click to the far left or right, but on the same horizontal line as the "From Day One" view, the day one web link gets triggered. Maybe this is acceptable. But the "View all responses" and "Answer Prompt" are both only directly clickable. Clicking around it does nothing.

Additionally, `containerRes` doesn't appear to be directly used. Do you foresee it being used? If not, maybe a boolean would be a better choice?

**Comment by roundhill** [comment]
> Wondering what you think about shrinking the clickability of the "from Day One" view? On my device it's centered. But if I click to the far left or right, but on the same horizontal line as the "From Day One" view, the day one web link gets triggered. Maybe this is acceptable. But the "View all responses" and "Answer Prompt" are both only directly clickable. Clicking around it does nothing.
> 
> Additionally, `containerRes` doesn't appear to be directly used. Do you foresee it being used? If not, maybe a boolean would be a better choice?

Thanks @notandyvee! I was confused about what those ids were for, a boolean is better! I also addressed the view tap area, and also added a tappable background selector.

**Review by notandyvee — APPROVED** [review]
Thanks for the changes. Code LGTM 🍕 .

I didn't think about this until just now. But what if we want to support future attribution clicks? Say, Tumblr as an example.  Not a change you need to make since theres no need at the moment. But instead of the external link set in the viewmodel, maybe set it in the `BloggingPromptAttribution` enum. Then we can pass it from the click listener. The link is decided by the enum. Downside is we'll have a bunch of nulls params. But it'd be more dynamic than assuming the attribution click is only day one, which it currently is. Again, not required. Just thinking out loud.

**Comment by roundhill** [comment]
> I didn't think about this until just now. But what if we want to support future attribution clicks? Say, Tumblr as an example. Not a change you need to make since theres no need at the moment. But instead of the external link set in the viewmodel, maybe set it in the `BloggingPromptAttribution` enum. Then we can pass it from the click listener. The link is decided by the enum. Downside is we'll have a bunch of nulls params. But it'd be more dynamic than assuming the attribution click is only day one, which it currently is. Again, not required. Just thinking out loud.

Good point! I think we'll leave that for the next dev to sort out if they want to add a different click ;)

**Pull request merged**
