### PR TITLE
Add source post link to pingback

### LINKED ISSUE #7852: Make pingback notifications easier to moderate
Implement the designed proposed on: https://github.com/wordpress-mobile/WordPress-iOS/issues/9479 for pingback notifications.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #7852 
This solution adds "Read the source post" button to Pingbacks. In future we might start getting the block from the backend so I've tried to make the code generating the block as separated as possible. 
I have implemented the designs in a bit hacky way ("If the comment is a pingback, show button instead of the code") but I can easily revert it - @jleandroperez and @elibud 

Solution with the design hack:

screenshot_1528366094

Solution without the design hack:

screenshot_1528368181

To test:
* Open a pingback notification
* You see a "Read the source post" button
* If you click it, you get redirected to the source post of the pingback

### CODE REVIEW

**Comment by elibud** [comment]
I personally prefer how it looks with the design hack, but I have no idea what's involved in the hack so I'll leave that decision to you.

**Comment by hypest** [comment]
Gave the PR a super quick look @planarvoid and here's a screenshot of what's displayed when I tap on the "READ THE SOURCE POST" button:

screenshot-1528884507576

I let it there to load for some time but it never seems to finish.

FWIW, here are the 2 posts I tried that perform a pingback:
https://stefanostestsite2.wordpress.com/2018/06/13/cross-ping/
https://stefanostestsite2.wordpress.com/2018/06/13/another-cross-link/

**Comment by planarvoid** [comment]
@hypest you're right! I was reusing an existing click listener and I've just noticed it doesn't work. That's what happens when we pass in `-1` as a `siteId` and we expect `0` as the empty value 😢 . I've fixed that now.

**Comment by hypest** [comment]
🚢 it!

**Pull request merged**
