### PR TITLE
Issue/2389 actionbar shadow

### PR DESCRIPTION
**Pull request by tonyr59h**
Resolves https://github.com/wordpress-mobile/WordPress-Android/issues/2389

I checked through all the screens and nothing seems out of place due to the theme changes.

### CODE REVIEW

**Comment by nbradbury** [comment]
This doesn't appear to be working. All of the screens that previously had a drop shadow still have one.

device-2015-03-10-053633

device-2015-03-10-053830

**Comment by tonyr59h** [comment]
Gah, looks like the API 18 solution isn't a catch-all. I've set the elevation to 0 in all the Activities as well now.

**Comment by nbradbury** [comment]
Setting the elevation to zero appears to work. Is `setWindowContentOverlayCompat` still necessary?

**Comment by tonyr59h** [comment]
Tested on API 18 emulator and 5.0 device, all screens looking good without needing the workaround.

**Comment by nbradbury** [comment]
This looks good. I did notice that `WPActivityUtils` is still in the `import` list of the activities that used to call `WPActivityUtils.setWindowContentOverlayCompat`. Once that minor detail is corrected I'll merge this.

**Comment by tonyr59h** [comment]
Good eye :eyes:

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
