### PR TITLE
issue/3595-my-profile-single-line-input

### LINKED ISSUE #3595: My profile: Input dialogs should be fixed to one line
Ex: screencap-2016-01-12t12-16-35 0100

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3595 - "My Profile" inputs are now limited to a single line, with the exception of "About Me."

### CODE REVIEW

**Comment by nbradbury** [comment]
> wrapping the lines to 120 as per the code style guide ;)

I was wondering where that 120 recommendation came from :) Do you have a relevant link?

**Comment by hypest** [comment]
@nbradbury https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CODESTYLE.md

**Comment by nbradbury** [comment]
Oh, I see I completely misunderstood you - thought you were referring to the input length, note the code line length.

**Comment by hypest** [comment]
Easy to misunderstand in the context of the specific ticket actually :)
I could have been a bit more descriptive though ;)

**Comment by nbradbury** [comment]
@hypest Done!

**Comment by hypest** [comment]
:ship:it

**Pull request merged**
