### PR TITLE
Update SiteCreationService from latest AutoForeground

### PR DESCRIPTION
**Pull request by hypest**
Bring over to SiteCreationService the latest AutoForeground updates from `develop`. While at it, unify and remove code duplication by moving common functionality inside the `AutoForeground` class.

To test #1:
* Make sure that the testplan in https://github.com/wordpress-mobile/WordPress-Android/pull/6878#totest still works OK

To test #2:
* Make sure that the testplan in https://github.com/wordpress-mobile/WordPress-Android/pull/6825#totest also works OK

### CODE REVIEW

**Comment by nbradbury** [comment]
Unrelated to this PR, but is the wording in this notification set in stone? I think we can just say "Logging in..." and drop the "Please wait while logging in."

screenshot_1513180602

**Comment by hypest** [comment]
Thanks for picking this up for review @nbradbury !

The notification copy is planned to be updated later, to match the design as shown in #6929. Is it OK with you to address it at that point?

**Comment by nbradbury** [comment]
> The notification copy is planned to be updated later, to match the design as shown in #6929. Is it OK with you to address it at that point?

Yep, that's fine.

**Comment by nbradbury** [comment]
Code-wise this looks good to me, but I've asked @mzorz to take a look since he tackled the original PR.

**Comment by mzorz** [comment]
Hi @hypest  - the code looks good to me as well  👍  (except for the `strings.xml` conflict that has just appeared with `develop` - check that)

While testing, had the good luck to make it  crash though, this is what I did:
1. following the steps in https://github.com/wordpress-mobile/WordPress-Android/pull/6825#totest:
2. after tapping "+" and sending the app to the background, I can see the foreground notification appear. My phone was locked in portrait, so I decided to unlock it and give some orientation changes a shot. It was then when the crash happened:

```
12-14 09:09:22.696 16007-16007/org.wordpress.android D/AndroidRuntime: Shutting down VM
12-14 09:09:22.699 16007-16007/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.wordpress.android, PID: 16007
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.ThemeModel.getThemeId()' on a null object reference
                                                                           at org.wordpress.android.ui.accounts.signup.SiteCreationService.activateTheme(SiteCreationService.java:214)
                                                                           at org.wordpress.android.ui.accounts.signup.SiteCreationService.access$700(SiteCreationService.java:36)
                                                                           at org.wordpress.android.ui.accounts.signup.SiteCreationService$3.onSettingsSaved(SiteCreationService.java:294)
                                                                           at org.wordpress.android.ui.prefs.SiteSettingsInterface$5.run(SiteSettingsInterface.java:997)
                                                                           at android.os.Handler.handleCallback(Handler.java:789)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-14 09:09:22.705 914-5742/? W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.accounts.NewBlogActivity
```

**Comment by hypest** [comment]
Thanks for the pass @mzorz ! I've added a commit to help with the `strings.xml` conflict but unfortunately, I'm not able to replicate the crash. Do you have some more specific steps to reproduce?

**Comment by mzorz** [comment]
> I'm not able to replicate the crash. Do you have some more specific steps to reproduce?

Not able to reproduce myself. Probably a combination of factors, and probably not strictly related to the PR itself.

Let's merge once Travis passes 👍

**Comment by mzorz** [comment]
:shipit:

**Comment by hypest** [comment]
Travis build fixed by borrowing the fix commit ce25382 from develop. Ready for another pass or merge @mzorz , thanks!

**Pull request merged**
