### PR TITLE
Issue/21237 unused dependencies

### LINKED ISSUE #21237: Remove unused dependencies
We now have a tool to help find unused dependencies: pbArwn-6Hw-p2

We should use this to locate our unused dependencies and remove them one-by-one. This will be tedious but could save us from so many dependabot PRs and improve build time.

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #21237

This PR removes several dependencies that were identified as unused via `./gradlew buildHealth`:

```
MODULE: WordPress
  androidTestImplementation com.squareup.okhttp3:mockwebserver
  implementation 'org.greenrobot:eventbus'
  implementation 'androidx.activity:activity-ktx'
  implementation 'androidx.arch.core:core-common'
  implementation 'androidx.arch.core:core-runtime'
  implementation 'androidx.lifecycle:lifecycle-livedata-ktx'
  implementation 'androidx.lifecycle:lifecycle-runtime-ktx'
  implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx'
  implementation "androidx.work:work-runtime-ktx"
  implementation "com.google.android.play:app-update-ktx"
  implementation "com.google.android.play:review-ktx"

MODULE: libs/editor
  androidx.lifecycle:lifecycle-runtime

MODULE libs/image-editor
  androidTestImplementation 'androidx.test.espresso:espresso-core'
  androidTestImplementation 'androidx.test.ext:junit'
  implementation 'androidx.activity:activity-ktx'
  implementation 'androidx.lifecycle:lifecycle-runtime'
```

Note that `buildHealth` identified many more issues besides unused dependencies, but this PR seeks only to remove those.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ParaskP7 — APPROVED** [review]
👋 @nbradbury !

I have reviewed and also tested this PR, everything LGTM, great job and thanks for dealing with unused dependencies, only 2 left to go! 🌟 🌟 🌟 

For those 2 left to go I have the following for you:

1. `org.mockito:mockito-android`: After testing this myself, I believe this is a false-positive and we can ignore that by applying this `dependencyAnalysis` configuration below, on the `WordPress` module, ideally below the `dependencies { ... }` block, effectively marking this as false-positive:

```groovy
dependencyAnalysis {
    issues {
        onUnusedDependencies {
            // This dependency is actually needed because otherwise UI tests fail to run (but do compile).
            exclude("org.mockito:mockito-android")
        }
    }
}
```

2. `com.automattic:Automattic-Tracks-Android`: After testing this myself, I understand that this dependency is indeed unused from within the `WordPress` module, and only required on the `libs:analytics` module, so, effectively this can be removed too, but I have more for you:
    - See `import com.automattic.android.tracks.TracksClient;` import.
    - A while ago, @wzieba added this 214243b2c9d2e1ffe96e1c20f01632d9b08b3c0d more targeted `com.automattic.tracks:crashlogging` dependency, effectively replacing the overall `Tracks` dependency with the specific `Crash Logging` dependency ([PR](https://github.com/wordpress-mobile/WordPress-Android/pull/20733)). But, there was a left-over, the included `$gradle.ext.tracksBinaryPath` build on the `WordPress` module, which Andy Valdez added tracks to the included builds ([PR](https://github.com/wordpress-mobile/WordPress-Android/pull/20193)).
    - This means that the included build on `WordPress` was no longer working-ish, or as expected, as this `Tracks` dependency is now unused over the `Crash Logging` one. After looking into it more, I understand that the actual `Tracks` dependency is only needed on the `libs:analytics` module, which wasn't converted to adhere to included builds. I get this was an oversight (see import).
    - No matter, I tested the included builds after moving it to the `libs:analytics` module, and it is not working as expected, and as such, as part of this PR, I would also recommend removing this functionality, and everything related to `Tracks` included builds, and then, as some point in the future, should it be needed, to add it back, but this time for `Crash Logging` purposes only (might be tricky). @wzieba wdyt? 🤔 

Having said the above, I am tentatively approving this for now, as to now block this PR, but ideally, we can easily get rid ALL unused dependencies if we want to on JP/WPAndroid.

**Comment by wzieba** [comment]
👋 hi folks

> `com.automattic:Automattic-Tracks-Android`

I think in the proposed diff, no changes related to `com.automattic:Automattic-Tracks-Android` have been applied.

I'm okay with removing or fixing the code related to included builds if it doesn't work.

**Comment by ParaskP7** [comment]
👋 @wzieba !

> I think in the proposed diff...

Which proposed diff do you mean? 😊

**Comment by wzieba** [comment]
I mean the diff from this PR: AFAIU it didn't remove dependency to `com.automattic:Automattic-Tracks-Android`, I'm not sure why we're discussing this matter here 😅 .

**Comment by wzieba** [comment]
I think this PR might also benefit from the new, "summarised" version of dependency diff. Here's the output: https://github.com/wordpress-mobile/WordPress-Android/pull/21246#issuecomment-2361271931

Some dependencies removed here were not removed from the classpath (e.g. eventbus) because other dependencies provide it (FluxC in this case).

**Comment by ParaskP7** [comment]
> I mean the diff from this PR: AFAIU it didn't remove dependency to com.automattic:Automattic-Tracks-Android, I'm not sure why we're discussing this matter here 😅 .

Yea, exactly, because it wasn't removed, but should, we are discussing this matter! 😄

**Comment by wzieba** [comment]
Ah I see the reasoning now. I think we can follow up on Tracks maybe on a different PR, as @nbradbury stated that

> Note that buildHealth identified many more issues besides unused dependencies, but this PR seeks only to remove those

and Tracks is not present in the list in PR description! Anyway, I'm fine with any fixes/updates regarding included builds of Tracks - I think it's not used feature anyway, we can remove it 🙂.

**Comment by nbradbury** [comment]
> I have reviewed and also tested this PR, everything LGTM, great job and thanks for dealing with unused dependencies, only 2 left to go!

Thanks for the review @ParaskP7 ! I took your advice and added Mockito to `onUnusedDependencies`. Resolving the issue with Tracks definitely sounds like something for another PR. I went ahead and added that to `onUnusedDependencies`, too, along with a comment, to suppress the warning about it being unused.

**Comment by ParaskP7** [comment]
👋 @nbradbury and thanks for the changes!

FYI: For `org.mockito:mockito-android` there is little we could do, so ignoring this is perfectly okay, especially since this is a `androidTest` related dependency, but for `com.automattic:Automattic-Tracks-Android`, if it were me, I wouldn't ignore that. Instead, after decided to not deal with this in this PR, I would just left it be there, seen as unused dependency, so that we don't forget to deal with that in the future, thus avoid putting it under the carpet (it ignored by our monitoring tool also).

PS: Actually, comparing to the other dependencies you removed, this case with `com.automattic:Automattic-Tracks-Android` is the best example of how this tool can shine, identifying such situation where a misconfiguration has occurred, whcih needs fixing, so personally, I love when that happens, it being an opportunity to improve/fix things.

**Pull request merged**
