### PR TITLE
Update colors in login library to 2.5.0

### PR DESCRIPTION
**Pull request by planarvoid**
This PR updates blues in the login library to the latest updates in the color palette.

To test:
- Check the colors during login look OK

## Regression Notes
1. Potential unintended areas of impact
- None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Nothing, since there are none

3. What automated tests I added (or what prevented me from doing so)
- Color changes shouldn't be automatically tested

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — CHANGES_REQUESTED** [review]
👋 @planarvoid !

Thanks a lot for creating this PR so quickly! 🙏 

In addition to your changes, I also suggest the following:
1) `wp_blue_40` to be replaced with `wp_blue_30`,
2) The library's `night/themes.xml` values for `colorPrimary`, `colorPrimaryVariant`, `colorSecondary` and `colorSecondaryVariant` to be update to match the same to that of the app's `night/styles.xml` values, see below:
```
        <item name="colorPrimary">@color/blue_30</item>
        <item name="colorPrimaryVariant">@color/blue_50</item>
        <item name="colorSecondary">@color/blue_30</item>
        <item name="colorSecondaryVariant">@color/blue_50</item>
```

**Comment by ParaskP7** [comment]
👋 @planarvoid !

Do you need any help in progressing with this?

**Comment by planarvoid** [comment]
makes sense @ParaskP7 , I've fixed it in 493425db5f

**Review by ParaskP7 — APPROVED** [review]
👋 @planarvoid !

Awesome, everything LGTM, good job! 🚀 

PS: Feel free to merge when CI completes.

**Pull request merged**
