### PR TITLE
Make the stats widget resizable

### LINKED ISSUE #3336: Stats widget: Make it available on smaller 5.X/6.X devices

### PR DESCRIPTION
**Pull request by daniloercoli**
Default width is now set to 5 cells on ALL versions of Android. Fallback to 4 cells when the space for 5 cells is not available on the screen.

The widget is now resizable, so you can resize it to 4 cells when 5 cells are available on the device.

Fix #3336

### CODE REVIEW

**Comment by maxme** [comment]
Something's weird. I can resize the widget on creation, but once it's on the launcher, I can't resize it: https://cloudup.com/cgif58ADlkW

**Comment by daniloercoli** [comment]
@maxme Can't repro it. Bet there is something wrong on your launcher. I tried it on different emulators without problems.
resize-widget

**Comment by maxme** [comment]
Weird, I'll try on my nexus 9

**Comment by maxme** [comment]
In the meantime:
* Can you move `src/main/res/drawable/stats_widget_preview.png` to `src/main/res/drawable-nodpi`?
* If you don't want to create xhdpi/xxhdpi versions of the stats widget header icon, can we reuse `ic_tab_sites_pressed`? They're the exact same icons, and `ic_tab_sites_pressed` is correctly sized (copy and rename if you think it could change in the future).

**Comment by maxme** [comment]
I can't resize it at all on my Nexus 9. I guess 250dp and 320dp is the same number of cells on this screen.

**Comment by daniloercoli** [comment]
Yep, 320dp is 4 cells only.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
