### PR TITLE
Feature/photo picker preview

### PR DESCRIPTION
**Pull request by nbradbury**
Adds a preview icon to items in the new photo picker. Tapping this icon opens a fullscreen preview, tapping elsewhere selects the photo, and long press (as before) enables multi-select.

android-media-preview-icon

### CODE REVIEW

**Comment by daniloercoli** [comment]
Code inspector says to check `getItemAtPosition`, since it can returns `null`.

I see there are calls to it, that are not wrapped inside a `if (isValidPosition(position)) {` call. 
Should we check if the return value is `null` or add `isValidPosition` around them?

**Comment by daniloercoli** [comment]
Code looks good. We can merge this, once the comment above is addressed.

**Comment by nbradbury** [comment]
> Code inspector says to check getItemAtPosition, since it can returns null

I'm not seeing any problems. The inspector warned me about two calls to `getItemAtPosition`, but both of them use `isValidPosition` first.

**Comment by daniloercoli** [comment]
Oh right. I misread a call at line 284 that seemed without `isValidPosition` first.

**Pull request merged**
