### PR TITLE
Feature/material theme and Dark Theme support Try. 2

### PR DESCRIPTION
**Pull request by khaykov**
Because of the issue in block editor we postponed merging this into develop. Trying to do it again :)

This PR moves app to the material theme and adds Dark Theme support.

This is a feature branch and most of the commits were reviewed.

Gutenberg PR: [RNMobile] - https://github.com/WordPress/gutenberg/pull/21139
Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2061

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
Thanks for re-opening, I will look at the bug which is showing on Block Editor.

**Comment by hypest** [comment]
FWIW, I managed to pinpoint a commit that seems to be the first to introduce the editor scrolling issue (https://github.com/wordpress-mobile/gutenberg-mobile/issues/2056) and looks to be 5e4f3b03f9. The one before it (94871fe427) doesn't manifest the issue). Note, both commits fail to build on their own. I had to add the `PostSettingsCardView` style back ([see this diff](https://gist.github.com/hypest/4cc9b63b66945585d373c5f9f649f10e))

**Comment by hypest** [comment]
In the effort to try to merge this work to the block editor release (1.25.0, ongoing at the time of writing), we'll stop working on this PR and instead focus on the PR that is targeting the release: https://github.com/wordpress-mobile/WordPress-Android/pull/11580

**Comment by marecar3** [comment]
Closing in favor: https://github.com/wordpress-mobile/WordPress-Android/pull/11580

**Pull request closed without merging**
