### PR TITLE
Use gridicons for media placeholders when available

### LINKED ISSUE #6242: Media placeholders should use gridicons
`WordPressMediaUtils.getPlaceholder()` needs to be changed to return gridicons rather than the outdated icons we currently return.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6242 - replaces the media placeholder images with gridicons, when available.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Should we use the new media placeholder images everywhere in the app (and remove the raster)?

- `media_image_placeholder` is used in `photo_picker_fragment.xml` and `HtmlToSpannedConverter.java`

- `media_movieclip` is used in `HtmlToSpannedConverter.java`

- `drawable/media_document` is used in `media_grid_item.xml`

- `media_audio` can be deleted.

**Comment by nbradbury** [comment]
@daniloercoli I got rid of `media_document` and `media_audio` in b7cdb4f, but I don't think we can remove those other two due to vector compatibility issues.

**Comment by daniloercoli** [comment]
> I don't think we can remove those other two due to vector compatibility issues.

Right, right 👍

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
