### PR TITLE
Untangle http:// and wordpress:// deeplinking URLs

### PR DESCRIPTION
**Pull request by maxme**
Fixes an issue that made `wordpress://` URLs non-functional.

This was probably introduced in: https://github.com/wordpress-mobile/WordPress-Android/pull/9957

Note that I'm not sure why the issue is happening, according to the [documentation](https://developer.android.com/training/app-links/deep-linking) this should work fine, and other urls like: `http://viewpost` should also work as well (which is an unwanted side effect).

# Test

#### Before the patch, run:
```
adb shell am start \
 -W -a android.intent.action.VIEW \
 -c android.intent.category.BROWSABLE \
 -d "wordpress://viewpost?blogId=124661775\&postId=1194"
```

The app won't open.

#### After the patch, run the same command:

```
adb shell am start \
 -W -a android.intent.action.VIEW \
 -c android.intent.category.BROWSABLE \
 -d "wordpress://viewpost?blogId=124661775\&postId=1194"
```

The app will open and show the specified post in the reader.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
Test results:

✅ `wordpress://viewpost?blogId=124661775\&postId=1194`
✅ `wordpress://stats`
✅ `wordpress://notifications`
⏳ `wordpress://read...`
✅  `https://stefanosuser.wordpress.com/2020/02/20/comments-issue/`

**Comment by hypest** [comment]
Feel free to merge @maxme after updating from develop to resolve the merge conflict 👍

**Comment by adityabhaskar** [comment]
@maxme Tangentially related: Is it possible to send an intent to open a post for editing in the WordPress app? Something on the lines of:
`wordpress://post?blogId=[site_id]&postId=[post_id]` or `https://wordpress.com/post/[blog_id]/[post_id]`.

At the moment they both just open the post editor for a blank new post in the currently selected site.

The reference code starts here: https://github.com/wordpress-mobile/WordPress-Android/blob/31cf4fe3094ddf13a86dfdbfdc2455564314652d/WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java#L133

**Comment by maxme** [comment]
@adityabhaskar That's a good idea and this would be possible if we changed that code a bit to capture the blog id and then open the editor for this specific site (similar to what is done with the "Share with" feature).

**Comment by adityabhaskar** [comment]
@maxme Should I create a new issue with this and tag you in it?

**Comment by maxme** [comment]
Yes please!

**Pull request merged**
