### PR TITLE
My Site Dashboard: Tabs - Track tab tapped and tab shown events

### PR DESCRIPTION
**Pull request by zwarm**
Parent #16007 

This PR introduces the following track events:

- `my_site_tab_tapped` with property `tab=dashboard|site_menu`. Any time the user taps on a tab or swipes to another tab
- `my_site_site_menu_shown`. Any time the tab is shown - includes user gestures & other types of navigation to my site
- `my_site_dashboard_shown`. Any time the tab is shown - includes user gestures & other types of navigation to my site

**To test:**
- Launch the app
- If not enabled, please enable `MySiteDashboardTabsFeatureConfig`, then restart the app
- Navigate to My Site -> Site Menu tab
- Verify the logs contain:
 🔵 Tracked: my_site_tab_tapped, Properties: {"tab":"site_menu","default_tab_experiment":"dashboard|site_menu|nonexistent"}
 🔵 Tracked: my_site_site_menu_shown, Properties: {"default_tab_experiment":"dashboard|site_menu|nonexistent"}
- Tap the "Dashboard" tab
- Verify the logs contain:
🔵 Tracked: my_site_tab_tapped, Properties: {"tab":"dashboard","default_tab_experiment":"dashboard|site_menu|nonexistent"}
🔵 Tracked: my_site_dashboard_shown, Properties: {"default_tab_experiment":"dashboard|site_menu|nonexistent"}

## Regression Notes
1. Potential unintended areas of impact
Tabs are not tracked

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and unit testing

3. What automated tests I added (or what prevented me from doing so)
Add two tests to `MySiteViewModelTest`

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Looks good, @zwarm 👍 

Just that with my site tab selected, both `my_site_tab_tapped` and `my_site_{tab}_shown` were tracked even when I switched from `Reader` tab to `My Site` tab. Is that expected? When can we expect `my_site_{tab}_shown` to be tracked without `my_site_tab_tapped` getting tracked? Maybe we need just one of these events. Let's discuss.

**Comment by zwarm** [comment]
>Just that with my site tab selected, both my_site_tab_tapped and my_site_{tab}_shown were tracked even when I switched from Reader tab to My Site tab. Is that expected? 

@ashiagr  I'm with you, but that's what iOS is doing too. See this screenshot of the iOS log. 

Alt desc 

I started out using `addOnTabSelectedListener` on the tabLayout for "tapped", but that only captures tab taps and not swipes.

**Comment by zwarm** [comment]
@ashiagr - Had a discussion with @leandroalonso and yes, both events are collected at the same time, except for iPad. We will keep both events as:is. Thanks for calling this out and having me double check. 👍

**Review by ashiagr — APPROVED** [review]
Thanks for double-checking @zwarm! 

:shipit:

**Pull request merged**
