### PR TITLE
Issue/6142 media browser filter

### LINKED ISSUE #6142: Replace media browser filter
Replace the current media browser dropdown filter with a TabBar that mimic the Calypso filter.

screen shot 2017-06-23 at 5 14 26 pm

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6142 - Updates the media browser to use tabs rather than a dropdown spinner for the filter. A few notes:

* This PR continues to use ALL / IMAGES / UNATTACHED as the filters. A subsequent PR will use the same filters as Calypso.
* I started off using a `ViewPager` but I was concerned about the resource usage of multiple media grids so I stuck with a single fragment and a `TabLayout`
* Getting this working required a lot more changes and cleanup than I expected, apologies in advance for the number of modifications
* ~~This PR needs a design review from @mattmiklic before being merged~~

device-2017-06-24-194719

### CODE REVIEW

**Comment by mattmiklic** [comment]
> This PR needs a design review from @mattmiklic before being merged

The screenshot looks good to me; appears to be right in line with the Material spec for tabs.

**Comment by daniloercoli** [comment]
I see the loading spinner appearing for while every time I go back to the grid view from the picture preview screen.
 - Open Media
- Tap on a picture
- The picture is loaded in the preview screen
- Tap back
The loading spinner is briefly shown on the screen.
https://cloudup.com/czOT2rcqRlc

**Comment by daniloercoli** [comment]
When in search mode the space taken by the tabbed interface is still there. Is this on purpose? 
device-2017-06-27-101053

Can't we "remove" that empty space?

**Comment by nbradbury** [comment]
> I see the loading spinner appearing for while every time I go back to the grid view from the picture preview screen.

Fixed in 8fc1e7f.

> When in search mode the space taken by the tabbed interface is still there. Is this on purpose?

That is on purpose but I'm open to suggestions. The problem with removing the space is it causes the media grid to move up, which is jarring - especially when it's done due to initiating multiselect.

**Comment by daniloercoli** [comment]
>That is on purpose but I'm open to suggestions. The problem with removing the space is it causes the media grid to move up, which is jarring - especially when it's done due to initiating multiselect.

I noticed that removing the space could be jarring immediately after I had submitted the comment above, but forgot to comment again. I think it's ok having the white space there for now, otherwise the jumping is even worse. Maybe we can add some sort of label there. 

Anyway, while testing this PR I noticed that the state of new items is not correctly shown in some cases. Try to add a media to the WP Library, by taking a new picture. When the picture is taken is shown in the media grid with the `enqueued` state. Then when the upload finishes the state is refresh. See the video linked here: https://cloudup.com/cntO_JfoKzQ

**Comment by nbradbury** [comment]
> while testing this PR I noticed that the state of new items are not correctly shown in some cases.

Can we open a separate issue for that? I don't think that's related to this PR.

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
