### PR TITLE
[Lib] Update tracks targetSdk version from 33 to 34.

### LINKED ISSUE #20360: Upgrade Tracks to Android 14
Issue can be tracked here: https://github.com/Automattic/Automattic-Tracks-Android/issues/199

### PR DESCRIPTION
**Pull request by notandyvee**
Fixes #20360

-----

This PR updates tracks so it's ready for Android 14 update. The `targetSdk` is updated from 33 to 34.

## Note

- [x] This PR https://github.com/Automattic/Automattic-Tracks-Android/pull/200 needs to be updates before merging. It's using a CI build for testing purposes.
- [x] Update Automattic-Tracks-Android version here

## To Test:

🚬 Smoke test the app. Filter the logcat by "track" so you can see the tracks logs working.

-----

## Regression Notes

1. Potential unintended areas of impact

    All tracks logs.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    🚬 Smoke test.

3. What automated tests I added (or what prevented me from doing so)

    n/a

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by notandyvee** [comment]
Damn. Just realized I didn't add a review 🤦🏻

**Comment by ravishanker** [comment]
👋 @notandyvee - Update Milestone to 24.6 since it seems not ready nor required for 24.5

**Comment by notandyvee** [comment]
> Update Milestone to 24.6 since it seems not ready nor required for 24.5

Hey @ravishanker . It was ready. But tracks needs to be reviewed first. You can review here: https://github.com/Automattic/Automattic-Tracks-Android/pull/200

**Comment by notandyvee** [comment]
Appreciate the review @ravishanker . Updated the tracks update. If you could just 🚬 test.

**Review by ravishanker — APPROVED** [review]
LGTM 👍

**Pull request merged**
