### PR TITLE
Implement Remote field config feature 

### PR DESCRIPTION
**Pull request by AjeshRPai**
Part of # https://github.com/wordpress-mobile/WordPress-Android/issues/17331
Dependant fluxC PR - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2593

## Changes
This PR adds the functionality to fetch the remote config field in the Wp Android app. 

This PR has the following changes 
- [Adds: Remote config annotation](https://github.com/wordpress-mobile/WordPress-Android/commit/ff1275b6333e898dc359d5309c2b8e09180977c9)
- [Adds: a generic remote config field](https://github.com/wordpress-mobile/WordPress-Android/commit/09aa798a1f9236cb33378e39fdea2d69150e449c)
- [Adds: remote fields for feature removal](https://github.com/wordpress-mobile/WordPress-Android/commit/131039e40302ddf887dc02161c28636aa8e47d4b)
- [Updates: naming of remote config to remote feature config](https://github.com/wordpress-mobile/WordPress-Android/commit/ee7ee6ae55d438810c0786149f8b1996afcada5f)
- [Adds: the logic for fetching and storing remote field configs in RemoteFieldConfigRepository](https://github.com/wordpress-mobile/WordPress-Android/commit/5cefb104f0547d4a6279913b559d884200259cbf)
- [Updates: RemoteFieldConfigRepository logic to use app config](https://github.com/wordpress-mobile/WordPress-Android/commit/ffdb5a6ad9cf1f0c6b7888dc482f62a639e87af7)
- [Adds: remote config fields to the debug settings view](https://github.com/wordpress-mobile/WordPress-Android/commit/8cb6fb81ee8e40f2d499e667186f5803f3b85023)

###  👀   Verify that the default Remote field config values given in class are reflected correctly 
1. Launch the app with default values 
2. Go to Me -> App settings -> Debug Settings 
3. Verify that the default value is shown for the remote field 
4. Verify that the source under the Remote field is BUILD CONFIG

### 👀  Make sure that remote config values are fetched and Updated on App Refresh 
1. Launch the app with default values 
2. Update the value of any remote field on the BE 
3. Go to Me -> App settings -> Debug Settings 
4. Verify that the value provided at the BE is shown for the remote field 
5. Verify that the source under the Remote field is REMOTE 

## Merge Instructions
- [x] Make sure the Dependant FluxC PR is merged 
- [x] Update the FluxC PR hash version on the build.gradle 
- [x] Wait for CI to complete 
- [x] Remote Not ready for Merge label 
- [ ] Merge as normal 

## Regression Notes
1. Potential unintended areas of impact
- Remote config values are not fetched properly 
- Regression issues in Feature flag implementation 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual testing 
- Unit tests for components 

3. What automated tests I added (or what prevented me from doing so)
- Unit tests for components 

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@AjeshRPai - I'm getting an exception right after login that is preventing me from doing any testing. I updated both branch with trunk locally, but still have the same failure. 

Steps
- Install app
- Login: Enter username
- Login: Enter password & tap log in
- Crash [logcat-dec-13.txt](https://github.com/wordpress-mobile/WordPress-Android/files/10219714/logcat-dec-13.txt)

**Comment by AjeshRPai** [comment]
Hey @zwarm 

I have 
- updated the fluxC PR with the latest changes from the `fluxC trunk `
- updated the fluxC hash version on this PR
- fixed test failures 
- updated this PR with the `trunk` branch

I also checked for the crash on the app, but I couldn't reproduce it.  Please see below the video capture of me trying to reproduce the crash. Let me know if the crash is still happening. 

https://user-images.githubusercontent.com/17463767/207624174-532a673c-cfab-455e-8d7e-2d35bc168e62.mp4

I also tried to reproduce this crash by installing apk from the trunk first and then installing apk from this branch to see if this had anything to do with the database version change or anything. But couldn't reproduce the crash.

**Review by zwarm — CHANGES_REQUESTED** [review]
@AjeshRPai 
The tracking fails on remote config keys because they contain dashes `-` and not underscores `_`. We need to replace the `-` with `_` before sending **configValues** to the tracker here:
`AnalyticsTracker.track(
                    Stat.FEATURE_FLAGS_SYNCED_STATE,
                    configValues`

Error message: `Cannot add the property: feature-flags-enabled to the event. Property name must match: ^[a-z_][a-z0-9_]*$`

I can see in the BE someone explicitly used `feature-flags-enabled`.

**Comment by AjeshRPai** [comment]
Hey @zwarm , 

The tracking of `AnalyticsTracker.track( Stat.FEATURE_FLAGS_SYNCED_STATE, configValues)` is failing with the message 

`Cannot add the property: feature-flags-enabled to the event. Property name must match: ^[a-z_][a-z0-9_]*$`. 

I can see the response from the BE contains the remote feature flag `feature-flags-enabled=false`, but I don't think it's being used anywhere in Android, as I don't see any class corresponding to it. Have asked for whether the flag is necessary/can be removed in slack p1671186897733629-slack-C03T04HETR8

**Comment by zwarm** [comment]
> Have asked for whether the flag is necessary/can be removed in slack p1671186897733629-slack-C03T04HETR8

Nice, I also suggested that we add a test to not allow dashes in the field name. I suspect I may be updating this. :)

**Comment by AjeshRPai** [comment]
@zwarm 👋🏼 

The remote config parameters for the blog post URLs also have to be changed from 
```
{
    "jp-deadline":
    "phase-two-blog-post": 
    "phase-three-blog-post": 
    "phase-four-blog-post": 
    "phase-new-users-blog-post": 
    "phase-self-hosted-blog-post": 
}
```
to 
```
{
    "jp_deadline": 
    "phase_two_blog_post":
    "phase_three_blog_post": 
    "phase_four_blog_post": 
    "phase_new_users_blog_post": 
    "phase_self_hosted_blog_post": 
}
```

I have brought it to attention in the project channel(slack reference p1671444151901629-slack-C04564QS0V7) so that IOS can also adopt the same pattern, once the changes are deployed in BE. I will make the necessary changes. Untill then am adding the label - [Not ready for review]

**Review by zwarm — APPROVED** [review]
Nice work @AjeshRPai . I was able to retest with the new BE values. Looks like a conflict needs to be resolved, so I will leave it up to you for merging this PR and the FluxC PR. 🙇

**Comment by AjeshRPai** [comment]
Hey @zwarm 

I have updated the build.gradle with the fluxC version([commit](https://github.com/wordpress-mobile/WordPress-Android/pull/17667/commits/f976b2beac388daf5c1f0285502920705e6834af), [fluxCVersion](https://buildkite.com/automattic/wordpress-fluxc-android/builds/2012#01852e81-0c7d-485e-9625-ac761c4ac061/188-310)) and resolved the conflicts. 

Enabling auto-merge.

**Comment by AjeshRPai** [comment]
Hey @zwarm 

Since the '-' is replaced with the '_' on the remote config endpoint,  I am making the necessary changes to the remote fields. ~~Once that change is done, please have a look at this PR again~~.  I have updated the remote field to use _ instead of - in the [a6d6d0b](https://github.com/wordpress-mobile/WordPress-Android/pull/17667/commits/a6d6d0b2119165b8a338cb49a002fd54db23a68e)


To verify that the remote field config works as intended, 
Change any value in the BE for any field from `JetpackFeatureRemovalRemoteFields.kt` and verify that the exact value is reflected on the debug settings. Once that's successful, we can merge this PR.

**Comment by zwarm** [comment]
@AjeshRPai - All looks good. I retested using your instructions "to verify that the remote field config works as intended". We are ready to ship!

**Pull request merged**
