### PR TITLE
Issue/10643 material plugins

### LINKED ISSUE #10643: Implement Material theme on Plugin List and Details screens
We should switch widgets used at Plugin List and Details screens to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10643

This PR moves Plugin Browser and details screens to Material Theme and adds Dark Theme support. There are some code changes for cosmetic reasons.

While refactoring is not in the scope of this PR, since I touched those files, I cleaned up/optimized some of the redundant code as suggested by AS, so do not be alarmed by the size of the PR. I suggest turning on the "Hide whitespace changes" option during the review.

There is a huge amount of PRs in this feature that covers all the screens within the app, so I'm requesting reviews from a wide variety of people.

comparison_plugins

To test:
- Navigate to Plugin Browser and Details screen and confirm it's visual and functional integrity in both Light and Dark themes. The theme can be changed from App Settings.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mattmiklic** [comment]
One other note about type -- the plugin names on the main Plugins screen have increased in the new theme. I believe they were originally designed to use the Caption text style (12pt). Can you check that?

**Comment by khaykov** [comment]
After discussing with @mattmiklic , I went ahead and changed the look of the plugin browser a bit.

comparison_plugin

**Comment by jkmassel** [comment]
I'm moving this PR to 14.1 since we're code freezing today.

**Comment by khaykov** [comment]
Thanks for the review, @malinajirka ! Selectors look fine to me - we are using default `?android:selectableItemBackground`, so it's possible to override all of them at once if we fell like it :)

**Pull request merged**
