### PR TITLE
Issue/6669 media viewpager

### PR DESCRIPTION
**Pull request by nbradbury**
This is the first of two PRs related to #6669. This one adds the ability to swipe through media when previewed from the new media settings screen. The next PR will add the ability to swipe the media settings screen itself.

Note: This PR isn't as large as it may appear - the new `MediaPreviewFragment` contains a lot of code that previously existed in `MediaPreviewActivity`.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Not sure if this was on purpose or not, but when I swipe through media and then click on the `<-` icon, the app takes me back to the media details of the first tapped picture in the grid.

Have we consider to open the details of the current media on the screen? 
It could make sense in a workflow like the following: Swipe through media, find the one I want to delete or modify and do that action. In this case I need to go back and manually find the picture in the grid.

**Comment by nbradbury** [comment]
> Not sure if this was on purpose or not, but when I swipe through media and then click on the <- icon, the app takes me back to the media details of the first tapped picture in the grid.

I wondered the same thing but wasn't sure it made sense to do that until the detail is also swipe-able. I can go ahead and add that now, though, rather than wait for detail swiping - your call.

**Comment by daniloercoli** [comment]
My feelings are that we should add it to this PR.

**Comment by nbradbury** [comment]
> My feelings are that we should add it to this PR.

OK, added in 1b030d5.

**Comment by daniloercoli** [comment]
It works fine @nbradbury 👏  
Although I found a small issue with the closing animation/transition. It seems that MediaLibrary activity keeps a reference to the tapped item on the grid, and the closing transition uses that item position to animate out. See the video https://cloudup.com/cd0FNT6WBio
Not sure if there is an easy fix for it.

**Comment by nbradbury** [comment]
> It seems that MediaLibrary activity keeps a reference to the tapped item on the grid, and the closing transition uses that item position to animate out.

Oh, good catch! I added a somewhat hacky solution in d7a6fd8. I wish it wasn't hacky, but I couldn't find any other solution.

**Comment by daniloercoli** [comment]
> Oh, good catch! I added a somewhat hacky solution in d7a6fd8. I wish it wasn't hacky, but I couldn't find any other solution.


I just noticed that even if you see a single picture details the closing transition is different if you tap back or tap on the `x` icon top-left of the screen.

If you tap the back button, the `onBackPressed->finish` methods are called, and the transition is a slideout one. Regardless of `mOverrideClosingTransition`.
If you tap `x` and `mOverrideClosingTransition` is false (I.E. you've just seen a single picture) the transition is the coolest one since `supportFinishAfterTransition();` is called. Hope I explained it clearly.

Something like the following should fix the issue:
```
    @Override
    public void onBackPressed() {
        saveChanges();
        // call finish() rather than super.onBackPressed() to enable skipping shared element transition
        if (mOverrideClosingTransition) {
            finish();
        } else {
            supportFinishAfterTransition();
        }
    }
```
and you can probably also change
```
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            onBackPressed();
            return true;

```

**Comment by nbradbury** [comment]
> I just noticed that even if you see a single picture details the closing transition is different if you tap back or tap on the x icon top-left of the screen.

Another good catch - I used your code to fix that in 6e4b6bb.

**Comment by daniloercoli** [comment]
Nice work @nbradbury! LGTM

**Pull request merged**
