### PR TITLE
Fix SAVE action in the editor on local drafts

### LINKED ISSUE #9966: Editor - Publish confirmation dialog shown on Save action
### Expected behavior
When I edit a local draft (a draft created while offline) and I click on SAVE action the draft is uploaded to the server.

### Actual behavior
When I edit a local draft (a draft created while offline) and I click on SAVE action a "Ready to publish? Keep editing / Publish now" dialog is shown. If I click on "publish now" action on the dialog the post gets actually published.

### Steps to reproduce the behavior

1. turn airplane mode ON
2. start a draft, give it a title, some content
3. exit the editor and observe it's saved as Local Drafts
4. open it again
5. edit the title or content
6. tap on SAVE (navigation bar)
7. observe the "Ready to publish? Keep editing / Publish immediately" dialog is shown

##### Tested on [device], Android [version], WPAndroid [version]
Emulator Android 9

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9966

Updates the logic when the PublishConfirmationDialog is shown so it corresponds with the following line https://github.com/wordpress-mobile/WordPress-Android/blob/9e3f6b03a5a4e57e2728cd120ec8ac022016034e/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L874

I've copied a few test scenarios from https://github.com/wordpress-mobile/WordPress-Android/pull/9661
To test:
TEST A
1. turn airplane mode ON
2. start a draft, give it a title, some content
3. exit the editor and observe it's saved as Local Drafts
4. open it again
5. edit the title or content
6. tap on SAVE (navigation bar)
7. Notice the "Ready to publish? Keep editing / Publish immediately" dialog is NOT shown
-----------------
TEST B
1. start a draft post, enter some title and body
2. tap on the overflow menu icon and tap `Settings` 
3. set the status to `Pending review`
4. tap back twice (once to go back to editing, another one to exit the editor)
5. observe the Post gets saved and reflects on the Posts list as `Pending review`
6. open it again
7. open the menu and tap on `Publish Now`
8. accept the confirmation dialog
9. observe the Post gets published.
-----------------
TEST C
1. start a draft post, enter some title and body
2. tap PUBLISH on the action bar
3. accept the confirmation dialog
4. observe the Post gets published.
-----------------
TEST D
1. start a draft post, enter some title and body
2. exit the editor so it gets saved as a Draft
3. open it again
4. tap on the overflow menu icon and tap `Publish Now`
5. accept the confirmation dialog
6. observe the Post gets published.
-----------------
TEST E
1. tap on an existing, scheduled Post in the Post list to open it
2. open the overflow menu and tap `Publish Now`
3. accept the confirmation dialog
4. observe the post actually gets published (post list updated, post is published on the web, etc.)
-----------------
TEST F
1. tap on an existing, scheduled Post in the Post list to open it
2. tap on SCHEDULE (main action button on the navigation bar)
3. it should just update the Post on the server (as nothing changed, it'll remain scheduled as it already was)
-----------------
TEST G
1. start a new draft
2. enter something in title and body
3. tap on the menu icon and tap on Settings
4. change the post status from Draft to Published
5. go back to editing
6. now open the overflow menu again
7. tap `Save as draft`
8. observe a snackbar is shown "Your post is uploading", toast is shown "Post converted back to draft" and it effectively gets uploaded as a Draft.~

-----------------
TEST H - I've filled an issue for this scenario https://github.com/wordpress-mobile/WordPress-Android/issues/10021 as it doesn't work. But I believe it's not related to this PR.
1. start a draft, enter title and text
2. post settings -> change status from `Draft` to  `Publish`
3. exit the editor
4. observe it's been saved as a Local Draft (that's fine)
5. ok so, open it again
6. tap on PUBLISH
7. observe the Post gets uploaded and published

Update release notes:

- The changes are too minor

### CODE REVIEW

**Comment by maxme** [comment]
The fix LGTM, but I wonder if we should change these 2 tests, to use `PostUtil.isFirstTimePublish` instead of `isNewPost`, seems more natural to me to offer the same option for a new post or local draft.

**Comment by malinajirka** [comment]
`PostUtils.isFirstTimePublish()` returns `true` even for remote-drafts. 
[This](https://github.com/wordpress-mobile/WordPress-Android/blob/9e3f6b03a5a4e57e2728cd120ec8ac022016034e/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L874) would be always `true`. 
[This](https://github.com/wordpress-mobile/WordPress-Android/blob/9e3f6b03a5a4e57e2728cd120ec8ac022016034e/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1505) would technically become `userCanPublishPosts() && status == PostStatus.DRAFT` which I think isn't something we want.

Did you perhaps mean `EditPostActivity.isFirstTimePublish()` ?

**Comment by maxme** [comment]
> PostUtils.isFirstTimePublish() returns true even for remote-drafts.

Yes that's right and that's not what I wanted. 

I'm actually confused about the presence of `isNewPost()` in this test:
https://github.com/wordpress-mobile/WordPress-Android/blob/9e3f6b03a5a4e57e2728cd120ec8ac022016034e/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L874

I'm not sure why we want to differentiate the main action when starting a fresh post or when opening a local draft.

>  `EditPostActivity.isFirstTimePublish()` ?

🙈 no

**Comment by maxme** [comment]
Note: I think this works here: https://github.com/wordpress-mobile/WordPress-Android/blob/9e3f6b03a5a4e57e2728cd120ec8ac022016034e/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L900-L902

Because when `isNewPost` is true,  `isLocalDraft` is always true

**Comment by maxme** [comment]
I'm merging that one since it's not a debate about the post states. It's simply fixing an issue with the save button.

**Pull request merged**
