### PR TITLE
Fix subscribers chart issues

### LINKED ISSUE #20864: IndexOutOfBoundsException: Index 1 out of bounds for length 1
Sentry Issue: [JETPACK-ANDROID-RZS](https://a8c.sentry.io/issues/5369085344/?referrer=github_integration)

```
IndexOutOfBoundsException: Index 1 out of bounds for length 1
    at org.wordpress.android.ui.stats.refresh.utils.SubscribersChartLabelFormatter.getAxisLabel(SubscribersChartLabelFormatter.kt:14)
    entries[index].label
...
(95 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by irfano**
This PR

|before|after|description|
|-|-|-|
|||adds title to the Subscribers chart card in loading state|
|||handles empty state of Followers card (https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3005). Since all cards in error state now, the screen displays Retry button|
|||Renames the chart card's title to "Subscriber Growth"|
|||Add singular-plural "subscribers" label support to the marker view of the subscribers chart.|

-----

## To Test:

1. Log in.
2. Set the airplane mode on your device.
3. Open SUBSCRIBERS from "My Site → Stats".
4. Verify that the Retry button id displayed instead of displaying "No data yet" message on the Subscribers card.
5. Turn off airplane mode. 
6. Verify that the Subscribers chart card has a title in the loading state.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - Not an important case for automated tests.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by notandyvee** [comment]
Code LGTM and everything works great. But one thing I noticed. Two cards have the same title, which is less than ideal. I recommend making it clearer. "Subscribers Chart", "Subscribers List", Etc. Since we are here.

subscribers-dupe

cc @staskus . This could be the same in iOS. Syncing between the two would be helpful. Or we can decide to ignore it. Up to y'all.

**Comment by aditi-bhatia** [comment]
^ I agree with @notandyvee 's feedback, I thought it was strange at first that both cards have the same title - but then noticed that's how it was in the final designs as well. 

In the earlier proposed designs (IqhXWz3Iir7RMb5XH5gGfZ-fi-108_4611), the name of that card was `Subscriber Growth`: 

Screenshot 2024-05-07 at 4 10 21 PM

Maybe we could change it to that, any thoughts?

**Comment by staskus** [comment]
Thanks, @aditi-bhatia and @notandyvee, great observation. I think calling it `Subscriber Growth` would be appropriate 👍 I'll update it on iOS as well. cc @irfano

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/284">24.9 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
I also updated the title to the "Subscriber Growth" in this PR.

**Review by aditi-bhatia — COMMENTED** [review]
Changes look good to me and work as expected 👍 I left a small clarifying comment on the Flux-C PR related to this to get a better understanding before I approve: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3005#pullrequestreview-2047275967

**Comment by aditi-bhatia** [comment]
Hi @irfano, I spent some time testing again today and there's a crash that I'm seeing from `SubscribersChartLabelFormatter.kt`. I'm only able to reproduce on one device with airplane mode on + I'm only seeing when testing with a blog with 0 subscribers (I've been using `buddyuniversity.wordpress.com` for this) :

Screenshot 2024-05-10 at 3 27 25 AM


I haven't debugged it too much yet (I can help with this tomorrow) but this is the value after setting a breakpoint:

Screenshot 2024-05-10 at 3 54 09 AM

**Comment by irfano** [comment]
I couldn't reproduce your crash, but I did fix another issue related to 0 subscribers case. It was crashing when tapping the line on sites with 0 subscribers. This might be related to the crash you're experiencing. I would appreciate it if you could find a way to reproduce it.

**Comment by aditi-bhatia** [comment]
Hi @irfano, I can't seem to reproduce the crash I mentioned above which would occur after clicking on `My Site -> Stats` on airplane mode on a blog with 0 subscribers. Now, I'm seeing a different crash after clicking the chart: 

Screenshot 2024-05-10 at 6 12 28 PM

To reproduce: 
- Load `Stats` with data on on a blog with 0 subscribers
- Turn off data and access Stats -> Subscribers again
- Click the blue line on the Subscribers Growth Chart

**Comment by irfano** [comment]
That's the crash I mentioned and fixed with my latest commit (9c581d37d962ca5f5435e809f0fec6e1d9a997cc). Can you ensure that you pulled the latest commit?

**Review by aditi-bhatia — APPROVED** [review]
I used a fresh install last time but maybe something went wrong with the versioning since I'm not able to reproduce the crash today. Tested using a fresh install on two devices, lgtm 👍

**Comment by irfano** [comment]
@oguzkocer, sorry for the delay in making this ready before the code freeze. We should have let you know earlier. Can we include this in `release/24.9`?

**Comment by oguzkocer** [comment]
@irfano Sure - but you'll need to wait a couple days for the beta as I just submitted it.

**Comment by irfano** [comment]
Thank you! 
> but you'll need to wait a couple days

That's fine! This fixes required but minor issues. So, it won't disrupt the testing process until the next beta is released.

**Review by antonis — APPROVED** [review]
Thank you for including a fix for https://github.com/wordpress-mobile/WordPress-Android/issues/20864 in your PR @irfano 🙇 
The code changes in https://github.com/wordpress-mobile/WordPress-Android/pull/20776/commits/e31a090ff9f88cbdc3bb6f8f55ecdda86437c342 look good and the app works as expected 🎉

**Pull request merged**
