### PR TITLE
Release/aztec 7.7 freeze

### PR DESCRIPTION
**Pull request by 0nko**
Aztec code-freeze changes for version 7.7.

### CODE REVIEW

**Comment by maxme** [comment]
I guess that's work in progress, should we have the toolbar deployed on wide screens?

screenshot-2017-06-20_18 20 35 604

**Comment by 0nko** [comment]
That's fine for this release, but thanks for pointing it out. We'll try to tweak it. 

Maybe we could just disable the advanced toolbar for the wide screen, what do you think @theck13?

**Comment by theck13** [comment]
That UI is working as intended for various screen sizes.  The toolbar will expand and stay expanded regardless of orientation change by tapping the expand button (i.e. horizontal ellipsis icon) so the user can choose to expand or collapse it to fit their needs.  If discoverability is the concern, we could add a tool tip focusing on the expand button.

**Comment by 0nko** [comment]
But couldn't we expand it automatically if the screen is wide enough by adding `aztec:advanced='false'` in `layout-w600dp` (or some other width that makes sense)?

**Comment by theck13** [comment]
That's definitely possible, but it might cause a weird experience if the device is rotated from portait with less than 600dp width to landscape with over 600dp width since the toolbar will change.  That might be worth user testing, @iamthomasbishop.

**Comment by catehstn** [comment]
Interested to see what @iamthomasbishop says but I think autoexpanding on rotation to widescreen and auto compressing to vertical is normal and not unexpected. I think most people probably keep their device in one rotation whilst writing - especially for tablets which are often attached to a keyboard.

**Comment by iamthomasbishop** [comment]
My thought is that even at wider views, the user is choosing between a simple ('basic') toolbar and advanced ('expanded') toolbar, so regardless of screen size we should show the basic by default. I'm open to changing it if user testing dictates we should, but that is the initial idea.

**Pull request merged**
