### PR TITLE
Fix configuration for Connected Tests and Screenshots

### PR DESCRIPTION
**Pull request by loremattei**
This PR attempts a fix for an issue where some tasks run out of memory:

- it updates the memory configuration to leave more free memory to spawned tasks.
- it splits some critical jobs in smaller parts.

To test:
- Make sure CI is green

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Note that it looks like Connected Tests are failing right now in develop, likely because PRs have been merged, but verifying them was difficult because the Connected Tests-2 job failed during the build. 

This PR doesn't fix the test failure itself, but it fixes the build step so that the other failures can be investigated. 

When reviewing it, please make sure the build step is successful for the Connected Test-2 job.

**Review by mzorz — APPROVED** [review]
Since the errors seen were about memory issues, hope these parameters changes augmenting run memory work alright!
Will merge once all is green
LGTM :shipit:

**Comment by renanferrari** [comment]
Just a heads up that we might still see an error here, probably related to the fix in #13373. Considering that PR needs the changes introduced here to make the CI job run successfully, I'd probably just go ahead and merge this anyway.

**Comment by mzorz** [comment]
Sounds good @renanferrari ! Let's merge this one and then I'll update #13373 with `develop` right after 👍

**Pull request merged**
