### PR TITLE
Address NPEs on NotificationsListFragmentPage

### LINKED ISSUE #12227: Several NPEs in NotificationsListFragmentPage
I combined several NPE crashes in the `NotificationsListFragmentPage` into a single issue. None of these issues are happening very frequently, but they are all probably easy to fix and we can fix them all in one go.

**Sentry Url**: https://sentry.io/share/issue/0a7bb29dcc6e476a9c6b52fbc65d3e9c/
**User Count**: 1
**Count**: 3
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-16T16:53:51.297000Z
**Last Seen**: 2020-06-17T16:10:06Z
**24 Hours**: 0
**30 Days**: 3

```
IllegalStateException: actionable_empty_view must not be null
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.hideEmptyView(NotificationsListFragmentPage.kt:235)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:140)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
     at android.os.Handler.dispatchMessage(Handler.java:107)
...
(5 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/11e8fd49add5405796fc301c818b216a/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T21:38:46.945000Z
**Last Seen**: 2020-06-18T21:38:46Z
**24 Hours**: 1
**30 Days**: 1

```
IllegalStateException: actionable_empty_view must not be null
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyView(NotificationsListFragmentPage.kt:283)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyViewForCurrentFilter(NotificationsListFragmentPage.kt:331)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:142)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
...
(6 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/0086b32a5d8f4eca85ce612aa4b9003a/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T09:51:32.375000Z
**Last Seen**: 2020-06-18T09:51:32Z
**24 Hours**: 1
**30 Days**: 1

```
KotlinNullPointerException: 
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$onEventMainThread$1.onResponse(NotificationsListFragmentPage.kt:394)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$onEventMainThread$1.onResponse(NotificationsListFragmentPage.kt:387)
     at org.wordpress.android.ui.notifications.utils.NotificationsActions$5.onResponse(NotificationsActions.java:108)
     at org.wordpress.android.ui.notifications.utils.NotificationsActions$5.onResponse(NotificationsActions.java:87)
     at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
     at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
     at android.os.Handler.handleCallback(Handler.java:874)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:198)
...
(4 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/a38306ca83c247ec98009f3f7d6745bf/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T05:03:11.110000Z
**Last Seen**: 2020-06-18T05:03:11Z
**24 Hours**: 1
**30 Days**: 1

```
NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.addOnScrollListener(androidx.recyclerview.widget.RecyclerView$OnScrollListener)' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$showNewUnseenNotificationsUI$1.run(NotificationsListFragmentPage.kt:357)
     at android.os.Handler.handleCallback(Handler.java:874)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:198)
     at android.app.ActivityThread.main(ActivityThread.java:6729)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Sentry Url**: https://sentry.io/share/issue/66c700157cb245549ebefa4dab8d0e9b/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T05:02:56.472000Z
**Last Seen**: 2020-06-18T05:02:56Z
**24 Hours**: 1
**30 Days**: 1

```
NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView org.wordpress.android.ui.ActionableEmptyView.getImage()' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyViewForCurrentFilter(NotificationsListFragmentPage.kt:339)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:142)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
     at android.os.Handler.dispatchMessage(Handler.java:107)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #12227 

~~This PR adds safe calls **?.** to synthetic properties to prevent NPE on null views.~~
After a conversation with @malinajirka , I have removed the safe call operator and added a `.cancel()` on the asynctask to help eliminate memory leaks that could cause the views to be null. 

To test:
These NPE's are very intermittent and I haven't been able to reproduce any of these NPEs. For testing, please ensure that the Notifications list is functioning correctly. I did try adding a `Thread.currentThread().sleep(5000)` in the doInBackground of the asyncTask, but still could not get the NPE to throw.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @zwarm! I'm a bit worried this approach will just hide existing bugs in the code. If we want to release a quick fix into 15.1 or 15.2, I'm completely fine with this approach. However, I'm not sure how I feel about keeping this code in our codebase forever. 
Views in fragment should be accessible when we are trying to work with them. If they are not, we have a bug in the code which is accessing the views. I've quickly scanned through all the stacktraces in the parent issue and it seems all of them have one thing in common: they are all executed asynchronously (`onPostExecute`, `onResponse`, `run `). In other words, imo they are all memory leaks.
Wdyt?

**Comment by zwarm** [comment]
> In other words, imo they are all memory leaks.

Thanks @malinajirka  That was my first instinct, so I included LeakCanary and ran through a few scenarios, but no leaks were detected. Let me take a deeper look at the LC logcat lines - maybe there is something buried in there that will help point to the culprit.

**Comment by malinajirka** [comment]
Thanks @zwarm! I've managed to reproduce the crash and it seems the crash is thrown under certain conditions even after the fix.

How to reproduce the crash
1. Checkout `malinjir-test-notifications-tab-crash`
2. Start the app
3. Select "MySite"
4. Select "Notifications"
5. Select "MySite"
6. Select "Notifications"
7. Select "My Site"
8. Wait until the app crashes

Tested with stock emulator Pixel 2, API 27.

It seems `reloadNotesFromDBAsync()` gets invoked twice and we override `mReloadNotesFromDBTask` with a new task, but no-one ever cancels the previous task. I think we should either cancel it or perhaps ignore the new request for `reloadNotesFromDBAsync()` when a task is already running. Wdyt?

----------------------------
It seems this PR is trying to fix the first two and the last crashes mentioned in the issue:
https://sentry.io/share/issue/0a7bb29dcc6e476a9c6b52fbc65d3e9c/
https://sentry.io/share/issue/11e8fd49add5405796fc301c818b216a/
https://sentry.io/share/issue/66c700157cb245549ebefa4dab8d0e9b/

This https://sentry.io/share/issue/0086b32a5d8f4eca85ce612aa4b9003a/ issue is caused by a different leak from [here](https://github.com/wordpress-mobile/WordPress-Android/blob/5457afd85c587947e00999fb05061a84a73f7169/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L385). We send a request to the server and we wait for the response. I don't think we support request cancellation. I think we have a couple of options here
- replace "notesAdapter!!.replaceNote(note)" with "notesAdapter?.replaceNote(note)". This wouldn't fix the leak, but would fix the crash.
- Move content of `onEventMainThread(event: NoteLikeOrModerationStatusChanged)` into a separate class (or static nested class) with a weakreference to the adapter. This would fix the leak and also fix the crash.


This https://sentry.io/share/issue/a38306ca83c247ec98009f3f7d6745bf/ issue is caused by a leak from [this](https://github.com/wordpress-mobile/WordPress-Android/blob/5457afd85c587947e00999fb05061a84a73f7169/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L355) `postDelayed` call. I guess we could add `notifications_list.removeCallbacks(...)` into the "onDestroyView", wdyt?

Let me know what you think. Btw we talked about merging the ".?" fix into 15.1 or 15.2.. Did you change your mind and decided to implement only the proper fix into 15.3?

**Comment by zwarm** [comment]
Thanks @malinajirka for getting the crash.  I'll check out your branch shortly and take it for a spin.  Ahh, you had a thread sleep. Never mind then.

> It seems `reloadNotesFromDBAsync()` gets invoked twice and we override `mReloadNotesFromDBTask` with a new task, but no-one ever cancels the previous task. I think we should either cancel it or perhaps ignore the new request for `reloadNotesFromDBAsync()` when a task is already running. Wdyt?

Yes, I had sworn I had a check in there for canceling before kicking it off, but it looks like I inadvertently deleted the line ( I checked local history for sanity) I've added it back.

> Move content of `onEventMainThread(event: NoteLikeOrModerationStatusChanged)` into a separate class (or static nested class) with a weakreference to the adapter. This would fix the leak and also fix the crash.

This would be my preferred choice. I would expect changes may be needed to any event handler that changes the list. I will research those and make modifications as needed.

> This https://sentry.io/share/issue/a38306ca83c247ec98009f3f7d6745bf/ issue is caused by a leak from [this](https://github.com/wordpress-mobile/WordPress-Android/blob/5457afd85c587947e00999fb05061a84a73f7169/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L355) `postDelayed` call. I guess we could add `notifications_list.removeCallbacks(...)` into the "onDestroyView", wdyt?

I think that is a reasonable solution. 

> Did you change your mind and decided to implement only the proper fix into 15.3?

Yes, felt it was better to address it properly. :)

**Comment by zwarm** [comment]
> Move content of onEventMainThread(event: NoteLikeOrModerationStatusChanged) into a separate class (or static nested class) with a weakreference to the adapter. This would fix the leak and also fix the crash.

One more q @malinajirka . `NotificationsActions.downloadNoteAndUpdateDB` emits a `NotificationChanged` event which re-adds all the notes. Why are we updating the single note at all when the entire list gets replaced? Am I missing something? If this is the case, couldn't we just remove the single note update from `fun onEventMainThread(event: NoteLikeOrModerationStatusChanged)`?

**Comment by malinajirka** [comment]
Good question :)! I think you are right. Perhaps it was added because the "reload from db" is a bit slower. But I doubt it as it should be almost instant in 99,9% of cases. I think it's worth a try ;).

**Comment by zwarm** [comment]
> I think it's worth a try ;).

In commit 46d2dd8. Things appear to be working as expected. This last commit should close out the PR. Let me know what you think. Thanks

**Pull request merged**
