### PR TITLE
Issue/reader excerpt fix

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes two problems introduced by #7634:

1. The routine to determine whether to show an excerpt didn't consider whether there even **is** an excerpt
2. The `use_excerpt` value was being incorrectly read from the database

@malinajirka Would you mind reviewing this one, since you did the initial review?

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @nbradbury! I'm sorry I missed those in the previous PR.

It seems, that some properties of posts don't get updated.
1. Set "For each article in a feed, show" to "Full Text"
2. Create a post with an excerpt
3. Open the post in the Reader - full content of the post is displayed
4. Set "For each article in a feed, show" to "Summary"
5. Manually refresh the post in the app - notice that the app still displays full content of the post
Interesting is, that in the response from the server is "use_excerpt" set to true. 

I've noticed that the ReaderPost.isSamePost() considers two post with different values of the "use_excerpt" attribute to be the same, but even when I change the text of the post, the app keeps displaying full content of the post.

There are multiple entries with the same post id in the local database but some of them have use_excerpt = 1 and some of them use_excerpt = 0.

I've also noticed that we don't update "excerpt" and "use_excerpt" attributes
[here](https://github.com/wordpress-mobile/WordPress-Android/blob/b3b52efdda7990435a79f496d7b7d4cd76a5f551/WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java#L167) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b3b52efdda7990435a79f496d7b7d4cd76a5f551/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L274). Is this desired?

Thanks for looking into this!

**Comment by nbradbury** [comment]
> I've also noticed that we don't update "excerpt" and "use_excerpt" attributes
> here and here. Is this desired?

Good catch - I just fixed that in 377d677.

> Manually refresh the post in the app - notice that the app still displays full content of the post
Interesting is, that in the response from the server is "use_excerpt" set to true.

I see what you mean. I believe the problem is because we don't refresh the rendered post [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b3b52efdda7990435a79f496d7b7d4cd76a5f551/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java#L665) when the post is updated. If it's okay with you, I'd rather address that in a separate issue.

**Comment by malinajirka** [comment]
Thanks for the changes @nbradbury! 

I'm sorry for nitpicking, but I'm wondering whether we shouldn't save the excerpt even [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b3b52efdda7990435a79f496d7b7d4cd76a5f551/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L274). As otherwise there might be several posts with different excerpts. WDYT?

**Comment by nbradbury** [comment]
> I'm sorry for nitpicking, but I'm wondering whether we shouldn't save the excerpt even here...

Not nit-picky at all - that's a good call. Added in dabd190.

**Comment by malinajirka** [comment]
Thank you!!! Looks good;)

**Pull request merged**
