### PR TITLE
Fix NPE in Site Settings

### LINKED ISSUE #20840: NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.bloggingreminders.BloggingReminde...
Sentry Issue: [JETPACK-ANDROID-83A](https://a8c.sentry.io/issues/4265444988/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.bloggingreminders.BloggingRemindersViewModel.onBlogSettingsItemClicked(int)' on a null object reference
    at org.wordpress.android.ui.prefs.SiteSettingsFragment.setupBloggingRemindersBottomSheet(SiteSettingsFragment.java:1307)
    mBloggingRemindersViewModel.onBlogSettingsItemClicked(mSite.getId());
    at org.wordpress.android.ui.prefs.SiteSettingsFragment.onPreferenceTreeClick(SiteSettingsFragment.java:585)
    setupBloggingRemindersBottomSheet();
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aditi-bhatia**
Fixes #20840

This PR fixes a crash in `SiteSettingsFragment` where `mBloggingRemindersViewModel.onBlogSettingsItemClicked()` is called on a null object.

-----

## To Test:
I haven't been able to reproduce this crash, so code review + smoke test `My Site -> Site Settings -> Blogging -> Reminders`. 

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

3. What I did to test those areas of impact (or what existing automated tests I relied on)

    - None

4. What automated tests I added (or what prevented me from doing so)

    - None
-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
`site` is already being checked in `onCreate` and the activity is finished if the site is null. 

The crash message is `Attempt to invoke virtual method 'void org.wordpress.android.ui.bloggingreminders.BloggingRemindersViewModel.onBlogSettingsItemClicked(int)' on a null object reference`. From the logs, I understand that the null object is `BloggingRemindersViewModel`, not site. Can you confirm?

**Comment by aditi-bhatia** [comment]
Hi @irfano thanks for taking a look 👍 

> site is already being checked in onCreate and the activity is finished if the site is null.

From what I understand, `mSite` can become null after `onCreate` is called (deletion or removal of a site) which is why a few other functions in this class are also doing a null check. I personally feel that it's safer to have than not, but open to discussion. 

> From the logs, I understand that the null object is BloggingRemindersViewModel, not site.

Good point, thank you for catching that! I've added a null check for `BloggingRemindersViewModel` as well to address the case where it isn't initialized. What do you think?

**Review by irfano — APPROVED** [review]
> I personally feel that it's safer to have than not

I agree!
LGTM! 👍🏻 I'm not merging since you may want to add this fix to RELEASE-NOTES.

**Comment by aditi-bhatia** [comment]
Thanks @irfano, I updated the release notes 👍  For future reference, how do we decide which bug/crash fixes to include there? I noticed a few other crash fixes didn't update this file.

**Comment by irfano** [comment]
> For future reference, how do we decide which bug/crash fixes to include there?

I usually add every change that affects users to release notes, but if it's a minor change, with * indicator. More detail: 
- pbMoDN-o4-p2
- pdcxQM-Km-p2

**Comment by aditi-bhatia** [comment]
Awesome, thank for you sharing!

**Pull request merged**
