### PR TITLE
Adds: overlay for new users and self hosted users

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #

Part of #17338  and #17680 

### 📓  Description 
This PR adds the Overlay for Self-hosted and New users in the corresponding Jetpack removal phases. The overlay will be shown when clicking the Jetpack feature card on the menu page. It will also be shown the first time user opens the app or logs in after the phase is activated. 

### ⭐  Major commits 
1. [Updates: Jetpack overlay landscape with new users content](https://github.com/wordpress-mobile/WordPress-Android/pull/17838/commits/31a640c635b1bf039925748cd6d657b0256e30e3)
2. [Updates: the logic of showing the overlay for the first time in phase](https://github.com/wordpress-mobile/WordPress-Android/pull/17838/commits/34f96236dca951955fd2c2390d42bf1deecbcf89)
3. [Adds: a barrier to handle the Primary button position](https://github.com/wordpress-mobile/WordPress-Android/pull/17838/commits/5d38cf8f1aeaad6123c0349c7bdde52a26eb155e)

### 📹  Screenshot and Video capture 
| Overlay in New users Phase Portrait  | Overlay in New users Phase Landscape | Overlay in Self hosted Phase (light) | Overlay in Self hosted phase (dark) |
|---|---|---|---|
| screenshot_new_users_phase_light_|screenshot_landscape_new_users_| screenshot_self_hosted_app_open_ |screenshot_night_self_hosted_ |

Note: the new user's phase overlay is scrollable in landscape and portrait mode so that the buttons can be seen. Attempted to post a video capture showing the capability, but due to size limits, it was not possible to show it in the PR description 

#### 1. New users phase 
- Login to WP app with a wp com account 
- Go to me -> app settings -> debug settings
- enable `jp_removal_new_users`
- Restart the app 
- ✅ Verify the feature collection overlay is shown
- Swipe away the app and reopen
- ✅ Verify the feature collection overlay is not shown
- Open the app 
- Notice that a card with Jetpack removal details is shown at the **bottom of the menu** 
- ✅ Verify that clicking on the card shows the overlay 
- ✅ Verify that the Overlay content matches the Project spec 

#### 2. Self hosted users phase
- Login to WP app with a wp com account 
- Go to me -> app settings -> debug settings
- enable `jp_removal_self_hosted`
- ✅ Verify the feature collection overlay is shown
- Swipe away the app and reopen
- ✅ Verify the feature collection overlay is not shown
- Open the app 
- Notice that a card with Jetpack removal details is shown on the **top of the menu** 
-  ✅ Verify that clicking on the card shows the overlay 
-  ✅ Verify that the Overlay content matches the Project spec 

## Regression Notes
1. Potential unintended areas of impact
- Overlays shown on the previous phase is not displayed as per the project spec due to the introduction of barrier in the overlay xml
- New users phase overlay and Self hosted users overlay content is not correct as the project spec 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
still installing the build so I can check it live but based on the screenshots everything looks good. One small tweak. The three bullet points with green icons. Can you increase the space between the icons and the text from what looks like 8dp to 16dp? it looks a little tight right now.

**Review by zwarm — APPROVED** [review]
👋 @AjeshRPai 
I have tested both phases "New User" and "Self hosted user" and all looks good. I like the improvements to shouldShowFeatureCollectionJetpackOverlayForFirstTime. 👍 

I'll approve, ~but won't merge until @osullivanchris has had the opportunity to review the designs.~ 
Update: I won't merge until CI has passed


Thanks

**Comment by AjeshRPai** [comment]
Hey @osullivanchris 

>Can you increase the space between the icons and the text from what looks like 8dp to 16dp?

Done with the commit [0605b54](https://github.com/wordpress-mobile/WordPress-Android/pull/17838/commits/0605b54619327176dd4e264643ba0f5ce359f020)

**Comment by osullivanchris** [comment]
Thanks @AjeshRPai 👍 

I got the build working now on my device and it works as expected 👍  😄

**Pull request merged**
