### PR TITLE
Merge release/20.5 after 20.5-rc-2

### PR DESCRIPTION
**Pull request by AliSoftware**
Merging the release branch after doing a new beta.

The new beta includes:
 * https://github.com/wordpress-mobile/WordPress-Android/pull/17044
 * Last-minute tooling fix for the `create_gh_release` lane (067f630550436b694e12aa400b45a320f21f40f7), that I needed to finish publishing the beta
 * Latest `strings.xml` from GlotPress
 * Version bump in `version.properties`

### Conflicts Resolution

There were conflicts on many `Wordpress/src/jetpack/res/values-*/strings.xml` files.

Turns out it was on all the non-Mag16 locales, that got updated on `release/20.5` when I ran our beta scripts, but were deleted in `trunk` when I landed https://github.com/wordpress-mobile/WordPress-Android/pull/17041 yesterday to limit Jetpack to Mag16 only. So that conflict made sense.

Resolved by merging `trunk` into this `merge/20.5-rc-2` branch then keeping what was in `trunk` (85ef246081c104491c2ac02169f15e5d297352d3), to keep all those non-Mag16 `jetpack/res/values-*/strings.xml` files deleted after landing this PR into `trunk`.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
LGTM! 💯 

PS: I disabled `auto-merge` @AliSoftware  so that to give you a change to merge it yourself after my approval and you reading my `alpha` related comment below, just in case you might want to apply any further changes here.

> Last-minute tooling fix for the create_gh_release lane (https://github.com/wordpress-mobile/WordPress-Android/commit/067f630550436b694e12aa400b45a320f21f40f7), that I needed to finish publishing the beta

Thank for that!

FYI: I also looked at all occurrences of `alpha` on both, the `build.rb` and `release.rb` files, and found a few. I am not sure if we need them all, do we? 🤔

-----

> There were conflicts on many Wordpress/src/jetpack/res/values-*/strings.xml files.

👍 

> Turns out it was on all the non-Mag16 locales, that got updated on release/20.5 when I ran our beta scripts, but were deleted in trunk when I landed https://github.com/wordpress-mobile/WordPress-Android/pull/17041 yesterday to limit Jetpack to Mag16 only. So that conflict made sense.

👍 

> Resolved by merging trunk into this merge/20.5-rc-2 branch then keeping what was in trunk (https://github.com/wordpress-mobile/WordPress-Android/commit/85ef246081c104491c2ac02169f15e5d297352d3), to keep all those non-Mag16 jetpack/res/values-*/strings.xml files deleted after landing this PR into trunk.

👍

**Comment by AliSoftware** [comment]
@ParaskP7 👋  Thanks for the review!

Could you report what occurrences of `alpha` I might have missed in `build.rb` and `release.rb`? The only remaining ones I could find on my end are the ones below… but with your comment I'm now wondering if I might have missed more?

 - `build.rb:20` and `build.rb:52`: those are expected parameters (`alpha: false`) of the `android_build_prechecks` action, hence why I kept them.
    - After checking in the source of the release-toolkit, it seems that this parameter is optional and defaults to `false`… so indeed we could consider omitting it after all 🤔 
    - Still, I prefer to be explicit at call site to indicate that the prechecks should not check for the status of a potential alpha build (because we don't have those anymore)
 - `release.rb:263`: I see `/-rc-|alpha-/.match?(release_title)` in the regex which decides if a GitHub Release should be marked as prerelease or not.
    - I figured that, while it's not strictly needed if we don't generate releases named `alpha-*` anymore, and we could simplify the regex here, it wouldn't hurt keeping it, especially to make the lane more generic and resilient including for cases where we might generate ad-hoc and on-demand builds for special requests and would chose to name those `alpha-XXX` (regardless of the flavor with which we'd build them) to not conflict those rare on-demand builds with `-rc-` versions.
    - That being said, it's probably unlikely that we'll need to create many GitHub Releases named `alpha-*` in the future, even manually on demand… so we could indeed consider removing that from the RegEx to clean things up (but keeping it wouldn't hurt either)
    - Besides, I wanted to keep the changes here minimal, not only because those were targeting `release/*` branch and I try to limit the diff when targeting those branches to avoid introducing unexpected bugs by doing too much changes, but also because I made that change directly in `release/*` without using a PR to have it reviewed prior to landing this one.

Did you spot any other occurrences aside from those above that I might have missed?

And does that rationale work for you for the above ones? Or would you prefer I remove those in this current PR before merging it?

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> Could you report what occurrences of alpha I might have missed in build.rb and release.rb? The only remaining ones I could find on my end are the ones below… but with your comment I'm now wondering if I might have missed more?

👍 

> build.rb:20 and build.rb:52: those are expected parameters (alpha: false) of the android_build_prechecks action, hence why I kept them.
> - After checking in the source of the release-toolkit, it seems that this parameter is optional and defaults to false… so indeed we could consider omitting it after all 🤔
> - Still, I prefer to be explicit at call site to indicate that the prechecks should not check for the status of a potential alpha build (because we don't have those anymore)

Yeap, we could either omit those to make it explicit that WPAndroid is not utilizing alphas anymore (same for comments), or as you also correctly pointed out, if you want to be explicit at the call site, then we can keep them, even though they are never being `true`. 🤔

I'll let this decision up to you. My only argument in favor of removing those would be that it might be beneficial for us to not having any `alpha` occurrences in those `*.rb` or any `*.rb` file from now one, in order to avoid missing/breaking something, or missing an opportunity on improving on something else, just like it happened in this case (067f630550436b694e12aa400b45a320f21f40f7).

> release.rb:263: I see /-rc-|alpha-/.match?(release_title) in the regex which decides if a GitHub Release should be marked as prerelease or not.
> - I figured that, while it's not strictly needed if we don't generate releases named alpha-* anymore, and we could simplify the regex here, it wouldn't hurt keeping it, especially to make the lane more generic and resilient including for cases where we might generate ad-hoc and on-demand builds for special requests and would chose to name those alpha-XXX (regardless of the flavor with which we'd build them) to not conflict those rare on-demand builds with -rc- versions.
> - That being said, it's probably unlikely that we'll need to create many GitHub Releases named alpha-* in the future, even manually on demand… so we could indeed consider removing that from the RegEx to clean things up (but keeping it wouldn't hurt either)
> - Besides, I wanted to keep the changes here minimal, not only because those were targeting release/* branch and I try to limit the diff when targeting those branches to avoid introducing unexpected bugs by doing too much changes, but also because I made that change directly in release/* without using a PR to have it reviewed prior to landing this one.

Yes, I agree with all that you stated here, and if you consider to keep the changes here minimal, please ignore that regex. I also agree with this parenthesis of your `(but keeping it wouldn't hurt either)`, still I wanted to note that, and thus trigger a discussion on it, just in case you were thinking about removing that too (to clean things up).

Again, I am letting this decision up to you, and if you think it is better to keep it as is, at least for now, let's just do that.

> Did you spot any other occurrences aside from those above that I might have missed?

The only 2 other occurrences are on comments `build.rb:126` + `build.rb:134`. I am not sure if we need those, do we? 🤔 

> And does that rationale work for you for the above ones? Or would you prefer I remove those in this current PR before merging it?

Your rationale work for me perfectly and I trust you on any decision you will make from here afterwards! 💯

**Comment by AliSoftware** [comment]
Thanks for the reply

> The only 2 other occurrences are on comments build.rb:126 + build.rb:134. I am not sure if we need those, do we? 🤔

🤦 I did remove those… locally… but then forgot to ⌘S the file 🤦 🤦 . No wonder my ⌘F didn't find those (I already removed them) but you did (I didn't save and commit the changes) 😂 

 - I now saved and push those in 0457096eb51fb469fa3b60527cbe7c0774638753.
 - I also removed the `alpha` on the `prechecks` action parameters as well in 17db38cc156eb6cdc53ed094a5fda2d7d83624e4.
    - In fact, I also removed the other `beta/final` parameters that were `false` on those call sites, to only keep just the `beta: true` or `final: true` as appropriate for the call site context.
    - I've also added `unless options[:skip_prechecks]` on that call that was forgotten, and made the call-site be a one-liner, to be consistent with how we similarly already did it on `build_beta` lane on line 67 and have all those call sites styled the same.
 - I'll keep the regex for now tho, because it feels a bit more "dangerous" to make that kind of regex change on the rush, especially in a `release` branch.

@ParaskP7 Can you validate one last time to ensure I didn't make any silly mistake with those last changes (especially on 17db38cc156eb6cdc53ed094a5fda2d7d83624e4)? 🥺  Thanks!

**Comment by ParaskP7** [comment]
Thank you so much for the changes @AliSoftware ! ❤️ 

> 🤦 I did remove those… locally… but then forgot to ⌘S the file 🤦 🤦 . No wonder my ⌘F didn't find those (I already removed them) but you did (I didn't save and commit the changes) 😂

🤣 

> - I now saved and push those in https://github.com/wordpress-mobile/WordPress-Android/commit/0457096eb51fb469fa3b60527cbe7c0774638753.

Awesome! ✅ 

> - I also removed the alpha on the prechecks action parameters as well in https://github.com/wordpress-mobile/WordPress-Android/commit/17db38cc156eb6cdc53ed094a5fda2d7d83624e4.

✅ 

>     - In fact, I also removed the other beta/final parameters that were false on those call sites, to only keep just the beta: true or final: true as appropriate for the call site context.

Love it! ❤️ 

>     - I've also added unless options[:skip_prechecks] on that call that was forgotten, and made the call-site be a one-liner, to be consistent with how we similarly already did it on build_beta lane on line 67 and have all those call sites styled the same.

You even found something that was forgotten, that's the spirit! ❤️ 

> I'll keep the regex for now tho, because it feels a bit more "dangerous" to make that kind of regex change on the rush, especially in a release branch.

I agree! 👍 

> @ParaskP7 Can you validate one last time to ensure I didn't make any silly mistake with those last changes (especially on https://github.com/wordpress-mobile/WordPress-Android/commit/17db38cc156eb6cdc53ed094a5fda2d7d83624e4)? 🥺 Thanks!

Not that you needed my extra validation, but I did one last validation, once and twice, everything looks good, no more `alpha`s, you all hear me, champagne, champagne, champagne for everyone!!! 🍾 🍾 🍾

Let's merge this! 🚀

**Pull request merged**
