### PR TITLE
Feature/media image sizes

### LINKED ISSUE #5878: Media Library - Improve pictures loading time/save bandwidth
As brought up in https://github.com/wordpress-mobile/WordPress-Android/pull/5841#discussion_r115000629 we could improve the Media Library on self-hosted sites by loading smaller images instead full pictures. 
We tried to use `media.getThumbnailUrl`, but the default thumbnails size in WordPress is 150x150px wide, that makes the media grid ugly but images load much faster (Average of 8kb images vs. 2Mb).

@nbradbury suggested to load the thumbnail first, [then load the larger image](https://github.com/wordpress-mobile/WordPress-Android/pull/5841#issuecomment-300576526)
This could be an option, but it will not save bandwidth, since you've to download the full size pictures anyway. 

Not sure if we've a way to access the `medium`, and `large`, picture URLs in the app. If not, we can open a ticket in core for this. If we can access the `large` version of the picture, we can use the thumbnail first, and then load the `large` file.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5878 - sites that can't use Photon now fall back to using the various media image sizes rather than the full-sized image when being displayed in the media browser.

Note: this PR relies on [this FluxC branch](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/448) which should be merged prior to reviewing this.

### CODE REVIEW

**Comment by aforcier** [comment]
@daniloercoli should this be targeting `release/7.5`?

**Comment by daniloercoli** [comment]
I think we can postpone this PR to 7.6 and merge it in `develop`. 
This is not going to fix a bug, and Photon is doing a good jobs on resizing pictures for self hosted sites.

**Comment by aforcier** [comment]
Sounds good to me @daniloercoli, only asking due to the milestone - updated that to 7.6.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
