### PR TITLE
Show Single Message for Pass or Fail when Adding Tag

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Avoid confusion from conflicting messages as described in https://github.com/wordpress-mobile/WordPress-Android/issues/4612 by showing a single message when adding a tag passes or fails.

### Test
**Pass**
1. Go to ***Reader*** tab.
2. Tap gear icon in the action bar.
3. Enter "a8c" in tag input field.
4. Tap done button in the keyboard.
5. Notice single, successful message.

**Fail**
1. Go to ***Reader*** tab.
2. Tap gear icon in the action bar.
3. Enter "a8c4dayz" in tag input field.
4. Tap done button in the keyboard.
5. Notice single, unsuccessful message.

### CODE REVIEW

**Comment by nbradbury** [comment]
This solution works fine over a fast connection, but over a slow connection there's a delay between adding the tag and seeing the toast saying it has been added.

The original goal was to be optimistic - assume the call will succeed, since most times it will, so tell the user right away that the tag has been added. That way there's no delay due to a slow connection.

But now that I look at this again (it's been a while since I wrote that code!), do we need to tell the user the tag has been added since we already immediately add the new tag to the listview? Perhaps a better option would be to do away with the successful toast entirely.

**Comment by theck13** [comment]
Good points.

Testing on the emulator with GSM network type and Poor signal strength leads to an equally confusing experience with or without the "Added tag" message.  With an immediate message, you may be confused by the new tag not showing until the process completes at some indeterminate time after the message.  With a delayed message, you may think the attempt failed immediately without any message while it's attempting in the background.  Either way, you may not be sure what happened.

The best option might be to add a progress spinner to show the user when the process has completed successfully or unsuccessfully.

**Comment by nbradbury** [comment]
> e. With an immediate message, you may be confused by the new tag not showing until the process completes at some indeterminate time after the message.

Oh, I was thinking the tag gets added to the list before the call is made, but you're right - it doesn't get added until after the call completes. So I agree a progress spinner is a better approach.

**Comment by theck13** [comment]
@nbradbury, I added the progress ***spinner***.  It's ready for another ***round***.

**Comment by nbradbury** [comment]
> I added the progress spinner. It's ready for another round.

facepalm

**Comment by nbradbury** [comment]
Looks good :shipit: !

**Pull request merged**
