### PR TITLE
Widget links to stats activity

### PR DESCRIPTION
**Pull request by planarvoid**
This PR adds links to the new Views widget that link to the Stats activity. 
The title is now clickable and opens the `Days` view in the Stats for the correct Site. 
The items in the list open the same screen but should update the selected date in the Overview block.

To test:
* Add a Views widget for a Site A to the home screen
* Click on the widget title
* The Stats activity is opened on the `Days` tab for Site A

To test 2:
* Add a Views widget for a Site A to the home screen
* Go to the widget and click on an Day 1 item in the list
* The Stats activity is opened on the `Days` tab for Site A showing the data for Day 1 on all the cards

To test 3:
* Open the app and switch to Site B
* Go to the Stats
* The Stats activity is opened for the Site B
* Go to the widget for the Site A and click on it
* The Stats activity is opened for the Site A 

To test N:
* Try combination of the tests with several widgets, sites and switching between places in the app

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by nbradbury** [comment]
Just a friendly reminder to please make sure to manually merge `develop` into this branch before you merge this PR, as `develop` now contains the AndroidX migration. The automatic merge can succeed but still break the build. Better to find out now before it breaks `develop`. Thanks!

**Review by khaykov — COMMENTED** [review]
I don't really have any comments on the code, but I found an issue testing the widget:
1. In the app select Site A.
2. Add a widget for Site B.
3. Tap somewhere in the widget for Site B to open Stats.
4. Observe that the Stats for Site B are shown.
5. In Stats, navigate away from the Stats activity, by clicking on "View more" of a card (eg. Post and Pages).
6. Go back to the Stats activity.
7. Observe that the Stats for Site A are shown instead.

**Comment by planarvoid** [comment]
@khaykov thanks! very good catch 💯  I'll look into it. I think we're overriding the selected site in the "View more" screen.

**Comment by planarvoid** [comment]
@khaykov all should be fixed now! I fixed it for the 'View all' screens and for the 'Insights management'. There was also a bug with the tab selection I fixed (the Days tab was not always auto-selected when coming from the widget)

**Comment by khaykov** [comment]
@planarvoid Thank for the fixes! Looks like Days tab fix introduced an issue where it gets selected every time on orientation change:

1. Open stats from widget.
2. Navigate to any tab that is not Days.
3. Rotate device.
4. Days tab gets selected.

Another issue:

1. Open stats from a specific day from a widget.
2. While on the Days tab, press "arrow" button or tap on the graph to select any other day.
3. Rotate device.
4. Notice that selected Day reset's to the one selected in widget originally.

PS: I don't have "Don't keep activities" ON - the issues happen during normal lifecycle.

**Comment by planarvoid** [comment]
@khaykov thanks for the testing! I've fixed the issue. We only reset the day/tab when there is a new intent and that should only happen once (it seems to work based on my testing efforts).

**Review by khaykov — APPROVED** [review]
Fixes work! Looks good now 👍

**Pull request merged**
