### PR TITLE
Merge/release 16.3 into develop

### PR DESCRIPTION
**Pull request by loremattei**
This PR merges 16.3 back into develop.

There was a conflict with the Gutenberg module hash due to a fix, which I resolved accepting the version in develop.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
The lint error is known and it's actually in develop. It's handled in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13592)

**Review by mokagio — APPROVED** [review]
:shipit:

**Comment by mokagio** [comment]
I wonder why Peril hasn't reported yet 🤔 

I checked its dashboard and I can see activity recently, so it's not offline.

**Comment by loremattei** [comment]
Weird! Probably a hiccup with the hook when this PR was created.

**Pull request merged**
