### PR TITLE
My Site Dashboard: Tabs - Implement default tab experiment logic + Show QS Card on default tab

### LINKED ISSUE #16180: My Site Dashboard: Tabs - Implement default tab experiment logic
Parent #15989 

As part of the A/B test, default the my site tab to "Dashboard/home" using the following rules:

If AppPrefs `MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT` == "nonexistent" => default to SITE_MENU
Otherwise use the value of the app pref key => dashboard|site_menu

The `MySiteDefaultTabExperiment` class can be used to get the variant value

### PR DESCRIPTION
**Pull request by ashiagr**
Closes #16180

This PR 

1. Sets initial `My Site` tab based on the default tab experiment variant as follows:
If `AppPrefs.MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT` == "dashboard" => default to DASHBOARD
Otherwise, `SITE MENU` is set as the default tab.

2. Displays `Quick Start Card` on the initial default tab. For this, I removed the hard-coded `QuickStartOrigin` in the `QuickStartTasksRepository` and used the default tab value in the `MySiteViewModel` for displaying the card in 4e60687897babe46667c8672561fdcb0c46c50f5.

To test:

`Test.1 - Default Tab Selection`
- Since we cannot control which value gets returned from the experiment for the default tab, I relied on the unit tests for testing the functionality. Make sure that the unit tests added in b6f906c3efecc65fb4e3d839c98cd6041d8c0013 cover important scenarios. 
Another option is to manually hard-code the `MySiteTabExperimentVariant` value in `AppPrefs.getMySiteDefaultTabExperimentVariant` and check that appropriate tab is shown as the default tab. 

`Test.2 - Quick Start Card on Default Tab`
- I updated existing tests that were dependent on `QuickStartOrigin` to now use the `MySiteDefaultTabExperiment` value. Make sure that the unit tests in d6c3b57c80c0c9ebacd2991fa19112e2df9bbec7 are updated correctly. 

`Test.3 - Quick Start Flow`
We only tested `Quick Start - Site Menu Step` when the quick start card was shown on the `Dashboard`/ `Home` tab. Now it is possible that the card is shown on `Site Menu` tab, so we might want to retest QS flow from QS card on this tab.

- Manually hard-code the `MySiteTabExperimentVariant` value to SITE_MENU variant in `AppPrefs.getMySiteDefaultTabExperimentVariant` .
- Reinstall the app.
- Go to My Site -> Me -> App Settings -> Debug settings.
- Turn on the `MySiteDashboardTabsFeatureConfig` flag under the Features in development section.
- Logout/ login and select "Show me around" when the quick start prompt is shown.
- Notice that `Quick Start Card` is shown in the `Site Menu` tab. 
- Run tests in [wpandroid-quick-start-testing-instructions.txt](https://github.com/wordpress-mobile/WordPress-Android/files/8246096/wpandroid-quick-start-testing-instructions.txt). 

## Regression Notes
1. Potential unintended areas of impact
The initial `My Site` tab is not set correctly. 
`Quick Start Card` is not shown on the initial tab and `Quick Start` flows don't work as expected.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I relied on automated tests as specified in the `To test` section.

4. What automated tests I added (or what prevented me from doing so)
Added/ updated unit tests to test default tab based on default tab experiment variant and that quick start is shown on the default tab.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — APPROVED** [review]
@ashiagr - Code looks good 👏 . It works as expected re: launching the initial tab based on the default variant.

I'll approve, but won't merge because I have a ❓ on testing QS. 
Scenario
- Default tab is site_menu
- QS shows up correctly on the tab
- Tap on view stats (from grow your audience) and the focus point is shown correctly
- Tap on the dashboard tab
- Tap on site_menu tab and the notification/focus pt is gone. Is this the expected behavior? I see the same when the card is on the dashboard tab. If I switch tabs, the notification dot disappears.

Can you double check for me - just to make sure I'm not adding logic that doesn't exist. Thanks

**Comment by ashiagr** [comment]
Good catch @zwarm! Looks like it was an easy fix - [d2088d5](https://github.com/wordpress-mobile/WordPress-Android/pull/16199/commits/d2088d508e91d3b82a7bf8889d0feaec6a1eb20d)

Another thing - It looks like we need to always set `Home` tab as the initial tab and set default tab based on the default tab experiment variant. I confirmed this behavior on iOS (notice how "Home" tab is always the initial tab and QS card is shown on the default tab "Site Menu" which is not the initial tab). I've added a "Not Ready for Merge" label till I fix this behavior. 🙏 

Screenshot 2022-03-30 at 3 08 55 PM

**Comment by zwarm** [comment]
> notice how "Home" tab is always the initial tab

@ashiagr Is that the case if you change your "initial" tab in the settings area (only on iOS)

**Comment by ashiagr** [comment]
> notice how "Home" tab is always the initial tab 
> Is that the case if you change your "initial" tab in the settings area (only on iOS)

We discussed it in DM. TL;DR tabs ordering doesn't change; just that appropriate tab is selected as the default tab based on default tab AB experiment.

@zwarm, I've updated the logic according to the walkthrough today and updated test cases. I wasn't able to test it after resolving the conflict with site header changes that got merged today. If you want to try out this PR, please go ahead. Otherwise, I'll do one more round of testing tomorrow and ping you. Thank you!

**Pull request merged**
