### PR TITLE
Lightmode Avatar Placeholder Issue 

### LINKED ISSUE #13918: My Site: In light mode, placeholder avatar is just a grey circle.
When in Light mode testing a self-hosted site (no Jetpack, no other sites), on the My Site screen, the avatar placeholder appears to just be a gray circle, not the actual avatar placeholder image.

screenshot_20210129-152853

wpandroid 16.6-rc-1, Pixel 2

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #13918

This fixes the issue of the placeholder image not being shown in light mode. The placeholder image had a white colour which in white background(light mode) would not be visible. The placeholder and fallback icon in case of error were replaced with another icon which is used as the placeholder for an avatar. To be more precise, the placeholder resource `ImageType.USER` is replaced with `ImageTypeAVATAR_WITH_BACKGROUND`. The `ImageType.USER` is unused and so is deleted. 

### Before 

| Light Mode | Dark Mode |
| :---        |    :----:   |  
|Screenshot_20220124-152007|Screenshot_20220124-151955|

### After the fix 

| Light Mode | Dark Mode |
| :---        |    :----:   |  
| Screenshot_20220124-151906 | Screenshot_20220124-151915 |

To test:

1. Launch the app in light mode
2. Login with a Wpcom or use a self-hosted account that doesn't have an account logo.
3. Go to My Site screen.
4. Notice that the user placeholder is displayed 

## Regression Notes
1. Potential unintended areas of impact 
    1. Places where the placeholder image type is `ImageType.USER` will crash
    2. Placeholder not being displayed properly 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tests 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Hey @AjeshRPai! 

While I'm testing your PR, can you check why APKs were not generated for this PR? You can check with `platform9` team for any environment setup issue.

**Comment by ashiagr** [comment]
👋 @AjeshRPai 

As discussed, I did preliminary testing and noticed that the new placeholder is not reflected in the light mode on my device (Android 12) although it is shown on an emulator (Android 9). I already tried clearing the app cache and storage to rule out any caching issues. 🤔 

https://user-images.githubusercontent.com/1405144/150797287-888aefa0-c925-4ea2-8f14-22dc163b16ef.mp4

**Comment by AliSoftware** [comment]
Ok I have no idea why CircleCI (which runs the "Installable Build" job) apparently refuses to be triggered on this particular PR, even after the push of empty commits to try to re-trigger it…

I don't think it should be related to the fact that @AjeshRPai is new to the org and this is their first PR, as CircleCI doesn't depend on that (but instead should run on every PR that is not from a fork).
What's strange is that this `issue/13918-lightmode-avatar-placeholder` branch from this PR is not even listed in CircleCI, as if CircleCI didn't even know about it at all, which even prevents me from manually triggering an Installable Build on that branch from their web UI as I can't select that branch to trigger it on. 😒 

I'll keep investigating but not sure I'll be able to spend too much time on it today (and not sure it's worth spending too much time on it anyway especially given @jkmassel already plans to migrate that last remaining CircleCI job to Buildkite soon anyway)

**Review by ashiagr — COMMENTED** [review]
The issue needs investigation for a potential `Android 12` bug. Considering low priority, keeping it on hold for now.

**Pull request closed without merging**
