### PR TITLE
Feature/quick start tutorials

### PR DESCRIPTION
**Pull request by khaykov**
Part of #7707

This PR adds all Quick Start tutorials.
Originally, I wanted to make some sort of framework for the tutorials, but they are all quite different, spread all around the place and touch different parts of apps, so this turned out to be a bit problematic, and increased complexity without a clear return. Maybe this is something we can tackle in the future, but for now, I kept it simple and (hopefully) relatively organized, but everything still looks like a mess :(

Testing instructions:

1. Navigate to Quick Start activity from My Site fragment.
2. Click on each tutorial (create site is completed by default), follow it's instructions and make sure that they make sense, and after they are fulfilled the tutorial is marked as done (crossed out) in Quick Start activity.

Visually tutorials look like this:

**View site:**
view_site

**Chose a theme:**
themes

**Customize site:**
customize

**Share:**
sharing
**Publish post:**
create_post

**Follow:**
follow

### CODE REVIEW

**Comment by khaykov** [comment]
cc @SylvesterWilmott

**Comment by folletto** [comment]
> Originally, I wanted to make some sort of framework for the tutorials, but they are all quite different, spread all around the place and touch different parts of apps, so this turned out to be a bit problematic, and increased complexity without a clear return

With the premise that I agree there has to be some balance, I'd also want to add that there _is_ a clear return. Once we have a framework we'll have the ability to add this kind of structure anywhere in the app, based on different triggers. The idea is to use this spike of development to lay the groundwork, so we can then start to build up the capability at a low cost from now on.

Then again, this is a balance. I just want to add that there is a clear return out of it :)

**Comment by SylvesterWilmott** [comment]
Looking good.

For the Publish Post and Follow screens, I assume we are not really able to position a dot on top of the bottom navigation? If this is the case I suggest a copy change for those dialogs.

The small inline icons seem to be aligned to the top of the line of text, can we nudge these upwards to account for the difference in icon size and text line height?

Also regarding the timings, how long are we keeping these on screen? Would be good to see a video/gif of one in action.

**Comment by khaykov** [comment]
Marking as not ready for review yet, as I'll change some visual aspects of the focus point (animation, positions, etc.)

**Comment by khaykov** [comment]
@SylvesterWilmott I'm working on adding focus point to bottom nav. So far it looks doable, but I wonder where exactly you wan't it to appear?

Regarding the icon size, I can't really move the icon up, but I increased its size to 18dp, and it looks pretty good.
I also changed the duration of the snack bar to 5s and added animation to focus point.

You can check all the changes [here](https://cloudup.com/caWi0BQ8Eo4).

**Comment by SylvesterWilmott** [comment]
> I increased its size to 18dp, and it looks pretty good.

Agree. This looks good!

> I also changed the duration of the snack bar to 5s and added animation to focus point.

Also looking spot on!

One question, what happens if the snackbar is open and the "view site" row is at the very bottom of the view (theres no view admin option)? will it overlap or is there enough space to show both simultaneously?

**Comment by khaykov** [comment]
> One question, what happens if the snackbar is open and the "view site" row is at the very bottom of the view (theres no view admin option)? will it overlap or is there enough space to show both simultaneously?

Looks like Android magic will make some space for it :) The list will shrink back when snackbar is gone.
[Image from Gyazo](https://gyazo.com/4153531e7064e68d815c78d9f4e203d7)

**Comment by khaykov** [comment]
@theck13 Sorry for the wait! PR turned out to be a bit bigger then I expected, but it should be pretty straightforward (hopefully). Hope I didn't miss anything :)

**Comment by khaykov** [comment]
Hmm. I'll try to split it into something more manageable :)

**Comment by khaykov** [comment]
This PR is being split into new, smaller ones, so I'm going to close it.

**Pull request closed without merging**
