### PR TITLE
[Reader IA] Open subscription management from Filter sheet

### LINKED ISSUE #19859: [Reader IA] Open existing subscription management screen from Filter sheets
Initially, both for the Blogs and Tags Filter sheet, we will add an "Edit" button on the top right, which should simply open the existing subscription management screen, the same way as the previous "Manage Subscription" top app bar button did.

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #19859 

> [!CAUTION]
> Should not be merged before #19856

Adds the `Edit` button to the Filter bottom sheet and opens the existing "Subscription Management" screen when tapping that button.

>[!Important]
> In the Reader IA project we are using the word "tag" instead of "topic" and "blog" instead of "site" but the existing subscription management UI uses the previous terminology. We are still figuring out what should be done with respect to that, a conversation started here: p1703879376821999-slack-C05N140C8H5

-----

## To Test:

1. Install and log into Jetpack
2. Go to the Reader
3. Select a Feed that contains filters (like "subscriptions")
4. Tap the "Blog" filter
5. **Verify** the "Edit" button is shown in the sheet (top right corner)
6. Tap the "Edit" button
7. **Verify** it opens the existing subs management screen in the "Sites" page
8. Go back
9. Tap the "Tag" filter
10.  Tap the "Edit" button
11. **Verify** it opens the existing subs management screen in the "Topics" page

-----

## Regression Notes

1. Potential unintended areas of impact

    - N/A

12. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

13. What automated tests I added (or what prevented me from doing so)

    - Updated existing test naming since an existing flow was used.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by RenanLukas** [comment]
Hey @thomashorta, thanks for the PR!

I've found a scenario where we display a `0 Blogs` chip. It's basically a fresh install where probably the subscribed blogs were not fetched yet. It doesn't crash or anything, but until the blogs were fetched it seemed like I wasn't subscribed to anything. 

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/b9d3dfba-c43d-4552-b30f-ae9887e9e3c0

I've created a [separate issue](https://github.com/wordpress-mobile/WordPress-Android/issues/19891) in case it makes sense.

**Review by RenanLukas — APPROVED** [review]
I've followed the testing steps and it's working as expected. Code LGTM :shipit:

**Comment by thomashorta** [comment]
> I've found a scenario where we display a 0 Blogs chip. It's basically a fresh install where probably the subscribed blogs were not fetched yet. It doesn't crash or anything, but until the blogs were fetched it seemed like I wasn't subscribed to anything.

I've seen this happen though not for such a long time like shown in your video, so I didn't investigate it further, but it makes sense that it could take some time (and probably takes longer depending on the number of blogs). I'm not 100% sure what would be the best fix for it but thank you for creating the issue, we can think of a solution when we work on it.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
