### PR TITLE
Point to gb-mobile fix attempt

### PR DESCRIPTION
**Pull request by hypest**
Attempt to fix a clipping issue in gutenberg-mobile.

This PR is a temporary PR to test out https://github.com/wordpress-mobile/gutenberg-mobile/pull/2151 from gutenberg-mobile. No plans for merging it directly to WPAndroid.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Hi there! `14.7` is being frozen, so this PR is being bumped to `14.8`. If these changes _have to_ be shipped with `14.7`, please target `release/14.7` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

_P.S: I am still working on the messaging for these bumps, so please let me know if you have any questions/concerns/feedback._

**Comment by oguzkocer** [comment]
Hi there! `14.8` is being frozen, so this PR is being bumped to `14.9`. If these changes _have to_ be shipped with `14.8`, please target `release/14.7` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Extra note:**
@hypest Looks like this PR might not need a milestone since it seems to be a `temporary PR`, as you put it, should we remove the milestone on it so it doesn't need to be bumped for each release?

**Comment by hypest** [comment]
Makes sense @oguzkocer , removed the milestone flagging, thanks!

**Comment by cameronvoell** [comment]
Closing as this fix has been merged in gb-mobile https://github.com/wordpress-mobile/gutenberg-mobile/pull/2151

**Pull request closed without merging**
