### PR TITLE
Issue/10203 img local path

### LINKED ISSUE #10203: Media files are sometimes uploaded with path to local storage
local-image-path
### Expected behavior
When I attach a media file to a post, the post won't get uploaded until the image gets uploaded and the local path to the image is replaced with url.

### Actual behavior
When I attach a media file to a post, the post gets sometimes uploaded even though its content still contains local path to the image.

### Steps to reproduce the behavior
1. Turn on airplane mode
2. Create a draft and add an image into the content
3. Click on Back
4. Create another draft and add **the same** image into the content
5. Click on back
6. Turn off the airplane mode
7. Wait until the uploads completes
8. Open the second post
9. Switch to HTML mode
10. Notice the post contains a path to the local storage

Another scenario which might result in a post with local path being uploaded to the server got fixed here https://github.com/wordpress-mobile/WordPress-Android/pull/10079#issuecomment-510037492

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10203 

@maxme @hypest @mzorz I think it'd be good to merge this fix into the next release (14.3) as we are not sure how many users are affected.

The previous implementation of `isMediaInGutenbergPostBody` wasn't taking into account that the `wp:image` tag can contain any number of attributes in any order. It always expected `id` would be the only attribute in the tag. More info https://github.com/wordpress-mobile/WordPress-Android/issues/10203#issuecomment-582355987.

To test:
1. Copy the regex into an online tool, such as https://regexr.com/ (remove the escape chars `\`)
2. Play with it and verify it works as intended
-------------------
1. Verify this issue https://github.com/wordpress-mobile/WordPress-Android/issues/10203#issuecomment-582346379 isn't reproducible

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by maxme** [comment]
@malinajirka Thanks for taking care of that.

Code looks good if the `localMediaId` string contains a number (and this is the case actually). It will fail if it contains any string due: double quotes will be added and are not expected in the regex, eg. `<!-- wp:image {"id":"string"} -->`). Ping @mkevins - more complex local ids were considered, I'm not sure if we're still planning to change anything there. If we're not planning to change them, then let's ship this.

**Comment by mkevins** [comment]
> Code looks good if the `localMediaId` string contains a number (and this is the case currently). It will fail if it contains any string due: double quotes will be added and are not expected in the regex, eg. `<!-- wp:image {"id":"string"} -->`). Ping @mkevins - more complex local ids were considered, I'm not sure if we're still planning to change anything there. If we're not planning to change them, then let's ship this.

AFAIK, ids will always be an integer for `wp:image` blocks (one of the local id collision solution proposals negates the id for local media, but it will still be an integer). One thing I'm wondering though, for the `isMediaInGutenbergPostBody` method: should we be considering other blocks as well (e.g. media-text, gallery, video)? If so, the patterns in the processors here might be useful as reference: https://github.com/wordpress-mobile/WordPress-Android/tree/15996c7c2bc8656d2d63c421294a6efbe66b308b/WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors.

**Comment by malinajirka** [comment]
>One thing I'm wondering though, for the isMediaInGutenbergPostBody method: should we be considering other blocks as well (e.g. media-text, gallery, video)?

ohh great point! I think you are right. I have created [a new ticket](https://github.com/wordpress-mobile/WordPress-Android/issues/11386) as it's not related to attribute ordering which this PR is trying to fix.


Thanks you both! Let me know if you want me to modify something in this PR or if you think we should fix both the issues in a single PR.

**Comment by mkevins** [comment]
This looks good (addressing the other blocks seems out of scope for this PR). Thanks for opening the issue to track @malinajirka :+1: .

**Comment by malinajirka** [comment]
I've update the target branch to `develop` and I'm merging this PR, since it has already been approved.

**Comment by oguzkocer** [comment]
@malinajirka Just a quick reminder that the release notes needs to be updated when a target branch is changed from the release branch to `develop`.

**Pull request merged**
