### PR TITLE
Prepublishing bottomsheet categories not loading in story creator

### LINKED ISSUE #14234: Stories prepublishing bottom sheet: Categories not loading
### Expected behavior

When publishing a story, the category list should be pre-filled.

### Actual behavior

In some cases the category screen is blank in the prepublishing bottom sheet from the story creator.

Originally submitted by a user, and I was able to reproduce.

### Steps to reproduce the behavior

From a fresh install of the app:
* Enter the story creator
* Press 'publish'
* Tap the categories option
* Notice that no categories load

Repeating those steps keep producing the same result. Also, when visiting the categories screen from My Site > Settings > Default Category, that is also blank.

One way I've found to get it working is to attempt to publish a regular post and load the categories option from the bottom sheet. They'll show up there, and then will be available the next time you try to create a story.

cc @jd-alexander maybe you have some insight into this one?

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #14234

## Findings
`TaxonomyActionBuilder.newFetchCategoriesAction(site)` was not being used in the `PrepublishingViewModel` to do an initial fetch of categories, so if the user did not attempt to create a post and modify the categories via Post Settings, the local cache will be empty.

Another issue that was mentioned was 

>  when visiting the categories screen from My Site > Settings > Default Category, that is also blank.

I was not able to reproduce this. I will give it another try tomorrow.

## Solution

1. Use `TaxonomyActionBuilder.newFetchCategoriesAction(site)` to fetch the categories when the bottom sheet is loaded so that when you navigate to the Categories you will see them. 

2. I did a cleanup of some unused functions & params.

## Testing
From a fresh install of the app:

1. Enter the story creator
2. Press 'publish'
3. Tap the categories option
4. Notice that categories load

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Review by zwarm — COMMENTED** [review]
@jd-alexander - I followed the testing instructions, but still see a blank list of categories when
- new install
- story post create
- accept requests for media access
- selected photos
- tapped the ->
- PPN bottom sheet shows
- tapped categories
- the list is empty
After I published the post and create another story, the categories show.

**Comment by jd-alexander** [comment]
> @jd-alexander - I followed the testing instructions, but still see a blank list of categories when
> 
> * new install
> * story post create
> * accept requests for media access
> * selected photos
> * tapped the ->
> * PPN bottom sheet shows
> * tapped categories
> * the list is empty
>   After I published the post and create another story, the categories show.

Thanks for the review @zwarm I just realized that in my environment sometimes the tags are shown and other times it isn't. I have resolved the issue, by listening to the `OnTaxonomyChanged` within the `PrepublishingCategoriesFragment` similarly to how `onTermUploaded` is handled and updating the `ViewModel` with the changes. I will continue testing and then submit these changes for review.

**Comment by zwarm** [comment]
@jd-alexander - Looking better, but now I see an issue when creating a subcategory: the option is not getting checked when returning to the list. Take a look.

**Comment by jd-alexander** [comment]
> @jd-alexander - Looking better, but now I see an issue when creating a subcategory: the option is not getting checked when returning to the list. Take a look.

Thanks for the thorough testing @zwarm I haven't been around categories so long, I didn't remember the subcategories. I was able to reproduce the behavior. I resolved it and added tests to cover the logic changes. I am going to go over the code again. Once the build is good, I will request another review.

**Review by zwarm — APPROVED** [review]
@jd-alexander 
All works as expected now. Thanks for making the changes!

**Pull request merged**
