### PR TITLE
Onboarding Improvements: Epilogue Screen Create New Site

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #14990

This PR enabled creating a new site from within the newly designed `Login Epilogue` screen.

NOTE:  Dismissing the `Your site has been created!` screen, instead of clicking the `OK` button shows the previous underlying screen (instead of the expected My Site screen). This is expected and working exactly as is with the `Site Picker` screen as well. A nice to have task was added to the parent issue which will aim to deal with that, if the ends up being decided as important to have.

-----

To test:
1. Go to `My Site` -> `App Settings` -> `Test feature configuration`.
2. Enable the `OnboardingImprovementsFeatureConfig` feature flag.
3. Log-out and log-in to the app again.
4. When on the `Login Epilogue` screen, click on the `Create New Site` button.
5. Make sure the `Choose a design` site creation screen is shown.
6. Pick a design, click preview or skip and in general verify everything works as expected. Then progress with the `Choose a domain`
7. Pick a name for your site and create a site. The `Your site has been created!` screen will be shown. Click `OK`. Note, you can also dismiss this screen, but it will navigate you back to the `Login Epilogue` screen as per the **NOTE** above.
8. Make sure the new `Quick Start Prompt` is shown.
9. Dismiss, click the `No thanks` or the `Show me around` button and make sure the `My Site` screen is shown with or without showing the `Quick Start` section, with its `Next Steps` and all, according to your action.

-----

## Regression Notes
1. Potential unintended areas of impact

The `Site Creation` flow might not work as expected when that flow is triggered from within the `Login Epilogue` screen and based on the base input that it was given.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@ParaskP7 - The happy path works as expected 🥳    I will approve this PR now but will wait for you to read the following before merging. 

I have one question and one sanity check.

> Pick a name for your site and create a site. The Your site has been created! screen will be shown. Click OK. Note, you can also dismiss this screen, but it will navigate you back to the Login Epilogue screen as per the NOTE above.

❓ I tapped the Back Button here and was navigated back to the Login Epilogue view as expected; however my newly created site was NOT shown in the site list. Should it be?

Following the path above, I clicked on another site and was prompted with the quick start view. I selected the show me around option. Then I navigated back to my brand new site and was not shown any quick start items in My Site. I believe this is the correct behavior, but wanted to verify with you.

**Comment by ParaskP7** [comment]
👋 @zwarm !

Thank you so much for this review! 🙏 

> @ParaskP7 - The happy path works as expected 🥳 I will approve this PR now but will wait for you to read the following before merging.

🎉 👍 

>❓ I tapped the Back Button here and was navigated back to the Login Epilogue view as expected; however my newly created site was NOT shown in the site list. Should it be?

Yes, this is expected, thus I noted that this is something we might want to work on, but as a separate task. The problem is that this flow works exactly like that even with the `Site Picker` screen. So, when you create a new site from the `Site Picker` screen, and then dismissing the screen when you reach the `Your site has been created!` screen, then you will observe the very same behavior, you will be navigated back to the `Site Picker` screen and the newly created site will NOT be shown in the site list. Thus, I decided that this is somehow broken/hasn't been dealt with in general, maybe because we are expecting the user to always click the `OK` button anyway, and as such I thought it is best if that is handled as part of a separate task, which is why I then added it as a nice to have.

Do you feel that we should be handling this in this PR?

One thing I thought of doing is triggering the `OK` click event if the user dismisses the screen. We can override the `onBackPressed()` call and direct the user to the next screen anyway. However, mind the fact that the next screen is actually showing the `Quick Start Prompt`, which might feel a bit off to be showing a fullscreen dialog when the user presses back. Most probably the best course of action is to navigate the user to the `My Site` screen on both cases, when coming from the `Site Picker` or the `Login Epilogue` screen, without any additional actions like showing a fullscreen dialog, but we need to think about it, agree on it and develop this solution as it is not trivial.

> Following the path above, I clicked on another site and was prompted with the quick start view. I selected the show me around option. Then I navigated back to my brand new site and was not shown any quick start items in My Site. I believe this is the correct behavior, but wanted to verify with you.

Yes, this is the expected behavior. Would you expect something else to happen instead?

If you are on the `Login Epilogue` screen, no matter where you come from, dismissing instead of clicking `OK` or otherwise, when you then chose a site, you will get to that new flow. The previous flow will cease to exist.

Then, from there, if you go and navigated back to your previously newly created site, the one where you dismissed instead of clicking `OK`, since you will doing that through the `Site Picker` screen, which again is another flow, you will never get to have the `Quick Start Prompt` shown as the `Site Picker` flow is not doing that by design.

**Review by zwarm — APPROVED** [review]
@ParaskP7 - thank you for the explanation.
I knew dismissing would take me back to the epilogue, but was unaware that the site wouldn't be shown. I don't consider that a blocker for this PR, nor do I consider it a "must-have". A better solution, down the line, would be the ability to recall the quick-start prompts from the My Site view. BUT, that's a different discussion 😆 

As for intercepting the back button, I don't think that is necessary right now; however I could see making a case for intercepting and showing QS prompt. It fits with our goal of increasing engagement. Of course we don't want to piss people off, but they did just create a new site and we do want them to set it up. Sounds like we can have multiple discussions on edge cases. 

Thanks for the discussion. And this time I remembered to Approve the PR!

**Comment by ParaskP7** [comment]
Thank YOU @zwarm !

> I knew dismissing would take me back to the epilogue, but was unaware that the site wouldn't be shown. I don't consider that a blocker for this PR, nor do I consider it a "must-have". A better solution, down the line, would be the ability to recall the quick-start prompts from the My Site view. BUT, that's a different discussion 😆

True, there is so many things we can do, all of which we might need to brainstorm through and decide on, let's keep that thought! 👍 

> As for intercepting the back button, I don't think that is necessary right now; however I could see making a case for intercepting and showing QS prompt. It fits with our goal of increasing engagement. Of course we don't want to piss people off, but they did just create a new site and we do want them to set it up. Sounds like we can have multiple discussions on edge cases.

Another thing for us to discuss and agree upon, lots of edge cases indeed... 🧑‍🏭 

> Thanks for the discussion. And this time I remembered to Approve the PR!

🍾  Thank YOU!

**Pull request merged**
