### PR TITLE
Add block site option to followed posts menu

### LINKED ISSUE #17590: Make the block site option available on posts of followed sites
### Description
In order to make the **block site option** more prominent we want to make it available both for followed and unfollowed sites.
When a followed site is blocked it should also be unfollowed.

Note that with the current logic [the button appears only for sites that the user does not follow](https://href.li/?https://github.com/wordpress-mobile/WordPress-Android/blob/ee7f8917d211e027dd7e4897c6a4e281f8acc0f9/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt#L186).

This task is to add the `Block this Site` option to the dropdown menu on posts of followed sites. On unfollowed sites this is already present:

| Unfollowed Site Post | Followed Site Post |
| - | - |
| unfollowed | followed |

Internal ref `pcdRpT-1ms-p2`

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #17590

This PR adds the option to block a site from the post `⋮` overflow menu of followed sites. Unfollowed sites already had this option.

Unfollowing the blog before blocking it was not necessary as this is already handled in the backend.
Internal ref:
> fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qoybpx%2Qoybt.cuc%3Se%3Qnr8q8q8p%2337-og

The functionality persists the blocked sites in the local reader database.

To test:

### Block site
1. Open the WordPress / Jetpack app and login
2. Go to `Reader` → `Discover`
   - If you don't currently follow any tags, select a few and refresh list
3. Tap on the top (blog name) of the first result
4. The Reader site screen should open for that blog
5. Tap on the `Follow` button
6. Tap on the `⋮` overflow menu for the first post
7. **Verify** the option to `Block this site` is available
8. Tap on `Block this site`
9. **Expect** the posts list to disappear
10. Go back
11. Tap the `Following` tab
12. Tap the `Filter menu`
13. **Verify** the previously blocked blog is not listed in the Following Sites list

### Unblock site
1. Open the Reader
2. Tap on the `⋮` overflow menu on one of the posts
3. Select `Block this site`
4. **Verify** that the post disappears from the list
5. **Verify** that an **Undo** snack bar appears
6. Tap on the **Undo** button
7. **Verify** that the post appears back along with the other posts from the site

### Sanity test
* Test upgrading from an older app version

## Regression Notes
1. Potential unintended areas of impact
   - Existing `Block site` functionality for unfollowed posts.
   - Existing `Undo block site` functionality.

15. What I did to test those areas of impact (or what existing automated tests I relied on)
    Manual testing.

16. What automated tests I added (or what prevented me from doing so)
    Updated test in `ReaderPostMoreButtonUiStateBuilderTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ovitrif** [comment]
We've currently put this on hold as we'll focus on adding the option to report & block users via reader.

As for the current state of things with this PR,
there's a few issues we've noticed (internal ref: pcdRpT-1ms-p2#comment-2120)

**Review by antonis — COMMENTED** [review]
Thank you for your work on this @ovitrif 🙇 
On a 1st pass everything looks to me and works as expected with the known issues 👍 

> As for the current state of things with this PR,
there's a few issues we've noticed (internal ref: pcdRpT-1ms-p2#comment-2120)

Probably we can add local persistence for the blocked sites and do not add them to the DB [like I tried doing here for the blocked users](https://github.com/wordpress-mobile/WordPress-Android/pull/17604/commits/a0dc44c6bee6a28c4a2e5c270ac09f1c3bfb5c0a#diff-6698962ec7d529d03ed4128791bac7a7a2279f17bbe052d31bd8542a6a59875aR908) (not sure if this approach would work for sites too though)

**Comment by ovitrif** [comment]
> Thank you for your work on this @ovitrif 🙇
> On a 1st pass everything looks to me and works as expected with the known issues 👍

Thank you for reviewing and testing the PR @antonis 🙇 

> Probably we can add local persistence for the blocked sites and do not add them to the DB [like I tried doing here for the blocked users](https://github.com/wordpress-mobile/WordPress-Android/pull/17604/commits/a0dc44c6bee6a28c4a2e5c270ac09f1c3bfb5c0a#diff-6698962ec7d529d03ed4128791bac7a7a2279f17bbe052d31bd8542a6a59875aR908)

Thank you for this great suggestion ❤️ 

I've drafted a quick WIP in https://github.com/wordpress-mobile/WordPress-Android/pull/17599/commits/6c383e496fd82df196479396f6521d32e5a43714 and on a quick check it works good 🎉 . We'll have to fix the merge conflicts and update the ReaderDatabase version after the [higher priority PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17604) is merged. Imho this looks quite promising, many thanks for your suggestion and paving the path forward with the implementation from your PR ❤️ .

**Review by antonis — COMMENTED** [review]
> I've drafted a quick WIP in https://github.com/wordpress-mobile/WordPress-Android/commit/6c383e496fd82df196479396f6521d32e5a43714 and on a quick check it works good 🎉 . We'll have to fix the merge conflicts and update the ReaderDatabase version after the https://github.com/wordpress-mobile/WordPress-Android/pull/17604 is merged. Imho this looks quite promising, many thanks for your suggestion and paving the path forward with the implementation from your PR ❤️ .

Thank you for the quick fix @ovitrif 🙇 
This LGTM and works ass expected. I've left a comment related to a mistake I originally did on my PR 😅

**Comment by ovitrif** [comment]
> Thank you for the quick fix @ovitrif 🙇 This LGTM and works as expected. I've left a comment related to a mistake I originally did on my PR 😅

Thank you @antonis  🙇 , adding the link here for your suggestion since it doesn't show on the main PR conversation:
https://github.com/wordpress-mobile/WordPress-Android/commit/6c383e496fd82df196479396f6521d32e5a43714#r92018884

**Comment by ovitrif** [comment]
Added the following fixes:
- Fixed the issue with db upgrade on https://github.com/wordpress-mobile/WordPress-Android/pull/17599/commits/9181f4621f1e2f8517b13b6ca23f00d887e13fcc
- Fixed the undo block site action, by correctly restoring the posts on the screen when `undo` is tapped on the snackbar: https://github.com/wordpress-mobile/WordPress-Android/pull/17599/commits/8f16fb5d75bcc85d4ef4506c65f1458711bb57ea

This PR seems seems quite ok now 👍 , of course merging will need manual work to adapt on top of the changes from:
- https://github.com/wordpress-mobile/WordPress-Android/pull/17604

**Review by zwarm — APPROVED** [review]
👍 @ovitrif - All looks good and works as stated. Thanks for the getting this done so quickly.

**Comment by ovitrif** [comment]
> 👍 @ovitrif - All looks good and works as stated. Thanks for the getting this done so quickly.

Thank you for reviewing this PR @zwarm 🙇 

As I'm merging the target branch into this PR branch to make it ready, I've added updated testing steps to:
- Test for unblocking a site
- Sanity test for reader DB when upgrading the app

**Comment by ovitrif** [comment]
@antonis cc. @zwarm This PR is ready for another pass, as it can now be merged into the target branch 🙇

**Review by antonis — APPROVED** [review]
Great work @ovitrif 👍 
I've retested the latest CI build on a Pixel 5 (Android 13) and everything worked for me. The code also looks good 🎉

**Pull request merged**
