### PR TITLE
Don't promote to foreground if null state

### LINKED ISSUE #7266: NPE in AutoForeground.promoteForeground() - App crashes after inputing password.
Logging to WordPress.com, the crash happens after you input correct password and "Log in" progress dialog is dismissed.

Only happens with 2fa enabled account.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.wordpress.android, PID: 29104
                  java.lang.RuntimeException: Unable to unbind to service org.wordpress.android.login.LoginWpcomService@6ba73e8 with Intent { cmp=org.wordpress.android/.login.LoginWpcomService }: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.wordpress.android.util.AutoForeground$ServiceState.isInProgress()' on a null object reference
                      at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3408)
                      at android.app.ActivityThread.-wrap27(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.wordpress.android.util.AutoForeground$ServiceState.isInProgress()' on a null object reference
                      at org.wordpress.android.util.AutoForeground.promoteForeground(AutoForeground.java:145)
                      at org.wordpress.android.util.AutoForeground.onUnbind(AutoForeground.java:123)
                      at android.app.ActivityThread.handleUnbindService(ActivityThread.java:3394)
                      at android.app.ActivityThread.-wrap27(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

### PR DESCRIPTION
**Pull request by hypest**
Fixes #7266 

To test:
1. With the app data cleared, launch the app
2. Try to login to WPCOM using an account that has 2FA enabled
3. Use your email and choose to enter a password instead of magiclink
4. After entering your password and hitting Next, some time goes by and the 2FA screen comes up normally

### CODE REVIEW

**Comment by maxme** [comment]
@hypest  or @mzorz can you double check this is doesn't happen in `release/9.4`?

**Comment by mzorz** [comment]
> can you double check this is doesn't happen in release/9.4

**Comment by hypest** [comment]
Confirmed _not_ happening on `release/9.4`. Also checked out the code and yes, `release/9.4` doesn't contain the change that introduced the bug.

**Comment by mzorz** [comment]
Confirmed it only crashes in `develop`. Looked at the code to double check and it makes sense, as changes in code that make this crash happen are only there.

**Comment by mzorz** [comment]
lol, what @hypest just said ☝️ 😂

**Comment by mzorz** [comment]
Tested, works alright 👍 
:shipit:

**Pull request merged**
