### PR TITLE
Bug 4765

### LINKED ISSUE #4765: Killing app while editor is open leaves an (Untitled) draft
### Steps to reproduce the behavior
1) Open a new post
2) Kill the app from the overview screen
3) Open the app back up and navigate to the Blog Posts page
4) Observe the (Untitled) local draft

android-untitled

### PR DESCRIPTION
**Pull request by nawabhussain**
Fixes #4765 

To test:

### CODE REVIEW

**Comment by maxme** [comment]
@nawabhussain we can't merge this you changed file mode in the whole directory and also downgraded the gradle wrapper. Rebase your branch to only include the commit that fixes the issue.

**Comment by nawabhussain** [comment]
@maxme what file modes were changed? I didn't downgrade the gradle wrapper explicitly maybe my develop repository wasn't updated. Should I delete this bug_4765 branch, fix the dev branch and then re do it? 
Thanks!

**Comment by maxme** [comment]
You can either close this PR and open a new one with one commit to fix #4765 (67f8852) or rebase your branch and clean it up.

**Comment by nawabhussain** [comment]
@maxme got  it. What about file modes?

**Comment by maxme** [comment]
> What about file modes?

Don't change file modes, I don't know what happened on your repo but you changed them from 644 to 755 in 8924c4b36429a3b66a5c204a2bd1314fd21bb6f9 - rebase and drop unnecessary commits and keep 67f8852 only.

**Pull request closed without merging**
