### PR TITLE
[Modal Layout Picker] Add analytics metrics for the layout picker

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2454

**Related PRs:** 
Depends on: https://github.com/wordpress-mobile/WordPress-Android/pull/13085

## Description

This PR adds analytics metrics to the layout picker's actions

## To test:

An easy way to test for these analytics is to debug the app and filter Logcat to look for the string `🔵 Tracked:`

Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

- Start by navigating to the Modal Layout Picker

### Template Create Page
1. Select a layout
1. Select Create Page
1. In the console, you'll see an event like:
`🔵 Tracked: editor_session_template_apply, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","session_id":"ba5e7e37-a29e-48a8-bbac-7e34625ee5c0","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}`

### Template Preview 
1. Select a layout
1. Select Preview
1. In the console, you'll see an event like:
`🔵 Tracked: editor_session_template_preview, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","session_id":"af74365c-abbe-42fc-b969-bafc7c3745b1","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}`

### Template Preview, then Create
1. Select a layout
1. Select Preview
1. In the console, you'll see an event like:
`🔵 Tracked: editor_session_template_apply, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","session_id":"ba5e7e37-a29e-48a8-bbac-7e34625ee5c0","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}`
1. Repeat selecting back and choosing a new layout as many times as you want 
1. Select Create Page
1. In the console, you'll see an event like:
`🔵 Tracked: editor_session_template_preview, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","session_id":"af74365c-abbe-42fc-b969-bafc7c3745b1","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}`

### Validate Editor Session

1. Create a new page from a selected layout using either of the paths mentioned above.
1. Perform some actions in the editor session like publishing, saving as a draft, or switching to the classic editor.
1. Expect to see editor events like the below containing the template field:
`🔵 Tracked: editor_session_start, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","startup_time_ms":7461,"session_id":"ba5e7e37-a29e-48a8-bbac-7e34625ee5c0","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0","unsupported_blocks":[]}`

### Create a Blank Page
1. Create a Blank Page
**Expect** The events mentioned in the last step to not have the template field populated. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @antonis, This is looking good for the events we're tracking. One thing I noticed that might be worth considering. Since we're reusing the same editor with the preview We're also firing the events `editor_opened`, `editor_session_start`, `editor_session_end`, and `editor_closed`. We aren't firing these on iOS so I just wanted to raise the question, should these be fired for the preview? I don't know if this would affect any funnels we have that might be looking at how often the editor is opened.

**Comment by antonis** [comment]
Hello @chipsnyder 👋 ,
thank you for reviewing this 🙇 

> One thing I noticed that might be worth considering. Since we're reusing the same editor with the preview We're also firing the events `editor_opened`, `editor_session_start`, `editor_session_end`, and `editor_closed`. We aren't firing these on iOS so I just wanted to raise the question, should these be fired for the preview? I don't know if this would affect any funnels we have that might be looking at how often the editor is opened.

I'm not sure either what is the correct approach on this. Implementation wise I can mute the extra logging by passing the `mIsPreview` flag to the `PostEditorAnalyticsSession`.

On the other hand leaving this as is resembles the behaviour when the `MODAL_LAYOUT_PICKER` build flag is off.  

**MLP ON**
```
2020-10-15 09:33:08.411 17591-17591/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_template_preview, Properties: {"has_unsupported_blocks":"0","template":"about-4","editor":"gutenberg","content_type":"new","session_id":"409b1f45-1070-4b23-9036-faf5064eba2b","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}
2020-10-15 09:33:08.417 17591-17591/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_post_created, Properties: {"blog_id":174576032,"created_post_source_detail":"no-detail","post_type":"page","created_post_source":"post-list","is_jetpack":false}
2020-10-15 09:33:08.429 17591-17591/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_opened, Properties: {"blog_id":174576032,"has_gutenberg_blocks":false,"post_type":"page","is_jetpack":false,"editor_has_hw_disabled":"0"}
2020-10-15 09:33:15.230 17591-28990/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_start, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","startup_time_ms":6816,"session_id":"409b1f45-1070-4b23-9036-faf5064eba2b","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0","unsupported_blocks":[]}
2020-10-15 09:33:19.671 17591-17591/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_closed
2020-10-15 09:33:20.238 17591-17591/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","session_id":"409b1f45-1070-4b23-9036-faf5064eba2b","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"cancel"}
```
**MLP OFF**
```
2020-10-15 09:36:50.122 29904-29904/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_post_created, Properties: {"blog_id":174576032,"created_post_source_detail":"page-from-my-site","post_type":"page","created_post_source":"post-list","is_jetpack":false}
2020-10-15 09:36:50.137 29904-29904/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_opened, Properties: {"blog_id":174576032,"has_gutenberg_blocks":false,"post_type":"page","is_jetpack":false,"editor_has_hw_disabled":"0"}
2020-10-15 09:36:56.229 29904-30504/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_start, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","startup_time_ms":6107,"session_id":"4edba602-ce81-4e67-b147-3187ed508422","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0","unsupported_blocks":[]}
2020-10-15 09:37:02.262 29904-30504/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_template_preview, Properties: {"has_unsupported_blocks":"0","template":"about","editor":"gutenberg","content_type":"new","session_id":"4edba602-ce81-4e67-b147-3187ed508422","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0"}
2020-10-15 09:37:35.734 29904-29904/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_closed
2020-10-15 09:37:36.257 29904-29904/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","content_type":"new","session_id":"4edba602-ce81-4e67-b147-3187ed508422","post_type":"page","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"cancel"}
```

cc @Tug

**Comment by Tug** [comment]
> On the other hand leaving this as is resembles the behaviour when the MODAL_LAYOUT_PICKER build flag is off.

Seems like a good opportunity to fix event parity between iOS and Android.

**Comment by chipsnyder** [comment]
> On the other hand leaving this as is resembles the behaviour when the MODAL_LAYOUT_PICKER build flag is off.

This is the flow on iOS as well in the way it is today. I think this case doesn't fully apply though because the selection of the template technically occurs outside of the editor session. 

The big difference here is Android loads the same editor fragment for previews as it does for editing. The difference in analytics though really comes down to describing the different implementations so to me the different analytics wouldn't be a big deal unless we use these for important funnels.

I think what might help us decide would be, do we use the events `editor_opened`, `editor_session_start`, `editor_session_end`, and `editor_closed` to track engagement at all? Ie If I preview all of the layouts will that affect any funnels? @Tug that might be something you can help us determine.

**Comment by antonis** [comment]
@chipsnyder , @Tug Thinking of this again the best approach is to align with iOS on this. The behaviour when `MODAL_LAYOUT_PICKER` build flag is off is not relevant anymore.

I fixed this with 08121840c900fea911c360a2f2f6608ccd1cd79f

**Review by chipsnyder — APPROVED** [review]
All is working well for me. Thanks for making those adjustments!

**Pull request merged**
