### PR TITLE
Reader : Support for *.wordpress.com deep links with custom domain as primary

### LINKED ISSUE #14216: "This post no longer exists" for links that use the non primary domain
It was reported in 3771371-zd-woothemes that when opening a link through the Chrome browser, the app shows "The post no longer exists".

### Expected behavior

I would expect the app would be able to open up the post that I clicked through the Chrome browser.

### Actual behavior

When I click a link that's pointing to the URL with a non-primary domain on Chrome browser, choose to open up with the WordPress app, I see a "The post no longer exists" error.

### Steps to reproduce the behavior

1. Visit a WordPress.com site that has a custom domain set as the primary domain on a Chrome browser (e.g. https://premiumtestsite20190311.blog/)
2. Click a link on the site that is pointing to the WordPress.com site address (see [this image](https://d.pr/i/C5fkrV) for the link to click)
3. Open up the link with WordPress app
4. See "This post no longer exists" error

Video recording: https://d.pr/v/JCZtZS/QfCufdf8mG

##### Tested on OPPO Reno 4, Android 11, WPAndroid 16.8-rc-2

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #14216

## Findings

Currently, when the Reader intercepts deep links pointing to the *.wordpress.com version of a post on a site using a custom domain, the Reader displays the `ErrorState` - "This post no longer exists". You can utilize the instructions in the issue if you wish to reproduce on `develop` before testing this PR.

<kbd></kbd>

After investigating the Reader functionality, I realized that this is happening due to the way how the post is being stored and fetched from the`ReaderPostTable`. 

When a site has a primary domain that is custom, the persisted `blogUrl` of a post inserted in `ReaderPostTable` has a custom domain instead of the `*.wordpress.com` variant, the query on the table would fail because it is basically passing a `blogUrl` of `*.wordpress.com` instead of the custom domain.

## Solution

1.  Modifications were made to the `requestBlogPost` method so that it now propagates the `blogUrl` of a `post` that is fetched so that the persisted `post` can be found using the `blogIdentifier` that represents the primary domain in use since this identifier will be a part of the `blogUrl` being stored in the `ReaderPost`.

2. To make this modification possible the `OnRequestListener<T>` now has a generic type so that if any need every arises for other `ReaderActions` to propagate changes through `onSuccess` a custom type can be specified. Approaching it this way, also allowed the changed to remain inline with the previous functionality. Since the `RequestListener` was modified all components that utilize it had to be updated. Currently, the only need for this passing data through the `onSuccess` is this method, so all other types were specified as `Void`/`Unit` to communicate that no result was being passed. 

### Reader Deeplink - with custom domain

1. Be on a site with a custom domain set as the primary domain.
2. Copy the URL for any post from the site.
3. Create a new post and add a link to the URL from the previous step.
4. Add another link to the URL from the previous step, except change the custom domain to the *.wordpress.com version.
5. Publish the post.
6. Open the post in Chrome.
7. Click on the 2nd link and choose to open the link in the WordPress app when prompted.
8. Notice that the post is rendered correctly now. 
9. You can utilize this post that is on a custom domain https://premiumtestsite20190311.blog/2021/03/09/test-post-links/ it has a link on it that leads to the site that has all posts with the custom domain. 

<kbd></kbd>

### Reader Deeplink - with WP.com domain

1. Be on a site with a non-custom domain / *.wordpress.com set as the primary domain.
2. Copy the URL for any post from the site.
3. Create a new post and add a link to the URL from the previous step.
4. Publish the post.
5. Click on the link and choose to open the link in the WordPress app when prompted.
6. Notice that the post is rendered correctly now. 
7. You can utilize [this post](https://hellokittysupreme.wordpress.com/2021/03/18/reader-testing-of-wp-com-domain/) that is on free wp.com site to verify that the deeplink behavior still works for sites that don't have custom domains 

<kbd></kbd>

### Reader Regression Testing

1. Open the app. 
2. Open the Reader. 
3. Open several reader posts via the different tabs and notice that they open as expected. 

### Comments Regression Testing

- Test the comments flow related to the reader. 

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Review by ashiagr — COMMENTED** [review]
Hiiii Joel 👋

Thank you for working on this and including detailed instructions 🙇‍♀️! It made testing really easy 😊. Solution looks good overall... I just found a crash during regression testing:

1. Click a post on the Reader.
2. Scroll down to the bottom of the details screen.
3. Click a related post (it should not be present in the local db and post fetch is triggered).
4. Notice that the app crashes.

Logs:

```
java.lang.ClassCastException: java.lang.String cannot be cast to kotlin.Unit
        at org.wordpress.android.ui.reader.usecases.ReaderFetchPostUseCase$fetchPostAndWaitForResult$listener$1.onSuccess(ReaderFetchPostUseCase.kt:44)
        at org.wordpress.android.ui.reader.actions.ReaderPostActions$6.onResponse(ReaderPostActions.java:299)
        at org.wordpress.android.ui.reader.actions.ReaderPostActions$6.onResponse(ReaderPostActions.java:292)
```

Seems like commit 1020255 has something to do with it. I can share a video if it helps, let me know. 

I think it will be better if we can test `CommentDetailFragment` also. Since the PR targets next release, I can do that next week.

**Comment by jd-alexander** [comment]
Thanks for the review and tests @ashiagr I am going to address the issues. Now, I will also work on testing the Comments flow as well and doing another set of regression testing.

> Seems like commit 1020255 has something to do with it. I can share a video if it helps, let me know.

Indeed! The bug is related to the type issue. I will make the necessary changes.

**Comment by jd-alexander** [comment]
I am going to go through the different flows to verify that all is well and then mark the PR as ready :)

**Comment by jd-alexander** [comment]
@ashiagr this is ready for another test and review. I tested all the flows that lead to the changes made to the `ReaderActions`. This involves: 

1. Clicking a blog post-related comment that fetches the post from the server. 
2. Opening several related posts. 
3. Opening several different reader posts. 
4. Opening the reader post via a deep link. 

Let me know if this covers all flows. Thanks!

**Review by ashiagr — APPROVED** [review]
Thanks for the changes! All looks good 👍.

**Pull request merged**
