### PR TITLE
Gutenberg related changes to land after 16.4 App cut

### PR DESCRIPTION
**Pull request by guarani**
This PR is for merging Gutenberg related changes to WPAndroid `develop` that were ongoing during the Gutenberg Editor 1.43.0 code freeze

To Test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
@jd-alexander, I'm following this step of the release checklist:

> Update the gutenberg/after_1.43.0 branches and open a PR against develop. If the branches are empty we’ll just delete them. The PR can actually get created as soon as something gets merged to the after_1.43.0 branches.  Merge the gutenberg/after_1.43.0 PR(s) only AFTER the main apps have cut their release branches.

I see two commits you authored, could you please clarify if these need to be merged back into the develop branch or not?

**Comment by jd-alexander** [comment]
@guarani the branch doesn't contain any changes so I don't think it needs to be merged in but from a process standpoint, we could still do it just to be safe. @hypest is it fine to `after` branch if no changes were merged into it?

**Comment by hypest** [comment]
👋 @jd-alexander , I think the process is that we just delete/close the "after" branches/PRs if there are no changes brought in.

**Comment by jd-alexander** [comment]
Thanks @hypest 🙇

**Pull request closed without merging**
