### PR TITLE
Media Browser: fix media preview for private sites

### LINKED ISSUE #12025: Media browser: preview broken for private sites
### Expected behavior
When going to the Media section of the app, I expect to be able to browse the available media on my site, with the thumbnails displaying correctly, and be able to see each item in full by tapping on them and getting their preview.

### Actual behavior
On a private site that has just been loaded, it doesn't load videos (some but not all image thumbnails are loaded, I'd think because we're using the authentication code for all Glide requests via GlideAppModule). Videos can't obtain a thumbnail nor be played.

### Steps to reproduce the behavior
1. upload a media item to a site on the web
2. make the site private
3. open the site on a WP app
4. go to media
5. observe you can't preview the uploaded media

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #12025

This PR adds the authentication headers when needed, in order to be able to successfully retrieve a video resource on a private site, either for creating a  frame's thumbnail (used in the Media Browser and MediaSettingsActivity) or to actually be able to play the video in VideoPreview.

While at it, I looked for all the places where [`MediaMetadataRetriever`](https://developer.android.com/reference/android/media/MediaMetadataRetriever) is used, and applied the same logic everywhere where applicable, namely:

- MediaGridAdapter -> `loadVideoThumbnail()` (explained above)
-  ImageUtils -> getVideoFrameFromVideo ->  
```
MediaMetadataRetriever mediaMetadataRetriever = new MediaMetadataRetriever(); 
setDataSource(videoPath, new HashMap<String, String>());
```
- AnalyticsUtils -> getMediaProperties -> VideoUtils. getVideoDurationMS -> `setDataSource()`. This does  not need to be changed given all the cases found are in the use of `AnalyticUtils.getMediaProperties()`, which in turn is only used for all videos being uploaded / picked from the device (and hence do not need the MetadataRetriever to be set any auth headers).
- MediaPreviewFragment   ->    `mVideoView.setVideoURI(Uri.parse(mediaUri));`

Also, the AztecVideoLoader has changed to allow this.

### Note

After testing and merging the PR at https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/30, I'll publish a new version of Utils to bintray and update the version in the editor lib, and revert the temporal change [introduced here with a `TODO`](https://github.com/wordpress-mobile/WordPress-Android/pull/12178/files#diff-37250c687b4cff923f7fd24da2794c3bR70-R74) to rollback and update the version

### To test
MediaBrowser:
1. log in to a private site that has videos (or, upload some videos to a private site)
2. go to the Media section of the app
3. tap on the Videos tab (or alternatively if you have mixed images and videos you'll be able to see the thumbnails for all in the All tab)
4. observe the thumbnails load properly
5. tap on a video
6. observe the big thumbnail in the media settings activity shows properly and the "Media could not be loaded" error toast does not appear anymore (and with that, you won't be thrown out of the activity anymore!)
7. tap on the preview up there
8. observe the video loads and autoplays 🎉 

Aztec editor:
1. make sure to be on a private site with some video in the media library
2. set the "Use Block Editor" to off in the site settings
3. create a new post (it should load Aztec)
4. tap on the media insertion button on the bottom toolbar
5. tap on the media library selector (W)
6. observe the thumbnails in the grade are shown (fixed above)
7. now tap on any video to insert
8. observe the video gets inserted and the thumbnail in the editor gets rendered properly.

ONE thing to note:
-- on the emulator, when proxied, it happened to me that the MEdiaSettingsActivity would fail to render the thumbnail in a private site with Auth failure from Volley, I debugged step by step and saw the auth headers effectively being sent, so I did the following:
1. debugging step by step, get the  mMedia.getThumbnailUrl(); see method ` loadImage()` in MediaSettingsActivity.
2. copied and opened the URL on an Incognito window, and observed it effectively answered with 403.
3. then pasted it on a new tab where I'm signed in to wp.com (also note I'm the owner of the private site I'm testing)
4. now it opens and renders well on the desktop browser
5. go back to Android Studio and let the application continue execution
6. observe the server now doesn't return 403, and the image gets rendered properly.

So, just noting this here for testing notes as you may run into the same problem (I tend to think this is emulator/proxy related, given the auth headers are definitely being set properly by the ImageManager in `GlideRequestFactory`.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@mzorz Just to avoid any confusion, the reason I didn't merge this PR when I approved is [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/12178/files#diff-37250c687b4cff923f7fd24da2794c3bR70-R72). I merged https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/30 so it should be ready for a new bintray version. If you want to merge this and handle that separately, I am fine with that as well. I don't think referencing the library directly will matter, hopefully I am not mistaken about that. 🤞

**Comment by mzorz** [comment]
> Just to avoid any confusion, the reason I didn't merge this PR when I approved is this comment. I merged wordpress-mobile/WordPress-Utils-Android#30 so it should be ready for a new bintray version. If you want to merge this and handle that separately, I am fine with that as well. I don't think referencing the library directly will matter, hopefully I am not mistaken about that. 🤞

Oh thanks for the clarification! I'll push a new version there and make the version count. I think the AztecVideoLoader needs to reference the new version as well. Will push the new version, update this PR, so we can merge after that.  👍

**Comment by oguzkocer** [comment]
Sounds good - if Github allows, please feel free to merge once you make the version change 👍

**Comment by mzorz** [comment]
Bumped the utils version in b100d6c, tested and works 👍 
Also forgot to setup proper injection for AztecVideoLoader, did that in 2ec2e83, should be good 👍  will  let some time pass in case you want to double check @oguzkocer (given this other part wasn't expected and I forgot to add before) otherwise I'll merge after some time 🙇 thank you once more!

**Comment by oguzkocer** [comment]
@mzorz Just typing up a response to recent changes - it's taking a few minutes though.

**Comment by mzorz** [comment]
Thanks a lot for these insights! I get what you mean, or at least the gist of it for sure :smile: 
Thanks once more!

**Pull request merged**
