### PR TITLE
Feature/site media shared element

### PR DESCRIPTION
**Pull request by nbradbury**
Adds a "shared element" transition to the media browser > media settings flow for devices running Lollipop or later. Note that this uses the standard shared element pattern designed by Google. We may be able to tweak it if any changes are needed, but that will likely require quite a bit of work/research.

[Video demo](https://cloudup.com/cPpWmaLUBty)

### CODE REVIEW

**Comment by folletto** [comment]
It's 👍  for me. Great idea. :)

**Comment by nbradbury** [comment]
> It's 👍 for me. Great idea. :)

That was quick :) Credit goes to @iamthomasbishop for the idea.

**Comment by daniloercoli** [comment]
So cool!

**Comment by daniloercoli** [comment]
This PR works great. :shipit: 

Side Note not related to this PR, but we may ant to fix it: I noticed that tapping the device home button doesn't save changes made to media settings. This could result in unexpected behavior, since the System could kill our activity/app. Maybe saving on tapping home, like we're doing on back pressed?

**Pull request merged**
