### PR TITLE
Add tracking for stats inconsistency

### PR DESCRIPTION
**Pull request by planarvoid**
Helps with #11412 

With the previous attempts I've added logs to find out what's happening when the user gets inconsistent stats. I'm now suspicious of some API caching so I'm adding tracking for the cases when the app is showing old data to the user. The threshold is 2 days so let's see if we get any relevant information out of this. I've added a field for checking the age of visible stats so we can filter out users who haven't been online in a while. 

To test:
- Go to Stats/Days tab
- Check that the overview (first) block is showing you the correct dates and nothing is crashing there
- The tracked error should not be visible in the logs - filter out `stats_overview_error`

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by designsimply** [comment]
Thank you for working on this! Apologies for the possibly obvious answer, but where exactly can I look up the stats for this? If I have a user reporting the problem in the future, what's the best way to figure out if they are included in this error logging?

**Comment by renanferrari** [comment]
@designsimply I'm not sure if that's what you mean, but this is still going to be logged on Tracks under the `wpandroid_stats_overview_error` event, and if a user report this problem in the future and they're on version 16.4 or later, it's probably going to show up on their application log. Let me know if this actually answers your question or if I've misunderstood what you've asked.

**Review by renanferrari — APPROVED** [review]
Thanks for the changes! I've tested the app with the provided steps and also ran the unit tests that have been introduced, and everything seems to be working as expected. Code also looks good. 

LGTM :shipit:

**Comment by designsimply** [comment]
That's exactly what I meant. Thank you!

**Pull request merged**
