### PR TITLE
Issue/8319 copy comment url phase 1

### LINKED ISSUE #8319: Comments: Copy the URL to a specific comment
Let's make it possible to copy the URL for a comment in the app. When the URL is copied, a toast message saying something like `URL copied to clipboard` can confirm the action.

A description of locations for copying the comment URL is below. A few outstanding questions:

* Should we include Notifications List and Comments List or only the Notifications Detail and Comments Detail?
* If Notifications List is included, where should be tap target be (there is no timestamp label)?
* If Comments List is included, how should we handle the existing multi-select mode activated with a long press?

**Notifications List**
1. Go to Notifications tab.
2. Long-press comment in notifications list.
3. Notice message that comment URL is copied.

**Notifications Comments List**
1. Go to Notifications tab.
2. Tap post in notifications list.
3. Tap Comments icon in post footer.
4. Long-press timestamp label for comment in comments list.
5. Notice message that comment URL is copied.

**Notifications Detail**
1. Go to Notifications tab.
2. Tap comment in notifications list.
3. Long-press timestamp label for comment.
4. Notice message that comment URL is copied.

**Comments List**
1. Go to My Site tab.
2. Tap Comments item under Publish section.
3. Long-press timestamp label for comment in list.
4. Notice message that comment URL is copied.

**Comments Detail**
1. Go to My Site tab.
2. Tap Comments item under Publish section.
3. Tap comment in comments list.
4. Long-press timestamp label on comment.
5. Notice message that comment URL is copied.

**Reader**
1. Go to Reader tab.
2. Tap Comments icon in post footer.
3. Long-press timestamp label for comment in comments list.
4. Notice message that comment URL is copied.

Internal ref: p4a5px-2gF-p2

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #8319 

### **Description**
This PR introduces the ability for a user to copy the direct url of a comment to the clipboard - option number 2 from the issue ticket, including the "share" action on the snackbar. 

Note: This PR uses a FluxC commit hash and is does not include release notes yet

### **Action Bar Changes**
- More option added to action bar
- Edit & trash options have been relocated to the More menu
more_only

 
### **More Menu Notes**
- Edit and trash/delete functionality remain the same as when they were located on the action bar
- Copy link address option will not be available if the comment is in the Trashed or Spam status

popmenu
more-when-trashed

### **Implementation Details**

- Updated comment_action_footer.xml
    - Removed the edit and trash buttons
    - Added more button
    - Added new vector drawable for the More icon
- Added a new menu resource called menu_comment_more.xml
- CommentDetailFragment
    - Added an onClickListener for the More button click to show the More popup menu
    - Moved logic to handle the edit and trash/delete buttons to the more menu handler
    - Prepare and show the more menu based upon comment status
    - Added logic to copy the url text to the clipboard
    - Added logic to show the snackbar and handle the Share action
- Added string resources as needed

### **Testing Instructions**

**Precursor**
    - A WP.com site that has multiple comments
    - A self-hosted site that has multiple comments. 
    
**Test More/Copy Link functionality (repeat below for each WP.com site and self-hosted site)**

- Log into WPAndroid
- Navigate to the site that has comments
- Tap Comments on the My Site tab to navigate to the comment list
- Select a comment from the comment list to open the comment detail view
- Tap the More button from the action bar to open the more menu
- Tap Copy link address 
    - The link has been copied to your clipboard. 
    - Scenario 1: Open an app in which you would type in text and use the paste function to copy the link address from the clipboard
    - Scenario 2: Tap Share from the snackbar and choose an app to share the copied link with

**Test Delete/Trash function (regression)**

- Log into WPAndroid
- Navigate to the site that has comments
- Tap Comments on the My Site tab to navigate to the comment list
- Select a comment from the comment list to open the comment detail view
- Tap the More button from the action bar to open the more menu
- Tap Trash
- The comment detail view closes and the user is redirected to the All comments list
- Navigate to the Trashed list using the drop down filter
- Tap on the comment you just trashed to open the comment detail view
- Tap on the More button 
    - The trash feature has been replaced with delete
    - The copy link address option is no longer visible

**PR submission checklist:**

- [X ] I have considered adding unit tests where possible.
- [X ] I have considered adding accessibility improvements for my changes.
- [X ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
> Only thing I noticed is that when I tried to paste my link, nothing was pasted. 

@osullivanchris - I have not experienced this. Would you be open for a 5 minute zoom so you can share your experience with me.

**Comment by osullivanchris** [comment]
@zwarm yep sure thing. I'm free for the next 90 minutes, ping me on slack when you want to chat

**Comment by zwarm** [comment]
> The only issue I noticed is that the popup is leaking on configuration change:

@malinajirka - So after quite a few hours of researching, this issue appears to be common across popupmenu implementations in general - across our app and across Google default apps (you can trigger it using the Google calculator app and the logcat matches our leak).

Requesting a `poupmenu.dismiss()` in `onPause()`, `onStop()`, `onDestroyView()` or `onDestroy()` are all ineffective. Setting the menu to null is ineffective, as is removing the onClick listener from the anchor widget and setting that anchor to null. It looks like there are some private to the `androidx.appcompat.widget.PopupMenu` class that may be the cause of the leak. There is an internal `MenuBuilder` on which a callback is registered. We can discuss later.

**Comment by zwarm** [comment]
> It seems you've unintentionally committed Leakcanary as a dependency.  

Good catch. Thanks.

**Pull request merged**
