### PR TITLE
Revisiting Learn More preference

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #3678, #3677, #3638, #3705.

cc @mattmiklic

Edit: Much of the work was actually done on the web page itself. Content was added [here](https://en.support.wordpress.com/settings/discussion-settings/#default-article-settings) that the mobile client uses for the dialog.

### CODE REVIEW

**Comment by nbradbury** [comment]
I'm seeing some weird behavior with this on my Nexus 6P:

* After I tap "Learn More" I see a dialog that's only a little taller than the process bar it contains
* Once the page loads, it scrolls down so I can't see the title or the first line

Demo video [here](https://cloudup.com/cCiMgm12qYg)

**Comment by tonyr59h** [comment]
> After I tap "Learn More" I see a dialog that's only a little taller than the process bar it contains

Oops! It's supposed to tightly enclose the progress indicator until the page loads. I had the window re-sizing done a little early. Fixed in f8402306be8f527a833292b00a2d6398e0fac747

**Comment by nbradbury** [comment]
> Oops! It's supposed to tightly enclose the progress indicator until the page loads.

That's an improvement but it still looks off to me. 
device-2016-02-15-184348

Is it possible to immediately show the dialog at its full size, with the progress bar centered in it?

PS: Feel free to file that as a new issue since it's really separate from what this PR is tackling.

**Comment by tonyr59h** [comment]
> Is it possible to immediately show the dialog at its full size, with the progress bar centered in it?

Yes, that won't be a problem. I like the mini progress bar as it doesn't block too much real-estate until there is content available, but since you can't edit while it's showing that's actually not helpful. cc @mattmiklic

**Comment by mattmiklic** [comment]
The changes to the page look great! That's a nice improvement.

> Is it possible to immediately show the dialog at its full size, with the progress bar centered in it?

I think this would be a good idea. I thought the box around the loading animation looked a little funny too, but thought it might be an Android pattern I just wasn't familiar with.

**Comment by tonyr59h** [comment]
Fixed in da1412bc66478f229a90620167056ef9bf49d5b7, definitely an improvement. Good eye @nbradbury!

**Comment by nbradbury** [comment]
That looks really good - nice improvement all around! :shipit:

**Pull request merged**
