### PR TITLE
Remove vector assets that have pngs

### PR DESCRIPTION
**Pull request by tonyr59h**
We can't have vector+PNG assets if we specifically expect a PNG to be used. I searched the `res` directory for `android:drawable[Left/Top/Right/Bottom]` and the only offender was `ic_dropdown_blue_light_24`. The vector asset of this drawable has been removed, the PNG's remain.

I was able to reproduce the original error on my Genymotion 4.1.1 emulator by deleting the PNG assets and running the app (crashed immediately). There's something fishy going on when both vectors and PNG's are available, but investigating seems like a bad use of time. This PR should eliminate the crash.

cc @mzorz 

To test:
* Launch the app on a device with API in the range of 4.1.1 - 4.4.4
* Reader tab uses the only changed asset so if it doesn't crash we're probably good
* People page is also a good place to test

### CODE REVIEW

**Comment by tonyr59h** [comment]
FWIW (not much!) these are all the resources targeted by `android:drawable[Left/Top/Right/Bottom]` attributes in `WordPress-Android`:

* ic_arrow_left_grey_16
* ic_location_on_grey_600
* ic_location_searching_black_40_32
* ic_tag_white_24
* ic_time_grey_darken_10_16
* stats_visitors_and_views_legend_background_primary/secondary
* media_image_placeholder
* ic_gallery_grid_selector
* ic_gallery_slideshow_selector
* ic_gallery_circles_selector
* ic_gallery_tiled_selector
* ic_gallery_squares_selector
* ic_notice_48

I've checked them all out to verify that they don't use vector assets, but feel free to double check 😉

**Comment by tonyr59h** [comment]
Don't merge this one yet! Going to keep the vector asset since it's used in other places besides layout files. I'll do a rename of the PNG's, per @theck13's suggestion, and update the layout files to point to the PNG's.

**Comment by tonyr59h** [comment]
Okay, this one is good to go now 👍

**Comment by mzorz** [comment]
:shipit:

**Pull request merged**
