### PR TITLE
Issue/update themes list

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update list view in ***Themes*** screen.  The placeholder and preview images were made full-width.  The ellipsis icons were made to match the theme name text color.  See the screenshots below for illustration.

themes

### Test
0. Use device with slow network connection.
1. Go to ***Sites*** tab.
2. Tap ***Themes*** under ***Look and Feel*** section.
3. Notice placeholder image is full-width in list view.
4. Wait for preview image to load.
5. Notice preview image is full-width in list view.
6. Wait for active theme to be selected.
7. Notice ellipsis icon is white for active theme.
8. Notice ellipsis icon is black for inactive themes.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by 0nko** [comment]
Is this PR still waiting for a design review or can we merge it?

**Comment by theck13** [comment]
It's still waiting for design review.

**Comment by iamthomasbishop** [comment]
Looking great, thanks for taking care of this! :shipit:

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
