### PR TITLE
Issue/13326 threat details & history design review

### PR DESCRIPTION
**Pull request by ashiagr**
Parent #13326

Threat Details & History Screens Design Review PR

Threat Details

Current Threat | Fixed Threat | Ignored Threat | Dark Mode
------------|-------------|-------------|------------
light mode |  fixed | ignored|  dark_mode

History

Loading | Fixed | Ignored | Error | Dark Mode
---------|------|---------|------|------------
history_loading | history_fixed | history_ignored | history_something_went_wrong |history_dark_mode

**Testing**

Prerequisite:

- Make sure both Scan feature flag and MySiteImprovements flag are set to on in the App settings.
- You have access to WP.com account with a site having scan capability and multiple threats (e.g. http://do.wpmt.co/jp-complete).

PS -  Jetpack Threat Tester (Internal ref: pbuNQi-Kb) can be used to re-add threats once they're fixed. 

Merge Instructions:

1. Make sure PR #13949 is merged to develop
2. Remove "Not Ready for Merge" label
3. Merge this PR

**Notes**

- "DiffViewer" for a core file threat is not implemented.
- Tweaks for tablet - not included in this MVP release. 
- History screen does not include date headers.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — APPROVED** [review]
Looking good @ashiagr 👍  from me

**Comment by osullivanchris** [comment]
👋  Hey thanks again for the PR. Nearly all the UI issues are covered in #13949 so I don't have much to add here.

The only one specific to this PR is the blocks of code. I don't think I provided you with an Android mock of that so its my fault. But I'm thinking we should use system colours for the greys so they automatically work in dark mode as well. And then I can provide red colour values for light mode, and another set of red colour values for dark mode. Does that work for you?

The only reason I am not sending them up-front is its sometimes hard to know what set of colours we are using in the code as it doesn't always match what I have in design tools. Lets sync up on it tomorrow.

**Comment by ashiagr** [comment]
👋 Chris,

Summarising our discussion on Slack, we applied these colors based on color suggestions in https://github.com/wordpress-mobile/WordPress-Android/pull/13949#issuecomment-773258496 + utilising some of the existing colors with emphasis values for the gray shades.

new_colors

**Comment by osullivanchris** [comment]
> Summarising our discussion on Slack, we applied these colors based on color suggestions in #13949 (comment) + utilising some of the existing colors with emphasis values for the gray shades.

Looks good, thanks @ashiagr !

**Pull request merged**
