### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by kwonye**
finally Google... (kidding)

Needs review: @maxme

### CODE REVIEW

**Comment by maxme** [comment]
We should update the wrapper to gradle 2.9 at the same time and remove the proguard workaround for samsung (and the proguard check in the release check script).

**Comment by maxme** [comment]
Also lint fails because of a new lint check `MissingPermission`

**Comment by maxme** [comment]
> Lint found 1 errors and 1140 warnings
> :WordPress:lint FAILED

Travis is failing due to 1 lint error. The bad news is I can't repro that locally (no error at all). I even tried to build and lint the project on a linux box, no error on lint...

**Comment by maxme** [comment]
Found the lint error with [this](https://github.com/maxme/WordPress-Android/commit/816abd8899599c516c035f2425959f2715b01c90) trick.

> The SDK platform-tools version ((21)) is too old  to check APIs compiled with API 23; please update

**Comment by kwonye** [comment]
Thanks for the investigating @maxme! I'll look into all of them further.

**Comment by kwonye** [comment]
All the changes you made seem to work, no? (Thanks for that!)

I believe this is ready to merge.

**Pull request merged**
