### PR TITLE
Issue/10640 material stats

### LINKED ISSUE #10640: Implement Material theme on Stats screen
We should switch widgets used at Stats screen to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

A big part of the app with a separate style file, which we should get rid of.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10640

This PR moves Stats to Material Theme and adds Dark Theme support (Widgets will follow).

Stats are pretty recent, so there are very little code changes, mostly visual stuff.

Stats consists of a bunch of similar-looking components, so I tried to present most of them in the screenshots. Tons of small changes here, so I recommend doing a design review with installed APK.

comparison_stats

To test:
- Using a site with some amount of traffic, navigate to Stats screen and confirm the visual and functional integrity of each element in both Light and Dark themes. I suggest enabling all the Insights from the insights management screen.
- On a self-hosted site without Jetpack, navigate to Stats screen, and confirm that Jetpack install flow looks as expected.
The theme can be changed from App Settings.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by mattmiklic** [comment]
The Install Jetpack screen is mostly good, but we don't want the white inner shapes inside the Jetpack logo to turn black in dark mode, they should remain white.

**Comment by mattmiklic** [comment]
On the "Tags & Categories" and "Authors" panels (and any other that use horizontal bars to show differences in numbers), we're currently using Gray 10 in both modes for the bar color. In Dark Mode, let's change it to Gray 60.

**Comment by mattmiklic** [comment]
For the icons in the "Posts and Pages", "Tags and Categories", Likes, Comments, and any other icons used in lists -- let's make those the medium emphasis on surface color, as we've done with icons on other screens (I believe).

**Comment by mattmiklic** [comment]
Here are color suggestions for the bar charts, including the bars and the gridlines behind them.

Screen Shot 2020-02-14 at 7 26 23 PM

**Comment by khaykov** [comment]
@mattmiklic Thanks for the feedback! I updated all the colors 👍 
comparison_st

And Jetpack icon. The original icon is transparent in the center so I had to place the white shape behind it.

Screenshot_1581836306

**Comment by mattmiklic** [comment]
This is all looking really good now! Just one small thing remaining; the gridlines behind the bar chart should switch to Gray 80 in dark mode.

I'm working on an updated illustration for Manage Your Stats that will work better in dark mode; I'll provide that today.

**Comment by mattmiklic** [comment]
I just noticed the color of the Jetpack logo is off -- can you update that to #00BE28?

**Comment by mattmiklic** [comment]
Here are new images to replace `insights_management_feature_image.png` and `insights_management_feature_image_tab`, as well as new dark mode versions of both.

insights_management_feature_image png
insights_management_feature_image_tab
insights_management_feature_image_tab_dark
insights_management_feature_image_dark png

**Comment by khaykov** [comment]
@develric Thanks for the review! I fixed the chevron color :)

Regarding New feature announcement image, can you try uninstalling the app and installing it again? I got a similar issue that got fixed by a reinstall, and I can only blame it on some sort of resource caching when building apk.

Regarding the selected column color - stats went through a dedicated design tweaking, so I assume it's ok (we can always fix it latter if folks complain) :)

**Comment by mattmiklic** [comment]
@khaykov it just occurred to me that I needed to provide you with hdpi–xxxhdpi assets for the insights promo illustrations, the ones I provided were only in mdpi. Here's a zip with all of the sizes.

[insights-promo-image.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4232570/insights-promo-image.zip)

**Pull request merged**
