### PR TITLE
Stats revamp v2 views and visitros graph on detail screen

### PR DESCRIPTION
**Pull request by ravishanker**
This PR updates Views and Visitors card on detail screen to reflect date selection

Fixes an outstanding item from 16684 

Review/ Merge Instructions

1. [Review corresponding FluxC PR.](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2447)
2. Make sure the corresponding FluxC PR is merged to trunk.
3. Replace FluxC trunk-<hash> in build.gradle.
4. Remove Not Ready for Merge label.
5. Merge the PR.

To test:

Setup:
1. Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
2. Select Debug Settings
3. Find StatsRevampV2FeatureConfig under Features in development enable it and restart app
4. Launch / Re-Launch app
5. Go to Stats either using quick links or menu
6. Switch to Insights tab if necessary
7. Make sure Views & Visitors card is visible on Insights tab. If not present then add it through stats management using either [+ add new stats card ] at the bottom or clicking ⚙️ icon at the top right hand corner.

Test:
- Click on View More on Views card.
- Ensure it takes to respective detail screen
- Ensure a date selector is visible at the top 
- Use < and > arrows on date selectors to move back and forth
- Ensure the cards on the screen reflect the date range selected

NOTE: 
- It may go into loading when navigated to detail screen due to caching 
- the date selector has a  week range as per Week tab

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Updated existing tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by irfano** [comment]
Why did we use a different use case for the detail card? Can't we use `UseCaseMode.BLOCK_DETAIL`

With this new use case, we lost the top part of the card.
|before|after|
|-|-|
|||

**Comment by ravishanker** [comment]
> Why did we use a different use case for the detail card? Can't we use `UseCaseMode.BLOCK_DETAIL`

That UseCaseMode mode doesn't help here, it's only being used for style updates like hiding view more.  The challenge here is that views and visitors graph is using **days** granularity and referrers and country cards are using **weeks** granularity.  Date picker is set to weeks as well.  When granularity is weeks, endpoint is returning only count for each week not values for days that is required for the graph.  Hence, the difficulty in having two different granularity card types on one screen unlike existing Day, Week etc tabs where all of them are of same granularity.  Please let me know if it is not clear.

> With this new use case, we lost the top part of the card.

Sorry, top part is not lost because of new use case.  I've deleted too many lines while cleaning up by mistake.  I've put that back now.  Thanks for spotting it.

**Comment by irfano** [comment]
> That UseCaseMode mode doesn't help here, it's only being used for style updates like hiding view more. The challenge here is that views and visitors graph is using **days** granularity and referrers and country cards are using **weeks** granularity. Date picker is set to weeks as well. When granularity is weeks, endpoint is returning only count for each week not values for days that is required for the graph. Hence, the difficulty in having two different granularity card types on one screen unlike existing Day, Week etc tabs where all of them are of same granularity. Please let me know if it is not clear.

Oh, I see. I tried to fix that without adding a new view model while adding events, but I couldn't solve it. I left `wpandroid_stats_previous_date_tapped` and `wpandroid_stats_next_date_tapped`. After total detail screens are done, I'll add those events.

> Sorry, top part is not lost because of new use case. I've deleted too many lines while cleaning up by mistake. I've put that back now. Thanks for spotting it.

👍🏻

**Comment by ravishanker** [comment]
> Oh, I see. I tried to fix that without adding a new view model while adding events, but I couldn't solve it. I left `wpandroid_stats_previous_date_tapped` and `wpandroid_stats_next_date_tapped`. After total detail screens are done, I'll add those events.
> 
No need to add them, they already exist in SelectedDateProvider (L:116 and L:124)

**Review by irfano — APPROVED** [review]
Good job! LGTM! 👍🏻

**Comment by irfano** [comment]
> No need to add them, they already exist in SelectedDateProvider (L:116 and L:124)

Sorry, I gave missing information. `wpandroid_stats_previous_date_tapped` is being tracked, but its property (`granularity`) was working wrong on some screens. I'll check it again.

**Pull request merged**
