### PR TITLE
Remove unused key from configure and unused tooling scripts

### PR DESCRIPTION
**Pull request by wzieba**
## Description

This PR removes unused configure secret and unused scripts stored in the repository. Twin WooCommerce PR: https://github.com/woocommerce/woocommerce-android/pull/12955

## To Test:

Not really needed. These files were not referenced anywhere in the code.

### CODE REVIEW

**Comment by wzieba** [comment]
@AliSoftware can you double-check if these scripts are ok to remove? I don't see they're being referenced anywhere, some of them are also not working anymore for some time already.

I left `list_missing_translations` and `rename_apk_aab` as they're pretty newish. Do you think we should leave them? I'm especially thinking about `list_missing_translations`, but maybe this is something that our release tooling does on its own already.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AliSoftware** [comment]
> I left `list_missing_translations` and `rename_apk_aab` as they're pretty newish. Do you think we should leave them? I'm especially thinking about `list_missing_translations`, but maybe this is something that our release tooling does on its own already.

 - `rename_apk_aab` can be removed, as just like with WCAndroid, as it was mostly useful back when the download of the universal, signed APK from GPC to attach it to the GitHub release was manual, but [that's since been automated](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/release.rb#L460)
 - `list_missing_translations`: I'd expect this feature to be provided by a _fastlane_ lane indeed.
    - There's [`check_translation_coverage`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/release.rb#L375) which reports locales for which translations are below a certain expected % (defaults to 100% for the Mag16); but it doesn't report the list of string keys missing a translation though.
    - While iirc, `list_missing_translations` was designed to be run manually when one had the error during release about the Mag16 not all being translated at 100%, so one could explicitly generate and paste the list of keys for which we were missing translations in each locale, and paste that in the scenario P2 post.
    - This was before we migrated the scenarios to ReleaseV2 (e.g. see p8Qyks-8FN-p2, search for the script name in the instructions). In don't see similar instructions in the scenarios of ReleaseV2 anymore. So I guess this one is obsolete
    - Though I'm not sure what Release Managers are supposed to do nowadays if the CI job during release mention missing translations… though apparently [the check was disabled during `finalize_release` for now](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/release.rb#L294-L295), and even if we re-enable it, [`abort_on_violations` is `false`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/fastlane/lanes/release.rb#L379) so I guess we decided this wouldn't be a release blocker anymore (even for Mag16 for which we're supposed to guarantee 100% translation)?
 - `tools/install-app-bundle.sh`: This one I don't use but I remember some developers mentioning they sometimes did use it, especially to easily install and test APKs they download, e.g.  from Prototype Build PR comments or similar. Personally I'd recommend them to scan the QR code from their test device instead, but I seem to remember that some still preferred that 🤷‍♂️  So maybe check with the devs if they want to keep it?
 - `tools/remove-unused-strings.sh`: same, this one I think was created by devs, and while I personally never used it nor know much about it, could be worth checking with them if they still end up using it sometimes or whatnot?

**Comment by wzieba** [comment]
> rename_apk_aab can be removed, as just like with WCAndroid,

Right, sorry for missing this 🤦 .

hi @nbradbury 👋 Do you use any of the scripts removed by this PR?

**Comment by nbradbury** [comment]
> hi @nbradbury 👋 Do you use any of the scripts removed by this PR?

@wzieba Thanks for checking! I do not.

**Comment by wzieba** [comment]
Gotcha, thanks for the confirmation @nbradbury ! Merging this then (can I have approve @nbradbury or @AliSoftware ?)

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
