### PR TITLE
Issue/site creation button

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the ***OK*** button color and style on the site creation preview screen to follow the updated design described in https://github.com/wordpress-mobile/WordPress-Android/issues/9545 and https://github.com/wordpress-mobile/WordPress-Android/pull/9546.  See the screenshots below for illustration.

site_creation_preview_portrait

site_creation_preview_landscape

### Test
1. Go to ***Sites*** tab.
2. Tap ***Switch Site*** button in top card view.
3. Tap ***Add New Site*** button in top app bar.
4. Tap ***Create WordPress.com Site*** option in dialog.
5. Tap any segment on ***Create Site*** screen.
6. Tap ***Skip*** button in ***1 of 3*** screen.
7. Tap ***Skip*** button in ***2 of 3*** screen.
8. Enter text in ***Search Domains*** field.
9. Tap domain in list.
10. Tap ***Create Site*** button.
11. Notice ***OK*** button is pink.
12. Long-press ***OK*** button.
13. Notice shadow is not clipped.
14. Rotate device.
15. Notice ***OK*** button is pink.
16. Long-press ***OK*** button.
17. Notice shadow is not clipped.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @theck13! Both the code and the app looks good;). I've tested it on phone+tablet (Android 9 and 5). 🚢

**Comment by malinajirka** [comment]
@SylvesterWilmott I know this is not related to this PR, but I'll mentioned it here and we can create an issue if you think it's worth fixing.

I believe you've mentioned the issue on Slack, but I haven't found any GitHub ticket. The grey backround on both the content+bottom button seems inconsistent and looks a bit weird. Wdyt?

site-creation

**Comment by SylvesterWilmott** [comment]
@malinajirka Created an issue #9703

**Comment by SylvesterWilmott** [comment]
Looks good @theck13

**Pull request merged**
