### PR TITLE
[Home Page Picker] Enable the feature

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2727

## Description
Enables the new Home Page Picker for release

## To test:

*Note: An easy way to test the analytics is to debug the app and filter Logcat to look for the string `🔵 Tracked:`*

### Start the Home Page Picker screen

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
1. Verify that you see the Choose Design screen
1. In the console expect to see:
`🔵 Tracked: enhanced_site_creation_site_design_viewed`

### Create a site with the default design
1. Start the Home Page Picker 
1. Press **SKIP**
1. In the console expect to see:
`🔵 Tracked: enhanced_site_creation_site_design_skipped`
1. Search for and Choose a domain
1. Tap **Create Site**
1. Expect Your site to be created with the default design

### Create a site with a specific design
1. Start the Home Page Picker 
1. Select a design
1. Press **Choose**
1. In the console expect to see something like (where `alves` is your selected design):
`🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"alves"}`
1. Search for and Choose a domain
1. Tap **Create Site**
1. Expect Your site to be created with the selected design

### Error tracking
1. Turn your internet access off (e.g. with flight mode)
1. Start the Home Page Picker
1. In the console expect to see something like:
`🔵 Tracked: enhanced_site_creation_error_shown, Properties: {"error_context":"design","error_description":"Error fetching designs","error_type":"unknown"}`

### Preview Design
1. Start Home Page Picker
1. Select a design
1. Press the **Preview** button on the bottom toolbar
1. Verify that the selected design preview loads
1. Verify that the following events are tracked (where *alves* the design you selected)
```
🔵 Tracked: enhanced_site_creation_site_design_preview_viewed, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loading, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loaded, Properties: {"template":"alves"}
```

### Choose Design from Preview
1. Follow the *Preview Design* steps above
1. Press Choose
1. Search and select a domain
1. Select create site
1. Verify that the created site has the selected design
1. Verify that the following events are tracked (where *alves* the design you selected)
```
🔵 Tracked: enhanced_site_creation_site_design_preview_viewed, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loading, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loaded, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_selected, Properties: {"template":"alves"}
```

### Preview Error
1. Start Home Page Picker
1. Disable the internet connection (e.g. flight mode)
1. Select a design
1. Press the **Preview** button on the bottom toolbar
1. Verify that that you see the error screen below
1. Enable the network connection
1. Press **Retry**
1. Verify that the selected design preview loads
1. Verify that the following events are tracked (where *alves* the design you selected)
```
🔵 Tracked: enhanced_site_creation_site_design_preview_viewed, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_error_shown, Properties: {"error_context":"design","error_description":"Preview error","error_type":"internet_unavailable_error"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loading, Properties: {"template":"alves"}
🔵 Tracked: enhanced_site_creation_site_design_preview_loaded, Properties: {"template":"alves"}
```

## Screenshots

|Choose Design|Preview Design|
|---|---|
|<image src="https://user-images.githubusercontent.com/304044/98543857-c4164080-229b-11eb-9b18-7012cba2e55a.gif"/>|<image src="https://user-images.githubusercontent.com/304044/99296484-84c59200-284f-11eb-85a4-e4b9ef7b8c39.png"/>|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
I've retested all flows above, and everything is working as expected. I've also verified the events in both the console as well as the live view, and everything is emitted as expected. :tada:

There are a couple of issues I discovered:

#### Blank preview after site creation

After creating the site, I observed that sometimes the preview remains blank. I'm unsure why this is, but I have a hunch it happens when using non-WPCOM domains. I also observed this on WordPress-iOS, for a `.blog` domain, but have not seen this for `.com` domains in either app.



#### Unreadable (low-contrast) font in brice theme:

I observed that the brice theme has low-contrast font when opening the home page in the editor. I'm not sure if this is a known issue, and / or if this project is the place to address this. I also haven't tested this with other themes to see if the issue exists elsewhere as well:

**Comment by antonis** [comment]
Hey @mkevins 👋 
thank you for reviewing this 🙇 
 
> There are a couple of issues I discovered:
> 
> #### Blank preview after site creation
> After creating the site, I observed that sometimes the preview remains blank. I'm unsure why this is, but I have a hunch it happens when using non-WPCOM domains. I also observed this on WordPress-iOS, for a `.blog` domain, but have not seen this for `.com` domains in either app.
> 
> 
> 
> #### Unreadable (low-contrast) font in brice theme:
> I observed that the brice theme has low-contrast font when opening the home page in the editor. I'm not sure if this is a known issue, and / or if this project is the place to address this. I also haven't tested this with other themes to see if the issue exists elsewhere as well:
> 
> 

I'll try to investigate this on the mobile side. Since the same behaviour is [reproduced on iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/15303#issuecomment-729439367) too @enejb and @tug might have a better insight.

**Comment by mkevins** [comment]
It seems that the low-contrast text issue will be resolved by https://github.com/wordpress-mobile/gutenberg-mobile/pull/2703. I've confirmed this by editing the same page via the [test apk](https://83268-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-13279-build-83268.apk) in https://github.com/wordpress-mobile/WordPress-Android/pull/13279:



:tada:  - nice work Gerardo! :smiley:

**Comment by antonis** [comment]
Hey @mkevins 👋 
I fixed the wrong analytics issue with 816b63b435b6d33d33fd6ba35f50d84391dfd311
Thank you for catching this 👍

**Comment by mkevins** [comment]
> Hey @mkevins 
> I fixed the wrong analytics issue with [816b63b](https://github.com/wordpress-mobile/WordPress-Android/commit/816b63b435b6d33d33fd6ba35f50d84391dfd311)
> Thank you for catching this

Thanks for the fast response with a fix! :+1: 

I've tested w/ the latest changes, and the event is firing as expected now.

**Comment by antonis** [comment]
I updated the `gutenberg-mobile` ref (e6560aa83023cc951f85f4f9048bb25edbd13c15) and the **Unreadable (low-contrast) font in brice theme** issue is fixed.
Thank you @mkevins for tracing this down and @geriux for fixing it 🙇 

<image width="360" src="https://user-images.githubusercontent.com/304044/99821827-28b68280-2b5b-11eb-86e6-85a487809d3b.png"/>

**Comment by geriux** [comment]
Hey there 👋  this is looking great nice work! Not sure if its related to this PR but while testing I saw the emojis aren't showing up when I try to create a new page:

<kbd></kbd>

Tested it using the latest APK on a Redmi Note 8T Android OS 9

**Comment by antonis** [comment]
Hey @geriux 👋 

Thank you for taking the time to review this 👍  I really appreciate it 🙇 

> Not sure if its related to this PR but while testing I saw the emojis aren't showing up when I try to create a new page:

This is not part of this PR but It's a problem that should be solved 😄 
I wasn't able to reproduce the issue. I even tried [devices with really small screen size](https://user-images.githubusercontent.com/304044/99977978-08cacd00-2dae-11eb-97d3-0dc41407f3b2.png) unsuccessfully. My guess is that the specific devices has special fonts for emojis (I guess it won't be the only one) that need more than the available space. I applied a (blind) fix ea7a15703c038cd0311c2a6f1f74244f69d02217 that allows autosizing of text for the emoji. If/when you have the time please check if this solves the issue with the latest apk.

**Comment by geriux** [comment]
> I wasn't able to reproduce the issue. I even tried [devices with really small screen size](https://user-images.githubusercontent.com/304044/99977978-08cacd00-2dae-11eb-97d3-0dc41407f3b2.png) unsuccessfully. My guess is that the specific devices has special fonts for emojis (I guess it won't be the only one) that need more than the available space. I applied a (blind) fix [ea7a157](https://github.com/wordpress-mobile/WordPress-Android/commit/ea7a15703c038cd0311c2a6f1f74244f69d02217) that allows autosizing of text for the emoji. If/when you have the time please check if this solves the issue with the latest apk.

Thanks for the fix @antonis ! Now they're showing up correctly 🎉

<kbd></kbd>

**Comment by antonis** [comment]
Hello @kyleaparker 👋 ,
thank you for [the review and the detailed feedback](https://github.com/wordpress-mobile/WordPress-Android/pull/13424#issuecomment-731880438) 🙏 

> * On the domains screen, remove the ellipsis from the title "Choose a domain ..." (see screenshot below)

This was was due to English resources (non US locale) still having the old wording (`Choose a domain name for your site`). I updated this for EN_GB/CA/AU and should be ok in the latest build.

> * The spacing of the back icon, title, and sub-text is inconsistent between screens.

Aligned with the *Choose a design* in the latest build

> * On a slow connection the homepage images load in one by one. Do we have a skeleton loading state we can use to fade the images in once they're available? I think this would help the loading state feel a bit smoother.

I'll align with @chipsnyder response on this. At this point we have a loading skeleton showing only one thumb while the api call is performed. After that placeholder images are shown while each thumbnail is generating/downloading.

> * I'd mentioned this in a previous PR but I think it would be useful to add the Skip option to the domains screen

A separate issue has been created to investigate this further https://github.com/wordpress-mobile/gutenberg-mobile/issues/2828

> * I think we should change the wording of the sub-text on the _Choose a Design_ screen from "Pick your favorite homepage layout. You can customize or change it later." to "Pick your favorite homepage layout. You can edit and customize it later." At least until we know which approach we are going to take on switching homepage layouts. cc @iamthomasbishop I'd like to hear your thoughts on changing the wording here.

Changed the wording according to the suggestion in the latest build

**Comment by kyleaparker** [comment]
Thanks for the reply @antonis, all sounds good to me 👍

**Review by Tug — APPROVED** [review]
:shipit:

**Pull request merged**
