### PR TITLE
Refresh BP card when date changes

### PR DESCRIPTION
**Pull request by khaykov**
This PR fixes and issue where Blogging Prompt card is not updated after Day changes and app is not restarted.

Gist of the problem is that to update the card we setup flow and keep continuously collecting from it. Problem is that the flow is setup only once, using set date, and even if we refresh the data, or the day changes the flow still collects from previous day.

As a workaround I collect all the prompts, and filter them in the flow. This way we always get fresh prompt to display.

To test:
- Launch JP app and confirm that BP card is visible.
- Answer prompt and confirm that the card updates.
- While the app is open, navigate to device settings and change clock to the next day.
- Return to the app, and confirm that dashboard is refreshing, and different prompt is visible.

## Regression Notes
1. Potential unintended areas of impact
- Potential unexpected issue with prompts.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
Updated existing tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@spencertransier (or @AliSoftware ?) I wonder if we still can get this into release as a beta fix?

cc @develric

**Comment by AliSoftware** [comment]
> @spencertransier (or @AliSoftware ?) I wonder if we still can get this into release as a beta fix?

Technically speaking, I'll do a new beta on Wednesday to land the latest translations anyway.

That being said, I'm not a fan of landing beta fixes in the release branch after the first week of the beta testing has passed, because that means this fix will have very little (one would even say not enough) time to get beta tested all over again (to ensure this fix doesn't introduce unintended side effects elsewhere or regressions) by beta testers before the final build.

So if this is not really a hard _blocker_ for users maybe we should consider targeting `trunk` and include that fix only on the next code freeze next Monday instead? (Cc @thehenrybyrd  for insights)

_(Full transparency: this intent to reduce betafixes — especially past 1st week unless really justified — is not specific to your PR, but something we've been trying to lean towards more in general lately; we haven't made any official comm about it yet, but P2 likely to come soon-ish)_

**Comment by khaykov** [comment]
@AliSoftware Got it! After some discussion we decided that the issue is not that super critical, and we can wait until next release.

**Review by RenanLukas — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
