### PR TITLE
Integrate gutenberg-mobile release 1.48.1

### PR DESCRIPTION
**Pull request by fluiddot**
## Description
This PR incorporates the 1.48.1 release of gutenberg-mobile.  
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3237

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
LGTM 🚢 All expected behavior verified with smoke testing. Awaiting GB-mobile/GB CI confirmation before merge.

**Comment by jd-alexander** [comment]
@fluiddot I see that the release notes changes were made in the GB PRs. I was wondering if the page fetching changes warranted any such changes here? Checking since the `release notes` checkmark in the PR was not checked.

I also remember seeing discussions about this change to release notes so late in the process as well, so this might be necessary at this point. Let me know what you think.

**Comment by fluiddot** [comment]
> @fluiddot I see that the release notes changes were made in the GB PRs. I was wondering if the page fetching changes warranted any such changes here? Checking since the `release notes` checkmark in the PR was not checked.

Yeah, I made changes in the release notes of GB because I forgot to add the hotfix I did in `1.47.1`. However that was for `WPAndroid - 16.8` so as this will be merged to `16.9`, I think it's ok to leave it as it is.

Regarding the checkmark, I'm going to check it now 👍 .

> I also remember seeing discussions about this change to release notes so late in the process as well, so this might be necessary at this point. Let me know what you think.

Yeah, as far as I know the release notes can't changed in this PR.

**Comment by fluiddot** [comment]
I've just updated the Gutenberg reference, now it points to the `v1.48.1` tag so it's ready to be merged.

**Comment by jd-alexander** [comment]
> I've just updated the Gutenberg reference, now it points to the `v1.48.1` tag so it's ready to be merged.

Thanks! Merging once CI passes.

**Review by jd-alexander — APPROVED** [review]
LGTM 🚢

**Pull request merged**
