### PR TITLE
Disables saving react root view from parent

### LINKED ISSUE #9685: Crash: android.os.TransactionTooLargeException
This one started in 11.8 and has been becoming more prominent in 12.0 and 12.1. 
It's currently the most common crash in Fabric.

Unluckily, the crash logs doesn't say much about where it occurs, but Fabric suggests that it is often seen when transferring bitmaps between Activities, or when saving a large amount of state between Activity configuration changes.

We had other occurrences of it in the past: https://github.com/wordpress-mobile/WordPress-Android/issues/5456.

Also, this thread https://github.com/facebook/react-native/issues/19458 suggests that it may be related to React-Native. The trend we see in Fabric (started in 11.8, growth a bit in 11.9, growth a lot in 12.0 and 12.1) seems to be compatible with mobile Gutenberg deployment in the app.

```
android.os.BinderProxy.transactNative (BinderProxy.java)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:6635)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)
```

5c93a36df8b88c2963f28894-fabric

### PR DESCRIPTION
**Pull request by antonis**
Partially/Fixes #9685

~~⚠️ **Based on https://github.com/wordpress-mobile/WordPress-Android/pull/20042 due to the issue discussed in p1706191625075559/1705569067.295549-slack-C6UJ0KRKQ**~~

*Related PRs:*
**Gutenberg-mobile PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/6575
**Gutenberg PR:** https://github.com/WordPress/gutenberg/pull/58266

## Description
This PR attempts to resolve the `TransactionTooLargeException` occurring due to the large view data on large post (internal ref: p9ugOq-4my-p2#comment-7997) by disabling saving the react native view hierarchy.

The crash is reproduced in big posts that result in a big `Bundle` due to the large `android:viewHierarchyState` and `androidx.lifecycle.BundlableSavedStateRegistry.key`. An example crash stack trace is the following:

```
RuntimeException
android.os.TransactionTooLargeException: data parcel size 842728 bytes
Bundle stats:
  android:viewHierarchyState [size=1536]
    android:views [size=1488]
  stateKeyEditorSessionData [size=5380]
  SITE [size=4728]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=829500]
    android:support:activity-result [size=3236]
      KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=2712]
    android:support:fragments [size=825888]
      fragment_431b0c7b-a639-4ecc-b449-97c52282a440 [size=811848]
        viewState [size=809228]
          0xf [size=1472]
          0xcb [size=1472]
          0xd9 [size=1472]...
```

The fix applied prevents the [EditPostActivity.onSaveInstanceState method](https://github.com/wordpress-mobile/WordPress-Android/blob/e55ce76c7a2052063ea4298b341811f769815f51/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1161) from saving [the view hierarchy below ReactRootView](https://github.com/WordPress/gutenberg/pull/58266/commits/1fa36f54b9895225cf0c878480cc9f08c42aa25b) resulting in a consistently small `Bundle` regardless of the post size.
For comparison [this is the Bundle of a post before](https://github.com/wordpress-mobile/WordPress-Android/files/14063061/before.txt) and [with the fix applied on this PR](https://github.com/wordpress-mobile/WordPress-Android/files/14063063/after.txt). The https://github.com/guardian/toolargetool can also be used to compare the Bundle sizes before and after (handy patch [toolargetool.patch](https://github.com/wordpress-mobile/WordPress-Android/files/14066321/toolargetool.patch))

-----

## To Test:
1. Open a really large post or create one (*)
2. Trigger the save state by adding a media to set the editor on the background (rotating might also work)
5. **Verify** that the app does not crash
6. **Sanity test** the editor for any introduced breakages

### (*)Steps to create a new post that reproduces the crash
The following steps reproduced the crash consistently on the latest version of the app on my Pixel 5 / Android 14 ([recording](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/b7cbf31d-f312-41aa-b07e-1d36c1b6af05)):
1. Open https://www.blindtextgenerator.com/lorem-ipsum and select the maximum available words (9999)
2. Press the copy to clipboard button
3. Head to the editor and paste the copied text 6-7 times
4. Try to add an image
5. **Notice** the crash 💥
 
https://github.com/wordpress-mobile/WordPress-Android/assets/304044/b7cbf31d-f312-41aa-b07e-1d36c1b6af05

## Notes
🧪 Though I've tested the fix for side effect I consider it safer to land on the next version (not the beta) to be tested extensively along the gutenberg-mobile library.
⚠️  Do not merge before https://github.com/wordpress-mobile/gutenberg-mobile/pull/6575 and https://github.com/WordPress/gutenberg/pull/58266 that this PR is based on.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Gutenberg editor

8. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

9. What automated tests I added (or what prevented me from doing so)

    - The introduced change is in Gutenberg

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by geriux** [comment]
Hey there @antonis 👋 I'm trying to reproduce the crash in the production app but I'm not able to with the testing devices I have, maybe I'm missing a step?

I opened a large post and changed the orientation a few times.

I tested with:
- Redmi Note 8T OS Android 11
- Samsung A23 5G OS Android 14

> * Open a really large post

I'm using a post that has 339 blocks, 8923 words, and 551131 characters, maybe it needs to be larger?

Let me know if I'm missing something, thank you!

**Comment by antonis** [comment]
Thank you for taking the time to have a look at this @geriux 🙇 

> I'm using a post that has 339 blocks, 8923 words, and 551131 characters, maybe it needs to be larger?

I have trouble reproducing this consistently myself. I'll construct some test data and steps that reproduce the crash more often and get back to you.

**Comment by antonis** [comment]
Hey @geriux 👋 
I managed to reproduce the crash consistently with the steps I've added on the description (similar to the steps on Artyom's [comment](https://github.com/wordpress-mobile/WordPress-Android/issues/9685#issuecomment-1843247594)).
Thank you for your help on this. Let me know if this helped 🙇

My understanding due to the frequency of this crash is that it should occur a lot simpler on some device setups or with the "right" content 🤷‍♂️

**Review by geriux — APPROVED** [review]
LGTM! Friendly reminder we need to release an alpha tag in Gutenberg Mobile once the other PRs have been merged. Let me know if I can help with that, thank you!

**Comment by antonis** [comment]
Thank you for reviewing this and the dependency PRs @geriux 🙇 

> Friendly reminder we need to release an alpha tag in Gutenberg Mobile once the other PRs have been merged. Let me know if I can help with that, thank you!

Thank you for the heads up! I'll start the merge process and ping you for help if needed 😅

**Pull request merged**
