### PR TITLE
Fix crash when contacting customer support within the editor

### LINKED ISSUE #6130: [Android] IllegalStateException: Method addObserver must be called on the main thread
Sentry Issue: [JETPACK-ANDROID-B86](https://a8c.sentry.io/issues/4418248063/?referrer=github_integration)

**Steps to reproduce it:**
1. Open a post/page.
2. Tap on the three dots button located at the top bar.
3. Tap on "Help & Support"
4. Tap on the "Contact support" button.
5. Observe the editor crashes.

```
IllegalStateException: Method addObserver must be called on the main thread
    at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
    at androidx.savedstate.SavedStateRegistryController.performAttach(SavedStateRegistryController.kt:48)
    at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.kt:63)
    at androidx.activity.ComponentDialog.onCreate(ComponentDialog.kt:74)
...
(25 additional frame(s) were not displayed)
```

### LINKED ISSUE #18804: IllegalStateException: Method addObserver must be called on the main thread
Sentry Issue: [JETPACK-ANDROID-7YX](https://a8c.sentry.io/issues/4263302554/?referrer=github_integration)

```
IllegalStateException: Method addObserver must be called on the main thread
    at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
    at androidx.savedstate.SavedStateRegistryController.performAttach(SavedStateRegistryController.kt:48)
    at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.kt:63)
    at androidx.activity.ComponentDialog.onCreate(ComponentDialog.kt:74)
...
(24 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by fluiddot**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/6130.
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/18804.

This PR addresses a crash related to contacting customer support from the Gutenberg editor. The custom support dialog needs to be called from the main thread. Since the calls from the editor happen on a different thread, we have to ensure that the call to display the customer support dialog is done in the main thread.

**To test:**

1. Open a post/page.
2. Tap on the three dots button located at the top bar.
3. Tap on "Help & Support"
4. Tap on the "Contact support" button.
5. Observe the customer support dialog is displayed and no crash is produced.

## Regression Notes
1. Potential unintended areas of impact
N/A

3. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

4. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by irfano — COMMENTED** [review]
I couldn't reproduce this on `trunk`, but the proposed change makes sense to me.

But I have a comment. `OnCustomerSupportOptionsListener` is a listener in the Gutenberg library. `OnCustomerSupportOptionsListener.onContactCustomerSupport()` is a UI event coming from Gutenberg. What do you think about changing the thread to the main thread from the Gutenberg side? In that way, we can be sure the thread will be safe in other places that use the listener.

**Comment by fluiddot** [comment]
> I couldn't reproduce this on `trunk`, but the proposed change makes sense to me.

@irfano That's interesting, I'm also using `trunk` and it's crashing.

https://github.com/wordpress-mobile/WordPress-Android/assets/14905380/242e8547-74c3-42fe-ac6c-f3ff6e6c85a9

> But I have a comment. `OnCustomerSupportOptionsListener` is a listener in the Gutenberg library. `OnCustomerSupportOptionsListener.onContactCustomerSupport()` is a UI event coming from Gutenberg. What do you think about changing the thread to the main thread from the Gutenberg side? In that way, we can be sure the thread will be safe in other places that use the listener.

Not sure I follow your suggestion. Do you mean to update the invocation to use the main thread?

```
public void onContactCustomerSupport() {
    if (getActivity() != null) {
        getActivity().runOnUiThread(() -> {
            mEditorFragmentListener.onContactCustomerSupport();
        });
    }
}
```
⬇️ 
```
public void onContactCustomerSupport() {
    new Handler(Looper.getMainLooper()).post(mEditorFragmentListener::onContactCustomerSupport);
}
```

I'd like to note that I relied on the UI thread approach following other listeners we have in the same file, e.g.:
https://github.com/wordpress-mobile/WordPress-Android/blob/75b8cf7de93001a5be6a3bb4fd55cb4f9c42b047/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L296-L303

On the other hand, `OnCustomerSupportOptionsListener` is a listener defined by Gutenberg ([reference](https://github.com/WordPress/gutenberg/blob/3c27042b0ec65125ef0bfc0dc36d2386d9545c10/packages/react-native-bridge/android/react-native-bridge/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java#L246-L249)) to provide the communication bridge between Gutenberg/React Native and the app. Hence, we can assume that it would be only used here.

If you meant to force Gutenberg to use the main thread, I don't think that would be possible because all events coming from Gutenberg/React Native originate in a separate thread (one created by React Native to run native modules). Therefore, not sure if that would be possible.

**Comment by irfano** [comment]
> @irfano That's interesting, I'm also using trunk and it's crashing.

We worked with @fluiddot and found out that some debug configs were different from the default values. That's why I couldn't reproduce it. After a clean installation, it's reproducible on my emulator too.

> If you meant to force Gutenberg to use the main thread, I don't think that would be possible because all events coming from Gutenberg/React Native originate in a separate thread (one created by React Native to run native modules). Therefore, not sure if that would be possible.

This was exactly what I meant and I didn't know how React Native handles communication. TIL, thank you!

**Review by irfano — APPROVED** [review]
The change LGTM and it has fixed the issue. 👍🏻 
I'm approving it now, and feel free to merge it after resolving the conflict.

**Pull request merged**
