### PR TITLE
Enable jetpack app features

### LINKED ISSUE #15915: Changes to Jetpack App
The goal of this task is to enable below features in the Jetpack app:

- [x] #15916 @ashiagr 
- [x] #15922 @ashiagr 
- [x] #15929 @ashiagr

### PR DESCRIPTION
**Pull request by ashiagr**
Closes #15915
Depends on https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/79

This is a feature branch PR to enable Jetpack app features. 

To test:
Please follow the testing steps covered in the linked sub-tasks. 

Merging Notes:

- Wait till referenced login lib PR removing Jetpack app sites filtering is merged to `trunk` (I will do this merging).
- Replace `wordPressLoginVersion` in build.gradle
- Remove `Not Ready for Merge` label and merge the PR.

## Regression Notes
1. Potential unintended areas of impact
Covered in individual sub-tasks.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Covered in individual sub-tasks.

3. What automated tests I added (or what prevented me from doing so)
Covered in individual sub-tasks.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by zwarm — APPROVED** [review]
👋  @ashiagr - I ❤️  the implementation by use of config flags .. it makes it easy to test + add/remove features in the future. Good catch on the shortcuts and feature announcements. And super kudos on the login pieces (very tricky)

I was able to test the following PRs in this feature build and everything worked as expected. I ran through JP and WP.

- #15920 
- #15928 
- #15930 

I'm going to approve, but not merge. I would love to give it one more go after #15944 has been merged in. 

Thanks for all the great work!!

**Comment by ashiagr** [comment]
Thanks so much @zwarm!

I've merged https://github.com/wordpress-mobile/WordPress-Android/pull/15944 and enabled normal login flow if no sites are found (and site creation is enabled) for `Jetpack` app instead of showing the "No Jetpack sites" screen.
Also, if signup is enabled, `Jetpack` app will now show a `PostSignupInterstitial` screen the first time it is shown similar to the `WordPress` app.

Note: Illustrations on `PostSignupInterstitial` screen and `MySite` empty screen are a bit off, I can either
i) hide them or 
ii) wait to replace them till we have the new ones. I'll create a task to track it.

EDIT: I've hidden `MySite` empty screen illustration for `Jetpack` app as it had `WordPress` app icon in 1f76982.

Ready for another look. 🙇‍♀️

**Review by zwarm — CHANGES_REQUESTED** [review]
@ashiagr - I stumbled across a few issues. 
- In Jetpack App: Upon first login to Jetpack app, the illustration in the view appears to be a WP one. 
Alt desc
2. In jetpack App: Tapping on Me -> log out doesn't log me out on the first attempt. I have to do it twice. See video.

https://user-images.githubusercontent.com/506707/154357529-41ba9390-d002-4984-a68f-36b40d050f73.mp4

**Comment by ashiagr** [comment]
👋 @zwarm,

I've replaced `PostSignupInterstitial` screen image (f2b93e4, df5022c): 

Light | Dark
------|-----
lt_device-2022-02-17-161734| dark_device-2022-02-17-160859

I've also merged login lib PR and updated the corresponding commit hash in this PR. - f552f2e

Regarding the logout (twice click) issue, it is difficult to find out a root cause in a limited time frame, but given that it can be reproduced only when there are no sites for the `Jetpack` app, and users are able to logout on the next attempt, we can find a fix as part of a separate PR. I've created an issue [here](https://github.com/wordpress-mobile/WordPress-Android/issues/15976) to track it. 

This is now ready for another look. 🙇‍♀️

**Review by zwarm — APPROVED** [review]
> I've replaced PostSignupInterstitial screen image

I now see the Jetpack illustration when logging in for the first time with an account that has no sites. 👍 

Thanks for creating that new PR for the double logout issue. I agree with you, this is definitely an edge case. 

I tested the login cases again and all is working as expected. 🙇  Nice job!

**Pull request merged**
