### PR TITLE
Issue/8700 update layouts large

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the ***Quick Start*** layouts on the ***Sites*** tab (https://github.com/wordpress-mobile/WordPress-Android/issues/8642) and full-screen dialog (https://github.com/wordpress-mobile/WordPress-Android/issues/8643) for large screens as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8700.  See the screenshots below for illustration.

v2_tablet_sites

v2_tablet_list

#### Note
There are a couple differences between the **_Design_** and **_Develop_** screenshots.  In the **_Sites_** screenshots, the row icons and text are vertically aligned with the start of the icons and text in the **_Switch Site_** and **_Next Steps_** views.  In the full-screen dialog screenshots, the toolbar color matches the updated designs shown in the [full-screen dialog changes](https://github.com/wordpress-mobile/WordPress-Android/pull/8720) and the **_Customize Your Site_** type is used since the **_Create Your Site_** task is not the **_Grow Your Audience_** type and to show a similar layout to the design mockup.

### Test
Both small and large screen devices should be used to test these changes to ensure the screenshots in the [full-screen dialog changes](https://github.com/wordpress-mobile/WordPress-Android/pull/8720) are shown for small screens and the screenshots above are shown for large screens.

0. Select site with Quick Start in progress.
1. Go to ***Sites*** tab.
2. Notice ***Next Steps*** view as shown above.
3. Tap **_Create Your Site_** or **_Grow Your Audience_** type.
4. Notice completed and uncompleted lists as shown above.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks really great, thanks!

Some small issues:

- Can the spacing between the quick start card and the site info card be 8dp?
- I don't know if this is feedback for this PR but can we leave a small delay between dismissing the quick start list and then scrolling to the correct point on the screen. In most cases the scroll is not shown
- Can we align the title "Next Steps" 16dp from the card edge?

**Comment by theck13** [comment]
> Can the spacing between the quick start card and the site info card be 8dp?

I updated the spacing in 4e7a17d.

> I don't know if this is feedback for this PR but can we leave a small delay between dismissing the quick start list and then scrolling to the correct point on the screen. In most cases the scroll is not shown

Since these changes don't modify the full-screen dialog dismissal and tasks tutorial, I think that would be better handled outside of this pull request, but we can do that.

**Comment by theck13** [comment]
I added the `[Status] Not Ready for Review` label since these changes are not compatible with the update skip list pull request (https://github.com/wordpress-mobile/WordPress-Android/pull/8813).  We'll merge that pull request first and I'll update these changes accordingly.

**Comment by theck13** [comment]
The update skip list pull request (#8813) has been merged and these changes have been updated accordingly.  This pull request is ready for review again.  The static interface hasn't changed, but the skip task animation has been improved.  See the animations below for illustration.

Real Time|Slow Motion
-|-
quick_start_tablet_fast|quick_start_tablet_slow

**Comment by SylvesterWilmott** [comment]
The skip task animation looks fantastic! Thanks @theck13 !

**Pull request merged**
