### PR TITLE
Fix timezone issue with traffic charts

### LINKED ISSUE #20412: Stats not loading Traffic by week in certain timezones
### Expected behavior

The Traffic should be filterable **By week**.

### Actual behavior

The Traffic tab doesn't load when I filter **By week**. This only breaks in UTC-positive timezones such as UTC+1.

### Steps to reproduce the behavior
1. Download Jetpack app v24.4 beta
2. Make sure the device is in a UTC-positive timezone such as UTC+1
3. Go to Stats > Traffic
4. Switch from **By day** to **By week**
5. Notice the chart doesn't load

### PR DESCRIPTION
**Pull request by irfano**
Fixes #20412 

This fixes blank page on TRAFFIC tab for some timezones.

This is the following PR of https://github.com/wordpress-mobile/WordPress-Android/pull/20387 since it did not resolve the issue.

> [!WARNING]
> Before Merging
> - [x] Merge https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2967
> - [x] Update FluxC version to FluxC's trunk

-----

## To Test:

1. Log in to JP.
2. Change the device timezone to an edge, -1.
3. Open the Stats Traffic tab.
4. Tap "By day" and change granularity to "By week".
5. Verify that the page is not blank.
6. Tap "By week" and change granularity to "By month".
7. Verify that the page loads successfully.
8. Repeat 3-7 with timezone set to -12 and +14.

-----

## Screenshots
| Before | After | 
| - | - | 
|  |  |

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - The issue was caused by a logic from 3rd party lib (FluxC). It's not possible to add automated tests in WPAndroid.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/278">24.4 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by aditi-bhatia — COMMENTED** [review]
Hi @irfano, I'm still seeing the loading issue with `weeks` and seeing the same issue on `months` as well. I tested using my current timezone (PST, so UTC-8): 

https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/5a985f07-95a8-4f81-ae45-94725cf36a89

**Comment by irfano** [comment]
Thank you for your test, @aditi-bhatia. I should have only disabled `applySiteTimezone` for lowGranularity calls. I have committed a fix. Could you please test it again?

**Review by aditi-bhatia — APPROVED** [review]
LGTM, fixes the issue 👍

**Comment by aditi-bhatia** [comment]
@irfano for this step: 

> Update FluxC version to FluxC's trunk

I'm not super familiar with FluxC, where would I find the current version number?

**Comment by irfano** [comment]
> I'm not super familiar with FluxC, where would I find the current version number?

I referenced FluxC's PR (d7e1963dce91145e1be9b881bc8c5a21a08fce9d) to test the FluxC change on this PR.
The "Update FluxC version" was a reminder not to merge this PR before updating the FluxC version. I intended to do it after your approval. Since FluxC PR has been merged into the `trunk`, I have now referenced `trunk` (314bc628b54d93ea267831d914f2b7055602c98b).

**Comment by irfano** [comment]
@oguzkocer, I merged this into the `release/24.4` branch as a beta fix. This also includes FluxC changes. The corresponding FluxC PR is included in the `release/2.70.1` branch of FluxC.

**Pull request merged**
