### PR TITLE
Fix #3185 startup optimization

### LINKED ISSUE #3185: Application startup optimization
We can move a some calls out off the UI thread during startup.

* [Mixpanel init](https://github.com/wordpress-mobile/WordPress-Android/blob/c77ae204af6fc8ad6c2abd9639fab44b89f07c9d/WordPress/src/main/java/org/wordpress/android/WordPress.java#L202-202)
* [JSON parsing](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/ABTestingUtils.java#L66)
* [Suggestion DB reset](https://github.com/wordpress-mobile/WordPress-Android/blob/c77ae204af6fc8ad6c2abd9639fab44b89f07c9d/WordPress/src/main/java/org/wordpress/android/WordPress.java#L235-235)

More details:
https://www.nimbledroid.com/play/org.wordpress.android?p=2DHAOt0aeYFLYL

### PR DESCRIPTION
**Pull request by maxme**
Fix #3185 startup optimization

Our calls to ProfilingUtils methods were outdated, we now have a better measurement of app launch with 5bc752b.

I also cherry-picked 5bc752b in `develop` to compare potential improvement. Results on my LG G3 while being signed in: around 2100ms startup time on `develop` and 1900ms with the current patch. Not a big difference, but we can't do much better.

Known "issue": `AnalyticsTracker.registerTracker()` is now called in it's own throwaway thread, so if we call `AnalyticsTracker.track()` before the registering end, events won't be sent. Not a big deal IMO, since we're not sending event before the first `Activity.onResume()` call. We could eventually store events in a waiting queue before tracker registrations in the future if we want to track stuff during app init.

### CODE REVIEW

**Comment by nbradbury** [comment]
I'm wondering if optimizing [initWpDb](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L177) would help as well? That routine calls [createAndVerifyWpDb](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L276), which looks pretty expensive.

**Comment by nbradbury** [comment]
Could [enableHttpResponseCache](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L654) be moved to `deferredInit`?

**Comment by maxme** [comment]
According to that profiler https://www.nimbledroid.com/my_apps/org.wordpress.android?p=2Q6zcfjjdQFVxq#Timeline - other calls in `App.onCreate` are pretty fast (the mixpanel instantiation was taking) - but that's not counting the db init with a lot of blog (test is only made with an empty non-logged app).

Would be great to measure that before touching the DB init.

**Comment by nbradbury** [comment]
> Would be great to measure that before touching the DB init.

My guess is that routine really does slow things down with a lot of blogs, and all it's doing is checking if any blog names or urls are null. A simple query could do that with a lot less overhead:

```
private boolean createAndVerifyWpDb() {
    try {
        wpDB = new WordPressDB(this);
        // verify account data - query will return 1 if any blog names or urls are null
        int result = SqlUtils.intForQuery(
                wpDB.getDatabase(),
                "SELECT 1 FROM accounts WHERE blogName IS NULL OR url IS NULL LIMIT 1",
                null);
        return (result != 1);
    } catch (RuntimeException e) {
        AppLog.e(T.DB, e);
        return false;
    }
}
```

**Comment by maxme** [comment]
Just tried this: https://gist.github.com/maxme/f1739011235a81883504

Measurements on 200+ blogs:
10ms with the old method
5ms with the new one

We should measure the whole `App.onCreate` method and send it somewhere (mixpanel?) once in a while (on app upgrade for instance) - so we can check if it's growing or have some kind of "alarm".

**Comment by nbradbury** [comment]
> We should measure the whole App.onCreate method and send it somewhere

I like that idea, especially if it can let us know which part of onCreate is performing slowly. 

For now, I'm good to merge this PR unless you want to add more to it.

**Comment by nbradbury** [comment]
Looks good :shipit:

**Pull request merged**
