### PR TITLE
RI: Expandable tags view design review

### LINKED ISSUE #12744: Topics chips component is non-deterministic and the chips flicker on re-rendering
### Expected behavior
When I click on the bookmark action the set of chips at the top of the post card view remains the same and it doesn't flicker.

### Actual behavior
When I click on the bookmark action the set of chips changes - some get hidden behind "x+" chip and the "x+" chip flickers.

**Note:** The whole card flickers in the current `develop`. The issue is fixed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/12716). So before you start testing this ticket, make sure the PR is merged or you are on the PR's branch.

### Steps to reproduce the behavior
1. Enable RI FF
2. Open Discover tab
3. Find a post with multiple topics
4. Click on bookmark action
5. Notice the set of chips changes
6. CLick on bookmark action again
7. Notice the "x+" chip flickers

### PR DESCRIPTION
**Pull request by ashiagr**
This PR updates styles for chips on expandable tags view and fixes #12744.

|Flicker Fix|
|---------|
flickr_fix

**Design Review** (cc @mbshakti )

light mode collapsed | dark mode collapsed 
------| --------
light_mode_colla | dark_mode_colla

light mode expanded | dark mode expanded 
------| --------
light_mode_expanded |dark_mode_ex

**Merge Instructions**

1. Make sure #12716 is reviewed and merged to develop
2. Remove "Not Ready for Merge" label
3. Merge this PR

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mbshakti** [comment]
Looks great! A couple of comments:
Topic chip fill color:
Screen Shot 2020-08-24 at 12 54 16 PM

Is it possible to go even lighter on the topic chip fill color? We are using black as the fill and then using disabled alpha right? 

I know disabled alpha is lowest we can go :( but topic chips feels too prominent and distract from the postcard content. One idea: Is it possible to use gray as the background instead of black, that way the background would be even lighter? AFAIK we only use whites and blacks and play with the opacity so don’t know if this suggestion holds. Let me know what you think.  

On dark mode, colors look perfect!

Hide button:
For the hide button, it currently looks like another topic chip i.e looks like it's a topic called "Hide", can we remove the topic chip fill for the hide button so that it visually looks different from rest of the topic chips? Quick mock up:
Screen Shot 2020-08-24 at 12 58 31 PM

One quick bug(?), I noticed that on landscape mode, it's really hard to tap on the topic chips. It always records my tap on the topic chips as a tap on the article, so keeps opening the article.

**Comment by malinajirka** [comment]
>One quick bug(?), I noticed that on landscape mode, it's really hard to tap on the topic chips. It always records my tap on the topic chips as a tap on the article, so keeps opening the article.

~@ashiagr We might want to consider adding the click listener to the chips group (whole component) and perhaps even adding some fake(invisible) bottom padding/margin. I agree that the current touch target is too small - I was testing it on an emulator so I didn't notice it :(.~

>For the hide button, it currently looks like another topic chip i.e looks like it's a topic called "Hide", can we remove the topic chip fill for the hide button so that it visually looks different from rest of the topic chips? Quick mock up:

~It feels a bit weird to me to have the "4+" clickable in the grey box and the "hide" button clickable without the box. I'd consider not showing the hide button at all -> when the user clicks on the expanded view, it'll just collapse itself. Wdyt?~

Ignore both my comments. I'm not sure what I was thinking - each chip is clickable :X.

**Comment by ashiagr** [comment]
Thanks for the review @mbshakti 

### Remove topic chip fill for the hide button

> can we remove the topic chip fill for the hide button so that it visually looks different from rest of the topic chips

Yes, removed - c9734d3. Updated screenshots:

Light mode | Dark mode
----------|-----------
light_mode | dark_mode

-----------------------------------------------------------------

### Hard to tap on the topic chip

 > One quick bug(?), I noticed that on landscape mode, it's really hard to tap on the topic chips. It always records my tap on the topic chips as a tap on the article, so keeps opening the article.

I've increased padding around the ChipGroup (in blue outline)

chip_padding

I've also disabled listening to touch on empty area inside the ChipGroup - e1dce21. Let me know if it feels better. 

touch_disable

-----------------------------------------------------------------

### Lighter topic chip fill color

> We are using black as the fill and then using disabled alpha right?

We're using `colorOnSurface` with `disabled_alpha`. `colorOnSurface` is black for light mode and white for dark mode. With disabled alpha it gives the current look.

 ` <item android:alpha="0.12" android:color="?attr/colorOnSurface" />`

> I know disabled alpha is lowest we can go :( but topic chips feels too prominent and distract from the postcard content. One idea: Is it possible to use gray as the background instead of black, that way the background would be even lighter? AFAIK we only use whites and blacks and play with the opacity so don’t know if this suggestion holds. Let me know what you think.

As mentioned  "we only use whites and blacks and play with the opacity" plus we have limited set of opacity values so I'm not sure about the suggestion. I'm still thinking on this.

**Comment by malinajirka** [comment]
Thanks @ashiagr! I've reviewed the code and LGTM. Feel free to merge it when the design review is finished.

Btw I noticed one minor UI bug - notice the "onclick" animation plays on the "hide" button after you click on the "x+" button.

**Comment by ashiagr** [comment]
> Btw I noticed one minor UI bug - notice the "onclick" animation plays on the "hide" button after you click on the "x+" button.

Modified ripple color here 76a43a4. Let me know if it looks better.

clickanimation

**Comment by mbshakti** [comment]
I wasn't able to install the build successful, but screen caps look great. Thanks!

**Review by malinajirka — APPROVED** [review]
LGTM, thanks @ashiagr! Feel free to merge it when the lint passes.

**Comment by ashiagr** [comment]
Thanks @malinajirka !

@mbshakti and I discussed with @mattmiklic and @khaykov regarding using a lower opacity, like 5% for the chips. 

Quoting @khaykov :
> As long as the chip BG meets accessibility standarts and can be easily distinguished from the underlying color we can go with a separate color or opacity.
> If it's not clickable and text is meets contrast guidelines it should be fine.
> If it's clickable I would make sure it's visible for folks with poor vision.

Since we already display lighter chips in iOS, to be consistent with it I think we can give custom opacity a try in light mode to overcome this issue mentioned by @mbshakti :

> topic chips feels too prominent and distract from the postcard content. 

Here's a screenshot

|Lighter chips|
|-------------|
light_mode

**Comment by malinajirka** [comment]
LGTM, thanks! ;)

**Comment by mbshakti** [comment]
Looking good, thanks so much for addressing this <3

**Pull request merged**
