### PR TITLE
Blaze: Tidy the WebView Header UI 

### PR DESCRIPTION
**Pull request by zwarm**
Parent #18001 

This PR tidies the Blaze WebView Header.
- Swapped out TopAppBar implementation for MainTopAppBar
- Customize the color for disabled vs. enabled action text

Light Cancel Enabled | Light Cancel Disabled
-- | --
Alt desc | Alt desc

Dark Cancel Enabled | Dark Cancel Disabled
-- | --
Alt desc | Alt desc

@shaunandrews - If you have the chance, can you take a look please. Thanks :)

**To test:**
- Install and launch the app
- Login with a wp.com account and select a site that is eligible for Blaze
- Navigate to Me -> App Settings -> Debug Setting
- Enable Blaze
- Restart the app
- Navigate to My SIte tab
- Tap on the Promote With Blaze card
- Tap on the Blaze a Post Now button within the overlay
- ✅ Verify the posts lists show the Header with "Cancel" text button enabled
- Select a post from the list and tap Promote
- Fill out the Appearance view and tap next
- Fill out the Audience view and tap next
- Fill out the Payment information and tap Save & Submit
- Watch the screen as it processes through the Checking Payment Info and the Creating Your Ad views
- ✅ Verify the Checking Payment Info and the Creating Your Ad views show a Header with "Cancel" disabled
- Wait for the process to complete
- ✅ Verify the header action button changed to "Done"

## Regression Notes
1. Potential unintended areas of impact
The action buttons show incorrectly

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
Hey @zwarm 👋🏼 

Everything looks good to me. It looks like it was expected. 

I have tested the end-to-end flows as well as checked the UI improvements
- [x] Created a campaign by adding a new card and completing the payment ✅ 
- [x] Created a campaign by using the same card ✅ 
- [x] Cancelled the flow during the payment ✅ 
- [x] UI improvements - Night Mode and Dark Mode  ✅

⚠️ On further testing, I found that when switching from Light Mode to DarkMode, when the user is on Webview, the flow gets reset to the Overlay. PFB the video capture. I don't think this is a blocker, since I believe this scenario won't happen without intention in the real world. But I **think may** be a small change in how we handle the UI state might fix the issue. So pointing it out. 

https://user-images.githubusercontent.com/17463767/222355042-2b19e472-9f5a-4f58-b066-c4a604bfea90.mp4

Approving but not merging so that @shaunandrews can have a look

**Review by AjeshRPai — APPROVED** [review]

**Comment by zwarm** [comment]
@AjeshRPai 

> ⚠️ On further testing, I found that when switching from Light Mode to DarkMode, when the user is on Webview, the flow gets reset to the Overlay. PFB the video capture. I don't think this is a blocker, since I believe this scenario won't happen without intention in the real world. But I **think may** be a small change in how we handle the UI state might fix the issue. So pointing it out.

As discussed, this is an outlier issue. We will revisit outside of the MVP. I've captured this in issue #18033

**Comment by enejb** [comment]
@zwarm and @AjeshRPai  would it make sense to compley remote the cancel button? 
When it is grayed out folks might still want to click it to cancel the flow.

**Comment by zwarm** [comment]
@enejb 

> @zwarm and @AjeshRPai would it make sense to compley remote the cancel button? When it is grayed out folks might still want to click it to cancel the flow.

- The button is not clickable when it's disabled, so no action will be taken if someone tries to click on it.

- The last tech spec update has it disabled.
" If the current step matches a value from blaze_non_dismissable_hash we will **disable** the nav bar button"

Please let me know if you want the "cancel" action button completely removed instead of disabled.

**Pull request merged**
