### PR TITLE
Issue/8829 null smart lock helper

### LINKED ISSUE #8829: Internal inconsistency error! mSmartLockHelper found null!
This isn't a crashing exception, but it's being manually reported in the code here:

https://github.com/wordpress-mobile/WordPress-Android/blob/34d489488d54ec5fb796c239595562e856ecad0d/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L658-L661

It looks like it's only triggered by `LoginMode: FULL`, which makes sense, as `mSmartLockHelper` isn't initialized on that code path:

https://github.com/wordpress-mobile/WordPress-Android/blob/34d489488d54ec5fb796c239595562e856ecad0d/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L136-L150

Hopefully that information is helpful for arriving at a fix. 

**reference:** 5be1a16bf8b88c2963c8c8f1-fabric
**90-day impact:** ~15 times/day, ~1300 affected users
**UX impact:** Users who end up in this state can't use their stored credentials to log in

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #8829 

The mSmartLockHelper wasn't being initialized when the user was redirected from a sign-up screen to login. This PR fixes the issue.

To test:
1. Clear app data and open the app
2. Click on Sign up for WordPress.com
3. Click on Sign up with email
4. Enter email of an existing account
5. Click on Next
6. Notice you are redirected to the `LoginMagicLinkRequestFragment` screen
7. Check the AppLog doesn't contain "Internal inconsistency error! mSmartLockHelper found null!" message
---------------
1. Clear app data and open the app
2. Click on Sign In
3. Notice SmartLock account chooser is shown
4. Choose one of the accounts
5. Make sure you are logged in successfully

Update release notes:

- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
👋 @malinajirka ! I tried the PR and verified that the `Internal inconsistency error!` is no longer there! Thanks for tackling this!

But, it seems that the SmartLock for Passwords popup now gets displayed after the app has just shown the MagicLinks screen. It works if chosen but, I think the flow gets a bit complex/confusing. I'd say that as is, the popup is either late (would be better to come up between after tapping "Next" in step 5 but before any screen changes) or too early (the popup could be offered if user taps on the "Enter password instead" secondary action on the MagicLink screen.

Can you check if it's easy enough to have the SmartLock popup show before the screen change?

**Comment by malinajirka** [comment]
Thanks @hypest !! Good point, I'll check it out next week.

**Comment by malinajirka** [comment]
@hypest I've looked into it again and I'm super confused.

1. Does the SmartLock really work for you? It seems the username and password is never automatically pre-filled for me as it always fails on [this condition](https://github.com/wordpress-mobile/WordPress-Android/blob/19d8591335de160e89df8e6de61c0e380662140a/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L265). Don't we need to setText of `mUsernameInput` and `mPasswordInput` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/19d8591335de160e89df8e6de61c0e380662140a/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L240) or modify the condition and the surrounding code?

smart-lock

2. 
>But, it seems that the SmartLock for Passwords popup now gets displayed after the app has just shown the MagicLinks screen. It works if chosen but, I think the flow gets a bit complex/confusing. I'd say that as is, the popup is either late (would be better to come up between after tapping "Next" in step 5 but before any screen changes) or too early (the popup could be offered if user taps on the "Enter password instead" secondary action on the MagicLink screen.

I feel like both flows might be quite confusing, especially if the user has more than one Google account  connected with their device. 
Imagine you enter "example**1**@gmail.com" and you tap on the "Next"/"Enter password instead" button and the app asks you if you want to login with "example**2**@gmail.com".
I feel like we should display the dialog when the user opens the app(login prologue) -> before they actually click on Sign-in or Sign-up. We'll save a couple of clicks for them and we'll avoid all the confusion + as a bonus the code will be much easier to follow. Wdyt?

**Comment by hypest** [comment]
> Does the SmartLock really work for you? 

It does, here's a gif with it running off `wasabiDebug` on my Nexus 5X, Android 7.1.2:

smartlock-for-passwords

Some extra info from my run:

1. `LoginUsernamePasswordFragment.jsva:239` is hit and the state/instance variables `mInputUsername` and `mInputPassword` do have the proper (non-empty) values. The breakpoint is hit after I tap on the smartlock popup and before the app has visually changed to the username/password screen.

I added a breakpoint to `LoginUsernamePasswordFragment.newInstance:98` that where is the code the values are passed to the Fragment, and here's a shot of the stacktrace from the debugger, which might be useful:

Screenshot 2019-04-08 at 16 37 27

Those values are then picked up in the fragment's `onCreate`.

2.
> I feel like we should display the dialog when the user opens the app(login prologue) -> before they actually click on Sign-in or Sign-up.

I think that'd be a departure from the original design's goal in the prologue screen, which was to first ask the user if they want to log in or to create a new account. Prompting them to login via SmartLock-for-passwords right of the bat would imply we know they want to log in, which we don't know. No strong feelings here though so, I think it'd be best if you get in touch with a designer and sort this out.

> ... especially if the user has more than one Google account connected with their device.

That's a good point in any case. That is, if the user has many pairs of name/pass stored in SmartLock, there is always the possibility they will choose the "wrong" one, not the one we'd like them to pick from the popup.

I think that at this point, I'd probably raise the question whether offering SmartLock-for-passwords in this flow is even appropriate. It'd be best if we could automatically fetch the _password_ only from Smartlock, not let the user go pick any pair from it.

**Comment by malinajirka** [comment]
Thank you Stefanos for the detailed description;)! We'd like to wrap up the Post Filters project by Friday - I'll make sure to wrap up this PR next week:).

**Comment by hypest** [comment]
I think there's no rush with this one @malinajirka so, cool 👍.

**Comment by malinajirka** [comment]
>>Does the SmartLock really work for you?

>It does, here's a gif with it running off wasabiDebug on my Nexus 5X, Android 7.1.2:

I'm truly sorry you had to spent time on this, totally my fault:(. I've missed these two lines ([1](https://github.com/wordpress-mobile/WordPress-Android/blob/e30f2c2abdc7009d8c96819f0e1567868f585f21/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L150) [2](https://github.com/wordpress-mobile/WordPress-Android/blob/e30f2c2abdc7009d8c96819f0e1567868f585f21/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L164)). It'd always override my credentials with an empty string. I was most probably modifying credentials in a wrong `gradle.properties` file. Sorry:(

>I think that'd be a departure from the original design's goal in the prologue screen, which was to first ask the user if they want to log in or to create a new account. Prompting them to login via SmartLock-for-passwords right of the bat would imply we know they want to log in, which we don't know. No strong feelings here though so, I think it'd be best if you get in touch with a designer and sort this out.

Yep, I realize it'd be a big change and we'd definitely need to discuss it with a designer or even more designers first.

>I think that at this point, I'd probably raise the question whether offering SmartLock-for-passwords in this flow is even appropriate. It'd be best if we could automatically fetch the password only from Smartlock, not let the user go pick any pair from it.

I've quickly checked the documentation and the api won't let us access the credentials if one of the following is true (it requires us to show the account chooser dialog if we want to proceed)
- `the user or the app has disabled auto sign-in` (we always disable it [here](https://github.com/wordpress-mobile/WordPress-Android/blob/e30f2c2abdc7009d8c96819f0e1567868f585f21/WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java#L704))
- `more than one account is known and the user must choose which account they would like to use.`

We could theoretically enable auto sign-in for the `sign-up to sign-in flow` and check whether the email user just entered matches the email stored in SmartLock. However, it'd require significant changes.

I've decide to go with a simple solution in order to prevent the "Internal inconsistency error! mSmartLockHelper found null!". This fix will allow the user to store the password into SmartLock even when they try to sign-up with an existing email and are redirected to the sign in flow. However, it won't allow them to sign in with the stored password. I'll create a separate issue with the options we have (show the smart lock account chooser on `LoginPrologue` or the solution outlined in the paragraph above) if you approve this PR .

It's ready for another round @hypest. Thanks

**Comment by loremattei** [comment]
I'm moving this to 12.5 since 12.4 has been cut. If this PR has to land 12.4, please feel free to target the release branch and to ping me to build a new beta.

**Comment by malinajirka** [comment]
Thanks! I've removed the line from release-notes.xml.

I'll merge this as soon as the checks are completed. ;)

**Pull request merged**
