### PR TITLE
Site Plan Mime Type Picker Integration

### LINKED ISSUE #14121: Media Pickers should filter files based on site's plan supported MIME types.
### Expected behavior
The MediaPicker needs support for allowed MIME types based on a site’s plan ([Dot Com](https://en.support.wordpress.com/accepted-filetypes/)) or configuration ( [Dot Org](https://href.li/?https://codex.wordpress.org/Uploading_Files)) as a means of filtering unavailable MIME types from the media pickers. 

`FluxC` is expected to have support for this at it's layer since it is in charge of managing the mime types allowed. [An issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1884) is tracking the behavior needed there.

### Actual behavior
All file types that are on a device are shown. 

### Steps to reproduce the behavior
1. Utilize a WPCom site with a free plan. 
2. Go to the File Block. 
3. Notice you are able to add `.key` and `.zip` files which should only be available on paid plans.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #14121 
FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1911

## Findings
The ConsolidatedMediaPicker was updated to the support file types available on each plan  https://wordpress.com/support/accepted-filetypes/ . Now when the Media Browser, and the Editor ( Audio and FIle Block) are utilized they will respect the paid vs free behavior defined in the plans. 

## Solution
Involved making updates to the `MimeTypes` behavior in FluxC and then integrating with logic with media components of the Consolidated Media Picker. 

### Prerequisite

Ensure that the device you are testing has a few sample audio files of the type mp3, mp4, ogg, wav. You can download sample audio files at <https://file-examples.com/index.php/sample-audio-files/>. ( For the Media Browser, test the System Picker option as well as it supports the behaviors below that are defined for the Media Browser itself.) 

### 1. Media Browser

1. Open the  Media Browser.
2. Attempt to upload an audio file.
3. Notice that no audio files are available.  

### 2. Block Editor

1. Create a new blog post.
2. Tap (+) (inserter) – this shows the Block Library sheet.
3. Notice that the Audio block is not visible on free sites.

### 1. Media Browser

1. Open the  Media Browser.
2. Attempt to upload an audio file.
3. Notice that all audio file types are available.

### 2. Block Editor

1. Create a new blog post.
2. Tap (+) (inserter) – this shows the Block Library sheet.
3. Notice that the Audio block is visible on paid sites.
4. Tap Audio to add the block's media placeholder to canvas.
5. Tap Add Audio to add a file.
6. Notice that all audio files are available.

Audio block in Editor | Choose from device 
--------|-------
  <kbd></kbd>    |     <kbd></kbd>

### Prerequisite

Ensure that the device you are testing has a few sample files of the type doc, pdf, key, zip. You can download sample files at <https://file-examples.com/index.php/sample-documents-download/>

### 1. Media Browser

1. Open the  Media Browser.
2. Attempt to upload a document.
3. Notice that files of the types below are available.  

- .pdf (Portable Document Format; Adobe Acrobat)
- .doc, .docx (Microsoft Word Document)
- .ppt, .pptx, .pps, .ppsx (Microsoft PowerPoint Presentation)
- .odt (OpenDocument Text Document)
- .xls, .xlsx (Microsoft Excel Document)

4. Notice that file of the types below are not available.

- .key (Apple Keynote Presentation)
- .zip (Archive File Format—as long as the .zip file contains accepted file types)

### 2. Block Editor

1. Create a new blog post.
2. Tap (+) (inserter) – this shows the Block Library sheet.
3. Tap File to add the block's media placeholder to canvas.
4. Tap Choose A File to add a file.
5. Notice that files of the types below are available.  

- .pdf (Portable Document Format; Adobe Acrobat)
- .doc, .docx (Microsoft Word Document)
- .ppt, .pptx, .pps, .ppsx (Microsoft PowerPoint Presentation)
- .odt (OpenDocument Text Document)
- .xls, .xlsx (Microsoft Excel Document)

6. Notice that file of the types below are not available.

- key (Apple Keynote Presentation)
- zip (Archive File Format—as long as the .zip file contains accepted file types)

File Explorer | Choose from device 
--------|-------
 <kbd></kbd>    |  <kbd></kbd>
    
### 1. Media Browser

1. Open the  Media Browser.
2. Attempt to upload a file.
3. Notice that all file types are available.

- .pdf (Portable Document Format; Adobe Acrobat)
- .doc, .docx (Microsoft Word Document)
- .ppt, .pptx, .pps, .ppsx (Microsoft PowerPoint Presentation)
- .odt (OpenDocument Text Document)
- .xls, .xlsx (Microsoft Excel Document)
- .key (Apple Keynote Presentation)
- .zip (Archive File Format—as long as the .zip file contains accepted file types)

### 2. Block Editor

1. Create a new blog post.
2. Tap (+) (inserter) – this shows the Block Library sheet.
4. Tap File to add the block's media placeholder to canvas.
5. Tap Choose A File to add a file.
6. Notice that files of the types below are available.  

- .pdf (Portable Document Format; Adobe Acrobat)
- .doc, .docx (Microsoft Word Document)
- .ppt, .pptx, .pps, .ppsx (Microsoft PowerPoint Presentation)
- .odt (OpenDocument Text Document)
- .xls, .xlsx (Microsoft Excel Document)
- .key (Apple Keynote Presentation)
- .zip (Archive File Format—as long as the .zip file contains accepted file types)

File Explorer | Choose from device 
--------|-------
 <kbd></kbd>    |  <kbd></kbd>

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by jd-alexander** [comment]
Hi @ParaskP7 while working on this PR I had to modify the detekt config to get the PR to pass CI lint checks. Since you have been leading the efforts on this, I want to notify you of the changes 53e0c04 4f1c900 to hear your thoughts. I ended up increasing them because I couldn't think of any way to lessen the params to the function/constructor (s) in question.

**Comment by jd-alexander** [comment]
Heads up to the reviewers. I will need to update this PR with test cases for the system picker.  The behavior is similar to that of the Consolidated Media Picker where file types not available on a plan aren't shown in the directory.

**Comment by ParaskP7** [comment]
👋 @jd-alexander !

> Hi @ParaskP7 while working on this PR I had to modify the detekt config to get the PR to pass CI lint checks. Since you have been leading the efforts on this, I want to notify you of the changes 53e0c04 4f1c900 to hear your thoughts. I ended up increasing them because I couldn't think of any way to lessen the params to the function/constructor (s) in question.

Thanks for pinging me on this! 🙏 

Instead of updating Detekt's configuration to increase the `LongParameterList.functionThreshold` and `LongParameterList.constructorThreshold` by +1, which will affect the whole codebase, why not just `@Suppress("LongParameterList")` the function/constructors in question if you really feel that there isn't any other way to get around that?

Just to be clear, I am not against updating Detekt's configuration, I am just trying to understand the why first. Also, maybe those kind of configuration updates deserve their own individual PR, since updating at least this exact configuration would potentially result in needing to update the baseline (to get rid of existing issues, since the threshold got more relaxed) and removed already existing `@Suppree("LongParameterList")` annotation, since they might not be needed any more (again, since the threshold got more relaxed).

PS: Have you had the change to read our conversation with Vojta about this here: `paqN3M-hh-p2#comment-481`

**Review by planarvoid — APPROVED** [review]
I've reviewed the changes and tested the behaviour and it's looking great 👍 . I'm not merging it yet because the FluxC part needs to be done first

**Comment by jd-alexander** [comment]
> I've reviewed the changes and tested the behaviour and it's looking great 👍 . I'm not merging it yet because the FluxC part needs to be done first

Thanks for the review @planarvoid I will take a look at these changes.

> PS: Have you had the change to read our conversation with Vojta about this here: paqN3M-hh-p2#comment-481

@ParaskP7 I haven't read that conversation as yet. I will do that and share my thoughts. Thanks!

**Review by tw875768 — APPROVED** [review]

**Comment by jd-alexander** [comment]
@ParaskP7 I ended up utilizing the `Suppress` annotation and that worked out well. Thanks for all the insights.

**Comment by jd-alexander** [comment]
@planarvoid I updated the flux C PR with the changes you requested and addressed the detekt issues here as well, so the PR is ready for another review 🙇🏾

**Review by planarvoid — APPROVED** [review]
I've retested the changes and it works well 👍 , feel free to merge this once the FluxC is updated to the latest tag

**Pull request merged**
