### PR TITLE
Domains Dashboard

### LINKED ISSUE #15298: [Android] Add Domains Dashboard
New domains dashboard a.k.a Site domains list
My Site -> Domains -> Site domains

See #15305

### PR DESCRIPTION
**Pull request by ravishanker**
builds domains list screen based on i2.

Fixes #15298 

<table><tr>
<td></td>
<td>
</tr></table>

To test:

1. Enable AppSettings -> Debug settings -> SiteDomainsFeatureConfig ✅
2. Return to **My Site**, Notice there's a new item under **Configuration** -> 🌐 Domains
3. Click on Domains, takes your Site Domains Screen
4. Test with a free plan and paid plan to to see the above screens

NOTE: It is work in progress, design and behavior will be improved in the next iterations.  
All links point to existing register domain flow 
The kebab menu, manage domains and learn more all will be implemented separately. 
The copy and design will be updated as it evolves in the next PRs

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by thehenrybyrd** [comment]
@ravishanker I downloaded the APK to take a look, and the Domains Dashboard screen appears as in the screenshots.

These items work as described:
- Domains Dashboard appears under Configuration (between Sharing and Site Settings) for sites with both paid and free plans.
- The "Add a domain" and "Search for a domain" buttons both point to existing domain registration flow
- In the case of a site with a paid plan but no custom domain, "Claim your free domain" appears rather than "Get your domain".

These items are not working yet, I presume to be added/fixed in a later version:
- Kebab menu (...) not tappable
- Manage Domains link does nothing
- Learn more link points to WordPress.com, rather than a support doc. 

One other thing I noticed is that the screen is titled "Site domains". Just "Domains" would be clearer and more succinct; I've shared this feedback with @kyleaparker as well in comments of the i3 post.

I haven't taken a close look at the code, so I'll let @renanferrari chime in for code comments.

**Comment by renanferrari** [comment]
@ravishanker Before I review this, can you clarify what exactly this PR is supposed to do? As @thehenrybyrd mentioned, there seems to be some functionality missing. Is this focusing on the UI only? 

Generally speaking, it's helpful for reviewers when a PR description contains some information about what the PR is trying to achieve and what part of the work is going to be completed at a later time.

**Comment by ravishanker** [comment]
> @ravishanker I downloaded the APK to take a look, and the Domains Dashboard screen appears as in the screenshots.
> 
> These items work as described:
> 
>     * Domains Dashboard appears under Configuration (between Sharing and Site Settings) for sites with both paid and free plans.
> 
>     * The "Add a domain" and "Search for a domain" buttons both point to existing domain registration flow
> 
>     * In the case of a site with a paid plan but no custom domain, "Claim your free domain" appears rather than "Get your domain".
> 
> 
> These items are not working yet, I presume to be added/fixed in a later version:
> 
>     * Kebab menu (...) not tappable
> 
>     * Manage Domains link does nothing
> 
>     * Learn more link points to WordPress.com, rather than a support doc.
> 
> 
> One other thing I noticed is that the screen is titled "Site domains". Just "Domains" would be clearer and more succinct; I've shared this feedback with @kyleaparker as well in comments of the i3 post.
> 
> I haven't taken a close look at the code, so I'll let @renanferrari chime in for code comments.

Thank you @thehenrybyrd for taking it for spin.  The features that are working are the only ones implemented.  The copy and design will be updated as it evolves.  It is all under feature flag, still accessible only in development
- The kebab menu for change site address will be implemented separately in the next PRs. 
- Updated Learn more and manage domains urls, they should work now.

**Comment by ravishanker** [comment]
> @ravishanker Before I review this, can you clarify what exactly this PR is supposed to do? As @thehenrybyrd mentioned, there seems to be some functionality missing. Is this focusing on the UI only?
> 
> Generally speaking, it's helpful for reviewers when a PR description contains some information about what the PR is trying to achieve and what part of the work is going to be completed at a later time.

Thank you @renanferrari for taking a quick look.  I mentioned above, it is another iteration of design and behavior on the previous one.  Updated description

**Review by renanferrari — APPROVED** [review]
@ravishanker Thanks for clarifying where this stands! I'm merging it now, so we can move forward with the project and take care of what's missing as soon as possible.

**Pull request merged**
