### PR TITLE
Merge develop into feature/master-post-filters

### PR DESCRIPTION
**Pull request by malinajirka**
This PR merges `develop` into `feature/master-post-filters`.

There were several merge conflicts + I had to manually fix a couple of issues.

- [Removed "fab_pressed" ](https://github.com/wordpress-mobile/WordPress-Android/pull/9607/commits/c0de86598e2a34d2aa9586578e3e4275eb2a7ee9) color - corresponding change was introduced here https://github.com/wordpress-mobile/WordPress-Android/commit/faaca95673ac969250b14639a8ede100d4d25a22
- [Added haptic feedback](https://github.com/wordpress-mobile/WordPress-Android/pull/9607/commits/65ace8d78cb85ab10d2445b885272f3c3a3c8d14) after merge - corresponding change was introduced here https://github.com/wordpress-mobile/WordPress-Android/commit/0b0072f287452fa764692e582da7782686e760fe but we've moved the view
- Introduced a new transparent color in https://github.com/wordpress-mobile/WordPress-Android/pull/9607/commits/2738ba45845bc3425687a80bd325093269edcfc8 ( @theck13  I've introduced a new transparent color as a hotfix so I could get this PR merged. Could you please check it and fix what's neccessary)
- Updated color scheme following this mapping in https://github.com/wordpress-mobile/WordPress-Android/pull/9607/commits/f023a18b572ea433157f80cb7e0543de2f1f84ee and https://github.com/wordpress-mobile/WordPress-Android/pull/9607/commits/7de3dcdba95d21167950f4046ef4433839219a06
```
wp_grey_lighten_30 -> neutral_50
white -> android:color/white
wp_grey_dark -> neutral_800
wp_grey_darken_20 -> neutral_500
fab_pressed -> removed
grey_darken_20 -> neutral_500
alert_red -> error_500
alert_yellow_dark -> warning_700
blue_wordpress -> primary_500
```

### CODE REVIEW

**Comment by theck13** [comment]
> Introduced a new transparent color in 2738ba4 ( @theck13 I've introduced a new transparent color as a hotfix so I could get this PR merged. Could you please check it and fix what's neccessary)

Actually, we don't need that color at all.  Since it's `#00######`, the alpha is 0 making it effectively the same as `@android:color/transparent`.  We can replace `android:startColor="@color/primary_500_transparent"/>` with `android:startColor="@android:color/transparent"/>` in `tab_layout_gradient` and it will be the same effect.  Then we can remove `primary_500_transparent` and `blue_500_transparent` from `colors.xml` since they will no longer be used.

> Updated color scheme following this mapping in f023a18 and 7de3dcd
> ```
> wp_grey_lighten_30 -> neutral_50
> white -> android:color/white
> wp_grey_dark -> neutral_800
> wp_grey_darken_20 -> neutral_500
> fab_pressed -> removed
> grey_darken_20 -> neutral_500
> alert_red -> error_500
> alert_yellow_dark -> warning_700
> blue_wordpress -> primary_500
> ```

We should replace `alert_red` with `error` and `alert_yellow_dark` with `warning_dark`.  The rest of the color replacements look good to me!

**Comment by malinajirka** [comment]
Thanks @theck13 !

>We should replace alert_red with error and alert_yellow_dark with warning_dark. The rest of the color replacements look good to me!

I've replaced these and created a PR - #9617.

>Actually, we don't need that color at all. Since it's #00######, the alpha is 0 making it effectively the same as @android:color/transparent. We can replace android:startColor="@color/primary_500_transparent"/> with android:startColor="@android:color/transparent"/> in tab_layout_gradient and it will be the same effect. Then we can remove primary_500_transparent and blue_500_transparent from colors.xml since they will no longer be used.

That's what I though as well and I used transparent. However, the color is used in a gradient and therefore its effect isn't the same. I believe we need to keep it. The question is if `primary_500_transparent` and `blue_500_transparent` are good names and if they follow the approach. Wdyt?

**Comment by theck13** [comment]
> That's what I though as well and I used transparent. However, the color is used in a gradient and therefore its effect isn't the same. I believe we need to keep it. The question is if `primary_500_transparent` and `blue_500_transparent` are good names and if they follow the approach. Wdyt?

Even if the color is used in a gradient, the effect is the same.  The preview in Android Studio looks different if you use `@color/primary_500_transparent` or `@android:color/transparent`, but they are actually the same at runtime.  Making the tab background white helps see they are the same too.  See the screenshots below for illustration.  I used `@color/primary_500_transparent` in the top images and `@android:color/transparent` in the bottom images.

gradient

**Comment by malinajirka** [comment]
Ohh, you are right. The AS tricked me :(. Thanks 🙇  

Fixed in #9634

**Pull request merged**
