### PR TITLE
Filter media list to call processMediaUri just once

### LINKED ISSUE #38287: Gallery block - Adding images creates unexpected Image blocks
## Description
Currently, there's a bug when adding images to a Gallery, where it would create the gallery itself and Image blocks from those images below the Gallery block. This is an issue happening on **Android only** so it looks like it's a native side bug with media selection.

This issue is happening on the WordPress Android version `19.0` and it affects that version and the on-going release for `19.1`.

## Step-by-step reproduction instructions
- Open the WordPress Android app
- Start a new post
- Add a Gallery block
- Add some images (from the device)

## Expected behaviour
The Gallery block should show correctly with the previously selected images.

## Actual behaviour
The Gallery block shows up with the images but after it some Image blocks are created as well.

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/4885740/151385043-847d4a0e-dd7c-4f2f-acae-5386ee419e97.mov

## WordPress information
- WordPress version: Latest
- Gutenberg version: Latest version in trunk, `1.70.0` and `1.69.0`
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No, using `Calvin`

## Device information
- Device: Redmi Note 8T and Android Simulator
- Operating system: Android 11
- WordPress app version: `19.0`, `19.1`

### PR DESCRIPTION
**Pull request by hypest**
Fixes https://github.com/WordPress/gutenberg/issues/38287 over at the Gutenberg side.

This PR refactors the code to avoid calling `processMediaUri()` multiple times when multiple media have been selected.

### To test 1
* Add a gallery block in a post
* Add media by selecting 2 photos from the local device gallery
* Observe the gallery block being populated without any additional image blocks to be added after it

### To test 2
* Add a video block to a post on a Free Simple site
* Upload a long video (longer than 5mins) from the local device gallery
* Notice that the video is not uploaded and a Toast informs that a paid plan is needed

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mkevins — APPROVED** [review]
Thanks for diving in to fix this one @hypest :+1: The code changes look great, and I tested this by first reproducing the issue without these changes, and then testing the same steps with these changes (tested on a Pixel 3a, physical device). This fixes the underlying cause of the issue.

A minor suggestion (not at all a blocker) is that we could rename the `processMediaUri` function to `processMediaUris` to indicate that it deals with a collection of URIs.

<details>
<summary>Rename function patch</summary>

```patch
diff --git a/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt b/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
index 0df3416a5d..1279499d4c 100644
--- a/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
+++ b/WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
@@ -68,7 +68,7 @@ class AddLocalMediaToPostUseCase @Inject constructor(
             return@filter true
         }
 
-        return processMediaUri(
+        return processMediaUris(
                 allowedUris,
                 site,
                 freshlyTaken,
@@ -77,7 +77,7 @@ class AddLocalMediaToPostUseCase @Inject constructor(
                 trackEvent)
     }
 
-    private suspend fun processMediaUri(
+    private suspend fun processMediaUris(
         uriList: List<Uri>,
         site: SiteModel,
         freshlyTaken: Boolean,
```
</details>

**Comment by ravishanker** [comment]
Thank you @hypest for investigating and making a quick fix.   I've tested the video upload limits, with single file and multiple files, it seems to work fine as before. 👍

**Comment by ravishanker** [comment]
I'm going to cherry pick this commit to a new PR on release/19.1 and see if there's still a chance to put this into it.

**Comment by ravishanker** [comment]
Closing this draft as it is picked and merged through #15872

**Pull request closed without merging**
