### PR TITLE
Update Kotlin to 1.6.10

### LINKED ISSUE #15703: 🚨 Update all our dependencies to be compatible with our kotlin version
### Expected behavior

All our dependencies use a compatible version of kotlin

### Actual behavior

Currently the app uses kotlin `1.5.32`, after it has been updated (from `1.4.0`) in https://github.com/wordpress-mobile/WordPress-Android/pull/15646 (h/t @ParaskP7) to fix a compilation issue.

But when I did the release build for 18.8 today, even if the build succeeded, I still saw a LOT (1000+) of those error messages in the log output:
```
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
…
```

See also p1639156434202200/1639150575.196500-slack-C02QANACA for more context and info.

We've shipped WPAndroid 18.8 to the PlayStore despite those errors but we should definitively ensure that those are fixed ASAP so we can be confident on the releases going forward. This is why I've made this issue target the 18.9 milestone.

### Steps to reproduce the behavior

 - Compile the app via `./gradlew buildWordPressVanillaRelease`
 - The build ends with "Build Succeeded"… yet the logs contains a lot of errors related to kotlin version mismatches and conflicts.

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR upgrades Kotlin to `1.6.10`.

It includes the following:
- Resolves the `MultilineIfElse` warnings on the `PageItemViewHolder` class (see [commit](https://github.com/wordpress-mobile/WordPress-Android/commit/2b352168a2a6806edbe1e6c2ed48e8d9c6a2684d)).
- Removes the unnecessary duplicate `@InternalCoroutinesApi` to solve a compilation error (see [commit](https://github.com/wordpress-mobile/WordPress-Android/commit/7218d581ae5477745451f67c161e4b86f807c915)).
- Removes the unnecessary `@ExperimentalStdlibApi` annotation to solve a couple of compilation errors (see [commit](https://github.com/wordpress-mobile/WordPress-Android/commit/33f3f37a661b6d549844788d07849abfe9f70101)).
- Removes and/or replaces the deprecated `@UseExperimental` annotation (see [commit](https://github.com/wordpress-mobile/WordPress-Android/commit/494dbaa5695270864d6d400adbca9cfd743350e9)).

To test:
- Smoke test the app.
- Test for build time increases (local & CI).

## Regression Notes
1. Potential unintended areas of impact

Build time increase.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual tests and CI checks.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: Note that after diffing the before and after the update I confirmed that all the below `Kotlin` classpath version related warnings will be removed after this PR is merged to `trunk`:

```
> Task :libs:WordPressAnnotations:compileKotlin
'compileJava' task (current target is 1.7) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

> Task :libs:WordPressProcessors:kaptGenerateStubsKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.72/916d54b9eb6442b615e6f1488978f551c0674720/kotlin-stdlib-jdk8-1.3.72.jar (version 1.3)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.32/2e8f666555c2a6bf10ef712be8a738e665132c8/kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.32/a1f8a73f899b85e6eb4337dff7e81b8b914bd2c9/kotlin-stdlib-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.32/8befc4a20c17094a148f1409c1bac163bc3ca630/kotlin-stdlib-common-1.5.32.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

> Task :libs:WordPressProcessors:compileKotlin
'compileJava' task (current target is 1.7) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.72/916d54b9eb6442b615e6f1488978f551c0674720/kotlin-stdlib-jdk8-1.3.72.jar (version 1.3)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.32/2e8f666555c2a6bf10ef712be8a738e665132c8/kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.32/a1f8a73f899b85e6eb4337dff7e81b8b914bd2c9/kotlin-stdlib-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.32/8befc4a20c17094a148f1409c1bac163bc3ca630/kotlin-stdlib-common-1.5.32.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

> Task :WordPress:kaptGenerateStubsWordpressWasabiDebugKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/64effc998fa5e07ee204a1066efd8700/transformed/jetified-kotlin-stdlib-jdk8-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/baacc739f74c7117c64357259ab9cdff/transformed/jetified-kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/35431a7d6af96f6e0af35414101ede24/transformed/jetified-kotlin-stdlib-1.6.0.jar (version 1.6)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/97ead81c9c337c2a1fc3801e0af5f393/transformed/jetified-kotlin-stdlib-common-1.6.0.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/64effc998fa5e07ee204a1066efd8700/transformed/jetified-kotlin-stdlib-jdk8-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/baacc739f74c7117c64357259ab9cdff/transformed/jetified-kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/35431a7d6af96f6e0af35414101ede24/transformed/jetified-kotlin-stdlib-1.6.0.jar (version 1.6)
    /Users/petros.paraskevopoulos/.gradle/caches/transforms-3/97ead81c9c337c2a1fc3801e0af5f393/transformed/jetified-kotlin-stdlib-common-1.6.0.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

```

**Comment by AliSoftware** [comment]
> FYI: Note that after diffing the before and after the update I confirmed that all the below `Kotlin` classpath version related warnings will be removed after this PR is merged to `trunk`:

So that means that should thus also fix https://github.com/wordpress-mobile/WordPress-Android/issues/15703 🤞  🕺 🎉

**Review by antonis — APPROVED** [review]
Great work @ParaskP7 🎉 
I smoke tested on a Pixel 5 (Android 12) the CI generated build and did not notice any issues. I've also build build locally (Android Studio Bumblebee | 2021.1.1 Patch 2) without issues. The code changed LGTM and follow your description 🎉 
Thank you fro tackling this 🙇

**Comment by ParaskP7** [comment]
👋 @antonis !

Thank you so much for reviewing, testing this PR, and actually merging with `trunk` to solve the conflict, you rock! ❤️ 🚀

**Pull request merged**
