### PR TITLE
Stop managing google api client when play services outdated.

### LINKED ISSUE #7106: Crash report in 9.1: ISE in LoginEmailFragment.onCreate
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.accounts.LoginActivity}: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3506)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at com.google.android.gms.common.internal.zzac.zza(Unknown Source)
       at com.google.android.gms.internal.zzzt.zza(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.zzf(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
       at org.wordpress.android.ui.accounts.login.LoginEmailFragment.onCreate(LoginEmailFragment.java:234)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
       at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:449)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
       at android.app.Activity.performResume(Activity.java:6770)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/5a3b85fc8cb3c2fa635a5531

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #7106 

The crash happens because we check if Google API client is connected before stopping managing it. 
Google API client will be managed but not connected when Google Play Services are outdated.

This one is a bit hard to reproduce because you need outdated Google Play Services. I only managed to reproduce it by accident with one of the older emulator images.
- With outdated Google Play Services install and launch the app.
- Press Login button.
- Observe "This app won't run unless you update Google Play services" dialog, and press "OK".
- Navigate back to Prologue screen and press Login again.
- Notice crash.

### CODE REVIEW

**Comment by khaykov** [comment]
Looks like some other issues with Google API's might cause this to happen. Sometimes [isGooglePlayServicesAvailable](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/accounts/SmartLockHelper.java#L53) returns `ConnectionResult.SUCCESS` but `GoogleApiClient` still think that Google Play Services is not installed and is refusing to connect. I attribute it to bugginess of `GoogleApiClient` and Google Play API's. 👻 

[https://gyazo.com/043e108703909b6c40be4e8c82657290](https://gyazo.com/043e108703909b6c40be4e8c82657290)

**Comment by hypest** [comment]
Hmm, can't reproduce the crash on my 7.1.2 Nexus 5X with downgraded PlayServices (v9.8.79). I actually tested the app with [this fix](https://github.com/wordpress-mobile/WordPress-Android/issues/7191) since it's needed to make the Login button work again. In other words, can't verify the fix in this PR :(

Any idea on how to reproduce the crash? Thanks!

**Comment by khaykov** [comment]
@hypest Looks like the steps might be different for different cases/devices (I was testing mostly on emulators).
I managed to reproduce it on real Pixel with Android 8.1.0. I think this steps might work for you too:

1. Navigate to Settings -> Apps -> Google Play services and Disable them (I don't have the option to downgrade them on any of my devices/emulators, but disabling them also causes the crash).
2. Do a fresh install of the app (I used the latest develop branch).
3. At the Prologue screen press login.
4. You should see "Enable Google Play services dialog". 

At this point, you have a couple ways to get to the crash:

First:

1. Change the device orientation (this will dismiss the dialog and bring up expanded input field).
2. Press Back button couple of times to navigate back to the Prologue screen.
3. Press "LOG IN" button and observe the crash.

Second (a bit obscure):

1. Press "ENABLE" button in the dialog to navigate to Google Play services app screen.
2. Press back button to navigate back into the app, without enabling the play services.
3. Press back to navigate back to Prologue. Press "LOG IN", then go back to Prologue and press Press "LOG IN" again.
4. Observe crash.

Thanks!

**Comment by hypest** [comment]
The "Disable Play Services" steps did it for me @khaykov and then I verified that the fix works, nice!

LGTM!

**Pull request merged**
