### PR TITLE
Issue/8482 privacy settings crash

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add the _**Crash reports**_ item to _**Privacy settings**_ similar to the [WooCommerce crash reports privacy settings feature](https://github.com/woocommerce/woocommerce-android/pull/443) as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8482.  See the screenshots below for illustration.

privacy_settings

#### Note
The WordPress implementation differs from the WooCommerce app in a few ways.  The default background was used rather than the card background as shown in the WooCommerce app.  The preference dividers were left as full-width rather than shortening them as shown in the WooCommerce app.  Both of those were excluded from these changes so that _**Privacy settings**_ would remain consistent with the rest of the app

### Test
Crashlytics are not enabled for debug builds so these changes must be tested on a release build or [this `if` statement](https://github.com/wordpress-mobile/WordPress-Android/blob/d0200999a091f3d3c6e0ed0bbfc39975092bae3f/WordPress/src/main/java/org/wordpress/android/util/CrashlyticsUtils.java#L19-L21) must be commented out while running a debug build.  The steps below assume the latter.

0. Set breakpoint [here](https://github.com/wordpress-mobile/WordPress-Android/blob/d0200999a091f3d3c6e0ed0bbfc39975092bae3f/WordPress/src/main/java/org/wordpress/android/util/CrashlyticsUtils.java#L25).
1. Launch WordPress app.
2. Notice `hasUserOptedOut` is `false`.
3. Go to ***Me*** tab.
4. Tap ***App Settings*** item.
5. Tap ***Privacy Settings*** item.
6. Notice updated layout as shown in screenshots above.
7. Notice _**Crash reports**_ item is enabled.
8. Tap _**Crash reports**_ item to disabled it.
9. Exit WordPress app.
10. Launch WordPress app.
11. Notice `hasUserOptedOut` is `true`.
12. Go to ***Me*** tab.
13. Tap ***App Settings*** item.
14. Tap ***Privacy Settings*** item.
15. Notice _**Crash reports**_ item is disabled.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
The [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/WordPress-Android/blob/d0200999a091f3d3c6e0ed0bbfc39975092bae3f/RELEASE-NOTES.txt) document was not updated since the release with the [original feature pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7768) did not include notes.  However, this pull request does include user-facing changes.  I'll update the release notes if the reviewers see fit.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Hey @theck13 !

At first glance I was a little confused about the last row, I only realised it was related to the option above after I checked the Woo screenshot. I think this text can work as descriptive text to the "Crash reports" row with a little copy tweak to follow material guidelines for settings descriptions:

last_row


Could we can also refine the UI a bit in this PR? Instead of the buttons being flush with the text and box edge we can add some spacing, see below for illustration:

spacing

**Comment by theck13** [comment]
Standard preferences don't support icon, title, and summary.  We can set any combination of two, but not all three.  In order to get all three for **_Crash reports_**, we would need to create a custom preference.  I tried to minimize these changes by just adding the crash reporting feature and keeping the preferences consistent.  Preferences across the app could use an update, but that would be a much bigger task and probably its own project.

I added the `8dp` top and bottom margin to the button in 1294263.  See the screenshots below for illustration.

privacy_settings_button

**Comment by theck13** [comment]
I was wrong.  Standard preferences *do* support icon, title, and summary.  The layout used by most WordPress preferences, `wp_preference_layout`, does not.  I created a new `wp_preference` layout in 663810d and updated the _**Crash reports**_ preference in 167532b and 0a7014f.  See the screenshots below for illustration.

privacy_settings_layout

Also, I noticed the preference buttons have built-in padding so we may want to remove the `8dp` top and bottom margin added in 1294263.  You can see the built-in padding by tapping a button while the layout bounds are displayed.  See the screenshots below for illustration.

privacy_settings_button_pressed

**Comment by SylvesterWilmott** [comment]
Thanks @theck13 

Looks good!

>I noticed the preference buttons have built-in padding so we may want to remove the 8dp top and bottom margin added in 1294263.

I see the padding there now, but it's fairly small is it 4dp? Can we subtract the built in padding from the padding we've added?

**Comment by theck13** [comment]
> I see the padding there now, but it's fairly small is it 4dp?

Close.  It's 6dp.

> Can we subtract the built in padding from the padding we've added?

I updated the `8dp` top and bottom margin of the button to `2dp` in b63f625.  See the screenshots below for illustration.

privacy_settings_button_pressed_2

**Comment by SylvesterWilmott** [comment]
This looks good @theck13 thanks!

Subtle edit but it makes a difference

**Comment by theck13** [comment]
Thanks, @SylvesterWilmott!  If it's good to merge design-wise, please remove the `[Status] Needs Design Review` label.

**Comment by theck13** [comment]
@nbradbury, this pull request is ready to be reviewed again.  These changes were added since your approval.
- Add top and bottom margin to button in learn more preference layout (1294263)
- Add themed layout for preferences (663810d)
- Update crash reports preference layout and summary in app settings (167532b)
- Update crash reports preference summary string resource (0a7014f)
- Add padding to start of switch view in wp switch preference class (01432f3)
- Update top and bottom margin of button in learn more preference layout (b63f625)

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
