### PR TITLE
Issue/6036 update heading menu

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update heading menu format button in the editor format toolbar as described in  as described in https://github.com/wordpress-mobile/WordPress-Android/issues/6036.

#### Note
The heading menu icon will not change based on the the heading applied or selected until https://github.com/wordpress-mobile/AztecEditor-Android/pull/377 is merged and the version containing those changes is included in the [WordPressEditor dependencies](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/build.gradle#L54).

### CODE REVIEW

**Comment by hypest** [comment]
Hey @theck13 , tried out the PR with manually compiling against latest Aztec lib develop. Here are a couple of things I noticed:

1. When in html mode, the heading icon doesn't look disabled. It doesn't respond to clicks (so, it is normally behaving as disabled) but the color is not dimmed.

2. The icon size for the headings seem a bit too small, at least compared to the rest of the icons on the format bar. Is this how it should look? 
aztec-format-headings-too-small

**Comment by theck13** [comment]
> When in html mode, the heading icon doesn't look disabled. It doesn't respond to clicks (so, it is normally behaving as disabled) but the color is not dimmed.

Good catch!  I was using `format_bar_button_heading_*` rather than `format_bar_button_heading_*_selector`.  That was fixed in https://github.com/wordpress-mobile/AztecEditor-Android/pull/381.

> The icon size for the headings seem a bit too small, at least compared to the rest of the icons on the format bar. Is this how it should look?

Yep.  Check out the icons at http://automattic.github.io/gridicons/ and you'll see that's as expected due to the shape of the H1, H2, H3, H4, H5, and H6 icons.

**Comment by hypest** [comment]
> Good catch! I was using format_bar_button_heading_* rather than format_bar_button_heading_*_selector. That was fixed in wordpress-mobile/AztecEditor-Android#381.

Thanks for the fix @theck13 , confirmed looking disabled as expected.

> Yep. Check out the icons at http://automattic.github.io/gridicons/ and you'll see that's expected due to the shape of the H1, H2, H3, H4, H5, and H6 icons.

I see. I still think that the heading icons size is not well balanced in respect to the rest on the format bar. What do you think @iamthomasbishop ?

I will merge this PR though anyway since, the size is something we can work on in a separate PR. :shipit:

**Comment by iamthomasbishop** [comment]
@hypest I will probably do another iteration on these icons, as I wasn't 100% sure how they'd line up on the grid and relative sizing. I might be able to bump them up a bit but not sure if they'll line up on the grid well then using our guidelines (2pt lines, etc).

**Pull request merged**
