### PR TITLE
[Gutenberg] Audio block capability now enables/disables media upload's media sources

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes  https://github.com/wordpress-mobile/gutenberg-mobile/pull/3523

`WordPress iOS` wordpress-mobile/WordPress-iOS#16533
`Gutenberg Mobile` wordpress-mobile/gutenberg-mobile#3523
`Gutenberg` https://github.com/WordPress/gutenberg/pull/31966

## Description

This PR checks to see if the user's site is on a free, paid or self hosted plan and as such, the relevant media upload options are shown. 

| Free Plans      	| Paid Plans              	| Self Hosted             	|
|-----------------	|-------------------------	|-------------------------	|
| Insert from URL 	| Insert from URL         	| Insert from URL         	|
|        -        	| Choose from device      	| Choose from device      	|
|        -        	| WordPress Media Library 	| WordPress Media Library 	|

### WP.com sites

**Note:** 

Support for Audio block audio uploads, and access to the media library is restricted to sites that are on a paid plan.

#### Free Plan
1. Create a new post. 
2. Add the Audio block. 
3. Notice that only the `Insert from URL` option is available as users aren't able to upload audio on free plans. 

#### Paid plan
1. Create a new post. 
2. Add the Audio block. 
3. Notice that all media options are available as users are able to upload audio on paid plans. 

Free Plan | Paid Plan 
--------|-------
 <kbd></kbd> |   <kbd></kbd>

### Self hosted sites

1. Create a new post. 
2. Add the Audio block. 
3. Notice that all media options are available as users are able to upload audio on self hosted sites. 

<kbd></kbd>

## Regression Notes
1. Potential unintended areas of impact

The blocks Cover, File, Gallery, Video, Media & Text all utilise the `media-upload` component that was modified. Verify that these blocks function as expected and all the relevant options are still shown for them in both paid and free plans. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
There are existing tests that are doing uploads via the WP media library and the file system so if there was an issue with the implementation those tests would fail. 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jd-alexander** [comment]
This PR will be updated once https://github.com/wordpress-mobile/gutenberg-mobile/pull/3548 is merged in so a final `Gutenberg Mobile PR` wordpress-mobile/gutenberg-mobile#3523 can be generated for testing on both platforms.

**Comment by fluiddot** [comment]
> This PR will be updated once [wordpress-mobile/gutenberg-mobile#3548](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3548) is merged in so a final `Gutenberg Mobile PR` [wordpress-mobile/gutenberg-mobile#3523](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3523) can be generated for testing on both platforms.

@jd-alexander Heads up that the [PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3548) is already merged

**Comment by jd-alexander** [comment]
Lint failures are unrelated to the changes I made. Not sure what is causing them. I will check that out tomorrow.

**Comment by fluiddot** [comment]
> Lint failures are unrelated to the changes I made. Not sure what is causing them. I will check that out tomorrow.

This happened to me too on a different PR and after restarting the job it worked 🤷‍♂️ . I'll restart it for you if you don't mind just in case it works.

**Comment by hypest** [comment]
Perhaps needs update from develop @jd-alexander ?

**Comment by jd-alexander** [comment]
> Perhaps needs update from develop @jd-alexander ?

Indeed! I am going to give that a go shortly.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

Approved via https://github.com/WordPress/gutenberg/pull/31966#pullrequestreview-673060329.

**Comment by fluiddot** [comment]
The installable build is failing because the tab `v1.55.0-alpha1` contains changes from GB-mobile that require [this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14503) to be merged first.

**Comment by fluiddot** [comment]
> The installable build is failing because the tab `v1.55.0-alpha1` contains changes from GB-mobile that require [this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14503) to be merged first.

Heads up that this PR can't be merged at this stage because the Gutenberg Mobile reference contains changes from this [other PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14503) that neither can't be merged due to the lack of the changes from this one 🙃 .

I pinged @SiobhyB, as the author of [that PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14503), and we decided to merge these changes there, here is the [merge commit](https://github.com/wordpress-mobile/WordPress-Android/pull/14503/commits/3e2d759778dce05a2f56f3bd95c9aab42f55b488). Once that PR gets merged, this will be automatically closed.

**Pull request merged**
