### PR TITLE
Merge/release 17.1 beta 1 into develop

### PR DESCRIPTION
**Pull request by JavonDavis**

### CODE REVIEW

**Review by jkmassel — APPROVED** [review]
The code seems ok, but there are a surprising number of commits around adding the new version number?

Just double-checking that all is good there – if so, good to merge

**Review by oguzkocer — CHANGES_REQUESTED** [review]
@JavonDavis Shouldn't the `fastlane-plugin-wpmreleasetoolkit` version be `0.17.0`? As part of https://github.com/wordpress-mobile/WordPress-Android/pull/14407 it was changed to `0.17.0` in c7ac829b774fb3f80f12e745b2a6c1ba40d9a4f1, but then a mistake happened in b565b4c929fd1ee0d49ed6a290ae1f30724264b6 and it was changed to `0.15.0`. Now it looks like it's set to `0.16.0`.

I am not 100% sure which version is the right one, but I think it'd be good for you to confirm it before we merge it in. So, just to make sure you see it, I'll mark this as `Request Changes`.

**Comment by JavonDavis** [comment]
> I am not 100% sure which version is the right one, but I think it'd be good for you to confirm it before we merge it in. So, just to make sure you see it, I'll mark this as Request Changes.

Thanks @oguzkocer let me double check here because locally things look good on my end

**Comment by JavonDavis** [comment]
@oguzkocer Ahhh so a new version of the gem actually needs to be created, at the moment 0.16 is still the latest version, since all that was created was a new tag for 0.17, I've never pushed a new version of our gem there so let me see if I can update it there.

**Comment by oguzkocer** [comment]
@JavonDavis I just wanted to make sure you were aware of it and double check that the current code is correct. Once you give the 👍, I'll approve the PR :)

**Review by oguzkocer — APPROVED** [review]

**Pull request merged**
