### PR TITLE
Make new Posts status `draft` by default

### LINKED ISSUE #8570: Drafts Automatically & Unintentionally Publishing
I'm not too sure if this is the best place to report an issue, but there's something which seems to have happened more than once, and it's rather frustrating.

### Expected behaviour

Drafts should remain drafts when media is uploaded to the Media Library, but the media should be uploaded regardless

### Actual behaviour

A recent draft is published when media is uploaded to the Media Library, even though there was no modification made to that post. 

### Steps to reproduce the behaviour

1. Create a new blog post and upload an image
2. Close the app (do not save the blog post as a draft, but do not click "Publish" either)
3. You can wait if you wish (there was a matter of days between step 2 and step 4 in the times which this has happened to me)
4. Enter your Gallery and hold an item, then click "Share" or the equivalent
5. Select "WordPress" and "Add to Media Library"
6. Draft turns into a published post

### Additional Context

-Samsung Galaxy Tab S2 SM-T713
-Version 11.0 of WordPress app 
-Using the Beta editor
-Activity log, unfortunately I can't upload directly to GitHub for some reason :(
https://clubpenguinmountains.files.wordpress.com/2018/11/screenshot_20181107-182850.jpg

An issue similar to this occurred in February 2018 too with my blog, and if I recall correctly, it was this exact same thing too which provoked the post to publish unintentionally. I'm assuming that because of this, it is a bug with the WordPress app, as it's never happened through a web browser, including with Calyspo and the Classic Editor. I'm able to recreate this on a test site too.

Thanks! :)

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #8570 and possibly other issues by making a Post satus `DRAFT` by default.

- in 50a5d30c977798074da2f875e4a1569f7085b099 we only changed the default `PUBLISHED` state to `DRAFT`
- in 7e20bbff48f5abaf4b316fce8ae1ababcb32a7ad we make the behavior for `SCHEDULED` posts consistent with FluxC handling of `future` Posts (see [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/post/PostStatus.java#L40-L46) and [comment here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/post/PostStatus.java#L16))
- finally, introduced this particular case handling when the user has a scheduled new draft that hasn't yet been saved online, and the user taps on `Save as draft`. Given uploading as is would mean to actually save a Post that is being scheduled (and that should/can be done through the SCHEDULE button), if the user taps on `Save as draft` we should assume they just want to save the draft (as opposed to publishing / scheduling its publishing for the future). So, introduced this behavior in cccc1c4e839291c03d5b668cc2718a118bb30444.

The behavior implemented in this PR should stick to what was defined before and is best defined by the test cases as follow. In particular, the test steps in these PRs should still be valid:
- https://github.com/wordpress-mobile/WordPress-Android/pull/7583
- https://github.com/wordpress-mobile/WordPress-Android/pull/7606

Adding to the tests described in #7583 the following test cases for the `SCHEDULED` state:
#### CASE D: start a draft, edit post settings to schedule it, schedule
1. start a draft
2. enter some title /text
3. tap on Post settings on the overflow menu
4. change the `Publish` value from `Immediately` to a point in the future (i.e. tomorrow)
5. Tap on SCHEDULE
6. observe the Post is uploaded and it shows state "scheduled" in the Posts list once uploaded.

#### CASE E: start a draft, edit post settings to schedule it, then save as draft
1. start a draft
2. enter some title /text
3. tap on Post settings on the overflow menu
4. change the `Publish` value from `Immediately` to a point in the future (i.e. tomorrow)
5. tap on `save as draft` on the overflow menu icon
6. should behave the same as CASE C above (it should just upload the draft, as that's what the user intended to do).

## General / App dismissal test cases
And now, the whole set of test cases that take into account app dismissal (as explained in issue #8570):
#### CASE A: draft and exit
1. start a draft
2. enter something
3. tap back
4. draft should be saved.

#### CASE B: draft, add media, and exit
1. start a draft
2. enter something
3. add media
4. tap back
5. media should still get uploaded and draft should be saved once finished uploading.

#### CASE C: draft, add media, publish
1. start a draft
2. enter something
3. add media
4. tap PUBLISH, accept confirmation
5. media should still get uploaded and Post should be published once finished uploading.

#### CASE D: draft, add media, schedule
1. start a draft
2. enter something
3. open post settings and change publish immediately to a date in the future to schedule
4. add media
5. tap SCHEDULE, accept confirmation if any
6. media should still get uploaded and Post should be saved as SCHEDULED once finished uploading.

#### CASE E: start draft, dismiss app
1. start a draft
2. enter something
3. tap on the recent apps list and dismiss the WP app
4. open the app again and go to Posts list
5. verify the Post has been saved as a local draft

#### CASE F: start a draft, add media, dismiss app
1. start a draft
2. enter something
3. add some media from device to start uploading
4. tap on the recent apps list and dismiss the WP app
5. open the app again and go to Posts list
6. verify the Post has been saved as a draft, media continued to upload and is OK in the Post

#### CASE G: start a draft, add media, tap PUBLISH, dismiss app
1. start a draft
2. enter something
3. add some media from device to start uploading
4. tap PUBLISH and accept confirmation dialog if any - the app will go back to previous screen while uploading media and enqueing Post to upload in the background async.
5. tap on the recent apps list and dismiss the WP app
6. open the app again and go to Posts list
7. verify the Post has been saved as PUBLISHED, media continued to upload and is OK in the Post

#### CASE H: start a draft, add media, wait for it to upload, dismiss app
1. start a draft
2. enter something
3. add some media from device to start uploading, and wait until it finishes uploading
4. tap on the recent apps list and dismiss the WP app
5. open the app again and go to Posts list
6. verify the Post has been saved as a draft, media/Post resume uploading if needed, and media is OK in the Post

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mzorz** [comment]
Sounds good @khaykov, thanks for taking the time to test everything in the list! It's quite a lot of use cases. I pinged @hypest to take a look as well, also summoning @daniloercoli who might want to take a look as well. :+1:

**Comment by hypest** [comment]
> Not sure if @hypest wants to take a look before merging this one!

Yeap, was trying to get to this yesterday and didn't make it. It's still on my plans for today. I'd like to get the insight this PR offers, to say the least.

**Comment by hypest** [comment]
Hey @mzorz , I think I found an issue not happening on `develop`:

1. Start a new post with Aztec editor (for simplicity to not involve Metro et al for Gutenberg)
2. Tap on the "PUBLISH" appbar button and accept any popups. The post will not be published of course since it's empty.
3. Input a title and some content
4. Tap on the "Save as draft" from the 3-dots menu
5. Observe the snackbar for "Your post is uploading" but no uploading actually taking place 💥

**Comment by mzorz** [comment]
> 1. Start a new post with Aztec editor (for simplicity to not involve Metro et al for Gutenberg)
> 2. Tap on the "PUBLISH" appbar button and accept any popups. The post will not be published of course since it's empty.
> 3. Input a title and some content
> 4. Tap on the "Save as draft" from the 3-dots menu
> 5. Observe the snackbar for "Your post is uploading" but no uploading actually taking place 💥

addressed this one in 0648bf1042 - what was happening is that we now set the status to `PUBLISHED` following the intent of the user (i.e. as they tap on the `Publish` button), but failed to leave the state of the `mPost` object as it was before, after updating the object with the current content/title on the Editor's screen and verifying we can't publish it (because of it being empty).

**Comment by mzorz** [comment]
This one should be ready for another round @hypest 🙇

**Comment by mzorz** [comment]
Thank you!

**Comment by torres126** [comment]
Thanks all for fixing this!

**Pull request merged**
