### PR TITLE
Use the Gutenberg-mobile binary JS bytecode

### PR DESCRIPTION
**Pull request by hypest**
This is a draft PR to enable testing https://github.com/wordpress-mobile/gutenberg-mobile/pull/2003 from gutenberg-mobile. The APK produced will load up a binary JS bytecode version for the block editor, resulting in better boot performance.

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
Tried the e2e tests locally but it's the `testPublishFullPost` failing for me, not the `testPublishSimplePost` as on CI. I'll rerun the connected tests on CI.

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.6` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.5` branch which will be available later today and update the milestone for the issue accordingly.

**Comment by oguzkocer** [comment]
Hi there! I will be freezing 14.6 in a little bit, to this PR is being bumped to 14.7. If you need this to be shipped in 14.6, please update the base branch to `release/14.6` and give me a heads up when the PR is merged so I can release a new beta.

**Comment by oguzkocer** [comment]
Hi there! `14.7` is being frozen, so this PR is being bumped to `14.8`. If these changes _have to_ be shipped with `14.7`, please target `release/14.7` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

_P.S: I am still working on the messaging for these bumps, so please let me know if you have any questions/concerns/feedback._

**Comment by oguzkocer** [comment]
Hi there! `14.8` is being frozen, so this PR is being bumped to `14.9`. If these changes _have to_ be shipped with `14.8`, please target `release/14.7` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Extra note:**
@hypest Looks like this PR is being bumped for the 4th time, should we either remove the milestone or add one that's more reflective of the intention of when it'll be merged?

**Comment by hypest** [comment]
Removed the milestone flagging, at least until this PR comes out of the Draft state, thanks for the suggestion Oguz 👍.

**Comment by hypest** [comment]
No need for this PR anymore, see https://github.com/wordpress-mobile/WordPress-Android/pull/13297#issuecomment-724191816.

**Pull request closed without merging**
