### PR TITLE
Merge editorialized release notes into `release/18.6`

### PR DESCRIPTION
**Pull request by mokagio**
Being unfamiliar with the Android workflow, I prefer to be safe and do this kind of PRs against the release branch first.

I'll take care of opening a `develop <- release/18.6` one if this gets approved.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
- [x] `.txt` and associated `.po` updated

**Comment by AliSoftware** [comment]
Oh shoot, I totally missed that you prepared the PR for me there @mokagio!

I've updated the release notes in `release/18.6` directly myself as usual in https://github.com/wordpress-mobile/WordPress-Android/pull/15533, and only seen your PR and its review request afterwards…
So I guess we can close this now, but thanks for the thoughtful gesture of preparing them for me anyway!

**Comment by AliSoftware** [comment]
Confirmed that your changes here matches mine in `release/18.6` (it's a shame that GitHub doesn't update the "File Changes" tab to reflect this after my new commits on `release/18.6` 🤔 )

```
$ git --no-pager diff origin/update-release-notes-18.6 release/18.6
# empty diff
```

**Comment by mokagio** [comment]
No worries. I should have cross posted this PR in our internal conversations 👍 

The important thing is that the notes got into `develop` 😄

**Pull request closed without merging**
