### PR TITLE
Replace icons with spectrum icons set.

### PR DESCRIPTION
**Pull request by develric**
This changes the app icons set to spectrum icons. As of now, this change is meant to stay in place for a month and then come back to the previous set of icons.

| Scenario | | | | |
|---|---|---|---|---|
| hdpi/api24 |  image | image | image | image |
| xxhdpi/api29 | image | image | image | image |

To test:

Note that the CI built apk builds the Jalapeno variant that has its own set of icons. To test this apk you should build vanilla variant!

- Install vanilla variant on low and high resolution simulators (both with Nougat or below API and Oreo or above API, **the more diverse combinations you can test the better** 😄 ).
- Check the icon is the new one as expected.

## Regression Notes
1. Potential unintended areas of impact
None if properly tested on the various resolutions and API levels threshold.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
4. N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @develric !

I reviewed and tested this PR as per the instructions. Everything LGTM, it is a 👍 from my side.

Just a couple of questions (❓) from my side to make sure we have covered it all:
- `Dark & Light` theme icons set are identical and that is what we want, right?
- `Wasabi & Jalapeno` icons set are not affected and that is what we want, right?

**Comment by develric** [comment]
Hey @ParaskP7 👋 , thanks for the review sir 🙇 !

>- Dark & Light theme icons set are identical and that is what we want, right?
>- Wasabi & Jalapeno icons set are not affected and that is what we want, right?

For both, the answer from my side is yep 😄 ...but just to get an additional confirmation cc @mattmiklic 🙇 (thinking mostly to the dark/light thing)

**Comment by ParaskP7** [comment]
👋 @develric @mattmiklic !

Please let me know when this is ready from your side and I can merge it. 🙏

**Comment by develric** [comment]
thanks @ParaskP7 🙇 , I'm pretty sure about [this](https://github.com/wordpress-mobile/WordPress-Android/pull/16586#issuecomment-1131717657), but happy if we can get a quick follow up from @mattmiklic just in case I'm missing anything (thanks sir 🙇 ).

**Comment by ParaskP7** [comment]
Thanks for the follow up @develric ! 🙏 

I'll do the merge on Monday anyway, so no rush, but it would be good if we get a 👍 from @mattmiklic as well. Else, I'll proceed without it and merge this on Monday.

**Comment by develric** [comment]
...also I do not think we never used a different set of icons for dark mode 🤔 ...so fair enough thanks 🙇

**Comment by mattmiklic** [comment]
Everything looks good here. 🚢 

I didn’t know we can do separate light and dark mode icons. Something for us to consider the next time we do an icon refresh!

**Pull request merged**
