### PR TITLE
Issue/6132 update promo dialog

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update editor promotion dialog layout as described in https://github.com/wordpress-mobile/WordPress-Android/issues/6132 and add editor footer preference to App Settings as described in https://github.com/wordpress-mobile/WordPress-Android/issues/6133.  The footer interface differs from the issue mockup to allow for the minimum 48dp touch target specified by [Material guidelines](https://material.io/guidelines/usability/accessibility.html#accessibility-style).  See the screenshots below for example.

#### Promotion Dialog
dialog

#### Setting Footer
setting

### Test
***Promotion Dialog***
1. Comment out [condition](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L267) to always show dialog.
2. Go to ***Sites*** tab.
3. Notice new editor promotion dialog.
4. Dismiss dialog with ***Not Now*** or back button.
5. Go to another tab.
6. Go to ***Sites*** tab.
7. Notice new editor promotion dialog.
8. Tap ***Try It*** button.
9. Notice editor is launched and confirmation snackbar is shown.
10. Tap ***Settings*** in snackbar.
11. Notice ***App Settings*** is shown with ***Beta*** editor selected.
12. Tap back arrow in toolbar.
13. Tap ***What's new?*** link in promotion dialog.
14. Notice release notes interface.
15. Tap ***Share link*** action.
16. Notice sharing interface.
17. Tap ***Report bug*** action.
18. Notice Helpshift conversation interface.

***Setting Footer***
1. Go to ***Me*** tab.
2. Tap ***App Settings*** item.
3. Notice footer preference in ***Editor*** section.
4. Tap footer preference.
5. Notice release notes interface.

#### Note
By forcing the promotion dialog to be displayed on every view with Step 1 in the ***Promotion Dialog*** test above, multiple dialogs will be shown while performing the tests.  That behavior is only for testing purposes.

### CODE REVIEW

**Comment by nbradbury** [comment]
If I rotate to landscape, the buttons at the bottom of the dialog are cut off.

screenshot_1498940282

**Comment by nbradbury** [comment]
Does this separator line need to be here? It makes it look disconnected from the **Editor** group.

screenshot_1498940348

**Comment by nbradbury** [comment]
When I tapped "Editor release notes and bug reporting," I saw a blank screen for a few seconds before the web page loaded. It made me think the feature was broken. 

When the web page appeared, it was jarring. I know it's unfinished, but I just wanted to see what's new and suddenly I'm looking at a WordPress.org page with all sorts of stuff on it unrelated to what's new in the editor (Register, Login, Search, Sidebar, etc.).

Any chance we can ditch the idea of loading a web page and show the content in a simpler, native way?

screenshot_1498940482

screenshot_1498940525

**Comment by theck13** [comment]
> If I rotate to landscape, the buttons at the bottom of the dialog are cut off.

I added a layout with a scroll view for landscape orientation in 3d870c70b08992ea9835b8927c93065eb72ad771.

> Does this separator line need to be here? It makes it look disconnected from the **Editor** group.

That divider is built in to the `PreferenceFragment`.  I can do something like this, but it will remove ***all*** dividers as shown in the screenshot below the code.

```java
@Override
public void onResume() {
    View rootView = getView();
    ListView list = (ListView) rootView.findViewById(android.R.id.list);
    list.setDivider(null);
    super.onResume();
}
```

dividerless

I would love to update the preference screens with the card interface as shown in the design guidelines screenshot below.  That would help eliminate the visual confusion the divider causes.

cardlike

> Any chance we can ditch the idea of loading a web page and show the content in a simpler, native way?

I think using an instance of the Reader which would allow the user to tap the back arrow and return to the ***Sites*** tab with the dialog shown would be ideal.  Is that possible?

**Comment by nbradbury** [comment]
> I added a layout with a scroll view for landscape orientation in 3d870c7.

Rather than adding a separate layout which requires the user to scroll, what do you think about simply hiding the image in landscape?

screenshot_1498950582

**Comment by nbradbury** [comment]
> That divider is built in to the PreferenceFragment. I can do something like this, but it will remove all dividers as shown in the screenshot below the code.

Oh, yuck. Given this, I'd say leave it as-is.

**Comment by nbradbury** [comment]
> I think using an instance of the Reader which would allow the user to tap the back arrow and return to the Sites tab with the dialog shown would be ideal. Is that possible?

i *think* that would be possible, but what about the bug report icon?

**Comment by theck13** [comment]
> Rather than adding a separate layout which requires the user to scroll, what do you think about simply hiding the image in landscape?

That works for me, but I differ to @iamthomasbishop on that one.

> i *think* that would be possible, but what about the bug report icon?

Can we not extend the Reader view and have a custom action menu?  If not, what about a floating button for the bug report action?

**Comment by nbradbury** [comment]
> Can we not extend the Reader view and have a custom action menu? If not, what about a floating button for the bug report action?

We could do that, but it adds technical debt to the reader simply to support a one-time "what's new" feature. Really, I think all that's needed here is something like the WHAT'S NEW section in Google Play for an app - just a basic bullet list touting the cool new things.

**Comment by iamthomasbishop** [comment]
> Rather than adding a separate layout which requires the user to scroll, what do you think about simply hiding the image in landscape?

@nbradbury @theck13 I’m okay with this. We ended up doing the same on iOS.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
