### PR TITLE
Site Creation Iteration 1.1

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR addresses some feedback we have gotten during testing phase of new site creation flow per @SylvesterWilmott's suggestions. I am opening an early draft PR so it's easier to discuss and showcase changes. Here are the changes so far:

1. 1791d1fd8f2306373e357ab23ad83cd9f3913fba updates a layout's name to be more generic. I think we forgot to do this during the initial implementation.
2. dd804ec2096243c6867f33c09460ac1e80592146 adds shadow to search input for vertical and domains pages. [before](https://cloudup.com/iqv3xnhELxx) - [after](https://cloudup.com/ct4-QKLKvmG)
3. 822373b226ddcace156822b4f343d1fccba780c2 removes auto-focus from all site creation pages. [before](https://cloudup.com/cPq7k-xyRqr) - [after](https://cloudup.com/cyw9cPq5JD1)
4. 38b1a5b8a4b8d911ba6e7e5a2aec5aba1767f678 adds subtitle to preview page. I didn't have the specs of the design for this (especially the landscape one) so I threw in some stuff which probably needs to be updated. [portrait](https://cloudup.com/c3NsjzZN0Am) - [landscape](https://cloudup.com/ctL_DbV3UDA)
5. b19f9b7478abc6ce1d0cdf57953a8c5165d9beba fixes an AS warning for `getScreenTitle` methods. Please see the commit message for more details.
6. 102f8f91effc69b5de9e27880aa62ac915f8c186 fixes the unit tests for auto-focus changes made in 822373b226ddcace156822b4f343d1fccba780c2. I initially forgot about these.
7. 2bbdd685c73f0a8786b4c305361ad87b66f3d81e merges `develop` into this branch to get the `sites/new` endpoint change (this may not be necessary, but since I'll be doing a lot of tests in this branch, it helps to have the latest version to see if we missed anything)
8. 54f25919ef4afb3444b159e1e07a28dcce155818 refactors all the site creation header layouts. By utilizing styles it makes it easier to be consistent across screens and identify the differences between each one. I am still not 100% happy with it, but I feel it's good enough and further work will result in diminishing returns.
9. 9cb54c668d7ffa6503c1c25327279b16a1e342c1 fixes the getScreenTitle for domains fragment. I forgot to do as part of (5).
10. c5bd296e169d8f1fbbfe78eaf9447ce196b89700 changes site info fragment to use the common site creation header.
11. fa6dfddfc6c21c2102efd7b2621b1f053b0c6777 changes the spacing between title and subtitle in site creation headers to be `4dp` instead of `8dp`. I forgot to do this as part of (10).
12. 037caa7b43c78e8ff90ba9958a2a8cb4dea4028b removes the space between search field and search results for verticals and domains screens.
13. ff072a0378481fa1b69d6c71c1db43f095930a45 adds start and end margins to vertical and domains screens and updates relevant margins.
14. ff072a0378481fa1b69d6c71c1db43f095930a45 changes the site preview title to be 20sp.
15. ba77b02960eab89a6c7904ae8eb2b1d30a22c0b3 updates the release notes.
16. bd78578bedc372185546fbae694fb22e62a2e54f moves the domain results to 8dp to the left. 
17. 43dc9a2ab8e87eb3ee7fc2afa571fc6e5a4d4bc9 removes the dividers from verticals and domains pages. https://cloudup.com/cVtzIOqa9ya
18. db08c4d0b45a250f53ae2d0c5c9da3a3b98097d5 removes the divider from the custom vertical which I of course forgot to do and also fixes the lint issue (for unused resource)

Here is a collection of screenshots for the screens that changed the most (especially after commit 7): https://cloudup.com/cdyWUHYHTq4

**To test:**
* Since most of these changes are design related, just going through the flow a couple times should be enough. Please keep an eye for the changes mentioned in this PR and let me know if anything seems amiss.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`

### CODE REVIEW

**Comment by oguzkocer** [comment]
@malinajirka This PR should be to ready to review now. I really suggest reviewing the PR commit by commit as explained in the description. The changes are pretty small but collectively they seem much bigger.

Also, sorry about some minor one line fixes, we were chatting with @SylvesterWilmott on Slack to get this done and I kept missing some things or some minor other things came up. I didn't want all of it to be a one huge commit, so this was the alternative. (committing as we go)

Let me know if there is anything that's not clear.

**Comment by SylvesterWilmott** [comment]
Looks great @oguzkocer 

There was a couple of things I noticed while going through it again:

- The custom category on the verticals screen still has a bottom divider
- We should add a full width divider on top of the custom category (ideally we would add this to the last item in the search results list so it's not visible when displaying custom category only)
Screenshot 2019-03-18 at 08 57 46

- We can now remove the shadow from all the bottom bars (with the button) since nothing passes behind these bars anymore

**Comment by malinajirka** [comment]
Thanks @oguzkocer for making all these changes! The code looks good and I haven't noticed any issues.

>Also, sorry about some minor one line fixes, we were chatting with @SylvesterWilmott on Slack to get this done and I kept missing some things or some minor other things came up. I didn't want all of it to be a one huge commit, so this was the alternative. (committing as we go)

No reason to apologize, I definitely prefer multiple small commits than one huge:).

>The custom category on the verticals screen still has a bottom divider

If I recall correctly and looking at the code the custom category never had a bottom divider. But I can see it on the screenshot as well. 😕 It's not there when I run the app from the code though.

>We can now remove the shadow from all the bottom bars (with the button) since nothing passes behind these bars anymore

I think the content can still pass behind on small devices.
bottom

Notes
The transition animation between screen still doesn't work, might be worth fixing (we don't need to do it in this PR). Wdyt?

Is anyone working or planning to work on these changes on iOS?

cc @SylvesterWilmott

**Comment by malinajirka** [comment]
I've partially reverted https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/43dc9a2ab8e87eb3ee7fc2afa571fc6e5a4d4bc9 in https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/cddb531ed578ebbd972428b9fb396cb3775fbf3d
+ I updated the logic when we show the divider
+ I've removed the start margin so the divider is full-width

divider

>The custom category on the verticals screen still has a bottom divider

Oguz removed the divider in https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/db08c4d0b45a250f53ae2d0c5c9da3a3b98097d5. Disregard my comment from yesterday.

I'll wait for your input @SylvesterWilmott regarding 
- shadow for the bottom bars
- slide in/out animation during screen transition (there is no animation at the moment)

**Comment by SylvesterWilmott** [comment]
Thanks @malinajirka, Divider looks good!

>I think the content can still pass behind on small devices.

I stand corrected. Let's leave the shadow there in that case.

>slide in/out animation during screen transition (there is no animation at the moment)

This would be a bonus but it certainly not critical

**Comment by malinajirka** [comment]
All the changes which haven't been reviewed yet (@SylvesterWilmott has done the design review)

As commented [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9410#issuecomment-474370806) I've partially reverted https://github.com/wordpress-mobile/WordPress-Android/commit/43dc9a2ab8e87eb3ee7fc2afa571fc6e5a4d4bc9 in https://github.com/wordpress-mobile/WordPress-Android/commit/cddb531ed578ebbd972428b9fb396cb3775fbf3d
- I updated the logic when we show the "custom vertical" divider
- I've removed the start margin so the "custom vertical" divider is full-width (this is technically reverted in https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/cda02cb40ae14576b5df4bd703d807fb1b9700e7)

Changes made in https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/cda02cb40ae14576b5df4bd703d807fb1b9700e7
- Shadow is removed from the search input
- 8dp margins on the search and results is removed
- Search transitions all the way to the top of the view
- Search input has a bottom border (divider)
- add start/end margins to the "custom vertical" divider 
- I also added "animateLayoutChanges" to the search box (I've discussed it with Sylvester - even the slow disappearing effect on the clearAllButton and he agrees it looks fine)

I've fixed the transition animation (slide in/out) between screen in https://github.com/wordpress-mobile/WordPress-Android/pull/9410/commits/6fb13cf51ed95f157af70bc630628a219249c72b

ui-updates

@oguzkocer Would you mind reviewing these changes - it doesn't make much sense to ask someone else for the review since you know the codebase.

**Comment by oguzkocer** [comment]
@malinajirka Everything looks good, there is just a `*` missing in the release notes I'll fix right now and then we can merge this. Since I opened the PR, it'd be great if you can approve and merge it instead. Thanks!

**Pull request merged**
