### PR TITLE
Rename M3Theme to AppThemeM3

### PR DESCRIPTION
**Pull request by nbradbury**
This PR renames `M3Theme` to `AppThemeM3` to make it more consistent with the existing `AppTheme`. There's really nothing to test - it's just a simple rename.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by dcalhoun — APPROVED** [review]
Make sense to me, I had wondered why we hadn't aligned the names. 

One thought: Would it be better to rename the old `AppTheme` to `AppThemeDeprecated`, and rename `M3` → `AppTheme`? Doing so might mitigate confusion regarding which "AppTheme" is the de facto. 

Alternatively, we could rename both to include a incrementing number—`AppThemeM2` and `AppThemeM3`.

**Comment by nbradbury** [comment]
> Alternatively, we could rename both to include a incrementing number—`AppThemeM2` and `AppThemeM3`

I like this idea! If it's okay with you, I'd prefer to make that change in a separate PR.

**Comment by dcalhoun** [comment]
> If it's okay with you, I'd prefer to make that change in a separate PR.

Of course! 🚀

**Pull request merged**
