### PR TITLE
Jetpack Section: Improve server creds clarity

### LINKED ISSUE #14666: Improve Server Credentials Clarity
We got feedback that it was easy to miss the line about server credentials, and it was not clear it was actionable.

I cannot reproduce the current version on Android to verify the current appearance, but here's the new design with hopefully minor tweaks. 

- Again I couldn't find an example of a disabled button currently in the app to use. But if we have a disabled state already let's use it. I just took the generic guidelines from https://material.io/components/buttons#contained-button
- Action next to the relevant button
- Plus icon to make it clear there is an action here, and consistent with Calypso
- Using normal text colour, but with an interactive green part highlighted

server credentials android

### PR DESCRIPTION
**Pull request by ashiagr**
Task #14666

This PR improves Server Credentials message clarity with an additional plus icon, interactive highlighted (`colorPrimary`) text followed by a normal text on the Scan and Threat Details screen. 

To test:

1. Install the Jetpack app.
2. Login with an account having a site w/o server credentials e.g. [pressable-jetpack-daily-scan-without-server-creds](http://pressable-jetpack-daily-scan-without-server-creds.mystagingwebsite.com/).
3. Switch to the above site from the site picker and go to the Scan screen from the My Site tab.
4. Notice that "Enter your server credentials to fix threat." is present with an interactive part and a plus icon below the "Fix threat" button.
5. Click on the plus button or the green-colored highlighted text. 
6. Notice that a page is displayed to enter server creds (might need to login).
7. Return to the Scan screen.
8. Click the threat in the threat list on the Scan screen.
9. Notice that the "Threat Details" screen is displayed with the same message below the "Fix threat" button and clicking it opens the same page as on step 6.

~~Note 1: Might need to toggle language to English (United States) as translations already exist for other languages.~~
~~Note 2: Similar string replacements were done earlier here: #13154 and more recently in #14090. I only replaced string values without changing their keys, they were automatically detected and sent to the translators for new translations.~~

a866fcd renames the strings to fix the lint.

Scan screen | Threat Details screen | Scan screen (Dark)  | Threat Details screen (Dark)
-------------|----------------------|---------------------|-----------------------------
jp_enter_server_creds_scan| jp_enter_server_creds_threat| jp_enter_server_creds_scan_dark| jp_enter_server_creds_threat_dark

[Repeat above steps for the WordPress app, notice the same changes are applied to the server creds message (with primary color for WordPress app).]

Scan screen | Threat Details screen | Scan screen (Dark)  | Threat Details screen (Dark)
-------------|----------------------|---------------------|-----------------------------
wp_enter_server_creds_Scan | wp_enter_server_creds_Threat | wp_enter_server_creds_Scan_dark | wp_enter_server_creds_Threat_dark

**Merge Instructions:**

- Wait for design review
- Remove not ready for merge label
- Merge the PR

## Regression Notes
1. Potential unintended areas of impact
WordPress app

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually WordPress app for the "Enter your server credentials to fix threat." message.

3. What automated tests I added (or what prevented me from doing so)
Updated existing tests for the server credentials message and added tests for the plus icon.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — CHANGES_REQUESTED** [review]
👋  thanks for sharing @ashiagr . Cool to see you are doing it on WordPress too, I wasn't even thinking about that! A few minor things

- Do we use underline for interactive elements? I don't remember seeing it before.
- Can you use gridicons-plus-small, rather than gridicions-plus? It looks a little large
- Are we doing this on Backup as well, is that another task?

**Comment by ashiagr** [comment]
Hey Chris 👋! Thanks for the feedback!

Addressed your comments below: 

> Do we use underline for interactive elements? I don't remember seeing it before.

Links inside a `TextView` get an underline by default. There's a way to remove it though. The reason why I left it for this message (even though it wasn't present in the mockup) was to be consistent with the "here to help" link in the description which has an underline below it. The "Terms and Services" link on the login screen has an underline as well, so I wanted to be consistent with that as well. 

terms_of_service

I've not yet removed the underline, will wait for another confirmation from you.

------------------------------------------------------------

> Can you use gridicons-plus-small, rather than gridicions-plus? It looks a little large

Reduced existing icon size to `18dp` in 78d3a6d to match it with the height of the enter server creds message (font `textAppearanceBody1` `16sp` + [minor padding around the text which is difficult to remove](https://stackoverflow.com/a/6594320)). Here are updated screenshots (seem to work well for small and large fonts with the text extending to the next line):

Normal font | Large font 
----------|---------
scan_enter_server_creds_icon | scan_enter_server_creds_icon_multilinetext

PS: I tried using the `gridicons-plus-small` icon, it has larger padding around the icon and [looked either squished (if I reduced icon size) or didn't go well for the text extending to the next line](https://cloudup.com/cuq0ns0f9Vp). 

I can further look into it if it doesn't look good enough 🙂. 

------------------------------------------------------------

> Are we doing this on Backup as well, is that another task?

Yes, there's another task for the Backup screen, the message is not yet added there. It's included in main task #14293 and we'll be adding it very soon. Thank you for checking about it 🙏.

------------------------------------------------------------

**Comment by osullivanchris** [comment]
> Links inside a TextView get an underline by default. There's a way to remove it though. The reason why I left it for this message (even though it wasn't present in the mockup) was to be consistent with the "here to help" link in the description which has an underline below it. The "Terms and Services" link on the login screen has an underline as well, so I wanted to be consistent with that as well.

Thanks for explaining. As (a) its platform convention, and (b) we're doing it elsewhere - lets keep it 👍 

> Reduced existing icon size to 18dp in 78d3a6d to match it with the height of the enter server creds message (font textAppearanceBody1 16sp + minor padding around the text which is difficult to remove). Here are updated screenshots (seem to work well for small and large fonts with the text extending to the next line):

Nice, thanks for investigating. It looks good now. We tend to use divisions of 8dp. So if you want to make it 16dp to be consistent, that's fine too. Either 16 or 18 will be fine visually, so I'll leave it up to you.

> Yes, there's another task for the Backup screen, the message is not yet added there. It's included in main task #14293 and we'll be adding it very soon. Thank you for checking about it 🙏.

Ok good to know!

All good from my side here!

**Review by zwarm — APPROVED** [review]
@ashiagr - All works as expected. Footnote follows the same pattern as other list items. The &lt and &gt worked out in well in the strings.xml. Nice improvements to the tests. 👍 

I have not merged because the `changes requested` is still open. It looks like you addressed them all, but I want to be 100% sure. Feel free to merge after that has been cleared.

**Comment by ashiagr** [comment]
Yes, those were addressed and approved by Chris in this comment: https://github.com/wordpress-mobile/WordPress-Android/pull/14722#issuecomment-849546336. I'll go ahead and merge this PR now.

**Review by osullivanchris — APPROVED** [review]

**Pull request merged**
