### PR TITLE
Parent PR for updating compileSdk 33

### LINKED ISSUE #17790: Update "compileSdk" to 33
`compileSdk` will be updated to `33`. This is the first task of Android 13 migration.
_Internal project thread: pbArwn-5IN-p2_

### PR DESCRIPTION
**Pull request by irfano**
Fixes #17790

This PR,
- Creates a parent branch (`feature/update-compile-sdk-33`),
- Disables all warnings as errors (those warnings will be resolved in separate PRs),
- Resolves errors to make the PR compilable.
---
### Next required tasks that will be merged into `feature/update-compile-sdk-33` via separate PRs:
- [x] Resolve `onBackPressed` warnings: #18019
- [x] Resolve `Intent` and `Bundle` warnings: https://github.com/wordpress-mobile/WordPress-Android/pull/18061
- [x] Resolve `readParcelable` warnings and add `android.permission.POST_NOTIFICATIONS`: https://github.com/wordpress-mobile/WordPress-Android/pull/18068
- [x] Resolve `PackageManager` warnings: https://github.com/wordpress-mobile/WordPress-Android/pull/18077
- [x] Re-enable all warnings as errors
> **Warning** for reviewers
> This PR shouldn't be merged unless all the required tasks above are completed.
---
To test:
- Thoroughly smoke-test both the WordPress and Jetpack apps and see if they both work as expected.

## Regression Notes
1. Potential unintended areas of impact
As this affects a lot of classes, every screen may be impacted. 
- The back navigation should work as it did before, without any crashes,
- Navigation between screens should work without crashing or any data loss,
- Deep links,
- Jetpack migration.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I smoke-tested notifications and screen navigations.

3. What automated tests I added (or what prevented me from doing so)
None. This doesn't add any new functionality to the app.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @irfano !

FYI: I just reviewed the first 8 commits which effectively create this parent `feature/update-compile-sdk-33` branch. Everything seems good to me, so it is a 👍 from my side on those.

PS: I also quickly smoke tested both, the `WordPress` and `Jetpack` apps, and the basics of functionality like posts/pages/stories, or navigating through the basic screens like my site/reader/notifications, and everything seems to be working as expected.

**Comment by pachlava** [comment]
@irfano 👋 

I'm still testing, but wanted to communicate earlier something that looks like a crash, and it's not reproducible with 21.9-rc-2. It happens when I try to select a category for a new story post:

1. Connect to a site that supports creation of story posts 
2. Start creating a story post
3. Select an image and continue
4. Tap `Categories`

https://user-images.githubusercontent.com/73365754/225629209-ddbdd2ba-e748-4c67-a662-fc9f1e647441.mp4

I reproduced it on Samsung A31 with Android 12 and the latest JP installable from this PR.

It's not reproducible with Pixel 7 + Android 13, and also not reproducible with JP 21.9-rc-2 on both devices.

I'll come back soon with info if it's rep on Emulator, so there might be some useful logs (I don't know how to retrieve the logs from the device after the app crash).

**Comment by pachlava** [comment]
I could reproduce the case above with `Pixel 2 API 31` Emulator:
```
2023-03-16 15:43:09.128 4224-4224/com.jetpack.android.prealpha D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2023-03-16 15:43:09.133 4224-4224/com.jetpack.android.prealpha E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jetpack.android.prealpha, PID: 4224
    java.lang.NullPointerException: null cannot be cast to non-null type org.wordpress.android.ui.posts.PrepublishingAddCategoryRequest
        at org.wordpress.android.ui.posts.PrepublishingCategoriesFragment.initViewModel(PrepublishingCategoriesFragment.kt:242)
        at org.wordpress.android.ui.posts.PrepublishingCategoriesFragment.onViewCreated(PrepublishingCategoriesFragment.kt:88)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by irfano** [comment]
Great job, @pachlava! Good catch! It probably caused crashes in other areas too.
I fixed the crash. Can you test it on the new build?

**Comment by pachlava** [comment]
Hey @irfano!

Thank you for the fix 🙇 The installable from d49b8d7aad54e9109588ce5f25d736d735aa1638 does not crash 👍 

I did not notice anything else, apart from two things that are not caused by this PR:
- Google login is not working, but this is [expected](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1400214722) for Jalapeno Debug builds.
- Back navigation is not working in several Blaze-related screen, but this is also true for 21.9-rc-2, so I'm going to communicate that separately.

Thank you!

UPD: just found out that the second point is on purpose (p5T066-3Ue-p2#comment-14484)

**Comment by irfano** [comment]
I made some changes after @pachlava's testing, which became necessary after syncing with the `trunk`. @ParaskP7, could you review the latest commits that were pushed after the last sub-PR was merged?

**Comment by ParaskP7** [comment]
> I made some changes after @pachlava's testing, which became necessary after syncing with the trunk. @ParaskP7, could you review the latest commits that were pushed after the last sub-PR was merged?

I am on-it @irfano , thanks for the ping! 👍 👀

**Comment by ParaskP7** [comment]
> I am on-it @irfano , thanks for the ping! 👍 👀

Done @irfano , thanks for the update, the changes look good (✅). However, I didn't test the `JetpackRemoteInstallActivity` related screen, maybe it is worth-it to test it (again), just to be sure that we are not missing something. Cc @pachlava

**Comment by pachlava** [comment]
> I didn't test the `JetpackRemoteInstallActivity` related screen, maybe it is worth-it to test it (again), just to be sure that we are not missing something. Cc @pachlava

I didn't go for a thorough test this time, but JP plugin remote installation worked in the latest installable for me, I checked on both Android 12 and 13.

**Comment by irfano** [comment]
Thanks for testing @pachlava!
@ParaskP7, can we merge this now?

**Comment by ParaskP7** [comment]
> @ParaskP7, can we merge this now?

Yes, I believe we can @irfano , feel free to merge this when you're ready! 🚀

**Review by ParaskP7 — APPROVED** [review]

**Pull request merged**
