### PR TITLE
Stats - Add the no activity indicator to the graph

### LINKED ISSUE #2206: “No stats available” message should use the same copy/style as the “No activity this period”
“No stats available” message should use the same copy/style as the “No activity this period” and overlay an empty chart with “ghost” bars to indicate that the days are still tappable. Compare to web stats.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2206

Designer and developer review needed.

cc @jancavan - When you have the time could you give this PR a run? 
Want to make sure that the new label isn't too big. If we want to reduce its size, we need to change icons and make them smaller.
screen shot 2015-07-16 at 12 17 25

### CODE REVIEW

**Comment by jancavan** [comment]
Thanks @daniloercoli. I think the label, especially the icon, are a bit large. Can we make them smaller similar to the mockup below?

no-activity2

I included smaller icons in case they are still needed: https://cloudup.com/c_shy_kq2yx

**Comment by daniloercoli** [comment]
Below is the dialog with the new icon in it:

screen shot 2015-07-16 at 23 51 50

Can't make the text smaller, otherwise it seems to small. 
If you're not ok with it, we need new icons a bit larger than the current version.

**Comment by jancavan** [comment]
@daniloercoli Looking good! A couple comments:

1. is it possible to align the icon and text? The icon looks a bit higher up than the text. In the mockup below, I just moved the icon a single pixel down.

icon-align

2. text color should be `#404040` not some shade of dark blue, sorry I didn't notice this earlier!

**Comment by daniloercoli** [comment]
Ok, i've fixed the alignment issue of the icon by changing the way icon was shown on the screen. 
Technical speaking I was using a property of the label called `textDrawable` but was giving me lot of troubles. Switched back the the classic `ImageView` and introduced a new element in the XML code.
Also switched back to your original icons that were bigger.

**Comment by daniloercoli** [comment]
This PR is developer ready now!

**Comment by daniloercoli** [comment]
@jancavan - We need a 128px icon as @nbradbury pointed above.

**Comment by nbradbury** [comment]
I'm confused by something that may or may not be part of this PR. In the stats for one of my test blogs, the Visitors tab has a zero on it but the graph shows that there were visitors. What does the zero on the tab mean, then?

stats-visitors

**Comment by daniloercoli** [comment]
The number in the Tab shows the visitors for the selected period. 
In your case, 0 Visitors on July 13.

**Comment by nbradbury** [comment]
Code looks good, ready to merge once the `xxxhdpi` icon is added.

**Comment by jancavan** [comment]
@daniloercoli Thanks for the fix, icon and text look aligned now. 

Here's the `xxxhdpi` icon: https://cloudup.com/chcllmKxeWl

**Comment by daniloercoli** [comment]
@nbradbury This PR is now ready to be merged.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
