### PR TITLE
Merge 22.0 final to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
LGTM! 💯 

-----

FYI: I just noticed something on the metadata side, comparing WordPress and Jetpack and wanted to flag that out here, just in case:
- The number of WordPress metadata are `18`, while `17` on Jetpack.
- The difference is that WordPress has an extra `fr-CA` metadata folder change.
- Also, I noticed that WordPress has a `pl-PL` (Polish) metadata folder change, while Jetpack has a `pt-BR` (Portuguese Brazil) metadata folder change.

@oguzkocer , I am not sure if the above is expected, thus I am going to approve this PR so as to not block it, but I am going to let you do the merging.

**Comment by ParaskP7** [comment]
> @oguzkocer , I am not sure if the above is expected, thus I am going to approve this PR so as to not block it, but I am going to let you do the merging.

Ah, I forgot about auto-merging! 😭

**Comment by oguzkocer** [comment]
@ParaskP7 I _think_ that's expected because not all translations were available at the time of finalization. There were also some fuzzy translations that haven't been addressed in a while. I reported those on Friday and should be addressed soon 🤞 

Specifically for `pt-BR`, we didn't have the release notes approved at the time of the finalization, but they got approved after, so I manually added those while submitting to Play Store.

I'll keep an eye on the reports just in case.

**Comment by ParaskP7** [comment]
Great, thanks for all this info @oguzkocer , as long as you are aware of all that I am at ease! 🚀 🤞

**Pull request merged**
