### PR TITLE
Small Reader Improvements: Update Reader Tracking Properties

### LINKED ISSUE #14069: Updating tracking properties in Reader
Add missing and update ambiguous properties as per the "Required code changes" column in a spreadsheet shared on p9xfpQ-1eg-p2.

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #14069

This tracking related updates were requested in order to enhance the data for the `Reader`.

After consulting the associated spreadsheet and investigating all `Reader` related tracking events it was decided to add all three main `Reader` tracking properties, wherever possible. Those are the:

- Blog Id (as `blog_id`, with a `numeric` value)
- Feed Id (as `feed_id`, with a `numeric` value) - This is based on @ashiagr feedback! 🙏 
- Is Followed (as `follow`, with `boolean` value)
- Source (as `source`, with a `string` value)

```
The `follow` property derived from:

- ReaderBlog.isFollowing, or
- ReaderPost.isFollowedByCurrentUser

I choose one over the other based on the context and it being available within that context.
I am not sure whether we should be using `ReaderBlog.isFollowing` over the 
`ReaderPost.isFollowedByCurrentUser` in all instances. Please code review and test this 
functionality in more depth to verify correctness.
```

```
The `source` property holds one of the below values:

- following
- discover
- liked
- saved
- custom
- a8c
- p2
- subscriptions
- search
- site_preview
- tag_preview
- post_detail
- comment
- user
- stats
- notification
- activity_log_detail
- unknown

Also, there is an extra source value of `post_list_saved_post_notice`, but this is an existing one.
```

As such please expect an analogous adjustment to what the spreadsheet dictated.

Below is a table with all the tracking events, their triggers and the tracking properties that were added (as `NEW`), already existed (as `EXISTS`) or not added (as `N/A`).

Number|Tracking Event | Trigger | Blog Id | Feed Id | Is Followed | Source
-------|-------|------|------|------|------|------
1|reader_discover_topic_tapped|When a user scrolls through the 'DISCOVER' tab, finds the 'You might like' card and clicks on a suggested 'topic' within that card.|~~N/A (*)~~|~~N/A (*)~~|~~N/A (*)~~|~~N/A (**)~~
2|reader_tag_previewed|When a user clicks on a 'topic' within a card.|~~N/A (*)~~|~~N/A (*)~~|~~N/A (*)~~|**NEW**
3|reader_post_card_tapped|When a user clicks on a card.|**NEW**|**NEW**|**NEW**|**NEW**
4|reader_article_opened|When a user clicks on a card and the article is shown.|*EXISTS*|*EXISTS*|**NEW**|~~N/A (***)~~
5|reader_article_rendered|When a user clicks on a card and the article is rendered.|*EXISTS*|*EXISTS*|**NEW**|~~N/A (***)~~
6|reader_blog_previewed|When a user clicks on a card's site.|**NEW**|**NEW**|**NEW**|**NEW**
7|reader_site_followed|When a user clicks on a card and then clicks on the site 'Follow' button within the card.|*EXISTS*|**NEW**|~~N/A~~|**NEW**
8|reader_site_unfollowed|When a user clicks on a card and then clicks on the site 'Unfollow' button within the card.|*EXISTS*|**NEW**|~~N/A~~|**NEW**
9|reader_suggested_site_toggle_follow|When a user is within the 'DISCOVER' tab, finds a suggested 'site' and then clicks the 'Follow/Unfollow' button.|*EXISTS*|**NEW**|*EXISTS*|~~N/A (**)~~
10|reader_reader_tag_followed|When a user is within the 'DISCOVER' tab, finds a suggested 'topic' and then clicks the 'Follow' button.|~~N/A (*)~~|~~N/A (*)~~|~~N/A~~|**NEW**
11|reader_reader_tag_unfollowed|When a user is within the 'DISCOVER' tab, finds a suggested 'topic' and then clicks the 'Unfollow' button.|~~N/A (*)~~|~~N/A (*)~~|~~N/A~~|**NEW**
12|reader_site_shared|When a user clicks on a card's site and then clicks on the share button within the site.|**NEW**|**NEW**|**NEW**|**NEW**
13|item_shared_reader|When a user clicks on card's menu (see ellipsis), and then clicks on the share menu option.|*EXISTS*|**NEW**|**NEW**|**NEW**
14|reader_post_saved|When a user clicks on card's save button.|**NEW**|**NEW**|**NEW**|**NEW**
15|reader_post_unsaved|When a user clicks on card's unsave button.|**NEW**|**NEW**|**NEW**|**NEW**
16|reader_saved_post_opened|When a user opens a saved card from any tab.|**NEW**|**NEW**|**NEW**|**NEW**
17|reader_article_liked|When a user clicks on card's like button.|*EXISTS*|*EXISTS*|**NEW**|**NEW**
18|reader_article_unliked|When a user clicks on card's unlike button.|*EXISTS*|*EXISTS*|**NEW**|**NEW**
19|reader_article_detail_liked|When a user clicks on a card and then clicks on the like button within the card.|*EXISTS*|*EXISTS*|**NEW**|**NEW**
20|reader_article_detail_unliked|When a user clicks on a card and then clicks on the unlike button within the card.|*EXISTS*|*EXISTS*|**NEW**|**NEW**

```
* - This means that this is a `Topic` or `Tag` and as such the `Blog Id` or `Feed Id` property is not applicable to it.
** - This means that this tracking event only occurs on the `DISCOVER` tab and as such the `Source` property is omitted.
*** - This means that this tracking event only occurs on the `POST DETAIL` tab (ish) and as such the `Source` property is omitted.
```

Also, as part of this `Reader` tracking properties update, the below enhancements occurred:
- For every `Reader` related screen and classes, the `ReaderTracker` wrapper class replaced all other tracking related classes (like `AnalyticsTrackerWrapper`, `AnalyticsUtilsWrapper`, `AnalyticsUtils`, etc). This is done in order to consolidate all `Reader` related tracking functionality in one place and make it reusable on all places.
- For every `Reader` related screen and classes that the `ReaderTracker` wrapper was utilised, a automatic refactoring occurred as an initial step to make the code easier to work with (like removing all possible warning, optimizing `Reader` related imports, etc).
- A lot of `Reader` tracking related functionality was optimized (unnecessary functions were deleted, nullability annotations were added, unused code was removed, etc).

Warning (⚠️):
- To review this PR please do a commit-by-commit review from within the IDE.
- Make sure to spend some time on the `Feature` related commit and skip the `Refactor` related commits.

To test:
- Launch app and go to `My Site` tab.
- Go to: `My Site` -> `Toolbar Avatar` -> `App Settings` -> `Privacy settings`
- Switch on `Collect information` to enable tracking on your device.
- Navigate to the `Reader` tab.
- Follow the table above, per tracking event, trigger the event and verify that the newly added properties are tracked. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ashiagr — COMMENTED** [review]
Thanks for working on this @ParaskP7! It's really nice to see all reader tracking through `ReaderTracker` 👏.

I focussed mainly on the feature commits and testing the events. I just have few things to share:

1. Noticed a crash for `reader_tag_previewed` event

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android.prealpha/org.wordpress.android.ui.reader.ReaderPostListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.reader.tracker.ReaderTracker.track(org.wordpress.android.analytics.AnalyticsTracker$Stat, java.util.Map)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.reader.tracker.ReaderTracker.track(org.wordpress.android.analytics.AnalyticsTracker$Stat, java.util.Map)' on a null object reference
        at org.wordpress.android.ui.reader.ReaderPostListFragment.trackTagLoaded(ReaderPostListFragment.java:254
```

2) In the xls from the mentioned P2 post, several events included a comment: 
> Add "blog_id"  property (keep empty for feeds)

I followed an external feed (feed id = 48313623), and the event that got logged was:

`reader_post_card_tapped, Properties: {"blog_id":48313623,"follow":true,"source":"following"}`

blog_ID and feed_ID from [/read/feed/48313623](https://public-api.wordpress.com/rest/v1.1/read/feed/48313623):

```
blog_ID:"0"
feed_ID:"48313623"
```

We're passing a feed id as blog id, which looks incorrect to me.

The same behaviour was seen for other events like: reader_blog_previewed, reader_site_shared, reader_saved_post_opened, reader_post_saved.

3. Regarding this: 

> I am not sure whether we should be using `ReaderBlog.isFollowing` over the 
`ReaderPost.isFollowedByCurrentUser` in all instances. 

AFAIK, both means the same. When we follow a post, it actually means we're following the blog to which it belongs to.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

Thank you so much for your thorough review, much appreciated!

> Thanks for working on this @ParaskP7! It's really nice to see all reader tracking through ReaderTracker 👏.

🙏 

> I focussed mainly on the feature commits and testing the events.

👍 

> 1. Crash
> Noticed a crash for `reader_tag_previewed` event

Many thanks for finding this crash. I'll handle this crash as soon as possible.

> 2. `blog_id` vs. `feed_id`
> We're passing a feed id as blog id, which looks incorrect to me.

Many thanks for identifying this inconsistency. As discussed, I'll add an additional `feed_id` property everywhere possible so that to avoid this kind of inconsistency.

> 3. `ReaderBlog.isFollowing` vs. `ReaderPost.isFollowedByCurrentUser`
> When we follow a post, it actually means we're following the blog to which it belongs to.

Many thanks for confirming that for me.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

I just pushed a few additional commits to this PR, mainly based on your feedback on `feed_id`. I have also updated the table in the description to account for this change. Many thanks for this suggestion, I do find value in it! 🚀 

> 1. Crash
> Noticed a crash for reader_tag_previewed event
> Many thanks for finding this crash. I'll handle this crash as soon as possible.

As discussed, I tried replicating this crash and couldn't. I anyway adding a few nullability annotations so that to make sure that we are handling any possible null pointer exceptions around that area (see c614adeb4a41bb132088def0ac5aaaad00754a56). I also, refactored this specific bit of logic to adjust that to the new `ReaderTracker` standards and thus making that more robust (see 47554145db3d73a544654cfa9aa7fff382913b58, 110ba61784e2f0c1b267b8eb58d3ba98573382be and 9b3a349db38160342711c11a084bbe3b9fd218c8).

> 2. blog_id vs. feed_id
> We're passing a feed id as blog id, which looks incorrect to me.
> Many thanks for identifying this inconsistency. As discussed, I'll add an additional feed_id property everywhere possible so that to avoid this kind of inconsistency.

I added `feed_id` to all `trackBlog(...)` specific methods within `ReaderTracker` and made the corresponding changes to get that `feedId` from the individual classes that are now require that to tricker these tracking events, see:
- 7b7bad1a1dc4d485aa52e11e37bfe1e7a1e627c9,
- 1c9a4ba9a2c0b8e4e6691002b49820b5d1be2d9c,
- 6dba2f95a758052346eb5c2ddcccd3bd7427ce46 and
- 883611bf812a2463472d9bacf362700a368af10d.

Would you mind doing another pass on this PR?

🙏

**Review by ashiagr — APPROVED** [review]
Thanks @ParaskP7! I verified the changes and all looks good to me 👍. Nicely done!

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Thanks @ParaskP7! I verified the changes and all looks good to me 👍. Nicely done!

Thank you for yet another code review Ashita! 🙏 🚀 

PS: @leandroalonso before I merge this brach with `develop` would you mind going through the table of changes and verify that you are also okay with all the above enhancements on the main `Reader` related tracking events?

**Comment by leandroalonso** [comment]
@ParaskP7 will do it later today!

**Comment by ParaskP7** [comment]
> @ParaskP7 will do it later today!

Many 🙏 @leandroalonso and if you need anything just let me know!

**Pull request merged**
