### PR TITLE
Add report user option in Reader post menu

### LINKED ISSUE #17602: Add report user option in the Reader post menu
### Description
We want to add a new `Report user` action at the end of the menu appearing in reader post. This action will open a web form similar to the one for reporting content (cc @enejb internal ref: `p1669977627322799/1669929094.952189-slack-C02FMH4G8`).

| Followed Site Post | Unfollowed Site Post |
| - | - |
| 205069298-3eab803b-7d9a-4879-8789-61a399b0368b|205069305-887341ea-8058-4402-ad3f-beb390aacdc6|

Internal ref `pcdRpT-1ms-p2`

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #17602

This PR adds functionality to report the author of a post from the Reader post `⋮` overflow menu.

- Internal BE ref: D94418-code

> The new option opens the form to report abuse on WP.com and passes the post author info. This form will be updated to support reporting users/authors.

This PR also changes the report icons (see screenshot) for:
- The existing `Report this post` functionality
- The added `Report this user` functionality

### 1. Test Report user from Discover
1. Open Reader
2. Tap on the `⋮` overflow menu of one of the posts
   - **Verify** that the report actions have a flag icon
4. Select `Report this user`
5. **Expect** To see a page for reporting the author
   > **Remark** Currently it opens the page to report post/site, this should change.

<details>
<summary><h3>2. Test report user from site post list</h3> (expand)</summary>

1. Open Reader
2. Tap on the header of one post in `Discover` to open the post list of that site
3. Tap on the `⋮` overflow menu of one of the posts
4. Select `Report this user`
6. **Expect** To see a page for reporting the author
   > **Remark** Currently it opens the page to report post/site, this should change.

</details>
<details>
<summary><h3>3. Test report user from post detail screen</h3> (expand)</summary>

1. Open Reader
2. Tap on the excerpt (text above icons) of one post in `Discover` to open the post in reader
3. Tap on the `⋮` overflow menu at the top right of the screen
4. Select `Report this user`
5. **Expect** To see a page for reporting the author
   > **Remark** Currently it opens the page to report post/site, this should change.

</details>

### Screenshot

| Followed Sites | Unfollwed Sites |
| - | - |
|  |  |

<details>
<summary><b>Report Author form</b> (web)</summary>

| report_author_form |
| - |
</details>

## Regression Notes
1. Potential unintended areas of impact
   N/a

7. What I did to test those areas of impact (or what existing automated tests I relied on)
   Manual testing.

8. What automated tests I added (or what prevented me from doing so)
   Added test to verify the click action and the presence of the new option.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Great work @ovitrif 👍 
I had a first pass at this though it is still in draft state. The code looks good and the app behaved as expected for me in all cases 🎖️ 
My understanding is that the only remaining part is testing with the deployed new report page (ref D94418-code). Right?

**Comment by ovitrif** [comment]
> Great work @ovitrif 👍 I had a first pass at this though it is still in draft state. The code looks good and the app behaved as expected for me in all cases 🎖️ 

Thank you for checking this PR @antonis 🙇 

> My understanding is that the only remaining part is testing with the deployed new report page (ref D94418-code). Right?

That's true, once the new report page is deployed this PR should be ready.

I've tested the integration manually by sandboxing the version with the new report page and checking if the page that is supposed to open in the WebView with this PR correctly links to the new web form and that worked as expected 👍

**Comment by hypest** [comment]
> That's true, once the new report page is deployed this PR should be ready.
>
> I've tested the integration manually by sandboxing the version with the new report page and checking if the page that is supposed to open in the WebView with this PR correctly links to the new web form and that worked as expected 👍

Hmm, do we need to wait for the backend to deploy then? I mean, why not merge and produce the builds to send to Playstore, and then wait for the backend deployment before submitting the hotfix? cc @antonis

**Comment by antonis** [comment]
> Hmm, do we need to wait for the backend to deploy then? I mean, why not merge and produce the builds to send to Playstore, and then wait for the backend deployment before submitting the hotfix?

Good point @hypest 👍 
My only concern with this is that the page opened for reporting before deploying the backend change (D94418-code) would be the same with the one for reporting content since [the current backend does not use the extra parameter passed by the client](https://github.com/wordpress-mobile/WordPress-Android/pull/17606/files#diff-ac70271fa48ae9d104b604b6f8f8fc09fc762394d5b72e41fee20ae3e0faabfbR539).
Tbh I'm not sure if this would be noticed by the reviewer (screenshots below for reference) but I think it might make sense to present the full solution since we are close to wrapping this up. Wdyt? cc @enejb 

<details>
<summary>Content reporting</summary>

Screenshot_20221208_175749
</details>

<details>
<summary>Author reporting</summary>

Screenshot_2022-12-05_at_10 34 50_PM
</details>

**Comment by hypest** [comment]
@antonis , note, what I'm suggesting is to go ahead when merging and _producing_ the binaries... *not* submitting for review. We can wait a moment for the backend changes to deploy and then submit the hotfix for review.

What I'm uncomfortable with is keeping a PR here in Draft mode even though all the implementation in the client side is finished.

**Comment by antonis** [comment]
> What I'm uncomfortable with is keeping a PR here in Draft mode even though all the implementation in the client side is finished.

Gocha 👍  [I've already reviewed this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17606#pullrequestreview-1208382251). I'll proceed with merging.

**Review by antonis — APPROVED** [review]
Thank you for your work on this @ovitrif 🙇 
[As discussed I'm proceeding with merging](https://github.com/wordpress-mobile/WordPress-Android/pull/17606#issuecomment-1342962860) this PR without waiting for the backend changes.

**Comment by antonis** [comment]
Retested with the deployed backend change and everything worked great 🚀

**Pull request merged**
