### PR TITLE
Merge release/19.9 (19.9-rc-3 + conflict resolution)

### PR DESCRIPTION
**Pull request by ParaskP7**
Merging the release branch after doing a new beta.

The new beta includes:
- #16582
- #16604
- #16607
- #16613
- #16614
  - https://github.com/wordpress-mobile/gutenberg-mobile/pull/4875
- #16586
- Latest `strings.xml` from GlotPress*
- Version bump in `version.properties`

`(*)` FYI: During `bundle exec fastlane new_beta_release` I got the below `Error downloading hi - 429 Too Many Requests` for the `id`, `hi`, `sk` and `cs` locales: Cc @AliSoftware 

<details>
  <summary>Click to expand and see the android download translations build log</summary>

```
[13:31:26]: -------------------------------------------
[13:31:26]: --- Step: android_download_translations ---
[13:31:26]: -------------------------------------------
[13:31:26]: Downloading translations for 'ar' from GlotPress (ar) [{:status=>"current"}]...
[13:31:27]: Downloading translations for 'de' from GlotPress (de) [{:status=>"current"}]...
[13:31:29]: Downloading translations for 'en-rGB' from GlotPress (en-gb) [{:status=>"current"}]...
[13:31:30]: Downloading translations for 'es' from GlotPress (es) [{:status=>"current"}]...
[13:31:32]: Downloading translations for 'fr-rCA' from GlotPress (fr) [{:status=>"current"}]...
[13:31:33]: Downloading translations for 'fr' from GlotPress (fr) [{:status=>"current"}]...
[13:31:35]: Downloading translations for 'he' from GlotPress (he) [{:status=>"current"}]...
[13:31:36]: Downloading translations for 'id' from GlotPress (id) [{:status=>"current"}]...
[13:31:37]: Error downloading id - 429 Too Many Requests
[13:31:37]: Downloading translations for 'it' from GlotPress (it) [{:status=>"current"}]...
[13:31:38]: Downloading translations for 'ja' from GlotPress (ja) [{:status=>"current"}]...
[13:31:39]: Downloading translations for 'ko' from GlotPress (ko) [{:status=>"current"}]...
[13:31:41]: Downloading translations for 'nl' from GlotPress (nl) [{:status=>"current"}]...
[13:31:42]: Downloading translations for 'pl' from GlotPress (pl) [{:status=>"current"}]...
[13:31:44]: Downloading translations for 'pt-rBR' from GlotPress (pt-br) [{:status=>"current"}]...
[13:31:45]: Downloading translations for 'ru' from GlotPress (ru) [{:status=>"current"}]...
[13:31:46]: Downloading translations for 'sr' from GlotPress (sr) [{:status=>"current"}]...
[13:31:48]: Downloading translations for 'sv' from GlotPress (sv) [{:status=>"current"}]...
[13:31:49]: Downloading translations for 'th' from GlotPress (th) [{:status=>"current"}]...
[13:31:50]: Downloading translations for 'tr' from GlotPress (tr) [{:status=>"current"}]...
[13:31:51]: Downloading translations for 'vi' from GlotPress (vi) [{:status=>"current"}]...
[13:31:53]: Downloading translations for 'zh-rCN' from GlotPress (zh-cn) [{:status=>"current"}]...
[13:31:54]: Downloading translations for 'zh-rTW' from GlotPress (zh-tw) [{:status=>"current"}]...
[13:31:55]: Downloading translations for 'az' from GlotPress (az) [{:status=>"current"}]...
[13:31:56]: Downloading translations for 'el' from GlotPress (el) [{:status=>"current"}]...
[13:31:57]: Downloading translations for 'es-rMX' from GlotPress (es-mx) [{:status=>"current"}]...
[13:31:58]: Downloading translations for 'es-rCL' from GlotPress (es-cl) [{:status=>"current"}]...
[13:31:59]: Downloading translations for 'gd' from GlotPress (gd) [{:status=>"current"}]...
[13:32:00]: Downloading translations for 'hi' from GlotPress (hi) [{:status=>"current"}]...
[13:32:01]: Error downloading hi - 429 Too Many Requests
[13:32:01]: Downloading translations for 'hu' from GlotPress (hu) [{:status=>"current"}]...
[13:32:01]: Downloading translations for 'nb' from GlotPress (nb) [{:status=>"current"}]...
[13:32:02]: Downloading translations for 'pl' from GlotPress (pl) [{:status=>"current"}]...
[13:32:04]: Downloading translations for 'th' from GlotPress (th) [{:status=>"current"}]...
[13:32:05]: Downloading translations for 'uz' from GlotPress (uz) [{:status=>"current"}]...
[13:32:05]: Downloading translations for 'zh-rHK' from GlotPress (zh-tw) [{:status=>"current"}]...
[13:32:07]: Downloading translations for 'eu' from GlotPress (eu) [{:status=>"current"}]...
[13:32:07]: Downloading translations for 'ro' from GlotPress (ro) [{:status=>"current"}]...
[13:32:09]: Downloading translations for 'mk' from GlotPress (mk) [{:status=>"current"}]...
[13:32:09]: Downloading translations for 'en-rAU' from GlotPress (en-au) [{:status=>"current"}]...
[13:32:10]: Downloading translations for 'sr' from GlotPress (sr) [{:status=>"current"}]...
[13:32:12]: Downloading translations for 'sk' from GlotPress (sk) [{:status=>"current"}]...
[13:32:12]: Error downloading sk - 429 Too Many Requests
[13:32:12]: Downloading translations for 'cy' from GlotPress (cy) [{:status=>"current"}]...
[13:32:13]: Downloading translations for 'da' from GlotPress (da) [{:status=>"current"}]...
[13:32:13]: Downloading translations for 'bg' from GlotPress (bg) [{:status=>"current"}]...
[13:32:14]: Downloading translations for 'sq' from GlotPress (sq) [{:status=>"current"}]...
[13:32:16]: Downloading translations for 'hr' from GlotPress (hr) [{:status=>"current"}]...
[13:32:16]: Downloading translations for 'cs' from GlotPress (cs) [{:status=>"current"}]...
[13:32:17]: Error downloading cs - 429 Too Many Requests
[13:32:17]: Downloading translations for 'pt-rBR' from GlotPress (pt-br) [{:status=>"current"}]...
[13:32:18]: Downloading translations for 'en-rCA' from GlotPress (en-ca) [{:status=>"current"}]...
[13:32:20]: Downloading translations for 'ms' from GlotPress (ms) [{:status=>"current"}]...
[13:32:21]: Downloading translations for 'es-rVE' from GlotPress (es-ve) [{:status=>"current"}]...
[13:32:22]: Downloading translations for 'gl' from GlotPress (gl) [{:status=>"current"}]...
[13:32:23]: Downloading translations for 'is' from GlotPress (is) [{:status=>"current"}]...
[13:32:24]: Downloading translations for 'es-rCO' from GlotPress (es-co) [{:status=>"current"}]...
[13:32:25]: Downloading translations for 'kmr' from GlotPress (kmr) [{:status=>"current"}]...
```

</details>

### 1. `build.gradle`
FluxC version conflict:

```
<<<<<<< merge/19.9-rc-3
    fluxCVersion = '1.42.2'
=======
    fluxCVersion = 'trunk-c5a745e60ccb39fc8178a146d467c3221d931bb1'
>>>>>>> trunk
```

And I kept `fluxCVersion = 'trunk-c5a745e60ccb39fc8178a146d467c3221d931bb1'`, which was in `trunk`. The `trunk`'s version seems to be the latest out of the two and thus the version we want to keep in `trunk` after this PR lands. @ashiagr @AjeshRPai , can you please verify and confirm that the resolution is good and that this is indeed what we want? 🙇 

### 2. `QuickStartTracker.kt` (NEW)

@ashiagr (see [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/16620#pullrequestreview-982801606))

### CODE REVIEW

**Comment by ovitrif** [comment]
> The new beta includes:
>
> https://github.com/wordpress-mobile/WordPress-Android/pull/16619

@ParaskP7 I think this one should not belong to the list 😅

**Comment by ParaskP7** [comment]
> @ParaskP7 I think this one should not belong to the list 😅

@ovitrif This is true, I have no idea how I end-up adding this number there, I meant to have `#16582` instead. 🤔 

Fixed, thank you so much for noting that! 🙇 ❤️ 🙏

**Comment by ashiagr** [comment]
Thanks for this PR, @ParaskP7!

> I kept fluxCVersion = 'trunk-c5a745e60ccb39fc8178a146d467c3221d931bb1', which was in trunk. The trunk's version seems to be the latest out of the two and thus the version we want to keep in trunk after this PR lands. Cc @ashiagr @AjeshRPai , can you please verify that this is indeed what we want?

`FluxC` `1.42.2` tag changes in [release/1.42.2](https://github.com/wordpress-mobile/WordPress-FluxC-Android/tree/release/1.42.2) branch are not merged to `FluxC` `trunk`. I'll create a `FluxC` PR to merge it to `trunk` as described in `Steps for Fixing FluxC During a Code Freeze - Phase 2`(Internal Ref: paqN3M-l3-p2) and add you as a reviewer.

I think once it is merged, we can point to the latest `FluxC` trunk commit in `WPAndroid` `build.gradle`.

**Comment by ParaskP7** [comment]
Thanks for your info @ashiagr and for working on this!

> FluxC 1.42.2 tag changes in [release/1.42.2](https://github.com/wordpress-mobile/WordPress-FluxC-Android/tree/release/1.42.2) branch are not merged to FluxC trunk. I'll create a FluxC PR to merge it to trunk as described in [Steps for Fixing FluxC During a Code Freeze - Phase 2](https://github.com/wordpress-mobile/WordPress-Android/pull/paqN3M-l3-p2) and add you as a reviewer.

Coolio! 👍 

> I think once it is merged, we can point to the latest FluxC trunk commit in WPAndroid build.gradle.

Sounds like a plan! 🥇

**Review by mokagio — APPROVED** [review]
- [x] `versionName` `rc` number and `versionCode` bumps in`version.properties`
- [x] `string.xml` updates
- [x] Diffs from the PRs that made it into this beta

This beta merge looks good to me.

I'm approving to unblock, but I'm not sure whether we want to merge as is or wait for the FluxC work @ashiagr mentions [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16620#issuecomment-1134632194) to be done?

**Comment by ashiagr** [comment]
@ParaskP7 I created FluxC merge PR here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2420 and added you as a reviewer. Let me know if anything is not in order. 🙏 

Once it is merged, we can point to the latest `FluxC` trunk commit in `WPAndroid` `build.gradle`.

**Comment by ParaskP7** [comment]
> @ParaskP7 I created FluxC merge PR here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2420 and added you as a reviewer. Let me know if anything is not in order. 🙏

Thank you @ashiagr , I am on it! 🥇 

> Once it is merged, we can point to the latest FluxC trunk commit in WPAndroid build.gradle.

👍 💯

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Once it is merged, we can point to the latest FluxC trunk commit in WPAndroid build.gradle.

This [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2420) is now merged. I will now update this release merge PR to point to the latest FluxC trunk commit. ⚙️

**Comment by ParaskP7** [comment]
👋 @ashiagr @AjeshRPai !

> Once it is merged, we can point to the latest FluxC trunk commit in WPAndroid build.gradle.

I just updated 'FluxC' to point to the latest 'FluxC' trunk commit. Can you verify that this is what you would also expect? 🙏 

PS: Today, I noticed a new merge conflict with `QuickStartTracker.kt` on this PR. Would you mind to also take a look at it and resolve the conflict to what you would expect to land on `trunk` when this PR merges. I would have done it myself (I actually tried) but I don't want to mess anything as I don't have the needed context in terms of the `Quick Start` work you have done so far. 🙇

**Review by ashiagr — APPROVED** [review]
👋 @ParaskP7 

> I just updated 'FluxC' to point to the latest 'FluxC' trunk commit. Can you verify that this is what you would also expect? 🙏

Yes, I pulled this branch and verified that our `FluxC` changes are included in it.

> Today, I noticed a new merge conflict with QuickStartTracker.kt on this PR. Would you mind to also take a look at it and resolve the conflict to what you would expect to land on trunk when this PR merges.

Merged `trunk` in 6e70dfd which resolves the conflict. 

All looks good to me now. Thank you so much for this PR! 🙏 
Feel free to merge when CI completes.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Yes, I pulled this branch and verified that our FluxC changes are included in it.

Thank you! 🙏 

> Merged trunk in https://github.com/wordpress-mobile/WordPress-Android/commit/6e70dfdf9c5f96e498230dccc0d1106d11398f6a which resolves the conflict.

Thank you! 🙇 

> All looks good to me now. Thank you so much for this PR! 🙏

Thank YOU! 🥇 

> Feel free to merge when CI completes.

👍

**Pull request merged**
