### PR TITLE
Add initial support for Video uploading to Aztec

### LINKED ISSUE #6342: AztecEditorFragment add support for Video uploading
Video uploading is still missing in Aztec. We should probably add it soon.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #6342 by adding minimal video support to Aztec, and build the foundations to introduce video in async (+ video optimization in async).

- Videos added to the editor have an overly to indicate that's a video file
- Tapping on the video opens the browser (In a future version we should open our preview activity)
- Video optimization is done as in the normal editor
- In a future version we need to handle videopress shortcode
- I've also done a cleanup of the code while I was there. If the diff appears too cobbled, check the following methods `appendMediaFile`, `onMediaUploadSucceeded`, `onMediaTapped`.

cc @khaykov @0nko @theck13

### CODE REVIEW

**Comment by 0nko** [comment]
Nice! Thanks @daniloercoli. Videos already "work" in Aztec, this feature is just not used in WordPress yet. The `<video>` tag is supported but you can only see it in the demo app, because the WP back-end strips it away. Only videos by means of shortcodes work (shortcode support is currently in progress in Aztec).

If you'd like you can take a look at [Aztec demo app](https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/app/src/main/kotlin/org/wordpress/aztec/demo/MainActivity.kt) to see the necessary callbacks, thumbnail preview loader (a frame from a video is used as an overlay), handling of playback, etc.

**Comment by daniloercoli** [comment]
Note: This PR should require a fast and dirty patch to Aztec, since Video items need to be added to the content as link, otherwise as explained above, the video shortcode is stripped, and no video at all.

**Comment by daniloercoli** [comment]
This PR should be merged after https://github.com/wordpress-mobile/AztecEditor-Android/pull/427
Before merging this PR we need to update the Aztec hash in Editors sub-project.

**Comment by 0nko** [comment]
If you want to ship this in `7.9` we'll need to change the base branch to `release/7.9` and remove the merges from develop up to `88222ea`.

**Comment by daniloercoli** [comment]
Thanks @0nko - I think it's fine to merge it in `develop`, since we just need it in Async.

**Comment by mzorz** [comment]
Good work @daniloercoli ! some things found while testing this one, we might want to track these down on separate issues/PRs 👍 

#### Thumbnails not being persisted
- When I start a video upload either from the storage or from the Camera, it shows the thumbnail OK

screenshot_20170726-104421


- Exiting the editor and coming back again doesn’t show the preview thumbnail as it was shown when I first included the video in the Post. Instead it shows the aztec image placeholder with the retry/failed overlay, or the play video overlay if it succeeded.

screenshot_20170726-100634
screenshot_20170726-100529


- The same happens if I let the video upload completely without leaving the editor, then coming back to the editor shows no video thumbnail.

#### Post list
- the Post list shows the `[video]` tag when the post is finished uploading, and also if there are no images in the post but a video is in there, it seems to  me the post item resizes itself as if it were to hold a featured image, but it shows a blank space instead (probably related to thumbnails up there)

screenshot_20170726-104448

- finally if the Post has a successfully uploaded video, the full tag is displayed in the post list
screen shot 2017-07-26 at 10 50 08 am

**Comment by mzorz** [comment]
Ok, tracked bugs in #6400 and #6401

**Comment by mzorz** [comment]
:shipit:

**Pull request merged**
