### PR TITLE
[Feature] Reader Improvements

### PR DESCRIPTION
**Pull request by RenanLukas**
Feature branch of Reader Improvements (ref: pcdRpT-3Eb-p2)

- [x] Tag and Site feed header
- [x] Post details header
- [x] Post feed cards
- [x] “You might like” and “Sites to follow” cards
- [x] Follow/Unfollow buttons

### CODE REVIEW

**Comment by RenanLukas** [comment]
Hey @tiagomar 👋 this is the PR I was telling you about in DM. When you have some time, could you please have a look at our changes on `androidTest` directory?

Thank you!

**Review by tiagomar — APPROVED** [review]
Hey @RenanLukas !

I just checked the changes under `androidTest` and changes to `WPScreenshotTest.java` are straightforward and looks good. The test is passing and the element removed is not even being in `trunk`. We're safe here. 🙇‍♂️ 

image

**Comment by RenanLukas** [comment]
Thank you for taking the time, @tiagomar  👍

**Review by jostnes — APPROVED** [review]
I ran `ReaderTests` locally and looks good, the previously failing test `e2eBookmarkPost` now works without issue. The changes look good too. Thanks for fixing the failing test! :shipit:

**Pull request merged**
