### PR TITLE
Fix connected android test

### PR DESCRIPTION
**Pull request by glung**
# Scope 

The README specifies to run `./gradlew cAT` to test the project. Though, the tests failed on the branch `develop`. 

This introduces a fix for the connected android test. It also updates the README with instructions to run the unit tests. 

Note: androidTest in subtrees (lib folder) are not in the scope. 

# Details 
- Remove test GCMIntentServiceTest.java as it was failing to start the GCMMessageService, and had no assertion 
- Fix test setup WPHtmlTest
- By default, testing instructions don't include subtrees in the `libs` folder.

### CODE REVIEW

**Comment by kwonye** [comment]
@glung I'm unable to get either of those commands to run and this may be the cause:

```
Execution failed for task ':libs:login:WordPressLoginFlow:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: javax/annotation/Generated
```

Are you seeing this on your build?

**Comment by mzorz** [comment]
> This introduces a fix for the connected android test. 

IIUC this PR is not fixing the test, but rather removing it. On the other hand, the tests this PR removes have not been kept up to date for long, so I see how it actually might make sense to remove it 😄. Would it be better though, to replace it with an actual working test instead of completely removing it? I'm more leaning towards not merging this PR for now, until we make a decision. Wdyt @kwonye ?

**Comment by glung** [comment]
I see your point and actually, I shared your thoughts initially. Then, I realized that: :
- The service was reworked and it's a bit of work to rewrite the test
- The test actually does not assert anything 

This led me to think that deleting the test is the best option. 

Though, I might miss some context!

**Comment by mzorz** [comment]
> The service was reworked and it's a bit of work to rewrite the test
> The test actually does not assert anything

👍 

> This led me to think that deleting the test is the best option.

That sounds convincing - Deleting it is! :shipit:

**Pull request merged**
