### PR TITLE
Issue/fix material theme conflicts

### PR DESCRIPTION
**Pull request by khaykov**
This PR fixes conflicts between `feture/material-theme` and `develop` branches.

Check the last 5 commits for fixes. We had conflicts in:
- Localized strings.xml
- Localized Fastlane Release Notes
- Post Settings Fragment (drawable reference was updated)
- The duplicate string was mixed into one of the localized strings.xml. This was not in a conflict, but surfaced during build.

Outside of this, the only major conflict was related to recent update to Pages list item, that was aimed at visually matching them with the compact Post List item. I made sure the changes visually match each other and Material Theme:
comparison_reader

To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@oguzkocer Thank you so much for actionable commits and explanation of the process! Now I know what do if I'll encounter something like this next time 🙇I checked the difference with `develop` after cherry-picking them, and everything looks ok to me.

Still, no idea how it got all messed up like this, and why some lines are marked as changed. Maybe different whitespace character?

**Comment by oguzkocer** [comment]
> Still, no idea how it got all messed up like this, and why some lines are marked as changed. Maybe different whitespace character?

I have no idea either, with the whitespace that was my guess too, but there are some other changes that shouldn't be in the feature branch I don't think. I wonder if any of the auto-merges caused that.

I think this PR is good as is, but once it's merged I suggest checking if any other files are unintentionally modified. I wrote a p2 post about this just now, so have a look at that and feel free to ping me if you need help.

**Comment by khaykov** [comment]
@malinajirka We are a bit time pressured with this PR, so if you think there are any visual changes required to Pages items - let me know and I'll add them :)

**Comment by malinajirka** [comment]
I'm sorry, I totally missed the ping. I've checked it and it looks good overall. I found one potential design issue - when a page is being uploaded a disabled overlay is shown. However, this overlay looks a bit weird in dark mode. Wdyt? 

Screenshot_1585898365

Note: Btw the same issue is present on the post list.

**Pull request merged**
