### PR TITLE
Enable editor debug mode when BuildConfig.DEBUG is true

### PR DESCRIPTION
**Pull request by maxme**
Note: I wonder if we should replace the debug action bar button to something else to make sure we're testing the editor in real life conditions.

### CODE REVIEW

**Comment by aforcier** [comment]
> Note: I wonder if we should replace the debug action bar button to something else to make sure we're testing the editor in real life conditions.

I agree in principle, but I'm not sure what we could add that wouldn't affect the UI in some way. We need to be able to dump the raw HTML at any given time for debugging, especially for `API<19` which doesn't support Chrome inspection. Do you have anything in mind?

**Comment by maxme** [comment]
> Do you have anything in mind?

* Click listener on the title, but that won't work if we add the blog picker
* Listen for hardware button press (volume up for instance)
* Konami code ;)?

**Comment by maxme** [comment]
We agreed to listen for volume up keyboard event. I'll drop the action bar icon and add a Toast message when volume up press is detected and the debug function called.

**Comment by maxme** [comment]
Added a Toast and Volume Up button listener in 4a82c7a

Note: I added the Volume Up key press listener to the WebView because I would have to add it to the activity and I wanted to keep this part in the editor repo.

**Comment by aforcier** [comment]
I wonder if it would be better to consume the volume up event when dumping the log, since the volume doesn't have any other use in the editor except for video playback. Otherwise we'll be caught by surprise by maxed out system volume after an editor debugging session. :wink:

**Comment by maxme** [comment]
> I wonder if it would be better to consume the volume up

Added this to  ff707a2 - I'm not sure which behavior is the weirdest but I don't care it's just for debug mode ;)

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
