### PR TITLE
Automated Transfer Analytics, Design & Copy Review

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR adds analytics for the Automated Transfer events. @SylvesterWilmott & @elibud has given 👍 to the event selection on Slack. The only other code changes is to fix a minor bug with dialog cancelation. A question from @SylvesterWilmott made me realize that the dialog cancelation was not being properly handled if the user tapped on the "Back" button while dialog is visible.

As discussed on Slack, we are going to do the design and copy review as part of this PR.

**Copy Review**

Here are all the strings that were added for this feature:

```
<string name="plugin_install_first_plugin_confirmation_dialog_message">Installing the first plugin on your site can take up to 1 minute and until it\'s complete you won\'t be able to use your site or make any changes to it. Would you like to proceed?</string>
<string name="plugin_install_first_plugin_progress_dialog_title">Install Plugin</string>
<string name="plugin_install_first_plugin_almost_finished_dialog_message">The plugin is installed, we are setting it up&#8230;</string>

<!-- Automated Transfer Eligibility Errors -->
<string name="plugin_install_site_ineligible_default_error">Plugins feature is not available for this site.</string>
<string name="plugin_install_site_ineligible_not_using_custom_domain">Plugins feature require a custom domain.</string>
<string name="plugin_install_site_ineligible_no_business_plan">Plugins feature require a business plan.</string>
<string name="plugin_install_site_ineligible_site_private">Plugins feature require the site to be public.</string>
<string name="plugin_install_site_ineligible_email_unverified">Plugins feature require a verified email address.</string>
<string name="plugin_install_site_ineligible_excessive_disk_space">Plugin cannot be installed due to disk space limitations.</string>
<string name="plugin_install_site_ineligible_no_vip_sites">Plugins cannot be installed on VIP sites.</string>
<string name="plugin_install_site_ineligible_non_admin_user">Plugin feature requires admin privileges.</string>
<string name="plugin_install_site_ineligible_not_domain_owner">Plugin feature requires primary domain subscription to be associated with this user.</string>
<string name="plugin_install_site_ineligible_site_graylisted">Plugin feature requires the site to be in good standing.</string>
```

I got the dialog strings from @SylvesterWilmott's design and added the `plugin_install_first_plugin_almost_finished_dialog_message` which we probably can improve a bit. I also agree with @nbradbury that "Installing Plugin" would probably be better for the initial title (maybe with ellipsis too).

I got the eligibility errors from the server side, but I have made some changes to it. The original errors mentioned Automated Transfer in the message, but I thought that would be confusing since we don't mention that in the initial dialog or anywhere else. Let me know if you want to change any of it. Also, keep in mind that these errors should be a very rare occurrence and we already handle as much of it as we can before the error can occur. So, just because we have an error message here, it does not mean we actually expect it to happen, we are just being defensive about it.

**Design Review**

I tried to record a video of the process a couple times, but the video is missing a few frames and looks a little weird. It's mostly a static dialog anyway, so I am just going to add some screenshots for it. I have skipped 14% & 71% screenshots and manually triggered the error one.

Questions for design review:
* Should we start from 1% or something like that? It takes about 10 seconds before it moves to 14% and most of the time it goes 14% at a time, but it's not guaranteed.
* Should we keep the toast for the error or go with something else?

screenshot_1524595389
screenshot_1524595392
screenshot_1524595408
screenshot_1524595435
screenshot_1524595437
screenshot_1524595947

### CODE REVIEW

**Comment by michelleweber** [comment]
Howdy, y'all! Some copy notes:

**Screen 1**
Install this plugin?

Installing first plugin can take up to one minute, and you won't be able to make any other changes to your site until installation is totally finished. Ready to proceed?

Cancel / Install

**Screens 2 & 3**
Installing plugin...

**Screen 4**
We're doing the final setup -- almost done...

**Comment by SylvesterWilmott** [comment]
Since we decided on the blocking progress meter I think we can cut down the copy on that first dialog:

`Install plugin`
`Installing the first plugin on your site can take up to 1 minute. During this time you won’t be able to make changes to your site`
`Cancel` `Install`

And agree with @michelleweber for screen 2, 3 and 4

**Comment by oguzkocer** [comment]
Updated the copies as suggested. Here are screenshots from after the change: https://cloudup.com/cbE9ElGEHfU

**Comment by oguzkocer** [comment]
I've got the all clear from our design god (@SylvesterWilmott) after adding a full stop at the end of the confirmation message. Thanks @SylvesterWilmott & @michelleweber!

@nbradbury Let me know if you'd like to do the code review or if I should look elsewhere :)

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
