### PR TITLE
Fix setting post ID for media uploads

### PR DESCRIPTION
**Pull request by aforcier**
**Not ready to merge!**

~~https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/426 should be merged first~~, and ~~3c2fb12 changed to the latest `develop` hash~~ done in 71cccab.

Sets the parent post ID of media uploads (when uploaded to a post that already exists remotely), and fixes a case where we were incorrectly setting the _local_ post ID as the media's parent post ID.

To test:
* Use the editor to upload media to posts (WP.com and self-hosted, local drafts and remote posts)
* After upload, open the media in the WP Media Library on the browser and confirm that:
  1. Media that were added to existing remote posts have those posts set as their parent (`Uploaded To` field)
  2. Media that were added to local draft posts have no parent

### CODE REVIEW

**Comment by nbradbury** [comment]
The code looks good but it doesn't appear to be working. I added an image from the WP media library to an existing post then uploaded the changes, but the image still shows as "unattached" in wp admin.

**Comment by nbradbury** [comment]
> This changeset only applies to media uploaded through the editor - already existing remote media won't be altered.

Ah, sorry - you did make that clear in the description.

**Comment by nbradbury** [comment]
OK, this appears to be working just fine. Should I review the FluxC branch, too?

**Comment by aforcier** [comment]
> OK, this appears to be working just fine. Should I review the FluxC branch, too?

Be my guest!

**Comment by aforcier** [comment]
https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/426 has been merged and I updated the FluxC hash - ready to go @nbradbury!

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
