### PR TITLE
Changed thumbnail size

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2563

## Description
Resizes thumbnails (from 136dpx204dp to 153dpx204dp) to have the same aspect ratio with the returned thumbnails to avoid awkward cropping .

|Downloaded image|Problem|
|---|---|
|||

## To test:
Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

1. Fresh install the app or clear storage (Device Settings>Apps>WordPress Beta>Storage & cache>Clear storage)
1. Login
1. Open the Modal Layout Picker 
1. Verify that the thumbnails are not cropped awkwardly

## Screenshot

|Before|After|
|---|---|
|device-2020-10-22-114307|device-2020-10-22-114238|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by chipsnyder — APPROVED** [review]
LGTM! I'll default to @iamthomasbishop's Design Review for the final 👍

**Comment by iamthomasbishop** [comment]
@antonis That looks much better! Would you mind adding screenshots of cases where there are 3+ thumbnails in a row, maybe also on some different device sizes? I don't foresee any issues based on the screenshots above, just want to make sure our overflows are looking okay 😄

**Comment by mkevins** [comment]
I reviewed and tested this on Pixel 3a (real device) as well as Pixel C (emulator) in both portrait and landscape modes, with the home pages row visible (which has many thumbnails available). Here are the results:

<details>
<summary>Portrait</summary>

Pixel 3a | Pixel C
-|-
pixel-3a-portrait | pixel-c-portrait

</details>

<details>
<summary>Landscape</summary>

| Pixel 3a |
|-|
|pixel-3a-landscape|

| Pixel C |
|-|
|pixel-c-landscape|

</details>


I'm not certain I encountered the exact "cropping" issue prior to these changes, I did notice that the image quality was reduced from the resizing (so it didn't look sharp), and this seems to be resolved now.

**Comment by antonis** [comment]
@chipsnyder and @mkevins thank you for taking the time to review this 👍 

@iamthomasbishop Matthew uploaded some screenshots already (thank you 🙇 )
I'm adding some more from an even smaller device (Nexus S: 480x800).

|One thumbnails |Two thumbnails |
|---|---|
|Screenshot_20201023_092124|Screenshot_20201023_092051|

I also noticed an issue with the selection layer checkmark (white pixels) after the resize and fixed it

|White pixels around checkmark|Fix|
|---|---|
|Screenshot_20201023_092355|Screenshot_20201023_102015|

**Comment by iamthomasbishop** [comment]
@antonis @mkevins Thanks for adding the screenshots, y'all! The new dimensions on the thumbnail cells work well — rock on! 🚀 

> I also noticed an issue with the selection layer checkmark (white pixels) after the resize and fixed it

@antonis Thank you!! I think I noticed that early in the review process but hadn't seen it lately. As it happens, my instinct for selecting the clean, white-background thumbnail images while testing meant I wasn't seeing the issue often 😄  Thanks for your attention to detail!

**Pull request merged**
