### PR TITLE
Issue/6680 remove deleted local media

### LINKED ISSUE #6680: Unhelpful toast when retrying deleted media
If you tap to retrying uploading an image you deleted from the device, you get the unhelpful error toast shown below. If it’s not even on the device, we should remove it or at very least say “unavailable” and not allow an action on it

screenshot_1506696872

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6680 by automatically removing local (non-uploaded) media that no longer exists.

To test:

* Put the device in airplane mode (so the media doesn't get uploaded)
* Add a picture from your device to the media library, then close the media library
* Delete the photo from your device (note this may require emptying the trash if you use Google Photos)
* Turn off airplane mode
* Return to the media library, the deleted media should automatically be removed

### CODE REVIEW

**Comment by daniloercoli** [comment]
Have we explored the idea of keeping the file in the media library, and add a customized message for this particular case?
Instead of deleting it from our library reference, we can provide info to recover the file from the Trash. (Corner case? just prosing ideas here).

**Comment by nbradbury** [comment]
> Have we explored the idea of keeping the file in the media library, and add a customized message for this particular case? Instead of deleting it from our library reference, we can provide info to recover the file from the Trash. (Corner case? just prosing ideas here).

I think the initial idea was to keep the image and overlay it with a "missing" label (or something along those lines). But you couldn't do anything with it except delete it, and you'd want to delete it, so it made sense to simply delete it silently.

I don't know how we'd enable recovering the image, since it's a device image that no longer exists.

**Comment by daniloercoli** [comment]
> But you couldn't do anything with it except delete it, and you'd want to delete it, so it made sense to simply delete it silently.
I don't know how we'd enable recovering the image, since it's a device image that no longer exists

Yes, the only thing we can do is redirecting them to the trash folder of Google Photos, assuming that they're using that app. Anyway I see this a bit too much for the moment, so i'm going to merge this PR. Feel free to open a new ticket if you think we should investigate the point raise above more.

**Comment by daniloercoli** [comment]
Could we call `ensureCorrectState` on resume, or early in the execution flow?
I noticed that it's called on response from the server, but on my connection it tool a while the server to respond, keeping me with the `retry` option for a while.

**Comment by nbradbury** [comment]
> Could we call ensureCorrectState on resume, or early in the execution flow?

I was worried about calling that routine too often since I feared it would hurt performance, but after looking at it again I realized it could easily be optimized. So, I've rewritten `ensureCorrectState()` and now it's called whenever the media grid is populated.

**Comment by daniloercoli** [comment]
LGTM!

**Pull request merged**
