### PR TITLE
Issue/8012 discard changes additions

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add the following to the ***Discard Local Changes*** feature as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8012.
- `18dp` spacing between snackbar message text and action button for two-button layout
- `AccessibilityUtils.getSnackbarDuration()` for snackbar durations
- `BasicFragmentDialog` for error when discarding changes

See the screenshots below for illustration.

discard_changes_preview_margin

#### Snackbar Spacing
1. Go to ***My Site*** tab.
2. Tap ***Blog Posts*** item under ***Publish*** section.
3. Tap ***Preview*** button on a post with local changes.
4. Notice snackbar with updated spacing.

#### Dialog Fragment
0. Disable network connection.
1. Go to ***My Site*** tab.
2. Tap ***Blog Posts*** item under ***Publish*** section.
3. Tap post with local changes.
4. Tap overflow menu action.
5. Tap ***Discard Local Changes*** item.
6. Notice error dialog.
7. Rotate device.
8. Notice error dialog.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good!

**Comment by malinajirka** [comment]
Thanks @theck13 ! Everything works and looks as expected.

I know it's not part of this PR, but it's related so I'm gonna ask here. I've noticed when the OnPostChanged event contains error, we always show the 'TAG_DISCARDING_CHANGES_ERROR_DIALOG`

- [EditPostActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/4b3f1eba31dc7ac54bc1d41eead9f423d40e62b6/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L3413)

- [PostPreviewActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/4b3f1eba31dc7ac54bc1d41eead9f423d40e62b6/WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java#L421)

Shouldn't we first check whether the `mIsDiscardingChanges` is true?

**Comment by theck13** [comment]
> Shouldn't we first check whether the `mIsDiscardingChanges` is true?

That's right.  Errors could occur by `PostAction.UPDATE_POST` even though it's not due to discarding changes.  I added that condition in 553bede.

**Comment by malinajirka** [comment]
Thanks!! Looks good.

**Pull request merged**
