### PR TITLE
Fix #3962 (smart lock crash) and Fix #3954 (smart lock enhancement)

### LINKED ISSUE #3954: Improve Smart Lock for Password by adding Name and Profile Picture url to credentials
Once we get the response for the `/me` endpoint, we can fill the name and profile picture url in smart lock for password credentials to present a nicer picker (the picker is only visible if the user has several credentials saved).

https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/Credential.Builder.html#public-methods

### LINKED ISSUE #3962: Crash report alpha-5: GoogleApiClient is not connected when `saveCrendentialsInSmartLock` is called
```
Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.internal.zzmf.zzb(Unknown Source)
       at com.google.android.gms.internal.zzmi.zzb(Unknown Source)
       at com.google.android.gms.internal.zzmg.zzb(Unknown Source)
       at com.google.android.gms.auth.api.credentials.internal.zzd.save(Unknown Source)
       at org.wordpress.android.ui.accounts.SignInFragment.saveCrendentialsInSmartLock(SignInFragment.java:643)
       at org.wordpress.android.ui.accounts.SignInFragment.access$2400(SignInFragment.java:85)
       at org.wordpress.android.ui.accounts.SignInFragment$15.onSuccess(SignInFragment.java:677)
       at org.wordpress.android.ui.accounts.helpers.LoginWPCom$1.onResponse(LoginWPCom.java:97)
       at org.wordpress.android.ui.accounts.helpers.LoginWPCom$1.onResponse(LoginWPCom.java:73)
       at com.wordpress.rest.Oauth$Request.deliverResponse(Oauth.java:96)
       at com.wordpress.rest.Oauth$PasswordRequest.deliverResponse(Oauth.java:113)
       at com.wordpress.rest.Oauth$Request.deliverResponse(Oauth.java:77)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by maxme**
Fix #3962: Fix a crash when CredentialsApi is disconnected.
Fix #3954: Add display name and profile picture to the saved credentials.

### CODE REVIEW

**Comment by kwonye** [comment]
@maxme in #3973 I've added a few additional safeguards. I think we should add one aspect of those changes to this PR as it'll be easier to find later: [Disconnect ApiClient onDestroyView()](https://github.com/wordpress-mobile/WordPress-Android/pull/3973/files#diff-d1955c04c369a8c269a4d81a5fdbe99fR230)

**Comment by kwonye** [comment]
Please only smartlock fill the username/pw if they are both blank.

**Comment by maxme** [comment]
> I think we should add one aspect of those changes to this PR as it'll be easier to find later: Disconnect ApiClient onDestroyView()

I think we should not do that. From the `GoogleApiClient.Builder enableAutoManage` documentation:

> Enables automatic lifecycle management in a support library FragmentActivity that connects the client in onStart() and disconnects it in onStop().

**Comment by maxme** [comment]
> Please only smartlock fill the username/pw if they are both blank. What happened was I tried signing into a different account and when I came back from my 2FA app, smartlock overwrote the username/pw.

**Comment by kwonye** [comment]
> I think we should not do that. From the GoogleApiClient.Builder enableAutoManage documentation:
Enables automatic lifecycle management in a support library FragmentActivity that connects the client in onStart() and disconnects it in onStop().

Good call. I'll remove it from that PR.

**Comment by kwonye** [comment]
Also, a too late :shipit:

**Pull request merged**
