### PR TITLE
Integrate gutenberg release 1.34.0

### PR DESCRIPTION
**Pull request by ceyhun**
This PR incorporates the 1.34.0 release of gutenberg-mobile. For details about the changes included in this PR and testing instructions please see the related gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2529

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dratwas** [comment]
DarkMode-2

 - [ ] Spacer block - Dark mode
 - [ ] Buttons block - Dark mode
 - [ ] Group - Dark mode
 - [ ] Columns - Dark mode

Group-2

 - [ ] Group - Navigation up button works as expected
 - [ ] Group - Navigation down works according to parent-first approach
 - [ ] Group - Cross navigation between blocks works as expected
 - [ ] Group - Ungroup button works as expected
 - [ ] Group - Check if in DarkMode all components gets proper colors
 - [ ] Group - Check if nested Placeholder block can be replaced

Spacer-2

 - [ ] Spacer block - Settings: Available height range is correct
 - [ ] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px
 - [ ] Spacer block - Spacer in horizontal layout works as expected

Buttons-4

 - [ ] Buttons block - Render custom text color
 - [ ] Buttons block - Render custom background color
 - [ ] Buttons block - Render gradient background color
 - [ ] Buttons block - Check if selection / caret color matches font color
 - [ ] Buttons block - The newly created Buttons has set background color to the theme-default color in preview

Button-5

 - [ ] Buttons block - Edit text styles
 - [ ] Buttons block - Render theme colors
 - [ ] Buttons block - Settings: Change Button border radius

Button-7

 - [ ] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options
 - [ ] Buttons block - Toolbar link button is active when Button has link

Editor Theme - 2

 - [ ] Custom Gradients - Check that custom gradients load in the editor
 - [ ] Offline Support

Color Settings - 2

 - [ ] Pressing color swatch
 - [ ] Customize gradient color
 - [ ] Custom color picker

**Comment by pinarol** [comment]
@chipsnyder can you check if there's anything odd about Editor Theme failed cases reported above?

**Comment by chipsnyder** [comment]
Tested the Editor Theme - 2 above using the this [APK](https://64750-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-12588-build-64750.apk) 

I had no problems: 


@dratwas If you open the editor a second time does the theme load? I wonder if the event for updating the theme was lost over the bridge loading. 

cc @pinarol

**Comment by dratwas** [comment]
>@dratwas If you open the editor a second time does the theme load? I wonder if the event for updating the theme was lost over the bridge loading.

Hey, @chipsnyder I tried the same build on 2 different devices and have the same issue on both of them. The reopening of the editor doesn't help :( I can use this gradient only on the web and see just in preview (even on the web -  it has default background in the visual editor). The same issue occurs on the emulator.

**Comment by chipsnyder** [comment]
After a bit of research and discovery with @dratwas help, we tracked this down to an issue with a Jetpack sync. It seems like it's updating these values with the data from the previous theme instead of the new theme. So the API response has the values for theme change n-1 if n is the current theme. 

@enejb is helping to investigate.

**Pull request merged**
