### PR TITLE
Issue/3247 reader gap detection

### PR DESCRIPTION
**Pull request by nbradbury**
A longstanding problem in the reader is that if you follow a high-traffic tag or haven't synched in a while, there may be a gap of missing posts between those just retrieved and those already on the device.

This PR attempts to address this by detecting these gaps and displaying a "gap marker" to indicate when posts are missing (very similar to Twitter). Tapping this gap marker retrieves the next batch of posts below the gap, then removes the existing posts below the gap (which will subsequently be filled in by infinite scroll).

To test this, follow a high-traffic tag like "sports" and set [READER_MAX_POSTS_TO_REQUEST](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java#L4) to 4 so the gaps occur more frequently. After synching the Android reader, open the web reader to that tag and wait for the number of new posts to exceed 4. When you pull-to-refresh in the app, it should show the latest posts with a gap marker below them.

_qsywgzg2o

Note: this PR is the Android equivalent of [this iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4311). @aerych gets the credit for the logic of gap detection.

### CODE REVIEW

**Comment by maxme** [comment]
It would be great to have a xxxhdpi `reader_tear` in `WordPress/src/future/res/drawable-xxxhdpi/`

**Comment by maxme** [comment]
I experienced something weird: 

* Tapped "Load more post"
* Scrolled to the top, then PTR to refresh the view (I think 1 new post was added here)
* Scrolled down, reader pulled some "old" articles (with the loading indicator showing on the bottom of the screen)
* Loading indicator was hidden and now I can't load more "old" posts 

Note: I set READER_MAX_POSTS_TO_REQUEST to 4 and currently in the Tag, I've 10 posts.

**Comment by maxme** [comment]
I tried to switch tag and get back to that one where I was stuck. When I try to load more "old" posts by scrolling down, I see the loading indicator for a second. it stops, but no "old" posts.

**Comment by maxme** [comment]
Another weird behavior:

* "Load more post" button was shown
* I scrolled up and refreshed the view (PTR), no new post were added
* Scrolled down, and the "Load more post" was not there anymore

**Comment by nbradbury** [comment]
@maxme I made a couple of changes to address the issues you mentioned:

* Swipe-to-refresh is now disabled while an update is in progress to prevent concurrent updates. This should've been in the app a while ago - an oversight on my part.

* The gap marker is now removed when the "New Posts" message appears (since the gap marker will be stale at this point).

I should have an `xxxhdpi` version of that image in the next day or two.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
