### PR TITLE
Only hide featured image when posts starts with an image

### LINKED ISSUE #7587: Featured images not displayed in Reader's single post view
I subscribe to quite a few Jetpack sites in the Reader, and I can see the featured images / images Reader picked for that post when looking at the posts in the list view. However, when I tap in the post to view the full image, it is nowhere to be found:

List view, where a thumbnail of the image appears:
screenshot_20180401-114728

In single view, the image is nowhere to be seen:
screenshot_20180401-114722

Would it be possible to display those images there?

<ul>
    <li>HTC U11</li>
    <li>WPAndroid Alpha 105</li>
</ul>

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #7587 

This piece of logic seems to be wrong. We're not adding the featured image any time the post contains any image. That can't be right. I think maybe originally it was supposed to not add the featured image only when the post starts with an image? I'd also be fine with removing the whole check because why not show the featured image on each post. 

Any idea about this @designsimply ?

To test:
* Go to Reader
* Click on an item with a featured image
* You see the featured image under the title
* Go back to Reader
* Click on an item without a featured image
* You don't see the featured image under the title
* Repeat with various sites/posts

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
Hi @planarvoid I have not tested the code yet (even if it seems quite straightforward), but waiting for the feedbacks from @designsimply  and hoping that it could be helpful in some way, I gave a look at how the behaviour is in Calypso reader (as a user, didn't go into the code). As far as I can tell, the reader in Calypso actually always adds the featured image when accessing the full post in the cases we are highlighting here:

- post without images in the body
- post with images in the body (both at the start of the body or in a different position inside the body)

A second confirmation of this behaviour would be useful, but if confirmed I would consider to align to Calypso reader and always add the feature image if present.

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.4` today, so this is being bumped to `13.5`. If you'd like it to go out as part of `13.4`, please target `release/13.4` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by planarvoid** [comment]
> A second confirmation of this behaviour would be useful, but if confirmed I would consider to align to Calypso reader and always add the feature image if present as you suggested.

@develric I've removed the `startsWith` and now we should be adding the featured image on all the posts.

**Comment by designsimply** [comment]
Sorry for the delayed reply! I see that in Slack you discussed that a change was made in 2014 with the following comment, which makes us believe the intention at that time was to show the featured image for individual posts in the Reader _only_ if there are no images in the post's content (and that this logic may not be working as intended at the moment).

>      /*
>     * returns true if the post has a featured image and there are no images in the
>     * post's content - when this is the case, the featured image is inserted at
>     * the top of the content
>     */

This comment from @nbradbury is also worth noting:

> So...if I remember correctly, in the reader post detail we only wanted to show an image at the top of a post if a featured image was assigned and there aren’t any other images in the post. Why we made this decision has been lost to the past.

I suspect that decision was made because most people who set a featured image set it to be the same image as the predominant image in the post. And in that fairly common use case, if you show the featured image at the top of the individual post in the Reader as well as the one in the body (which is the change it sounds like you're making here) and then the user adds an image to the body of the post and also sets the featured image to be that same image (this is pretty common), then what happens is that we receive complaints from users saying the image is showing double—which it is… because they added it twice: once as the featured image and once near the top of the post, but it _feels_ like a bug to the user in that case. I suspect that the logic is different in the app compared to Calypso because a seemingly (but actually added twice) image showing in the Reader is perceived by users as a bug more often than a case where the featured image does not show up is complained about. So, in summary, either way you choose to do it and both logic arguments are valid 🙂 and we likely opted in the past to choose the one that's different from Calypso (do not show featured images on individual posts in the Reader in the app if there is an image in the content) because the experience is different on mobile and feels more like a bug to users whereas the case Jeremy raised is more rare and therefore less complained about. You can't really have it both ways, users will complain regardless of which option you choose, so the best thing to do is to choose the experience you think will work best for most users and then explain why the decision was made to the rest.

cc @rachelmcr about my hunch in the paragraph above because you may have additional insight about the reason the decision about not showing a featured image for individual posts in the Reader was made in the past. 😊

In the case of @jeherve's bug report at https://github.com/wordpress-mobile/WordPress-Android/issues/7587, his example is a bit of an edge case because the blog in the screenshots he showed is a Jetpack blog with the feed set as a summary feed (see Settings > Reading > For each article in a feed, show) which you can tell in the app because of the "Visit Eric Binnion" for more" block at the bottom of the post in the 2nd screenshot showing the individual post detail Reader for that post. So! [That post](https://eric.blog/2018/03/31/about-20-and-20-minutes-to-replace-the-back-on-my-phone-not-too-bad/) likely has no featured image set and Calypso Reader shows the first image from the post in the Reader Stream and no image in the post because the post probably does not have any featured image set and the feed does not send an image from the body through with the excerpt because the blog is setup to use the a summary feed instead of a full text feed. 

> show the featured image for individual posts in the Reader _only_ if there are no images in the post's content

In my opinion, the logic to show the featured image for individual posts in the Reader _only_ if there are no images in the post's content seems like a good option because without it I'm pretty sure users will report images showing up double as a bug even though it's a design decision. cc @osullivanchris

**Comment by nbradbury** [comment]
> I suspect that decision was made because most people who set a featured image set it to be the same image as the predominant image in the post.

@designsimply Thanks for jostling my memory - you're exactly right about that. I remember now that we got complaints about duplicate images which is why we changed that logic.

**Comment by planarvoid** [comment]
thanks for the detailed reply @designsimply ! What do you think that instead of only showing the featured image only if there are no images in the post I try to look for an image with the same name and only hide featured image if there is an image with the same name within the post?

**Comment by rachelmcr** [comment]
> What do you think that instead of only showing the featured image only if there are no images in the post I try to look for an image with the same name and only hide featured image if there is an image with the same name within the post?

That seems like a reasonable approach to me. I looked for how Calypso does de-duping for featured images and I found where it was implemented in https://github.com/Automattic/wp-calypso/pull/14719 using image URLs, similar to what you're proposing. (Note that there is a known issue with the Calypso approach when the post has images with size variants, see https://github.com/Automattic/wp-calypso/issues/19544.)

**Comment by osullivanchris** [comment]
Thanks for the detailed explanation @designsimply 

I just want to add one contributing factor. On mobile I would expect a featured image to look in some way like a header, showing above all the headings and body content.

In fact when I look at the reader on desktop the featured image is truly used as a header image, behind the heading and author image.

We are treating featured images visually like something that is in the body of the post. Leading to issues like confusion between featured image and other image, duplication, etc.

Would it solve the problems if we treated the featured image more like a header per calypso/web?

Screenshot attached just to clarify what I'm talking about, I hope I am understanding the context correctly
screenshot

**Pull request merged**
