### PR TITLE
Support forum:  remove feature flag

### LINKED ISSUE #18816: Support Forum: Remove Feature Flag
This feature flag is no longer necessary, hence to be removed

### PR DESCRIPTION
**Pull request by ravishanker**
Removes Support Forum Feature Config as it is no longer required.

Fixes #18816 

| WordPress | Jetpack |
|--------|--------|
|Screenshot_20230724_195301 | Screenshot_20230724_195344| 

To test:

- Launch WP app
- Go to Help screen (Me -> Help)
- `Verify` the help screen is as shown in first image above, and there is no `Contact support` option
- Tap on `Community forums`
- `Verify` it goes to WP Mobile App Forum on the web
- Logout
- Try the above steps from Help on Login screen
- `Verify` it goes to Help screen, and `Community forums` goes to forum on the web
===============================================================
- Launch JP app
- Navigate to Help screen (Me -> Help)
- `Verify` help screen looks as second image above
- Tap on Contact support
- `Verify` it opens Zendesk chat (after confirming email, if not done already)

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Existing tests, and manual testing

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ravishanker** [comment]
👋 @wordpress-mobile/mobile-ui-testing-squad - ContactUsTests are passing when run locally, and seems to fail on CI!  Could you please take a look. 🙇 
Screenshot 2023-07-25 at 12 27 56 pm

**Comment by jostnes** [comment]
> 👋 @wordpress-mobile/mobile-ui-testing-squad - ContactUsTests are passing when run locally, and seems to fail on CI! Could you please take a look. 🙇 Screenshot 2023-07-25 at 12 27 56 pm

👋 @ravishanker! I investigated and found that the failing test in the CI is running against the WP app. The test wasn't able to go through the flow as the Contact Support button is not available (which is expected behavior in this case):
image

We need to update the test case so the WP variant doesn't go through the contact support flow. I'm testing a fix now and will let you know and push a commit if it works.

**Comment by jostnes** [comment]
👋 again @ravishanker, I pushed a fix in https://github.com/wordpress-mobile/WordPress-Android/pull/18818/commits/53668f98afeb48d65bdf1b2ef87a7e5c41792e05 . With this change, the Support Contact flow is only executed on the JP app, the test for the WP app ends after asserting that the right items are displayed on the screen.

Next time something similar to this happens, I would recommend that you go through the Firebase video first, which is always helpful to determine the cause of the failure if you need still need help after that feel free to ping us and we'll try to help as best as we could!

**Review by irfano — APPROVED** [review]
LGTM! WP and JP apps work as expected. 👍🏻

**Pull request merged**
