### PR TITLE
[Bug] Move a small bug fix to a more appropriate place.

### LINKED ISSUE #20026: Android 14 infinite progress bar when selecting specific media from device
### Expected behavior

When uploading media, selecting "choose from device", then selecting only a few media options vs "Allow All" when prompted, should work as normal and paginate properly.

### Actual behavior

When the device has media, we query the media, then we filter it out based on the `MimeType`. This is important because our pagination logic utilizes a `lastModified` timestamp which we use from the queried media. But when we [filter out unsupported mime types](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java#L297), we inadvertently miss out on toggling the media loading progress bar to off.

Screenshot_20240118_165304

### Steps to reproduce the behavior

- [ ] The ideal scenario is to have MP3s on your device since I know that reproduces it.
- [ ] Use Android 14, which allows you to choose specific media to allow WP/JP to access.
- [ ] Load the app and go to More -> Media -> Click plus icon on the top right (+) -> Choose from device
- [ ] Only allow certain media. 2 or 3 images is enough.
- [ ] Assuming you met all the criteria, an infinite progress bar will show.

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

* Galaxy Z Fold 5
* Android 14
* Jetpack `24.0`

### PR DESCRIPTION
**Pull request by notandyvee**
Fixes #20026

Related: https://github.com/wordpress-mobile/WordPress-Android/pull/19979

-----

## To Test:

You'll need an Android 14 samsung device to test as that is where the bug is reproduced in

- [ ] The ideal scenario is to have MP3s on your device since I know that reproduces it. I have slack installed and the ringtone mp3s are what is popping up.
- [ ] Use Android 14, which allows you to choose specific media to allow WP/JP to access.
- [ ] Load the app and go to More -> Media -> Click plus icon on the top right (+) -> Choose from device
- [ ] Only allow certain media. 2 or 3 images is enough.
- [ ] The loading progress bar under the media should disappear.
- [ ] Allow access to all media. Ensure you can paginate properly.

-----

## Regression Notes

1. Potential unintended areas of impact

    n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    Tested access media on my device.

3. What automated tests I added (or what prevented me from doing so)

    n/a

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/277">24.3</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by notandyvee** [comment]
@irfano I can't get a hold of an additional android 14 samsung device to test this properly. I can't actually reproduce the issue outside of my samsung device. I'll update if I do. In the meantime the fix essentially just moves the same logic from line 72 to 121. 🚬 testing media viewing on an Android 14 device should suffice.

**Review by irfano — APPROVED** [review]
I have tested `trunk` on my Android 14 Samsung device to reproduce the issue, but I couldn't. I also tested this PR on the same device, and it still works without any issues.
I'm approving the PR, but I am leaving merging to you in case you want to make changes based on my test results with the Samsung device.

**Comment by notandyvee** [comment]
Thanks for that @irfano. Could you actually try and apply this [patch](https://github.com/wordpress-mobile/WordPress-Android/files/14314128/repro-bug-patch.patch) after checking this branch out? It just undoes the changes that fixes the bug. And try again. You need to have mp3s. Having slack installs is an easy way to get some mp3s. Let me know if you still can't reproduce.

**Comment by irfano** [comment]
I applied the patch. Downloaded some mp3 files to the "Downloads" folder. I installed Slack. Followed test instructions in the description. Still can't reproduce the issue.

**Comment by notandyvee** [comment]
@irfano it was bothering me so I spent more time looking for ways to reproduce this. I found out the reason. I guess the audio type matters. I recommend you use an emulator for this. Attaching a zip with ~35 audio files. I believe those are voicemail files. Idky, but my phone has those files. The key is having enough of those files to paginate. Hence > 32, which is the pagination amount. Copy those files into your emulator to reproduce this bug. Then confirm the branch itself fixes it.

[test-audio.zip](https://github.com/wordpress-mobile/WordPress-Android/files/14316002/test-audio.zip)

Screenshot 2024-02-16 at 4 03 26 PM

**Comment by irfano** [comment]
I tried what you suggested, but I still can't reproduce it. Sharing the video here to ensure my steps are the same as yours.

[Screen_recording_20240219_150550.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/248cf0f2-a7b9-4c56-a554-f3e006902163)

**Comment by irfano** [comment]
I forgot to apply the patch in my previous comment. I was able to reproduce it after applying the patch.
Now everything makes sense with your original fix and updating the place of the fix LGTM!
Thank you for investigating this issue and helping me test it. 👍🏻 Merging now.

**Pull request merged**
