### PR TITLE
[Dependency Updates] Main Batch - AndroidX Core

### LINKED ISSUE #17561: Dependency Updates - Main Batch - AndroidX Core
Parent #17551
Batch Branch: [deps/main-batch-androidx-core](https://github.com/wordpress-mobile/WordPress-Android/tree/deps/main-batch-androidx-core)

-----

🚫 Blocked By:
- [x] #17560 and its `kotlinxCoroutinesVersion` update to `1.6.4` (for more info see #17643)

-----

This issue is about updating all `Main - AndroidX Core` related dependencies for the whole project.

This `Main - AndroidX Core` batch contains the following `5` dependencies:

- [x] `androidxArchCoreVersion = '2.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/arch-core)) #17642
- [x] `androidxLifecycleVersion = '2.4.1'` (see [releases](https://developer.android.com/jetpack/androidx/releases/lifecycle)) #17643
- [x] `androidxCoreVersion = '1.3.2'` (see [releases](https://developer.android.com/jetpack/androidx/releases/core)) #17691 
- [x] `androidxFragmentVersion = '1.4.1'` (see [releases](https://developer.android.com/jetpack/androidx/releases/fragment)) #17696
- [x] `androidxAppcompatVersion = '1.1.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/appcompat)) #17743

PLUS:

- #18366

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #17551
Closes #17561

This PR updates:
- [x] `androidxArchCoreVersion` to [2.1.0](https://developer.android.com/jetpack/androidx/releases/arch-core#2.1.0) (via #17642).
- [x] `androidxLifecycleVersion` to [2.5.1](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.1) (via #17643).
- [x] `androidxCoreVersion` to [1.8.0](https://developer.android.com/jetpack/androidx/releases/core#1.8.0) (via #17691).
- [x] `androidxFragmentVersion` to [1.5.5](https://developer.android.com/jetpack/androidx/releases/fragment#1.5.5) (via #17696).
- [x] `androidxAppcompatVersion` to [1.4.2](https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.2) (via  #17743).

Note that this is the parent branch were all the above PRs were targeting. As such:
1. The code review part was already done as part of the individual PRs above. Thus, no Dev is to review this PR.
2. This PR's sole purpose is making sure these changes are thoroughly tested by a QE.

-----

PS: @pachlava I added you as the main reviewer, that is, in addition to the @wordpress-mobile/apps-infrastructure team itself, since I just wanted someone from the QE team to thoroughly test and sign-off on that change for WPAndroid.

-----

To test:

- Thoroughly smoke test both, the WordPress and Jetpack apps, and see if they both work as expected.
- In addition to the above smoke test, per the linked PRs above, you could follow the individual test instructions included in them and focus on the specifics of what to test per update.

-----

### Merge instructions

- [x] Wait for #17743 PR to be approved and merged to this `deps/main-batch-androidx-core` branch.
- [x] Update PR with latest `trunk`.
- [x] Remove `[PR] Not Ready For Merge]` label.
- [x] Prepare and update PR to a `Ready for review` state.
- [x] Assign a QE reviewer.
- [ ] Merge PR to `trunk`.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Potential breakage of screens and core functionality as these `AndroidX Core` libraries are being added as a transitive dependency across lots of `androidx` and `com.google` and `other` libraries.
    - Some of the transitive dependencies added might be causing some kind of misbehaviour.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

    - `N/A`

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pachlava** [comment]
@ParaskP7 👋 

I started with some testing today, and there's one thing I've noticed so far. This was on real `Samsung A31 | Android 12`.

1. (Not 100% sure if this is expected to work for Pre-Alpha builds generally, but I tend to think yes)

- Select "Log in with WP.com"
- Select "Continue with Google"
- I had an G account already known to my phone, so it was available for selection in the pop-up shown right after previous step.
- Select the account ~> after a brief `Logging in` overlay, nothing happens.

It does work well with `21.5-rc-1` though.

**Comment by ParaskP7** [comment]
👋 @pachlava !

First of all, thank you so much for for eagerness in testing and already finding something, much appreciated. 🙇‍♂️

But, could you please hold on your testing until this PR get ready for review, after I merge this other pending PR into it and explicitly assign you as a reviewer here? 🙏

I would hate asking you to re-test this PR, thus having you doing this twice. Apologies for not being too clear about the fact that this PR is not ready for testing. With my request for QE, I was trying to have you plan for the testing on this PR a bit in advance so that I know who to assign to it when it gets ready. I hope that makes sense, again many thanks and apologies for any inconvenience. 🙏

**Comment by pachlava** [comment]
Oh, it's my bad @ParaskP7 😅 

For whatever reason, I thought that it's ready for review, even though I clearly saw that it's still a draft. No worries, yesterday I just spent a little time in the login area, so it's not a problem 👍

**Comment by ParaskP7** [comment]
Thank you so much @pachlava and apologies for any inconvience! 🙇 🙏 🌟 

> yesterday I just spent a little time in the login area

🥇 

PS: I'll ping you once this PR is ready for review, this will be maybe done today, but to be honest, I feel like this will happen next week. It all depends on how quickly this [other PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17743) is going to be reviewed. 🤞

**Comment by ovitrif** [comment]
Following up on [this conversation](https://github.com/wordpress-mobile/WordPress-Android/pull/17743#pullrequestreview-1247690981) from the last PR that's now merged to this branch, I noticed an crash in Reader → Comments on both apps (WordPress & Jetpack) that I could reproduce every time:

**Crash in Reader →  Comments**
1. Build & open WordPress or Jetpack app from this branch
2. Login
3. Go to Reader → Discover (or any tab)
4. Tap on the `💬 Comments` icon for a post (3rd icon below)
5. **Notice** the app crashes

Since the crash was not reproducible on `trunk` I suspect it might be caused by possible incompatibilities with the updated dependencies from this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/17743.
I also tested on commit https://github.com/wordpress-mobile/WordPress-Android/pull/17741/commits/ba732819753ce0b44d4d04d0cdf5dfee64a5d5fe which was the last change on this PR before merging the PR linked above, and there the crash doesn't reproduce 🤔 .

<details>
<summary><h4>💥 Crash Log (click to expand) ↘️</h4></summary>

```js
FATAL EXCEPTION: main
Process: com.jetpack.android.beta, PID: 9450
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jetpack.android.beta/org.wordpress.android.ui.reader.ReaderCommentListActivity}: android.view.InflateException: Binary XML file line #60 in com.jetpack.android.beta:layout/reader_activity_comment_list: Binary XML file line #39 in com.jetpack.android.beta:layout/reader_include_comment_box: Error inflating class org.wordpress.android.widgets.SuggestionAutoCompleteText
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
        ...
Caused by: android.view.InflateException: Binary XML file line #60 in com.jetpack.android.beta:layout/reader_activity_comment_list: Binary XML file line #39 in com.jetpack.android.beta:layout/reader_include_comment_box: Error inflating class org.wordpress.android.widgets.SuggestionAutoCompleteText
Caused by: android.view.InflateException: Binary XML file line #39 in com.jetpack.android.beta:layout/reader_include_comment_box: Error inflating class org.wordpress.android.widgets.SuggestionAutoCompleteText
Caused by: java.lang.reflect.InvocationTargetException
        ...
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
    at org.wordpress.android.ui.reader.ReaderCommentListActivity.onCreate(ReaderCommentListActivity.java:169)
    at android.app.Activity.performCreate(Activity.java:8305)
    ...


Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.ui.suggestion.util.SuggestionTokenizer.findTokenStart(java.lang.CharSequence, int)' on a null object reference
    at org.wordpress.android.widgets.SuggestionAutoCompleteText.enoughToFilter(SuggestionAutoCompleteText.java:67)
    at android.widget.AutoCompleteTextView.refreshAutoCompleteResults(AutoCompleteTextView.java:961)
    at android.widget.AutoCompleteTextView$MyWatcher.afterTextChanged(AutoCompleteTextView.java:927)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:11081)
    ...
    at androidx.emoji2.viewsintegration.EmojiEditTextHelper$HelperInternal19.<init>(EmojiEditTextHelper.java:268)
    at androidx.emoji2.viewsintegration.EmojiEditTextHelper.<init>(EmojiEditTextHelper.java:109)
    at androidx.appcompat.widget.AppCompatEmojiEditTextHelper.<init>(AppCompatEmojiEditTextHelper.java:52)
    at androidx.appcompat.widget.AppCompatMultiAutoCompleteTextView.<init>(AppCompatMultiAutoCompleteTextView.java:97)
    at androidx.appcompat.widget.AppCompatMultiAutoCompleteTextView.<init>(AppCompatMultiAutoCompleteTextView.java:74)
    at org.wordpress.android.widgets.SuggestionAutoCompleteText.<init>(SuggestionAutoCompleteText.java:36)
    ... 38 more
```
</details>

**Comment by ParaskP7** [comment]
> Following up on https://github.com/wordpress-mobile/WordPress-Android/pull/17743#pullrequestreview-1247690981 from the last PR that's now merged to this branch, I noticed an crash in Reader → Comments on both apps (WordPress & Jetpack) that I could reproduce every time:

Thank you so much for finding this crash @ovitrif , much appreciated, I'll follow the details on it and try to figure out a fix! 🙇 

In the meantime, I'll update this PR with latest `trunk` and make it ready for review so that @pachlava can start QE testing on this PR as well. 🙏 

Once more, thank you both for helping with the testing efforts on this very important change! 💯

**Comment by ParaskP7** [comment]
👋 @pachlava !

FYI: This [other PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17743) that I mentioned above has been now merged to this PR, I also updated this PR with latest `trunk`, assigned you as a QE to this PR and effectively made this PR review for review. You can now start testing at your earliest convenience.

PS: In the meanwhile I'll take a look at [this crash](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1381943601) that @ovitrif just found.

**Comment by ParaskP7** [comment]
👋 @ovitrif 

> Crash in Reader → Comments
> - Build & open WordPress or Jetpack app from this branch
> - Login
> - Go to Reader → Discover (or any tab)
> - Tap on the 💬 Comments icon for a post (3rd icon below)
> - Notice the app crashes

I managed to fix this crash by applying a simple fix (181781a1282bdc20c751fd659ae5c31129bc8acf). Can you double check again next week and let me know if you also think that this nullability fix is enough? 🙇

**Comment by lmischner** [comment]
Coverage:
Primarily in Jetpack, some in WordPress.

[x] Edit media from a post
(cropping using edit box as well as zoom and rotation)
[x] Preview post from individual post's editor and from Posts > Drafts screen
[x] Saving
[x] Reader/Discover view - view comments, save posts, like posts
[x] Comments (reply, like, edit)
[x] Media picker (from different types of image blocks and in the Media screen)
[x] Create site
[x] Stats of a post

Were there other areas I missed that were affected? 


Questions/issues:
* When I edit a comment, I'm seeing the `<p>` tags in the comment itself. Is this expected in Android? I'm not seeing the same in the iOS apps. 
* If I manually type HTML into a comment, should we render it in the saved comment? 
* When I add an image to a gallery block, the outline is misaligned:
Screenshot_20230113-125901
* Should previewing a page/post require logging in? In iOS, preview shows an overlay with the content, in Android it opens the page in a browser and (depending on the site) may require logging in.

**Comment by ParaskP7** [comment]
Thanks for helping with the testing efforts @lmischner , this so much appreciated! 🙇 🙏 🥇 

> Were there other areas I missed that were affected?

Actually, the whole app is affected as these updates are core to Android. Thus, I can't exactly specific the areas. The more screens and functionalities we test the better.

> When I edit a comment, I'm seeing the <p> tags in the comment itself. Is this expected in Android? I'm not seeing the same in the iOS apps.

This is a good finding but I am not sure about that. However, if the same happens when building the app from `trunk` or when using the `beta`, `production` releases, then it is safe to ignore it here and for the purpose of this PR.

> If I manually type HTML into a comment, should we render it in the saved comment?

Hmmm, again, I am not sure about that too, for extra clarification maybe we better ask an engineer that was working on that comments feature?

> When I add an image to a gallery block, the outline is misaligned:

Hmmm, is that happening when building the app from `trunk` or when using the `beta`, `production` releases too? Maybe we should get someone from the Gutenberg team to help?

> Should previewing a page/post require logging in? In iOS, preview shows an overlay with the content, in Android it opens the page in a browser and (depending on the site) may require logging in.

I am not sure about the logging in requirement. But, and sorry for keep being a broken record, if the same behaviour happens when building the app from `trunk` or when using the `beta`, `production` releases, then it is safe to ignore it here and for the purpose of this PR.

**Comment by ovitrif** [comment]
> I managed to fix this crash by applying a simple fix ([181781a](https://github.com/wordpress-mobile/WordPress-Android/commit/181781a1282bdc20c751fd659ae5c31129bc8acf)). Can you double check again next week and let me know if you also think that this nullability fix is enough? 🙇

@ParaskP7 Thank you for resolving the issue 🙇 🏅 
The nullability fix looks good to me, I've also tested the reader comments again on prod version and the version from this branch and I see the issue has been properly resolved and there are no other issues with this functionality 🚀

**Comment by ParaskP7** [comment]
> The nullability fix looks good to me, I've also tested the reader comments again on prod version and the version from this branch and I see the issue has been properly resolved and there are no other issues with this functionality 🚀

Coolio, thank you so much for re-testing and verifying that everything is now working as expected with this functionality @ovitrif , much appreciated! 🙇 ❤️ 🚀

**Comment by pachlava** [comment]
> 👋 @pachlava !
>
> ... You can now start testing at your earliest convenience.

Thanks, @ParaskP7, I've just started. I'm using the [installable](https://buildkite.com/automattic/wordpress-android/builds/8698#0185ac1d-c0a5-4567-8a77-d2efef2aec7b) from the last commit, and firstly checked if the Google account login thing I mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1381017300) went away, and it looks like it did not. Could it be the result of the update 🤔 (since it works in the beta version)

**Comment by ParaskP7** [comment]
> Thanks, @ParaskP7, I've just started. I'm using the [installable](https://buildkite.com/automattic/wordpress-android/builds/8698#0185ac1d-c0a5-4567-8a77-d2efef2aec7b) from the last commit...

Thank you for starting your testing @pachlava ! 🙇 ❤️ 

> ...and firstly checked if the Google account login thing I mentioned https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1381017300 went away, and it looks like it did not.

Great, noted, thanks again for this find! 🥇 

> Could it be the result of the update 🤔 (since it works in the beta version)

Yea, I am not sure, I'll need to dig deeper to figure that out. 🤔

FYI: Note that I am on support rotation this week. Thus, I will not be able to investigate or apply fixes this week. But, I'll make sure to make it my priority from Monday next week. In the meanwhile, please continue your testing and if you find more problem please do report them here (just like you did [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1381017300)). I'll then gather all those and try to fix as many as possible.

**Comment by pachlava** [comment]
> FYI: Note that I am on support rotation this week. Thus, I will not be able to investigate or apply fixes this week.

No worries @ParaskP7! The main thing is to get those findings communicated, and it's good to hear that there's no hurry with them. I surely can wait for a week, and I'll continue to post them here if I stumble across something else 👍

**Comment by lmischner** [comment]
>But, and sorry for keep being a broken record, if the same behaviour happens when building the app from `trunk` or when using the `beta`, `production` releases, then it is safe to ignore it here and for the purpose of this PR.

No worries! A good reminder about how I could have been answering those questions on my own! Thanks for taking a look through.

I tried all of my reported issues with the most recently released version of Jetpack and determined that none were specific to this PR. 👍

**Comment by ParaskP7** [comment]
👋 @lmischner !

> No worries! A good reminder about how I could have been answering those questions on my own! Thanks for taking a look through.

🙏 🙇 

> I tried all of my reported issues with the most recently released version of Jetpack and determined that none were specific to this PR. 👍

That's good to hear and :phew: that was close, thanks again for all your help Lindsey! 😄 🤞 💃

**Comment by ParaskP7** [comment]
👋 @pachlava !

> I started with some testing today, and there's one thing I've noticed so far. This was on real Samsung A31 | Android 12.

About the issue you mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1381017300), I tested it on my side just now on both, a Pixel (6a) and a Samsung (S21) device, both on Android 13, and everything seems to be working as expected on my side... 🤔 

I wonder what is happening on your side and how I might be able to reproduce this on my side... 🤷 Any ideas? 

Suggestion (💡): Maybe it is indeed pre-alpha build related. Can you try and get another APK from any other recent PR. Then, try and test this functionality again, maybe it is indeed related to the PR APKs more so than anything else. PS: I'll also do the same on my side and if it isn't working with this PR's APK, then this should be it (I got the installable from [this job](https://buildkite.com/automattic/wordpress-android/builds/8855)). 🤞

**Comment by ParaskP7** [comment]
👋 @pachlava !

> Suggestion (💡): Maybe it is indeed pre-alpha build related. Can you try and get another APK from any other recent PR. Then, try and test this functionality again, maybe it is indeed related to the PR APKs more so than anything else. PS: I'll also do the same on my side and if it isn't working with this PR's APK, then this should be it (I got the installable from [this job](https://buildkite.com/automattic/wordpress-android/builds/8855)). 🤞

I actually just verified it just now that the pre-alpha `Jalapeno` installable build is not working with `Continue with Google`, while the `Wasabi` local build that I used did. ✅ 

Actually, me thinking about it a bit more, looking at it a bit more carefully, this is actually expected. You could also observer the note on our installable build related bot messages [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1378761514) and [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1378762771). PS: Olivier opened a discussion back then (`pdnsEh-BN-p2`), I got also involved, but once more I forgot about it until it hit me again just now... 😊

```
Note: This installable build uses the JalapenoDebug build flavor, and does not support Google Login.
```

As such, and if there isn't anything else blocking this PR, testing-wise, I recommend we merge this to `trunk` and progress with subsequent dependency updates work. Wdyt? 😃

**Comment by pachlava** [comment]
Wow, that's relieving to know that G-login is not expected to work in `Jalapeno` variant. Thank you for the extra invesigation @ParaskP7!

> As such, and if there isn't anything else blocking this PR, testing-wise, I recommend we merge this to trunk and progress with subsequent dependency updates work. Wdyt? 😃

Absolutely! 👍 I still have some findings to report, but they are also true for the WPAndroid beta, so this one can be merged. Thank you! 🙇

**Comment by ParaskP7** [comment]
> Wow, that's relieving to know that G-login is not expected to work in Jalapeno variant. Thank you for the extra invesigation @ParaskP7!

I know, right! 😅 

> Absolutely! 👍 I still have some findings to report, but they are also true for the WPAndroid beta, so this one can be merged. Thank you! 🙇

Woohoo, merging it is, thank you for the merging confirmation @pachlava ! 🎉 ❤️ 🚀 

PS: I'll just wait for the code freeze of `21.6` to first happen today before I merge this to `trunk` tomorrow. This way we could test these bulk updates in development for a couple of weeks before they end up being tested via beta testing. This will give us some extra confidence about this change. Cc @jkmassel

**Review by pachlava — APPROVED** [review]
Approving since [no issues ](https://github.com/wordpress-mobile/WordPress-Android/pull/17741#issuecomment-1400214722)that are unique to the installable were found. Thank you, @ParaskP7 ⭐ :shipit:

**Pull request merged**
