### PR TITLE
issue/2867-reader-detail-back-nav

### LINKED ISSUE #2867: Reader detail back navigation doesn't work
At some point after 4.2, [this code](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java#L74-L79) stopped working, so hitting the back arrow in the toolbar no longer navigates back.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixed #2867 - back navigation in reader detail now works again.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Looks good, it's working now :+1:

The solution looks familiar, I noticed something nearly identical in a crash report [here](https://github.com/wordpress-mobile/WordPress-Android/issues/2859). Since that onBackPressed has the potential to cause some trouble I'd recommend making sure we're in a good state to invoke it.

**Comment by tonyr59h** [comment]
[Here's](https://github.com/wordpress-mobile/WordPress-Android/pull/2864/files) @daniloercoli's solution to the issue for reference.

**Comment by nbradbury** [comment]
> Since that onBackPressed has the potential to cause some trouble I'd recommend making sure we're in a good state to invoke it.

That shouldn't be a problem in this situation since `onBackPressed()` simply exits the activity without any fragment transaction.

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
