### PR TITLE
Feature branch: per-app language preferences

### PR DESCRIPTION
**Pull request by nbradbury**
This is the feature branch for per-app language preferences. All code has been reviewed in previous PRs, but a quick test is still recommended:

* Run on an Android 13+ device
* Go to App Settings
* Change the language
* Verify the change is reflected in the UI
* Force quit and restart the app and verify the language change is still reflected
* Do the same on a pre-13 device

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ParaskP7** [comment]
👋 @nbradbury !

Quick question, because I'll be off on AFK from Monday, actually approaching EOD atm, do you need that merged today? 🤔 

FYI: I am asking that because it would be valuable for someone other than me to review this final merge to `trunk`, just so that gets some additional set of eyes on it. Otherwise, I can just proceed with the testing part, just one more time, and approve it to unblock the merge, without much reviewing (did all the reviews in the previous PRs anyway).

**Comment by nbradbury** [comment]
@ParaskP7 If possible, it would be best to get this merged today as I'm AFK all of next week. But perhaps after this is merged, then next week @jkmassel could give testing changing language a spin?

**Comment by ParaskP7** [comment]
Noted @nbradbury , I'll then test this once more in about an hour (or so) and then (most probably) approve it too (✅), I am sure there are no changes between this and the previous PR we were working on just few minutes ago. 😊

**Review by ParaskP7 — APPROVED** [review]
👋 @nbradbury !

I have reviewed (quickly again) and tested this (once more), everything works as expected, a great great job well done, kudos! 🚀 x 🚀 ^ 🚀 

image

So much code removed, love it! ❤️

**Pull request merged**
