### PR TITLE
Feature/web preview navbar

### PR DESCRIPTION
**Pull request by khaykov**
This PR targets a feature branch and adds a navbar to web preview activity.

Navbar and its basic logic are implemented in the view model, but the buttons don't do anything yet.
All the additional logic comes soon.

To test:
- Navigate to site preview.
- Make sure buttons look good and code makes sense :)

Screenshot_1562726753
Screenshot_1562726760

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by maxme** [comment]
Note for the next steps: we have a ticket https://github.com/wordpress-mobile/WordPress-Android/issues/10107 to show/hide actions depending of the context (eg. we don't want to show the "share" action on a post preview).

**Comment by planarvoid** [comment]
looks pretty good! I feel like the divider on top of the nav bar should be a bit thicker and darker but I might be wrong and I can't find the designs :-)

**Comment by SylvesterWilmott** [comment]
Looks good @khaykov !

> I feel like the divider on top of the nav bar should be a bit thicker and darker

Good spot, it should be darker for sure We should use Gray 10 here to align with the main bottom nav.

**Comment by khaykov** [comment]
@SylvesterWilmott Changed color to neutral_100 to match main bottom navbar.

Screenshot_1562794950

**Comment by khaykov** [comment]
I'm going to merge this one since PR was approved and color updated.

**Comment by SylvesterWilmott** [comment]
Thanks @khaykov . Looks good

**Pull request merged**
