### PR TITLE
Fix: Removes Explore Plan from Quick start list 

### LINKED ISSUE #16477: Quick Start showing Plans item despite app not showing plan information
### Expected behavior

The "Grow your audience" Quick Start screen should not show an "Explore plans" item. (The plans screen was removed in https://github.com/wordpress-mobile/WordPress-Android/issues/16471, but removing the corresponding Quick Start item was overlooked.)

### Actual behavior

The "Grow your audience" Quick Start screen shows an "Explore plans" item.

#### New site
1. Log in to the app
2. Create a new site
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

#### Existing site
1. Log in to the app
2. Locate an existing site that has not completed its Quick Start steps
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

### Additional information

As @zwarm ([internal reference](p1651671871579959/1651587009.445519-slack-C011BKNU1V5)) mentions:

> it's a bit involved to remove the quickstart task; especially taking into account users who have started on the quick start flow.

so that must be kept in mind when addressing this issue. 

Also, as @thehenrybyrd points out ([internal reference](p1651671795976489/1651587009.445519-slack-C011BKNU1V5)), **_if_** the removal of the Plans screen is temporary, it might be best to prioritize updating the plans and showing the screen again, instead of addressing this issue.

##### Tested on Samsung Galaxy S10, Android 12, WPAndroid 19.7

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #16477 

Dependant FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2415

This PR fixes the issue where the explore plans were visible on the Quickstart task list. This PR fixes the following scenario.  which was missed from the previous [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16582) to fix the removal of plans. 

| Quick start in Progress with Explore Plans| Quick start in Progress after Removing Explore plans|  
|---|---|
|Screenshot 2022-05-20 at 5 44 00 PM| Screenshot 2022-05-20 at 5 44 34 PM
 
Note: The Quick start task title and description for Follow Other Sites and Check your stats has been changed as part of the [QS-V2 Project](https://github.com/wordpress-mobile/WordPress-Android/issues/16349).

### To Test 1

🟢  Test Scenario 1 - Explore Plans + Other tasks pending 
- Install the app having the Explore plans listed (E.g. from release/19.7 branch).
- Login to the app with a quick start in progress.
- Complete all tasks, excluding Explore plans + one task like Check your stats.
- Install the app from the current PR.
- Notice that Quick Start is not completed, and other tasks are shown as Pending
- Notice that Explore Plans is not shown in Quick start task list 

🟢  Test Scenario 2 - Only Explore Plans Pending 
- Install the app having the Explore plans listed (E.g. from release/19.7 branch).
- Login to the app with a quick start in progress.
- Complete all tasks, excluding Explore plans 
- Install the app from the current PR.
- Notice that Quick Start is completed and Notification is shown 

Note: In this PR, we update the database schema version to remove the explore plans with migration. Hence, After installing the build from this branch, when you try to install another build from the trunk or `release/19.7` with the previous schema version. The app will crash. To avoid that, clean and install any build after installing the build from this branch.

### Merge Instructions 
- Make sure dependant PR is merge 
- Update FluxC Version 
- Remove Status not ready to merge label
- Merge 

## Regression Notes
1. Potential unintended areas of impact
Quick start list not being shown properly 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AjeshRPai** [comment]
@ParaskP7  Pinging you here(again 😄 ) to inform you that we would like to include this fix in the next beta release.

**Review by ashiagr — APPROVED** [review]
Tested given scenarios. Works as described. 👍

**Comment by ParaskP7** [comment]
Thanks for the ping @AjeshRPai ! 👋 

When you are ready and @ashiagr approves this PR, just let me know and I'll merge it. 💯 

PS: I am currently seeing 0 file changes atm, I am not sure why, but you are probably on top of that, right? 😅

**Comment by ParaskP7** [comment]
😄 

> When you are ready and @ashiagr approves this PR, just let me know and I'll merge it. 💯

Then...

> Tested given scenarios. Works as described. 👍

@ashiagr you are too fast for me! 😛

**Comment by AjeshRPai** [comment]
@ParaskP7 We have made the necessary changes in FluxC and there would only be a change in the fluxC Version in the gradle file in this PR. Dependant FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2415.

**Comment by ParaskP7** [comment]
> @ParaskP7 We have made the necessary changes in FluxC and there would only be a change in the fluxC Version in the gradle file in this PR. Dependant FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2415.

@AjeshRPai got it, but I am seeing that the `FluxC` version on the `release/19.9` branch is already pointing to `1.42.1`. Thus, this PR is of 0 file changes. We can merge it anyway, to include your 2 commits, but I just wanted to mention that in case we are missing something here. 🙏

**Comment by ParaskP7** [comment]
FYI: @AjeshRPai I am seeing this previous [Release PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16582), 2 days ago, which actually did the `1.42.1` FluxC update, but I also see that @ashiagr created the draft `1.42.1` FluxC release an hour ago. I am a bit confused to be honest. Please let me know that everything is as you expected and that we are not missing something. If you provide a bit more info for me to understand it better it would be great.

PS: Apologies for not picking-up fast enough with all this, I just got the release from Olivier yesterday and trying not to mess it up for him... 😅

**Comment by AjeshRPai** [comment]
@ParaskP7 This part was a little bit confusing to me as well. I will try to explain as much as I understand. 

We created the tag `1.42.1` to fix the plans issue with the [Release PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16582). What we intended to do today was to delete the present tag `1.42.1` since it included only our change from the previous [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16582) and create the tag `1.42.1` again to include the change from this PR. But this didn't go as planned; we got some build error from S3 in the FLUXC CI Build that 1.42.1 is already published. Now we have created `release/1.42.2` and we are planning to create tag 1.42.2. We will update the fluxC Version in this PR and remove the not ready for merge label once the tag is successfully published. 

@ashiagr Hope this is correct 😅 

Again: Am sorry for not providing this info earlier so that you could get the context.

**Comment by ParaskP7** [comment]
Oh, this all makes sense now @AjeshRPai ! Thank you so much for taking the time to explain it to me! 🙇

**Comment by ashiagr** [comment]
Thanks, @AjeshRPai! Your explanation is correct. 

👋 @ParaskP7, 

We didn't realize that `1.42.1` `FluxC` tag that was created 2 days ago was already published to S3 and cannot be republished to point to another commit until we saw [this error](https://buildkite.com/automattic/wordpress-fluxc-android/builds/1243#11282141-9a05-4eb2-bd78-eb734d0015ec/159-191). To resolve the issue, we created a new `1.42.2` `FluxC` tag which has all the changes from `1.42.1` tag  + `FluxC` fix for this PR, more details here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2417.

I'll update `1.42.1` tag draft release with the details. 

Let me know if anything is not clear. I'll not merge this PR until everyone is on the same page. Really sorry about any inconvenience due to this. 🙏

**Comment by ParaskP7** [comment]
👋 @ashiagr and thanks for your input, I am all onboard now with what's happening, thank you! 🙇

**Comment by ashiagr** [comment]
> When you are ready and @ashiagr approves this PR, just let me know and I'll merge it. 

@ParaskP7 this PR is ready to be merged. 

Thank you, both of you!

EDIT: I'm merging it to keep `release/19.9` up-to-date before the weekend.

**Pull request merged**
