### PR TITLE
Update scripts to build Android App Bundles

### PR DESCRIPTION
**Pull request by jtreanor**
There is a new app publishing format, [Android App Bundles](https://developer.android.com/platform/technology/app-bundle), which has a number of benefits. You can read more in that link, but the most compelling is a smaller app download and availability of new features like Dynamic Delivery and Instant Apps.

This PR updates our build scripts to build Android app bundle files as instead of `.apk` files. The process to build is practically unchanged. I will update our docs when this is merged. I have released WPAndroid `alpha-167` using these scripts.

With this change, the Google Play **download size for a Google Pixel 3 has been reduced from 23MB to 13.6MB**. This is because it can download only what it needs. ~Do you think this is worth calling out in the release notes?~ I have added it now.

To test:

- Install `bundletool` with `brew install bundletool`. If you don't do this step, the script will prompt you to.
- Run `./tools/build-release-app-bundle.sh alpha-167` to build the `alpha-167` tag as an Android app bundle.
- Install the bundle in an emulator or device with `./tools/install-app-bundle.sh build/wpandroid-alpha-167.aab`
- Install the universal apk with `adb install build/wpandroid-alpha-167-universal.apk`

**Note:** If you are seeing some build failures, you may need to delete the `WordPress/build` directory.

It's also worth installing WPAndroid `alpha-167` from Google Play which was built with these scripts, and checking that it works correctly.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jtreanor** [comment]
I’ve tested this out some more and I’m confident this works as described.

**Comment by jtreanor** [comment]
Marking as not ready for review as there seems to be an uptick in crashes in `alpha-167`, possibly caused by a proguard issue when building app bundles.

**Comment by jkmassel** [comment]
> Do you think this is worth calling out in the release notes?

Yes – this is a user-affecting feature that should make life a little nicer, so definitely worth calling out IMHO.

**Comment by jtreanor** [comment]
@jkmassel Done 😄

**Pull request merged**
