### PR TITLE
Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ MediaPickerViewModel

### PR DESCRIPTION
**Pull request by Hoossayn**
Parent: https://github.com/wordpress-mobile/WordPress-Android/issues/17010

This PR resolves/suppresses all complexity related LongMethod warnings for the MediaPickerFragment class (see docs [here](https://detekt.dev/docs/rules/complexity#longmethod)):

`1` x LongMethod  and `1` x ComplexMethod (Resolve: 6e15dca9a196bb70a24d1821ed33c95f1f1c64cc + 5546437d3e6a2c79ea2a374e19105bc05eff2dde + c1ae415557e1bf6c83edd7bdbd9e1447367d39a6 + a27b17aa771ad6c7f27af64953ab8e21dccfba9a + 77977efa737cc7d2c9fd21ebfc203870d2657c1d)

-----

To test:

- There is nothing much to test here.

- Verifying that all the CI checks are successful should be enough (especially the detekt check).

- However, if you really want to be thorough, you could smoke test the WordPress and/or Jetpack apps to verify that everything works as expected on every screen that relates to these changes. Specifically, you could follow the below steps:
   
    - Go to the menu tab
    - click on media option 
    - click on the upload media button or the (+) button at the top right corner 
    - select choose from device 
    - select an image

## Regression Notes
1. Potential unintended areas of impact
     can't think of any 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
   See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)
     N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @Hoossayn !

Thanks for opening yet another PR! 🙇

Quick couple of questions:
1) Is that PR ready for review? 🤔
2) I am also seeing this 4cffcefdc6859038e268838f24c0618b19217504 commit here, is that correct and why did you need to do that? 🤔

**Comment by Hoossayn** [comment]
> 👋 @Hoossayn !
> 
> Thanks for opening yet another PR! 🙇
> 
> Quick couple of questions:
> 
> 1. Is that PR ready for review? 🤔
> 2. I am also seeing this [4cffcef](https://github.com/wordpress-mobile/WordPress-Android/commit/4cffcefdc6859038e268838f24c0618b19217504) commit here, is that correct and why did you need to do that? 🤔

@ParaskP7 it's NOT ready for review. i think the commit is from merging remote with my branch

**Comment by ParaskP7** [comment]
👋 @Hoossayn !

Having quickly reviewed this PR, I would vote against doing this 6e15dca9a196bb70a24d1821ed33c95f1f1c64cc kind of refactorings (another one is this a27b17aa771ad6c7f27af64953ab8e21dccfba9a commit). 🙏

It would be preferable and more readable to have each named argument on a separate line. This way, the comma that separates each named argument would be always at the end of the line, not somewhere in between the line, which will end up making a change a bit more difficult to do and/or review afterwards. Could you maybe please consider another alternative? 🤔

**Comment by ParaskP7** [comment]
> @ParaskP7 it's NOT ready for review. i think the commit is from merging remote with my branch

Great, thank you for your clarification @Hoossayn . Next time I'll avoid reviewing any PR of yours that are in draft mode, I hope that's okay with you too.

PS: Please also consider [this](https://github.com/wordpress-mobile/WordPress-Android/pull/17381#issuecomment-1296996031) comment of mine before you make this PR ready or in case you create another PR (after closing this). 👍

**Pull request closed without merging**
