### PR TITLE
Feature/back forward navigation

### PR DESCRIPTION
**Pull request by khaykov**
This PR adds Back and Forward navigation to Site preview and opens external links in the browser.

During my tests, Back and Forward navigation worked pretty well, but it's worth mentioning that it works on "trying it's best" basis since we don't have resources to make our own web browser, and `WebView` gives us limited tools. There are some websites that behave in a way that adds a request or sneaky redirect that we can't handle to the history, but looks like this does not compromise user experience significantly, and is a huge improvement over current behavior (Back navigation with device Back button).

PS: Navbar behavior specific to other activities that extend `WPWebViewActivity` and different use cases will be addressed in subsequent PR's.

[Image from Gyazo](https://gyazo.com/bedbc6d4a4d1c26656f93566d32be979)

To test:
- Open Site preview for a couple of different sites.
- Notice that clicking on links that lead to external sites opens them in an external browser (or prompts to).
- Notice that back forward navigation works mostly as expected.
- Notice that navigation back with the device back button also works.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
>I'd personally make the color difference between enabled and disabled back/forward buttons bigger because it's very hard to notice that a button is enabled

Agreed. @khaykov Can we change the disabled colour to 1 shade lighter?

**Comment by khaykov** [comment]
@SylvesterWilmott Done! Let me know how it looks :)

Screenshot_1564254350

**Comment by SylvesterWilmott** [comment]
Thanks for the screenshot!

I think what wasn't clear before was the colour of the "active" icons. The colour for these should be `Gray 60` from the color studio. We can also then move back to what was previously used for the disabled state.

**Comment by khaykov** [comment]
@SylvesterWilmott I pulled changes from the color studio update, and after reverting disabled color, it looks like this: 
Screenshot_1564417503

**Comment by khaykov** [comment]
We agreed on colors so I'm merging this one.

**Pull request merged**
