### PR TITLE
Feature/media detail revamp

### PR DESCRIPTION
**Pull request by nbradbury**
Redesigned the media detail screen.

media-details-after

### CODE REVIEW

**Comment by mattmiklic** [comment]
I just had a few minutes to try some ideas tonight; here's what I've got. These are all just suggestions, so use as much of this as you can and ignore the rest.

mediadetail-android

I dropped the dark gray background, opting instead to make the image "full bleed", like we did with posts in the reader. The text below conforms to the 16dp keyline.

I've used standard <a href="https://www.google.com/design/spec/style/typography.html#typography-styles">Material Design typography styles</a>, though using Open Sans instead of Roboto, obviously. While it's more likely to require some scrolling because each label and value are on separate lines, I think it's clearer this way.

Instead of the Copy icon in the list, I added a Share icon to the toolbar. I imagined that tapping it would open a panel where you could either copy the link to the clipboard or share it through the standard system share tools. This seemed like a slightly more obvious and user-friendly approach if we can do it.
I also replaced the pencil and trash icons with our Gridicon versions of the same (let me know what format you need if you need me to export these for you).

I wasn't clear on what tapping the Pencil icon would do -- if some of these values are editable, should we just style them the same way we're doing with site settings, and have each one open a dialog when tapped?

You can see which styles I've used for each line, and measurements, here:
mediadetail-android-annotated

**Comment by nbradbury** [comment]
> I just had a few minutes to try some ideas tonight; here's what I've got.

Thanks @mattmiklic! I've marked this PR "not ready for review" so I can tidy things up based on your mockup.

I really like the look of the full-bleed image, but that was one of the first things I tried and it didn't work out too well. With small images (ie: ones smaller than the width of the screen) it causes pixelation, and with portrait photos it required either forcing the user to scroll to see the entire photo or cropping the photo. Perhaps I could use full-bleed for larger landscape photos, though?

The spacing in your mockup is much better than my own - I'll work on that. I'm not sold on using labels ("File name," etc.), though, as they seem unnecessary. My preferences is to skip the labels so the user is less likely to have to scroll.

The pencil icon enables editing the media item's caption and description, and that feature already existed prior to my PR. I agree about the "copy" feature being unusual, and I should probably move that to the toolbar or an overflow menu. A "share" icon is beyond the scope of this, though (sharing a media item is pretty involved).

**Comment by maxme** [comment]
Minor, but last item lacks a bottom margin: https://cloudup.com/cb8T8EQbrW7
:coffee:

**Comment by nbradbury** [comment]
@maxime Ready for another (hopefully last!) round.

**Comment by maxme** [comment]
Much cleaner than the old detail view! :shipit:

**Pull request merged**
