### PR TITLE
issue/6257-media-video-overlay

### LINKED ISSUE #6257: Video overlay in media library does nothing when used as a picker
In #6245 we added video thumbnails with a "player" overlay. When used as a picker (to insert media into a post), tapping this overlay does nothing. In addition, having both the player icon and preview icon showing takes up too much space.

device-2017-07-07-172339_1024

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6257 - resolved the problem by moving the video player icon to the bottom left, where the fullscreen preview icon would be.

device-2017-07-07-122731

### CODE REVIEW

**Comment by daniloercoli** [comment]
Looks good in WP Media Library, but not in the picker where I still see both the player icon and preview icon.
device-2017-07-07-231607

**Comment by nbradbury** [comment]
> Looks good in WP Media Library, but not in the picker where I still see both the player icon and preview icon.

Addressed in dbe8403.

**Comment by daniloercoli** [comment]
It seems to me that the player icon is bigger (and slightly shifted to the right?) in the Picker. Instead everything seems fine in WP Media Library.

Picker:
device-2017-07-10-112612

Media Library:
device-2017-07-10-112915

**Comment by nbradbury** [comment]
> It seems to me that the player icon is bigger (and slightly shifted to the right?)

Good eye - you're right, I was using different `dimen` sizes for the icons. Fixed in 7cca32f.

screenshot_1499698917

**Comment by daniloercoli** [comment]
Good! :shipit:

**Pull request merged**
