### PR TITLE
Adding .debug suffix for easier development with the play store app

### PR DESCRIPTION
**Pull request by kwonye**
I'd like to suggest we add these to make it possible for us to have both the release and debug versions on the device at the same time.

Thoughts? @maxme @daniloercoli @nbradbury @roundhill @tonyr59h @aforcier @oguzkocer

### CODE REVIEW

**Comment by maxme** [comment]
Nope, one of the purpose of the `wasabi` variant is to have both versions on a device at the same time. IMO Vanilla debug and release should have the same package name. We could eventually have `zalpha` debug with a suffix and drop `wasabi` but we must be sure we won't need different feature matrix.

**Comment by kwonye** [comment]
> We could eventually have zalpha debug with a suffix and drop wasabi but we must be sure we won't need different feature matrix.

My preference would be to keep wasabi as it'd probably be best to keep it as similar to vanilla as possible. zalpha could potentially have dozens of specials flags in it with the pace we're going.

**Comment by kwonye** [comment]
> Nope, one of the purpose of the wasabi variant is to have both versions on a device at the same time. 

Totally fair (love the icon btw). Reverted changes to vanilla but also "beta" wording from all `wasabi`-related parts as it's not actually our beta.

**Comment by maxme** [comment]
When we switched to the naming `wasabi` I kept the `.beta` part because we have (or had) server side tools (and analytics) using this. IMO we should just close this PR.

**Pull request closed without merging**
