### PR TITLE
Track when not the default WPCOM post URLs handler

### PR DESCRIPTION
**Pull request by hypest**
Adds a track point to see if the app is not set as the default for handling WPCOM post URLs. That can be an indication of bad UX with the app so, gathering it can be helpful for assessments.

### CODE REVIEW

**Comment by nbradbury** [comment]
The default handler will only be our app if the user has clicked a wordpress.com reader link and chosen to **always** open them in our app. So the vast majority of the time, our app won't be the default. What's the value in tracking this?

And if there is value in tracking this, is it necessary to do it in `onResume()`? Seems like something we'd want to do only at startup.

**Comment by hypest** [comment]
> The default handler will only be our app if the user has clicked a wordpress.com reader link and chosen to always open them in our app. So the vast majority of the time, our app won't be the default. What's the value in tracking this?

True, my goal was actually to only track when _another_ app is the default. Here's the think though, we cannot find that out without hardcoding the system chooser activity name (which is an internal API one though) or be sure which activity is the signature of the chooser. So, I thought we can do that later by analysing and filtering the tracks on the Tracks tool.

> And if there is value in tracking this, is it necessary to do it in onResume()? Seems like something we'd want to do only at startup.

Startup (`onCreate`) would be OK as well, I opted for `onResume` to get the result "faster" without waiting for the system to cold-start the app. I can demote it to `onCreate` if you feel better with it, let me know! Thanks!

**Comment by nbradbury** [comment]
> I can demote it to onCreate if you feel better with it, let me know!

I would prefer to see this in `onCreate` unless there's a good reason to do it more often.

**Comment by hypest** [comment]
Moved the check to `onCreate` @nbradbury , ready for another pass. Thanks!

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
