### PR TITLE
Issue/13329 backup complete skeleton

### PR DESCRIPTION
**Pull request by zwarm**
Parent #13329 

This PR creates skeleton fragment, vm, and test for the Backup Download Progress screen.

Merge instructions
- Make sure #13586 & #13587 have been merged.
- Remove Not Ready for Merge label
- Merge as normal

To test:
There is nothing to test on this PR

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — COMMENTED** [review]
👋 @zwarm !

I have reviewed the solution. Let me know if you need my help.

PS: My comments on this PR are identical to what I already left on the [Issue/13329 backup progress skeleton #13587](https://github.com/wordpress-mobile/WordPress-Android/pull/13587) PR. As such, I will not duplicate my comments here. If need be, just refer to them from the other PR.

**Comment by ParaskP7** [comment]
I am assigned to this PR, after our group chat confirmation, but it is not 100% clear to me whether I should merge this or whether you want to do any additional work on it. If it's okay, as a reviewing, I'll start merging the PRs from the next one I'll get assigned to?

**Comment by zwarm** [comment]
@ParaskP7 - Added the initDagger fun. Layout files requests have been noted, the designs are NOT complete yet. Thanks,

**Review by ParaskP7 — APPROVED** [review]

**Comment by ParaskP7** [comment]
👋 @zwarm !

> Added the initDagger fun. Layout files requests have been noted, the designs are NOT complete yet. Thanks

Thanks for letting me know Annmarie, I added the `NOT` in your quote above, probably this is what you meant.

I have approved this PR to unblock you, feel free to merge it when you feel ready.

**Pull request merged**
