### PR TITLE
Fix/14993 multiple sites blogging reminders opening issues

### LINKED ISSUE #14993: Configuring Blogging Reminders for multiple sites results in receiving notifications for only one site
### Expected behavior
When enabling Blogging Reminders for multiple sites connected to app, I receive an individual notification for each site based upon my settings. 

### Actual behavior
When enabling Blogging Reminders for multiple sites connected to app, I receive a single notification for one site (presumably the last site configured). I do not receive notifications for the other connected sites. 

### Steps to reproduce the behavior
1. Launch WPAndroid app. 
2. Log into a WPCom account with multiple sites connected OR connect multiple self-hosted sites.
3. For each site configured Blogging Reminders through either the publish prompt OR within the site settings screen. 
4. Await for the next appropriate time for a Blogging Reminder. 
5. ⚠️ Only one notification is received, rather than one for each site.

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes #14993 

To test:

- Turn on the blogging reminders flag (Me/App settings/Test feature configuration - BloggingRemindersFeatureConfig)
- Notice the blogging goals option appears (My Site > Settings > Blogging reminders)
- Click on for e.g. "Twice a week" button under Blogging goals setting
- Notice the blogging reminders prologue screen is shown
- Click on "Set goals"
- Select a day for blogging when screen is shown, then ensure "Update" button is enabled
- Click on "Update" button
- Notice the epilogue screen is shown. Done button is enabled, Clicking Done button should dismiss bottomsheet
- Repeat the steps for other sites that you may have
- Wait for the next day, verify that notifications appear for all the sites that have been setup for reminders

## Regression Notes
1. Potential unintended areas of impact
Site Settings

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Blogging reminders flow from Site Settings

3. What automated tests I added (or what prevented me from doing so)
Unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AliSoftware** [comment]
* 17.7 got submitted on Friday as usual (and announced in P2s and Slack) so this was already way too late to make this PR target release/17.7 at that point. 17.7 got released today anyway.
* 17.8 is going into code freeze today as planned with new Sprint, so retargetting this one to `develop` for 17.9 as it should be. If you really need it to make it to 17.8, please communicate it (to your RM, your EW, and the team) so we can plan accordingly.

**Review by renanferrari — COMMENTED** [review]
Hey @ravishanker, thanks for the changes! I can confirm they work as expected, but I did find a couple of issues that were already present but became more evident with the changes made by this PR:

1. Even though we have separate notifications for each site now, clicking a notification that was sent before another one, won't redirect us to the Post Lists screen. It seems that only the latest notification keeps the correct corresponding action on click.
2. If a single site receives more than one notification, they are going to be separated as well, although I feel like it would be better if the latest notification would replace the older one if it's from the same site.

I dig a bit more into this and I found that issue 1. is being caused by the fact that we are generating the same `PendingIntent` for every notification. I think we were assuming that an `Intent` with different extra data would result in different `PendingIntent`s, but this is not true, as per the `PendingIntent` documentation:

>A common mistake people make is to create multiple `PendingIntent` objects with `Intent`s that only vary in their "extra" contents, expecting to get a different `PendingIntent` each time.  This does **not** happen. The parts of the `Intent` that are used for matching are the same ones defined by `Intent.filterEquals`.  If you use two `Intent` objects that are equivalent as per `Intent.filterEquals`, then you will get the same `PendingIntent` for both of them.

It then suggests that we should either change any of the attributes considered by `Intent.filterEquals` or use a different request code. I believe we could go with the latter and use a combination of the `REMINDER_NOTIFICATION_ID` + `siteId` to make this work for each different site. Something like:

```kotlin
PendingIntent.getActivity(
        context,
        REMINDER_NOTIFICATION_ID + siteId,
        PostsListActivity.buildIntent(context, site, actionsShownByDefault = true),
        FLAG_CANCEL_CURRENT
)
```

Then I believe we could use this same approach to solve issue 2. as well, instead of generating a random id for each notification each time:

```kotlin
reminderNotificationManager.notify(REMINDER_NOTIFICATION_ID + siteId, reminderNotification)
```

I haven't tested this, but let me know if it makes sense to you!

**Comment by ravishanker** [comment]
> I haven't tested this, but let me know if it makes sense to you!

Makes sense.  Thanks @renanferrari for taking time to analyze the issues and coming up with a potential solution too.  I've updated with the suggestion.  It seems to cater for issues one and two.  Please give it another go.

**Review by renanferrari — APPROVED** [review]
LGTM 👍

**Pull request merged**
