### PR TITLE
Enable core library desugaring

### PR DESCRIPTION
**Pull request by renanferrari**
This PR enables [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring), which makes it possible for us to use Java 8+ APIs, most notably `java.time` and `java.util.stream`.

This was mainly motivated by the fact that we are going to be making quite a few operations with dates during the [Notifications](https://github.com/orgs/wordpress-mobile/projects/95) project and the `java.time` API can make that a lot less painful.

**To test:**

Not much to test here. Just making sure it builds and all existing tests pass should be enough.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by planarvoid** [comment]
I think the `lint` is failing because of the Java changes.

**Comment by oguzkocer** [comment]
I've run this lint task locally with 6GB of memory and it passed fine within a reasonable amount of time. Unfortunately in CircleCI, we are limited to 2GB of memory and it looks like that's not enough to get lint task done after these changes.

The good news is that I plan to move the lint task to BuildKite during the upcoming HACK week which will not have this restriction and the task should pass fine.

Assuming this is an optional PR, the best thing to do might be to postpone merging this PR for a bit. Sorry about that!

**Review by planarvoid — COMMENTED** [review]
The app builds without problems. I'm getting the lint errors locally when running the CI command (`lintWordpressVanillaRelease`)


```
  Errors found:
  
  /Users/vojta/Development/wordpress/WordPress-Android/WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java:556: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] results) {
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/vojta/Development/wordpress/WordPress-Android/WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java:841: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/vojta/Development/wordpress/WordPress-Android/WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java:152: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      public void onRequestPermissionsResult(int requestCode,
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by AliSoftware** [comment]
Moving this PR as well as https://github.com/wordpress-mobile/WordPress-Android/pull/14719 to next milestone since 17.6 goes into code freeze today.

**Pull request merged**
