### PR TITLE
Small stats design improvements

### LINKED ISSUE #9305: [Stats Refresh] Use different standard icons in "Referrers" block
The icon shown for "Search Engines" in the Referrer block can be updated to gridicons as well as providing a fallback icon for items without an icon.

- Replace search engines icon with `gridicons-search`
- Use `gridicons-globe` as fallback icon
- Icon are `grey_dark`

screenshot 2019-02-21 at 12 01 46

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9305 #9306 #9303 #9292 
This PR fixes several small details in stats. 
* I'm changing the image type of icons to `ICON` and of the avatar to `AVATAR_WITH_BACKGROUND` as they show the proper placeholders.
* In referrers I'm replacing the icon in `search engines` with a gridicon
* In referrers there is now a default `globe` icon if the icon is missing
* I'm removing the default loading empty message from the bar chart
* The chevron's size in the expandable item is now 16dp and the color is changed to `grey_darken_20` 

To test:
* Open Stats/DWMY
* Check all the above points

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Everything looks good! However I'm still getting the empty message on the chart on rotate.

**Review by 0nko — APPROVED** [review]
LGTM. I can also see the chart message.

**Comment by planarvoid** [comment]
@0nko thanks for the check! it should be fixed now. I moved the setter out of the `delay` block

**Comment by 0nko** [comment]
Thanks @planarvoid! :shipit:

**Pull request merged**
