### PR TITLE
[WIP] Remove confusion caused by the displaying a "Publish" button as main action for a Draft

### LINKED ISSUE #15617: After changing Scheduled post back to Draft status, "Publish" button can cause confusion.
### Expected behavior

It should be possible to change the status of a scheduled post back to a draft.

### Actual behavior

The post was published instead.

### Steps to reproduce the behavior

1. Create a new post and schedule it by giving it a future date
2. Open the post in the mobile app and try to switch its status to draft
3. Notice how it gets published

During one of my tests (not the one recorded below), I was able to switch the post to a draft by changing its date back to an older date, but this did not work consistently.

https://user-images.githubusercontent.com/4452464/143422107-c6f918f5-e764-4850-8ec4-987afa6a158e.mp4

##### Tested on [device], Android [version], WPAndroid [version]

App version: alpha-330
Device: One Plus Nord2 5G + OsygenOS V11.3

This is closely related to https://github.com/wordpress-mobile/WordPress-Android/issues/11393 and https://github.com/wordpress-mobile/WordPress-Android/issues/12344

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes [#15617](https://github.com/wordpress-mobile/WordPress-Android/issues/15617)
Related [#15843](https://github.com/wordpress-mobile/WordPress-Android/issues/15843)

## Description

**This PR replaces the `PUBLISH` button in the editor of a draft post with a `SAVE` button.** The `PUBLISH` button remains available on a draft via the kebab ( `⋮`) menu, but is renamed to `Publish Now` for consistency with other post types (scheduled, pending).

I explored different approaches but this solution appears to be the safest and quickest way to do something about the confusion some users may have when trying to save a draft post after it was scheduled (more on this in the linked issue).

I'd like to add the a (personal) remark that before getting used to the WordPress app the Publish button for draft posts also caused confusion for me.

<details>

  <summary>An alternative approach that I explored:</summary>

  Replace the `PUBLISH` button with `UPDATE` → This might help with keeping the editor screen consistent with the iOS app, but it can be confusing to existing users that are comfortable with the current flow for saving a draft* if we remove the `Save` button.

  If we don't remove the  `Save`  button from the kebab menu, we end up showing two buttons that are practically doing the same thing for the user, and unless we add an additional `Publish Now` button we no longer have the option to publish a draft post directly.

  The main reason I explored this option was in an attempt to also address [#15843 - Draft Post screen inconsistency between Android and iOS](https://github.com/wordpress-mobile/WordPress-Android/issues/15843).
Turned out that's a bit of a different thing, and it's probably better to separate the issue we're trying to fix here.
</details>

---

*_(On version 19.4 saving a draft post is done by opening the kebab menu & selecting the `Save` button)_

#### Save Button

1. Launch the app.
2. From `My Site` tap the `Posts` icon in quick links or scroll down & select `Posts`.
3. Add a new post or go to drafts if you have draft posts.
4. **Verify** that the main button in the editor toolbar is `SAVE`.
5. Add something for the Title and the first paragraph block of the post (otherwise the post can't be saved).
6. Tap the `SAVE` button.
7. **Verify** the post is saved and the app lands on the Posts page → Drafts tab.

#### Publish Now button under menu

1. Open the new draft post you just saved.
2. Tap the `⋮` kebab menu next to `Save`.
3. **Verify** that the first menu option is `Publish Now` .
4. Tap `Publish Now` & **verify** it opens the panel to publish the post.
4. **Verify** the post is published and the app lands on the Posts page → Published tab.

## Previews

| Before | After |
| --- | --- |
| before | after |

## Regression Notes

1. Potential unintended areas of impact
   - Other post states (draft, pending, etc...).
   - Different states of a draft (brand new, already saved)
2. What I did to test those areas of impact (or what existing automated tests I relied on)
   Manual testing and relied on the unit tests.
3. What automated tests I added (or what prevented me from doing so)
   I updated the following tests in  `EditorActionsProviderTest`:
   - `Verify actions of a DRAFT`
   - `Verify actions of a DRAFT when the user doesn't have publishing rights`

### PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### PR Reviewing notes:

- Gathering feedback from this early stage is useful for this PR.
- One reviewer should be enough to merge this.
- **This PR is still a draft because I noticed two bugs 🐞:**
  - Pressing the `Publish Now` button on a draft that was already saved opens a panel displaying `Update now` as primary action button → Tapping it publishes the post.
  - Pressing the `Publish Now` button on a draft that was **not** yet saved opens a panel displaying `Save now` as primary action button → Tapping it doesn't publish the post.

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Thank you for working on this @ovitrif 👍 
The code changes at this point LGTM and the app behaves as described including the two open issues.

Tbh I'm not sure what the expected behavior is for our users. On the one hand this resolves the https://github.com/wordpress-mobile/WordPress-Android/pull/16084 but changing the default button for new posts from `Publish` to `Save` might be a big change for the editor.

Our designers @kyleaparker and @iamthomasbishop may have a better view on how to move forward with this 🙏

**Comment by ovitrif** [comment]
> Thank you for working on this @ovitrif 👍 The code changes at this point LGTM and the app behaves as described including the two open issues.
> 
> Tbh I'm not sure what the expected behavior is for our users. On the one hand this resolves the #16084 but changing the default button for new posts from `Publish` to `Save` might be a big change for the editor.
> 
> Our designers @kyleaparker and @iamthomasbishop may have a better view on how to move forward with this 🙏

Thank you @antonis for testing & reviewing the current solution! 🙇
Glad we're pinging Kylea & Thomas for designer(s) review of this, it's indeed a big change for our users and for that reason I also marked this with 3 stars `[***]` in the `RELEASE-NOTES`, to make sure users are aware of it if we go forward with this change.

**Comment by kyleaparker** [comment]
For the sake of a quick solution, this works! I think the ideal solution would be to autosave draft posts, and have a visual indicator that a post has been saved, this way the Publish button could be persistent and available at all times.

**Comment by ovitrif** [comment]
> For the sake of a quick solution, this works! I think the ideal solution would be to autosave draft posts, and have a visual indicator that a post has been saved, this way the Publish button could be persistent and available at all times.

Hey @kyleaparker 👋 

Thank you for your feedback on this 🙇 !

If I understood correctly from this internal discussion p5T066-2Vl-p2#comment-11024 we already have autosave for Android, and perhaps that's the reason the `Publish` button is persistent on Android for draft posts, while in iOS we have an `Update` button.

The original issue #15617 that we're targeting with this PR is a bit controversial IMHO, which is why I'm not inclined to advocate for merging this PR as it is (even if we fix the 2 bugs we identified).

Seeing from your feedback that having the "PUBLISH" button persistent is the desired **I wonder what alternative solution we could provide to make sure users are not confused** by it when editing a draft and wanting to just save it and exit.

As I already mentioned in the description of this PR, for me it was also confusing to see "PUBLISH" for a draft when I was still a new user of the App, which is why I also understand the issue's author point of view :)

> have a visual indicator that a post has been saved

Could this be the path for a better solution?

**Comment by iamthomasbishop** [comment]
@ovitrif  @antonis  Thanks for the ping! I spent some time thinking about the primary flows and logic, and here's what I was imagining with this proposal in mind — does everything look correct here, or am I missing something?

<a href="https://user-images.githubusercontent.com/1200432/158261311-035823f1-fb1b-46fa-8f77-26b4e6464f53.png"></a>

Assuming this lines up with what is being proposed, I do agree that this is a good step in the right direction, definitely a bit clearer than the current implementation. One thing though: because this is a relatively consequential change that will have some real impact (both qualitative and quantitative), I think it would be good to test with users prior to shipping it to everyone.

**Comment by mkevins** [comment]
Though not directly related with the intent of this PR, I wonder whether the "Save" option could be better worded as "Save and exit", since it is surprising behavior, imo, that tapping "Save" exits the editor. Unless the behavior changes (possibly as a result of this PR, though I don't think that is the intent?) I believe it's possible to address this additional enhancement as a mere string change. Wdyt? Does this seem like an improvement in wording for that menu option?

**Comment by antonis** [comment]
> does everything look correct here, or am I missing something?

@iamthomasbishop The flows look correct 👍 
What mostly worries me with the change is that [the **Publish** button is not available in new posts](https://github.com/wordpress-mobile/WordPress-Android/pull/16084#pullrequestreview-906987165) and by default new posts are saved as drafts. This change is probably big in the context of the issue we are targeting to solve and will most probably have an effect on published posts (that is one of our metrics).

<details>
<summary>Current behavior</summary>

https://user-images.githubusercontent.com/304044/158409260-3cb8c9ae-b4eb-4bf4-8751-126e3563ac95.mp4
</details>

<details>
<summary>Proposed change</summary>

https://user-images.githubusercontent.com/304044/158409308-16715b61-c395-455f-aea0-1964fda47216.mp4
</details>

I think if we proceed with any change we need to keep the publish button persistent as @kyleaparker suggested. 
Also adding @hypest to the conversation since this change affects the editor.

**Comment by ovitrif** [comment]
> What mostly worries me with the change is that [the **Publish** button is not available in new posts](https://github.com/wordpress-mobile/WordPress-Android/pull/16084#pullrequestreview-906987165) and by default new posts are saved as drafts. This change is probably big in the context of the issue we are targeting to solve and will most probably have an effect on published posts (that is one of our metrics).

> I think if we proceed with any change we need to keep the publish button persistent

That's a valid concern, and I missed a bit putting enough emphasis on it.
For new posts I agree the **Publish** button **should** be persistent 🙂

**Comment by ovitrif** [comment]
> Though not directly related with the intent of this PR, I wonder whether the "Save" option could be better worded as "Save and exit", since it is surprising behavior, imo, that tapping "Save" exits the editor.

@mkevins Thank you for raising this, I agree with it, feels like surprising behavior for me too 🙋🏻‍♂️

> Unless the behavior changes (possibly as a result of this PR, though I don't think that is the intent?) I believe it's possible to address this additional enhancement as a mere string change. Wdyt? Does this seem like an improvement in wording for that menu option?

We can keep this on our radar regardless of the outcome of this PR ✅

Edit: Added [a note on the backlog](https://github.com/orgs/wordpress-mobile/projects/115#column-17637236) for this.

**Comment by ovitrif** [comment]
We won't progress on this for now in light of the other priorities 😅

**Pull request closed without merging**
