### PR TITLE
Fetch purchased themes

### LINKED ISSUE #3459: Themes browser: fetch purchased themes
Themes that have been purchased should show up as available for activation.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #3459 

To test: 

1. On a site that has purchased premium themes, load the Theme browser for the first time.
2. Verify that the premium themes in your account show up in the list.

Needs review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Hiya @kwonye 
Since I haven't been actively working on Android in a while its probably a good idea to get another set of eyes, even for a relatively simple patch.  So having said that, take this feedback with a grain of salt. ;)

 I'm not too keen about how `fetchPurchasedThemes` is doing its own thing, and ignoring the `mFetchingThemes` flag set in `fetchThemes`.  Seems like `fetchPurchasedThemes` and `fetchThemesIfNoneAvailable` are doing basically the same job, just hitting a different endpoint. Would it make sense to combine them into a single task and wrangle the `mFetchingThemes` flag and calls to `FetchThemesTask` in one place?

**Comment by kwonye** [comment]
> Since I haven't been actively working on Android in a while its probably a good idea to get another set of eyes, even for a relatively simple patch

@aerych that's totally fair. I'll have someone else merge this in.

> Would it make sense to combine them into a single task and wrangle the mFetchingThemes flag and calls to FetchThemesTask in one place?

Unfortunately `fetchThemes()` is deceptively complex. It's called on initial start up and also when searching. Adding fetchPurchasedThemes everytime a user scrolls to the end of the list would result in a lot more calls. With `fetchPurchasedThemes` only being called `onResume()`, it saves a bunch of extra work. Also the reason for the `mFetchingThemes` boolean is to make sure the requests don't get sent twice, resulting in double entries.

At the end of the day, you're right. The fact that I had to explain all that for simply fetching themes correctly means this deserves at least another pass through. I'll separate out the fetching of themes with the searching of themes, and hopefully that will result is a more cohesive result.

Thanks!

**Comment by kwonye** [comment]
Ok, after trying the other way, I've determined this way is actually better (unfortunately). The separation between initial request, search, and purchased themes adds another "state" which I'd prefer to avoid.

@tonyr59h let us know what you think :)

**Comment by tonyr59h** [comment]
#4003 discovered and filed while testing.

> @tonyr59h let us know what you think :)

More states == more complications
I see the merit in merging similar/duplicate code, but a case can also be made for writing explicit code. In this case there seems to be little harm in having similar but separate and explicit methods.

**Comment by kwonye** [comment]
@tonyr59h somehow was calling the wrong version of the REST api. That fixed it. Ready for review again.

**Comment by tonyr59h** [comment]
> somehow was calling the wrong version of the REST api

Yeah, that's happened to me a few times too. Would be nice to wrap the various version getters so it could get you the correct version automagically.

**Comment by tonyr59h** [comment]
The REST calls are working now 👍 

Ran into an issue with an account that has a ton of purchased themes (209, maybe Premium subscription?). At a certain point theme info is no longer being downloaded. Scrolling to the bottom of the list the refresh view is shown, continuously restarting its animation, but no network calls seem to be made.

**Comment by kwonye** [comment]
> At a certain point theme info is no longer being downloaded. Scrolling to the bottom of the list the refresh view is shown, continuously restarting its animation, but no network calls seem to be made.

I was able to reproduce that issue without this feature so it is not related to this change. I've created #4028 to address this

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
