### PR TITLE
Update release notes translation script

### PR DESCRIPTION
**Pull request by maxme**
Update release notes translation script

### CODE REVIEW

**Comment by mzorz** [comment]
I've tried the script using `./tools/get-translated-release-notes.sh release_note_71 none` just to test and it produces this set of files

```MacBook-Pro-2:release-notes mariozorz$ ls -l
total 144
-rw-r--r--  1 mariozorz  wheel  2140 Jul 18 15:13 strings-ar.xml
-rw-r--r--  1 mariozorz  wheel  1676 Jul 18 15:13 strings-de.xml
-rw-r--r--  1 mariozorz  wheel  2040 Jul 18 15:13 strings-en-gb.xml
-rw-r--r--  1 mariozorz  wheel  2341 Jul 18 15:13 strings-es.xml
-rw-r--r--  1 mariozorz  wheel  2066 Jul 18 15:13 strings-fr.xml
-rw-r--r--  1 mariozorz  wheel  1830 Jul 18 15:13 strings-he.xml
-rw-r--r--  1 mariozorz  wheel  1703 Jul 18 15:13 strings-id.xml
-rw-r--r--  1 mariozorz  wheel  1817 Jul 18 15:13 strings-it.xml
-rw-r--r--  1 mariozorz  wheel  1838 Jul 18 15:13 strings-ja.xml
-rw-r--r--  1 mariozorz  wheel  1703 Jul 18 15:13 strings-ko.xml
-rw-r--r--  1 mariozorz  wheel  2243 Jul 18 15:13 strings-nl.xml
-rw-r--r--  1 mariozorz  wheel  2220 Jul 18 15:13 strings-pl.xml
-rw-r--r--  1 mariozorz  wheel  2037 Jul 18 15:13 strings-pt-br.xml
-rw-r--r--  1 mariozorz  wheel  1900 Jul 18 15:13 strings-ru.xml
-rw-r--r--  1 mariozorz  wheel  1964 Jul 18 15:13 strings-sv.xml
-rw-r--r--  1 mariozorz  wheel  1744 Jul 18 15:13 strings-tr.xml
-rw-r--r--  1 mariozorz  wheel  1244 Jul 18 15:13 strings-zh-cn.xml
-rw-r--r--  1 mariozorz  wheel  1592 Jul 18 15:13 strings-zh-tw.xml
MacBook-Pro-2:release-notes mariozorz$ 
```

Shouldn't it generate one file, that has the structure as in the example?
screen-shot-2017-07-18-at-08-56-14

**Comment by maxme** [comment]
These are the temporary files (fetched from GlotPress), but they should be in `/tmp/release-notes/`

**Comment by mzorz** [comment]
> note that release_note_71 does not exist in GlotPressTried with `./tools/get-translated-release-notes.sh release_note_79 none`, 
but the result is this

**Comment by mzorz** [comment]
:shipit:

**Pull request merged**
