### PR TITLE
Fix #5123: People tweaks for Jetpack sites

### LINKED ISSUE #5123: People: Add support for People Management to Jetpack-connected sites
### Expected behavior

I expect to be able to manage the users/followers on my site (in the People section) for WordPress.com and Jetpack-connected sites. (This includes Business sites that were automatically transferred.)

### Actual behavior

The People section is only supported for WordPress.com sites.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-34

### PR DESCRIPTION
**Pull request by aforcier**
Addresses #5123, making a few fixes needed for a smooth Jetpack experience in the People activity.

1. Added the missing `Subscriber` role for Jetpack sites
2. Disabled inviting new users to Jetpack sites: it doesn't look like this flow is supported yet. Calypso sends the user to their self-hosted `wp-admin`. Relevant Calypso issue: https://github.com/Automattic/wp-calypso/issues/11107.

To test:
* Try changing user roles for Jetpack and WP.com sites - only Jetpack sites should offer the `Subscriber` role
* Check user invitation flow - it should only be available for WP.com sites

### CODE REVIEW

**Comment by maxme** [comment]
> Disabled inviting new users to Jetpack sites: it doesn't look like this flow is supported yet. Calypso sends the user to their self-hosted wp-admin. Relevant Calypso issue: Automattic/wp-calypso#11107.

Using the `feature/fluxc-integration` branch, I tried to invite both a wpcom user and an email address on a Jetpack site and it's working well. In the first case I get this screen after clicking in the email link:

screen shot 2017-03-09 at 08 51 11

In the other case (email address), Calypso asks me to create a wpcom user (expected).

**Comment by maxme** [comment]
> Added the missing Contributor role for Jetpack sites

I confirm **Subscriber** role now works correctly on Jetpack sites.

**Comment by maxme** [comment]
Looks good, but I would keep the invitation button for Jetpack sites. I don't know why Calypso redirects to wpadmin for Jetpack sites, I guess it's a frontend issue only.

**Comment by aforcier** [comment]
> Using the feature/fluxc-integration branch, I tried to invite both a wpcom user and an email address on a Jetpack site and it's working well.

Have you tried adding a user as a role other than follower? When I do, I get a normal invitation screen like you did, but after accepting things are in a weird state:

1. From the perspective of the inviter, the new user doesn't appear in the list of users, neither in Calypso nor in the Jetpack site's wp-admin
2. From the perspective of the new user, they have the site added to Calypso, but they don't seem to have permissions for anything - errors everywhere, can't publish posts, etc (tested this for Editor and Administrator)

**Comment by aforcier** [comment]
I did miss that Follower was working - if you can reproduce the above issue too, I can restore the invitation button for Jetpack sites, but only allow adding Followers.

**Comment by maxme** [comment]
> I did miss that Follower was working - if you can reproduce the above issue too, I can restore the invitation button for Jetpack sites, but only allow adding Followers.

Ok let's do that, re-enable the invite button but only keep the Follower role in the list for Jetpack sites.

**Comment by aforcier** [comment]
> Ok let's do that, re-enable the invite button but only keep the Follower role in the list for Jetpack sites.

Done in d6f73d6 and f5b9c59. I also disabled the arrow and pop-up dialog in the Jetpack site case.

**Comment by maxme** [comment]
Changes look good, :shipit:

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/pull/15357

**Pull request merged**
