### PR TITLE
Rename invalid url message to invalid blog url to avoid confusion

### PR DESCRIPTION
**Pull request by oguzkocer**
This is the 2nd of Account Settings PRs. It's a very simple change and I am not really sure if I should split this up or not. The only reason I wanted to split it up is, even though simple, it changes 48 files which clutters up main PR. I think it'll just be easier for the reviewer. If I shouldn't split it, please let me know and I'll close the PR and avoid it in the future. Thanks!

Reason for the change: I need an `invalid_url_message` string resource and instead of coming up with a different name I wanted to rename the original one since it says "Check that the blog URL entered is valid".

/cc @astralbodies 

Needs Review: @hypest Up for another one? I promise it'll take less then 2 minutes :)

### CODE REVIEW

**Comment by maxme** [comment]
Please don't change translation files `WordPress/src/main/res/values-XXXXXXX/strings.xml` - not a big deal but introduce some noise.

**Comment by maxme** [comment]
Also I'm not sure about the wording - "blog" vs "site", I think we want to avoid the use of "blog".

**Comment by oguzkocer** [comment]
@maxme So, should I just change the `values/strings.xml`? If that's the case, we can just close this PR, because noise was the only reason I split this up, I can remove the changes from the other `values-xx` files in the main PR.

Re - wording: I used `invalid_blog_url` because the string says Blog, if you prefer I can change both the resource and the string?

**Comment by maxme** [comment]
> @maxme So, should I just change the values/strings.xml?

Yes

> If that's the case, we can just close this PR, because noise was the only reason I split this up, I can remove the changes from the other values-xx files in the main PR.

Yes

> Re - wording: I used invalid_blog_url because the string says Blog, if you prefer I can change both the resource and the string?

And yes ;) (check the Calypso repo, to make sure I'm not mistaken)

**Comment by oguzkocer** [comment]
Thanks @maxme! :)

**Comment by oguzkocer** [comment]
@maxme I *think* we need to change the values in `WordPress/src/main/res/values-XXXXXXX/strings.xml` because I am adding the original string `invalid_url_message` after this change. If I don't change the values, wouldn't the new string be translated as the old one in those languages?

**Comment by maxme** [comment]
@oguzkocer Nope, translations are always deleted/re-downloaded (from GlotPress) before a release. So it's useless to commit them.

**Comment by oguzkocer** [comment]
I see - thanks for clarifying!

**Pull request closed without merging**
