### PR TITLE
Delete cancelled media from media library

### LINKED ISSUE #5942: Cancelled media uploads from editor remain in Media Library
When canceling a media upload from the editor (Aztec or visual), it's correctly removed the post and the network request is cancelled, but the media item continues to show up in the media library.

eternal-media-upload

There's no obvious way to remove it (it can be done by long-pressing until a trash icon appears in the action bar) - but it shouldn't appear in the first place.

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5942, partially. When manually cancelling media uploads from the editor, they'll now be deleted, and won't show up as permanently 'Uploading' in the media browser:

eternal-media-upload

If the user exits the editor with in-progress media, they won't be deleted (as the user might re-open the post and retry the media). Instead, they'll be marked as failed, and will show up with a 'Retry' message in the media browser:

retry-media-library

This still isn't ideal. Retrying from the media browser will work, and the media will be uploaded to the site, but the post won't be updated to use the remote media URL. This will be fixed once the async media branch is in `develop`, and in my opinion this is as far as it's worth fixing `develop` in the meantime.

**Note:** ~~https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/457 should be reviewed in parallel, and this PR should be updated to use the latest FluxC `develop` hash before being merged.~~ https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/457 merged and hash updated in 4f51a5c.

Note: A separate PR with a more satisfying fix will be made against the `feature/async-media` branch.

To test:
1. Upload media to the editor
2. Cancel the media
3. Verify that the media doesn't exist in the media library
4. Upload another media to the editor
5. Exit the editor while media is in progress
6. Verify that the media shows up with a 'Retry' message in the media library

Try the above for WP.com and self-hosted sites.

cc @mzorz

### CODE REVIEW

**Comment by mzorz** [comment]
Note: had to merge `develop` into this branch to get the latest updates in FluxC methods naming (#6034), but didn't update the remote branch.

With that in mind, the main purpose of this PR:
> and won't show up as permanently 'Uploading' in the media browser:

is confirmed to be working alright, however this is the detailed result as per my tests:

**CASE A**: OK for both wp.com and self-hosted
1. start new post
2. write something and add a pic
3. cancel it
4. go to media library, validate there’s nothing in there


**CASE B:** 
(same behavior observed for both wp.com and self-hosted)
1. start new post
2. write something and add a pic
3. exit the editor without canceling
4. go to media library
5. the media library shows 2 items, one QUEUED, the other one UPLOADING
screenshot_20170614-163325

6. when the one UPLOADING finishes, the QUEUED one still remains
screenshot_20170614-163456

I'd say it's a minor issue and still fixes the key error which is having neverending "UPLOADING" images. Open to suggestions here @aforcier .

**Comment by mzorz** [comment]
Also note, tapping on the item marked `QUEUED` would show a blank screen with an error
screenshot_20170614-162524

**Comment by aforcier** [comment]
> Note: had to merge develop into this branch to get the latest updates in FluxC methods naming (#6034), but didn't update the remote branch.

Merged `develop` in (f944479).

> when the one UPLOADING finishes, the QUEUED one still remains
> I'd say it's a minor issue and still fixes the key error which is having neverending "UPLOADING" images. Open to suggestions here @aforcier .

As we discussed, let's look for this bug in the PR I'll open fixing cancellation in the `feature/async-media` branch - if it's fixed there we can just not worry about it, otherwise we'll open a new issue.

> Also note, tapping on the item marked QUEUED would show a blank screen with an error

We have an open issue for this one - https://github.com/wordpress-mobile/WordPress-Android/issues/5270.

**Comment by mzorz** [comment]
:shipit:

**Pull request merged**
