### PR TITLE
Add project gradle.properties to configure gradle performance

### PR DESCRIPTION
**Pull request by kwonye**
We did not have a default project `gradle.properties`. It has to be at the project level, not the module level as this is where the IDE gets its JVM arguments. This will help anyone who uses Android Studio to build.

I took the default template from Android Studio.

`gradle.properties` is still in the `.gitignore` file, so further changes will not be added to git.

Needs review: @maxme

### CODE REVIEW

**Comment by maxme** [comment]
I'm not sure, I think it's too late... Checking out that branch deleted my original `gradle.properties` (not sure why git didn't warn me) :(

**Comment by kwonye** [comment]
> I'm not sure, I think it's too late...

Do you mean that most people have already created it locally so we shouldn't add it to git? If so, I disagree. I had actually put the `jvmargs` into the module `gradle.properties` thinking that is where it should be placed. I can imagine most people doing the same.

> Checking out that branch deleted my original gradle.properties (not sure why git didn't warn me) :(

Sorry about that! Likewise, I didn't know git overwrote files without warning...

**Comment by maxme** [comment]
Ok, can we add `org.gradle.configureondemand = true` and  `org.gradle.daemon = true` (with bare minimum doc) as well? So if it deletes my config once more, I can revert to my old one quicker ;).

**Comment by maxme** [comment]
https://docs.gradle.org/current/userguide/build_environment.html

**Comment by kwonye** [comment]
@maxme good call, added. Again, sorry it deleted your file. I'll post a warning to everyone that an upcoming PR may wipe out their gradle.properties file.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
