### PR TITLE
Remove FluxC migration code

### LINKED ISSUE #5643: Drop the pre-FluxC migration code introduced for 7.0

### PR DESCRIPTION
**Pull request by maxme**
Fixes #5643: Remove FluxC migration code introduced in 7.0

## Test non-migration from 6.9 (or previous versions):

1. Install 6.9, sign in a wpcom account (or pure self hosted)
2. Install this branch (same build variant), you should be signed out (signin screen):  ✅ 

## Test non-migration from 7.x:

1. Install 7.0,  sign in a wpcom account
2. Install this branch (same build variant), you should be signed in:  ✅

### CODE REVIEW

**Comment by aforcier** [comment]
We can [drop `PostStore` from `WordPress.java`](https://github.com/wordpress-mobile/WordPress-Android/blob/9e99f325ff3f7f3a871ecfb67bcef697611d71a2/WordPress/src/main/java/org/wordpress/android/WordPress.java#L120) now.

**Comment by aforcier** [comment]
Looks good!

* `6.9` --> this: ✅
* `7.x` --> this: ✅
* Clean install of this: ✅

Aside from the [tiniest of nits](https://github.com/wordpress-mobile/WordPress-Android/pull/6383#issuecomment-317715008), this is good to go 👍.

**Comment by maxme** [comment]
> We can drop PostStore from WordPress.java now.

Removed in ffba92a

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
