### PR TITLE
[Gutenberg] Use tarball instead of git tag for forked dependencies

### PR DESCRIPTION
**Pull request by ceyhun**
Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3982

This PR only bumps the Gutenberg Mobile reference.

**To test:**
Follow testing instructions from https://github.com/WordPress/gutenberg/pull/34886.

## Regression Notes
1. Potential unintended areas of impact
None apart from the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Smoke testing that the editor could be opened and blocks could be added.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hypest — APPROVED** [review]
Looks and runs fine so, I'll go ahead and give it a LGTM!

**Review by hypest — APPROVED** [review]
LGTM!

And similar to the [same comment on the WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17198#pullrequestreview-765154199), before merging the main apps PRs, we shall create an alpha tag to point to the gutenberg-mobile merged version, right?

**Comment by fluiddot** [comment]
> LGTM!
> 
> And similar to the [same comment on the WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17198#pullrequestreview-765154199), before merging the main apps PRs, we shall create an alpha tag to point to the gutenberg-mobile merged version, right?

Exactly, we'll create an alpha tag after merging the gutenberg-mobile PR and update the reference here.

**Comment by fluiddot** [comment]
> > LGTM!
> > And similar to the [same comment on the WPiOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17198#pullrequestreview-765154199), before merging the main apps PRs, we shall create an alpha tag to point to the gutenberg-mobile merged version, right?
> 
> Exactly, we'll create an alpha tag after merging the gutenberg-mobile PR and update the reference here.

The Gutenberg Mobile reference now points to the tag `v1.63.0-alpha1`.

**Pull request merged**
