### PR TITLE
Fix 6951 - Aztec newlines lost with media success/failure processing

### LINKED ISSUE #6951: Aztec: new lines are lost in Calypso mode
### Expected
New lines should be kept at all times

### Observed
New lines are gone after a failed media item is processed by `AztecTextParser` when a media item is finished uploading

### Steps to reproduce the behavior
1. start a new draft
2. write some text entering “ENTER” on purpose, like:
“something<ENTER>”
“another thing<enter>”
“bla bla<enter>”
“bla bla<enter>”
“bla bla<enter>”
“bla bla<enter>”

3. insert some media items
4. exit the editor while media items are uploading
5. either wait until uploads finish, or if inpatient make the uploads fail, maybe by turning airplane mode ON
6. see the post show the error in the post list
8. now open the Post
9. see all new lines are gone
screen shot 2017-12-05 at 7 14 26 pm

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6951

Related Aztec PR https://github.com/wordpress-mobile/AztecEditor-Android/pull/569
**NOTE:** the AztecEditor PR need to be merged first, and then we need to update the hash reference in `build.gradle` here.

To test:
1. start a new draft
2. write some text entering “ENTER” on purpose, like:
“something<ENTER>”
“another thing<enter>”
“bla bla<enter>”
“bla bla<enter>”
“bla bla<enter>”
“bla bla<enter>”

3. insert some media items
4. exit the editor while media items are uploading
5. either wait until uploads finish, or make the uploads fail, maybe by turning airplane mode ON (_please test both cases as it takes 2 different code paths_)
6. see the post show the error in the post list
8. now open the Post
9. see the Post is kept as originally saved

cc @0nko

### CODE REVIEW

**Comment by 0nko** [comment]
The mentioned PR has been merged but there are some conflicts now 👇.

**Comment by mzorz** [comment]
> The mentioned PR has been merged but there are some conflicts now 

fixed in f49e6dd 🙇  - ready for review

**Comment by mzorz** [comment]
fixed latest merge conflicts in f3c6cd0

Ready for another pass @0nko ! 🙇

**Comment by 0nko** [comment]
So I tested it with a bigger video the interruption case isn't working for me. It works when you open the draft with a failed upload for the first time, but when I leave the post and go back it's on one line again.

**Comment by mzorz** [comment]
> So I tested it with a bigger video the interruption case isn't working for me. It works when you open the draft with a failed upload for the first time, but when I leave the post and go back it's on one line again

That's right! bc46b08 should fix it. Thanks for testing this beyond the simple steps provided 🙇

**Comment by 0nko** [comment]
Nice work. I could not reproduce the bug anymore! 👍 
:shipit:

**Pull request merged**
