### PR TITLE
Stats - New approach on comparing Views and Visitors

### LINKED ISSUE #2347: New Approach to Views / Visitors
The web version of Stats is going to introduce a new way to show users the relation between the counts of Views and Visitors.

We should replicate the new UI in this native app. Below is a screenshot of what is going to be web stats on mobile.
53dec374-b2bb-11e4-84ac-bb18025da497

The PR is not yet merged/deployed to users, and minor changes could happen in the next few days, but we can already start implementing it, since changes required to show 2 dataset in the graph are not small.

### PR DESCRIPTION
**Pull request by daniloercoli**
From our iteration planning hangout we decided to spend some time determining what is the best way to show users the relation between the counts of Views and Visitors.  We ended up with a solution that involves the following changes:

- Introduction of a legend on each tab of the graph
- On the View tabs there is now a checkbox that enables users to compare Views and Visitors
- Views and Visitors share the same Y-axis

untitled

This PR fix #2347 and #2117 (The later was quickly fixed since a definitive solution that looks shiny on the UI front involves lot of changes, and we're not sure we want to do atm).

### CODE REVIEW

**Comment by jancavan** [comment]
@daniloercoli looks good! "Views" appears while loading though. Would it be possible to get rid of that and just have it empty?

loading

**Comment by daniloercoli** [comment]
@jancavan - Ok, I've removed the legend on the screen at startup. It will be available as soon as data arrives from the wire.

**Comment by jancavan** [comment]
@daniloercoli Just saw this. Thanks for updating, looks good :+1:

**Comment by daniloercoli** [comment]
This is ready for developer review.

**Comment by nbradbury** [comment]
It took me a few tries to figure out that check-marking "Visitors" simply overlaid visitors on the existing chart, and even then I was confused by the separate Visitors tab (is it showing the same data? if so, why? if not, what's the difference?). I think many users will be similarly confused.

Why not drop the checkmark and *always* show Visitors overlaid on the first chart, then drop the Visitors tab entirely?

**Comment by tonyr59h** [comment]
Coming along very nicely! Seems to be working as expected, just have a few UI thoughts:

<ol>
<li>The image is from my S3, which shows an alignment issue with the checkbox. My Nexus 5 displays it just fine though. I'm guessing it's something to do with the checkbox height on different displays</li>
<li>Looks like the issue above also causes a slight 'jump' in the UI when switching to/from the Views tab, only on my S3.</li>
<li>On the jumpiness note I also noticed one when there's different order of magnitude in the y-axis values between tabs (see https://cloudup.com/cXAYJl9mot2). Should we clamp the width of the y-axis labels?</li>
</ol>

Gravy:
I think it would look good to animate the visitors overlay in/out as the user toggles it. I love how responsive it is right now, animating it may make it more apparent.

**Comment by tonyr59h** [comment]
> Why not drop the checkmark and always show Visitors overlaid on the first chart, then drop the Visitors tab entirely?

Since both tabs share the same y-axis this would make sense.

**Comment by tonyr59h** [comment]
The checkbox is always cleared when the user switches tabs. By design?

**Comment by jancavan** [comment]
> Why not drop the checkmark and always show Visitors overlaid on the first chart, then drop the Visitors tab entirely?

Yeah, that makes sense and we did try having just 3 tabs for Calypso, but with one tab having 2 items (Views and Visitors), it looked strange. We also tried giving each tab the same width, but with the first tab having 2 items, it looked squished.


https://github.com/Automattic/calypso-pre-oss/issues/3619

We'll continue to keep iterating from here, but as of this point, this is the solution we came up with and we're also trying to get uniformity across Calypso, Android and iOS. Right now, the Visitors tab is only for you to view Visitors data by itself. 

> The checkbox is always cleared when the user switches tabs.

@tonyr59h @daniloercoli Sorry I missed this so thanks for pointing this out. The checkbox need to be checked by default and its state should remain the same even after switching tabs.

**Comment by daniloercoli** [comment]
@tonyr59h I've fixed the issue with the left padding on the Checkbox for devices running Android 4.1 or lower.

It appears that the Checkbox already uses padding by default internally and overriding it with paddingLeft causes the issue you're reported above. We had 2 options, one is to use a different layout file, and the other is to set the padding programatically. I've used the latter for simplicity, otherwise I need to a new folder to the prj, and add a new layout file.

**Comment by tonyr59h** [comment]
@daniloercoli just tested with the changes. Everything checks out, looks like we can :shipit:

**Comment by daniloercoli** [comment]
You can merge the PR then :) 
Remember to delete the branch once it's merged.

**Pull request merged**
