### PR TITLE
Removes display of empty sitepicker dialog when user doesn't have multiple sites

### LINKED ISSUE #12372: Account Settings: Primary site option is available even when the user has no sites
### Expected behavior
I expect that the "Primary site" setting won't be available if I don't have any sites.

### Actual behavior
The "Primary site" setting is available even if I don't have any sites and displays an empty site picker dialog.

### Steps to reproduce the behavior
1. Login to the app with an WP.com account that have no sites
2. Press the avatar icon at the top right corner of the screen
3. On the Me screen, select **Account Settings**
4. On the Account Settings screen, notice that the **Primary site** option is available
5. Select **Primary site**
6. Notice that the site picker dialog is empty

##### Tested on Pixel 3 XL, Android 9, WPAndroid 15.2-rc-1

Note: these steps were originally provided by @guarani in pbMoDN-ET-p2#comment-1206

### PR DESCRIPTION
**Pull request by SowmiaS**
Fixes #12372

### Now
- When the user has no sites, on click of primary site preference, an empty dialog is shown.
- When the user has only one site, on click of primary site preference, a dialog is shown with that one site being selected already.

### Why
- It doesn’t make sense for the user to see an empty dialog when the user has no sites to choose as the primary site.
- It doesn’t make sense to show a dialog to choose a site where there are no other site options to choose from. As it has only one site.

### How:
- when the user **has multiple sites** and clicks on primary site preference, the **dialog is opened with sites to choose** as the primary site.
- when the user **doesn’t have multiple sites** ( zero or only one site), then the **dialog is not shown** to the user on clicking the primary site preference.

### **Screenshots**
| After  | Before|
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/4975407/164614200-f89f8499-3b1e-4555-b155-8a6302485894.mp4">  | <video src="https://user-images.githubusercontent.com/4975407/164614188-105c0662-fa87-4dd0-a414-eb0b50d7323f.mp4">|
| <video src="https://user-images.githubusercontent.com/4975407/164615005-9acc2dfd-cfe3-4c98-bf15-08d08edfaf16.mp4">  | <video src="https://user-images.githubusercontent.com/4975407/164614202-75cadd2a-2273-466c-b2cc-1bff66a01923.mp4">|
| <video src="https://user-images.githubusercontent.com/4975407/164614158-0d1877f5-6ae3-416e-9b7d-2a9357389687.mp4">  | <video src="https://user-images.githubusercontent.com/4975407/164614128-3b77a56a-5953-4c33-b8cf-1555e4996e4c.mp4">|

## Regression Notes
This PR may impact the `App Settings` screen and `Site Settings` screen as `DetailListPreference` is reused on all screens.
I have verified the `App settings` and `site settings` screen if, on click of preferences, the dialog is shown properly with options.
| App Settings  | Site Settings |
| ------------- | ------------- |
| regression_app_settings | regression_site_settings|

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AjeshRPai** [comment]
Hey @SowmiaS Ping me once this is updated with the `trunk` branch and ready for review. Thanks in Advance.

**Comment by SowmiaS** [comment]
@AjeshRPai 👋 This PR is ready for review. I think this PR needs approval from design team. Kindly tag the respective team to have a look.
Thank you.

**Comment by AjeshRPai** [comment]
@SowmiaS Thanks for working on it. I am not sure whether any design review is needed or not. Correct me if am wrong but there is no change in UI just that we don't show the Dialog in the case of no sites and only one site right?. 

❓ Do you think showing a snack bar with the message "no sites present" or "only one site present" in case someone taps on the primary site preference makes sense? 🤔 .

**Comment by SowmiaS** [comment]
@AjeshRPai 
> I am not sure whether any design review is needed or not. Correct me if am wrong but there is no change in UI just that we don't show the Dialog in the case of no sites and only one site right?.

Ya, you are right. we just don't show the dialog in case of no sites / only one site. 
[The issue](https://github.com/wordpress-mobile/WordPress-Android/issues/12372) is **an empty dialog is shown when there are no sites**. I have come up with the decision to hide the dialog on no sites and only one site. I am not sure if the team consults these kind of decisions with the design. 

> ❓ Do you think showing a snack bar with the message "no sites present" or "only one site present" in case someone taps on the primary site preference makes sense? 🤔 .

Since It is settings screen, simpler the UI would be better. I think display of snack bar with the message "no sites present" or "only one site present" is not needed. I think the user would understand that there are no sites / only one site from the feedback on clicking the preference. 🤔 wdyt?

**Comment by AjeshRPai** [comment]
> Since It is settings screen, simpler the UI would be better. I think display of snack bar with the message "no sites present" or "only one site present" is not needed. I think the user would understand that there are no sites / only one site from the feedback on clicking the preference. 🤔 wdyt?

On second thought, I agree with you. I feel there is no need for a snack bar.  I will try to add someone for a design review and make the decision on whether snack bar is needed or not.

**Comment by osullivanchris** [comment]
> ❓ Do you think showing a snack bar with the message "no sites present" or "only one site present" in case someone taps on the primary site preference makes sense? 🤔 .

I had the same thought as this when I was watching the videos. I think the new behaviours make sense. But I think an explanation may be helpful to the user. We don't know why they are tapping it. For example, maybe they have two sites on different email accounts. Or maybe they think they have been added to a site, but they haven't yet. They won't know why nothing is happening.

So, I think a Snackbar telling the user they have zero sites or only one site, could be helpful when the UI does nothing on interaction.

Otherwise looks like an improvement, and thanks for working on it! 🙌

**Review by AjeshRPai — CHANGES_REQUESTED** [review]
@SowmiaS 

As @osullivanchris pointed out, I think we can add a snack bar for letting the user know that there is only one site. Other than that, everything looks good to me. 

>So, I think a Snackbar telling the user they have zero sites or only one site, could be helpful when the UI does nothing on interaction.

**Comment by SowmiaS** [comment]
> For example, maybe they have two sites on different email accounts. Or maybe they think they have been added to a site, but they haven't yet. They won't know why nothing is happening.

@AjeshRPai 
@osullivanchris Thanks for your input. This makes sense. 

Just a small suggestion **in the way we show the message**. I would recommend showing a ```Toast``` message instead of ```Snackbar```. But this is just my opinion, Please let me know your thoughts.

**Reason:**

-  If there is a pending email address change, a ```Snackbar``` will be shown permanently (it will not be dismissed after a few seconds) in the Account settings screen. 
- The behaviour mentioned in point 1 is necessary because there will be discard button in the ```Snackbar```. The user should be **always have the option to discard the email address change**.
- When we display a ```Snackbar``` on clicking the primary site (having only one site or zero sites), we have to redisplay the ```Snackbar``` for email address change after this is dismissed.
- Dismissing and reshowing the ```Snackbar``` with the email change message  may be confusing for the user.

Please check the below video for a better understanding.

|  Snackbar|Toast|
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/4975407/205236657-ab0165e5-0d5a-474e-b258-d2b7682fedd5.mp4">  | <video src="https://user-images.githubusercontent.com/4975407/205236678-92dba67e-cadf-4d5f-ba8a-27451ff3ad7b.mp4">|

Note: In Android only one ```Snackbar``` can be displayed at the moment.

**Comment by osullivanchris** [comment]
@SowmiaS apologies for the slow reply, this slipped past me in my notifications.

Firstly, thanks for explaining the difference between Snackbar and Toast messages, previously I just used these terms interchangeably and was not picturing what I see is a toast message.

I think maybe the problem here stems from the way the **email address verification** is being handled. It should either:

- display a Snackbar and dismiss
- display some other UI if it needs to be displayed indefinitely

For example, if the message about email address verification needs to be displayed indefinitely, it could be displayed under the email address as a piece of small print. That would free up the Snackbar for us.

However given that the issue I've raised about displaying some information is a small detail, and there are other areas of the app where we disable a field and don't inform the user why, I think using a Toast message will do the job for now. 👍

**Review by AjeshRPai — APPROVED** [review]
Hey @SowmiaS 

I have tested the PR as of now, and everything looks good to me 👍🏼 

On clicking primary site 
- empty dialogue is not shown when there is only one site 🟢 
- A dialogue to choose a site is shown when there is more than one site 🟢 

Let me know if you want me to merge this PR and take the task of showing toast as a separate issue or if you would like to do it in this PR. 

I am approving but not merging this PR.

**Comment by Mina012015** [comment]
Ok

في الأربعاء، ١٤ ديسمبر، ٢٠٢٢ ٣:٤٥ م Ajesh R Pai ***@***.***>
كتب:

**Comment by SowmiaS** [comment]
Sorry for the delay. @AjeshRPai 
> Let me know if you want me to merge this PR and take the task of showing toast as a separate issue or if you would like to do it in this PR.

Let me take it up as a separate issue.

Kindly merge this PR.

Thanks.

**Comment by AjeshRPai** [comment]
@SowmiaS 👍🏼 

Once again @SowmiaS , thanks for working on this. I have created an issue for showing toast here - https://github.com/wordpress-mobile/WordPress-Android/issues/17676. I am merging this PR. 🎉 

@osullivanchris - Could u update the message to be shown in toast on this issue https://github.com/wordpress-mobile/WordPress-Android/issues/17676? 🤔

**Pull request merged**
