### PR TITLE
Feature/switching to material theme

### LINKED ISSUE #10629: Switch app to Material theme
In order to implement a Dark Theme, clean up and reduce amount of styles we are using, we need to switch our app to the Material theme.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10629

In this PR we are switching the main Theme of our app from `AppCompat` to `Bridge` version of `Material` Theme. `Bridge` is a transitional theme, that includes styles and attributes from both `AppCompat` and `Material` themes. In practical terms, this means that only Material versions of widgets we are using (from `com.google.android.material.*`) might get affected by the change. I'm using colors provided by @mattmiklic.

We started to use Material widgets some time ago, and since we often time explicitly style all the elements, not many widgets were affected. The majority of issues came from a change in `primaryColor` - we switched it to `blue_50` while keeping toolbar color the same `primary_50`. Fixes for those components are mostly temporary in nature since we are currently going screen by screen switching the rest of the widgets to their material versions and implementing correct styling, and will reach them sooner or later.

Using a new version of the Material library resulted in changers to nullability of attributes in some methods, like `onAttach` (all the changes in java and kotlin files are related to this).

Another change you might notice is `textAppearance` of Tabs, since the Material theme is using `textAppearanceButton` for Tabs.  @mattmiklic do you think it's ok?

[Image from Gyazo](https://gyazo.com/14d626f8732e0bf70b7da7606fda9f89)

To test, I would like you to visuall check a couple of screens and make sure toolbar/tabs look ok. If you notice any other layout differences please let me know!

Screens to check:

- Site preview (white toolbar).
- Stats (top Toolbar/Tabs and tabs at the Comment card on Insight tab.
- Plugin Details.
- Media Settings.
- Post List.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@mattmiklic Yes, it's default color. Material theme is using opacity for inactive/disable elements, so we don't need to pick a color for those elements (although we can).

On a related note, I'm dealing with a swat of build issues, and some of them might get resolved with the update of the Gradle plugin version that we are using. I'll post a comment here when it'll happen.

**Comment by mattmiklic** [comment]
> Material theme is using opacity for inactive/disable elements, so we don't need to pick a color for those elements (although we can).

Looks good to me, then! 👍

**Comment by khaykov** [comment]
As expected, updated of Gradle plugin fixed the build issues 🎉 I have been working off this branch for 2 weeks (with even more material components) and no issues so far.

@develric I think you required an updated material library to progress with your own project, so would be great if you could take a look at this one :)
@marecar3 I think you also needed a material theme for #10279 so just letting you know that it's ready for the review :)

Also, If anyone else would like to try this branch - feel free to do so.

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.5` today, so this is being bumped to `13.6`. If you'd like it to go out as part of `13.5`, please target `release/13.5` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by khaykov** [comment]
Thanks for taking a look @develric ! I didn't realize the change comes from androidx-fragment 1.1.0 inside the material library :) I assume by the time feature branch will reach develop, we will switch to 1.1.0 anyway, so I think it's ok to leave this change as is for now.

I'm fine with just you reviewing this branch - since it's a feture branch, we will have plenty more people looking at it pretty soon.

Again, thanks for the review!

**Pull request merged**
