### PR TITLE
Fix rtl layouts in My Sites section

### PR DESCRIPTION
**Pull request by malinajirka**
Partially fixes #2278 - Fixes RTL layouts on my sites screens

Some Views are not properly positioned in the RTL language mode.

To test: 
1. Check layouts of the My Sites + sub-screens
2. Change your locale to a RTL language (eg. Hebrew) or force RTL layouts in the developer options.
3. Check the layouts, see step 1

Doesn't fix the ViewPager swipe direction in the RTL mode.

### CODE REVIEW

**Comment by malinajirka** [comment]
Some fixes are included in the 'feature/rtl-audit-me-notifications' branch - see https://github.com/wordpress-mobile/WordPress-Android/pull/7174.

**Comment by malinajirka** [comment]
Thanks a lot for the feedback:-)! I've fixed all the issues.

**Comment by khaykov** [comment]
Thanks for the fixes! I have just a couple more nitpicks about padding :D

I'm comparing to current dev branch.

There is still a bit of extra padding near the X at search bar:

[https://gyazo.com/cdbe59155441f5c5bc99deb99252b8bf](https://gyazo.com/cdbe59155441f5c5bc99deb99252b8bf)

And around external link icons (those can be fixed by adding 0dp padding to left/start in `MySiteListRowTextView`):

[https://gyazo.com/c121e6f9b733c102f980ffdac6099de1](https://gyazo.com/c121e6f9b733c102f980ffdac6099de1)

Thanks!

**Comment by malinajirka** [comment]
Thanks @khaykov! You have a great eye for small differences ;). I've fixed the issues.

**Comment by khaykov** [comment]
:shipit:

**Pull request merged**
