### PR TITLE
Magic link is the new login experience

### LINKED ISSUE #4461: Replace Sign In with Magic Links
Make Magic Link the new way to sign in to the WordPress app

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4461 

We are going with magic links as the primary way to log in (at least for WordPress.com)

Because `MagicLinkSignInActivity/Fragment` was simply subclassing/overriding `SignInActivity/Fragment` it's fairly straight forward. All overridden/new methods have been added.

To test:
Go through all log-in situations
1. Log in with a username/password
2. Log in with an email address/magic link
3. Log in with an email address/password
4. Verify smart lock auto-fills account details if the user already has a password saved
5. Log into a self-hosted site
6. Create a new account on WordPress.com

Needs review: @maxme

### CODE REVIEW

**Comment by aforcier** [comment]
I'd like to suggest that we modify the flow slightly when a username is entered, to simplify the flow for self-hosted users.

We could query the `is-available/username?` endpoint in that situation, and if it's not a WP.com username we can go straight to the self-hosted login screen (with the URL field) instead of the username+password only screen.

**Comment by kwonye** [comment]
Moving to 6.2 as there won't be a decision made until then

**Comment by maxme** [comment]
@kwonye not sure if you're working on @aforcier suggestion or if the PR is ready for review. 

Also we should define the conditions of what is a successful or unsuccessful experiment before merging it.

**Comment by kwonye** [comment]
> We could query the is-available/username? endpoint in that situation, and if it's not a WP.com username we can go straight to the self-hosted login screen (with the URL field) instead of the username+password only screen.

@aforcier unfortunately if a username is "admin" or "david", it'll trigger a lot more false-positives than help the self-hosted user. That's why we explicitly did email. So I do not believe we should implement this (cc @maxme)

> Also we should define the conditions of what is a successful or unsuccessful experiment before merging it.

I think the biggest criteria is decreasing log-in error rate. Do you have any other suggestions?

Code-wise it's ready for review. (thanks for the reminder!)

**Comment by kwonye** [comment]
> (By the way, if someone uses admin as their username, we should definitely send them straight to the self-hosted screen - there are probably a few others like administrator and perhaps user we can check on).

@aforcier Good point! I actually think this would be an instant-win. Created #4684

As for the others, there are a few things we have to consider:

1. What happens if the user mistypes their username and is on WP.com?
2. There's backend work required for this, possibly delaying the feature
3. We don't even know if we'll keep this feature, making additional work on it a sunk-cost if we discard it.

Because the self-hosted user has to click the "add a self-hosted WordPress site" currently, I say we ship this as-is and iterate on it after we see the results.

**Comment by aforcier** [comment]
> What happens if the user mistypes their username and is on WP.com?

I concede it's not ideal, but the user can:

1. Press "Sign in to WordPress.com" to go back to the username/email screen and correct their username, or
2. Correct their username and password, ignore the URL field and login successfully, or
3. Correct their username and password, enter any `wordpress.com` URL and login successfully (pending https://github.com/wordpress-mobile/WordPress-Android/pull/4686)

> There's backend work required for this, possibly delaying the feature

Hmm, I'm not sure what backend work would be needed - the `is-available/username?` endpoint seems to be working. What did you have in mind?

> We don't even know if we'll keep this feature, making additional work on it a sunk-cost if we discard it.
>
> Because the self-hosted user has to click the "add a self-hosted WordPress site" currently, I say we ship this as-is and iterate on it after we see the results.

This is fair enough, though I might argue that removing one step for some self-hosted users (those using usernames or emails not on WP.com) might help contribute to a net decrease in log-in error rate and prompt us to keep the feature.

In any case, I'll leave it up to you and @maxme to decide. 😄

**Comment by karama78** [comment]
Bon soir mes frères je ne comprends rien ces applications ne sont pas dans
mon site

thilognedierry

**Comment by karama78** [comment]
Bonjour,

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.

MMOUHAMADOU LAMINE

Veuillez confirmer que vous connaissez MMOUHAMADOU LAMINE: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=kq1YXxaf&invitationId=6195937970730659840&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiummomzc%7Ek3








Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=0-iummomzc-k3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEs-_LcuX0XQQAAAVfxk-BxZz5ji1iPW_2AJ8U9DEaWAms90N9rkXC1VcpfbPjxD8_8GJ7ph_RFCrbyYeSXr0kVb-95UvLletXLIVns_AOrl-VEugCxiCmiem3TlqED8FoNugyTVzBTYdyFTVInmxu3eOy-2s8JNnIjFRX0BHNTD5gfBbiKstj6Njf1RwtVnpXY&eid=0-iummomzc-k3


Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iummomzc-k3&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.

**Comment by maxme** [comment]
When the user is logged in a wpcom account, adding a new self hosted site to the app (Site Picker -> + button -> self hosted), the password field is hidden - https://cloudup.com/c39ZLdRl12A

**Comment by aforcier** [comment]
I just noticed that iOS already implements email this way:

> Case: User enters an email
> --> Email exists on .com? --> Show option to send magic link
> --> Email does not exist on .com? --> Show self-hosted login screen

ios-magic-link-email-self-hosted

By contrast, this implementation still shows the WP.com login screen if the `is-available?email` endpoint returns `true` (so we know it's a self-hosted email, unless it was misspelt):

android-magic-link-email-self-hosted

**Comment by maxme** [comment]
Also make sure of this https://github.com/wordpress-mobile/WordPress-Android/issues/4704 (when it's merged in develop)

**Comment by kwonye** [comment]
> BUG: When the user is logged in a wpcom account, adding a new self hosted site to the app (Site Picker -> + button -> self hosted), the password field is hidden

Thanks @maxme, addressed in 4f6d1a8

> By contrast, this implementation still shows the WP.com login screen if the is-available?email endpoint returns true (so we know it's a self-hosted email, unless it was misspelt):

Thanks @aforcier. I'm guessing you meant when it returns false, and if so, I've addressed that in 10b03a7

**Comment by aforcier** [comment]
> Thanks @aforcier. I'm guessing you meant when it returns false, and if so, I've addressed that in 10b03a7

Hehe, I actually did mean true - the endpoint returns `true` if the queried email is available to be registered (otherwise, a `JSON` error object if the email has already been registered on WP.com, or is an invalid email).

In any case, as of 10b03a7 the self-hosted screen is shown if a non-WP.com email is entered, but there's another issue - the app still tries to log into WP.com in the end:

1. Enter email address for self-hosted site that doesn't exist on WP.com
2. Get self-hosted login screen
3. Fill in correct password and URL for self-hosted site
4. The app attempts to sign in to WP.com instead of to the self-hosted site (and fails)

**Comment by kwonye** [comment]
> In any case, as of 10b03a7 the self-hosted screen is shown if a non-WP.com email is entered, but there's another issue - the app still tries to log into WP.com in the end:

Great catch, thanks! Fixed.

**Comment by kwonye** [comment]
@maxme #4708 is merged into develop and all bugs addressed. Ready for another pass!

**Comment by maxme** [comment]
:shipit:

**Comment by karama78** [comment]
Hi ,

MMOUHAMADOU LAMINE KANE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=kq1YXxaf&invitationId=6195937970730659840&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-z241y6%7Eiv24q6q6%7Egb

View MMOUHAMADOU LAMINE KANE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=kq1YXxaf&invitationId=6195937970730659840&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-z241y6%7Eiv24q6q6%7Egb

J’aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.





Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à ses utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/e/v2?e=z241y6-iv24q6q6-gb&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=z241y6-iv24q6q6-gb&loid=AQFYNJv2LPM7nQAAAVgqgmEdMSZIp7nbb4jV9Oqio8KThcwYxY8hu9t6oVGZtnG7_hIHkPpN9ea70TUxv2EJcl7YgPbZDbIDJSTd1aFKzTPmBKnwJmhRYNUXzxuKFf5kr8aWwbPo-NpCX57rK1s5w6SvgsaYkQAK_vbjdBunDzGtzw3eNJDtEqMh_bAEOpcHl3Jm

Cet e-mail est destiné à reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=z241y6-iv24q6q6-gb&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA. LinkedIn et le logo de LinkedIn sont des marques déposées de LinkedIn.

**Pull request merged**
