### PR TITLE
Issue/2475 connection error for self-hosted users

### LINKED ISSUE #2475: Connection error for non-WPCom users
If you are logged in as a user on a self-hosted blog, you get a `Connection error` when backgrounding/foregrounding the app (if `WordPress.SECONDS_BETWEEN_BLOGLIST_UPDATE` has passed)

Screencap from @maxme: 
screencap-2015-03-16t10-33-29 0100

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #2475 

To test without waiting, change `WordPress.SECONDS_BETWEEN_BLOGLIST_UPDATE` to `1`.

Sorry I could not unit test this. There were a lot of static calls (NetworkUtil, etc). Creating setters/getters would've made readability much worse.

### CODE REVIEW

**Comment by maxme** [comment]
IMO, We should better change the test here: https://github.com/kwonye/WordPress-Android/blob/8f5b1256f77795ee7ce2b07b9de49c73042411b9/WordPress/src/main/java/org/wordpress/android/WordPress.java#L119

(from `isSignedIn` to `hasDotComToken`)

**Comment by kwonye** [comment]
>IMO, We should better change the test here

Great call! I'll change it and test it out.

**Comment by kwonye** [comment]
Change was made. However, the merge from develop has caused another connection error. Will investigate tomorrow. DO NOT MERGE

**Comment by kwonye** [comment]
@maxme Fixed the issue where trying to retrieve mixpanel email would cause a REST error. Now, only retrieving if user has WPCom token

**Comment by maxme** [comment]
That's weird we haven't experienced this before.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
