### PR TITLE
Revert force-enable feature of Aztec

### LINKED ISSUE #6006: Revert force-enable of Aztec
The force-enable feature for Aztec introduced by #6004 was a one-time deal and should be reversed in 7.6.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #6006.

### CODE REVIEW

**Comment by maxme** [comment]
Note to the reviewer: according to #6006 - this should be merged in `release/7.6`

**Comment by 0nko** [comment]
What I meant by that was that it should not be in `develop` by the time we branch version 7.6 from it. So it should be gone both from `develop` and `release/7.6`.

**Comment by mzorz** [comment]
Just to make sure, applying the patch here and thus removing the "force aztec" code does make the  app behave as it did before (i.e. not force new users to use Aztec), but for users that have now already been forced into Aztec (they currently have their flag set to Aztec as they've already run the current version of the app, forcing them into Aztec) and update the app to this patch, they will still have Aztec enabled and will only be able to come back to their previous setting by going into `App settings` and set the editor switch themselves. Just to confirm here: is this behavior what was intended?

**Comment by mzorz** [comment]
Just for the record: confirmed this is the intended behavior with @0nko.

:shipit:

**Pull request merged**
