### PR TITLE
Feature/site media settings

### LINKED ISSUE #6606: Task List: Site Media Settings Master
This is the first task list for the media settings redesign. This list is devoted entirely to redesigning media settings from the Site Media activity. Implementing this redesign from the Editor will come later.

- [x] Image & video settings
- [x] Audio detail & preview (play)
- [x] Document detail (no preview)
- [x] Remove code for previous version of this feature

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #6606 - This PR implements the new media settings redesign for site media (ie: media viewed in the media browser). Media settings for the editor will come in a later PR after changes have been made on the Aztec side.

Screen shots below, demo video [here](https://cloudup.com/cp0OBUjf-7J)

media-settings

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
I got a chance to play around with this last night and I have a few thoughts/suggestions:

- The positioning of the loading indicator (centered on the screen) feels a little odd. My thought is we should either move it to be centered over the media preview that's loading up top -or- we could put the loading indicator over the thumbnail (when the user taps it) until the media is preloaded, then transition to the detail.

- Would it be possible to allow the user to "flick" away images when in an image detail screen, similar to Google Photos, Twitter, etc? Feels like this might be an expected option and I've seen in a lot of places.

- Seems like the shadow over media previews stays anchored to the top of the screen as the user scrolls. This is probably okay, but perhaps should be contained within the top preview area with a mask so that it doesn't overflow and cover the File Details etc when scrolling.

- I'm seeing a "sorry, this video cannot be played" pretty regularly when attempting to play a video.

- Play button on video and audio media previews should be 50x50dp, they are currently 42dp I believe.

- Background behind loading images etc should be Dark Gray (same as audio/doc background)

**Comment by nbradbury** [comment]
> The positioning of the loading indicator (centered on the screen) feels a little odd. 

@iamthomasbishop  Agreed, I moved it to the center of the media preview in bfa3fc5.

> Background behind loading images etc should be Dark Gray (same as audio/doc background)

Just addresesed this in a3f0eb0.

> I'm seeing a "sorry, this video cannot be played" pretty regularly when attempting to play a video.

Yuck. A quick [Google search](https://www.google.com/search?q=sorry%2C+this+video+cannot+be+played+android) shows this is a fairly widespread problem on Android and apparently is due to using an unsupported video format. This existed long before this PR, so I'll file a separate issue for this.

> Would it be possible to allow the user to "flick" away images when in an image detail screen, similar to Google Photos, Twitter, etc?

Ha, don't think I knew you could that! I should be able to do that, but I'd prefer to do it in a separate PR as this one is already quite large.

> Play button on video and audio media previews should be 50x50dp, they are currently 42dp I believe.

Hmmm, they're actually 56dp x 56dp, but perhaps there's some padding I'm not aware of. What tool are you using to determine they're 42dp?

> Seems like the shadow over media previews stays anchored to the top of the screen as the user scrolls.

That's actually on purpose - otherwise the toolbar text would blend into the background when you scroll down.

screenshot_1505998939

**Comment by iamthomasbishop** [comment]
> Ha, don't think I knew you could that! I should be able to do that, but I'd prefer to do it in a separate PR as this one is already quite large.

Sounds good @nbradbury !

> Hmmm, they're actually 56dp x 56dp, but perhaps there's some padding I'm not aware of. What tool are you using to determine they're 42dp?

I'm not 100% sure of the padding, but optically edge-to-edge, I was seeing 42dp when I pulled a screenshot over my mocks. I was using a measuring tool in xScope to measure. 

> That's actually on purpose - otherwise the toolbar text would blend into the background when you scroll down.

Ah, good point. I also didn't realize that was standard. Roll with it 👍

**Comment by nbradbury** [comment]
> I'm not 100% sure of the padding, but optically edge-to-edge, I was seeing 42dp when I pulled a screenshot over my mocks. I was using a measuring tool in xScope to measure.

I used Android's layout inspector to confirm the play icon is 56dp (it's 168px, which is 56dp at xxhdpi), but it turns out there's considerable padding in the image file itself. I compensated for this by enlarging it 60dp, which makes the apparent size without padding to be 50dp.

screenshot_1506081586

**Comment by iamthomasbishop** [comment]
> I compensated for this by enlarging it 60dp, which makes the apparent size without padding to be 50dp.

Perfect! That looks more appropriate at first glance.

**Comment by daniloercoli** [comment]
On my Android 5 device the "play video" overlay looks blurried
device-2017-09-25-125736

Also, the URL field does seem to be properly rendered. Should not be the ellipses at the end?

**Comment by nbradbury** [comment]
@daniloercoli I was stumped as to why the play icon is blurry on that device - it's a vector image so it should resize without any blurring. But I just tested on an Android 5 emulator and sure enough, the icon is blurry.

Turns out this is due to how the support library handles vector images on older devices, and the solution is to create vectors at the exact size desired to they're not resized (which is annoying, since the main benefit of vectors is they're suppposed to be resizable!). I addressed this in e469389.

The URL being cut off turned out to also be caused by a bug on older devices. Fixed in `042da3d` by using `android:singleLine="true"` instead of `android:maxLines="1"`.

**Comment by daniloercoli** [comment]
> Turns out this is due to how the support library handles vector images on older devices, and the solution is to create vectors at the exact size desired to they're not resized (which is annoying, since the main benefit of vectors is they're suppposed to be resizable!). I addressed this in e469389.

😮

**Comment by daniloercoli** [comment]
Nice work @nbradbury! :shipit: 

Side note: Have we considered to add swipe gestures to the media settings screen? Would be cool to have it.

**Pull request merged**
