### PR TITLE
Gutenberg mobile release v1.8.0

### PR DESCRIPTION
**Pull request by Tug**
This PR updates the gutenberg-mobile reference to point to the latest release, v1.8.0.

The reference is currently pointing to the release/1.8.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1172.

**Build is currently failing as we're using the `develop` base, we might want to switch to `release/12.6`!**

To test:
The block editor should work as normal.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
I think I'm noticing two issues

### A. Crash on switch to HTML mode
1. Create a new Gutenberg post with some simple text
2. Back out to the post list, leaving the post to be saved as draft
3. Go into the post again and switch to HTML mode via the 3-dots menu at the top-right
4. 💥 

### B. Image URL not getting updated properly after uploading
1. Create a new Gutenberg post
2. Add an image block and immediately hit the "Publish" button, before the image finishes uploading
3. Wait for the post to get published
4. View the post and notice that the image is not there. If you check the html markup, you'll see that the image still has the device local `///data/` scheme instead of a `https://` one.

**Comment by maxme** [comment]
>     4\. View the post and notice that the image is not there. If you check the html markup, you'll see that the image still has the device local `///data/` scheme instead of a `https://` one.

For some reasons the callback [`onCancelUploadForMediaDueToDeletedBlock`](https://github.com/wordpress-mobile/WordPress-Android/blob/345e9463b8db2441efd78aae0304ac1fd12bd80a/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L260-L262) is called when we hit the publish button while a media is being uploaded. This cancels the media upload and makes the post upload fails (in some case) or succeed with an wrong url (like in the case you described).

We're observing the combination of 2 issues:
- `onCancelUploadForMediaDueToDeletedBlock` shouldn't be called.
- The post upload process should stop if the media upload was cancelled (it's probably not related to Gutenberg).

**Comment by maxme** [comment]
>     * `onCancelUploadForMediaDueToDeletedBlock` shouldn't be called.

I'm not 100% sure, but after having some fun building the stack trace in my head :), I think this happens via:
- `gutenberg/packages/block-library/src/image/edit.native.js::componentWillUnmount` that calls,
- `src/block-management/block-holder.js::onRemoveBlockCheckUpload` that calls,
- `react-native-gutenberg-bridge::requestImageUploadCancel( mediaId );` that calls,
- `WPAndroidGlueCode.requestImageUploadCancel()` that calls,
- `mOnMediaLibraryButtonListener.onCancelUploadForMediaDueToDeletedBlock()`, that calls
- `GutenbergEditorFragment.OnMediaLibraryButtonListener.onCancelUploadForMediaDueToDeletedBlock` that calls,
- `GutenbergEditorFragment.cancelMediaUploadForDeletedBlock`that calls,
- ....
- `EditPostAcitivity.cancelMediaUpload()`.

So I guess that when we push the "Publish" from the wpandroid editor, the activity gets closed (we return to the post list), at that point the fragment is closed and send the `componentWillUnmount` through the RN tree until it hits the one from the Image block. The callback from `imageblock.componentWillUnmount` goes the other way around back to the `EditPostActivity` and cancel the image upload and 💥 .

**Comment by hypest** [comment]
Thanks for the investigation and the great analysis @maxme !

The change in `componentWillUnmount()` doesn't make sense to me although I might not have all the context. @Tug is AFK at the moment so, went ahead and reverted the change. The issue (Case "B" in [the comment above](https://github.com/wordpress-mobile/WordPress-Android/pull/10092#issuecomment-506685500)) seems fixed now.

**Pull request merged**
