### PR TITLE
Issue/9349 update notifications tabs (Part 1)

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the ***Notifications*** list view from segmented control to tabs as described in https://github.com/wordpress-mobile/WordPress-Android/issues/9349.  This is the first part of the issue, which replaces the segmented control interface while keeping the same behavior.  The ability to swipe between tabs will be added in a subsequent pull request.  See the screenshots and animation below for illustration.

### Test
1. Go to ***Notifications*** tab.
2. Notice ***All***, ***Unread***, ***Comments***, ***Follows***, and ***Likes*** tabs.
3. Tap ***All***, ***Unread***, ***Comments***, ***Follows***, and ***Likes*** tabs.
4. Notice notification list updates based on tab selected.
5. Scroll down/up.
6. Notice toolbar hides/shows based on scroll.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
The `RELEASE-NOTES.txt` document was updated in 96a8f2a with the following:
> Updated Notifications with tabs

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Awesome to see this getting some loving 🙂 It looks like a great improvement overall but I have one question: is the internal padding on each tab slightly too much (24dp?). IIRC the other tabs we are using use 16dp, which lines up with the app bar title, but I don't have an Android device in front of me to confirm. Other than that, looks great to me!

**Comment by theck13** [comment]
That is the default tab layout including the internal padding.  The ***All*** tab in the ***Notifications*** screenshot below appears to have more padding since the text is only three characters.  The tabs have a minimum width so short labels look like more padding.  You can see it in the ***Days*** tab in the ***Stats*** screenshot below.

tabs_notifications

tabs_pages

tabs_stats

**Comment by iamthomasbishop** [comment]
Sorry for the radio silence – I should've known better than to leave a comment as I was heading out the door on a Friday 😄 

> appears to have more padding since the text is only three characters

That makes total sense, I had forgotten about the min-width of 90 in the Material Guidelines. Personally, I'm not sure where the 90dp is coming from (considering 48dp is the usual min size for tap area, I'd expect 80dp = 16 + 1 6+ 48 🤷‍♂️ ), but let's stick to what the guidelines suggest for consistency.

:shipit:

**Comment by theck13** [comment]
> Tab selection is not retained during configuration change.

I added retaining the last selected tab in f234d04.

> There is a margin around Toolbar in landscape orientation and on bigger devices:

I removed the layout margin for the app bar in fff00bb.

> There is a weird behavior navigating away from notification screen through AEV and coming back.

That was fixed by retaining the last selected tab in f234d04.

**Comment by khaykov** [comment]
Thanks for the fixes @theck13 ! They look good 👍 
I found another small issue - AEV in landscape orientation is overlapped by tab bar:
[Image from Gyazo](https://gyazo.com/97a9a2b534f749b3345fafca02b01709)

**Comment by theck13** [comment]
> AEV in landscape orientation is overlapped by tab bar

That's an unfortunate consequence of the app bar scroll behavior.  I added a statement to show/hide the actionable empty view image based on device orientation in 78e7dcd.  See the screenshots below for illustration.

**Pull request merged**
