### PR TITLE
Page List : Empty editor when loading more items.

### LINKED ISSUE #11339: Empty editor opened after clicking on existing page item
### Expected behavior
When I click on page in the page list, the editor is opened with the title and content of the page.

### Actual behavior
When I click on page in the page list, the editor is opened with an empty title and content.

### Steps to reproduce the behavior
Update 2/28/2020: The issue happens only when you click on the page item after the first 20 pages were loaded but FluxC is still loading more. In order to reproduce this issue, either make sure to use a site with a lot of pages or change [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7cf14c3b2b1001bf50ae46bc39b0d3f67533d13a/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L72) to 1.

1. My Site
2. Site Pages
3. Click on one of the existing pages
4. Notice the editor is empty
If you leave the editor and click on the page again, it works. However, if you leave back to My Site and repeat the steps it'll fail again. It seems it's failing on the first page you open after entering the page list screen.

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Pixel 2, Android 9
I've tested the behavior in both Aztec and Gutenberg.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #11339

## Solution
I fetch the latest page from the `PostStore` based on the `remote id` since the `local id` is out of sync. I am still checking to see if this solution will resolve the issue without any drawbacks since we are now running another query for the `PostModel` when we wanted to avoid that. 

## Testing
Ensure you have 20 or more pages or change [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7cf14c3b2b1001bf50ae46bc39b0d3f67533d13a/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L72) to 1.
1. My Site
2. Site Pages
3. Click on one of the existing pages
4. Notice the editor is not empty.

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thank you @jd-alexander!

I have been thinking about other possible solution, but all of them have bigger downsides then the solution you are proposing. Only thing I noticed is that the solution doesn't work for local drafts, since those drafts don't have remoteId yet.
1. Turn on airplane mode
2. Create a new page
3. Go back to the page list
4. Click on the page created in step 2 and notice nothing happens


SideNote:
Just listing other solutions we considered for future reference - read [this](https://github.com/wordpress-mobile/WordPress-Android/issues/11339#issuecomment-592469982) for context
1. Increase page size for fetchPages request to 0/99999. We are loading all the pages in one go anyway so we'd limit number of requests as a bonus. This solution doesn't work, since the API supports page size only in interval 1-99.
2. Move the logic for requesting additional pages from PageStore to WPAndroid. We could update `pageMap` after each page gets fetched. Unfortunately, this solution has undesired UX issue. The list keeps jumping as we load next pages. We can't display the pages until we fetch all of them as we are not able to order them correctly.

**Comment by jd-alexander** [comment]
Thanks for expounding @malinajirka 
> I have been thinking about other possible solutions, but all of them have vital downsides. Only thing I noticed is that the current solution doesn't work for local drafts, since those drafts don't have remoteId yet.

Just realized this. Thanks. 

Will keep tinkering to see if anything else pops up.

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.6` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.5` branch which will be available later today and update the milestone for the issue accordingly.

**Comment by jd-alexander** [comment]
@malinajirka when testing today with the `remoteId` there are times when the post still isn't found and I have to tap the item another time for it to be opened but it works most of the times. Do you see this as a better experience than opening an empty page? I think it is. We could further improve this experience by showing a snackbar when it isn't found that tells them to try again shortly. Not something I would want to do but still not comfortable shipping it as, where a user clicks and nothing happens. let me know your thoughts on this. Also for the local draft solution, I utilized the `PageModel` `hasLocalChanges` which is set when a page is a local draft or has local changes. Is that okay?

**Comment by malinajirka** [comment]
>Also for the local draft solution, I utilized the PageModel hasLocalChanges which is set when a page is a local draft or has local changes. Is that okay?

My guess is that this is the reason why it's not always working. Page with local changes is a page which exists in remote and has local changes -> in other words it's a page with unstable local id -> [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/11339#issuecomment-592469982) can still imo happen. Have you tried using `page.post.isLocalDraft`?

>fixed activity launcher method issue. https://github.com/wordpress-mobile/WordPress-Android/pull/11413/commits/0a7db618122ee59071f1847ba64be005a621a009

What was the issue with the previous implementation? I think we can't just change it without changing some other code. If we launch the EditPostActivity using a reference to PagesActivity, `PagesFragment.onActivityResult` won't get invoked. Wdyt?


SideNote:
Btw it seems you've checked out a different branch in gutenberg submodule and pushed the changes. Was it intentional?

**Comment by jd-alexander** [comment]
Thanks for the review!
> My guess is that this is the reason why it's not always working. Page with local changes is a page which exists in remote and has local changes -> in other words it's a page with unstable local id -> this issue can still imo happen. Have you tried using page.post.isLocalDraft?

So I did a change to utilize `isLocalDraft` and the issue still persists. 584e557

> What was the issue with the previous implementation? I think we can't just change it without changing some other code. If we launch the EditPostActivity using a reference to PagesActivity, PagesFragment.onActivityResult won't get invoked. Wdyt?

Thank you for spotting this! I hadn't realized the fragment part 👍 I had to utilize this method because we are now passing a `PostModel` instead of a `PageModel` based on the need to fetch the `Post` from the `PostStore` when a page is tapped. I made changes to how the function worked here so let me know if this is fine b22bbd4

> SideNote:
Btw it seems you've checked out a different branch in gutenberg submodule and pushed the changes. Was it intentional?

Whoops, it wasn't. Resolved it by syncing the gutenberg in this branch with `develop` so it has now disappeared from the diff.

**Review by malinajirka — APPROVED** [review]
Thank you @jd-alexander!

>So I did a change to utilize isLocalDraft and the issue still persists. 584e557

Interesting. I wasn't able to reproduce it. Either case, as you mentioned this is still a huge improvement to the current state. If you are able to reproduce it, could you please create a ticket with reproduction steps + gif. We can assign it to groundskeeping with low priority.


I'm approving this PR. However, I think it'd be good to add a release note. Wdyt? Feel free to merge this PR after you update the release-notes.txt. Thanks!

**Comment by jd-alexander** [comment]
> Thank you @jd-alexander!

Thanks for the review! 

> Interesting. I wasn't able to reproduce it. Either case, as you mentioned this is still a huge improvement to the current state. If you are able to reproduce it, could you please create a ticket with reproduction steps + gif. We can assign it to groundskeeping with low priority.

https://github.com/wordpress-mobile/WordPress-Android/issues/11539

> I'm approving this PR. However, I think it'd be good to add a release note. Wdyt? Feel free to merge this PR after you update the release-notes.txt. Thanks!

Thanks, I just updated the release notes. I will be doing the merge now!

**Comment by jd-alexander** [comment]
@malinajirka closing this in favor of https://github.com/wordpress-mobile/WordPress-Android/pull/11568 since I am having some Gutenberg issues on this branch.

**Pull request closed without merging**
