### PR TITLE
[Reader] Update limit of fetched tag posts from 20 to 7 in Reader

### LINKED ISSUE #19472: [Reader] Decrease requested amount for followed sites
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/21854

Currently, we request 20 sites on the Following filter. This causes the request to take a long time. Reduce that amount to 7 to match what the web is currently doing.

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19472

This was previously [implemented](https://github.com/wordpress-mobile/WordPress-Android/pull/19473) and then [reverted](https://github.com/wordpress-mobile/WordPress-Android/pull/19628) because the item animations when paging happened were wrong.

It seems like #19881 fixed the animations issue, which made me implement this again since there's a meaningful performance impact for the user by decreasing the number of fetched posts.

-----

## To Test:

- Install JP and sign in
- Open Reader and select "Subscriptions" menu item;
- Verify if 7 items are fetched each time we fetch a new page.

Another way to test is opening the tag posts list from blogging prompts card:
- Install JP and sign in
- Open "My Site"
- Tap on "View all responses" in blogging prompts card
- Verify if 7 items are fetched each time we fetch a new page.
-----

## Regression Notes

1. Potential unintended areas of impact

    - Inserting new posts wrong animation

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    --

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by daniloercoli** [comment]
We're correctly retrieving 7 items  from the backend. 👍 

A few things i noticed testing this PR:

**Top Filter UI Element Reverts to Discovery**
- With a fresh installation of the app
- Open the Reader, initially set to the Discover page.
- Tap on Discover and switch to Subscriptions.
- I observed that it quickly reverted back to Discover. Could this be due to an ongoing network request? or possibly because subscription data had not yet been retrieved?

** The animation expanding the Top UI is a bit laggy**
- Transitioning from Discovery to Subscriptions on my device is slow, and briefly, I can see the first pill labeled "Subscriptio" until the UI fully expands.

Side note: is the Top UI element still in progress? If i select Subscriptions, then select "XX Tags", it does says "Selected Site".

**Comment by RenanLukas** [comment]
Thanks for the review, @daniloercoli 

> Top Filter UI Element Reverts to Discovery

I couldn't reproduce this one. I've tried in this branch and in the feature branch (`feature/reader-ia`), both with a fresh install.

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/6b2f1433-eeb2-455c-93eb-5db135bb9e23


If it's reproducible and not caused by this change in the number of fetched posts (which at first sight doesn't seem related) I believe we should create a separate issue for it.

> Transitioning from Discovery to Subscriptions on my device is slow, and briefly, I can see the first pill labeled "Subscriptio" until the UI fully expands.

I also couldn't reproduce this one. Does it happen regularly or just the first time `Subscriptions` is loaded? If it happens regularly maybe we should also create an issue.

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/ff6f50a5-817f-49fb-90e6-85549a676873


> Side note: is the Top UI element still in progress? If i select Subscriptions, then select "XX Tags", it does says "Selected Site".

Hmm, this part should be done already. Where did you see the `Selected Site` label?


https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/63387f36-d088-46f5-b210-1ae9b383b260

**Comment by thomashorta** [comment]
@daniloercoli I believe the branch of this PR is a bit outdated and many changes came in the `feature/reader-ia` since `issue/19473-update-limit-of-fetched-tag-posts-after-fixing-paging` was created, that's likely why you're seeing some of the issues you're seeing, and some of them were already fixed, like the one you mentioned here:
> is the Top UI element still in progress? If i select Subscriptions, then select "XX Tags", it does says "Selected Site".

Since that Filter top bar UI component (the Blogs and Tags pills) was still in development when this branch was opened.

I just did a `git push --force` after rebasing this branch with the latest `feature/reader-ia`. Feel free to check again, as that should contain the latest changes related to the Reader IA project.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by daniloercoli — APPROVED** [review]
LGTM!  The issues I reported in the comments have either been already fixed or are not related to this PR. Consequently, I have opened new tickets for those that are unrelated.
https://github.com/wordpress-mobile/WordPress-Android/issues/19938
https://github.com/wordpress-mobile/WordPress-Android/issues/19939

**Pull request merged**
