### PR TITLE
Fix updating granularity issue for widgets

### PR DESCRIPTION
**Pull request by irfano**
This refactors tracking granularity change and fixes an issue with updating granularity from the widget for the second time.

-----

## To Test:

1. Enable stats_traffic_tab feature flag (Me -> Debug settings - Remote Features)
2. Go to Stats
3. Long press on the app icon in the launcher on device home screen
4. Select Widgets
5. Long press on each of the widgets below
6. Add it to the home screen
7. Follow the prompt to configure the widget with a Site, Colour, and a View as required

#### 1. At a glance widget
- `Ensure` it opens in Traffic tab with 'By day' selected when the feature flag is enabled
- Change the granularity
- Put the app in the background (do not kill it)
- Tap the glance widget again. `Ensure` it opens in Traffic tab with 'By day' selected

#### 2. Today widget
- `Ensure` it opens in Traffic tab with 'By day' selected when the feature flag is enabled
- Change the granularity
- Put the app in the background (do not kill it)
- Tap the Today widget again. `Ensure` it opens in Traffic tab with 'By day' selected

#### 3. Views this week widget
- `Ensure` it opens in Traffic tab with 'By week' selected when the feature flag is enabled
- Change the granularity
- Put the app in the background (do not kill it)
- Tap the Views this week widget again. `Ensure` it opens in Traffic tab with 'By week' selected

#### 4. Views widget
- `Ensure` it opens in Traffic tab with 'By day' selected when the feature flag is enabled
- `Tap` on each row like Today or a date
- `Verify` that it opens the respective date views
- Change the granularity
- Put the app in the background (do not kill it)
- Tap the Views this week widget again. `Ensure` it opens in Traffic tab with 'By day' selected

##### Finally
- Disable the feature flag
- Test each of the widgets opens in Insights or tabs respectively as before

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - Widgets are not proper for automated tests.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/278">24.4</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ravishanker** [comment]
**Views this week** widget, and **Views** widget working only when tapped on their **heading**.  It's not, on a row in the widget.  It works the first time, then doesn't after switching the granularity, backgrounding the app, and tapping on a row in both **Views this week**, and **Views** widgets

**Comment by ravishanker** [comment]
Fixed the granularity issues in a08e3fde41c3392a7c39e132caba618f8f7fc9da

**Review by ravishanker — APPROVED** [review]
Thanks for taking care of this 👍

**Pull request merged**
