### PR TITLE
Me gravatar menu accessibility

### LINKED ISSUE #11599: Me menu with Gravatar accessibility
While working on the #11598 PR (adding gravatar to Me menu) we needed to add an actionLayout custom menu to host the gravatar. This apparently make the long press that should show the tooltip with the menu title/description not working out of the box.

### Expected behavior
Long pressing on the Me with Gravatar menu we should get a tooltip with the menu description `Me`

### Actual behavior
Long pressing on the Me with Gravatar menu nothing is shown.

### Steps to reproduce the behavior
Long press on the Me with Gravatar menu and notice that the tooltip with a `Me` text is not shown.

### PR DESCRIPTION
**Pull request by develric**
This PR does the following:

- Fixes #11599 : using the TooltipCompat for the actionLayout custom me menu
- Tries to make the usage of `MeGravatarLoader > constructGravatarUrl` a bit more consistent
- Fixes RTL support for me menu: before this PR trying to set an RTL language results in the menu to not being visualized (fix here ea97163)

### Me menu tooltip on long press
- long press the me menu and check you get a tooltip with the `Me` word

### Me menu talkback announce
- Enable TalkBack and check the me menu is announced with `Me` word

### RTL support
- Set English language and check you have the Me menu with Gravatar on the right
- Try to long press and tap on it to smoke test the functionality
- Set an RTL language (like Hebrew) and check you have the Me menu with Gravatar on the left
- Try to long press and tap on it to smoke test the functionality

| Screenshot_1586339164 | Screenshot_1586339213 |
|---|---|

## NOTE
@osullivanchris while working on this PR I was thinking if it could make sense to change the alignment of the Me Menu; currently I did not change things in this PR respect to what we had [here](https://github.com/wordpress-mobile/WordPress-Android/pull/11598#issuecomment-610266190) but was looking into making the me menu area wider (64dp see image below) so that it aligns on a 16dp end instead of 8dp. I think 48dp is the material design standard menu width tbh but right/end alignment (especially looking to the main FAB at the bottom) looks a bit strange maybe; let me know if there can be some better related guidelines, thanks 😊

| Screenshot_1586341716 | Screenshot_1586341016 |
|---|---|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
Thanks for the follow up @osullivanchris 🙇‍♂️.

> The version on the 'me' icon is consistent with the UI I'm seeing for long press on other nav bar icons though, so I assume its the correct style there.

Yep I confirm I looked for consistency with the other menus long press tooltip.

> One additional note that I know vertically we have 12dp and 12dp. It would be better if we had 8 or 16dp. [...] I did consider it, but it just didn't work with a different size image.

Thanks for the clarification and I agree that the spec-ed 32dp seems the best fit dimension we can have there 👍. 

Changed the me menu width to 64dp here c5184cc and updated the PR description images.

**Comment by develric** [comment]
**NOTE:** I made a quick check with dark mode and AFAIU it seems fine; pinging @khaykov if you can have a look 🙇‍♂️. Some things I could have doubts are `ic_user_white_24dp` icon (feelColor set to `@android:color/white`) and `me_action_layout.xml` setting the layout background as `?android:attr/actionBarItemBackground` (previous PR #11598 )

| Screenshot_1586851302 | Screenshot_1586851329 |
|---|---|
| Screenshot_1586851528 | Screenshot_1586851517 |

**Comment by khaykov** [comment]
I was about to merge it, but found one small issue with icon color - give me a moment to investigate.

**Comment by khaykov** [comment]
nvm, it was from me modifying code to test a couple of different scenarios :)

**Pull request merged**
