### PR TITLE
Fix issue when media in post were sometimes uploaded with local path

### LINKED ISSUE #10203: Media files are sometimes uploaded with path to local storage
local-image-path
### Expected behavior
When I attach a media file to a post, the post won't get uploaded until the image gets uploaded and the local path to the image is replaced with url.

### Actual behavior
When I attach a media file to a post, the post gets sometimes uploaded even though its content still contains local path to the image.

### Steps to reproduce the behavior
1. Turn on airplane mode
2. Create a draft and add an image into the content
3. Click on Back
4. Create another draft and add **the same** image into the content
5. Click on back
6. Turn off the airplane mode
7. Wait until the uploads completes
8. Open the second post
9. Switch to HTML mode
10. Notice the post contains a path to the local storage

Another scenario which might result in a post with local path being uploaded to the server got fixed here https://github.com/wordpress-mobile/WordPress-Android/pull/10079#issuecomment-510037492

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10203 

Fixes issue where posts were sometimes uploaded with local media.

Clarification why this issue is happening
1. User adds imageA to postA-> UploadService is started -> the iamge is added to the UploadQueue
2. User adds imageA to a postB -> UploadService is started -> the image is **not** added into the queue as it's already there
3. The upload of imageA finishes -> the content of postA gets updated (local path is replaced with url), but the content of postB is never updated as the image wasn't tied to/referencing it. PostB doesn't have any pending MediaUploads so it's pushed to the server.

To test:
1. Turn on airplane mode
2. Create a draft and add an image into the content
3. Click on Back
4. Create another draft and add **the same** image into the content
5. Click on back
6. Turn off the airplane mode
7. Wait until the uploads completes
8. Open the first post
9. Switch to HTML mode
10. Verify the media item cotnains url to the remote file
11. Repeat steps 8-10 for the second post

Update release notes:
- Too minor change - the chance a real user would add a same media to two posts and uploaded them at the same time are quite low

### CODE REVIEW

**Comment by malinajirka** [comment]
Btw I was wondering whether we intentionally wanted to really check just `SiteAndFilePath` and do not check whether it's attached to the same post. However, since the MediaUploadModel contains `localPostId` it's attached to, I believe it's not a good idea even if it was the original intention.

**Comment by maxme** [comment]
> I was wondering whether we intentionally wanted to really check just `SiteAndFilePath` and do not check whether it's attached to the same post.

Not sure why we would do this. Makes sense to me to check the post id. 

I did a few tests, and unfortunately it doesn't fix #10203 - https://bia.is/s/fJ4L/10204-1.webm

**Comment by mzorz** [comment]
> Btw I was wondering whether we intentionally wanted to really check just SiteAndFilePath and do not check whether it's attached to the same post. However, since the MediaUploadModel contains localPostId it's attached to, I believe it's not a good idea even if it was the original intention.

Thanks for bringing this up! IIRC (or at least how I make sense of it) the original intention was to check we don't  upload the same media file twice to the same _Site_ (incurring into potential network costs for the upload and producing an unneeded duplicate on the server) - while it's totally possible to upload the _same media file_ to two _different_ _sites_ (and potentially likely to happen if you have more than one site you'd like to use the image for, I agree it's weird this would happen "at the same time" intentionally, unless you have the posts queued for upload and then network is available, then it doesn't sound so weird with the current behavior of wakening and uploading draft posts, right?). So the check for `site` is because media is uploaded to the site, so that's the "universe" it belongs to.

For the record: tried to follow up the history, while I couldn't find the specific relevant comment that would help us understand why:
- This commit changed things
https://github.com/wordpress-mobile/WordPress-Android/commit/5a253c9ddfe2a5a26d1286d873b1bc4935ee41cb
- see here https://github.com/wordpress-mobile/WordPress-Android/commit/5a253c9ddfe2a5a26d1286d873b1bc4935ee41cb#diff-339e1ea3210c67f894a26e04d833f5f9L239
this is where `addUniqueMediaToQueue()` was introduced and the check for site id and path was introduced. 
- This is the PR https://github.com/wordpress-mobile/WordPress-Android/pull/4616

Tried to dig deeper as to find a comment or anything but couldn't find it.

It sounds (to me) the problem described in the issue may be laying somewhere else then?

**Comment by malinajirka** [comment]
>Thanks for bringing this up! IIRC (or at least how I make sense of it) the original intention was to check we don't upload the same media file twice to the same Site (incurring into potential network costs for the upload and producing an unneeded duplicate on the server)

That's what I would have betted on. However, I'm either missing something or the solution was never actually working properly.

This is my understanding of the **current state**
MediaModel - is referencing a specific media file on the site. The media can be added to a single post (when it's `localPostId` is set to != 0) or be just a standalone media which is visible just in the Media browser (when it's `localPostId` is set to == 0).

MediaUploadModel - is a wrapper class which is used to keep track of the current "upload" state (failed, uploading, completed).

**The issue with the current state**

The idea was that if the MediaModel is already present in the uploadQueue, we don't want to add it there again as we'd unnecessarily waste users' data. The condition I modified in this PR was checking just the siteId and imagePath. However, the issue is that the MediaModel is referencing only a single `localPostId` -> it can't be attached to multiple posts. Therefore when the upload completes the local path of the image is replaced with a url only in one of the multiple posts -> all but the first post are uploaded with the local path.

**Our options**
1. Use the current "hotfix" - the application will waste user's data if the user adds a same image to multiple posts before they get uploaded (eg. in offline).

2. Proposed proper solution (which I don't think is worth it)

MediaModel - remove `localPostId` from the MediaModel as it represents the image in the Media library. Not the instance of the image in a post.

MediaUploadModel - Add a list of `localPostIds` referencing all the posts which needs to be updated when the upload completes (so the local path to the image can be replaced with the url)

Let me know what you think about it. Either case I'd suggest merging this issue and creating a new issue with a comment that this PR needs to be reverted and a proper solution implemented.

cc @mzorz 

> did a few tests, and unfortunately it doesn't fix #10203 

@maxme I'm at a similar spot as yesterday. I'm not able to reproduce your issue. However, I've tried to remove my change an it fails in 100% cases. When I run the code with the change it works for me. So perhaps, there is another issue which results in the same behavior 🤷‍♂.

**Comment by maxme** [comment]
> I'm not able to reproduce your issue. However, I've tried to remove my change an it fails in 100% cases. When I run the code with the change it works for me. So perhaps, there is another issue which results in the same behavior 🤷‍♂.

Yep, the fix makes sense so I'll merge this and keep the issue open if it's ok for you.

**Comment by mzorz** [comment]
> Let me know what you think about it. Either case I'd suggest merging this issue and creating a new issue with a comment that this PR needs to be reverted and a proper solution implemented.

Sounds good

> Update: One more thing I just realized. The proposed solution might not be actually feasible. The MediaUploadModel is hidden in FluxC so I'm not sure how much changes we'd need to make. That's probably the main reason why the author decided to add the "localPostId" into the MediaModel.

It'll be a longer path but it's still the right path so, nice that you documented the finding here.

> Yep, the fix makes sense so I'll merge this and keep the issue open if it's ok for you.

As discussed elsewhere, may I suggest we also add a comment in code, to make sense of why the PostId is checked there with this addition? Otherwise the code intent becomes less clear (as a Media is site-wide, if we only read the code to see it also checks postId makes future selves wonder why)

**Comment by maxme** [comment]
> I'm not able to reproduce your issue. However, I've tried to remove my change an it fails in 100% cases. When I run the code with the change it works for me. So perhaps, there is another issue which results in the same behavior 🤷‍♂.

Yep, the fix makes sense so I'll merge this and keep the issue open if it's ok for you.

**Comment by malinajirka** [comment]
Thank you both!

I've added a comment in https://github.com/wordpress-mobile/WordPress-Android/pull/10204/commits/450283c0518cd2505cea240c0b5d3709399bc532 and I created an issue for the proper fix https://github.com/wordpress-mobile/WordPress-Android/issues/10210.

**Pull request merged**
