### PR TITLE
Show visitors over views in the overview usecase

### LINKED ISSUE #9028: Stats: Display Visitors Over Views in Stats Graph
Some people miss seeing the number of visitors to their sites when viewing the stats graph within the app. The number of visitors used to display in a darker colour against the number of views. This is still the case in Calypso, but not with the refreshed Android stats.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9028 
This PR adds adds the visitors as an overlay to the Overview block. Now when the user has `Views` selected, there is an overlapping bar in dark blue color that represents the visitors. We've also added a legend that explains it. The difference is visible even when highlighted. The legend is not visible when other types (Visitors/Likes/Comments) are selected.

To test:
* Open Stats - Days/Weeks/Months/Years
* Select Views as the type in the Overview block
* There are a dark overlapping bars that display visitors over views
* There is a legend visible that explains the dark bars
* Select Visitors/Likes/Comments
* Notice that the dark bars are gone
* Notice that the legend is also gone

screenshot_1550506126

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks great @planarvoid thanks!

Two small things:

- Let's change the colour of the legend label to `grey_darken_20`
- It appears the font weight of the tab labels "views, visitors, likes, comments" were not changed to regular.

I'd also be great to see the chart + legend with the big number we added if possible.

**Review by 0nko — APPROVED** [review]
This looks great, @planarvoid! Just one small thing I noticed - when you switch from Views to a different tab, the chart doesn't seem to have any smooth transition (it does going the other way to Views and between other tabs).

**Comment by planarvoid** [comment]
@0nko  yep, this is the issue we were facing with the double animation of the nested recycler view. It's described in a comment here - `org.wordpress.android.ui.stats.refresh.lists.sections.BlockListAdapter`. I think I might give it another try but basically the issue is that Android doesn't animate both the recycler views. The outer one is changing the size of a block and the inner one is adding an item to the block. We can animate either the outer or the inner change. Animating the outer change looks good when adding an item, when we're removing an item, it doesn't.

**Comment by planarvoid** [comment]
hey @SylvesterWilmott , thanks for checking 👍 
> Let's change the colour of the legend label to `grey_darken_20`
done
> It appears the font weight of the tab labels "views, visitors, likes, comments" were not changed to regular.
Fixed
> I'd also be great to see the chart + legend with the big number we added if possible.
It's two separate branches at the moment. Once one of them is merged, you'll see the combination on the other PR

**Comment by planarvoid** [comment]
@SylvesterWilmott I've updated the screenshot so now you can see the big value above the legend. Let me know what you think 👍

**Comment by SylvesterWilmott** [comment]
Thanks @planarvoid . This looks good!

**Review by 0nko — APPROVED** [review]
:shipit: after the conflicts are resolved.

**Comment by SylvesterWilmott** [comment]
One minor thing, can we just add an additional 8dp margin to the bottom of the chart?

**Comment by loremattei** [comment]
Hey! I'm moving this one to 11.9 since 11.8 has been cut. If it has to land 11.8, please feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by planarvoid** [comment]
@SylvesterWilmott I've implemented your suggestions and updated the screenshot 👍

**Pull request merged**
