### PR TITLE
Fix/9905 crash inflate exception binary xml file line

### PR DESCRIPTION
**Pull request by marecar3**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/9905

**The main approach** for a potential fix is to increment `android material library` from `1.0.0` to `1.1.0-rc01`. 

Reason for that was because the codebase from the library was much improved. 

They changed a logic around crashing line from old release and general logic how drawables can be set. https://github.com/material-components/material-components-android/blob/cd59e98f7e2185ddb075ff0fc91f29765d562968/lib/java/com/google/android/material/textfield/TextInputLayout.java#L344 
(log -> https://sentry.io/share/issue/9eaadccac3be4c259943d72c46427792/). 

Thanks to @mzorz comment 👉 https://github.com/wordpress-mobile/WordPress-Android/issues/9905#issuecomment-514213827 I got inspired to make one more step in this fix.

**The second approach** is to use our own [xml](https://github.com/wordpress-mobile/WordPress-Android/commit/0f545724a56503906d3db9ab493a91ff4986bb21) which represents show/hide password icon in order to avoid a potential crash if icon can't be found in runtime.

**Note:** The new version of `android material library` forced some compile time issues : 

Screen Shot 2019-07-23 at 3 43 16 PM

⬆️ this was resolved with adding `!!` and as I am not experienced in Kotlin, if someone has some better approach I am open for suggestions.

Screen Shot 2019-07-23 at 3 44 25 PM

**To test:**

It's very hard to reproduce crash from the logs. However, one should check for potential regressions. 

In order to achieve that one should open and check every screen where `TextInputLayout` or any other component from `material` library is used. Especially`Enter your WordPress password` screen should be checked, where password visibility icon (show/hide password) shod work as before (expected).

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by planarvoid** [comment]
> ... this was resolved with adding !! and as I am not experienced in Kotlin, if someone has some better approach I am open for suggestions.

I think you're keeping the previous functionality by this approach (it would've crashed even before if the `fragmentManager` were null). 

If you wanna add a non-null check, you can do something like this:
```
fragmentManager?.let { nonNullFragmentManager -> 
      dialog.show(nonNullFragmentManager, it)
}
```
I'm not sure it's worth the extra effort

**Comment by mzorz** [comment]
> I think you're keeping the previous functionality by this approach (it would've crashed even before if the fragmentManager were null).

Exactly - I think Marko's code in that regard looks ok as is, as not having a non-null FragmentManager at any point is probably good to let it crash

**Comment by hypest** [comment]
The material library is now at version `1.1.0-beta01` ([link](https://mvnrepository.com/artifact/com.google.android.material/material/1.1.0-beta01)). It'd be good to upgrade this PR to that to test it, but still not merge it until the library reaches a non alpha-beta release state.

**Comment by marecar3** [comment]
Thanks, @hypest will update it!

**Comment by khaykov** [comment]
Just FYI, I also have a PR up for a switch to the material library #10587
There are couple of issues with a release build, that hopefully could be fixed when the Gradle update in #10583 is done.

**Comment by marecar3** [comment]
>Just FYI, I also have a PR up for a switch to the material library #10587
There are couple of issues with a release build, that hopefully could be fixed when the Gradle update in #10583 is done.

Thanks @khaykov !

**Comment by khaykov** [comment]
Some additional info - we are using the beta version of the material components lib in `feature/material-theme` branch. It has some in-progress Dark Theme stuff, and might not be ready to be merged into develop branch when the stable milestone of components library is released, so we might still want to use this PR to update the library.

**Comment by malinajirka** [comment]
@marecar3 I might not have a full context here. However, I'm wondering if we should still consider going with the second approach considering the material design library is not released yet. 
```
The second approach is to use our own xml which represents show/hide password icon in order to avoid a potential crash if icon can't be found in runtime.
```
The app crashed over 30k since this PR was opened. I feel like it's especially important to fix this ASAP because it's crashing during the login flow - my guess would be that a huge percentage of the users will simply uninstall the app when it crashes during login.

Wdyt?

**Comment by marecar3** [comment]
> @marecar3 I might not have a full context here. However, I'm wondering if we should still consider going with the second approach considering the material design library is not released yet.
> 
> ```
> The second approach is to use our own xml which represents show/hide password icon in order to avoid a potential crash if icon can't be found in runtime.
> ```
> 
> The app crashed over 30k times since this PR was opened. I feel like it's especially important to fix this ASAP because it's crashing during the login flow - my guess would be that a huge percentage of the users will simply uninstall the app when it crashes during login.
> 
> Wdyt?

Hey @malinajirka!

Sorry for the late response here. I started to work on this was again, so still investigating what could be the best approach. Thanks for sharing your thoughts!

**Comment by designsimply** [comment]
<sup>(internal reference: paqN3M-7F-p2)</sup>

**Comment by designsimply** [comment]
The blocker here is a decisions is needed about whether or not to use `material-components-android` `v1.1.0-beta02` in production because it may help solve the crash noted at https://github.com/wordpress-mobile/WordPress-Android/issues/9905 and because it's necessary for Dark Mode.

<sup>(internal reference: paqN3M-7F-p2)</sup>

@maxme can you help us with a final decision on this one?

**Comment by maxme** [comment]
The good news, there is an https://github.com/material-components/material-components-android/releases/tag/1.1.0-rc01

FWIW, we already used android beta version support libraries in production. I think we never had any issue specific to that, and we definitely got issues with production ready support libraries.

So I'd say: upgrade to rc1 and :shipit:

**Comment by marecar3** [comment]
> The good news, there is a release candidate for 1.1.0 https://github.com/material-components/material-components-android/releases/tag/1.1.0-rc01
> 
> FWIW, we already used android beta version support libraries in production. I think we never had any issue specific to that, and we definitely got issues with production ready support libraries.
> 
> So I'd say: upgrade to rc1 and :shipit:

They felt that we need RC 💯 
Thanks a lot, @maxme for pointing to this one.

@maxme @designsimply I have updated this PR and now it's using: `1.1.0-rc01`

Hey @khaykov, maybe you can do the same on`material-theme` PR, WDYT?

**Comment by malinajirka** [comment]
Thanks @marecar3! I've reviewed the code and the changes looks good over all. I still have one  question though :). Do I understand it correctly, that we are implementing both the approaches you mentioned in the PR description (`The main approach`, `The second approach`) ? I though the idea was to wait for the design library update and see if it fixes the issue before we implement another workaround which might be unnecessary.

**Comment by marecar3** [comment]
> Thanks @marecar3! I've reviewed the code and the changes looks good over all. I still have one question though :). Do I understand it correctly, that we are implementing both the approaches you mentioned in the PR description (`The main approach`, `The second approach`) ? I though the idea was to wait for the design library update and see if it fixes the issue before we implement another workaround which might be unnecessary.

Hey @malinajirka,
That's a good question! 

My idea here was to use both approaches as we can't reproduce this issue, so I wanted to introduce a solution that has a high chance of solving this crash.

First - `1.1.0-rc1` version of the app has this line of code: https://github.com/material-components/material-components-android/blob/267e299a4ea4c23671af679d7ad3d7fbca4c51e5/lib/java/com/google/android/material/textfield/TextInputLayout.java#L677
which won't let their code to set drawable for password toggle.

Second - The above approach will allow us to set or own drawable selector: https://github.com/wordpress-mobile/WordPress-Android/pull/10279/files#diff-91ccf1392cbaf25d3589aae6f8c92245R118

With those two steps, we will be sure that:
1. Their code won't set bad drawable
2. We will set our own drawable selector.

Let me know what do you think.

**Comment by malinajirka** [comment]
>My idea here was to use both approaches as we can't reproduce this issue, so I wanted to introduce a solution that has a high chance of solving this crash.

Thanks for the clarification! ;) I'd personally prefer to release the second approach after we know for sure it's needed, but I'm fine with this solution as well - especially since it's quite a common crash. One thing we might want to consider is vectorizing the images so we don't unnecessarily increase the size of the APK. 


I have done tons of tests. I found a bug which seems a bit weird and a bit disturbing. I've tested `develop` and it doesn't happen there. It seems Google changed conditions when `onSaveInstanceState` is being invoked.

1. Open LoginEmailPassword screen
2. Enter password
3. Rotate your screen twice
4. Boom

SideNote: It seems the OS is trying to invoke `onSaveInstanceState` on `LoginMagicLinkRequestFragment` even though its UI hasn't been even created since the last rotation.

```
2020-01-09 11:02:39.133 4085-4085/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 4085
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
        at org.wordpress.android.login.LoginMagicLinkRequestFragment.onSaveInstanceState(LoginMagicLinkRequestFragment.java:246)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
        at org.wordpress.android.ui.accounts.LoginActivity.onSaveInstanceState(LoginActivity.java:176)
        at android.app.Activity.performSaveInstanceState(Activity.java:1549)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4809)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4157)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4757)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by marecar3** [comment]
> > My idea here was to use both approaches as we can't reproduce this issue, so I wanted to introduce a solution that has a high chance of solving this crash.
> 
> Thanks for the clarification! ;) I'd personally prefer to release the second approach after we know for sure it's needed, but I'm fine with this solution as well - especially since it's quite a common crash. One thing we might want to consider is vectorizing the images so we don't unnecessarily increase the size of the APK (but we can do that in another PR in the next release).
> 
> I have done tons of tests. I found a bug which seems a bit weird and a bit disturbing. I've tested `develop` and it doesn't happen there. It seems Google changed conditions when `onSaveInstanceState` is being invoked.
> 
> 1. Open LoginEmailPassword screen
> 2. Enter password
> 3. Rotate your screen twice
> 4. Boom
> 
> SideNote: It seems the OS is trying to invoke `onSaveInstanceState` on `LoginMagicLinkRequestFragment` even though its UI hasn't been even created since the last rotation.
> 
> ```
> 2020-01-09 11:02:39.133 4085-4085/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.wordpress.android.beta, PID: 4085
>     java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
>         at org.wordpress.android.login.LoginMagicLinkRequestFragment.onSaveInstanceState(LoginMagicLinkRequestFragment.java:246)
>         at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
>         at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
>         at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
>         at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
>         at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
>         at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
>         at org.wordpress.android.ui.accounts.LoginActivity.onSaveInstanceState(LoginActivity.java:176)
>         at android.app.Activity.performSaveInstanceState(Activity.java:1549)
>         at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
>         at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4809)
>         at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4157)
>         at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4757)
>         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
>         at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```

Hey, @khaykov probably you want to be interested in this one also as the same issue can be reproduced on `material-theme` branch. I have raised an issue on Android tracker: https://issuetracker.google.com/issues/147480935, but let us know if you have some ideas about this. Thanks.

**Comment by khaykov** [comment]
I can confirm that the bug was introduced in appcompat 1.1.0 and still exist in`1.2.0-alpha01 `and in the latest `1.2.0-SNAPSHOT`

**Comment by marecar3** [comment]
Closing this one in favor of https://github.com/wordpress-mobile/WordPress-Android/pull/11172

**Pull request closed without merging**
