### PR TITLE
Stats - 2-columns layout on tablets

### LINKED ISSUE #2764: Improve UI on tablets
The web version of Stats has introduced a 2-columns layout on desktop, and large mobile screen.

We need to experimenting it, and check if replicable on this native app, or add a padding to the left and right. The latter is the solution used on all other app's screens.

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR introduces the 2-columns layout on tablet with 720DP or more, bringing the mobile app in par with the mobile version of Calypso Stats. Below is a detailed recap of what we're showing at different screen sizes/densities.

<b>Devices with 720DP or more</b>
Barchart height is 200DP
Landscape ---> 15 items in the graph.
Portrait ---> 10 items in the graph.

<b>Devices with 600DP or more</b>
Barchart height is 128DP (*default as previous)
Landscape & Portrait ---> 10 items in the graph.

<b>Devices less than 600DP</b>
Barchart height is 128DP (*default as previous)
Landscape & Portrait ---> 7 items in the graph.

Designer and developer review is needed. 
@isaackeyet @jancavan 

/cc @astralbodies 
Fix #2764

### CODE REVIEW

**Comment by jancavan** [comment]
@daniloercoli Two-columns looks good, great job! One minor comment - the page headings are a bit small, they're about the same size as the module headings:

screenshot 2015-07-10 11 03 26

Can they be slightly bigger?
screenshot 2015-07-10 11 03 38

@isaackeyet do you have additional feedback for 2-columns?

**Comment by daniloercoli** [comment]
@jancavan - I made the label a bit larger. Moved it from "medium" to "large" size. 

OLD:
screen shot 2015-07-11 at 11 05 02


NEW:

screen shot 2015-07-11 at 11 09 42

**Comment by jancavan** [comment]
@daniloercoli the Date heading looks good. Is "Other Recent Stats" the same size? If not, can we please make it large too?

**Comment by daniloercoli** [comment]
Sorry, I forgot the change the size of that label. I've updated the size, and now the branch is ready to be reviewed by a developer.

**Comment by tonyr59h** [comment]
Looks great! :shipit:

**Comment by astralbodies** [comment]
Did we miss the review by @isaackeyet?

**Comment by tonyr59h** [comment]
Good call @astralbodies, I pinged him on Slack about it. Thanks :)

**Comment by isaackeyet** [comment]
@astralbodies @tonyr59h it looks like Jan reviewed this one. I think only one designer sign-off is needed :P

**Comment by astralbodies** [comment]
Awesome - just making sure :grin:

**Pull request merged**
