### PR TITLE
Fix an issue with self hosted sites and default categories

### PR DESCRIPTION
**Pull request by maxme**
Fix an issue with self hosted sites and default categories

### CODE REVIEW

**Comment by aforcier** [comment]
Confirming that this fixes the issue where we'd get an 'invalid term' error when publishing to a self-hosted site before `FETCH_CATEGORIES` finished processing when the post was opened for editing.

However, as we discussed, it looks like the default values for WP.com/Jetpack sites aren't respected unless the user first visits Site Settings and makes a selection. The WP.com REST API is more resilient than XML-RPC and will happily accept a `0` category and replace it with the default category server-side. For the post format it looks like the app will default to `standard` in this situation, which isn't ideal.

Do you want to open a separate issue for that @maxme?

**Comment by maxme** [comment]
> Do you want to open a separate issue for that @maxme?

Yes, that's already the case in 6.9 and previous versions, we're very close to 7.0 release so I won't risk bigger changes.

**Comment by aforcier** [comment]
Opened https://github.com/wordpress-mobile/WordPress-Android/issues/5500.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
