### PR TITLE
Remove locale aware activity

### PR DESCRIPTION
**Pull request by nbradbury**
As a follow up to #21521, this PR removes `LocaleAwareActivity`. There are a lot of files changed in this PR, but this was because we extended `LocaleAwareActivity` in so many places. In this PR, I changed them all to extend `AppCompatActivity`.

Testing steps are the same as the prior PR.

Test 1:

- Run the app on a device using Android 13 or later
- Go to App Settings and tap "Interface language"
- Note that the system dialog for "App Language" appears instead of our own
- Verify changing languages works

Test 2:

- Perform the above with an older device and verify our own language dialog appears and changing languages works

**Note:** There's still quite a bit of cleanup to do related to locale handling (unnecessary functions, etc.), but I wanted to keep this PR dedicated to removing `LocaleAwareActivity`. Cleanup is being addressed in [this draft PR](https://github.com/wordpress-mobile/WordPress-Android/pull/21527).

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ParaskP7 — APPROVED** [review]
👋 @nbradbury !

I have reviewed and tested this PR as per the instructions, everything works as expected, good job! 🌟 

-----

`EXTRAS`

About this [Fixed detekt errors commit](https://github.com/wordpress-mobile/WordPress-Android/pull/21523/commits/18a731a15d048fdf7b1862b0f9943ecd642a540d) and the `TODO: Xyz` comment having its colon (`:`) character [removed](https://github.com/wordpress-mobile/WordPress-Android/pull/21523/commits/18a731a15d048fdf7b1862b0f9943ecd642a540d) just to fixed Detekt complaining, I suggest keeping that colon (`:`) character, otherwise the `TODO Xyz` format is not the expected one. Instead, I suggest adding the `@Suppress("ForbiddenComment")` annotation to suppress this warning.

PS: Not related to this PR, but same applies to:
- `ReaderPostNewViewHolder.loadVideoThumbnail(...)` function (needs to suppress, it being a Kotlin class), and
- `JobServiceId.isJobServiceWithSameParamsPending(...)` method (need not to suppress, it being a Java class).

Them being the only other `TODO` I could find with the colon (`:`) character.

**Comment by nbradbury** [comment]
> I suggest keeping that colon (`:`) character, otherwise the `TODO Xyz` format is not the expected one. Instead, I suggest adding the `@Suppress("ForbiddenComment")` annotation to suppress this warning.

@ParaskP7 Can you elaborate on this? I'm not sure why this would be an improvement.

**Comment by ParaskP7** [comment]
> @ParaskP7 Can you elaborate on this? I'm not sure why this would be an improvement.

Sure @nbradbury , I have a few things on that:
1. Detekt is looking for `TODO: Xyz` and not `TODO Xyz` comments to report on violations ([ForbiddenComment](https://detekt.dev/docs/rules/style/#forbiddencomment)). This rules is supposed to help prevent such comments to enter the the codebase, and only be used during development.
2. From a quick search, the JP/WPAndroid codebase is mostly using `TODO: Xyz`, instead of `TODO Xyz`, so this helps with keeping some consistency.
3. I also personally prefer to use `TODO: Xyz` over `TODO Xyz`, because the colon (`:`) helps with creating a "correct" sentence, me starting with a `TODO Xyz`, `FIXME Xyz`, etc, feels to me a bit off. However, I understand this is totally a personal preference thing, and me getting used to this, over anything else.

**Pull request merged**
