### PR TITLE
Revert targetSdk to 33

### PR DESCRIPTION
**Pull request by irfano**
This reverts the `targetSdk` to 33. Because we found two more services (`SiteCreationService` and [LoginWpcomService](https://href.li/?https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/trunk/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java)) that extends `AutoForeground` and calls `startForeground()`. Since they call `startForeground()` these services are also foreground services and they need `foregroundServiceType`. Currently, we set service type only for [UploadService and MediaDeleteService](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/AndroidManifest.xml#L833-L842).

Further discussion: pcdRpT-5fy-p2#comment-10425

-----

## To Test:

No need to test. This PR reverts targetSdk to the version that is currently used in the store version.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - I didn't add any test since this only revert the targetSdk.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/289">25.3</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by notandyvee — APPROVED** [review]
Clean revert. Thanks for this @irfano 🙏🏻

**Comment by nbradbury** [comment]
Just a note that when we do tackle the update to Android 14, on Upside Down Cake and above we need to call `ServiceCompat.startService` with a [foreground service type](https://developer.android.com/about/versions/14/changes/fgs-types-required#include-fgs-type-runtime). From a quick glance at our code, we may only need to be concerned about that for `UploadService`.

**Comment by irfano** [comment]
@nbradbury, we can use `ServiceCompat` only if we pass the foreground service type in the `startService()` call.  

> If the foreground service type is not specified in the call, the type defaults to the values defined in the manifest.
> \- https://developer.android.com/about/versions/14/changes/fgs-types-required#include-fgs-type-runtime

I think we don't need to pass the foreground service type in the `startService()` call since they're already defined in the AndroidManifest.

**Comment by nbradbury** [comment]
We can _probably_ hold off merging this since #21059 addresses the missing services and other Android 14 requirements.

**Comment by oguzkocer** [comment]
This was directly reverted in `release/25.2`.

**Pull request closed without merging**
