### PR TITLE
[Gutenberg] Use Hermes bytecode

### PR DESCRIPTION
**Pull request by hypest**
This PR is another attempt after https://github.com/wordpress-mobile/WordPress-Android/pull/11436

If it proves more successful I will close the other one.

Gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2780

**No need to merge this PR per se as it's practically only bumps the gb-mobile hash; the improvements will be included anyway when the gb-mobile side PRs merge.**

To test:
No special testing other than all operations should look and feel faster.
One easy to spot improvement (I guess) is to start a new post and notice how much faster the editor comes online.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mchowning — APPROVED** [review]
This is working great! 🙇  Thank you @hypest !

Spent a fair bit of time testing this with `Vanilla`, `Jalapeno`, and `Wasabi` builds (including a `VanillaRelease` build). I tried to hit every flow I could think of and everything appears to be working great. 👍

**Comment by mchowning** [comment]
:wave: @hypest ! I've merged the gb and gb-mobile PRs, but I haven't merged this one because you said:

> No need to merge this PR per se as it's practically only bumps the gb-mobile hash; the improvements will be included anyway when the gb-mobile side PRs merge.

I'm not sure exactly what you mean when you say "the improvements will be included anyway when the gb-mobile side PRs merge", would you mind expanding on that a bit just so I can understand a bit better?

**Comment by hypest** [comment]
> I'm not sure exactly what you mean when you say "the improvements will be included anyway when the gb-mobile side PRs merge", would you mind expanding on that a bit just so I can understand a bit better?

Hey @mchowning, ah, sorry. I mean that the changes/bump will be picked up by the normal editor release process. If there was a need for WPAndroid side changes beyond the hash bump then we'd need to merge them together with the gb-mobile PRs.

At this stage, since the gb-mobile/gutenberg PRs got merged (🎉🙇‍♂️), the upcoming Monday editor cut will pick them up very soon.

**Comment by mchowning** [comment]
>  I mean that the changes/bump will be picked up by the normal editor release process... [S]ince the gb-mobile/gutenberg PRs got merged (🎉🙇‍♂️), the upcoming Monday editor cut will pick them up very soon.

Ah, that makes sense. My inclination would be to still merge this PR to ensure (😉) that the rest of the WPAndroid devs are exposed to these changes while our release process is pending next week. In other words, although these changes will get picked up by our release branch, they won't make it to WPAndroid's `develop` branch until the end of next week, right? I'd hate for the non-gutenberg WPAndroid devs to discover an issue at that point in time. Maybe I'm missing something though, let me know what you think.

**Comment by mchowning** [comment]
I don't feel that strongly one or the other about merging this, but in case we decide we do want to merge it I went ahead and pushed an update (eef44b5) to this branching bringing in the post-hermes-merge gutenberg-mobile submodule hash.

**Comment by hypest** [comment]
v1.41.0 of the gb-mobile editor has been cut and the WPAndroid PR for that is including the Hermes bytecode work so, it's safe to close this at this stage. Thanks for the review and update Matt!

**Pull request closed without merging**
