### PR TITLE
Updating support library to 23.4

### LINKED ISSUE #3791: Upgrade to support library v23.3 and use VectorDrawableCompat
We must upgrade to v23.2 and add `vectorDrawables.useSupportLibrary = true` in our gradle config, also check that PNGs aren't generated anymore and make sure that works on all API levels.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #3791 

Needs review: @maxme

### CODE REVIEW

**Comment by kwonye** [comment]
@maxme added the vector drawable support in this PR as it's easier to track the change here.

**Comment by kwonye** [comment]
ping @maxme

**Comment by maxme** [comment]
I got a crash on 4.1.1 device: `android.view.InflateException: Binary XML file line #134: Error inflating class <unknown>`

**Comment by maxme** [comment]
I'll have a look at that later, but I guess we must use `app:srcCompat` and we should probably replace `.setImageDrawable()` calls.

http://android-developers.blogspot.fr/2016/02/android-support-library-232.html
> Using AppCompat and app:srcCompat is the most foolproof method of integrating vector drawables into your app.

**Comment by maxme** [comment]
`CONTRIBUTING.md` needs a refresh: https://github.com/wordpress-mobile/WordPress-Android/issues/3791#issuecomment-188985354

**Comment by kwonye** [comment]
> I got a crash on 4.1.1 emulator: android.view.InflateException: Binary XML file line #134: Error inflating class <unknown>

@maxme, I was unable to repro the crash. Please test again with latest changes.

All `android:src` is now `app:srcCompat` and with a run-through of the app, everything is working fine. 

Also, all `Activity` classes had to be changed to `AppCompatActivity`.

> CONTRIBUTING.md needs a refresh: #3791 (comment)

Refreshed. Feel free to modify further as you see fit.

**Comment by kwonye** [comment]
Lint error: `MissingPrefix: Missing Android XML namespace`

Marking as `Not Ready for Review` until fixed (hopefully in the next gradle/AS update)

**Comment by maxme** [comment]
> Lint error: MissingPrefix: Missing Android XML namespace

We have 2 lint errors in the editor sub project only. We probably have to add the `vectorDrawables.useSupportLibrary = true` option to the corresponding gradle file.

**Comment by kwonye** [comment]
> We have 2 lint errors in the editor sub project only. We probably have to add the vectorDrawables.useSupportLibrary = true option to the corresponding gradle file.

Hmm, I'm seeing this, @maxme: 
screen shot 2016-03-22 at 6 39 01 pm

**Comment by maxme** [comment]
Ah right, lint was faiiling on the editor sub project. I tried to update to `buildToolsVersion "24.0.0-rc2"` but got the same problem. 

https://code.google.com/p/android/issues/detail?id=201790

**Comment by kwonye** [comment]
@maxme, with b541fbf I believe this is ready to merge. 

As much as I hate editing the lint file, I believe it is specific enough to be ok. It only ignores `app` prefixes in `Image*` classes.

**Comment by maxme** [comment]
TIL you can ignore matching error messages. This looks safe since if the namespace declaration is missing, the build will fail.

Lint is still broken, you must add the same trick in the editor `lint.xml` file.

**Comment by kwonye** [comment]
> TIL you can ignore matching error messages

I know right? I felt so happy/dirty at the same time. 

> Lint is still broken, you must add the same trick in the editor lint.xml file.

Thanks, addressed.

**Comment by maxme** [comment]
Apparently 23.3.0 brings new bugs :(

screenshot-2016-04-12_10 57 23 741

Maybe related to https://code.google.com/p/android/issues/detail?id=206227&q=23.3.&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by kwonye** [comment]
@maxme I fixed the broken images in `SignInActivity` by changing it to inherit from `AppCompatActivity` 😭

(It's always bugged me why the images didn't work only in `SignInActivity`)

I verified there are no other classes that inherit from `FragmentActivity`. I also looked around the app to see if any other resources were missing and couldn't find any. I believe this is ready to merge.

**Comment by maxme** [comment]
I had this crash on a Genymotion 4.1.1 when the new editor promo header tried to show up:

```
05-17 09:22:07.035 1948-1948/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
android.content.res.Resources$NotFoundException: File res/drawable/new_editor_promo_header.xml from drawable resource ID #0x7f0201f1
    at android.content.res.Resources.loadDrawable(Resources.java:1918)
    at android.content.res.Resources.getDrawable(Resources.java:659)
    at org.wordpress.android.ui.posts.PromoDialog.onViewCreated(PromoDialog.java:59)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:843)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
    at android.app.BackStackRecord.run(BackStackRecord.java:635)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
    at android.content.res.Resources.loadDrawable(Resources.java:1915)
    at android.content.res.Resources.getDrawable(Resources.java:659) 
    at org.wordpress.android.ui.posts.PromoDialog.onViewCreated(PromoDialog.java:59) 
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:843) 
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035) 
    at android.app.BackStackRecord.run(BackStackRecord.java:635) 
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397) 
    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426) 
    at android.os.Handler.handleCallback(Handler.java:615) 
    at android.os.Handler.dispatchMessage(Handler.java:92) 
    at android.os.Looper.loop(Looper.java:137) 
    at android.app.ActivityThread.main(ActivityThread.java:4745) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
    at dalvik.system.NativeStart.main(Native Method) 
```

I've checked the xml file, it seems correct, I'll try to reimport it from svg and try again.

**Comment by maxme** [comment]
> I've checked the xml file, it seems correct, I'll try to reimport it from svg and try again.

I actually think it's a `setImageDrawable` issue with the wrong drawable.

**Comment by maxme** [comment]
Ok I fixed it, but I'll need the vector drawable version of `stats_widget_promo_header`

**Comment by kwonye** [comment]
Thanks for all the updates @maxme 👍

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
