### PR TITLE
[Gutenberg] Set and reference heading anchors

### PR DESCRIPTION
**Pull request by dcalhoun**
Fixes wordpress-mobile/gutenberg-mobile#15567

- **Guntenberg:** WordPress/gutenberg#27935
- **Guntenberg Mobile:** wordpress-mobile/gutenberg-mobile#2947
- **WordPress iOS:** wordpress-mobile/WordPress-iOS#15567

To test: Test plan in Gutenberg PR.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dcalhoun** [comment]
Closing as I learned this PR is unnecessary for merely making changes to Gutenberg.

**Comment by hypest** [comment]
> this PR is unnecessary for merely making changes to Gutenberg.

👋 David. It's true that opening PRs in the WP apps or gutenberg-mobile repos for Gutenberg-side only changes is not strictly necessary, mainly because those changes will get brought in those repos via the mobile editor release process.

That said, it's a good practice to try and bring the changes into the repos as soon as possible. One gotcha for the main app repos is that we avoid merging updates during the editor freeze week (the second week of each sprint) to avoid bringing in changes that haven't gone through the scrutinizing process of the editor release.

**Comment by dcalhoun** [comment]
> That said, it's a good practice to try and bring the changes into the repos as soon as possible. One gotcha for the main app repos is that we avoid merging updates during the editor freeze week (the second week of each sprint) to avoid bringing in changes that haven't gone through the scrutinizing process of the editor release.

@hypest thanks for the context. So, are you saying I _should_ open this type of PR for every Gutenberg change (provided it's not merged during freeze week)? Should I reopen this PR and the sibling wordpress-mobile/WordPress-iOS#15567?

**Comment by hypest** [comment]
I understand that the changes are not affecting the RN bridge interface so, no particular need to reinstate the PRs 👍
(By the way, relevant internal post ref: `p9ugOq-1bP-p2`)

**Pull request closed without merging**
