### PR TITLE
Use `trackWithSiteDetails` to track media upload events

### PR DESCRIPTION
**Pull request by jhnstn**
This uses `AnalyticsUtils.trackWithSiteDetails` to track media upload events so that we can better diagnosis failure events.

-----

## To Test:

- Add a some media to a blog via the editor and via the media library 
- Notice that the media related tracking log messages now include `site_type`, `blog_id`, and `is_jetpack` properties 

-----

## Regression Notes

1. Potential unintended areas of impact

    Change in metric tracking 

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Verified that only new keys are added to the tracking event
    - Verified that the event ids are unchanged 

3. What automated tests I added (or what prevented me from doing so)

    No additional test coverage is needed.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by AjeshRPai — APPROVED** [review]
Tested the PR by uploading Media through editor and library. Tracking events have site details 👍🏼

**Comment by SiobhyB** [comment]
@jhnstn, @AjeshRPai, I tested the following events with the installable build from this PR, but am not seeing a blog ID associated with any of them in Tracks:

- `jpandroid_editor_upload_media_failed`
- `jpandroid_media_service_upload_started`
- `jpandroid_media_service_upload_response_error`
- `jpandroid_media_service_upload_response_ok`

Are you seeing something different, or is there something else I'm missing here? I tested on a simple .com site and used the live view in Tracks to check the details associated with the events.

**Comment by AjeshRPai** [comment]
Hey @SiobhyB 

I am not sure whats wrong here . I tested this change  by running this branch in physical testing device. 

Before this change - tracking info log

```
🔵 Tracked: media_service_upload_response_ok, Properties: {"ext":"jpg","age_ms":4316,"bytes":1130364,"mime":"image\/jpeg","megapixels":12}
🔵 Tracked: media_service_upload_started, Properties: {"ext":"jpg","age_ms":4345,"bytes":1130364,"mime":"image\/jpeg","megapixels":12}
```

After this change - tracking log 
```
🔵 Tracked: media_service_upload_response_ok, Properties: {"ext":"jpg","blog_id":197876910,"site_type":"blog","age_ms":3518,"bytes":238604,"mime":"image\/jpeg","megapixels":3,"is_jetpack":true}
🔵 Tracked: media_service_upload_started, Properties: {"ext":"jpg","blog_id":197876910,"site_type":"blog","age_ms":3553,"bytes":238604,"mime":"image\/jpeg","megapixels":3,"is_jetpack":true}
```

So this change looks fine to me. I am sorry if I made any mistake in testing or reviewing this change. 

@jhnstn  Also, checking the track events for media - query param - `jpandroid_media_service` I can see that most events are not registered. I think registering the events and may be adding these new parameters to the event will fix what @SiobhyB  is seeing in tracks. 

Useful link on how to register and add parameters to an event here - p1689686654875529-slack-C04PWEZSYFL

**Comment by SiobhyB** [comment]
@AjeshRPai, thank you for the response! The `is_jetpack` and `site_type` props have _always_ shown up for these events in Tracks. I assume they're being added elsewhere in the code, and it's likely not necessary to add them again here. 

As for the `blog_id`, I'm not sure why it's still not showing up for me with the changes from this PR, but don't think registering the events would make a difference. For the companion iOS PR at https://github.com/wordpress-mobile/WordPress-iOS/pull/22328, I was able to see the blog ID showing up for the events, even without going through the steps to register them.

**Comment by jhnstn** [comment]
@SiobhyB  I was able to see the new properties in Tracks when using a local build from trunk. Not sure why they were not showing up for you. Doesn't look like it's an issue with event registration since the iOS events you mentioned are also unregistered.
I also noticed that `is_jetpack` is slightly different from the existing `user_info_jetpack_user` . The former checks if the site is a [connected Jetpack site](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java#L264).

**Pull request merged**
