### PR TITLE
[My Site Dashboard] Compose cards reusable toolbar

### PR DESCRIPTION
**Pull request by thomashorta**
I am working on another Dashboard card using Compose and realized that the 2 existing Compose cards are currently repeating a lot of code regarding the "Toolbar" part with the Context Menu. Besides that, the toolbar section of those Compose cards does not match visually with the existing XML/Android View cards, causing icon misalignment and different title paddings.

This PRs aims at creating a reusable composable `MySiteCardToolbar` that can be used in My Site Dashboard cards and make them fit in a bit better with the other existing cards. It also makes it easier to create the Context Menu items and callbacks.

The 2 cards that were refactored to use this new Toolbar are:
- `DomainTransferCard`
- `BlazeCampaignsCard`

I added @ravishanker and @zwarm because of the cards that I touched, but don't worry if you can't review at this time.

Before | After
--- | ---
image | image

-----

### `DomainTransferCard`
1. Install and log into the Jetpack app
2. Go to My Site Dashboard
3. **Verify** the domain transfer card looks correct
4. **Verify** the domain transfer card interactions are working as expected (including context menu)

### `BlazeCampaignsCard`
Pre-requisite: you need to use an account/site that has Blaze Campaigns, so I recommend using the text account mentioned in pe7hp4-nI-p2 to do so.

1. Install and log into the app (with an account/site that has Blaze Campaigns)
2. Go to My Site Dashboard
3. **Verify** the Blaze campaigns card looks correct
4. **Verify** the Blaze campaigns card interactions are working as expected (including context menu)

-----

## Regression Notes

1. Potential unintended areas of impact

    - Issue with the interactions on the cards

6. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

7. What automated tests I added (or what prevented me from doing so)

    - Only UI refactor

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by ravishanker — APPROVED** [review]
Thanks for refactoring, and making it reusable. 🚀 

Cards are working as before. 👍

**Comment by RenanLukas** [comment]
Thanks for the PR, @thomashorta 

Definitely not related to your changes, but I wanted to point out that sometimes I'm getting an error in the context of the Blaze card navigation. When I tap the card without any active campaigns:
image

Sometimes it shows the progress state for a long time and eventually this error:
image

**Review by RenanLukas — APPROVED** [review]
Thanks for creating this component! The cards are working as expected and code LGTM :shipit:

**Comment by thomashorta** [comment]
> Thanks for the PR, @thomashorta
> 
> Definitely not related to your changes, but I wanted to point out that sometimes I'm getting an error in the context of the Blaze card navigation.


Good point, I confirmed with a `trunk` build and that happens there as well, so not related to this change, but it would be nice to check what's going on. cc @zwarm

**Pull request merged**
