### PR TITLE
Fix rare image settings crash

### LINKED ISSUE #5669: Crash report on multiple versions: ClassCastException in downloadExternalMedia
```
Fatal Exception: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
       at org.wordpress.android.util.HTTPUtils.setupUrlConnection(HTTPUtils.java:21)
       at org.wordpress.android.editor.Utils.downloadExternalMedia(Utils.java:194)
       at org.wordpress.android.editor.ImageSettingsDialogFragment$4.run(ImageSettingsDialogFragment.java:322)
       at java.lang.Thread.run(Thread.java:818)
```

### LINKED ISSUE #5676: Crash report on many versions: ISE in downloadExternalMedia
```
Fatal Exception: java.lang.IllegalStateException: closed
       at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:174)
       at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:1176)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
       at java.io.InputStream.read(InputStream.java:162)
       at org.wordpress.android.editor.Utils.downloadExternalMedia(Utils.java:216)
       at org.wordpress.android.editor.ImageSettingsDialogFragment$4.run(ImageSettingsDialogFragment.java:322)
       at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5669. An over-ambitious cast was causing a (fairly rare) crash when opening the image settings screen on certain non-stock devices.

Also fixes #5676 by removing `downloadExternalMedia()`.

* Refactored the image settings screen to use an `ImageLoader` to show thumbnails
* Modified the visual editor `WebView` to use the safe `URLConnection` instead of `HTTPUtils`' implementation

### Notes:

1. I'll be disposing of the `HTTPUtils` class in a PR in the `WordPress-Utils-Android` repo - it's not used anywhere else. (https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/13)

2. The Aztec editor uses its own `ImageGetter`, which wraps around an `ImageLoader` - so we're now calling two `setImageLoader`s for Aztec, one from the `EditorFragmentAbstract` and one from `AztecEditorFragment`. This is pretty messy, but I didn't want to make any big changes to Aztec. cc @0nko for your opinion

I thought this was worth adding this crash fix to `7.3`. If we don't make it in time I'll change the base branch.

### To test:
The crash seems to affect specific (non-stock) devices - I haven't been able to reproduce the crash even on a Samsung S3. However, we can confirm that everything is still working as it should in general:

1. In the (hybrid) visual editor and in Aztec, edit an image
2. Confirm that the image thumbnail loads in the image settings screen
3. Try the above for self-hosted, and for a private WP.com site
4. Try uploading images in the (hybrid) visual editor to test the `EditorWebViewAbstract` change

### CODE REVIEW

**Comment by 0nko** [comment]
The problem is that Aztec expects an `ImageGetter` interface implementation. That's why it needs its own setter, which wraps around the WordPress loader. But it seems that the image loader set in `EditorFragmentAbstract` is only used by the legacy editor. Once we get rid of it we can also remove the setter.

**Comment by aforcier** [comment]
> But it seems that the image loader set in EditorFragmentAbstract is only used by the legacy editor. Once we get rid of it we can also remove the setter.

With this changeset Aztec will also need the `ImageLoader`, since it uses the same image settings fragment as the (hybrid) visual editor and has the same bug. But with the overall cleanup we'll do when we drop down to Aztec only, we can maybe refactor the `ImageGetter` to expose a `getImageLoader` method or something, and drop the `EditorFragmentAbstract` method.

I take it though you feel the changes as they are now are okay and we can revisit this later @0nko?

**Comment by 0nko** [comment]
> I take it though you feel the changes as they are now are okay and we can revisit this later @0nko?

Yeah. We can refactor this once we use Aztec as a primary editor.

**Comment by daniloercoli** [comment]
Tested on 2 of my devices and everything seems to work fine on both the current visual editor and Aztec.

We can improve the image settings screen by avoiding loading the full size picture, but use photon and a smaller size. I noticed that loading the settings screen could take a while if your internet connection is laggy or slow.

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
