### PR TITLE
Add A/B test for site intent question

### LINKED ISSUE #15980: [Site Intent Question] A/B Test the site intent question screen
### Description
The site intent question screen should be shown conditionally to A/B test the implementation.
We will use “Local” A/B testing instead of ExPlat to get quicker results.

_Note: All development should be behind [the feature flag `SITE_INTENT_QUESTION`](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)_

<details>
<summary>Notes from previous implementation</summary>

we used a “local” a/b testing [in this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14452). Due to the requirements we had at the time, the implementation is probably more complex than what you might need at the moment, but it should give you a good idea of how things worked under the hood. Just keep in mind that this implementation ended up [causing an issue](https://github.com/wordpress-mobile/WordPress-Android/pull/14478) later on and that the fix we had [wasn’t exactly perfect](https://github.com/wordpress-mobile/WordPress-Android/pull/14478#discussion_r615161836) as well. I’d probably consider [keeping it as simple as the iOS implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/17328/files#diff-dd5d1197f8b51946ef1a85fd4ab79950224beb9abf9b4b20862683671230428d) apparently is.
</details>

#### Definition of Done
* The new screen is shown for the treatment A/B test variation
* The flow remains as is for the control variation
* The flow chosen is tracked in analytics
* The user selection is tracked in analytics. TBD what we would track (probably the vertical id and/or name)
* Tests are added where applicable

### PR DESCRIPTION
**Pull request by antonis**
Fixes #15980

## Description
This PR Adds A/B test for the site intent question screen that splits equally between the control and treatment variations. Specifically:
* [Implements an A/B testing mechanism](https://github.com/wordpress-mobile/WordPress-Android/pull/16128/commits/5542f6fa9f51e9cf79394b421543cd2c851aac56)
   * The implementation is inspired by a [previous PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14452) and a [follow up bug-fix](https://github.com/wordpress-mobile/WordPress-Android/pull/14478) simplified to match [the iOS implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/17328/files#diff-dd5d1197f8b51946ef1a85fd4ab79950224beb9abf9b4b20862683671230428d) of that feature.
</details>

* [Adds the A/B test for site intent question screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16128/commits/7483a425d181811254e153ddbbc40057559b47d8)
* [Tracks analytics for the selected variation](https://github.com/wordpress-mobile/WordPress-Android/pull/16128/commits/efa17407ebb5a5a390ba8ff34998700479397659)

### Feature flag is off
1. [Turn OFF the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)
2. Start the site creation flow
3. **Verify** the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is **NOT** shown
4. **Verify** that **NO** `enhanced_site_creation_intent_question_*` [event are emitted](https://github.com/wordpress-mobile/WordPress-Android/pull/16043)
### Control variation
1. [Turn ON the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)
2. Start the site creation flow
3. **Verify** the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is NOT shown
4. **Verify** that the `enhanced_site_creation_intent_question_experiment, Properties: {"variation":"control"}` event is emitted

<details>
<summary>Control flow recording</summary>

https://user-images.githubusercontent.com/304044/159048503-56d650b6-b728-40e5-ab1d-1e9713c1c5f1.mp4
</details>

### Treatment variation
1. [Turn ON the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)
2. Start the site creation flow
3. **Verify** the the [site intent screen](https://github.com/wordpress-mobile/WordPress-Android/pull/16103) is shown
4. **Verify** that the `enhanced_site_creation_intent_question_experiment, Properties: {"variation":"treatment"}` event is emitted

<details>
<summary>Treatment flow recording</summary>

https://user-images.githubusercontent.com/304044/159048579-134d79fe-51b2-4d48-9b4b-898ba6a56740.mp4
</details>

_Note: One way to change the variation is to create random accounts (like the recordings above) till you achieve the desired. A manual way is to temporarily [reverse the variation on the code](https://github.com/wordpress-mobile/WordPress-Android/pull/16128/files#diff-80b5ec6affb87d12089ee77006d4759f645b66f822dc90df108b5251bad480b0R27) using your current account._

## Regression Notes
1. Potential unintended areas of impact

This change conditionally adds a new step to the site creation flow for users in the Treatment group of the A/B test. We verify that the Control group is unaffected by this change. Also, while this screen is developed, it's behind a feature flag that is OFF by default. We must ensure it stays off until we ship this feature.

3. What I did to test those areas of impact (or what existing automated tests I relied on)

I verified that when the feature flag is OFF, the new screen is not shown, even when the user is in the Treatment group
I verified that when the feature flag is ON, the new screen is not shown, if a user in the Control group

4. What automated tests I added (or what prevented me from doing so)

Added tests validating the correctness of the mechanism with `SiteIntentQuestionABExperimentTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
I added the `[Status] Not Ready for Merge` label since the implemented randomness may make [the rest of the feature implementation](https://github.com/orgs/wordpress-mobile/projects/121/views/1) more difficult.

**Review by ovitrif — APPROVED** [review]
Thank you for implementing this @antonis 🙇‍♂️

I tested all 3 scenarios and they worked as you described in the testing instructions 🎉

- Feature flag is off
- Control variation
- Treatment variation

The code changes LGTM 👍

**Comment by ovitrif** [comment]
> I added the [Status] Not Ready for Merge label since the implemented randomness may make [the rest of the feature implementation](https://github.com/orgs/wordpress-mobile/projects/121/views/1) more difficult.

I'm ok if we merge the PR, since it won't be that difficult to override it for local development:

```patch
diff --git a/WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt b/WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt
index 61ef2f5d29..d71fefb762 100644
--- a/WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt
+++ b/WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt
@@ -18,7 +18,7 @@ class SiteIntentQuestionABExperiment
     private val default = CONTROL
 
     val variant: Variation
-        get() = calculateVariant()
+        get() = TREATMENT // calculateVariant()
 
     private fun calculateVariant(): Variation {
         val variation = if (!accountStore.hasAccessToken()) {

```

Saving the above code to a `local.patch` file in the root project dir & calling `git apply local.patch` should do it 😉

**Comment by antonis** [comment]
Merging now since the feature development is complete

**Pull request merged**
