### PR TITLE
Feature/media browser new filters

### PR DESCRIPTION
**Pull request by nbradbury**
Builds upon #6144 by changing the media filters to match those in Calypso. Previously the filters were ALL / IMAGES / UNATTACHED, now they're ALL / IMAGES / DOCUMENTS / VIDEOS / AUDIO.

after

### CODE REVIEW

**Comment by daniloercoli** [comment]
Empty "no content" message disappears upon rotating the device. https://cloudup.com/cyFVn8aA25O

**Comment by daniloercoli** [comment]
I see no documents in the app, but have some in Calypso. 
screen shot 2017-06-28 at 16 49 21

I bet this is due to pagination....since those PDFs are really old. Should we change the logic to be in par with Calypso?

**Comment by daniloercoli** [comment]
It seems to me that the app does make a call to load more items when you switch to a tab with few items in it. See the video here: https://cloudup.com/cYph6SL7wvk (The first time I went to `Audio` the app called the backend for new items).

Probably because the app thinks it's near the end, make a call to fetch more items:
https://github.com/wordpress-mobile/WordPress-Android/blob/feature/media-browser-new-filters/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java#L228

**Comment by nbradbury** [comment]
> Empty "no content" message disappears upon rotating the device. 

Fixed in 23c7112

**Comment by nbradbury** [comment]
> I bet this is due to pagination....since those PDFs are really old. Should we change the logic to be in par with Calypso?

Oh, yuck. I guess this has been an issue for a long time but it was less likely to happen with the previous set of filters. I think the solution will be to add a partial `mime_type` parameter when requesting media, as documented [here](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/media/), which will require a FluxC change.

**Comment by daniloercoli** [comment]
👍

**Pull request merged**
