### PR TITLE
Jetpack focus:  display an overlay when the app is accessed from a disabled entry point on Phase 4

### LINKED ISSUE #17849: Jetpack Focus: Display an overlay when the app is accessed from a disabled entry point
Ref: p1674713277160309-slack-C04564QS0V7

And collect jetpack_feature_incorrectly_accessed tracking event (shortcut and deep link entry points)

### PR DESCRIPTION
**Pull request by AjeshRPai**
Closes #17849 

## What?
This PR implements The Jetpack feature overlay for phase 4 - shown when you access the deep link and shortcut in phase 4. 

## Why?
Earlier we used to show the Landing page when the user navigates from the deeplink and shortcut on phase 4 without any messaging or overlay, this felt like a bad good User experience since the user expects to be guideded to Stats/Reader. Showing an overlay to the user informing that the features have moved to the user will prompt the user to migrate to the Jetpack app. 

## How?
- We reverted the commits in this PR which removed the Handling of deep links on P4 - https://github.com/wordpress-mobile/WordPress-Android/pull/17750/files
- Implemented the logic to show Phase 4 overlay when navigating from shortcuts with this commit [Adds: logic for showing the overlay in phase 4 for shortcuts](https://github.com/wordpress-mobile/WordPress-Android/pull/17851/commits/3b09c46593d515dcd9af5ef676a8c286371f05f8)
- Adds the tracking logic when accessing the shortcuts, deep link in p4
    -  [Add stats, notifications, and reader when capturing the calling_function](https://github.com/wordpress-mobile/WordPress-Android/pull/17851/commits/47ec312eb048bcb2d757cc4239f2fdd639128a63) , 
    - Add a shortcut name when capturing the calling_function event for tracking logic [Add shortcut name when capturing the calling_function event](https://github.com/wordpress-mobile/WordPress-Android/pull/17851/commits/60c018d00c3204217284deed80d712bf45200131)

## 📹 Screenshots 
lightModePhase4Overlay

### 1. When Phase 4 is not enabled 
- Go to the Wp app 
- Login to app 
- Disable jp_removal_four
- Verify that shortcuts/deep link work as expected 
- Verify that no overlay for p4 is shown and the user is guided to the correct page 

### 2. When Phase 4 is enabled 
- Go to the Wp app 
- Login to app 
- Enable jp_removal_four and Restart the app 
- Verify that shortcuts/deep link work redirects to the home page 
- Verify that an overlay for P4 is shown  
- Check the logs for a jetpack_feature_incorrectly_accessed tracked event with {"calling_function": "deep_link"}
- Check the logs for a remove_feature_overlay_displayed tracked event with {"source": "disabled_entry_point"} 

### 3. Regression testing 
- Follow the testing instructions from the [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17742) 
- Verify that the Migration flows are not affected 

## Regression Notes
1. Potential unintended areas of impact
Migration Overlays or Deeplink overlays are affected 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by zwarm** [comment]
@AjeshRPai - Everything is working as expected. I tested pre and post 4. The overlays are visible upon entry for P4 and not visible < P4. In P4 the user lands on the my site view when deep linking or using a already created shortcut (for stats, notifications). I did not have any issue with the deep linking overlays.

What you had for tracking was fine, I only added the "stats", "notifications" or "reader" prefix

**Comment by AjeshRPai** [comment]
Hey @ovitrif 👋🏼 
Since this change shows an overlay in p4 for deep links, we thought you should be aware of this change. Hence the Ping.  Also, we tested this PR with the test instructions from your Migration [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17742), and we found no regression issues. Please look at this PR if you feel this will affect any other flow or overlay shown. I will look for a 👍🏼 from you before I merge this PR. Please comment if you want me to wait until you review the PR.

**Comment by ovitrif** [comment]
> Hey @ovitrif 👋🏼
> will look for a 👍🏼 from you before I merge this PR. Please comment if you want me to wait until you review the PR.

Hey @AjeshRPai 👋 
Thank you for the ping 🙇 , and many thanks for testing the scenarios from the [Migration PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17742), you rock! 💯 🥇 🏆 

I'll quickly check the code and submit my review 👍

**Review by ovitrif — APPROVED** [review]
Code changes LGTM 🎉 

Thank you for the excellent work on wrangling this @AjeshRPai 👏

**Pull request merged**
