### PR TITLE
Jetpack App (Basics): Update Base Colors

### LINKED ISSUE #14380: Jetpack App (Basics): Update Base Colors
Parent: #14293

This task is based on `pcdRpT-k6-p2#comment-321` where it is described in more details what base color values to use on the Jetpack app:

| Base Color | Light Theme | Dark Theme
-----|-----|-----
colorPrimary|jetpack_green_50 (`#008710`)|jetpack_green_40 (`#069e08`)
colorPrimaryVariant|jetpack_green_40 (`#069e08`)|jetpack_green_50 (`#008710`)
colorSecondary|jetpack_green_50 (`#008710`)|jetpack_green_40 (`#069e08`)
colorSecondaryVariant|jetpack_green_40 (`#069e08`)|jetpack_green_50 (`#008710`)

### PR DESCRIPTION
**Pull request by ParaskP7**
Fixes #14380 

This PR updates the `Jetpack` related base colors based on the latest design feedback.

Screen/Theme | WordPress | Jetpack
-----|-----|-----
Login/Light | wordpress_login_light | jetpack_login_light
Login/Dark | wordpress_login_dark | jetpack_login_dark
My Site/Light | wordpress_my_site_light | jetpack_my_site_light
My Site/Dark | wordpress_my_site_dark | jetpack_my_site_dark

In addition to that, in this PR:
- The `studio colors` where extracted to its own individual `colors_studio_palette.xml` file.
- The `semantic colors` where extracted to its own individual `colors_semantic.xml` file.
- The `translucent colors` where extracted to it own individual `colors_translucent.xml` file.
- The `WordPress` primary and secondary `semantic` base colors where replaced with the `studio colors` blue `primary` ones.
- The `Jetpack` primary and secondary `semantic` base colors where replaced with the `studio colors` jetpack green `primary` ones.

**To Test**
- Build, launch and smoke test the `blue` colors on each product flavor for the `WordPress` dimension:
  - `wordpressVanillaDebug` (Prod)
  - `wordpressWasabiDebug` (Beta)
  - `wordpressJalapenoDebug` (Alpha)
- Build, launch and smoke test the `jetpack green` colors on each product flavor for the `Jetpack` dimension:
  - `jetpackVanillaDebug` (Prod)
  - `jetpackWasabiDebug` (Beta)
  - `jetpackJalapenoDebug` (Alpha)

**Merge Instructions**
- ~~A quick design review by @osullivanchris on the base color changes for the `Jetpack` app.~~ 🟢 
- ~~Remove `Needs Design Review` label.~~ 🟢 
- Merge as normal.

## Regression Notes
1. Potential unintended areas of impact

🟢 

2. What I did to test those areas of impact (or what existing automated tests I relied on)

🟢 

3. What automated tests I added (or what prevented me from doing so)

🟢 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — CHANGES_REQUESTED** [review]
Looks great so far. I will continue using the app to see if other details emerge. Here are a couple specific to colours.

As discussed on slack:

- some native components (e.g. switches and checkboxes) are using a lighter colour than the one we have defined. As you mentioned we might need to change the values here and keep looking for other ones that are 'off'. 
- on light mode, a selected top tab has black text and green underline (e.g. reader/stats). In dark mode, both the text and line are green. Should be white text with green underline. As discussed this exists on WordPress Android too. So we should change on both.

Two for me to look at (I don't know the solution yet):
- pink colour on the notification dot
- stats needs a bit of love

**Review by ashiagr — APPROVED** [review]
Looks great code-wise!

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> Looks great so far. I will continue using the app to see if other details emerge. Here are a couple specific to colours.

Thanks for the thorough review! 🙏 

> some native components (e.g. switches and checkboxes) are using a lighter colour than the one we have defined. As you mentioned we might need to change the values here and keep looking for other ones that are 'off'.

I have created this individual issue to handle this case: #14436

PS: I actually think that it is better to change these values as a separate task to keep this `base colors` task more targeted, without adding any exceptions to it. Wdyt?

> on light mode, a selected top tab has black text and green underline (e.g. reader/stats). In dark mode, both the text and line are green. Should be white text with green underline. As discussed this exists on WordPress Android too. So we should change on both.

I have created this individual issue to handle this case: #14436

> Two for me to look at (I don't know the solution yet):
> - pink colour on the notification dot
> - stats needs a bit of love

🙏

**Comment by osullivanchris** [comment]
> PS: I actually think that it is better to change these values as a separate task to keep this base colors task more targeted, without adding any exceptions to it. Wdyt?

Yep all sounds good to me! Sounds like a good plan of action 😄  thanks for addressing all those

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> Yep all sounds good to me! Sounds like a good plan of action 😄 thanks for addressing all those

Brilliant, I'll merge this PR then and continue with the individual tasks, thanks for the 🟢 light Chris! 🙏

**Pull request merged**
