### PR TITLE
Updates Jetpack banners and badges copy

### PR DESCRIPTION
**Pull request by antonis**
## Description
Updates Jetpack banners and badges copy for consistency (internal ref pcdRpT-5EP-p2)

-----

## To Test:
1. Open the WordPress app from this PR
2. Verify that the copy `Jetpack powered` is displayed in the following screens:
- Activity logs
- Themes
- Social
- People
- Me tab
- App Settings

|Activity logs|Themes|
|---|---|
|Screenshot_20240205_123320|Screenshot_20240205_123342|

|Social|People|
|---|---|
|Screenshot_20240205_123403|Screenshot_20240205_123427|

|Me tab|App Settings|
|---|---|
|Screenshot_20240205_123447|Screenshot_20240205_123504|

-----

## Regression Notes

1. Potential unintended areas of impact

    None

3. What I did to test those areas of impact (or what existing automated tests I relied on)

    Manual testing

4. What automated tests I added (or what prevented me from doing so)

    Updated existing testcase

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/277">24.3 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by kristastevens** [comment]
👋 Thanks for the copy review ping! For consistency, I'd recommend: 

> Powered by Jetpack

It's clean and clear.

**Comment by spencertransier** [comment]
@antonis I'm cutting the 24.2 release branch in a few minutes, so feel free to update the base branch of this PR to `release/24.2` so that it can be included in that version.

**Comment by antonis** [comment]
> 👋 Thanks for the copy review ping! For consistency, I'd recommend:
>> Powered by Jetpack

Thank you for the prompt response and the feedback @kristastevens 🙇 
I'll wait for internal feedback on this before proceeding with the change (ref pcdRpT-5EP-p2#comment-8984).

**Review by mkevins — APPROVED** [review]
This is working as described (tested on a Pixel 3a, physical device). Thanks for the changes Antonis!

**Comment by antonis** [comment]
Thank you for reviewing @mkevins 🙇

**Pull request merged**
