### PR TITLE
Jetpack Scan: Display a warning for when server credentials are not configured

### LINKED ISSUE #14434: Jetpack Scan: display a warning for when server credentials are not configured
### Expected behavior

1. When the user taps Scan
2. And server credentials are not configured
3. The user can't start the Fix Threat flow and they see a warning
4. When the warning is tapped user is redirected to https://wordpress.com/settings/jetpack/site (where "site" is the site address)

### Design

Similar to the design in [Jetpack Restore: display a warning for when server credentials are not configured](https://github.com/wordpress-mobile/WordPress-Android/issues/14111).

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #14434

To test:

#### Test.1: Server creds message is displayed

1. Log in to the app with a `WordPress.com` account having a site that 
   - has a scan plan without server credential configured 
   - has a fixable threat in the current state
(e.g.  Test site:  [pressable-jetpack-daily-scan-without-server-creds](http://pressable-jetpack-daily-scan-without-server-creds.mystagingwebsite.com/))
2. Go to My Sites -> Jetpack -> Scan
3. Run scan so that fixable threat is shown on the screen
3. Notice that on the scan and scan -> threat details screens
    - Fix All button is disabled
    - Enter server credentials message is displayed
4. Click Enter server credentials message from both the screens
5. Notice that the external jetpack settings URL is opened (might need to login to the site on the browser)

https://user-images.githubusercontent.com/1405144/114521795-6201a300-9c60-11eb-870c-36a500950216.mp4
   
https://user-images.githubusercontent.com/1405144/114521901-78a7fa00-9c60-11eb-9d4e-19506a5e4686.mp4

#### Test.2: Server creds message is not displayed
6. Repeat Test.1 for a site that 
     - has a scan plan with server credential configured and
     - has a fixable threat in the current state
     (e.g.  Test site:  [pressable-jetpack-daily-scan](http://pressable-jetpack-daily-scan.mystagingwebsite.com))
    or 
     - has a scan plan without server credential configured and
     - has no fixable threats
     (e.g.  Test site:  [pressable-jetpack-complete](https://pressable-jetpack-complete.mystagingwebsite.com/))

7. Notice that Enter server credentials message is not displayed

https://user-images.githubusercontent.com/1405144/114523233-bd806080-9c61-11eb-8c2c-1dfbec26b534.mp4

https://user-images.githubusercontent.com/1405144/114524819-2b795780-9c63-11eb-9e45-c49de8e87390.mp4

### Merge Instructions

- Make sure https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1951 is merged to `FluxC` `develop`
- Create a tag on `FluxC` `develop`
- Update `FluxC` tag in `build.gradle` in this PR
- Remove the `Not Ready for Merge` label
- Merge this PR with `develop`

### Review Instructions

- Only one reviewer is required
- Any of the reviewers relatively free can review

## Regression Notes
1. Potential unintended areas of impact
N/A - Changes are limited to the Jetpack section. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A - Changes are limited to the Jetpack section. 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I have reviewed and tested this PR as per the instructions, everything works as expected, really good job. Also, amazing job on adding all those extra tests! And, as I mentioned that before, I also loved how you spit the tests and prepared the sites, this made it so easy for me to test the overall solution, kudos! 🌟 ❤️

I actually don't have any real comments for this PR per se, all I can give you is the below:
- Minor (🔍): All the classes you touched can be reformatted according to the indentation that we have agreed (including the tests). If you want, feel free to do this now so we avoid going through that again in the future.
- Warning (⚠️): I noticed that the `JetpackListItemState` has been defined as `abstract`. Detekt complains about that, the whole file ends up being one big warning. 😅 Consider, replacing the `abstract` keyword with `open`.

**Comment by ashiagr** [comment]
>  All the classes you touched can be reformatted according to the indentation that we have agreed (including the tests)

Yep, I wanted to reformat but didn't want to introduce too many changes to this PR before the review. I'll go ahead and do this now.

**Comment by ashiagr** [comment]
@ParaskP7 as discussed will create another PR formatting Jetpack package files. 
I've included your other review comment. Ready for another look.

**Comment by ashiagr** [comment]
@osullivanchris, pinging you so that you can take a look at the exact message. Let me know it needs any changes.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> @ParaskP7 as discussed will create another PR formatting Jetpack package files.

Great! ❤️ 

> I've included your other review comment. Ready for another look.

Thanks so much for this update, LGTM! 🚀

**Comment by osullivanchris** [comment]
> @osullivanchris, pinging you so that you can take a look at the exact message. Let me know it needs any changes.

Thanks for the ping!

Current text

> Enter your server credentials to enable threat fixing.

The phrase "enable threat fixing" doesn't feel quite right. My attempt:

> Add your server credentials to fix threats. 

or 

> To fix threats, you need to add your server credentials.

Any preference? Probably not big enough to be worth getting an editorial review on it?

**Comment by ashiagr** [comment]
Thanks for the suggestions @osullivanchris!

> Add your server credentials to fix threats.

Can we replace "Add" with "Enter" to align with this other message for restore backups:

108420658-da288b00-7212-11eb-9bdd-bb2ace231f80

**Comment by osullivanchris** [comment]
> Can we replace "Add" with "Enter" to align with this other message for restore backups:

Sounds good. So that's

> Enter your server credentials to fix threats

**Comment by ashiagr** [comment]
Message updated in a3b63d9

Scan screen - Plural | Scan screen -Singular | Threat details - Singular
---|---|---
device-2021-04-14-184306|device-2021-04-14-184354|device-2021-04-14-184340

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I reviewed the latest changes and LGTM! 🌟 

Minor (🔍) suggestions below:
1) For the `ThreatDetailsListItemsBuilder.buildEnterServerCredsMessageState(...)` function, I suggest us doing the same as you did for the `ScanStateListItemsBuilder.buildEnterServerCredsMessageState(...)` function, that is to extract the `messageResId` variable and reuse it instead of duplicating it. It seems that this is more robust to me as it will avoid us using a separate stings in the future, one might one string but forget about the other one. Wdyt?
2) I suggest adding the `plural` related test for the new functionality added to the `ScanStateListItemsBuilder.buildEnterServerCredsMessageState(...)`. Wdyt?

I am going to approve this PR anyway, since none is blocking. I am **NOT** going to merge this PR yet to give you some time to apply any of my suggestions. However, feel free to ignore them and merge the PR yourself.

**Comment by ashiagr** [comment]
Thanks @ParaskP7! I've included the 1st suggestion, ignoring the 2nd considering it a minor one.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Thanks @ParaskP7! I've included the 1st suggestion, ignoring the 2nd considering it a minor one.

LGTM, 🟢 light from me, feel free to merge when CI completes. 🚀

**Pull request merged**
