### PR TITLE
Feature/media metadata overlay

### PR DESCRIPTION
**Pull request by nbradbury**
Removes the `MediaItemFragment` and moves displaying/editing media metadata to the full-screen media preview.

Tapping on an item in the media browser now opens it in the full-screen preview. Metadata about the media is overlaid on the preview and can be edited from there.

Video demo:

<a href="https://cloudup.com/cXwi6iFC8We">https://cloudup.com/cXwi6iFC8We</a>

### CODE REVIEW

**Comment by daniloercoli** [comment]
Two minor things:

- https://cloudup.com/cwt3FYIjUkf  The overlay at the bottom of the screen reappears when I rotate the device, even if i'm editing the properties of the media making the screen looking over-populated for a couple of secs. 

- https://cloudup.com/cte1uvzV6-x Would be possible to request the picture from the network by using the `Max(device-width, device-height)` value? We will save 1 network request upon device rotation.

**Comment by nbradbury** [comment]
> The overlay at the bottom of the screen reappears when I rotate the device, even if i'm editing the properties of the media

Fixed in 3049f06

> Would be possible to request the picture from the network by using the Max(device-width, device-height) value? We will save 1 network request upon device rotation.

I tried this but it didn't appear to change anything - a request for the image still occurred after rotation. And because I used `Math.max(width, height)` the image wasn't always sized correctly for the display.

**Comment by daniloercoli** [comment]
I really like this new screen! Just another minor thing, when I tap on edit the "Title" field has the cursor in it, but the keyboard is not available on the screen. I have to tap the Title field again.

**Comment by nbradbury** [comment]
> when I tap on edit the "Title" field has the cursor in it, but the keyboard is not available on the screen.

Fixed in f34bed4

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
