### PR TITLE
Fix Featured Image issues when leaving the editor

### LINKED ISSUE #4766: Leaving the editor removes Featured Image from post
### Steps to reproduce the behavior
1) Open the editor for a new post, setting the title and body
2) Open post settings and set a featured image.
3) Back out of the editor
4) Navigate to the Blog Posts list and edit the post
5) Open post settings and confirm the featured image is still set
6) Publish the post
7) Note that your post no longer has a featured image

android-no-featured-image

##### Tested on Nexus 6P, Android 7.1.1 (shown above on an Android 4.4 emulator)

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #4766 by making sure feature image field is tested when checking for changes in `hasChanges` routine.

To test:
- Open the editor for a new post, setting the title and body
- Open post settings and set a featured image
- Tap back twice and go back to posts list
- Edit the post again
- Open post settings and confirm the featured image is still set
- ^ repeat the steps above by removing the FI
- Re-add the FI, and publish the post
- Check that FI is set on the post

### CODE REVIEW

**Comment by nbradbury** [comment]
This doesn't appear to be fixed. Here's what I did:

* Created a new post with a featured image
* Backed out to the post list
* Opened that post in the editor again and verified it still had a featured image
* Published it

The featured image disappeared after the post was published.

**Comment by daniloercoli** [comment]
@nbradbury - I've tried to refactor the code around FeatureImage detection/upgrading/uploading, making it a little bit more easy to grasp, and fixed the issue above.
I did a bunch of testing, but please double check this by setting/remove/upgrade FI on published posts.

**Comment by daniloercoli** [comment]
@nbradbury Never mind there are still issues. Will take a look to this PR tomorrow.

**Comment by aforcier** [comment]
Note that [some things](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e013c94a64ea0b3139e9eb3f3b38a5a196d7a133/fluxc/src/main/java/org/wordpress/android/fluxc/model/PostModel.java) [have changed](https://github.com/wordpress-mobile/WordPress-Android/pull/4574) re: `Post` model and featured images in FluxC. I'm not sure whether this issue is still present in the FluxC branch or not (we need [MediaStore](https://github.com/wordpress-mobile/WordPress-Android/pull/4616) integrated to test it properly, which is nearly done). But it might be worth holding off a bit if the fix is looking tricky to avoid having to do it twice.

**Comment by daniloercoli** [comment]
Thanks @aforcier. It seems to a be an easy fix, once you get all the logic behind FI. 
Ready for another review pass!

**Comment by nbradbury** [comment]
Nice work @daniloercoli, works fine now :shipit:

**Pull request merged**
