### PR TITLE
Jetpack App (Emphasis): Hide Reader

### LINKED ISSUE #14508: Jetpack App (Emphasis): Hide Reader
Parent: #14294

The goal of this task is to hide the Reader tab for the Jetpack app.
(based on the "Hide Reader" requirement of the `pcdRpT-iP` P2 post)

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #14508

This PR 
- hides the Reader tab for the Jetpack app (based on the "Hide Reader" requirement of the `pcdRpT-iP` P2 post).
- only displays the title for the empty view on the Notifications tab and hides actions to go to the Reader or create a post (based on https://github.com/wordpress-mobile/WordPress-iOS/pull/16339#issuecomment-823407368).

To test:
- Comment out condition to `hideEmptyView()` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt#L150-L154) so that `showEmptyViewForCurrentFilter() `gets called for the notifications tab **.
- Install and log in to the Jetpack app `jetpackJalapenoDebug`. 
- Notice that the Reader tab is not visible in the bottom bar.
- Go to the Notifications tab.
- Notice that the empty view is visible without the description and action button.

jp

------

- Repeat the above steps for the WordPress app `wordpressJalapenoDebug`
- Notice that 
    - the Reader tab is visible in the bottom bar.
    - the empty view is visible on the Notifications tab with the description and action button.

wp

** Revert commented out code after testing the apps.

## Regression Notes
1. Potential unintended areas of impact
WordPress app

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested WordPress app for the presence of the Reader tab and empty view on the Notifications tab.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @ashiagr 👍 
I tested this on a Pixel 5 (Android 11) and both the Jetpack and Wordpress apps work as expected. The code changes are consistent and LGTM 🎉 

It would nice to have tests for the modification but I understand that the `BuildConfig` makes this difficult and that tests can be added at a later stage when more tabs are added to the app as described in the design (`pcdRpT-iP-p2`).

**Comment by ashiagr** [comment]
Thank you @antonis!

Yes, tests look a bit tricky at this time but are definitely planned for the future.

Appreciate your time in reviewing this 🙏.

**Comment by antonis** [comment]
Hey @ashiagr 👋 
I investigated the crash we talked about. It seems that this involves a corner case related to my configuration.

The prompt I'm getting is [`FOLLOW_SITES_TUTORIAL`](https://github.com/wordpress-mobile/WordPress-Android/blob/4b13a2bcfe62d9820f446aea44019817f02ee39f/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartMySitePrompts.kt#L45) which points to the missing layout id `R.id.bottom_nav_reader_button`, since the tab is removed. That leads to a null pointer exception when trying to get the `targetView.getWidth()`.
I'm not sure if it makes sense to put effort on this since the quick actions will be removed for the Jetpack app. Probably I would just add [one more null check](https://github.com/wordpress-mobile/WordPress-Android/blob/5b861ce2dcbeabb924dc0b4ba6a1b6940724b22e/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L1239). 

Screenshot 2021-04-28 at 2 18 42 PM

**Comment by antonis** [comment]
Thank you for adding the null checks @ashiagr! The code changes look good and the app runs fine with the configuration that previously caused the crash 🙇

**Comment by ashiagr** [comment]
Thank you @antonis! Glad you caught it. Even though quick actions will be removed for the Jetpack app, went ahead and added a null check since the crash isn't always reproducible and we might want to show quick actions at some point.

I'll merge the PR now.

**Pull request merged**
