### PR TITLE
My Site Dashboard-Phase 2: Initial Structure - Introduce Pull-to-refresh

### PR DESCRIPTION
**Pull request by zwarm**
Parent #14215

This PR introduces pull-to-refresh to the My Site view controlled by the `MySiteDashboardPhase2FeatureConfig` feature flag.

A `mocked_refresh_posts_data.json` raw resource was added to show the difference from initial load and PTR request. This will be removed once the true endpoint gets hooked up. 

We may want to consider adding a call to `PostsDataSource.refresh()` to the MySiteViewModel.refresh fun so that Posts cards get updated on return to the MySite tab. I did not hook this up in this PR, so PTR can be tested and can be visually verify that the data changed. All all likelihood, the data won't change often.

I had to split the `@Before` setUp in MySiteViewModelTest to support testing the PTR enabled flag. `setUp` now calls `init()` with a parameter for setting the `MySiteDashboardPhase2FeatureConfig` feature flag. If there is a better way, I am open to exploring it. 

https://user-images.githubusercontent.com/506707/138352339-25b097fe-b946-4b90-b6ac-8510e469284b.mp4

**To test:**
- Launch the app with `MySiteDashboardPhase2FeatureConfig` set to off
- Try to swipe to refresh
- Note: swipe to refresh is not active
- Navigate to My Site -> App Settings -> Debug Settings and set `MySiteDashboardPhase2FeatureConfig` to on
- Restart the App
- Navigate back to My Site tab
- Try to swipe to refresh
- Note: swipe to refresh indicator is shown and the posts cards change to "refreshed" in the title

## Regression Notes
1. Potential unintended areas of impact
My Site view allows PTR when the feature flag is off

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing + 
Added two tests to `MySiteViewModelTest` to cover testing the enabling/disabling of the swipe refresh layout.

3. What automated tests I added (or what prevented me from doing so)
Added two tests to `MySiteViewModelTest` 

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Whoa! Thank you so much for introducing much-awaited PTR on "My Site" tab. 🙌 

> We may want to consider adding a call to PostsDataSource.refresh() to the MySiteViewModel.refresh fun so that Posts cards get updated on return to the MySite tab. I did not hook this up in this PR, so PTR can be tested and can be visually verify that the data changed. All all likelihood, the data won't change often.

Sounds good 👍 

> I had to split the @Before setUp in MySiteViewModelTest to support testing the PTR enabled flag. setUp now calls init() with a parameter for setting the MySiteDashboardPhase2FeatureConfig feature flag. If there is a better way, I am open to exploring it.

This looks fine to me. 

I've tested `pull-to-refresh` action refreshes the postcards, as intended. 

Just one question: We'll be adding refresh logic for the applicable site list items and cards in the upcoming PRs, correct? For e.g. if we change a site plan from outside the mobile app and then pull-to-refresh in the app, then the updated plan should be shown next to the `Plan` list item.

**Comment by zwarm** [comment]
@ashiagr 
> Just one question: We'll be adding refresh logic for the applicable site list items and cards in the upcoming PRs, correct? 

I kept this work focused on the Post cards, as they were the immediate need. We can handle other cards the same way (like `CurrentAvatarUrl` and `PostCardsSource` . )

If the intent is for the entire screen to refresh on PTR, then I'll close this PR and change the solution to fit that intent. Also, should we make the decision that the entire view gets refreshed on return to My Site tab as well? Today only the following get refreshed:
```
        selectedSiteRepository.updateSiteSettingsIfNecessary()
        quickStartRepository.refresh()
        currentAvatarSource.refresh()
```
Perhaps we can just invalidate the siteSettings on PTR and all the other sources. It's worth investigating. 
Let me know. Thanks :)

**Comment by ashiagr** [comment]
> should we make the decision that the entire view gets refreshed on return to My Site tab as well

I think it is ok to refresh selectively on return to My Site tab, but if the user explicitly performs `pull-to-refresh`, IMHO it should provide the latest state of all the cards and items.

> Perhaps we can just invalidate the siteSettings on PTR and all the other sources. It's worth investigating.

Agree, that's worth investigating. 

I understand that this PR fulfills the immediate need for refreshing the post cards, and it is behind a feature flag so I don't see any issues merging it. 🤷‍♀️ 

> We can handle other cards the same way (like CurrentAvatarUrl and PostCardsSource . )

Yep, let's do this in another PR, maybe just add a subtask for it.

**Comment by zwarm** [comment]
Closing this PR. It was decided that we will not pursue PTR for only post cards.  
@ashiagr @ParaskP7 FYI

**Pull request closed without merging**
