### PR TITLE
Issue/update passcodelock

### PR DESCRIPTION
**Pull request by tonyr59h**
__Do not merge__ until [this PR](https://github.com/wordpress-mobile/PasscodeLock-Android/pull/17) has been merged and a new version of the library has been released.

### CODE REVIEW

**Comment by maxme** [comment]
Make sure to close #53 when this is merged.

**Comment by tonyr59h** [comment]
@daniloercoli just finished up with switching to PreferenceFragment, I think it's ready for a merge and release.

**Comment by daniloercoli** [comment]
@would you mind to merge develop into this branch, and fix building errors?

**Comment by tonyr59h** [comment]
All merged up :)

**Comment by daniloercoli** [comment]
I'm seeing the following error on this branch:
```/WordPress/build/intermediates/res/vanilla/debug/values/values.xml:526: error: Attribute "buttonStyle" has already been defined```

**Comment by tonyr59h** [comment]
Hmm, I can't get that error to show up. I'm using a compiled version of PasscodeLock without any changes from its feature branch and no local changes (save for build.gradle using the local PasscodeLock library). So I've still got
> classpath 'com.android.tools.build:gradle:1.0.0'

and

> buildToolsVersion "22.0.1"

Can you try clearing your cache and trying again?

**Comment by daniloercoli** [comment]
@tonyr59h I removed an unused file (maybe added during merge with "develop") and unused styles. 
Give it a run, and if it's OK for you we can merge this PR.

**Pull request merged**
