### PR TITLE
build: bump kotlin to `1.9.22`

### PR DESCRIPTION
**Pull request by wzieba**
And compose compiler to 1.5.9

This bump is needed to use the newest version of ksp in the future.

-----

## To Test:

Smoke testing the app should be enough.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AjeshRPai** [comment]
Hey @wzieba 

I think dependabot just raised another PR - https://github.com/wordpress-mobile/WordPress-Android/pull/20245 when you closed this PR-  https://github.com/wordpress-mobile/WordPress-Android/pull/19756.

**Comment by wzieba** [comment]
Thanks for the ping @AjeshRPai ! I'll close #20245 as well then. Because Compose compiler version depends strictly on Kotlin version, those automated Kotlin bump PRs will unfortunatelly always fail to build.

**Comment by wzieba** [comment]
hi @zwarm 👋 do you have the capacity to review the PR this week?

**Comment by AjeshRPai** [comment]
@wzieba, I can take this on 👍🏼 . Given that https://github.com/wordpress-mobile/WordPress-Android/pull/19756 was assigned to me and didn't review, I feel responsible and want to make up for it. 😅 .

**Comment by wzieba** [comment]
😄 gotcha, thank you @AjeshRPai !

**Review by AjeshRPai — APPROVED** [review]
Hey @wzieba 

Smoke tested the following scenarios in the app, Everything looks good to me 

- [x]  Sign up ✅
- [x]  Sign in using wp com ✅
- [x]  Sign in using Gmail ✅
- [x]  Create a site ✅
- [x]  Quick start tour - select show me around after the above task ✅
- [x]  Create and Publish a Post using media ✅
- [x]  Create and publish the page ✅
- [x]  Change site icon and upload media ✅
- [x]  Change site title ✅
- [x]  Check stats, Activity log, blaze, comments ✅

**Pull request merged**
