### PR TITLE
Design: changes to color values

### LINKED ISSUE #2175: Design: update colors and variables
We finally have a nice color system in WordPress.com for the grays and the naming. I'd like to update the colors file to reflect those changes.

Here are the latest colors: https://wordpress.com/design-handbook/colors/

This will include changing the variable names to be more consistent with WordPress.com. For example, instead of `grey_extra_light`, `grey_medium_light`, etc, it would be `gray_light`, `gray_dark`, `gray_lighten_20`, etc.

### PR DESCRIPTION
**Pull request by drw158**
Aligns the Android style guide colors to the WordPress.com handbook.

- Moved old variables to depreciated section.
- Added new variables.
- Moved all transparent colors to one section.

See https://wordpress.com/design-handbook/colors/

Fixes #2175

### CODE REVIEW

**Comment by drw158** [comment]
Meant "Android" instead of "iOS" in my commit message.

**Comment by drw158** [comment]
Here's the plan:

- Deploy these changes so developers can start using the new variables.
- Because the old variables have not been removed, developers can update their projects on their own time.
- Once all old instances of the variables have been replaced with the new ones, we can remove the depreciated variables.

**Comment by drw158** [comment]
@roundhill I didn't change the Calypso Colors section; Since all of those values can be replaced with the new, updated values, I would like to get rid of them. Possible?

**Comment by maxme** [comment]
IMHO, we should replace all occurrences of deprecated colors now and remove them from the `colors` file. 

* What should we do with `calypso_*` colors? remove them too?
* Is it safe to replace all `blue_new_kid` by `blue_wordpress`, `blue_extra_light` by `blue_light`, etc.?

**Comment by drw158** [comment]
Thanks for taking a look @maxme!

Yea, ideally we should go ahead and replace all occurrences of the deprecated variables now.

We should remove the `calypso` colors as well. I took a another look, and added them to the conversion chart. There were a few colors that only Notifications was using, so I separated them out into its own section (in https://github.com/wordpress-mobile/WordPress-Android/commit/02ad026ba65d723daa9b66b441ba978ee724407a). Calypso colors should be ok to remove now. Wasn't sure about this line though at 153:

```
<!-- If you are changing these colors, please update them in NotificationsConstants as well -->
```

`blue_new_kid` should be replaced by `blue_medium`, which is almost the same color, so we should be fine there. `blue_extra_light` is the only one that might cause minor issues (we don't have an equivalent color in the new handbook). I think we'll just have to check around the app and see where it's used, maybe create a new color based on `blue_light`.

Here is the updated conversion chart:

[deprecated color] = [new color]
```
blue_extra_light = blue_light
blue_new_kid = blue_medium
blue_extra_dark = blue_dark
orange_medium = orange_jazzy
orange_dark = orange_fire
grey_extra_light = grey_lighten_30
grey_medium_light = grey
grey_medium = grey_darken_10
grey_medium_dark = grey_darken_30
grey_extra_dark = grey_dark

semi_transparent_blue_extra_light = semi_transparent_blue_light
translucent_grey_extra_dark = translucent_grey_dark
translucent_grey_light = translucent_grey_lighten_20
translucent_grey_extra_light = translucent_grey_lighten_30
translucent_grey_medium_light = translucent_grey_lighten_10

wordpress_blue = blue_wordpress

calypso_blue_unread = blue_medium
calypso_blue_dark = grey_dark
calypso_grey = grey_lighten_10
calypso_blue = grey
calypso_blue_border = grey_lighten_20
calypso_blue_light = grey_lighten_30
calypso_orange_light = notification_status_unapproved_background
calypso_orange = notification_status_unapproved ( also = alert_yellow )
calypso_orange_dark = notification_status_unapproved_darker
```

**Comment by maxme** [comment]
Thanks @drw158 !
I'll remove old colors / replace them using your chart and  have a look at NotificationsConstants and update them if needed.

**Comment by maxme** [comment]
@drw158 replacements done in 65bddb2

@daniloercoli and @jancavan I reused a translucent grey here https://github.com/wordpress-mobile/WordPress-Android/blob/65bddb2c0983604d893a029a0112580638eb86d3/WordPress/src/main/res/values/colors.xml#L107 let me know if that's ok or if we need a specific color.

@roundhill I removed NotificationsConstants in ff4093e - I think it's better this way even if we have to keep a Context in NoteBlockClickableSpan - I'll reintroduced it if I missed something.

**Comment by drw158** [comment]
Awesome, this looks great @maxme 

Let's swap out the Stats colors so that they use the colors from the handbook:

Before:
```
<color name="stats_text_color">#404040</color>
<color name="stats_link_text_color">@color/blue_wordpress</color>
<color name="stats_module_content_list_header">#93A6C0</color>
<color name="stats_blue_labels">#587295</color>
<color name="stats_bar_graph_views">#0085BF</color>
<color name="stats_bar_graph_grid">#D9D9D9</color>
<color name="stats_bar_graph_vertical_label">#93a6c0</color>
<color name="stats_div_color">#B7B7B7</color>
<color name="stats_lists_background_color">#f4f8fA</color>
<color name="stats_empty_placeholder_color">@color/translucent_grey_lighten_30</color>
```

After:
```
<color name="stats_text_color">@color/grey_dark</color>
<color name="stats_link_text_color">@color/blue_wordpress</color>
<color name="stats_module_content_list_header">@color/grey</color>
<color name="stats_blue_labels">@color/grey_darken_20</color>
<color name="stats_bar_graph_views">@color/blue_wordpress</color>
<color name="stats_bar_graph_grid">@color/grey_lighten_20</color>
<color name="stats_bar_graph_vertical_label">@color/grey</color>
<color name="stats_div_color">@color/grey_lighten_10</color>
<color name="stats_lists_background_color">@color/grey_light</color>
<color name="stats_empty_placeholder_color">@color/translucent_grey_lighten_30</color>
```

Also, one small change: can we add a link to the handbook on line 34/35?
```
 <!-- WordPress.com Colors -->
 <!-- wordpress.com/design-handbook/colors -->
```

I didn't want to do it myself in case in caused any annoying conflicts.

cc @jancavan

**Comment by jancavan** [comment]
Thanks @drw158 @maxme colors look good.

**Comment by maxme** [comment]
@drw158 I've made these changes in 7dd83a0

**Comment by maxme** [comment]
I did an overall test of the app, everything seems ok. The only thing that bothers me is status bar color, looks a bit off compared to the action bar. 


screenshot_2015-03-04-17-54-46

**Comment by drw158** [comment]
@maxme:

The colors of the bars should match up what MT worked on here: 

screen-shot-2015-02-27-at-12-46-18-pm

The action bar color should be `blue_wordpress`.

The status bar looks like it's a shade of the action bar. I'll ping MT and see how that color was generated.

**Comment by drw158** [comment]
@jancavan: I noticed that the colors of the stats are different on the web than the screenshot maxime shared above.

screen shot 2015-03-04 at 11 48 55 am

**Comment by jancavan** [comment]
@drw158 thanks for pointing this out. I'll work with @maxme and @daniloercoli to get this updated.

**Comment by daniloercoli** [comment]
I think @maxme posted screenshots of the current version of wp-android. 2 months old code.
The "develop" branch (candidate to be released as 3.9) should have the same colors we're using now on the web.

**Comment by maxme** [comment]
We changed the stats colors because of this comment: https://github.com/wordpress-mobile/WordPress-Android/pull/2185#issuecomment-76751213 - should we revert these changes or update the Web colors?

**Comment by maxme** [comment]
I'm merging this with broken stats colors. Opening a new issue https://github.com/wordpress-mobile/WordPress-Android/issues/2390

**Pull request merged**
