### PR TITLE
Handle image load failure on preview screen

### LINKED ISSUE #11346: Handle image load failure on preview screen
Goal of this task is to display an error placeholder in case of image load failure on the image preview screen as mentioned in the https://github.com/wordpress-mobile/WordPress-Android/pull/11222#issuecomment-584078153

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #11346

This PR displays a retry button when image to be edited fails to load on the preview screen.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @ashiagr!

The code looks good. However, I've encountered one bug and I'm also not entirely sure about the design. Having a basic button in the middle of the screen seems a bit weird. Wdyt?

1. Add an image into the editor
2. Turn on airplane mode
3. Click on "Edit" image
4. Notice retry button is shown
5. Click on retry
6. Turn off airplane mode
7. Click on retry
8. Notice the low resolution image is opened in uCrop

**Comment by ashiagr** [comment]
I've updated retry UI and tried to fix the bug. Ready for another pass @malinajirka , thanks 🙏.

**Comment by malinajirka** [comment]
Thanks @ashiagr ! The bug fix seems good. I have two minor notes to the design update:
1. The text is "grey" is that intentional? I'd expect a white text, since the icon is white. Wdyt?


2. Clicking on the retry icon doesn't do anything. I need to click on the text to invoke the refresh.

**Comment by ashiagr** [comment]
> The text is "grey" is that intentional? I'd expect a white text, since the icon is white. Wdyt?

Fixed here d1ce2ed. Updated base theme to have white accent and `textColor` color so we don't  have to worry about it everytime.

> Clicking on the retry icon doesn't do anything. I need to click on the text to invoke the refresh.

Fixed here e3690b7. Clicking anywhere on the image view will trigger retry. Retry icon was set to `ImageButton` which interfered.

> The bug fix seems good. 

It seems to have this issue as well 😄 https://github.com/wordpress-mobile/WordPress-Android/issues/11377.

Ready for another look @malinajirka !

**Comment by malinajirka** [comment]
>Fixed here d1ce2ed. Updated base theme to have white accent and textColor color so we don't have to worry about it everytime.

Perfect solution, thank you!

>Fixed here e3690b7. Clicking anywhere on the error layout will trigger retry. Retry icon was set to ImageButton which interfered.

Yeah, that was my guess. Works like a charm now!

>It seems to have fixed this issue as well 😄 #11377.

Tested and you are right, awesome! 

Looks great, thank you!

**Pull request merged**
