### PR TITLE
Show privacy settings banner for users in GDPR jurisdictions

### LINKED ISSUE #18567: Android - Show popover for EU users
## Description
A popover should be shown when the user opens the app from an EU country for the first time (saved locally) and has the analytics enabled.
The pop up should allow the user to:
* Disable the analytics
* Go to settings
* Save the settings and close the popup
* Dissmish the pop up

We will follow the [Woo popover design](pecCkj-AB-p2) adjusted to much the style of the app. An indicative design is shown below.

new user

Similar Woo implementation https://github.com/woocommerce/woocommerce-android/pull/9047

### LINKED ISSUE #18569: Android - Track user actions
Implement the following new analytic events.

Event | Trigger
---- | ----
`privacy_choices_banner_presented` | When the banner is presented
`privacy_choices_banner_settings_button_tapped` | When the settings button is tapped
`privacy_choices_banner_save_button_tapped` | When the save button is tapped

### PR DESCRIPTION
**Pull request by mkevins**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/18567

To test:
1. Launch (either) app
2. Login with a user from an EU country subject to GDPR (e.g. France)
3. **Expect to see the popup asking your consent**
   |  |
   | - |
4. **Verify the events** mentioned in [this task](https://github.com/wordpress-mobile/WordPress-Android/issues/18569) are tracked
5. Retry with an user from a non-GDPR country (e.g. US)
6. Expect to **not** see the popup
7. Restart the app after approving or denying consent
8. **Verify the popup is no longer shown**

## Regression Notes
1. Potential unintended areas of impact
   First load of My Site dashboard.

6. What I did to test those areas of impact (or what existing automated tests I relied on)
   n/a

9. What automated tests I added (or what prevented me from doing so)
   The new logic is covered by unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by ovitrif** [comment]
Ouch, I "closed" by mistake, glad I could reopen the PR

**Comment by ovitrif** [comment]
made ready for review as I will be focused on patching things if required, otherwise merging this PR

**Comment by mkevins** [comment]
> made ready for review as I will be focused on patching things if required, otherwise merging this PR

Thanks for your help on this Ovi!

**Review by ovitrif — APPROVED** [review]
Works as expected, I tested the happy flow and would merge this after testing and validating the unhappy flow 😅 , ie. the flow when it shouldn't be shown.

**Comment by ovitrif** [comment]
IMHO the landscape view isn't very much the best UX we can do:
|  |
| - |

But I won't block the merge just because of this. I will try to fix it on trunk, with another PR 👍🏻 

All in all this is awesome work and many goodies added to the codebase, as well as solving the actual problem, and improving our compliance to the GDPR laws.

Thanks a million @mkevins for your effort on this work! 🙇🏻

**Review by ovitrif — APPROVED** [review]
I reviewed my own patches and consider them appropriate. :trollface:

**Comment by ovitrif** [comment]
Added 2 more patches and now enabled auto-merge for this:
- I've added a fix to expand the bottom-sheet popup initial view on Landscape ([see why](https://github.com/wordpress-mobile/WordPress-Android/pull/18696#issuecomment-1607102421)).
- 91b0ba9 to fix the failing UI test: `e2eActivityLogCardNavigation`


Preview with the patch for landscape: [`bab0115`](https://github.com/wordpress-mobile/WordPress-Android/pull/18696/commits/bab0115d87cefccbb5fdb9bbc121f42f61c7f96b):
| Land | Port |
| - | - |
|  |  |

**Comment by mkevins** [comment]
Thanks for all your help Ovi, and special thanks for wrangling the landscape issue and remaining failing test!

**Pull request merged**
