### PR TITLE
Issue/8216-empty-site-picker

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add an actionable empty view shown when no sites match the query while searching in the site picker (i.e. ***My Site*** > ***Switch Site***) as described in https://github.com/wordpress-mobile/WordPress-Android/issues/8216.  This was not included in the original project, but it's similar to the work in https://github.com/wordpress-mobile/WordPress-Android/issues/7996.  See the screenshots below for illustration.

aes_site_picker

#### Note
I'm not entirely happy with this solution.  I would prefer to use the [`EmptyViewRecyclerView`](https://github.com/wordpress-mobile/WordPress-Android/blob/19d8591335de160e89df8e6de61c0e380662140a/WordPress/src/main/java/org/wordpress/android/ui/prefs/EmptyViewRecyclerView.java) and [`ActionableEmptyView`](https://github.com/wordpress-mobile/WordPress-Android/blob/9db1372865d79967a8a6c1360ba89bba86521c68/WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt) views in tandem to automate showing/hiding the empty view without extra code.  There is a lot happening with the site picker and [some bugs](https://github.com/wordpress-mobile/WordPress-Android/issues/8224) will need to be fixed before we can utilize [`EmptyViewRecyclerView`](https://github.com/wordpress-mobile/WordPress-Android/blob/19d8591335de160e89df8e6de61c0e380662140a/WordPress/src/main/java/org/wordpress/android/ui/prefs/EmptyViewRecyclerView.java) and [`ActionableEmptyView`](https://github.com/wordpress-mobile/WordPress-Android/blob/9db1372865d79967a8a6c1360ba89bba86521c68/WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt).

### Test
0. Use account with multiple sites.
1. Go to ***My Site*** tab.
2. Tap ***Switch Site*** button in top card view.
3. Tap ***Search*** action in top toolbar.
4. Enter text matching no sites.
5. Notice actionable empty view is shown.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by khaykov** [comment]
Thanks for the PR! I found a weird behavior when you press back arrow from search screen:
[Image from Gyazo](https://gyazo.com/e216e74b06dd721e33c8eb5c4095067b)

Empty view stays visible, and search icon dissapears (I'm not sure if this one related to this PR)

**Comment by theck13** [comment]
I updated the visibility of the empty view in 5a6166a.  Thanks for catching that!

I noticed the same bugs with the toolbar actions while working on this.  I created a separate [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/8224) since it's currently occurring on `develop` and not a consequence of these changes.

**Comment by loremattei** [comment]
Hey! I moved the milestone to 10.9 since 10.8 has been cut. Please, feel free to move it back to 10.8 if it has to land there: just target the release branch and ping me to update the build!

**Comment by SylvesterWilmott** [comment]
LGTM

**Comment by theck13** [comment]
I think this is ready to merge now.  Would you like to do the honors, @khaykov?

**Pull request merged**
