### PR TITLE
Jetpack: Display multisite not supported screen for multisites

### LINKED ISSUE #14946: Jetpack: Display Scan Not Available Screen for Unavailable Scan State
iOS Issue: [WordPress-iOS#16755](https://github.com/wordpress-mobile/WordPress-iOS/issues/16755)

If a site is a multisite, the scan endpoint returns `unavailable` for the scan state.

GET: `https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/scan`
RESPONSE:
```
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": false,
    "reason": "multisite_not_supported"
}
```

Currently we are not doing any anything for this `unavailable` the state, we display a generic error, see below:

We should consider displaying the same view we show in `Calypso`, see below:

Jetpack - Display Scan Not Available Screen for Unavailable Scan State (Calypso)

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #14946

This PR displays multisite not supported message for a multisite. It uses the standard `ActionableEmptyView` to be consistent with other error states UI on the Scan screen.

Corresponding FluxC PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2069

Light | Dark
-----|-----
multi_lt_1 | multi_dark_1

To test:

1. Open the Jurassic Ninja site: https://jurassic.ninja/specialops/
2. Pick a Jetpack plan (use Jetpack Complete).
3. Launch a Jetpack Mutlisite on subdomains site.
4. Connect to this site and open the app.
5. Go to: My Site -> Scan
6. Verify that you see multisite not supported message

**Merge Instructions**

1. Make sure corresponding FluxC PR is merged
2. Wait till I add a FluxC tag and update it in build.gradle
3. Remove "Not Ready for Merge" label
4. Merge the PR

## Regression Notes
1. Potential unintended areas of impact
Changes have no impact on the rest of the functionality as this is a separate flow applicable only for multi sites.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A (added unit tests for the functionality added)

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I have reviewed and tested this PR as per the instructions, everything works as expected, good job! 🌟 

PS: Thanks so much for your help with the `Jurassic Ninja` problem! 🙏

**Review by osullivanchris — APPROVED** [review]
👋  Hey @ashiagr  it looks good. 

FYI I had a jurassic ninja issue

> Oh No! There was a problem launching the new WP. (The API responded in a weird way).

But based on the screenshots, this looks exactly like the design. So 👍  from me.

FYI @momo-ozawa [re-used some existing views for these empty states on iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/16817#event-4996100612), rather than using the empty state style per the design. Just pointing out in case that approach is useful to you on any further states we have on Android. Whatever is quickest for you with these states I think.

**Comment by ashiagr** [comment]
Thank you for the review @osullivanchris !

> FYI I had a jurassic ninja issue
Oh No! There was a problem launching the new WP. (The API responded in a weird way).
But based on the screenshots, this looks exactly like the design. So 👍 from me.

Yes, we noticed it as well. It was tested by Petros using a jurassic ninja site that I created a few days ago. So we should be ok here. 

> FYI @momo-ozawa re-used some existing views for these empty states on iOS, rather than using the empty state style per the design. Just pointing out in case that approach is useful to you on any further states we have on Android. Whatever is quickest for you with these states I think.

Yes, I saw her message. The solution implemented in this PR was quickest for me as the scan screen error states used the same layout. 

Once again thank you for a quick look, both of you @ParaskP7 & @osullivanchris 🙇‍♀️.

Merging it now.

**Comment by osullivanchris** [comment]
> Yes, I saw her message. The solution implemented in this PR was quickest for me as the scan screen error states used the same layout.

Ok cool, sounds good!

> Merging it now.

Great!

**Pull request merged**
