### PR TITLE
Scheduled posts order lists latest post first #15844

### LINKED ISSUE #15844: Scheduled posts order lists latest post first
### Expected behavior
Scheduled posts should show the post that is going to be posted the soonest first on the list. The discussion here: p5T066-2Vl-p2#comment-11021 

Currently, it shows that way on the web browser but not on mobile apps. On My Site Dashboard posts card, only the top 3 scheduled posts will be displayed, because of this ordering, it will show the 3 scheduled posts that are going to be posted the latest.

### Actual behavior
The list of scheduled posts shows the post that is scheduled the soonest last on the list.

### Steps to reproduce the behavior
On web:
image

On Android:
scheduled posts

##### Tested on [device], Android [version], WPAndroid [version]

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #15844

Scheduled posts show the latest post first instead of showing the post that is going to be posted the soonest first on the list

*Solution*
Add code in `PostListViewModel.kt` to sort the scheduled posts

To test:
1. Login with an account
2. Navigate to `MENU` tab from the `My Site` bottom nav option
3. Click on `Posts`
4. Schedule two to three posts using new post option
5. Navigate to `Scheduled` tab
6. List of posts will be displayed in order of:
- Latest created date ( The issue )
- Latest scheduled date ( The fix )

## Regression Notes
1. Potential unintended areas of impact
- Post list ordering

8. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual regression test where post list is displayed

9. What automated tests I added (or what prevented me from doing so)
- None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### Demo
https://www.loom.com/share/0684ed4dee3e4712a79c1f342596918c

### CODE REVIEW

**Review by irfano — CHANGES_REQUESTED** [review]
Thanks for handling this. It works well. 
There's a small detekt and checkstyle error. We can merge after fixing it.

**Comment by gitstart** [comment]
> Thanks for handling this. It works well. There's a small detekt and checkstyle error. We can merge after fixing it.

Thank you @irfano for reviewing the PR. 
Soon will push the fix for it.

**Comment by gitstart** [comment]
Hello @irfano,
Please check it now. Hope all lint issue will be fixed.
Thank you!

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻

**Pull request merged**
