### PR TITLE
[Update Detekt Version] Update Detekt to 1.21.0

### LINKED ISSUE #16898: Update Detekt Version - Update to 1.20.0
Parent #16892

This issue is about updating Detekt to the next version, the [1.20.0](https://github.com/detekt/detekt/releases/tag/v1.20.0).

While updating Detekt to the next version, new rules might end up being enabled that would need to be resolved/suppressed as well. This issue will deal with that too.

### LINKED ISSUE #16899: Update Detekt Version - Update to the Latest Stable (1.21.0)
Parent #16892

This issue is about updating Detekt to the [latest stable](https://github.com/detekt/detekt/releases), the [1.21.0](https://github.com/detekt/detekt/releases/tag/v1.21.0).

While updating Detekt to the next version, new rules might end up being enabled that would need to be resolved/suppressed as well. This issue will deal with that too.

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent: #16892
Closes: #16898
Closes: #16899

This PR:
- Updates Detekt to `1.21.0` (from `1.19.0` via `1.20.0`) (f9803cb85794c96be310bf620f8b33a45b4a544a + bb316e90db785a36a6bf08f5726e9dfd87a255b3).
- Updates Detekt configuration to adhere with the update (6462ecc9f8a1d86808d55ae6b0de3af585fc1d09 + 0b8225936a17bff1bcb7ae072a9ab3260a14d2f0)
- 1.20.0 Related:
    - Resolves `UnnecessaryAbstractClass` warnings (d702ca924b2c56f9c5bc24e8768aaff335b9537c)
    - Resolves `TopLevelPropertyNaming` warnings (4ef2603db97bce726d32fff243c6ba9e72f4770d)
- 1.21.0 Related:
    - Suppresses `UseCheckOrError` warnings (bd4df02300cdfe189fac66141c713fb4ed2e2306)
    - Resolves `ExplicitItLambdaParameter` warnings (3046bb71c7375313b0cdf72d0e6927651867304a)
    - Resolves `UseRequire` warnings (0983a08d2a3d19f5bb56055676dfdca5d8596ca5)
    - Suppresses `DestructuringDeclarationWithTooManyEntries` warnings (e6346527ad5d9796d112094fc3d1ff392bd6c666)
    - Suppresses `ReturnCount` warnings (74baf6ee1ff616c15fa08b7f8d250e80d290614a)
    - Resolves `FunctionNaming` warnings (8ba62d7be11f3f1e29106acf996e2c112233462d)
    - Suppresses `ComplexMethod` warning (bd067b69cbae70d980c50e154dc2b2fb5cdb4005)

PS: I recommend reviewing this PR commit-by-commit.

-----

To test:

- Verify that all the CI checks are successful (especially the detekt check).
- Smoke test the app and verify everything works as expected.

-----

## Regression Notes
1. Potential unintended areas of impact

N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@ParaskP7 FYI: I won't be able to get to this until Monday because I need a couple days of focused project work. If it's still up for review, I should be able to review it then 🤞

**Review by AjeshRPai — APPROVED** [review]
@ParaskP7  I have reviewed the changes in the PR commit-by-commit. Everything looks good to me. I have done smoke testing of the app as well. Works fine 👍🏼 

👏🏼 Praise: Thanks for adding the detailed messages in each commit and also for the links to each rule set in the corresponding commit.  You 🪨 

I am approving the changes but leaving this unmerged in case you're waiting for more feedback from the https://github.com/orgs/wordpress-mobile/teams/owl-team. 

Feel free to merge this at your convenience.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> @ParaskP7 FYI: I won't be able to get to this until Monday because I need a couple days of focused project work. If it's still up for review, I should be able to review it then 🤞

Hey, thanks for the heads-up and for being so considerate! 🙇

In this case, please don't worry about this PR, is nothing too urgent. That's one of the reasons I am always choosing to also add one member of the client engineering team (as the main reviewer) and us, the Owl team in general, as an additional one. thank YOU Oguz! 🥇 

And... I am just seeing, that Mr. @AjeshRPai the great, already did the review, thank YOU Ajesh! 🥇

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

> @ParaskP7 I have reviewed the changes in the PR commit-by-commit. Everything looks good to me. I have done smoke testing of the app as well. Works fine 👍🏼

Great, thank you so much for the review and smoke testing Ajesh, you rock! 🙇 🌟 🪨 

> 👏🏼 Praise: Thanks for adding the detailed messages in each commit and also for the links to each rule set in the corresponding commit. You 🪨

Back to you! ❤️ 

> I am approving the changes but leaving this unmerged in case you're waiting for more feedback from the https://github.com/orgs/wordpress-mobile/teams/owl-team.

Coolio, your approval is all I need at this point, just one approval, thank you so so so much! 🙏 

> Feel free to merge this at your convenience.

👍

**Pull request merged**
