### PR TITLE
Merge Jetpack CI updates into release branch

### PR DESCRIPTION
**Pull request by JavonDavis**
Resolving conflicts from https://github.com/wordpress-mobile/WordPress-Android/pull/14613. See that PR for full context

### CODE REVIEW

**Comment by oguzkocer** [comment]
@JavonDavis Is this replacing #14613? If so, is there a reason for not updating the base branch of #14613 and fixing the merge conflicts there?

**Comment by JavonDavis** [comment]
> @JavonDavis Is this replacing #14613? If so, is there a reason for not updating the base branch of #14613 and fixing the merge conflicts there?

@oguzkocer currently we've been using that branch as the base branch for any new jetpack release branch, so instead of resolving the conflicts there and maybe muddying the history a bit more(because I saw there were conflicts in a strings file) I decided to create a separate merge branch to handle it, but after actually resolving it I realized it was much simpler conflict than I anticipated and just left the branch as is. I'm ok to instead just merge this into the add/jetpack-ci-lanes branch and keep everything on one PR if you think that might keep things simpler

**Comment by oguzkocer** [comment]
@JavonDavis I think that might be the best because we are going to lose the current discussions in that PR and may need to start them from scratch.

**Comment by JavonDavis** [comment]
> @JavonDavis I think that might be the best because we are going to lose the current discussions in that PR and may need to start them from scratch.

ok! 👍

**Comment by JavonDavis** [comment]
Moving these changes into https://github.com/wordpress-mobile/WordPress-Android/pull/14613

**Pull request closed without merging**
