### PR TITLE
Site creation rework: category screen

### LINKED ISSUE #6925: Site-creation rework: Site category screen
Implement step 1 of the site-creation wizard, the site category selection.

| Step 1: Site Category |
| --- |
| screen shot 2017-11-30 at 23 03 24 |

### PR DESCRIPTION
**Pull request by hypest**
Fixes #6925 

To test:
* With the app logged in, go to site picker and hit the "+" action to add a new site
* Choose "Create WordPress.com site"
* Notice the "Create New Site" screen come up and asking to select the site category
* Tapping on any of the 3 big cards should bring up a Toast with the category selected

### CODE REVIEW

**Comment by nbradbury** [comment]
@hypest This looks good, the only issue I found was when scrolling to the bottom in landscape, the very bottom of the last card is cut off.

screen shot 2017-12-11 at 6 47 08 pm

**Comment by hypest** [comment]
Thanks for picking this up @nbradbury , and nice catch! I've added some breathing space in 
18d4750. Let me know if anything else grabs your attention, thanks!

**Comment by nbradbury** [comment]
@hypest The problem is fixed, but it looks like there may have been a bad merge with develop as this branch has swelled to 98 commits. Perhaps you meant to merge `develop` into the feature branch and then merge the feature branch into this one?

**Comment by hypest** [comment]
> Perhaps you meant to merge develop into the feature branch and then merge the feature branch into this one?

The feature branch is shared with @theck13 and I didn't want to disrupt his work. Besides the "swelling", do you think this a problem?

In the meantime, I see there are now some conflicts and I'll address those now.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
