### PR TITLE
Merge final release/20.1

### PR DESCRIPTION
**Pull request by AliSoftware**
- [x] `changelog/*.txt` files updated with latest translations
- [x] `values*/strings.xml` updated with latest translations
- [x] Version bumped in `version.properties`
- [x] WPAndroid submitted to Google for review
- [x] JPAndroid submitted to Google for review

Also includes a quick fix (`|| true`) on the `rename_apk_aab.sh` helper script that I noticed while using it for the first time on my brand new M1 mac where `bundletool` was not yet installed.

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
- [x] `versionName` dropping the `rc` suffix and `versionCode` bump in`version.properties`
- [x] `strings.xml` updates
- [x] `release_notes.xml` and `changelogs/*.txt` updates
- [ ] Diff from PRs that made it into the `release/` branch since the last beta — None here

**Comment by mokagio** [comment]
For the record, when I looked at this PR I saw that CI hadn't reported on the `test-imageeditor` job. However, the job was finished and green [on Buildkite](https://buildkite.com/automattic/wordpress-android/builds/5325).

image

image

This could be an hiccup. I [triggered a re-build](https://buildkite.com/automattic/wordpress-android/builds/5340). If everything goes fine, auto-merge will kick in and we file the issue away as a CI hiccup.

Another possibility could be that something in the task name changed and the GitHub configuration for the required checks changed accordingly and the release branch is no longer matches the required checks expectations. In such case, I think it would be okay to admin-merge this. We'll see what the next CI run shows...

**Comment by AliSoftware** [comment]
> Another possibility could be that something in the task name changed and the GitHub configuration for the required checks changed accordingly and the release branch is no longer matches the required checks expectations.

Yep this is very likely what happened there. Especially following Petros' work on the module restructuring in https://github.com/wordpress-mobile/WordPress-Android/pull/16765#issuecomment-1158620409

**Comment by ParaskP7** [comment]
👋 @AliSoftware @mokagio !

> Yep this is very likely what happened there. Especially following Petros' work on the module restructuring in https://github.com/wordpress-mobile/WordPress-Android/pull/16765#issuecomment-1158620409

Yes, this is exactly right, we had two of those GitHub checked disabled, for `test-image-editor` and `test-processors`. The `test-image-editor` is already re-enabled (see `GitHub Checks` section in the parent issue [here](https://github.com/wordpress-mobile/WordPress-Android/issues/16562)). For the `test-processors` I'll wait for a couple more days for people to catch-up on `trunk` and will re-enable that as well.

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

FYI: For the WordPress and Jetpack `installable-build` related checks failing I am seeing this `upload_to_s3` fastlane step being the problem: `[!] File already exists in S3 bucket a8c-apps-public-artifacts at 8204deb9481772038e97669f4e11f5a5e6b4f94f/jetpack-installable-build-pr16818-7e9675a.apk`

**Comment by AliSoftware** [comment]
I'm expecting this one was because Gio restarted the job when he saw the CI check was not reported, which means the re-run tried to publish to s3 a second time for the same commit. If so, it's safe to ignore the failure then.

**Comment by AliSoftware** [comment]
Admin-merging given the above, i.e.:
 - The required `test-image-editor` check will never succeed because it was renamed in `trunk` but `release/20.1` still uses the old name
 - The Installable Builds failed because the job was retried a second time and the artifacts were thus already existing in S3

**Pull request merged**
