### PR TITLE
[HACK Week] Read full Post in the App

### PR DESCRIPTION
**Pull request by notandyvee**
#20529 

It bothered me that when I wanted to view my post in the post list, it defaulted to view it on web. Why? Instead we should be utilizing mobile components. The reader has one. Let's use that one.

See for reference p1710452465319629-slack-C05N140C8H5

-----

| Read | Post |
|--------|--------|
| Screenshot_20240326_130506 | Screenshot_20240326_130536| 

## To Test:

- [x] Go to My Site and click to your posts.
- [x] Click on the overflow menu item to view more options.
- [x] You should not see a "Read" action item.
- [x] Clicking "View" should take you to a webview to read the post.
- [x] Go to debug settings and turn on `view_post_list_on_activity`.
- [x] Go back to posts.
- [x] Click on the overflow menu item.
- [x] You should now see a "Read" action item right under "View".
- [x] Clicking "Read" should take you to a screen that looks exactly like the one we use for viewing posts on the reader.

Bonus:

- [x] If you test wordpress and not jp, you shouldn't have the ability to see the "Read" option at all regardless of feature flag value.

-----

## Regression Notes

1. Potential unintended areas of impact

    n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    n/a

3. What automated tests I added (or what prevented me from doing so)

    n/a

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [x] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ReadPost</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ravishanker** [comment]
Does this change really require a feature flag?  

Also, worth creating an issue for this, and post it in [#hack-week-mobile-reader-customization ](https://a8c.slack.com/archives/C06PGTY5PKK), and [#jetpack-mobile-reader-improvements](https://a8c.slack.com/archives/C05N140C8H5) channels as an FYI.  Wdyt?

**Comment by notandyvee** [comment]
> Does this one line change really require a feature flag?

Idk. It's a behavior change. Figured we can test it out. Roll it out slowly. If we don't think it's necessary, I can remove it.

**Comment by notandyvee** [comment]
Any chance you can test @aditi-bhatia 🙏🏻

**Comment by aditi-bhatia** [comment]
@notandyvee Taking a look now 👍

**Review by aditi-bhatia — APPROVED** [review]
Nice work! This is a much better user experience. I personally think a feature flag might not be necessary since this is a small enough change, but also understand if you'd prefer to keep it just in case

**Review by ravishanker — APPROVED** [review]
Nice work 👍 

Created an issue, and updated the description.

One thing to fix before merging is the top status bar background(see second image in the description), compare that with first image.

**Comment by notandyvee** [comment]
Good points y'all. Since I added a new menu item, the feature flag isn't really necessary anymore, so I removed it. I'd actually like a quick vibe check from @osullivanchris . When the JP build is ready, could you install and run a quick test. Does the menu item and icon look fine? I updated the screenshots above. So the icon is current.

note: I did notice the status bar thing that Ravi pointed out. I will leave it for now because it affects the reader as well. Out of scope here. Instead I will create an issue if one doesn't exist for it.

**Comment by osullivanchris** [comment]
@notandyvee I can't login to the build for some reason but this looks fine to me. Initially I saw some misalignment with the text/icon but looks fixed now with the updated icon.

**Pull request merged**
