### PR TITLE
Fix #3280 - Sign in: Tapping return from username field should move t…

### LINKED ISSUE #3280: Sign in: Tapping return from username field should move to password field
Nexus 7, OS 5.1.1

From a fresh install fill out the sign in screen for wpcom. 
Tapping return while the cursor is in the username field does nothing.

### PR DESCRIPTION
**Pull request by AftonTroll**
…o password field

Added checks for return key and next key while in the user text field. When this happens, the focus is moved to the password field.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Thanks for contributing, @AftonTroll!

Been waiting on this enhancement for a while, it's good to have someone taking care of it. I think if you use `android:imeOptions="actionNext"` we can get the same effect without touching the code, helping us avoid code bloat. Have you tried this option? I haven't myself so I'm not sure if there are other things to look out for but it's worth a shot.

**Comment by maxme** [comment]
> I think if you use android:imeOptions="actionNext"

If that doesn't work, we could reuse [this](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/3247-reader-gap-detection/WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java#L360-L373). Also we should make sure everything works OK with the self hosted URL and the 2-steps code fields when they're shown.

**Comment by AftonTroll** [comment]
@tonyr59h I tried it now and it works well for the navigation from the username field to the password field. The ActionListener that @maxme pointed at already fixes the navigation between password and URL. I'll make sure it works with the 2-step as well before pushing.

However, there is an issue that the navigation becomes strange when errors (not filling data) occur. It would make more sense to navigate to the topmost field with an error.
The change in the code is easy as well: just switch place between show username error and show password error. Is this a separate issue or should I include it as well?

How do I update this pull-request? Do I just need to push my changes to the branch in my fork? Or is there more?

Thank you for your patience :)

**Comment by tonyr59h** [comment]
> How do I update this pull-request? Do I just need to push my changes to the branch in my fork?

You got it :+1:

> Is this a separate issue or should I include it as well?

Wouldn't hurt to throw those improvements into this PR.

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
