### PR TITLE
removed line that prevented like/approve actions to appear on wearables

### LINKED ISSUE #4723: Notifications: wearable doesn't show Like/Approve (only Reply)
### Expected behavior

When receiving a comment notification, 2 actions are typically shown:
- Reply
- Like (or) Approve
### Actual behavior

Only `Reply`  is being shown.
### Steps to reproduce the behavior

Have someone comment on a post of yours, and wait for hte notification appear on your handset and wearable. The notification on the handset should have REPLY and LIKE / APPROVE (these latter depend on your blog settings for comments). The notif on the wearable has only REPLY and the default wearable actions (block app).
##### Tested on [Nexus 5], Android [6.0.1]

cc @hoverduck

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4723 

To test:
Have someone comment on a post of yours, and wait for the notification appear on your handset and wearable. The notification on the handset should have REPLY and LIKE / APPROVE (these latter depend on your blog settings for comments). The notif on the wearable should also have the same actions as seen on the handset.

### CODE REVIEW

**Comment by daniloercoli** [comment]
I think this PR is OK, and can be merged. Do we have someone with a wearable device to test this? Or I can merge it anyway?

**Comment by mzorz** [comment]
I have tested it on the emu, but maybe @tonyr59h can check it out? as he helped us test on a wearable in the past :)

**Comment by tonyr59h** [comment]
On it!

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
