### PR TITLE
Issue/10433 semantic color names in xml layouts

### PR DESCRIPTION
**Pull request by khaykov**
Part of #10433

This PR is intended to be a part of a gradual effort to get our styling in order and reduce tech debt.

In this PR I changed direct color references to their semantic attributes in XML layouts. I did it only in layouts where it makes sense and the change is straightforward. I left out some layouts that will require extra TLC and will address them in subsequent PR's.

This PR does not carry any visual changes. All the changes are semantic.

I identified the following color groups based on common usage

| Semantic Attribute Name | Semantic color name (color studio name)   | iOS name   |
|-------------------------|----------------------|------------|
| wpColorTextTetriary             | neutral_40 (gray_40) | textTetriary       |
| wpColorTextQuaternary       | neutral_30 (gray_30)    | textQuaternary |
| wpColorTextInverted       |  @ android:color/white    | textInverted  |
| wpColorAccent       | accent_50 (pink_50)    | accent |
| wpColorAccentLight       | accent_30 (pink_30)    | N/A |
| wpColorError       | error_50 (red_50)    | error |
| wpColorPrimary       | primary (wordpress_blue_50)    | primary |
| wpColorPrimaryLight       | primary_40 (wordpress_blue_40)    | primaryLight |
| wpColorPrimaryDark       | primary_70 (wordpress_blue_70)    | primaryDark |
| wpColorSuccess       | success_50 (green_50)    | success |
| wpColorWarningDark       | warning_50 (yellow_50)    | warning |
| wpColorWarningLight       | warning (yellow_20)    | N/A |
| wpColorBasicBackground       | neutral_0 (gray_0)    | basicBackground |
| wpColorSurface       | @ android:color/white    | listForeground (?) |
| wpColorDivider       | gray_5 | divider |
| wpColorAppBar       | primary_50 (wordpress_blue_50)    | appBar |

PS: I also fixed usage of white color, by switching from `@color/white` to `@android:color/white`

Colors that do not fit into this table are used sparingly and will require some additional attention to determine if we going to change them to more commonly used semantic variations, add them to the list or leave them be.

To test:
- From developer - app builds, and changes in XML files are limited to switching from color references to attributes.
- From designer - there is no visual change, I would just love to have a second pair of eyes to make sure everything looks the same. Maybe any comments on semantic color names?

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
Uf. Looks like Login flow is using layouts from main `WordPress` module, but the theme from `WordPressLogin` module which is causing some issues. Will investigate.

**Comment by jkmassel** [comment]
Howdy! The `13.3` code freeze is today, so I'm bumping this to `13.4`. If you'd like it to be part of the `13.3` release, please target the `release/13.3` branch, and DM me once it's merged so that I can include it as a new beta release!

**Comment by khaykov** [comment]
Ready for review!

**Comment by mattmiklic** [comment]
I didn't find any other issues in a quick visual check of the test build. No comments from me on the semantic naming; I think it makes sense and is probably more relevant to developers than designers for the most part.

**Comment by khaykov** [comment]
Thanks @mattmiklic ! I'm going to hold on merging this one for a bit, while I'm figuring how it might affect switching to Material Theme.

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.4` today, so this is being bumped to `13.5`. If you'd like it to go out as part of `13.4`, please target `release/13.4` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.5` today, so this is being bumped to `13.6`. If you'd like it to go out as part of `13.5`, please target `release/13.5` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by khaykov** [comment]
Since we decided to move with the material theme, I'm closing this PR for now.

**Pull request closed without merging**
