### PR TITLE
Fixes: Title is not shown on My Site Dashboard with no sites & Tab height

### LINKED ISSUE #16154: No Title is Shown on Empty State View
No Title is shown where there are no sites present for a User

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #16154 & #16219

Since the changes were small and dependent on each other, this PR fixes the issue of toolbar height and margin and the 
No Title shown in Empty State(No Sites Present for an account). 

### My Site Dashboard when no sites are present  

Test 1 
- Launch app with an account having no sites
- Notice that **My Site** is shown in the toolbar 

Test 2
- Launch the app with an account having sites 
- Go to My Site
- Notice that the Site Info is shown above the quick links and collapses to Site title when scrolled below

Test 3
- Launch the app.
- Go to My Site -> Me -> App Settings -> Debug settings.
- Turn on the MySiteDashboardTabsFeatureConfig flag under the Features in development section.
- Restart the app
- Notice that the Site Info is shown above the tabs and collapses to Site title when scrolled below

## Regression Notes
1. Potential unintended areas of impact
My Site Dashboard not being shown properly when Sites are Present 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual Testing 

3. What automated tests I added (or what prevented me from doing so)
None 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by osullivanchris** [comment]
@AjeshRPai mostly looking good here

- My Site tab with no sites looks good
- Header size looks much better now

Small issue. There's a space between the blue line indicating the active tab, and the bottom of the tab bar. On reader, and in general with the material component, the active line should be right at the bottom. Not sure where the extra space is coming from.

image

image

**Comment by AjeshRPai** [comment]
@osullivanchris Thanks for reviewing it. 😄 

>Small issue. There's a space between the blue line indicating the active tab, and the bottom of the tab bar. On reader, and in general with the material component, the active line should be right at the bottom. Not sure where the extra space is coming from.

I will add it as an issue and take it up in a separate PR.

**Comment by zwarm** [comment]
@AjeshRPai I see an issue with scrolling for quick start. See the attached video.

https://user-images.githubusercontent.com/506707/161116932-b085a9fe-b16a-475c-913d-c8a452685688.mp4

**Comment by AjeshRPai** [comment]
>I see an issue with scrolling for quick start. See the attached video.

@zwarm Nice catch. I am gonna create an issue for this bug and fix it in a separate PR as that is not related to the changes in this PR. 

Added [Quick start scroll issue with My Site Header](https://github.com/wordpress-mobile/WordPress-Android/issues/16224) in the Parent issue

**Review by ashiagr — APPROVED** [review]
Works as expected, @AjeshRPai 👍

Just noting down a minor glitch: with no site, the title disappears if I swipe down. But let's not block this PR because of it, we can add it as a `good first issue` and merge the PR.

https://user-images.githubusercontent.com/1405144/161202584-1b966578-499e-45f5-8213-74251ef664b2.mp4

**Comment by AjeshRPai** [comment]
@ashiagr , Thanks for the review. 

>Just noting down a minor glitch: with no site, the title disappears if I swipe down. But let's not block this PR because of it, we can add it as a good first issue and merge the PR.

Agreed. I have added this issue [here](https://github.com/wordpress-mobile/WordPress-Android/issues/16226)

**Comment by ashiagr** [comment]
Thanks @AjeshRPai! I'll merge the PR now.

**Pull request merged**
