### PR TITLE
Track if tags are added or not in Post Settings

### LINKED ISSUE #11401: Track when tags aren't added in Post Settings
### Expected behavior
When the user doesn't add a tag, the associated tracks event should be set to `false`. 

### Actual behavior
Currently, only when tags are added the is the the `with_tags` property added to the post analytics object. 

### Steps to reproduce the behavior
1. Create a new post. 
2. Don't add any tags and publish the post. 
3. You will see that the `false` value isn't pushed; only `true` occurrences exist. 
4. You can then redo this process and add a tag to the post and it should be shown. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #11401

## Solution
Tracks if tags are added or not by checking the tags contained in the `PostModel`. 

## Testing
1. Create a new post. 
2. Go to post settings. 
3. Add a tag. 
4. Publish post. 
5. Check to ensure the event was tracked as `with_tags` = `true` 
6. Repeat steps 1 - 5 but skip step 3. 
7. Check to ensure the event was tracked as `with_tags` = `false`

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@jd-alexander This draft PR is targeting `release/14.3` but it doesn't look like it's marked ready for review nor asked for a review by a specific developer. When you are targeting a release branch, please make sure you're doing everything you can to get it to be merged as soon as possible. The later a merge is the riskier it is.

In this case, it looks like this is not an urgent fix, so please update your target branch to `develop` or `release/14.4` which will be available later today. Since you previously targeted a release branch, I am bumping the milestone to `14.4` but please update it to `14.5` if you decide to merge to `develop`.

**Comment by jd-alexander** [comment]
@oguzkocer thanks! Yes, we were supposed to look into it during the meetup but that didn't happen. Will modify it now.

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.6` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.5` branch which will be available later today and update the milestone for the issue accordingly.

---

@jd-alexander Another reminder to make sure to ask a review from a developer or to add a comment explaining what's currently holding up this PR. Thanks!

**Comment by jd-alexander** [comment]
Thanks @oguzkocer 
I will get it reviewed.

**Comment by jd-alexander** [comment]
@oguzkocer I saw that you did a version bump. I am still new to how the release process bumping works in some cases so could you share a bit more. Thanks much 😄

**Comment by oguzkocer** [comment]
@jd-alexander I am not entirely sure what you're asking, but we are on a 2 week release cycle. With 3 versions to keep in mind:
* **Production:** Currently released version (14.4)
* **Beta:** Frozen branch which should only be targeted for fixes and only when it's absolutely necessary. (14.5)
* **Develop:** Whatever is merged to develop will be frozen in 14.6 in ~2 weeks and released 2 weeks after that

Ideally developers keep track of their PRs and set the milestone for when the PRs will land. Just before we freeze the next version, we ping developers that we bumped it to the next release, but if they feel that it should be released sooner, they can target the release branch instead, which would be `release/14.5` right now. We strongly discourage doing this especially in the second week of a frozen branch because that leaves very little time for testing and might end up causing more issues than it's fixing it.

We use the milestones to figure out the PR list for that release, check the release note and see if that matches the PRs and also add them to the release announcement post. Therefore, it's important for the milestone set for a PR to be correct.

Does that answer your question?

_P.S: I am still trying to figure out the best messaging for the version bump and we want to automate this because it takes quite a bit of time especially if we go into look what's happening with the PR, which I do. I also personally ping people to make sure a PR is not forgotten if it hasn't been updated in a while._

**Comment by malinajirka** [comment]
Thanks @jd-alexander! The code works as you described. However, I noticed there are several more attributes ('with_XYZ') in the surrounding code. We might want to consider changing all of them. Wdyt? 

Also, I'm not entirely sure it's a bug per-se. I think the author wanted to include the attribute only when it's true (in other words when the attribute is missing, it means false). I see your point and I agree it seems better to always include the attribute with true/false. Having said that I'm not 100% convinced it's a good idea to change how the event behaves now. Because we'll still need to account for the missing attributes in our Track's queries, right? 
For example, if I'd run a query `with_tag==false` it'd return only results since this change, right? I'd need to run `with_tag==null || with_tag==false` to get the correct result. So I'm a bit afraid the change might make it less convenient. Wdyt? (What is your opinion about this @oguzkocer ?)


>I saw that you did a version bump.

Do you mean [this commit](https://github.com/wordpress-mobile/WordPress-Android/pull/11402/commits/a7ff77b03b512915a076efba332044760feb77d6)? I think we just need to merge develop into this branch for it to disappear from the change set of this PR.

**Comment by oguzkocer** [comment]
> For example, if I'd run a query with_tag==false it'd return only results since this change, right? I'd need to run with_tag==null || with_tag==false to get the correct result. So I'm a bit afraid the change might make it less convenient.

I agree with @malinajirka.

> Do you mean this commit? I think we just need to merge develop into this branch for it to disappear from the change set of this PR.

Oh.. What Jirka said. It looks like you branched from `release/14.3` and then changed to `develop`, so the diff generated is not correct. It would probably go away if you change the base branch to some other branch and then back to `develop`, because the current `develop` version is definitely ahead of what this diff is showing.

Also, @jd-alexander Just as a general thing, I never push commits to other people's branches. If I really want to make a change in a branch that doesn't belong to me, I'll open a PR against that branch instead. The only exception to this, that I can remember, was sometimes I'd push some commits to Jirka's branch and he would push into mine on some things we worked on together, but this was after we explicitly talked about it.

**Comment by jd-alexander** [comment]
> Oh.. What Jirka said. It looks like you branched from release/14.3 and then changed to develop, so the diff generated is not correct. It would probably go away if you change the base branch to some other branch and then back to develop, because the current develop version is definitely ahead of what this diff is showing.

Okay great! 

> Also, @jd-alexander Just as a general thing, I never push commits to other people's branches. If I really want to make a change in a branch that doesn't belong to me, I'll open a PR against that branch instead. The only exception to this, that I can remember, was sometimes I'd push some commits to Jirka's branch and he would push into mine on some things we worked on together, but this was after we explicitly talked about it.

Thanks for the explanation @oguzkocer 😉I know you wouldn't do that for sure and that's why I asked for some details about it because I know it was something possibly related to the release branch targetting I was doing 😄 

Again, thanks for sharing all of the explanations on the branching process. I really appreciate it.

**Comment by jd-alexander** [comment]
Thanks for the review on the issue @oguzkocer @malinajirka I made this change because it seemed the false reports weren't being made in Tracks so this has to be explicitly done and it was requested by Leandro that's currently working on the iOS implementation of pre-publishing nudges. I am going to reinvestigate just to verify this from a testing standpoint and share those findings here to verify this claim some more.

**Comment by jd-alexander** [comment]
Thanks for the review on the issue at hand @oguzkocer @malinajirka 

> Thanks @jd-alexander! The code works as you described. However, I noticed there are several more attributes ('with_XYZ') in the surrounding code. We might want to consider changing all of them. Wdyt?

> Also, I'm not entirely sure it's a bug per-se. I think the author wanted to include the attribute only when it's true (in other words when the attribute is missing, it means false). I see your point and I agree it seems better to always include the attribute with true/false. Having said that I'm not 100% convinced it's a good idea to change how the event behaves now. Because we'll still need to account for the missing attributes in our Track's queries, right?
For example, if I'd run a query with_tag==false it'd return only results since this change, right? I'd need to run with_tag==null || with_tag==false to get the correct result. So I'm a bit afraid the change might make it less convenient. Wdyt? (What is your opinion about this @oguzkocer ?)

I agree with this as well. To be clear, I mainly added this at the request of Leandro but I will be communicating to him that the `null` value is to be used as false in this case and indeed changing this event (along with the others) might not be beneficial to our queries/trends. Thank you both of your help with this 🙏

**Comment by jd-alexander** [comment]
Closing based on the discussion we had about this 🙏

**Pull request closed without merging**
