### PR TITLE
Issue/2732 tablet tabstrip

### LINKED ISSUE #2732: More Compact Tabs for Tablet UI?
I've seen a few apps that will compact the tabs and left-align them when in a tablet UI in landscape:

device-2015-05-19-153459

It appears that the material guidelines recommend this as well: http://www.google.com/design/spec/components/tabs.html#tabs-specs

Current look:
device-2015-05-19-154801

@joen and @drw158, any thoughts?

### PR DESCRIPTION
**Pull request by nbradbury**
Fix #2732 - The material guidelines are inconsistent about how to address this issue, as are Google's own apps, but I believe what works best is to follow this:

screen shot 2015-05-20 at 5 43 51 pm

So, when in landscape (on any device, not just tablets) the tabs are left-aligned and aligned with the left keyline (which in our app is the content). When in portrait, the tabs are distributed evenly. This is similar to how the stock Clock app handles things.

[Here are video demos](https://cloudup.com/cvBMoqV8dmh) of this PR in both portrait and landscape.

### CODE REVIEW

**Comment by daniloercoli** [comment]
In portrait:
Wonder why there is a space between the edge of the view and the tab edge:
screen shot 2015-05-22 at 10 41 07
Is this because the margin between the tab edge and view edge is more of  16dp?

**Comment by daniloercoli** [comment]
<blockquote>So, when in landscape (on any device, not just tablets) the tabs are left-aligned and aligned with the left keyline (which in our app is the content).</blockquote>
Maybe I''ve missed some discussions here, but why in ladscape you've decided to left align tabs?
In the guideline there are 2 options, left align and center align. With the latter that seems to be the recommended.

**Comment by nbradbury** [comment]
> Wonder why there is a space between the edge of the view and the edge of the tab:

The [tab guidelines](http://www.google.com/design/spec/components/tabs.html#tabs-specs) suggest aligning the tabs with the left keyline, which in our case is the tab content.

**Comment by nbradbury** [comment]
> Wonder why there is a space between the edge of the view and the edge of the tab

That space is the padding between the left edge and the content of each page.

> but why in ladscape you've decided to left align tabs?

Honestly, I could've gone either way on that. In the end it just felt more natural to keep them left-aligned with the content, but I could be easily convinced to change it.

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
