### PR TITLE
Issue/10646 material post settings

### LINKED ISSUE #11253: Implement Material theme on Post Settings
We should switch widgets used at Post Settings their material counterparts, remove color references where possible, and switch to using material textAppearance attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #11253

This PR moves post settings to the material theme and adds a Dark Mode support.

Most of the changes come from XML files, so do not be alarmed by the size.

Location activity is provided by OS as far as I'm aware, and outside of our styling reach.

comparison_post_settings

To test:
- Navigate to post settings and make sure all options and nested screens look ok in both light and dark modes.

You can change the app theme from App Settings.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by khaykov** [comment]
@mattmiklic Absolutely! Let me know what you think:

comparison_ps

**Comment by mattmiklic** [comment]
Looks good!

**Comment by ashiagr** [comment]
Hi @khaykov , I tested these changes. and everything looked great 👍. 

Would it be possible to switch pop up text fields for slug, excerpt, password fields as well to outlined ones?

| Slug | Excerpt | 
| ------ | ------------- | 
|  slug | excerpt |

**Comment by khaykov** [comment]
@jd-alexander @ashiagr Thank you so much for the review!
I fixed the category row height and updated the looks on input dialog.

[Image from Gyazo](https://gyazo.com/878ba94f540dd83feba5d440c8f669a1)

**Comment by khaykov** [comment]
Ah, good eye, @jd-alexander ! I fixed the padding :) 

Screenshot_1582171635

**Pull request merged**
