### PR TITLE
Issue/6115 sharing dialog rotation take2

### LINKED ISSUE #6115: Sharing: rotation closes settings dialog
* Tap Sharing on the My Site tab
* Tap Manage
* Tap any setting that opens a dialog
* Rotate the device
* The dialog disappears

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6115 - WPPrefView now uses a `DialogFragment` to avoid having the dialog disappear after rotating the device.

To test:

* Tap Sharing on the My Site tab
* Tap Manage
* Tap any of the first four settings (the ones that show a dialog)
* Rotate the device

Dialog should remain visible after rotation.

### CODE REVIEW

**Comment by daniloercoli** [comment]
I've got the following crash on Android 5.
```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.publicize.PublicizeListActivity}: java.lang.NullPointerException: Attempt to invoke direct method 'android.app.Dialog org.wordpress.android.widgets.WPPrefView.getDialog()' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:144)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke direct method 'android.app.Dialog org.wordpress.android.widgets.WPPrefView.getDialog()' on a null object reference
                                                                         at org.wordpress.android.widgets.WPPrefView.access$700(WPPrefView.java:37)
                                                                         at org.wordpress.android.widgets.WPPrefView$WPPrefDialogFragment.onCreateDialog(WPPrefView.java:457)
                                                                         at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                                         at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
                                                                         at android.app.Activity.performCreateCommon(Activity.java:5971)
                                                                         at android.app.Activity.performCreate(Activity.java:5978)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:144) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
```

**Comment by nbradbury** [comment]
@daniloercoli Did that crash happen after rotating the device?

**Comment by daniloercoli** [comment]
Yes, it happened when I rotated the device to land.

**Comment by nbradbury** [comment]
@daniloercoli I **think** you're using the wrong branch - there's another one for this issue which I meant to close (and just did). Make sure you use the branch that ends with "take2."

**Comment by daniloercoli** [comment]
Sorry about that, you're right. Testing the correct branch right away.

**Comment by daniloercoli** [comment]
Hope i'm testing the right branch now :) 

Not sure if this is related to this PR (and probably not) but I see this other crash now:
```
06-26 16:50:54.350 1893-1893/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.wordpress.android, PID: 1893
                                                                     java.lang.RuntimeException: Parcel: unable to marshal value org.wordpress.android.widgets.WPPrefView$PrefListItem@d8d1e50
                                                                         at android.os.Parcel.writeValue(Parcel.java:1337)
                                                                         at android.os.Parcel.writeList(Parcel.java:711)
                                                                         at android.os.Parcel.writeValue(Parcel.java:1284)
                                                                         at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                         at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                         at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                         at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                         at android.os.Parcel.writeValue(Parcel.java:1259)
                                                                         at android.os.Parcel.writeSparseArray(Parcel.java:751)
                                                                         at android.os.Parcel.writeValue(Parcel.java:1287)
                                                                         at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                         at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                         at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                         at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                         at android.app.FragmentState.writeToParcel(Fragment.java:139)
                                                                         at android.os.Parcel.writeTypedArray(Parcel.java:1191)
                                                                         at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
                                                                         at android.os.Parcel.writeParcelable(Parcel.java:1357)
                                                                         at android.os.Parcel.writeValue(Parcel.java:1262)
                                                                         at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                         at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                         at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                         at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                         at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2895)
                                                                         at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

It happens when I tap the `home` button (Doen't matter if the dialog is on the screen or not).
- Tap Sharing on the My Site tab
- Tap Manage
- Tap Home

**Comment by nbradbury** [comment]
Yuck, I'm able to repro that on an API 21 emulator :( I don't think that's due to the changes in this PR but I'll go ahead and tackle that as part of this PR.

**Comment by nbradbury** [comment]
@daniloercoli I fixed that crash in 11f9c03, ready for another round!

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
