### PR TITLE
Fix Post updated when opening and closing the editor

### LINKED ISSUE #6382: Opening/closing the editor produces Post to be updated
### Expected behavior
Editing a Post and leaving it unchanged should just leave it as it was.

### Actual behavior
We trigger ‘local changes’ when just opening and closing the editor

### Steps to reproduce the behavior
1. enter a post that has images in it
2. just exit the editor without modifying anything
3. the post is sent online

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6382

This PR checks whether the Title or Post content of a `PostModel` differ from the current PostModel values before trying to set them up, and checks if they have been changed in order to know whether this Post should or should not be updated.

To test:
1. Go to the Posts list and start a new draft
2. Write a title and some content
3. Exit the editor, and see the post be uploaded
4. Tap on the recently uploaded post
5. Exit the editor without modifying anything
6. Observe the Post is not re-uploaded unnecessarily

cc @aforcier

### CODE REVIEW

**Comment by aforcier** [comment]
@mzorz The post is still uploading for me when I follow your steps. Though, once a post has been uploaded twice, it no longer gets incorrectly uploaded after that.

**Comment by mzorz** [comment]
> The post is still uploading for me when I follow your steps. Though, once a post has been uploaded twice, it no longer gets incorrectly uploaded after that.

Sorry for not catching this one before your tests @aforcier!  addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/6393/commits/6e495c74fb2a2a480049d1b19c57cdcb75cd3982

Ready for another round 👍

**Comment by aforcier** [comment]
@mzorz the original issue is fixed, but there's a new bug now, some UTC tomfoolery:

0. Be in a UTC- timezone
1. Start a new post
2. Enter title and content, and exit the editor
3. Post should be saved as a remote draft
4. Publish the post (press 'Publish' from the post list)
5. Notice the post is `Scheduled`, because the publish date was set to the current time in UTC, and then converted to your local timezone (so for me, scheduled 4 hours in the future)

**Comment by mzorz** [comment]
Good catch 😥 @aforcier , after considering this a bit decided to revert all commits related to UTC changes I made recently, which were supposed to be harmless but proved otherwise.
- revert this commit https://github.com/wordpress-mobile/WordPress-Android/pull/6392/commits/614ebc7a87c69e67d8f38ea99418ab128db309bd, which was introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/6392
- revert this commit https://github.com/wordpress-mobile/WordPress-Android/pull/6393/commits/b6229fcef5a8f5a2ac4c82d3f3678ef283a36ab8, which was introduced in this PR

Would you give it another round please? thanks 🙇

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
