### PR TITLE
Stories: Update library hash to fix font ANR issue

### LINKED ISSUE #13693: ApplicationNotResponding: in FontResolver in Stories
Sentry Issue: [WORDPRESS-ANDROID-120C](https://sentry.io/share/issue/796af984441d4fb3b4fdefbcdda55dbb/)

This is happening when loading fonts in Stories, perhaps we can try force pre-loading them somehow in the background instead of waiting until the TextDialog appears (when the user needs it)?

```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 5000 ms.
    at android.os.BinderProxy.transactNative(BinderProxy.java)
    at android.os.BinderProxy.transact(BinderProxy.java:578)
    at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
    at android.content.ContentResolver.query(ContentResolver.java:951)
    at android.content.ContentResolver.query(ContentResolver.java:887)
    at androidx.core.provider.FontsContractCompat.getFontFromProvider(FontsContractCompat.java:835)
    at androidx.core.provider.FontsContractCompat.fetchFonts(FontsContractCompat.java:733)
    at androidx.core.provider.FontsContractCompat.getFontInternal(FontsContractCompat.java:184)
    at androidx.core.provider.FontsContractCompat.getFontSync(FontsContractCompat.java:243)
    at androidx.core.graphics.TypefaceCompat.createFromResourcesFamilyXml(TypefaceCompat.java:117)
    at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:426)
    at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:372)
    at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:241)
    at com.wordpress.stories.compose.text.TextStyleGroupManager$Companion.getFontWithFallback(TextStyleGroupManager.kt:236)
    at com.wordpress.stories.compose.text.TextStyleGroupManager$Companion.resolveTypeface(TextStyleGroupManager.kt:229)
    at com.wordpress.stories.compose.text.TextStyleGroupManager$Companion.access$resolveTypeface(TextStyleGroupManager.kt:210)
    at com.wordpress.stories.compose.text.TextStyleGroupManager.getFont(TextStyleGroupManager.kt:108)
    at com.wordpress.stories.compose.text.TextStyleGroupManager.<init>(TextStyleGroupManager.kt:99)
    at com.wordpress.stories.compose.text.TextEditorDialogFragment.onAttach(TextEditorDialogFragment.kt:54)
    at androidx.fragment.app.Fragment.performAttach(Fragment.java:2673)
    at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1182)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
    at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:7948)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)```

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #13693 by incorporating the fix in the stories library (https://github.com/Automattic/stories-android/pull/639).

### To test:

The only functionality change has already been tested in the above PR.

However, the Ruby changes from https://github.com/Automattic/stories-android/pull/635 are also included in the hash update. They shouldn't affect anything, but confirm the app builds.

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mzorz** [comment]
Just updated the branch with base `develop` as the Detekt [lint issue](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/21306/workflows/127f9ddb-36aa-41d5-8c6f-516dde24988f/jobs/95952) was resolved [there](https://github.com/wordpress-mobile/WordPress-Android/pull/14067) 👍

**Comment by mzorz** [comment]
The current (new) [linter issue](https://circleci.com/gh/wordpress-mobile/WordPress-Android/96022?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on this PR:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/circleci/project/libs/stories-android/stories/build.gradle' line: 77

* What went wrong:
Could not determine the dependencies of task ':libs:stories-android:stories:preBuild'.
> Could not create task ':libs:stories-android:stories:createBuildConfigFieldsFromProperties'.
   > Could not find method loadGradleProperties() for arguments [] on root project 'project' of type org.gradle.api.Project.
```

should be resolved with this other PR in the Stories library repo https://github.com/Automattic/stories-android/pull/640. Once we merge that one we can update the commit hash on this very PR and merge once all turns green @aforcier 👍

**Comment by mzorz** [comment]
I was having local issues with the linter on `develop` and on this branch locally so, went ahead and tested the aforementioned fix on a new test branch and it seems the linter there on CI runs well https://github.com/wordpress-mobile/WordPress-Android/pull/14072 - just making a note here 👍

**Comment by aforcier** [comment]
Thanks @mzorz! I updated to the latest stories hash after merging https://github.com/Automattic/stories-android/pull/640. That still failed CI due to some ruby issues, I updated again to latest WPAndroid `develop` and it looks clear now, ready for another look 😅

**Review by mzorz — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
