### PR TITLE
Issue/11911 Open post for editing using intents

### LINKED ISSUE #11911: Feature request: Open post for editing using intents
### Expected behavior

The app currently handles intents with `wordpress://post` and `https://wordpress.com/post` URI to open the post editor with a new blank post. In the case of second URI, it optionally takes a `blog_id` or `blogname` as parameter in the pathname, e.g. `https://wordpress.com/post/1231`. If blog_id is present, the new post is created for that site, else for the currently selected site.

The reference code is here: The reference code starts here: https://github.com/wordpress-mobile/WordPress-Android/blob/31cf4fe3094ddf13a86dfdbfdc2455564314652d/WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java#L133

### Requested behavior

Allow specification of a post_id as additional parameter in both these URI to enable opening of a specific post for editing. 

E.g., the URI below would open post with id `786` on site with id `1231` for editing:

`wordpress://post/blog_id=1231&post_id=786`
`https://wordpress.com/post/1231/786`

##### Similar behaviour is already present for viewing a post in the app:

`wordpress://viewpost/blog_id=1231&post_id=786`

---

Following up from feedback by @maxme here https://github.com/wordpress-mobile/WordPress-Android/pull/11550#issuecomment-627168327_

### PR DESCRIPTION
**Pull request by adityabhaskar**
Adds functionality to edit a post or create a new post on a specific site using deep links.

Fixes #11911 

# To test:

Use the adb command to open app with deep link intents.

```shell
adb shell am start \
 -W -a android.intent.action.VIEW \
 -c android.intent.category.BROWSABLE \
 -d "<Insert test link from below>"
```

## Test links

Links marked with * are already handled by the app, the action should stay same as before.

Deep linking with custom scheme
1. `wordpress://post?blogId=177737282\&postId=37`
    - should open post for editing
2. `wordpress://post?blogId=177737282\&postId=wrongPostId`
    - should open a blank new post for given site
    - should show a toast about post not found
3. `wordpress://post?blogId=177737282`
    - should open a blank new post for given site
4. `wordpress://post?blogId=wrongBlogId`
    - should open a blank new post for currently selected site
    - should show a toast about site not found
5. `wordpress://post?postId=37`
    - should open a blank new post for currently selected site
6. \* `wordpress://post`
    - should open a blank new post for currently selected site

Deep linking with normal web url

7. `https://wordpress.com/post/testsite650835620.wordpress.com/37`
    - should open post for editing
8. `https://wordpress.com/post/testsite650835620.wordpress.com/wrongPostId`
    - should open a blank new post for given site
    - should show a toast about post not found
9. \* `https://wordpress.com/post/testsite650835620.wordpress.com/`
    - should open a blank new post for given site
10. \*  `https://wordpress.com/post/wrong-hostname`
    - should open a blank new post for currently selected site
    - should show a toast about site not found
11. \*  `https://wordpress.com/post/`
    - should open the browser, not the app

## Unhandled condition

If the post exists on server but not in the local `PostStore`, the app will act as if the post doesn't exist. The app behaviour will then follow # 2 above instead of # 1. This may be expected behaviour, so not addressing it.

One solution for this condition could be to sync posts with server if `remotePostId` not found in local `PostStore`, and try to find post again. This will, however, add a user noticeable delay in opening the post and may not be good UX.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by maxme** [comment]
Thank you for working on this @adityabhaskar! I'll review this next week.

> One solution for this condition could be to sync posts with server if remotePostId not found in local PostStore, and try to find post again. This will, however, add a user noticeable delay in opening the post and may not be good UX.

I think we should do the extra steps and implement fetching the post from the server if it's not found locally. We can show a loading indicator in this case. I'll check how this can be done when I'm reviewing the PR.

**Comment by zwarm** [comment]
@adityabhaskar - So far all looks good. Can you please resolve the conflicts and then I will proceed with testing. Thanks.

**Comment by adityabhaskar** [comment]
Hi @zwarm, I've resolved the conflicts from your updates. Look forward to feedback from testing.

Cheers!

**Comment by zwarm** [comment]
@adityabhaskar - It is all working as expected. I agree with 

> I think we should do the extra steps and implement fetching the post from the server

We are still working on how to implement the loading indicator. Will update as soon as we have possible solution. Thanks.

**Comment by adityabhaskar** [comment]
If we implemented a splash screen, it'd take care of some of the fetching delay. It would also help me work on this long pending issue #11380 :)

**Comment by zwarm** [comment]
@adityabhaskar - Thanks for your patience.

We have made the decision to move forward with the PR as written. A new issue will be created for fetching the post if it doesn't exist locally, as implementing a loading indicator will need design work before we can move forward. 

The action to call for actually fetching the Post is `fetchPost`. You can take a look at that here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/75050e8e588c95ea5ba836194ece8aa0011b8472/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L620


> If we implemented a splash screen

An interesting solution, but at this time it's not the direction we are moving towards. 

The only thing left before I can merge is the removal of the libs/gutenberg-mobile changes.

Nice work!

**Comment by adityabhaskar** [comment]
Hi @zwarm, thanks for the review and feedback. I've removed the submodule update, so it should be ready to go. 

It was this instruction in [the readme](https://github.com/wordpress-mobile/WordPress-Android#build-instructions) that caused the submodule update:

> 5. `git submodule update --init --recursive` to pull the submodules (optionally use `--depth=1 --recommend-shallow` flags to skip pulling full submodules' history).

I'm not sure how it got pushed though.

Thanks again for the review, and please let me know here if you want me to work on a splash screen, or on adding the post loading once design is ready.

Cheers!

Adi

**Pull request merged**
