### PR TITLE
Issue/6409 reader jetpack excerpt

### LINKED ISSUE #6409: Reader post detail should show the RSS excerpt (if any) for Jetpack sites
Calypso applies a special treatment for Jetpack posts from sites that have RSS excerpts enabled. It only shows the excerpt and the featured image, if any, and shows a notice `Visit SITE_NAME for the full post.`.

Example of this kind of post: https://wordpress.com/read/blogs/67272686/posts/7751

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6409 - Changes the reader detail to show only excerpts for Jetpack posts that have them. Note the design of the "Visit Site Name for more" footer was approved by Derek (reader squad designer and lead).

To test:
* View this post in Calypso reader https://wordpress.com/read/blogs/67272686/posts/7751
* Like the post
* Open the Android reader to "Posts I Like" and view the post detail for the above post

screenshot_1502391413

### CODE REVIEW

**Comment by daniloercoli** [comment]
Are we already using the `excerpt` field in the post list too? Excerpts are hand-crafted, and can be an arbitrary text, completely different from the post content. 
If we're not using `excerpts` in posts list, we can fall on a situation where the posts list shows part of the content of the post and the details screen uses the excerpt instead.

**Comment by nbradbury** [comment]
> Are we already using the excerpt field in the post list too?

Yes, we do use the excerpt in the post list - see [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java#L408).

**Comment by daniloercoli** [comment]
:man_facepalming: I tried by finding occurrences of `shouldShowExcerpt` and it did find only one. So the question.

**Comment by daniloercoli** [comment]
Looks good! :shipit:

**Pull request merged**
