### PR TITLE
Upgrade Gradle to 5.4.1 & Gradle plugin to 3.5.1

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR upgrades Gradle version to 5.4.1 and Gradle plugin version to 3.5.1. While doing this upgrade I ended up having to upgrade WellSql https://github.com/wordpress-mobile/wellsql/pull/14 and FluxC https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1397. I also had a lot of different build errors related to `Volley` and some other dependencies, so I added/upgraded/excluded related dependencies. I aimed for the smallest set of changes for this upgrade and this was the best I could get. Let me know if any of these changes don't make sense or unnecessary.

I am opening this PR as a Draft PR since it depends on the linked FluxC PR and we'll need to update the FluxC version before we can merge this PR.

**To test:**
Do a clean build and make sure the app builds and works as expected.

**PR submission checklist:**

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
@malinajirka If you have any extra time, do you think you could take a look at the [test issue](https://circleci.com/gh/wordpress-mobile/WordPress-Android/22588?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). I have looked into it and it looks like it's related to Robolectric version, however upgrading that creates [another issue](https://github.com/robolectric/robolectric/issues/5147). Once I manually add the `guava` dependency, I get yet [another issue](https://github.com/robolectric/robolectric/issues/4026). I tried to use a different version, but had no luck with that either.

I think this might be the last step to upgrade the Gradle version. We have some lint issues, but they seem rather straightforward to fix, although there are quite a few of them, so I am thinking we do that in a separate PR first.

**Comment by malinajirka** [comment]
Thanks Oguz! ;) The current change set LGTM!

I've updated Robolectric version to 4.3. When I run `./gradlew --stacktrace testVanillaRelease` locally it passes. However, the CI seems to timeout - perhaps when downloading ("Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar" - it took quite some time on my machine).

Regarding the lint issues
UseSparseArrays - I'd consider suppressing this warning at a project level or decreasing its severity to info. Sparse arrays can cause weird behavior in unit tests and imho the performance benefit isn't significant anyway. Wdyt?

StaticFieldLeak - This set of errors is pretty weird as they should be suppressed through the `lint-baseline.xml`. Not sure what's going on there 🤷‍♂ 

 DefaultLocale, DiffUtilEquals - These seem like issues we should probably fix 🤔 

@maxme @hypest I'm not sure how much related this is, but just to be safe. Could you please confirm these changes won't break the Gutenberg development flow. Thanks!

**Comment by malinajirka** [comment]
>However, the CI seems to timeout - perhaps when downloading ("Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar" - it took quite some time on my machine).

I've temporarily increased the no output timeout to 30 minutes so the CI would have enough time to download the file and store it into a cache. It seems that it worked as expected, so the only thing left is fixing the lint issues ;).

**Comment by oguzkocer** [comment]
Thank you for your help @malinajirka! 🙇 I've separated the lint PR https://github.com/wordpress-mobile/WordPress-Android/pull/10593, let's discuss the issues there and merged it into this branch when it's ready.

**Comment by mchowning** [comment]
:wave: @malinajirka and @oguzkocer ! This is great! Thanks for taking this on.

I am seeing a build failure from this branch when I run `./gradlew assembleWasabiDebug` with  `wp.BUILD_GUTENBERG_FROM_SOURCE=true` in gradle.properties. We use this flag for development of gutenberg to see gutenberg changes in WPAndroid. The error I'm seeing seems to be the result of it not being able to find the `AppLog` class for some reason.

<details><summary>Build error logs</summary>

```
> Task :react-native-gutenberg-bridge:compileDebugJavaWithJavac FAILED

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:35: error: cannot find symbol
import org.wordpress.android.util.AppLog;
                                 ^
  symbol:   class AppLog
  location: package org.wordpress.android.util

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:236: error: package AppLog does not exist
                        AppLog.d(AppLog.T.EDITOR, message);
                                       ^

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:236: error: cannot find symbol
                        AppLog.d(AppLog.T.EDITOR, message);
                        ^
  symbol: variable AppLog

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:239: error: package AppLog does not exist
                        AppLog.i(AppLog.T.EDITOR, message);
                                       ^

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:239: error: cannot find symbol
                        AppLog.i(AppLog.T.EDITOR, message);
                        ^
  symbol: variable AppLog

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:242: error: package AppLog does not exist
                        AppLog.w(AppLog.T.EDITOR, message);
                                       ^

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:242: error: cannot find symbol
                        AppLog.w(AppLog.T.EDITOR, message);
                        ^
  symbol: variable AppLog

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:245: error: package AppLog does not exist
                        AppLog.e(AppLog.T.EDITOR, message);
                                       ^

/Users/matt/dev/a8c/WordPress-Android/libs/gutenberg-mobile/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java:245: error: cannot find symbol
                        AppLog.e(AppLog.T.EDITOR, message);
                        ^
  symbol: variable AppLog
```

</details>

I have seen an error similar to this in a different context, so it is possible there is something going on with my setup, but I don't see this error when I build off of `develop` so I don't think it's just me. With that said, it wouldn't be a bad idea to verify that someone else is seeing the same issue when they build on their machine. 

I am still in support rotation today, so I can't dig into this now, but I would be happy to take a closer look at this on Monday if you'd like.

**Comment by mchowning** [comment]
Following up on the issue with building gutenberg from source enabled. I merged [a fix for that](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1451) that will be included in the gutenberg-mobile release that _should_ get merged into the `develop` branches for both WPAndroid and mogile-gutenberg this Friday. After that, we will be able to build gutenberg from source with this PR. 

**If you would like to merge this sooner (i.e., this week), just let me know.** I'll just need to do two quick things to make that possible:

1. Update the gutenberg-mobile submodule ref in this PR so that my fix from gutenberg-mobile is included (may also need to merge in the latest changes from `develop` into this PR in order to avoid a merge conflict with my change to the submodule ref); and
2. Merge my fix into the gutenberg-mobile `develop` branch so that anyone doing development this week has my fix.

**Comment by maxme** [comment]
Thanks for checking the gutenberg flow @mchowning, and thanks @oguzkocer for doing this change.

**Pull request merged**
