### PR TITLE
Change "∞" symbol with "100%" on stats

### LINKED ISSUE #17314: "(∞)" shouldn't be used for infinite percentages in stats screens
### Expected behavior
When the percentage is `∞` for data in stats screens, we should only show the increase.
expected

### Actual behavior
When the percentage is `∞` for data in stats screens, it shows `(∞)`.
actual

### Steps to reproduce the behavior
1. Launch the Jetpack app. (WordPress app has the same issue too, but Jetpack has more places showing `(∞)`.)
2. Open Stats from "My Site → HOME → Stats" it "My Site → MENU → Stats".
3. If the Views & Visitors card is not added to the screen, add it by using ⚙️ button at the top end of the screen.
4. Find a case which "Previous Week" had 0 views, and "This week" has more than 0 views.
5. Notice `(∞)` is being shown as the percentage.

The problem is also on Total Likes card, Total Comments card, and the bar chart on DAYS, WEEKS, MONTHS, YEARS tabs.

### PR DESCRIPTION
**Pull request by irfano**
Fixes #17314 

This changes "∞" symbol with "100%" on stats. The issue description states removing "∞" symbol but this PR changes it to "%100" and matches this behavior with the web. 

|before|after|
|-|-|
|||
|||

-----

## To Test:

1. Log in.
2. Open "My Site → Stats"
3. Select the INSIGHTS tab. 
4. Select a date that has 0 views for the previous date on Views & Visitors card.
5. Verify that the data shows "%100" instead of "∞".
6. Repeat the same test for total cards.
7. Repeat the same test for the Overview card on granular tabs.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - Updated `StatsUtilsTest`.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/280">24.6</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by aditi-bhatia — APPROVED** [review]
This change definitely makes more sense 👍 LGTM

**Comment by aditi-bhatia** [comment]
@irfano Just wanted to double check, it looks like the 24.6 code freeze is today. Do you know if it's already begun / if this PR will be going into 24.6 or 24.7? I see the update to `Release Notes` mentions 24.7 and want to make sure the version is correct if merged today.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/280">24.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
> @irfano Just wanted to double check, it looks like the 24.6 code freeze is today. Do you know if it's already begun / if this PR will be going into 24.6 or 24.7? I see the update to Release Notes mentions 24.7 and want to make sure the version is correct if merged today.

I initially thought we couldn't merge this before the 24.6 code freeze. However, since the code freeze didn't happen yesterday, Ravi already updated the version in the release notes and merged it into `24.6`. Thank you both!

**Pull request merged**
