### PR TITLE
Issue/7996 actionable empty states (Part 1)

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add the actionable empty state view class, [`ActionableEmptyView`](), and implement a single instance of the actionable empty states described in https://github.com/wordpress-mobile/WordPress-Android/issues/7996.  Only one instance is included in this pull request to show the new class in action and keep the changeset small.  The remaining actionable empty states  in https://github.com/wordpress-mobile/WordPress-Android/issues/7996 will be included in a subsequent pull request.  See the screenshots below for illustration.

aes_media

### Test
1. Go to ***My Site*** tab.
2. Tap ***Media*** item under ***Publish*** section.
3. Tap ***All***, ***Images***, ***Documents***, ***Videos***, and ***Audio*** tabs.
4. Notice empty view when no media is present.
5. Tap ***Upload Media*** button.
6. Notice new media popup menu.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looking good!

Does the text area have a maximum width? Also what does it look like with a long text string there (3 lines)?

**Comment by theck13** [comment]
> Does the text area have a maximum width?

The title and subtitle (not shown in the screenshots above) have a [maximum width of `300dp`](https://github.com/wordpress-mobile/WordPress-Android/pull/8055/files#diff-a38f8955f26ed07cc283ff53e02b57dbR321) and a [horizontal margin of `30dp`](https://github.com/wordpress-mobile/WordPress-Android/pull/8055/files#diff-a38f8955f26ed07cc283ff53e02b57dbR320).

> Also what does it look like with a long text string there (3 lines)?

Here's what the title looks like with a long text string of three lines.

aes_media_lines

**Comment by SylvesterWilmott** [comment]
Looks great @theck13 !

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
