### PR TITLE
[Reader IA] Subscribing to tag doesn't update the chip count 

### LINKED ISSUE #20012: [Reader IA][Bug] Subscribing/Unsubscribing to a tag should auto-update tag filter pill in Subscriptions feed
### Expected behavior
When the "Subscriptions" feed is open, subscribing or unsubscribing to a tag in the "Manage subscription" screen, and going back to the feed, should cause the tag filter pill to refresh and use the latest tag count.

### Actual behavior
When the "Subscriptions" feed is open, subscribing or unsubscribing to a tag in the "Manage subscription" screen, and going back to the feed, doesn't update the tag filter pill until a refresh happens (pull or tapping on the pill).

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/da4880ce-2fc2-4168-8194-ac15f298ed25

### Steps to reproduce the behavior
1. Install and log into Jetpack on a `feature/reader-ia` branch build
2. Go to Reader
3. Go to the Subscriptions feed
4. Tap the Tag filter pill
5. Follow/Unfollow a tag
6. Go back to reach the Subscriptions feed again
7. **Verify** the screen was not updated (incorrect number of subscribed tags)

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #20012 

-----

## To Test

1. Install Jetpack and sign in;
2. Open Reader;
3. Open the drop-down menu and tap on `Subscriptions` feed;
4. Tap the tags pill;
5. Subscribe to a tag;
6. Go back to reach the Subscriptions feed again
7. Verify the number of tags is shown correctly
8. Repeat steps 4-7 but this time unsubscribe from a tag.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    --
-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by daniloercoli** [comment]
Unfortunately, the tag count does not update immediately when I subscribe to a new tag. As shown in the recording, the count only changes from 16 to 17 tags after I initiate a manual pull-to-refresh.

https://github.com/wordpress-mobile/WordPress-Android/assets/518232/c2352e4d-7752-4ca4-988e-f037cd7c2410

**Comment by RenanLukas** [comment]
Thanks for the review, @daniloercoli 👍 

After some trial and error I think I've managed to make the behavior of adding a new tag to be exactly like iOS, which means the latest added tag won't be shown as selected when you navigate from manage blogs & tags screen back to the feed.

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/ee063571-5af6-4e14-bbf7-6bcd4979fbfc

It seems like this change have fixed the issue you were facing, but please let me know if it still continues to happen.

**Comment by RenanLukas** [comment]
I've added `Do not merge` until I confirm what should be the correct target branch.

**Review by daniloercoli — APPROVED** [review]
Works as expected. LGTM!

**Comment by RenanLukas** [comment]
Merging to `release/24.2`. See p1707227033739459-slack-CC7L49W13

**Review by daniloercoli — APPROVED** [review]

**Pull request merged**
