### PR TITLE
Feature/3578 delete site start over

### PR DESCRIPTION
**Pull request by kwonye**
Addresses #3578 

screenshot_20160112-144937

When a user selects "Start Over", then "Contact Support", they go to HelpShift where they can ask to have their site reset.

Needs review: @aforcier

### CODE REVIEW

**Comment by kwonye** [comment]
Not ready to merge until decision about vector drawables are made.

**Comment by aforcier** [comment]
Found one display issue while testing older APIs. On API<21, `android:backgroundTint` isn't supported and the 'Contact Support' button doesn't have a background:

start-over-api18-button-issue

**Comment by kwonye** [comment]
> Found one display issue while testing older APIs. On API<21, android:backgroundTint isn't supported and the 'Contact Support' button doesn't have a background:

Thanks @aforcier, addressed in 25a1d94. Ready for merge now when you deem it :shipit:

**Comment by aforcier** [comment]
All good, nice work @kwonye :shipit:

**Pull request merged**
