### PR TITLE
Issue/10649 material reader post list

### PR DESCRIPTION
**Pull request by khaykov**
The first part of #10649

This PR moves Reader Post List and Tags & Sites to Material Theme and adds Dark Theme support. There are some code changes for cosmetic reasons. 

@develric @osullivanchris I would like to loop you guys in since this PR touches Subfilter, which is part of IA.

Reader without IA changes:

 comparison_reader_no_ia

With IA changes (alpha branch):

comparison_reader_post_list

To test:
- Navigate to Reader post list, and switch between different filters/subfilters. Make sure everything looks good in both light and dark themes.
- Navigate to Reader's Tags & Sites screen, and make sure everything looks good in both light and dark themes.

You can switch the theme from App Settings.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
Forgot to update selectors for like/comment buttons:
[Image from Gyazo](https://gyazo.com/b0be21cf0b953aa7c9d4a78118c7e1f8)

[Image from Gyazo](https://gyazo.com/9227e66edfbfa94df0d0b47ba2790fe6)

**Comment by mattmiklic** [comment]
> I find the absolute white on absolute black a little stark to read in large chunks. 

@khaykov could you double-check that we're using the High Emphasis On Surface color for the titles and body text in the Reader? In dark mode it should be 87% #FFFFFF so not quite as stark as full white on full black.

newcolors-dark-1

**Comment by khaykov** [comment]
@mattmiklic I updated post title, excerpt and menu icon colors to use High Emphasis alpha 👍 
comparison_reader_text

**Comment by mattmiklic** [comment]
I think that looks great. 👍

**Comment by osullivanchris** [comment]
Looks good!! One other small thing I'm noticing is the stroke around images. I am thinking we have a stroke for when an image is mostly white on white, or black on black, to show where the image ends and not just have something floating.

However the stroke looks _**a bit**_ strong to me. Should we use less emphasis?

**Comment by mattmiklic** [comment]
> However the stroke looks a bit strong to me. Should we use less emphasis?

Good catch, that should probably be darker/more subtle in dark mode.

**Comment by khaykov** [comment]
I totally missed that one! I changed the color to use disabled emphasis (medium one looks a bit too strong in light mode). WDYT?

comparison_reader_border

**Comment by mattmiklic** [comment]
That looks better for sure. Would it be possible to use the same color we use for the dividers between posts? It's a little more subtle and it'd be nice if it matched.

**Comment by khaykov** [comment]
@mattmiklic Sure thing! Looks like this:
comparison_reader_text

**Comment by mattmiklic** [comment]
I think that's just right. 👌

**Comment by khaykov** [comment]
Thanks for taking a look at this PR, @develric ! I tried to make the bottom text area look more like one used in comments, so it's a bit shorter, so it looks as expected :)

**Pull request merged**
