### PR TITLE
Merge Visual Editor

### PR DESCRIPTION
**Pull request by aforcier**
Merges the visual editor feature branch into `develop`. All commits have gone through previous PRs, except for https://github.com/wordpress-mobile/WordPress-Android/commit/8cb2a41e202a644d882e7a4f58016427337c7b1d and onward.

Includes all work on the editor up to and including [0.6](https://github.com/wordpress-mobile/WordPress-Editor-Android/milestones/0.6).

To build the editor, select the `zalpha` or `wasabi` build flavor (it's not enabled for `vanilla`).

### CODE REVIEW

**Comment by maxme** [comment]
- [x] upgrade from `vanilla release` to `zalpha release`
- [x] upgrade from `zalpha release` to `vanilla release` (in case someone leave the alpha)
- [x] make sure enable / disable links work
- [x] setting a featured image from the post settings
- [x] setting a featured image from the image settings
- [x] check wasabi variant has visual editor enabled
- [x] tap an uploading video (you get a "would you like to cancel" popup) wait for a video upload error to arrive and tap the cancel button (works, but I've encountered a weird state where both the error and the retry text were shown, we probably have a race condition here, will open a new issue if that happens again).

**Comment by maxme** [comment]
- [ ] delete a video using the backspace key on a virtual keyboard. Works on emulators (5.0, 4.2.2) / doesn't work on XPeria Z5 (5.1.1)
- [ ] Tap "Edit" on a published post, don't edit the post, tap back - get the "Local modification saved" Toast, but there is no local modifications.

**Comment by aforcier** [comment]
* Fixed a source of NPE in onMediaUploadFailed
* Made ZSSEditor responsible for flagging uploads as complete - this fixes an issue where it's possible to upload a post with local-url media if you press upload just before the local url is swapped for the remote one

**Comment by aforcier** [comment]
Updated to keep the format bar disabled when the device is rotated and the title field is selected.

**Comment by tonyr59h** [comment]
:shipit: :tada: :balloon: :fireworks:

**Comment by roundhill** [comment]
Is this real life?

**Pull request merged**
