### PR TITLE
Add some tooling for code freeze

### PR DESCRIPTION
**Pull request by loremattei**
This PR adds some Fastlane lanes to automate a part of the code freeze steps. The main goal is to avoid mistakes with version names, codes, etc. while issuing the various commands.

The script needs the name of the version to freeze and:
 - Pulls the develop branch from GH.
 - Verifies that the version in the `develop` branch is an `alpha` version.
 - Reads the `version code` from the alpha one.
 - Calculates the various version names and codes.
At the end of this process, it displays the results for approval. If something is miscalculated, the user can abort the script.
If everything is ok and the user confirms the operation, the script:
- Pulls the branches from GH.
- Create the new release branch.
- Updates the version strings.
- Protects the release branch on GH.

The script works only for the standard scenario. Corner cases will be handled in the classic way (there's usually little value in making overcomplicated script to handle corner cases).

Given the checks it performs, it should be tested within a real-life environment in order to have it work (you can tinker with other cases to verify the checks it performs).

To test:
1. General setup
1.1 Copy the `env.example` file to `~/.wpandroid-env.default`.
1.2 Generate a new GitHub personal access token and fill the `GHHEHLPER_ACCESS` field with it
1.3 Run `bundle install``

2. Test environment setup
The following test instructions are related to the current state of the repository where 11.1 is in code freeze and they will simulate the next code freeze (11.2).

2.1 please tag 11.1 in your release/11.1 branch (you will remove the tag later).

3. Code Freeze lane test
3.1 Run `bundle exec fastlane code_freeze codefreeze_version:11.2`.
3.2 Verify that it gets the version rights.
3.3 Confirm the operation to have it continue.
3.4 Verify that the version in the `release/11.1` branch has been correctly updated.
3.5 Verify that the version in the `develop` branch has been correctly updated.
3.6 Verify that the `release/11.2` branch has been correctly created and updated.
3.7 Verify that the `release/11.2` has been pushed to GH and it's protected.
3.8 Verify that the `11.2` milestone on GH has the frozen tag (the snowflake symbol)  in the title.
3.9 Verify that the `wpandroid_prs_list_11.1_11.2.txt` file has been created in your home, with the merged PRs list.

4. Clean up steps
After the test, please clean up the environment by reverting the operations performed by the script
4.1 Remove the branch protection for `release/11.2` branch on GH.
4.2 Delete the `release/11.2` branch on both GH and you local copy.
4.3 Remove the frozen tag from the title of the `11.2` milestone on GH.
4.4 Delete last commit from your local `develop` branch.
4.5 Delete last commit from your local `release/11.1` branch.

### CODE REVIEW

**Comment by mzorz** [comment]
Wow this is quite a piece - I'm sure it'll help in future releases! 🤖 
LGTM @loremattei , just a note for what I did, given the current freeze:

```
2.1 please tag 11.2 in your release/11.2 branch (you will remove the tag later).

Code Freeze lane test
3.1 Run bundle exec fast-lane code_freeze codefreeze_version:11.3.
+3.2 Verify that it gets the version rights.
3.3 Confirm the operation to have it continue.
+3.4 Verify that the version in the release/11.2 branch has been correctly updated.
+3.5 Verify that the version in the develop branch has been correctly updated.
+3.6 Verify that the release/11.3 branch has been correctly created and updated.
+3.7 Verify that the release/11.3 has been pushed to GH and it's protected.
+3.8 Verify that the 11.3 milestone on GH has the frozen tag (the snowflake symbol) in the title.
+3.9 Verify that the wpandroid_prs_list_11.2_11.3.txt file has been created in your home, with the merged PRs list.
```

The output for this was:

```
MacBook-Pro-5:WordPress-Android mariozorz$ bundle exec fastlane code_freeze codefreeze_version:11.3
+-----------------------------------+---------+-----------------------------------------+
|                                     Used plugins                                      |
+-----------------------------------+---------+-----------------------------------------+
| Plugin                            | Version | Action                                  |
+-----------------------------------+---------+-----------------------------------------+
| fastlane-plugin-wpmreleasetoolkit | 0.1.1   | gp_downloadmetadata setfrozentag        |
|                                   |         | promo_screenshots                       |
|                                   |         | gp_update_metadata_source get_prs_list  |
|                                   |         | setbranchprotection                     |
+-----------------------------------+---------+-----------------------------------------+

[12:31:13]: ------------------------------
[12:31:13]: --- Step: default_platform ---
[12:31:13]: ------------------------------
[12:31:13]: Driving the lane 'android code_freeze' 🚀
[12:31:13]: --------------------------------
[12:31:13]: --- Step: android_codefreeze ---
[12:31:13]: --------------------------------
[12:31:13]: Skip confirm on code freeze: false
[12:31:13]: Code freezing release: 11.3
[12:31:13]: Update release branch version: true
[12:31:13]: $ git checkout develop
[12:31:13]: ▸ Switched to branch 'develop'
[12:31:13]: ▸ Your branch is up to date with 'upstream/develop'.
[12:31:13]: $ git pull
[12:31:19]: ▸ Already up to date.
[12:31:19]: $ cat ./WordPress/build.gradle | grep versionName
[12:31:19]: ▸ versionName "alpha-135"
[12:31:19]: $ cat ./WordPress/build.gradle | grep versionCode
[12:31:19]: ▸ versionCode 636
[12:31:19]: $ git checkout release/11.2
[12:31:19]: ▸ Switched to branch 'release/11.2'
[12:31:19]: ▸ Your branch is up to date with 'upstream/release/11.2'.
[12:31:19]: $ git pull
[12:31:21]: ▸ Already up to date.
[12:31:21]: Building a new release branch starting from develop.
Version in develop is alpha-135 (code: 636).
After code freeze:
11.2 on branch release/11.2: version name: 11.2 - version code: 637.
New 11.3 on branch release/11.3: version name: 11.3-rc-1 - version code: 638.
New alpha on branch develop: version name: alpha-136 - version code: 639.
Do you want to continue?
 (y/n)
y
[12:31:28]: Git status is clean, all good! 💪
[12:31:28]: $ git checkout develop
[12:31:29]: ▸ Switched to branch 'develop'
[12:31:29]: ▸ Your branch is up to date with 'upstream/develop'.
[12:31:29]: $ git pull
[12:31:30]: ▸ Already up to date.
[12:31:30]: $ git checkout -b release/11.3
[12:31:30]: ▸ Switched to a new branch 'release/11.3'
[12:31:30]: $ git push --set-upstream origin release/11.3
[12:31:34]: ▸ remote:
[12:31:34]: ▸ remote: Create a pull request for 'release/11.3' on GitHub by visiting:
[12:31:34]: ▸ remote:      https://github.com/wordpress-mobile/WordPress-Android/pull/new/release/11.3
[12:31:34]: ▸ remote:
[12:31:34]: ▸ To https://github.com/wordpress-mobile/WordPress-Android.git
[12:31:34]: ▸ * [new branch]            release/11.3 -> release/11.3
[12:31:34]: ▸ Branch 'release/11.3' set up to track remote branch 'release/11.3' from 'origin'.
[12:31:34]: $ ./tools/update-release-names.sh 637 11.2 11.3-rc-1 alpha-136
[12:31:34]: ▸ Current version code: 637 - previous alpha version code: 636
[12:31:34]: ▸ Switching and pulling: release/11.2
[12:31:36]: ▸ Editing WordPress/build.gradle - name: 11.2 code: 637
[12:31:36]: ▸ Adding to git
[12:31:36]: ▸ Switching and pulling: release/11.3
[12:31:38]: ▸ Editing WordPress/build.gradle - name: 11.3-rc-1 code: 638
[12:31:38]: ▸ Adding to git
[12:31:38]: ▸ Switching and pulling: develop
[12:31:40]: ▸ Editing WordPress/build.gradle - name: alpha-136 code: 639
[12:31:40]: ▸ Adding to git
[12:31:40]: ---------------------------------
[12:31:40]: --- Step: setbranchprotection ---
[12:31:40]: ---------------------------------
[12:31:42]: Logged in as: 
WARNING: The preview version of the Branch_protection API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
[12:31:43]: --------------------------
[12:31:43]: --- Step: setfrozentag ---
[12:31:43]: --------------------------
[12:31:44]: Logged in as: 
true
[12:31:45]: New milestone: 11.3 ❄️
[12:31:46]: Logged in as: 
[12:31:47]: --------------------------
[12:31:47]: --- Step: get_prs_list ---
[12:31:47]: --------------------------
[12:31:47]: $ git log --pretty=oneline 11.2...
[12:31:47]: ▸ f0de61eb6d08f108508e15cce4a3ff383d0921c9 alpha-136 / 639 version bump
[12:31:47]: ▸ cb836699f395c861c5aa73b2d747ec918663c0f1 Merge pull request #8565 from wordpress-mobile/merge-release-11.2-into-develop
[12:31:47]: ▸ fe03b52b13a5881f9b81568c0b8e0d241ea24be6 Merge release/11.2 into develop
[12:31:47]: ▸ 13853532e0aaadcfea15472d08f9b2b67a5bf530 Merge pull request #8562 from wordpress-mobile/merge-release-11.1-into-develop
[12:31:47]: ▸ ddd843b9d2626fa4e8673243ecd58fb47f97901f Merge release/11.1 into develop
[12:31:47]: ▸ 08aeba510d0e0b3cd87df6ff085b215888571585 Merge pull request #8555 from wordpress-mobile/issue/8546-site-search
[12:31:47]: ▸ 39059a5f6e1c3254f3d8c010fef55d9c2fd8fe15 Only show the empty message when the actual list being displayed is empty
[12:31:47]: ▸ 9d1119f0efef5cd61ccfad597d4881332e819172 Do not hide the progress indicator if the post search is still in progress
[12:31:47]: ▸ 9c705577a6b0e57ff2ec330b770eb5a6e2afe88f Display the empty message based on the result for each list individually
[12:31:47]: ▸ b0b019654aaa298d29525a31277ed7ec618628a3 Fix the true cause for the issue - empty post list prevented the sites from being searched
[12:31:47]: ▸ 26e25a8e6004f6ede748c095bc8e8d1a12d88a18 To simplify the search logic, we will search both posts and sites at the same time
[12:31:47]: ▸ 0ed3acd728af593aace22a2c36df4c1a416ba8f2 Merge pull request #8527 from wordpress-mobile/feature/fix-fastlane-version
[12:31:47]: ▸ 9d6739235adbf655a3e5a40a7dad65be9fccbba2 alpha-135 / 636 version bump
[12:31:47]: ▸ 544e797b8f6ab01662d04be1adb391fe25025f08 Pin the fastlane version
[12:31:47]: Logged in as: 

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | android_codefreeze  | 27          |
| 3    | setbranchprotection | 3           |
| 4    | setfrozentag        | 3           |
| 5    | get_prs_list        | 4           |
+------+---------------------+-------------+

[12:31:51]: fastlane.tools finished successfully 🎉
MacBook-Pro-5:WordPress-Android mariozorz$
```

Then, after verifying everything, I went through the cleanup steps:

```
Clean up steps
After the test, please clean up the environment by reverting the operations performed by the script
+4.1 Remove the branch protection for release/11.3 branch on GH.
+4.2 Delete the release/11.3 branch on both GH and you local copy.
+4.3 Remove the frozen tag from the title of the 11.3 milestone on GH.
+4.4 Delete last commit from your local develop branch.
+4.5 Delete last commit from your local release/11.2 branch.
```

I also deleted the local `11.2` tag by issuing `git tag --delete 11.2` on my local repo.

There's a conflict in this PR currently, I think we can merge this after that gets resolved 👍 

:shipit:

**Comment by mzorz** [comment]
BTW I noticed this:
```
[12:31:42]: Logged in as: 
WARNING: The preview version of the Branch_protection API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
```
Do you think there's anything wrong with my local setup for the tests @loremattei ?

**Comment by loremattei** [comment]
@mzorz thank you very very much for going through this one!
I've pushed a commit to remove the conflict.

About the API Branch_protection warning: it is a known one. The script uses that API to set the branch protection for the release branch against accidental deletion and unreviewed PR merges. The worst thing that can happen if it should fail silently, it is that the branch doesn't get the protection, which means that it remains in its normal state. 
We don't use to protect the branch in this project, but since it's something that comes for free sharing the underlying fastlane plugin, I think it can be a nice add-on. So, if it fails, we don't lose anything.  

Does it make sense to you? We can surely remove that call if you think it's better to avoid using that API.

**Comment by mzorz** [comment]
> We don't use to protect the branch in this project, but since it's something that comes for free sharing the underlying fastlane plugin, I think it can be a nice add-on. So, if it fails, we don't lose anything.

Nice one! 

Merging it is, then 🎉

**Pull request merged**
