### PR TITLE
Update login library from subtree

### PR DESCRIPTION
**Pull request by aforcier**
Brings in the latest changes to the login library, imported from WooAndroid.

Changes:

* Two crash fixes: https://github.com/woocommerce/woocommerce-android/pull/413 and https://github.com/woocommerce/woocommerce-android/pull/747
* A renamed resource

To test:

A cursory login flow test - also confirm that the illustration on the 'magic link sent' screen is correct.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by aforcier** [comment]
Looks like there's a lint issue, looking into it.

**Comment by theck13** [comment]
The `img_email_alert_120dp` drawable was intentionally renamed to `img_illustration_email_alert_120dp` in 6309b4caeabb4fe65efa0a606e90ea9c4519c8bd.  I see it was renamed again to `login_email_alert` with these changes.  Can we keep it `img_illustration_email_alert_120dp` to maintain the naming convention of other illustration images?

**Comment by aforcier** [comment]
> The img_email_alert_120dp drawable was intentionally renamed to img_illustration_email_alert_120dp in wordpress-mobile/WordPress-Login-Flow-Android@6309b4c#diff-27a60f5489d2613b526776b5f63ef90a.  I see it was renamed again to login_email_alert with these changes.  Can we keep it img_illustration_email_alert_120dp to maintain the naming convention of other illustration images?

`img_email_alert_120dp` was renamed to `login_email_alert` a while back in WooAndroid along with other WordPress-themed assets that needed to be overwritten - but those changes weren't synced to the subtree.

It would seem we have conflicting conventions - WordPress-themed assets that should be overwritten are named `login_x` (see e.g. `login_site_address_help`, `login_toolbar_icon`). I'd favor keeping the naming explicit, since it's otherwise easy to mistakenly remove the overwriting image in the host app (the login prefix makes it clearer, I would hope).

What's the goal and format of the convention? It seems okay to me to have a different naming scheme for assets overwriting other assets, but some clarity on the intention would help, maybe there's a compromise that can fit both conventions.

**Comment by theck13** [comment]
The naming convention for images is similar to that used for icons and is described in the [_Drawable Resources_ section of the CONTRIBUTING.md file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md#drawable-resources).  The `illustration_` part was added in https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/commit/6309b4caeabb4fe65efa0a606e90ea9c4519c8bd#diff-27a60f5489d2613b526776b5f63ef90a since the image resembles other illustration images used in the app.

The general goal of the convention is to name drawables what they _are_ rather than what they _are for_ for a couple reasons.  As an example, the `img_illustration_email_alert_120dp` name is more descriptive than `login_email_alert`.  That helps when a developer is searching for an existing drawable to use in their project.  They may get a design without image names and have no idea if the image already exists or not.  Using a descriptive name related to what the images are helps find the file and avoid duplication.  They may not know the image was used in the login feature initially, but they may know of the `img_` prefix convention or that other drawables similar to that style have the `illustration_` part, etc.  Also, the convention allows us to reuse drawables without causing confusion.  As an example, if I wanted to reuse the `login_email_alert` drawable for the ***Notifications*** screen in the `notifications_list_fragment_page` layout, it may be confusing to use a resource named `login_email_alert` since it has nothing to do with login.

Avoiding accidentally removing the overwriting image makes sense, but I don't think removing resources like that occurs without reason (e.g. lint warning) and review.  If someone is attempting to remove the overwriting image since they think it's not being used in the host app, it's debatable whether the `login_` prefix will stop them or not.

**Comment by aforcier** [comment]
> The naming convention for images is similar to that used for icons and is described in the Drawable Resources section of the CONTRIBUTING.md file. The illustration_ part was added in wordpress-mobile/WordPress-Login-Flow-Android@6309b4c#diff-27a60f5489d2613b526776b5f63ef90a since the image resembles other illustration images used in the app.
> 
> The general goal of the convention is to name drawables what they are rather than what they are for for a couple reasons. As an example, the img_illustration_email_alert_120dp name is more descriptive than login_email_alert. That helps when a developer is searching for an existing drawable to use in their project. They may get a design without image names and have no idea if the image already exists or not. Using a descriptive name related to what the images are helps find the file and avoid duplication. They may not know the image was used in the login feature initially, but they may know of the img_ prefix convention or that other drawables similar to that style have the illustration_ part, etc. Also, the convention allows us to reuse drawables without causing confusion. As an example, if I wanted to reuse the login_email_alert drawable for the Notifications screen in the notifications_list_fragment_page layout, it may be confusing to use a resource named login_email_alert since it has nothing to do with login.
> 
> Avoiding accidentally removing the overwriting image makes sense, but I don't think removing resources like that occurs without reason (e.g. lint warning) and review. If someone is attempting to remove the overwriting image since they think it's not being used in the host app, it's debatable whether the login_ prefix will stop them or not.

I'd say that naming drawables what they are rather than what they are for makes total sense for the project itself, but less so for a library. 

For example, the icon displayed in the format bar during login (the WordPress W) used to be called `ic_my_sites_white_32dp`. Already not the best name since it was a re-use of the my sites icon. However, a 'what they are' style name might have described it as `ic_wordpress_w_white_32dp`. This would have made sense when the login code was built into WPAndroid, but it doesn't for the library, since the Woo app doesn't use the WordPress W, and keeping that name in the library would have meant calling a resource in the Woo app `ic_wordpress_com_w_white_32dp` (or `ic_my_sites_white_32dp`) when it was actually now a Woo logo.

I also think that even following the `img_illustration_` convention has potential to be misleading down the road. It's entirely possible that WordPress keeps using an illustration there, but the Woo app or some new app starts using a standard image instead (or vice versa). Describing the content of the image doesn't seem to suit the library well (this is ultimately something we could prescribe in the library's own `CONTRIBUTING.md`).

Under those circumstances, I don't find the argument of searching for resources by name a compelling reason to follow this convention for library assets, in fact it seems more likely to just be misleading.

If we needed to reuse an image overriding a login library one, we could probably use an alias resource to avoid duplication, and reference that from the new screen. I think there's value in being explicit about which assets are library overrides.

**Comment by aforcier** [comment]
> If we needed to reuse an image overriding a login library one, we could probably use an alias resource to avoid duplication, and reference that from the new screen. I think there's value in being explicit about which assets are library overrides.

Thinking about this some more, I had an idea that might work as a compromise. What if instead we kept the `img_illustration_email_alert_120dp` resource name in WPAndroid, but used an alias drawable to overwrite the login library's naming?

I restored the naming in b1d9a8a and added the alias in 5877958. WDYT?

**Comment by theck13** [comment]
> For example, the icon displayed in the format bar during login (the WordPress W) used to be called `ic_my_sites_white_32dp`. Already not the best name since it was a re-use of the my sites icon.

Ha!  You picked the best or worst example depending on how you look at it.  The `my_sites_` part of that icon comes from the name of the [gridicon](https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-my-sites.svg) from which the vector drawable was created.  That naming is also described in the [_Drawable Resources_ section of the CONTRIBUTING.md file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md#drawable-resources).  That gridicon doesn't have the best name since it references a specific part of the WordPress app like you mentioned.  The gridicon name in the convention was used since those icons were already established and they could be used to connect design assets and development resources using things like [this list](http://automattic.github.io/gridicons/).  That way a developer knows exactly which icon to use when a designer says, "Use the my sites gridicon."  I agree; that specific icon could use a rename though.

Unfortunately, the source assets like those used for `img_illustration_email_alert_120dp` do not have an established naming convention and some are customized for specific features.  That's why the "name resources what they are" convention was used.

> However, a 'what they are' style name might have described it as `ic_wordpress_w_white_32dp`. This would have made sense when the login code was built into WPAndroid, but it doesn't for the library, since the Woo app doesn't use the WordPress W, and keeping that name in the library would have meant calling a resource in the Woo app `ic_wordpress_com_w_white_32dp` (or `ic_my_sites_white_32dp`) when it was actually now a Woo logo.

That is a consequence of the login library being originally created for the WordPress app only.  It was never intended to be used as a standalone library until well after the resources were created.  If it was created as a library from the beginning, it should probably have a more generic icon and should be named something completely different based on that resource like `ic_logo_32dp`.

> I also think that even following the `img_illustration_` convention has potential to be misleading down the road. It's entirely possible that WordPress keeps using an illustration there, but the Woo app or some new app starts using a standard image instead (or vice versa). Describing the content of the image doesn't seem to suit the library well (this is ultimately something we could prescribe in the library's own `CONTRIBUTING.md`).
> 
> Under those circumstances, I don't find the argument of searching for resources by name a compelling reason to follow this convention for library assets, in fact it seems more likely to just be misleading.
> 
> If we needed to reuse an image overriding a login library one, we could probably use an alias resource to avoid duplication, and reference that from the new screen. I think there's value in being explicit about which assets are library overrides.

Yep, I agree that aliasing is the best option here.  That will allow the host to use whatever naming convention it chooses _and_ cause Android Studio to detect the resource is being used, which may avoid accidentally deleting the file as mentioned earlier.  I think the naming of the resources in the library should probably be more generic and maybe even be renamed to follow a semantic naming convention, but we can leave that for another debate.

**Pull request merged**
