### PR TITLE
feat: Toggle editor theme styles via feature flag

### PR DESCRIPTION
**Pull request by dcalhoun**
Provide experimental support for the editor WYSIWYG feature.

Fixes https://github.com/Automattic/dotcom-forge/issues/9450.

## Testing Instructions

1. Create a WordPress site that uses block theme, select a style with easily recognizable foreground and background colors (i.e., not black and white).
1. Add the site to the WordPress/Jetpack app.
1. Navigate to _Me_ → _Debug settings_ and enable the following feature flags: 
    - `experimental_block_editor`
    - `experimental_block_editor_theme_styles`
1. Open the editor for the site.
1. Verify the selected theme styles display.
1. Close the editor.
1. Disable the `experimental_block_editor_theme_styles` flag.
1. Open the editor for the site.
1. Verify the default styles display.

## Regression Notes

1. Potential unintended areas of impact
    The existing editor fails.
3. What I did to test those areas of impact (or what existing automated tests I relied on)
    Briefly tested the existing editor.
4. What automated tests I added (or what prevented me from doing so)
   N/A for this experimental feature.

## PR Submission Checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nbradbury** [comment]
@dcalhoun Do you have a site I can use to test this? Also, I'm not sure from the description what I should expect to see. Perhaps a video would help?

**Comment by dcalhoun** [comment]
> @dcalhoun Do you have a site I can use to test this? Also, I'm not sure from the description what I should expect to see. Perhaps a video would help?

WordPress.com's [Choose a Theme’s Style](https://wordpress.com/support/using-styles/style-variations/) should provide additional context. The block editor should render content using a theme's styles—i.e., what-you-see-is-what-you-get. You can observe this same feature in the web editor, where the block editor's background color will match your theme's background color, the block editor's text color will match your theme's text color, etc. 

An Atomic or jurassic.ninja site should allow for selecting a theme style. Happy to invite you to one of my testing sites, if that is preferred. Just let me know.

**Comment by nbradbury** [comment]
> The block editor should render content using a theme's styles—i.e., what-you-see-is-what-you-get. You can observe this same feature in the web editor, where the block editor's background color will match your theme's background color, the block editor's text color will match your theme's text color, etc.

Thanks for the context. I thought I needed to use a specific block-related theme for this, but I see otherwise. I'll get back to reviewing this.

**Review by nbradbury — APPROVED** [review]
@dcalhoun This is working great, feel free to merge when ready! :shipit:

**Pull request merged**
