### PR TITLE
Add Publish button for drafts in post list

### LINKED ISSUE #4110: Post List: Add link to publish draft post directly from post list
### Expected behavior

When viewing drafts in the post list, I expect to see the options to Edit, Preview, Publish, and Trash the post. Here are those options in Calypso:

screen shot 2016-05-20 at 12 35 57 pm

Those options are also available in WPiOS:

screen shot 2016-05-20 at 12 39 27 pm

### Actual behavior

Drafts only have the options to Edit, View/Preview, or Trash/Delete. There is no option to publish directly from the post list:

### Steps to reproduce the behavior

1. Open the WordPress app
2. Create a new post in the editor
3. Save the new post as a draft
4. Open the Blog Posts list
5. Find the draft post in the list of posts

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-8
Also reported by a user in an app review (WPAndroid 5.3)

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #4110

To test:

1. Create a draft post (local or remote)
2. A Publish button should be visible under the post in the post list
3. Clicking the Publish button uploads the post and updates the state to 'published'

Review: @kwonye

### CODE REVIEW

**Comment by nbradbury** [comment]
I'm afraid there are a couple of issues with this PR,

* [This check](https://github.com/wordpress-mobile/WordPress-Android/pull/4189/files#diff-167de1d12c4fee063112c77ac2c6c2adR386) doesn't account for all the situations where a post is "publishable" and doesn't match the logic we use [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java#L169) to determine whether to show a "publish" message when previewing the post.
* On smaller screens we show only three buttons on the CardView, with a "More" button to animate in the other buttons (you can try this on any device by setting `mAlwaysShowAllButtons` to false [here](https://github.com/wordpress-mobile/WordPress-Android/blob/48d4bb85067d7b68b3e3ef8253a27d0ab9c20c98/WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java#L99)). So, the logic for showing the publish button needs to take this into account.

**Comment by 0nko** [comment]
- The example condition whether a post is "publishable" doesn't take into account non-local drafts. Shouldn't I be able to publish those?
- Is it safe to assume that you can never have both Stats and Publish buttons under the same post? Or can an unpublished post have stats, for example?

**Comment by nbradbury** [comment]
Right now in the post preview we show this when the post has already been published but has changes which haven't been uploaded yet:

post-preview-publish

Since we show a publish button there, it would make sense to have a publish button on that post in the list as well. But since that post has already been published (it just has unpublished changes), it does have stats.

So in theory we could show both “publish” and “stats.” However, that complicates things for this PR since there’s not much space for all those buttons.

My vote would actually be to not have a publish button in the list, since it seems odd to publish something without seeing the full content of what you're publishing. But if it's decided that we want a publish button there, then I think it would be fair to make publish & stats mutually exclusive.

**Comment by 0nko** [comment]
@mattmiklic: Hi Matt. We're debating whether we should show a Publish button under a post in the Post List screen (as described in #4110). What do you think about Nick's comment above? 

In case we decide to display the Publish button, I've already come up with a solution that can display and cycle through 3 rows if both Stats and Publish buttons are visible. If there is only one of them there will be just 2 rows, like it is now.

**Comment by mattmiklic** [comment]
> We're debating whether we should show a Publish button under a post in the Post List screen (as described in #4110). What do you think about Nick's comment above?

I agree with the points that @nbradbury made about the utility of publishing directly from the list -- but having said that, the current goal is to bring about greater consistency between Calypso and our native apps UI. Since we made the decision to include the Publish button (and put it in place of the Stats button) in Calypso, I would follow the same design pattern for Android.

**Comment by 0nko** [comment]
> The example condition whether a post is "publishable" doesn't take into account non-local drafts. Shouldn't I be able to publish those?

@nbradbury: What about non-local drafts?

**Comment by nbradbury** [comment]
> Since we made the decision to include the Publish button (and put it in place of the Stats button) in Calypso, I would follow the same design pattern for Android.

I wasn't aware of that - that certainly simplifies things :)

> @nbradbury: What about non-local drafts?

@0nko That's a good question. The app's preview feature currently only shows the Publish button for posts that have local changes, but we'd want the preview & list to both show Publish for the same reasons. If Calypso shows a Publish button for drafts, then we should probably do the same for the app (and update the wording in the preview to handle non-local drafts).

**Comment by 0nko** [comment]
I checked and Calypso does show a Publish button for drafts, but only shows the Stats button for published posts. I'll update the code accordingly.

**Comment by 0nko** [comment]
I've updated the logic for showing the Publish button like we discussed. I hope I got it all covered... 

However, I kept the option for showing both Stats and Publish button at the same time. The reason is that the mobile app can have a local draft of a published post, which means both of the buttons should be visible. 

One thing I could see that might need more work is the layout on 1080 screens. The buttons looks a bit cramped if all 5 of them are visible, but I don't know..

**Comment by nbradbury** [comment]
@0nko This is **much** better, but I think we can stick with the idea of publish & stats being mutually exclusive. I think five buttons is too many, especially on smaller screens where you have to rotate through three rows of buttons before you even see the publish button.

**Comment by mattmiklic** [comment]
> This is much better, but I think we can stick with the idea of publish & stats being mutually exclusive. I think five buttons is too many, especially on smaller screens where you have to rotate through three rows of buttons before you even see the publish button.

Agreed here.

**Comment by nbradbury** [comment]
Hey @0nko, I noticed in 8edbfed that you made publish & stats mutually exclusive, so this PR looks good to me now. If you can resolve the conflicts, I'll merge it. Nice work!

**Comment by 0nko** [comment]
Sorry @nbradbury, I was AFK last week. I've merged the changes and resolved some minor conflicts in strings.xml. It should be good to go.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
