### PR TITLE
Remove Stats Opened Web Version from Analytics

### LINKED ISSUE #3470: Remove WPAnalyticsStatStatsOpenedWebVersion
Ref: https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/issues/48

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #3470

### CODE REVIEW

**Comment by daniloercoli** [comment]
Also fix https://github.com/wordpress-mobile/WordPress-Analytics-Android/issues/1

**Comment by maxme** [comment]
Using the following script:

```
events="APPLICATION_OPENED APPLICATION_CLOSED APPLICATION_INSTALLED APPLICATION_UPGRADED READER_ACCESSED READER_ARTICLE_COMMENTED_ON READER_ARTICLE_LIKED READER_ARTICLE_OPENED READER_ARTICLE_UNLIKED READER_BLOG_BLOCKED READER_BLOG_FOLLOWED READER_BLOG_PREVIEWED READER_BLOG_UNFOLLOWED READER_DISCOVER_VIEWED READER_FRESHLY_PRESSED_LOADED READER_INFINITE_SCROLL READER_LIST_FOLLOWED READER_LIST_LOADED READER_LIST_PREVIEWED READER_LIST_UNFOLLOWED READER_TAG_FOLLOWED READER_TAG_LOADED READER_TAG_PREVIEWED READER_TAG_UNFOLLOWED STATS_ACCESSED STATS_INSIGHTS_ACCESSED STATS_PERIOD_DAYS_ACCESSED STATS_PERIOD_WEEKS_ACCESSED STATS_PERIOD_MONTHS_ACCESSED STATS_PERIOD_YEARS_ACCESSED STATS_VIEW_ALL_ACCESSED STATS_SINGLE_POST_ACCESSED STATS_TAPPED_BAR_CHART STATS_SCROLLED_TO_BOTTOM STATS_WIDGET_ADDED STATS_WIDGET_REMOVED STATS_WIDGET_TAPPED EDITOR_CREATED_POST EDITOR_ADDED_PHOTO_VIA_LOCAL_LIBRARY EDITOR_ADDED_PHOTO_VIA_WP_MEDIA_LIBRARY EDITOR_UPDATED_POST EDITOR_SCHEDULED_POST EDITOR_CLOSED_POST EDITOR_PUBLISHED_POST EDITOR_SAVED_DRAFT EDITOR_TAPPED_BLOCKQUOTE EDITOR_TAPPED_BOLD EDITOR_TAPPED_IMAGE EDITOR_TAPPED_ITALIC EDITOR_TAPPED_LINK EDITOR_TAPPED_MORE EDITOR_TAPPED_STRIKETHROUGH EDITOR_TAPPED_UNDERLINE ME_ACCESSED MY_SITE_ACCESSED NOTIFICATIONS_ACCESSED NOTIFICATIONS_OPENED_NOTIFICATION_DETAILS NOTIFICATION_REPLIED_TO NOTIFICATION_APPROVED NOTIFICATION_UNAPPROVED NOTIFICATION_LIKED NOTIFICATION_UNLIKED NOTIFICATION_TRASHED NOTIFICATION_FLAGGED_AS_SPAM OPENED_POSTS OPENED_PAGES OPENED_COMMENTS OPENED_VIEW_SITE OPENED_VIEW_ADMIN OPENED_MEDIA_LIBRARY OPENED_BLOG_SETTINGS OPENED_ACCOUNT_SETTINGS OPENED_MY_PROFILE CREATED_ACCOUNT ACCOUNT_LOGOUT SHARED_ITEM ADDED_SELF_HOSTED_SITE SIGNED_IN SIGNED_INTO_JETPACK PERFORMED_JETPACK_SIGN_IN_FROM_STATS_SCREEN STATS_SELECTED_INSTALL_JETPACK PUSH_NOTIFICATION_RECEIVED PUSH_NOTIFICATION_TAPPED SUPPORT_OPENED_HELPSHIFT_SCREEN SUPPORT_SENT_REPLY_TO_SUPPORT_MESSAGE LOGIN_FAILED LOGIN_FAILED_TO_GUESS_XMLRPC PUSH_AUTHENTICATION_APPROVED PUSH_AUTHENTICATION_EXPIRED PUSH_AUTHENTICATION_FAILED PUSH_AUTHENTICATION_IGNORED SETTINGS_LANGUAGE_SELECTION_FORCED NOTIFICATION_SETTINGS_LIST_OPENED NOTIFICATION_SETTINGS_STREAMS_OPENED NOTIFICATION_SETTINGS_DETAILS_OPENED NOTIFICATION_SETTINGS_UPDATED THEMES_ACCESSED_THEMES_BROWSER THEMES_ACCESSED_SEARCH THEMES_CHANGED_THEME THEMES_PREVIEWED_SITE THEMES_DEMO_ACCESSED THEMES_CUSTOMIZE_ACCESSED THEMES_SUPPORT_ACCESSED THEMES_DETAILS_ACCESSED"

for i in $events; do
  [ `ack $i | wc -l` -le 3 ] && echo $i
done
```

I found some event names that are not used or not implemented in one tracker. 

To be removed
```
READER_FRESHLY_PRESSED_LOADED
READER_LIST_FOLLOWED
READER_LIST_PREVIEWED
READER_LIST_UNFOLLOWED
```

Not implemented in mixpanel tracker:
```
ACCOUNT_LOGOUT
```

Event name exists, but not tracked and it should be:
```
READER_DISCOVER_VIEWED
THEMES_CUSTOMIZE_ACCESSED
OPENED_ACCOUNT_SETTINGS
OPENED_MY_PROFILE (future?)
```

Not sure what to do with:
```
NOTIFICATION_LIKED
NOTIFICATION_UNLIKED
NOTIFICATION_SETTINGS_LIST_OPENED
NOTIFICATION_SETTINGS_STREAMS_OPENED
NOTIFICATION_SETTINGS_DETAILS_OPENED
NOTIFICATION_SETTINGS_UPDATED
```

**Comment by daniloercoli** [comment]
Thanks @maxme - it's already in my list for this iteration the checking on all events, for both apps. Will keep your comment as reference.

**Comment by maxme** [comment]
:+1: :shipit:

**Pull request merged**
