### PR TITLE
Feature/add login library tooling

### PR DESCRIPTION
**Pull request by loremattei**
This PR adds a new Fastlane lane that merges the strings from the libraries used by the project into the main strings.xml file. The lane is now configured to look at the login library.
The PR also updates the main strings.xml with the current version of the login library.

Important: this PR disables the `validate-login-library.sh` script on Travis so that developers are not required to add the strings to both libraries during development, _but_ adds the `localize_libs` lane to the `code_freeze` one to ensure that it's executed at every code freeze. 

## To Test:
1. Run `bundle install`
2. Run `bundle exec fastlane localize_libs` and verify that the script is executed without errors and no changes are made.
3. Make some changes to the `strings.xml` file of the Android Login Library, run `bundle exec fastlane localize_libs` again and verify that the changes are merged into the app `strings.xml`.

### CODE REVIEW

**Comment by aforcier** [comment]
@loremattei this is working for changes made to the login library, but there's a case I don't think is being handled right:
1. Make a change to a string in WPAndroid that overwrites a string from the login library
2. Run `bundle exec fastlane localize_libs`
3. Notice that the change to WPAndroid's `strings.xml` is removed, since the entry was replaced with the (outdated) entry from the login library

From our original proposal, we wanted:
> every addition and/or change made to the strings during the development of every client application should be committed to the login library repository only.

So it seems that we should somehow prevent changes to login library strings being made in WPAndroid and not carried over.

**Comment by loremattei** [comment]
@aforcier you're right, though I think that the best way to prevent this is to make it a habit for the developers that the strings should be changed in the origin library. It seems to work pretty well on WPiOS without any additional check, though the architecture of WPAndroid seems to be far more complex as the dependencies are imported in a lot of different ways (I think we may want to work on this in the future...).

I'm not sure there's a convenient way to handle the problem you mention at release time, which is the time when this script is supposed to run. We have a system (the `content_override` tag) to prevent to script to overwrite the strings in the main app file, when the change in it is intentional.

If we want to add a check on unintentional changes to the WPAndroid strings file, I think that the best way would to add a script that runs in the CI and that: 
 - checks the branch and doesn't run if the branch is `develop` or `release/XX` (otherwise we wouldn't be able to make any changes;
 - loops the diffs in the main WPAndroid strings.xml file and, for every string, checks if it is present in the login library (looking at the key). 
- if it finds a string that has been changed in the WPAndroid strings.xml and that belongs to the Login library, it raises an error.

Wdyt?

**Comment by aforcier** [comment]
@loremattei I agree, I think the checks for this have to happen via the CI on each PR. The added benefit is this will help folks get used to making the changes in the source library (if left to the release manager no one would realize it was a problem).

> If we want to add a check on unintentional changes to the WPAndroid strings file, I think that the best way would to add a script that runs in the CI and that:
>* checks the branch and doesn't run if the branch is develop or release/XX (otherwise we wouldn't be able to make any changes;
>* loops the diffs in the main WPAndroid strings.xml file and, for every string, checks if it is present in the login library (looking at the key).
>* if it finds a string that has been changed in the WPAndroid strings.xml and that belongs to the Login library, it raises an error.

This sounds good to me - I guess with an exception for strings tagged `content_override`?

**Comment by loremattei** [comment]
> This sounds good to me - I guess with an exception for strings tagged content_override?
Yep! You're right!

**Comment by loremattei** [comment]
Hey @aforcier! Finally I'm able to resume this work (I think this is the longest lasting PR I've ever opened). 
Thinking better to the issue, I think that a simpler logic would work to avoid the issue you mentioned. Basically, the logic in your script is already enough to avoid the issue, because it doesn't allow to merge the PR if a string has been changed in WPAndroid and not in the library.

I think that a simpler logic is better when it's equally effective, so I just ported your script to Ruby/fastlane. The reason for doing the porting is that, this way, the list of the tags to skip and of the libraries (if we'll have more of them in the future) to check are shared between the scripts.

If it looks good to you, before merging this PR I'll publish a post detailing the process and highlighting that the changes have to be done in the library.

**Comment by aforcier** [comment]
Hey @loremattei! Gave this a full pass, making local changes then running `validate_login_strings`, then `localize_libs` if validation passed. Results:

```
no changes: nothing happens ✅

login string changed in main xml: ERROR! ✅
login string changed in both xmls: clear ✅ ---> localize_libs: nothing happens ✅
login string changed in login xml: clear ✅ ---> localize_libs: works ✅
login string changed in main xml with content_ovveride: clear ✅ ---> localize_libs: nothing happens ✅

login string added in login xml: clear ✅ ---> localize_libs: works ✅
login string added in both xmls, and are the same: clear ✅ ---> localize_libs: nothing happens ✅
login string added in both xmls, and differ: ERROR! ✅
login string added in both xmls, and differ, but content_override is used: clear ✅ ---> localize_libs: nothing happens ✅

login string removed in login xml: clear ✅ ---> localize_libs: nothing happens ✅
login string removed in main xml: clear ✅ ---> localize_libs: works (string is re-added to main xml) ✅
login string removed in both xml: clear ✅ ---> localize_libs: nothing happens ✅
```

However, I noticed a problem when I made a test PR that should fail `validate_login_strings` (https://github.com/wordpress-mobile/WordPress-Android/pull/9232) - Circle CI passed. When I ran it locally it also passed.

**It looks like the issue is that `validate_login_strings` is only catching problems with local changes** - if a change that should break is already committed, it doesn't catch it.

Also there's currently a conflict in this branch.

**Comment by loremattei** [comment]
Very good point @aforcier!

I added another step to the script that gets the diffs from the PRs and repeats all the checks with those ones.
This way, it can be used in local (it works as before if you don't provide a PR URL) and in the CI.

I tested that it fails with a change in a string that's in the login library and that doesn't fail with a change in a string that's only in the main file (https://github.com/wordpress-mobile/WordPress-Android/pull/9283).

Could you please take another look at this?

**Comment by aforcier** [comment]
Looks good @loremattei! I gave it a try with a new PR too: https://github.com/wordpress-mobile/WordPress-Android/pull/9309

:shipit:!

I won't merge since you wanted to write about the process first (https://github.com/wordpress-mobile/WordPress-Android/pull/8723#issuecomment-461790500) 👍

**Comment by loremattei** [comment]
Thanks @aforcier!

**Pull request merged**
