### PR TITLE
Fixing typo for magic links

### LINKED ISSUE #4153: Typo in magic links analytics
All magic link analytics properties have `loagin_...` instead of `login_...`

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4153 

Needs review: @maxme

### CODE REVIEW

**Comment by kwonye** [comment]
Thanks for finding this @frosty

**Comment by maxme** [comment]
Note: make sure to cherry pick in `hotfix/5.4.1`

**Comment by maxme** [comment]
Cherry picked in hotfix/5.4.1

**Comment by kwonye** [comment]
Sorry, I was supposed to merge this into 5.4.1... Thanks for cherry picking.

**Pull request closed without merging**
