### PR TITLE
Fastlane: Push current branch only, don't rely on local git configuration

### PR DESCRIPTION
**Pull request by maxme**
Push current branch only, don't rely on local git configuration

### CODE REVIEW

**Comment by maxme** [comment]
@loremattei bumped `release-toolkit` to version 0.8.2

**Comment by maxme** [comment]
Note: Wait before #10965 before merging that one.

**Comment by loremattei** [comment]
Hey @maxme! This look good to me, but I think we also need the updated `Gemfile.lock` or the repository will turn out to be dirty after `bundle install`.

**Comment by maxme** [comment]
Thanks @loremattei, You can see I'm not familiar with ruby gems ;) - updated in 08d3cd1

**Pull request merged**
