### PR TITLE
Enable account closure

### PR DESCRIPTION
**Pull request by mkevins**
### Description

This PR adds support for the user to close their account from the account settings screen.

**Note**: This is a feature branch, and should not be merged until all the respective upstream PRs have been reviewed, tested, and merged onto this branch.

PRs:

* https://github.com/wordpress-mobile/WordPress-Android/pull/18382
* https://github.com/wordpress-mobile/WordPress-Android/pull/18386
* https://github.com/wordpress-mobile/WordPress-Android/pull/18391
* https://github.com/wordpress-mobile/WordPress-Android/pull/18407
* https://github.com/wordpress-mobile/WordPress-Android/pull/18409
* https://github.com/wordpress-mobile/WordPress-Android/pull/18444
* https://github.com/wordpress-mobile/WordPress-Android/pull/18457
* https://github.com/wordpress-mobile/WordPress-Android/pull/18470

(PT: pcdRpT-2yo-p2)

### To test:

**Note**: As this is a feature PR, please test with the latest changes in the HEAD PR's branch: https://github.com/wordpress-mobile/WordPress-Android/pull/18444

<details>
<summary>A note about coverage</summary>

When considering [the possible errors from the API](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/enable-account-closure--18413-add-tracks-events/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/DialogErrorUi.kt#L38-L43), some scenarios may be difficult to test or are not relevant to real users / scenarios. E.g.:

* `UNAUTHORIZED`: This may happen for A8C accounts, but will likely be preempted by the Atomic site error anyway
  * Also, I was not brave enough to try the account closure flow with my main account 😅 .
* `ATOMIC_SITE`: This scenario is covered in the testing steps
* `CHARGEBACKED_SITE`: This may require either mocking the response, or some elaborate manual setup
  * It also doesn't sound like a particularly good idea to test for real 😅 
* `ACTIVE_SUBSCRIPTIONS`: This scenario is covered in the testing steps
* `ACTIVE_MEMBERSHIPS`: This is _not_ tested, mainly because I didn't see an easy way to get a disposable account into this state
* `INVALID_TOKEN`: This state should not be reachable, afaiu (outside of debugging the flow)
* `UNKNOWN`: I don't know how to get this error (no pun intended)

I think the manual testing coverage is reasonable, given that, but please let me know if you feel otherwise.
</details>

<details>
<summary>Prerequisites (helpers)</summary>

In order to test the following flows, for convenience I have prepared some pre-configured accounts to test certain error conditions. Please see ref: pc8HXX-17y-p2 to access those credentials.

I have also prepared some scripts to make generating disposable accounts easier via `adb`
</details>

#### :red_circle: User with an Atomic site

1. Log in with a pre-configured account (with an Atomic site)
2. Navigate to the account settings (Me :arrow_right: Account Settings)
3. Tap "Close Account"
4. Expect that an error dialog is displayed with a button to contact support
   * Expect that the error is tracked: `🔵 Tracked: close_account_failed, Properties: {"error_code":"atomic-site"}`
5. Tap "Contact Support"
6. Expect that the Help screen is displayed
   * Expect that the origin is tracked: `🔵 Tracked: support_opened, Properties: {"origin":"ACCOUNT_CLOSURE_DIALOG"}`
7. Tap back
8. Tap dismiss
9. Expect that the dialog is dismissed

#### :red_circle: User with a Personal site

1. Log in with a pre-configured account (with a Personal site)
2. Navigate to the account settings (Me :arrow_right: Account Settings)
3. Tap "Close Account"
4. Expect that a dialog is displayed requesting the user to type their username for confirmation
5. Enter the username
6. Expect a the dialog to go into a pending state briefly (spinner), then an error dialog is displayed with a button to contact support
   * Expect that the error is tracked: `🔵 Tracked: close_account_failed, Properties: {"error_code":"active-subscriptions"}`
7. Tap "Contact Support"
8. Expect that the Help screen is displayed
   * Expect that the origin is tracked: `🔵 Tracked: support_opened, Properties: {"origin":"ACCOUNT_CLOSURE_DIALOG"}`
9. Tap back
10. Tap dismiss
11. Expect that the dialog is dismissed

#### :green_circle: Success case (disposable account)

1. Create or login with a disposable account (the account will be deleted)
2. Navigate to the account settings (Me :arrow_right: Account Settings)
3. Tap "Close Account"
4. Expect that a dialog is displayed requesting the user to type their username for confirmation
5. Enter the username
6. Expect a the dialog to go into a pending state briefly (spinner), then a success dialog is displayed with an ok button
   * Expect that the success is tracked: `🔵 Tracked: closed_account`
7. Tap "Ok"
8. Expect to be logged out and brought to the app's landing screen

## Regression Notes
1. Potential unintended areas of impact
Account settings

13. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

14. What automated tests I added (or what prevented me from doing so)
We do not currently have the established mocks for testing the account deletion flow, and adding that configuration would exceed the scope of this task.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @mkevins 🥇 
The code changes LGTM to me and the added tests look great. I've tested the implementation and went through the UI Changes testing checklist and everything worked great for me 🎉 

|Deleting progress|Account deleted|Error flow|
|---|---|---|
|Screenshot_20230518_131037|Screenshot_20230518_131045|Screenshot_20230517_151250|

I have two minor UI suggestions that I do not consider blocking:
* Lock the edit box when the deletion is in progress.
* Would it be possible to remove the empty space below the button when the process is complete? If not, would adding some text below the title make it better (e.g. `You would now be logged out and redirected to the app landing screen.`).

I would also suggest adding a release note since it's a new user facing feature.

**Comment by antonis** [comment]
I think the failing instrumented tests will be fixed with this PR https://github.com/wordpress-mobile/WordPress-Android/pull/18464 (related internal ref: p1684409358185439/1684256862.513919-slack-C04TBSWP09M)

**Comment by mkevins** [comment]
Thanks for reviewing and testing, and for your feedback Antonis!

> I have two minor UI suggestions that I do not consider blocking:
> 
> * Lock the edit box when the deletion is in progress.

Great idea! Addressed w/ 

> * Would it be possible to remove the empty space below the button when the process is complete? If not, would adding some text below the title make it better (e.g. `You would now be logged out and redirected to the app landing screen.`).

This is something I noticed as well, and I opened a task for it (https://github.com/wordpress-mobile/WordPress-Android/issues/18468). It is a strange issue where the dialog does not change height unless `usePlatformDefaultWidth`  is false. It isn't clear why that width property would affect the height, but the work-around seems to work, so I'll push a PR for that.

**Update**: I've opened a PR for this: https://github.com/wordpress-mobile/WordPress-Android/pull/18470

> I would also suggest adding a release note since it's a new user facing feature.

Thanks, I agree, I'll add one to this PR. :+1:

**Comment by mkevins** [comment]
Thank you for reviewing and testing this. I know the testing was cumbersome :sweat_smile: .

**Comment by ovitrif** [comment]
FYI I didn't review this again because I reviewed it via all PRs that were merged into it.

Not sure if #18464 would've fixed the UI tests, the failures were different:

| Capture 20230518T2010@2x |
| - |

**Comment by antonis** [comment]
> Not sure if https://github.com/wordpress-mobile/WordPress-Android/pull/18464 would've fixed the UI tests, the failures were different:

Good catch @ovitrif 👍 
I was fast in [my judgement above](https://github.com/wordpress-mobile/WordPress-Android/pull/18412#issuecomment-1553324186) 😬 
Do you think this is related with the new code added for this project?

**Comment by ovitrif** [comment]
> Good catch @ovitrif 👍 I was fast in [my judgement above](https://github.com/wordpress-mobile/WordPress-Android/pull/18412#issuecomment-1553324186) 😬 Do you think this is related with the new code added for this project?

Thank you @antonis for engaging my input 🙇🏻 

My feelings tell me the test failures are not caused by the changes we added here 🤞🏻 

Though even the slightest possibility should keep us alert, keeping an eye on the tests status IMHO 👀

**Comment by antonis** [comment]
> Though even the slightest possibility should keep us alert, keeping an eye on the tests status IMHO 👀

Sounds good @ovitrif 👍 

Checking the test crash I think it is related to this Sentry report p1683819728601849-slack-CK3STS3PB

**Comment by mkevins** [comment]
Thank you both for all your work reviewing and testing this feature. Also, extra thanks for looking into the UI tests.

**Pull request merged**
