### PR TITLE
[Dependency Updates] Update `glideVersion` to 4.15.1

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #17568

This PR updates `glideVersion` to [4.15.1](https://github.com/bumptech/glide/releases/tag/v4.15.1).

PS: Since this library was anyway pointing to `4.12.0` (it seems for some time now), the below commits was for documentation purposes only and weren't causing any actual changes whatsoever:

- [Update glide to 4.11.0](https://github.com/wordpress-mobile/WordPress-Android/commit/b9f20afde5b90e644ed063447ffd107aac1b7dc3)
- [Update glide to 4.12.0](https://github.com/wordpress-mobile/WordPress-Android/commit/ba8b4e311c37e01dcdafcb350d50200f0e7144ea)

-----

PS: @irfano I added you as the main reviewer, randomly so, since I just wanted someone from the WordPress team to be aware of and sign-off on that change for WPAndroid. I also added the @wordpress-mobile/apps-infrastructure team, but this in done only for monitoring purposes, as such, I am not expecting any active review from that team. Thus, feel free to merge this PR if you deem so.

-----

Dependency Refactor List:

1. [Remove glide volley in favor of glide version for both artifacts](https://github.com/wordpress-mobile/WordPress-Android/commit/1defbcb16ae8222a698f6e5eeb11612c7c860c63)

-----

## To test:

1. See the dependency tree diff result and verify correctness.
2. Thoroughly smoke test both, the WordPress and Jetpack apps, and see if everything is working as expected.
3. In addition to the above smoke test, you can expand the below and follow the inner and more explicitly test steps within, which is mainly related to the fixes (see above) and transitive updates on external and internal libraries (see [diff](https://github.com/wordpress-mobile/WordPress-Android/pull/18433#issuecomment-1548105947)):

<details>
    <summary>1a. Post Editing Flow [libs:editor]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ This test makes sure that the `Post Editing` flow, which comes from the [libs:editor](https://github.com/wordpress-mobile/WordPress-Android/tree/trunk/libs/editor)
module is also working as expected and that any transitive dependency changes aren't affecting
any `Material` related components.

- Add a new `blog` post.
- Add as many blocks as possible, along with any combination of those (like the `paragraph`, `heading`,
`image`, `video`, `separator`, `quote`, `gallery`, `columns`, `rows` blocks).
- Verify that the `Post Editing` screen, along with all the blocks you added, are shown and
that everything is functioning as expected.
- Publish the post and verify that it is displayed as expected both, on the mobile and web.

</details>

<details>
    <summary>1b. Story Flow [com.automattic:stories]</summary>

ℹ️ This test applies to the `Jetpack` app.
❗️ This test makes sure that the `Story` flow, which comes from the [com.automattic:stories](https://github.com/Automattic/stories-android)
library is also working as expected and that any transitive dependency changes aren't affecting
any `Constraint Layout` related screens.

- Create a new `story` post.
- Add a couple of `images` to that story.
- Add a some `text` on top of any image you uploaded.
- Verify that everything is functioning as expected and that you can publish the story.
- Publish the story and make sure that the story has been published as expected.

</details>

<details>
    <summary>2a. Site Page Layout [ModalLayoutPickerFragment.kt + LayoutViewHolder.kt + ImageManager.kt]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Add a new `site` page.
- Verify the `Choose a layout` screen is shown and functioning as expected,
along with it displaying the layout thumbnails correctly.

</details>

<details>
    <summary>2b. Site Creation Layout [HomePagePickerFragment.kt + LayoutViewHolder.kt + ImageManager.kt]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Go to `Site Picker` -> Click the `+` button -> Chose `Create WordPress.com site`.
- Verify the `What's your website about?` screen is shown and functioning as expected, along with
displaying the topics thumbnails correctly.
- Chose a topic (eg. `Lifestyle`).
- Verify the `Choose a theme` screen is shown and functioning as expected,
along with it displaying the theme thumbnails correctly.

</details>

<details>
    <summary>3. Blog Post Layout [EditPostActivity.kt + AztecEditorFragment.kt + AztecImageLoader.kt]</summary>

ℹ️ This test applies to both, the `WordPress` and `Jetpack` apps.
❗️ In order to be able to switch off the `Block Editor` option, the testing site must be on a
business plan, or on a plan that still supports the use of the `Classic Editor` option.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section at the bottom and click on its `Site Settings` option.
- Find the `Editor` section in the middle and switch off the `Use Block Editor` option. This will
make sure that any new post will be created using the `Aztec` classic editor.
- Add a new `blog` post.
- Add a new `image`.
- Publish the post.
- Verify that opening to edit the post again, everything functioning as expected,
along with it displaying the image thumbnail correctly.

</details>

<details>
    <summary>4. Stats Widget Layout [ViewsWidgetUpdater.kt + WidgetUtils.kt]</summary>

ℹ️ This test applies to the `Jetpack` app.

- Add a Jetpack related `Views this week` or any other such widget to the home screen.
- From the widget's settings, select your `Site`, then `Color` and click the `ADD WIDGET` button.
- Expand the widget to take as much of the horizontal and vertical space as possible.
- Verify that the widget is shown and functioning as expected,
along with it displaying the site thumbnail correctly.

</details>

<details>
    <summary>5a. Comment Detail Screen [CommentDetailFragment.kt + CommentUtils.kt + WPCustomImageGetter.kt + WPRemoteResourceViewTarget.kt]</summary>

ℹ️ This test applies to both, the `Jetpack` and `WordPress` apps.
❓️ Not sure how to best and quickly test this, let me know if you have an idea.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Content` section at the top and click on its `Comments` option
to open the `Comments` screen.
- Find a comment (❓️ with an image ❓️) from the list of comments and click on it.
- Verify that the `Comment Detail` screen is shown and functioning as expected,
along with it displaying the image thumbnail correctly.

</details>

<details>
    <summary>5b. Activity Log Detail Screen [ActivityLogDetailFragment.kt + NotificationsUtils.kt + WPCustomImageGetter.kt + WPRemoteResourceViewTarget.kt]</summary>

ℹ️ This test applies to both, the `Jetpack` and `WordPress` apps.
❓️ Not sure how to best and quickly test this, let me know if you have an idea.

- Go to `My Site` tab -> `MENU` sub-tab.
- Find the `Manage` section in the middle and click on its `Activity Log` option.
- Find an event (❓️ with an image ❓️) from the list of events and click on it.
- Verify that the `Activity Log Detail` screen is shown and functioning as expected,
along with it displaying the image thumbnail correctly.

</details>

<details>
    <summary>6. JP/WP Screenshot Testing [JPScreenshotTest.java + WPScreenshotTest.java + WPSupportUtils.java + PlaceholderComparison.java]</summary>

ℹ️ This test applies to both, the `Jetpack` and `WordPress` apps.
❗️ Not sure if it is worth it to test this, let me know if you have any thoughts on that.
❓️ Not sure how to best and quickly test this, let me know if you have an idea.

</details>

-----

## Regression Notes

1. Potential unintended areas of impact

    - Potential breakage or misbehaviour of screens and image loading related components as `Glide` is a library that is being used across many screens, especially screens that utilize any image loading functionality.
    - Some of the transitive dependencies added might be causing some kind of misbehaviour.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - See `To test` section.

3. What automated tests I added (or what prevented me from doing so)

    - N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Review by irfano — COMMENTED** [review]
👏🏻  Great job on comprehensive testing instructions. I couldn't find any changes in the Glide changelogs that could break the app.

---

> 5b. Activity Log Detail Screen [ActivityLogDetailFragment.kt + NotificationsUtils.kt + WPCustomImageGetter.kt + WPRemoteResourceViewTarget.kt]

❓  I'm sharing the activity log detail screen that contains an image. But this screen shows the image as a link and doesn't use `WPRemoteResourceViewTarget`. I couldn't find a case that `ActivityLogDetailFragment` uses Glide. `ActivityLogDetailFragment` uses `NotificationsUtilsWrapper`, but it [accesses only a function](https://github.com/wordpress-mobile/WordPress-Android/blob/380a6de79ca90947814a3c7e87916a71329e0442/WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt#L190-L197) that is not related to Glide. So, is 5b related to Glide?


---
>JP/WP Screenshot Testing [JPScreenshotTest.java + WPScreenshotTest.java + WPSupportUtils.java + PlaceholderComparison.java]

❓  Can't we say if CI tests pass, `WPScreenshotTest` and `JPScreenshotTest` still work fine?

**Comment by ParaskP7** [comment]
👋 @irfano !

> I couldn't find any changes in the Glide changelogs that could break the app.

Awesome, thank you for reviewing and testing this, you rock! ❤️ 🙇 🚀 

> ❓ I'm sharing the activity log detail screen that contains an image. But this screen shows the image as a link and doesn't use WPRemoteResourceViewTarget. I couldn't find a case that ActivityLogDetailFragment uses Glide. ActivityLogDetailFragment uses NotificationsUtilsWrapper, but it [accesses only a function](https://github.com/wordpress-mobile/WordPress-Android/blob/380a6de79ca90947814a3c7e87916a71329e0442/WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt#L190-L197) that is not related to Glide. So, is 5b related to Glide?

To my understanding this [function](https://github.com/wordpress-mobile/WordPress-Android/blob/380a6de79ca90947814a3c7e87916a71329e0442/WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt#L190-L197) is related to Glide, and that is, due to it using this [addImageSpansForBlockMedia(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L322-L410) function, which in turn, is using this [WPCustomImageGetter](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L336-L338) class, which is using the [WPRemoteResourceViewTarget](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/util/image/getters/WPCustomImageGetter.kt#L34) class, and that in the end used Glide, thus me adding it to the testing list, just in case.

Am I missing something here Irfan? 🤔 PS: I might surely do... 🤔 

FYI: The reason for me adding these comprehensive test instruction is mainly twofold, on the one hand, just for us to be sure that this dependency, which is very outdated, will not cause any regression after being merged, and on the other hand, so that I can then use those testing instruction as the baseline for the test instructions documentation per dependency update work that I hope to deliver at some point in the future (see `pcdRpT-2Hp-p2`).

> ❓ Can't we say if CI tests pass, WPScreenshotTest and JPScreenshotTest still work fine?

Yes, for the purpose of this PR, I think we can, and thus this doesn't need to block this PR, but FYI and AFAIK the WP/JS screenshot tests are not running as part of the CI tests, so 🤷 ...

**Review by irfano — APPROVED** [review]
> To my understanding this [function](https://github.com/wordpress-mobile/WordPress-Android/blob/380a6de79ca90947814a3c7e87916a71329e0442/WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt#L190-L197) is related to Glide, and that is, due to it using this [addImageSpansForBlockMedia(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L322-L410) function, which in turn, is using this [WPCustomImageGetter](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L336-L338) class, which is using the [WPRemoteResourceViewTarget](https://github.com/wordpress-mobile/WordPress-Android/blob/d311b3df5964086697329842a78e95613bd8f6f2/WordPress/src/main/java/org/wordpress/android/util/image/getters/WPCustomImageGetter.kt#L34) class, and that in the end used Glide, thus me adding it to the testing list, just in case.
> 
> Am I missing something here Irfan? 🤔 PS: I might surely do... 🤔

Yes, you're right. `ActivityLogDetailFragment` can access Glide via `WPCustomImageGetter`, but I couldn't find a case that it can happen. I tested various activity log items, but `mediaArray` was null on all of them, so it skipped using `WPCustomImageGetter`. 

So, there are 2 ways we can go. We can remove `5b` from intructions or we keep it with `❓️ with an image ❓️` message, thus perhaps future testers may know a activity log detail type that can have `mediaArray` and trigger `WPCustomImageGetter()`.

Since we're just discussing updating testing instructions, I'm approving the PR and leaving the merge to you.

> Yes, for the purpose of this PR, I think we can, and thus this doesn't need to block this PR, but FYI and AFAIK the WP/JS screenshot tests are not running as part of the CI tests, so 🤷 ...

Oh yes! So we can skip testing WP/JP screenshot tests since they are broken.

**Comment by ParaskP7** [comment]
👋 @irfano and thanks for your reply!

> Yes, you're right. ActivityLogDetailFragment can access Glide via WPCustomImageGetter, but I couldn't find a case that it can happen. I tested various activity log items, but mediaArray was null on all of them, so it skipped using WPCustomImageGetter.

Same! 🫣

> So, there are 2 ways we can go. We can remove 5b from intructions or we keep it with ❓️ with an image ❓️ message, thus perhaps future testers may know a activity log detail type that can have mediaArray and trigger WPCustomImageGetter().

Yeap, I would vote for keeping it, at least for now and until we future out, at some point in the future, if that piece of logic can be tested or even doing anything. It might as well be dead code, who knows, this needs further and deep investigation but shouldn't block this PR... 🤷 

> Since we're just discussing updating testing instructions, I'm approving the PR and leaving the merge to you.

Great, thanks for the approval and discussing all that with me, much appreciated that you took the time to do a thorough and detailed testing on this dependency update. ❤️ 

I'll proceed with merging now as everything else seems to be working anyway! 🚀 

> Oh yes! So we can skip testing WP/JP screenshot tests since they are broken.

Yea! 🫣

**Pull request merged**
