### PR TITLE
Fixed issue with sharing external media/links from other apps

### PR DESCRIPTION
**Pull request by marecar3**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/10570

Following gb-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1817

To test:

**Test sharing media (Image/Video)**
1. Make sure that default Editor is Gutenberg
2. Go to Photos and Videos
3. Find proper image/video
4. Click on the share button and choose WPAndroid
5. WPAndroid will open and image/video should be uploaded with success

**Test sharing link from Web Browser in Gutenberg**
1. Make sure that default Editor is Gutenberg
2. Open some Web Browser
3. Visit random url
4. Click on the share button and choose WPAndroid
5. WPAndroid will open and the title with a clickable link from Web Browser should be in the Post.

**Test sharing link from Web Browser in Aztec**
1. Make sure that default Editor is Aztec
2. Open some Web Browser
3. Visit random url
4. Click on the share button and choose WPAndroid
5. WPAndroid will open and the title with a clickable link from Web Browser should be in the Post.

**Test sharing link from other apps (Youtube, Twitter...) in Gutenberg**
1. Make sure that default Editor is Gutenberg
2. Open another app (Youtube, Twitter...)
3. Pick some video/Twitter post ....
4. Click on the share button and choose WPAndroid
5. WPAndroid will open with a link in the Post.

**Test sharing link from other apps (Youtube, Twitter...) in Aztec**
1. Make sure that default Editor is Aztec
2. Open another app (Youtube, Twitter...)
3. Pick some video/Twitter post ....
4. Click on the share button and choose WPAndroid
5. WPAndroid will open with a link in the Post.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
> LGTM tested on my Pixel 3a 👍
> 
> One thing that I noticed while testing sharing media was the button above "Add to new post" didn't have any text. This issue seems separate from this change but wanted to know if you knew off hand what it should say?
> 
> 

Thanks for the review @chipsnyder !
That's an interesting problem. I didn't experience it. Maybe we can raise an issue about that?

**Comment by chipsnyder** [comment]
Opened the issue at https://github.com/wordpress-mobile/WordPress-Android/issues/11173

**Comment by marecar3** [comment]
> This may already be fixed with this merge, and/or it may merit opening a separate issue, but I have noticed that sharing from Simplenote is still not working either, with the block editor enabled.

Hey @mrfoxtalbot , I have tested this PR against Simplenote and it's working for me.
Thanks for pointing on that one.

**Comment by maxme** [comment]
Thank you @marecar3, @chipsnyder  and @mrfoxtalbot - I'm glad this one is fixed!

**Comment by marecar3** [comment]
Thanks, @maxme !

**Pull request merged**
