### PR TITLE
FluxC: Fix WP.com site creation

### PR DESCRIPTION
**Pull request by aforcier**
Fixes a few issues with creating a new WP.com site (both standalone and as part of new user signup).

1. The order of the site name param (the *.wordpress.com part of its URL) and the site title was reversed when `NewSitePayload` was created (the naming is confusing - the endpoint calls these `blog_name` and `blog_title` respectively, and we've kept the same naming in FluxC).
2. `NewBlogFragment` should validate the new site before creating it
3. The progress indicator wasn't being displayed

Note: There's one more issue, which is that site creation can take longer than 30 seconds, which is our current default timeout in FluxC. I've increased it to 90 seconds for this endpoint in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/330 - using that branch for testing might be necessary.

cc @maxme

### CODE REVIEW

**Comment by maxme** [comment]
> should validate the new site before creating it

I'm not sure why we need the dry run step? The site won't be created if we there is an error and we'll get the same errors if it's not valid.

**Comment by aforcier** [comment]
> should validate the new site before creating it
> > I'm not sure why we need the dry run step? The site won't be created if we there is an error and we'll get the same errors if it's not valid.

In my tests it looked like non-dryrun requests were taking much longer than dryrun ones, even when an error was ultimately returned. When I saw that I assumed this was known and that's why the code used to do a validation step first pre-FluxC. I can't reproduce this now though, so either I was mistaken or something has changed server-side.

As an aside, requests were taking 40-50 seconds to complete yesterday and now they're taking 3-4 seconds, which could be related to the differences I was saying.

Anyway, I'll drop the validation step since it doesn't seem to be any faster for error-checking.

**Comment by aforcier** [comment]
Fixed in 4f2e414 (also resolved the merge conflict), ready for another pass @maxme

**Comment by maxme** [comment]
:shipit: thanks, I've one more test site.

**Pull request merged**
