### PR TITLE
Reader Detail Updates (Post Header UI Polishing)

### PR DESCRIPTION
**Pull request by ashiagr**
Task: #12900

This PR polishes post header UI, particularly

- Applies new follow button style
- Updates post title style

Looking for design review for UI updates so far (except for the backlog items in #12900 )

**Mobile**

| Light Mode Following | Light Mode Follow | Dark Mode Following | Dark Mode Follow |
|-----|-----|-----|-----|
|device-2020-10-06-125504|device-2020-10-06-125513|device-2020-10-06-125548|device-2020-10-06-125602|

**Mobile Landscape**
| Following | Follow | 
|-----|-----|
|device-2020-10-06-125418| device-2020-10-06-125449

**Tablet Light Mode** 

| Following | Follow | 
|-----|-----|
|device-2020-10-06-125831| device-2020-10-06-125848|

**Tablet Dark Mode** 

| Following | Follow |
|-----|-----|
|device-2020-10-06-130145| device-2020-10-06-130153|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mbshakti** [comment]
This is looking amazing! So excited to see this screen come to life with the updated designs. 

Some feedback/requests:
1. Can we add the overflow/ellipsis menu to the header on the RDV page?

Screen Shot 2020-10-07 at 11 08 11 AM

2. For the action bar, I noticed there's nothing about it in the backlog items, so adding four pieces of feedback/requests here. 

(2A) Can we make the action bar sticky so that it doesn't disappear/reappear on scroll, mainly because it feels too unpredictable. I don't know how complex this task if going to be so we can talk on slack more if needed! 

(2B) For the post actions on the action bar, can we make them visually evenly distributed so it matches the post actions style on the postcard UI? 
Screen Shot 2020-10-07 at 11 14 50 AM

(2C) Can we add the same drop shadow style as the RDV header to the action bar? 

(2D) In dark mode, can we match the phone's back & home button background color with the post actions bar? Not sure if that would be a universal change across the app (seems like it might be).  
Screen Shot 2020-10-07 at 11 26 13 AM


3. [UI nit] What's the padding right value of the follow/unfollow button? It seems to have a lot of space to the right. 
Screen Shot 2020-10-07 at 11 18 10 AM

4. I imagine that's coming in future PRs ;) but just double checking that we removing the "liked by.." "more in.." sections which are currently at the bottom of the RDV? 

5. When I tap the globe icon on the RDV, it opens up a bottom sheet and redirects me else where when I try to visit the site (unexpected). But when I tap on the "visit the site" link on the ellipsis menu (on the main feed postcards), it opens up the in-app browser (expected). Do you know why this might be happening? My guess is that the globe icon means something different on iOS & Android. If it means something different on the different platforms, when I used the globe icon in the mocks, it essentially meant "visit this site" because we don't want to redirect the user to something external of the app....

Screen Shot 2020-10-07 at 11 33 59 AM

6. This is a request because I forgot to include this change in the mockups after Leandro & I decided to make a change to iOS after some discussion about the information hierarchy of the screen. Can we move the timestamp from next to the site URL to next to the author's name. 

Screen Shot 2020-10-07 at 11 40 56 AM

 
If anything is unclear or out of scope, let me know!

**Comment by ashiagr** [comment]
Thanks so much @mbshakti !

I wasn't able to work on the bottom bar till now. I planned to work on it along with comments entry point changes, should've stated it here :(.

I'll address 3 & 6 in this PR and start integrating your feedback/ requests (1, 2, 4 and 5) in the future PRs (thanks for clearly stating them 🙏, I'll keep these points in mind while implementing).

**Comment by ashiagr** [comment]
Updated UI for 3 & 6.
Ready for another look @mbshakti 🙇‍♀️

> 3. [UI nit] What's the padding right value of the follow/unfollow button? It seems to have a lot of space to the right.

Min target size of 48dp created extra space around the icon only follow button. I've retained min target height but removed min target width to fix it and changed ripple background to circular. Hope it looks better 🤞.
icon only



> 6. This is a request because I forgot to include this change in the mockups after Leandro & I decided to make a change to iOS after some discussion about the information hierarchy of the screen. Can we move the timestamp from next to the site URL to next to the author's name.

Updated screenshots:

Light mode | Dark mode
------------|----------
lightmode| darkmode

**Review by malinajirka — APPROVED** [review]
Great job @ashiagr! I haven't found any issues in the code.

**Comment by mbshakti** [comment]
Looks awesome, thanks for making the changes @ashiagr! I love the circular ripple background for the follow icon 😻

**Review by mbshakti — APPROVED** [review]

**Pull request merged**
