### PR TITLE
Feature/bottom nav phase2

### LINKED ISSUE #7666: Bottom Navigation: Phase 1
Add phase 1 of bottom navigation to the app. This entails removing the TabLayout and ViewPager from the main activity and replacing them with a BottomNavigationView and related adapter. We'll also need to figure out how to add a badge to the notifications page, which may be tricky since BottomNavigationView isn't very customizable.

### LINKED ISSUE #7667: Bottom Navigation: Phase 2
Once Phase 1 (#7666) of bottom navigation has been completed, we need to figure out how to add the "New Post" button to the middle of the navbar. This will likely entail rolling our own navbar component, because Google's `BottomNavigationView` is very basic and hard to customize.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #7666 and fixes #7667 - implements "phase 1" and "phase 2" of bottom navigation for the main activity, replacing the current ViewPager and related code and adding a "New Post" button to the navigation (which meant ditching the FAB on the "My Site" page).

Note to the reviewer: don't be frightened by the number of commits - there was a ton of experimentation while this was being worked on which resulted in a lot of small commits.

### CODE REVIEW

**Comment by suroyo** [comment]
Good

**Comment by hypest** [comment]
Another functional level thing I notices is that the push notifications don't seem to arrive automatically. Need to manually go to the notifications screen and pull-to-refresh.

**Comment by hypest** [comment]
Good news @nbradbury , had a look at the code and looks 👍 !

**Comment by nbradbury** [comment]
> Flicker in Notifications list. It seems that the empty state view bleeds in for a moment.

Yeah, that's a bug in `develop` right now which I believe @theck13 is working on.

> Another functional level thing I notices is that the push notifications don't seem to arrive automatically. Need to manually go to the notifications screen and pull-to-refresh...The red badge doesn't seem to appear automatically either.

I'm not able to repro this. I just went to my browser, liked one of my posts, and the notification & red dot appeared automatically.

> A bit crammed when in landscape, especially in the Reader

Hmm, you must be seeing something different than I am (screenshot below). What are you seeing?

landscape

**Comment by nbradbury** [comment]
> Animation on "Write" button feels unnatural (slow, linear). I'll leave that for a design review pass though.

@iamthomasbishop Any thoughts on this?

**Comment by theck13** [comment]
> Yeah, that's a bug in `develop` right now which I believe @theck13 is working on.

The [fix](https://github.com/wordpress-mobile/WordPress-Android/pull/7674) was pushed and is ready for review.

**Comment by hypest** [comment]
> > Another functional level thing I notices is that the push notifications don't seem to arrive automatically. Need to manually go to the notifications screen and pull-to-refresh...The red badge doesn't seem to appear automatically either.
>
> I'm not able to repro this. I just went to my browser, liked one of my posts, and the notification & red dot appeared automatically.

Hmm, I tried twice to revert to `develop` where it worked all the time. I had the emulator and the device connected and running in parallel on the same account. That might have caused the issue. I see normal behavior now that I only use the device. Weird 🤔 

> >  A bit crammed when in landscape, especially in the Reader
>
> Hmm, you must be seeing something different than I am (screenshot below). What are you seeing?

I'm seeing the same as in your screenshot. By crammed, I mean that the scrollable height is now reduced by the height of the added bottom bar. When scrolling, the toolbar and the bottom bar stay in place, leaving around 3 "thumb widths" worth of space to scroll on my Nexus 5X (and my finger size apparently). Nothing that I would hold the PR back though, just needed to add a remark about it.

**Comment by nbradbury** [comment]
> I'm seeing the same as in your screenshot. By crammed, I mean that the scrollable height is now reduced by the height of the added bottom bar.

Oh, right! Yes, that it pretty tight. Perhaps in the future we could hide the navbar when scrolling down, which is mentioned in the [guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior)

**Comment by iamthomasbishop** [comment]
Sorry for the delay - Just running through for a final design pass 😄 

* That was a good point by @hypest - space is tight there. And I agree w/ your assessment @nbradbury that we could hide the navbars on scroll, even in portrait - but maybe that's something we tackle separately

* I don't really have a problem with the `[+]` button's transition itself, but I would like to see the New Post screen/full-scree dialog show quicker, with less of a delay. I'm not sure how long the delay is right now (~.5s?), but it could stand to be quicker. Maybe the new post screen should open immediately when the `[+]` button transition completes (bounces once)

* I'd like to see a subtle 1sp border-top, probably `grey_lighten_20`. I'm not sure how I feel about the shadow that's currently on there, IIRC the guidelines don't recommend a shadow

* Maybe my eyes are playing tricks on me, but it looks like the Notifications badge might be set in either `orange_fire` or `alert_red`, where it should be `orange_jazzy`

So exciting to see this become a reality! Well done :)

**Comment by nbradbury** [comment]
> I agree w/ your assessment @nbradbury that we could hide the navbars on scroll, even in portrait - but maybe that's something we tackle separately

I'd definitely want to handle this separately, because I **think** it's going to be a fair amount of work.

> Maybe the new post screen should open immediately when the [+] button transition completes (bounces once)

Unfortunately, I'm already doing that - the delay is due to the overhead of creating the post screen. I tried showing the post screen while the animation was at the midpoint, but that just caused the animation to stutter until the screen appeared.

> I'd like to see a subtle 1sp border-top...I'm not sure how I feel about the shadow that's currently on there

I assume you mean 1dp rather than 1sp, since the latter is for fonts? If so, here's how that looks:

separator

Note that the shadow wasn't my doing - that was the stock behavior of Google's component, so I figured it was correct.

> Notifications badge...should be orange_jazzy

Just changed it:

orange

**Comment by iamthomasbishop** [comment]
> Unfortunately, I'm already doing that - the delay is due to the overhead of creating the post screen. I tried showing the post screen while the animation was at the midpoint, but that just caused the animation to stutter until the screen appeared.

Ah, ok. In that case let's try to slow down the animation slightly of the New Post button to close the gap a bit. I'm not sure if slowing the animation down is going to solve the concern, but let's give it a shot. If it doesn't feel better, this is something I can live w/ for now.

> I assume you mean 1dp rather than 1sp, since the latter is for fonts?

Yea exactly, my bad 🤦‍♂️

-------

Other than the timing thing on the New Post button animation, this is looking ready to 🚢 !

**Comment by nbradbury** [comment]
Note: Thomas and I chatted on Slack about slowing down the animation and it was decided to stick with the way it is.

**Comment by nbradbury** [comment]
This has passed both code review and design review, so :shipit: !

**Pull request merged**
