### PR TITLE
Feature/deep linking improvements

### PR DESCRIPTION
**Pull request by kwonye**
Augments #8544 which addresses #6313 

This is a refactor to move the logic that handles deep links to `DeepLinkingIntentReceiverActivity` per @malinajirka's suggestion. This makes sure we don't add to `WPMainActivity` and isolates all deep link concerns to one class.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @kwonye ! 

It looks good to me. Only thing I've noticed is that it doesn't work when the user isn't logged in. Shouldn't we handle that case too - wdyt?

**Comment by kwonye** [comment]
Thanks @malinajirka, and sorry for the miscommunication. Yes, the previous work we did already handles the logged out use case. For this app banner however, it simply goes to the reader tab which requires the rest of the app to be logged in. This will result in a ton of breaks if we allow the user to go in without logging in for these sections.

Thankfully they can still read a post without being logged in which is the main use case. I'll clear up the merge conflict and merge this, thanks!

**Comment by malinajirka** [comment]
Thanks @kwonye! I'm sorry for the miscommunication and for not explaining my thoughts clearly enough. I wasn't suggesting we should allow the user to go in without logging in. I was just thinking we could redirect the user to the login screen, let them them login in and then continue with the flow. But I guess it's not so important.

**Comment by kwonye** [comment]
> When the user is not logged in, the login flow is shown. When they log in, the flow automatically continues and the target screen is shown.

Gotcha! Yea that'd be great. Let's do that in later iterations.

**Pull request merged**
