### PR TITLE
Issue/5407 media library drop image filenames

### LINKED ISSUE #5407: Media library: drop file name and file type from images
For consistency with Calypso, the media library should drop file names and file types from the bottom image cells. For non-images, though, we should keep the file name and type and display them centered in the cell.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5407 - drops file names and file types from images in the media browser, improves the display of non-images.

Before & after shots below.

before

Note: as with other media browser PRs, you may notice duplication or wrong images in grid cells. This is being addressed separately - see #5434

### CODE REVIEW

**Comment by daniloercoli** [comment]
Not related to this PR but the "uploading" indicator (spinner + text) doesn't seem centered in the cell.
The text string seems to be centered in the cell, while the spinner is positioned above it. The whole result feels a little bit weird to me.

device-2017-03-21-090731

**Comment by daniloercoli** [comment]
PDF File (1st cell) placeholder seems wrong:
device-2017-03-21-091739


Video file (1st cell) placeholder:
device-2017-03-21-091427

**Comment by nbradbury** [comment]
> the "uploading" indicator (spinner + text) doesn't seem centered in the cell.

Fixed in 375ecbb

> PDF File (1st cell) placeholder seems wrong

That's definitely wrong, and I can't reproduce it. It *should* look like the screenshot below.

screenshot_1490094355

What device/emulator are you seeing this with?

**Comment by daniloercoli** [comment]
> What device/emulator are you seeing this with?

I can actually reproduce it on both 
- Wiko Ridge 4G powered by Android 5.0.2
- Nexus 5X - Android 7.1.1

**Comment by nbradbury** [comment]
Looking at your screenshots again, I'm wondering if the PDF and video icons aren't being shown by the app but are instead actual images in your media library. Do you have those two images in your media library?

**Comment by daniloercoli** [comment]
Hehe, I had already checked that before replying with the pictures above :)
screen shot 2017-03-21 at 14 20 28

**Comment by daniloercoli** [comment]
:shipit:

**Pull request merged**
