### PR TITLE
issue/4037-reader-smiley

### LINKED ISSUE #4037: Smiley text shows broken image in Reader
When I add a smiley to a post using the text `:)`, the post shows a broken image in the Reader. Instead, I expected it to show a smiling emoji.

### Steps to reproduce the behavior
1. Go to any blog that you can read on the reader, and publish a post that includes the text `:)`
2. View the post in the reader and see a broken image instead of a smiley emoji:
smiley-emoji-broken-image

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4037 - when resizing images in the reader detail, we now skip wp.com emojis since they're already correctly sized. Refer to #4037 for steps to repro the problem prior to this PR.

### CODE REVIEW

**Comment by maxme** [comment]
Works well, probably not related to this patch but I noticed a weird squashed smileys on a Genymotion 4.1.1 emulator:

screenshot-2016-05-02_15 40 22 659

Works well on other devices I tested this on.

**Comment by maxme** [comment]
I think this is because the post is empty (only contains 2 smileys)

**Comment by nbradbury** [comment]
@maxme I opened issue #4046 for the squashed smilies.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
