### PR TITLE
More logs to the dependency tree script

### PR DESCRIPTION
**Pull request by ovitrif**
The PR adds extended (& hopefully better 🤞🏽) logging to the [`dependency-tree-diff.sh`](https://github.com/wordpress-mobile/WordPress-Android/blob/e1570fc871c41921bbf36c7de4517667cf35decf/tools/dependency-tree-diff/dependency-tree-diff.sh) script.

## To test:
Look into the:
- [circleci logs when `.gradle` files **have** been changed ↗️](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19197/workflows/f75c0737-6fea-4274-ae39-4651683fab47/jobs/69148)
- [circleci logs when `.gradle` files **haven't** been changed ↗️](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/30029/workflows/be0897bc-8cc8-4de7-bdeb-7fcc1bff0e8b/jobs/120857)

## Regression Notes
1. Potential unintended areas of impact
   N/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
   N/a

3. What automated tests I added (or what prevented me from doing so)
   N/a

### PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Review Notes
- This PR is based on the [woocommerce-android PR #6167](https://github.com/woocommerce/woocommerce-android/pull/6167); thanks @kidinov 🙇‍♂️
- One review should be enough for merging

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
Great stuff, thank you Ovi! ❤️ 🚀 🌟

Did a review of the logs in CI and the output looks great, we should be able to figure any problems with this job easier next time. 💯

However, and before we merge this can you double check the CI output as well, on the [WCAndroid equivalent PR](https://github.com/woocommerce/woocommerce-android/pull/6167) I was able to see more output (see [here](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19197/workflows/f75c0737-6fea-4274-ae39-4651683fab47/jobs/69148)), while in this PR I am only able to see up until `--> Target branch is trunk`. This is most probably because the script exited due to the fact that the Gradle file haven't changed since (see `exit 0`), but this makes me wonder how and why the WCAndroid output did show more than that.

I am approving this PR anyway, since I am pretty sure that we will get the result we want when the diff will run next time, but I just wanted to mention that in case you want to somehow manually trigger it just to be on the safe side. Ah, actually @kidinov provided the CI logs of a previous build that he did to test the log output, the [final CI build logs](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19198/workflows/44b298e6-a9c5-4522-95bf-7b3a72fd97cb/jobs/69149) for WCAndroid didn't include this extra output as well, just as expected. 😊

**Comment by ovitrif** [comment]
> However, and before we merge this can you double check the CI output as well, on the https://github.com/woocommerce/woocommerce-android/pull/6167 I was able to see more output (see [here](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19197/workflows/f75c0737-6fea-4274-ae39-4651683fab47/jobs/69148)), while in this PR I am only able to see up until --> Target branch is trunk. This is most probably because the script exited due to the fact that the Gradle file haven't changed since (see exit 0), but this makes me wonder how and why the WCAndroid output did show more than that.
> [...]
> Ah, actually @kidinov provided the CI logs of a previous build that he did to test the log output, the [final CI build logs](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19198/workflows/44b298e6-a9c5-4522-95bf-7b3a72fd97cb/jobs/69149) for WCAndroid didn't include this extra output as well, just as expected. 😊

Thank you for the review and the remark @ParaskP7 🙇‍♂️; let me see if I can wrangle somehow to test the whole flow, also when we're not going the `exit 0` route 🤞🏽

**Comment by ovitrif** [comment]
@ParaskP7 I added a temporary test commit ([108e194](https://github.com/wordpress-mobile/WordPress-Android/commit/108e194027202b5ccf37dacb5ff21589060d6688)) for testing the flow with dependency changes & updated the pr description to this:

>Look into the:
>
> - [circleci logs when .gradle files have been changed ↗️](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/19197/workflows/f75c0737-6fea-4274-ae39-4651683fab47/jobs/69148)
> - [circleci logs when .gradle files haven't been changed ↗️](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/30029/workflows/be0897bc-8cc8-4de7-bdeb-7fcc1bff0e8b/jobs/120857)

Force-pushed afterwards to have the same history that you reviewed on 🙇‍♂️

Thank you, looks much better now with a clear preview of the new logging 🎉

**Comment by ParaskP7** [comment]
> @ParaskP7 I added a temporary test commit ([108e194](https://github.com/wordpress-mobile/WordPress-Android/commit/108e194027202b5ccf37dacb5ff21589060d6688)) for testing the flow with dependency changes & updated the pr description to this:

This is awesome @ovitrif thank you so much for doing that and proving the logs, you rock! 🚀 

PS: I reviewed both logs and can confirm its correctness, it's a 🟢 light from my side!

> Force-pushed afterwards to have the same history that you reviewed on 🙇‍♂️

🥇 

> Thank you, looks much better now with a clear preview of the new logging 🎉

💯

**Pull request merged**
