### PR TITLE
Fix crashes with Traffic tab when Talkback enabled

### LINKED ISSUE #20287: TRAFFIC tab crashed when Talkback is enabled.
### Expected behavior
The traffic tab should work with accessibility.

### Actual behavior
When Talkback is enabled, the app crashes on opening the Traffic Tab.

### Steps to reproduce the behavior
1. Log in JP app.
2. Enable "stats_traffic_tab" from "Me → Debug settings"
3. Enable Talkback from the device settings.
4. Open "My Site → Stats"
5. Open the TRAFFIC tab and select By week, By month or By year.
6. Notice it crashes.

https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/65386de6-2518-4e4b-beeb-46c89800afb7

### PR DESCRIPTION
**Pull request by aditi-bhatia**
Fixes #20287 

This PR fixes two bugs. The first bug was where the Stats traffic tab would crash when toggling between granularities with Talkback enabled. This crash was due to an `index out of bounds` exception which was occurring because we were using an incorrect value for the data size. 
The second bug was a crash which would happen after double tapping on the individual bars within a graph. This was due to an error parsing the date, which was incorrectly being parsed using the granularity of the graph itself (i.e `months`), instead of the granularity of the bar (i.e. `weeks` in a `month` chart).

-----

## To Test:
1. Enable the `stats_traffic_tab` feature flag from `Me` → `Debug settings`
2. In device settings, enable Talkback (accessibility). 
3. Open `My Site` → `Stats`.
4. Open the `Traffic` tab and toggle between `week`, `month`, and `year`. Try clicking on the bars themselves as well.
5. Double tap on the graph bars.
6. Ensure you see no crash in steps 4 and 5 + Talkback works as expected.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

7. What I did to test those areas of impact (or what existing automated tests I relied on)

    - None

8. What automated tests I added (or what prevented me from doing so)

    - None

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [x] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/278">24.4</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
Thank you for addressing the crash, Aditi.
I have encountered another crash when double-tapping on a bar. Talkback prompts "Double tap to activate", which was helping to select the bar on granularity tabs. However, there is no bar selection functionality on the TRAFFIC tab.
If you try Talkback when `stats_traffic_tab` is off, you'll see what I mean. Can we remove "Double tap to activate" on the TRAFFIC tab? This should also resolve the crash.

**Comment by aditi-bhatia** [comment]
Hi @irfano, I'm seeing/hearing `double tap to activate` with both the feature flag `enabled` and `disabled`. I'm also able to select bars with the feature flag disabled 🤔 Can you clarify?

**Comment by aditi-bhatia** [comment]
This is the crash I'm seeing on `double tap` of the bars. Since Talkback prompts `double tap to activate` with the feature flag disabled, I don't think it's a good idea to remove it, but open to discussion.
Screenshot 2024-03-01 at 1 02 14 PM

**Comment by aditi-bhatia** [comment]
Hi @irfano, I went ahead and fixed the second date-related crash discussed above and updated the PR description/testing steps. You should no longer see a crash when double tapping the bars and the functionality should match that of with the feature flag turned off. Let me know what you think 👍

**Review by irfano — APPROVED** [review]
This fixes all crashes related to accessibility. Good job! 
The Talback still works as before when the flag is off. But the Talkback shouldn't prompt "double tap to activate" on the TRAFFIC chart. I opened a separate https://github.com/wordpress-mobile/WordPress-Android/issues/20363 for it since it's not a crash.

**Comment by aditi-bhatia** [comment]
> This fixes all crashes related to accessibility. Good job!
> The Talback still works as before when the flag is off. But the Talkback shouldn't prompt "double tap to activate" on the TRAFFIC chart. I opened a separate https://github.com/wordpress-mobile/WordPress-Android/issues/20363 for it since it's not a crash.

Sounds good, thanks!

**Pull request merged**
