### PR TITLE
Accessibility labels added for tabbar items

### LINKED ISSUE #2769: Add accessibility labels for tabbar

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #2769. I have tested it with voice over, but tap & hold doesn't bring up a label. I am assuming there is nothing we can do about it.

### CODE REVIEW

**Comment by nbradbury** [comment]
This is intended for 4.2, not 4.3, right?

**Comment by nbradbury** [comment]
Showing the content description in a toast when long-pressing a tab would be nice as well. You can do that by replacing [these lines](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/SlidingTabLayout.java#L322-L325) with this:
```
final String desc = mContentDescriptions.get(i, null);
if (desc != null) {
    tabView.setContentDescription(desc);
    // show toast with content description on long click
    tabView.setOnLongClickListener(new OnLongClickListener() {
        @Override
        public boolean onLongClick(View v) {
            int offsetX = v.getLeft();
            int offsetY = v.getTop() + v.getHeight() + (v.getHeight() / 2);
            Toast toast = Toast.makeText(v.getContext(), desc, Toast.LENGTH_SHORT);
            toast.setGravity(Gravity.LEFT | Gravity.TOP, offsetX, offsetY);
            toast.show();
            return true;
        }
    });
}
```

**Comment by oguzkocer** [comment]
@nbradbury I've made the change you requested, it's working great :) Thanks for your help!

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
