### PR TITLE
Feature/58 filter comments by status rest api

### PR DESCRIPTION
**Pull request by mzorz**
Addresses #58. Differs from #3691 in that this one uses REST api instead of XML RPC, and deals with a possible migration (i.e. a device running the current released android app, with stuff in its database, updates to this version running REST api for comments).

### CODE REVIEW

**Comment by mzorz** [comment]
Also, this pull request introduces a draft idea to enforce the [Flux pattern](https://facebook.github.io/flux/docs/overview.html): in the public methods in the `RestClientUtils` class, we have a `FluxProxyListenerBridge` implementing `RestRequest.Listener` that enforces the flow in which things need be done (flux lifecycle). The enforcing is done by first calling the `onSave`  method of the `FluxProxyListener` interface, then immediately after calling `onDataReady` on the same interface, providing a way to ensure that for any API call we first save it to the database and then return the obtained objects for further processing.

Here the definition of `interface FluxProxyListener`

    public interface FluxProxyListener<T> {
        /** Called when a response is received and needs be saved. */
        public T onSave(JSONObject response);
        /** Called after onSave() is called and data is ready to be processed */
        public void onDataReady(T response);
    }

And here the bridge that enforces that flow (`onSave` first, `onDataReady` after)

    private class FluxProxyListenerBridge implements Listener {

        FluxProxyListener mFluxListener = null;

        public FluxProxyListenerBridge(FluxProxyListener fluxListener){
            mFluxListener = fluxListener;
        }

        @Override
        public void onResponse(JSONObject response) {
            Object result = mFluxListener.onSave(response);
            mFluxListener.onDataReady(result);
        }
    }

Finally, an example of this (in this case, the `getComments` method which I implemented for this feature):

    public void getComments(String siteId, Map<String, String> params, final FluxProxyListener listener, FluxProxyErrorListener errorListener) {
        String path = String.format("sites/%s/comments", siteId);
        FluxProxyListenerBridge listenerBridge = new FluxProxyListenerBridge(listener);
        get(path, params, null, listenerBridge, errorListener);
    }


The idea should be for all methods in RestClientUtils to follow this structure, so the actual API would make sure we save things to the database. The implementation of actually saving and doing something else with the data once saved is left to each instance of FluxyProxyListener passed as argument, as the particularities of _how to save the data_ is better known to the caller at a higher level (that who knows how data is structured) rather than the RestClientUtils class itself.

**Comment by maxme** [comment]
> Also, this pull request introduces a draft initial idea to try enforcing the Flux pattern: in the public methods in the RestClientUtils class, we have a FluxProxyListenerBridge implementing RestRequest.Listener that enforces the flow in which things need be done (flux lifecycle). The enforcing is done by first calling the onSave method of the FluxProxyListener interface, then immediately after calling onDataReady on the same interface, providing a way to ensure that for any API call we first save it to the database and then return the obtained objects for further processing.

I really like the Flux pattern, actually our future implementation of the [network + persistence layer](https://github.com/wordpress-mobile/WordPress-Stores-Android) is based on Flux. But in that patch, it's only adding more complexity and using it in only one of our REST call doesn't make much sense.

**Comment by mzorz** [comment]
Awesome! This was just an idea to start a conversation going :)
First things first, 100% agreed the flux implementation in the network + persistence layer repo you started is the way to go long run. Maybe calling this piece of code anywhere near "Flux" was misleading! (my clarification to “_draft initial idea_” didn’t seem to kick in really well) 

> and using it in only one of our REST call doesn't make much sense.

Yes - I wasn't intending to change every method in that class to follow this principle without getting your feedback first :) - if it was good to you guys, then I would go and apply it consistently as said above

> But in that patch, it's only adding more complexity 


Let me explain a bit where this comes from: I observed a pattern that can be seen in [`org.xmlrpc.android.ApiHelper`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/xmlrpc/android/ApiHelper.java), where the methods accessing the network also then persist retrieved data to the database. Also, I've noticed the adapters are the ones reading the db and serving data to the UI layer, so it all looked pretty much like you were following the flux pattern (well actions impact the database and then the UI always reflects on the database). Even if not naming the components in the architecture, the main core concepts seemed to be there.
So, given the same method that retrieves from the network also saves to the DB, I thought it would be cleaner to have an interface to make a separation in responsibilities in this regard ( `interface FluxProxyListener<T>` ) and a class whose sole purpose is to enforce these two steps happen in that order 1. fetch 2. save (`FluxProxyListenerBridge `).
Of course, this all is assuming the RestClientUtils would follow a similar pattern that ApiHelper does (like, at some point in history things started to get migrated from xmlrpc to REST api). Is it correct? If it is, ok so, that said, if we only try to literally follow the same structure then (the `save` action happens in `RestClientUtils`) we need that class to know about the details of what kind of objects it's dealing with (basically, the same that happens with `ApiHelper` in xmlrpc)  - unless we use an interface to separate this. Using an interface adds minimal overhead while keeping it cleaner, but no harm done if we just follow the retrieve/save flow inside RestClientUtils (we’ll just have lots of imports and code particular to knowing how to handle/convert JSONObject to our data models in each method there).

Hope it clarifies a bit, otherwise just let me know and I'll take this interface out and only leave the RestClientUtils implementation of getComments.

BTW, in this regard, which one is the preferred way to go:

a) the implementation following xmlrpc (https://github.com/wordpress-mobile/WordPress-Android/pull/3691) 
b) or this one? (using REST for `getComments`)

Thanks for reviewing and looking forward to your comments @maxme

**Comment by maxme** [comment]
>  I thought it would be cleaner to have an interface to make a separation in responsibilities in this regard 

I get your point, but we're pretty much in maintenance mode for this part of the code, it needs some deeper changes and this is just one more bandaid.

> a) the implementation following xmlrpc (#3691) 
> b) or this one? (using REST for getComments)

Ideally both, but both in the same patch ;). 

The WordPress.com REST API only works for WordPress.com and Self Hosted sites connect via [Jetpack](http://jetpack.me/) - so if someone uses the app with a Self Hosted site that is not connected through Jetpack, he won't be able to filter his comments.

XMLRPC calls work on all the sites (WordPress.com, Self Hosted with our without Jetpack), so if the XMLRPC calls aren't limitted to implement the feature, this is usually the way to go. But apparently in that case XMLRPC calls prevent you to fetch trashed comments (make sure this is true maybe by reading the server xmlrpc code, I'll have a look at it later, it could save you the REST implementation).

Since this is a trial project, I don't think this is super important.

**Comment by mzorz** [comment]
Great, thanks for clarifying where we are at! I hope I'm on the same page now :+1: 

> But apparently in that case XMLRPC calls prevent you to fetch trashed comments (make sure this is true maybe by reading the server xmlrpc code, I'll have a look at it later, it could save you the REST implementation). 

I have tested XMLRPC for `trash` filter and it works too (even if the documentation does not reflect that, and the commented code on Android suggests `trash` only works for REST)

> Ideally both, but both in the same patch ;).

I'll merge the REST Api call into this patch but will only leave the XMLRPC call wired in, sounds good?

**Comment by maxme** [comment]
> I'll merge the REST Api call into this patch but will only leave the XMLRPC call wired in, sounds good?

Yes please, and I presume both branches share the same Activity / Fragment / Adapter code.

**Comment by mzorz** [comment]
Translated changes to add REST API support for `getComments` on https://github.com/wordpress-mobile/WordPress-Android/pull/3691 (leaving XMLRPC wired in only as agreed)
I guess we can close this one now, right @maxme?

**Comment by maxme** [comment]
> I guess we can close this one now, right @maxme?

Yep.

**Pull request closed without merging**
