### PR TITLE
[Build] Remove Gradle Enterprise from Project

### PR DESCRIPTION
**Pull request by ParaskP7**
Since `Gradle Enterprise (GE)` is shut down, at least temporarily (see `paaHJt-4Ap-p2`), this PR removes the existing `Gradle Enterprise` configuration as well (234a185ae7aa4a6dedf1b4aaf9a0234eedcfbd8a + 79d80cef8236a45185c55784a9a5459dee524b6a).

Also, this PR adds back the previously removed custom Gradle related `buildScan` and `buildCache` configuration (0a79ca165be9ecd106f0c4557808fa81e691f5eb + 89efb1754416bbd0db1cf59c236e29f078736ea2).

FYI: While adding back the previously removed custom Gradle related `buildScan` and `buildCache` configuration, while the previous configuration only targeted `CI`, this new configuration also enables those for `LOCAL` builds. 🤞 

PS: I also chose not to bring back the `GRADLE_ENTERPRISE_ANALYTICS_DISABLE`, `GRADLE_ENTERPRISE_ANALYTICS_USERNAME`, and `GRADLE_ENTERPRISE_ANALYTICS_HOSTNAME` configuration that was added to `buildScan` afterwards (#16489). And this was done due to the fact that I don't think this kind of obfuscation is still necessary for when working without `Gradle Enterprise`. 🤔

-----

To test:

- (`GE`): Verify `LOCAL` and `CI` builds no longer output the `A network error occurred.` error at the end of the build, related to it failing to connect to `Gradle Enterprise` since it has been shut down for day now.
- (`buildScan`): Verify `LOCAL` and `CI` builds are publishing the build scan at the end of the build, and create the corresponding build scan link.
- (`buildCache`): Verify `LOCAL` and `CI` builds are able to use the remote build cache. ⚠️

-----

The ⚠️ above on the `buildCache` functionality is due to the fact that even during my local testing, after re-configuring `buildCache`, it seems that builds are failing to connect to the remove http build cache ([url](http://10.0.2.215:5071/cache/)), see specific errors below:
  - `Could not load entry 2808becc7dc09f5e801fd94fca56cd08 from remote build cache: Connect to 10.0.2.215:5071 [/10.0.2.215] failed: Connect timed out`
  - `The remote build cache was disabled during the build due to errors.`

~~Thus, I added the `[Do Not Merge]` title prefix and the `[Status] Not Ready for Merge` label.~~

**UPDATE**: `buildCache` (and `buildScan`) got disabled for local builds, as such, this ⚠️ is no longer relevant as it was only applicable to local builds.

-----
## Regression Notes

1. Potential unintended areas of impact

    - Build scan is not working as expected or makes `LOCAL` build slower than usual (due to `uploadInBackground` misconfiguration or otherwise).
    - Build cache is not working as expected or makes builds slower than usual (due to slow download speeds or otherwise).

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

    - N/A

-----

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: @oguzkocer I added you as the review in this PR and [this other](https://github.com/Automattic/buildkite-ci/pull/152) Buildkite CI PR, which is (kind of) associated with this change too, just in case you are able to help out with the `Gradle Cache` configuration, welcome (😅 ), apologies for the shameless plug and thank you! 🙇 🙏 🥇

**Comment by oguzkocer** [comment]
> FYI: While adding back the previously removed custom Gradle related buildScan and buildCache configuration, while the previous configuration only targeted CI, this new configuration also enables those for LOCAL builds. 🤞

If we want to add the `buildCache` for local builds, I think that's fine. Although I don't think the server we use for the build cache is accessible outside of our AWS cluster. I'll defer that to @jkmassel.

However, I really don't think we want to publish our build scans to the public automatically. We enabled the build scans in GE for local builds, because we owned the data in GE. There is no longer any benefit to publishing a scan every build because we won't be able to aggregate that data. I'd also be uncomfortable publishing all my builds to Gradle especially if there was no easy way to avoid it. Since developers can publish a scan when they need it by adding `--scan` argument to their Gradle commands, my suggestion would be to disable this behavior. I hope my reasoning makes sense.

> PS: I also chose not to bring back the GRADLE_ENTERPRISE_ANALYTICS_DISABLE, GRADLE_ENTERPRISE_ANALYTICS_USERNAME, and GRADLE_ENTERPRISE_ANALYTICS_HOSTNAME configuration that was added to buildScan afterwards (https://github.com/wordpress-mobile/WordPress-Android/pull/16489). And this was done due to the fact that I don't think this kind of obfuscation is still necessary for when working without Gradle Enterprise. 🤔

It's actually more important to have these because now the build scan data is not owned by us. If we are able to keep the obfuscation, I think we should. Having said that, if we disable the automatic build scan publishing as I suggested above, I don't think this is too important one way or another. Personally, when I publish a build scan, I always delete it when I am done and anyone else paranoid like me can do the same. 🤷

**Comment by oguzkocer** [comment]
> The ⚠️ above on the buildCache functionality is due to the fact that even during my local testing, after re-configuring buildCache, it seems that builds are failing to connect to the remove http build cache ([url](http://10.0.2.215:5071/cache/)), see specific errors below:

I think this is likely because the server is not accessible outside of the AWS cluster as I mentioned in my other comment - that's unless something has changed while I was AFK. I'll defer to @jkmassel on this one.

---

P.S: @ParaskP7 Just as an FYI, I am not leaving any code review suggestions at the moment, because these discussions might require updates to it. It'll be cleaner to review the code once these are settled.

**Comment by ParaskP7** [comment]
👋 @oguzkocer and thanks for your input, much appreciated! 🥇 

> If we want to add the buildCache for local builds, I think that's fine. Although I don't think the server we use for the build cache is accessible outside of our AWS cluster. I'll defer that to @jkmassel.

That's good to know, I wasn't aware of the fact that the build cache might not be accessible outside of our AWS cluster. 👍 

This previous comment on our custom `buildCache` configuration, and more specifically this `...at least for now` gave me some confidence that we might be able to try and utilize build cache locally: `// Build cache is only enabled for CI, at least for now` (see [here](https://github.com/wordpress-mobile/WordPress-Android/pull/14863/files#diff-7f825392aa37acd1cee0c2e7b9bb7366ad6eac64f3e6cdd816e156bcb69d30deR82))

Also, me getting the 👍 from @jkmassel here (`paaHJt-4Ap-p2#comment-7129`) gave me the impression that we could use `buildCache` even locally, at least trying it out, since I didn't get a specific response to my question about enabling that on local builds. 🤷 

FYI: I'll go ahead and disable `buildCache` for local builds until we figure out:
1. If we are able to access build cache outside our AWS cluster.
2. If we want to do that above or even enabled build cache locally for that matter.

> However, I really don't think we want to publish our build scans to the public automatically. We enabled the build scans in GE for local builds, because we owned the data in GE. There is no longer any benefit to publishing a scan every build because we won't be able to aggregate that data.

👍 

> I'd also be uncomfortable publishing all my builds to Gradle especially if there was no easy way to avoid it. Since developers can publish a scan when they need it by adding --scan argument to their Gradle commands, my suggestion would be to disable this behavior. I hope my reasoning makes sense.

Your reasoning makes sense. 💯 

FYI: I'll go ahead and disable `buildScan` for local builds.

> It's actually more important to have these because now the build scan data is not owned by us. If we are able to keep the obfuscation, I think we should. Having said that, if we disable the automatic build scan publishing as I suggested above, I don't think this is too important one way or another.

Yes, let's disable the `buildScan` for local builds for now and then take it from there.

> Personally, when I publish a build scan, I always delete it when I am done and anyone else paranoid like me can do the same. 🤷

😅 I actually understand where you are coming from, maybe I should start doing the same and be more mindful about what I share, with whom and for what reason. 💯 

> I think this is likely because the server is not accessible outside of the AWS cluster as I mentioned in my other comment - that's unless something has changed while I was AFK. I'll defer to @jkmassel on this one.

👍 

> P.S: @ParaskP7 Just as an FYI, I am not leaving any code review suggestions at the moment, because these discussions might require updates to it. It'll be cleaner to review the code once these are settled.

👍

**Comment by ParaskP7** [comment]
👋 @oguzkocer @jkmassel !

> FYI: I'll go ahead and disable `buildScan` for local builds.

This is now done: b984404ecdc62f9398ea6440fadddcf6da9a6f79

> FYI: I'll go ahead and disable `buildCache` for local builds until...

This is now done: 381fc8d98241d7e34bdf3350b3b08c0b65b135f3

**Review by oguzkocer — APPROVED** [review]
The build scan is published from CI tasks and the remote build cache seems to be working. The issues with local build cache and build scans are also resolved now. :shipit: 

Screen Shot 2023-03-05 at 5 27 24 PM

**Comment by ParaskP7** [comment]
Awesome, thank you so much for your review and testing on that @oguzkocer , very helpful as always! 🙇 ❤️ 🚀

**Pull request merged**
