### PR TITLE
Hide/show the bottom navbar on search action

### PR DESCRIPTION
**Pull request by hypest**
Note: this PR is opened against another PR ([the bottom nav phase2 PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7680))

I've been in touch with @nbradbury and since he's AFK at the time of writing, I investigated the issue and came up with this PR.

### Issue
The bottom nav bar stays visible when searching in the Reader. As per the Material Design guidelines, it should be hidden when the virtual keyboard is visible.

### Solution
Unfortunately, there is no robust way to detect or follow the IME's state. There a a few _hacks_ on how to follow it but I don't think those are practical. Until we come up with a workable solution that can be implemented across the app, this PR offers a compromise: Hide/show the bottom nav when the search action is active in the Reader page.

We don't need to accept this PR. It's opened as a small proposal/solution.

### To test
1. Go to the Reader and notice the bottom nav being visible
2. Tap on the search button to initiate the search mode. Notice the virtual keyboard opening and the bottom nav disappearing.
3. Hit the _system_ Back button (not the toolbar one) and notice the virtual keyboard disappearing but the bottom nav bar still be hidden
4. Hit "Back" again to exit the search more. Notice the bottom nav re-appearing.

### CODE REVIEW

**Comment by nbradbury** [comment]
Thanks for tackling this @hypest! I think this works fine - it's pretty close to what I would've done, and like you I wasn't able to resort to hacks to determine the keyboard visibility.

One thing, though: if the user has a hardware keyboard, what should happen to the bottom nav?

@iamthomasbishop ☝️ That may be a question for you.

**Comment by nbradbury** [comment]
@iamthomasbishop I think keeping the nav visible for hardware keyboards is the best approach. It doesn't get in the way, and hiding it would be awkward IMO.

@hypest If you like I can take this PR over from you.

**Comment by hypest** [comment]
> @hypest If you like I can take this PR over from you.

Work away @nbradbury , it's all yours :)

**Comment by nbradbury** [comment]
@hypest I updated this PR to skip hiding the bottom nav if there's a hardware keyboard present. I also consolidated all the calls to check for a hardware keyboard, and renamed the controller methods (I prefer they start with `on...`).

**Comment by hypest** [comment]
Hey @nbradbury, btw, feel free to merge this PR when you think is ready. 👍

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
