### PR TITLE
Fix #2282: Prevent posts from being opened if uploading

### LINKED ISSUE #2282: Double Posting
I've found myself double posting via the app a number of times

What I do:
1. Create a post
2. Add an image
3. Hit publish
4. Say to myself "hmm, I didn't get any confirmation, I wonder if that worked?"
5. Open the post
6. Hit publish again
7. Facepalm

### PR DESCRIPTION
**Pull request by solinger10**
Followed @maxme's recommendation and made posts unable to be opened if they are uploading.

### CODE REVIEW

**Comment by solinger10** [comment]
#2282

**Comment by maxme** [comment]
We should show a toast message to inform the user that post can't be opened.

**Comment by maxme** [comment]
Note: see https://github.com/wordpress-mobile/WordPress-Android/blob/fc9f1990b7562ea2c5650b0ca5f0321e73b9f018/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ToastUtils.java

**Comment by solinger10** [comment]
Sure, I just hard coded in the message "Unable to open this post". Should I be using something from the strings file or adding an extra line to it?

**Comment by maxme** [comment]
> Should I be using something from the strings file or adding an extra line to it

Yes, please add that string to https://github.com/wordpress-mobile/WordPress-Android/blob/8f2a46ff1f8c223e9ecba97014455a30051a824a/WordPress/src/main/res/values/strings.xml

Also, I prefer "Unable to open this post while it's uploading" (or something similar), so the user knows he has to wait before retrying.

**Comment by maxme** [comment]
@solinger10, project doesn't compile (you need to prefix apostrophes by "\" in the `strings.xml` file)

**Comment by solinger10** [comment]
Whoops, sorry about that. Looking at it, I think it looks better when the toast fits on one line so I removed the word "this" from the message also.

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
