### PR TITLE
Jetpack: Merge security settings master branch

### LINKED ISSUE #6194: Jetpack: Add Jetpack Security Settings
- [x] Monitor uptime - #6273
- [x] Send Notification via e-mail - #6273
- [x] Send app Notification - #6273
- [x] Prevent brute force attacks - #6408
- [x] Whitelisted IP addresses - #6408
~- [ ] Spam filtering~ - Probably not implementing
- [x] Allow login with .com credentials - #6440
- [x] Match accounts using e-mail - #6440
- [x] Require 2FA - #6440
- [x] Learn More - #6553

Problems to address before merging:
- [x] Sanitize Whitelist IP's/ranges - #6571
- [x] Verify app update path
- [x] Nest views of nested preferences - #6571
- [x] Improve error handling - #6579

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #6194. All the work has been reviewed in a series of PRs against this feature branch. A quick pass to make sure all the new settings work is probably sufficient, I'm running a more extensive test session to try and catch any edge case bugs.

cc @oguzkocer since you reviewed all the other work. I know you're swamped and still catching up from your time off so maybe @mzorz, @daniloercoli, or @nbradbury wouldn't mind taking this one?

### CODE REVIEW

**Comment by daniloercoli** [comment]
screen shot 2017-10-18 at 13 11 34

Noticed the wording is a bit different in the Monitor Module settings. 
The app referrers to `push notifications` instead it should be `Notifications` ? 
Since we're creating a new note that is shown in the wpcom web sidebar, and sent to devices and browsers with web notifications enabled.

**Comment by daniloercoli** [comment]
I hadn't enabled the monitor module in Jetpack on my site, but the UI was available in the mobile app. The module was ON.

In Calypso there were no trace of it under `Security` tab.  I have to enable the module on the site. Should we check if the module is enabled before showing it on the mobile UI?

**Comment by tonyr59h** [comment]
> The app referrers to push notifications instead it should be Notifications ?

I hadn't thought of that potential for confusion. [iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/7724) uses the same semantics as this PR and it's what was decided in #6194. I think we should ship as-is and take care of it in another PR if we decide to change it.

**Comment by tonyr59h** [comment]
> I hadn't enabled the monitor module in Jetpack on my site, but the UI was available in the mobile app. The module was ON.

It being on is definitely a problem. When I disable it on my site it's still available in Calypso. Are you checking it via `https://wordpress.com/settings/security/[yoursite].com` or `[yoursite].com/wp-admin/admin.php?page=jetpack#/security`? Monitor settings don't appear in the latter for some reason, but they always do in the former.

**Comment by daniloercoli** [comment]
> It being on is definitely a problem. 

That was problem on test site I think, that is super slow so both Calypso and the app cache the prev values and take some time to refresh the UI with new values.

**Comment by daniloercoli** [comment]
LGTM! :shipit:

**Pull request merged**
