### PR TITLE
Jepack App (Basic): UI Tests for Screenshots

### PR DESCRIPTION
**Pull request by zwarm**
Parent #14634 

This PR adds Jetpack App Screenshots support, specifically new UI tests were added for:
- Site
- Activity Log
- Scan
- Backup Download
- Stats

It is best to review this PR by commit. There are a lot mock `.json` file changes, so the file count is high, as well as the number of lines. 

The way I approached this work was as follows:
- Executed WP connected tests locally before any coding changes to check for all passing
- Executed WPScreenshotTest.wPScreenShotTest before any coding changes to check for all passing
- Fixed failing WP Connected and WPScreenshotTest tests by updating `blocks.json`
- Added JPScreenshotTest 1x1, updating/adding any mock .json files as I encountered errors
- The test section that required the most new .json files was Navigate Sites 
- The test section that required the most updates to .json files was Stats.
- As part of the Stats update, I refactored a good portion of the .json files to be more generic so that could be used for other sites. This mostly included changing either
            -  `urlPath` to `urlPattern` and replacing the hardcoded site id with `.*`. 
            OR
            -  `urlPath` to `urlPattern` and replacing the hardcoded site id with `([0-9]+)`. 
- The code changes are limited to three classes:
    - `WPScreenshotTest`
    - `JPScreenshotTest`
    - `MySitePages.java`
- I added an if statement to both `WPScreenshotTest` & `JPScreenshotTest`, so that they only run when executing against the proper build. `WPScreenshotTest` for WordPress app builds and `JPScreenshotTest` for Jetpack app builds. I found that they both run when connected tests are running and will both fail when run against the wrong build. If you have a better suggestion, I am all ears.
- I had considered creating a androidTestJetpack, but the infrastructure is not set up for it in CI and out of caution for scope, I did not feel it was prudent to start down that road 2 weeks before release. This can be revisited after release.
- For a sanity check, connected tests, WPScreenshotTest and JPScreenshotTest were executed throughout the entire development process, as well as after the final commit.
- There may be changes needed based on design @osullivanchris . All data for stats based on data that is preexisiting. I will cover any design changes in a separate PR because I believe it may include changes to many .json files.

My Site | Activity Log | Jetpack Scan | Jetpack Backup | Stats
-- | -- | -- | -- | --
My Site | Activity Log | Scan | Backup | Stats

To test:
- Check out this branch
- Select a Jetpack debug variant
- Run `JPScreenshotTest.jPScreenshotTest`
- 1 test should pass
------------------------
- Change the build to a WordPress variant
- Run `WPScreenshotTest.wPScreenshotTest`
- 1 test should pass

## Regression Notes
1. Potential unintended areas of impact
WPScreenshots and/or WP Connected tests

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Ran WP connected tests after each JP change
Ran WPScreenshot tests after each JP change

3. What automated tests I added (or what prevented me from doing so)
JPScreenshot

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
Looks good to me! If there's any queries or issues that come up with the data that we're using, just let me know!

**Review by ashiagr — COMMENTED** [review]
Thank you @zwarm for working on this! I tested on `Pixel 3a XL API 29` and screenshots tests ran fine for both the apps, good job 👍.

The only issue I see is when I run connected tests `./gradlew :WordPress:connectedWordPressJalapenoDebugAndroidTest`, I get few errors:

```
com.github.tomakehurst.wiremock.client.VerificationException: 3 requests were unmatched by any stub mapping. Shown with closest stub mappings:
expected:<
GET
/wp/v2/sites/181851495/blocks?per_page=100&context=edit&_locale=user&locale=en_US

context: edit
locale: en_US
_locale: user
Query: per_page = 10
> but was:<
GET
/wp/v2/sites/181851495/blocks?per_page=100&context=edit&_locale=user&locale=en_US

context: edit
locale: en_US
_locale: user
per_page: 100
>

expected:<
GET
/wp/v2/sites/181851495/media
> but was:<
GET
/wp/v2/sites/181851495/blocks?per_page=100&context=edit&_locale=user&locale=en_US
>

expected:<
GET
/wp/v2/sites/181851495/media/

locale: en_US
> but was:<
GET
/wp/v2/sites/181851495/blocks?per_page=100&context=edit&_locale=user&locale=en_US

locale: en_US
>
at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:92)
at com.github.tomakehurst.wiremock.junit.WireMockRule.access$000(WireMockRule.java:34)
at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:74)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.wordpress.android.ui.screenshots.WPLocaleTestRule$1.evaluate(WPLocaleTestRule.java:39)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```

Wondering if commit 7f94ed8c could be causing it. Wdyt?

**Comment by ashiagr** [comment]
Never mind, it ran the second time. Looks like some caching issue.

**Review by ashiagr — APPROVED** [review]
@zwarm, I'm approving this PR. Feel free to merge it now or when corresponding changes are made to the fastlane for taking the screenshots.

**Comment by zwarm** [comment]
> @zwarm, I'm approving this PR. Feel free to merge it now or when corresponding changes are made to the fastlane for taking the screenshots.

Thanks @ashiagr - I know this was a weird one. I'm going to merge, as the JP tests won't run yet, but I need this PR done to start on the next task. 🙇

**Pull request merged**
