### PR TITLE
Implement selected domain UI

### LINKED ISSUE #17901: Update selected domain UI
Update the UI to mark when a domain is selected.

#### Subtasks

- [ ] #18295

### Design

| Before |After |
| - | - |
|  |  |

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)

### PR DESCRIPTION
**Pull request by ovitrif**
Resolves #17901

This PR:
- ★ Implements the logic to highlight the selected domain on the UI
- ⊕ Updates the global primary color in dark mode to conform with the design system
- ⊕ Updates the leading and bottom paddings for domain title to match the design

| 🌑 | 🌞 |
| - | - |
| light | dark |

#### Prerequisite

<details><summary>◐ Toggle the <code>SiteCreationDomainPurchasingFeatureConfig</code> flag</summary>

1. Go to `Me` → `App Settings` → `Debug settings`
2. Scroll to the `Features in development` section
3. Tap on the item corresponding to the flag
4. Tap `RESTART THE APP` button

</details>

### ● Treatment Variation · flag `ON`

- <details><summary><b>Verify</b> UI for selected domain matches the design specs</summary>

   1. See prerequisite
   2. Go to `My Site`
   3. Tap the `↓` arrow at the right of the site name
   4. Tap the `+` at the top right
   5. Tap the `⊕ Create WordPress.com site` button
   6. Skip steps 1 and 2
   7. Enter a text to get domain suggestions
   8. ✅ Tap a few items and compare app's UI vs UI design
</details>

## Regression Notes
1. Potential unintended areas of impact
   N/a - new functionality behind feature flag

9. What I did to test those areas of impact (or what existing automated tests I relied on)
   Manual testing and unit testing

10. What automated tests I added (or what prevented me from doing so)
   Unit test in `SiteCreationDomainsViewModelTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

`n/a` ~~UI Changes testing checklist~~

### CODE REVIEW

**Review by mkevins — APPROVED** [review]
These changes look good, and the code changes look great. Nice work Ovi!

A minor observation I had (though seemingly unrelated with this PR): When I have selected a domain, and then tap back to go back to the theme selection screen, pick a theme again, and return back to the domain search screen, the search input is empty, but the previous results (including the selected domain) are still present. Also, the "Purchase domain" button is still visible. Maybe this is expected, but it felt weird since the search input was still empty. Is this expected behavior?

**Comment by ovitrif** [comment]
> When I have selected a domain, and then tap back to go back to the theme selection screen, pick a theme again, and return back to the domain search screen, the search input is empty, but the previous results (including the selected domain) are still present. Also, the "Purchase domain" button is still visible. Maybe this is expected, but it felt weird since the search input was still empty.

Thank you for finding this and reporting it @mkevins 🙇🏻 !

> Is this expected behavior?

It doesn't feel "expected" to me, but upon checking in production I found it repro's:

<details><summary>🎬 Prod repro scenario</summary>

<video src="https://user-images.githubusercontent.com/4588074/233601199-93d3d271-2590-42de-9a23-ccb704b02625.mp4" style="max-width: 315px;"></video>

</details>


Given the fact that it's in production for a long time, my suggestion going forward is to ignore it for now (cc. @antonis) 🙏🏻

**Comment by antonis** [comment]
> my suggestion going forward is to ignore it for now

I agree that this should not be blocking 👍  Let's open an issue to track this down thought.

**Comment by mkevins** [comment]
> I agree that this should not be blocking 👍 Let's open an issue to track this down thought.

I've opened an issue to track this: https://github.com/wordpress-mobile/WordPress-Android/issues/18311

**Pull request merged**
