### PR TITLE
Add GutenbergKit

### PR DESCRIPTION
**Pull request by geriux**
**Related PRs:**
- https://github.com/wordpress-mobile/GutenbergKit/pull/23
- https://github.com/wordpress-mobile/GutenbergKit/pull/29

This PR adds GutenbergKit behind a feature flag. Due to the complexity of the editor setup in the app, I incorporated the new code into existing files, which made it difficult to work with the mixed Java and Kotlin files.

Most of the editor's functionality should be working, although I disabled some UI elements, such as the undo/redo buttons and certain menu items, until we add support for them.

**Current feature support:**

- Create posts and pages
- Use page layouts from the picker
- Blogging prompts
- Share a website into the editor
- Copy/paste an image into the editor
- Restore the editor's state if the activity is closed
- Upload media from the device’s files within the editor
- Preview posts/pages
- Sync content changes as you type
- Auto-save when closing the editor
- Discard creating a draft if the post is empty (title and content)

-----

## To Test:

> [!NOTE]  
> **Precondition:** Enable the feature flag, Go to the Me tab > Debug settings > `experimental_block_editor`

## Creating an empty post

- Open the app
- Create a new post
- Type a title and some content
- Tap on the back arrow
- **Expect**: The editor to close and the post to autosave and to be uploaded to the server

## Editing an existing post

- Open the app
- Go to the posts section
- Open a post
- **Expect** the post content to be in the editor
- Edit the content
- Close the editor
- Open the post
- **Expect** the content to be updated

## Create an empty page

- Open the app
- Go to Pages
- Add a page
- Select "Create blank page"
- Add some content
- Close the editor
- **Expect** the page to be created with the new content

## Create a page from a layout

- Open the app
- Go to Pages
- Add a page
- Select a layout
- **Expect** the layout to be added into the editor

## Blogging prompts

- Open the app
- Scroll to the "Prompts" section
- Tap on "Answer prompt"
- **Expect** the editor to open with the content of the prompt

## Sharing a site

- Open your browser
- Go to a site
- Open the sharing window
- Tap on the Jetpack/WordPress app
- **Expect** the app to open and the title and link added into the post

## Media upload

- Open the editor
- Add an Image/Gallery block
- Select an image
- **Expect** the media to be uploaded

## Smoke test the current editor

To make sure no regressions were added, smoke testing the current editor would be great, adding some texts and media to make sure it works as expected.

-----

## Regression Notes

1. Potential unintended areas of impact

    - It should only affect the new editor but smoke testing the production version would be good too.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - No new tests were added.

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nbradbury** [comment]
@geriux This is looking really promising but I did run into several issues in my initial round of testing. I'll add each issue as a separate comment.

**Comment by nbradbury** [comment]
Adding an image doesn't work. As the video shows, tapping "Upload" does nothing and tapping "Media Library" just removes the button frame.

https://github.com/user-attachments/assets/0aadcf59-6eed-422e-bca5-9834d9578269

**Comment by nbradbury** [comment]
If I copy an image from Chrome and paste it into the editor, it briefly appears but then gets removed.


https://github.com/user-attachments/assets/d1eae1fb-afca-4059-b3c7-a143577fc9e8

**Comment by nbradbury** [comment]
Sharing an image from Google Photos to the app doesn't work. It creates a new post but the image isn't added.


https://github.com/user-attachments/assets/42c2fc70-cd09-4ba4-b838-33c0cdee6b5f

**Comment by nbradbury** [comment]
Creating a new page from a layout doesn't work.


https://github.com/user-attachments/assets/7f7c1445-f732-4d84-afd2-2abde6d34a67

**Comment by nbradbury** [comment]
There seem to be random problems with the keyboard focus. For example, after I type a list item and press Enter, it correctly moves to a new line and creates a new list item and the software keyboard remains visible but typing is ignored until you tap again. Another example: if I choose to add a quote, it creates the quote block but the keyboard doesn't react until you tap again.

**Comment by dcalhoun** [comment]
👋🏻 @nbradbury. I'd appreciate your review of this pull request and its latest sibling: https://github.com/wordpress-mobile/GutenbergKit/pull/29. Please do not hold back on any critique or suggestions, I welcome them. 

I believe I addressed the issues reported in the [previous review](https://github.com/wordpress-mobile/GutenbergKit/pull/23#issuecomment-2372043892), but let me know if I overlooked anything or you encounter new issues. 

Thanks!

**Comment by nbradbury** [comment]
@dcalhoun I'm seeing some of the same media issues with this PR that I mentioned in [my previous review](https://github.com/wordpress-mobile/GutenbergKit/pull/23#issuecomment-2372043892). Are there build instructions I'm missing? I thought maybe I needed to enable local builds for GutenbergKit, but I see you've updated the reference [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21223/commits/dc27142dd2be0b72521fceb134da2d32812fc5aa) so I assumed that wasn't necessary.

**Update:** I'm assuming I'm testing it correctly because I notice some of the previous problems have been resolved (such as the editor losing focus and not being able to create a page from a layout). The problems I'm still seeing are:

- Inserting device media into a post fails - it looks like it's working, but when the upload completes I'm left with this:

upload

- Trying to select from the media library does nothing, and although inserting from a URL now works the button blacks out when you tap it:
- 
https://github.com/user-attachments/assets/b6387b77-9014-483e-a9bd-a1dfdfe57d91

- Sharing from Google Photos still creates a new post but the media is not inserted

**Comment by dcalhoun** [comment]
> Are there build instructions I'm missing? 

@nbradbury I recommend testing with the [installable prototype](https://github.com/wordpress-mobile/WordPress-Android/pull/21223#issuecomment-2341311367) build provided on the pull request. It provides an environment more closely resembling production. 

If you prefer to build locally, there should not be specific build steps required. Switching to this branch, pulling the latest changes, and syncing Gradle should achieve the correct build output. 

Inserting media from the _Media Library_ option is unsupported at this time. Inserting media from the device should succeed. 

Inserting media from Google Photo succeeds for me. Will you share additional details regarding your testing service and the type of WordPress site you are using? 

<details><summary>Screen recording: Insert from Google Photos</summary>
<p>


https://github.com/user-attachments/assets/17b989ff-331d-4fa4-9fdb-ee12dab017e2



</p>
</details>

**Comment by nbradbury** [comment]
> I recommend testing with the [installable prototype](https://github.com/wordpress-mobile/WordPress-Android/pull/21223#issuecomment-2341311367) build provided on the pull request.

I guess I was thrown off that the installable build comment was dated Sept 10 so I thought it was outdated. I'll test with that and report back.

**Comment by dcalhoun** [comment]
> I guess I was thrown off that the installable build comment was dated Sept 10 so I thought it was outdated.

Ah, the automation edits the existing comment with new build information whenever new commits are pushed to the remote branch. GitHub's UI hides the change long dates behind the "edited" menu.

**Comment by nbradbury** [comment]
@dcalhoun I'm still seeing the same issues with the prototype build, but I believe I've figured out one of them. I was testing with a private site but after I changed the site to hidden attaching device media works. I'm not seeing anything helpful in the log when attempting with a private site.

However, the "Media Library" button still doesn't work, and tapping to add from a URL still blackens the button.

Attempting to share from Google Photos is also not working, and I'm seeing this in LogCat:

```
Error reading orientation of the file: /data/user/0/org.wordpress.android.prealpha/cache/Screenshot_20241014-175920.png (Ask Gemini)
                                                                                                    java.lang.IllegalArgumentException: Volume data not found
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:154)
                                                                                                    	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1229)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1161)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1117)
                                                                                                    	at org.wordpress.android.util.ImageUtils.getImageOrientation(ImageUtils.java:100)
                                                                                                    	at org.wordpress.android.util.ImageUtils.optimizeImage(ImageUtils.java:547)
                                                                                                    	at org.wordpress.android.util.WPMediaUtils.getOptimizedMedia(WPMediaUtils.java:83)
                                                                                                    	at org.wordpress.android.util.MediaUtilsWrapper.getOptimizedMedia(MediaUtilsWrapper.kt:30)
                                                                                                    	at org.wordpress.android.ui.posts.editor.media.OptimizeMediaUseCase.optimizeMedia(OptimizeMediaUseCase.kt:54)
```

And then I see this:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.editor.gutenberg.GutenbergContainerFragment.mediaFileUploadProgress(int, float)' on a null object reference
                                                                                                    	at org.wordpress.android.editor.gutenberg.GutenbergEditorFragment.onMediaUploadProgress(GutenbergEditorFragment.java:1552)
                                                                                                    	at org.wordpress.android.ui.posts.EditPostActivity.onUploadProgress(EditPostActivity.kt:1889)
                                                                                                    	at org.wordpress.android.ui.posts.EditPostActivity.onMediaUploaded(EditPostActivity.kt:3732)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
                                                                                                    	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511) 
                                                                                                    	at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
```

**Comment by dcalhoun** [comment]
> I was testing with a private site [...]

@nbradbury I can reproduce private site failures and will investigate. 

> [...] the "Media Library" button still doesn't work [...]

_Media Library_ support is not built and should not be tested. 

> [...] tapping to add from a URL still blackens the button.

I experience the illegible URL button text and will address this. 

> Attempting to share from Google Photos is also not working [...] 

I am unable to reproduce this currently. From glancing at the [code related to the stack trace](https://github.com/wordpress-mobile/WordPress-Android/blob/dc27142dd2be0b72521fceb134da2d32812fc5aa/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L210-L212), it appears problematic—where a fragment is never assigned, in contrast to the [previous Gutenberg implementation](https://github.com/wordpress-mobile/WordPress-Android/blob/dc27142dd2be0b72521fceb134da2d32812fc5aa/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L214-L216). 

* Are you able to share a screen recording of the steps? 
* Is your site a Simple, Atomic, or self-hosted site? 
* What device and OS versions are you using?

**Comment by dcalhoun** [comment]
@nbradbury I captured a few of your reported issues in separate tickets: 

* https://github.com/Automattic/dotcom-forge/issues/9446
* https://github.com/Automattic/dotcom-forge/issues/9086
* https://github.com/Automattic/dotcom-forge/issues/8678

If suggest we fix the Google Photos insert failures plaguing your site, and then look to review and merge this PR. We could address the aforementioned listed issues in separate PRs. That will reduce PR size and simplify parallel work. WDYT? 

Whenever you have a moment, will you share additional details regarding your experience with Google Photos? Thanks! 

* Are you able to share a screen recording of the steps?
* Is your site a Simple, Atomic, or self-hosted site?
* What device and OS versions are you using?

**Comment by nbradbury** [comment]
> If suggest we fix the Google Photos insert failures plaguing your site, and then look to review and merge this PR. We could address the aforementioned listed issues in separate PRs. That will reduce PR size and simplify parallel work. WDYT?

That works for me!

I'm testing this with a Pixel 7a, API 14. My primary testing site is a free wp.com site but I see the same issue with `content-heavy.wpmt.co`. Video is below. I should add that if I disable the block editor, sharing from Google Photos works.

https://github.com/user-attachments/assets/8f4678c3-5736-4c5b-ab43-4eefbdab7190

**Comment by dcalhoun** [comment]
Thank you for sharing the screen recording. The aspect I overlooked was that unexpected outcome occurs when _sharing_ from Google Photos. I had only tested inserting media from within the editor while using Google Photos as the source. I'll debug the issue and report back.

**Comment by dcalhoun** [comment]
@nbradbury after spending a bit of time investigating sharing media to GutenbergKit, I suggest we review and merge this PR without that feature. The feature was [expressly disabled](https://github.com/wordpress-mobile/WordPress-Android/blob/dc27142dd2be0b72521fceb134da2d32812fc5aa/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L1402-L1403) until we built support. 

While it is simple enough to receive the shared media file path and pass that along to the WebView, security restrictions prevent a WebView from using `fetch` to retrieve the file. We will likely need to create a custom URL scheme allowing for `fetch` to retrieve the file or manage uploading the file to the Media Library within the native host app. The former might allow for leveraging existing logic in the Gutenberg project (preferred outcome), the latter would require platform-specific logic. 

If the rest of the proposed changes are sound from your perspective, WDYT about merging this without the ability to receive shared files and address that separate in https://github.com/Automattic/dotcom-forge/issues/9449?

**Comment by nbradbury** [comment]
> WDYT about merging this without the ability to receive shared files and address that separate

I'm good with that, especially in light of the fact that the feature was purposely disabled.

**Review by nbradbury — APPROVED** [review]
:shipit:

**Comment by dcalhoun** [comment]
@nbradbury great! Once you have time to review https://github.com/wordpress-mobile/GutenbergKit/pull/29, I'll work to merge this work.

**Pull request merged**
