### PR TITLE
fix: Update published post date

### LINKED ISSUE #21001: Unable to change date of a published post
### Expected behavior

If I want to change the date of a published post, I expect to see the new date, but it's not happening.

### Actual behavior

Edit a published post, and before updating/publishing, I change the publish date but the date isn't updating. 

### Steps to reproduce the behavior

1. Open a previously published post and make some changes
2. Before saving the changes, choose change the publish date and then update the post.
3. See that the publish date didn't change. 

This happens on mobile app only. 

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

I tested on my Google Pixel phone with Android, but it was also reported 8323256-zd-a8c and [here](https://link.reviewbot.io/notification?action=share&review=b5dDFzdaAzqC2Pdqno08).

Issue initially opened https://github.com/Automattic/jetpack/issues/37851

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3045

## Description

Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/21001. 

Reverts the changes in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3003 which addressed https://github.com/wordpress-mobile/WordPress-Android/issues/17375. However, those changes introduced a regression in the form of https://github.com/wordpress-mobile/WordPress-Android/issues/21001. 

I was unable to quickly identify a simple solution that solved both the original bug and the regression. Therefore, I opted to merely revert the changes, as https://github.com/wordpress-mobile/WordPress-Android/issues/17375 seems like an outlier, requiring an inaccurate system time by disabling the device's automatic clock synchronization. 

## Testing Instructions

See https://github.com/wordpress-mobile/WordPress-Android/issues/21001.

## Regression Notes

1. Potential unintended areas of impact
    Regressions in various post status. 
2. What I did to test those areas of impact (or what existing automated tests I relied on)
    Manually tested publishing, save as draft, trashing, updating, etc. 
3. What automated tests I added (or what prevented me from doing so)
    Felt less valuable for this revert. Little existing tests to build upon for the modified FluxC code. 

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the ~right-to-left layout)
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jkmassel — APPROVED** [review]
This is definitely the best fix for now.

**Comment by dcalhoun** [comment]
Thanks for the review, @jkmassel. I believe we need to approve and merge https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3045 so that we can update the FluxC reference to point to a commit on the `trunk` branch. 

https://github.com/wordpress-mobile/WordPress-Android/blob/6b4b7dce85ce49fb206702aae6e394050fd9dfc8/build.gradle#L30

Would you be willing to review the FluxC PR? I'm happy to update the WP-Android reference once the FluxC PR is merged.

**Comment by jkmassel** [comment]
> Thanks for the review, @jkmassel. I believe we need to approve and merge [wordpress-mobile/WordPress-FluxC-Android#3045](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3045) so that we can update the FluxC reference to point to a commit on the `trunk` branch.
> 
> https://github.com/wordpress-mobile/WordPress-Android/blob/6b4b7dce85ce49fb206702aae6e394050fd9dfc8/build.gradle#L30
> 
> Would you be willing to review the FluxC PR? I'm happy to update the WP-Android reference once the FluxC PR is merged.

For sure! Please just tag me in it whenever!

**Comment by dcalhoun** [comment]
The [referenced PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3045) is already ready for review. I formally requested your review on it now.

**Pull request merged**
