### PR TITLE
build: bump Hilt/Dagger to `2.50`

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR bumps `Hilt`/`Dagger` dependency to newest stable, `2.50`. It's part of `ksp` migration.

### How to test?

As `Hilt`/`Dagger` should throw compile-time errors if something's wrong, I think testing is not necessary. You can always smoke test the app.

### CODE REVIEW

**Comment by wzieba** [comment]
hi @jarvislin 👋 the GitHub system selected you for the review, but I see you're AFK so I run the random assignment again.

@aditi-bhatia hi! Are you fine with reviewing this PR? 🙂

**Comment by wzieba** [comment]
hi @aditi-bhatia , do you think you'll have the capacity to review this PR this/next week?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/277">24.3</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
@aditi-bhatia is on the support rotation this sprint. I can review this.

**Comment by wzieba** [comment]
gotcha, thank you @irfano !

**Review by irfano — APPROVED** [review]
I smoke-tested basic screens and did not encounter any issues. I also checked [release notes](https://github.com/google/dagger/releases) and did not see any changes that might affect the app during runtime. LGTM! 👍🏻

**Pull request merged**
