### PR TITLE
fix #3340 minor changes to post uploaded notification

### LINKED ISSUE #3340: Minor changes to the "Post Uploaded" notification
* Set the title as “Post/Page Published” or "Post/Page Updated" instead of the generic "Post/Page Uploaded".
* Share the post title with the url

### PR DESCRIPTION
**Pull request by maxme**
fix #3340 minor changes to post uploaded notification. 

https://cloudup.com/cmyA23WzBSj

I'm wondering if we should only show that notification when the post has been published for the first time (ie. went from localdraft or draft to published) @mattmiklic - we could also add an analytics event to see how it's used.

### CODE REVIEW

**Comment by mattmiklic** [comment]
> I'm wondering if we should only show that notification when the post has been published for the first time (ie. went from localdraft or draft to published)

Do users currently get a notification upon publishing a post? Since publishing is usually a direct action, it doesn't seem like we'd need to show them a notification in response (i.e., there's no similar notification when sending a Mail message or posting a Tweet).

I wouldn't want to get a notification after each edit of a post, since I often make multiple small edits after publishing something.

I do see it being useful when the user has scheduled a post -- getting a notification when it has published successfully would make sense there.

**Comment by maxme** [comment]
> Do users currently get a notification upon publishing a post? Since publishing is usually a direct action, it doesn't seem like we'd need to show them a notification in response (i.e., there's no similar notification when sending a Mail message or posting a Tweet).

Yes, this was introduced recently because the "share post" button was removed from the post view. The main purpose is to have the "Share link" button in the notification after publishing. Behavior is copied from the Google Drive app. We had good feedback from our users in Play Store comments about that notification, and I think we should keep it at least for the first publishing.

> I wouldn't want to get a notification after each edit of a post, since I often make multiple small edits after publishing something.

Yes, but on the other hand it's pretty easy to dismiss notifications.

> I do see it being useful when the user has scheduled a post -- getting a notification when it has published successfully would make sense there.

That's actually not the case (and that would be a push nofitication).

**Comment by mattmiklic** [comment]
> Behavior is copied from the Google Drive app. We had good feedback from our users in Play Store comments about that notification, and I think we should keep it at least for the first publishing.

Gotcha, knowing the context that makes sense, then. I do think it makes sense to have some kind of confirmation when an edit is successful. A system-level notification feels a little bit heavy for the use-case, I could see us doing something within the app that the user doesn't have to dismiss, but since it matches the example we're using elsewhere, I'd say go with it (that's a yes to the notification for publishing and editing).

**Comment by maxme** [comment]
> A system-level notification feels a little bit heavy for the use-case

Yeah, IMO it's only good for users who fire an upload and forget it (hide the app or switch to another).

I don't like that idea much but something we could do: When the upload finishes, display a snack bar if the user is still in the app or a notification if he left the app.

**Comment by mattmiklic** [comment]
> When the upload finishes, display a snack bar if the user is still in the app or a notification if he left the app.

I like this idea, I think it would be a little simpler, which feels right.

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
