### PR TITLE
Menus persistence layer - data models and database methods, sans tests

### LINKED ISSUE #3588: Menus Calypso - Persistence layer
Define Menus models, create database table, and implement methods for serialization.

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #3588

Ref #3670.

Needs review: @maxme

I'll open a separate PR with the tests once this is merged.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Marking this as not ready while we work through wpstores investigation.

**Comment by tonyr59h** [comment]
Ready for merge now.

**Comment by maxme** [comment]
I already miss WellSql ;)

**Comment by maxme** [comment]
Should we have an intersection table to manage relationship between Locations and MenuItems?

**Comment by tonyr59h** [comment]
> I already miss WellSql ;)

Same, one of the many reasons to look forward to WPStores integration :)

**Comment by tonyr59h** [comment]
> Should we have an intersection table to manage relationship between Locations and MenuItems?

The relationship between Menus/Locations and Menus/MenuItems is one-to-many, I don't think we need to implement an intersection table. Some [major changes](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/3587-menus-networking/WordPress/src/main/java/org/wordpress/android/models/MenuModel.java#L19) are being introduced on the networking branch. If we decide to move forward with the intersection table I'd prefer to add it on that branch to avoid a nasty merge ;)

**Comment by maxme** [comment]
Ready to :shipit: - can you merge develop into the branch to make travis happy.

**Pull request merged**
