### PR TITLE
Issue/13066 ppn move add category action

### PR DESCRIPTION
**Pull request by zwarm**
Part of #13066 

This PR removes the "Add New Category" link from the select categories bottom sheet and adds a "+" to the toolbar/title area. It also removes "bolding" from the Add Category button on the Add Category view.

Before|After|Before|After
---|---|---|---
|||

**Merge Instructions**
Note: This PR will be merged into a feature branch
Make sure #13167 has been merged (this PR may need a sync after 13167 has been merged - let me know)
Remove the Not Ready For Merge label
Merge as normal

**To test:**

- Launch the app
- Select Blog posts
- Select Edit on a post
- From the edit post view, tap the UPDATE action to launch the bottom sheet
- Tap the categories row to launch the Select categories view
- Notice the "Add new category" link is gone and there is a "+" in the toolbar area
-Tap on the "+" to ensure the Add Category view is launched
- Notice the "Add Category" button text is no longer bold

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ashiagr** [comment]
Thanks @zwarm ! Code-wise it looks good. 

Noticed a scenario when I saw repeated categories:

repeated_categories

I think after I added a category I accidentally dismissed the pop up by clicking outside instead of clicking back arrow on the pop up.

**Comment by zwarm** [comment]
> Noticed a scenario when I saw repeated categories:

@ashiagr  - this was fixed in the previous PR, but I have not merged it into this one yet. You are too quick. Let me merge.

**Comment by zwarm** [comment]
@ashiagr - all ready now. Sorry for the confusion. Thanks again.

**Comment by ashiagr** [comment]
Noticed a crash after pulling latest changes. Blank row was created (steps in [video](https://cldup.com/WQvtwyhc_t.mp4)),  back arrow became unresponsive followed by a crash

```
java.lang.IllegalStateException: it.name must not be null
        at org.wordpress.android.ui.posts.GetCategoriesUseCase$formatCategories$formattedCategories$1.invoke(GetCategoriesUseCase.kt:57)
        at org.wordpress.android.ui.posts.GetCategoriesUseCase$formatCategories$formattedCategories$1.invoke(GetCategoriesUseCase.kt:18)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3304)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3321)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3320)
        at org.wordpress.android.ui.posts.GetCategoriesUseCase.formatCategories(GetCategoriesUseCase.kt:57)
        at org.wordpress.android.ui.posts.GetCategoriesUseCase.getPostCategoriesString(GetCategoriesUseCase.kt:37)
        at org.wordpress.android.ui.posts.PrepublishingHomeViewModel.setupHomeUiState(PrepublishingHomeViewModel.kt:133)
```

Might not be related to this PR. Feel free to ignore it in this PR if it is a known issue.

**Pull request merged**
