### PR TITLE
Update Tracks lib to version 1.0.2

### PR DESCRIPTION
**Pull request by daniloercoli**
Before merge or test this PR we should publish the new artifacts of the Tracks library on Maven central.

I've already created a tag 1.0.2 on the library github site here: https://github.com/Automattic/Automattic-Tracks-Android
You can even use "develop" since the code is the same of the tag.

### CODE REVIEW

**Comment by tonyr59h** [comment]
I compiled locally and linked the library with the WP project and all is running well. What can I inspect to verify that the 1.0.2 changes are working?

**Comment by daniloercoli** [comment]
The only things modified in 1.0.2 was the regexp that validates properties name. https://github.com/Automattic/Automattic-Tracks-Android/pull/9

**Comment by tonyr59h** [comment]
:shipit: 

Good for a merge once it's released to Maven Central. You want to handle that or me?

**Comment by daniloercoli** [comment]
Don't have all the signing stuff or accounts for that. @maxme usually publish things on Maven/PlayStore.

**Comment by tonyr59h** [comment]
No problem, I'll push it up and this when it's available.

**Comment by tonyr59h** [comment]
Released and re-built in Travis, all good :shipit:

**Pull request merged**
