### PR TITLE
Jetpack App Basics: Base colors

### LINKED ISSUE #14298: Jetpack App (Basics): Create Base Color Structure
Parent: #14293

- Update `styles.xml` to extract primary/secondary colors to become placeholders.
- Update `colors.xml` for WordPress app.
- Add `colors.xml` for Jetpack app.
- Add `themes.xml` for the WordPress Login library.
- Make sure to add all the related values directories for various device configuration (`values-night`, `values-v23`, etc).

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #14298 

This PR updates base colors for the Jetpack App
- Updated `styles.xml` to extract primary/secondary colors to become placeholders.
- Updated `colors.xml` for WordPress app.
- Added `colors.xml` for Jetpack app.
- Added `themes.xml` for the WordPress Login library.
- Added the related values directories for various device configuration (values-night, values-v23, values-v27).

**Merge instructions**
- Ensure that PR #14320 & PR #14321 have been merged
- Remove "Not ready for merge" label
- Merge as normal

**Pre test**
- You must update your local copy of `google-services.json` before running the app.
-- Copy existing `org.wordress.android`,  `org.wordress.android.prealpha`, `org.wordress.android.beta` sections and replace with `com.jetpack.android`, `com.jetpack.android.prealpha`, `com.jetpack.android.beta`.

**To Test**
- Build and launch each product flavor. 
- - `wordpressVanillaDebug` (Prod)
- `wordpressWasabiDebug` (Beta)
- `wordpressJalapenoDebug` (Alpha)
- `jetpackVanillaDebug` (Prod)
- `jetpackWasabiDebug` (Beta)
- `jetpackJalapenoDebug` (Alpha)
- Verify that Jetpack build variants show "green" and Wordpress as "Pinkish"

Note that:
- `jetpackDebug` should build all `debug` product flavors related to the `jetpack` dimension.
- `jetpackJalapeno` should build both, the `debug` and `release`, `jalapeno` product flavor for `jetpack` dimension.
- `jetpackWasabi` should build both, the `debug` and `release`, `wasabi` product flavor for `jetpack` dimension.

|Wordpress|Jetpack
|---|---
|WP|JP
PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — CHANGES_REQUESTED** [review]
👋 @zwarm !

I have reviewed and tested this PR as per the instructions, everything almost works as expected, good job! 🌟

Below is a number of things I have gathered for you:
1) Warning (⚠️): The dark theme is not working as expected. This is because the `values-night` version of the main `styles.xml` need to be updated as well.
2) Suggestion (💡): Instead of extracting the `colorPrimary`, `colorPrimaryVariant`, `colorSecondary` and `colorSecondaryVariant` colors into the already existing `colors.xml` file, I suggest creating a new `colors_base.xml` file and extract those new base colors there. This is exactly what the `Woo` team did, which I find great since this means that we are keeping things as separate and explicit as possible. In the end you will end up with two `colors_base.xml` files for both the `values` and `values-night` on the `main` source set and the same on the `jetpack` source set. PS: I also suggest moving the `primary` related semantic colors from the `colors.xml` to the `colors_base.xml` on the `main` source set (this is already done on the `jetpack` source set and as such this will help keeping those consistent with each other).
3) Suggestion (💡): After playing a bit with the `themes.xml` files on the `jetpack` source set and their corresponding `Theme.LoginFlow` style, having seen what `Woo` did as well, I figured out a cleaner and more robust way of doing exactly the same but this time without the need to add anything style related within the `jetpack` source set. So, what I suggest is:
  - Deleting all the `themes.xml` files from the `jetpack` source set,
  - Add a new `styles_login.xml` to the `main` source set,
  - Define a new `LoginTheme` style within the `styles_login.xml` file, which will have a parent of `Theme.LoginFlow`,
  - Override the `colorPrimary`, `colorPrimarySurface`, `colorPrimaryVariant`, `colorSecondary` and `colorSecondaryVariant` properties for this new style, just like we did for the `Base.Wordpress` style,
  - Replace the `Theme.LoginFlow` with the `LoginTheme` style in the `AndroidManifest.xml (see `LoginEpilogueActivity`, `SignupEpilogueActivity` and `PostSignupInterstitialActivity`),
  - Define an empty new `LoginTheme.TransparentStatusBar` style within the `styles_login.xml` file, which will have a parent of `LoginTheme`,
  - Add a new `styles_login.xml` to the `main` source set for `values-v23`,
  - Define a non empty new `LoginTheme.TransparentStatusBar` style within that `styles_login.xml` file, which will have a parent of `LoginTheme`,
  - Override the `android:statusBarColor` property for this new style (with `@android:color/transparent`),
  - Replace the `Theme.LoginFlow.TransparentStatusBar` with the `LoginThemeTransparentStatusBar` style in the `AndroidManifest.xml` (see `LoginActivity`),

Once more this is what the `Woo` team is doing, with the exception that they don't have the transparent related style, which makes our configuration a bit more complex due to `values-v23`.

In the end the structure of `res` for the `jetpack` source set will become as simple as the below screenshot: 

image

This actually now makes much more sense because the `jetpack` source set will not deal atm with anything but overriding the app name (see `strings.xml`) and base colors (see `colors_base.xml`).

😃 lots I wrote, I know, but I am here if you need help or clarification on any of those. 🙏 

PS: The `styles_login.xml` file name and convention aligns with what the `Woo` team has but defers to the `WordPress` one, because we are using it the other way around, having the `styles` in the suffix instead as a prefix, see:
- `jetpack_styles.xml`,
- `reader_styles.xml`,
- `scan_styles.xml` and
- `stats_styles.xml`
I actually suggest we follow the `Woo` naming convention on that because this way all style related files will be grouped together. Currently it is a bit difficult to gather all the styles within the `values` res folder since they are not grouped.

**Comment by zwarm** [comment]
@ParaskP7 - All the suggested changes have been incorporated. Dark and light themes seem to be working correctly. I did not go through every single view in the app, so there may be a few that I missed, but overall it's looking good. Thanks

**Review by ParaskP7 — CHANGES_REQUESTED** [review]
👋 @zwarm !

> @ParaskP7 - All the suggested changes have been incorporated. Dark and light themes seem to be working correctly. I did not go through every single view in the app, so there may be a few that I missed, but overall it's looking good. Thanks

I have reviewed the changes you made, many thanks! 🙏 

I noticed that some of the requested changes as still pending or incomplete, I am going to list those below:
1) The `themes.xml` files, within the `jetpack` source set, for both, the `values-v23` and `values-27` res folders, need to be deleted as well. As such, the now empty `values-v23` and `values-27` folders need to be deleted as well.
2) The `colors.xml` file, within the `jetpack` source set, for `values-night`, need to be renamed to `colors_base.xml` as well.
3) For the newly added `styles_login.xml` file, the `<item name="colorPrimarySurface">@color/colorPrimaryVariant</item>` item needs to be added for the `LoginTheme` style.
4) For the newly added `styles_login.xml` file, for the `values` res folder, the `<item name="android:statusBarColor">@android:color/transparent</item>` needs to be deleted for the `LoginTheme.TransparentStatusBar` style. It should only be available for `values-v23` res folder.

When the above is done we can merge this PR! 🥳

**Comment by zwarm** [comment]
All taken care of in 45e5d00
Thanks @ParaskP7. :)

Next time we switch directions, we may want to consider splitting into a two PRs ...to separate original direction from new direction.

**Review by ParaskP7 — APPROVED** [review]

**Pull request merged**
