### PR TITLE
Fixes Loading Private Image in Comments

### PR DESCRIPTION
**Pull request by roundhill**
It was driving me a little crazy when private blog images wouldn't load in the reader comments. The issue was that the photon wrapper url isn't able to access private images.

Turns out we can just provide the photon query arguments at the end of the url if it's on wordpress.com and it will be processed just like a photon-wrapped image which solves the problem.

### CODE REVIEW

**Comment by nbradbury** [comment]
Rather than fix this just for images in comments, we should be able to fix similar problems elsewhere in the app by updating `PhotonUtils.getImageUrl()` to special case wordpress.com urls.

I'm thinking we can add this code [here](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java#L90):

```
// use wordpress.com as the host if image is on wordpress.com since it supports the same
// query params and, more importantly, can handle images in private blogs
if (imageUrl.contains("wordpress.com")) {
    return imageUrl + query;
}
```

**Comment by roundhill** [comment]
Cool! Go ahead and commit that.

**Comment by roundhill** [comment]
All set @nbradbury, thanks for the more elegant solution.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
