### PR TITLE
Fix #2445 - NPE in MediaBrowserActivity broadcast receiver

### LINKED ISSUE #2445: Crash report 3.9-rc-1: NPE in MediaBrowserActivity
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.wordpress.android.ui.media.MediaBrowserActivity$1@424ab198
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.ui.media.MediaBrowserActivity$1.onReceive(MediaBrowserActivity.java:80)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #2445

### CODE REVIEW

**Comment by fadils** [comment]
I'm just wondering if it would be better to squash the commits? Or it's more preferred this way?

**Comment by tonyr59h** [comment]
I prefer having non-functional-changing commits separate so it's easier to filter logical differences. Definitely open for discussion though.

**Comment by fadils** [comment]
IMHO, I just find it's better to have a [rather concise history](http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests) in the repo..

**Comment by tonyr59h** [comment]
Makes sense, especially with a repository as large and active as this one. I'll rebase.

**Pull request closed without merging**
