### PR TITLE
Illegal state exception on SignIn with MagicLink

### LINKED ISSUE #4894: Crash report 6.2: ISE in SignInActivity.onMagicLinkRequestSuccess
```
Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1560)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
       at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:667)
       at org.wordpress.android.ui.accounts.SignInActivity.slideInFragment(SignInActivity.java:227)
       at org.wordpress.android.ui.accounts.SignInActivity.slideInFragment(SignInActivity.java:216)
       at org.wordpress.android.ui.accounts.SignInActivity.onMagicLinkRequestSuccess(SignInActivity.java:280)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:931)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:925)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #4894 by checking that the fragment is still attached to the activity.

@will Would you mind to check this one?

### CODE REVIEW

**Comment by will** [comment]
It's been nearly a decade since I've done any java and also I'm on my phone
so it's tough to reason through the implications of exiting out early like
that, but I trust you and this seems like a great patch. Ship it!

**Comment by daniloercoli** [comment]
cc  @kwonye ;)

**Comment by kwonye** [comment]
Thanks so much for doing this, @daniloercoli 🙇

**Comment by kwonye** [comment]
@daniloercoli can you recreate a new PR against `release/6.3` please? Changing the base branch here doesn't work (adds all the other commits since branch off)

Feel free to merge once the PR is committed :shipit:

**Pull request closed without merging**
