### PR TITLE
Add remote feature flag for domain management

### LINKED ISSUE #19193: 🤖 Remote Feature Flag
Flag Key: "domain_management"

### PR DESCRIPTION
**Pull request by mkevins**
Fixes #19193

### Description

This PR adds support for the domain management remote feature flag.

To test:

This PR can be tested together with the UI in [the dependent PR for the Domains button](https://github.com/wordpress-mobile/WordPress-Android/pull/19268):

#### Flag enabled

1. Sandbox the emulator (or physical device), with the remote flag set to `true`
2. Navigate to the "Me" screen
3. Observe that the "Domains" button is shown

#### Flag disabled

1. Follow steps 1 and 2 from above, but with the remote flag set to `false`
2. Leave the "Me" screen and return to it
   * Note: this step may need to be repeated to ensure the flag value is fetched before the screen loads
3. Observe that the "Domains" button is absent

## Regression Notes
1. Potential unintended areas of impact
N/A

5. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

6. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

**Comment by justtwago** [comment]
I'm facing a problem with modifying the `domain_management` feature flag from the client side.



I do see the new `domain_management` flag but it's _not_ remote. When I'm checking the checkbox and leaving the screen or restarting the app, the value's not being saved so I cannot reach the "Domains" button.

Please, let me know if I need to manage the feature flag in another way.

PS, I use the sandbox that is up to date.

**Comment by justtwago** [comment]
According to pc8HXX-1gR-p2, along with `Me > Domains` path, there should be an alternative `My Site > Menu > Domains > Manage all Domains`. I don't see a separate task for it, so just wanted to double-check wthether it should be included in this PR too.

**Review by justtwago — APPROVED** [review]
After putting the FF to my sandbox FF config file, it works perfectly. Thank you!

**Comment by mkevins** [comment]
Thank you for testing and reviewing this Artyom!

**Pull request merged**
