### PR TITLE
Jetpack Focus: Emphasize uninstalling the app in the migration success card

### LINKED ISSUE #18262: Jetpack Focus: Update migration success UI
## Description

Update the wording on the migration success card to make clear to users they should uninstall the app instead of deleting their site.

Slack ref: p1681290711175429-slack-C0180B5PRJ4
Design ref: qk5s4q4mZsXknwhMWo2vIY-fi-10230_21914

```[tasklist]
## Todo
- [x] Update strings on the final step of the migration
- [x] Update strings and appearance on the dashboard card
- [x] Update strings on the migration popover
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #18262

## Description
Updates the migration success card design to make clear to users they should **uninstall the WordPress app** (not delete their site)

Design ref: qk5s4q4mZsXknwhMWo2vIY-fi-10230_21914
Matching iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/20515

## To test

1. Delete the Jetpack app
2. Install the WordPress app if not installed already
3. Login in the WordPress app if not already
4. Build and run the Jetpack app
5. Follow the migration flow
6. *Verify* that the migration success card should match the new designs - please test light vs dark mode, landscape vs portrait, min / max font sizes
7. Tap on the migration success card
8. *Verify* that the overlay should match the new designs  - please test light vs dark mode, landscape vs portrait, min / max font sizes (note: we've decided to use ["on your device" instead of "on your iPhone"](p1681296746617889/1681290711.175429-slack-C0180B5PRJ4)) 

|Before | After (light mode) | After (dark mode)|
|---|---|---|
|Screenshot_20230413_200404|Screenshot_20230413_200504|Screenshot_20230413_200532|
|Screenshot_20230413_200417|Screenshot_20230413_200515|Screenshot_20230413_200541|

|Final migration step|After RTL (light mode)|After RTL (dark mode)|
|---|---|---|
|Screenshot_20230413_204115|Screenshot_20230413_202342|Screenshot_20230413_202327|

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
Having trouble recreating this state on alpha builds, the WordPress APK sends me to the play store. But based on the screenshots, everything looks as expected 👍

**Review by ovitrif — APPROVED** [review]
LGTM :shipit: 

Thanks @antonis for wrangling this 🙇‍♂️

---

## Test Results

### Migration

| 🟢 Light | 🟢 Dark | 🟢 Rtl |
| - | - | - |
| 1l | 1d | 1lr |

### Home

| 🟢 Light | 🟢 Dark | 🟢 Rtl | 🟢 Max | 🟢 Min |
| - | - | - | - | - |
| 2l | 2d | 2lr | 2lr+ | 2lr- |

**Comment by ovitrif** [comment]
Merging to `release/22/2` as agreed (internal ref: p1681750685411839/1681750332.643279-slack-CC7L49W13)

**Comment by antonis** [comment]
Thank you for your feedback @ovitrif and @osullivanchris 🙇 
I'll proceed with [merging to 22.2 as discussed](https://github.com/wordpress-mobile/WordPress-Android/pull/18271#issuecomment-1511753429) after the tests pass.

ps. Thank you for suggesting https://github.com/alexjlockwood/avocado @ovitrif 🙇

**Comment by antonis** [comment]
I've added a new separate RTL resource since the simple mirroring reverted the icon.

|LTR light mode|RTL dark mode|
|---|---|
|Screenshot_20230418_135439|Screenshot_20230418_135412|

**Pull request merged**
