### PR TITLE
Release/16.4

### PR DESCRIPTION
**Pull request by loremattei**
Merge `release/16.4` into `trunk`

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]

**Comment by AliSoftware** [comment]
@oguzkocer Probably not a big deal, but process-wise shouldn't we merge the PR to trunk only _after_ the release went live on Monday? 🤷

**Comment by oguzkocer** [comment]
@AliSoftware That's correct, I just blanked out as we used to do the release PRs on the same day they are released. If we want to follow that process, we should probably keep the PR as a draft until the release goes live.

Having said that, we really don't use `trunk` for anything anymore and as far as I know we are just using it for consistency across repos. The important thing should be the tags/releases, so there is some argument to be made for just merging the PR when it's ready just so it's out of the way. 🤷

**Comment by AliSoftware** [comment]
Totally, that's why I think that's not that big a deal that it was merged already 👍

It might be more problematic for iOS repos where the build could be rejected by Apple and we shouldn't merge to trunk in those cases (That's why I do my trunk release PRs as draft for WCiOS);
For Android it should be ok… though that might change if we start to use PlayStore's "Managed Publishing" in the future 🤔

**Comment by mokagio** [comment]
FWIW I like "keep trunk release PRs drafts till it's confirmed we shipped that code" idea 👍

**Pull request merged**
