### PR TITLE
Site Creation: Site Preview UI

### LINKED ISSUE #8505: [Site Creation] Step: Site Preview - UI
Modify/Create UI for Site Preview step in the Site Creation flow.

- Handle loading of webview and block taps but allow scrolling
- Not tied to anything
- No fragment transition

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #8505. This PR adds the UI for the site creation preview screen. It uses a mocked url which will be tied to the VM once we introduce it. If I haven't missed anything, it should be the exact replica of what @SylvesterWilmott has designed. Here is a screenshot from the emulator:

screenshot_1542928702

To test:
* The `NEW_SITE_CREATION_ENABLED` flag needs to be enabled in `WordPress/build.gradle`.
* Since the fragment is not added to the flow yet, it'll need to be done to be able to test. One easy way to do that would be to change the `showFragment` in `NewSiteCreationActivity.onCreate()` to instead show the newly added fragment. Once that's done, you can go to the site selection screen, tap on the `+` icon and select "Create WordPress.com site" to see it.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @oguzkocer. It looks really good overall, I have noticed just one issue. 

- The links are still clickable - it might be confusing for users as they may expect something is loading even though we've consumed the action
- I'd suggest adding a bottom padding to the CardView and draw it "behind" the `sitePreviewOkButtonContainer` so the rounded corner is not visible. Wdyt?

site_preview


Note for @SylvesterWilmott -> the landscape mode isn't great. We may want to consider providing a slightly different layout. Wdyt?
device-2018-11-23-130416

**Comment by SylvesterWilmott** [comment]
Looks awesome @oguzkocer !

- As @malinajirka said above, let's get rid of the rounded corners at the bottom of the preview. It would definitely help here to place the preview below the button if we ever decide to use a `back` or `bounce` easing curve when we present it.

- What is the elevation of the button area? Maybe we can try 1 up from the current.

- Thanks for pointing out the landscape mode issue @malinajirka . I will add a landscape version to Zeplin

- Can you show a screenshot on tablet size please.

**Comment by oguzkocer** [comment]
> The links are still clickable - it might be confusing for users as they may expect something is loading even though we've consumed/discarded the action

I forgot to add this to the PR description sorry about that @malinajirka. We chatted about this with @kwonye when I was implementing it and we basically said that the workaround to block the links (adding an overlay and propagating scroll, unless you have a different idea) is not worth to add at least in the initial iteration. I have also thought that maybe there is a better way to handle the issue instead of just blocking the links completely, such as showing a toast that this is just a preview or asking to open your site in the browser etc. Long story short, we are not handling this in this PR and can discuss it in a later grooming chat.

> As @malinajirka said above, let's get rid of the rounded corners at the bottom of the preview. It would definitely help here to place the preview below the button if we ever decide to use a back or bounce easing curve when we present it.

@SylvesterWilmott I don't think I fully understood the second sentence, but the rounded corner issue should be fixed. Here is the updated screenshot: https://cloudup.com/cR-jdTH5EGH

> What is the elevation of the button area? Maybe we can try 1 up from the current.

It was `4dp`, I updated it to `6dp` in the screenshot I linked above. If it still feels off (it kind of feels that way to me), it maybe because the elevation is not the problem and there is something else going on, let me know and I'll look into it.

> Thanks for pointing out the landscape mode issue @malinajirka . I will add a landscape version to Zeplin

@malinajirka It's not yet added to Zeplin unless I am mistaken. Let's separate that to its own PR. We'll add an issue for it when it's ready and I'll take care of it.

> Can you show a screenshot on tablet size please.

Of course, will add it to the PRs from now on for design review. Here it is: https://cloudup.com/cCW9ZByhwmp

**Comment by malinajirka** [comment]
>I forgot to add this to the PR description sorry about that @malinajirka. We chatted about this with @kwonye when I was implementing it and we basically said that the workaround to block the links (adding an overlay and propagating scroll, unless you have a different idea) is not worth to add at least in the initial iteration. I have also thought that maybe there is a better way to handle the issue instead of just blocking the links completely, such as showing a toast that this is just a preview or asking to open your site in the browser etc. Long story short, we are not handling this in this PR and can discuss it in a later grooming chat.

No worries. I like the idea of showing a toast or similar:). 

>@malinajirka It's not yet added to Zeplin unless I am mistaken. Let's separate that to its own PR. We'll add an issue for it when it's ready and I'll take care of it.

I completely agree. (I wanted to indicate we shouldn't handle it in this PR by writting "Note for Sylvester".)



LGTM Thanks @oguzkocer - I think we can merge it as soon as the design review is done:).

**Comment by SylvesterWilmott** [comment]
Thanks @oguzkocer 

>maybe because the elevation is not the problem and there is something else going on, let me know and I'll look into it.

I think it's because the shadow of elevated objects are moved down along the Y axis so there's not much shadow on top. I think it's good.

For the tablet view, can we apply a max-width of 512dp to both the preview and the button?

**Comment by SylvesterWilmott** [comment]
Thanks @oguzkocer 

>it maybe because the elevation is not the problem and there is something else going on

It's because elevation adds shadow thats offset positively on the Y axis so we don't get to see a lot of the shadow above. For me it's good!

For the tablet layout, we will want to apply a max-width to both the preview and the button, I'll add this to zeplin as well as the phone landscape asap.

**Comment by oguzkocer** [comment]
Thanks both for the reviews!

> For the tablet layout, we will want to apply a max-width to both the preview and the button, I'll add this to zeplin as well as the phone landscape asap.

@SylvesterWilmott Sounds good!

**Pull request merged**
