### PR TITLE
Merge hotfix `release/20.6.1` into current `release/20.7`

### PR DESCRIPTION
**Pull request by AliSoftware**
Merging `release/20.6.1` back into `release/20.7` after doing a hotfix.

The hotfix contained the following fixes:
 * https://github.com/wordpress-mobile/WordPress-Android/pull/17123
 * https://github.com/wordpress-mobile/WordPress-Android/pull/17124

> **Warning**: A Play Store bug is currently preventing us from submitting the hotfix. [internal ref: pbArwn-5g8-p2]
>
> Since this bug is likely on Google Play Store's side, we don't expect any new commits to be needed on `release/20.6.1` to fix it (we'll just resubmit as soon as Google fixed it on their end), **so this PR should be good to be reviewed and merged once the conflicts are resolved**, _even if_ the hotfix's `.aab` couldn't be submitted to Play Store yet. And merging it sooner than later would unblock us from preparing the `20.7-rc-2` beta ASAP to be ready when it finally becomes possible to upload `.aab` on Play Store Console again.

TODO:
 - [x] Submit `20.6.1` for review (once Play Store bug solved)
 - [x] Fix conflicts on this PR (see below; waiting for @ovitrif to chime in on the `MeFragment.kt` conflict) then undraft this PR
 - [ ] Once this PR is merged, we will also need to do a new beta, and bump its `versionCode` manually (see below)

### `MeFragment.kt`
```
<<<<<<< merge/20.6.1-into-20.7
            jetpackBadge.root.isVisible = true
            if (jetpackBrandingUtils.shouldShowJetpackPoweredBottomSheet()) {
                jetpackBadge.footerJetpackBadge.jetpackPoweredBadge.setOnClickListener {
                    jetpackBrandingUtils.trackBadgeTapped(ME)
                    viewModel.showJetpackPoweredBottomSheet()
                }
=======
            jetpackBadge.isVisible = true
            jetpackBadge.setOnClickListener {
                jetpackBrandingUtils.trackBadgeTapped(ME)
                viewModel.showJetpackPoweredBottomSheet()
>>>>>>> release/20.7
```
cc @ovitrif for confirming which resolution to pick for this conflict

### `build.gradle`

```
<<<<<<< merge/20.6.1-into-20.7
    wordPressLoginVersion = '0.18.0'
    gutenbergMobileVersion = 'v1.81.2'
=======
    wordPressLoginVersion = '0.19.0'
    gutenbergMobileVersion = 'v1.82.0'
>>>>>>> release/20.7
```
We should pick the lines from `release/20.7`, but cc @geriux to double-check that a `v1.82.1` is in the works to include the bug fix (that landed in `1.81.2`), and that `v1.82.1` will be shipped in a future beta of WP/JP Android

### `version.properties`

```
<<<<<<< merge/20.6.1-into-20.7
versionName=20.6.1
versionCode=1268
=======
versionName=20.7-rc-1
versionCode=1267
>>>>>>> release/20.7
```
We will pick the values from `release/20.7` for now, but will have to manually bump `versionCode` to `1269` (instead of the `1268` that our tooling will bump from seeing `1267` in `trunk`) when we'll do the new beta once this PR lands.
(There's no point in choosing `versionCode=1268` or `versionCode=1269` in advance while resolving this conflict, because our tooling we update it based on what's in `trunk` when we'll run `fastlane new_beta_release`…)

---

```mermaid
%%{ init: {
    "gitGraph": { "mainBranchName": "trunk" }
}}%%
gitGraph
       commit id:"20.6 code freeze"
       branch release_20.6
       commit id:"beta fixes…"
       commit id:"finalize_release" tag:"20.6"
       branch release_20.6.1 order:4
       checkout trunk
       commit id:"features…"
       merge release_20.6
       commit id:" "
       branch release_20.7
       checkout release_20.7
       commit id:"code_freeze"
       commit id:"(not published)" tag:"20.7-rc-1" type: REVERSE
       checkout release_20.6.1
       commit id:"fix: #17123"
       commit id:"fix: #17124" tag:"20.6.1 (todo)"
       branch merge_20.6.1-into-20.7
       checkout merge_20.6.1-into-20.7
       commit id:"fix conflict" type: HIGHLIGHT
       checkout release_20.7
       merge merge_20.6.1-into-20.7
       commit id:"(TODO: new beta)" tag:"20.7-rc-2" type: REVERSE
```

### CODE REVIEW

**Comment by geriux** [comment]
> cc @geriux to double-check that a v1.82.1 is in the works to include the bug fix (that landed in 1.81.2), and that v1.82.1 will be shipped in a future beta of WP/JP Android

Thanks for the ping, yes a `1.82.1` beta is [in the works](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5140) to include this fix as well. 🙇

**Comment by ovitrif** [comment]
> ### `MeFragment.kt`
> ```
> <<<<<<< merge/20.6.1-into-20.7
>             jetpackBadge.root.isVisible = true
>             if (jetpackBrandingUtils.shouldShowJetpackPoweredBottomSheet()) {
>                 jetpackBadge.footerJetpackBadge.jetpackPoweredBadge.setOnClickListener {
>                     jetpackBrandingUtils.trackBadgeTapped(ME)
>                     viewModel.showJetpackPoweredBottomSheet()
>                 }
> =======
>             jetpackBadge.isVisible = true
>             jetpackBadge.setOnClickListener {
>                 jetpackBrandingUtils.trackBadgeTapped(ME)
>                 viewModel.showJetpackPoweredBottomSheet()
> >>>>>>> release/20.7
> ```
> 
> cc @ovitrif for confirming which resolution to pick for this conflict

@AliSoftware It's unclear to me why we have `jetpackBadge.root.isVisible = true` vs `jetpackBadge.isVisible = true`.

If I look at the [changelog of the hotfix PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17124/files#diff-44a7887783e952cfbdec7d4b88ffe9c41307ca9401a43ae6ab27817c90502d6bR132-R136) the changeset is different and some updates are already in. Initially for that PR I created a branch on top of [`release/20.6.1`](https://github.com/wordpress-mobile/WordPress-Android/tree/release/20.6.1) before committing changes for the hotfix.

Aside from the unclear thingie, we should pick the first version, i.e. the one with the `if (jetpackBrandingUtils.shouldShowJetpackPoweredBottomSheet()` condition.

I'll investigate this further on a local merge attempt 👍 .

**Comment by ovitrif** [comment]
> > ### `MeFragment.kt`
> > ```
> > <<<<<<< merge/20.6.1-into-20.7
> >             jetpackBadge.root.isVisible = true
> >             if (jetpackBrandingUtils.shouldShowJetpackPoweredBottomSheet()) {
> >                 jetpackBadge.footerJetpackBadge.jetpackPoweredBadge.setOnClickListener {
> >                     jetpackBrandingUtils.trackBadgeTapped(ME)
> >                     viewModel.showJetpackPoweredBottomSheet()
> >                 }
> > =======
> >             jetpackBadge.isVisible = true
> >             jetpackBadge.setOnClickListener {
> >                 jetpackBrandingUtils.trackBadgeTapped(ME)
> >                 viewModel.showJetpackPoweredBottomSheet()
> > >>>>>>> release/20.7
> > ```
> I'll investigate this further on a local merge attempt 👍 .

There was a change that updated the same code in this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/17095

This change is part of `release/20.7` and it wasn't yet in `release/20.6.1` on top of which I created the branch for the [hotfix](https://github.com/wordpress-mobile/WordPress-Android/pull/17124).

Practically, this means none of the two options are correct because the code binding to the badge is different on `20.7` → therefore a "manual merge" is required to update the code to fix the references.

the final code of the enclosing `if` condition should be:
```kt
if (jetpackBrandingUtils.shouldShowJetpackBranding()) {
    jetpackBadge.isVisible = true
    if (jetpackBrandingUtils.shouldShowJetpackPoweredBottomSheet()) {
        jetpackBadge.setOnClickListener {
            jetpackBrandingUtils.trackBadgeTapped(ME)
            viewModel.showJetpackPoweredBottomSheet()
        }
    }
}
```

I'm not sure how we acting in such situations though. This code will only build when `merge/20.6.1-into-20.7` is merged into `release/20.7`.

I've collected all changes in a merge example branch: [`merge/20.6.1-into-20.7-me-fragment-conflict-fix`](https://github.com/wordpress-mobile/WordPress-Android/compare/merge/20.6.1-into-20.7...merge/20.6.1-into-20.7-me-fragment-conflict-fix).
This one should build.

**Comment by AliSoftware** [comment]
Thanks @ovitrif for checking the conflict and @spencertransier for merging the branch to solve it and mark PR ready.

I'm surprised though that the diff from https://github.com/wordpress-mobile/WordPress-Android/pull/17136/commits/0b40faee0b7037ce54ad8b3c19cc7f07bee08327 (merge conflict resolution from @spencertransier ) does not contain all the same things as the comparison of the branch that @ovitrif created in https://github.com/wordpress-mobile/WordPress-Android/compare/merge/20.6.1-into-20.7...merge/20.6.1-into-20.7-me-fragment-conflict-fix — which also contains some changes in XML files as well in its diff.

I'm not sure if it's just a GitHub glitch in what diff it's actually showing me in each case (and what branches they compare) and just because I'm looking at this from my phone and not digging too much in details so maybe it's just a red herring in practice… or if that's a genuine thing that got missed during the conflict resolution.

My gut feeling would say it's the former (ie red herring and all is ok) — also because @ovitrif only mentioned `MeFragment.kt` in his comment above but not the XML files I see in his branch's diff — and all is good; but just in case it's the latter and to be on the safe side, it would be nice to get a final approval from @ovitrif that the conflict resolution that landed in 0b40faee0b7037ce54ad8b3c19cc7f07bee08327 didn't miss anything 😅

**Comment by AliSoftware** [comment]
Update: Thinking about it a bit more I think the layout and dimens XML I see in @ovitrif 's link are because it's comparing against the merge branch, while those xml changes are already in the release/20.7 branch so it's normal they don't appear in Spencer commits… strengthening my belief that my comment above is a red herring and result is all ok and as expected after all…?

**Review by antonis — APPROVED** [review]
Thank you for wrangling this @AliSoftware 🙇 
I've tested the generated builds and the apps behave as expected. The code changes also look consistent to me and include all the changes from https://github.com/wordpress-mobile/WordPress-Android/pull/17124 🎉 
Note that the [Gutenberg version upgrade](https://github.com/wordpress-mobile/WordPress-Android/pull/17123) is not included in this PR but [this should be ok according to this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/17136#issuecomment-1238280267).

**Comment by mokagio** [comment]
Merging after @antonis' approval, despite the bit of back and forth on whether the diff is correct. From reading the conversation, I get the feeling that the diff is indeed correct. 

All in all, I think it's a safer bet to merge and unblock shipping a new build, rather than waiting any longer for additional confirmation, particularly because we haven't shipped a 20.7 beta yet and we're getting close to half-way through its code freeze cycle.

**Comment by ovitrif** [comment]
> Update: Thinking about it a bit more I think the layout and dimens XML I see in @ovitrif 's link are because it's comparing against the merge branch, while those xml changes are already in the release/20.7 branch so it's normal they don't appear in Spencer commits… strengthening my belief that my comment above is a red herring and result is all ok and as expected after all…?

 That's true, my example branch was trying to make a buildable intermediate "version" of '20.6.1' that includes the code changes that led to the initial merge conflict; but in reality only the change from MeFragment was needed 👍, everything else was already there in 20.7 release branch.

**Pull request merged**
