### PR TITLE
Notifications Refresh (Phase 1)

### PR DESCRIPTION
**Pull request by antonis**
### List UI
- https://github.com/wordpress-mobile/WordPress-Android/issues/20022
- https://github.com/wordpress-mobile/WordPress-Android/issues/20023
- https://github.com/wordpress-mobile/WordPress-Android/issues/20021
- https://github.com/wordpress-mobile/WordPress-Android/issues/20020
- https://github.com/wordpress-mobile/WordPress-Android/issues/20039
### Inline Actions
- https://github.com/wordpress-mobile/WordPress-Android/issues/20024
- ~~https://github.com/wordpress-mobile/WordPress-Android/issues/20025~~
- https://github.com/wordpress-mobile/WordPress-Android/issues/20040
### Navigation bar
- https://github.com/wordpress-mobile/WordPress-Android/issues/20066
- https://github.com/wordpress-mobile/WordPress-Android/issues/20065
### Details View
- https://github.com/wordpress-mobile/WordPress-Android/issues/20096
### Push notifications
- https://github.com/wordpress-mobile/WordPress-Android/issues/20099
### Other
- https://github.com/wordpress-mobile/WordPress-Android/issues/20101

-----

## To Test:

Use the test instructions of each PR to test the feature as a whole.
Also check
- Test List UI changes: pdcxQM-39Z-p2
- Navigation Bar and Inline Changes: pdcxQM-3a7-p2

-----

## Regression Notes

1. Potential unintended areas of impact

    - Notifications tab and push notifacations

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - `NotificationsListViewModelTest`, `NotificationHelperTest`

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          11 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>EnabledActions</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>NoteTimeGroup</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Notification</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>PostLike</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>NoteType</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>LinearLayoutManagerWrapper</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>InlineActionEvent</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>SharePostButtonTapped</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Filter</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jarvislin — APPROVED** [review]
I only encountered #20308 during my manual test.
Other features are working as expected.

**Comment by antonis** [comment]
> I only encountered https://github.com/wordpress-mobile/WordPress-Android/issues/20308 during my manual test.

Thank you for testing and the fix @jarvislin 🙇 
I'll proceed with merging as soon as the CI checks complete 🚀

**Review by mkevins — APPROVED** [review]
Tested this again, with the latest fix, and I did not observe any regressions. LGTM! :shipit:

**Pull request merged**
