### PR TITLE
Update stories - removal of deprecated kotlin-android-extensions

### PR DESCRIPTION
**Pull request by malinajirka**
This PR updates stories library to the current `stories/develop`. The changes in the stories library have already been tested. The changes are related to the replacement of kotlin synthetic accessors with view bindings and removal of deprecated `kotlin-android-extensions`.

To test:
Smoke test stories

cc @oguzkocer When this PR gets merged, it should hopefully unblock your effort to update AGP.

## Regression Notes
1. Potential unintended areas of impact
Stories

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I've tried adding images from various sources, adding texts, changing rotation/color/etc and publishing a story.

3. What automated tests I added (or what prevented me from doing so)
The changes touch just the UI layer so unit tests can't be added.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by aforcier** [comment]
Haven't tested the build yet, but I noticed the lint errors in the failing task were from the stories lib. Should be addressed in this PR: https://github.com/Automattic/stories-android/pull/706

**Review by aforcier — APPROVED** [review]
Switched to the branch from https://github.com/Automattic/stories-android/pull/706, and:

✅ `lintWordpressVanillaRelease` is green
✅ Smoke tested stories, everything continues to work smoothly

:shipit: (assuming https://github.com/Automattic/stories-android/pull/706 is merged and this PR is updated to `stories-android` `develop` after that)

**Review by zwarm — APPROVED** [review]
@malinajirka - I focused my testing on the build: added new stories, updated stories, text placement, size, color, single images, multiple images, previewing, sharing. Everything is working as expected. 👍

**Comment by malinajirka** [comment]
Awesome thank you both! 🙇

**Comment by malinajirka** [comment]
cc @oguzkocer it seems all usages of `kotlin-android-extensions` have been removed ;).

**Pull request merged**
