### PR TITLE
Fix #213. Update counter after media deletion/addition

### LINKED ISSUE #213: Media: Deleting an item does not update the counters.
Go to the media feature.
Notice the number of items currently in the list.
Tap an item to view its detail.
Tap to view the action bar menu and choose the delete option. 
You're back on the main list, the item is removed, but the count did not update. 

2.5 beta 4
Nexus 4 / 4.3

### PR DESCRIPTION
**Pull request by fadils**
Simply update the counter whenever MediaGridFragment is visible after a backstack change.

### CODE REVIEW

**Comment by tonyr59h** [comment]
Looks good :+1:

I noticed the same issue occurs when you add an image. I think this solution would fix that as well, maybe around [here](https://github.com/fadils/WordPress-Android/blob/fix-213/WordPress/src/main/java/org/wordpress/android/ui/media/MediaAddFragment.java#L118).

**Comment by fadils** [comment]
Really? On my end, adding a media without connection still updates the counter.
How do you produce the issue?

**Comment by tonyr59h** [comment]
[Here's](https://cldup.com/G92fvhIRiz.mp4) a video of the reproduction without an internet connection. It will also reproduce with a connection,

**Comment by fadils** [comment]
It turns out that my app's HEAD is already with this fix.
Yes, confirmed even with media addition the counter is updated.
Let me amend the commit message to a rather appropriate one.

**Comment by tonyr59h** [comment]
:shipit:

**Pull request merged**
