### PR TITLE
Populate the "Email" field instead of the "Your Name" in Helpshift

### LINKED ISSUE #6892: Populate the "Email" field instead of the "Your Name" in Helpshift
### Expected behavior
App populates the "Email (optional)" field in Helpshift when using the "Help" toolbar action in the Login email screen.

### Actual behavior
App populates the "Your Name" field with the email.

### Steps to reproduce the behavior
* With the app data cleaned, launch the app and hit "LOG IN"
* Put in some email address and hit the "HELP" button on the toolbar
* On the Helpshift dialog that comes up, notice that the email populates the middle field that is devoted to the user's name. See attached screenshot too.

screenshot-1511274813488

##### Tested on [device], Android [version]
Nexus 5X, Android 7.1.1

### PR DESCRIPTION
**Pull request by jorgecasariego**
Fixes #6892 

**To test:**
1. With the app data cleaned, launch the app and hit "LOG IN"
2. Put in some email address and hit the "HELP" button on the toolbar
3. On the Helpshift dialog that comes up, notice that the email populates the email field and for the name field is split the email address to pre-fill name

<div class="row">

</div>

### CODE REVIEW

**Comment by AmandaRiu** [comment]
Code changes look solid. Tested on emulators running 16, 19, 22, and 27. All good. The only part I'm not sure of is this line: https://github.com/jorgecasariego/WordPress-Android/blob/d2fe7113fadcff2331e022733b30fab95c2d15ef/WordPress/src/main/java/org/wordpress/android/util/HelpshiftHelper.java#L358

```
if (TextUtils.isEmpty(emailAddress)) {
       emailAddress = UserEmailUtils.getPrimaryEmail(context);
}
```
This helper attempts to query the android `AccountManager` for a user account and parse an email from the result. This doesn't work in my test environment and I could not find any references to the use of `AccountManager` in this repo. I also don't see it being used in the login process, but I may be missing something. 

@maxme or @oguzkocer : WDYT of this 👆

**Comment by jorgecasariego** [comment]
You're right @AmandaRiu 

There isn't other reference to the use of **AccountManager** throughout the project but as it was already implemented and it worked then I left it

**Comment by oguzkocer** [comment]
@AmandaRiu It looks like we were making that call previously as well, so I don't think it's anything we should be worried about. Even if it's, it'd be outside the scope of this PR, since the PR only improves on it.

**Comment by AmandaRiu** [comment]
Fix approved. merging.

**Comment by jorgecasariego** [comment]
Thanks @AmandaRiu

**Pull request merged**
