### PR TITLE
Merge release/19.8 (19.8-rc-3 + conflict resolution)

### PR DESCRIPTION
**Pull request by AliSoftware**
Merging the release branch after doing a new beta.

The new beta includes:
 * https://github.com/wordpress-mobile/WordPress-Android/pull/16462
 * https://github.com/wordpress-mobile/WordPress-Android/pull/16515
    * https://github.com/wordpress-mobile/gutenberg-mobile/pull/4833
    * https://github.com/wordpress-mobile/WordPress-Android/pull/16485
 * Latest `strings.xml` from GlotPress
 * Version bump in `version.properties`

### 1. `QuickStartRepository.kt:100`
```
<<<<<<< merge/19.8-rc-3
    var currentTab = if (isMySiteTabsEnabled) MySiteTabType.DASHBOARD else MySiteTabType.ALL
    var quickStartTaskOriginTab = if (isMySiteTabsEnabled) MySiteTabType.DASHBOARD else MySiteTabType.ALL
=======
    var quickStartTaskOrigin = if (isMySiteTabsEnabled) MySiteTabType.DASHBOARD else MySiteTabType.ALL
    var quickStartType: QuickStartType = NewSiteQuickStartType
>>>>>>> trunk
```

My gut would suggest to keep:
 * `currentTab` and `quickStartTaskOriginTab` from [PR #16462 to `release/19.8`](https://github.com/wordpress-mobile/WordPress-Android/pull/16462/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eL93-R94)
 * `quickStartType` from [PR #16500 to `trunk`](https://github.com/wordpress-mobile/WordPress-Android/pull/16500/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eR98) + [this one](https://github.com/wordpress-mobile/WordPress-Android/pull/16523/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eR101)
— cc @AjeshRPai @ashiagr 

### 2. `QuickStartRepository.kt:161`
```
<<<<<<< merge/19.8-rc-3
            isSiteMenuStepRequiredForTask(task) -> requestTabStepForTask(task, MySiteTabType.SITE_MENU)
            isHomeStepRequiredForTask(task) -> requestTabStepForTask(task, MySiteTabType.DASHBOARD)
            task == QuickStartTask.UPDATE_SITE_TITLE -> {
=======
            isSiteMenuStepRequiredForTask(task) -> requestSiteMenuStepForTask(task)
            task == QuickStartNewSiteTask.UPDATE_SITE_TITLE -> {
>>>>>>> trunk
```
My gut would suggest to keep:
 * `isSiteMenuStepRequiredForTask` and `isHomeStepRequiredForTask` from [PR #16462 to `release/19.8`](https://github.com/wordpress-mobile/WordPress-Android/pull/16462/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eL147-R149)
 * the `task ==` line from [PR #16500 to `trunk`](https://github.com/wordpress-mobile/WordPress-Android/pull/16500/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eL150-R158)
— cc @AjeshRPai @ashiagr 

### 3. `QuickStartRepository.ky:341`
```
<<<<<<< merge/19.8-rc-3
    private fun isHomeStepRequiredForTask(task: QuickStartTask) =
            quickStartTaskOriginTab == MySiteTabType.DASHBOARD &&
                    currentTab == MySiteTabType.SITE_MENU &&
                    task.isShownInHomeTab()

    // the quick start focus point shown in case of when the default tab is site menu or dashboard varies
    // this function checks whether the passed tasks is shown in site menu
    private fun QuickStartTask.isShownInSiteMenuTab() =
            when (quickStartTaskOriginTab) {
                MySiteTabType.DASHBOARD ->
                    when (this) {
                        QuickStartTask.ENABLE_POST_SHARING,
                        QuickStartTask.EXPLORE_PLANS -> true
                        else -> false
                    }
                MySiteTabType.SITE_MENU ->
                    when (this) {
                        QuickStartTask.CHECK_STATS,
                        QuickStartTask.REVIEW_PAGES,
                        QuickStartTask.EDIT_HOMEPAGE,
                        QuickStartTask.ENABLE_POST_SHARING,
                        QuickStartTask.EXPLORE_PLANS -> true
                        else -> false
                    }
                else -> false
            }

    private fun QuickStartTask.isShownInHomeTab() = when (this) {
        QuickStartTask.CHECK_STATS,
        QuickStartTask.REVIEW_PAGES,
        QuickStartTask.EDIT_HOMEPAGE -> true
=======
    private fun QuickStartTask.showInSiteMenu() = when (this) {
        QuickStartNewSiteTask.ENABLE_POST_SHARING,
        QuickStartNewSiteTask.EXPLORE_PLANS -> true
>>>>>>> trunk
```
My gut would suggest to:
 * Keep the code from [PR #16462 to `release/19.8`](https://github.com/wordpress-mobile/WordPress-Android/pull/16462/files#diff-17423ebb29daca17468db150728f788640bd1f7f45bb0dba62dfc779cce1050eL300-R332)
 * But replace every instance of `QuickStartTask.<ALL_CAPS_NAME>` with `QuickStartNewSiteTask.<ALL_CAPS_NAME>` (based on [PR #16500 to `trunk`](https://github.com/wordpress-mobile/WordPress-Android/pull/16500))
— cc @AjeshRPai @ashiagr

### 4. `MySiteViewControllerTest.kt`

Ok errr… I'll let this resolution to @AjeshRPai @ashiagr  😓 

### 5. `QuickStartRepositoryTest.kt`

```
<<<<<<< merge/19.8-rc-3
    private val dashboardTasks = listOf(
            QuickStartTask.CHECK_STATS,
            QuickStartTask.REVIEW_PAGES,
            QuickStartTask.EDIT_HOMEPAGE
    )

    private val nonSiteMenuTasks = QuickStartTask.values().subtract(siteMenuTasks)
=======
    private val nonSiteMenuTasks = QuickStartTask.getAllTasks().subtract(siteMenuTasks)
>>>>>>> trunk
```
My gut would suggest to:
 - Keep `dashboardTasks` from [PR #16462 to `release/19.8`](https://github.com/wordpress-mobile/WordPress-Android/pull/16462/files#diff-1f6209ff3d9030a59fc0250b0d44a0d1014095acd60d3a4937df276ee254a40c)
 - Keep `nonSiteMenuTasks = QuickStartTask.getAllTasks()` from [PR #16500 to `trunk`](https://github.com/wordpress-mobile/WordPress-Android/pull/16500/files#diff-1f6209ff3d9030a59fc0250b0d44a0d1014095acd60d3a4937df276ee254a40cL72-R75)

### 6. `build.gradle`

Usual Gutenberg version conflict for when we have a betafix:

```
<<<<<<< merge/19.8-rc-3
    gutenbergMobileVersion = 'v1.75.1'
=======
    gutenbergMobileVersion = 'v1.76.0-alpha1'
>>>>>>> trunk
```

The right move should be to keep the `1.76.0-alpha1` from `trunk` since that's what we want to keep in trunk even after this PR lands.
cc @mchowning @geriux to make sure that you'll get whatever fixes landed in the `1.75.1` into the `1.76.0` final before code freeze on Monday.

### CODE REVIEW

**Comment by geriux** [comment]
> cc @mchowning @geriux to make sure that you'll get whatever fixes landed in the 1.75.1 into the 1.76.0 final before code freeze on Monday.

Thanks for the ping! It is already included in `1.76.0` 👍

**Comment by ashiagr** [comment]
👋 @AjeshRPai 

I've resolved merge conflicts. Can you verify that all changes are included from https://github.com/wordpress-mobile/WordPress-Android/pull/16462?

**Review by AjeshRPai — APPROVED** [review]
@AliSoftware  I have checked the changes and made sure that all the changes from the PR - #16462 are included after resolving conflicts. 👍🏼 

@ashiagr Thanks for resolving the conflicts.

**Comment by AliSoftware** [comment]
Thank you both for taking care of this!

**Pull request merged**
