### PR TITLE
[Modules Restructuring] Restructure Image Editor Module

### LINKED ISSUE #16565: Modules Restructuring - Image Editor Module
Parent #16562
Related Repo `N/A`

This issue is about investigating the `image-editor` lib project module and converting it to pure module.

- [x] Investigate module @ParaskP7 
- [x] Convert to pure module @ParaskP7 #16765

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #16562
Fixes #16565

This PR restructures the `image-editor` module removing the extra `ImageEditor` level from it. This effectively makes `image-editor` a pure module, without any extra inner levels or unnecessary build files lying around (like `settings.gradle`, `.gitignore`, etc).

PS.1: @ashiagr I added you as the main reviewer, that is, in addition to the @wordpress-mobile/owl-team team itself, since you helped us with the [navigation component](https://github.com/wordpress-mobile/WordPress-Android/pull/16632) update recently and its testing. As such, this should be very straightforward for you to test again, verify correctness and sign-off on that change for WPAndroid. 🥇 

PS.2: @AliSoftware I added you as a secondary reviewer, that is, in addition to the @wordpress-mobile/owl-team team itself, as I did a [localization.rb](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/90d6bd1643b8dc53183a765297587982635afd81) related change that I want you to double check and verify against, just in case I missed something vital. 🥇 

-----

Question (❓): As per my licensing question on this other related PR of mine [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16744) and since I don't see any `LICENCE` file for this module, like I did for the `analytics` mode, which is pointing to `MIT`, I am not sure if we should include a licence for this module too or exclude the licensing information from the `analytics` and all other modules in general so that we start depending solely on the root level `LICENCE` that WPAndroid is using, which is `GPLv2`, wdyt? 🤔 

-----

To test:
- Build the app and install it on your device or emulator.
- Go to `Posts` -> Click on the plus 🔵 FAB button on the bottom right -> Select `Blog post` to create a new post.
- Search for and add an `Image` block -> Choose an image from either of the options available. -> Use this photo.
- Click the `Media options` cycle button on the top right of this photo -> Select `Edit`.
- Crop this photo and/or do any other editing -> Then click on the ✓ icon on the top right.
- Verify that the photo editing worked and that the photo is updated accordingly.

The above is just one example of how this change can tested so that we could quickly verify the overall correctness of this PR. However, feel free to smoke test other aspects as well, especially if you are aware any or all the other places where `image-editor` is being used.

PS: In addition to the above, you might also want to verify that the `image-editor` testing command works as expect by just copy-pasting this command below and running it locally. This is because I did a Buildkite [pipeline.yml](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) related change as part of this PR as well.

`./gradlew :libs:image-editor:test`

-----

## Regression Notes
1. Potential unintended areas of impact

N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

See `To test` section above.

3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> buildkite/wordpress-android/test-imageeditor Expected — Waiting for status to be reported

I am seeing this check is not completing and I am wondering if [this change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) of mine somehow affected the Buildkite build somehow, maybe [the labelling change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) I did is somehow hardcoded somewhere, I really don't know and a quick search on it didn't help me... Any ideas, should I revert [the labelling part of this change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) back to `ImageEditor`? 🤔

**Review by oguzkocer — APPROVED** [review]
Gradle changes look good to me 👍 

> I am seeing this check is not completing and I am wondering if [this change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) of mine somehow affected the Buildkite build somehow, maybe [the labelling change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) I did is somehow hardcoded somewhere, I really don't know and a quick search on it didn't help me... Any ideas, should I revert [the labelling part of this change](https://github.com/wordpress-mobile/WordPress-Android/pull/16765/commits/22ec034232853380c2ae447b9f8bd79338aebdcb) back to ImageEditor? 🤔

@ParaskP7 Correct, this is about the label change as GitHub keeps the required checks hard-coded [here](https://github.com/wordpress-mobile/WordPress-Android/settings/branch_protection_rules/4567122). I've removed the old check from the required list. Once this PR is merged, we can add the new label as a required check - possibly after waiting a few days so developers get caught up with `trunk`.

**Review by ashiagr — APPROVED** [review]
Thank you for this PR, @ParaskP7! Code changes look good to me. 👍 Also, I tested image editing (single and multiple) using image and gallery blocks and found no issues.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Thank you for the review! 🙇 

> @ParaskP7 Correct, this is about the label change as GitHub keeps the required checks hard-coded [here](https://github.com/wordpress-mobile/WordPress-Android/settings/branch_protection_rules/4567122).

👍

> I've removed the old check from the required list. Once this PR is merged, we can add the new label as a required check - possibly after waiting a few days so developers get caught up with trunk.

Thank you so much for doing so Oguz! 🙇 

I'll add a task on the [parent issue](https://github.com/wordpress-mobile/WordPress-Android/issues/16562) so that we don't forget to add back the new label after this PR is merged and after having waited a few days for developers to catch up with it. 🥇

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Thank you for this PR, @ParaskP7! Code changes look good to me. 👍 Also, I tested image editing (single and multiple) using image and gallery blocks and found no issues.

Thank you so much for reviewing and testing this PR! 🙇

**Review by AliSoftware — APPROVED** [review]
I focused only on the changes done in `fastlane/lanes/localization.rb` and `.buildkite/pipeline.yml` (and didn't go thru the testing instructions), but from the diff those changes look good to me 👍

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> I focused only on the changes done in fastlane/lanes/localization.rb and .buildkite/pipeline.yml (and didn't go thru the testing instructions), but from the diff those changes look good to me 👍

Great, thank you, this is all I needed, a 👍 on the `localization.rb` change just in case I am not aware of any other change that needs to be done in addition to it, thank you! 🥇

**Pull request merged**
