### PR TITLE
Dismiss save popup on post upload and change events

### PR DESCRIPTION
**Pull request by mchowning**
Makes the dismissal of the blocking save in progress dialog more robust (and hopefully avoid more issues like https://github.com/wordpress-mobile/WordPress-Android/issues/13320) by causing that dialog to be dismissed any time the post is uploaded or changed.

This is almost certainly a bit of overkill, but I'm not seeing any adverse side effects, and my thinking is that it's better if we dismiss the dialog too much/early than failing to dismiss it and leaving the user with a non-responsive app that needs to be force killed. This is certainly a subjective judgment call though, so definitely open to other opinions.

We could just listen to these events in `EditPostActivity` and keep all of the `onPostUploaded` and `onPostChanged` logic together, but I thought it would be better to make a little progress (admittedly _very_ little progress) toward shrinking `EditPostActivity` and try to keep as much of the save dialog show/hide logic together in the `StorePostViewModel` class as we can.

#### Happy Path
1. Open a post
2. Make some changes
3. Allow the autosave to occur
4. Exit the editor
5. Observe no issues

#### Save-On-Exit Triggered
1. Open a post
2. Make some changes
3. Before the autosave kicks in exit the editor (so, exit the editor within <0.5s of changing the post)
4. Observe that the save dialog opens. On debug builds, the editor will crash after the save-on-exit completes because we wanted to raise a red flag in this scenario since the save-on-exit occurring can indicate there is a bug in the autosave mechanism. For that reason, in testing this, you may want to either (a) create a release build; or (b) make a debug build after commenting out [these lines](https://github.com/wordpress-mobile/WordPress-Android/blob/4412d7b8f892f2436177120a0fddae580b1951a7/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1782-L1784).

#### Post Preview
1. Open a _new_ post (if you open a saved post you'll encounter https://github.com/wordpress-mobile/WordPress-Android/issues/12570)
2. Add some content to the post
3. Wait a few seconds to give the autosave time to complete (otherwise you'll encounter https://github.com/wordpress-mobile/WordPress-Android/issues/13361)
4. Preview the post by tapping the "Preview" button in the menu
5. Observe the "Saving" dialog appears
6. Observe the post preview screen is presented
7. Back out of the post preview screen
8. Observe that the "Saving" dialog is _not_ visible when you return to the editor screen.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks for the PR, I'm going to review this later today. Just posting a note here that [this issue](https://github.com/wordpress-mobile/WordPress-Android/issues/13379) is happening even on this PR.

**Comment by malinajirka** [comment]
I created a quick fix but these two issues are present even on this PR - https://github.com/wordpress-mobile/WordPress-Android/pull/13380.

**Review by malinajirka — APPROVED** [review]
Thanks @mchowning! The changes LGTM - great improvement!

We just need to merge develop and fix the build, before we merge these changes back to develop. `showSavingProgressDialog` is not public anymore and has been renamed.

**Comment by mchowning** [comment]
> We just need to merge develop and fix the build, before we merge these changes back to develop. `showSavingProgressDialog` is not public anymore and has been renamed.

Thanks for calling that out! 🙇  I'm just waiting for [16.1 to be merged back to `develop`](https://github.com/wordpress-mobile/WordPress-Android/pull/13389), so I can resolve those issues when I merge this.

**Comment by loremattei** [comment]
Hey! I'm moving this to 16.3 has 16.2 has been cut. If you want this to make it to 16.2, please feel free to ping me!

**Comment by mchowning** [comment]
:wave: @loremattei ! I just merged this to the `release/16.2` branch like we discussed.

**Comment by loremattei** [comment]
Perfect! Thank you @mchowning!

**Pull request merged**
