### PR TITLE
Jetpack focus: Add tracks to banners and badges

### LINKED ISSUE #16979: [Android] Add tracks

### PR DESCRIPTION
**Pull request by ravishanker**
This PR adds tracks to banners and badges and disables full screen bottom sheet for now.

Fixes #16979 

| Banner | Badge | Bottom Sheet |
|---|---|---|
|banner_sharing| home_badge_light|Screenshot_20220726_124506|

To test:

- Build and run
- Launch WordPress app
- Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
- Select Debug Settings
- Find JetpackPoweredBottomFeatureConfig under Features in development Re-launch app (scroll down if necessary)
- Navigate to the following screens

Find and tap on **Jetpack powered banner**. Ensure a bottom sheet pops up. Filter Logcat in AS for WordPress-STATS and observe for tracks like so 🔵 Tracked: **jetpack_powered_banner_tapped**  with respective **screen** property.
- Stats
- Notifications
- Reader
- Reader Search
- Activity Log
- Sharing

Find and tap on **Jetpack powered badge**. Ensure a bottom sheet pops up. Filter Logcat in AS for WordPress-STATS: and observe for tracks like so 🔵 Tracked: **jetpack_powered_badge_tapped** with respective **screen** property.

- Home 
- Activity Log detail
- Reader detail
- App Settings
- Notifications Settings
- Me

Tap on Get the new Jetpack app button on any bottom sheet.  Observe for tracks in Logcat
🔵 Tracked: jetpack_powered_bottom_sheet_get_jetpack_app_tapped

NOTE:  You may find an additional property like **"default_tab_experiment":"site_menu"**, that is added by another feature.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and unit tests

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by irfano** [comment]
- Banner tracks work fine but the tracking line is not in click listener on `NotificationsListFragment` (event is tracked when the banner appears currently).
- I couldn't test badge tracks. The bottom sheet doesn't appear when I click the badge.

**Comment by ravishanker** [comment]
> * Banner tracks work fine but the tracking line is not in click listener on `NotificationsListFragment` (event is tracked when the banner appears currently).

Fixed, thank you

>     * I couldn't test badge tracks. The bottom sheet doesn't appear when I click the badge.

Did you enable the new feature flag JetpackPoweredBottomFeatureConfig?

**Comment by irfano** [comment]
> Did you enable the new feature flag JetpackPoweredBottomFeatureConfig?

I didn't enable it. But It's still not working after enabling it.

`jetpack_badge_footer` has `FrameLayout` and `jetpack_badge` as a child. When I tap FrameLayout, it's working, but it's not working when tapped the badge. I think we should fix this in another PR. Feel free to merge this if you agree with me on fixing the problem in another PR.

https://user-images.githubusercontent.com/2471769/182627733-47a967b5-cdef-4eaa-a00f-c2bf805ac9f9.mp4

**Comment by ravishanker** [comment]
> `jetpack_badge_footer` has `FrameLayout` and `jetpack_badge` as a child. When I tap FrameLayout, it's working, but it's not working when tapped the badge. I think we should fix this in another PR. Feel free to merge this if you agree with me on fixing the problem in another PR.

Makes sense, there're some layout changes coming, we can fix it as part of it.

**Review by irfano — APPROVED** [review]
LGTM!

**Pull request merged**
