### PR TITLE
Add missing tests to rewind feature

### PR DESCRIPTION
**Pull request by planarvoid**
- some cleanup of tests and add some missing test coverage

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I'm moving the milestone to 10.6 because 10.5 has been cut. Please, feel free to move it back to 10.5 if it has to land there: update it to target the release branch and ping me to update the build!

**Comment by loremattei** [comment]
Hey! I'm moving the milestone to 10.7 because 10.6 has been cut. Please, feel free to move it back to 10.6 if it has to land there: update it to target the release branch and ping me to update the build!

**Comment by 0nko** [comment]
Oops, I missed this somehow. @planarvoid, could you please resolve the conflicts and I'll review this ASAP.

**Comment by planarvoid** [comment]
@0nko done, let's wait for travis

**Comment by 0nko** [comment]
:shipit:

**Pull request merged**
