### PR TITLE
[Tooling] Fastfile cleanup - phase 1

### PR DESCRIPTION
**Pull request by AliSoftware**
Similar to what I recently did on WPiOS in https://github.com/wordpress-mobile/WordPress-iOS/pull/18140, this splits the `Fastfile` in smaller and more manageable files to ease future maintenance of our many lanes.

This PR is only the first of a set of PRs to clean up things.

 - This PR **only consists of moving lanes around and nothing else** (all changes were pure cut & paste, without any change) — then adds [the same `completion.zsh` file we added (and already reviewed and tested) in WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/18223) to make autocomplete support the split.
 - A follow-up PR will later build on this to reduce the noise of the comments documenting each lane, as those are quite verbose. In this future PR we plan to adopt the same, more compact style of documentation as we did in https://github.com/wordpress-mobile/WordPress-iOS/pull/18140/commits/8b47d7ce5c17461ff6dc56aa779f7846e4359d89
 - Finally this will likely be tidied up by a final PR running `rubocop` to standardize code styling and similar tweaks

### Review Guidance

I've decided to split that work in 3 PRs built on top of one another rather than a huge PR doing everything in order to make this way easier to review.

For this particular PR, since this is only about moving things around without changing any content, review should be quite straightforward:

 - You can use the `diff_lanes.rb` script provided below (which is the same as the one I provided in wordpress-mobile/WordPress-iOS#18140, except for loading the `Jetpack-Fastfile` as WPAndroid didn't have such file in `trunk`).
    - This script will extract each `lane :xyz do … end` block into its own text file (both for before/after the change) then run `diff` on each
    - You can then review all the `*-diff.txt` files to ensure that the implementation of each lane and function is still exactly the same before vs after the move
 - Then you can run `bundle exec fastlane lanes` to ensure that fastlane does not see any syntax error and still list the same list of lanes as before

_Please don't comment on code style or lane doc comments when reviewing that PR, as these are not the subject this PR is focusing on, and those will be addressed in the follow-up PRs_

<details><summary><tt>diff_lanes.rb</tt></summary>

```ruby
#!/usr/bin/env ruby

require 'fileutils'

OUTPUT_DIR = 'fastlane-lanes-diff-report'

def parse_lanes(content)
  current_lane = nil
  lane_indentation = ''
  buffer = ''
  implementations = {}

  content.lines.each do |line|
    # Detect `lane` or `def`, remember name and indentation, and start buffering next lines (aka implementation)
    lane_match = /^(\s*)lane (:\w*) +do/.match(line)&.captures || /^(\s*)def (\w*)/.match(line)&.captures
    if lane_match
      current_lane = lane_match[1]
      lane_indentation = lane_match[0]
    end

    next if current_lane.nil? # Skip any line outside a `lane` or `def` block

    buffer += line

    # Detect `end` keyword with matching indentation
    if /^#{lane_indentation}end$/.match?(line.chomp)
      implementations[current_lane] = buffer
      current_lane = nil
      lane_indentation = ''
      buffer = ''
    end
  end

  implementations
end

# Construct file path for given lane and suffix
def fpath(lane, suffix)
  (type, name) = lane.start_with?(':') ? ['lane', lane.delete_prefix(':')] : ['def', lane]
  File.join(OUTPUT_DIR, "#{type}-#{name}-#{suffix}.txt")
end

# Dump implementation of each lane/def in a dedicated `.txt` file. Raise if file already exist (suggesting the lane/def was declared/detected twice)
def dump_lanes(h, suffix:)
  h.each do |lane, impl|
    file = fpath(lane, suffix)
    raise "File already exists: #{file}" if File.exist?(file)
    File.write(file, impl)
  end
end


### MAIN ###

raise "Please delete #{OUTPUT_DIR} before starting" if Dir.exist?(OUTPUT_DIR) && !Dir.empty?(OUTPUT_DIR)
FileUtils.mkdir_p(OUTPUT_DIR)

# Parse **new** lanes from `Fastfile` + `fastlane/lanes/*.rb`
(['fastlane/Fastfile'] + Dir.glob('fastlane/lanes/*.rb')).each do |f|
  puts "--- Parsing: #{f}..."
  new_lanes = parse_lanes(File.read(f))
  dump_lanes(new_lanes, suffix: 'new')
end

# Parse **old** lanes from trunk's `Fastfile`, `Jetpack-Fastfile` and `ScreenshotFastfile`
puts "--- Parsing lanes from trunk..."
trunk_lanes = {}.merge(
  parse_lanes(`git show trunk:fastlane/Fastfile`),
  parse_lanes(`git show trunk:fastlane/ScreenshotFastfile`)
)
dump_lanes(trunk_lanes, suffix: 'trunk')

# Compute diffs between the two
trunk_lanes.each do |lane, impl|
  diff = `diff -w "#{fpath(lane, 'trunk')}" #{fpath(lane,'new')}`
  File.write(fpath(lane, 'diff'), diff)
end
```
</details>

### CODE REVIEW

**Comment by AliSoftware** [comment]
Just noting that I plan to rebase this on Monday to:
 - Replicate here the recent changes which happened in #16235 
 - Fix the conflict along the way
 - Target the `release/19.6` branch once code freeze for 19.6 has happened Monday morning

**Review by mokagio — APPROVED** [review]
> I've decided to split that work in 3 PRs built on top of one another rather than a huge PR doing everything in order to make this way easier to review.

Appreciated.

:shipit:

**Comment by mokagio** [comment]
I didn't noticed the merge conflicts when I approved. 

FWIW, I think the commit on `trunk` that introduced the conflicts was [this one](https://github.com/wordpress-mobile/WordPress-Android/commit/1897f41f8eb47980df210568a58543cd6851b265#diff-dff4b99d4e651ab9d7597876ec8dbe92aa934e42c0fb55f4aadd6c106fc96688).

**Comment by AliSoftware** [comment]
- Rebased the whole branch on top of latest `trunk`
 - Fixed the conflict at part of the rebase, by re-applying all the changes made on the `Fastfile` since last time on the new split files
 - Verified that I didn't forget anything by re-comparing the diff between 6069ee7...605c5ed (changes made on `trunk` between when that PR's branch was initially cut and now) and the result of my `diff_lanes.rb` script before the change
 - Verified that I didn't forget re-applying anything by re-running my `diff_lanes.rb` script again after reapplying all the changes and confirming that all `*-diff.txt` files generated by the script were empty
 - Especially confirmed that even changes not from the lanes implementations but from other parts of the `Fastfile`, like the change made by #16231, was also included

So all seems to be back on track and I'm going to merge this as soon as CI goes green so that I can use and test this during `code_freeze` and `complete_code_freeze` of 19.6.

**Pull request merged**
