### PR TITLE
Refactor notification detail activity to use ViewPager2

### PR DESCRIPTION
**Pull request by mkevins**
### Description

This PR updates the `NotificationsDetailActivity` to migrate from `ViewPager` to `ViewPager2`, to remove the usages of deprecated framework APIs. It also, in turn, migrates `NotificationDetailFragmentAdapter` to extend `FragmentStateAdapter` instead of the deprecated `FragmentStatePagerAdapter`.

#### Note

There are work-arounds in place in the existing implementation to mitigate framework bugs, but these work-arounds are no longer possible with the migration to `ViewPager2`, and likely no longer necessary.

* An `IllegalStateException` is [wrapped in a try / catch](https://github.com/wordpress-mobile/WordPress-Android/pull/20467/files#diff-e48edd5a3728c682d33322513d5ae0d968c321d8cda405d1dd45e9f4ac8b4152L632-L638) in `restoreState`, which cannot be overriden as it declared final in `FragmentStateAdapter`.
  * [Original issue](https://issuetracker.google.com/issues/36963722)
* A `TransactionTooLargeException` is avoided by [nulling the nested state collection in the bundle](https://github.com/wordpress-mobile/WordPress-Android/pull/20467/files#diff-e48edd5a3728c682d33322513d5ae0d968c321d8cda405d1dd45e9f4ac8b4152L650) in `saveState`, which is no longer possible since it is declared final in `FragmentStateAdapter`.
  * [Original issue](https://issuetracker.google.com/issues/37103380#comment77)

I don't expect these issues to reoccur with the migration to `ViewPager2`, but I'm noting these removals here, in case unexpected regressions are detected.

-----

## To Test:

Smoke test (behavior should not change):

* Log in to an account with notifications
* Tap the notifications tab
* Tap one of the notifications (expect to see the detail view)
* Swipe left and right to view other notifications in the list
* Expect the transitions to be working as before

-----

## Regression Notes

1. Potential unintended areas of impact

Notifications Detail View

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

The code is not yet in a state to facilitate adding unit tests for these changes.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>WPViewPager2Transformer</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>TransformType</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jarvislin — COMMENTED** [review]
Hi @mkevins Thanks for migrating to ViewPager2.
I found two issues when I smoke test this PR:
1. Buttons on the toolbar have disappeared or at a wrong position.
2. Buttons at the bottom bar have disappeared.

| This PR | Prod |
|---|---|
| Screenshot_20240315-143158 | Screenshot_20240315-143216 |
| Screenshot_20240315-143149 | Screenshot_20240315-143207 |

**Comment by mkevins** [comment]
> Hi @mkevins Thanks for migrating to ViewPager2. I found two issues when I smoke test this PR:
> 
> 1. Buttons on the toolbar have disappeared or at a wrong position.
> 2. Buttons at the bottom bar have disappeared.
> 

Thank you for testing this! I could not reproduce this on my account, but was able to on yours, and I'm not quite sure why 🤔 . In any case, I suspect this may somehow be related with the migration to `FragmentStateAdapter`, and how the toolbar is [conditionally shown or hidden](https://github.com/wordpress-mobile/WordPress-Android/pull/20467/files#diff-e48edd5a3728c682d33322513d5ae0d968c321d8cda405d1dd45e9f4ac8b4152R247-R249).

I think this is a good place to start debugging, but the UI updating mechanism may need to be refactored a bit in the activity to ensure stale state isn't a factor (I recall the activity was restarting multiple times, for whatever reason, even on trunk, so I couldn't rule out some kind of race condition).

**Comment by antonis** [comment]
Hey @jarvislin 👋 
I took the liberty of pushing a few minor code improvements and tried to fix the reported toolbar issue. Could you give it another round of testing 🙇

**Review by jarvislin — COMMENTED** [review]
Hi @antonis, buttons at the bottom bar are displayed correctly. But the issue of toolbar still occurs, please see the following video:

**Comment by antonis** [comment]
Thank you for testing @jarvislin 🙇 
I'm now able to reproduce with my test account. It's weird that it is reproduced only when I start from a post notification.
I'll investigate further and ping you for another round of testing 🤞  

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/1c5c0e2c-7eff-43b0-94c2-47251fb38cb4

**Comment by antonis** [comment]
> buttons at the bottom bar are displayed correctly. But the issue of toolbar still occurs

I've investigated this and I think I understand the conflict that creates this issue. `NotificationsDetailActivity` and the `ReaderPostDetailFragment` have a toolbar. To prevent showing a duplicate one [we are hiding it on the second case](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java#L249) (introduced with https://github.com/wordpress-mobile/WordPress-Android/pull/13202). For some reason (which I haven't figured) the change to `ViewPager2` affected the timing of things and both toolbars are hidden only when we open the detail screen with a post notification (see https://github.com/wordpress-mobile/WordPress-Android/pull/20467#issuecomment-2036238769)

<details>
<summary>To visualise the issue, if we never hide the toolbar we end up having two of them. One from the notification details and one from the reader details!</summary>

Screenshot_20240404_111855
</details>

I fixed the toolbar visibility with d6da7a08aa9bc68bac739bf8b24da2d2ea393f22 but there is a remaining issue. The browse and share menu items are not (always) visible in the toolbar as before. They are still accessible inside the menu which inflates correctly.

<details>
<summary>I've tried hacky ways to enforce their visibility but this didn't work either :( </summary>

```
    @Override
    public boolean onPrepareOptionsMenu(@NonNull Menu menu) {
        boolean result = super.onCreateOptionsMenu(menu);
        MenuItem browse = menu.findItem(R.id.menu_browse);
        if (browse != null) {
            browse.setVisible(true);
            browse.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
        }
        MenuItem share = menu.findItem(R.id.menu_share);
        if (share != null) {
            share.setVisible(true);
            share.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
        }
        return result;
    }
```

</details>

I plan to stop the investigation for today and revisit later in the week.

@jarvislin If you have any thoughts on how to work around this they are more than welcome 🙇

**Comment by jarvislin** [comment]
Hi @antonis, 
I found a solution here: https://stackoverflow.com/a/45653449
And I just pushed my changes. Could you check if the changes also work on your device? Thanks

**Comment by antonis** [comment]
Thank you for the changes @jarvislin 🙇 
Your changes seem to fix the toolbar issue and I didn't notice any side effects in the reader functionality.

Testing out the implementation I've noticed again the toolbar missing on some occasions and an inconsistent behaviour since sometimes the wrong notifications seems to open :( I don't think this is related to your changes though.  

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/4db561a7-3456-46cf-a7de-e09452acaede

**Comment by jarvislin** [comment]
@antonis Thank you for the testing.

> Testing out the implementation I've noticed again the toolbar missing on some occasions and an inconsistent behaviour

I think the root cause of the behavior is the animation of viewpager.
When it was swiping, it also handled the visibility of toolbar.
And there were too many pages, so the main thread was stuck, which caused the visibility of toolbar to be wrong (I guess).
I've removed the swiping animation, can you try again? I cannot reproduce the issue on my device 🙏

**Review by antonis — APPROVED** [review]
> I think the root cause of the behavior is the animation of viewpager.
When it was swiping, it also handled the visibility of toolbar.
And there were too many pages, so the main thread was stuck, which caused the visibility of toolbar to be wrong (I guess).
I've removed the swiping animation, can you try again?

This fixed it for me 🎉 
I've retested the flows and everything looks good to me both on the notifications and the reader side. 

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/67f8553d-eeb9-4ee0-8507-034ef85b92a9

Thank you for helping out with this @jarvislin 🙇 
I'm approving on my side. Feel free to merge ✅ 

ps. Of course thank you @mkevins for this refactoring 🙇

**Comment by mkevins** [comment]
Thank you both for following through with this! I knew it was in good hands, and it's very nice to see this merged! 🎉

**Pull request merged**
