### PR TITLE
Feature/15609 add tracks

### LINKED ISSUE #15609: [Android] About Screen v1: Add tracks
See https://docs.google.com/spreadsheets/d/1X1DhOvWuVylbQpRBPbmsq2yPoj962_KSL8D3uXssOc4/edit#gid=0

Looks like tracks are spread across items in WPAndroid and about-automattic-android library.  Since library doesn't have any network related code.  Should this be done entirely on WPAndroid side by passing a callback function!

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes #15609 

This PR updates with necessary changes to allow posting tracks.  It depends on [Part 1](https://github.com/Automattic/about-automattic-android/pull/18)  PR and [fixes](https://github.com/Automattic/about-automattic-android/pull/19) on about-automattic-android library

NOTE:  After merging [Part1](https://github.com/Automattic/about-automattic-android/pull/18).  Need to update the about-automattic-library version in the build.gradle

To test:

**Setup: Enable feature flag**

1. On the Main screen, tap the Me button.
1. On the Me screen, go to App Settings > Debug settings.
1. On the Debug Settings screen, scroll down to the "Features in development" section and tap `UnifiedAboutFeatureConfig` to enable the About feature flag.
1. Restart the app

**Test**

1. On the Main screen, tap the Me button.
1. Notice About WordPress option
1. Tap on the About WordPress item.
1. Click on each of the items in order and
1. Notice in the Logcat the following tracks are logged

```
🔵 Tracked: about_screen_shown, Properties: {"screen":"main"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"share"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"rate_us"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"twitter"}

🔵 Tracked: about_screen_button_tapped, Properties: {"button":"legal"}
🔵 Tracked: about_screen_dismissed, Properties: {"screen":"legal_and_more"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"terms_of_service"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"privacy_policy"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"acknowledgements"}
🔵 Tracked: about_screen_dismissed, Properties: {"screen":"legal_and_more"}

🔵 Tracked: about_screen_button_tapped, Properties: {"button":"automattic_family"}
🔵 Tracked: about_screen_button_tapped, Properties: {"button":"work_with_us"}

🔵 Tracked: about_screen_dismissed, Properties: {"screen":"main"}

```

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
Manual testing

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by renanferrari — COMMENTED** [review]
Hey @ravishanker, thanks for handling this but there are a few issues with this PR:

1. Although the app is tracking the event you mentioned, that's not the right event we should be tracking there. The parameters are also incorrect.
2. We also don't need to add separate events for each tap event.

In case you missed it, please refer to the analytics doc linked here for the correct values: pc5zdG-lb-p2

**Comment by AliSoftware** [comment]
Moving this one to 18.9 as I'm doing doing the code freeze for 18.8

**Review by renanferrari — COMMENTED** [review]
Other than the issues I mentioned in [my review](18-gh-Automattic/about-automattic-android#pullrequestreview-818490657) on the Part 1 PR, I think the only thing we need to change in this PR is that it should target the frozen branch.

**Comment by renanferrari** [comment]
I still found some issues with the Part 1 PR and will submit a new PR to fix those issues soon. Once we merge that new PR, we can sync the implementation here with the latest version of the library and finally merge this. I have added the `[Status] Not Ready for Merge` label here to indicate we're not merging this until we do so.

**Comment by ravishanker** [comment]
> I still found some issues with the Part 1 PR and will submit a new PR to fix those issues soon. Once we merge that new PR, we can sync the implementation here with the latest version of the library and finally merge this. I have added the `[Status] Not Ready for Merge` label here to indicate we're not merging this until we do so.

-  Merged the other [PR](https://github.com/Automattic/about-automattic-android/pull/19)
-  Updated the library version to latest here

However, the build is failing due to GB issue, that is reported in channels.  Please merged if if it gets resolved.  Thank you.

**Comment by AliSoftware** [comment]
FYI https://github.com/wordpress-mobile/WordPress-Android/pull/15646 has landed to fix the GB compilation issue, but its cherry-pick to `release/18.8` (https://github.com/wordpress-mobile/WordPress-Android/pull/15647) is still pending review.

**Comment by ravishanker** [comment]
Hey @renanferrari - Please merge this when you get a chance.  It's all green now.  Thank you

**Review by renanferrari — APPROVED** [review]
Tested again and everything is working as expected.

LGTM 👍

**Comment by AliSoftware** [comment]
This just got included in the latest beta 18.8-rc-2 🎉

**Pull request merged**
