### PR TITLE
Issue/10644 material site creation

### LINKED ISSUE #10644: Implement Material theme on Site Creation flow
We should switch widgets used at Site Creation flow to their material counterparts, remove color references where possible, and switch to using material `textAppearance` attributes.

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10644

#11229 needs to be merged first.

This PR adds material theme and Dark Mode support to site creation flow.

The only change to logic is related to NEXT/SKIP buttons. Instead of styling a single button, we have two buttons and switch their visibility on demand.

It's kind of hard to take a screenshot of the shimmering skeleton layout, but I used the same colors as in the post list.

comparison_site_creation

Landscape:
comparison_cr_land

To test:
- Go through site creation flow, and make sure that everything looks good in both light and dark themes.
Pay attention to Skip/Next buttons.

You can change the app theme from App Settings.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@mattmiklic this is not a real text filed, more like artist rendering of the browser address field. I can switch it to the text field, but this might go against initial intent with it?

**Comment by mattmiklic** [comment]
Hey @khaykov, sorry my last comment wasn't clear. In my comment about using the outlined text field component, I was referring to the site title/tagline screen. Here's a side-by-side with your screenshot and what I was thinking:

Screen Shot 2020-02-06 at 3 54 06 PM

On the address field in the preview screen, I was noting the 1px transparent line underneath the address bar area of the illustration. It's not that perceptible (in this screenshot, anyway) in light mode but it stands out in dark mode. I'm not sure if that's coming from our illustration or the screenshot, though.

Screen Shot 2020-02-06 at 3 55 53 PM

**Comment by khaykov** [comment]
@mattmiklic Ah, got it! Yes, you are right, I'll fix those right away :)

**Comment by khaykov** [comment]
@mattmiklic I updated the input fields. 

[Image from Gyazo](https://gyazo.com/43a6818ab01a658ee21136935fe90eb9)

The line thing is actually part of a website theme. Not sure why it's there, but it's there :) 

[Image from Gyazo](https://gyazo.com/023d49177e2ca4b1d9aadcb2b3bb50d8)

**Comment by mattmiklic** [comment]
Looking good!

> The line thing is actually part of a website theme. Not sure why it's there, but it's there :)

Nothing to worry about then; 🚢!

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by oguzkocer** [comment]
We're freezing `14.3` today, so this PR is being bumped to `14.4`. If you'd like it to ship with `14.3`, please merge it into `release/14.3` and ping me – I'll be happy to cut a new beta release.

**Pull request merged**
