### PR TITLE
Addressing issues with Site Settings NumberPickerDialog

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #3641 by using a NumberPickerDialog for the threading preference. The issue also brought to my attention similar problems with Close After and Paging preferences.

### CODE REVIEW

**Comment by maxme** [comment]
Now there is a on/off switch, should we remove the "none" option from the list?

**Comment by mattmiklic** [comment]
> Now there is a on/off switch, should we remove the "none" option from the list?

Yep, we should. :+1:

**Comment by tonyr59h** [comment]
This PR also addresses #3685 via 455bc6343e8f30982c8376992784ea0ec859569c

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
