### PR TITLE
Add floating "New notes" button

### LINKED ISSUE #4743: Add floating "New notes" button
If a notification is received while looking at the notifications list, it'd be great to have a floating "New notes" button appear, and when you tap on it you're taken all the way up without having to scroll.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #4743 by adding a floating "New notes" button that appears when a new notification is received while looking at the notifications list (note: it doesn't appear if you're already at the top of the list).
When you tap on it you're taken all the way up without having to scroll the list.

Also merged develop into this branch. 

To test: 
- Scroll the notifications list.
- Make a comment on a blog.
- Wait till the PN reaches the device.
- You should see the button appearing at the bottom of the list.
- Tapping the button should take you to the top of the list.

cc @kwonye

### CODE REVIEW

**Comment by daniloercoli** [comment]
For the record, the following https://github.com/wordpress-mobile/WordPress-Android/pull/4745/commits/807345b979510753b07c1e0f9ab6ac7e572b8716 is the only commit to review.

**Comment by mzorz** [comment]
I love this feature, and it looks great @daniloercoli :)

Code looks good, just one thing I found while testing:

Weird behaviour detected (corner case):
- while at the Notifications screen, if I get a new PN, the banner appears and the bell icon turns into unread ribbon, and I quickly lock the screen
- unlock the screen again, the orange dot goes away but the banner button is sitting there and never goes away, even if I scroll the list manually to the top, or refresh the list by pulling down, or anything. It only goes away if I tap on it.


Same behaviour is observed when this happens:

- open the app and stay in some other tab (Reader, main, or profile), but not the Notifications tab.
- make yourself receive a notification
- see the orange dot appear on the bell icon
- tap on / swipe to the notifications tab: the “new notifications” banner is there and nothing makes it go away except pressing it. 

In both cases I would have expected the button to go away either after a few seconds or when scrolling the list up.

**Comment by daniloercoli** [comment]
Thanks @mzorz !  Not sure how I missed that simple tests.... :face_with_head_bandage: 
Anyway, those should be fixed now.

Consider that I found other minor edge cases, but were already there before I added the badge. Will add to the master thread, to be sure we will take care of them.

**Comment by mzorz** [comment]
Thank you @daniloercoli ! ok now I found another thing with this new commit: if I scroll the list down to somehwere in the middle or bottom (just not at the top), and then switch tabs or lock the screen and come back, now the unread ribbon and "new notes" button disappear - I think the only case where the button should be dismissed is if you actually either press it or scroll all the way to the top, making the actual new notifications visible and therefore not `unread` anymore.

If we could take care of that, that would be perfect!

**Comment by mzorz** [comment]
Update @daniloercoli : 
>  if I scroll the list down to somehwere in the middle or bottom (just not at the top), and then switch tabs or lock the screen and come back

I should have written:

> if I scroll the list down to somehwere in the middle or bottom (just not at the top), and then switch tabs, receive a notification and come back

**Comment by daniloercoli** [comment]
This is done on purpose. As soon as you switch to notifications tab everything is marked as seen and both the ribbon and the new button disappear. We may want to autoscroll to the top though.

**Comment by daniloercoli** [comment]
This is done on purpose. As soon as you switch to notifications tab everything is marked as seen and both the ribbon and the new button disappear. We may want to autoscroll to the top though.

**Comment by daniloercoli** [comment]
This is done on purpose. As soon as you switch to notifications tab everything is marked as seen and both the ribbon and the new button disappear. We may want to autoscroll to the top though.

**Comment by mzorz** [comment]
Auto scroll to the top should be fine :+1:

**Comment by mzorz** [comment]
Awesomeness 🔥

**Pull request merged**
