### PR TITLE
Editor - Featured Images

### PR DESCRIPTION
**Pull request by aforcier**
Adds support for featured images for the new visual editor, implementing https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/16.

* Re-implements the existing legacy editor functionality of setting an image as featured from the image settings dialog:

16-featured-image-image-settings

Demo: https://cloudup.com/caRCGPOBaxV

This will work for images in already published posts, as well as recognize featured images that were set from outside the Android app.

* Also adds support for setting the featured image from the post settings dialog:

16-featured-image-post-settings

Demo: https://cloudup.com/cHGNN2CdZOA

This isn't fully implemented yet. You can set a featured image, change it, or remove it, but you can only use images already uploaded to the WP media library. Full functionality (upload from device, take photo) will be added in a future PR.

Ref on related discussion: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/16#issuecomment-154875657.

Issue for future improvements: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/265

This also includes some changes to the post settings layout. cc @thianhlu

<h4>Some notes</h4>

* I changed how featured images are handled to get around a issue with the XML-RPC `metaWeblog.editPost` call. If you attempt to update an existing post and re-assign the same featured id (`wp_post_thumbnail`) to it, the upload fails with a 404: 'Invalid attachment ID.' error. If the featured image hasn't changed, you're supposed to omit that parameter from the call. This didn't affect the legacy editor because you couldn't change the featured image for published posts.

* I fixed a bug where alignment metadata for images was incorrectly capitalized. If you have posts with images you wrote with a previous version of the visual editor, the image alignment data may not be recognized and will be set to 'None' when you launch image settings. Updating from there will persist the changes (and all images added from this version on will work correctly).

Needs review: @tonyr59h @bummytime

### CODE REVIEW

**Comment by tonyr59h** [comment]
Love the changes! This is going to make a lot of folks happy when it ships, it's one of the most brought up features on the Play Store reviews.

After 20 minutes of trying to break it I only found one issue. Changing the featured image via `Image settings` doesn't take, though I'm still treated to an upload icon and a notification that the post was updated.

**Comment by aforcier** [comment]
> Changing the featured image via Image settings doesn't take, though I'm still treated to an upload icon and a notification that the post was updated.

It looks like in some cases the new featured image is getting overwritten by autosave (when autosave pulls data from the post settings screen). Made a change so that post settings are updated as soon as the featured image is changed. Should be working now!

**Comment by bummytime** [comment]
@aforcier testing this out:

Tested on:
* API 16 :+1: 
* API 17 :+1:  (including Nexus4 device)
* API 18 :+1: 
* API 19 :+1: 
* API 21 :+1:
* API 22 :+1:  (including Samsung S6 device)
* API 23 :+1:  (including Nexus7 device)

The fix for the `featured image via Image settings` bug you have in the latest commit seems to help...but tbh I was not seeing the issue originally. I'll let @tonyr59h weigh in on that. :-)

Very nice work on this @aforcier!

**Comment by tonyr59h** [comment]
Looks like it's all working now. I did some .org and .com testing and didn't run into any problems. Great work @aforcier!

:shipit:

**Comment by meremagee** [comment]
:yellow_heart:

**Pull request merged**
