### PR TITLE
[Modal Layout Picker] "Preview" button functionality

### PR DESCRIPTION
**Pull request by antonis**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2452

**Related PRs:**

- Depends on: https://github.com/wordpress-mobile/WordPress-Android/pull/13018

- `gutenberg`:
1. https://github.com/WordPress/gutenberg/pull/25661
1. https://github.com/WordPress/gutenberg/pull/25930
- `gutenberg-mobile`:
1. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2674
1. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2696
- `WordPress-FluxC-Android`
1. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1715

To test:

Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

- Start by navigating to the Modal Layout Picker

### Preview a layout
1. Select a layout from the list
1. Select Preview
- **Expect** to see a read-only editor load that shows a preview of the selected layout.

### Preview a layout, then a different one
1. Select a layout from the list
1. Select Preview
- **Expect** to see a read-only editor load that shows a preview of the selected layout.
1. Select Back
1. Select a different layout from the list
1. Select Preview
- **Expect** to see a read-only editor load that shows a preview of the newly selected layout.

### Preview a layout, then cancel
1. Select a layout from the list
1. Select Preview
- **Expect** to see a read-only editor load that shows a preview of the selected layout.
1. Select Back
- Or close the modal by swiping down from the top
1. Close the modal via the ✖️ 

### Preview a layout, then create a page
1. Select a layout from the list
1. Select Preview
- **Expect** to see a read-only editor load that shows a preview of the selected layout.
1. Select Create Page
- **Expect** to see the page editor load with the selected layout content populated.
- **Expect** to see the page editor load with a title that relates to the content. Example a layout from the "About Pages" should have a title like "About"

### Spot check for regressions
Open an existing page or blog, expect the content to be loaded and for normal editing to take place.

### Spot check Modal Layout Picker Disabled
1. Disable Modal Layout Picker
1. Create a new page
- **Expect** to see the existing Starter Page Template Picker
1. Select an option
- **Expect** to see the Preview with "Close" and "Apply" as actions
1. Try Each option, expect it to behave as it previously did. 

## NOTES

I tried another approach by creating a separate Gutenberg Editor just for the preview functionality ([this is the approach on iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/14871/files#diff-f6c17c64b35f459474509b0698039f10)). This proved quite complex and the amount of code that needed to be duplicated (and maintained) made it a worst approach in my view.
Thus the approach followed in this PR is passing a `isPreview` flag and making the less changes possible to achieve the desired result.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by malinajirka — COMMENTED** [review]
Great job @antonis! The code looks good.

I'm not sure if this was discussed or not, so I'm better sharing it. We used to have support for local previews in the past. They were removed in [this ticket](https://github.com/wordpress-mobile/WordPress-Android/issues/9729). Mostly because the local preview never looks the same as the actual site - it's missing css. Since we removed local previews I'm wondering if it make sense to re-introduce them for page layouts. AFAIK they have exactly the same issues - I tested a few layouts and encountered differences between the editor view and preview in a webview. If this was already discussed, please ignore this comment. 

Some issues I noticed
1. When the app crashes/the user restarts the app while in preview, a draft is created. I'm not sure it's an issue, just mentioning it so we are aware of it.

2. Title is always empty - I tested 6 layouts on a self-hosted and .com sites.
missing-title


3. "Don't keep activities" in developer settings results in an empty layout chooser.
dontkeepactivities

**Comment by antonis** [comment]
Hello @malinajirka 👋 ,

thank you for taking the time to review this 🙇 

> I'm not sure if this was discussed or not, so I'm better sharing it. We used to have support for local previews in the past. They were removed in [this ticket](https://github.com/wordpress-mobile/WordPress-Android/issues/9729). Mostly because the local preview never looks the same as the actual site - it's missing css. Since we removed local previews I'm wondering if it make sense to re-introduce them for page layouts. AFAIK they have exactly the same issues - I tested a few layouts and encountered differences between the editor view and preview in a webview. If this was already discussed, please ignore this comment.

Tbh, I was not aware that local previews were intentionally [removed](https://github.com/wordpress-mobile/WordPress-Android/issues/9729) in the past. In my understanding the limitations of the preview functionality were considered during design and [there will be a separate project in the future to expand this preview to provide a more WYSIWYG experience.](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2452) (cc @chipsnyder )

> 1. When the app crashes/the user restarts the app while in preview, a draft is created. I'm not sure it's an issue, just mentioning it so we are aware of it.

I will investigate this further.

> 2. Title is always empty - I tested 6 layouts on a self-hosted and .com sites.

I fixed this as part of a next [pr](https://github.com/wordpress-mobile/WordPress-Android/pull/13097) with 1c3f9410ba42b18f0b2c756885749653e7535b0e

<details>
  <summary>Screenshot</summary>

</details>

> 3. "Don't keep activities" in developer settings results in an empty layout chooser.

I will investigate this further.

**Comment by antonis** [comment]
> 1. When the app crashes/the user restarts the app while in preview, a draft is created. I'm not sure it's an issue, just mentioning it so we are aware of it.

Tried to handle this in the `onDestroy` method of `EditPostActivity` unsuccessfully. I'm not sure if I can prevent this from happening without major changes in the editor.

> 3. "Don't keep activities" in developer settings results in an empty layout chooser.

Fixed with 32e255f2e5a2d8a065ae449977493a4438761583 and 2b24ee11cb257730d116c117ebcae967e46e0834 (depends on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1715)

**Comment by chipsnyder** [comment]
> Tbh, I was not aware that local previews were intentionally removed in the past. In my understanding the limitations of the preview functionality were considered during design and there will be a separate project in the future to expand this preview to provide a more WYSIWYG experience. (cc @chipsnyder )

Thanks for sharing that ticket about Previews @malinajirka. When planning this project we discussed more of WYSIWYG experience but it was determined that reusing the Preview that is currently shown as part of the Gutenberg preview would be sufficient for this project. (_internal reference: pb3aDo-ny_) but we are discussing with @iamthomasbishop about what the next phase of the preview will look like.

**Review by malinajirka — APPROVED** [review]
LGTM, thanks @antonis!

**Pull request merged**
