### PR TITLE
Merge Release Notes for 20.4

### PR DESCRIPTION
**Pull request by ParaskP7**
PR to make sure the Editorialized Release Notes for 20.4 land in `trunk` by end of week.

@wordpress-mobile/owl-team could you please double check these 2 commits (91a72e54a7a269165b0d5df52b762696e3072d50 + f2d58a8e4449398d08820ace9a956bc595708b8a) that I ended-up committing manually due to a time out issue with [RubyGems](https://rubygems.org/). You can read the description on both those commits for more details on all that.

~~PS: Yesterday, I updated my Mac to the latest macOS (Monterey 12.5), maybe that's has something to do with it... Apart from that I don't know why [RubyGems](https://rubygems.org/) started timing out on my end, maybe this is temporary outage on their end. 🤔~~

UPDATE: Today I tried running `bundle exec fastlane update_appstore_strings version:20.4` again. This time it worked!

It seems that there was indeed a problem with [RubyGems](https://rubygems.org/) yesterday. So, after me running this `update_appstore_strings` fastlane command I got the following today, note the `Nothing to commit, working tree clean ✅.` output, the manual commits I did yesterday completely match the result that I would be getting my running `update_appstore_strings` anyway as nothing new was committed (or pushed afterwards):

<details>
  <summary>Click to expand!</summary>
  
  `bundle exec fastlane update_appstore_strings version:20.4`
  ```
[11:52:54]: ----------------------------------------------------------------------
[11:52:54]: --- Step: Switch to android update_wordpress_appstore_strings lane ---
[11:52:54]: ----------------------------------------------------------------------
[11:52:54]: Cruising over to lane 'android update_wordpress_appstore_strings' 🚖
[11:52:54]: -------------------------------------
[11:52:54]: --- Step: android_get_app_version ---
[11:52:54]: -------------------------------------
[11:52:54]: -------------------------------------
[11:52:54]: --- Step: ensure_git_status_clean ---
[11:52:54]: -------------------------------------
[11:52:54]: $ git status --porcelain
[11:52:54]: Git status is clean, all good! 💪
[11:52:54]: ---------------------------------------
[11:52:54]: --- Step: an_update_metadata_source ---
[11:52:54]: ---------------------------------------
[11:52:54]: Parameter .po file path: /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/metadata/PlayStoreStrings.po
[11:52:54]: Release version: 20.4
[11:52:54]: File /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/metadata/PlayStoreStrings.po updated!
[11:52:54]: ---------------------
[11:52:54]: --- Step: git_add ---
[11:52:54]: ---------------------
[11:52:54]: Successfully added "/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/metadata/PlayStoreStrings.po" 💾.
[11:52:54]: ------------------------
[11:52:54]: --- Step: git_commit ---
[11:52:54]: ------------------------
[11:52:54]: $ git status /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/metadata/PlayStoreStrings.po --porcelain
[11:52:54]: Nothing to commit, working tree clean ✅.
[11:52:54]: Cruising back to lane 'android update_appstore_strings' 🚘
[11:52:54]: --------------------------------------------------------------------
[11:52:54]: --- Step: Switch to android update_jetpack_appstore_strings lane ---
[11:52:54]: --------------------------------------------------------------------
[11:52:54]: Cruising over to lane 'android update_jetpack_appstore_strings' 🚖
[11:52:54]: -------------------------------------
[11:52:54]: --- Step: android_get_app_version ---
[11:52:54]: -------------------------------------
[11:52:54]: -------------------------------------
[11:52:54]: --- Step: ensure_git_status_clean ---
[11:52:54]: -------------------------------------
[11:52:54]: $ git status --porcelain
[11:52:54]: Git status is clean, all good! 💪
[11:52:54]: ---------------------------------------
[11:52:54]: --- Step: an_update_metadata_source ---
[11:52:54]: ---------------------------------------
[11:52:54]: Parameter .po file path: /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/jetpack_metadata/PlayStoreStrings.po
[11:52:54]: Release version: 20.4
[11:52:54]: File /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/jetpack_metadata/PlayStoreStrings.po updated!
[11:52:54]: ---------------------
[11:52:54]: --- Step: git_add ---
[11:52:54]: ---------------------
[11:52:54]: Successfully added "/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/jetpack_metadata/PlayStoreStrings.po" 💾.
[11:52:54]: ------------------------
[11:52:54]: --- Step: git_commit ---
[11:52:54]: ------------------------
[11:52:54]: $ git status /Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/fastlane/../WordPress/jetpack_metadata/PlayStoreStrings.po --porcelain
[11:52:54]: Nothing to commit, working tree clean ✅.
[11:52:54]: Cruising back to lane 'android update_appstore_strings' 🚘
  ```

</details>

So, all in all, we are good to go with the release notes and this PR can be safely reviewed now! 🎉

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: We can ignore the Buildkite related [Instrumented Tests](https://buildkite.com/automattic/wordpress-android/builds/5785#01823f20-eb04-4369-ac35-215ca363e61d) check failing for now. I can merge this to `trunk` anyway since I think this test is just being flaky (`wPScreenshotTest`) and it is not related to the release notes update anyhow (see [Firebase Test Lab](https://console.firebase.google.com/project/api-project-108380595987/testlab/histories/bh.b3d1e88d8b09c8be/matrices/6705242340131978808/executions/bs.e28d285715a38f0b/test-cases)).

Cc @jkmassel @pachlava

**Comment by pachlava** [comment]
> this test is just being flaky (wPScreenshotTest)

Actually, excluding the `org.wordpress.android.ui.screenshots` package from execution on CI is something that has to be done, and I have this in the backlog, once I'm done with `publishSimplePost` fix. Screenshots tests are usually not a part of UI tests in most of the repos, and they were not for current repo, before moving to Buildkite (old CircleCI config):

```yml
      - android/firebase-test:
          ...
          test-targets: notPackage org.wordpress.android.ui.screenshots
          ...
```

**Comment by ParaskP7** [comment]
> Screenshots tests are usually not a part of UI tests in most of the repos, and they were not for current repo, before moving to Buildkite (old CircleCI config)

This is a good point @pachlava ! 👍 What are your thought on that @jkmassel ? 🤔

**Comment by pachlava** [comment]
FWIW, I have a [draft PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16952) where I tried excluding screenshots tests yesterday (instead of disabling them, since having them disabled also prevents from running them locally), but it [looks like ](https://buildkite.com/automattic/wordpress-android/builds/5763#01823b3f-00b7-487b-b4e6-8e6643a783f4/322-1204)`test_target` option is not supported when providing it via Fastlane (but it did work when it was a part of CircleCI `config.yml`). I had to put this on hold to work on more urgent `publishSimplePost` fix.

**Comment by ParaskP7** [comment]
👋 @oguzkocer @jkmassel !

Could you please review this PR today/tomorrow so it gets merged to `trunk` before the end of the week so that we don't miss the translation process happening during the weekend. 🙇 

PS.1: Tomorrow I am AFK so I want be able to help with that, so feel free to merge that yourself directly, that is, after (and if 🤞 ) it gets approved. 🙏 
PS.2: Same for the [iOS related PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/19117) (which is already approved but in draft form). Since @mokagio is AFK for today/tomorrow (most probably) it would be great for someone to merge that to `trunk` before the end of the week. 🙏

**Comment by ParaskP7** [comment]
**FYI**: This PR now includes the #16964 betafix in it as well. As such, when this PR lands to `trunk` the `editorial release notes` along with this fix will land to `trunk`.

**UPDATE**: This betafix ended-up being a false positive and it actually not affecting `20.4` after all. As such, it got reverted (see a31ad31f035fe741929a3184839d2d6246526664). See Slack conversation for more details: `CC7L49W13/p1658998548428079`

**Review by oguzkocer — APPROVED** [review]

**Pull request merged**
