### PR TITLE
Merge Release/16.9 into develop

### PR DESCRIPTION
**Pull request by JavonDavis**
This branch was created from https://github.com/wordpress-mobile/WordPress-Android/tree/release/16.9 ... It seems unwanted commits were pulled into the history of that branch and brought in changes to the MeFragment that were breaking the signed build. The follow steps were carried out.

1. Create `release/16.9-backup` from `release/16.9` and push
2. Rollback to the 16.9-beta-3 commit 039fa59c9a7d69b99b3a9e80d2d28701d35e801e
3. Cherry pick the all the commits after that did not merge in the unwanted chanes
4.  Force push the branch 

This resolved the error that was happening when clicking the Me button in a signed build -> https://sentry.io/organizations/a8c/issues/1024074753/?project=1438088&query=is%3Aunresolved+user.email%3Ajavonldavis14%40gmail.com+version%3A16.9&statsPeriod=14d

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
Looks good, CI is green<sup>*</sup> and the only changes I can see here are localization and version number related, so nothing that would touch the Me fragment. 

:shipit: 

---

`*` _CI is green_: Actually, the Release Build task failed when trying to create the release on GitHub because of a 404. 🤔 I'd say GitHub had a hiccup at the time...

As a result, there is no 16.9 release, only the tag.

I would hack the lane that creates the GitHub release to run only that and try again.

**Comment by JavonDavis** [comment]
@mokagio Over the weekend I gave that release build multiple goes, consistently getting that API error from Github, I'll give it another go but if it's happening again, it'll require a deeper look. Also from Github's status page the API seems to be 🟢  as well

**Comment by JavonDavis** [comment]
@jkmassel @mokagio @AliSoftware  I'd like to go ahead and merge this even though the release build is failing... The release steps will have to be manually done for now

**Review by AliSoftware — APPROVED** [review]
Strange failures.

I'm all 👍  for you to merge despite the Release Job failing as long as you finish the steps (create the GH release etc) manually 🙂

**Comment by mokagio** [comment]
> I'd like to go ahead and merge this even though the release build is failing... The release steps will have to be manually done for now

Good call 👍

**Pull request merged**
