### PR TITLE
Fix #4485: replace auto suggestion by server domain suggestions

### LINKED ISSUE #4485: NUX: Offer suggestions for username/site address when the first choice is already taken
When a user creates a new account, we offer a fairly unhelpful error message if the username or site address is already taken:

Username isn't available:

> That username already exists

Site address isn't available:

> That site already exists

It would be great to offer suggestions to users when their first choice isn't available, so they don't have to repeatedly enter their choices and potentially continue to run into that error. Not being able to find an available username or site address is very discouraging and can lead users to abandon the signup.

### PR DESCRIPTION
**Pull request by maxme**
Fix #4485: replace auto suggestion by server domain suggestions

This PR removes the old way of suggesting the domain name (via username or site title) and use a remote call to get a list of suggestions. Unfortunately the remote call only return one `.wordpress.com` domain.

### CODE REVIEW

**Comment by maxme** [comment]
screenshot-2017-04-20_15 08 46 616
screenshot-2017-04-20_15 09 12 584

**Comment by maxme** [comment]
Note: this is not the perfect flow. I'd much prefer to have a separated screen for picking a domain name (kind of what we have on the web), but this is part of a bigger project: revamp the sign up experience.

**Comment by nbradbury** [comment]
@maxme I'm unable to build this branch - I get `Could not find com.github.wordpress-mobile.WordPress-FluxC-Android:fluxc:feature~domain-suggestions-SNAPSHOT`.

**Comment by maxme** [comment]
> @maxme I'm unable to build this branch - I get Could not find com.github.wordpress-mobile.WordPress-FluxC-Android:fluxc:feature~domain-suggestions-SNAPSHOT

Ah right, the branch was merged and deleted, I'll update the dependency.

**Comment by maxme** [comment]
Updated in 49f64e5

**Comment by nbradbury** [comment]
We should clear the adapter when the user changes the username. Otherwise the previous suggestion still briefly appears in the dropdown.

screenshot_1493040855

**Comment by maxme** [comment]
Ready for another round, there was a mistake in the new user screen (I used the wrong watcher), fixed in 48fdd14 - I've also encountered some weird behavior in the new site screen that is fixed by  	75fc0ce

**Comment by karama78** [comment]
Bon jour mon téléphone ne supporte pas ces applications c'est les
applications du web que vous devez m'aider

thilognedierry

2017-04-25 8:50 GMT+01:00 Maxime Biais <notifications@github.com>:

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
