### PR TITLE
9384 better error toast

### LINKED ISSUE #9384: Account Settings: better error messaging for change email flow when address is already in use
### Expected behavior
While logged into a WordPress.com account on the app, I try to update my email address to one that's used on a different WordPress.com account.
I expect to get an error which explains the email address is already being used on another account.

### Actual behavior
I get the error "Could not save your account settings".

nochange

### Steps to reproduce the behavior
You'll need two WordPress.com accounts to test.
1. Logged into account #1, go to Me > Account Settings and tap Email.
2. Change the email address to the email address associated with account #2.
3. See the "Could not save your account settings" error.

User report, Xiaomi Redmi Note 4X, WP Android 11.6 - #1855172-zen
I also tested on WPiOS 11.9 with similar results, reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/11214

### PR DESCRIPTION
**Pull request by jtj9817**
The old error handling method for the email address used only hard-coded strings which doesn't adequately handle other type of errors that are possible. The event.error.message method could possibly be a better solution but since I use a development build, there's no way to properly test it - addressed in the discussion of #9384 .

Fixes #9384 (hopefully)
The error message as it is right now:

### CODE REVIEW

**Comment by rachelmcr** [comment]
Thanks for opening this PR, @jtj9817! I see there are some failing tests, though — have you had a chance to take a look at those failures?

**Comment by rachelmcr** [comment]
@jtj9817 Actually, you can ignore my earlier message. I just had a check-in with @aforcier about this PR, and unfortunately I led you astray in my recommendations on #9384. I didn't consider that the error message coming from the server usually isn't localized, and we don't have a way to localize it from the app, so this solution won't work for all the languages we offer. I'm sorry about that!

@aforcier offered to look into this, since it may take a server-side fix. I'm going to go ahead and close this PR, but we really appreciate you digging in to this issue. Let us know if we can help you get started on another issue/fix!

**Comment by aforcier** [comment]
@jtj9817 after some server-side digging, it seems like the best approach after all for the moment is to just use the error message string from the server as you had originally implemented. It won't cover every language used in the app, but at the moment it's a good compromise versus the server-side work that would need to happen.

Sorry for the trouble! I'm re-opening this PR. If you're up for it, please resolve the lint issues, and I believe a merge of `develop` into the branch is needed to resolve an errant submodule update.

**Comment by loremattei** [comment]
I'm moving this to 12.5 since 12.4 has been cut. If this PR has to land 12.4, please feel free to target the release branch and to ping me to build a new beta.

**Comment by loremattei** [comment]
Hey! I'm moving this to 12.6 since 12.5 has been cut. If you want this to land 12.5, please feel free to target the release branch and ping me to build a new beta.

**Comment by nbradbury** [comment]
Just a friendly reminder to please make sure to manually merge `develop` into this branch before you merge this PR, as `develop` now contains the AndroidX migration. The automatic merge can succeed but still break the build. Better to find out now before it breaks `develop`. Thanks!

**Comment by aforcier** [comment]
Superseded by #10010.

**Pull request closed without merging**
