### PR TITLE
Updated location of stats and page QS focus point.

### LINKED ISSUE #12262: Point to Quick Actions rather than list items for 'Stats' and 'Pages' prompts
When the user is pointed to **Stats** and **Pages**, we currently point them to the list items.

However, we want to teach people to use the Quick Actions. The duplicate list items will also be removed in future.

Note: we will not do the same for Posts. For posts, we will route users through the Floating Action Button on the main My Site screen. See #12263 

quick-actions-prompt

### LINKED ISSUE #12263: Guide users to F.A.B. to create posts during Quick Start
After introducing the FAB, we want to emphasise it as a shortcut to creating posts.

Rather than guiding users to navigate to blog posts and then create a post, lets point them to the F.A.B. and sheet to create their post. Images below

Note: we are taking a slightly different approach with posts and pages so that users have the opportunity to learn creating both ways. See #12262 

blog posts via fab

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #12262 

This PR moves the Quick Start focus point for Stats and Pages from rows to IA buttons. I also renamed the "Tap Site Pages.." in action prompt to just "Tap Pages..."

@osullivanchris I took a little liberty with the placement of a focus point - please let me know if you want it in another place (I can't guarantee precise placement, but can get it pretty close).

[Image from Gyazo](https://gyazo.com/7ecd08c2d8afa646669c445858b5de1c)

To test:
- Create new site and start a QuickStart.
- Navigate to Customize Your Site task list and pick Create A New Page task.
- Confirm that the focus point is at the Pages IA button.

- Navigate to Grow Your Audience task list and pick Check Your Site Stats task.
- Confirm that the focus point is at the Stats IA button.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by khaykov** [comment]
@osullivanchris 
> Agree with this, although in the build I'm still seeing Site Pages

Are you using en_GB locale by any chance? If so yes, it will take some time for the change to be reflected :)

> There's also changes after the user taps into 'Pages' -> point them to the FAB and maybe tweak copy. But perhaps that's another PR

I think I might have missed this. Is it documented somewhere? I can probably put a focus point on FAB, but not sure what copy should I use.

**Comment by oguzkocer** [comment]
Hi there! `15.2` is being frozen, so this PR is being bumped to `15.3`. If these changes _have to_ be shipped with `15.2`, please target `release/15.2` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Comment by osullivanchris** [comment]
@khaykov  sorry I didn't catch your response before AFK week.

> Are you using en_GB locale by any chance? If so yes, it will take some time for the change to be reflected :)

em..probably!!

> I think I might have missed this. Is it documented somewhere? I can probably put a focus point on FAB, but not sure what copy should I use.

I mentioned it in the p2. All I said was "We should show a tap target on the FAB at least, and reconsider the label". So I had not figured out the label myself. If you can put a focus on the FAB I think that could help. For the copy, I don't really have a better suggestion. It would probably be clearer with just adding the focus point.

**Comment by khaykov** [comment]
@osullivanchris Got it! I'll add a focus point to FAB in a separate PR, as part of #12263

**Pull request merged**
