### PR TITLE
Update Aztec to version 1.3

### PR DESCRIPTION
**Pull request by maxme**
Update Aztec to version 1.3

### CODE REVIEW

**Comment by hypest** [comment]
This doesn't build for me. Raises `Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?` in a couple of sites in `strings.xml`. In my local setup, it happens that I have build tools `v7.0.2` installed even though the project uses `v26.0.2`. Perhaps `aapt` is picked up from 7.0.2 as per https://groups.google.com/d/msg/android-developers/AX2S3Zh6hoI/inqSYJO0nqwJ?

**Comment by maxme** [comment]
I updated to the latest version of build-tools `28.0.0-rc1` and it works fine. Can you clean, try again and post the full error?

**Comment by hypest** [comment]
[Here's the log](https://gist.github.com/hypest/bedd0dc123c3bebeda879633266c1fec) @maxme .

Judging from the path on the `aapt` stacktraces it seems to run v26.0.2 of it anyway.

**Comment by hypest** [comment]
OK, the issue I'm experiencing seems to be localized to my setup and it also happens on `develop` so, no issue with this PR per se.

The interesting thing of cource is that the `aapt` error/warning observed is still valid so, as @maxme suggested over at Slack, let's track it in a dedicated ticket. I will open one.

**Pull request merged**
