### PR TITLE
[GM/issues/605]Honors OS font size scale in GM editor

### PR DESCRIPTION
**Pull request by hotchemi**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/605

## Overview

This PR fixes gutenberg editor screen to honor OS font size when fontScale is changed(The issue is reported at [gutenberg-mobile/issues/605](https://github.com/wordpress-mobile/gutenberg-mobile/issues/605).

Since `GutenbergContainerFragment` is initialized with `setRetainInstance(true)` I just moved `WPAndroidGlueCode#onCreateView` in `Fragment#onCreateView` which can be called even if retainInstance is true.

### Links

- Original commit: https://github.com/wordpress-mobile/WordPress-Android/commit/98940ebc95a567909ad53e43beda0ba2623329d5
- PR: https://github.com/wordpress-mobile/WordPress-Android/pull/9030
- https://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean)

### Screenshots

| Before | After |
| ----------- | ----------- |
| ||

### To test

- Turn on `Use Block Editor` from app setting
- Open editor screen and type something
- Go to OS setting(Accessibility→Font Size) and change font size
- Back to editor screen and confirm content font size has been changed

### Update release notes

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hotchemi** [comment]
@hypest @daniloercoli I've updated the PR as discussed yesterday. Could you take a look when you have time?🙇

**Comment by daniloercoli** [comment]
Did you miss some commits @hotchemi ? 
Testing this brach I see the app crashing due to `WPAndroidGlueCode.attachToContainer` called before `GutenbergContainerFragment#onCreateView` and then `WPAndroidGlueCode.onCreateView`  is not called yet. 


Tested on Android 7.1.1. and 9.0. Would you mind to take a look?

**Comment by hotchemi** [comment]
Sorry for the late, I think we need more investigation for the change so let me close the PR for the time being 🙇 Thank you for your review! 🙏

**Comment by hypest** [comment]
👋 @hotchemi , I know this PR is now closed and we also had reservations about the solution that was lifting the `setRetainInstance()` state of the container fragment.

I noticed that ReactInstanceManager has [this recreateReactContextInBackground() method](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L350) that I have the feeling that it could be used in our case to trigger a RN "repaint" to use new configuration settings (font size in our case). Can you investigate going down that path?

**Pull request closed without merging**
