### PR TITLE
Issue/crash context notifications

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update from `requireContext()` to `getContext()` when passing context to the `DisplayUtils.isLandscape(Context)` method to fix a crash as described in https://github.com/wordpress-mobile/WordPress-Android/issues/9621.  The `DisplayUtils.isLandscape(Context)` method handles the case when the passed `context` is `null` by returning `false` so we don't need to pass `requireContext()`.  In the `NotificationsListFragmentPage` class, the `DisplayUtils.isLandscape(Context)` method is used to determine whether or not to show the image in the actionable empty view.  If `getContext()` is `null`, `DisplayUtils.isLandscape(Context)` will return `false` and the image will remain visible.  The worst case scenario would be showing the image in landscape orientation causing the actionable empty view to take up the entire screen height, which would require the user to scroll to see the whole screen.  That worst case is better than a crash.

I'm open to another fix if anyone has a better solution.  I'm unable to reproduce the crash so I'm not sure what is the root of the problem exactly.

### Review
Only one developer is required to review these changes, but anyone can perform the review.

### Release
The `RELEASE-NOTES.txt` document was updated in 7580d1cf376f8aff37dce7cac9e94ebd2057e913 with the following:
> Fixed crash when viewing Notifications tab

### CODE REVIEW

**Comment by daniloercoli** [comment]
What about adding an `isAdded()`check in `onDataLoaded` of `NotificationsListFragmentPage`?

**Comment by theck13** [comment]
The first solution I had was doing exactly that like this.

```java
@Override
public void onDataLoaded(int itemsCount) {
    if (itemsCount > 0) {
        hideEmptyView();
    } else if (isAdded()) {
        showEmptyViewForCurrentFilter();
    }
}
```

I didn't submit that for a couple reasons.  The only part of the `showEmptyViewForCurrentFilter()` method that needs context is the `mActionableEmptyView.image.setVisibility(DisplayUtils.isLandscape(requireContext()) ? View.GONE : View.VISIBLE);` statement.  As mentioned above, the worst case scenario is that that statement shows the actionable empty view image in landscape orientation.  Adding `isAdded()` could skip the entire `showEmptyViewForCurrentFilter()` method when it isn't necessary.  It should never happen, but skipping the `showEmptyViewForCurrentFilter()` method when `onDataLoaded(int)` occurs and `isAdded()` is `false` would lead to a weird state showing the actionable empty view with incorrect title, description, and button.  Ultimately, I wanted to make the change with the smallest potential impact since I can't reproduce the crash.

Do you think there are other consequences to the `getContext()` changes?  Do you think `isAdded()` would be better?

**Comment by mzorz** [comment]
👋 @theck13 @daniloercoli  IIUC, `onDataLoaded` is being called before the `Fragment` is properly attached to the `Activity` 
through the list Adapter. Maybe a way to handle this sync problem is to have a flag such as `mShouldShowEmptyViewForCurrentFilter`, set it to `true` in `onDataLoaded` if `isAdded()==false`  and then actually call `showEmptyViewForCurrentFilter()` later in `onAttach()` if `mShouldShowEmptyViewForCurrentFilter==true`

**Comment by mzorz** [comment]
Here's a git diff to make it simpler to follow what I was trying to say 😅 https://gist.github.com/mzorz/0767dd0f303ed14c71c8b74c26385900

**Comment by theck13** [comment]
> `onDataLoaded` is being called before the `Fragment` is properly attached to the `Activity` 
through the list Adapter

To be honest, I'm not sure if `onDataLoaded` is called before being attached or after being detached since it could be asynchronous coming from the [`myNotifyDatasetChanged();` statement in the `ReloadNotesFromDBTask.onPostExecute` task](https://github.com/wordpress-mobile/WordPress-Android/blob/9657129980bdf79340dcf19de6e4f3f951013f2f/WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java#L344).

**Comment by daniloercoli** [comment]
> Do you think there are other consequences to the getContext() changes? Do you think isAdded() would be better?

Thanks for the clarification @theck13 . I'm ok with your solution.

**Comment by mzorz** [comment]
> To be honest, I'm not sure if onDataLoaded is called before being attached or after being detached since it could be asynchronous coming from the myNotifyDatasetChanged(); statement in the ReloadNotesFromDBTask.onPostExecute task.

Gotcha, was thinking the same a bit after sending the comment. The lifecycle says that `onResume ()` (where the ReloadNotesFromDBTask is actually triggered from) should come way after `onAttach`, so yeah it looks like a detachment problem. If that is the case, then it looks like a valid hypothesis is that the user is now abandoning the Activity, and thus the context is detached, in which case Danilo's suggestion here https://github.com/wordpress-mobile/WordPress-Android/pull/9623#issuecomment-484576237 would be enough.

But, what doesn't seem to fit into this hypothesis is the number of occurrences of the crash so, I tend to be hesitant of "hiding" it because there could be something else (maybe more important) happening.

I agree the solution proposed is still better than a crash, but, what do you think about adding some logging using `CrashlyticsUtils.log(String message)` with some more info when this happens, so we can still keep track of the event occurrence trend and keep evaluating other causes?

**Comment by theck13** [comment]
> I agree the solution proposed is still better than a crash, but, what do you think about adding some logging using `CrashlyticsUtils.log(String message)` with some more info when this happens, so we can still keep track of the event occurrence trend and keep evaluating other causes?

This makes sense to me.  I added the log statement in f9a5dfce38.

**Pull request merged**
