### PR TITLE
Feature/7032 fancy tags

### LINKED ISSUE #7032: Feature: fancy tags
Implement the "fancy tags" feature as per @mattmiklic's design below.

* The circled number denotes the number of posts with that tag...On Android it would be a supplemental action. Tapping anywhere opens the edit view. This behavior is in line with the OS specs for disclosure buttons & supplemental actions.
* Rather than show a 0 on every tag that doesn’t have any posts associated with it, I’m proposing that we just not show a number for those tags. The repeating 0 seems like it doesn’t really add much value.
* Tapping the trash icon on the detail view opens an alert confirming the deletion; the message and button options should be the same as Calypso.

tags2

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #7032 - adds tags to site settings. To test:

* Go to site settings
* Tap "Tags"
* Check that your site's tags are all showing
* Add a new tag using the FAB
* Modify an existing tag
* Delete a tag

screenshot_1515027531

cc @oguzkocer

### CODE REVIEW

**Comment by roundhill** [comment]
Fancy tags indeed! Looks awesome 👍

**Comment by oguzkocer** [comment]
While on tag detail screen, if I tap the background below the details, it selects a different tag. I guess we should either show only one fragment at a time (by replacing) or make the background ignore the UI interaction in detail fragment.

**Comment by oguzkocer** [comment]
> I guess we should either show only one fragment at a time (by replacing) or make the background ignore the UI interaction in detail fragment.

Please ignore this part, because I just assumed there were multiple fragments before I started reviewing the PR.

**Comment by nbradbury** [comment]
> While on tag detail screen, if I tap the background below the details, it selects a different tag.

Fixed in 5b1fe98

**Comment by nbradbury** [comment]
> Should we re-open the keyboard if the user rotates when they were typing something?
> While on landscape do we want to allow full-screen edit in detail fragment? 

I'm okay with leaving these as-is. There are other places in the app where the keyboard goes away on rotation, and where the keyboard is full-screen in landscape.

> After a few rotations and search I sometimes end up with a search button in detail fragment: 

I can't repro that. What API level is your emulator, and is it Genymotion or stock?

> how do you feel about making the detail fragment a separate activity?

I'm fine keeping it as a fragment. It doesn't use `onAttach` or `onDetach` so it's not affected by #6937.

> Finally, do you think it'd be better if we used the "SiteSettings" prefix for these tag related resources & classes

Good call. I made that change in 1014d64.

**Comment by oguzkocer** [comment]
> I made a change in e19bfbc that may fix that. Could you give it a try?

Yeap, that fixed the issue.

**Pull request merged**
